import ROOT
ROOT.gSystem.Load("libLArCV")
ROOT.gSystem.Load("libLArCVData")
from ROOT import larcv
c=larcv.IOManager("larcv::Image2D")
o=c(c.kREAD)
o.reset()
o.set_verbosity(0)
o.add_in_file("aho.root")
o.initialize()
#o.get_data("boke")
o.read_entry(0)
print o.get_data("aho").size()
o.read_entry(1)
print o.get_data("aho").size()
o.read_entry(2)
print o.get_data("aho").size()
#o.save_entry()
#o.save_entry()
#o.save_entry()
#o.save_entry()
o.finalize()
