LArCV: ANNx.h File Reference
ANNx.h File Reference
#include <iomanip>
#include <ANN/ANN.h>
Classes
class ANNorthRect
class ANNorthHalfSpace
Typedefs
typedef ANNorthHalfSpace * ANNorthHSArray
Enumerations
enum { ANN_LO =0, ANN_HI =1 }
enum { ANN_IN =0, ANN_OUT =1 }
enum ANNerr { ANNwarn = 0, ANNabort = 1 }
Functions
void annError (const char *msg, ANNerr level)
void annPrintPt (ANNpoint pt, int dim, std::ostream &out)
void annAssignRect (int dim, ANNorthRect &dest, const ANNorthRect &source)
Variables
int ANNmaxPtsVisited
int ANNptsVisited
Typedef Documentation
ANNorthHSArray
typedef ANNorthHalfSpace* ANNorthHSArray
Definition at line 167 of file ANNx.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ANN_LO
ANN_HI
Definition at line 45 of file ANNx.h.
 {ANN_LO=0, ANN_HI=1};   // splitting indices
anonymous enum
anonymous enum
Enumerator
ANN_IN
ANN_OUT
Definition at line 46 of file ANNx.h.
 {ANN_IN=0, ANN_OUT=1};  // shrinking indices
ANNerr
enum ANNerr
Enumerator
ANNwarn
ANNabort
Definition at line 48 of file ANNx.h.
 {ANNwarn = 0, ANNabort = 1};
Function Documentation
annAssignRect()
void annAssignRect (int dim, ANNorthRect & dest, const ANNorthRect & source)
Definition at line 148 of file ANN.cpp.
References dim, ANNorthRect::hi, and ANNorthRect::lo.
Referenced by annBnds2Box(), tryCentroidShrink(), and ANNorthRect::~ANNorthRect().
 {
     for (int i = 0; i < dim; i++) {
         dest.lo[i] = source.lo[i];
         dest.hi[i] = source.hi[i];
     }
 }
annError()
void annError (const char * msg, ANNerr level)
Definition at line 169 of file ANN.cpp.
References ANNabort.
Referenced by ANNbd_tree::ANNbd_tree(), ANNkd_tree::ANNkd_tree(), ANNbruteForce::annkSearch(), ANNkd_tree::annkSearch(), annReadDump(), annReadTree(), ANNpr_queue::insert(), and selectDecomp().
 {
     if (level == ANNabort) {
         cerr << "ANN: ERROR------->" << msg << "<-------------ERROR\n";
         exit(1);
     }
     else {
         cerr << "ANN: WARNING----->" << msg << "<-------------WARNING\n";
     }
 }
annPrintPt()
void annPrintPt (ANNpoint pt, int dim, std::ostream & out)
Definition at line 70 of file ANN.cpp.
References dim.
Referenced by ANNkd_tree::Dump(), and ANNkd_tree::Print().
 {
     for (int j = 0; j < dim; j++) {
         out << pt[j];
         if (j < dim-1) out << " ";
     }
 }
Variable Documentation
ANNmaxPtsVisited
int ANNmaxPtsVisited
Definition at line 190 of file ANN.cpp.
Referenced by ANNbd_shrink::ann_FR_search(), ANNkd_split::ann_FR_search(), ANNbd_shrink::ann_search(), ANNkd_split::ann_search(), ANNkd_tree::annkPriSearch(), and annMaxPtsVisit().
ANNptsVisited
int ANNptsVisited
Definition at line 191 of file ANN.cpp.
Referenced by ANNbd_shrink::ann_FR_search(), ANNkd_leaf::ann_pri_search(), ANNbd_shrink::ann_search(), ANNkd_leaf::ann_search(), ANNkd_split::ann_search(), ANNkd_tree::annkPriSearch(), and ANNkd_tree::annkSearch().