LArCV: SegDatumFillerBase.cxx File Reference
SegDatumFillerBase.cxx File Reference
#include "SegDatumFillerBase.h"
#include "DataFormat/EventImage2D.h"
#include <sstream>
Namespaces
larcv
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Macros
#define __SEGDATUMFILLERBASE_CXX__
Functions
this fill_entry_data (event_image_data, event_label_data)
if (entry_image_data.size() !=_entry_data_size)
for (size_t i=0;i< _entry_data_size;++i) _image_data[current_image_index_start+i]
Variables
auto const & entry_image_data = entry_image()
auto const & entry_label_data = entry_label()
const size_t current_image_index_start = _current_entry * _entry_image_size
return true
Macro Definition Documentation
__SEGDATUMFILLERBASE_CXX__
#define __SEGDATUMFILLERBASE_CXX__
Definition at line 2 of file SegDatumFillerBase.cxx.
Function Documentation
fill_entry_data()
this fill_entry_data (event_image_data , event_label_data)
for()
for ()
Initial value:
= entry_label_data[i]
    ++_current_entry
if()
if (entry_image_data.size() ! = _entry_data_size)
Definition at line 108 of file SegDatumFillerBase.cxx.
References entry_image_data, and LARCV_CRITICAL.
{
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << event_image->run() << "," << event_image->subrun() << "," << event_image->event() << ")"
       << " fill_entry_data() filled IMAGE data with size " << entry_image_data.size()
       << " where it is supposed to be " << _entry_image_size << std::endl;
       throw larbys();
     }
Variable Documentation
current_image_index_start
const size_t current_image_index_start = _current_entry * _entry_image_size
Definition at line 116 of file SegDatumFillerBase.cxx.
Referenced by larcv::DatumFillerBase::process().
entry_image_data
auto const& entry_image_data = entry_image()
Definition at line 105 of file SegDatumFillerBase.cxx.
Referenced by if(), and larcv::DatumFillerBase::process().
entry_label_data
auto const& entry_label_data = entry_label()
Definition at line 106 of file SegDatumFillerBase.cxx.
Referenced by larcv::DatumFillerBase::process().
true
return true
Definition at line 125 of file SegDatumFillerBase.cxx.
Referenced by larcv::ADCScale::configure(), and larcv::ROIMask::configure().