LArCV: larcv::LArbysImageFilter Class Reference
larcv::LArbysImageFilter Class Reference
#include <LArbysImageFilter.h>
Public Member Functions
LArbysImageFilter (const std::string name="LArbysImageFilter")
~LArbysImageFilter ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void SetLArbysImageAna (LArbysImageAna *larbysana_ptr)
void SetLArbysImageExtract (LArbysImageExtract *larbysext_ptr)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void ClearVertex ()
void ClearEvent ()
void WriteOut (size_t vertexid)
Private Attributes
LArbysImageAna * _larbysana_ptr
LArbysImageExtract * _larbysext_ptr
larocv::VertexAnalysis _vtx_ana
bool _require_two_multiplicity
bool _require_match
bool _require_fiducial
std::string _filtereventtreename
std::string _filtervertextreename
TTree * _event_tree
uint _run
uint _subrun
uint _event
uint _entry
std::vector< larocv::data::Vertex3D > _vertex3d_v
std::vector< std::vector< std::vector< larocv::data::ParticleCluster > > > _particle_cluster_vvv
std::vector< std::vector< std::vector< larocv::data::TrackClusterCompound > > > _track_compound_vvv
TTree * _vtx3d_tree
uint _vtx3d_id
uint _vtx3d_n_planes
uint _vtx3d_type
double _vtx3d_x
double _vtx3d_y
double _vtx3d_z
std::vector< double > _vtx2d_x_v
std::vector< double > _vtx2d_y_v
std::vector< uint > _ntrack_par_v
std::vector< uint > _nshower_par_v
std::vector< double > _circle_x_v
std::vector< double > _circle_y_v
std::vector< uint > _par_multi
TTree * _mc_tree
Detailed Description
Definition at line 11 of file LArbysImageFilter.h.
Constructor & Destructor Documentation
LArbysImageFilter()
larcv::LArbysImageFilter::LArbysImageFilter (const std::string name = "LArbysImageFilter")
Definition at line 8 of file LArbysImageFilter.cxx.
Referenced by larcv::LArbysImageFilterProcessFactory::create().
     : ProcessBase(name),
       _larbysana_ptr(nullptr),
       _larbysext_ptr(nullptr),
       _vtx_ana(),
       _event_tree(nullptr),
       _vtx3d_tree(nullptr)
   {}
~LArbysImageFilter()
larcv::LArbysImageFilter::~LArbysImageFilter () inline
Definition at line 15 of file LArbysImageFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEvent()
void larcv::LArbysImageFilter::ClearEvent () private
Definition at line 60 of file LArbysImageFilter.cxx.
References _larbysana_ptr, _particle_cluster_vvv, _track_compound_vvv, _vertex3d_v, and larcv::LArbysImageAna::Verticies().
Referenced by process(), and SetLArbysImageExtract().
{
     _vertex3d_v.clear();
     _vertex3d_v.reserve(_larbysana_ptr->Verticies().size());
     _particle_cluster_vvv.clear();
     _particle_cluster_vvv.reserve(_larbysana_ptr->Verticies().size());
     _track_compound_vvv.clear();
     _track_compound_vvv.reserve(_larbysana_ptr->Verticies().size());
   }
ClearVertex()
void larcv::LArbysImageFilter::ClearVertex () private
Definition at line 49 of file LArbysImageFilter.cxx.
References _par_multi, _vtx2d_x_v, _vtx2d_y_v, _vtx3d_id, _vtx3d_n_planes, _vtx3d_type, _vtx3d_x, _vtx3d_y, _vtx3d_z, larcv::kINVALID_DOUBLE, and larcv::kINVALID_INT.
Referenced by SetLArbysImageExtract(), and WriteOut().
{
     _vtx3d_id=kINVALID_INT;
     _vtx3d_n_planes=kINVALID_INT;
     _vtx3d_type=kINVALID_INT;
     _vtx3d_x=kINVALID_DOUBLE;
     _vtx3d_y=kINVALID_DOUBLE;
     _vtx3d_z=kINVALID_DOUBLE;
     _vtx2d_x_v.clear();
     _vtx2d_y_v.clear();
     _par_multi.clear();
   }
configure()
void larcv::LArbysImageFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file LArbysImageFilter.cxx.
References _filtereventtreename, _filtervertextreename, _require_fiducial, _require_match, _require_two_multiplicity, and larcv::PSet::get().
Referenced by ~LArbysImageFilter().
   {
     _require_two_multiplicity = cfg.get<bool>("RequireMultiplicityTwo",true);
     _require_match            = cfg.get<bool>("RequireMatch",true);
     _require_fiducial         = cfg.get<bool>("RequireFiducial",true);
     _filtervertextreename     = cfg.get<std::string>("FilterVertexTreeName","FilterVertexTree");
     _filtereventtreename      = cfg.get<std::string>("FilterEventTreeName","FilterEventTree");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImageFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 120 of file LArbysImageFilter.cxx.
References _event_tree, _larbysana_ptr, _mc_tree, _vtx3d_tree, larcv::ProcessBase::ana_file(), and larcv::LArbysImageAna::GetMCTreeName().
Referenced by ~LArbysImageFilter().
   {
     _event_tree->Write();
     _vtx3d_tree->Write();
     std::string oldfilename;
     std::string oldtreename;
     oldfilename = _larbysana_ptr->GetRootName();
     oldtreename = _larbysana_ptr->GetMCTreeName();
     TFile *oldfile = new TFile(oldfilename.c_str(),"read");
     TTree *oldtree = (TTree*)oldfile->Get(oldtreename.c_str());
     //_mc_tree->Print();
     _mc_tree = oldtree->CloneTree();
     //_mc_tree->CopyEntries(oldtree);
     ana_file().cd();
     _mc_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImageFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 24 of file LArbysImageFilter.cxx.
References _entry, _event, _event_tree, _filtereventtreename, _filtervertextreename, _par_multi, _particle_cluster_vvv, _run, _subrun, _track_compound_vvv, _vertex3d_v, _vtx2d_x_v, _vtx2d_y_v, _vtx3d_id, _vtx3d_tree, _vtx3d_type, _vtx3d_x, _vtx3d_y, and _vtx3d_z.
Referenced by ~LArbysImageFilter().
   {
     _vtx3d_tree = new TTree(_filtervertextreename.c_str(),"");
     _vtx3d_tree->Branch("run",&_run,"run/i");
     _vtx3d_tree->Branch("subrun",&_subrun,"subrun/i");
     _vtx3d_tree->Branch("event",&_event,"event/i");
     _vtx3d_tree->Branch("entry",&_entry,"entry/i");
     _vtx3d_tree->Branch("id",&_vtx3d_id,"id/i");
     _vtx3d_tree->Branch("type", &_vtx3d_type,"type/i");
     _vtx3d_tree->Branch("x",&_vtx3d_x,"x/D");
     _vtx3d_tree->Branch("y",&_vtx3d_y,"y/D");
     _vtx3d_tree->Branch("z",&_vtx3d_z,"z/D");
     _vtx3d_tree->Branch("vtx2d_x_v",&_vtx2d_x_v );
     _vtx3d_tree->Branch("vtx2d_y_v",&_vtx2d_y_v );
     _vtx3d_tree->Branch("multi_v",&_par_multi);
     _event_tree = new TTree(_filtereventtreename.c_str(),"");
     _event_tree->Branch("run",&_run,"run/i");
     _event_tree->Branch("subrun",&_subrun,"subrun/i");
     _event_tree->Branch("event",&_event,"event/i");
     _event_tree->Branch("entry",&_entry,"entry/i");
     _event_tree->Branch("Vertex3D_v",&_vertex3d_v);
     _event_tree->Branch("ParticleCluster_vvv",&_particle_cluster_vvv);
     _event_tree->Branch("TrackClusterCompound_vvv",&_track_compound_vvv);
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::LArbysImageFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 86 of file LArbysImageFilter.cxx.
References _entry, _event, _event_tree, _larbysana_ptr, _larbysext_ptr, _require_fiducial, _require_match, _require_two_multiplicity, _run, _subrun, _vertex3d_v, _vtx3d_tree, _vtx_ana, larcv::LArbysImageExtract::ADCImages(), larcv::LArbysImageExtract::ADCMeta(), ClearEvent(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::event_id(), LARCV_DEBUG, larcv::LArbysImageAna::Particles(), larcv::LArbysImageAna::Vertex(), larcv::LArbysImageAna::Verticies(), and WriteOut().
Referenced by ~LArbysImageFilter().
   {
     ClearEvent();
     const auto& event_id = mgr.event_id();
     _run    = (uint) event_id.run();
     _subrun = (uint) event_id.subrun();
     _event  = (uint) event_id.event();
     _entry =  (uint) mgr.current_entry();
     for(size_t vertexid=0; vertexid<_larbysana_ptr->Verticies().size(); ++vertexid) {
       std::vector<std::vector<larocv::data::ParticleCluster> > pcluster_vv;
       for(size_t planeid=0;planeid<3;++planeid)  {
     pcluster_vv.push_back(_larbysana_ptr->Particles(vertexid,planeid));
     _vtx_ana.ResetPlaneInfo(_larbysext_ptr->ADCMeta(planeid));
       }
       if (_require_two_multiplicity) {
     auto multiplicity=_vtx_ana.RequireParticleCount(pcluster_vv,2,2);
     if (!multiplicity) continue;
       }
       if (_require_fiducial) {
     auto fiduciality=_vtx_ana.CheckFiducial(_larbysana_ptr->Vertex(vertexid));
     if (!fiduciality) continue;
       }
       if(_require_match) {
     auto match_vv = _vtx_ana.MatchClusters(pcluster_vv,_larbysext_ptr->ADCImages(),0.5,2,2);
     if (match_vv.empty()) continue;
       }
       WriteOut(vertexid);
       _vtx3d_tree->Fill();
     }
     LARCV_DEBUG()<<"Filtered "<<_larbysana_ptr->Verticies().size()<<" to "<<_vertex3d_v.size()<<std::endl;
     if (_vertex3d_v.empty()) return false;
     _event_tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetLArbysImageAna()
void larcv::LArbysImageFilter::SetLArbysImageAna (LArbysImageAna * larbysana_ptr) inline
Definition at line 20 of file LArbysImageFilter.h.
References _larbysana_ptr.
     { _larbysana_ptr = larbysana_ptr; }
SetLArbysImageExtract()
void larcv::LArbysImageFilter::SetLArbysImageExtract (LArbysImageExtract * larbysext_ptr) inline
Definition at line 22 of file LArbysImageFilter.h.
References _larbysext_ptr, ClearEvent(), ClearVertex(), and WriteOut().
     { _larbysext_ptr = larbysext_ptr; }
WriteOut()
void larcv::LArbysImageFilter::WriteOut (size_t vertexid) private
Definition at line 68 of file LArbysImageFilter.cxx.
References _larbysana_ptr, _par_multi, _particle_cluster_vvv, _track_compound_vvv, _vertex3d_v, _vtx2d_x_v, _vtx2d_y_v, _vtx3d_id, _vtx3d_n_planes, _vtx3d_type, _vtx3d_x, _vtx3d_y, _vtx3d_z, ClearVertex(), larcv::LArbysImageAna::Particles(), larcv::LArbysImageAna::PlaneParticles(), larcv::LArbysImageAna::PlaneTracks(), and larcv::LArbysImageAna::Vertex().
Referenced by process(), and SetLArbysImageExtract().
{
     const auto& vtx3d = _larbysana_ptr->Vertex(vertexid);
     _vertex3d_v.emplace_back(vtx3d);
     _particle_cluster_vvv.emplace_back(_larbysana_ptr->PlaneParticles(vertexid));
     _track_compound_vvv.emplace_back(_larbysana_ptr->PlaneTracks(vertexid));
     ClearVertex();
     _vtx3d_id=vertexid;
     _vtx3d_n_planes=vtx3d.num_planes;
     _vtx3d_type=(uint)vtx3d.type;
     _vtx3d_x=vtx3d.x;
     _vtx3d_y=vtx3d.y;
     _vtx3d_z=vtx3d.z;
     for(size_t plane=0; plane<3;  ++plane) {
       _vtx2d_x_v.push_back(vtx3d.cvtx2d_v[plane].center.x);
       _vtx2d_y_v.push_back(vtx3d.cvtx2d_v[plane].center.y);
       _par_multi.push_back(_larbysana_ptr->Particles(vertexid,plane).size());
     }
   }
Member Data Documentation
_circle_x_v
std::vector<double> larcv::LArbysImageFilter::_circle_x_v private
Definition at line 57 of file LArbysImageFilter.h.
_circle_y_v
std::vector<double> larcv::LArbysImageFilter::_circle_y_v private
Definition at line 58 of file LArbysImageFilter.h.
_entry
uint larcv::LArbysImageFilter::_entry private
Definition at line 41 of file LArbysImageFilter.h.
Referenced by initialize(), and process().
_event
uint larcv::LArbysImageFilter::_event private
Definition at line 40 of file LArbysImageFilter.h.
Referenced by initialize(), and process().
_event_tree
TTree* larcv::LArbysImageFilter::_event_tree private
Definition at line 37 of file LArbysImageFilter.h.
Referenced by finalize(), initialize(), and process().
_filtereventtreename
std::string larcv::LArbysImageFilter::_filtereventtreename private
Definition at line 34 of file LArbysImageFilter.h.
Referenced by configure(), and initialize().
_filtervertextreename
std::string larcv::LArbysImageFilter::_filtervertextreename private
Definition at line 35 of file LArbysImageFilter.h.
Referenced by configure(), and initialize().
_larbysana_ptr
LArbysImageAna* larcv::LArbysImageFilter::_larbysana_ptr private
Definition at line 28 of file LArbysImageFilter.h.
Referenced by ClearEvent(), finalize(), process(), SetLArbysImageAna(), and WriteOut().
_larbysext_ptr
LArbysImageExtract* larcv::LArbysImageFilter::_larbysext_ptr private
Definition at line 29 of file LArbysImageFilter.h.
Referenced by process(), and SetLArbysImageExtract().
_mc_tree
TTree* larcv::LArbysImageFilter::_mc_tree private
Definition at line 60 of file LArbysImageFilter.h.
Referenced by finalize().
_nshower_par_v
std::vector<uint> larcv::LArbysImageFilter::_nshower_par_v private
Definition at line 56 of file LArbysImageFilter.h.
_ntrack_par_v
std::vector<uint> larcv::LArbysImageFilter::_ntrack_par_v private
Definition at line 55 of file LArbysImageFilter.h.
_par_multi
std::vector<uint> larcv::LArbysImageFilter::_par_multi private
Definition at line 59 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_particle_cluster_vvv
std::vector<std::vector<std::vector<larocv::data::ParticleCluster> > > larcv::LArbysImageFilter::_particle_cluster_vvv private
Definition at line 43 of file LArbysImageFilter.h.
Referenced by ClearEvent(), initialize(), and WriteOut().
_require_fiducial
bool larcv::LArbysImageFilter::_require_fiducial private
Definition at line 33 of file LArbysImageFilter.h.
Referenced by configure(), and process().
_require_match
bool larcv::LArbysImageFilter::_require_match private
Definition at line 32 of file LArbysImageFilter.h.
Referenced by configure(), and process().
_require_two_multiplicity
bool larcv::LArbysImageFilter::_require_two_multiplicity private
Definition at line 31 of file LArbysImageFilter.h.
Referenced by configure(), and process().
_run
uint larcv::LArbysImageFilter::_run private
Definition at line 38 of file LArbysImageFilter.h.
Referenced by initialize(), and process().
_subrun
uint larcv::LArbysImageFilter::_subrun private
Definition at line 39 of file LArbysImageFilter.h.
Referenced by initialize(), and process().
_track_compound_vvv
std::vector<std::vector<std::vector<larocv::data::TrackClusterCompound> > > larcv::LArbysImageFilter::_track_compound_vvv private
Definition at line 44 of file LArbysImageFilter.h.
Referenced by ClearEvent(), initialize(), and WriteOut().
_vertex3d_v
std::vector<larocv::data::Vertex3D> larcv::LArbysImageFilter::_vertex3d_v private
Definition at line 42 of file LArbysImageFilter.h.
Referenced by ClearEvent(), initialize(), process(), and WriteOut().
_vtx2d_x_v
std::vector<double> larcv::LArbysImageFilter::_vtx2d_x_v private
Definition at line 53 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx2d_y_v
std::vector<double> larcv::LArbysImageFilter::_vtx2d_y_v private
Definition at line 54 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx3d_id
uint larcv::LArbysImageFilter::_vtx3d_id private
Definition at line 47 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx3d_n_planes
uint larcv::LArbysImageFilter::_vtx3d_n_planes private
Definition at line 48 of file LArbysImageFilter.h.
Referenced by ClearVertex(), and WriteOut().
_vtx3d_tree
TTree* larcv::LArbysImageFilter::_vtx3d_tree private
Definition at line 46 of file LArbysImageFilter.h.
Referenced by finalize(), initialize(), and process().
_vtx3d_type
uint larcv::LArbysImageFilter::_vtx3d_type private
Definition at line 49 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx3d_x
double larcv::LArbysImageFilter::_vtx3d_x private
Definition at line 50 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx3d_y
double larcv::LArbysImageFilter::_vtx3d_y private
Definition at line 51 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx3d_z
double larcv::LArbysImageFilter::_vtx3d_z private
Definition at line 52 of file LArbysImageFilter.h.
Referenced by ClearVertex(), initialize(), and WriteOut().
_vtx_ana
larocv::VertexAnalysis larcv::LArbysImageFilter::_vtx_ana private
Definition at line 30 of file LArbysImageFilter.h.
Referenced by process().
The documentation for this class was generated from the following files:
LArbysImageFilter.h
LArbysImageFilter.cxx