LArCV: larcv::pmtweights::PMTWeightImageBuilder Class Reference
larcv::pmtweights::PMTWeightImageBuilder Class Reference
#include <PMTWeightImageBuilder.h>
Public Member Functions
PMTWeightImageBuilder (const std::string name="PMTWeightImageBuilder")
Default constructor.
~PMTWeightImageBuilder ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::string fGeoFile
std::string fPMTImageProducer
std::string fTPCImageProducer
std::string fOutputProducerName
int fNWirePixels
int fStartTick
int fEndTick
PMTWireWeights * m_WireWeights
bool fCheckSat
int fPMTImageIndex
float fHGpedestal
bool fSaveWeightMask
std::string fWeightMaskProducerName
bool fDebugSaveDistWeightMatrix
bool fResizedMat
std::map< int, larcv::Image2D > resizedWeightMat
Detailed Description
Definition at line 32 of file PMTWeightImageBuilder.h.
Constructor & Destructor Documentation
PMTWeightImageBuilder()
larcv::pmtweights::PMTWeightImageBuilder::PMTWeightImageBuilder (const std::string name = "PMTWeightImageBuilder")
Default constructor.
Definition at line 19 of file PMTWeightImageBuilder.cxx.
Referenced by larcv::pmtweights::PMTWeightImageBuilderProcessFactory::create().
       : ProcessBase(name)
     {}
~PMTWeightImageBuilder()
larcv::pmtweights::PMTWeightImageBuilder::~PMTWeightImageBuilder ()
Default destructor.
Definition at line 14 of file PMTWeightImageBuilder.cxx.
References m_WireWeights.
{
       delete m_WireWeights;
       m_WireWeights = NULL;
     }
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::pmtweights::PMTWeightImageBuilder::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 23 of file PMTWeightImageBuilder.cxx.
References fCheckSat, fDebugSaveDistWeightMatrix, fEndTick, fGeoFile, fHGpedestal, fNWirePixels, fOutputProducerName, fPMTImageIndex, fPMTImageProducer, fSaveWeightMask, fStartTick, fTPCImageProducer, fWeightMaskProducerName, and larcv::PSet::get().
     {
       fGeoFile     = cfg.get<std::string> ( "GeoFile" );
       fNWirePixels = cfg.get<int>( "NWirePixels" );
       fPMTImageProducer = cfg.get<std::string>( "PMTImageProducer" );
       fTPCImageProducer = cfg.get<std::string>( "TPCImageProducer" );
       fStartTick = cfg.get<int>( "StartTick" );
       fEndTick = cfg.get<int>( "EndTick" );
       fCheckSat = cfg.get<bool>("CheckSaturation");
       fPMTImageIndex = cfg.get<int>("PMTImageIndex");
       fHGpedestal = cfg.get<float>("HGpedestal",2047.0);
       fOutputProducerName = cfg.get<std::string>( "OutputProducerName" );
       fSaveWeightMask = cfg.get<bool>("SaveWeightMask",false);
       fWeightMaskProducerName = cfg.get<std::string>("WeightMaskProducer","weightmask");
       fDebugSaveDistWeightMatrix = cfg.get<bool>("DebugSaveDistWeightMatrix", false );
     }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::pmtweights::PMTWeightImageBuilder::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 195 of file PMTWeightImageBuilder.cxx.
     {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::pmtweights::PMTWeightImageBuilder::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 40 of file PMTWeightImageBuilder.cxx.
References fGeoFile, fNWirePixels, fResizedMat, and m_WireWeights.
     {
       m_WireWeights = new PMTWireWeights( fGeoFile, fNWirePixels );
       fResizedMat = false;
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::pmtweights::PMTWeightImageBuilder::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 47 of file PMTWeightImageBuilder.cxx.
References larcv::ImageMeta::cols(), larcv::Image2D::compress(), larcv::EventImage2D::Emplace(), fCheckSat, fDebugSaveDistWeightMatrix, fEndTick, fHGpedestal, fOutputProducerName, fPMTImageIndex, fPMTImageProducer, fResizedMat, fSaveWeightMask, fStartTick, fTPCImageProducer, fWeightMaskProducerName, larcv::IOManager< T >::get_data(), larcv::Image2D::kAverage, larcv::kProductImage2D, LARCV_DEBUG, m_WireWeights, larcv::Image2D::meta(), larcv::Image2D::pixel(), larcv::pmtweights::PMTWireWeights::planeWeights, larcv::Image2D::resize(), resizedWeightMat, larcv::ImageMeta::rows(), and larcv::Image2D::set_pixel().
     {
       auto pmt_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,fPMTImageProducer));
       if(!pmt_event_image || pmt_event_image->Image2DArray().empty()) return false;
       auto tpc_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,fTPCImageProducer));
       if(!tpc_event_image || tpc_event_image->Image2DArray().empty()) return false;
       // -------------------
       // Pick out PMT Image
       // -------------------
       larcv::Image2D const& pmtimg_highgain = pmt_event_image->at( fPMTImageIndex ); // placeholder code
       //larcv::Image2D const& pmtimg_lowgain  = event_image->at( 4 ); // placeholder code
 //       std::cout << "pmt image: " << pmtimg_highgain.meta().rows() << " x " << pmtimg_highgain.meta().cols() << std::endl;
 //       std::cout << "tpc image: " << tpc_event_image->at(2).meta().rows() << " x " << tpc_event_image->at(2).meta().cols() << std::endl;
 //       std::cout << "summing between: " << fStartTick << " and " << fEndTick << std::endl;
       // sum pmt charge in the trigger window
       larcv::Image2D pmtq( 32, 1 );
       float totalq = 0.0;
       for (int ipmt=0; ipmt<32; ipmt++) {
     float high_q = 0.0;
     float low_q  = 0.0;
     bool usehigh = true;
     for (int t=fStartTick; t<=fEndTick; t++) {
       // sum over the trigger window
       float hq = pmtimg_highgain.pixel( t, ipmt )-fHGpedestal;
       high_q += hq;
       if ( fCheckSat && hq>1040 )
         usehigh = false;
     }
     if ( high_q <0.0 )
       high_q  = 0.0;
     if ( low_q < 0.0 )
       low_q = 0.0;
     if ( high_q > 0.0 ) {
       if ( usehigh ) {
         pmtq.set_pixel( ipmt, 0, high_q/100.0 );
         totalq += high_q/100.0;
       }
       else {
         pmtq.set_pixel( ipmt, 0, 10.0*low_q/100.0 );
         totalq += 10.0*low_q/100.0;
       }
     }
       }//end of pmt loop
       // normalize charge
       if ( totalq > 0 ) {
     for (size_t ipmt=0; ipmt<32; ipmt++) {
       pmtq.set_pixel( ipmt, 0, pmtq.pixel( ipmt, 0 )/totalq );
       //std::cout << "PMT " << ipmt << ": " << pmtq.pixel( ipmt, 0 )/totalq << std::endl;
     }
       }
       LARCV_DEBUG() << "Total Q: " << totalq << std::endl;
       // need to resize weight matrices to have right number of wire pixels: wait until we get the first image so we can resize
       if ( !fResizedMat ) {
     resizedWeightMat.clear();
     for (int p=0; p<3; p++) {
       larcv::Image2D const& tpcimg  = tpc_event_image->at( p );
       larcv::Image2D weights( m_WireWeights->planeWeights[p] );
       int factor = weights.meta().rows()/tpcimg.meta().cols(); // cols is the wire dimension
       if ( weights.meta().rows()%tpcimg.meta().cols()!=0 )
         factor++;
       weights.resize( tpcimg.meta().cols()*factor, weights.meta().cols(), 0.0 );
       weights.compress( tpcimg.meta().cols(), weights.meta().cols(), larcv::Image2D::kAverage );
 //    std::cout << "(" << weights.meta().rows() << "," << weights.meta().cols() << ") "
 //          << "(" << tpcimg.meta().rows()  << "," << tpcimg.meta().cols() << ")" << std::endl;
       resizedWeightMat[p] = weights;
       // check it:
       for (int r=0; r<weights.meta().rows(); r++) {
         for (int c=0; c<weights.meta().cols(); c++) {
           if ( std::isnan(weights.pixel( r, c )) || weights.pixel( r, c )<0 || weights.pixel( r, c )>1.0 ) {
         std::cout << "weird weight value in (" << p << ", " << r << ", " << c << ")=" << weights.pixel( r, c ) << std::endl;
           }
         }
       }
     }
     fResizedMat = true;
       }
       // make weight matrices
       std::vector<larcv::Image2D> pmtw_image_array;
       for (int p=0; p<3; p++) {
     larcv::Image2D const& planeweight = resizedWeightMat[p];
     larcv::Image2D weights = planeweight*pmtq;
     pmtw_image_array.emplace_back( weights );
 //  std::cout << "planeweights: (" << planeweight.meta().rows() << "," << planeweight.meta().cols() << ") "
 //        << "pmt-weights: (" << weights.meta().rows()  << "," << weights.meta().cols() << ")" << std::endl;
       }
       // now apply weights
       std::vector<larcv::Image2D> weighted_images;
       std::vector<larcv::Image2D> mask_images;
       for (int p=0; p<3; p++) {
     larcv::Image2D const& tpcimg  = tpc_event_image->at( p );
     larcv::Image2D const& weights = pmtw_image_array.at( p );
     larcv::Image2D weighted( tpcimg );
     larcv::Image2D mask( tpcimg );
 //      std::cout << "tpc: (" << tpcimg.meta().rows() << "," << tpcimg.meta().cols() << ") "
 //        << "weights: (" << resizedWeightMat[p].meta().rows()  << "," << resizedWeightMat[p].meta().cols() << ")" << std::endl;
     for (size_t c=0; c<weighted.meta().cols(); c++) {
       float w = weights.pixel(c,0);
 //    if ( w<0 ) w = 0.0;
 //    if ( w>1.0 ) w = 1.0;
       for (size_t r=0; r<weighted.meta().rows(); r++) {
         weighted.set_pixel(r,c, w*tpcimg.pixel(r,c));
         mask.set_pixel( r, c, w );
       }
     }
     weighted_images.emplace_back( weighted );
     if (fSaveWeightMask) {
       mask_images.emplace_back( mask );
     }
       }
       LARCV_DEBUG() << "Made " << weighted_images.size() << " PMT Weighted Images." << std::endl;
       auto out_image_v = (::larcv::EventImage2D*)(mgr.get_data(::larcv::kProductImage2D,fOutputProducerName));
       ::larcv::EventImage2D* out_mask_v = NULL;
       out_image_v->Emplace(std::move(weighted_images));
       if ( fSaveWeightMask ) {
     out_mask_v = (::larcv::EventImage2D*)(mgr.get_data(::larcv::kProductImage2D,fWeightMaskProducerName));
     out_mask_v->Emplace(std::move(mask_images));
       }
       if ( fDebugSaveDistWeightMatrix ){
     auto out_matrix_v = (::larcv::EventImage2D*)(mgr.get_data(::larcv::kProductImage2D,"DistWeightMatrix"));
     std::vector<larcv::Image2D> mat;
     for (int p=0; p<3; p++) {
       mat.push_back( resizedWeightMat[p] );
     }
     out_matrix_v->Emplace(std::move(mat));
       }
       return true;
     }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fCheckSat
bool larcv::pmtweights::PMTWeightImageBuilder::fCheckSat
Definition at line 58 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fDebugSaveDistWeightMatrix
bool larcv::pmtweights::PMTWeightImageBuilder::fDebugSaveDistWeightMatrix
Definition at line 63 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fEndTick
int larcv::pmtweights::PMTWeightImageBuilder::fEndTick
Definition at line 56 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fGeoFile
std::string larcv::pmtweights::PMTWeightImageBuilder::fGeoFile
Definition at line 50 of file PMTWeightImageBuilder.h.
Referenced by configure(), and initialize().
fHGpedestal
float larcv::pmtweights::PMTWeightImageBuilder::fHGpedestal
Definition at line 60 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fNWirePixels
int larcv::pmtweights::PMTWeightImageBuilder::fNWirePixels
Definition at line 54 of file PMTWeightImageBuilder.h.
Referenced by configure(), and initialize().
fOutputProducerName
std::string larcv::pmtweights::PMTWeightImageBuilder::fOutputProducerName
Definition at line 53 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fPMTImageIndex
int larcv::pmtweights::PMTWeightImageBuilder::fPMTImageIndex
Definition at line 59 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fPMTImageProducer
std::string larcv::pmtweights::PMTWeightImageBuilder::fPMTImageProducer
Definition at line 51 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fResizedMat
bool larcv::pmtweights::PMTWeightImageBuilder::fResizedMat
Definition at line 65 of file PMTWeightImageBuilder.h.
Referenced by initialize(), and process().
fSaveWeightMask
bool larcv::pmtweights::PMTWeightImageBuilder::fSaveWeightMask
Definition at line 61 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fStartTick
int larcv::pmtweights::PMTWeightImageBuilder::fStartTick
Definition at line 55 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fTPCImageProducer
std::string larcv::pmtweights::PMTWeightImageBuilder::fTPCImageProducer
Definition at line 52 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
fWeightMaskProducerName
std::string larcv::pmtweights::PMTWeightImageBuilder::fWeightMaskProducerName
Definition at line 62 of file PMTWeightImageBuilder.h.
Referenced by configure(), and process().
m_WireWeights
PMTWireWeights* larcv::pmtweights::PMTWeightImageBuilder::m_WireWeights
Definition at line 57 of file PMTWeightImageBuilder.h.
Referenced by initialize(), process(), and ~PMTWeightImageBuilder().
resizedWeightMat
std::map< int, larcv::Image2D> larcv::pmtweights::PMTWeightImageBuilder::resizedWeightMat
Definition at line 66 of file PMTWeightImageBuilder.h.
Referenced by process().
The documentation for this class was generated from the following files:
PMTWeightImageBuilder.h
PMTWeightImageBuilder.cxx