LArCV: larcv::PGraph Class Reference
larcv::PGraph Class Reference
User defined class PGraph ...
#include <PGraph.h>
Public Member Functions
PGraph ()
Default constructor.
~PGraph ()
Default destructor.
size_t NumParticles () const
void Add (const larcv::ROI &roi, size_t pcluster_idx)
void Emplace (larcv::ROI &&roi, size_t pcluster_idx)
void Set (const std::vector< larcv::ROI > &roi_v, const std::vector< size_t > &pcluster_idx_v)
void Emplace (std::vector< larcv::ROI > &&roi_v, std::vector< size_t > &&pcluster_idx_v)
void Clear ()
const std::vector< larcv::ROI > & ParticleArray () const
const std::vector< size_t > & ClusterIndexArray () const
Private Attributes
std::vector< larcv::ROI > _part_v
std::vector< size_t > _pcluster_idx_v
Detailed Description
User defined class PGraph ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file PGraph.h.
Constructor & Destructor Documentation
PGraph()
larcv::PGraph::PGraph () inline
Default constructor.
Definition at line 31 of file PGraph.h.
 {}
~PGraph()
larcv::PGraph::~PGraph () inline
Default destructor.
Definition at line 34 of file PGraph.h.
 {}
Member Function Documentation
Add()
void larcv::PGraph::Add (const larcv::ROI & roi, size_t pcluster_idx)
Definition at line 14 of file PGraph.cxx.
References _part_v, and _pcluster_idx_v.
Referenced by NumParticles(), and larcv::VertexFilter::process().
   { _part_v.push_back(roi); _pcluster_idx_v.push_back(pcluster_idx); }
Clear()
void larcv::PGraph::Clear ()
Definition at line 11 of file PGraph.cxx.
References _part_v, and _pcluster_idx_v.
Referenced by NumParticles().
   { _part_v.clear(); _pcluster_idx_v.clear(); }
ClusterIndexArray()
const std::vector<size_t>& larcv::PGraph::ClusterIndexArray () const inline
Definition at line 50 of file PGraph.h.
References _pcluster_idx_v.
 { return _pcluster_idx_v; }
Emplace() [1/2]
void larcv::PGraph::Emplace (larcv::ROI && roi, size_t pcluster_idx)
Definition at line 17 of file PGraph.cxx.
References _part_v, and _pcluster_idx_v.
Referenced by NumParticles(), larcv::VertexFilter::process(), and larcv::LArbysImage::StoreParticles().
   { _part_v.emplace_back(std::move(roi)); _pcluster_idx_v.push_back(pcluster_idx); }
Emplace() [2/2]
void larcv::PGraph::Emplace (std::vector< larcv::ROI > && roi_v, std::vector< size_t > && pcluster_idx_v)
Definition at line 27 of file PGraph.cxx.
References _part_v, and _pcluster_idx_v.
   {
     assert(roi_v.size() == pcluster_idx_v.size());
     _part_v = std::move(roi_v);
     _pcluster_idx_v = std::move(pcluster_idx_v);
   }
NumParticles()
size_t larcv::PGraph::NumParticles () const inline
Definition at line 36 of file PGraph.h.
References _part_v, Add(), Clear(), Emplace(), and Set().
 { return _part_v.size(); }
ParticleArray()
const std::vector<larcv::ROI>& larcv::PGraph::ParticleArray () const inline
Definition at line 49 of file PGraph.h.
References _part_v.
 { return _part_v; }
Set()
void larcv::PGraph::Set (const std::vector< larcv::ROI > & roi_v, const std::vector< size_t > & pcluster_idx_v)
Definition at line 20 of file PGraph.cxx.
References _part_v, and _pcluster_idx_v.
Referenced by NumParticles().
   {
     assert(roi_v.size() == pcluster_idx_v.size());
     _part_v = roi_v;
     _pcluster_idx_v = pcluster_idx_v;
   }
Member Data Documentation
_part_v
std::vector<larcv::ROI> larcv::PGraph::_part_v private
Definition at line 53 of file PGraph.h.
Referenced by Add(), Clear(), Emplace(), NumParticles(), ParticleArray(), and Set().
_pcluster_idx_v
std::vector<size_t> larcv::PGraph::_pcluster_idx_v private
Definition at line 54 of file PGraph.h.
Referenced by Add(), Clear(), ClusterIndexArray(), Emplace(), and Set().
The documentation for this class was generated from the following files:
PGraph.h
PGraph.cxx