LArCV: larcv::LArbysImageCheater Class Reference
larcv::LArbysImageCheater Class Reference
#include <LArbysImageCheater.h>
Public Member Functions
LArbysImageCheater (const std::string name="LArbysImageCheater")
~LArbysImageCheater ()
void SetIOManager (IOManager *mgr)
void SetTrueROIProducer (const std::string &true_prod)
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
const larocv::ImageClusterManager & Manager () const
const PreProcessor & PProcessor () const
const LArbysImageMaker & LArbysImgMaker () const
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Member Functions
void Process ()
const std::vector< larcv::Image2D > & get_image2d (IOManager &mgr, std::string producer)
void get_rsee (IOManager &mgr, std::string producer, int &run, int &subrun, int &event, int &entry)
bool Reconstruct (const std::vector< larcv::Image2D > &adc_image_v, const std::vector< larcv::Image2D > &track_image_v, const std::vector< larcv::Image2D > &shower_image_v, const std::vector< larcv::Image2D > &thrumu_image_v, const std::vector< larcv::Image2D > &stopmu_image_v, const std::vector< larcv::Image2D > &chstat_image_v)
bool StoreParticles (IOManager &iom, const std::vector< larcv::Image2D > &adcimg_v, size_t &pidx)
void Report () const
Protected Attributes
larocv::ImageClusterManager _alg_mgr
larocv::ImageManager _adc_img_mgr
larocv::ImageManager _track_img_mgr
larocv::ImageManager _shower_img_mgr
larocv::ImageManager _thrumu_img_mgr
larocv::ImageManager _stopmu_img_mgr
larocv::ImageManager _chstat_img_mgr
::fcllite::PSet _image_cluster_cfg
bool _debug
bool _preprocess
bool _write_reco
bool _mask_thrumu_pixels
bool _mask_stopmu_pixels
std::string _output_module_name
size_t _output_module_offset
std::string _rse_producer
std::string _adc_producer
std::string _roi_producer
std::string _track_producer
std::string _shower_producer
ProductType_t _tags_datatype
std::string _thrumu_producer
std::string _stopmu_producer
std::string _channel_producer
std::string _output_producer
std::string _vertex_algo_name
std::string _par_algo_name
std::string _3D_algo_name
larocv::AlgorithmID_t _vertex_algo_id
larocv::AlgorithmID_t _par_algo_id
larocv::AlgorithmID_t _3D_algo_id
size_t _vertex_algo_vertex_offset
size_t _par_algo_par_offset
double _process_count
double _process_time_image_extraction
double _process_time_analyze
double _process_time_cluster_storage
bool _union_roi
PreProcessor _PreProcessor
LArbysImageMaker _LArbysImageMaker
std::vector< larcv::Image2D > _empty_image_v
std::vector< larcv::Image2D > _thrumu_image_v
std::vector< larcv::Image2D > _stopmu_image_v
ROI _current_roi
bool _store_shower_image
std::string _shower_pixel_prod
Private Attributes
::larutil::SpaceChargeMicroBooNE _sce
IOManager * _mgr
std::string _true_prod
Detailed Description
Definition at line 9 of file LArbysImageCheater.h.
Constructor & Destructor Documentation
LArbysImageCheater()
larcv::LArbysImageCheater::LArbysImageCheater (const std::string name = "LArbysImageCheater")
Definition at line 12 of file LArbysImageCheater.cxx.
Referenced by larcv::LArbysImageCheaterProcessFactory::create().
                                                              :
     LArbysImage(),
     _sce(),
     _mgr(nullptr)
   {}
~LArbysImageCheater()
larcv::LArbysImageCheater::~LArbysImageCheater () inline
Definition at line 13 of file LArbysImageCheater.h.
References Process(), SetIOManager(), and SetTrueROIProducer().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::LArbysImage::configure (const PSet & cfg) virtual inherited
Implements larcv::ProcessBase.
Definition at line 29 of file LArbysImage.cxx.
References larcv::LArbysImage::_3D_algo_name, larcv::LArbysImage::_adc_producer, larcv::LArbysImage::_alg_mgr, larcv::LArbysImage::_channel_producer, larcv::LArbysImage::_image_cluster_cfg, larcv::LArbysImage::_LArbysImageMaker, larcv::LArbysImage::_mask_stopmu_pixels, larcv::LArbysImage::_mask_thrumu_pixels, larcv::LArbysImage::_output_producer, larcv::LArbysImage::_par_algo_name, larcv::LArbysImage::_par_algo_par_offset, larcv::LArbysImage::_preprocess, larcv::LArbysImage::_PreProcessor, larcv::LArbysImage::_process_count, larcv::LArbysImage::_process_time_analyze, larcv::LArbysImage::_process_time_cluster_storage, larcv::LArbysImage::_process_time_image_extraction, larcv::LArbysImage::_roi_producer, larcv::LArbysImage::_rse_producer, larcv::LArbysImage::_shower_pixel_prod, larcv::LArbysImage::_shower_producer, larcv::LArbysImage::_stopmu_producer, larcv::LArbysImage::_store_shower_image, larcv::LArbysImage::_tags_datatype, larcv::LArbysImage::_thrumu_producer, larcv::LArbysImage::_track_producer, larcv::LArbysImage::_vertex_algo_name, larcv::LArbysImage::_vertex_algo_vertex_offset, larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::PSet::get(), larcv::PSet::get_pset(), and LARCV_INFO.
Referenced by larcv::LArbysImage::~LArbysImage().
   {
     _rse_producer         = cfg.get<std::string>("RSEImageProducer","wire");
     _adc_producer         = cfg.get<std::string>("ADCImageProducer");
     _track_producer       = cfg.get<std::string>("TrackImageProducer","");
     _shower_producer      = cfg.get<std::string>("ShowerImageProducer","");
     _thrumu_producer      = cfg.get<std::string>("ThruMuImageProducer","");
     _stopmu_producer      = cfg.get<std::string>("StopMuImageProducer","");
     _channel_producer     = cfg.get<std::string>("ChStatusImageProducer","");
     _roi_producer         = cfg.get<std::string>("ROIProducer","");
     _output_producer      = cfg.get<std::string>("OutputImageProducer","");
     auto tags_datatype    = cfg.get<size_t>("CosmicTagDataType");
     _tags_datatype = (ProductType_t) tags_datatype;
     _mask_thrumu_pixels = cfg.get<bool>("MaskThruMu",false);
     _mask_stopmu_pixels = cfg.get<bool>("MaskStopMu",false);
     _LArbysImageMaker.Configure(cfg.get<larcv::PSet>("LArbysImageMaker"));
     _preprocess = cfg.get<bool>("PreProcess");
     if (_preprocess) {
       LARCV_INFO() << "Preprocessing image" << std::endl;
       _PreProcessor.Configure(cfg.get<larcv::PSet>("PreProcessor"));
     }
     _process_count = 0;
     _process_time_image_extraction = 0;
     _process_time_analyze = 0;
     _process_time_cluster_storage = 0;
     _image_cluster_cfg = ::fcllite::PSet(_alg_mgr.Name(),cfg.get_pset(_alg_mgr.Name()).data_string());
     _vertex_algo_name    = cfg.get<std::string>("VertexAlgoName");
     _par_algo_name       = cfg.get<std::string>("ParticleAlgoName");
     _3D_algo_name        = cfg.get<std::string>("3DAlgoName");
     _vertex_algo_vertex_offset = cfg.get<size_t>("VertexAlgoVertexOffset",0);
     _par_algo_par_offset       = cfg.get<size_t>("ParticleAlgoParticleOffset",0);
     _store_shower_image = cfg.get<bool>("StoreShowerImage",false);
     if(_store_shower_image) {
       _shower_pixel_prod = cfg.get<std::string>("ShowerPixelProducer");
       assert(!_shower_pixel_prod.empty());
     }
     return;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImage::finalize () virtual inherited
Implements larcv::ProcessBase.
Definition at line 742 of file LArbysImage.cxx.
References larcv::LArbysImage::_alg_mgr, larcv::ProcessBase::ana_file(), and larcv::ProcessBase::has_ana_file().
Referenced by larcv::LArbysImage::~LArbysImage().
   {
     if ( has_ana_file() )  {
       _alg_mgr.Finalize(&(ana_file()));
     }
   }
get_image2d()
const std::vector< larcv::Image2D > & larcv::LArbysImage::get_image2d (IOManager & mgr, std::string producer) protected inherited
Definition at line 149 of file LArbysImage.cxx.
References larcv::LArbysImage::_empty_image_v, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_CRITICAL, and LARCV_DEBUG.
Referenced by larcv::LArbysImage::LArbysImgMaker(), and larcv::LArbysImage::process().
{
     if(!producer.empty()) {
       LARCV_DEBUG() << "Extracting " << producer << " Image\n" << std::endl;
       auto ev_image = (EventImage2D*)(mgr.get_data(kProductImage2D,producer));
       if(!ev_image) {
     LARCV_CRITICAL() << "Image by producer " << producer << " not found..." << std::endl;
     throw larbys();
       }
       return ev_image->Image2DArray();
     }
     LARCV_DEBUG() << "... this producer empty" << std::endl;
     return _empty_image_v;
   }
get_rsee()
void larcv::LArbysImage::get_rsee (IOManager & mgr, std::string producer, int & run, int & subrun, int & event, int & entry) protected inherited
Definition at line 112 of file LArbysImage.cxx.
References larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kINVALID_SIZE, larcv::kProductImage2D, and LARCV_CRITICAL.
Referenced by larcv::LArbysImage::LArbysImgMaker(), and larcv::LArbysImage::process().
{
     auto ev_image = (EventImage2D*)(mgr.get_data(kProductImage2D,producer));
     size_t local_run    = ev_image->run();
     size_t local_subrun = ev_image->subrun();
     size_t local_event  = ev_image->event();
     size_t local_entry  = mgr.current_entry();
     if (local_run == kINVALID_SIZE)  {
       LARCV_CRITICAL() << "Invalid run number @ entry " << local_entry << " from " << producer << " producer" << std::endl;
       throw larbys();
     }
     if (local_subrun == kINVALID_SIZE)  {
       LARCV_CRITICAL() << "Invalid subrun number @ entry " << local_entry << " from " << producer << " producer" << std::endl;
       throw larbys();
     }
     if (local_event == kINVALID_SIZE)  {
       LARCV_CRITICAL() << "Invalid event number @ entry " << local_entry << " from " << producer << " producer" << std::endl;
       throw larbys();
     }
     if (local_entry == kINVALID_SIZE)  {
       LARCV_CRITICAL() << "Invalid entry number @ entry "  << local_entry << " from " << producer << " producer" << std::endl;
       throw larbys();
     }
     run    = (int) local_run;
     subrun = (int) local_subrun;
     event  = (int) local_event;
     entry  = (int) local_entry;
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImage::initialize () virtual inherited
Implements larcv::ProcessBase.
Definition at line 78 of file LArbysImage.cxx.
References larcv::LArbysImage::_3D_algo_id, larcv::LArbysImage::_3D_algo_name, larcv::LArbysImage::_alg_mgr, larcv::LArbysImage::_image_cluster_cfg, larcv::LArbysImage::_par_algo_id, larcv::LArbysImage::_par_algo_name, larcv::LArbysImage::_stopmu_image_v, larcv::LArbysImage::_thrumu_image_v, larcv::LArbysImage::_vertex_algo_id, and larcv::LArbysImage::_vertex_algo_name.
Referenced by larcv::LArbysImage::~LArbysImage().
   {
     _thrumu_image_v.clear();
     _stopmu_image_v.clear();
     _alg_mgr.Configure(_image_cluster_cfg.get_pset(_alg_mgr.Name()));
     const auto& data_man = _alg_mgr.DataManager();
     _vertex_algo_id = larocv::kINVALID_ALGO_ID;
     if (!_vertex_algo_name.empty()) {
       _vertex_algo_id = data_man.ID(_vertex_algo_name);
       if (_vertex_algo_id == larocv::kINVALID_ALGO_ID)
     throw larbys("Specified invalid vertex algorithm");
     }
     _par_algo_id = larocv::kINVALID_ALGO_ID;
     if (!_par_algo_name.empty()) {
       _par_algo_id = data_man.ID(_par_algo_name);
       if (_par_algo_id == larocv::kINVALID_ALGO_ID) {
     throw larbys("Specified invalid particle algorithm");
       }
     }
     _3D_algo_id = larocv::kINVALID_ALGO_ID;
     if (!_3D_algo_name.empty()) {
       _3D_algo_id = data_man.ID(_3D_algo_name);
       if (_3D_algo_id == larocv::kINVALID_ALGO_ID) {
     throw larbys("Specified invalid 3D info algorithm");
       }
     }
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
LArbysImgMaker()
const LArbysImageMaker& larcv::LArbysImage::LArbysImgMaker () const inline inherited
Definition at line 38 of file LArbysImage.h.
References larcv::LArbysImage::_LArbysImageMaker, larcv::LArbysImage::get_image2d(), larcv::LArbysImage::get_rsee(), larcv::LArbysImage::Process(), larcv::LArbysImage::Reconstruct(), and larcv::LArbysImage::StoreParticles().
 { return _LArbysImageMaker; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Manager()
const larocv::ImageClusterManager& larcv::LArbysImage::Manager () const inline inherited
Definition at line 35 of file LArbysImage.h.
References larcv::LArbysImage::_alg_mgr.
 { return _alg_mgr; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
PProcessor()
const PreProcessor& larcv::LArbysImage::PProcessor () const inline inherited
Definition at line 37 of file LArbysImage.h.
References larcv::LArbysImage::_PreProcessor.
 { return _PreProcessor; }
Process()
void larcv::LArbysImageCheater::Process () protected virtual
Reimplemented from larcv::LArbysImage.
Definition at line 23 of file LArbysImageCheater.cxx.
References larcv::LArbysImage::_alg_mgr, _mgr, _sce, _true_prod, larcv::IOManager< T >::get_data(), larcv::kProductROI, and LARCV_DEBUG.
Referenced by ~LArbysImageCheater().
{
     //
     // Cheat the first algo by extracting the truth vertex position
     //
     std::string cheater_alg_name = "vertexcheater";
     LARCV_DEBUG() << "Set cheater algo name: " << cheater_alg_name << std::endl;
     auto cheater_id = _alg_mgr.GetClusterAlgID(cheater_alg_name);
     auto cheater_alg = (larocv::VertexCheater*)_alg_mgr.GetClusterAlgRW(cheater_id);
     if (!cheater_alg) throw larbys("Could not find RW cheater algo");
     if (!_mgr) throw larbys("No IOManager pointer specified");
     auto true_roi_producer = _true_prod;
     LARCV_DEBUG() << "Set true ROI producer name: " << true_roi_producer << std::endl;
     auto ev_roi = (EventROI*)_mgr->get_data(kProductROI,true_roi_producer);
     if(!ev_roi) throw larbys("Could not read given true ROI producer");
     if(ev_roi->ROIArray().empty()) throw larbys("Could not find given true ROI producer");
     const auto& roi = ev_roi->ROIArray().front();
     auto tx = roi.X();
     auto ty = roi.Y();
     auto tz = roi.Z();
     LARCV_DEBUG() << "Read (x,y,z)=("<<tx<<","<<ty<<","<<tz<<")"<<std::endl;
     const auto offset = _sce.GetPosOffsets(tx,ty,tz);
     tx = tx - offset[0] + 0.7;
     ty = ty + offset[1];
     tz = tz + offset[2];
     LARCV_DEBUG() << "SCE (x,y,z)=("<<tx<<","<<ty<<","<<tz<<")"<<std::endl;
     larocv::data::Vertex3D true_vertex;
     true_vertex.x = tx;
     true_vertex.y = ty;
     true_vertex.z = tz;
     cheater_alg->SetTrueVertex(true_vertex);
     _alg_mgr.Process();
   }
process()
bool larcv::LArbysImage::process (IOManager & mgr) virtual inherited
Implements larcv::ProcessBase.
Definition at line 165 of file LArbysImage.cxx.
References larcv::LArbysImage::_adc_producer, larcv::LArbysImage::_alg_mgr, larcv::LArbysImage::_channel_producer, larcv::LArbysImage::_current_roi, larcv::LArbysImage::_LArbysImageMaker, larcv::LArbysImage::_mask_stopmu_pixels, larcv::LArbysImage::_mask_thrumu_pixels, larcv::LArbysImage::_roi_producer, larcv::LArbysImage::_rse_producer, larcv::LArbysImage::_shower_pixel_prod, larcv::LArbysImage::_shower_producer, larcv::LArbysImage::_stopmu_image_v, larcv::LArbysImage::_stopmu_producer, larcv::LArbysImage::_store_shower_image, larcv::LArbysImage::_tags_datatype, larcv::LArbysImage::_thrumu_image_v, larcv::LArbysImage::_thrumu_producer, larcv::LArbysImage::_track_producer, larcv::ROI::AppendBB(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::LArbysImage::get_image2d(), larcv::LArbysImage::get_rsee(), larcv::Pixel2D::Intensity(), larcv::kProductPixel2D, larcv::kProductROI, LARCV_CRITICAL, LARCV_DEBUG, larcv::mask_image(), larcv::LArbysImage::Reconstruct(), and larcv::LArbysImage::StoreParticles().
Referenced by larcv::LArbysImage::~LArbysImage().
   {
     LARCV_DEBUG() << "Process index " << mgr.current_entry() << std::endl;
     int run, subrun, event, entry;
     get_rsee(mgr,_rse_producer,run,subrun,event,entry);
     _alg_mgr.SetRSEE(run,subrun,event,entry);
     bool status = true;
     if(_roi_producer.empty()) {
       size_t pidx = 0;
       const auto& adc_image_v    = get_image2d(mgr,_adc_producer);
       const auto& track_image_v  = get_image2d(mgr,_track_producer);
       const auto& shower_image_v = get_image2d(mgr,_shower_producer);
       const auto& chstat_image_v = get_image2d(mgr,_channel_producer);
       _LArbysImageMaker.ConstructCosmicImage(mgr, _thrumu_producer, _tags_datatype, adc_image_v, _thrumu_image_v);
       _LArbysImageMaker.ConstructCosmicImage(mgr, _stopmu_producer, _tags_datatype, adc_image_v, _stopmu_image_v);
       const auto& thrumu_image_v = _thrumu_image_v;
       const auto& stopmu_image_v = _stopmu_image_v;
       assert(adc_image_v.size());
       assert(track_image_v.empty()  || adc_image_v.size() == track_image_v.size());
       assert(shower_image_v.empty() || adc_image_v.size() == shower_image_v.size());
       assert(chstat_image_v.empty() || adc_image_v.size() == chstat_image_v.size());
       assert(thrumu_image_v.empty() || adc_image_v.size() == thrumu_image_v.size());
       assert(stopmu_image_v.empty() || adc_image_v.size() == stopmu_image_v.size());
       bool mask_thrumu = _mask_thrumu_pixels && !thrumu_image_v.empty();
       bool mask_stopmu = _mask_stopmu_pixels && !stopmu_image_v.empty();
       if(!mask_thrumu && !mask_stopmu) {
     LARCV_DEBUG() << "Reconstruct no mask thrumu and no mask stopmu" << std::endl;
     status = Reconstruct(adc_image_v,
                  track_image_v,shower_image_v,
                  thrumu_image_v,stopmu_image_v,
                  chstat_image_v);
     status = status && StoreParticles(mgr,adc_image_v,pidx);
       } // don't mask stop mu or thru mu
       else {
     auto copy_adc_image_v    = adc_image_v;
     auto copy_track_image_v  = track_image_v;
     auto copy_shower_image_v = shower_image_v;
     LARCV_DEBUG() << "ADC image size " << adc_image_v.size() << std::endl;
     for(size_t plane=0; plane<adc_image_v.size(); ++plane) {
       if(mask_thrumu) {
         LARCV_DEBUG() << "Masking thrumu plane " << plane << std::endl;
         mask_image(copy_adc_image_v[plane], thrumu_image_v[plane]);
         if(!copy_track_image_v.empty() ) mask_image(copy_track_image_v[plane],  thrumu_image_v[plane]);
         if(!copy_shower_image_v.empty()) mask_image(copy_shower_image_v[plane], thrumu_image_v[plane]);
       }
       if(mask_stopmu) {
         LARCV_DEBUG() << "Masking stopmu plane " << plane << std::endl;
         mask_image(copy_adc_image_v[plane], stopmu_image_v[plane]);
         if(!copy_track_image_v.empty() ) mask_image(copy_track_image_v[plane],  stopmu_image_v[plane]);
         if(!copy_shower_image_v.empty()) mask_image(copy_shower_image_v[plane], stopmu_image_v[plane]);
       }
     }
     status = Reconstruct(copy_adc_image_v,
                  copy_track_image_v,copy_shower_image_v,
                  thrumu_image_v, stopmu_image_v,
                  chstat_image_v);
     status = status && StoreParticles(mgr,copy_adc_image_v,pidx);
       } // mask stop mu or thru mu
     }
     //ROI exists, process per crop
     else{
       size_t pidx = 0;
       const auto& adc_image_v    = get_image2d(mgr,_adc_producer);
       const auto& track_image_v  = get_image2d(mgr,_track_producer);
       const auto& shower_image_v = get_image2d(mgr,_shower_producer);
       const auto& chstat_image_v = get_image2d(mgr,_channel_producer);
       _LArbysImageMaker.ConstructCosmicImage(mgr, _thrumu_producer, _tags_datatype, adc_image_v, _thrumu_image_v);
       _LArbysImageMaker.ConstructCosmicImage(mgr, _stopmu_producer, _tags_datatype, adc_image_v, _stopmu_image_v);
       const auto& thrumu_image_v = _thrumu_image_v;
       const auto& stopmu_image_v = _stopmu_image_v;
       auto pixel_height = adc_image_v.front().meta().pixel_height();
       auto pixel_width  = adc_image_v.front().meta().pixel_width();
       LARCV_DEBUG() << "Recieved ADC image (w,h)=("<<pixel_width<<","<<pixel_height<<")"<<std::endl;
       assert(adc_image_v.size());
       assert(track_image_v.empty()  || adc_image_v.size() == track_image_v.size());
       assert(shower_image_v.empty() || adc_image_v.size() == shower_image_v.size());
       assert(chstat_image_v.empty() || adc_image_v.size() == chstat_image_v.size());
       assert(thrumu_image_v.empty() || adc_image_v.size() == thrumu_image_v.size());
       assert(stopmu_image_v.empty() || adc_image_v.size() == stopmu_image_v.size());
       LARCV_DEBUG() << "ADC image sz " << adc_image_v.size() << std::endl;
       LARCV_DEBUG() << "TRK image sz " << track_image_v.size() << std::endl;
       LARCV_DEBUG() << "SHR image sz " << shower_image_v.size() << std::endl;
       LARCV_DEBUG() << "CHS image sz " << chstat_image_v.size() << std::endl;
       LARCV_DEBUG() << "TMU image sz " << thrumu_image_v.size() << std::endl;
       LARCV_DEBUG() << "SMU image sz " << stopmu_image_v.size() << std::endl;
       LARCV_DEBUG() << "Extracting " << _roi_producer << " ROI\n" << std::endl;
       if( !(mgr.get_data(kProductROI,_roi_producer)) ) {
     LARCV_CRITICAL() << "ROI by producer " << _roi_producer << " not found..." << std::endl;
     throw larbys();
       }
       const auto& roi_v = ((EventROI*)(mgr.get_data(kProductROI,_roi_producer)))->ROIArray();
       LARCV_DEBUG() << "Got " << roi_v.size() << " ROIs" << std::endl;
       for(const auto& roi : roi_v) {
     LARCV_DEBUG() << "ROI @ " << &roi << " pidx " << pidx << std::endl;
     _current_roi = larcv::ROI();
     const auto& bb_v = roi.BB();
     assert(bb_v.size() == adc_image_v.size());
     std::vector<larcv::Image2D> crop_adc_image_v;
     std::vector<larcv::Image2D> crop_track_image_v;
     std::vector<larcv::Image2D> crop_shower_image_v;
     std::vector<larcv::Image2D> crop_thrumu_image_v;
     std::vector<larcv::Image2D> crop_stopmu_image_v;
     std::vector<larcv::Image2D> crop_chstat_image_v;
     crop_adc_image_v.reserve(3);
     crop_track_image_v.reserve(3);
     crop_shower_image_v.reserve(3);
     crop_thrumu_image_v.reserve(3);
     crop_stopmu_image_v.reserve(3);
     crop_chstat_image_v.reserve(3);
     for(size_t plane=0; plane<bb_v.size(); ++plane) {
       const auto& bb           = bb_v[plane];
       const auto& adc_image    = adc_image_v[plane];
       LARCV_DEBUG() << "bb:   " << bb.dump();
       LARCV_DEBUG() << "adc:  " << adc_image.meta().dump();
       crop_adc_image_v.emplace_back(adc_image.crop(bb));
       _current_roi.AppendBB(crop_adc_image_v.at(plane).meta());
       LARCV_DEBUG() << "crop: " << crop_adc_image_v.back().meta().dump();
       if(!track_image_v.empty()) {
         const auto& track_image  = track_image_v[plane];
         crop_track_image_v.emplace_back(track_image.crop(bb));
       }
       if(!shower_image_v.empty()) {
         const auto& shower_image = shower_image_v[plane];
         crop_shower_image_v.emplace_back(shower_image.crop(bb));
       }
       if(!thrumu_image_v.empty()) {
         const auto& thrumu_image = thrumu_image_v[plane];
         crop_thrumu_image_v.emplace_back(thrumu_image.crop(bb));
       }
       if(!stopmu_image_v.empty()) {
         const auto& stopmu_image = stopmu_image_v[plane];
         crop_stopmu_image_v.emplace_back(stopmu_image.crop(bb));
       }
       if(!chstat_image_v.empty()) {
         const auto& chstat_image = chstat_image_v[plane];
         crop_chstat_image_v.emplace_back(chstat_image.crop(bb));
       }
       if(!crop_thrumu_image_v.empty() && _mask_thrumu_pixels) {
         LARCV_DEBUG() << "Masking thrumu plane " << plane << std::endl;
         mask_image(crop_adc_image_v[plane], crop_thrumu_image_v[plane]);
         if(!crop_track_image_v.empty() ) mask_image(crop_track_image_v[plane],  crop_thrumu_image_v[plane]);
         if(!crop_shower_image_v.empty()) mask_image(crop_shower_image_v[plane], crop_thrumu_image_v[plane]);
       }
       if(!crop_stopmu_image_v.empty() && _mask_stopmu_pixels) {
         LARCV_DEBUG() << "Masking stopmu plane " << plane << std::endl;
         mask_image(crop_adc_image_v[plane], crop_stopmu_image_v[plane]);
         if(!crop_track_image_v.empty() ) mask_image(crop_track_image_v[plane],  crop_stopmu_image_v[plane]);
         if(!crop_shower_image_v.empty()) mask_image(crop_shower_image_v[plane], crop_stopmu_image_v[plane]);
       }
     }
     status = status && Reconstruct(crop_adc_image_v,
                        crop_track_image_v,
                        crop_shower_image_v,
                        crop_thrumu_image_v,
                        crop_stopmu_image_v,
                        crop_chstat_image_v);
     status = status && StoreParticles(mgr,crop_adc_image_v,pidx);
       } // end loop over ROI
     } // end image fed to reco
     if(_store_shower_image) {
       LARCV_DEBUG() << "Storing shower image..." << std::endl;
       auto event_shr_pixel = (EventPixel2D*)mgr.get_data(kProductPixel2D,_shower_pixel_prod);
       const auto& shower_image_v = get_image2d(mgr,_shower_producer);
       for(size_t plane=0; plane<3; ++plane) {
     LARCV_DEBUG() << "... @plane=" << plane << std::endl;
     const auto& shr_img2d = shower_image_v[plane];
     const auto& shr_meta = shr_img2d.meta();
     event_shr_pixel->SetMeta(plane,shr_meta);
     LARCV_DEBUG() << "... rows=" << shr_img2d.meta().rows() << " cols=" << shr_img2d.meta().cols() << std::endl;
     for(size_t row=0; row<shr_img2d.meta().rows(); ++row) {
       for(size_t col=0; col<shr_img2d.meta().cols(); ++col) {
         if (shr_img2d.pixel(row,col)<10) continue;
         Pixel2D px(col,row);
         px.Intensity(shr_img2d.pixel(row,col));
         event_shr_pixel->Emplace(plane,std::move(px));
       } // end col
     } // end row
       } // end plane
     } // end store shower image
     LARCV_DEBUG() << "return " << status << std::endl;
     LARCV_DEBUG() << std::endl;
     return status;
   } // end process
Reconstruct()
bool larcv::LArbysImage::Reconstruct (const std::vector< larcv::Image2D > & adc_image_v, const std::vector< larcv::Image2D > & track_image_v, const std::vector< larcv::Image2D > & shower_image_v, const std::vector< larcv::Image2D > & thrumu_image_v, const std::vector< larcv::Image2D > & stopmu_image_v, const std::vector< larcv::Image2D > & chstat_image_v) protected inherited
Definition at line 594 of file LArbysImage.cxx.
References larcv::LArbysImage::_adc_img_mgr, larcv::LArbysImage::_adc_producer, larcv::LArbysImage::_alg_mgr, larcv::LArbysImage::_channel_producer, larcv::LArbysImage::_chstat_img_mgr, larcv::LArbysImage::_LArbysImageMaker, larcv::LArbysImage::_preprocess, larcv::LArbysImage::_PreProcessor, larcv::LArbysImage::_process_count, larcv::LArbysImage::_process_time_analyze, larcv::LArbysImage::_process_time_image_extraction, larcv::LArbysImage::_shower_img_mgr, larcv::LArbysImage::_shower_producer, larcv::LArbysImage::_stopmu_img_mgr, larcv::LArbysImage::_stopmu_producer, larcv::LArbysImage::_thrumu_img_mgr, larcv::LArbysImage::_thrumu_producer, larcv::LArbysImage::_track_img_mgr, larcv::LArbysImage::_track_producer, larcv::LArbysImageMaker::ExtractImage(), LARCV_CRITICAL, LARCV_DEBUG, larcv::PreProcessor::PreProcess(), and larcv::LArbysImage::Process().
Referenced by larcv::LArbysImage::LArbysImgMaker(), and larcv::LArbysImage::process().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _adc_img_mgr.clear();
     _track_img_mgr.clear();
     _shower_img_mgr.clear();
     _thrumu_img_mgr.clear();
     _stopmu_img_mgr.clear();
     _chstat_img_mgr.clear();
     _alg_mgr.ClearData();
     larocv::Watch watch_all, watch_one;
     watch_all.Start();
     watch_one.Start();
     LARCV_DEBUG() << "Extract adc prod: " << _adc_producer << std::endl;
     LARCV_DEBUG() << "... sz " << adc_image_v.size() << std::endl;
     for(auto& img_data : _LArbysImageMaker.ExtractImage(adc_image_v)) {
       _adc_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                 std::move(std::get<1>(img_data)));
     }
     if(!_track_producer.empty()) {
       LARCV_DEBUG() << "Extract track prod: " << _track_producer << std::endl;
       LARCV_DEBUG() << "... sz " << track_image_v.size() << std::endl;
       for(auto& img_data : _LArbysImageMaker.ExtractImage(track_image_v))  {
     _track_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                     std::move(std::get<1>(img_data)));
       }
     }
     if(!_shower_producer.empty()) {
       LARCV_DEBUG() << "Extract shower prod: " << _shower_producer << std::endl;
       LARCV_DEBUG() << "... sz " << shower_image_v.size() << std::endl;
       for(auto& img_data : _LArbysImageMaker.ExtractImage(shower_image_v)) {
     _shower_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                      std::move(std::get<1>(img_data)));
       }
     }
     if(!_stopmu_producer.empty()) {
       LARCV_DEBUG() << "Extract stopmu prod: " << _stopmu_producer << std::endl;
       LARCV_DEBUG() << "... sz " << stopmu_image_v.size() << std::endl;
       for(auto& img_data : _LArbysImageMaker.ExtractImage(stopmu_image_v)) {
     _thrumu_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                      std::move(std::get<1>(img_data)));
       }
     }
     if(!_thrumu_producer.empty()) {
       LARCV_DEBUG() << "Extract thrupmu prod: " << _thrumu_producer << std::endl;
       LARCV_DEBUG() << "... sz " << thrumu_image_v.size() << std::endl;
       for(auto& img_data : _LArbysImageMaker.ExtractImage(thrumu_image_v)) {
     _stopmu_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                      std::move(std::get<1>(img_data)));
       }
     }
     if(!_channel_producer.empty()) {
       LARCV_DEBUG() << "Extract channel prod: " << _channel_producer << std::endl;
       LARCV_DEBUG() << "... sz " << chstat_image_v.size() << std::endl;
       for(auto& img_data : _LArbysImageMaker.ExtractImage(chstat_image_v)) {
     _chstat_img_mgr.emplace_back(std::move(std::get<0>(img_data)),
                      std::move(std::get<1>(img_data)));
       }
     }
     _process_time_image_extraction += watch_one.WallTime();
     for (size_t plane = 0; plane < _adc_img_mgr.size(); ++plane) {
       auto       & img  = _adc_img_mgr.img_at(plane);
       const auto & meta = _adc_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add adc @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetWire);
     }
     for (size_t plane = 0; plane < _track_img_mgr.size(); ++plane) {
       auto       & img  = _track_img_mgr.img_at(plane);
       const auto & meta = _track_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add track @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetTrack);
     }
     for (size_t plane = 0; plane < _shower_img_mgr.size(); ++plane) {
       auto       & img  = _shower_img_mgr.img_at(plane);
       const auto & meta = _shower_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add shower @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetShower);
     }
     for (size_t plane = 0; plane < _thrumu_img_mgr.size(); ++plane) {
       auto       & img  = _thrumu_img_mgr.img_at(plane);
       const auto & meta = _thrumu_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add thrumu @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetThruMu);
     }
     for (size_t plane = 0; plane < _stopmu_img_mgr.size(); ++plane) {
       auto       & img  = _stopmu_img_mgr.img_at(plane);
       const auto & meta = _stopmu_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add stopmu @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetStopMu);
     }
     for (size_t plane = 0; plane < _chstat_img_mgr.size(); ++plane) {
       auto       & img  = _chstat_img_mgr.img_at(plane);
       const auto & meta = _chstat_img_mgr.meta_at(plane);
       if (!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       LARCV_DEBUG() << "... add chstat @plane="<<plane<<std::endl;
       _alg_mgr.Add(img, meta, larocv::ImageSetID_t::kImageSetChStatus);
     }
     if (_preprocess) {
       // give a single plane @ a time to pre processor
       auto& adc_img_v= _alg_mgr.InputImages(larocv::ImageSetID_t::kImageSetWire);
       auto& trk_img_v= _alg_mgr.InputImages(larocv::ImageSetID_t::kImageSetTrack);
       auto& shr_img_v= _alg_mgr.InputImages(larocv::ImageSetID_t::kImageSetShower);
       auto nplanes = adc_img_v.size();
       for(size_t plane_id=0;plane_id<nplanes;++plane_id) {
     LARCV_DEBUG() << "Preprocess image set @ "<< " plane " << plane_id << std::endl;
     if (!_PreProcessor.PreProcess(adc_img_v[plane_id],trk_img_v[plane_id],shr_img_v[plane_id])) {
       LARCV_CRITICAL() << "... could not be preprocessed, abort!" << std::endl;
       throw larbys();
     }
       }
     }
     watch_one.Start();
     Process();
     _process_time_analyze += watch_all.WallTime();
     ++_process_count;
     LARCV_DEBUG() << "end" << std::endl;
     return true;
   }
Report()
void larcv::LArbysImage::Report () const protected inherited
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetIOManager()
void larcv::LArbysImageCheater::SetIOManager (IOManager * mgr)
Definition at line 18 of file LArbysImageCheater.cxx.
References _mgr, and LARCV_INFO.
Referenced by ~LArbysImageCheater().
{
     _mgr = mgr;
     LARCV_INFO() << "Set IOManager pointer as " << _mgr << std::endl;
   }
SetTrueROIProducer()
void larcv::LArbysImageCheater::SetTrueROIProducer (const std::string & true_prod)
Definition at line 70 of file LArbysImageCheater.cxx.
References _true_prod.
Referenced by ~LArbysImageCheater().
{
     _true_prod = true_prod;
   }
StoreParticles()
bool larcv::LArbysImage::StoreParticles (IOManager & iom, const std::vector< larcv::Image2D > & adcimg_v, size_t & pidx) protected inherited
Definition at line 399 of file LArbysImage.cxx.
References larcv::LArbysImage::_3D_algo_id, larcv::LArbysImage::_alg_mgr, larcv::LArbysImage::_output_producer, larcv::LArbysImage::_par_algo_id, larcv::LArbysImage::_par_algo_par_offset, larcv::LArbysImage::_vertex_algo_id, larcv::LArbysImage::_vertex_algo_vertex_offset, larcv::ROI::AppendBB(), larcv::PGraph::Emplace(), larcv::ROI::EndPosition(), larcv::IOManager< T >::get_data(), larcv::kINVALID_DOUBLE, larcv::kINVALID_SIZE, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kShapeShower, larcv::kShapeTrack, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, larcv::ROI::Position(), and larcv::ROI::Shape().
Referenced by larcv::LArbysImage::LArbysImgMaker(), and larcv::LArbysImage::process().
{
     LARCV_DEBUG() << "start" << std::endl;
     // nothing to be done
     if (_vertex_algo_id == larocv::kINVALID_ALGO_ID) {
       LARCV_INFO() << "Nothing to be done..." << std::endl;
       return true;
     }
     const auto& adc_cvimg_orig_v = _alg_mgr.InputImages(larocv::ImageSetID_t::kImageSetWire);
     static std::vector<cv::Mat> adc_cvimg_v;
     adc_cvimg_v.clear();
     adc_cvimg_v.resize(3);
     auto event_pgraph           = (EventPGraph*)  iom.get_data(kProductPGraph,_output_producer);
     auto event_ctor_pixel       = (EventPixel2D*) iom.get_data(kProductPixel2D,_output_producer + "_ctor");
     auto event_img_pixel        = (EventPixel2D*) iom.get_data(kProductPixel2D,_output_producer + "_img");
     auto event_ctor_super_pixel = (EventPixel2D*) iom.get_data(kProductPixel2D,_output_producer + "_super_ctor");
     auto event_img_super_pixel  = (EventPixel2D*) iom.get_data(kProductPixel2D,_output_producer + "_super_img");
     const auto& data_mgr = _alg_mgr.DataManager();
     const auto& ass_man  = data_mgr.AssManager();
     const auto vtx3d_array = (larocv::data::Vertex3DArray*) data_mgr.Data(_vertex_algo_id, _vertex_algo_vertex_offset);
     const auto& vtx3d_v = vtx3d_array->as_vector();
     const auto par_array = (larocv::data::ParticleArray*) data_mgr.Data(_par_algo_id,_par_algo_par_offset);
     const auto& par_v = par_array->as_vector();
     const auto info_3D_array = (larocv::data::Info3DArray*) data_mgr.Data(_3D_algo_id,0);
     const auto& info_3D_v = info_3D_array->as_vector();
     auto n_reco_vtx = vtx3d_v.size();
     LARCV_DEBUG() << "Got " << n_reco_vtx << " reconstructed vertex" << std::endl;
     for(size_t vtxid=0; vtxid< n_reco_vtx; ++vtxid) {
       const auto& vtx3d = vtx3d_v[vtxid];
       LARCV_DEBUG() << vtxid << ") @ (x,y,z) : ("<<vtx3d.x<<","<<vtx3d.y<<","<<vtx3d.z<<")"<<std::endl;
       for(size_t plane=0; plane<3; ++plane)
     adc_cvimg_v[plane] = adc_cvimg_orig_v[plane].clone();
       auto par_id_v = ass_man.GetManyAss(vtx3d,par_array->ID());
       if (par_id_v.empty()) {
     LARCV_DEBUG() << "No associated particles to vertex " << vtxid << std::endl;
     continue;
       }
       std::vector<const larocv::data::ParticleCluster*> super_pcluster_v(3,nullptr);
       for(size_t plane=0; plane<3; ++plane) {
     const auto super_par_array = (larocv::data::ParticleClusterArray*) data_mgr.Data(_vertex_algo_id,1+plane+3);
     const auto& super_par_v = super_par_array->as_vector();
     auto super_ass_id_v = ass_man.GetManyAss(vtx3d,super_par_array->ID());
     if (super_ass_id_v.empty()) continue;
     assert (super_ass_id_v.size()==1);
     super_pcluster_v[plane] = &(super_par_v.at(super_ass_id_v.front()));
       }
       PGraph pgraph;
       for(const auto& par_id : par_id_v) {
     const auto& par = par_v.at(par_id);
     const auto info3d_id   = ass_man.GetOneAss(par,info_3D_array->ID());
     if (info3d_id == kINVALID_SIZE) throw larbys("Particle unassociated to 3D info collection");
     const auto& par_info3d = info_3D_v.at(info3d_id);
     // New ROI for this particle
     ROI proi;
     // Store the vertex
     proi.Position(vtx3d.x,vtx3d.y,vtx3d.z,kINVALID_DOUBLE);
     // Store the end point
     proi.EndPosition(par_info3d.overall_pca_end_pt.at(0),
              par_info3d.overall_pca_end_pt.at(1),
              par_info3d.overall_pca_end_pt.at(2),
              kINVALID_DOUBLE);
     // Store the type
     if      (par.type==larocv::data::ParticleType_t::kTrack)   proi.Shape(kShapeTrack);
     else if (par.type==larocv::data::ParticleType_t::kShower)  proi.Shape(kShapeShower);
     // Push the ROI into the PGraph
     LARCV_DEBUG() << " @ pg array index " << pidx << std::endl;
     for(size_t plane=0; plane<3; ++plane)
       proi.AppendBB(adc_image_v[plane].meta());
     pgraph.Emplace(std::move(proi),pidx);
     pidx++;
     // @ Each plane, store pixels and contour per matched particle
     for(size_t plane=0; plane<3; ++plane) {
       const auto& pmeta = adc_image_v[plane].meta();
       std::vector<Pixel2D> super_pixel_v, super_ctor_v;
       std::vector<Pixel2D> pixel_v, ctor_v;
       const auto& pcluster = par._par_v[plane];
       const auto& pctor = pcluster._ctor;
       const auto& img2d = adc_image_v.at(plane);
       const auto& cvimg = adc_cvimg_v.at(plane);
       if(!pctor.empty()) {
         const auto& super_pcluster = super_pcluster_v[plane];
         if (!super_pcluster) {
           LARCV_CRITICAL() << "particle exists but super contour not present" << std::endl;
           throw larbys("die");
         }
         const auto& super_pctor = super_pcluster->_ctor;
         auto super_pctor_masked = larocv::MaskImage(cvimg,super_pctor,0,false);
         auto super_par_pixel_v = larocv::FindNonZero(super_pctor_masked);
         auto pctor_masked = larocv::MaskImage(cvimg,pctor,0,false);
         auto par_pixel_v = larocv::FindNonZero(pctor_masked);
         super_pixel_v.reserve(super_par_pixel_v.size());
         super_ctor_v.reserve(super_pctor.size());
         pixel_v.reserve(par_pixel_v.size());
         ctor_v.reserve(pctor.size());
         // Store super particle Image2D pixels
         for (const auto& px : super_par_pixel_v) {
           auto col  = cvimg.cols - px.x - 1;
           auto row  = px.y;
           auto gray = img2d.pixel(col,row);
           super_pixel_v.emplace_back(col,row);
           super_pixel_v.back().Intensity(gray);
         }
         // Store the particle Image2D pixels
         for (const auto& px : par_pixel_v) {
           auto col  = cvimg.cols - px.x - 1;
           auto row  = px.y;
           auto gray = img2d.pixel(col,row);
           pixel_v.emplace_back(col,row);
           pixel_v.back().Intensity(gray);
         }
         // Store super contour
         for(const auto& pt : super_pctor)  {
           auto col  = cvimg.cols - pt.x - 1;
           auto row  = pt.y;
           auto gray = 1.0;
           super_ctor_v.emplace_back(row,col);
           super_ctor_v.back().Intensity(gray);
         }
         // Store contour
         for(const auto& pt : pctor)  {
           auto col  = cvimg.cols - pt.x - 1;
           auto row  = pt.y;
           auto gray = 1.0;
           ctor_v.emplace_back(row,col);
           ctor_v.back().Intensity(gray);
         }
       } // empty particle contour on this plane
       Pixel2DCluster super_pixcluster(std::move(super_pixel_v));
       Pixel2DCluster super_pixctor(std::move(super_ctor_v));
       Pixel2DCluster pixcluster(std::move(pixel_v));
       Pixel2DCluster pixctor(std::move(ctor_v));
       event_img_super_pixel->Emplace(plane,std::move(super_pixcluster),pmeta);
       event_ctor_super_pixel->Emplace(plane,std::move(super_pixctor),pmeta);
       event_img_pixel->Emplace(plane,std::move(pixcluster),pmeta);
       event_ctor_pixel->Emplace(plane,std::move(pixctor),pmeta);
     } // end this plane
       } // end this particle
       event_pgraph->Emplace(std::move(pgraph));
     } // end vertex
     LARCV_DEBUG() << "Event pgraph size " << event_pgraph->PGraphArray().size() << std::endl;
     return true;
   }
Member Data Documentation
_3D_algo_id
larocv::AlgorithmID_t larcv::LArbysImage::_3D_algo_id protected inherited
Definition at line 100 of file LArbysImage.h.
Referenced by larcv::LArbysImage::initialize(), and larcv::LArbysImage::StoreParticles().
_3D_algo_name
std::string larcv::LArbysImage::_3D_algo_name protected inherited
Definition at line 96 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::initialize().
_adc_img_mgr
larocv::ImageManager larcv::LArbysImage::_adc_img_mgr protected inherited
Definition at line 62 of file LArbysImage.h.
Referenced by larcv::LArbysImageReAna::Process(), and larcv::LArbysImage::Reconstruct().
_adc_producer
std::string larcv::LArbysImage::_adc_producer protected inherited
Definition at line 82 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_alg_mgr
larocv::ImageClusterManager larcv::LArbysImage::_alg_mgr protected inherited
Definition at line 61 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::finalize(), larcv::LArbysImage::initialize(), larcv::LArbysImage::Manager(), Process(), larcv::LArbysImageReAna::Process(), larcv::LArbysImage::process(), larcv::LArbysImage::Process(), larcv::LArbysImage::Reconstruct(), and larcv::LArbysImage::StoreParticles().
_channel_producer
std::string larcv::LArbysImage::_channel_producer protected inherited
Definition at line 91 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_chstat_img_mgr
larocv::ImageManager larcv::LArbysImage::_chstat_img_mgr protected inherited
Definition at line 67 of file LArbysImage.h.
Referenced by larcv::LArbysImage::Reconstruct().
_current_roi
ROI larcv::LArbysImage::_current_roi protected inherited
Definition at line 121 of file LArbysImage.h.
Referenced by larcv::LArbysImageReAna::Process(), and larcv::LArbysImage::process().
_debug
bool larcv::LArbysImage::_debug protected inherited
Definition at line 71 of file LArbysImage.h.
_empty_image_v
std::vector<larcv::Image2D> larcv::LArbysImage::_empty_image_v protected inherited
Definition at line 117 of file LArbysImage.h.
Referenced by larcv::LArbysImage::get_image2d().
_image_cluster_cfg
::fcllite::PSet larcv::LArbysImage::_image_cluster_cfg protected inherited
Definition at line 69 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::initialize().
_LArbysImageMaker
LArbysImageMaker larcv::LArbysImage::_LArbysImageMaker protected inherited
Definition at line 115 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::LArbysImgMaker(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_mask_stopmu_pixels
bool larcv::LArbysImage::_mask_stopmu_pixels protected inherited
Definition at line 76 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_mask_thrumu_pixels
bool larcv::LArbysImage::_mask_thrumu_pixels protected inherited
Definition at line 75 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_mgr
IOManager* larcv::LArbysImageCheater::_mgr private
Definition at line 25 of file LArbysImageCheater.h.
Referenced by Process(), and SetIOManager().
_output_module_name
std::string larcv::LArbysImage::_output_module_name protected inherited
Definition at line 78 of file LArbysImage.h.
_output_module_offset
size_t larcv::LArbysImage::_output_module_offset protected inherited
Definition at line 79 of file LArbysImage.h.
_output_producer
std::string larcv::LArbysImage::_output_producer protected inherited
Definition at line 92 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::StoreParticles().
_par_algo_id
larocv::AlgorithmID_t larcv::LArbysImage::_par_algo_id protected inherited
Definition at line 99 of file LArbysImage.h.
Referenced by larcv::LArbysImage::initialize(), and larcv::LArbysImage::StoreParticles().
_par_algo_name
std::string larcv::LArbysImage::_par_algo_name protected inherited
Definition at line 95 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::initialize().
_par_algo_par_offset
size_t larcv::LArbysImage::_par_algo_par_offset protected inherited
Definition at line 103 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::StoreParticles().
_preprocess
bool larcv::LArbysImage::_preprocess protected inherited
Definition at line 72 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::Reconstruct().
_PreProcessor
PreProcessor larcv::LArbysImage::_PreProcessor protected inherited
Definition at line 114 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::PProcessor(), and larcv::LArbysImage::Reconstruct().
_process_count
double larcv::LArbysImage::_process_count protected inherited
Definition at line 105 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::Reconstruct().
_process_time_analyze
double larcv::LArbysImage::_process_time_analyze protected inherited
Definition at line 107 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::Reconstruct().
_process_time_cluster_storage
double larcv::LArbysImage::_process_time_cluster_storage protected inherited
Definition at line 108 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure().
_process_time_image_extraction
double larcv::LArbysImage::_process_time_image_extraction protected inherited
Definition at line 106 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::Reconstruct().
_roi_producer
std::string larcv::LArbysImage::_roi_producer protected inherited
Definition at line 83 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_rse_producer
std::string larcv::LArbysImage::_rse_producer protected inherited
Definition at line 81 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_sce
::larutil::SpaceChargeMicroBooNE larcv::LArbysImageCheater::_sce private
Definition at line 24 of file LArbysImageCheater.h.
Referenced by Process().
_shower_img_mgr
larocv::ImageManager larcv::LArbysImage::_shower_img_mgr protected inherited
Definition at line 64 of file LArbysImage.h.
Referenced by larcv::LArbysImage::Reconstruct().
_shower_pixel_prod
std::string larcv::LArbysImage::_shower_pixel_prod protected inherited
Definition at line 124 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_shower_producer
std::string larcv::LArbysImage::_shower_producer protected inherited
Definition at line 85 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_stopmu_image_v
std::vector<larcv::Image2D> larcv::LArbysImage::_stopmu_image_v protected inherited
Definition at line 119 of file LArbysImage.h.
Referenced by larcv::LArbysImage::initialize(), and larcv::LArbysImage::process().
_stopmu_img_mgr
larocv::ImageManager larcv::LArbysImage::_stopmu_img_mgr protected inherited
Definition at line 66 of file LArbysImage.h.
Referenced by larcv::LArbysImage::Reconstruct().
_stopmu_producer
std::string larcv::LArbysImage::_stopmu_producer protected inherited
Definition at line 90 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_store_shower_image
bool larcv::LArbysImage::_store_shower_image protected inherited
Definition at line 123 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_tags_datatype
ProductType_t larcv::LArbysImage::_tags_datatype protected inherited
Definition at line 87 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::process().
_thrumu_image_v
std::vector<larcv::Image2D> larcv::LArbysImage::_thrumu_image_v protected inherited
Definition at line 118 of file LArbysImage.h.
Referenced by larcv::LArbysImage::initialize(), and larcv::LArbysImage::process().
_thrumu_img_mgr
larocv::ImageManager larcv::LArbysImage::_thrumu_img_mgr protected inherited
Definition at line 65 of file LArbysImage.h.
Referenced by larcv::LArbysImage::Reconstruct().
_thrumu_producer
std::string larcv::LArbysImage::_thrumu_producer protected inherited
Definition at line 89 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_track_img_mgr
larocv::ImageManager larcv::LArbysImage::_track_img_mgr protected inherited
Definition at line 63 of file LArbysImage.h.
Referenced by larcv::LArbysImage::Reconstruct().
_track_producer
std::string larcv::LArbysImage::_track_producer protected inherited
Definition at line 84 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), larcv::LArbysImage::process(), and larcv::LArbysImage::Reconstruct().
_true_prod
std::string larcv::LArbysImageCheater::_true_prod private
Definition at line 26 of file LArbysImageCheater.h.
Referenced by Process(), and SetTrueROIProducer().
_union_roi
bool larcv::LArbysImage::_union_roi protected inherited
Definition at line 110 of file LArbysImage.h.
_vertex_algo_id
larocv::AlgorithmID_t larcv::LArbysImage::_vertex_algo_id protected inherited
Definition at line 98 of file LArbysImage.h.
Referenced by larcv::LArbysImage::initialize(), and larcv::LArbysImage::StoreParticles().
_vertex_algo_name
std::string larcv::LArbysImage::_vertex_algo_name protected inherited
Definition at line 94 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::initialize().
_vertex_algo_vertex_offset
size_t larcv::LArbysImage::_vertex_algo_vertex_offset protected inherited
Definition at line 102 of file LArbysImage.h.
Referenced by larcv::LArbysImage::configure(), and larcv::LArbysImage::StoreParticles().
_write_reco
bool larcv::LArbysImage::_write_reco protected inherited
Definition at line 73 of file LArbysImage.h.
The documentation for this class was generated from the following files:
LArbysImageCheater.h
LArbysImageCheater.cxx