LArCV: larcv::DLCosmicTagUtil Class Reference
larcv::DLCosmicTagUtil Class Reference
#include <DLCosmicTagUtil.h>
Public Member Functions
DLCosmicTagUtil ()
Default constructor.
virtual ~DLCosmicTagUtil ()
Default destructor.
void Configure (PSet &pset)
Configures class.
void go_to_entry (size_t entry)
Loads the entry from the input larlite tree (via larlite::storage_manager object)
larlite::event_base * get_data (larlite::data::DataType_t data_type, std::string producername)
Wrapper around larlite::storage_manager::get_data.
std::vector< larcv::Image2D > makeIntimeCroppedImage (const std::vector< larcv::Image2D > &adc_wholeview_v, const int padding=10) const
use the intime cluster objects to form a crop within the wholeview image
std::vector< larcv::Image2D > makeCosmicMaskedImage (const std::vector< larcv::Image2D > &adc_view_v) const
within the region defined by the input images, provide a masked adc image
std::vector< larcv::Image2D > makeClusterTaggedImages (const std::vector< larcv::Image2D > &adc_view_v) const
within the region defined by the input images, tag the pixels with the cluster IDs
larlite::storage_manager & io ()
get the io manager (providing mutable instance)
int getNumClusters () const
get the number of clusters in the current entry
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static larcv::ImageMeta metaFromPixelMask (const larlite::pixelmask &mask, unsigned int planeid=0)
utility to make larcv::imagemeta from larlite::pixelmask
Protected Attributes
std::string _larlite_input_filename
std::vector< std::string > _intime_pixelmask_producername_v
std::string _intime_larflowcluster_producername
size_t _entry
larlite::storage_manager * _io
const larlite::event_larflowcluster * m_larflowcluster_v
std::vector< const larlite::event_pixelmask * > m_pixelmask_vv
bool fEntryLoaded
Detailed Description
Definition at line 19 of file DLCosmicTagUtil.h.
Constructor & Destructor Documentation
DLCosmicTagUtil()
larcv::DLCosmicTagUtil::DLCosmicTagUtil ()
Default constructor.
Definition at line 9 of file DLCosmicTagUtil.cxx.
     : _entry(-1),
       _io(nullptr),
       m_larflowcluster_v(nullptr),
       fEntryLoaded(false)
   {}
~DLCosmicTagUtil()
larcv::DLCosmicTagUtil::~DLCosmicTagUtil () virtual
Default destructor.
Definition at line 20 of file DLCosmicTagUtil.cxx.
References _io.
{
     _io->close();
     delete _io;
   }
Member Function Documentation
Configure()
void larcv::DLCosmicTagUtil::Configure (PSet & pset)
Configures class.
Parameters
[in] pset Parameter set for class.
Configurable parameters
InputFilename: larlite file containing larflowcluster and pixelmask objects
IntimePixelMaskProducer: name of trees containing intime pixel mask objects. should be in plane order.
IntimeLArFlowClusterProducer: name of tree containing intime larflow cluster objects
Definition at line 30 of file DLCosmicTagUtil.cxx.
References _intime_larflowcluster_producername, _intime_pixelmask_producername_v, _io, _larlite_input_filename, larcv::PSet::get(), and LARCV_ERROR.
{
     _larlite_input_filename             = pset.get<std::string>("InputFilename");
     _intime_pixelmask_producername_v    = pset.get<std::vector<std::string> >("IntimePlanePixelMaskProducers");
     if ( _intime_pixelmask_producername_v.size()==0 ) {
       LARCV_ERROR() << "Empty producer list for IntimePlanePixelMaskProducers" << std::endl;
     }
     _intime_larflowcluster_producername = pset.get<std::string>("IntimeLArFlowClusterProducer");
     _io = new larlite::storage_manager( larlite::storage_manager::kREAD );
     _io->add_in_filename( _larlite_input_filename );
     _io->open();
   }
get_data()
larlite::event_base * larcv::DLCosmicTagUtil::get_data (larlite::data::DataType_t data_type, std::string producername)
Wrapper around larlite::storage_manager::get_data.
Parameters
[in] data_type larlite::data enumerate ID.
[in] producername Name of tree to get object from.
Definition at line 111 of file DLCosmicTagUtil.cxx.
References _io.
Referenced by go_to_entry().
{
     return _io->get_data( data_type, producername );
   }
getNumClusters()
int larcv::DLCosmicTagUtil::getNumClusters () const
get the number of clusters in the current entry
Get number of clusters in the entry.
Returns
number of clusters in the entry
Definition at line 97 of file DLCosmicTagUtil.cxx.
References fEntryLoaded, LARCV_ERROR, and m_larflowcluster_v.
Referenced by io().
{
     // check proper condition of class
     if ( !fEntryLoaded )
       LARCV_ERROR() << "Entry has not been loaded yet." << std::endl;
     return m_larflowcluster_v->size();
   }
go_to_entry()
void larcv::DLCosmicTagUtil::go_to_entry (size_t entry)
Loads the entry from the input larlite tree (via larlite::storage_manager object)
Parameters
[in] entry Entry number in TChain (or TTree).
Definition at line 57 of file DLCosmicTagUtil.cxx.
References _entry, _intime_larflowcluster_producername, _intime_pixelmask_producername_v, fEntryLoaded, get_data(), io(), LARCV_DEBUG, LARCV_ERROR, m_larflowcluster_v, and m_pixelmask_vv.
{
     // load entry
     io().go_to( entry );
     _entry = io().get_index();
     // get data objects for the entry
     m_larflowcluster_v = (larlite::event_larflowcluster*)get_data( larlite::data::kLArFlowCluster,
                                   _intime_larflowcluster_producername );
     m_pixelmask_vv.resize( _intime_pixelmask_producername_v.size(), nullptr );
     for ( size_t iproducer=0; iproducer<_intime_pixelmask_producername_v.size(); iproducer++ ) {
       m_pixelmask_vv[iproducer] = (larlite::event_pixelmask*) get_data( larlite::data::kPixelMask,
                                     _intime_pixelmask_producername_v[iproducer] );
     }
     // make sure the products are as expected
     size_t nclusters = m_larflowcluster_v->size();
     if ( nclusters!=m_pixelmask_vv.front()->size() ) {
       LARCV_ERROR() << "Number of larflowclusters and pixelmasks in the entry (" << _entry << ") do not match."
             << " clusters=" << nclusters
             << " pixelmasks=" << m_pixelmask_vv.front()->size()
             << std::endl;
     }
     for ( auto const& pevent_pixelmask : m_pixelmask_vv ) {
       if ( pevent_pixelmask->size()!=nclusters ) {
     LARCV_ERROR() << "Pixelmasks in entry don't agree across planes. " << nclusters
               << " vs " << pevent_pixelmask->size() << std::endl;
       }
     }
     LARCV_DEBUG() << "Loaded " << m_larflowcluster_v->size() << " larflowclusters and pixelmasks" << std::endl;
     fEntryLoaded = true;
   }
io()
larlite::storage_manager& larcv::DLCosmicTagUtil::io () inline
get the io manager (providing mutable instance)
Definition at line 41 of file DLCosmicTagUtil.h.
References _io, getNumClusters(), and metaFromPixelMask().
Referenced by go_to_entry().
 { return (*_io); };
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
makeClusterTaggedImages()
std::vector< larcv::Image2D > larcv::DLCosmicTagUtil::makeClusterTaggedImages (const std::vector< larcv::Image2D > & adc_view_v) const
within the region defined by the input images, tag the pixels with the cluster IDs
Make images where cluster instances are marked.
Same indices are used across planes for 2D matching. The ID used is simply the index of the cluster as ordered in the event container. It is expected that entry has been loaded using
See also
DLCosmicTagUtil::go_to_entry
Parameters
[in] adc_view_v Input vector of ADC images
Returns
vector of tagged images
Definition at line 256 of file DLCosmicTagUtil.cxx.
References larcv::ImageMeta::col(), larcv::ImageMeta::contains(), fEntryLoaded, LARCV_ERROR, m_larflowcluster_v, m_pixelmask_vv, larcv::Image2D::meta(), larcv::Image2D::paint(), larcv::ImageMeta::row(), and larcv::Image2D::set_pixel().
{
     // check proper condition of class
     if ( !fEntryLoaded )
       LARCV_ERROR() << "Entry has not been loaded yet." << std::endl;
     // the numbers of planes should match
     if ( adc_view_v.size()!=m_pixelmask_vv.size() ) {
       LARCV_ERROR() << "Number of input ADC plane images (" << adc_view_v.size() << ") "
             << "does not match with the number of pixelmask planes (" << m_pixelmask_vv.size() << ")"
             << std::endl;
     }
     // create blank copies of the input images
     std::vector< larcv::Image2D > img_v;
     for ( auto const& img : adc_view_v ) {
       larcv::Image2D blank( img.meta() );
       blank.paint(0.0);
       img_v.emplace_back( std::move(blank) );
     }
     // if we have no clusters, we provide an empty mask
     if ( m_larflowcluster_v->size()==0 )
       return img_v;
     // now mask+tag. we tag only those pixels from the pixel masks.
     size_t nplanes = adc_view_v.size();
     for ( size_t iplane=0; iplane<nplanes; iplane++ ) {
       // get the input image and the output masked image
       const larcv::Image2D& adcimg = adc_view_v.at(iplane);
       const larcv::ImageMeta& adcmeta = adcimg.meta();
       larcv::Image2D& masked = img_v.at(iplane);
       // loop over the pixelmask objects for this plane
       auto const& pevent_pixelmask = m_pixelmask_vv.at(iplane);
       for ( int icluster=0; icluster<(int)pevent_pixelmask->size(); icluster++ ) {
     auto const& mask = pevent_pixelmask->at(icluster);
     // for each point, check if inside input image meta
     // if so, copy adc value to output
     for ( int ipt=0; ipt<mask.len(); ipt++ ) {
       std::vector<float> xy = mask.point(ipt);
       if ( ! adcmeta.contains( xy[0], xy[1] ) )
         continue;
       int adccol = adcmeta.col( xy[0] );
       int adcrow = adcmeta.row( xy[1] );
       masked.set_pixel( adcrow, adccol, icluster );
     }
       }
     }
     return img_v;
   }
makeCosmicMaskedImage()
std::vector< larcv::Image2D > larcv::DLCosmicTagUtil::makeCosmicMaskedImage (const std::vector< larcv::Image2D > & adc_view_v) const
within the region defined by the input images, provide a masked adc image
Mask the input image with the pixel masks from the entry.
It is expected that entry has been loaded using
See also
DLCosmicTagUtil::go_to_entry
Parameters
[in] mask Input vector of ADC images
Returns
vector of masked ADC images
Definition at line 190 of file DLCosmicTagUtil.cxx.
References larcv::ImageMeta::col(), larcv::ImageMeta::contains(), fEntryLoaded, LARCV_DEBUG, LARCV_ERROR, m_larflowcluster_v, m_pixelmask_vv, larcv::Image2D::meta(), larcv::Image2D::paint(), larcv::Image2D::pixel(), larcv::ImageMeta::row(), and larcv::Image2D::set_pixel().
{
     // check proper condition of class
     if ( !fEntryLoaded )
       LARCV_ERROR() << "Entry has not been loaded yet." << std::endl;
     // the numbers of planes should match
     if ( adc_view_v.size()!=m_pixelmask_vv.size() ) {
       LARCV_ERROR() << "Number of input ADC plane images (" << adc_view_v.size() << ") "
             << "does not match with the number of pixelmask planes (" << m_pixelmask_vv.size() << ")"
             << std::endl;
     }
     // create blank copies of the input images
     std::vector< larcv::Image2D > img_v;
     for ( auto const& img : adc_view_v ) {
       larcv::Image2D blank( img.meta() );
       blank.paint(0.0);
       img_v.emplace_back( std::move(blank) );
     }
     // if we have no clusters, we provide an empty mask
     if ( m_larflowcluster_v->size()==0 )
       return img_v;
     // now mask. we transfer only those pixels from the pixel masks.
     size_t nplanes = adc_view_v.size();
     for ( size_t iplane=0; iplane<nplanes; iplane++ ) {
       // get the input image and the output masked image
       const larcv::Image2D&   adcimg  = adc_view_v.at(iplane);
       const larcv::ImageMeta& adcmeta = adcimg.meta();
       larcv::Image2D& masked = img_v.at(iplane);
       // loop over the pixelmask objects for this plane
       auto const& pevent_pixelmask = m_pixelmask_vv.at(iplane);
       for ( auto const& mask : *pevent_pixelmask ) {
     // for each point, check if inside input image meta
     // if so, copy adc value to output
     LARCV_DEBUG() << "Masking image on plane=" << iplane << " with " << mask.len() << " pixels" << std::endl;
     for ( int ipt=0; ipt<mask.len(); ipt++ ) {
       std::vector<float> xy = mask.point(ipt);
       if ( ! adcmeta.contains( xy[0], xy[1] ) )
         continue;
       int adccol = adcmeta.col( xy[0] );
       int adcrow = adcmeta.row( xy[1] );
       masked.set_pixel( adcrow, adccol, adcimg.pixel( adcrow, adccol ) );
     }
       }
     }
     return img_v;
   }
makeIntimeCroppedImage()
std::vector< larcv::Image2D > larcv::DLCosmicTagUtil::makeIntimeCroppedImage (const std::vector< larcv::Image2D > & adc_wholeview_v, const int padding = 10) const
use the intime cluster objects to form a crop within the wholeview image
Provide a cropped image around the intime pixelmask It is expected that entry has been loaded using.
See also
DLCosmicTagUtil::go_to_entry
Parameters
[in] adc_wholeview_v Input images with ADC values to crop from.
[in] padding Number of pixels to add around mask. Default is 10.
Returns
vector of cropped images; entries align with input images.
Definition at line 123 of file DLCosmicTagUtil.cxx.
References larcv::ImageMeta::contains(), fEntryLoaded, larcv::ImageMeta::inclusive(), LARCV_ERROR, m_larflowcluster_v, m_pixelmask_vv, metaFromPixelMask(), and larcv::ImageMeta::overlap().
{
     // check proper condition of class
     if ( !fEntryLoaded )
       LARCV_ERROR() << "Entry has not been loaded yet." << std::endl;
     // the numbers of planes should match
     if ( adc_wholeview_v.size()!=m_pixelmask_vv.size() ) {
       LARCV_ERROR() << "Number of input ADC plane images (" << adc_wholeview_v.size() << ") "
             << "does not match with the number of pixelmask planes (" << m_pixelmask_vv.size() << ")"
             << std::endl;
     }
     // the output vector
     std::vector< larcv::Image2D > img_v;
     //return empty vector if no clusters
     if ( m_larflowcluster_v->size()==0 )
       return img_v;
     // we get the bounding boxes from each of the pixelmasks and form a axis-aligned union bounding box
     // the bounding boxes are represented by the image2d imagemeta class
     std::vector< larcv::ImageMeta > meta_v;
     // setup the first meta(s)
     size_t plane = 0;
     for ( auto const& pevent_pixelmask : m_pixelmask_vv ) {
       auto const& mask = pevent_pixelmask->front();
       larcv::ImageMeta meta = DLCosmicTagUtil::metaFromPixelMask( mask, plane );
       meta_v.emplace_back( std::move(meta) );
     }
     // now loop through the rest of the masks, updating the imagemeta
     for ( plane=0; plane<m_pixelmask_vv.size(); plane++ ) {
       size_t nclusters = m_pixelmask_vv[plane]->size();
       for ( size_t icluster=1; icluster<nclusters; icluster++ ) {
     auto const& mask = (*m_pixelmask_vv[plane])[icluster];
     larcv::ImageMeta cluster_meta = DLCosmicTagUtil::metaFromPixelMask( mask, plane );
     larcv::ImageMeta& union_meta  = meta_v.at(plane);
     union_meta = union_meta.inclusive( cluster_meta );
       }
     }
     // now that we have union metas for each plane, crop out the regions
     // if for some reason we extend outside the range, we make an intersection box
     for ( plane=0; plane<m_pixelmask_vv.size(); plane++ ) {
       larcv::ImageMeta& unionmeta = meta_v.at(plane);
       const larcv::ImageMeta& adcmeta = adc_wholeview_v.at(plane).meta();
       if ( !adcmeta.contains( unionmeta ) ) {
     unionmeta = unionmeta.overlap( adcmeta );
       }
       // make crop
       larcv::Image2D crop = adc_wholeview_v.at(plane).crop( unionmeta );
       img_v.emplace_back( std::move(crop) );
     }
     return img_v;
   }
metaFromPixelMask()
larcv::ImageMeta larcv::DLCosmicTagUtil::metaFromPixelMask (const larlite::pixelmask & mask, unsigned int planeid = 0) static
utility to make larcv::imagemeta from larlite::pixelmask
Parameters
[in] mask Input PixelMask.
[in] plane PlaneID to be assigned to output imagemeta.
Returns
ImageMeta representing bounding box around pixels in pixelmask.
Definition at line 323 of file DLCosmicTagUtil.cxx.
Referenced by io(), and makeIntimeCroppedImage().
{
     std::vector<float> bbox = mask.as_vector_bbox();
     // pixel coordinate height and widths
     float width  = bbox[2]-bbox[0];
     float height = bbox[3]-bbox[1];
     // origin for larcv1 is (minx, maxy)
     larcv::ImageMeta meta( width, height, mask.rows(), mask.cols(),
                bbox[0], bbox[3], (larcv::PlaneID_t)planeid );
     return meta;
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_entry
size_t larcv::DLCosmicTagUtil::_entry protected
Definition at line 57 of file DLCosmicTagUtil.h.
Referenced by go_to_entry().
_intime_larflowcluster_producername
std::string larcv::DLCosmicTagUtil::_intime_larflowcluster_producername protected
Definition at line 54 of file DLCosmicTagUtil.h.
Referenced by Configure(), and go_to_entry().
_intime_pixelmask_producername_v
std::vector<std::string> larcv::DLCosmicTagUtil::_intime_pixelmask_producername_v protected
Definition at line 53 of file DLCosmicTagUtil.h.
Referenced by Configure(), and go_to_entry().
_io
larlite::storage_manager* larcv::DLCosmicTagUtil::_io protected
Definition at line 58 of file DLCosmicTagUtil.h.
Referenced by Configure(), get_data(), io(), and ~DLCosmicTagUtil().
_larlite_input_filename
std::string larcv::DLCosmicTagUtil::_larlite_input_filename protected
Definition at line 52 of file DLCosmicTagUtil.h.
Referenced by Configure().
fEntryLoaded
bool larcv::DLCosmicTagUtil::fEntryLoaded protected
Definition at line 61 of file DLCosmicTagUtil.h.
Referenced by getNumClusters(), go_to_entry(), makeClusterTaggedImages(), makeCosmicMaskedImage(), and makeIntimeCroppedImage().
m_larflowcluster_v
const larlite::event_larflowcluster* larcv::DLCosmicTagUtil::m_larflowcluster_v protected
Definition at line 59 of file DLCosmicTagUtil.h.
Referenced by getNumClusters(), go_to_entry(), makeClusterTaggedImages(), makeCosmicMaskedImage(), and makeIntimeCroppedImage().
m_pixelmask_vv
std::vector<const larlite::event_pixelmask*> larcv::DLCosmicTagUtil::m_pixelmask_vv protected
Definition at line 60 of file DLCosmicTagUtil.h.
Referenced by go_to_entry(), makeClusterTaggedImages(), makeCosmicMaskedImage(), and makeIntimeCroppedImage().
The documentation for this class was generated from the following files:
DLCosmicTagUtil.h
DLCosmicTagUtil.cxx