LArCV: larcv::PyImageStitcherProcessFactory Class Reference
larcv::PyImageStitcherProcessFactory Class Reference
#include <PyImageStitcher.h>
Public Member Functions
PyImageStitcherProcessFactory ()
ctor
~PyImageStitcherProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 71 of file PyImageStitcher.h.
Constructor & Destructor Documentation
PyImageStitcherProcessFactory()
larcv::PyImageStitcherProcessFactory::PyImageStitcherProcessFactory () inline
ctor
Definition at line 74 of file PyImageStitcher.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("PyImageStitcher",this); }
~PyImageStitcherProcessFactory()
larcv::PyImageStitcherProcessFactory::~PyImageStitcherProcessFactory () inline
dtor
Definition at line 76 of file PyImageStitcher.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::PyImageStitcherProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 78 of file PyImageStitcher.h.
References larcv::PyImageStitcher::PyImageStitcher().
 { return new PyImageStitcher(instance_name); }
The documentation for this class was generated from the following file:
PyImageStitcher.h