LArCV: larlite::ChStatusFinder Class Reference
larlite::ChStatusFinder Class Reference
User custom analysis class made by SHELL_USER_NAME.
#include <ChStatusFinder.h>
Public Member Functions
ChStatusFinder ()
Default constructor.
virtual ~ChStatusFinder ()
Default destructor.
virtual bool initialize ()
IMPLEMENT in ChStatusFinder.cc! Initialization method to be called before the analysis event loop.
virtual bool analyze (storage_manager *storage)
IMPLEMENT in ChStatusFinder.cc! Analyze a data event-by-event.
virtual bool finalize ()
IMPLEMENT in ChStatusFinder.cc! Finalize method to be called after all events processed.
Public Attributes
size_t _num_entries
std::string _in_producer
std::string _out_producer
larcv::IOManager _io
Detailed Description
User custom analysis class made by SHELL_USER_NAME.
Definition at line 25 of file ChStatusFinder.h.
Constructor & Destructor Documentation
ChStatusFinder()
larlite::ChStatusFinder::ChStatusFinder () inline
Default constructor.
Definition at line 30 of file ChStatusFinder.h.
 : _io(larcv::IOManager::kREAD) { _name="ChStatusFinder"; _fout=0;}
~ChStatusFinder()
virtual larlite::ChStatusFinder::~ChStatusFinder () inline virtual
Default destructor.
Definition at line 33 of file ChStatusFinder.h.
References analyze(), finalize(), and initialize().
 {}
Member Function Documentation
analyze()
bool larlite::ChStatusFinder::analyze (storage_manager * storage) virtual
IMPLEMENT in ChStatusFinder.cc! Analyze a data event-by-event.
Definition at line 22 of file ChStatusFinder.cxx.
References _in_producer, _io, _num_entries, _out_producer, larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::kProductChStatus, and larcv::IOManager< T >::read_entry().
Referenced by ~ChStatusFinder().
{
     static size_t entry=0;
     _io.read_entry(entry);
     auto in_chstatus = (::larcv::EventChStatus*)(_io.get_data(::larcv::kProductChStatus,_in_producer));
     auto out_chstatus = storage->get_data<event_chstatus>(_out_producer);
     storage->set_id(in_chstatus->run(),in_chstatus->subrun(),in_chstatus->event());
     for(auto const& plane_status : in_chstatus->ChStatusMap()) {
       ::larlite::chstatus status;
       ::larlite::geo::PlaneID pid(0,0,plane_status.first);
       status.set_status(pid,plane_status.second.as_vector());
       out_chstatus->emplace_back(std::move(status));
     }
     entry++;
     if(entry == _num_entries) {
       _io.finalize();
       throw DataFormatException("Finished");
     }
     return true;
   }
finalize()
bool larlite::ChStatusFinder::finalize () virtual
IMPLEMENT in ChStatusFinder.cc! Finalize method to be called after all events processed.
Definition at line 53 of file ChStatusFinder.cxx.
Referenced by ~ChStatusFinder().
{
     // This function is called at the end of event loop.
     // Do all variable finalization you wish to do here.
     // If you need, you can store your ROOT class instance in the output
     // file. You have an access to the output file through "_fout" pointer.
     //
     // Say you made a histogram pointer h1 to store. You can do this:
     //
     // if(_fout) { _fout->cd(); h1->Write(); }
     //
     // else
     //   print(MSG::ERROR,__FUNCTION__,"Did not find an output file pointer!!! File not opened?");
     //
     return true;
   }
initialize()
bool larlite::ChStatusFinder::initialize () virtual
IMPLEMENT in ChStatusFinder.cc! Initialization method to be called before the analysis event loop.
Definition at line 10 of file ChStatusFinder.cxx.
References _in_producer, _io, _num_entries, _out_producer, larcv::IOManager< T >::get_n_entries(), and larcv::IOManager< T >::initialize().
Referenced by ~ChStatusFinder().
{
     _io.initialize();
     _num_entries = _io.get_n_entries();
     if(_out_producer.empty()) throw DataFormatException("Output producer forgotten...");
     if(_in_producer.empty()) throw DataFormatException("Input producer forgotten...");
     return true;
   }
Member Data Documentation
_in_producer
std::string larlite::ChStatusFinder::_in_producer
Definition at line 51 of file ChStatusFinder.h.
Referenced by analyze(), and initialize().
_io
larcv::IOManager larlite::ChStatusFinder::_io
Definition at line 53 of file ChStatusFinder.h.
Referenced by analyze(), and initialize().
_num_entries
size_t larlite::ChStatusFinder::_num_entries
Definition at line 50 of file ChStatusFinder.h.
Referenced by analyze(), and initialize().
_out_producer
std::string larlite::ChStatusFinder::_out_producer
Definition at line 52 of file ChStatusFinder.h.
Referenced by analyze(), and initialize().
The documentation for this class was generated from the following files:
ChStatusFinder.h
ChStatusFinder.cxx