LArCV: supera::ParamsROI Class Reference
supera::ParamsROI Class Reference
User defined class ParamsROI ...
#include <ParamsROI.h>
Public Member Functions
ParamsROI ()
Default constructor.
~ParamsROI ()
Default destructor.
void configure (const supera::Config_t &)
const std::string & OutROILabel () const
Private Attributes
std::string _out_roi_producer
Detailed Description
User defined class ParamsROI ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file ParamsROI.h.
Constructor & Destructor Documentation
ParamsROI()
supera::ParamsROI::ParamsROI () inline
Default constructor.
Definition at line 31 of file ParamsROI.h.
 {}
~ParamsROI()
supera::ParamsROI::~ParamsROI () inline
Default destructor.
Definition at line 34 of file ParamsROI.h.
References configure().
 {}
Member Function Documentation
configure()
void supera::ParamsROI::configure (const supera::Config_t & cfg)
Definition at line 8 of file ParamsROI.cxx.
References _out_roi_producer, and larcv::PSet::get().
Referenced by larcv::SuperaMCROI::configure(), and ~ParamsROI().
   {
     _out_roi_producer = cfg.get<std::string>("OutROILabel","");
   }
OutROILabel()
const std::string& supera::ParamsROI::OutROILabel () const inline
Definition at line 41 of file ParamsROI.h.
References _out_roi_producer.
Referenced by larcv::SuperaMCPCluster::process(), and larcv::SuperaMCROI::process().
 { return _out_roi_producer;      }
Member Data Documentation
_out_roi_producer
std::string supera::ParamsROI::_out_roi_producer private
Definition at line 45 of file ParamsROI.h.
Referenced by configure(), and OutROILabel().
The documentation for this class was generated from the following files:
ParamsROI.h
ParamsROI.cxx