LArCV: larcv::OperateImageProcessFactory Class Reference
larcv::OperateImageProcessFactory Class Reference
#include <OperateImage.h>
Public Member Functions
OperateImageProcessFactory ()
ctor
~OperateImageProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 55 of file OperateImage.h.
Constructor & Destructor Documentation
OperateImageProcessFactory()
larcv::OperateImageProcessFactory::OperateImageProcessFactory () inline
ctor
Definition at line 58 of file OperateImage.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("OperateImage",this); }
~OperateImageProcessFactory()
larcv::OperateImageProcessFactory::~OperateImageProcessFactory () inline
dtor
Definition at line 60 of file OperateImage.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::OperateImageProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 62 of file OperateImage.h.
References larcv::OperateImage::OperateImage().
 { return new OperateImage(instance_name); }
The documentation for this class was generated from the following file:
OperateImage.h