LArCV: supera::ImageMetaMaker Class Reference
supera::ImageMetaMaker Class Reference
User defined class ImageMetaMaker ...
#include <ImageMetaMaker.h>
Public Member Functions
ImageMetaMaker ()
Default constructor.
virtual ~ImageMetaMaker ()
Default destructor.
virtual void configure (const supera::Config_t &)
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
ImageMetaMakerBase * MetaMakerPtr ()
Static Private Member Functions
static ImageMetaMakerBase * SharedMetaMaker ()
static void SetSharedMetaMaker (ImageMetaMakerBase *ptr)
Private Attributes
ImageMetaMakerBase * _meta_maker
Static Private Attributes
static ImageMetaMakerBase * _shared_meta_maker = nullptr
Friends
class larcv::SuperaMetaMaker
Detailed Description
User defined class ImageMetaMaker ...
these comments are used to generate doxygen documentation!
Definition at line 30 of file ImageMetaMaker.h.
Constructor & Destructor Documentation
ImageMetaMaker()
supera::ImageMetaMaker::ImageMetaMaker () inline
Default constructor.
Definition at line 37 of file ImageMetaMaker.h.
                      : _meta_maker(nullptr)
     {}
~ImageMetaMaker()
virtual supera::ImageMetaMaker::~ImageMetaMaker () inline virtual
Default destructor.
Definition at line 41 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker, and larcv::SuperaMetaMaker::configure().
 { delete _meta_maker; }
Member Function Documentation
ColCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::ColCompressionFactor () const
Definition at line 36 of file ImageMetaMaker.cxx.
References _meta_maker, supera::ImageMetaMakerBase::ColCompressionFactor(), and SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->ColCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->ColCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
configure()
void supera::ImageMetaMaker::configure (const supera::Config_t & cfg) virtual
Reimplemented in larcv::SuperaMCROI, larcv::SuperaHit, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, and larcv::SuperaMCPCluster.
Definition at line 10 of file ImageMetaMaker.cxx.
References _meta_maker, and supera::CreateImageMetaMaker().
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::configure(), larcv::SuperaSimVoxel3D::configure(), larcv::SuperaKeyPointCluster::configure(), larcv::SuperaWire::configure(), larcv::SuperaHit::configure(), and larcv::SuperaMCROI::configure().
   {
     if(_meta_maker) delete _meta_maker;
     _meta_maker = supera::CreateImageMetaMaker(cfg);
   }
Meta()
const std::vector< larcv::ImageMeta > & supera::ImageMetaMaker::Meta () const
Definition at line 16 of file ImageMetaMaker.cxx.
References _meta_maker, supera::ImageMetaMakerBase::Meta(), and SharedMetaMaker().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
   {
     if(_meta_maker) return _meta_maker->Meta();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->Meta();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
MetaMakerPtr()
ImageMetaMakerBase* supera::ImageMetaMaker::MetaMakerPtr () inline
Definition at line 51 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker.
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
     { return _meta_maker; }
RowCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::RowCompressionFactor () const
Definition at line 26 of file ImageMetaMaker.cxx.
References _meta_maker, supera::ImageMetaMakerBase::RowCompressionFactor(), and SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->RowCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->RowCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
SetSharedMetaMaker()
static void supera::ImageMetaMaker::SetSharedMetaMaker (ImageMetaMakerBase * ptr) inline static private
Definition at line 60 of file ImageMetaMaker.h.
Referenced by larcv::SuperaMetaMaker::configure().
 { _shared_meta_maker = ptr; }
SharedMetaMaker()
static ImageMetaMakerBase* supera::ImageMetaMaker::SharedMetaMaker () inline static private
Definition at line 59 of file ImageMetaMaker.h.
Referenced by ColCompressionFactor(), Meta(), and RowCompressionFactor().
 { return _shared_meta_maker; }
Friends And Related Function Documentation
larcv::SuperaMetaMaker
friend class larcv::SuperaMetaMaker friend
Definition at line 32 of file ImageMetaMaker.h.
Member Data Documentation
_meta_maker
ImageMetaMakerBase* supera::ImageMetaMaker::_meta_maker private
Definition at line 56 of file ImageMetaMaker.h.
Referenced by ColCompressionFactor(), configure(), Meta(), and RowCompressionFactor().
_shared_meta_maker
ImageMetaMakerBase * supera::ImageMetaMaker::_shared_meta_maker = nullptr static private
Definition at line 58 of file ImageMetaMaker.h.
The documentation for this class was generated from the following files:
ImageMetaMaker.h
ImageMetaMaker.cxx