LArCV: larcv::Pixel2DCluster Class Reference
larcv::Pixel2DCluster Class Reference
User defined class Pixel2DCluster ...
#include <Pixel2DCluster.h>
Public Member Functions
Pixel2DCluster ()
Default constructor.
Pixel2DCluster (std::vector< larcv::Pixel2D > &&rhs)
Alternative constructor 1.
Pixel2DCluster (const std::vector< larcv::Pixel2D > &rhs)
Alternative constructor 2.
~Pixel2DCluster ()
Default destructor.
double Intensity () const
size_t ID () const
void Pool (const PoolType_t type)
float min_x () const
float min_y () const
float max_x () const
float max_y () const
size_t argmin_x () const
size_t argmin_y () const
size_t argmax_x () const
size_t argmax_y () const
ImageMeta bounds () const
float min () const
float max () const
float std () const
float mean () const
size_t argmax () const
size_t argmin () const
Pixel2DCluster & operator+= (const Pixel2D &rhs)
Pixel2DCluster & operator+= (const Pixel2DCluster &rhs)
Public Attributes
T elements
STL member.
Private Attributes
size_t _id
Friends
class EventPixel2D
Detailed Description
User defined class Pixel2DCluster ...
these comments are used to generate doxygen documentation!
Definition at line 30 of file Pixel2DCluster.h.
Constructor & Destructor Documentation
Pixel2DCluster() [1/3]
larcv::Pixel2DCluster::Pixel2DCluster () inline
Default constructor.
Definition at line 37 of file Pixel2DCluster.h.
Referenced by Pool().
       : std::vector<larcv::Pixel2D>() {}
Pixel2DCluster() [2/3]
larcv::Pixel2DCluster::Pixel2DCluster (std::vector< larcv::Pixel2D > && rhs) inline
Alternative constructor 1.
Definition at line 40 of file Pixel2DCluster.h.
       : std::vector<larcv::Pixel2D>(std::move(rhs)) {}
Pixel2DCluster() [3/3]
larcv::Pixel2DCluster::Pixel2DCluster (const std::vector< larcv::Pixel2D > & rhs) inline
Alternative constructor 2.
Definition at line 43 of file Pixel2DCluster.h.
       : std::vector<larcv::Pixel2D>(rhs) {}
~Pixel2DCluster()
larcv::Pixel2DCluster::~Pixel2DCluster () inline
Default destructor.
Definition at line 46 of file Pixel2DCluster.h.
 {}
Member Function Documentation
argmax()
size_t larcv::Pixel2DCluster::argmax () const
Definition at line 86 of file Pixel2DCluster.cxx.
Referenced by ID(), and max().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  max_q   = std::numeric_limits<float>::max();
     size_t max_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx)
       if( (*this)[idx].Intensity() < max_q ) max_idx = idx;
     return max_idx;
   }
argmax_x()
size_t larcv::Pixel2DCluster::argmax_x () const
Definition at line 43 of file Pixel2DCluster.cxx.
References max_x().
Referenced by ID(), and max_x().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  max_x   = std::numeric_limits<float>::min();
     size_t max_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx) {
       if( (*this)[idx].X() > max_x ) {
     max_idx = idx;
     max_x = (*this)[idx].X();
       }
     }
     return max_idx;
   }
argmax_y()
size_t larcv::Pixel2DCluster::argmax_y () const
Definition at line 55 of file Pixel2DCluster.cxx.
References max_y().
Referenced by ID(), and max_y().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  max_y   = std::numeric_limits<float>::min();
     size_t max_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx) {
       if( (*this)[idx].Y() > max_y ) {
     max_idx = idx;
     max_y = (*this)[idx].Y();
       }
     }
     return max_idx;
   }
argmin()
size_t larcv::Pixel2DCluster::argmin () const
Definition at line 94 of file Pixel2DCluster.cxx.
Referenced by ID(), and min().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  min_q   = std::numeric_limits<float>::max();
     size_t min_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx)
       if( (*this)[idx].Intensity() < min_q ) min_idx = idx;
     return min_idx;
   }
argmin_x()
size_t larcv::Pixel2DCluster::argmin_x () const
Definition at line 19 of file Pixel2DCluster.cxx.
References min_x().
Referenced by ID(), and min_x().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  min_x   = std::numeric_limits<float>::max();
     size_t min_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx) {
       if( (*this)[idx].X() < min_x ) {
     min_idx = idx;
     min_x = (*this)[idx].X();
       }
     }
     return min_idx;
   }
argmin_y()
size_t larcv::Pixel2DCluster::argmin_y () const
Definition at line 31 of file Pixel2DCluster.cxx.
References min_y().
Referenced by ID(), and min_y().
   { if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     float  min_y   = std::numeric_limits<float>::max();
     size_t min_idx = std::numeric_limits<size_t>::max();
     for(size_t idx = 0; idx < this->size(); ++idx) {
           if( (*this)[idx].Y() < min_y ) {
     min_idx = idx;
     min_y = (*this)[idx].Y();
       }
     }
     return min_idx;
   }
bounds()
ImageMeta larcv::Pixel2DCluster::bounds () const
Definition at line 103 of file Pixel2DCluster.cxx.
References larcv::kINVALID_PLANE, max_x(), max_y(), min_x(), and min_y().
Referenced by ID().
   {
     if(this->empty()) throw larbys("Empty Pixel2DCluster!");
     size_t max_x = 0;
     size_t min_x = std::numeric_limits<size_t>::max();
     size_t max_y = 0;
     size_t min_y = std::numeric_limits<size_t>::max();
     for(auto const& px : (*this)) {
       if(px.X() > max_x) max_x = px.X();
       if(px.X() < min_x) min_x = px.X();
       if(px.Y() > max_y) max_y = px.Y();
       if(px.Y() < min_y) min_y = px.Y();
     }
     return ImageMeta(max_x - min_x, max_y - min_y,
              max_y - min_y, max_x - min_x,
              min_x, max_y,
              kINVALID_PLANE);
   }
ID()
size_t larcv::Pixel2DCluster::ID () const inline
Definition at line 56 of file Pixel2DCluster.h.
References _id, argmax(), argmax_x(), argmax_y(), argmin(), argmin_x(), argmin_y(), bounds(), max(), max_x(), max_y(), mean(), min(), min_x(), min_y(), Pool(), and std().
     { return _id; }
Intensity()
double larcv::Pixel2DCluster::Intensity () const inline
Definition at line 49 of file Pixel2DCluster.h.
Referenced by Pool().
     { double res = 0.;
       for(auto const& px : (*this)) { res += px.Intensity(); }
       return res;
     }
max()
float larcv::Pixel2DCluster::max () const
Definition at line 70 of file Pixel2DCluster.cxx.
References argmax().
Referenced by ID().
   { return (*this)[this->argmax()].Intensity(); }
max_x()
float larcv::Pixel2DCluster::max_x () const
Definition at line 15 of file Pixel2DCluster.cxx.
References argmax_x().
Referenced by argmax_x(), bounds(), larcv::cluster_to_image2d(), and ID().
   { return (*this)[this->argmax_x()].X(); }
max_y()
float larcv::Pixel2DCluster::max_y () const
Definition at line 17 of file Pixel2DCluster.cxx.
References argmax_y().
Referenced by argmax_y(), bounds(), larcv::cluster_to_image2d(), and ID().
   { return (*this)[this->argmax_y()].Y(); }
mean()
float larcv::Pixel2DCluster::mean () const
Definition at line 81 of file Pixel2DCluster.cxx.
Referenced by ID().
   { double sum=0;
     for(auto const& v : (*this)) sum += v.Intensity();
     return (float)(sum / (double)(this->size()));
   }
min()
float larcv::Pixel2DCluster::min () const
Definition at line 68 of file Pixel2DCluster.cxx.
References argmin().
Referenced by ID().
   { return (*this)[this->argmin()].Intensity(); }
min_x()
float larcv::Pixel2DCluster::min_x () const
Definition at line 11 of file Pixel2DCluster.cxx.
References argmin_x().
Referenced by argmin_x(), bounds(), larcv::cluster_to_image2d(), and ID().
   { return (*this)[this->argmin_x()].X(); }
min_y()
float larcv::Pixel2DCluster::min_y () const
Definition at line 13 of file Pixel2DCluster.cxx.
References argmin_y().
Referenced by argmin_y(), bounds(), larcv::cluster_to_image2d(), and ID().
   { return (*this)[this->argmin_y()].Y(); }
operator+=() [1/2]
Pixel2DCluster& larcv::Pixel2DCluster::operator+= (const Pixel2D & rhs) inline
Definition at line 83 of file Pixel2DCluster.h.
     { this->push_back(rhs); return (*this); }
operator+=() [2/2]
Pixel2DCluster& larcv::Pixel2DCluster::operator+= (const Pixel2DCluster & rhs) inline
Definition at line 85 of file Pixel2DCluster.h.
     { for(auto const& px : rhs) { (*this) += px; }; return (*this); }
Pool()
void larcv::Pixel2DCluster::Pool (const PoolType_t type)
Definition at line 122 of file Pixel2DCluster.cxx.
References Intensity(), larcv::kPoolAverage, larcv::kPoolMax, larcv::kPoolSum, and Pixel2DCluster().
Referenced by ID().
   {
     std::vector<larcv::Pixel2D> res;
     res.reserve(this->size());
     std::vector<float> unique_count;
     unique_count.reserve(this->size());
     std::map<larcv::Pixel2D,size_t> unique_map;
     for(auto const& px : *this) {
       auto iter = unique_map.find(px);
       if(iter == unique_map.end()) {
     unique_map[px] = res.size();
     unique_count.push_back(1.);
     res.push_back(px);
       }else{
     switch(type) {
     case kPoolMax:
       res[(*iter).second].Intensity(std::max( res[(*iter).second].Intensity() , px.Intensity() ));
       break;
     case kPoolSum:
     case kPoolAverage:
       res[(*iter).second].Intensity( res[(*iter).second].Intensity() + px.Intensity() );
       unique_count[(*iter).second] += 1.0;
       break;
     }
       }
     }
     if(type == kPoolAverage) {
       for(size_t i=0; i<res.size(); ++i)
     res[i].Intensity( res[i].Intensity() / unique_count[i] );
     }
     (*this) = Pixel2DCluster(std::move(res));
   }
std()
float larcv::Pixel2DCluster::std () const
Definition at line 72 of file Pixel2DCluster.cxx.
Referenced by ID().
   { double qmean=0;
     for(auto const& v : (*this)) qmean += v.Intensity();
     qmean /= (double)(this->size());
     double qstd=0;
     for(auto const& v : (*this)) qstd += pow(qmean - v.Intensity(),2);
     qstd /= (double)(this->size());
     return sqrt(qstd);
   }
Friends And Related Function Documentation
EventPixel2D
friend class EventPixel2D friend
Definition at line 32 of file Pixel2DCluster.h.
Member Data Documentation
_id
size_t larcv::Pixel2DCluster::_id private
Definition at line 90 of file Pixel2DCluster.h.
Referenced by ID().
elements
T std::vector< T >::elements inherited
STL member.
The documentation for this class was generated from the following files:
Pixel2DCluster.h
Pixel2DCluster.cxx