LArCV: larcv::ImageHolder Class Reference
larcv::ImageHolder Class Reference abstract
#include <ImageHolder.h>
Public Member Functions
ImageHolder (const std::string name="ImageHolder")
Default constructor.
virtual ~ImageHolder ()
Default destructor.
void move_pmt_image (Image2D &)
void move_tpc_image (std::vector< larcv::Image2D > &)
void move_tpc_segment (std::vector< larcv::Image2D > &)
void move_ch_status (std::map< larcv::PlaneID_t, larcv::ChStatus > &)
void move_roi (std::vector< larcv::ROI > &)
void retrieve_id (const EventBase *data)
size_t run () const
size_t subrun () const
size_t event () const
virtual void configure (const PSet &)=0
virtual void initialize ()=0
virtual bool process (IOManager &mgr)=0
virtual void finalize ()=0
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
size_t _run
size_t _subrun
size_t _event
std::vector< larcv::Image2D > _tpc_image_v
std::vector< larcv::Image2D > _tpc_segment_v
Image2D _pmt_image
std::map< ::larcv::PlaneID_t, larcv::ChStatus > _ch_status_m
std::vector< larcv::ROI > _roi_v
Detailed Description
Definition at line 29 of file ImageHolder.h.
Constructor & Destructor Documentation
ImageHolder()
larcv::ImageHolder::ImageHolder (const std::string name = "ImageHolder")
Default constructor.
Definition at line 8 of file ImageHolder.cxx.
References _event, _run, and _subrun.
     : ProcessBase(name)
   { _run = _subrun = _event = 0; }
~ImageHolder()
virtual larcv::ImageHolder::~ImageHolder () inline virtual
Default destructor.
Definition at line 37 of file ImageHolder.h.
References move_ch_status(), move_pmt_image(), move_roi(), move_tpc_image(), and move_tpc_segment().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
virtual void larcv::ProcessBase::configure (const PSet &) pure virtual inherited
Implemented in larcv::RSEFilter, larcv::ReadJarrettFile, larcv::hires::HiResImageDivider, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::LArbysImagePID, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::GoodcROIFilter, larcv::OperateImage, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::NuFilter, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::BadRegionAna, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LArbysImage, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by larcv::ProcessBase::_configure_(), and larcv::ProcessBase::~ProcessBase().
event()
size_t larcv::ImageHolder::event () const inline
Definition at line 50 of file ImageHolder.h.
References _event.
Referenced by larcv::ImageMerger::process().
 { return _event;  }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
virtual void larcv::ProcessBase::finalize () pure virtual inherited
Implemented in larcv::RSEFilter, larcv::TrackerEventDisplay, larcv::Run3DTracker, larcv::ReadJarrettFile, larcv::hires::HiResImageDivider, larcv::DatumFillerBase, larcv::ImageROICheckMC, larcv::PIDImageMaker, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::ReadRuiFile, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::GoodcROIFilter, larcv::OperateImage, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::NuFilter, larcv::WireMask, larcv::BadRegionAna, larcv::LArbysImageMC, larcv::LArbysImage, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by larcv::ProcessBase::~ProcessBase().
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
virtual void larcv::ProcessBase::initialize () pure virtual inherited
Implemented in larcv::RSEFilter, larcv::hires::HiResImageDivider, larcv::ReadJarrettFile, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::GoodcROIFilter, larcv::OperateImage, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::NuFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::BadRegionAna, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LArbysImage, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by larcv::ProcessBase::~ProcessBase().
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
move_ch_status()
void larcv::ImageHolder::move_ch_status (std::map< larcv::PlaneID_t, larcv::ChStatus > & dest)
Definition at line 21 of file ImageHolder.cxx.
References _ch_status_m.
Referenced by larcv::ImageMerger::process(), and ~ImageHolder().
   { dest = std::move(_ch_status_m); }
move_pmt_image()
void larcv::ImageHolder::move_pmt_image (Image2D & dest)
Definition at line 12 of file ImageHolder.cxx.
References _pmt_image.
Referenced by larcv::ImageMerger::process(), and ~ImageHolder().
   { dest = std::move(_pmt_image); }
move_roi()
void larcv::ImageHolder::move_roi (std::vector< larcv::ROI > & dest)
Definition at line 24 of file ImageHolder.cxx.
References _roi_v.
Referenced by larcv::ImageMerger::process(), and ~ImageHolder().
   { dest = std::move(_roi_v); }
move_tpc_image()
void larcv::ImageHolder::move_tpc_image (std::vector< larcv::Image2D > & dest)
Definition at line 15 of file ImageHolder.cxx.
References _tpc_image_v.
Referenced by larcv::ImageMerger::process(), and ~ImageHolder().
   { dest = std::move(_tpc_image_v); }
move_tpc_segment()
void larcv::ImageHolder::move_tpc_segment (std::vector< larcv::Image2D > & dest)
Definition at line 18 of file ImageHolder.cxx.
References _tpc_segment_v.
Referenced by larcv::ImageMerger::process(), and ~ImageHolder().
   { dest = std::move(_tpc_segment_v); }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
virtual bool larcv::ProcessBase::process (IOManager & mgr) pure virtual inherited
Implemented in larcv::RSEFilter, larcv::hires::HiResImageDivider, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::ReadJarrettFile, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::GoodcROIFilter, larcv::OperateImage, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::NuFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BadRegionAna, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImage, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by larcv::ProcessBase::_process_(), and larcv::ProcessBase::~ProcessBase().
retrieve_id()
void larcv::ImageHolder::retrieve_id (const EventBase * data) inline
Definition at line 45 of file ImageHolder.h.
References _event, _run, _subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::DataStream::process().
     { _run=data->run(); _subrun=data->subrun(); _event=data->event(); }
run()
size_t larcv::ImageHolder::run () const inline
Definition at line 48 of file ImageHolder.h.
References _run.
Referenced by larcv::ImageMerger::process().
 { return _run;    }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
subrun()
size_t larcv::ImageHolder::subrun () const inline
Definition at line 49 of file ImageHolder.h.
References _subrun.
Referenced by larcv::ImageMerger::process().
 { return _subrun; }
Member Data Documentation
_ch_status_m
std::map< ::larcv::PlaneID_t,larcv::ChStatus> larcv::ImageHolder::_ch_status_m protected
Definition at line 58 of file ImageHolder.h.
Referenced by move_ch_status(), and larcv::DataStream::process().
_event
size_t larcv::ImageHolder::_event protected
Definition at line 54 of file ImageHolder.h.
Referenced by event(), ImageHolder(), and retrieve_id().
_pmt_image
Image2D larcv::ImageHolder::_pmt_image protected
Definition at line 57 of file ImageHolder.h.
Referenced by move_pmt_image(), and larcv::DataStream::process().
_roi_v
std::vector<larcv::ROI> larcv::ImageHolder::_roi_v protected
Definition at line 59 of file ImageHolder.h.
Referenced by move_roi(), and larcv::DataStream::process().
_run
size_t larcv::ImageHolder::_run protected
Definition at line 54 of file ImageHolder.h.
Referenced by ImageHolder(), retrieve_id(), and run().
_subrun
size_t larcv::ImageHolder::_subrun protected
Definition at line 54 of file ImageHolder.h.
Referenced by ImageHolder(), retrieve_id(), and subrun().
_tpc_image_v
std::vector<larcv::Image2D> larcv::ImageHolder::_tpc_image_v protected
Definition at line 55 of file ImageHolder.h.
Referenced by move_tpc_image(), and larcv::DataStream::process().
_tpc_segment_v
std::vector<larcv::Image2D> larcv::ImageHolder::_tpc_segment_v protected
Definition at line 56 of file ImageHolder.h.
Referenced by move_tpc_segment(), and larcv::DataStream::process().
The documentation for this class was generated from the following files:
ImageHolder.h
ImageHolder.cxx