LArCV: larcv::ChStatus Class Reference
larcv::ChStatus Class Reference
User defined class ChStatus ...
#include <ChStatus.h>
Public Member Functions
ChStatus ()
Default constructor.
ChStatus (PlaneID_t plane, std::vector< short > &&data)
Status vector move ctor.
~ChStatus ()
Default destructor.
void Initialize (size_t nwires, short status=chstatus::kUNKNOWN)
Initialize instance (nullify status + set dimension)
void Reset (short status=chstatus::kUNKNOWN)
Set all channels' status to what's specified.
void Plane (PlaneID_t p)
Set plane id.
void Status (size_t wire, short status)
Set wire status.
PlaneID_t Plane () const
Plane getter.
short Status (size_t wire) const
Status getter.
const std::vector< short > & as_vector () const
Status vector const reference getter.
std::string dump () const
Status vector dumper.
Private Attributes
std::vector< short > _status_v
larcv::PlaneID_t _plane
Detailed Description
User defined class ChStatus ...
these comments are used to generate doxygen documentation!
Definition at line 25 of file ChStatus.h.
Constructor & Destructor Documentation
ChStatus() [1/2]
larcv::ChStatus::ChStatus () inline
Default constructor.
Definition at line 30 of file ChStatus.h.
References _plane, _status_v, Initialize(), larcv::chstatus::kUNKNOWN, Reset(), and ~ChStatus().
 {}
ChStatus() [2/2]
larcv::ChStatus::ChStatus (PlaneID_t plane, std::vector< short > && data) inline
Status vector move ctor.
Definition at line 34 of file ChStatus.h.
       : _status_v(std::move(data))
       , _plane(plane)
     {}
~ChStatus()
larcv::ChStatus::~ChStatus () inline
Default destructor.
Definition at line 40 of file ChStatus.h.
Referenced by ChStatus().
 {}
Member Function Documentation
as_vector()
const std::vector<short>& larcv::ChStatus::as_vector () const inline
Status vector const reference getter.
Definition at line 55 of file ChStatus.h.
References _status_v, and dump().
Referenced by larcv::WireMask::process().
 { return _status_v; }
dump()
std::string larcv::ChStatus::dump () const
Status vector dumper.
Definition at line 43 of file ChStatus.cxx.
References _plane, _status_v, and larcv::chstatus::kGOOD.
Referenced by as_vector().
   {
     std::stringstream ss;
     ss << "Plane " << _plane << " ... " << _status_v.size() << " wires:" << std::endl;
     for(size_t i=0; i<_status_v.size(); ++i) {
       if(_status_v[i] >= chstatus::kGOOD)
     ss << _status_v[i] << " ";
       else
     ss << "\033[93m" << _status_v[i] << "\033[00m ";
       if(i && (i+1)%50==0) ss << std::endl;
     }
     if(_status_v.size()%50)
       ss << std::endl;
     return ss.str();
   }
Initialize()
void larcv::ChStatus::Initialize (size_t nwires, short status = chstatus::kUNKNOWN)
Initialize instance (nullify status + set dimension)
Definition at line 10 of file ChStatus.cxx.
References _status_v, and Reset().
Referenced by ChStatus(), and larcv::SuperaChStatus::initialize().
   {
     _status_v.resize(nwires);
     Reset(init_status);
   }
Plane() [1/2]
void larcv::ChStatus::Plane (PlaneID_t p) inline
Set plane id.
Definition at line 47 of file ChStatus.h.
References _plane, and Status().
Referenced by larcv::SuperaChStatus::initialize(), and larcv::EventChStatus::Insert().
 { _plane = p; }
Plane() [2/2]
PlaneID_t larcv::ChStatus::Plane () const inline
Plane getter.
Definition at line 51 of file ChStatus.h.
References _plane, and Status().
 { return _plane; }
Reset()
void larcv::ChStatus::Reset (short status = chstatus::kUNKNOWN)
Set all channels' status to what's specified.
Definition at line 16 of file ChStatus.cxx.
References _status_v.
Referenced by ChStatus(), and Initialize().
   { for(auto& s : _status_v) s = init_status; }
Status() [1/2]
void larcv::ChStatus::Status (size_t wire, short status)
Set wire status.
Definition at line 19 of file ChStatus.cxx.
References _status_v.
Referenced by Plane().
   {
     if(wire >= _status_v.size()) {
       std::stringstream ss;
       ss << "<<ChStatus::" << __FUNCTION__ << ">>"
      << " Invalid wire requested (" << wire
      << " while currently registered # wires: " << _status_v.size() << ")";
       throw larbys(ss.str());
     }
     _status_v[wire] = status;
   }
Status() [2/2]
short larcv::ChStatus::Status (size_t wire) const
Status getter.
Definition at line 31 of file ChStatus.cxx.
References _status_v.
   {
     if(wire >= _status_v.size()) {
       std::stringstream ss;
       ss << "<<ChStatus::" << __FUNCTION__ << ">>"
      << " Invalid wire requested (" << wire
      << " while currently registered # wires: " << _status_v.size() << ")";
       throw larbys(ss.str());
     }
     return _status_v[wire];
   }
Member Data Documentation
_plane
larcv::PlaneID_t larcv::ChStatus::_plane private
Definition at line 61 of file ChStatus.h.
Referenced by ChStatus(), dump(), and Plane().
_status_v
std::vector<short> larcv::ChStatus::_status_v private
Definition at line 60 of file ChStatus.h.
Referenced by as_vector(), ChStatus(), dump(), Initialize(), Reset(), and Status().
The documentation for this class was generated from the following files:
ChStatus.h
ChStatus.cxx