LArCV: Supera Class Reference
Supera Class Reference
Public Member Functions
Supera (fhicl::ParameterSet const &p)
Supera (Supera const &)=delete
Supera (Supera &&)=delete
Supera & operator= (Supera const &)=delete
Supera & operator= (Supera &&)=delete
bool filter (art::Event &e) override
void beginJob ()
void endJob ()
const ::larcv::logger & logger () const
Private Attributes
::larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel > _core
::larcv::logger _logger
Detailed Description
Definition at line 40 of file Supera_module.cc.
Constructor & Destructor Documentation
Supera() [1/3]
Supera::Supera (fhicl::ParameterSet const & p) explicit
Definition at line 67 of file Supera_module.cc.
References _core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::configure().
 {
   _core.configure(main_cfg);
 }
Supera() [2/3]
Supera::Supera (Supera const &) delete
Supera() [3/3]
Supera::Supera (Supera &&) delete
Member Function Documentation
beginJob()
void Supera::beginJob ()
Definition at line 72 of file Supera_module.cc.
References _core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::initialize().
 {
   _core.initialize();
 }
endJob()
void Supera::endJob ()
Definition at line 77 of file Supera_module.cc.
References _core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::finalize().
 {
   _core.finalize();
 }
filter()
bool Supera::filter (art::Event & e) override
Definition at line 82 of file Supera_module.cc.
References _core, larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::clear_data(), larcv::chstatus::kNEGATIVEPEDESTAL, larcv::chstatus::kNOTPRESENT, larcv::supera::Nchannels(), supera::Nchannels(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::process_event(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_digit(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_generator(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_mcreco(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_opdigit(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_simch(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_wire(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_chstatus(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_id(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::store_chstatus(), and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::use_mc().
 {
   _core.clear_data();
   _core.set_id(e.id().run(),e.id().subRun(),e.id().event());
   art::Handle<std::vector<recob::Wire> > wire_h;
   e.getByLabel(_core.producer_wire(),wire_h);
   if(!wire_h.isValid()) { throw ::larcv::larbys("Could not load wire data!"); }
   art::Handle<std::vector<raw::OpDetWaveform> > opdigit_h;
   e.getByLabel(_core.producer_opdigit(),opdigit_h);
   if(!opdigit_h.isValid()) { throw ::larcv::larbys("Could not load opdigit data!"); }
   //
   // Fill Channel Status
   //
   if(_core.store_chstatus()) {
     std::vector<bool> filled_ch( ::larcv::supera::Nchannels(), false );
     // If specified check RawDigit pedestal value: if negative this channel is not used by wire (set status=>-2)
     if(!_core.producer_digit().empty()) {
       art::Handle<std::vector<raw::RawDigit> > digit_h;
       e.getByLabel(_core.producer_digit(),digit_h);
       for(auto const& digit : *digit_h) {
     auto const ch = digit.Channel();
     if(ch >= filled_ch.size()) throw ::larcv::larbys("Found RawDigit > possible channel number!");
     if(digit.GetPedestal()<0.) {
       _core.set_chstatus(ch,::larcv::chstatus::kNEGATIVEPEDESTAL);
       filled_ch[ch] = true;
     }
       }
     }
     // Set database status
     const lariov::ChannelStatusProvider& chanFilt = art::ServiceHandle<lariov::ChannelStatusService>()->GetProvider();
     for(size_t i=0; i < ::larcv::supera::Nchannels(); ++i) {
       if ( filled_ch[i] ) continue;
       if (!chanFilt.IsPresent(i)) _core.set_chstatus(i,::larcv::chstatus::kNOTPRESENT);
       else _core.set_chstatus(i,(short)(chanFilt.Status(i)));
     }
   }
   bool status=true;
   if(_core.use_mc()) {
     art::Handle<std::vector<simb::MCTruth> > mctruth_h;
     art::Handle<std::vector<sim::MCTrack>  > mctrack_h;
     art::Handle<std::vector<sim::MCShower> > mcshower_h;
     e.getByLabel(_core.producer_generator(), mctruth_h);
     e.getByLabel(_core.producer_mcreco(),    mctrack_h);
     e.getByLabel(_core.producer_mcreco(),    mcshower_h);
     if(!mctruth_h.isValid() || !mctrack_h.isValid() || !mcshower_h.isValid())
       throw ::larcv::larbys("Necessary MC info missing...");
     if(_core.producer_simch().empty()) {
       std::vector<sim::SimChannel> empty_simch;
       status = _core.process_event(*opdigit_h, *wire_h, *mctruth_h, *mctrack_h, *mcshower_h, empty_simch);
     }else{
       art::Handle<std::vector<sim::SimChannel> > simch_h;
       e.getByLabel(_core.producer_simch(), simch_h);
       if(!simch_h.isValid()) throw ::larcv::larbys("SimChannel requested but not available");
       status = _core.process_event(*opdigit_h, *wire_h, *mctruth_h, *mctrack_h, *mcshower_h, *simch_h);
     }
   }else{
     std::vector<simb::MCTruth>   empty_mctruth;
     std::vector<sim::MCTrack>    empty_mctrack;
     std::vector<sim::MCShower>   empty_mcshower;
     std::vector<sim::SimChannel> empty_simch;
     status = _core.process_event(*opdigit_h, *wire_h,empty_mctruth,empty_mctrack,empty_mcshower,empty_simch);
   }
   return status;
 }
logger()
const ::larcv::logger& Supera::logger () const inline
Definition at line 57 of file Supera_module.cc.
References _logger.
 { return _logger;}
operator=() [1/2]
Supera& Supera::operator= (Supera const &) delete
operator=() [2/2]
Supera& Supera::operator= (Supera &&) delete
Member Data Documentation
_core
::larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel> Supera::_core private
Definition at line 62 of file Supera_module.cc.
Referenced by beginJob(), endJob(), filter(), and Supera().
_logger
::larcv::logger Supera::_logger private
Definition at line 63 of file Supera_module.cc.
Referenced by logger().
The documentation for this class was generated from the following file:
Supera_module.cc