LArCV: supera::ParamsChStatus Class Reference
supera::ParamsChStatus Class Reference
User defined class ParamsChStatus ...
#include <ParamsChStatus.h>
Public Member Functions
ParamsChStatus ()
Default constructor.
~ParamsChStatus ()
Default destructor.
void configure (const supera::Config_t &)
const std::string & OutChStatusLabel () const
Private Attributes
std::string _out_chstatus_producer
Detailed Description
User defined class ParamsChStatus ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file ParamsChStatus.h.
Constructor & Destructor Documentation
ParamsChStatus()
supera::ParamsChStatus::ParamsChStatus () inline
Default constructor.
Definition at line 31 of file ParamsChStatus.h.
 {}
~ParamsChStatus()
supera::ParamsChStatus::~ParamsChStatus () inline
Default destructor.
Definition at line 34 of file ParamsChStatus.h.
References configure().
 {}
Member Function Documentation
configure()
void supera::ParamsChStatus::configure (const supera::Config_t & cfg)
Definition at line 8 of file ParamsChStatus.cxx.
References _out_chstatus_producer, and larcv::PSet::get().
Referenced by larcv::SuperaChStatus::configure(), and ~ParamsChStatus().
   {
     _out_chstatus_producer = cfg.get<std::string>("OutChStatusLabel", "");
   }
OutChStatusLabel()
const std::string& supera::ParamsChStatus::OutChStatusLabel () const inline
Definition at line 41 of file ParamsChStatus.h.
References _out_chstatus_producer.
Referenced by larcv::SuperaChStatus::process().
 { return _out_chstatus_producer; }
Member Data Documentation
_out_chstatus_producer
std::string supera::ParamsChStatus::_out_chstatus_producer private
Definition at line 45 of file ParamsChStatus.h.
Referenced by configure(), and OutChStatusLabel().
The documentation for this class was generated from the following files:
ParamsChStatus.h
ParamsChStatus.cxx