LArCV: larcv::ImageChargeAnaProcessFactory Class Reference
larcv::ImageChargeAnaProcessFactory Class Reference
#include <ImageChargeAna.h>
Public Member Functions
ImageChargeAnaProcessFactory ()
ctor
~ImageChargeAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 56 of file ImageChargeAna.h.
Constructor & Destructor Documentation
ImageChargeAnaProcessFactory()
larcv::ImageChargeAnaProcessFactory::ImageChargeAnaProcessFactory () inline
ctor
Definition at line 59 of file ImageChargeAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ImageChargeAna",this); }
~ImageChargeAnaProcessFactory()
larcv::ImageChargeAnaProcessFactory::~ImageChargeAnaProcessFactory () inline
dtor
Definition at line 61 of file ImageChargeAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ImageChargeAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 63 of file ImageChargeAna.h.
References larcv::ImageChargeAna::ImageChargeAna().
 { return new ImageChargeAna(instance_name); }
The documentation for this class was generated from the following file:
ImageChargeAna.h