LArCV: larcv::CosmicVertexAna Class Reference
larcv::CosmicVertexAna Class Reference
#include <CosmicVertexAna.h>
Public Member Functions
CosmicVertexAna (const std::string name="CosmicVertexAna")
Default constructor.
~CosmicVertexAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
LArbysImageMaker _LArbysImageMaker
TTree * _tree
int _run
int _subrun
int _event
int _entry
int _roid
int _vtxid
std::string _img2d_prod
std::string _pgraph_prod
std::string _pcluster_ctor_prod
std::string _pcluster_img_prod
std::string _reco_roi_prod
std::string _thrumu_img_prod
std::string _stopmu_img_prod
std::vector< int > _num_allpix_v
std::vector< int > _num_nottag_v
std::vector< int > _num_thrutag_v
std::vector< int > _num_stoptag_v
std::vector< int > _pts_in_raw_clus_v
std::vector< int > _pts_stopmu_ovrlap_v
std::vector< int > _pts_thrumu_ovrlap_v
std::vector< float > _endCos_v
ProductType_t _tags_datatype
Detailed Description
Definition at line 29 of file CosmicVertexAna.h.
Constructor & Destructor Documentation
CosmicVertexAna()
larcv::CosmicVertexAna::CosmicVertexAna (const std::string name = "CosmicVertexAna")
Default constructor.
Definition at line 28 of file CosmicVertexAna.cxx.
Referenced by larcv::CosmicVertexAnaProcessFactory::create().
                                                        :
     ProcessBase(name),
     _LArbysImageMaker(),
     _tree(nullptr)
   {}
~CosmicVertexAna()
larcv::CosmicVertexAna::~CosmicVertexAna () inline
Default destructor.
Definition at line 37 of file CosmicVertexAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::CosmicVertexAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 34 of file CosmicVertexAna.cxx.
References _img2d_prod, _LArbysImageMaker, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _reco_roi_prod, _stopmu_img_prod, _tags_datatype, _thrumu_img_prod, larcv::LArbysImageMaker::Configure(), larcv::PSet::get(), and LARCV_DEBUG.
Referenced by ~CosmicVertexAna().
   {
     _img2d_prod         = cfg.get<std::string>("Image2DProducer");
     _pgraph_prod        = cfg.get<std::string>("PGraphProducer");
     _pcluster_ctor_prod = cfg.get<std::string>("PxContourProducer");
     _pcluster_img_prod  = cfg.get<std::string>("PxImageProducer");
     _thrumu_img_prod = cfg.get<std::string>("ThruMuProducer");
     _stopmu_img_prod = cfg.get<std::string>("StopMuProducer");
     _reco_roi_prod      = cfg.get<std::string>("RecoROIProducer");
     auto tags_datatype  = cfg.get<size_t>("CosmicTagDataType");
     _tags_datatype = (ProductType_t) tags_datatype;
     _LArbysImageMaker.Configure(cfg.get<PSet>("LArbysImageMaker"));
     LARCV_DEBUG() << "Image2DProducer:  " << _img2d_prod << std::endl;
     LARCV_DEBUG() << "PGraphProducer:   " << _pgraph_prod << std::endl;
     LARCV_DEBUG() << "PxContouProducer: " << _pcluster_ctor_prod << std::endl;
     LARCV_DEBUG() << "PxImageProducer:  " << _pcluster_img_prod << std::endl;
     LARCV_DEBUG() << "RecoROIProducer:  " << _reco_roi_prod << std::endl;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::CosmicVertexAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 266 of file CosmicVertexAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~CosmicVertexAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::CosmicVertexAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 55 of file CosmicVertexAna.cxx.
References _endCos_v, _entry, _event, _num_allpix_v, _num_nottag_v, _num_stoptag_v, _num_thrutag_v, _pts_in_raw_clus_v, _pts_stopmu_ovrlap_v, _pts_thrumu_ovrlap_v, _roid, _run, _subrun, _tree, and _vtxid.
Referenced by ~CosmicVertexAna().
   {
     _tree = new TTree("CosmicVertexTree","");
     _tree->Branch("run"         , &_run       , "run/I"       );
     _tree->Branch("subrun"      , &_subrun    , "subrun/I"    );
     _tree->Branch("roid"        , &_roid      , "roid/I"      );
     _tree->Branch("vtxid"       , &_vtxid     , "vtxid/I"     );
     _tree->Branch("event"       , &_event     , "event/I"     );
     _tree->Branch("entry"       , &_entry     , "entry/I"     );
     _tree->Branch("num_nottag_v"        , &_num_nottag_v        );
     _tree->Branch("num_stoptag_v"       , &_num_stoptag_v       );
     _tree->Branch("num_thrutag_v"       , &_num_thrutag_v       );
     _tree->Branch("num_allpix_v"        , &_num_allpix_v        );
     _tree->Branch("pts_in_raw_clus_v"   , &_pts_in_raw_clus_v   );
     _tree->Branch("pts_stopmu_ovrlap_v" , &_pts_stopmu_ovrlap_v );
     _tree->Branch("pts_thrumu_ovrlap_v" , &_pts_thrumu_ovrlap_v );
     _tree->Branch("endCos_v"       , &_endCos_v       );
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::CosmicVertexAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 79 of file CosmicVertexAna.cxx.
References _endCos_v, _entry, _event, _img2d_prod, _LArbysImageMaker, _num_allpix_v, _num_nottag_v, _num_stoptag_v, _num_thrutag_v, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _pts_in_raw_clus_v, _pts_stopmu_ovrlap_v, _pts_thrumu_ovrlap_v, _reco_roi_prod, _roid, _run, _stopmu_img_prod, _subrun, _tags_datatype, _thrumu_img_prod, _tree, _vtxid, larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::crop_metas(), larcv::IOManager< T >::current_entry(), larcv::LArbysImageMaker::ExtractMat(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, larcv::EventPGraph::PGraphArray(), larcv::EventPixel2D::Pixel2DClusterArray(), larcv::Pixel2D::X(), and larcv::Pixel2D::Y().
Referenced by ~CosmicVertexAna().
   {
     bool has_reco_vtx = false;
     // Get Image2D vector
     auto const ev_img2d = (EventImage2D*)(mgr.get_data(kProductImage2D,_img2d_prod));
     if (!ev_img2d) throw larbys("Invalid image producer provided");
     //Get cROI vector
     auto const ev_croi_v     = (EventROI*)(mgr.get_data(kProductROI,_reco_roi_prod));
     if (!ev_croi_v) throw larbys("Invalid cROI producer provided");
     //Get pgraph vector
     EventPGraph* ev_pgraph = nullptr;
     if (!_pgraph_prod.empty()) {
       ev_pgraph = (EventPGraph*)(mgr.get_data(kProductPGraph,_pgraph_prod));
       if (!ev_pgraph) throw larbys("Invalid pgraph producer provided!");
       has_reco_vtx = true;
     }
     //Get countour vector
     EventPixel2D* ev_ctor_v = nullptr;
     if (!_pcluster_ctor_prod.empty()) {
       ev_ctor_v = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pcluster_ctor_prod));
       if (!ev_ctor_v) throw larbys("Invalid Contour Pixel2D producer provided!");
       if (!has_reco_vtx) throw larbys("Gave PGraph producer but no particle cluster?");
     }
     //Get cluster vector
     EventPixel2D* ev_pcluster_v = nullptr;
     if (!_pcluster_img_prod.empty()) {
       ev_pcluster_v = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pcluster_img_prod));
       if (!ev_pcluster_v) throw larbys("Invalid Particle Pixel2D producer provided!");
       if (!has_reco_vtx) throw larbys("Gave PGraph producer but no image cluster?");
     }
     //Convert pcluster vector to pcluster array
     const auto& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
     //Convert raw Image2D vector to Image2D Array
     const auto& adc_img2d_v = ev_img2d->Image2DArray();
     //Contruct thrumu and stopmu images
     std::vector<larcv::Image2D> thrumu_img2d_v;
     std::vector<larcv::Image2D> stopmu_img2d_v;
     _LArbysImageMaker.ConstructCosmicImage(mgr,_thrumu_img_prod,_tags_datatype,adc_img2d_v,thrumu_img2d_v);
     _LArbysImageMaker.ConstructCosmicImage(mgr,_stopmu_img_prod,_tags_datatype,adc_img2d_v,stopmu_img2d_v);
     //Create empty ROI vector with expected size of the cROI array, proceed to crop the
     //raw adc images to the ROIs
     std::vector<std::vector<ImageMeta> > roid_v;
     roid_v.reserve(ev_croi_v->ROIArray().size());
     for(auto const& croi : ev_croi_v->ROIArray()) {
       auto const& bb_v = croi.BB();
       roid_v.push_back(crop_metas(adc_img2d_v,bb_v));
     }
     auto num_verts = ev_pgraph->PGraphArray().size();
     _vtxid = -1;
     std::vector<size_t> plane_order_v = {2,0,1};
     for (int vtxID = 0; vtxID < num_verts; ++vtxID) {
       _num_allpix_v.clear();
       _num_allpix_v.resize(3,-1);
       _num_nottag_v.clear();
       _num_nottag_v.resize(3,-1);
       _num_thrutag_v.clear();
       _num_thrutag_v.resize(3,-1);
       _num_stoptag_v.clear();
       _num_stoptag_v.resize(3,-1);
       _pts_in_raw_clus_v.clear();
       _pts_in_raw_clus_v.resize(3,-1);
       _pts_stopmu_ovrlap_v.clear();
       _pts_stopmu_ovrlap_v.resize(3,-1);
       _pts_thrumu_ovrlap_v.clear();
       _pts_thrumu_ovrlap_v.resize(3,-1);
       _endCos_v.clear();
       _endCos_v.resize(3,-2);
       auto pgraph = ev_pgraph->PGraphArray().at(vtxID);
       auto const& roi_v = pgraph.ParticleArray();
       auto const& bb_v  = roi_v.front().BB();
       auto iter = std::find(roid_v.begin(),roid_v.end(),bb_v);
       if (iter == roid_v.end()) throw larbys("Unknown image meta");
       auto roid = iter - roid_v.begin();
       if (roid != _roid) _vtxid = 0;
       _roid  = roid;
       _vtxid += 1;
       _run    = ev_img2d->run();
       _subrun = ev_img2d->subrun();
       _event  = ev_img2d->event();
       _entry  = mgr.current_entry();
       auto const& cluster_idx_v = pgraph.ClusterIndexArray();
       if (cluster_idx_v.size() < 2) {
     _tree->Fill();
     continue;
       }
       auto const& cluster_idx0  = cluster_idx_v[0];
       auto const& cluster_idx1  = cluster_idx_v[1];
       for(auto const& plane : plane_order_v){
     auto crop_img      =  pgraph.ParticleArray().back().BB(plane);
     auto crop_mat_raw  = _LArbysImageMaker.ExtractMat(adc_img2d_v.at(plane).crop(crop_img));
     auto crop_mat_stop = _LArbysImageMaker.ExtractMat(stopmu_img2d_v.at(plane).crop(crop_img));
     auto crop_mat_thru = _LArbysImageMaker.ExtractMat(thrumu_img2d_v.at(plane).crop(crop_img));
     auto raw_non_zero    = cv::countNonZero(crop_mat_raw);
     auto stopmu_non_zero = cv::countNonZero(crop_mat_stop);
     auto thrumu_non_zero = cv::countNonZero(crop_mat_thru);
     _num_allpix_v.at(plane)  = raw_non_zero;
     _num_nottag_v.at(plane)  = raw_non_zero - thrumu_non_zero - stopmu_non_zero;//thrumu_non_zero + stopmu_non_zero - raw_non_zero;
     _num_stoptag_v.at(plane) = stopmu_non_zero;//raw_non_zero - stopmu_non_zero;
     _num_thrutag_v.at(plane) = thrumu_non_zero;//raw_non_zero - thrumu_non_zero;
     auto iter_pcluster = pcluster_m.find(plane);
     if(iter_pcluster == pcluster_m.end()) continue;
     auto const& pcluster_v = (*iter_pcluster).second;
     auto const& pcluster0  = pcluster_v.at(cluster_idx0);
     auto const& pcluster1  = pcluster_v.at(cluster_idx1);
     int nInClusterRaw   = pcluster0.size() + pcluster1.size();
     std::vector<cv::Point> pointsInRaw;
     larcv::Pixel2D startPt;
     if (pcluster0.size() > 0) {
       startPt = pcluster0.at(0);
     }
     larcv::Pixel2D maxPt0;
     larcv::Pixel2D maxPt1;
     float maxDist0 = -1;
     float maxDist1 = -1;
     for (auto const& pt : pcluster0) {
       pointsInRaw.push_back(cv::Point(pt.X(),pt.Y()));
       float dist0 = std::sqrt( ((float)startPt.X() - (float)pt.X())*((float)startPt.X() - (float)pt.X()) + ((float)startPt.Y() - (float)pt.Y())*((float)startPt.Y() - (float)pt.Y())) ;
       if (dist0 > maxDist0 ) {
         maxDist0 = dist0;
         maxPt0 = pt;
       }
     }
     for (auto const& pt : pcluster1) {
       pointsInRaw.push_back(cv::Point(pt.X(),pt.Y()));
       float dist1 = std::sqrt( ((float)startPt.X() - (float)pt.X())*((float)startPt.X() - (float)pt.X()) + ((float)startPt.Y() - (float)pt.Y())*((float)startPt.Y() - (float)pt.Y()));
       if ( dist1 > maxDist1 ) {
         maxDist1 = dist1;
         maxPt1 = pt;
       }
     }
     if (pcluster0.size() > 0) {
       float dot  = ((float)maxPt0.X()-(float)startPt.X())*((float)maxPt1.X()-(float)startPt.X()) + ((float)maxPt0.Y()-(float)startPt.Y())*((float)maxPt1.Y()-(float)startPt.Y());
       float mag0 = std::sqrt(std::pow((float)maxPt0.X()-(float)startPt.X(),2)+std::pow((float)maxPt0.Y()-(float)startPt.Y(),2));
       float mag1 = std::sqrt(std::pow((float)maxPt1.X()-(float)startPt.X(),2)+std::pow((float)maxPt1.Y()-(float)startPt.Y(),2));
       _endCos_v.at(plane) = dot/(mag0*mag1);
     }
     auto pointsInThru = larocv::FindNonZero(crop_mat_thru);
     auto pointsInStop = larocv::FindNonZero(crop_mat_stop);
     int nInThru = 0;
     int nInStop = 0;
     for (auto const& pt : pointsInRaw) {
       if (std::find(pointsInThru.begin(),pointsInThru.end(),pt) != pointsInThru.end()) nInThru++;
       if (std::find(pointsInStop.begin(),pointsInStop.end(),pt) != pointsInStop.end()) nInStop++;
     }
     _pts_thrumu_ovrlap_v.at(plane) = nInThru;
     _pts_stopmu_ovrlap_v.at(plane) = nInStop;
     _pts_in_raw_clus_v.at(plane)   = nInClusterRaw;
       }
       _tree->Fill();
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_endCos_v
std::vector<float> larcv::CosmicVertexAna::_endCos_v private
Definition at line 75 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_entry
int larcv::CosmicVertexAna::_entry private
Definition at line 56 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_event
int larcv::CosmicVertexAna::_event private
Definition at line 55 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_img2d_prod
std::string larcv::CosmicVertexAna::_img2d_prod private
Definition at line 60 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_LArbysImageMaker
LArbysImageMaker larcv::CosmicVertexAna::_LArbysImageMaker private
Definition at line 49 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_num_allpix_v
std::vector<int> larcv::CosmicVertexAna::_num_allpix_v private
Definition at line 68 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_num_nottag_v
std::vector<int> larcv::CosmicVertexAna::_num_nottag_v private
Definition at line 69 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_num_stoptag_v
std::vector<int> larcv::CosmicVertexAna::_num_stoptag_v private
Definition at line 71 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_num_thrutag_v
std::vector<int> larcv::CosmicVertexAna::_num_thrutag_v private
Definition at line 70 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_pcluster_ctor_prod
std::string larcv::CosmicVertexAna::_pcluster_ctor_prod private
Definition at line 62 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_pcluster_img_prod
std::string larcv::CosmicVertexAna::_pcluster_img_prod private
Definition at line 63 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_pgraph_prod
std::string larcv::CosmicVertexAna::_pgraph_prod private
Definition at line 61 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_pts_in_raw_clus_v
std::vector<int> larcv::CosmicVertexAna::_pts_in_raw_clus_v private
Definition at line 72 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_pts_stopmu_ovrlap_v
std::vector<int> larcv::CosmicVertexAna::_pts_stopmu_ovrlap_v private
Definition at line 73 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_pts_thrumu_ovrlap_v
std::vector<int> larcv::CosmicVertexAna::_pts_thrumu_ovrlap_v private
Definition at line 74 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_reco_roi_prod
std::string larcv::CosmicVertexAna::_reco_roi_prod private
Definition at line 64 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_roid
int larcv::CosmicVertexAna::_roid private
Definition at line 57 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_run
int larcv::CosmicVertexAna::_run private
Definition at line 53 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_stopmu_img_prod
std::string larcv::CosmicVertexAna::_stopmu_img_prod private
Definition at line 66 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_subrun
int larcv::CosmicVertexAna::_subrun private
Definition at line 54 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
_tags_datatype
ProductType_t larcv::CosmicVertexAna::_tags_datatype private
Definition at line 77 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_thrumu_img_prod
std::string larcv::CosmicVertexAna::_thrumu_img_prod private
Definition at line 65 of file CosmicVertexAna.h.
Referenced by configure(), and process().
_tree
TTree* larcv::CosmicVertexAna::_tree private
Definition at line 51 of file CosmicVertexAna.h.
Referenced by finalize(), initialize(), and process().
_vtxid
int larcv::CosmicVertexAna::_vtxid private
Definition at line 58 of file CosmicVertexAna.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
CosmicVertexAna.h
CosmicVertexAna.cxx