LArCV: larcv::IOManager< T > Class Template Reference
larcv::IOManager< T > Class Template Reference
LArCV
User defined class IOManager ...
#include <IOManager.h>
Public Types
enum IOMode_t {
kREAD, kWRITE, kBOTH, kREAD,
kWRITE, kBOTH, kREAD, kWRITE,
kBOTH
}
enum IOMode_t {
kREAD, kWRITE, kBOTH, kREAD,
kWRITE, kBOTH, kREAD, kWRITE,
kBOTH
}
Three IO modes: read, write, or read-and-write.
enum IOMode_t {
kREAD, kWRITE, kBOTH, kREAD,
kWRITE, kBOTH, kREAD, kWRITE,
kBOTH
}
Public Member Functions
IOManager (IOMode_t mode=kREAD)
Default constructor.
~IOManager ()
Default destructor.
void reset ()
void add_in_file (const std::string filename, const std::string dirname="")
void set_out_file (const std::string name)
size_t producer_id (const std::string &producer) const
bool initialize ()
bool read_entry (const size_t index)
bool save_entry ()
std::vector< T > & get_data (const std::string &producer)
std::vector< T > & get_data (const size_t id)
void finalize ()
IOManager (IOMode_t mode=kREAD, std::string name="IOManager")
Default constructor.
IOManager (const PSet &cfg)
Configuration PSet construction so you don't have to call setter functions.
~IOManager ()
Default destructor.
IOMode_t io_mode () const
IO mode accessor.
void reset ()
void add_in_file (const std::string filename, const std::string dirname="")
void clear_in_file ()
void set_out_file (const std::string name)
ProducerID_t producer_id (const ProductType_t type, const std::string &producer) const
ProductType_t product_type (const size_t id) const
void configure (const PSet &cfg)
bool initialize ()
bool read_entry (const size_t index, bool force_reload=false)
bool save_entry ()
void finalize ()
void clear_entry ()
void set_id (const size_t run, const size_t subrun, const size_t event)
size_t current_entry () const
size_t get_n_entries () const
EventBase * get_data (const ProductType_t type, const std::string &producer)
EventBase * get_data (const ProducerID_t id)
template<class T >
T & get_data (const std::string &producer)
template<class T >
T & get_data (const ProducerID_t id)
const EventBase & event_id () const
const EventBase & last_event_id () const
const std::vector< std::string > producer_list (const ProductType_t type) const
const std::vector< std::string > & file_list () const
IOManager (IOMode_t mode=kREAD)
Default constructor.
~IOManager ()
Default destructor.
void reset ()
void add_in_file (const std::string filename, const std::string dirname="")
void set_out_file (const std::string name)
size_t producer_id (const std::string &producer) const
bool initialize ()
bool read_entry (const size_t index)
bool save_entry ()
std::vector< T > & get_data (const std::string &producer)
std::vector< T > & get_data (const size_t id)
void finalize ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void prepare_input ()
size_t register_producer (const std::string &name)
void set_id ()
void prepare_input ()
size_t register_producer (const ProductType_t type, const std::string &name)
void prepare_input ()
size_t register_producer (const std::string &name)
Private Attributes
IOMode_t _io_mode
bool _prepared
TFile * _out_file
size_t _tree_index
size_t _tree_entries
std::string _out_file_name
std::vector< std::string > _in_file_v
std::vector< std::string > _in_dir_v
std::vector< std::map< std::string, size_t > > _key_list
std::vector< TTree * > _out_tree_v
std::vector< TChain * > _in_tree_v
std::vector< size_t > _in_tree_index_v
size_t _product_ctr
std::vector< larcv::EventBase * > _product_ptr_v
std::vector< larcv::ProductType_t > _product_type_v
size_t _in_tree_index
size_t _out_tree_index
size_t _in_tree_entries
size_t _out_tree_entries
bool _hasindex
EventBase _event_id
EventBase _set_event_id
EventBase _last_event_id
std::vector< std::map< std::string, larcv::ProducerID_t > > _key_list
TChain * _in_index_tree_v
TChain * _out_index_tree_v
std::vector< std::string > _store_only_name
std::vector< larcv::ProductType_t > _store_only_type
std::vector< std::string > _read_only_name
std::vector< larcv::ProductType_t > _read_only_type
std::vector< bool > _store_only_bool
std::vector< bool > _read_id_bool
std::map< std::string, size_t > _key_m
std::vector< std::vector< T > * > _product_v
Detailed Description
template<class T>
class larcv::IOManager< T >
User defined class IOManager ...
LArCV file IO hanlder class: it can read/write LArCV file.
these comments are used to generate doxygen documentation!
Definition at line 30 of file arxiv/IOManager.h.
Constructor & Destructor Documentation
~IOManager() [1/2]
template<class T > larcv::IOManager< T >::~IOManager () inline
Default destructor.
Definition at line 46 of file IOManager.h.
 {}
IOManager()
template<class T > larcv::IOManager< T >::IOManager (IOMode_t mode = kREAD) inline
Default constructor.
Definition at line 38 of file old/IOManager.h.
References larcv::IOManager< T >::reset().
       : _io_mode       ( mode          )
       , _prepared      ( false         )
       , _out_file      ( nullptr       )
       , _tree_index    ( 0             )
       , _tree_entries  ( 0             )
       , _out_file_name ( ""            )
       , _in_file_v     ()
       , _in_dir_v      ()
       , _key_m         ()
       , _out_tree_v    ()
       , _in_tree_v     ()
       , _in_tree_index_v ()
       , _product_v     ()
       , _product_ctr   (0)
     { reset(); }
~IOManager() [2/2]
template<class T > larcv::IOManager< T >::~IOManager () inline
Default destructor.
Definition at line 56 of file old/IOManager.h.
References larcv::IOManager< T >::reset().
 {}
Member Function Documentation
add_in_file() [1/2]
template<class T > void larcv::IOManager< T >::add_in_file (const std::string filename, const std::string dirname = "")
add_in_file() [2/2]
template<class T > void larcv::IOManager< T >::add_in_file (const std::string filename, const std::string dirname = "") inline
Definition at line 59 of file old/IOManager.h.
References larcv::IOManager< T >::_in_dir_v, and larcv::IOManager< T >::_in_file_v.
     { _in_file_v.push_back(filename); _in_dir_v.push_back(dirname); }
finalize() [1/2]
template<class T > void larcv::IOManager< T >::finalize ()
finalize() [2/2]
template<class T > void larcv::IOManager< T >::finalize ()
get_data() [1/3]
template<class T > std::vector<T>& larcv::IOManager< T >::get_data (const std::string & producer)
get_data() [2/3]
template<class T > std::vector<T>& larcv::IOManager< T >::get_data (const size_t id)
get_data() [3/3]
template<class T > EventBase* larcv::IOManager< T >::get_data (const ProducerID_t id)
initialize() [1/2]
template<class T > bool larcv::IOManager< T >::initialize ()
initialize() [2/2]
template<class T > bool larcv::IOManager< T >::initialize ()
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
prepare_input() [1/2]
template<class T > void larcv::IOManager< T >::prepare_input () private
prepare_input() [2/2]
template<class T > void larcv::IOManager< T >::prepare_input () private
producer_id()
template<class T > size_t larcv::IOManager< T >::producer_id (const std::string & producer) const
read_entry()
template<class T > bool larcv::IOManager< T >::read_entry (const size_t index)
register_producer()
template<class T > size_t larcv::IOManager< T >::register_producer (const std::string & name) private
reset() [1/2]
template<class T > void larcv::IOManager< T >::reset ()
reset() [2/2]
template<class T > void larcv::IOManager< T >::reset ()
save_entry() [1/2]
template<class T > bool larcv::IOManager< T >::save_entry ()
save_entry() [2/2]
template<class T > bool larcv::IOManager< T >::save_entry ()
set_out_file() [1/2]
template<class T > void larcv::IOManager< T >::set_out_file (const std::string name)
set_out_file() [2/2]
template<class T > void larcv::IOManager< T >::set_out_file (const std::string name) inline
Definition at line 61 of file old/IOManager.h.
References larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_tree_entries, larcv::IOManager< T >::_tree_index, larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::larcv_base::name(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::save_entry().
     { _out_file_name = name; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
The documentation for this class was generated from the following files:
arxiv/IOManager.h
arxiv/IOManager.cxx