LArCV: larcv::VertexFilter Class Reference
larcv::VertexFilter Class Reference
#include <VertexFilter.h>
Public Member Functions
VertexFilter (const std::string name="VertexFilter")
~VertexFilter ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void clear ()
void SetIndexVector (const std::vector< bool > &vec)
void SetParticleType (const std::vector< std::pair< int, int > > &vec)
void FillParticles (const std::vector< size_t > &cid_v, EventPixel2D *ictor_v, EventPixel2D *iimg_v, EventPixel2D *octor_v, EventPixel2D *oimg_v)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
TTree * _tree
int _run
int _subrun
int _event
int _entry
int _cvtxid
int _fvtxid
bool _set_shape
std::string _in_pg_prod
std::string _in_ctor_prod
std::string _in_img_prod
std::string _in_super_ctor_prod
std::string _in_super_img_prod
std::string _out_pg_prod
std::string _out_ctor_prod
std::string _out_img_prod
std::string _out_super_ctor_prod
std::string _out_super_img_prod
std::vector< bool > _idx_v
std::vector< std::pair< int, int > > _par_v
Detailed Description
Definition at line 10 of file VertexFilter.h.
Constructor & Destructor Documentation
VertexFilter()
larcv::VertexFilter::VertexFilter (const std::string name = "VertexFilter")
Definition at line 14 of file VertexFilter.cxx.
Referenced by larcv::VertexFilterProcessFactory::create().
     : ProcessBase(name), _tree(nullptr)
   {}
~VertexFilter()
larcv::VertexFilter::~VertexFilter () inline
Definition at line 14 of file VertexFilter.h.
References clear(), configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
clear()
void larcv::VertexFilter::clear ()
Definition at line 350 of file VertexFilter.cxx.
References _cvtxid, _entry, _event, _fvtxid, _idx_v, _par_v, _run, _subrun, larcv::kINVALID_INT, and LARCV_DEBUG.
Referenced by process(), and ~VertexFilter().
{
     LARCV_DEBUG() << "start" << std::endl;
     _idx_v.clear();
     _par_v.clear();
     _run = kINVALID_INT;
     _subrun = kINVALID_INT;
     _event = kINVALID_INT;
     _entry = kINVALID_INT;
     _cvtxid = kINVALID_INT;
     _fvtxid = kINVALID_INT;
     LARCV_DEBUG() << "end" << std::endl;
   }
configure()
void larcv::VertexFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 18 of file VertexFilter.cxx.
References _in_ctor_prod, _in_img_prod, _in_pg_prod, _in_super_ctor_prod, _in_super_img_prod, _out_ctor_prod, _out_img_prod, _out_pg_prod, _out_super_ctor_prod, _out_super_img_prod, _set_shape, and larcv::PSet::get().
Referenced by ~VertexFilter().
   {
     // assert 2 particles and set shape
     _set_shape = cfg.get<bool>("SetShape");
     // PGraph
     _in_pg_prod    = cfg.get<std::string>("InputPGraphProducer");
     _out_pg_prod   = cfg.get<std::string>("OutputPGraphProducer");
     // Input contour and image
     _in_ctor_prod = cfg.get<std::string>("InputCtorProducer","");
     _in_img_prod  = cfg.get<std::string>("InputImgProducer","");
     // Input super contour and super image
     _in_super_ctor_prod = cfg.get<std::string>("InputSuperCtorProducer","");
     _in_super_img_prod  = cfg.get<std::string>("InputSuperImgProducer","");
     // Output contour and image
     _out_ctor_prod = cfg.get<std::string>("OutputCtorProducer","");
     _out_img_prod  = cfg.get<std::string>("OutputImgProducer","");
     // Output super contour and super image
     _out_super_ctor_prod = cfg.get<std::string>("OutputSuperCtorProducer","");
     _out_super_img_prod  = cfg.get<std::string>("OutputSuperImgProducer","");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
FillParticles()
void larcv::VertexFilter::FillParticles (const std::vector< size_t > & cid_v, EventPixel2D * ictor_v, EventPixel2D * iimg_v, EventPixel2D * octor_v, EventPixel2D * oimg_v)
Definition at line 274 of file VertexFilter.cxx.
References larcv::EventPixel2D::Append(), larcv::EventPixel2D::ClusterMetaArray(), LARCV_DEBUG, and larcv::EventPixel2D::Pixel2DClusterArray().
Referenced by process(), and SetParticleType().
{
     LARCV_DEBUG() << "start" << std::endl;
     auto const& ctor_m      = ictor_v->Pixel2DClusterArray();
     auto const& ctor_meta_m = ictor_v->ClusterMetaArray();
     LARCV_DEBUG() << "ctor_m sz=     " << ctor_m.size() << std::endl;
     LARCV_DEBUG() << "ctor_meta_m sz=" << ctor_meta_m.size() << std::endl;
     auto const& pcluster_m      = iimg_v->Pixel2DClusterArray();
     auto const& pcluster_meta_m = iimg_v->ClusterMetaArray();
     LARCV_DEBUG() << "pcluster_m sz=     " << pcluster_m.size() << std::endl;
     LARCV_DEBUG() << "pcluster_meta_m sz=" << pcluster_meta_m.size() << std::endl;
     for(size_t plane=0; plane<3; ++plane) {
       LARCV_DEBUG() << "@plane=" << plane << std::endl;
       auto iter_pcluster = pcluster_m.find(plane);
       if(iter_pcluster == pcluster_m.end()) {
     LARCV_DEBUG() << "skip pcluster_m" << std::endl;
     continue;
       }
       auto iter_pcluster_meta = pcluster_meta_m.find(plane);
       if(iter_pcluster_meta == pcluster_meta_m.end()) {
     LARCV_DEBUG() << "skip pcluster_meta_m" << std::endl;
     continue;
       }
       auto iter_ctor = ctor_m.find(plane);
       if(iter_ctor == ctor_m.end()) {
     LARCV_DEBUG() << "skip ctor_m" << std::endl;
     continue;
       }
       auto iter_ctor_meta = ctor_meta_m.find(plane);
       if(iter_ctor_meta == ctor_meta_m.end()) {
     LARCV_DEBUG() << "skip ctor_meta_m" << std::endl;
     continue;
       }
       LARCV_DEBUG() << "accepted!" << std::endl;
       auto const& pcluster_v      = (*iter_pcluster).second;
       auto const& pcluster_meta_v = (*iter_pcluster_meta).second;
       auto const& ctor_v      = (*iter_ctor).second;
       auto const& ctor_meta_v = (*iter_ctor_meta).second;
       for (auto cidx : cid_v) {
     LARCV_DEBUG() << "@cidx=" << cidx << std::endl;
     auto const& pcluster      = pcluster_v.at(cidx);
     auto const& pcluster_meta = pcluster_meta_v.at(cidx);
     auto const& ctor      = ctor_v.at(cidx);
     auto const& ctor_meta = ctor_meta_v.at(cidx);
     octor_v->Append(plane,ctor,ctor_meta);
     oimg_v->Append(plane,pcluster,pcluster_meta);
       }
       LARCV_DEBUG() << "end this plane" << std::endl;
     } // end plane
     LARCV_DEBUG() << "end" << std::endl;
   }
finalize()
void larcv::VertexFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 345 of file VertexFilter.cxx.
References _tree.
Referenced by ~VertexFilter().
{
     assert(_tree);
     _tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::VertexFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 45 of file VertexFilter.cxx.
References _cvtxid, _entry, _event, _fvtxid, _run, _subrun, and _tree.
Referenced by ~VertexFilter().
{
     _tree = new TTree("VertexFilterTree","");
     _tree->Branch("run"    , &_run    , "run/I");
     _tree->Branch("subrun" , &_subrun , "subrun/I");
     _tree->Branch("event"  , &_event  , "event/I");
     _tree->Branch("entry"  , &_entry  , "entry/I");
     _tree->Branch("cvtxid" , &_cvtxid , "cvtxid/I");
     _tree->Branch("fvtxid" , &_fvtxid , "fvtxid/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::VertexFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 57 of file VertexFilter.cxx.
References _cvtxid, _entry, _event, _fvtxid, _idx_v, _in_ctor_prod, _in_img_prod, _in_pg_prod, _in_super_ctor_prod, _in_super_img_prod, _out_ctor_prod, _out_img_prod, _out_pg_prod, _out_super_ctor_prod, _out_super_img_prod, _par_v, _run, _set_shape, _subrun, _tree, larcv::PGraph::Add(), clear(), larcv::IOManager< T >::current_entry(), larcv::PGraph::Emplace(), FillParticles(), larcv::IOManager< T >::get_data(), larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kShapeShower, larcv::kShapeTrack, LARCV_CRITICAL, LARCV_DEBUG, and larcv::EventPixel2D::Pixel2DClusterArray().
Referenced by ~VertexFilter().
{
     LARCV_DEBUG() << "start" << std::endl;
     auto in_pg_v   = (EventPGraph*)  mgr.get_data(kProductPGraph,  _in_pg_prod);
     auto out_pg_v  = (EventPGraph*)  mgr.get_data(kProductPGraph,  _out_pg_prod);
     if (!(out_pg_v->PGraphArray().empty())) throw larbys("data product not empty");
     EventPixel2D* in_ctor_v  = nullptr;
     EventPixel2D* in_img_v   = nullptr;
     EventPixel2D* in_super_ctor_v  = nullptr;
     EventPixel2D* in_super_img_v   = nullptr;
     EventPixel2D* out_ctor_v = nullptr;
     EventPixel2D* out_img_v  = nullptr;
     EventPixel2D* out_super_ctor_v = nullptr;
     EventPixel2D* out_super_img_v  = nullptr;
     bool set_pixel  = false;
     bool set_spixel = false;
     if (!_in_ctor_prod.empty() or !_in_img_prod.empty()) {
       if (_in_ctor_prod.empty() or _in_img_prod.empty()) {
     LARCV_CRITICAL() << "must specify both INPUT ctor and img producer" << std::endl;
     throw larbys();
       }
       in_ctor_v = (EventPixel2D*) mgr.get_data(kProductPixel2D, _in_ctor_prod);
       in_img_v  = (EventPixel2D*) mgr.get_data(kProductPixel2D, _in_img_prod);
       if (_out_ctor_prod.empty() or _out_img_prod.empty()) {
     LARCV_CRITICAL() << "must specify both OUTPUT ctor and img producer" << std::endl;
     throw larbys();
       }
       out_ctor_v = (EventPixel2D*) mgr.get_data(kProductPixel2D, _out_ctor_prod);
       out_img_v  = (EventPixel2D*) mgr.get_data(kProductPixel2D, _out_img_prod);
       if (!(out_ctor_v->Pixel2DClusterArray().empty())) throw larbys("data product not empty");
       if (!(out_img_v->Pixel2DClusterArray().empty()))  throw larbys("data product not empty");
       set_pixel = true;
     }
     if (!_in_super_ctor_prod.empty() or !_in_super_img_prod.empty()) {
       if (_in_super_ctor_prod.empty() or _in_super_img_prod.empty()) {
     LARCV_CRITICAL() << "must specify both INPUT super ctor and img producer" << std::endl;
     throw larbys();
       }
       in_super_ctor_v = (EventPixel2D*) mgr.get_data(kProductPixel2D, _in_super_ctor_prod);
       in_super_img_v  = (EventPixel2D*) mgr.get_data(kProductPixel2D, _in_super_img_prod);
       if (_out_super_ctor_prod.empty() or _out_super_img_prod.empty()) {
     LARCV_CRITICAL() << "must specify both OUTPUT super ctor and img producer" << std::endl;
     throw larbys();
       }
       out_super_ctor_v = (EventPixel2D*) mgr.get_data(kProductPixel2D, _out_super_ctor_prod);
       out_super_img_v  = (EventPixel2D*) mgr.get_data(kProductPixel2D, _out_super_img_prod);
       if (!(out_super_ctor_v->Pixel2DClusterArray().empty())) throw larbys("data product not empty");
       if (!(out_super_img_v->Pixel2DClusterArray().empty()))  throw larbys("data product not empty");
       set_spixel = true;
     }
     _run    = (int) in_pg_v->run();
     _subrun = (int) in_pg_v->subrun();
     _event  = (int) in_pg_v->event();
     _entry  = (int) mgr.current_entry();
     //
     // nothing to do
     //
     if (_idx_v.empty()) {
       LARCV_DEBUG() << "empty index vector" << std::endl;
       LARCV_DEBUG() << "return" << std::endl;
       clear();
       return true;
     }
     //
     // something to do
     //
     if (_idx_v.size() != in_pg_v->PGraphArray().size())
       throw larbys("pgraph & index vector size differ");
     int cluster_index_id = -1;
     for(size_t pgid=0; pgid < in_pg_v->PGraphArray().size(); ++pgid) {
       LARCV_DEBUG() << "@pgid=" << pgid << std::endl;
       if (!_idx_v[pgid]) continue;
       LARCV_DEBUG() << "...passed..." << std::endl;
       const auto& pg_old = (*in_pg_v).PGraphArray()[pgid];
       //
       // don't filter the particles
       //
       if (!set_pixel and !set_spixel) {
     out_pg_v->Append(pg_old);
     _cvtxid = pgid;
     _fvtxid = out_pg_v->PGraphArray().size() - 1;
     _tree->Fill();
     LARCV_DEBUG() << "... next pgid" << std::endl;
     continue;
       }
       //
       // filter the particles and set type
       //
       const auto& par_old_v = pg_old.ParticleArray();
       const auto& ci_old_v  = pg_old.ClusterIndexArray();
       PGraph pg_new;
       if(_set_shape) {
     const auto& par_pair = _par_v[pgid];
     if (par_pair.first  < 0) throw larbys("particle 0 invalid !");
     if (par_pair.second < 0) throw larbys("particle 1 invalid !");
     assert (par_old_v.size() == 2);
     //
     // update particle label and store
     //
     auto roi0 = par_old_v.front();
     auto roi1 = par_old_v.back();
     roi0.Shape( par_pair.first  ? kShapeTrack : kShapeShower );
     roi1.Shape( par_pair.second ? kShapeTrack : kShapeShower );
     if (roi0.Shape() == kShapeShower) roi0.PdgCode(11);
     else roi0.PdgCode(14);
     if (roi1.Shape() == kShapeShower) roi1.PdgCode(11);
     else roi1.PdgCode(14);
     LARCV_DEBUG() << "set par0 shape=" << (int)roi0.Shape() << std::endl;
     LARCV_DEBUG() << "set par1 shape=" << (int)roi1.Shape() << std::endl;
     cluster_index_id++;
     pg_new.Emplace(std::move(roi0),cluster_index_id);
     cluster_index_id++;
     pg_new.Emplace(std::move(roi1),cluster_index_id);
       }
       else {
     for(size_t pid=0; pid<par_old_v.size(); ++pid) {
       cluster_index_id++;
       pg_new.Add(par_old_v[pid],cluster_index_id);
     }
       }
       out_pg_v->Emplace(std::move(pg_new));
       LARCV_DEBUG() << "ci_old_v sz=" << ci_old_v.size() << std::endl;
       std::vector<size_t> cid_v;
       if (_set_shape) {
     assert (par_old_v.size() == 2);
     cid_v.resize(2);
     cid_v[0] = ci_old_v.front();
     cid_v[1] = ci_old_v.back();
       }
       // NOTE SETTING SHAPE NOT HANDLED
       if (set_pixel) {
     LARCV_DEBUG() << "storing pixels..."<< std::endl;
     FillParticles(ci_old_v,
               in_ctor_v,in_img_v,
               out_ctor_v,out_img_v);
     LARCV_DEBUG() << "...done!"<< std::endl;
       }
       if (set_spixel) {
     LARCV_DEBUG() << "storing super pixels..." << std::endl;
     FillParticles(ci_old_v,
               in_super_ctor_v,in_super_img_v,
               out_super_ctor_v,out_super_img_v);
     LARCV_DEBUG() << "...done!"<< std::endl;
       }
       LARCV_DEBUG() << "end this pgraph" << std::endl;
       assert (!out_pg_v->PGraphArray().empty());
       if(set_pixel) {
     assert (!out_ctor_v->Pixel2DClusterArray().empty());
     assert (!out_img_v->Pixel2DClusterArray().empty());
       }
       if(set_spixel) {
     assert (!out_super_ctor_v->Pixel2DClusterArray().empty());
     assert (!out_super_img_v->Pixel2DClusterArray().empty());
       }
       _cvtxid = pgid;
       _fvtxid = out_pg_v->PGraphArray().size() - 1;
       _tree->Fill();
     } // end pgraph
     LARCV_DEBUG() << "... writing " << out_ctor_v->Pixel2DClusterArray().size() << " out_ctor_v planes" << std::endl;
     LARCV_DEBUG() << "... writing " << out_img_v->Pixel2DClusterArray().size() << " out_img_v planes" << std::endl;
     LARCV_DEBUG() << "... writing " << out_super_ctor_v->Pixel2DClusterArray().size() << " out_super_ctor_v planes" << std::endl;
     LARCV_DEBUG() << "... writing " << out_super_img_v->Pixel2DClusterArray().size() << " out_super_img_v planes" << std::endl;
     LARCV_DEBUG() << "end" << std::endl;
     clear();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetIndexVector()
void larcv::VertexFilter::SetIndexVector (const std::vector< bool > & vec) inline
Definition at line 22 of file VertexFilter.h.
References _idx_v.
     { _idx_v = vec; }
SetParticleType()
void larcv::VertexFilter::SetParticleType (const std::vector< std::pair< int, int > > & vec) inline
Definition at line 25 of file VertexFilter.h.
References _par_v, and FillParticles().
     { _par_v = vec; }
Member Data Documentation
_cvtxid
int larcv::VertexFilter::_cvtxid private
Definition at line 40 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_entry
int larcv::VertexFilter::_entry private
Definition at line 38 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_event
int larcv::VertexFilter::_event private
Definition at line 37 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_fvtxid
int larcv::VertexFilter::_fvtxid private
Definition at line 41 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_idx_v
std::vector<bool> larcv::VertexFilter::_idx_v private
Definition at line 61 of file VertexFilter.h.
Referenced by clear(), process(), and SetIndexVector().
_in_ctor_prod
std::string larcv::VertexFilter::_in_ctor_prod private
Definition at line 47 of file VertexFilter.h.
Referenced by configure(), and process().
_in_img_prod
std::string larcv::VertexFilter::_in_img_prod private
Definition at line 48 of file VertexFilter.h.
Referenced by configure(), and process().
_in_pg_prod
std::string larcv::VertexFilter::_in_pg_prod private
Definition at line 45 of file VertexFilter.h.
Referenced by configure(), and process().
_in_super_ctor_prod
std::string larcv::VertexFilter::_in_super_ctor_prod private
Definition at line 50 of file VertexFilter.h.
Referenced by configure(), and process().
_in_super_img_prod
std::string larcv::VertexFilter::_in_super_img_prod private
Definition at line 51 of file VertexFilter.h.
Referenced by configure(), and process().
_out_ctor_prod
std::string larcv::VertexFilter::_out_ctor_prod private
Definition at line 55 of file VertexFilter.h.
Referenced by configure(), and process().
_out_img_prod
std::string larcv::VertexFilter::_out_img_prod private
Definition at line 56 of file VertexFilter.h.
Referenced by configure(), and process().
_out_pg_prod
std::string larcv::VertexFilter::_out_pg_prod private
Definition at line 53 of file VertexFilter.h.
Referenced by configure(), and process().
_out_super_ctor_prod
std::string larcv::VertexFilter::_out_super_ctor_prod private
Definition at line 58 of file VertexFilter.h.
Referenced by configure(), and process().
_out_super_img_prod
std::string larcv::VertexFilter::_out_super_img_prod private
Definition at line 59 of file VertexFilter.h.
Referenced by configure(), and process().
_par_v
std::vector<std::pair<int,int> > larcv::VertexFilter::_par_v private
Definition at line 62 of file VertexFilter.h.
Referenced by clear(), process(), and SetParticleType().
_run
int larcv::VertexFilter::_run private
Definition at line 35 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_set_shape
bool larcv::VertexFilter::_set_shape private
Definition at line 43 of file VertexFilter.h.
Referenced by configure(), and process().
_subrun
int larcv::VertexFilter::_subrun private
Definition at line 36 of file VertexFilter.h.
Referenced by clear(), initialize(), and process().
_tree
TTree* larcv::VertexFilter::_tree private
Definition at line 34 of file VertexFilter.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
VertexFilter.h
VertexFilter.cxx