LArCV: larcv::supera::Cropper< T, U, V > Class Template Reference
larcv::supera::Cropper< T, U, V > Class Template Reference
#include <Cropper.h>
Public Member Functions
Cropper ()
virtual ~Cropper ()
void configure (const larcv::supera::Config_t &cfg)
WTRangeArray_t WireTimeBoundary (const T &mct) const
Given single MCTrack, returns length 4 range array (3 planes + time)
which contains all trajectory points of input MCTrack.
WTRangeArray_t WireTimeBoundary (const T &mct, const std::vector< V > &sch_v) const
WTRangeArray_t WireTimeBoundary (const U &mcs) const
WTRangeArray_t WireTimeBoundary (const U &mcs, const std::vector< V > &sch_v) const
::larcv::ROI ParticleROI (const T &mct, const int time_offset) const
::larcv::ROI ParticleROI (const T &mct, const std::vector< V > &sch_v, const int time_offset) const
::larcv::ROI ParticleROI (const U &mcs, const int time_offset) const
::larcv::ROI ParticleROI (const U &mcs, const std::vector< V > &sch_v, const int time_offset) const
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
std::vector< larcv::ImageMeta > WTRange2BB (const WTRangeArray_t &) const
Private Attributes
unsigned int _max_time_tick
Maximum tick number in time.
unsigned int _time_padding
Padding in time axis (height) for Cropper::Format function.
unsigned int _wire_padding
Padding in wire axis (width) for Cropper::Format function.
unsigned int _min_width
unsigned int _min_height
Detailed Description
template<class T, class U, class V>
class larcv::supera::Cropper< T, U, V >
Definition at line 26 of file Cropper.h.
Constructor & Destructor Documentation
Cropper()
template<class T, class U, class V> larcv::supera::Cropper< T, U, V >::Cropper () inline
Definition at line 30 of file Cropper.h.
                 : _max_time_tick(9600)
         , _time_padding(10)
         , _wire_padding(10)
         , _min_width(10)
         , _min_height(14)
       {}
~Cropper()
template<class T, class U, class V> virtual larcv::supera::Cropper< T, U, V >::~Cropper () inline virtual
Definition at line 37 of file Cropper.h.
 {}
Member Function Documentation
configure()
template<class T, class U, class V> void larcv::supera::Cropper< T, U, V >::configure (const larcv::supera::Config_t & cfg)
Referenced by larcv::supera::Cropper< sim::MCTrack, sim::MCShower, sim::SimChannel >::~Cropper().
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
ParticleROI() [1/4]
template<class T, class U, class V> ::larcv::ROI larcv::supera::Cropper< T, U, V >::ParticleROI (const T & mct, const int time_offset) const
Referenced by larcv::supera::Cropper< sim::MCTrack, sim::MCShower, sim::SimChannel >::~Cropper().
ParticleROI() [2/4]
template<class T, class U, class V> ::larcv::ROI larcv::supera::Cropper< T, U, V >::ParticleROI (const T & mct, const std::vector< V > & sch_v, const int time_offset) const
ParticleROI() [3/4]
template<class T, class U, class V> ::larcv::ROI larcv::supera::Cropper< T, U, V >::ParticleROI (const U & mcs, const int time_offset) const
ParticleROI() [4/4]
template<class T, class U, class V> ::larcv::ROI larcv::supera::Cropper< T, U, V >::ParticleROI (const U & mcs, const std::vector< V > & sch_v, const int time_offset) const
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
WireTimeBoundary() [1/4]
template<class T, class U, class V> WTRangeArray_t larcv::supera::Cropper< T, U, V >::WireTimeBoundary (const T & mct) const
Given single MCTrack, returns length 4 range array (3 planes + time)
which contains all trajectory points of input MCTrack.
Referenced by larcv::supera::Cropper< sim::MCTrack, sim::MCShower, sim::SimChannel >::~Cropper().
WireTimeBoundary() [2/4]
template<class T, class U, class V> WTRangeArray_t larcv::supera::Cropper< T, U, V >::WireTimeBoundary (const T & mct, const std::vector< V > & sch_v) const
WireTimeBoundary() [3/4]
template<class T, class U, class V> WTRangeArray_t larcv::supera::Cropper< T, U, V >::WireTimeBoundary (const U & mcs) const
WireTimeBoundary() [4/4]
template<class T, class U, class V> WTRangeArray_t larcv::supera::Cropper< T, U, V >::WireTimeBoundary (const U & mcs, const std::vector< V > & sch_v) const
WTRange2BB()
template<class T, class U, class V> std::vector<larcv::ImageMeta> larcv::supera::Cropper< T, U, V >::WTRange2BB (const WTRangeArray_t &) const private
Referenced by larcv::supera::Cropper< sim::MCTrack, sim::MCShower, sim::SimChannel >::~Cropper().
Member Data Documentation
_max_time_tick
template<class T, class U, class V> unsigned int larcv::supera::Cropper< T, U, V >::_max_time_tick private
Maximum tick number in time.
Definition at line 58 of file Cropper.h.
_min_height
template<class T, class U, class V> unsigned int larcv::supera::Cropper< T, U, V >::_min_height private
Definition at line 62 of file Cropper.h.
_min_width
template<class T, class U, class V> unsigned int larcv::supera::Cropper< T, U, V >::_min_width private
Definition at line 61 of file Cropper.h.
_time_padding
template<class T, class U, class V> unsigned int larcv::supera::Cropper< T, U, V >::_time_padding private
Padding in time axis (height) for Cropper::Format function.
Definition at line 59 of file Cropper.h.
_wire_padding
template<class T, class U, class V> unsigned int larcv::supera::Cropper< T, U, V >::_wire_padding private
Padding in wire axis (width) for Cropper::Format function.
Definition at line 60 of file Cropper.h.
The documentation for this class was generated from the following file:
Cropper.h