LArCV: larcv::ROIAna Class Reference
larcv::ROIAna Class Reference
#include <ROIAna.h>
Public Member Functions
ROIAna (const std::string name="ROIAna")
Default constructor.
~ROIAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
float area (const ImageMeta &meta) const
float area (const ImageMeta *meta) const
void clear ()
Private Attributes
TTree * _roi_tree
std::string _roi_producer
std::string _img_producer
std::string _seg_producer
int _run
int _subrun
int _event
int _entry
int _nroi
float _area_exclusive0
float _area_exclusive1
float _area_exclusive2
float _area_inclusive0
float _area_inclusive1
float _area_inclusive2
float _union_area0
float _union_area1
float _union_area2
float _area_image0
float _area_image1
float _area_image2
larutil::SpaceChargeMicroBooNE _sce
int _good_croi0
int _good_croi1
int _good_croi2
int _good_croi_ctr
int _nearest_wire_err
Detailed Description
Definition at line 30 of file ROIAna.h.
Constructor & Destructor Documentation
ROIAna()
larcv::ROIAna::ROIAna (const std::string name = "ROIAna")
Default constructor.
Definition at line 15 of file ROIAna.cxx.
References clear().
Referenced by larcv::ROIAnaProcessFactory::create().
     : ProcessBase(name), _roi_tree(nullptr)
   { clear(); }
~ROIAna()
larcv::ROIAna::~ROIAna () inline
Default destructor.
Definition at line 38 of file ROIAna.h.
References area(), clear(), configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
area() [1/2]
float larcv::ROIAna::area (const ImageMeta & meta) const private
Definition at line 303 of file ROIAna.cxx.
References larcv::ImageMeta::cols(), and larcv::ImageMeta::rows().
Referenced by area(), process(), and ~ROIAna().
{
     return (float) meta.rows() * (float) meta.cols();
   }
area() [2/2]
float larcv::ROIAna::area (const ImageMeta * meta) const private
Definition at line 307 of file ROIAna.cxx.
References area().
{
     return area(*meta);
   }
clear()
void larcv::ROIAna::clear () private
Definition at line 311 of file ROIAna.cxx.
References _area_exclusive0, _area_exclusive1, _area_exclusive2, _area_image0, _area_image1, _area_image2, _area_inclusive0, _area_inclusive1, _area_inclusive2, _nroi, _union_area0, _union_area1, and _union_area2.
Referenced by initialize(), ROIAna(), and ~ROIAna().
                      {
     _nroi = 0;
     _area_exclusive0 = 0.0;
     _area_exclusive1 = 0.0;
     _area_exclusive2 = 0.0;
     _area_inclusive0 = 0.0;
     _area_inclusive1 = 0.0;
     _area_inclusive2 = 0.0;
     _union_area0 = 0.0;
     _union_area1 = 0.0;
     _union_area2 = 0.0;
     _area_image0 = 0.0;
     _area_image1 = 0.0;
     _area_image2 = 0.0;
   }
configure()
void larcv::ROIAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file ROIAna.cxx.
References _img_producer, _roi_producer, _seg_producer, and larcv::PSet::get().
Referenced by ~ROIAna().
   {
     _roi_producer      = cfg.get<std::string>("ROIProducer");
     _img_producer      = cfg.get<std::string>("ImageProducer");
     _seg_producer      = cfg.get<std::string>("SegmentProducer");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ROIAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 298 of file ROIAna.cxx.
References _roi_tree.
Referenced by ~ROIAna().
   {
     _roi_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ROIAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 27 of file ROIAna.cxx.
References _area_exclusive0, _area_exclusive1, _area_exclusive2, _area_image0, _area_image1, _area_image2, _area_inclusive0, _area_inclusive1, _area_inclusive2, _entry, _event, _good_croi0, _good_croi1, _good_croi2, _good_croi_ctr, _nroi, _roi_tree, _run, _subrun, _union_area0, _union_area1, _union_area2, and clear().
Referenced by ~ROIAna().
   {
     clear();
     _roi_tree = new TTree("ROITree","ROITree");
     _roi_tree->Branch("run",&_run,"run/I");
     _roi_tree->Branch("subrun",&_subrun,"subrun/I");
     _roi_tree->Branch("event",&_event,"event/I");
     _roi_tree->Branch("entry",&_entry,"entry/I");
     _roi_tree->Branch("nroi",&_nroi,"nroi/I");
     _roi_tree->Branch("area_exclusive0",&_area_exclusive0,"area_exclusive0/F");
     _roi_tree->Branch("area_exclusive1",&_area_exclusive1,"area_exclusive1/F");
     _roi_tree->Branch("area_exclusive2",&_area_exclusive2,"area_exclusive2/F");
     _roi_tree->Branch("area_inclusive0",&_area_inclusive0,"area_inclusive0/F");
     _roi_tree->Branch("area_inclusive1",&_area_inclusive1,"area_inclusive1/F");
     _roi_tree->Branch("area_inclusive2",&_area_inclusive2,"area_inclusive2/F");
     _roi_tree->Branch("area_union0",&_union_area0,"area_union0/F");
     _roi_tree->Branch("area_union1",&_union_area1,"area_union1/F");
     _roi_tree->Branch("area_union2",&_union_area2,"area_union2/F");
     _roi_tree->Branch("area_image0",&_area_image0,"area_image0/F");
     _roi_tree->Branch("area_image1",&_area_image1,"area_image1/F");
     _roi_tree->Branch("area_image2",&_area_image2,"area_image2/F");
     _roi_tree->Branch("good_croi0",&_good_croi0,"good_croi0/I");
     _roi_tree->Branch("good_croi1",&_good_croi1,"good_croi1/I");
     _roi_tree->Branch("good_croi2",&_good_croi2,"good_croi2/I");
     _roi_tree->Branch("good_croi_ctr",&_good_croi_ctr,"good_croi_ctr/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ROIAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 62 of file ROIAna.cxx.
References _area_exclusive0, _area_exclusive1, _area_exclusive2, _area_image0, _area_image1, _area_image2, _area_inclusive0, _area_inclusive1, _area_inclusive2, _entry, _event, _good_croi0, _good_croi1, _good_croi2, _good_croi_ctr, _img_producer, _nearest_wire_err, _nroi, _roi_producer, _roi_tree, _run, _sce, _seg_producer, _subrun, _union_area0, _union_area1, _union_area2, area(), larcv::IOManager< T >::current_entry(), larcv::EventBase::event(), larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::kINVALID_DOUBLE, larcv::kINVALID_INT, larcv::Image2D::kOverWrite, larcv::kProductImage2D, larcv::kProductROI, LARCV_CRITICAL, LARCV_WARNING, larcv::EventROI::ROIArray(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by ~ROIAna().
   {
     EventROI *ev_roi = nullptr;
     if (!_roi_producer.empty()) {
       ev_roi = (EventROI*)mgr.get_data(kProductROI,_roi_producer);
       if (!ev_roi) {
     LARCV_CRITICAL() << "Requested ROI producer " << _roi_producer
              << " could not be found" << std::endl;
     throw larbys();
       }
     }
     _run    = (int) ev_roi->run();
     _subrun = (int) ev_roi->subrun();
     _event  = (int) ev_roi->event();
     _entry  = (int) mgr.current_entry();
     EventImage2D *ev_img = nullptr;
     if (!_img_producer.empty()) {
       ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,_img_producer);
       if (!ev_img) {
     LARCV_CRITICAL() << "Requested Image2D producer " << _img_producer
              << " could not be found" << std::endl;
     throw larbys();
       }
     }
     double pixel_height = ev_img->Image2DArray().front().meta().pixel_height();
     double pixel_width  = ev_img->Image2DArray().front().meta().pixel_width();
     std::array<float,3> area_exclusive_v;
     std::array<float,3> area_inclusive_v;
     std::array<float,3> area_union_v;
     std::array<float,3> area_image_v;
     for(auto& v : area_exclusive_v) v=0;
     for(auto& v : area_inclusive_v) v=0;
     for(auto& v : area_union_v) v=0;
     for(auto& v : area_image_v) v=0;
     _nroi = ev_roi->ROIArray().size();
     std::vector<std::vector<const ImageMeta*> > meta_vv;
     meta_vv.resize(3);
     for(auto& meta_v : meta_vv) meta_v.reserve(_nroi);
     for(const auto& roi : ev_roi->ROIArray() ) {
       for(size_t plane=0; plane < 3; ++plane) {
     meta_vv[plane].emplace_back(&(roi.BB(plane)));
       }
     }
     std::array<ImageMeta,3> union_meta_v;
     for(size_t plane=0; plane<3; ++plane) {
       const auto& meta_v = meta_vv[plane];
       auto& area_exclusive    = area_exclusive_v.at(plane);
       auto& area_inclusive    = area_inclusive_v.at(plane);
       auto& area_union        = area_union_v.at(plane);
       auto& union_meta        = union_meta_v.at(plane);
       auto& area_image        = area_image_v.at(plane);
       //
       // sum the area
       //
       for(auto meta : meta_v)
     area_inclusive += area(meta);
       //
       // calculate the union size
       //
       bool first = true;
       for(auto meta : meta_v) {
     if (first) {
       union_meta = *meta;
       first = false;
       continue;
     }
     union_meta = union_meta.inclusive(*meta);
       }
       area_union = area(union_meta);
       //
       // calculate exclusive area
       //
       double width  = pixel_width  * union_meta.cols();
       double height = pixel_height * union_meta.rows();
       union_meta = ImageMeta(width,height,
                  union_meta.rows(),union_meta.cols(),
                  union_meta.tl().x,union_meta.tl().y,
                  plane);
       Image2D mask(union_meta);
       mask.paint(0.0);
       for(auto meta : meta_v) {
     ImageMeta bb(pixel_width*(meta->cols()),pixel_height*(meta->rows()),
              meta->rows(),meta->cols(),
              meta->tl().x,meta->tl().y,
              plane);
     Image2D img_bb(bb);
     img_bb.paint(1.0);
     mask.overlay(img_bb,Image2D::kOverWrite);
       }
       const auto& mask_v = mask.as_vector();
       area_exclusive = std::accumulate(std::begin(mask_v),std::end(mask_v),0.0);
       //
       // calculate the image size
       //
       area_image = area(ev_img->Image2DArray().at(plane).meta());
     }
     for(size_t plane=0; plane<3; ++plane) {
       if(plane==0) {
     _area_exclusive0 = area_exclusive_v[plane];
     _area_inclusive0 = area_inclusive_v[plane];
     _union_area0     = area_union_v[plane];
     _area_image0     = area_image_v[plane];
       }
       if(plane==1) {
     _area_exclusive1 = area_exclusive_v[plane];
     _area_inclusive1 = area_inclusive_v[plane];
     _union_area1     = area_union_v[plane];
     _area_image1     = area_image_v[plane];
       }
       if(plane==2) {
     _area_exclusive2 = area_exclusive_v[plane];
     _area_inclusive2 = area_inclusive_v[plane];
     _union_area2     = area_union_v[plane];
     _area_image2     = area_image_v[plane];
       }
     }
     _good_croi0 = kINVALID_INT;
     _good_croi1 = kINVALID_INT;
     _good_croi2 = kINVALID_INT;
     _good_croi_ctr = kINVALID_INT;
     _nearest_wire_err = kINVALID_INT;
     bool has_mc = false;
     EventROI *seg_roi = nullptr;
     if (!_seg_producer.empty()) {
       seg_roi = (EventROI*) mgr.get_data(kProductROI,_seg_producer);
       if (!seg_roi) larbys("Could not get seg producer");
       has_mc = true;
     }
     if(has_mc) {
       float _tx,_ty,_tz,_tt,_te;
       float _scex,_scey,_scez;
       _tx = _ty = _tz = _tt = _te = -1.;
       _scex = _scey = _scez = -1.;
       auto geo = larutil::Geometry::GetME();
       auto larp = larutil::LArProperties::GetME();
       double xyz[3];
       double wire_v[3];
       for(auto const& roi : seg_roi->ROIArray()){
     if(std::abs(roi.PdgCode()) == 12 || std::abs(roi.PdgCode()) == 14) {
       _tx = roi.X();
       _ty = roi.Y();
       _tz = roi.Z();
       _tt = roi.T();
       _te = roi.EnergyInit();
       auto const offset = _sce.GetPosOffsets(_tx,_ty,_tz);
       _scex = _tx - offset[0] + 0.7;
       _scey = _ty + offset[1];
       _scez = _tz + offset[2];
     }
       }
       xyz[0] = _scex;
       xyz[1] = _scey;
       xyz[2] = _scez;
       try {
     wire_v[0] = geo->NearestWire(xyz,0);
     wire_v[1] = geo->NearestWire(xyz,1);
     wire_v[2] = geo->NearestWire(xyz,2);
     _nearest_wire_err = 0;
       } catch(const std::exception& e) {
     LARCV_WARNING()<<"Cannot find nearest wire for ("<<xyz[0]<<","<<xyz[1]<<","<<xyz[2]<<")"<<std::endl;
     wire_v[0] = wire_v[1] = wire_v[2] = kINVALID_DOUBLE;
     _nearest_wire_err = 1;
       }
       const double tick = (_scex / larp->DriftVelocity() + 4) * 2. + 3200.;
       _good_croi0 = 0;
       _good_croi1 = 0;
       _good_croi2 = 0;
       _good_croi_ctr = 0;
       for(auto const& croi : ev_roi->ROIArray()) {
     auto const& bb_v = croi.BB();
     size_t good_croi_ctr = 0;
     for(size_t plane=0; plane<bb_v.size(); ++plane) {
       auto const& croi_meta = bb_v[plane];
       auto const& wire = wire_v[plane];
       if( croi_meta.min_x() <= wire && wire <= croi_meta.max_x() &&
           croi_meta.min_y() <= tick && tick <= croi_meta.max_y() ) {
         ++good_croi_ctr;
       }
     }
     if(good_croi_ctr <= _good_croi_ctr) continue;
     if(good_croi_ctr > 1) _good_croi_ctr+=1;
     for(size_t plane=0; plane<bb_v.size(); ++plane) {
       auto const& croi_meta = bb_v[plane];
       auto const& wire = wire_v[plane];
       if( croi_meta.min_x() <= wire && wire <= croi_meta.max_x() &&
           croi_meta.min_y() <= tick && tick <= croi_meta.max_y() ) {
         if(plane == 0) _good_croi0 = 1;
         if(plane == 1) _good_croi1 = 1;
         if(plane == 2) _good_croi2 = 1;
       }
     }
       } // end check of true vertex in cROI
     }
     _roi_tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_area_exclusive0
float larcv::ROIAna::_area_exclusive0 private
Definition at line 66 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_exclusive1
float larcv::ROIAna::_area_exclusive1 private
Definition at line 67 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_exclusive2
float larcv::ROIAna::_area_exclusive2 private
Definition at line 68 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_image0
float larcv::ROIAna::_area_image0 private
Definition at line 78 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_image1
float larcv::ROIAna::_area_image1 private
Definition at line 79 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_image2
float larcv::ROIAna::_area_image2 private
Definition at line 80 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_inclusive0
float larcv::ROIAna::_area_inclusive0 private
Definition at line 70 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_inclusive1
float larcv::ROIAna::_area_inclusive1 private
Definition at line 71 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_area_inclusive2
float larcv::ROIAna::_area_inclusive2 private
Definition at line 72 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_entry
int larcv::ROIAna::_entry private
Definition at line 62 of file ROIAna.h.
Referenced by initialize(), and process().
_event
int larcv::ROIAna::_event private
Definition at line 61 of file ROIAna.h.
Referenced by initialize(), and process().
_good_croi0
int larcv::ROIAna::_good_croi0 private
Definition at line 84 of file ROIAna.h.
Referenced by initialize(), and process().
_good_croi1
int larcv::ROIAna::_good_croi1 private
Definition at line 85 of file ROIAna.h.
Referenced by initialize(), and process().
_good_croi2
int larcv::ROIAna::_good_croi2 private
Definition at line 86 of file ROIAna.h.
Referenced by initialize(), and process().
_good_croi_ctr
int larcv::ROIAna::_good_croi_ctr private
Definition at line 87 of file ROIAna.h.
Referenced by initialize(), and process().
_img_producer
std::string larcv::ROIAna::_img_producer private
Definition at line 56 of file ROIAna.h.
Referenced by configure(), and process().
_nearest_wire_err
int larcv::ROIAna::_nearest_wire_err private
Definition at line 89 of file ROIAna.h.
Referenced by process().
_nroi
int larcv::ROIAna::_nroi private
Definition at line 64 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_roi_producer
std::string larcv::ROIAna::_roi_producer private
Definition at line 55 of file ROIAna.h.
Referenced by configure(), and process().
_roi_tree
TTree* larcv::ROIAna::_roi_tree private
Definition at line 53 of file ROIAna.h.
Referenced by finalize(), initialize(), and process().
_run
int larcv::ROIAna::_run private
Definition at line 59 of file ROIAna.h.
Referenced by initialize(), and process().
_sce
larutil::SpaceChargeMicroBooNE larcv::ROIAna::_sce private
Definition at line 82 of file ROIAna.h.
Referenced by process().
_seg_producer
std::string larcv::ROIAna::_seg_producer private
Definition at line 57 of file ROIAna.h.
Referenced by configure(), and process().
_subrun
int larcv::ROIAna::_subrun private
Definition at line 60 of file ROIAna.h.
Referenced by initialize(), and process().
_union_area0
float larcv::ROIAna::_union_area0 private
Definition at line 74 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_union_area1
float larcv::ROIAna::_union_area1 private
Definition at line 75 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
_union_area2
float larcv::ROIAna::_union_area2 private
Definition at line 76 of file ROIAna.h.
Referenced by clear(), initialize(), and process().
The documentation for this class was generated from the following files:
ROIAna.h
ROIAna.cxx