LArCV: larcv::SegmentFilter Class Reference
larcv::SegmentFilter Class Reference
#include <SegmentFilter.h>
Public Member Functions
SegmentFilter (const std::string name="SegmentFilter")
Default constructor.
~SegmentFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _seg_producer
std::vector< bool > _allowed_segment_v
Detailed Description
Definition at line 26 of file SegmentFilter.h.
Constructor & Destructor Documentation
SegmentFilter()
larcv::SegmentFilter::SegmentFilter (const std::string name = "SegmentFilter")
Default constructor.
Definition at line 12 of file SegmentFilter.cxx.
Referenced by larcv::SegmentFilterProcessFactory::create().
     : ProcessBase(name)
   {}
~SegmentFilter()
larcv::SegmentFilter::~SegmentFilter () inline
Default destructor.
Definition at line 34 of file SegmentFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SegmentFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file SegmentFilter.cxx.
References _allowed_segment_v, _seg_producer, larcv::PSet::get(), larcv::kROITypeMax, and larcv::String2ROIType().
Referenced by ~SegmentFilter().
   {
     auto allowed_par_v = cfg.get<std::vector<std::string> >("Allowed");
     _seg_producer = cfg.get<std::string>("SegProducer");
     _allowed_segment_v.resize((size_t)kROITypeMax,false);
     for(const auto& par : allowed_par_v) {
       auto roi_type = String2ROIType(par);
       _allowed_segment_v[(size_t)roi_type] = true;
     }
     _allowed_segment_v.front() = true;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SegmentFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 50 of file SegmentFilter.cxx.
Referenced by ~SegmentFilter().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SegmentFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 31 of file SegmentFilter.cxx.
Referenced by ~SegmentFilter().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SegmentFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 34 of file SegmentFilter.cxx.
References _allowed_segment_v, _seg_producer, larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_DEBUG, and larcv::ROIType2String().
Referenced by ~SegmentFilter().
   {
     auto ev_seg = (EventImage2D*)mgr.get_data(kProductImage2D,_seg_producer);
     for(size_t plane=0; plane<3; ++plane) {
       for(auto px : ev_seg->Image2DArray()[plane].as_vector()) {
     if (!_allowed_segment_v[(size_t)px]) {
       LARCV_DEBUG() << "... saw px value for px="<<(int)px<< " a " << ROIType2String((ROIType_t)px) << " @ entry= " << mgr.current_entry() << std::endl;
       return false;
     }
       }
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_allowed_segment_v
std::vector<bool> larcv::SegmentFilter::_allowed_segment_v private
Definition at line 47 of file SegmentFilter.h.
Referenced by configure(), and process().
_seg_producer
std::string larcv::SegmentFilter::_seg_producer private
Definition at line 46 of file SegmentFilter.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
SegmentFilter.h
SegmentFilter.cxx