LArCV: larcv::SuperaMCPClusterProcessFactory Class Reference
larcv::SuperaMCPClusterProcessFactory Class Reference
#include <SuperaMCPCluster.h>
Public Member Functions
SuperaMCPClusterProcessFactory ()
ctor
~SuperaMCPClusterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 51 of file SuperaMCPCluster.h.
Constructor & Destructor Documentation
SuperaMCPClusterProcessFactory()
larcv::SuperaMCPClusterProcessFactory::SuperaMCPClusterProcessFactory () inline
ctor
Definition at line 54 of file SuperaMCPCluster.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SuperaMCPCluster",this); }
~SuperaMCPClusterProcessFactory()
larcv::SuperaMCPClusterProcessFactory::~SuperaMCPClusterProcessFactory () inline
dtor
Definition at line 56 of file SuperaMCPCluster.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SuperaMCPClusterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 58 of file SuperaMCPCluster.h.
References larcv::SuperaMCPCluster::SuperaMCPCluster().
 { return new SuperaMCPCluster(instance_name); }
The documentation for this class was generated from the following file:
SuperaMCPCluster.h