LArCV: larcv::SSNetTruthAna Class Reference
larcv::SSNetTruthAna Class Reference
#include <SSNetTruthAna.h>
Public Member Functions
SSNetTruthAna (const std::string name="SSNetTruthAna")
Default constructor.
~SSNetTruthAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
TTree * _tree
int _entry
int _run
int _subrun
int _event
std::string _ev_img2d_prod
std::string _ev_trk2d_prod
std::string _ev_shr2d_prod
std::string _roi_prod
std::string _true_roi_prod
size_t _crop_radius
larutil::SpaceChargeMicroBooNE _sce
float _trkpixel0
float _trkpixel1
float _trkpixel2
float _shrpixel0
float _shrpixel1
float _shrpixel2
float _npixel0
float _npixel1
float _npixel2
float _shr_ratiopixel0
float _shr_ratiopixel1
float _shr_ratiopixel2
float _trk_ratiopixel0
float _trk_ratiopixel1
float _trk_ratiopixel2
float _npixelsum
float _npixelavg
float _trkpixelsum
float _trkpixelavg
float _shrpixelsum
float _shrpixelavg
float _trk_ratiopixelsum
float _trk_ratiopixelavg
float _shr_ratiopixelsum
float _shr_ratiopixelavg
float _n_valid_planes
Detailed Description
Definition at line 10 of file SSNetTruthAna.h.
Constructor & Destructor Documentation
SSNetTruthAna()
larcv::SSNetTruthAna::SSNetTruthAna (const std::string name = "SSNetTruthAna")
Default constructor.
Definition at line 18 of file SSNetTruthAna.cxx.
Referenced by larcv::SSNetTruthAnaProcessFactory::create().
                                                    :
     ProcessBase(name),
     _tree(nullptr)
   {}
~SSNetTruthAna()
larcv::SSNetTruthAna::~SSNetTruthAna () inline
Default destructor.
Definition at line 19 of file SSNetTruthAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SSNetTruthAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 23 of file SSNetTruthAna.cxx.
References _crop_radius, _ev_img2d_prod, _ev_shr2d_prod, _ev_trk2d_prod, _roi_prod, _true_roi_prod, and larcv::PSet::get().
Referenced by ~SSNetTruthAna().
   {
     _ev_img2d_prod   = cfg.get<std::string>("EventImage2DProducer");
     _ev_trk2d_prod   = cfg.get<std::string>("TrackImage2DProducer");
     _ev_shr2d_prod   = cfg.get<std::string>("ShowerImage2DProducer");
     _roi_prod        = cfg.get<std::string>("ROIProducer");
     _true_roi_prod   = cfg.get<std::string>("TrueROIProducer");
     _crop_radius     = cfg.get<size_t>("CropRadius");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SSNetTruthAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 296 of file SSNetTruthAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~SSNetTruthAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SSNetTruthAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 34 of file SSNetTruthAna.cxx.
References _entry, _event, _n_valid_planes, _npixel0, _npixel1, _npixel2, _npixelavg, _npixelsum, _run, _shr_ratiopixel0, _shr_ratiopixel1, _shr_ratiopixel2, _shr_ratiopixelavg, _shr_ratiopixelsum, _shrpixel0, _shrpixel1, _shrpixel2, _shrpixelavg, _shrpixelsum, _subrun, _tree, _trk_ratiopixel0, _trk_ratiopixel1, _trk_ratiopixel2, _trk_ratiopixelavg, _trk_ratiopixelsum, _trkpixel0, _trkpixel1, _trkpixel2, _trkpixelavg, and _trkpixelsum.
Referenced by ~SSNetTruthAna().
   {
     _tree = new TTree("EventCosmicPixelTree","");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("trkpixel0",&_trkpixel0,"_trkpixel0/F");
     _tree->Branch("trkpixel1",&_trkpixel1,"_trkpixel1/F");
     _tree->Branch("trkpixel2",&_trkpixel2,"_trkpixel2/F");
     _tree->Branch("shrpixel0",&_shrpixel0,"_shrpixel0/F");
     _tree->Branch("shrpixel1",&_shrpixel1,"_shrpixel1/F");
     _tree->Branch("shrpixel2",&_shrpixel2,"_shrpixel2/F");
     _tree->Branch("npixel0",&_npixel0,"_npixel0/F");
     _tree->Branch("npixel1",&_npixel1,"_npixel1/F");
     _tree->Branch("npixel2",&_npixel2,"_npixel2/F");
     _tree->Branch("shr_ratiopixel0",&_shr_ratiopixel0,"_shr_ratiopixel0/F");
     _tree->Branch("shr_ratiopixel1",&_shr_ratiopixel1,"_shr_ratiopixel1/F");
     _tree->Branch("shr_ratiopixel2",&_shr_ratiopixel2,"_shr_ratiopixel2/F");
     _tree->Branch("trk_ratiopixel0",&_trk_ratiopixel0,"_trk_ratiopixel0/F");
     _tree->Branch("trk_ratiopixel1",&_trk_ratiopixel1,"_trk_ratiopixel1/F");
     _tree->Branch("trk_ratiopixel2",&_trk_ratiopixel2,"_trk_ratiopixel2/F");
     _tree->Branch("npixelsum",&_npixelsum,"_npixelsum/F");
     _tree->Branch("npixelavg",&_npixelavg,"_npixelavg/F");
     _tree->Branch("trkpixelsum",&_trkpixelsum,"_trkpixelsum/F");
     _tree->Branch("trkpixelavg",&_trkpixelavg,"_trkpixelavg/F");
     _tree->Branch("shrpixelsum",&_shrpixelsum,"_shrpixelsum/F");
     _tree->Branch("shrpixelavg",&_shrpixelavg,"_shrpixelavg/F");
     _tree->Branch("trk_ratiopixelsum",&_trk_ratiopixelsum,"_trk_ratiopixelsum/F");
     _tree->Branch("trk_ratiopixelavg",&_trk_ratiopixelavg,"_trk_ratiopixelavg/F");
     _tree->Branch("shr_ratiopixelsum",&_shr_ratiopixelsum,"_shr_ratiopixelsum/F");
     _tree->Branch("shr_ratiopixelavg",&_shr_ratiopixelavg,"_shr_ratiopixelavg/F");
     _tree->Branch("n_valid_planes",&_n_valid_planes,"_n_valid_planes/F");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SSNetTruthAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 82 of file SSNetTruthAna.cxx.
References _crop_radius, _entry, _ev_img2d_prod, _ev_shr2d_prod, _ev_trk2d_prod, _event, _n_valid_planes, _npixel0, _npixel1, _npixel2, _npixelavg, _npixelsum, _roi_prod, _run, _sce, _shr_ratiopixel0, _shr_ratiopixel1, _shr_ratiopixel2, _shr_ratiopixelavg, _shr_ratiopixelsum, _shrpixel0, _shrpixel1, _shrpixel2, _shrpixelavg, _shrpixelsum, _subrun, _tree, _trk_ratiopixel0, _trk_ratiopixel1, _trk_ratiopixel2, _trk_ratiopixelavg, _trk_ratiopixelsum, _trkpixel0, _trkpixel1, _trkpixel2, _trkpixelavg, _trkpixelsum, _true_roi_prod, larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, and LARCV_DEBUG.
Referenced by ~SSNetTruthAna().
   {
     auto const ev_img2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_img2d_prod));
     if (!ev_img2d) throw larbys("Invalid event image producer provided");
     auto const ev_trk2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_trk2d_prod));
     if (!ev_trk2d) throw larbys("Invalid event trk producer provided");
     auto const ev_shr2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_shr2d_prod));
     if (!ev_shr2d) throw larbys("Invalid event shr producer provided");
     auto const ev_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_prod));
     if (!ev_roi) throw larbys("Invalid ROI producer provided!");
     if (ev_roi->ROIArray().size() == 0) {
       throw larbys("NO ROI??");
     }
     auto const ev_true_roi = (EventROI*)(mgr.get_data(kProductROI,_true_roi_prod));
     const auto& roi = ev_roi->ROIArray().front();
     _run    = (int) ev_img2d->run();
     _subrun = (int) ev_img2d->subrun();
     _event  = (int) ev_img2d->event();
     _entry  = (int) mgr.current_entry();
     LARCV_DEBUG() << "(r,s,e,e)=("<<_run<<","<<_subrun<<","<<_event<<","<<_entry<<")"<<std::endl;
     std::array<size_t,3> trk_pixel_v;
     std::array<size_t,3> shr_pixel_v;
     for(auto& v : trk_pixel_v) v = 0;
     for(auto& v : shr_pixel_v) v = 0;
     const auto& nu_roi = ev_true_roi->ROIArray().front();
     LARCV_DEBUG() << "PDG: " << nu_roi.PdgCode() << std::endl;
     auto tx = nu_roi.X();
     auto ty = nu_roi.Y();
     auto tz = nu_roi.Z();
     auto tt = nu_roi.T();
     auto const offset = _sce.GetPosOffsets(tx,ty,tz);
     auto scex = tx - offset[0] + 0.7;
     auto scey = ty + offset[1];
     auto scez = tz + offset[2];
     auto geo  = larutil::Geometry::GetME();
     auto larp = larutil::LArProperties::GetME();
     double xyz[3];
     double wire_v[3];
     const double tick = (scex / larp->DriftVelocity() + 4) * 2. + 3200.;
     xyz[0] = scex;
     xyz[1] = scey;
     xyz[2] = scez;
     try {
       wire_v[0] = geo->NearestWire(xyz,0);
       wire_v[1] = geo->NearestWire(xyz,1);
       wire_v[2] = geo->NearestWire(xyz,2);
     } catch(const std::exception& e) {
       throw larbys("Could not find nearest wire");
     }
     float n_valid_planes = 0;
     for (size_t plane=0; plane<3; ++plane) {
       const auto& img2d = ev_img2d->Image2DArray().at(plane);
       const auto& trk2d = ev_trk2d->Image2DArray().at(plane);
       const auto& shr2d = ev_shr2d->Image2DArray().at(plane);
       const auto& bb = roi.BB(plane);
       auto const& wire = wire_v[plane];
       float xpixel = -1.0;
       float ypixel = -1.0;
       if( bb.min_x() <= wire && wire <= bb.max_x() &&
       bb.min_y() <= tick && tick <= bb.max_y() ) {
     xpixel = wire - bb.min_x();
     ypixel = (tick - bb.min_y()) / 6.0;
     LARCV_DEBUG() << "Set (xpixel,ypixel)=("<<xpixel<<","<<ypixel<<")"<<std::endl;
     n_valid_planes +=1;
       } else { continue; }
       auto crop_img2d  = img2d.crop(bb);
       auto crop_trk2d  = trk2d.crop(bb);
       auto crop_shr2d  = shr2d.crop(bb);
       crop_img2d.threshold(10,0);
       crop_shr2d.threshold(10,0);
       crop_trk2d.threshold(10,0);
       size_t trk_pixels = 0;
       size_t shr_pixels = 0;
       ypixel = crop_img2d.meta().rows() - ypixel;
       // auto mat0 = as_gray_mat(crop_img2d,0,255,1);
       // auto mat1 = as_gray_mat(crop_trk2d,0,255,1);
       // auto mat2 = as_gray_mat(crop_shr2d,0,255,1);
       // cv::threshold(mat0,mat0,1,255,1);
       // cv::threshold(mat1,mat1,1,255,1);
       // cv::threshold(mat2,mat2,1,255,1);
       // auto mat3 = mat2.clone();
       // mat3.setTo(cv::Scalar(255.0));
       // mat3.at<uchar>((int)ypixel,(int)xpixel) = (uchar)0.0;
       // if (plane==0) {
       //    cv::imwrite("img0.png"   ,mat0);
       //    cv::imwrite("trk0.png"   ,mat1);
       //    cv::imwrite("shr0.png"   ,mat2);
       //    cv::imwrite("vtx0.png"   ,mat3);
       // }
       // if (plane==1) {
       //    cv::imwrite("img1.png"   ,mat0);
       //    cv::imwrite("trk1.png"   ,mat1);
       //    cv::imwrite("shr1.png"   ,mat2);
       //    cv::imwrite("vtx1.png"   ,mat3);
       // }
       // if (plane==2) {
       //    cv::imwrite("img2.png"   ,mat0);
       //    cv::imwrite("trk2.png"   ,mat1);
       //    cv::imwrite("shr2.png"   ,mat2);
       //    cv::imwrite("vtx2.png"   ,mat3);
       // }
       for(size_t row=0; row < crop_img2d.meta().rows(); ++row) {
     for(size_t col=0; col < crop_img2d.meta().cols(); ++col) {
       auto trk_px   = crop_trk2d.pixel(row,col);
       auto shr_px   = crop_shr2d.pixel(row,col);
       float dx = std::pow((float)row - (float)ypixel,2);
       float dy = std::pow((float)col - (float)xpixel,2);
       float dd =  dx + dy;
       dd = std::sqrt(dd);
       if (dd < (float)_crop_radius) {
         if (trk_px) trk_pixels++;
         if (shr_px) shr_pixels++;
       }
     }
       }
       shr_pixel_v[plane] = shr_pixels;
       trk_pixel_v[plane] = trk_pixels;
       // if ((shr_pixels + trk_pixels) == 0) {
       //    LARCV_CRITICAL() << "Vertex @plane="<<plane<<" & no pixels encountered" <<std::endl;
       //    throw larbys();
       // }
     }
     //
     // ROI region
     //
     _trkpixel0 = trk_pixel_v[0];
     _trkpixel1 = trk_pixel_v[1];
     _trkpixel2 = trk_pixel_v[2];
     _shrpixel0 = shr_pixel_v[0];
     _shrpixel1 = shr_pixel_v[1];
     _shrpixel2 = shr_pixel_v[2];
     _npixel0 = _trkpixel0 + _shrpixel0;
     _npixel1 = _trkpixel1 + _shrpixel1;
     _npixel2 = _trkpixel2 + _shrpixel2;
     _shr_ratiopixel0 = _npixel0 ? (float)_shrpixel0 / (float)_npixel0 : 0;
     _shr_ratiopixel1 = _npixel1 ? (float)_shrpixel1 / (float)_npixel1 : 0;
     _shr_ratiopixel2 = _npixel2 ? (float)_shrpixel2 / (float)_npixel2 : 0;
     _trk_ratiopixel0 = _npixel0 ? (float)_trkpixel0 / (float)_npixel0 : 0;
     _trk_ratiopixel1 = _npixel1 ? (float)_trkpixel1 / (float)_npixel1 : 0;
     _trk_ratiopixel2 = _npixel2 ? (float)_trkpixel2 / (float)_npixel2 : 0;
     _npixelsum = _npixel0 + _npixel1 + _npixel2;
     _npixelavg = _npixelsum / n_valid_planes;
     _trkpixelsum = _trkpixel0 + _trkpixel1 + _trkpixel2;
     _trkpixelavg = _trkpixelsum / n_valid_planes;
     _shrpixelsum = _shrpixel0 + _shrpixel1 + _shrpixel2;
     _shrpixelavg = _shrpixelsum / n_valid_planes;
     _trk_ratiopixelsum = _trk_ratiopixel0 + _trk_ratiopixel1 + _trk_ratiopixel2;
     _trk_ratiopixelavg = _trk_ratiopixelsum / n_valid_planes;
     _shr_ratiopixelsum = _shr_ratiopixel0 + _shr_ratiopixel1 + _shr_ratiopixel2;
     _shr_ratiopixelavg = _shr_ratiopixelsum / n_valid_planes;
     _n_valid_planes = n_valid_planes;
     _tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_crop_radius
size_t larcv::SSNetTruthAna::_crop_radius private
Definition at line 45 of file SSNetTruthAna.h.
Referenced by configure(), and process().
_entry
int larcv::SSNetTruthAna::_entry private
Definition at line 34 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_ev_img2d_prod
std::string larcv::SSNetTruthAna::_ev_img2d_prod private
Definition at line 39 of file SSNetTruthAna.h.
Referenced by configure(), and process().
_ev_shr2d_prod
std::string larcv::SSNetTruthAna::_ev_shr2d_prod private
Definition at line 41 of file SSNetTruthAna.h.
Referenced by configure(), and process().
_ev_trk2d_prod
std::string larcv::SSNetTruthAna::_ev_trk2d_prod private
Definition at line 40 of file SSNetTruthAna.h.
Referenced by configure(), and process().
_event
int larcv::SSNetTruthAna::_event private
Definition at line 37 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_n_valid_planes
float larcv::SSNetTruthAna::_n_valid_planes private
Definition at line 84 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_npixel0
float larcv::SSNetTruthAna::_npixel0 private
Definition at line 57 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_npixel1
float larcv::SSNetTruthAna::_npixel1 private
Definition at line 58 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_npixel2
float larcv::SSNetTruthAna::_npixel2 private
Definition at line 59 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_npixelavg
float larcv::SSNetTruthAna::_npixelavg private
Definition at line 70 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_npixelsum
float larcv::SSNetTruthAna::_npixelsum private
Definition at line 69 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_roi_prod
std::string larcv::SSNetTruthAna::_roi_prod private
Definition at line 43 of file SSNetTruthAna.h.
Referenced by configure(), and process().
_run
int larcv::SSNetTruthAna::_run private
Definition at line 35 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_sce
larutil::SpaceChargeMicroBooNE larcv::SSNetTruthAna::_sce private
Definition at line 47 of file SSNetTruthAna.h.
Referenced by process().
_shr_ratiopixel0
float larcv::SSNetTruthAna::_shr_ratiopixel0 private
Definition at line 61 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shr_ratiopixel1
float larcv::SSNetTruthAna::_shr_ratiopixel1 private
Definition at line 62 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shr_ratiopixel2
float larcv::SSNetTruthAna::_shr_ratiopixel2 private
Definition at line 63 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shr_ratiopixelavg
float larcv::SSNetTruthAna::_shr_ratiopixelavg private
Definition at line 82 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shr_ratiopixelsum
float larcv::SSNetTruthAna::_shr_ratiopixelsum private
Definition at line 81 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shrpixel0
float larcv::SSNetTruthAna::_shrpixel0 private
Definition at line 53 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shrpixel1
float larcv::SSNetTruthAna::_shrpixel1 private
Definition at line 54 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shrpixel2
float larcv::SSNetTruthAna::_shrpixel2 private
Definition at line 55 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shrpixelavg
float larcv::SSNetTruthAna::_shrpixelavg private
Definition at line 76 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_shrpixelsum
float larcv::SSNetTruthAna::_shrpixelsum private
Definition at line 75 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_subrun
int larcv::SSNetTruthAna::_subrun private
Definition at line 36 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::SSNetTruthAna::_tree private
Definition at line 31 of file SSNetTruthAna.h.
Referenced by finalize(), initialize(), and process().
_trk_ratiopixel0
float larcv::SSNetTruthAna::_trk_ratiopixel0 private
Definition at line 65 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trk_ratiopixel1
float larcv::SSNetTruthAna::_trk_ratiopixel1 private
Definition at line 66 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trk_ratiopixel2
float larcv::SSNetTruthAna::_trk_ratiopixel2 private
Definition at line 67 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trk_ratiopixelavg
float larcv::SSNetTruthAna::_trk_ratiopixelavg private
Definition at line 79 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trk_ratiopixelsum
float larcv::SSNetTruthAna::_trk_ratiopixelsum private
Definition at line 78 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trkpixel0
float larcv::SSNetTruthAna::_trkpixel0 private
Definition at line 49 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trkpixel1
float larcv::SSNetTruthAna::_trkpixel1 private
Definition at line 50 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trkpixel2
float larcv::SSNetTruthAna::_trkpixel2 private
Definition at line 51 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trkpixelavg
float larcv::SSNetTruthAna::_trkpixelavg private
Definition at line 73 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_trkpixelsum
float larcv::SSNetTruthAna::_trkpixelsum private
Definition at line 72 of file SSNetTruthAna.h.
Referenced by initialize(), and process().
_true_roi_prod
std::string larcv::SSNetTruthAna::_true_roi_prod private
Definition at line 44 of file SSNetTruthAna.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
SSNetTruthAna.h
SSNetTruthAna.cxx