LArCV: larcv::LArbysImagePID Class Reference
larcv::LArbysImagePID Class Reference
#include <LArbysImagePID.h>
Public Member Functions
LArbysImagePID (const std::string name="LArbysImagePID", const std::vector< std::string > particle_types={"electron", "gamma", "muon", "pion", "proton"}, const std::vector< std::string > interaction_types={"1p1e", "1p1g", "1p1mu", "1p1pi", "2p"})
Default constructor.
~LArbysImagePID ()
Default destructor.
void configure (const PSet &)
void Clear ()
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
bool _use_shape
std::vector< std::string > _particle_types_v
std::vector< std::string > _interaction_types_v
std::vector< std::vector< float > > _rois_score_vv
std::vector< std::vector< std::vector< float > > > _ptype_scores_vvv
std::vector< int > _ptype_ctr_v
std::vector< std::pair< int, int > > _interaction_pair_v
std::vector< float > _score_sum_v
uint _run
uint _subrun
uint _event
uint _entry
bool _verbosity
Detailed Description
Definition at line 30 of file LArbysImagePID.h.
Constructor & Destructor Documentation
LArbysImagePID()
larcv::LArbysImagePID::LArbysImagePID (const std::string name = "LArbysImagePID", const std::vector< std::string > particle_types = {"electron", "gamma", "muon", "pion", "proton"}, const std::vector< std::string > interaction_types = {"1p1e", "1p1g", "1p1mu", "1p1pi", "2p"})
Default constructor.
Definition at line 10 of file LArbysImagePID.cxx.
Referenced by larcv::LArbysImagePIDProcessFactory::create().
     : ProcessBase(name)
     , _particle_types_v(particle_types)
     , _interaction_types_v(interaction_types)
   {}
~LArbysImagePID()
larcv::LArbysImagePID::~LArbysImagePID () inline
Default destructor.
Definition at line 40 of file LArbysImagePID.h.
References Clear(), configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
Clear()
void larcv::LArbysImagePID::Clear ()
Definition at line 18 of file LArbysImagePID.cxx.
References _interaction_pair_v, _ptype_ctr_v, _ptype_scores_vvv, _rois_score_vv, and _score_sum_v.
Referenced by process(), and ~LArbysImagePID().
{
     _ptype_ctr_v.clear();
     _ptype_ctr_v.resize(5,0);
     _rois_score_vv.clear();
     _rois_score_vv.resize(2);
     _ptype_scores_vvv.clear();
     _score_sum_v.clear();
     _interaction_pair_v.clear();
     //_roi_score.resize(5,0.0);
     //_rois_score_vv[0]=_roi_score;
     //_rois_score_vv[1]=_roi_score;
   }
configure()
void larcv::LArbysImagePID::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 36 of file LArbysImagePID.cxx.
References _use_shape, _verbosity, and larcv::PSet::get().
Referenced by ~LArbysImagePID().
   {
     _use_shape = cfg.get<bool>("UseShape");
     _verbosity = cfg.get<bool>("Verbosity");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImagePID::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 139 of file LArbysImagePID.cxx.
Referenced by ~LArbysImagePID().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImagePID::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 42 of file LArbysImagePID.cxx.
Referenced by ~LArbysImagePID().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::LArbysImagePID::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 45 of file LArbysImagePID.cxx.
References _entry, _event, _ptype_ctr_v, _ptype_scores_vvv, _rois_score_vv, _run, _score_sum_v, _subrun, _use_shape, _verbosity, Clear(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductPGraph, LARCV_CRITICAL, and LARCV_DEBUG.
Referenced by ~LArbysImagePID().
   {
     Clear();
     _ptype_ctr_v.resize(5,0);
     auto ev_pgraph = (EventPGraph*)mgr.get_data(kProductPGraph,"test");
     _run    = ev_pgraph->run();
     _subrun = ev_pgraph->subrun();
     _event  = ev_pgraph->event();
     _entry  = mgr.current_entry();
     auto pgraphs = ev_pgraph->PGraphArray();
     LARCV_DEBUG()<< "Entry: "<<_entry
          <<", Run: "<<_run
          <<", Subrun: "<<_subrun
          <<", Event: "<<_event
          <<", has "<<pgraphs.size()<<" vertices."
          <<std::endl;
     _ptype_scores_vvv.resize(pgraphs.size());
     _score_sum_v.resize(pgraphs.size(),0.0);
     LARCV_DEBUG()<<"number of vtx is "<<pgraphs.size()<<std::endl;
     std::vector<std::vector<float>> ptype_scor(2, std::vector<float>(5,0.0));
     for(auto &ptype_score : _ptype_scores_vvv) ptype_score = ptype_scor;
     for (size_t vtx_idx=0; vtx_idx< pgraphs.size(); ++vtx_idx)
       {
     auto rois_obj = pgraphs[vtx_idx];
     if (rois_obj.NumParticles()!=2){
       LARCV_CRITICAL()<<"    The vertex has >>>> "<< rois_obj.NumParticles()<<" <<<< rois !"<<std::endl;
       //throw larbys("Go to match, LArbysImageFilter(LArbysImage)");
     }
     auto rois = rois_obj.ParticleArray();
     for (int roi_idx=0; roi_idx<2; ++roi_idx){
       auto roi = rois[roi_idx];
       _rois_score_vv[roi_idx] = roi.TypeScore();
       if (_use_shape){
         if (roi.Shape()==0&& roi.Type()==0){
           _ptype_ctr_v[roi.Type()]++;
           _ptype_scores_vvv[vtx_idx][roi_idx][roi.Type()]=roi.TypeScore()[roi.Type()];
         }
         if (roi.Shape()==0&& roi.Type()==1){
           _ptype_ctr_v[roi.Type()]++;
           _ptype_scores_vvv[vtx_idx][roi_idx][roi.Type()]=roi.TypeScore()[roi.Type()];
         }
         if (roi.Shape()==1&& roi.Type()==2){
           _ptype_ctr_v[roi.Type()]++;
           _ptype_scores_vvv[vtx_idx][roi_idx][roi.Type()]=roi.TypeScore()[roi.Type()];
         }
         if (roi.Shape()==0&& roi.Type()==3){
           _ptype_ctr_v[roi.Type()]++;
           _ptype_scores_vvv[vtx_idx][roi_idx][roi.Type()]=roi.TypeScore()[roi.Type()];
         }
         if (roi.Shape()==1&& roi.Type()==4){
           _ptype_ctr_v[roi.Type()]++;
           _ptype_scores_vvv[vtx_idx][roi_idx][roi.Type()]=roi.TypeScore()[roi.Type()];
         }
       }
       if(!_use_shape){
         for (int type=0; type<5; ++type){
           if (roi.Type()==type) {
         _ptype_ctr_v[type]++;
         _ptype_scores_vvv[vtx_idx][roi_idx][type]=roi.TypeScore()[type];
         _score_sum_v[vtx_idx]+=roi.TypeScore()[type];
           }
         }
       }
       //LARCV_DEBUG()<<roi.Index()<<std::endl;
       //LARCV_DEBUG()<<particle_types[roi.Type()]<<std::endl;
     }
     for (auto x : _ptype_ctr_v) if(_verbosity) std::cout<< x <<" ";
     if(_verbosity) std::cout<<std::endl;
     for (auto scores : _rois_score_vv) {
       for (auto score : scores) if(_verbosity) std::cout<<score<<" ";
       if(_verbosity) std::cout<<std::endl;
     }
     if(_verbosity) std::cout<<std::endl;
     for (auto scores : _ptype_scores_vvv) {
       for (auto score : scores) {
         for (auto scor : score)if(_verbosity) std::cout<<scor<<" ";
       }
       if(_verbosity) std::cout<<std::endl;
     }
     if(_verbosity) std::cout<<std::endl;
     _ptype_ctr_v.clear();
     _ptype_ctr_v.resize(5,0);
       }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_entry
uint larcv::LArbysImagePID::_entry private
Definition at line 71 of file LArbysImagePID.h.
Referenced by process().
_event
uint larcv::LArbysImagePID::_event private
Definition at line 70 of file LArbysImagePID.h.
Referenced by process().
_interaction_pair_v
std::vector<std::pair<int, int> > larcv::LArbysImagePID::_interaction_pair_v private
Definition at line 64 of file LArbysImagePID.h.
Referenced by Clear().
_interaction_types_v
std::vector<std::string> larcv::LArbysImagePID::_interaction_types_v private
Definition at line 57 of file LArbysImagePID.h.
_particle_types_v
std::vector<std::string> larcv::LArbysImagePID::_particle_types_v private
Definition at line 56 of file LArbysImagePID.h.
_ptype_ctr_v
std::vector<int> larcv::LArbysImagePID::_ptype_ctr_v private
Definition at line 62 of file LArbysImagePID.h.
Referenced by Clear(), and process().
_ptype_scores_vvv
std::vector<std::vector<std::vector<float> > > larcv::LArbysImagePID::_ptype_scores_vvv private
Definition at line 61 of file LArbysImagePID.h.
Referenced by Clear(), and process().
_rois_score_vv
std::vector<std::vector<float> > larcv::LArbysImagePID::_rois_score_vv private
Definition at line 59 of file LArbysImagePID.h.
Referenced by Clear(), and process().
_run
uint larcv::LArbysImagePID::_run private
Definition at line 68 of file LArbysImagePID.h.
Referenced by process().
_score_sum_v
std::vector<float> larcv::LArbysImagePID::_score_sum_v private
Definition at line 66 of file LArbysImagePID.h.
Referenced by Clear(), and process().
_subrun
uint larcv::LArbysImagePID::_subrun private
Definition at line 69 of file LArbysImagePID.h.
Referenced by process().
_use_shape
bool larcv::LArbysImagePID::_use_shape private
Definition at line 54 of file LArbysImagePID.h.
Referenced by configure(), and process().
_verbosity
bool larcv::LArbysImagePID::_verbosity private
Definition at line 73 of file LArbysImagePID.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
LArbysImagePID.h
LArbysImagePID.cxx