LArCV: larcv::ReadJarrettFile Class Reference
larcv::ReadJarrettFile Class Reference
#include <ReadJarrettFile.h>
Public Member Functions
ReadJarrettFile (const std::string name="ReadJarrettFile")
Default constructor.
~ReadJarrettFile ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void SetSplineLocation (const std::string &fpath)
void SetLLOutName (const std::string &foutll)
bool IsGoodVertex (int run, int subrun, int event, int vtxID)
bool IsGoodEntry (int run, int subrun, int event)
void ReadVertexFile (std::string filename)
std::vector< TVector3 > GetJarretVertex (int run, int subrun, int event)
void finalize ()
void MCevaluation ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
int iTrack
larlite::storage_manager _storage
larcv::AStarTracker tracker
std::vector< std::vector< int > > _vertexInfo
TH2D * hEcomp
TH1D * hAverageIonization
TH1D * hEcomp1D
TH1D * hEcomp1D_m
TH1D * hEcomp1D_p
TH2D * hEcomp_m
TH2D * hEcomp_p
TH1D * hEnuReco
TH1D * hEnuTh
TH2D * hEnuvsPM_th
TH1D * hPM_th_Reco_1D
TH2D * hPM_th_Reco
TH2D * hEnuComp
TH1D * hEnuComp1D
double NeutrinoEnergyTh
double NeutrinoEnergyReco
TH2D * hEcompdQdx
TH2D * hIonvsLength
double Ep_t
double Em_t
int run
int subrun
int event
int _vtx_id
int NvertexSubmitted
int NgoodReco
int NtracksReco
std::vector< std::string > checkEvents
std::string _filename
TTree * _recoTree
std::vector< int > _trk_id_v
std::vector< double > _E_muon_v
std::vector< double > _E_proton_v
std::vector< double > _Length_v
std::vector< double > _Avg_Ion_v
std::vector< double > _vertexPhi
std::vector< double > _vertexTheta
std::vector< double > _closestWall
std::vector< double > _closestWallSCE
std::vector< double > _Ion_5cm_v
std::vector< double > _Ion_10cm_v
std::vector< double > _Ion_tot_v
std::vector< double > _IondivLength_v
std::vector< std::vector< double > > _Angle_v
std::vector< bool > _Reco_goodness_v
std::vector< larlite::event_track > _EventRecoVertices
TVector3 MCvertex
TVector3 RecoVertex
TVector3 RecoVertex_SCE
bool GoodVertex
bool _missingTrack
bool _nothingReconstructed
bool _tooShortDeadWire
bool _tooShortFaintTrack
bool _tooManyTracksAtVertex
bool _possibleCosmic
bool _possiblyCrossing
bool _branchingTracks
bool _jumpingTracks
bool _isMC
std::string _input_pgraph_producer
std::string _spline_file
std::string _foutll
Detailed Description
Definition at line 37 of file ReadJarrettFile.h.
Constructor & Destructor Documentation
ReadJarrettFile()
larcv::ReadJarrettFile::ReadJarrettFile (const std::string name = "ReadJarrettFile")
Default constructor.
Definition at line 52 of file ReadJarrettFile.cxx.
Referenced by larcv::ReadJarrettFileProcessFactory::create().
     : ProcessBase(name),
     _foutll("larlite_reco3D.root"),
     _spline_file("")
     {}
~ReadJarrettFile()
larcv::ReadJarrettFile::~ReadJarrettFile () inline
Default destructor.
Definition at line 45 of file ReadJarrettFile.h.
References configure(), initialize(), process(), and SetSplineLocation().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ReadJarrettFile::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 58 of file ReadJarrettFile.cxx.
References _input_pgraph_producer, _isMC, and larcv::PSet::get().
Referenced by ~ReadJarrettFile().
     {
         _input_pgraph_producer     = cfg.get<std::string>("InputPgraphProducer");
         _isMC                      = cfg.get<bool>("IsMC");
     }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ReadJarrettFile::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 550 of file ReadJarrettFile.cxx.
References _recoTree, _storage, larcv::ProcessBase::ana_file(), event, larcv::AStarTracker::finalize(), larcv::ProcessBase::has_ana_file(), hAverageIonization, hEcomp, hEcomp1D, hEcomp1D_m, hEcomp1D_p, hEcomp_m, hEcomp_p, hEcompdQdx, hEnuComp, hEnuComp1D, hEnuReco, hEnuTh, hEnuvsPM_th, hIonvsLength, hPM_th_Reco, hPM_th_Reco_1D, NgoodReco, NvertexSubmitted, run, subrun, and tracker.
Referenced by SetLLOutName().
     {
         std::cout << NvertexSubmitted << " vertex submitted" << std::endl;
         std::cout << NgoodReco << " well reconstructed vertices" << std::endl;
         std::cout << NgoodReco*100./NvertexSubmitted << " % efficiency" << std::endl;
         std::cout << "saving root files?...";
         if(hEcomp->GetEntries() > 1){
             std::cout << "... yes" << std::endl;
             hEcomp->SaveAs(Form("hEcomp_%d_%d_%d.root",run,subrun,event));
             hEcomp_p->SaveAs(Form("hEcomp_p_%d_%d_%d.root",run,subrun,event));
             hEcomp_m->SaveAs(Form("hEcomp_m_%d_%d_%d.root",run,subrun,event));
             hEcompdQdx->SaveAs(Form("hEcompdQdx_%d_%d_%d.root",run,subrun,event));
             hEcomp1D->SaveAs(Form("hEcomp1D_%d_%d_%d.root",run,subrun,event));
             hEcomp1D_m->SaveAs(Form("hEcomp1D_m_%d_%d_%d.root",run,subrun,event));
             hEcomp1D_p->SaveAs(Form("hEcomp1D_p_%d_%d_%d.root",run,subrun,event));
             hIonvsLength->SaveAs(Form("hIonvsLength_%d_%d_%d.root",run,subrun,event));
             hAverageIonization->SaveAs(Form("hAverageIonization_%d_%d_%d.root",run,subrun,event));
             hEnuReco->SaveAs(Form("hEnuReco_%d_%d_%d.root",run,subrun,event));
             hEnuTh->SaveAs(Form("hEnuTh_%d_%d_%d.root",run,subrun,event));
             hEnuComp->SaveAs(Form("hEnuComp_%d_%d_%d.root",run,subrun,event));
             hEnuComp1D->SaveAs(Form("hEnuComp1D_%d_%d_%d.root",run,subrun,event));
             hEnuvsPM_th->SaveAs(Form("hEnuvsPM_th_%d_%d_%d.root",run,subrun,event));
             hPM_th_Reco_1D->SaveAs(Form("hPM_th_Reco_1D_%d_%d_%d.root",run,subrun,event));
             hPM_th_Reco->SaveAs(Form("hPM_th_Reco_%d_%d_%d.root",run,subrun,event));
         }
         else{std::cout << "... no" << std::endl;}
         tracker.finalize();
         std::cout << "finalized tracker" << std::endl;
         if(has_ana_file()) {
             ana_file().cd();
             _recoTree->Write();
         }
         std::cout << "wrote _recoTree" << std::endl;
         _storage.close();
         std::cout << "finalized storage" << std::endl;
         hEcomp->Delete();
         hEcomp_p->Delete();
         hEcomp_m->Delete();
         hEcompdQdx->Delete();
         hEcomp1D->Delete();
         hEcomp1D_m->Delete();
         hEcomp1D_p->Delete();
         hIonvsLength->Delete();
         hAverageIonization->Delete();
         hEnuReco->Delete();
         hEnuTh->Delete();
         hEnuComp->Delete();
         hEnuComp1D->Delete();
         hEnuvsPM_th->Delete();
         hPM_th_Reco_1D->Delete();
         hPM_th_Reco->Delete();
     }
GetJarretVertex()
std::vector< TVector3 > larcv::ReadJarrettFile::GetJarretVertex (int run, int subrun, int event)
Definition at line 469 of file ReadJarrettFile.cxx.
References _filename.
Referenced by SetLLOutName().
{
         std::vector<TVector3> vertex_vector;
         std::ifstream file(Form("%s",_filename.c_str()));
         if(!file){std::cout << "ERROR, could not open file of selected vertices to sort through" << std::endl;return vertex_vector;}
         std::string firstline;
         getline(file, firstline);
         bool goOn = true;
         int Run,SubRun,Event,Entry,ROI_ID,vtxid,rescale_vtxid;
         double x,y,z;
         char coma;
         while(goOn){
             file >> Run >> SubRun >> Event >> Entry >> ROI_ID >> vtxid >> rescale_vtxid >> x >> y >> z ;
             if(run == Run && SubRun == subrun && event == Event){
                 vertex_vector.push_back(TVector3(x,y,z));
             }
             if(file.eof()){goOn=false;break;}
         }
         return vertex_vector;
     }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ReadJarrettFile::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 64 of file ReadJarrettFile.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _closestWall, _closestWallSCE, _E_muon_v, _E_proton_v, _filename, _foutll, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _jumpingTracks, _Length_v, _missingTrack, _nothingReconstructed, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _recoTree, _spline_file, _storage, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _trk_id_v, _vertexPhi, _vertexTheta, _vtx_id, Em_t, Ep_t, event, GoodVertex, hAverageIonization, hEcomp, hEcomp1D, hEcomp1D_m, hEcomp1D_p, hEcomp_m, hEcomp_p, hEcompdQdx, hEnuComp, hEnuComp1D, hEnuReco, hEnuTh, hEnuvsPM_th, hIonvsLength, hPM_th_Reco, hPM_th_Reco_1D, larcv::AStarTracker::initialize(), LARCV_CRITICAL, LARCV_INFO, MCvertex, NgoodReco, NtracksReco, NvertexSubmitted, RecoVertex, RecoVertex_SCE, run, larcv::AStarTracker::SetCompressionFactors(), larcv::AStarTracker::SetDrawOutputs(), larcv::AStarTracker::SetOutputDir(), larcv::AStarTracker::SetSplineFile(), larcv::AStarTracker::SetVerbose(), subrun, and tracker.
Referenced by ~ReadJarrettFile().
     {
         LARCV_INFO() << "[ReadJarrettFile]" << std::endl;
         //SetSplineLocation("Proton_Muon_Range_dEdx_LAr_TSplines.root");
         assert(!_spline_file.empty());
         tracker.SetDrawOutputs(false);
         tracker.SetOutputDir("png");
         tracker.SetSplineFile(_spline_file);
         tracker.initialize();
         tracker.SetCompressionFactors(1,6);
         tracker.SetVerbose(0);
         NvertexSubmitted = 0;
         NgoodReco=0;
         std::string filename;
         //if(_isMC)filename="/Volumes/DataStorage/DeepLearningData/VertexedFiles/NuMuSelection_10-5.txt";
         //if(!_isMC)filename = "/Volumes/DataStorage/DeepLearningData/data_5e19/EXTBNB/EXTBNBSelected.txt";
         std::cout << filename << std::endl;
         _filename = filename;
         //if(_isMC)ReadVertexFile(filename);// when using runall.sh
         //ReadVertexFile(filename);// when running on extBNB numu
         hEcomp             = new TH2D("hEcomp","hEcomp;E_th;E_reco",100,0,1000,100,0,1000);
         hEcomp_m           = new TH2D("hEcomp_m","hEcomp_m;E_th;E_reco",100,0,1000,100,0,1000);
         hEcomp_p           = new TH2D("hEcomp_p","hEcomp_p;E_th;E_reco",100,0,1000,100,0,1000);
         hEcomp1D           = new TH1D("hEcomp1D","hEcomp1D; (E_{reco}-E_{truth})/E_{truth}",500,-2,8);
         hEcomp1D_m         = new TH1D("hEcomp1D_m","hEcomp1D_m; (E_{reco}-E_{truth})/E_{truth}",1000,-2,2);
         hEcomp1D_p         = new TH1D("hEcomp1D_p","hEcomp1D_p; (E_{reco}-E_{truth})/E_{truth}",1000,-2,2);
         hAverageIonization = new TH1D("hAverageIonization","hAverageIonization",100,0,10000);
         hEnuReco           = new TH1D("hEnuReco","hEnuReco; E_{#nu, reco} (MeV)",200,0,2000);
         hEnuTh             = new TH1D("hEnuTh","hEnuTh;E_{#nu, th} (MeV)",200,0,2000);
         hEcompdQdx         = new TH2D("hEcompdQdx","hEcompdQdx;AverageADCperPix/L;(E_{reco}-E_{truth})/E_{truth}",100,0,1000,100,-2,8);
         hIonvsLength       = new TH2D("hIonvsLength","hIonvsLength;L [cm];AverageADCperPix",100,0,1000,100,0,10000);
         hEnuComp           = new TH2D("hEnuComp","hEnuComp;hEnuTh (MeV);hEnuReco (MeV)",200,0,2000,200,0,2000);
         hEnuComp1D         = new TH1D("hEnuComp1D","hEnuComp1D;(E_{reco}-E_{truth})/E_{truth}",1000,-2,2);
         hEnuvsPM_th        = new TH2D("hEnuvsPM_th","hEnuvsPM_th;E_{#nu};E_{p}+E_{m}",200,0,2000,200,0,2000);
         hPM_th_Reco_1D     = new TH1D("hPM_th_Reco_1D","hPM_th_Reco_1D;(E_{p+m reco}-E_{p+m th})/E_{p+m th}",1000,-2,2);
         hPM_th_Reco        = new TH2D("hPM_th_Reco","hPM_th_Reco;E_{p+m th};E_{p+m reco}",200,0,2000,200,0,2000);
         _recoTree = new TTree("_recoTree","_recoTree");
         _recoTree->Branch("run",&run);
         _recoTree->Branch("subrun",&subrun);
         _recoTree->Branch("event",&event);
         _recoTree->Branch("vtx_id", &_vtx_id , "vtx_id/I");
         _recoTree->Branch("trk_id_v", &_trk_id_v);
         _recoTree->Branch("NtracksReco",&NtracksReco);
         _recoTree->Branch("E_muon_v",&_E_muon_v);
         _recoTree->Branch("E_proton_v",&_E_proton_v);
         _recoTree->Branch("Length_v",&_Length_v);
         _recoTree->Branch("Avg_Ion_v",&_Avg_Ion_v);
         _recoTree->Branch("Ion_5cm_v",&_Ion_5cm_v);
         _recoTree->Branch("Ion_10cm_v",&_Ion_10cm_v);
         _recoTree->Branch("Ion_tot_v",&_Ion_tot_v);
         _recoTree->Branch("_IondivLength_v",&_IondivLength_v);
         _recoTree->Branch("Angle_v",&_Angle_v);
         _recoTree->Branch("Ep_t", &Ep_t);
         _recoTree->Branch("Em_t", &Em_t);
         _recoTree->Branch("Reco_goodness_v",&_Reco_goodness_v);
         _recoTree->Branch("GoodVertex",&GoodVertex);
         _recoTree->Branch("missingTrack",&_missingTrack);
         _recoTree->Branch("nothingReconstructed",&_nothingReconstructed);
         _recoTree->Branch("tooShortDeadWire",&_tooShortDeadWire);
         _recoTree->Branch("tooShortFaintTrack",&_tooShortFaintTrack);
         _recoTree->Branch("tooManyTracksAtVertex",&_tooManyTracksAtVertex);
         _recoTree->Branch("possibleCosmic",&_possibleCosmic);
         _recoTree->Branch("possiblyCrossing",&_possiblyCrossing);
         _recoTree->Branch("branchingTracks",&_branchingTracks);
         _recoTree->Branch("jumpingTracks",&_jumpingTracks);
         _recoTree->Branch("RecoVertex",&RecoVertex);
     _recoTree->Branch("RecoVertex_SCE",&RecoVertex_SCE);
         _recoTree->Branch("MCvertex",&MCvertex);
         _recoTree->Branch("vertexPhi",&_vertexPhi);
         _recoTree->Branch("vertexTheta",&_vertexTheta);
         _recoTree->Branch("closestWall",&_closestWall);
     _recoTree->Branch("closestWallSCE",&_closestWallSCE);
         if (_foutll.empty()) throw larbys("specify larlite file output name");
         _storage.set_io_mode(larlite::storage_manager::kWRITE);
         _storage.set_out_filename(_foutll);
         if(!_storage.open()) {
             LARCV_CRITICAL() << "ERROR, larlite output file could not open" << std::endl;
             throw larbys("die");
         }
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
IsGoodEntry()
bool larcv::ReadJarrettFile::IsGoodEntry (int run, int subrun, int event)
Definition at line 426 of file ReadJarrettFile.cxx.
References _vertexInfo.
Referenced by SetLLOutName().
{
         bool okVertex = false;
         for(size_t ivertex = 0;ivertex<_vertexInfo.size();ivertex++){
             if(   run    == _vertexInfo[ivertex][0]
                && subrun == _vertexInfo[ivertex][1]
                && event  == _vertexInfo[ivertex][2]
                )okVertex = true;
         }
         return okVertex;
     }
IsGoodVertex()
bool larcv::ReadJarrettFile::IsGoodVertex (int run, int subrun, int event, int vtxID)
Definition at line 412 of file ReadJarrettFile.cxx.
References _vertexInfo.
Referenced by SetLLOutName().
     {
         bool okVertex = false;
         for(size_t ivertex = 0;ivertex<_vertexInfo.size();ivertex++){
             if(   run    == _vertexInfo[ivertex][0]
                && subrun == _vertexInfo[ivertex][1]
                && event  == _vertexInfo[ivertex][2]
                //&& ROIid  == _vertexInfo[ivertex][4]
                && vtxID  == _vertexInfo[ivertex][5]
                )okVertex = true;
         }
         return okVertex;
     }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MCevaluation()
void larcv::ReadJarrettFile::MCevaluation ()
Definition at line 489 of file ReadJarrettFile.cxx.
References _Avg_Ion_v, _Length_v, checkEvents, Em_t, Ep_t, event, larcv::AStarTracker::GetEnergies(), hAverageIonization, hEcomp, hEcomp1D, hEcomp1D_m, hEcomp1D_p, hEcomp_m, hEcomp_p, hEcompdQdx, hEnuComp, hEnuComp1D, hEnuReco, hEnuvsPM_th, hIonvsLength, hPM_th_Reco, hPM_th_Reco_1D, larcv::AStarTracker::IsGoodVertex(), NeutrinoEnergyTh, run, subrun, and tracker.
Referenced by process(), and SetLLOutName().
{
         std::cout << "MCevaluation()" << std::endl;
         std::vector< std::vector<double> > Energies_v = tracker.GetEnergies();
         //_Length_v = tracker.GetVertexLength();
         if(!tracker.IsGoodVertex()){std::cout << "error: is not good vertex" << std::endl;return;}
         if(_Avg_Ion_v.size()!=2){std::cout << "error: _Avg_Ion_v.size() = " << _Avg_Ion_v.size() << std::endl;return;}
         std::cout << "in store energies : " << std::endl;
         std::cout << Energies_v[0][0] << ":" << Energies_v[0][1] << std::endl;
         std::cout << Energies_v[1][0] << ":" << Energies_v[1][1] << std::endl;
         double Epreco;
         double Emreco;
         if(_Avg_Ion_v[0] > _Avg_Ion_v[1]){
             Epreco = Energies_v[0][0];// first track is proton
             Emreco = Energies_v[1][1];// second track is muon
         }
         else{
             Epreco = Energies_v[1][0]; // second track is proton
             Emreco = Energies_v[0][1]; // first track is muon
         }
         hEcomp->Fill(Ep_t,Epreco);
         hEcomp->Fill(Em_t,Emreco);
         hEcomp_p->Fill(Ep_t,Epreco);
         hEcomp_m->Fill(Em_t,Emreco);
         hEcomp1D->Fill((Epreco-Ep_t)/Ep_t);
         hEcomp1D->Fill((Emreco-Em_t)/Em_t);
         hEcomp1D_p->Fill((Epreco-Ep_t)/Ep_t);
         hEcomp1D_m->Fill((Emreco-Em_t)/Em_t);
         hEnuvsPM_th->Fill(NeutrinoEnergyTh,Ep_t+Em_t);
         hPM_th_Reco_1D->Fill(((Epreco+Emreco)-(Ep_t+Em_t))/(Ep_t+Em_t));
         hPM_th_Reco->Fill(Ep_t+Em_t,Epreco+Emreco);
         hEcompdQdx->Fill(_Avg_Ion_v[1]/_Length_v[1],(Epreco-Ep_t)/Ep_t);
         hEcompdQdx->Fill(_Avg_Ion_v[0]/_Length_v[0],(Emreco-Em_t)/Em_t);
         if( std::abs((Epreco-Ep_t)/Ep_t) > 0.1 || std::abs((Emreco-Em_t)/Em_t) > 0.1 ){
             checkEvents.push_back(Form("%d_%d_%d",run,subrun,event));
         }
         std::cout << "proton : Epreco = " << Epreco << " MeV, Epth : " << Ep_t << " MeV..." << 100*(Epreco-Ep_t)/Ep_t << " %" << std::endl;
         std::cout << "muon   : Emreco = " << Emreco << " MeV, Emth : " << Em_t << " MeV..." << 100*(Emreco-Em_t)/Em_t << " %" << std::endl;
         std::cout << "E nu th   : " << NeutrinoEnergyTh << " MeV" << std::endl;
         std::cout << "E nu Reco : " << Epreco+Emreco << " MeV" << std::endl;
         std::cout << "relative Enu diff: " << 100*((Epreco+Emreco)-NeutrinoEnergyTh)/NeutrinoEnergyTh << " %" << std::endl;
         std::cout << "relative Enu_p+m diff: " << 100*((Epreco+Emreco)-(Ep_t+Em_t))/(Ep_t+Em_t) << " %" << std::endl;
         hEnuReco->Fill(Epreco+Emreco);
         hEnuComp->Fill(NeutrinoEnergyTh,Epreco+Emreco);
         hEnuComp1D->Fill(((Epreco+Emreco)-NeutrinoEnergyTh)/NeutrinoEnergyTh);
         for(size_t itrack = 0;itrack<_Avg_Ion_v.size();itrack++){
             hAverageIonization->Fill(_Avg_Ion_v[itrack]);
             hIonvsLength->Fill(_Length_v[itrack],_Avg_Ion_v[itrack]);
         }
     }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ReadJarrettFile::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 155 of file ReadJarrettFile.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _closestWall, _closestWallSCE, _E_muon_v, _E_proton_v, _input_pgraph_producer, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _isMC, _jumpingTracks, _Length_v, _missingTrack, _nothingReconstructed, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _recoTree, _storage, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _trk_id_v, _vertexPhi, _vertexTheta, _vtx_id, larcv::IOManager< T >::current_entry(), Em_t, Ep_t, event, larcv::IOManager< T >::get_data(), larcv::IOManager< T >::get_n_entries(), larcv::AStarTracker::GetAverageIonization(), larcv::AStarTracker::GetClosestWall(), larcv::AStarTracker::GetClosestWall_SCE(), larcv::AStarTracker::GetEnergies(), larcv::AStarTracker::GetRecoGoodness(), larcv::AStarTracker::GetReconstructedVertexTracks(), larcv::AStarTracker::GetTotalIonization(), larcv::AStarTracker::GetVertexAngle(), larcv::AStarTracker::GetVertexLength(), larcv::AStarTracker::GetVertexPhi(), larcv::AStarTracker::GetVertexTheta(), GoodVertex, hEnuTh, larcv::AStarTracker::IsGoodVertex(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductROI, MCevaluation(), MCvertex, NeutrinoEnergyTh, NgoodReco, NtracksReco, NvertexSubmitted, larcv::AStarTracker::ReconstructVertex(), RecoVertex, RecoVertex_SCE, larcv::EventROI::ROIArray(), run, larcv::AStarTracker::SetOriginalImage(), larcv::AStarTracker::SetSingleVertex(), larcv::AStarTracker::SetTaggedImage(), larcv::AStarTracker::SetTrackInfo(), subrun, and tracker.
Referenced by ~ReadJarrettFile().
     {
         std::cout << std::endl;
         std::cout << "============================================" << std::endl;
         std::cout << "Entry " << mgr.current_entry() << " / " << mgr.get_n_entries() << std::endl;
         std::cout << "============================================" << std::endl;
         gStyle->SetOptStat(0);
         TVector3 vertex(-1,-1,-1);
     TVector3 vertex_SCE(-1,-1,-1);
         TVector3 endPoint[2];
         MCvertex.SetXYZ(-1,-1,-1);
     larutil::SpaceChargeMicroBooNE sce;
         auto ev_pgraph_v     = (EventPGraph*) mgr.get_data(kProductPGraph,_input_pgraph_producer); // for BNB 5e19, comment when EXTBNB
         run    = ev_pgraph_v->run();
         subrun = ev_pgraph_v->subrun();
         event  = ev_pgraph_v->event();
         larlite::event_track* track_ptr = (larlite::event_track*)_storage.get_data(larlite::data::kTrack,"trackReco");
         larlite::event_vertex* vertex_ptr = (larlite::event_vertex*)_storage.get_data(larlite::data::kVertex,"trackReco");
         if(ev_pgraph_v->PGraphArray().size()==0){_storage.set_id(run,subrun,event);_storage.next_event(true); return true;}
         //if(_isMC && !IsGoodEntry(run,subrun,event)){_storage.set_id(run,subrun,event);_storage.next_event(true); return true;}
         auto ev_img_v           = (EventImage2D*)mgr.get_data(kProductImage2D,"wire");
         auto tag_img_thru_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"thrumutags");
         auto tag_img_stop_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"stopmutags");
         //auto ev_pcluster_v = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_img");
         //auto ev_ctor_v     = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_ctor");
         // get the event clusters and full images
         //auto const& ctor_m = ev_ctor_v->Pixel2DClusterArray();
         auto full_adc_img_v = &(ev_img_v->Image2DArray());
         auto full_tag_img_thru_v = &(tag_img_thru_v->Image2DArray());
         auto full_tag_img_stop_v = &(tag_img_stop_v->Image2DArray());
         Ep_t = -1;
         Em_t = -1;
         EventROI *ev_partroi_v = 0;
         std::vector<larcv::ROI> mc_roi_v;
         std::vector<TVector3> MCVertices;
         //____________________
         // get MC vertex info
         //--------------------
         if(_isMC){
             ev_partroi_v= (EventROI*)mgr.get_data(kProductROI,"segment");
             mc_roi_v = ev_partroi_v->ROIArray();
             std::vector<TVector3> MuonVertices;
             std::vector<TVector3> ProtonVertices;
             std::vector<TVector3> ElectronVertices;
             std::vector<TVector3> MuonEndPoint;
             std::vector<TVector3> ProtonEndPoint;
             std::vector<TVector3> ElectronEndPoint;
             for(size_t iMC = 0;iMC<mc_roi_v.size();iMC++){
                 if(mc_roi_v[iMC].PdgCode() == 14){
                     NeutrinoEnergyTh = mc_roi_v[iMC].EnergyDeposit();
                     hEnuTh->Fill(NeutrinoEnergyTh);
                     std::cout << "Neutrino : " << NeutrinoEnergyTh << " MeV" << std::endl;
                 }
                 if(mc_roi_v[iMC].PdgCode() == 13){
                     std::cout << "muon.....@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                     Em_t = mc_roi_v[iMC].EnergyDeposit();
                     MuonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                     MuonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
                 }
                 if(mc_roi_v[iMC].PdgCode() == 2212){
                     std::cout << "proton...@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                     Ep_t = mc_roi_v[iMC].EnergyDeposit();
                     ProtonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                     ProtonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
                 }
                 if(mc_roi_v[iMC].PdgCode() == 11){
                     std::cout << "electron.@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                     ElectronVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                     ElectronEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
                 }
             }
             std::vector<TVector3> MCEndPoint;
             bool isVertex = false;
             bool isNumu = false;
             bool isNue = false;
             std::vector<int> goodMuon, goodElectron;
             for(size_t iProton = 0;iProton<ProtonVertices.size();iProton++){
                 isVertex = false;
                 isNumu = false;
                 isNue = false;
                 for(size_t iMuon = 0;iMuon<MuonVertices.size();iMuon++){
                     if(MuonVertices[iMuon] == ProtonVertices[iProton]){isVertex = true;isNumu = true;goodMuon.push_back(iMuon);}
                 }
                 for(size_t iElectron = 0;iElectron<ElectronVertices.size();iElectron++){
                     if(ProtonVertices[iProton] == ElectronVertices[iProton]){isVertex = true;isNue = true;goodElectron.push_back(iElectron);}
                 }
                 if(isVertex && MCVertices.size()!=0 && ProtonVertices[iProton] == MCVertices[MCVertices.size()-1])continue;
                 if(isVertex){
                     MCVertices.push_back(ProtonVertices[iProton]);
                     MCEndPoint.push_back(ProtonEndPoint[iProton]);
                     MCvertex = ProtonVertices[iProton];
                     if(isNumu){
                         for(size_t imu = 0;imu<goodMuon.size();imu++){
                             MCEndPoint.push_back(MuonEndPoint[goodMuon[imu]]);
                         }
                     }
                     if(isNue){
                         for(size_t ie = 0;ie<goodElectron.size();ie++){
                             MCEndPoint.push_back(ElectronEndPoint[goodElectron[ie]]);
                         }
                     }
                 }
             }
         }
         //______________
         // End MC
         //--------------
         // loop over found vertices
         //auto const& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
         std::vector<TVector3> vertex_v;
     std::vector<TVector3> vertex_sce_v;
         std::vector<larcv::ImageMeta> Full_meta_v(3);
         std::vector<larcv::Image2D> Tagged_Image(3);
         std::vector<larcv::Image2D> Full_image_v(3);
         double wireRange = 5000;
         double tickRange = 8502;
         // Create base image2D with the full view, fill it with the input image 2D, we will crop it later
         for(size_t iPlane=0;iPlane<3;iPlane++){
             Full_meta_v[iPlane] = larcv::ImageMeta(wireRange,tickRange,(int)(tickRange)/6,(int)(wireRange),0,tickRange);
             Full_image_v[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             Tagged_Image[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             if(full_adc_img_v->size() == 3)Full_image_v[iPlane].overlay( (*full_adc_img_v)[iPlane] );
             //if(full_tag_img_thru_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_thru_v)[iPlane] );
             //if(full_tag_img_stop_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_stop_v)[iPlane] );
         }
         tracker.SetOriginalImage(Full_image_v);
         tracker.SetTaggedImage(Tagged_Image);
         tracker.SetTrackInfo(run, subrun, event, 0);
         std::cout << run << " " << subrun << " " << event <<  std::endl;
         //if(!(subrun == 107 && event == 96242)){_storage.set_id(run,subrun,event);_storage.next_event(true); return true;}
         for(size_t pgraph_id = 0; pgraph_id < ev_pgraph_v->PGraphArray().size(); ++pgraph_id) {// comment when running on EXTBNB
       auto const& pgraph = ev_pgraph_v->PGraphArray().at(pgraph_id);
       double pt_X = pgraph.ParticleArray().front().X();
       double pt_Y = pgraph.ParticleArray().front().Y();
       double pt_Z = pgraph.ParticleArray().front().Z();
       auto const sceOffset = sce.GetPosOffsets(pt_X,pt_Y,pt_Z);
       double sceptX = pt_X + sceOffset[0] - 0.7;
       double sceptY = pt_Y - sceOffset[1];
       double sceptZ = pt_Z - sceOffset[2];
       TVector3 vertex(pt_X,pt_Y,pt_Z);
       TVector3 vertex_SCE(sceptX,sceptY,sceptZ);
       vertex_v.push_back(vertex);
       vertex_sce_v.push_back(vertex_SCE);
         }
         NvertexSubmitted+=vertex_v.size();
         int TrackID = 0;
         if(vertex_v.size()!=0){
             for(size_t ivertex = 0;ivertex<vertex_v.size();ivertex++){
                 NtracksReco = 0;
                 if(_trk_id_v.size()!=0)_trk_id_v.clear();
                 if(_IondivLength_v.size()!=0)_IondivLength_v.clear();
                 double xyz[3] = {vertex_v[ivertex].X(),vertex_v[ivertex].Y(),vertex_v[ivertex].Z()};
                 vertex_ptr->push_back(larlite::vertex(xyz,ivertex));
                 tracker.SetSingleVertex(vertex_v[ivertex]);
                 tracker.ReconstructVertex();
                 larlite::event_track recoedVertex = tracker.GetReconstructedVertexTracks();
                 for(size_t itrack = 0; itrack<recoedVertex.size();itrack++){
                     recoedVertex[itrack].set_track_id(TrackID);
                     (*track_ptr).push_back(recoedVertex[itrack]);
                     _trk_id_v.push_back(TrackID);
                     TrackID++;
                     if(recoedVertex[itrack].Length(0) > 5){NtracksReco++;}
                 }
                 std::vector< std::vector<double> > Energies_v = tracker.GetEnergies();
                 _E_muon_v.resize(Energies_v.size());
                 _E_proton_v.resize(Energies_v.size());
                 for(size_t trackid=0; trackid<Energies_v.size(); ++trackid) {
                     _E_proton_v[trackid] = Energies_v[trackid].front();
                     _E_muon_v[trackid]   = Energies_v[trackid].back();
                 }
                 _vtx_id         = (int) ivertex;
                 _Length_v       = tracker.GetVertexLength();
                 _closestWall    = tracker.GetClosestWall();
         _closestWallSCE = tracker.GetClosestWall_SCE();
                 _Avg_Ion_v      = tracker.GetAverageIonization();
                 _Ion_5cm_v      = tracker.GetTotalIonization(5);
                 _Ion_10cm_v     = tracker.GetTotalIonization(10);
                 _Ion_tot_v      = tracker.GetTotalIonization();
                 for(size_t itrack = 0; itrack<_Length_v.size();itrack++){
                     _IondivLength_v.push_back(_Ion_tot_v[itrack]/_Length_v[itrack]);
                 }
                 _Angle_v         = tracker.GetVertexAngle(15); // average over 15 cm to estimate the angles
                 _vertexPhi       = tracker.GetVertexPhi();
                 _vertexTheta     = tracker.GetVertexTheta();
                 _Reco_goodness_v = tracker.GetRecoGoodness();
                 _missingTrack          = _Reco_goodness_v.at(0);
                 _nothingReconstructed  = _Reco_goodness_v.at(1);
                 _tooShortDeadWire      = _Reco_goodness_v.at(2);
                 _tooShortFaintTrack    = _Reco_goodness_v.at(3);
                 _tooManyTracksAtVertex = _Reco_goodness_v.at(4);
                 _possibleCosmic        = _Reco_goodness_v.at(5);
                 _possiblyCrossing      = _Reco_goodness_v.at(6);
                 _branchingTracks       = _Reco_goodness_v.at(7);
                 _jumpingTracks         = _Reco_goodness_v.at(8);
         RecoVertex     = vertex_v.at(ivertex);
         RecoVertex_SCE = vertex_sce_v.at(ivertex);
         GoodVertex = false;
                 GoodVertex = tracker.IsGoodVertex();
                 if(GoodVertex)NgoodReco++;
                 //______________________
                 if(_isMC)MCevaluation();
                 //----------------------
                 _recoTree->Fill();
                 std::cout << std::endl << std::endl;
             }
         }
         _storage.set_id(run,subrun,event);
         _storage.next_event(true);
         std::cout << "...Reconstruted..." << std::endl;
         return true;
     }
ReadVertexFile()
void larcv::ReadJarrettFile::ReadVertexFile (std::string filename)
Definition at line 437 of file ReadJarrettFile.cxx.
References _vertexInfo.
Referenced by SetLLOutName().
     {
         std::cout << "ReadVertexFile" << std::endl;
         if(_vertexInfo.size()!=0)_vertexInfo.clear();
         std::vector<int> thisVertexInfo;
         std::ifstream file(Form("%s",filename.c_str()));
         if(!file){std::cout << "ERROR, could not open file of selected vertices to sort through" << std::endl;return;}
         std::string firstline;
         getline(file, firstline);
         bool goOn = true;
         int Run,SubRun,Event,Entry,ROI_ID,vtxid,rescale_vtxid;
         double x,y,z;
         char coma;
         while(goOn){
             //file >> Run >> coma >> SubRun >> coma >> Event >> coma >> Entry >> coma >> ROI_ID >> coma >> vtxid >> coma >> x >> coma >> y >> coma >> z >> coma >> rescale_vtxid;
             file >> Run >> SubRun >> Event >> Entry >> ROI_ID >> vtxid >> rescale_vtxid >> x >> y >> z ;
             //file >> Run >> coma >> SubRun >> coma >> Event >> coma >> Entry >> coma >> ROI_ID >> coma >> vtxid >> coma >> x >> coma >> y >> coma >> z ;
             if(thisVertexInfo.size()!=0)thisVertexInfo.clear();
             thisVertexInfo.push_back(Run);      //0
             thisVertexInfo.push_back(SubRun);   //1
             thisVertexInfo.push_back(Event);    //2
             thisVertexInfo.push_back(Entry);    //3
             thisVertexInfo.push_back(ROI_ID);   //4
             //thisVertexInfo.push_back(vtxid);    //5
             thisVertexInfo.push_back(rescale_vtxid);//5
             _vertexInfo.push_back(thisVertexInfo);
             if(file.eof()){goOn=false;break;}
         }
         std::cout << _vertexInfo.size() << " vertices to loop through" << std::endl;
     }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetLLOutName()
void larcv::ReadJarrettFile::SetLLOutName (const std::string & foutll) inline
Definition at line 52 of file ReadJarrettFile.h.
References _foutll, event, finalize(), GetJarretVertex(), IsGoodEntry(), IsGoodVertex(), MCevaluation(), ReadVertexFile(), run, and subrun.
 { _foutll = foutll; }
SetSplineLocation()
void larcv::ReadJarrettFile::SetSplineLocation (const std::string & fpath)
Definition at line 605 of file ReadJarrettFile.cxx.
References _spline_file, LARCV_DEBUG, LARCV_INFO, larcv::AStarTracker::SetSplineFile(), and tracker.
Referenced by ~ReadJarrettFile().
{
         LARCV_INFO() << "setting spline loc @ " << fpath << std::endl;
         tracker.SetSplineFile(fpath);
         _spline_file = fpath;
         LARCV_DEBUG() << "end" << std::endl;
     }
Member Data Documentation
_Angle_v
std::vector<std::vector<double> > larcv::ReadJarrettFile::_Angle_v private
Definition at line 113 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_Avg_Ion_v
std::vector<double> larcv::ReadJarrettFile::_Avg_Ion_v private
Definition at line 104 of file ReadJarrettFile.h.
Referenced by initialize(), MCevaluation(), and process().
_branchingTracks
bool larcv::ReadJarrettFile::_branchingTracks private
Definition at line 129 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_closestWall
std::vector<double> larcv::ReadJarrettFile::_closestWall private
Definition at line 107 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_closestWallSCE
std::vector<double> larcv::ReadJarrettFile::_closestWallSCE private
Definition at line 108 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_E_muon_v
std::vector<double> larcv::ReadJarrettFile::_E_muon_v private
Definition at line 101 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_E_proton_v
std::vector<double> larcv::ReadJarrettFile::_E_proton_v private
Definition at line 102 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_EventRecoVertices
std::vector<larlite::event_track> larcv::ReadJarrettFile::_EventRecoVertices private
Definition at line 115 of file ReadJarrettFile.h.
_filename
std::string larcv::ReadJarrettFile::_filename private
Definition at line 97 of file ReadJarrettFile.h.
Referenced by GetJarretVertex(), and initialize().
_foutll
std::string larcv::ReadJarrettFile::_foutll private
Definition at line 135 of file ReadJarrettFile.h.
Referenced by initialize(), and SetLLOutName().
_input_pgraph_producer
std::string larcv::ReadJarrettFile::_input_pgraph_producer private
Definition at line 133 of file ReadJarrettFile.h.
Referenced by configure(), and process().
_Ion_10cm_v
std::vector<double> larcv::ReadJarrettFile::_Ion_10cm_v private
Definition at line 110 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_Ion_5cm_v
std::vector<double> larcv::ReadJarrettFile::_Ion_5cm_v private
Definition at line 109 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_Ion_tot_v
std::vector<double> larcv::ReadJarrettFile::_Ion_tot_v private
Definition at line 111 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_IondivLength_v
std::vector<double> larcv::ReadJarrettFile::_IondivLength_v private
Definition at line 112 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_isMC
bool larcv::ReadJarrettFile::_isMC private
Definition at line 131 of file ReadJarrettFile.h.
Referenced by configure(), and process().
_jumpingTracks
bool larcv::ReadJarrettFile::_jumpingTracks private
Definition at line 130 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_Length_v
std::vector<double> larcv::ReadJarrettFile::_Length_v private
Definition at line 103 of file ReadJarrettFile.h.
Referenced by initialize(), MCevaluation(), and process().
_missingTrack
bool larcv::ReadJarrettFile::_missingTrack private
Definition at line 122 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_nothingReconstructed
bool larcv::ReadJarrettFile::_nothingReconstructed private
Definition at line 123 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_possibleCosmic
bool larcv::ReadJarrettFile::_possibleCosmic private
Definition at line 127 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_possiblyCrossing
bool larcv::ReadJarrettFile::_possiblyCrossing private
Definition at line 128 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_Reco_goodness_v
std::vector<bool> larcv::ReadJarrettFile::_Reco_goodness_v private
Definition at line 114 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_recoTree
TTree* larcv::ReadJarrettFile::_recoTree private
Definition at line 99 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and process().
_spline_file
std::string larcv::ReadJarrettFile::_spline_file private
Definition at line 134 of file ReadJarrettFile.h.
Referenced by initialize(), and SetSplineLocation().
_storage
larlite::storage_manager larcv::ReadJarrettFile::_storage private
Definition at line 66 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and process().
_tooManyTracksAtVertex
bool larcv::ReadJarrettFile::_tooManyTracksAtVertex private
Definition at line 126 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_tooShortDeadWire
bool larcv::ReadJarrettFile::_tooShortDeadWire private
Definition at line 124 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_tooShortFaintTrack
bool larcv::ReadJarrettFile::_tooShortFaintTrack private
Definition at line 125 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_trk_id_v
std::vector<int> larcv::ReadJarrettFile::_trk_id_v private
Definition at line 100 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_vertexInfo
std::vector< std::vector<int> > larcv::ReadJarrettFile::_vertexInfo private
Definition at line 68 of file ReadJarrettFile.h.
Referenced by IsGoodEntry(), IsGoodVertex(), and ReadVertexFile().
_vertexPhi
std::vector<double> larcv::ReadJarrettFile::_vertexPhi private
Definition at line 105 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_vertexTheta
std::vector<double> larcv::ReadJarrettFile::_vertexTheta private
Definition at line 106 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
_vtx_id
int larcv::ReadJarrettFile::_vtx_id private
Definition at line 92 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
checkEvents
std::vector<std::string> larcv::ReadJarrettFile::checkEvents private
Definition at line 96 of file ReadJarrettFile.h.
Referenced by MCevaluation().
Em_t
double larcv::ReadJarrettFile::Em_t private
Definition at line 88 of file ReadJarrettFile.h.
Referenced by initialize(), MCevaluation(), and process().
Ep_t
double larcv::ReadJarrettFile::Ep_t private
Definition at line 87 of file ReadJarrettFile.h.
Referenced by initialize(), MCevaluation(), and process().
event
int larcv::ReadJarrettFile::event private
Definition at line 91 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetLLOutName().
GoodVertex
bool larcv::ReadJarrettFile::GoodVertex private
Definition at line 121 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
hAverageIonization
TH1D* larcv::ReadJarrettFile::hAverageIonization private
Definition at line 70 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp
TH2D* larcv::ReadJarrettFile::hEcomp private
Definition at line 69 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp1D
TH1D* larcv::ReadJarrettFile::hEcomp1D private
Definition at line 71 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp1D_m
TH1D* larcv::ReadJarrettFile::hEcomp1D_m private
Definition at line 72 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp1D_p
TH1D* larcv::ReadJarrettFile::hEcomp1D_p private
Definition at line 73 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp_m
TH2D* larcv::ReadJarrettFile::hEcomp_m private
Definition at line 74 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcomp_p
TH2D* larcv::ReadJarrettFile::hEcomp_p private
Definition at line 75 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEcompdQdx
TH2D* larcv::ReadJarrettFile::hEcompdQdx private
Definition at line 85 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEnuComp
TH2D* larcv::ReadJarrettFile::hEnuComp private
Definition at line 81 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEnuComp1D
TH1D* larcv::ReadJarrettFile::hEnuComp1D private
Definition at line 82 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEnuReco
TH1D* larcv::ReadJarrettFile::hEnuReco private
Definition at line 76 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hEnuTh
TH1D* larcv::ReadJarrettFile::hEnuTh private
Definition at line 77 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and process().
hEnuvsPM_th
TH2D* larcv::ReadJarrettFile::hEnuvsPM_th private
Definition at line 78 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hIonvsLength
TH2D* larcv::ReadJarrettFile::hIonvsLength private
Definition at line 86 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hPM_th_Reco
TH2D* larcv::ReadJarrettFile::hPM_th_Reco private
Definition at line 80 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
hPM_th_Reco_1D
TH1D* larcv::ReadJarrettFile::hPM_th_Reco_1D private
Definition at line 79 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and MCevaluation().
iTrack
int larcv::ReadJarrettFile::iTrack private
Definition at line 65 of file ReadJarrettFile.h.
MCvertex
TVector3 larcv::ReadJarrettFile::MCvertex private
Definition at line 117 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
NeutrinoEnergyReco
double larcv::ReadJarrettFile::NeutrinoEnergyReco private
Definition at line 84 of file ReadJarrettFile.h.
NeutrinoEnergyTh
double larcv::ReadJarrettFile::NeutrinoEnergyTh private
Definition at line 83 of file ReadJarrettFile.h.
Referenced by MCevaluation(), and process().
NgoodReco
int larcv::ReadJarrettFile::NgoodReco private
Definition at line 94 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and process().
NtracksReco
int larcv::ReadJarrettFile::NtracksReco private
Definition at line 95 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
NvertexSubmitted
int larcv::ReadJarrettFile::NvertexSubmitted private
Definition at line 93 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), and process().
RecoVertex
TVector3 larcv::ReadJarrettFile::RecoVertex private
Definition at line 118 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
RecoVertex_SCE
TVector3 larcv::ReadJarrettFile::RecoVertex_SCE private
Definition at line 119 of file ReadJarrettFile.h.
Referenced by initialize(), and process().
run
int larcv::ReadJarrettFile::run private
Definition at line 89 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetLLOutName().
subrun
int larcv::ReadJarrettFile::subrun private
Definition at line 90 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetLLOutName().
tracker
larcv::AStarTracker larcv::ReadJarrettFile::tracker private
Definition at line 67 of file ReadJarrettFile.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetSplineLocation().
The documentation for this class was generated from the following files:
ReadJarrettFile.h
ReadJarrettFile.cxx