LArCV: larcv::ReadNueFile Class Reference
larcv::ReadNueFile Class Reference
#include <ReadNueFile.h>
Public Member Functions
ReadNueFile (const std::string name="ReadNueFile")
~ReadNueFile ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void SetSplineLocation (const std::string &fpath)
void SetLLOutName (const std::string &foutll)
void ClearEvent ()
void ClearVertex ()
void FillMC (const std::vector< ROI > &mc_roi_v)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void advance_larlite ()
Private Attributes
std::string _foutll
int iTrack
larlite::storage_manager _storage
larcv::AStarTracker tracker
std::vector< std::vector< int > > _vertexInfo
std::string _spline_file
TTree * _recoTree
std::string _img2d_producer
std::string _pgraph_producer
std::string _par_pix_producer
std::string _true_roi_producer
std::vector< std::string > checkEvents
int _run
int _subrun
int _event
int _nentry
bool _mask_shower
std::vector< larcv::ImageMeta > _Full_meta_v
std::vector< larcv::Image2D > _Full_image_v
std::vector< larcv::Image2D > _Tagged_Image
std::vector< double > _E_muon_v
std::vector< double > _E_proton_v
std::vector< double > _Length_v
std::vector< double > _Avg_Ion_v
std::vector< double > _vertexPhi_v
std::vector< double > _vertexTheta_v
std::vector< double > _closestWall_v
std::vector< double > _Ion_5cm_v
std::vector< double > _Ion_10cm_v
std::vector< double > _Ion_tot_v
std::vector< double > _IondivLength_v
std::vector< double > _Trunc_dQdX1_v
std::vector< double > _Trunc_dQdX3_v
std::vector< std::vector< double > > _Angle_v
std::vector< int > _Reco_goodness_v
std::vector< larlite::event_track > _EventRecoVertices
int _missingTrack
int _nothingReconstructed
int _tooShortDeadWire
int _tooShortFaintTrack
int _tooManyTracksAtVertex
int _possibleCosmic
int _possiblyCrossing
int _branchingTracks
int _jumpingTracks
bool _isMC
int _vtx_id
float _vtx_x
float _vtx_y
float _vtx_z
double _Ep_t
double _Em_t
double _Ee_t
int _GoodVertex
int _Nreco
int _entry
double _MuonStartPoint_X
double _ProtonStartPoint_X
double _ElectronStartPoint_X
double _MuonStartPoint_Y
double _ProtonStartPoint_Y
double _ElectronStartPoint_Y
double _MuonStartPoint_Z
double _ProtonStartPoint_Z
double _ElectronStartPoint_Z
double _MuonEndPoint_X
double _ProtonEndPoint_X
double _ElectronEndPoint_X
double _MuonEndPoint_Y
double _ProtonEndPoint_Y
double _ElectronEndPoint_Y
double _MuonEndPoint_Z
double _ProtonEndPoint_Z
double _ElectronEndPoint_Z
Detailed Description
Definition at line 10 of file ReadNueFile.h.
Constructor & Destructor Documentation
ReadNueFile()
larcv::ReadNueFile::ReadNueFile (const std::string name = "ReadNueFile")
Definition at line 35 of file ReadNueFile.cxx.
Referenced by larcv::ReadNueFileProcessFactory::create().
     : ProcessBase(name),
       _foutll(""),
       _spline_file(""),
       _recoTree(nullptr)
   {}
~ReadNueFile()
larcv::ReadNueFile::~ReadNueFile () inline
Definition at line 15 of file ReadNueFile.h.
References configure(), finalize(), initialize(), process(), and SetSplineLocation().
 {}
Member Function Documentation
advance_larlite()
void larcv::ReadNueFile::advance_larlite () private
Definition at line 491 of file ReadNueFile.cxx.
References _event, _run, _storage, and _subrun.
Referenced by process(), and SetLLOutName().
{
     _storage.set_id(_run,_subrun,_event);
     _storage.next_event(true);
   }
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEvent()
void larcv::ReadNueFile::ClearEvent ()
Definition at line 375 of file ReadNueFile.cxx.
References _Ee_t, _ElectronEndPoint_X, _ElectronEndPoint_Y, _ElectronEndPoint_Z, _ElectronStartPoint_X, _ElectronStartPoint_Y, _ElectronStartPoint_Z, _Em_t, _Ep_t, _event, _MuonEndPoint_X, _MuonEndPoint_Y, _MuonEndPoint_Z, _MuonStartPoint_X, _MuonStartPoint_Y, _MuonStartPoint_Z, _Nreco, _ProtonEndPoint_X, _ProtonEndPoint_Y, _ProtonEndPoint_Z, _ProtonStartPoint_X, _ProtonStartPoint_Y, _ProtonStartPoint_Z, _run, _subrun, larcv::kINVALID_DOUBLE, and larcv::kINVALID_INT.
Referenced by process(), and SetLLOutName().
{
     _run    = kINVALID_INT;
     _subrun = kINVALID_INT;
     _event  = kINVALID_INT;
     _Nreco = 0;
     _MuonStartPoint_X = -1.0*kINVALID_DOUBLE;
     _ProtonStartPoint_X = -1.0*kINVALID_DOUBLE;
     _ElectronStartPoint_X = -1.0*kINVALID_DOUBLE;
     _MuonStartPoint_Y = -1.0*kINVALID_DOUBLE;
     _ProtonStartPoint_Y = -1.0*kINVALID_DOUBLE;
     _ElectronStartPoint_Y = -1.0*kINVALID_DOUBLE;
     _MuonStartPoint_Z = -1.0*kINVALID_DOUBLE;
     _ProtonStartPoint_Z = -1.0*kINVALID_DOUBLE;
     _ElectronStartPoint_Z = -1.0*kINVALID_DOUBLE;
     _MuonEndPoint_X = -1.0*kINVALID_DOUBLE;
     _ProtonEndPoint_X = -1.0*kINVALID_DOUBLE;
     _ElectronEndPoint_X = -1.0*kINVALID_DOUBLE;
     _MuonEndPoint_Y = -1.0*kINVALID_DOUBLE;
     _ProtonEndPoint_Y = -1.0*kINVALID_DOUBLE;
     _ElectronEndPoint_Y = -1.0*kINVALID_DOUBLE;
     _MuonEndPoint_Z = -1.0*kINVALID_DOUBLE;
     _ProtonEndPoint_Z = -1.0*kINVALID_DOUBLE;
     _ElectronEndPoint_Z = -1.0*kINVALID_DOUBLE;
     _Ep_t = -1.0*kINVALID_DOUBLE;
     _Em_t = -1.0*kINVALID_DOUBLE;
     _Ee_t = -1.0*kINVALID_DOUBLE;
   }
ClearVertex()
void larcv::ReadNueFile::ClearVertex ()
Definition at line 411 of file ReadNueFile.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _closestWall_v, _E_muon_v, _E_proton_v, _GoodVertex, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _jumpingTracks, _Length_v, _missingTrack, _nothingReconstructed, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _vertexPhi_v, _vertexTheta_v, _vtx_id, _vtx_x, _vtx_y, _vtx_z, larcv::kINVALID_FLOAT, and larcv::kINVALID_INT.
Referenced by process(), and SetLLOutName().
{
     _vtx_id = -1.0 * kINVALID_INT;
     _vtx_x  = -1.0 * kINVALID_FLOAT;
     _vtx_y  = -1.0 * kINVALID_FLOAT;
     _vtx_z  = -1.0 * kINVALID_FLOAT;
     _E_muon_v.clear();
     _E_proton_v.clear();
     _Length_v.clear();
     _Avg_Ion_v.clear();
     _Angle_v.clear();
     _vertexPhi_v.clear();
     _vertexTheta_v.clear();
     _closestWall_v.clear();
     _Ion_5cm_v.clear();
     _Ion_10cm_v.clear();
     _Ion_tot_v.clear();
     _IondivLength_v.clear();
     _Reco_goodness_v.clear();
     _GoodVertex = -1.0*kINVALID_INT;
     _missingTrack = -1.0*kINVALID_INT;
     _nothingReconstructed = -1.0*kINVALID_INT;
     _tooShortDeadWire = -1.0*kINVALID_INT;
     _tooShortFaintTrack = -1.0*kINVALID_INT;
     _tooManyTracksAtVertex = -1.0*kINVALID_INT;
     _possibleCosmic = -1.0*kINVALID_INT;
     _possiblyCrossing = -1.0*kINVALID_INT;
     _branchingTracks = -1.0*kINVALID_INT;
     _jumpingTracks = -1.0*kINVALID_INT;
   }
configure()
void larcv::ReadNueFile::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 42 of file ReadNueFile.cxx.
References _img2d_producer, _mask_shower, _par_pix_producer, _pgraph_producer, _true_roi_producer, and larcv::PSet::get().
Referenced by ~ReadNueFile().
   {
     _img2d_producer    = cfg.get<std::string>("Image2DProducer");
     _pgraph_producer   = cfg.get<std::string>("PGraphProducer");
     _par_pix_producer  = cfg.get<std::string>("ParPixelProducer");
     _true_roi_producer = cfg.get<std::string>("TrueROIProducer");
     _mask_shower       = cfg.get<bool>("MaskShower",true);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
FillMC()
void larcv::ReadNueFile::FillMC (const std::vector< ROI > & mc_roi_v)
Definition at line 442 of file ReadNueFile.cxx.
References _Ee_t, _ElectronEndPoint_X, _ElectronEndPoint_Y, _ElectronEndPoint_Z, _ElectronStartPoint_X, _ElectronStartPoint_Y, _ElectronStartPoint_Z, _Em_t, _Ep_t, _MuonEndPoint_X, _MuonEndPoint_Y, _MuonEndPoint_Z, _MuonStartPoint_X, _MuonStartPoint_Y, _MuonStartPoint_Z, _ProtonEndPoint_X, _ProtonEndPoint_Y, _ProtonEndPoint_Z, _ProtonStartPoint_X, _ProtonStartPoint_Y, _ProtonStartPoint_Z, and LARCV_INFO.
Referenced by SetLLOutName().
{
     bool found_muon = false;
     bool found_proton = false;
     bool found_electron = false;
     for(size_t iMC = 0;iMC<mc_roi_v.size();iMC++){
       if(mc_roi_v[iMC].PdgCode() == 13){
     if (found_muon) continue;
     LARCV_INFO() << "muon.....@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
     _MuonStartPoint_X = mc_roi_v[iMC].X();
     _MuonStartPoint_Y = mc_roi_v[iMC].Y();
     _MuonStartPoint_Z = mc_roi_v[iMC].Z();
     _MuonEndPoint_X = mc_roi_v[iMC].EndPosition().X();
     _MuonEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
     _MuonEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
     _Em_t = mc_roi_v[iMC].EnergyDeposit();
     found_muon = true;
       }
       if(mc_roi_v[iMC].PdgCode() == 2212){
     if (found_proton) continue;
     LARCV_INFO() << "proton...@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
     _ProtonStartPoint_X = mc_roi_v[iMC].X();
     _ProtonStartPoint_Y = mc_roi_v[iMC].Y();
     _ProtonStartPoint_Z = mc_roi_v[iMC].Z();
     _ProtonEndPoint_X = mc_roi_v[iMC].EndPosition().X();
     _ProtonEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
     _ProtonEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
     _Ep_t = mc_roi_v[iMC].EnergyDeposit();
     found_proton = true;
       }
       if(mc_roi_v[iMC].PdgCode() == 11){
     if(found_electron) continue;
     LARCV_INFO() << "electron.@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
     _ElectronStartPoint_X = mc_roi_v[iMC].X();
     _ElectronStartPoint_Y = mc_roi_v[iMC].Y();
     _ElectronStartPoint_Z = mc_roi_v[iMC].Z();
     _ElectronEndPoint_X = mc_roi_v[iMC].EndPosition().X();
     _ElectronEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
     _ElectronEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
     _Ee_t = mc_roi_v[iMC].EnergyDeposit();
     found_electron = true;
       }
     } // end rois
     return;
   } // end mc
finalize()
void larcv::ReadNueFile::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 357 of file ReadNueFile.cxx.
References _recoTree, _storage, larcv::ProcessBase::ana_file(), larcv::AStarTracker::finalize(), larcv::ProcessBase::has_ana_file(), and tracker.
Referenced by ~ReadNueFile().
{
     tracker.finalize();
     if(has_ana_file()) {
       ana_file().cd();
       _recoTree->Write();
     }
     _storage.close();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ReadNueFile::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 52 of file ReadNueFile.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _closestWall_v, _E_muon_v, _E_proton_v, _entry, _event, _foutll, _GoodVertex, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _jumpingTracks, _Length_v, _missingTrack, _nothingReconstructed, _Nreco, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _recoTree, _run, _spline_file, _storage, _subrun, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _Trunc_dQdX1_v, _Trunc_dQdX3_v, _vertexPhi_v, _vertexTheta_v, _vtx_id, _vtx_x, _vtx_y, _vtx_z, larcv::AStarTracker::initialize(), LARCV_CRITICAL, LARCV_INFO, larcv::AStarTracker::SetCompressionFactors(), larcv::AStarTracker::SetDrawOutputs(), larcv::AStarTracker::SetOutputDir(), larcv::AStarTracker::SetSplineFile(), larcv::AStarTracker::SetVerbose(), and tracker.
Referenced by ~ReadNueFile().
   {
     LARCV_INFO() << "[ReadNueFile]" << std::endl;
     assert(!_spline_file.empty());
     tracker.SetDrawOutputs(false);
     tracker.SetOutputDir("png");
     tracker.SetSplineFile(_spline_file);
     tracker.initialize();
     tracker.SetCompressionFactors(1,6);
     tracker.SetVerbose(2);
     _recoTree = new TTree("_recoTree","_recoTree");
     _recoTree->Branch("run"     , &_run   , "_run/I");
     _recoTree->Branch("subrun"  , &_subrun, "_subrun/I");
     _recoTree->Branch("event"   , &_event , "_event/I");
     _recoTree->Branch("entry"   , &_entry , "_entry/I");
     //
     // Reco information
     //
     _recoTree->Branch("vtx_id", &_vtx_id, "vtx_id/I");
     _recoTree->Branch("vtx_x" , &_vtx_x , "vtx_x/F");
     _recoTree->Branch("vtx_y" , &_vtx_y , "vtx_y/F");
     _recoTree->Branch("vtx_z" , &_vtx_z , "vtx_z/F");
     _recoTree->Branch("E_muon_v"   , &_E_muon_v);
     _recoTree->Branch("E_proton_v" , &_E_proton_v);
     _recoTree->Branch("Length_v"   , &_Length_v);
     _recoTree->Branch("Avg_Ion_v",&_Avg_Ion_v);
     _recoTree->Branch("Ion_5cm_v",&_Ion_5cm_v);
     _recoTree->Branch("Ion_10cm_v",&_Ion_10cm_v);
     _recoTree->Branch("Ion_tot_v",&_Ion_tot_v);
     _recoTree->Branch("IondivLength_v",&_IondivLength_v);
     _recoTree->Branch("Truncated_dQdX1_v",&_Trunc_dQdX1_v);
     _recoTree->Branch("Truncated_dQdX3_v",&_Trunc_dQdX3_v);
     _recoTree->Branch("Angle_v"    , &_Angle_v);
     _recoTree->Branch("vertexPhi",&_vertexPhi_v);
     _recoTree->Branch("vertexTheta",&_vertexTheta_v);
     _recoTree->Branch("closestWall",&_closestWall_v);
     _recoTree->Branch("Reco_goodness_v" , &_Reco_goodness_v);
     _recoTree->Branch("GoodVertex" , &_GoodVertex, "GoodVertex/I");
     _recoTree->Branch("Nreco" , &_Nreco , "Nreco/I");
     _recoTree->Branch("missingTrack",&_missingTrack);
     _recoTree->Branch("nothingReconstructed",&_nothingReconstructed);
     _recoTree->Branch("tooShortDeadWire",&_tooShortDeadWire);
     _recoTree->Branch("tooShortFaintTrack",&_tooShortFaintTrack);
     _recoTree->Branch("tooManyTracksAtVertex",&_tooManyTracksAtVertex);
     _recoTree->Branch("possibleCosmic",&_possibleCosmic);
     _recoTree->Branch("possiblyCrossing",&_possiblyCrossing);
     _recoTree->Branch("branchingTracks",&_branchingTracks);
     _recoTree->Branch("jumpingTracks",&_jumpingTracks);
     if (_foutll.empty()) throw larbys("specify larlite file output name");
     _storage.set_io_mode(larlite::storage_manager::kWRITE);
     _storage.set_out_filename(_foutll);
     if(!_storage.open()) {
       LARCV_CRITICAL() << "ERROR, larlite output file could not open" << std::endl;
       throw larbys("die");
     }
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ReadNueFile::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 118 of file ReadNueFile.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _closestWall_v, _E_muon_v, _E_proton_v, _entry, _event, _Full_image_v, _Full_meta_v, _GoodVertex, _img2d_producer, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _jumpingTracks, _Length_v, _mask_shower, _missingTrack, _nothingReconstructed, _Nreco, _par_pix_producer, _pgraph_producer, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _recoTree, _run, _storage, _subrun, _Tagged_Image, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _true_roi_producer, _Trunc_dQdX1_v, _Trunc_dQdX3_v, _vertexPhi_v, _vertexTheta_v, _vtx_id, _vtx_x, _vtx_y, _vtx_z, advance_larlite(), ClearEvent(), ClearVertex(), larcv::EventPixel2D::ClusterMetaArray(), larcv::AStarTracker::ComputeTruncateddQdX(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::get_n_entries(), larcv::AStarTracker::GetAverageIonization(), larcv::AStarTracker::GetClosestWall(), larcv::AStarTracker::GetEnergies(), larcv::AStarTracker::GetRecoGoodness(), larcv::AStarTracker::GetReconstructedVertexTracks(), larcv::AStarTracker::GetTotalIonization(), larcv::AStarTracker::GetVertexAngle(), larcv::AStarTracker::GetVertexLength(), larcv::AStarTracker::GetVertexPhi(), larcv::AStarTracker::GetVertexTheta(), larcv::AStarTracker::IsGoodVertex(), iTrack, larcv::kINVALID_DOUBLE, larcv::kINVALID_INT, larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, larcv::kShapeTrack, LARCV_INFO, larcv::EventPixel2D::Pixel2DClusterArray(), larcv::AStarTracker::ReconstructVertex(), larcv::AStarTracker::SetOriginalImage(), larcv::AStarTracker::SetSingleVertex(), larcv::AStarTracker::SetTaggedImage(), larcv::AStarTracker::SetTrackInfo(), and tracker.
Referenced by ~ReadNueFile().
   {
     ClearEvent();
     LARCV_INFO() << std::endl;
     LARCV_INFO() << "============================================" << std::endl;
     LARCV_INFO() << "Entry " << mgr.current_entry() << " / " << mgr.get_n_entries() << std::endl;
     LARCV_INFO() << "============================================" << std::endl;
     gROOT->SetBatch(kTRUE);
     TVector3 vertex;
     //
     // Loop per vertex (larcv type is PGraph "Particle Graph")
     //
     auto ev_img_v       = (EventImage2D*) mgr.get_data(kProductImage2D,_img2d_producer);
     auto ev_pgraph_v    = (EventPGraph*)  mgr.get_data(kProductPGraph,_pgraph_producer);
     EventPixel2D* ev_pix_v = nullptr;
     if (!_par_pix_producer.empty())
       ev_pix_v = (EventPixel2D*) mgr.get_data(kProductPixel2D,_par_pix_producer);
     EventROI* ev_partroi_v = nullptr;
     if (!_true_roi_producer.empty())
       ev_partroi_v = (EventROI*) mgr.get_data(kProductROI,_true_roi_producer);
     // auto tag_img_thru_v = (EventImage2D*) mgr.get_data(kProductImage2D,"thrumutags");
     // auto tag_img_stop_v = (EventImage2D*) mgr.get_data(kProductImage2D,"stopmutags");
     auto ev_vertex = (larlite::event_vertex*) _storage.get_data(larlite::data::kVertex,"trackReco");
     auto ev_track  = (larlite::event_track*)  _storage.get_data(larlite::data::kTrack,"trackReco");
     auto ev_ass    = (larlite::event_ass*)    _storage.get_data(larlite::data::kAssociation,"trackReco");
     _run    = (int) ev_pgraph_v->run();
     _subrun = (int) ev_pgraph_v->subrun();
     _event  = (int) ev_pgraph_v->event();
     _entry  = (int) mgr.current_entry();
     // get the event clusters and full images
     const auto& full_adc_img_v = ev_img_v->Image2DArray();
     // const auto& full_tag_img_thru_v = tag_img_thru_v->Image2DArray();
     // const auto& full_tag_img_stop_v = tag_img_stop_v->Image2DArray();
     //
     // No vertex, continue (but fill)
     //
     if (ev_pgraph_v->PGraphArray().empty()) {
       ClearVertex();
       advance_larlite();
       return true;
     }
     static double wireRange = 5000;
     static double tickRange = 8502;
     if (_Full_meta_v.empty()) {
       assert (_Full_image_v.empty());
       assert (_Tagged_Image.empty());
       _Full_meta_v.resize(3);
       _Full_image_v.resize(3);
       _Tagged_Image.resize(3);
       for(size_t iPlane=0;iPlane<3;iPlane++){
     _Full_meta_v[iPlane]  = larcv::ImageMeta(wireRange,tickRange,(int)(tickRange)/6,(int)(wireRange),0,tickRange);
     _Full_image_v[iPlane] = larcv::Image2D(_Full_meta_v[iPlane]);
     _Tagged_Image[iPlane] = larcv::Image2D(_Full_meta_v[iPlane]);
       }
     } else {
       assert (full_adc_img_v.size()==3);
       for(size_t iPlane=0;iPlane<3;iPlane++){
     _Full_image_v[iPlane].paint(0);
     _Tagged_Image[iPlane].paint(0);
     _Full_image_v[iPlane].overlay( full_adc_img_v[iPlane] );
       }
       //if(full_tag_img_thru_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_thru_v)[iPlane] );
       //if(full_tag_img_stop_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_stop_v)[iPlane] );
     }
     //
     // loop over found vertices
     //
     static std::vector<TVector3> vertex_v;
     vertex_v.clear();
     vertex_v.reserve(ev_pgraph_v->PGraphArray().size());
     for(size_t pgraph_id = 0; pgraph_id < ev_pgraph_v->PGraphArray().size(); ++pgraph_id) {
       iTrack++;
       auto const& pgraph        = ev_pgraph_v->PGraphArray().at(pgraph_id);
       auto const& roi_v         = pgraph.ParticleArray();
       auto const& cluster_idx_v = pgraph.ClusterIndexArray();
       //
       // Get Estimated 3D Start and End Points
       vertex_v.emplace_back(pgraph.ParticleArray().front().X(),
                 pgraph.ParticleArray().front().Y(),
                 pgraph.ParticleArray().front().Z());
       if (_mask_shower) {
     assert (ev_pix_v);
     const auto& pix_m          = ev_pix_v->Pixel2DClusterArray();
     const auto& pix_meta_m     = ev_pix_v->ClusterMetaArray();
     //
     // mask shower particle pixels
     // method : pixels stored via larbys image
     //
     for(size_t roid=0; roid < roi_v.size(); ++roid) {
       const auto& roi = roi_v[roid];
       auto cidx = cluster_idx_v.at(roid);
       if (roi.Shape() == kShapeTrack) continue;
       for(size_t plane=0; plane<3; ++plane) {
         auto iter_pix = pix_m.find(plane);
         if(iter_pix == pix_m.end())
           continue;
         auto iter_pix_meta = pix_meta_m.find(plane);
         if(iter_pix_meta == pix_meta_m.end())
           continue;
         auto const& pix_v      = (*iter_pix).second;
         auto const& pix_meta_v = (*iter_pix_meta).second;
         auto const& pix      = pix_v.at(cidx);
         auto const& pix_meta = pix_meta_v.at(cidx);
         auto& plane_img = _Full_image_v.at(plane);
         for(const auto& px : pix) {
           auto posx = pix_meta.pos_x(px.Y());
           auto posy = pix_meta.pos_y(px.X());
           auto row = plane_img.meta().row(posy);
           auto col = plane_img.meta().col(posx);
           plane_img.set_pixel(row,col,0);
         }
       } // end plane
     } // end ROI
       } // end mask shower
     } // end vertex
     tracker.SetOriginalImage(_Full_image_v);
     tracker.SetTaggedImage(_Tagged_Image);
     tracker.SetTrackInfo(_run, _subrun, _event, 0);
     static std::vector<std::vector<unsigned> > ass_vertex_to_track_vv;
     ass_vertex_to_track_vv.clear();
     ass_vertex_to_track_vv.resize(vertex_v.size());
     for(size_t ivertex = 0;ivertex<vertex_v.size();ivertex++){
       const auto& vtx = vertex_v[ivertex];
       double xyz[3] = {vtx.X(),vtx.Y(),vtx.Z()};
       ev_vertex->push_back(larlite::vertex(xyz,ivertex));
       auto& ass_vertex_to_track_v = ass_vertex_to_track_vv[ivertex];
       _vtx_id = (int) ivertex;
       _vtx_x  = (float) vtx.X();
       _vtx_y  = (float) vtx.Y();
       _vtx_z  = (float) vtx.Z();
       tracker.SetSingleVertex(vtx);
       tracker.ReconstructVertex();
       auto recoedVertex = tracker.GetReconstructedVertexTracks();
       LARCV_INFO() << "found " << recoedVertex.size() << " tracks" << std::endl;
       for(auto& itrack : recoedVertex) {
     ass_vertex_to_track_v.push_back(ev_track->size());
     ev_track->push_back(itrack);
       }
       auto Energies_v = tracker.GetEnergies();
       size_t ntracks = Energies_v.size();
       _E_muon_v.resize(ntracks);
       _E_proton_v.resize(ntracks);
       for(size_t trackid=0; trackid<ntracks; ++trackid) {
     _E_proton_v[trackid] = Energies_v[trackid].front();
     _E_muon_v[trackid]   = Energies_v[trackid].back();
       }
       _Length_v      = tracker.GetVertexLength();;
       _Angle_v       = tracker.GetVertexAngle(15);
       _Avg_Ion_v     = tracker.GetAverageIonization();
       _closestWall_v = tracker.GetClosestWall();
       _Ion_5cm_v     = tracker.GetTotalIonization(5);
       _Ion_10cm_v    = tracker.GetTotalIonization(10);
       _Ion_tot_v     = tracker.GetTotalIonization();
       _Trunc_dQdX1_v = tracker.ComputeTruncateddQdX(1.0);
       _Trunc_dQdX3_v = tracker.ComputeTruncateddQdX(3.0);
       _vertexPhi_v   = tracker.GetVertexPhi();
       _vertexTheta_v = tracker.GetVertexTheta();
       _IondivLength_v.resize(ntracks,-1.0*kINVALID_DOUBLE);
       for(size_t itrack = 0; itrack<ntracks;itrack++)
     _IondivLength_v[itrack] = _Ion_tot_v[itrack] / _Length_v[itrack];
       auto Reco_goodness_v = tracker.GetRecoGoodness();
       _Reco_goodness_v.resize(Reco_goodness_v.size(),kINVALID_INT);
       for(size_t gid=0; gid< _Reco_goodness_v.size(); ++gid)
     _Reco_goodness_v[gid] = (int) Reco_goodness_v[gid];
       assert (_Reco_goodness_v.size() == 9);
       _missingTrack          = (int) _Reco_goodness_v[0];
       _nothingReconstructed  = (int) _Reco_goodness_v[1];
       _tooShortDeadWire      = (int) _Reco_goodness_v[2];
       _tooShortFaintTrack    = (int) _Reco_goodness_v[3];
       _tooManyTracksAtVertex = (int) _Reco_goodness_v[4];
       _possibleCosmic        = (int) _Reco_goodness_v[5];
       _possiblyCrossing      = (int) _Reco_goodness_v[6];
       _branchingTracks       = (int) _Reco_goodness_v[7];
       _jumpingTracks         = (int) _Reco_goodness_v[8];
       auto GoodVertex = false;
       GoodVertex  = tracker.IsGoodVertex();
       _GoodVertex = (int) GoodVertex;
       _Nreco++;
       _recoTree->Fill();
       ClearVertex();
     }
     // set the ass
     ev_ass->set_association(ev_vertex->id(),ev_track->id(), ass_vertex_to_track_vv);
     advance_larlite();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetLLOutName()
void larcv::ReadNueFile::SetLLOutName (const std::string & foutll) inline
Definition at line 23 of file ReadNueFile.h.
References _foutll, advance_larlite(), ClearEvent(), ClearVertex(), and FillMC().
 { _foutll = foutll; }
SetSplineLocation()
void larcv::ReadNueFile::SetSplineLocation (const std::string & fpath)
Definition at line 368 of file ReadNueFile.cxx.
References _spline_file, LARCV_DEBUG, LARCV_INFO, larcv::AStarTracker::SetSplineFile(), and tracker.
Referenced by ~ReadNueFile().
{
     LARCV_INFO() << "setting spline loc @ " << fpath << std::endl;
     tracker.SetSplineFile(fpath);
     _spline_file = fpath;
     LARCV_DEBUG() << "end" << std::endl;
   }
Member Data Documentation
_Angle_v
std::vector<std::vector<double> > larcv::ReadNueFile::_Angle_v private
Definition at line 73 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Avg_Ion_v
std::vector<double> larcv::ReadNueFile::_Avg_Ion_v private
Definition at line 63 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_branchingTracks
int larcv::ReadNueFile::_branchingTracks private
Definition at line 85 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_closestWall_v
std::vector<double> larcv::ReadNueFile::_closestWall_v private
Definition at line 66 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_E_muon_v
std::vector<double> larcv::ReadNueFile::_E_muon_v private
Definition at line 60 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_E_proton_v
std::vector<double> larcv::ReadNueFile::_E_proton_v private
Definition at line 61 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Ee_t
double larcv::ReadNueFile::_Ee_t private
Definition at line 96 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronEndPoint_X
double larcv::ReadNueFile::_ElectronEndPoint_X private
Definition at line 122 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronEndPoint_Y
double larcv::ReadNueFile::_ElectronEndPoint_Y private
Definition at line 126 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronEndPoint_Z
double larcv::ReadNueFile::_ElectronEndPoint_Z private
Definition at line 130 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronStartPoint_X
double larcv::ReadNueFile::_ElectronStartPoint_X private
Definition at line 107 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronStartPoint_Y
double larcv::ReadNueFile::_ElectronStartPoint_Y private
Definition at line 111 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ElectronStartPoint_Z
double larcv::ReadNueFile::_ElectronStartPoint_Z private
Definition at line 115 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_Em_t
double larcv::ReadNueFile::_Em_t private
Definition at line 95 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_entry
int larcv::ReadNueFile::_entry private
Definition at line 100 of file ReadNueFile.h.
Referenced by initialize(), and process().
_Ep_t
double larcv::ReadNueFile::_Ep_t private
Definition at line 94 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_event
int larcv::ReadNueFile::_event private
Definition at line 51 of file ReadNueFile.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), and process().
_EventRecoVertices
std::vector<larlite::event_track> larcv::ReadNueFile::_EventRecoVertices private
Definition at line 75 of file ReadNueFile.h.
_foutll
std::string larcv::ReadNueFile::_foutll private
Definition at line 32 of file ReadNueFile.h.
Referenced by initialize(), and SetLLOutName().
_Full_image_v
std::vector<larcv::Image2D> larcv::ReadNueFile::_Full_image_v private
Definition at line 57 of file ReadNueFile.h.
Referenced by process().
_Full_meta_v
std::vector<larcv::ImageMeta> larcv::ReadNueFile::_Full_meta_v private
Definition at line 56 of file ReadNueFile.h.
Referenced by process().
_GoodVertex
int larcv::ReadNueFile::_GoodVertex private
Definition at line 98 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_img2d_producer
std::string larcv::ReadNueFile::_img2d_producer private
Definition at line 42 of file ReadNueFile.h.
Referenced by configure(), and process().
_Ion_10cm_v
std::vector<double> larcv::ReadNueFile::_Ion_10cm_v private
Definition at line 68 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Ion_5cm_v
std::vector<double> larcv::ReadNueFile::_Ion_5cm_v private
Definition at line 67 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Ion_tot_v
std::vector<double> larcv::ReadNueFile::_Ion_tot_v private
Definition at line 69 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_IondivLength_v
std::vector<double> larcv::ReadNueFile::_IondivLength_v private
Definition at line 70 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_isMC
bool larcv::ReadNueFile::_isMC private
Definition at line 87 of file ReadNueFile.h.
_jumpingTracks
int larcv::ReadNueFile::_jumpingTracks private
Definition at line 86 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Length_v
std::vector<double> larcv::ReadNueFile::_Length_v private
Definition at line 62 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_mask_shower
bool larcv::ReadNueFile::_mask_shower private
Definition at line 54 of file ReadNueFile.h.
Referenced by configure(), and process().
_missingTrack
int larcv::ReadNueFile::_missingTrack private
Definition at line 78 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_MuonEndPoint_X
double larcv::ReadNueFile::_MuonEndPoint_X private
Definition at line 120 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_MuonEndPoint_Y
double larcv::ReadNueFile::_MuonEndPoint_Y private
Definition at line 124 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_MuonEndPoint_Z
double larcv::ReadNueFile::_MuonEndPoint_Z private
Definition at line 128 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_MuonStartPoint_X
double larcv::ReadNueFile::_MuonStartPoint_X private
Definition at line 105 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_MuonStartPoint_Y
double larcv::ReadNueFile::_MuonStartPoint_Y private
Definition at line 109 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_MuonStartPoint_Z
double larcv::ReadNueFile::_MuonStartPoint_Z private
Definition at line 113 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_nentry
int larcv::ReadNueFile::_nentry private
Definition at line 52 of file ReadNueFile.h.
_nothingReconstructed
int larcv::ReadNueFile::_nothingReconstructed private
Definition at line 79 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_Nreco
int larcv::ReadNueFile::_Nreco private
Definition at line 99 of file ReadNueFile.h.
Referenced by ClearEvent(), initialize(), and process().
_par_pix_producer
std::string larcv::ReadNueFile::_par_pix_producer private
Definition at line 44 of file ReadNueFile.h.
Referenced by configure(), and process().
_pgraph_producer
std::string larcv::ReadNueFile::_pgraph_producer private
Definition at line 43 of file ReadNueFile.h.
Referenced by configure(), and process().
_possibleCosmic
int larcv::ReadNueFile::_possibleCosmic private
Definition at line 83 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_possiblyCrossing
int larcv::ReadNueFile::_possiblyCrossing private
Definition at line 84 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_ProtonEndPoint_X
double larcv::ReadNueFile::_ProtonEndPoint_X private
Definition at line 121 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ProtonEndPoint_Y
double larcv::ReadNueFile::_ProtonEndPoint_Y private
Definition at line 125 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ProtonEndPoint_Z
double larcv::ReadNueFile::_ProtonEndPoint_Z private
Definition at line 129 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ProtonStartPoint_X
double larcv::ReadNueFile::_ProtonStartPoint_X private
Definition at line 106 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ProtonStartPoint_Y
double larcv::ReadNueFile::_ProtonStartPoint_Y private
Definition at line 110 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_ProtonStartPoint_Z
double larcv::ReadNueFile::_ProtonStartPoint_Z private
Definition at line 114 of file ReadNueFile.h.
Referenced by ClearEvent(), and FillMC().
_Reco_goodness_v
std::vector<int> larcv::ReadNueFile::_Reco_goodness_v private
Definition at line 74 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_recoTree
TTree* larcv::ReadNueFile::_recoTree private
Definition at line 41 of file ReadNueFile.h.
Referenced by finalize(), initialize(), and process().
_run
int larcv::ReadNueFile::_run private
Definition at line 49 of file ReadNueFile.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), and process().
_spline_file
std::string larcv::ReadNueFile::_spline_file private
Definition at line 39 of file ReadNueFile.h.
Referenced by initialize(), and SetSplineLocation().
_storage
larlite::storage_manager larcv::ReadNueFile::_storage private
Definition at line 34 of file ReadNueFile.h.
Referenced by advance_larlite(), finalize(), initialize(), and process().
_subrun
int larcv::ReadNueFile::_subrun private
Definition at line 50 of file ReadNueFile.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), and process().
_Tagged_Image
std::vector<larcv::Image2D> larcv::ReadNueFile::_Tagged_Image private
Definition at line 58 of file ReadNueFile.h.
Referenced by process().
_tooManyTracksAtVertex
int larcv::ReadNueFile::_tooManyTracksAtVertex private
Definition at line 82 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_tooShortDeadWire
int larcv::ReadNueFile::_tooShortDeadWire private
Definition at line 80 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_tooShortFaintTrack
int larcv::ReadNueFile::_tooShortFaintTrack private
Definition at line 81 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_true_roi_producer
std::string larcv::ReadNueFile::_true_roi_producer private
Definition at line 45 of file ReadNueFile.h.
Referenced by configure(), and process().
_Trunc_dQdX1_v
std::vector<double> larcv::ReadNueFile::_Trunc_dQdX1_v private
Definition at line 71 of file ReadNueFile.h.
Referenced by initialize(), and process().
_Trunc_dQdX3_v
std::vector<double> larcv::ReadNueFile::_Trunc_dQdX3_v private
Definition at line 72 of file ReadNueFile.h.
Referenced by initialize(), and process().
_vertexInfo
std::vector< std::vector<int> > larcv::ReadNueFile::_vertexInfo private
Definition at line 37 of file ReadNueFile.h.
_vertexPhi_v
std::vector<double> larcv::ReadNueFile::_vertexPhi_v private
Definition at line 64 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_vertexTheta_v
std::vector<double> larcv::ReadNueFile::_vertexTheta_v private
Definition at line 65 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_id
int larcv::ReadNueFile::_vtx_id private
Definition at line 89 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_x
float larcv::ReadNueFile::_vtx_x private
Definition at line 90 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_y
float larcv::ReadNueFile::_vtx_y private
Definition at line 91 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_z
float larcv::ReadNueFile::_vtx_z private
Definition at line 92 of file ReadNueFile.h.
Referenced by ClearVertex(), initialize(), and process().
checkEvents
std::vector<std::string> larcv::ReadNueFile::checkEvents private
Definition at line 47 of file ReadNueFile.h.
iTrack
int larcv::ReadNueFile::iTrack private
Definition at line 33 of file ReadNueFile.h.
Referenced by process().
tracker
larcv::AStarTracker larcv::ReadNueFile::tracker private
Definition at line 35 of file ReadNueFile.h.
Referenced by finalize(), initialize(), process(), and SetSplineLocation().
The documentation for this class was generated from the following files:
ReadNueFile.h
ReadNueFile.cxx