LArCV: larcv::ImageFromPixel2DProcessFactory Class Reference
larcv::ImageFromPixel2DProcessFactory Class Reference
#include <ImageFromPixel2D.h>
Public Member Functions
ImageFromPixel2DProcessFactory ()
ctor
~ImageFromPixel2DProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 64 of file ImageFromPixel2D.h.
Constructor & Destructor Documentation
ImageFromPixel2DProcessFactory()
larcv::ImageFromPixel2DProcessFactory::ImageFromPixel2DProcessFactory () inline
ctor
Definition at line 67 of file ImageFromPixel2D.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ImageFromPixel2D",this); }
~ImageFromPixel2DProcessFactory()
larcv::ImageFromPixel2DProcessFactory::~ImageFromPixel2DProcessFactory () inline
dtor
Definition at line 69 of file ImageFromPixel2D.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ImageFromPixel2DProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 71 of file ImageFromPixel2D.h.
References larcv::ImageFromPixel2D::ImageFromPixel2D().
 { return new ImageFromPixel2D(instance_name); }
The documentation for this class was generated from the following file:
ImageFromPixel2D.h