LArCV: larcv::AlgoDataAna Class Reference
larcv::AlgoDataAna Class Reference
#include <AlgoDataAna.h>
Public Member Functions
AlgoDataAna (const std::string name="AlgoDataAna")
~AlgoDataAna ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
LArOCVSerial * _larocvserial
TChain * _reco_chain
size_t _reco_index
size_t _reco_entries
std::string _input_larbys_reco_root_file
uint _reco_run
uint _reco_subrun
uint _reco_event
uint _reco_entry
std::string _reco_tree_name
std::string _serial_name
TTree * _vertex_tree
double _reco_vertex_x
double _reco_vertex_y
double _reco_vertex_z
Detailed Description
Definition at line 11 of file AlgoDataAna.h.
Constructor & Destructor Documentation
AlgoDataAna()
larcv::AlgoDataAna::AlgoDataAna (const std::string name = "AlgoDataAna")
Definition at line 10 of file AlgoDataAna.cxx.
Referenced by larcv::AlgoDataAnaProcessFactory::create().
     : ProcessBase(name), _larocvserial(nullptr), _reco_chain(nullptr), _vertex_tree(nullptr)
   {}
~AlgoDataAna()
larcv::AlgoDataAna::~AlgoDataAna () inline
Definition at line 14 of file AlgoDataAna.h.
References configure(), and initialize().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::AlgoDataAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file AlgoDataAna.cxx.
References _input_larbys_reco_root_file, _reco_tree_name, _serial_name, and larcv::PSet::get().
Referenced by ~AlgoDataAna().
   {
     _input_larbys_reco_root_file = cfg.get<std::string>("InputLArbysImageFile");
     _reco_tree_name = cfg.get<std::string>("RecoTreeName");
     _serial_name    = cfg.get<std::string>("LArOCVSerialName");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::AlgoDataAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 45 of file AlgoDataAna.cxx.
References _larocvserial, _reco_chain, _reco_entries, _reco_entry, _reco_event, _reco_run, _reco_subrun, _reco_vertex_x, _reco_vertex_y, _reco_vertex_z, _vertex_tree, larcv::LArOCVSerial::_vertex_v, larcv::ProcessBase::ana_file(), LARCV_DEBUG, and LARCV_INFO.
Referenced by process().
   {
     LARCV_INFO() << "See... " << _reco_entries << "... reco entries" << std::endl;
     for(size_t reco_entry=0; reco_entry<_reco_entries; ++reco_entry) {
       if (reco_entry)
     _reco_chain->GetEntry(reco_entry);
       if(!_larocvserial)
     throw larbys("Invalid pointer to LArOCVSerial type");
       _reco_entry = reco_entry;
       LARCV_DEBUG() << reco_entry << ") @("
             <<_reco_run    <<","
             <<_reco_subrun <<","
             <<_reco_event  <<","
             <<_reco_entry  <<") vtx sz: "
             << _larocvserial->_vertex_v.size() << std::endl;
       for(const auto& vtx : _larocvserial->_vertex_v) {
     _reco_vertex_x = vtx.x;
     _reco_vertex_y = vtx.y;
     _reco_vertex_z = vtx.z;
     _vertex_tree->Fill();
       }
     }
     ana_file().cd();
     _vertex_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::AlgoDataAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 21 of file AlgoDataAna.cxx.
References _input_larbys_reco_root_file, _larocvserial, _reco_chain, _reco_entries, _reco_entry, _reco_event, _reco_index, _reco_run, _reco_subrun, _reco_tree_name, _reco_vertex_x, _reco_vertex_y, _reco_vertex_z, _serial_name, and _vertex_tree.
Referenced by ~AlgoDataAna().
   {
     _reco_chain = new TChain(_reco_tree_name.c_str());
     _reco_chain->AddFile(_input_larbys_reco_root_file.c_str());
     _reco_chain->SetBranchAddress("run",&_reco_run);
     _reco_chain->SetBranchAddress("subrun",&_reco_subrun);
     _reco_chain->SetBranchAddress("event",&_reco_event);
     _reco_chain->SetBranchAddress("entry",&_reco_entry);
     _reco_chain->SetBranchAddress(_serial_name.c_str(),&_larocvserial);
     _reco_index = 0;
     _reco_chain->GetEntry(_reco_index);
     _reco_entries = _reco_chain->GetEntries();
     _vertex_tree = new TTree("OutTree","OutTree");
     _vertex_tree->Branch("run"   ,&_reco_run,"run/i");
     _vertex_tree->Branch("subrun",&_reco_subrun,"subrun/i");
     _vertex_tree->Branch("event" ,&_reco_event,"event/i");
     _vertex_tree->Branch("entry" ,&_reco_entry,"entry/i");
     _vertex_tree->Branch("x",&_reco_vertex_x,"x/D");
     _vertex_tree->Branch("y",&_reco_vertex_y,"y/D");
     _vertex_tree->Branch("z",&_reco_vertex_z,"z/D");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::AlgoDataAna::process (IOManager & mgr) inline virtual
Implements larcv::ProcessBase.
Definition at line 18 of file AlgoDataAna.h.
References finalize().
 { return true; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_input_larbys_reco_root_file
std::string larcv::AlgoDataAna::_input_larbys_reco_root_file
Definition at line 27 of file AlgoDataAna.h.
Referenced by configure(), and initialize().
_larocvserial
LArOCVSerial* larcv::AlgoDataAna::_larocvserial
Definition at line 21 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_chain
TChain* larcv::AlgoDataAna::_reco_chain
Definition at line 23 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_entries
size_t larcv::AlgoDataAna::_reco_entries
Definition at line 25 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_entry
uint larcv::AlgoDataAna::_reco_entry
Definition at line 32 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_event
uint larcv::AlgoDataAna::_reco_event
Definition at line 31 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_index
size_t larcv::AlgoDataAna::_reco_index
Definition at line 24 of file AlgoDataAna.h.
Referenced by initialize().
_reco_run
uint larcv::AlgoDataAna::_reco_run
Definition at line 29 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_subrun
uint larcv::AlgoDataAna::_reco_subrun
Definition at line 30 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_tree_name
std::string larcv::AlgoDataAna::_reco_tree_name
Definition at line 34 of file AlgoDataAna.h.
Referenced by configure(), and initialize().
_reco_vertex_x
double larcv::AlgoDataAna::_reco_vertex_x
Definition at line 38 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_vertex_y
double larcv::AlgoDataAna::_reco_vertex_y
Definition at line 39 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_reco_vertex_z
double larcv::AlgoDataAna::_reco_vertex_z
Definition at line 40 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
_serial_name
std::string larcv::AlgoDataAna::_serial_name
Definition at line 35 of file AlgoDataAna.h.
Referenced by configure(), and initialize().
_vertex_tree
TTree* larcv::AlgoDataAna::_vertex_tree
Definition at line 37 of file AlgoDataAna.h.
Referenced by finalize(), and initialize().
The documentation for this class was generated from the following files:
AlgoDataAna.h
AlgoDataAna.cxx