LArCV: larcv::ROIAnaProcessFactory Class Reference
larcv::ROIAnaProcessFactory Class Reference
#include <ROIAna.h>
Public Member Functions
ROIAnaProcessFactory ()
ctor
~ROIAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 96 of file ROIAna.h.
Constructor & Destructor Documentation
ROIAnaProcessFactory()
larcv::ROIAnaProcessFactory::ROIAnaProcessFactory () inline
ctor
Definition at line 99 of file ROIAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ROIAna",this); }
~ROIAnaProcessFactory()
larcv::ROIAnaProcessFactory::~ROIAnaProcessFactory () inline
dtor
Definition at line 101 of file ROIAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ROIAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 103 of file ROIAna.h.
References larcv::ROIAna::ROIAna().
 { return new ROIAna(instance_name); }
The documentation for this class was generated from the following file:
ROIAna.h