LArCV: larcv::MultiROICropperProcessFactory Class Reference
larcv::MultiROICropperProcessFactory Class Reference
#include <MultiROICropper.h>
Public Member Functions
MultiROICropperProcessFactory ()
ctor
~MultiROICropperProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 68 of file MultiROICropper.h.
Constructor & Destructor Documentation
MultiROICropperProcessFactory()
larcv::MultiROICropperProcessFactory::MultiROICropperProcessFactory () inline
ctor
Definition at line 71 of file MultiROICropper.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("MultiROICropper",this); }
~MultiROICropperProcessFactory()
larcv::MultiROICropperProcessFactory::~MultiROICropperProcessFactory () inline
dtor
Definition at line 73 of file MultiROICropper.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::MultiROICropperProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 75 of file MultiROICropper.h.
References larcv::MultiROICropper::MultiROICropper().
 { return new MultiROICropper(instance_name); }
The documentation for this class was generated from the following file:
MultiROICropper.h