LArCV: larcv::MaskImage Class Reference
larcv::MaskImage Class Reference
#include <MaskImage.h>
Public Member Functions
MaskImage (const std::string name="MaskImage")
Default constructor.
~MaskImage ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
float _pi_thresh_min
float _mask_value
bool _ignore_ref_origin
bool _use_abs_value
std::string _output_producer
std::string _reference_image_producer
std::string _target_image_producer
Detailed Description
Definition at line 26 of file MaskImage.h.
Constructor & Destructor Documentation
MaskImage()
larcv::MaskImage::MaskImage (const std::string name = "MaskImage")
Default constructor.
Definition at line 11 of file MaskImage.cxx.
Referenced by larcv::MaskImageProcessFactory::create().
     : ProcessBase(name)
   {}
~MaskImage()
larcv::MaskImage::~MaskImage () inline
Default destructor.
Definition at line 34 of file MaskImage.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::MaskImage::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file MaskImage.cxx.
References _ignore_ref_origin, _mask_value, _output_producer, _pi_thresh_min, _reference_image_producer, _target_image_producer, _use_abs_value, and larcv::PSet::get().
Referenced by ~MaskImage().
   {
     _pi_thresh_min = cfg.get<float>("MinPIThreshold");
     _use_abs_value = cfg.get<bool>("UseAbsValue",false);
     _mask_value = cfg.get<float>("MaskValue");
     _output_producer = cfg.get<std::string>("OutputProducer","");
     _reference_image_producer = cfg.get<std::string>("ReferenceProducer");
     _target_image_producer = cfg.get<std::string>("TargetProducer");
     _ignore_ref_origin = cfg.get<bool>("IgnoreRefOrigin",false);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::MaskImage::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 117 of file MaskImage.cxx.
Referenced by ~MaskImage().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::MaskImage::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 27 of file MaskImage.cxx.
Referenced by ~MaskImage().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::MaskImage::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 30 of file MaskImage.cxx.
References _ignore_ref_origin, _mask_value, _output_producer, _pi_thresh_min, _reference_image_producer, _target_image_producer, _use_abs_value, larcv::EventImage2D::Emplace(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_CRITICAL, LARCV_DEBUG, and larcv::Image2D::paint().
Referenced by ~MaskImage().
   {
     auto ref_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_reference_image_producer));
     if(!ref_event_image) {
       LARCV_CRITICAL() << "Reference EventImage2D not found: " << _reference_image_producer << std::endl;
       throw larbys();
     }
     auto tar_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_target_image_producer));
     if(!tar_event_image) {
       LARCV_CRITICAL() << "Target EventImage2D not found: " << _target_image_producer << std::endl;
       throw larbys();
     }
     EventImage2D* out_event_image = nullptr;
     if(_output_producer.empty()) out_event_image = tar_event_image;
     else out_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_output_producer));
     if(!out_event_image) {
       LARCV_CRITICAL() << "Output EventImage2D could not be made " << _output_producer << std::endl;
       throw larbys();
     }
     auto const& ref_image_v = ref_event_image->Image2DArray();
     std::vector<larcv::Image2D> tar_image_v;
     if(_output_producer.empty())
       tar_event_image->Move(tar_image_v);
     else
       tar_image_v = tar_event_image->Image2DArray();
     // Check # planes
     if(ref_image_v.size() != tar_image_v.size()) {
       LARCV_CRITICAL() << "# planes in target (" << tar_image_v.size()
                << ") producer " << _target_image_producer << " and reference (" << ref_image_v.size()
                << ") producer " << _reference_image_producer << " are not same!" << std::endl;
       throw larbys();
     }
     for(size_t pid=0; pid<tar_image_v.size(); ++pid) {
       auto& tar_image = tar_image_v[pid];
       auto ref_image = Image2D(tar_image.meta());
       ref_image.paint(0);
       LARCV_DEBUG() << "Overlaying:\n" << tar_image.meta().dump() << ref_image_v[pid].meta().dump() << std::flush;
       if(_ignore_ref_origin) {
     if(tar_image.meta().cols() != ref_image_v[pid].meta().cols() ||
        tar_image.meta().rows() != ref_image_v[pid].meta().rows() ) {
       LARCV_CRITICAL() << "IgnoreRefOrigin option = true ... only allowed if ref and target image dimensions are identical!" << std::endl;
       throw larbys();
     }
     std::vector<float> ref_data = ref_image_v[pid].as_vector();
     ref_image.move(std::move(ref_data));
       }
       else{ ref_image.overlay( ref_image_v[pid] ); }
       if(tar_image.as_vector().size() != ref_image.as_vector().size()) {
     LARCV_CRITICAL() << "Different size among the target (" << tar_image.as_vector().size()
              << ") and reference (" << ref_image.as_vector().size()
              << ")!" << std::endl;
     throw larbys();
       }
       auto const& ref_vector = ref_image.as_vector();
       if(_use_abs_value) {
     for(size_t px_idx = 0; px_idx < ref_vector.size(); ++px_idx)
       if( std::fabs(ref_vector[px_idx]) < _pi_thresh_min) tar_image.set_pixel(px_idx,_mask_value);
       } else {
     for(size_t px_idx = 0; px_idx < ref_vector.size(); ++px_idx)
       if(ref_vector[px_idx] < _pi_thresh_min) tar_image.set_pixel(px_idx,_mask_value);
       }
     }
     out_event_image->Emplace(std::move(tar_image_v));
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_ignore_ref_origin
bool larcv::MaskImage::_ignore_ref_origin private
Definition at line 48 of file MaskImage.h.
Referenced by configure(), and process().
_mask_value
float larcv::MaskImage::_mask_value private
Definition at line 47 of file MaskImage.h.
Referenced by configure(), and process().
_output_producer
std::string larcv::MaskImage::_output_producer private
Definition at line 50 of file MaskImage.h.
Referenced by configure(), and process().
_pi_thresh_min
float larcv::MaskImage::_pi_thresh_min private
Definition at line 46 of file MaskImage.h.
Referenced by configure(), and process().
_reference_image_producer
std::string larcv::MaskImage::_reference_image_producer private
Definition at line 51 of file MaskImage.h.
Referenced by configure(), and process().
_target_image_producer
std::string larcv::MaskImage::_target_image_producer private
Definition at line 52 of file MaskImage.h.
Referenced by configure(), and process().
_use_abs_value
bool larcv::MaskImage::_use_abs_value private
Definition at line 49 of file MaskImage.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
MaskImage.h
MaskImage.cxx