LArCV: larcv::PGraphTruthMatch Class Reference
larcv::PGraphTruthMatch Class Reference
#include <PGraphTruthMatch.h>
Public Member Functions
PGraphTruthMatch (const std::string name="PGraphTruthMatch")
~PGraphTruthMatch ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void ClearVertex ()
Private Attributes
TTree * _tree
std::string _adc_img2d_prod
std::string _true_img2d_prod
std::string _reco_pgraph_prod
std::string _reco_pixel_prod
int _run
int _subrun
int _event
int _entry
int _vtxid
float _vtx_x
float _vtx_y
float _vtx_z
int _vtx_on_nu
std::vector< float > _unknownfrac_v
std::vector< float > _electronfrac_v
std::vector< float > _gammafrac_v
std::vector< float > _pizerofrac_v
std::vector< float > _muonfrac_v
std::vector< float > _kminusfrac_v
std::vector< float > _piminusfrac_v
std::vector< float > _protonfrac_v
std::vector< int > _vtx_on_nu_v
std::vector< int > _par_npx_v
std::vector< int > _par_id_v
std::vector< std::vector< int > > _par_id_vv
Detailed Description
Definition at line 9 of file PGraphTruthMatch.h.
Constructor & Destructor Documentation
PGraphTruthMatch()
larcv::PGraphTruthMatch::PGraphTruthMatch (const std::string name = "PGraphTruthMatch")
Definition at line 16 of file PGraphTruthMatch.cxx.
Referenced by larcv::PGraphTruthMatchProcessFactory::create().
     : ProcessBase(name)
   {}
~PGraphTruthMatch()
larcv::PGraphTruthMatch::~PGraphTruthMatch () inline
Definition at line 13 of file PGraphTruthMatch.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearVertex()
void larcv::PGraphTruthMatch::ClearVertex () private
Definition at line 299 of file PGraphTruthMatch.cxx.
References _electronfrac_v, _gammafrac_v, _kminusfrac_v, _muonfrac_v, _par_id_v, _par_id_vv, _par_npx_v, _piminusfrac_v, _pizerofrac_v, _protonfrac_v, _unknownfrac_v, _vtx_on_nu, _vtx_on_nu_v, _vtx_x, _vtx_y, _vtx_z, _vtxid, larcv::kINVALID_FLOAT, and larcv::kINVALID_INT.
Referenced by process().
{
     _vtx_x = -1.0*kINVALID_FLOAT;
     _vtx_y = -1.0*kINVALID_FLOAT;
     _vtx_z = -1.0*kINVALID_FLOAT;
     _vtxid     = -1.0*kINVALID_INT;
     _vtx_on_nu = -1.0*kINVALID_INT;
     _vtx_on_nu_v.clear();
     _par_id_v.clear();
     _par_id_vv.clear();
     _par_npx_v.clear();
     _unknownfrac_v.clear();
     _electronfrac_v.clear();
     _gammafrac_v.clear();
     _pizerofrac_v.clear();
     _muonfrac_v.clear();
     _kminusfrac_v.clear();
     _piminusfrac_v.clear();
     _protonfrac_v.clear();
   }
configure()
void larcv::PGraphTruthMatch::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 20 of file PGraphTruthMatch.cxx.
References _adc_img2d_prod, _reco_pgraph_prod, _reco_pixel_prod, _true_img2d_prod, larcv::PSet::get(), and LARCV_INFO.
Referenced by ~PGraphTruthMatch().
   {
     LARCV_INFO() << "start" << std::endl;
     _adc_img2d_prod     = cfg.get<std::string>("ADCImageProducer");
     _true_img2d_prod    = cfg.get<std::string>("TrueImageProducer");
     _reco_pgraph_prod   = cfg.get<std::string>("RecoPGraphProducer");
     _reco_pixel_prod    = cfg.get<std::string>("RecoPxProducer");
     LARCV_INFO() << "end" << std::endl;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::PGraphTruthMatch::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 292 of file PGraphTruthMatch.cxx.
References _tree, and LARCV_DEBUG.
Referenced by ~PGraphTruthMatch().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _tree->Write();
     LARCV_DEBUG() << "end" << std::endl;
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::PGraphTruthMatch::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 30 of file PGraphTruthMatch.cxx.
References _electronfrac_v, _entry, _event, _gammafrac_v, _kminusfrac_v, _muonfrac_v, _par_id_v, _par_id_vv, _par_npx_v, _piminusfrac_v, _pizerofrac_v, _protonfrac_v, _run, _subrun, _tree, _unknownfrac_v, _vtx_on_nu, _vtx_on_nu_v, _vtx_x, _vtx_y, _vtx_z, _vtxid, and LARCV_DEBUG.
Referenced by ~PGraphTruthMatch().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _tree = new TTree("PGraphTruthMatch","");
     _tree->Branch("run"    , &_run    , "run/I");
     _tree->Branch("subrun" , &_subrun , "subrun/I");
     _tree->Branch("event"  , &_event  , "event/I");
     _tree->Branch("entry"  , &_entry  , "entry/I");
     _tree->Branch("vtxid"       , &_vtxid, "vtxid/I");
     _tree->Branch("vtx_x"       , &_vtx_x, "vtx_x/F");
     _tree->Branch("vtx_y"       , &_vtx_y, "vtx_y/F");
     _tree->Branch("vtx_z"       , &_vtx_z, "vtx_z/F");
     _tree->Branch("vtx_on_nu"   , &_vtx_on_nu, "vtx_on_nu/I");
     _tree->Branch("vtx_on_nu_v" , &_vtx_on_nu_v);
     _tree->Branch("unknownfrac_v" , &_unknownfrac_v);
     _tree->Branch("electronfrac_v", &_electronfrac_v);
     _tree->Branch("gammafrac_v"   , &_gammafrac_v);
     _tree->Branch("pizerofrac_v"  , &_pizerofrac_v);
     _tree->Branch("muonfrac_v"    , &_muonfrac_v);
     _tree->Branch("kminusfrac_v"  , &_kminusfrac_v);
     _tree->Branch("piminusfrac_v" , &_piminusfrac_v);
     _tree->Branch("protonfrac_v"  , &_protonfrac_v);
     _tree->Branch("par_npx_v", &_par_npx_v);
     _tree->Branch("par_id_v" , &_par_id_v);
     _tree->Branch("par_id_vv", &_par_id_vv);
     LARCV_DEBUG() << "end" << std::endl;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::PGraphTruthMatch::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 63 of file PGraphTruthMatch.cxx.
References _adc_img2d_prod, _electronfrac_v, _entry, _event, _gammafrac_v, _kminusfrac_v, _muonfrac_v, _par_id_v, _par_id_vv, _par_npx_v, _piminusfrac_v, _pizerofrac_v, _protonfrac_v, _reco_pgraph_prod, _reco_pixel_prod, _run, _subrun, _tree, _true_img2d_prod, _unknownfrac_v, _vtx_on_nu, _vtx_on_nu_v, _vtx_x, _vtx_y, _vtx_z, _vtxid, ClearVertex(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kINVALID_DOUBLE, larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kROITypeMax, LARCV_DEBUG, LARCV_WARNING, and larcv::Project3D().
Referenced by ~PGraphTruthMatch().
   {
     ClearVertex();
     auto ev_adc_img     = (EventImage2D*) mgr.get_data(kProductImage2D , _adc_img2d_prod);
     _run    = (int)ev_adc_img->run();
     _subrun = (int)ev_adc_img->subrun();
     _event  = (int)ev_adc_img->event();
     _entry  = (int)mgr.current_entry();
     if (_true_img2d_prod.empty()) {
       _tree->Fill();
       return true;
     }
     auto ev_seg_img     = (EventImage2D*) mgr.get_data(kProductImage2D , _true_img2d_prod);
     auto ev_reco_pgraph = (EventPGraph*)  mgr.get_data(kProductPGraph  , _reco_pgraph_prod);
     auto ev_reco_pix    = (EventPixel2D*) mgr.get_data(kProductPixel2D , _reco_pixel_prod);
     const auto& adc_img_v   = ev_adc_img->Image2DArray();
     const auto& seg_img_v   = ev_seg_img->Image2DArray();
     const auto& pgraph_v    = ev_reco_pgraph->PGraphArray();
     const auto& pix_m       = ev_reco_pix->Pixel2DClusterArray();
     const auto& pix_meta_m  = ev_reco_pix->ClusterMetaArray();
     LARCV_DEBUG() << "GOT: " << pgraph_v.size() << " vertices" << std::endl;
     for(size_t pgraph_id = 0; pgraph_id < pgraph_v.size(); ++pgraph_id) {
       ClearVertex();
       _vtxid = (int)pgraph_id;
       LARCV_DEBUG() << "@pgraph_id=" << pgraph_id << std::endl;
       auto const& pgraph        = pgraph_v.at(pgraph_id);
       auto const& roi_v         = pgraph.ParticleArray();
       auto const& cluster_idx_v = pgraph.ClusterIndexArray();
       //
       // vertex on NU pixels ?
       //
       const auto reco_x = roi_v.front().X();
       const auto reco_y = roi_v.front().Y();
       const auto reco_z = roi_v.front().Z();
       _vtx_x = reco_x;
       _vtx_y = reco_y;
       _vtx_z = reco_z;
       _vtx_on_nu_v.resize(3,0);
       for(size_t plane=0; plane<3; ++plane) {
     const auto& plane_img = seg_img_v.at(plane);
     const auto& pmeta = plane_img.meta();
     const int nrows = plane_img.meta().rows();
     const int ncols = plane_img.meta().cols();
     double xpixel = larcv::kINVALID_DOUBLE;
     double ypixel = larcv::kINVALID_DOUBLE;
     Project3D(pmeta,
           reco_x,reco_y,reco_z,0.0,
           plane,
           xpixel, ypixel);
     // Projection outside the image can happen
     int xx = (int) (xpixel+0.5);
     int yy = (int) (ypixel+0.5);
     yy = nrows - yy - 1;
     float pixel_type = 0.0;
     if (yy >= nrows or yy < 0) {
       LARCV_WARNING() << "3D location outside of image! Skip this plane" << std::endl;
       LARCV_WARNING() << "(rx,ry,rz)=(" << reco_x << "," << reco_y << "," << reco_z << ")" << std::endl;
       LARCV_WARNING() << "(x,y)=(" << xx << "," << yy << ")" << std::endl;
       continue;
     }
     if (xx >= ncols or xx < 0) {
       LARCV_WARNING() << "3D location outside of image! Skip this plane" << std::endl;
       LARCV_WARNING() << "(rx,ry,rz)=(" << reco_x << "," << reco_y << "," << reco_z << ")" << std::endl;
       LARCV_WARNING() << "(x,y)=(" << xx << "," << yy << ")" << std::endl;
       continue;
     }
     pixel_type += plane_img.pixel(yy,xx);
     // check a ``box" around this projected location
     int yp1 = yy+1;
     int xp1 = xx+1;
     int ym1 = yy-1;
     int xm1 = xx-1;
     // (yp,x) (yp,xp) (yp,xm)
     if (yp1 >= 0 and yp1 < nrows) {
       pixel_type += plane_img.pixel(yp1,xx);
       if (xp1 >= 0 and xp1 < ncols) pixel_type += plane_img.pixel(yp1,xp1);
       if (xm1 >= 0 and xm1 < ncols) pixel_type += plane_img.pixel(yp1,xm1);
     }
     // (ym,x) (ym,xp) (ym,xm)
     if (ym1 >= 0 and ym1 < nrows) {
       pixel_type += plane_img.pixel(ym1,xx);
       if (xp1 >= 0 and xp1 < ncols) pixel_type += plane_img.pixel(ym1,xp1);
       if (xm1 >= 0 and xm1 < ncols) pixel_type += plane_img.pixel(ym1,xm1);
     }
     // (y,xp) (y,xm)
     if(xp1>=0 and xp1<ncols) pixel_type += plane_img.pixel(yy,xp1);
     if(xm1>=0 and xm1<ncols) pixel_type += plane_img.pixel(yy,xm1);
     if (pixel_type > 0) _vtx_on_nu_v[plane] = 1;
       }
       _vtx_on_nu = 0;
       for(auto on_nu : _vtx_on_nu_v) {
     if (on_nu>0) _vtx_on_nu += 1;
       }
       //
       // particle enclose which NU daughters?
       //
       auto npars = roi_v.size();
       _unknownfrac_v.resize(npars);
       _electronfrac_v.resize(npars);
       _gammafrac_v.resize(npars);
       _pizerofrac_v.resize(npars);
       _muonfrac_v.resize(npars);
       _kminusfrac_v.resize(npars);
       _piminusfrac_v.resize(npars);
       _protonfrac_v.resize(npars);
       _par_id_v.resize(npars);
       _par_id_vv.resize(npars);
       _par_npx_v.resize(npars,0);
       LARCV_DEBUG() << "GOT: " << npars << " particles" << std::endl;
       for(size_t roid=0; roid < npars; ++roid) {
     std::vector<int> pixel_type_v(((int)larcv::kROITypeMax)+1,0);
     const auto& roi = roi_v[roid];
     auto cidx = cluster_idx_v.at(roid);
     for(size_t plane=0; plane<3; ++plane) {
       auto iter_pix = pix_m.find(plane);
       if(iter_pix == pix_m.end())
         continue;
       auto iter_pix_meta = pix_meta_m.find(plane);
       if(iter_pix_meta == pix_meta_m.end())
         continue;
       auto const& pix_v      = (*iter_pix).second;
       auto const& pix_meta_v = (*iter_pix_meta).second;
       auto const& pix      = pix_v.at(cidx);
       auto const& pix_meta = pix_meta_v.at(cidx);
       const auto& plane_img = seg_img_v.at(plane);
       for(const auto& px : pix) {
         auto posx = pix_meta.pos_x(px.Y());
         auto posy = pix_meta.pos_y(px.X());
         auto row  = plane_img.meta().row(posy);
         auto col  = plane_img.meta().col(posx);
         float pixel_type = (size_t) plane_img.pixel(row,col);
         pixel_type_v.at((size_t)pixel_type) += 1;
       }
     } // end plane
       int npixels = 0;
       for(auto px_count : pixel_type_v)
     npixels += px_count;
       _par_npx_v[roid] = npixels;
       auto res_iter = std::max_element(std::begin(pixel_type_v), std::end(pixel_type_v));
       auto res_loc  = std::distance(std::begin(pixel_type_v), res_iter);
       _par_id_v[roid] = res_loc;
       auto& unknownfrac  = _unknownfrac_v[roid];
       auto& electronfrac = _electronfrac_v[roid];
       auto& gammafrac    = _gammafrac_v[roid];
       auto& pizerofrac   = _pizerofrac_v[roid];
       auto& muonfrac     = _muonfrac_v[roid];
       auto& kminusfrac   = _kminusfrac_v[roid];
       auto& piminusfrac  = _piminusfrac_v[roid];
       auto& protonfrac   = _protonfrac_v[roid];
       unknownfrac  = 0.0;
       electronfrac = 0.0;
       gammafrac    = 0.0;
       pizerofrac   = 0.0;
       muonfrac     = 0.0;
       kminusfrac   = 0.0;
       piminusfrac  = 0.0;
       protonfrac   = 0.0;
       if (npixels) {
     unknownfrac  = (float) pixel_type_v.at(0) / (float) npixels;
     electronfrac = (float) pixel_type_v.at(3) / (float) npixels;
     gammafrac    = (float) pixel_type_v.at(4) / (float) npixels;
     pizerofrac   = (float) pixel_type_v.at(5) / (float) npixels;
     muonfrac     = (float) pixel_type_v.at(6) / (float) npixels;
     kminusfrac   = (float) pixel_type_v.at(7) / (float) npixels;
     piminusfrac  = (float) pixel_type_v.at(8) / (float) npixels;
     protonfrac   = (float) pixel_type_v.at(9) / (float) npixels;
       }
       _par_id_vv[roid] = std::move(pixel_type_v);
       } // end this particle
       LARCV_DEBUG() << "... next" << std::endl;
       _tree->Fill();
     } // end this vertex
     LARCV_DEBUG() << "end" << std::endl;
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_adc_img2d_prod
std::string larcv::PGraphTruthMatch::_adc_img2d_prod private
Definition at line 22 of file PGraphTruthMatch.h.
Referenced by configure(), and process().
_electronfrac_v
std::vector<float> larcv::PGraphTruthMatch::_electronfrac_v private
Definition at line 41 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_entry
int larcv::PGraphTruthMatch::_entry private
Definition at line 30 of file PGraphTruthMatch.h.
Referenced by initialize(), and process().
_event
int larcv::PGraphTruthMatch::_event private
Definition at line 29 of file PGraphTruthMatch.h.
Referenced by initialize(), and process().
_gammafrac_v
std::vector<float> larcv::PGraphTruthMatch::_gammafrac_v private
Definition at line 42 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_kminusfrac_v
std::vector<float> larcv::PGraphTruthMatch::_kminusfrac_v private
Definition at line 45 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_muonfrac_v
std::vector<float> larcv::PGraphTruthMatch::_muonfrac_v private
Definition at line 44 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_par_id_v
std::vector<int> larcv::PGraphTruthMatch::_par_id_v private
Definition at line 51 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_par_id_vv
std::vector<std::vector<int> > larcv::PGraphTruthMatch::_par_id_vv private
Definition at line 52 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_par_npx_v
std::vector<int> larcv::PGraphTruthMatch::_par_npx_v private
Definition at line 50 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_piminusfrac_v
std::vector<float> larcv::PGraphTruthMatch::_piminusfrac_v private
Definition at line 46 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_pizerofrac_v
std::vector<float> larcv::PGraphTruthMatch::_pizerofrac_v private
Definition at line 43 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_protonfrac_v
std::vector<float> larcv::PGraphTruthMatch::_protonfrac_v private
Definition at line 47 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_reco_pgraph_prod
std::string larcv::PGraphTruthMatch::_reco_pgraph_prod private
Definition at line 24 of file PGraphTruthMatch.h.
Referenced by configure(), and process().
_reco_pixel_prod
std::string larcv::PGraphTruthMatch::_reco_pixel_prod private
Definition at line 25 of file PGraphTruthMatch.h.
Referenced by configure(), and process().
_run
int larcv::PGraphTruthMatch::_run private
Definition at line 27 of file PGraphTruthMatch.h.
Referenced by initialize(), and process().
_subrun
int larcv::PGraphTruthMatch::_subrun private
Definition at line 28 of file PGraphTruthMatch.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::PGraphTruthMatch::_tree private
Definition at line 20 of file PGraphTruthMatch.h.
Referenced by finalize(), initialize(), and process().
_true_img2d_prod
std::string larcv::PGraphTruthMatch::_true_img2d_prod private
Definition at line 23 of file PGraphTruthMatch.h.
Referenced by configure(), and process().
_unknownfrac_v
std::vector<float> larcv::PGraphTruthMatch::_unknownfrac_v private
Definition at line 40 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_on_nu
int larcv::PGraphTruthMatch::_vtx_on_nu private
Definition at line 38 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_on_nu_v
std::vector<int> larcv::PGraphTruthMatch::_vtx_on_nu_v private
Definition at line 49 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_x
float larcv::PGraphTruthMatch::_vtx_x private
Definition at line 34 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_y
float larcv::PGraphTruthMatch::_vtx_y private
Definition at line 35 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_z
float larcv::PGraphTruthMatch::_vtx_z private
Definition at line 36 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
_vtxid
int larcv::PGraphTruthMatch::_vtxid private
Definition at line 32 of file PGraphTruthMatch.h.
Referenced by ClearVertex(), initialize(), and process().
The documentation for this class was generated from the following files:
PGraphTruthMatch.h
PGraphTruthMatch.cxx