LArCV: larcv::ThreadDatumFiller Class Reference
larcv::ThreadDatumFiller Class Reference
User defined class ThreadDatumFiller ...
#include <ThreadDatumFiller.h>
Public Member Functions
ThreadDatumFiller (std::string name)
Default constructor.
ThreadDatumFiller ()
Default destructor.
void reset ()
void configure (const std::string config_file)
void configure (const PSet &cfg)
void initialize ()
void override_input_file (const std::vector< std::string > &flist)
void batch_process (size_t nentries)
void finalize ()
ProcessID_t process_id (std::string name) const
std::vector< std::string > process_names () const
const std::map< std::string, size_t > & process_map () const
const ProcessBase * process_ptr (ProcessID_t id) const
const IOManager & io () const
ThreadDatumFiller (std::string name="ThreadDatumFiller")
Default constructor.
~ThreadDatumFiller ()
Default destructor.
void reset ()
copy ctor
void configure (const std::string config_file)
void configure (const PSet &cfg)
bool batch_process (size_t nentries=0)
void set_random_access (bool do_random)
void set_next_index (size_t index)
void set_next_batch (const std::vector< size_t > &index_v)
bool thread_config () const
bool thread_running () const
size_t process_ctr () const
size_t get_n_entries () const
const std::vector< size_t > & processed_entries () const
const std::vector< larcv::EventBase > & processed_events () const
const std::string & producer (DatumFillerBase::FillerDataType_t dtype) const
const std::vector< int > dim (bool image=true) const
const std::vector< float > & data () const
const std::vector< float > & labels () const
const std::vector< float > & weights () const
const std::vector< float > & multiplicities () const
const std::vector< std::vector< larcv::ImageMeta > > & meta () const
const ProcessDriver * pd ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
bool _process_entry_ ()
bool _batch_process_ (size_t nentries)
Private Attributes
DatumFillerBase * _filler
std::vector< size_t > _batch_entries
bool _enable_filter
bool _random_access
IOManager _io
std::map< std::string, larcv::ProcessID_t > _proc_m
std::vector< larcv::ProcessBase * > _proc_v
bool _processing
bool _batch_processing
TFile * _fout
std::string _fout_name
ThreadFillerState_t _thread_state
bool _use_threading
bool _configured
size_t _num_processed
std::vector< larcv::EventBase > _batch_events
std::vector< int > _dim_v
ProcessDriver _driver
std::thread _th
std::vector< std::string > _input_fname_v
size_t _optional_next_index
std::vector< size_t > _optional_next_index_v
Detailed Description
User defined class ThreadDatumFiller ...
these comments are used to generate doxygen documentation!
Definition at line 27 of file arxiv/ThreadDatumFiller.h.
Constructor & Destructor Documentation
ThreadDatumFiller() [1/3]
larcv::ThreadDatumFiller::ThreadDatumFiller (std::string name)
Default constructor.
Definition at line 11 of file arxiv/ThreadDatumFiller.cxx.
     : larcv_base(name)
     , _filler(nullptr)
     , _enable_filter(false)
     , _random_access(false)
     , _io(IOManager::kREAD)
     , _proc_v()
     , _processing(false)
     , _fout(nullptr)
     , _fout_name("")
   {}
ThreadDatumFiller() [2/3]
larcv::ThreadDatumFiller::ThreadDatumFiller () inline
Default destructor.
Definition at line 35 of file arxiv/ThreadDatumFiller.h.
References batch_process(), configure(), finalize(), initialize(), override_input_file(), process_id(), process_map(), process_names(), process_ptr(), and reset().
 {}
ThreadDatumFiller() [3/3]
larcv::ThreadDatumFiller::ThreadDatumFiller (std::string name = "ThreadDatumFiller")
Default constructor.
~ThreadDatumFiller()
larcv::ThreadDatumFiller::~ThreadDatumFiller ()
Default destructor.
Definition at line 26 of file ThreadDatumFiller.cxx.
References _driver, _processing, _th, and larcv::ProcessDriver::finalize().
   {
     if (_th.joinable()) _th.join();
     if (_processing) _driver.finalize();
   }
Member Function Documentation
_batch_process_()
bool larcv::ThreadDatumFiller::_batch_process_ (size_t nentries) private
Definition at line 308 of file ThreadDatumFiller.cxx.
References _batch_entries, _batch_events, _driver, _enable_filter, _filler, larcv::DatumFillerBase::_nentries, _num_processed, _optional_next_index, _optional_next_index_v, _processing, _random_access, _thread_state, larcv::DatumFillerBase::batch_begin(), larcv::DatumFillerBase::batch_end(), larcv::ProcessDriver::event_id(), larcv::EventBase::event_key(), larcv::IOManager< T >::get_n_entries(), larcv::ProcessDriver::get_tree_index(), larcv::ProcessDriver::initialize(), larcv::ProcessDriver::io(), larcv::kINVALID_SIZE, larcv::kThreadStateIdle, larcv::kThreadStateRunning, LARCV_DEBUG, LARCV_INFO, and larcv::ProcessDriver::process_entry().
Referenced by meta(), and pd().
   {
     LARCV_DEBUG() << " start" << std::endl;
     _thread_state = kThreadStateRunning;
     _filler->_nentries = nentries;
     if (!_processing) {
       LARCV_INFO() << "Initializing for 1st time processing" << std::endl;
       _driver.initialize();
       _processing = true;
     }
     size_t last_entry = kINVALID_SIZE - 1;
     if (_batch_entries.size()) last_entry = _batch_entries.back();
     _batch_entries.resize(nentries, 0);
     _batch_events.clear();
     _batch_events.reserve(nentries);
     _filler->_nentries = nentries;
     _filler->batch_begin();
     size_t valid_ctr = 0;
     std::random_device rd;
     std::mt19937 gen(rd());
     std::uniform_int_distribution<> dis(0, _driver.io().get_n_entries() - 1);
     if (_random_access)
       LARCV_INFO() << "Generating random numbers from 0 to " << _driver.io().get_n_entries() << std::endl;
     // counter for _optional_next_index_v
     size_t next_batch_ctr = 0;
     LARCV_INFO() << "Entering process loop" << std::endl;
     while (valid_ctr < nentries) {
       size_t entry = last_entry + 1;
       if(_optional_next_index_v.size()) {
     if(next_batch_ctr >= _optional_next_index_v.size())
       break;
     entry = _optional_next_index_v[next_batch_ctr];
     ++next_batch_ctr;
       }else{
     if (_optional_next_index != kINVALID_SIZE) {
       entry = _optional_next_index;
       _optional_next_index = kINVALID_SIZE;
     }
     if (entry == kINVALID_SIZE) entry = 0;
     if (_random_access) {
       entry = dis(gen);
       while (entry == last_entry) entry = dis(gen);
     }
     else if (entry >= _driver.io().get_n_entries()) entry -= _driver.io().get_n_entries();
       }
       LARCV_INFO() << "Processing entry: " << entry
            << " (tree index=" << _driver.get_tree_index( entry ) << ")" << std::endl;
       last_entry = entry;
       bool good_status = _driver.process_entry(entry, true);
       if (_enable_filter && !good_status) {
         LARCV_INFO() << "Filter enabled: bad event found" << std::endl;
         continue;
       }
       LARCV_INFO() << "Finished processing event id: " << _driver.event_id().event_key() << std::endl;
       _batch_entries[valid_ctr] = _driver.get_tree_index( entry );
       _batch_events.push_back(_driver.event_id());
       ++valid_ctr;
       LARCV_INFO() << "Processed good event: valid entry counter = " << valid_ctr << " : " << _batch_events.size() << std::endl;
     }
     _num_processed += valid_ctr;
     _filler->batch_end();
     _thread_state = kThreadStateIdle;
     _optional_next_index = kINVALID_SIZE;
     _optional_next_index_v.clear();
     LARCV_DEBUG() << " end" << std::endl;
     return true;
   }
_process_entry_()
bool larcv::ThreadDatumFiller::_process_entry_ () private
Referenced by io().
batch_process() [1/2]
bool larcv::ThreadDatumFiller::batch_process (size_t nentries)
Definition at line 219 of file arxiv/ThreadDatumFiller.cxx.
References _batch_entries, _batch_processing, _enable_filter, _filler, _io, larcv::DatumFillerBase::_nentries, _proc_v, _processing, _random_access, larcv::DatumFillerBase::batch_begin(), larcv::DatumFillerBase::batch_end(), larcv::IOManager< T >::get_n_entries(), LARCV_CRITICAL, LARCV_DEBUG, larcv::DatumFillerBase::process(), and larcv::IOManager< T >::read_entry().
Referenced by meta(), and ThreadDatumFiller().
   {
     LARCV_DEBUG() << " start" << std::endl;
     if(!_processing) {
       LARCV_CRITICAL() << "Must call initialize() before start processing!" << std::endl;
       throw larbys();
     }
     _batch_processing = true;
     size_t last_entry = 0;
     if(_batch_entries.size()) last_entry = _batch_entries.back();
     _batch_entries.resize(nentries,0);
     _filler->_nentries = nentries;
     _filler->batch_begin();
     size_t valid_ctr = 0;
     std::random_device rd;
     std::mt19937 gen(rd());
     std::uniform_int_distribution<> dis(0,_io.get_n_entries());
     while(valid_ctr < nentries) {
       size_t entry = ++last_entry;
       if(_random_access) entry = dis(gen);
       else if(entry >= _io.get_n_entries()) entry -= _io.get_n_entries();
       _io.read_entry(entry);
       last_entry = entry;
       bool good_status=true;
       for(auto& p : _proc_v) {
         good_status = good_status && p->_process_(_io);
         if(!good_status && _enable_filter) break;
       }
       if(!good_status && _enable_filter) continue;
       good_status = _filler->process(_io);
       if(!good_status) continue;
       _batch_entries[valid_ctr] = entry;
       ++valid_ctr;
     }
     _filler->batch_end();
     _batch_processing = false;
     LARCV_DEBUG() << " end" << std::endl;
   }
batch_process() [2/2]
bool larcv::ThreadDatumFiller::batch_process (size_t nentries = 0)
configure() [1/4]
void larcv::ThreadDatumFiller::configure (const std::string config_file)
Definition at line 76 of file arxiv/ThreadDatumFiller.cxx.
References _processing, larcv::CreatePSetFromFile(), LARCV_CRITICAL, LARCV_DEBUG, and larcv::larcv_base::name().
Referenced by set_next_batch(), and ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // check state
     if(_processing) {
       LARCV_CRITICAL() << "Must call finalize() before calling initialize() after starting to process..." << std::endl;
       throw larbys();
     }
     // check cfg file
     if(config_file.empty()) {
       LARCV_CRITICAL() << "Config file not set!" << std::endl;
       throw larbys();
     }
     // check cfg content top level
     auto main_cfg = CreatePSetFromFile(config_file);
     if(!main_cfg.contains_pset(name())) {
       LARCV_CRITICAL() << "ThreadDatumFiller configuration (" << name() << ") not found in the config file (dump below)" << std::endl
                << main_cfg.dump()
                << std::endl;
       throw larbys();
     }
     auto const cfg = main_cfg.get<larcv::PSet>(name());
     configure(cfg);
   }
configure() [2/4]
void larcv::ThreadDatumFiller::configure (const PSet & cfg)
Definition at line 102 of file arxiv/ThreadDatumFiller.cxx.
References larcv::ProcessBase::_configure_(), _enable_filter, _filler, _fout_name, _proc_m, _proc_v, _random_access, larcv::PSet::clear(), larcv::PSet::contains_pset(), larcv::ProcessFactory::create(), larcv::PSet::dump(), larcv::ProcessFactory::get(), larcv::PSet::get(), LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, larcv::larcv_base::name(), reset(), and larcv::larcv_base::set_verbosity().
   {
     // check process config exists
     if(!cfg.contains_pset("ProcessList")) {
       LARCV_CRITICAL() << "ProcessList config not found!" << std::endl
                << cfg.dump() << std::endl;
       throw larbys();
     }
     // check if filler config exists
     auto filler_type = cfg.get<std::string>("FillerType","");
     if(filler_type.empty()) {
       LARCV_CRITICAL() << "FillerType not set!" << std::endl
             << cfg.dump() << std::endl;
       throw larbys();
     }
     if(!cfg.contains_pset(filler_type)) {
       LARCV_CRITICAL() << "Configuration for a filler "
             << filler_type << " not found!" << std::endl
             << cfg.dump() << std::endl;
       throw larbys();
     }
     reset();
     LARCV_INFO() << "Retrieving IO config" << std::endl;
     auto const io_config = cfg.get<larcv::PSet>("IOManager");
     LARCV_INFO() << "Retrieving ProcessList" << std::endl;
     auto const proc_config = cfg.get<larcv::PSet>("ProcessList");
     // Prepare IO manager
     //LARCV_INFO() << "Configuring IO" << std::endl;
     // Set ThreadDatumFiller
     LARCV_INFO() << "Retrieving self (ThreadDatumFiller) config" << std::endl;
     set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     _enable_filter = cfg.get<bool>("EnableFilter");
     _random_access = cfg.get<bool>("RandomAccess");
     _fout_name = cfg.get<std::string>("AnaFile","");
     // Process list
     auto process_instance_type_v = cfg.get<std::vector<std::string> >("ProcessType");
     auto process_instance_name_v = cfg.get<std::vector<std::string> >("ProcessName");
     if(process_instance_type_v.size() != process_instance_name_v.size()) {
       LARCV_CRITICAL() << "ProcessType and ProcessName config parameters have different length! "
                << "(" << process_instance_type_v.size() << " vs. " << process_instance_name_v.size() << ")" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << "Start looping process list to instantiate processes" << std::endl;
     for(auto& p : _proc_v) if(p) { delete p; }
     _proc_v.clear();
     _proc_m.clear();
     for(size_t i=0; i<process_instance_type_v.size(); ++i) {
       auto const& name = process_instance_name_v[i];
       auto const& type = process_instance_type_v[i];
       if(_proc_m.find(name) != _proc_m.end()) {
            LARCV_CRITICAL() << "Duplicate Process name found: " << name << std::endl;
            throw larbys("Duplicate algorithm name found!");
       }
       size_t id = _proc_v.size();
       LARCV_NORMAL() << "Instantiating Process ID=" << id << " Type: " << type << " w/ Name: " << name << std::endl;
       auto ptr = ProcessFactory::get().create(type,name);
       //ptr->_id = id;
       ptr->_configure_(proc_config.get_pset(name));
       if(ptr->_event_creator) {
          LARCV_CRITICAL() << "Event creator is not allowed!" << std::endl;
          throw larbys();
        }
       _proc_m[name] = id;
       _proc_v.push_back(ptr);
     }
     LARCV_INFO() << "Configuring the filler: " << filler_type << std::endl;
     _filler = (DatumFillerBase*)(ProcessFactory::get().create(filer_type,filler_type));
     _filler->_configure_(cfg.get(filer_type));
     LARCV_DEBUG() << " done" << std::endl;
   }
configure() [3/4]
void larcv::ThreadDatumFiller::configure (const std::string config_file)
configure() [4/4]
void larcv::ThreadDatumFiller::configure (const PSet & cfg)
data()
const std::vector< float > & larcv::ThreadDatumFiller::data () const
Definition at line 207 of file ThreadDatumFiller.cxx.
References _filler, _processing, larcv::DatumFillerBase::data(), larcv::DatumFillerBase::kFillerImageData, LARCV_CRITICAL, and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Data is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->data(DatumFillerBase::kFillerImageData);
   }
dim()
const std::vector< int > larcv::ThreadDatumFiller::dim (bool image = true) const
Definition at line 181 of file ThreadDatumFiller.cxx.
References _filler, _processing, larcv::DatumFillerBase::dim(), LARCV_CRITICAL, and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Dimension is not known before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->dim(image);
   }
finalize()
void larcv::ThreadDatumFiller::finalize ()
Definition at line 269 of file arxiv/ThreadDatumFiller.cxx.
References _filler, _fout, _io, _proc_v, larcv::DatumFillerBase::finalize(), larcv::IOManager< T >::finalize(), LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, larcv::larcv_base::name(), and reset().
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "called" << std::endl;
     for(auto& p : _proc_v) {
       LARCV_INFO() << "Finalizing: " << p->name() << std::endl;
       p->finalize(_fout);
     }
     LARCV_INFO() << "Finalizing: " << _filler->name() << std::endl;
     _filler->finalize(_fout);
     // Profile repor
     LARCV_INFO() << "Compiling time profile..." << std::endl;
     std::stringstream ss;
     for(auto& p : _proc_v) {
       if(!p->_profile) continue;
       ss << "  \033[93m" << std::setw(20) << std::setfill(' ') << p->name() << "\033[00m"
      << " ... # call " << std::setw(5) << std::setfill(' ') << p->_proc_count
      << " ... total time " << p->_proc_time << " [s]"
      << " ... average time " << p->_proc_time / p->_proc_count << " [s/process]"
      << std::endl;
     }
     std::string msg(ss.str());
     if(!msg.empty())
       LARCV_NORMAL() << "Simple time profiling requested and run..." << std::endl
              << "  ================== " << name() << " Profile Report ==================" << std::endl
              << msg
              << std::endl;
     if(_fout) {
       LARCV_NORMAL() << "Closing analysis output file..." << std::endl;
       _fout->Close();
     }
     LARCV_INFO() << "Finalizing IO..." << std::endl;
     _io.finalize();
     LARCV_INFO() << "Resetting..." << std::endl;
     reset();
   }
get_n_entries()
size_t larcv::ThreadDatumFiller::get_n_entries () const inline
Definition at line 64 of file ThreadDatumFiller.h.
References _driver, larcv::IOManager< T >::get_n_entries(), and larcv::ProcessDriver::io().
 { return _driver.io().get_n_entries(); }
initialize()
void larcv::ThreadDatumFiller::initialize ()
Definition at line 183 of file arxiv/ThreadDatumFiller.cxx.
References _batch_processing, _filler, _fout, _fout_name, _io, _proc_v, _processing, larcv::IOManager< T >::get_n_entries(), larcv::DatumFillerBase::initialize(), larcv::IOManager< T >::initialize(), LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, and larcv::larcv_base::name().
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // check state
     if(_processing) {
       LARCV_CRITICAL() << "Must call finalize() before calling initialize() after starting to process..." << std::endl;
       throw larbys();
     }
     // Initialize process
     for(auto& p : _proc_v) {
       LARCV_INFO() << "Initializing: " << p->name() << std::endl;
       p->initialize();
     }
     // Initialize filler
     LARCV_INFO() << "Initializing: " << _filler->name() << std::endl;
     _filler->initialize();
     // Initialize IO
     LARCV_INFO() << "Initializing IO " << std::endl;
     _io.initialize();
     // Handle invalid cases
     auto const nentries = _io.get_n_entries();
     // Prepare analysis output file if needed
     if(!_fout_name.empty()) {
       LARCV_NORMAL() << "Opening analysis output file " << _fout_name << std::endl;
       _fout = TFile::Open(_fout_name.c_str(),"RECREATE");
     }
     // Change state from to-be-initialized to to-process
     _processing = true;
     _batch_processing = false;
   }
io()
const IOManager& larcv::ThreadDatumFiller::io () const inline
Definition at line 59 of file arxiv/ThreadDatumFiller.h.
References _io, and _process_entry_().
 { return _io; }
labels()
const std::vector< float > & larcv::ThreadDatumFiller::labels () const
Definition at line 220 of file ThreadDatumFiller.cxx.
References _filler, _processing, larcv::DatumFillerBase::data(), larcv::DatumFillerBase::kFillerLabelData, LARCV_CRITICAL, and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Label is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->data(DatumFillerBase::kFillerLabelData);
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and set_next_batch().
     { return *_logger; }
meta()
const std::vector< std::vector< larcv::ImageMeta > > & larcv::ThreadDatumFiller::meta () const
Definition at line 260 of file ThreadDatumFiller.cxx.
References _batch_process_(), _configured, _filler, _optional_next_index_v, _processing, _th, _thread_state, _use_threading, batch_process(), larcv::kThreadStateStarting, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, larcv::DatumFillerBase::meta(), and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Weight is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->meta();
   }
multiplicities()
const std::vector< float > & larcv::ThreadDatumFiller::multiplicities () const
Definition at line 234 of file ThreadDatumFiller.cxx.
References _filler, _processing, larcv::DatumFillerBase::data(), larcv::DatumFillerBase::kFillerMultiplicityData, LARCV_CRITICAL, and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Multiplicities is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->data(DatumFillerBase::kFillerMultiplicityData);
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), configure(), finalize(), larcv::ProcessDriver::finalize(), initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
override_input_file()
void larcv::ThreadDatumFiller::override_input_file (const std::vector< std::string > & flist)
Definition at line 36 of file arxiv/ThreadDatumFiller.cxx.
References _io, larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::clear_in_file(), and LARCV_DEBUG.
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     _io.clear_in_file();
     for(auto const& f : flist) _io.add_in_file(f);
   }
pd()
const ProcessDriver* larcv::ThreadDatumFiller::pd () inline
Definition at line 84 of file ThreadDatumFiller.h.
References _batch_process_(), _driver, and _processing.
 { return &_driver; }
process_ctr()
size_t larcv::ThreadDatumFiller::process_ctr () const inline
Definition at line 62 of file ThreadDatumFiller.h.
References _num_processed.
 { return _num_processed; }
process_id()
ProcessID_t larcv::ThreadDatumFiller::process_id (std::string name) const
Definition at line 43 of file arxiv/ThreadDatumFiller.cxx.
References _proc_m, LARCV_CRITICAL, and LARCV_DEBUG.
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     auto iter = _proc_m.find(name);
     if(iter == _proc_m.end()) {
       LARCV_CRITICAL() << "Process w/ name " << name << " not found..." << std::endl;
       throw larbys();
     }
     return (*iter).second;
   }
process_map()
const std::map< std::string, larcv::ProcessID_t > & larcv::ThreadDatumFiller::process_map () const
Definition at line 63 of file arxiv/ThreadDatumFiller.cxx.
References _proc_m, and LARCV_DEBUG.
Referenced by ThreadDatumFiller().
   { LARCV_DEBUG() << "Called" << std::endl; return _proc_m; }
process_names()
std::vector< std::string > larcv::ThreadDatumFiller::process_names () const
Definition at line 54 of file arxiv/ThreadDatumFiller.cxx.
References _proc_m, and LARCV_DEBUG.
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     std::vector<std::string> res;
     res.reserve(_proc_m.size());
     for(auto const& name_id : _proc_m) res.push_back(name_id.first);
     return res;
   }
process_ptr()
const ProcessBase * larcv::ThreadDatumFiller::process_ptr (ProcessID_t id) const
Definition at line 66 of file arxiv/ThreadDatumFiller.cxx.
References _proc_v, LARCV_CRITICAL, and LARCV_DEBUG.
Referenced by ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     if(id >= _proc_v.size()) {
       LARCV_CRITICAL() << "Invalid ID requested: " << id << std::endl;
       throw larbys();
     }
     return _proc_v[id];
   }
processed_entries()
const std::vector<size_t>& larcv::ThreadDatumFiller::processed_entries () const inline
Definition at line 66 of file ThreadDatumFiller.h.
References _batch_entries.
 { return _batch_entries; }
processed_events()
const std::vector<larcv::EventBase>& larcv::ThreadDatumFiller::processed_events () const inline
Definition at line 68 of file ThreadDatumFiller.h.
References _batch_events, data(), dim(), labels(), meta(), multiplicities(), producer(), and weights().
 { return _batch_events; }
producer()
const std::string & larcv::ThreadDatumFiller::producer (DatumFillerBase::FillerDataType_t dtype) const
Definition at line 194 of file ThreadDatumFiller.cxx.
References _filler, _processing, LARCV_CRITICAL, larcv::DatumFillerBase::producer(), and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Data is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->producer(dtype);
   }
reset() [1/2]
void larcv::ThreadDatumFiller::reset ()
Definition at line 23 of file arxiv/ThreadDatumFiller.cxx.
References _enable_filter, _filler, _fout, _fout_name, _io, _proc_v, _processing, _random_access, LARCV_DEBUG, and larcv::IOManager< T >::reset().
Referenced by configure(), finalize(), set_next_batch(), and ThreadDatumFiller().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     _io.reset();
     _enable_filter = _random_access = false;
     for(size_t i=0; i<_proc_v.size(); ++i) { delete _proc_v[i]; _proc_v[i]=nullptr; }
     _proc_v.clear();
     _processing = false;
     _fout = nullptr;
     _fout_name = "";
     if(_filler) delete _filler;
   }
reset() [2/2]
void larcv::ThreadDatumFiller::reset ()
copy ctor
set_next_batch()
void larcv::ThreadDatumFiller::set_next_batch (const std::vector< size_t > & index_v)
Definition at line 45 of file ThreadDatumFiller.cxx.
References _configured, _driver, _enable_filter, _filler, _input_fname_v, _num_processed, _optional_next_index, _optional_next_index_v, _processing, _random_access, _use_threading, larcv::PSet::add_value(), configure(), larcv::ProcessDriver::configure(), larcv::CreatePSetFromFile(), larcv::ProcessDriver::finalize(), larcv::PSet::get(), larcv::PSet::get_pset(), larcv::kINVALID_SIZE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, larcv::logger::level(), larcv::larcv_base::logger(), larcv::larcv_base::name(), larcv::ProcessDriver::override_input_file(), larcv::ProcessDriver::process_id(), larcv::ProcessDriver::process_names(), larcv::ProcessDriver::process_ptr(), larcv::PSet::pset_keys(), larcv::ProcessDriver::random_access(), larcv::ProcessDriver::reset(), reset(), larcv::larcv_base::set_verbosity(), thread_running(), and larcv::PSet::value_keys().
Referenced by set_random_access().
   {
     if (thread_running()) {
       LARCV_CRITICAL() << "Cannot set next index while thread is running!" << std::endl;
       throw larbys();
     }
     if( _optional_next_index != kINVALID_SIZE ) {
       LARCV_CRITICAL() << "Next batch indecies already set! Cannot call this function..." << std::endl;
       throw larbys();
     }
     _optional_next_index_v = index_v;
   }
set_next_index()
void larcv::ThreadDatumFiller::set_next_index (size_t index)
Definition at line 32 of file ThreadDatumFiller.cxx.
References _optional_next_index, _optional_next_index_v, LARCV_CRITICAL, and thread_running().
Referenced by set_random_access().
   {
     if (thread_running()) {
       LARCV_CRITICAL() << "Cannot set next index while thread is running!" << std::endl;
       throw larbys();
     }
     if( _optional_next_index_v.size() ) {
       LARCV_CRITICAL() << "Next batch indecies already set! Cannot call this function..." << std::endl;
       throw larbys();
     }
     _optional_next_index = index;
   }
set_random_access()
void larcv::ThreadDatumFiller::set_random_access (bool do_random) inline
Definition at line 51 of file ThreadDatumFiller.h.
References _random_access, set_next_batch(), and set_next_index().
     { _random_access=do_random;}
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and set_next_batch().
     { _logger->set(level); }
thread_config()
bool larcv::ThreadDatumFiller::thread_config () const inline
Definition at line 58 of file ThreadDatumFiller.h.
References _use_threading.
 { return _use_threading; }
thread_running()
bool larcv::ThreadDatumFiller::thread_running () const inline
Definition at line 60 of file ThreadDatumFiller.h.
References _thread_state, and larcv::kThreadStateIdle.
Referenced by data(), dim(), labels(), meta(), multiplicities(), producer(), set_next_batch(), set_next_index(), and weights().
 { return (_thread_state != kThreadStateIdle); }
weights()
const std::vector< float > & larcv::ThreadDatumFiller::weights () const
Definition at line 247 of file ThreadDatumFiller.cxx.
References _filler, _processing, larcv::DatumFillerBase::data(), larcv::DatumFillerBase::kFillerWeightData, LARCV_CRITICAL, and thread_running().
Referenced by processed_events().
   {
     if (!_processing) {
       LARCV_CRITICAL() << "Weight is not available before start processing!" << std::endl;
       throw larbys();
     }
     if (thread_running()) {
       LARCV_CRITICAL() << "Thread is currently running (cannot retrieve data)" << std::endl;
       throw larbys();
     }
     return _filler->data(DatumFillerBase::kFillerWeightData);
   }
Member Data Documentation
_batch_entries
std::vector< size_t > larcv::ThreadDatumFiller::_batch_entries private
Definition at line 66 of file arxiv/ThreadDatumFiller.h.
Referenced by _batch_process_(), batch_process(), and processed_entries().
_batch_events
std::vector<larcv::EventBase> larcv::ThreadDatumFiller::_batch_events private
Definition at line 97 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), and processed_events().
_batch_processing
bool larcv::ThreadDatumFiller::_batch_processing private
Definition at line 73 of file arxiv/ThreadDatumFiller.h.
Referenced by batch_process(), and initialize().
_configured
bool larcv::ThreadDatumFiller::_configured private
Definition at line 93 of file ThreadDatumFiller.h.
Referenced by meta(), and set_next_batch().
_dim_v
std::vector<int> larcv::ThreadDatumFiller::_dim_v private
Definition at line 98 of file ThreadDatumFiller.h.
_driver
ProcessDriver larcv::ThreadDatumFiller::_driver private
Definition at line 99 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), get_n_entries(), pd(), set_next_batch(), and ~ThreadDatumFiller().
_enable_filter
bool larcv::ThreadDatumFiller::_enable_filter private
Definition at line 67 of file arxiv/ThreadDatumFiller.h.
Referenced by _batch_process_(), batch_process(), configure(), reset(), and set_next_batch().
_filler
DatumFillerBase * larcv::ThreadDatumFiller::_filler private
Definition at line 65 of file arxiv/ThreadDatumFiller.h.
Referenced by _batch_process_(), batch_process(), configure(), data(), dim(), finalize(), initialize(), labels(), meta(), multiplicities(), producer(), reset(), set_next_batch(), and weights().
_fout
TFile* larcv::ThreadDatumFiller::_fout private
Definition at line 74 of file arxiv/ThreadDatumFiller.h.
Referenced by finalize(), initialize(), and reset().
_fout_name
std::string larcv::ThreadDatumFiller::_fout_name private
Definition at line 75 of file arxiv/ThreadDatumFiller.h.
Referenced by configure(), initialize(), and reset().
_input_fname_v
std::vector<std::string> larcv::ThreadDatumFiller::_input_fname_v private
Definition at line 105 of file ThreadDatumFiller.h.
Referenced by set_next_batch().
_io
IOManager larcv::ThreadDatumFiller::_io private
Definition at line 69 of file arxiv/ThreadDatumFiller.h.
Referenced by batch_process(), finalize(), initialize(), io(), override_input_file(), and reset().
_num_processed
size_t larcv::ThreadDatumFiller::_num_processed private
Definition at line 95 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), process_ctr(), and set_next_batch().
_optional_next_index
size_t larcv::ThreadDatumFiller::_optional_next_index private
Definition at line 106 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), set_next_batch(), and set_next_index().
_optional_next_index_v
std::vector<size_t> larcv::ThreadDatumFiller::_optional_next_index_v private
Definition at line 107 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), meta(), set_next_batch(), and set_next_index().
_proc_m
std::map<std::string,larcv::ProcessID_t> larcv::ThreadDatumFiller::_proc_m private
Definition at line 70 of file arxiv/ThreadDatumFiller.h.
Referenced by configure(), process_id(), process_map(), and process_names().
_proc_v
std::vector<larcv::ProcessBase*> larcv::ThreadDatumFiller::_proc_v private
Definition at line 71 of file arxiv/ThreadDatumFiller.h.
Referenced by batch_process(), configure(), finalize(), initialize(), process_ptr(), and reset().
_processing
bool larcv::ThreadDatumFiller::_processing private
Definition at line 72 of file arxiv/ThreadDatumFiller.h.
Referenced by _batch_process_(), batch_process(), configure(), data(), dim(), initialize(), labels(), meta(), multiplicities(), pd(), producer(), reset(), set_next_batch(), weights(), and ~ThreadDatumFiller().
_random_access
bool larcv::ThreadDatumFiller::_random_access private
Definition at line 68 of file arxiv/ThreadDatumFiller.h.
Referenced by _batch_process_(), batch_process(), configure(), reset(), set_next_batch(), and set_random_access().
_th
std::thread larcv::ThreadDatumFiller::_th private
Definition at line 103 of file ThreadDatumFiller.h.
Referenced by meta(), and ~ThreadDatumFiller().
_thread_state
ThreadFillerState_t larcv::ThreadDatumFiller::_thread_state private
Definition at line 90 of file ThreadDatumFiller.h.
Referenced by _batch_process_(), meta(), and thread_running().
_use_threading
bool larcv::ThreadDatumFiller::_use_threading private
Definition at line 91 of file ThreadDatumFiller.h.
Referenced by meta(), set_next_batch(), and thread_config().
The documentation for this class was generated from the following files:
arxiv/ThreadDatumFiller.h
arxiv/ThreadDatumFiller.cxx