LArCV: larcv::LArbysImageResult Class Reference
larcv::LArbysImageResult Class Reference abstract
#include <LArbysImageResult.h>
Public Member Functions
LArbysImageResult (const std::string name="LArbysImageResult")
~LArbysImageResult ()
void Configure (const PSet &)
void Initialize ()
bool Analyze (const ::larocv::ImageClusterManager &mgr)
void Finalize (TFile *fout=nullptr)
virtual bool Analyze (larocv::ImageClusterManager &mgr)=0
void EventID (const size_t entry, const size_t run, const size_t subrun, const size_t event)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
size_t _run
Unique event keys.
size_t _subrun
size_t _event
size_t _entry
Private Attributes
std::string _combined_vertex_name
uint _combined_particle_offset
Detailed Description
Definition at line 13 of file LArbysImageResult.h.
Constructor & Destructor Documentation
LArbysImageResult()
larcv::LArbysImageResult::LArbysImageResult (const std::string name = "LArbysImageResult")
Definition at line 8 of file LArbysImageResult.cxx.
     : LArbysImageAnaBase(name)
   {}
~LArbysImageResult()
larcv::LArbysImageResult::~LArbysImageResult () inline
Definition at line 18 of file LArbysImageResult.h.
References Analyze(), Configure(), Finalize(), and Initialize().
 {}
Member Function Documentation
Analyze() [1/2]
virtual bool larcv::LArbysImageAnaBase::Analyze (larocv::ImageClusterManager & mgr) pure virtual inherited
Referenced by larcv::LArbysImageAnaBase::~LArbysImageAnaBase().
Analyze() [2/2]
bool larcv::LArbysImageResult::Analyze (const ::larocv::ImageClusterManager & mgr)
Definition at line 21 of file LArbysImageResult.cxx.
References _combined_particle_offset, _combined_vertex_name, and larcv::kINVALID_SIZE.
Referenced by ~LArbysImageResult().
   {
     const larocv::data::AlgoDataManager& data_mgr   = mgr.DataManager();
     const larocv::data::AlgoDataAssManager& ass_man = data_mgr.AssManager();
     auto track_particle_cluster_id = data_mgr.ID(_combined_vertex_name);
     const auto vtx3d_array = (larocv::data::Vertex3DArray*)
       data_mgr.Data(track_particle_cluster_id, 0);
     const auto& vtx3d_v = vtx3d_array->as_vector();
     for(const auto& vtx3d : vtx3d_v) {
       for(uint plane_id=0; plane_id<3;  ++plane_id) {
     //get the particle cluster array
     const auto par_array = (larocv::data::ParticleClusterArray*)
       data_mgr.Data(track_particle_cluster_id, plane_id+_combined_particle_offset);
     //get the compound array
     const auto comp_array = (larocv::data::TrackClusterCompoundArray*)
       data_mgr.Data(track_particle_cluster_id, plane_id+_combined_particle_offset+3);
     auto par_ass_idx_v = ass_man.GetManyAss(vtx3d,par_array->ID());
     for(auto ass_idx : par_ass_idx_v) {
       if (ass_idx==kINVALID_SIZE) throw larbys("Invalid vertex->particle association detected");
       const auto& par = par_array->as_vector()[ass_idx];
       const auto par_ctor = par._ctor;
       //Here the particle contour and do something, like cluster hits
       /*
         ...
         ...
        */
       auto comp_ass_id = ass_man.GetOneAss(par,comp_array->ID());
       if (comp_ass_id==kINVALID_SIZE) continue;
       const auto& comp = comp_array->as_vector()[comp_ass_id];
       // Here we can get the end points, dQdX
       /*
         ...
         ...
        */
     } // end particle ass
       } // end this plane
     } // end this vertex
     return true;
   }
Configure()
void larcv::LArbysImageResult::Configure (const PSet & cfg) virtual
Implements larcv::LArbysImageAnaBase.
Definition at line 12 of file LArbysImageResult.cxx.
References _combined_particle_offset, _combined_vertex_name, and larcv::PSet::get().
Referenced by ~LArbysImageResult().
   {
     _combined_vertex_name = cfg.get<std::string>("CombinedVertexName");
     _combined_particle_offset = cfg.get<uint>("ParticleOffset");
   }
EventID()
void larcv::LArbysImageAnaBase::EventID (const size_t entry, const size_t run, const size_t subrun, const size_t event) inline inherited
Definition at line 24 of file LArbysImageAnaBase.h.
References larcv::LArbysImageAnaBase::_entry, larcv::LArbysImageAnaBase::_event, larcv::LArbysImageAnaBase::_run, and larcv::LArbysImageAnaBase::_subrun.
     { _entry = entry; _run = run; _subrun = subrun; _event = event; }
Finalize()
void larcv::LArbysImageResult::Finalize (TFile * fout = nullptr) virtual
Implements larcv::LArbysImageAnaBase.
Definition at line 79 of file LArbysImageResult.cxx.
Referenced by ~LArbysImageResult().
   {}
Initialize()
void larcv::LArbysImageResult::Initialize () virtual
Implements larcv::LArbysImageAnaBase.
Definition at line 18 of file LArbysImageResult.cxx.
Referenced by ~LArbysImageResult().
   {}
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_combined_particle_offset
uint larcv::LArbysImageResult::_combined_particle_offset private
Definition at line 28 of file LArbysImageResult.h.
Referenced by Analyze(), and Configure().
_combined_vertex_name
std::string larcv::LArbysImageResult::_combined_vertex_name private
Definition at line 27 of file LArbysImageResult.h.
Referenced by Analyze(), and Configure().
_entry
size_t larcv::LArbysImageAnaBase::_entry protected inherited
Definition at line 34 of file LArbysImageAnaBase.h.
Referenced by larcv::LArbysImageAnaBase::EventID().
_event
size_t larcv::LArbysImageAnaBase::_event protected inherited
Definition at line 33 of file LArbysImageAnaBase.h.
Referenced by larcv::LArbysImageAnaBase::EventID().
_run
size_t larcv::LArbysImageAnaBase::_run protected inherited
Unique event keys.
Definition at line 31 of file LArbysImageAnaBase.h.
Referenced by larcv::LArbysImageAnaBase::EventID().
_subrun
size_t larcv::LArbysImageAnaBase::_subrun protected inherited
Definition at line 32 of file LArbysImageAnaBase.h.
Referenced by larcv::LArbysImageAnaBase::EventID().
The documentation for this class was generated from the following files:
LArbysImageResult.h
LArbysImageResult.cxx