LArCV: larcv::Voxel3DMeta Class Reference
larcv::Voxel3DMeta Class Reference
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
#include <Voxel3D.h>
Public Member Functions
Voxel3DMeta ()
Default ctor.
~Voxel3DMeta ()
Default dtor.
void Set (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, size_t xnum, size_t ynum, size_t znum)
Define dimensions.
void Clear ()
Clear method.
bool Valid () const
Checker if the meta parameters are set properly or not.
Voxel3DID_t Size () const
Returns size.
Voxel3DID_t ID (double x, double y, double z) const
Given a position, returns voxel ID.
const std::array< double, 3 > Position (Voxel3DID_t id) const
Given a valid voxel ID, returns a position array.
double X (Voxel3DID_t id) const
Given a valid voxel ID, returns X position.
double Y (Voxel3DID_t id) const
Given a valid voxel ID, returns Y position.
double Z (Voxel3DID_t id) const
Given a valid voxel ID, returns Z position.
size_t NumVoxelX () const
Returns voxel count along x-axis.
size_t NumVoxelY () const
Returns voxel count along y-axis.
size_t NumVoxelZ () const
Returns voxel count along z-axis.
double SizeVoxelX () const
Returns voxel size along x-axis;.
double SizeVoxelY () const
Returns voxel size along y-axis;.
double SizeVoxelZ () const
Returns voxel size along z-axis;.
double MaxX () const
Returns voxel definition maximum x value.
double MaxY () const
Returns voxel definition maximum y value.
double MaxZ () const
Returns voxel definition maximum z value.
double MinX () const
Returns voxel definition minimum x value.
double MinY () const
Returns voxel definition minimum y value.
double MinZ () const
Returns voxel definition minimum z value.
std::string Dump () const
text dumper
Private Attributes
bool _valid
Boolean set to true only if voxel parameters are properly set.
Voxel3DID_t _num_element
Total number of voxel elements.
double _xmin
X min value in voxel definition in [cm].
double _xmax
X max value in voxel definition in [cm].
double _xlen
X voxel size in [cm].
double _ymin
Y min value in voxel definition in [cm].
double _ymax
Y min value in voxel definition in [cm].
double _ylen
Y voxel size in [cm].
double _zmin
Z min value in voxel definition in [cm].
double _zmax
Z min value in voxel definition in [cm].
double _zlen
Z voxel size in [cm].
size_t _xnum
Number of voxels along X.
size_t _ynum
Number of voxels along Y.
size_t _znum
Number of voxels along Z.
Detailed Description
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
Definition at line 94 of file Voxel3D.h.
Constructor & Destructor Documentation
Voxel3DMeta()
larcv::Voxel3DMeta::Voxel3DMeta ()
Default ctor.
Definition at line 13 of file Voxel3D.cxx.
   { Clear(); }
~Voxel3DMeta()
larcv::Voxel3DMeta::~Voxel3DMeta () inline
Default dtor.
Definition at line 99 of file Voxel3D.h.
References larcv::Voxel3D::Set().
 {}
Member Function Documentation
Clear()
void larcv::Voxel3DMeta::Clear ()
Clear method.
Definition at line 16 of file Voxel3D.cxx.
References larcv::kINVALID_DOUBLE, and larcv::kINVALID_SIZE.
   {
     _xmin = _xmax = _xlen = kINVALID_DOUBLE;
     _ymin = _ymax = _ylen = kINVALID_DOUBLE;
     _zmin = _zmax = _zlen = kINVALID_DOUBLE;
     _xnum = _ynum = _znum = kINVALID_SIZE;
     _valid = false;
   }
Dump()
std::string larcv::Voxel3DMeta::Dump () const
text dumper
Definition at line 152 of file Voxel3D.cxx.
Referenced by larcv::SuperaSimVoxel3D::process().
   {
     std::stringstream ss;
     ss << "X range: " << _xmin << " => " << _xmax << " ... " << _xnum << " bins" << std::endl
        << "Y range: " << _ymin << " => " << _ymax << " ... " << _ynum << " bins" << std::endl
        << "Z range: " << _zmin << " => " << _zmax << " ... " << _znum << " bins" << std::endl;
     return std::string(ss.str());
   }
ID()
Voxel3DID_t larcv::Voxel3DMeta::ID (double x, double y, double z) const
Given a position, returns voxel ID.
Definition at line 84 of file Voxel3D.cxx.
References larcv::kINVALID_VOXEL3DID.
Referenced by supera::SimCh2Voxel3D().
   {
     if(!_valid) throw larbys("Voxel3DMeta::ID cannot be called on invalid meta!");
     if(x > _xmax || x < _xmin) return kINVALID_VOXEL3DID;
     if(y > _ymax || y < _ymin) return kINVALID_VOXEL3DID;
     if(z > _zmax || z < _zmin) return kINVALID_VOXEL3DID;
     Voxel3DID_t xindex = (x - _xmin) / _xlen;
     Voxel3DID_t yindex = (y - _ymin) / _ylen;
     Voxel3DID_t zindex = (z - _zmin) / _zlen;
     if(xindex == _xnum) xindex -= 1;
     if(yindex == _ynum) yindex -= 1;
     if(zindex == _znum) zindex -= 1;
     return (zindex * (_xnum * _ynum) + yindex * _xnum + xindex);
   }
MaxX()
double larcv::Voxel3DMeta::MaxX () const inline
Returns voxel definition maximum x value.
Definition at line 137 of file Voxel3D.h.
 { return _xmax; }
MaxY()
double larcv::Voxel3DMeta::MaxY () const inline
Returns voxel definition maximum y value.
Definition at line 139 of file Voxel3D.h.
 { return _ymax; }
MaxZ()
double larcv::Voxel3DMeta::MaxZ () const inline
Returns voxel definition maximum z value.
Definition at line 141 of file Voxel3D.h.
 { return _zmax; }
MinX()
double larcv::Voxel3DMeta::MinX () const inline
Returns voxel definition minimum x value.
Definition at line 143 of file Voxel3D.h.
 { return _xmin; }
MinY()
double larcv::Voxel3DMeta::MinY () const inline
Returns voxel definition minimum y value.
Definition at line 145 of file Voxel3D.h.
 { return _ymin; }
MinZ()
double larcv::Voxel3DMeta::MinZ () const inline
Returns voxel definition minimum z value.
Definition at line 147 of file Voxel3D.h.
 { return _zmin; }
NumVoxelX()
size_t larcv::Voxel3DMeta::NumVoxelX () const inline
Returns voxel count along x-axis.
Definition at line 125 of file Voxel3D.h.
 { return _xnum; }
NumVoxelY()
size_t larcv::Voxel3DMeta::NumVoxelY () const inline
Returns voxel count along y-axis.
Definition at line 127 of file Voxel3D.h.
 { return _ynum; }
NumVoxelZ()
size_t larcv::Voxel3DMeta::NumVoxelZ () const inline
Returns voxel count along z-axis.
Definition at line 129 of file Voxel3D.h.
 { return _znum; }
Position()
const std::array< double, 3 > larcv::Voxel3DMeta::Position (Voxel3DID_t id) const
Given a valid voxel ID, returns a position array.
Definition at line 102 of file Voxel3D.cxx.
   {
     if(!_valid) throw larbys("Voxel3DMeta::Position cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::Position invalid Voxel3DID_t!");
     Voxel3DID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     Voxel3DID_t yid = id / _xnum;
     Voxel3DID_t xid = (id - yid * _xnum);
     std::array<double,3> pos;
     pos[0] = _xmin + ((double)xid + 0.5) * _xlen;
     pos[1] = _ymin + ((double)yid + 0.5) * _ylen;
     pos[2] = _zmin + ((double)zid + 0.5) * _zlen;
     return pos;
   }
Set()
void larcv::Voxel3DMeta::Set (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, size_t xnum, size_t ynum, size_t znum)
Define dimensions.
Definition at line 25 of file Voxel3D.cxx.
References larcv::kINVALID_DOUBLE, and larcv::kINVALID_SIZE.
Referenced by larcv::SuperaSimVoxel3D::process().
   {
     if(xmin == kINVALID_DOUBLE || xmax == kINVALID_DOUBLE)
       throw larbys("Voxel3DMeta::Set x boundary not set!");
     if(xmin >= xmax)
       throw larbys("Voxel3DMeta::Set xmin >= xmax!");
     if(ymin == kINVALID_DOUBLE || ymax == kINVALID_DOUBLE)
       throw larbys("Voxel3DMeta::Set y boundary not set!");
     if(ymin >= ymax)
       throw larbys("Voxel3DMeta::Set ymin >= ymax!");
     if(zmin == kINVALID_DOUBLE || zmax == kINVALID_DOUBLE)
       throw larbys("Voxel3DMeta::Set z boundary not set!");
     if(zmin >= zmax)
       throw larbys("Voxel3DMeta::Set zmin >= zmax!");
     if(xnum == kINVALID_SIZE || xnum == 0)
       throw larbys("Voxel3DMeta::Set x voxel count not set!");
     if(ynum == kINVALID_SIZE || ynum == 0)
       throw larbys("Voxel3DMeta::Set y voxel count not set!");
     if(znum == kINVALID_SIZE || znum == 0)
       throw larbys("Voxel3DMeta::Set z voxel count not set!");
     _xmin = xmin;
     _xmax = xmax;
     _xlen = (xmax - xmin) / ((double)xnum);
     _xnum = xnum;
     _ymin = ymin;
     _ymax = ymax;
     _ylen = (ymax - ymin) / ((double)ynum);
     _ynum = ynum;
     _zmin = zmin;
     _zmax = zmax;
     _zlen = (zmax - zmin) / ((double)znum);
     _znum = znum;
     if( (_xmin + _xlen * _xnum) != _xmax )
       throw larbys("Voxel3DMeta::Set (xmax - xmin) not divisible by xnum!");
     if( (_ymin + _ylen * _ynum) != _ymax )
       throw larbys("Voxel3DMeta::Set (ymax - ymin) not divisible by ynum!");
     if( (_zmin + _zlen * _znum) != _zmax )
       throw larbys("Voxel3DMeta::Set (zmax - zmin) not divisible by znum!");
     _num_element = _xnum * _ynum * _znum;
     _valid = true;
   }
Size()
Voxel3DID_t larcv::Voxel3DMeta::Size () const inline
Returns size.
Definition at line 113 of file Voxel3D.h.
References larcv::Voxel3D::ID().
 { return _num_element; }
SizeVoxelX()
double larcv::Voxel3DMeta::SizeVoxelX () const inline
Returns voxel size along x-axis;.
Definition at line 131 of file Voxel3D.h.
 { return _xlen; }
SizeVoxelY()
double larcv::Voxel3DMeta::SizeVoxelY () const inline
Returns voxel size along y-axis;.
Definition at line 133 of file Voxel3D.h.
 { return _ylen; }
SizeVoxelZ()
double larcv::Voxel3DMeta::SizeVoxelZ () const inline
Returns voxel size along z-axis;.
Definition at line 135 of file Voxel3D.h.
 { return _zlen; }
Valid()
bool larcv::Voxel3DMeta::Valid () const inline
Checker if the meta parameters are set properly or not.
Definition at line 111 of file Voxel3D.h.
Referenced by larcv::Voxel3DSet::Emplace().
 { return _valid; }
X()
double larcv::Voxel3DMeta::X (Voxel3DID_t id) const
Given a valid voxel ID, returns X position.
Definition at line 119 of file Voxel3D.cxx.
   {
     if(!_valid) throw larbys("Voxel3DMeta::X cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::X invalid Voxel3DID_t!");
     Voxel3DID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     Voxel3DID_t yid = id / _xnum;
     Voxel3DID_t xid = (id - yid * _xnum);
     return _xmin + ((double)xid + 0.5) * _xlen;
   }
Y()
double larcv::Voxel3DMeta::Y (Voxel3DID_t id) const
Given a valid voxel ID, returns Y position.
Definition at line 132 of file Voxel3D.cxx.
   {
     if(!_valid) throw larbys("Voxel3DMeta::Y cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::Y invalid Voxel3DID_t!");
     Voxel3DID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     Voxel3DID_t yid = id / _xnum;
     return _ymin + ((double)yid + 0.5) * _ylen;
   }
Z()
double larcv::Voxel3DMeta::Z (Voxel3DID_t id) const
Given a valid voxel ID, returns Z position.
Definition at line 143 of file Voxel3D.cxx.
   {
     if(!_valid) throw larbys("Voxel3DMeta::Z cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::Z invalid Voxel3DID_t!");
     Voxel3DID_t zid = id / (_xnum * _ynum);
     return _zmin + ((double)zid + 0.5) * _zlen;
   }
Member Data Documentation
_num_element
Voxel3DID_t larcv::Voxel3DMeta::_num_element private
Total number of voxel elements.
Definition at line 154 of file Voxel3D.h.
_valid
bool larcv::Voxel3DMeta::_valid private
Boolean set to true only if voxel parameters are properly set.
Definition at line 153 of file Voxel3D.h.
_xlen
double larcv::Voxel3DMeta::_xlen private
X voxel size in [cm].
Definition at line 158 of file Voxel3D.h.
_xmax
double larcv::Voxel3DMeta::_xmax private
X max value in voxel definition in [cm].
Definition at line 157 of file Voxel3D.h.
_xmin
double larcv::Voxel3DMeta::_xmin private
X min value in voxel definition in [cm].
Definition at line 156 of file Voxel3D.h.
_xnum
size_t larcv::Voxel3DMeta::_xnum private
Number of voxels along X.
Definition at line 168 of file Voxel3D.h.
_ylen
double larcv::Voxel3DMeta::_ylen private
Y voxel size in [cm].
Definition at line 162 of file Voxel3D.h.
_ymax
double larcv::Voxel3DMeta::_ymax private
Y min value in voxel definition in [cm].
Definition at line 161 of file Voxel3D.h.
_ymin
double larcv::Voxel3DMeta::_ymin private
Y min value in voxel definition in [cm].
Definition at line 160 of file Voxel3D.h.
_ynum
size_t larcv::Voxel3DMeta::_ynum private
Number of voxels along Y.
Definition at line 169 of file Voxel3D.h.
_zlen
double larcv::Voxel3DMeta::_zlen private
Z voxel size in [cm].
Definition at line 166 of file Voxel3D.h.
_zmax
double larcv::Voxel3DMeta::_zmax private
Z min value in voxel definition in [cm].
Definition at line 165 of file Voxel3D.h.
_zmin
double larcv::Voxel3DMeta::_zmin private
Z min value in voxel definition in [cm].
Definition at line 164 of file Voxel3D.h.
_znum
size_t larcv::Voxel3DMeta::_znum private
Number of voxels along Z.
Definition at line 170 of file Voxel3D.h.
The documentation for this class was generated from the following files:
Voxel3D.h
Voxel3D.cxx