LArCV: larcv::SuperaSimVoxel3DProcessFactory Class Reference
larcv::SuperaSimVoxel3DProcessFactory Class Reference
#include <SuperaSimVoxel3D.h>
Public Member Functions
SuperaSimVoxel3DProcessFactory ()
ctor
~SuperaSimVoxel3DProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 61 of file SuperaSimVoxel3D.h.
Constructor & Destructor Documentation
SuperaSimVoxel3DProcessFactory()
larcv::SuperaSimVoxel3DProcessFactory::SuperaSimVoxel3DProcessFactory () inline
ctor
Definition at line 64 of file SuperaSimVoxel3D.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SuperaSimVoxel3D",this); }
~SuperaSimVoxel3DProcessFactory()
larcv::SuperaSimVoxel3DProcessFactory::~SuperaSimVoxel3DProcessFactory () inline
dtor
Definition at line 66 of file SuperaSimVoxel3D.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SuperaSimVoxel3DProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 68 of file SuperaSimVoxel3D.h.
References larcv::SuperaSimVoxel3D::SuperaSimVoxel3D().
 { return new SuperaSimVoxel3D(instance_name); }
The documentation for this class was generated from the following file:
SuperaSimVoxel3D.h