LArCV: larcv::EventPixel2DFactory Class Reference
larcv::EventPixel2DFactory Class Reference
#include <EventPixel2D.h>
Public Member Functions
EventPixel2DFactory ()
ctor
~EventPixel2DFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 96 of file EventPixel2D.h.
Constructor & Destructor Documentation
EventPixel2DFactory()
larcv::EventPixel2DFactory::EventPixel2DFactory () inline
ctor
Definition at line 99 of file EventPixel2D.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductPixel2D.
 { DataProductFactory::get().add_factory(kProductPixel2D,this); }
~EventPixel2DFactory()
larcv::EventPixel2DFactory::~EventPixel2DFactory () inline
dtor
Definition at line 101 of file EventPixel2D.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventPixel2DFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 103 of file EventPixel2D.h.
References larcv::EventPixel2D::EventPixel2D().
 { return new EventPixel2D; }
The documentation for this class was generated from the following file:
EventPixel2D.h