LArCV: larcv::MaskImageProcessFactory Class Reference
larcv::MaskImageProcessFactory Class Reference
#include <MaskImage.h>
Public Member Functions
MaskImageProcessFactory ()
ctor
~MaskImageProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 60 of file MaskImage.h.
Constructor & Destructor Documentation
MaskImageProcessFactory()
larcv::MaskImageProcessFactory::MaskImageProcessFactory () inline
ctor
Definition at line 63 of file MaskImage.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("MaskImage",this); }
~MaskImageProcessFactory()
larcv::MaskImageProcessFactory::~MaskImageProcessFactory () inline
dtor
Definition at line 65 of file MaskImage.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::MaskImageProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 67 of file MaskImage.h.
References larcv::MaskImage::MaskImage().
 { return new MaskImage(instance_name); }
The documentation for this class was generated from the following file:
MaskImage.h