LArCV: larcv::CosmicROIFiller Class Reference
larcv::CosmicROIFiller Class Reference
#include <CosmicROIFiller.h>
Public Member Functions
CosmicROIFiller (const std::string name="CosmicROIFiller")
Default constructor.
~CosmicROIFiller ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _roi_producer
ProductType_t _ref_type
std::string _ref_producer
int _roi_type
Detailed Description
Definition at line 26 of file CosmicROIFiller.h.
Constructor & Destructor Documentation
CosmicROIFiller()
larcv::CosmicROIFiller::CosmicROIFiller (const std::string name = "CosmicROIFiller")
Default constructor.
Definition at line 10 of file CosmicROIFiller.cxx.
Referenced by larcv::CosmicROIFillerProcessFactory::create().
   : ProcessBase(name)
 {}
~CosmicROIFiller()
larcv::CosmicROIFiller::~CosmicROIFiller () inline
Default destructor.
Definition at line 34 of file CosmicROIFiller.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::CosmicROIFiller::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file CosmicROIFiller.cxx.
References _ref_producer, _ref_type, _roi_producer, _roi_type, and larcv::PSet::get().
Referenced by ~CosmicROIFiller().
 {
   _ref_type = (ProductType_t)(cfg.get<unsigned short>("RefType"));
   _ref_producer = cfg.get<std::string>("RefProducer");
   _roi_producer = cfg.get<std::string>("ROIProducer");
   _roi_type = cfg.get<int>("ROIType");
 }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::CosmicROIFiller::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 42 of file CosmicROIFiller.cxx.
Referenced by ~CosmicROIFiller().
 {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::CosmicROIFiller::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 22 of file CosmicROIFiller.cxx.
Referenced by ~CosmicROIFiller().
 {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::CosmicROIFiller::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 25 of file CosmicROIFiller.cxx.
References _ref_producer, _ref_type, _roi_producer, _roi_type, larcv::IOManager< T >::get_data(), larcv::kProductROI, LARCV_CRITICAL, and larcv::ROI::Type().
Referenced by ~CosmicROIFiller().
 {
   auto ref_data = mgr.get_data(_ref_type, _ref_producer);
   if (!ref_data) {
     LARCV_CRITICAL() << "Could not find reference product type " << _ref_type
                      << " made by " << _ref_producer << std::endl;
     throw larbys();
   }
   auto event_roi = (EventROI*)(mgr.get_data(kProductROI, _roi_producer));
   std::vector<larcv::ROI> roi_v;
   ROI cosmic_roi;
   cosmic_roi.Type((ROIType_t) _roi_type);
   roi_v.emplace_back(cosmic_roi);
   event_roi->Emplace(std::move(roi_v));
   return true;
 }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_ref_producer
std::string larcv::CosmicROIFiller::_ref_producer private
Definition at line 48 of file CosmicROIFiller.h.
Referenced by configure(), and process().
_ref_type
ProductType_t larcv::CosmicROIFiller::_ref_type private
Definition at line 47 of file CosmicROIFiller.h.
Referenced by configure(), and process().
_roi_producer
std::string larcv::CosmicROIFiller::_roi_producer private
Definition at line 46 of file CosmicROIFiller.h.
Referenced by configure(), and process().
_roi_type
int larcv::CosmicROIFiller::_roi_type private
Definition at line 49 of file CosmicROIFiller.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
CosmicROIFiller.h
CosmicROIFiller.cxx