LArCV: larcv::SuperaKeyPointClusterProcessFactory Class Reference
larcv::SuperaKeyPointClusterProcessFactory Class Reference
#include <SuperaKeyPointCluster.h>
Public Member Functions
SuperaKeyPointClusterProcessFactory ()
ctor
~SuperaKeyPointClusterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 74 of file SuperaKeyPointCluster.h.
Constructor & Destructor Documentation
SuperaKeyPointClusterProcessFactory()
larcv::SuperaKeyPointClusterProcessFactory::SuperaKeyPointClusterProcessFactory () inline
ctor
Definition at line 77 of file SuperaKeyPointCluster.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SuperaKeyPointCluster",this); }
~SuperaKeyPointClusterProcessFactory()
larcv::SuperaKeyPointClusterProcessFactory::~SuperaKeyPointClusterProcessFactory () inline
dtor
Definition at line 79 of file SuperaKeyPointCluster.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SuperaKeyPointClusterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 81 of file SuperaKeyPointCluster.h.
References larcv::SuperaKeyPointCluster::SuperaKeyPointCluster().
 { return new SuperaKeyPointCluster(instance_name); }
The documentation for this class was generated from the following file:
SuperaKeyPointCluster.h