LArCV: larcv::ROIPadProcessFactory Class Reference
larcv::ROIPadProcessFactory Class Reference
#include <ROIPad.h>
Public Member Functions
ROIPadProcessFactory ()
~ROIPadProcessFactory ()
ProcessBase * create (const std::string instance_name)
Abstract constructor method.
Detailed Description
Definition at line 39 of file ROIPad.h.
Constructor & Destructor Documentation
ROIPadProcessFactory()
larcv::ROIPadProcessFactory::ROIPadProcessFactory () inline
Definition at line 42 of file ROIPad.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ROIPad",this); }
~ROIPadProcessFactory()
larcv::ROIPadProcessFactory::~ROIPadProcessFactory () inline
Definition at line 43 of file ROIPad.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ROIPadProcessFactory::create (const std::string instance_name) inline virtual
Abstract constructor method.
Implements larcv::ProcessFactoryBase.
Definition at line 44 of file ROIPad.h.
References larcv::ROIPad::ROIPad().
 { return new ROIPad(instance_name); }
The documentation for this class was generated from the following file:
ROIPad.h