LArCV: larcv::TrackerEventDisplay Class Reference
larcv::TrackerEventDisplay Class Reference
#include <TrackerEventDisplay.h>
Public Member Functions
TrackerEventDisplay (const std::string name="TrackerEventDisplay")
Default constructor.
~TrackerEventDisplay ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void SetSplineLocation (const std::string &fpath)
void SetLLOutName (const std::string &foutll)
void SetLLInName (const std::string &finll)
void SetRootAnaFile (const std::string &anaFile)
void SetOutDir (std::string s)
void SetEventList (std::string s)
bool IsGoodVertex (int run, int subrun, int event, int vtxID)
bool IsGoodEntry (int run, int subrun, int event)
void MapTree ()
void CreateSelectedList ()
int SearchMap ()
std::vector< TVector3 > GetJarretVertex (int run, int subrun, int event)
void finalize ()
void MCevaluation ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
int iTrack
larlite::storage_manager _storage
larcv::AStarTracker tracker
std::vector< std::vector< int > > _vertexInfo
double NeutrinoEnergyTh
double NeutrinoEnergyReco
double Ep_t
double Em_t
int _run
int _subrun
int _event
int _nentry
int _entry
int _Nreco
int _run_tree
int _subrun_tree
int _event_tree
int _vtx_id_tree
int _vtx_id
int NvertexSubmitted
int NgoodReco
int NtracksReco
std::vector< std::string > checkEvents
std::string _filename
TTree * _recoTree
std::vector< std::vector< int > > TreeMap
std::vector< std::vector< int > > SelectedList
std::vector< int > _trk_id_v
std::vector< double > _E_muon_v
std::vector< double > _E_proton_v
std::vector< double > * _Length_v
std::vector< double > _Avg_Ion_v
std::vector< double > _Avg_IonY_v
std::vector< double > _vertexPhi
std::vector< double > _vertexTheta
std::vector< double > _closestWall
std::vector< double > _Ion_5cm_v
std::vector< double > _Ion_10cm_v
std::vector< double > _Ion_tot_v
std::vector< double > _IonY_5cm_v
std::vector< double > _IonY_10cm_v
std::vector< double > _IonY_tot_v
std::vector< double > _Trunc_dQdX1_v
std::vector< double > _Trunc_dQdX3_v
std::vector< double > _IondivLength_v
std::vector< std::vector< double > > _trackQ3_v
std::vector< std::vector< double > > _trackQ5_v
std::vector< std::vector< double > > _trackQ10_v
std::vector< std::vector< double > > _trackQ20_v
std::vector< std::vector< double > > _trackQ30_v
std::vector< std::vector< double > > _trackQ50_v
std::vector< std::vector< double > > _TotalADCvalues_v
std::vector< std::vector< double > > _Angle_v
std::vector< bool > * _Reco_goodness_v
std::vector< bool > * _track_Goodness_v
std::vector< larlite::event_track > _EventRecoVertices
std::vector< TVector3 > MCVertices
TVector3 MCvertex
TVector3 RecoVertex
TVector3 _RecoVertex
bool GoodVertex
bool _missingTrack
bool _nothingReconstructed
bool _tooShortDeadWire
bool _tooShortFaintTrack
bool _tooManyTracksAtVertex
bool _possibleCosmic
bool _possiblyCrossing
bool _branchingTracks
bool _jumpingTracks
float _vtx_x
float _vtx_y
float _vtx_z
double _Ep_t
double _Em_t
double _Ee_t
double _MuonStartPoint_X
double _ProtonStartPoint_X
double _ElectronStartPoint_X
double _MuonStartPoint_Y
double _ProtonStartPoint_Y
double _ElectronStartPoint_Y
double _MuonStartPoint_Z
double _ProtonStartPoint_Z
double _ElectronStartPoint_Z
double _MuonEndPoint_X
double _ProtonEndPoint_X
double _ElectronEndPoint_X
double _MuonEndPoint_Y
double _ProtonEndPoint_Y
double _ElectronEndPoint_Y
double _MuonEndPoint_Z
double _ProtonEndPoint_Z
double _ElectronEndPoint_Z
std::string _input_pgraph_producer
std::string _img2d_producer
std::string _par_pix_producer
std::string _true_roi_producer
std::string _spline_file
std::string _foutll
std::string _finll
std::string _fana
std::string out_dir
std::string eventListFile
bool _mask_shower
Detailed Description
Definition at line 36 of file TrackerEventDisplay.h.
Constructor & Destructor Documentation
TrackerEventDisplay()
larcv::TrackerEventDisplay::TrackerEventDisplay (const std::string name = "TrackerEventDisplay")
Default constructor.
Definition at line 53 of file TrackerEventDisplay.cxx.
Referenced by larcv::TrackerEventDisplayProcessFactory::create().
     : ProcessBase(name),
     _spline_file("Proton_Muon_Range_dEdx_LAr_TSplines.root"){}
~TrackerEventDisplay()
larcv::TrackerEventDisplay::~TrackerEventDisplay () inline
Default destructor.
Definition at line 44 of file TrackerEventDisplay.h.
References configure(), initialize(), process(), and SetSplineLocation().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::TrackerEventDisplay::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 57 of file TrackerEventDisplay.cxx.
References _img2d_producer, _input_pgraph_producer, _mask_shower, _par_pix_producer, _true_roi_producer, and larcv::PSet::get().
Referenced by ~TrackerEventDisplay().
{
         _input_pgraph_producer     = cfg.get<std::string>("InputPgraphProducer");
         _img2d_producer            = cfg.get<std::string>("Image2DProducer");
         _par_pix_producer          = cfg.get<std::string>("ParPixelProducer");
         _true_roi_producer         = cfg.get<std::string>("TrueROIProducer");
         _mask_shower               = cfg.get<bool>("MaskShower",false);
     }
CreateSelectedList()
void larcv::TrackerEventDisplay::CreateSelectedList ()
Definition at line 343 of file TrackerEventDisplay.cxx.
References eventListFile, LARCV_CRITICAL, and SelectedList.
Referenced by initialize(), and SetEventList().
{
         if(SelectedList.size()!=0)SelectedList.clear();
         if(eventListFile=="")return;
         std::ifstream listFile(eventListFile);
         if (!listFile) {
             LARCV_CRITICAL() << "ERROR, could not open " << eventListFile << " will die now..." << std::endl;
             throw larbys("die");
         }
         bool GoOn = true;
         int thisRun, thisSubRun, thisEvent, thisVertex;
         while(GoOn == true){
             std::vector<int> eventInfo(4);
             listFile >> thisRun >> thisSubRun >> thisEvent >> thisVertex;
             eventInfo[0] = thisRun;
             eventInfo[1] = thisSubRun;
             eventInfo[2] = thisEvent;
             eventInfo[3] = thisVertex;
             if(listFile.eof()){GoOn=false;break;}
             SelectedList.push_back(eventInfo);
             std::cout << SelectedList.back()[0] << "\t" << SelectedList.back()[1] << "\t" << SelectedList.back()[2] << "\t" << SelectedList.back()[3] << std::endl;
         }
     }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::TrackerEventDisplay::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 286 of file TrackerEventDisplay.cxx.
References _storage, larcv::AStarTracker::finalize(), and tracker.
Referenced by SetEventList().
{
         tracker.finalize();
         std::cout << "finalized tracker" << std::endl;
         _storage.close();
     }
GetJarretVertex()
std::vector<TVector3> larcv::TrackerEventDisplay::GetJarretVertex (int run, int subrun, int event)
Referenced by SetEventList().
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::TrackerEventDisplay::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 66 of file TrackerEventDisplay.cxx.
References _event_tree, _fana, _finll, _Length_v, _Reco_goodness_v, _recoTree, _run_tree, _spline_file, _storage, _subrun_tree, _track_Goodness_v, _vtx_id_tree, CreateSelectedList(), larcv::AStarTracker::initialize(), LARCV_CRITICAL, LARCV_INFO, MapTree(), out_dir, larcv::AStarTracker::SetDrawOutputs(), larcv::AStarTracker::SetOutputDir(), larcv::AStarTracker::SetSplineFile(), larcv::AStarTracker::SetVerbose(), and tracker.
Referenced by ~TrackerEventDisplay().
{
         LARCV_INFO() << "[TrackerEventDisplay]" << std::endl;
         assert(!_spline_file.empty());
         tracker.SetDrawOutputs(false);
         tracker.SetOutputDir(out_dir);
         tracker.SetSplineFile(_spline_file);
         tracker.initialize();
         tracker.SetVerbose(0);
         std::string filename;
         std::cout << filename << std::endl;
         if (_finll.empty()) throw larbys("specify larlite file input name");
         if (_fana.empty())  throw larbys("specify root ana file input name");
         _storage.set_io_mode(larlite::storage_manager::kREAD);
         _storage.add_in_filename(_finll);
         if(!_storage.open()) {
             LARCV_CRITICAL() << "ERROR, larlite input file could not open" << std::endl;
             throw larbys("die");
         }
         TFile *fINana = TFile::Open(Form("%s",_fana.c_str()),"READ");
         if(!(fINana->IsOpen())){
             LARCV_CRITICAL() << "ERROR, root ana file could not open" << std::endl;
             throw larbys("die");
         }
         _recoTree = nullptr;
         _recoTree = (TTree*)fINana->Get("_recoTree");
         if(_recoTree==0){
             LARCV_CRITICAL() << "ERROR, could not access _recoTree" << std::endl;
             throw larbys("die");
         }
         _track_Goodness_v = 0;
         _Length_v = 0;
         _Reco_goodness_v = 0;
         _recoTree->SetBranchAddress("run",&_run_tree);
         _recoTree->SetBranchAddress("subrun",&_subrun_tree);
         _recoTree->SetBranchAddress("event",&_event_tree);
         _recoTree->SetBranchAddress("vtx_id",&_vtx_id_tree);
         _recoTree->SetBranchAddress("track_Goodness_v",&_track_Goodness_v);
         _recoTree->SetBranchAddress("Length_v",&_Length_v);
         _recoTree->SetBranchAddress("Reco_goodness_v",&_Reco_goodness_v);
         CreateSelectedList();
         MapTree();
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
IsGoodEntry()
bool larcv::TrackerEventDisplay::IsGoodEntry (int run, int subrun, int event)
Referenced by SetEventList().
IsGoodVertex()
bool larcv::TrackerEventDisplay::IsGoodVertex (int run, int subrun, int event, int vtxID)
Referenced by SetEventList().
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MapTree()
void larcv::TrackerEventDisplay::MapTree ()
Definition at line 301 of file TrackerEventDisplay.cxx.
References _event_tree, _recoTree, _run_tree, _subrun_tree, _vtx_id_tree, and TreeMap.
Referenced by initialize(), and SetEventList().
{
         if(TreeMap.size() == 0)TreeMap.clear();
         for(int i=0;i<_recoTree->GetEntries();i++){
             _recoTree->GetEntry(i);
             std::vector<int> entryInfo(4);
             entryInfo[0] = _run_tree;
             entryInfo[1] = _subrun_tree;
             entryInfo[2] = _event_tree;
             entryInfo[3] = _vtx_id_tree ;
             TreeMap.push_back(entryInfo);
         }
     }
MCevaluation()
void larcv::TrackerEventDisplay::MCevaluation ()
Definition at line 248 of file TrackerEventDisplay.cxx.
References _Avg_Ion_v, _event, _run, _subrun, checkEvents, Em_t, Ep_t, larcv::AStarTracker::GetEnergies(), larcv::AStarTracker::IsGoodVertex(), NeutrinoEnergyTh, and tracker.
Referenced by SetEventList().
{
         std::cout << "MCevaluation()" << std::endl;
         std::vector< std::vector<double> > Energies_v = tracker.GetEnergies();
         //_Length_v = tracker.GetVertexLength();
         if(!tracker.IsGoodVertex()){std::cout << "error: is not good vertex" << std::endl;return;}
         if(_Avg_Ion_v.size()!=2){std::cout << "error: _Avg_Ion_v.size() = " << _Avg_Ion_v.size() << std::endl;return;}
         std::cout << "in store energies : " << std::endl;
         std::cout << Energies_v[0][0] << ":" << Energies_v[0][1] << std::endl;
         std::cout << Energies_v[1][0] << ":" << Energies_v[1][1] << std::endl;
         double Epreco;
         double Emreco;
         if(_Avg_Ion_v[0] > _Avg_Ion_v[1]){
             Epreco = Energies_v[0][0];// first track is proton
             Emreco = Energies_v[1][1];// second track is muon
         }
         else{
             Epreco = Energies_v[1][0]; // second track is proton
             Emreco = Energies_v[0][1]; // first track is muon
         }
         if( std::abs((Epreco-Ep_t)/Ep_t) > 0.1 || std::abs((Emreco-Em_t)/Em_t) > 0.1 ){
             checkEvents.push_back(Form("%d_%d_%d",_run,_subrun,_event));
         }
         std::cout << "proton : Epreco = " << Epreco << " MeV, Epth : " << Ep_t << " MeV..." << 100*(Epreco-Ep_t)/Ep_t << " %" << std::endl;
         std::cout << "muon   : Emreco = " << Emreco << " MeV, Emth : " << Em_t << " MeV..." << 100*(Emreco-Em_t)/Em_t << " %" << std::endl;
         std::cout << "E nu th   : " << NeutrinoEnergyTh << " MeV" << std::endl;
         std::cout << "E nu Reco : " << Epreco+Emreco << " MeV" << std::endl;
         std::cout << "relative Enu diff: " << 100*((Epreco+Emreco+146)-NeutrinoEnergyTh)/NeutrinoEnergyTh << " %" << std::endl;
         std::cout << "relative Enu_p+m diff: " << 100*((Epreco+Emreco)-(Ep_t+Em_t))/(Ep_t+Em_t) << " %" << std::endl;
     }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::TrackerEventDisplay::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 118 of file TrackerEventDisplay.cxx.
References _entry, _event, _img2d_producer, _Length_v, _Reco_goodness_v, _recoTree, _run, _storage, _subrun, _track_Goodness_v, _vtx_id, larcv::IOManager< T >::current_entry(), larcv::AStarTracker::DrawVertex(), larcv::AStarTracker::FeedLarliteVertexTracks(), larcv::AStarTracker::FeedVtxGoodness(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::get_n_entries(), larcv::kProductImage2D, SearchMap(), larcv::AStarTracker::SetOriginalImage(), larcv::AStarTracker::SetSingleVertex(), larcv::AStarTracker::SetTaggedImage(), larcv::AStarTracker::SetTrackInfo(), larcv::AStarTracker::SetVertexID(), and tracker.
Referenced by ~TrackerEventDisplay().
{
         //ClearEvent();
         std::cout << std::endl;
         std::cout << "============================================" << std::endl;
         std::cout << "Entry " << mgr.current_entry() << " / " << mgr.get_n_entries() << std::endl;
         std::cout << "============================================" << std::endl;
         gStyle->SetOptStat(0);
         TVector3 vertex(-1,-1,-1);
         auto ev_img_v        = (EventImage2D*)mgr.get_data(kProductImage2D,_img2d_producer);
         _run    = (int) ev_img_v->run();
         _subrun = (int) ev_img_v->subrun();
         _event  = (int) ev_img_v->event();
         _entry  = (int) mgr.current_entry();
         _storage.next_event();
         auto ev_track  = (larlite::event_track*)  _storage.get_data(larlite::data::kTrack,"trackReco");
         auto ev_vertex = (larlite::event_vertex*) _storage.get_data(larlite::data::kVertex,"trackReco");
         auto ev_ass    = (larlite::event_ass*)    _storage.get_data(larlite::data::kAssociation,"trackReco");
         if(ev_img_v->Image2DArray().size()==0){std::cout << "ev_img_v->Image2DArray().size()==0" << std::endl;return true;}
         if(ev_track->size()==0){std::cout << "ev_track->size()==0" << std::endl;return true;}
         if((int)(_storage.run_id()) != _run){std::cout << "run# larlite and larcv don't match" << std::endl;return true;}
         if((int)(_storage.subrun_id()) != _subrun){std::cout << "subrun# larlite and larcv don't match" << std::endl;return true;}
         if((int)(_storage.event_id()) != _event){std::cout << "event# larlite and larcv don't match" << std::endl;return true;}
         //auto tag_img_thru_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"thrumutags");
         //auto tag_img_stop_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"stopmutags");
         //auto ev_pcluster_v = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_img");
         //auto ev_ctor_v     = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_ctor");
         // get the event clusters and full images
         //auto const& ctor_m = ev_ctor_v->Pixel2DClusterArray();
         auto full_adc_img_v = &(ev_img_v->Image2DArray());
         //auto full_tag_img_thru_v = &(tag_img_thru_v->Image2DArray());
         //auto full_tag_img_stop_v = &(tag_img_stop_v->Image2DArray());
         //
         // Fill MC if exists
         //
         /*EventROI* ev_partroi_v = nullptr;
         if (!_true_roi_producer.empty()) ev_partroi_v = (EventROI*) mgr.get_data(kProductROI,_true_roi_producer);
         if (ev_partroi_v) {
             const auto& mc_roi_v = ev_partroi_v->ROIArray();
             FillMC(mc_roi_v);
         }*/
         // loop over found vertices
         //auto const& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
         std::vector<larcv::ImageMeta> Full_meta_v(3);
         std::vector<larcv::Image2D> Tagged_Image(3);
         std::vector<larcv::Image2D> Full_image_v(3);
         double wireRange = 5000;
         double tickRange = 8502;
         // Create base image2D with the full view, fill it with the input image 2D, we will crop it later
         for(size_t iPlane=0;iPlane<3;iPlane++){
             Full_meta_v[iPlane] = larcv::ImageMeta(wireRange,tickRange,(int)(tickRange)/6,(int)(wireRange),0,tickRange);
             Full_image_v[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             Tagged_Image[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             if(full_adc_img_v->size() == 3)Full_image_v[iPlane].overlay( (*full_adc_img_v)[iPlane] );
             //if(full_tag_img_thru_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_thru_v)[iPlane] );
             //if(full_tag_img_stop_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_stop_v)[iPlane] );
         }
         tracker.SetOriginalImage(Full_image_v);
         tracker.SetTaggedImage(Tagged_Image);
         tracker.SetTrackInfo(_run, _subrun, _event, 0);
         std::cout << _run << " " << _subrun << " " << _event <<  std::endl;
         static std::vector<TVector3> vertex_v;
         if(vertex_v.size()!=0)vertex_v.clear();
         larlite::event_track* ev_trk=nullptr;
         auto const& vtx_to_trk = _storage.find_one_ass(ev_vertex->id(), ev_trk, ev_vertex->name());
         if(!ev_trk || ev_trk->size() == 0) throw larlite::DataFormatException("Could not find associated track data product!");
         for(int vertex_index=0;vertex_index<ev_vertex->size();vertex_index++){
             larlite::event_track TracksAtVertex;
             _vtx_id = vertex_index;
             std::cout << "vertex #" << vertex_index << std::endl;
             int treeEntry = SearchMap();
             if(treeEntry==-1){std::cout << "Not in the list...passing..." << std::endl;continue;}
             _recoTree->GetEntry(treeEntry);
             bool GoodReco = true;
             int N5cm = 0;
             std::cout  << "==> "<< _Length_v->size() << ",  " << _track_Goodness_v->size() << std::endl;
             for(int i = 0;i<_Length_v->size();i++){
                 if(_Length_v->at(i) > 5 && _track_Goodness_v->at(i) != 1)GoodReco =false;
                 if(_Length_v->at(i) > 5)N5cm++;
             }
             if(N5cm != 2)GoodReco=false;
             if(_Length_v->size() == 0)GoodReco=false;
             //if(!GoodReco)continue;
             tracker.FeedVtxGoodness((*_Reco_goodness_v));
             tracker.SetSingleVertex(TVector3(ev_vertex->at(vertex_index).X(),ev_vertex->at(vertex_index).Y(),ev_vertex->at(vertex_index).Z()));
             tracker.SetVertexID(ev_vertex->at(vertex_index).ID());
             for(auto const& trk_index : vtx_to_trk[vertex_index]) {
                 TracksAtVertex.push_back( (*ev_trk)[trk_index]);
                 std::cout << "\t => trk#" << trk_index << ", " << TracksAtVertex.back().Length() << " cm" << std::endl;
             }
             tracker.FeedLarliteVertexTracks(TracksAtVertex);
             tracker.DrawVertex();
         }
         return true;
     }
SearchMap()
int larcv::TrackerEventDisplay::SearchMap ()
Definition at line 314 of file TrackerEventDisplay.cxx.
References _event, _run, _subrun, _vtx_id, LARCV_CRITICAL, SelectedList, and TreeMap.
Referenced by process(), and SetEventList().
{
         int treeEntry=-1;
         for(int i=0;i<TreeMap.size();i++){
             if(_run != TreeMap[i][0])continue;
             if(_subrun != TreeMap[i][1])continue;
             if(_event  != TreeMap[i][2])continue;
             if(_vtx_id != TreeMap[i][3])continue;
             treeEntry=i;
             break;
         }
         if(treeEntry==-1){
             LARCV_CRITICAL() << "ERROR, could not find matching entry in _recoTree" << std::endl;
             throw larbys("die");
         }
         if(SelectedList.size()==0)return treeEntry;
         bool inList = false;
         for(int i=0;i<SelectedList.size();i++){
             if(_run != SelectedList[i][0])continue;
             if(_subrun != SelectedList[i][1])continue;
             if(_event  != SelectedList[i][2])continue;
             if(_vtx_id != SelectedList[i][3])continue;
             inList = true;
             break;
         }
         if(inList) return treeEntry;
         else return -1;
     }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetEventList()
void larcv::TrackerEventDisplay::SetEventList (std::string s) inline
Definition at line 55 of file TrackerEventDisplay.h.
References CreateSelectedList(), eventListFile, finalize(), GetJarretVertex(), IsGoodEntry(), IsGoodVertex(), MapTree(), MCevaluation(), and SearchMap().
 {eventListFile = s;}
SetLLInName()
void larcv::TrackerEventDisplay::SetLLInName (const std::string & finll) inline
Definition at line 52 of file TrackerEventDisplay.h.
References _finll.
 { _finll = finll;}
SetLLOutName()
void larcv::TrackerEventDisplay::SetLLOutName (const std::string & foutll) inline
Definition at line 51 of file TrackerEventDisplay.h.
References _foutll.
 { _foutll = foutll; }
SetOutDir()
void larcv::TrackerEventDisplay::SetOutDir (std::string s) inline
Definition at line 54 of file TrackerEventDisplay.h.
References out_dir.
 {out_dir = s;}
SetRootAnaFile()
void larcv::TrackerEventDisplay::SetRootAnaFile (const std::string & anaFile) inline
Definition at line 53 of file TrackerEventDisplay.h.
References _fana.
 {_fana = anaFile;}
SetSplineLocation()
void larcv::TrackerEventDisplay::SetSplineLocation (const std::string & fpath)
Definition at line 294 of file TrackerEventDisplay.cxx.
References _spline_file, LARCV_DEBUG, LARCV_INFO, larcv::AStarTracker::SetSplineFile(), and tracker.
Referenced by ~TrackerEventDisplay().
{
         LARCV_INFO() << "setting spline loc @ " << fpath << std::endl;
         tracker.SetSplineFile(fpath);
         _spline_file = fpath;
         LARCV_DEBUG() << "end" << std::endl;
     }
Member Data Documentation
_Angle_v
std::vector< std::vector<double> > larcv::TrackerEventDisplay::_Angle_v private
Definition at line 127 of file TrackerEventDisplay.h.
_Avg_Ion_v
std::vector<double> larcv::TrackerEventDisplay::_Avg_Ion_v private
Definition at line 104 of file TrackerEventDisplay.h.
Referenced by MCevaluation().
_Avg_IonY_v
std::vector<double> larcv::TrackerEventDisplay::_Avg_IonY_v private
Definition at line 105 of file TrackerEventDisplay.h.
_branchingTracks
bool larcv::TrackerEventDisplay::_branchingTracks private
Definition at line 145 of file TrackerEventDisplay.h.
_closestWall
std::vector<double> larcv::TrackerEventDisplay::_closestWall private
Definition at line 108 of file TrackerEventDisplay.h.
_E_muon_v
std::vector<double> larcv::TrackerEventDisplay::_E_muon_v private
Definition at line 101 of file TrackerEventDisplay.h.
_E_proton_v
std::vector<double> larcv::TrackerEventDisplay::_E_proton_v private
Definition at line 102 of file TrackerEventDisplay.h.
_Ee_t
double larcv::TrackerEventDisplay::_Ee_t private
Definition at line 154 of file TrackerEventDisplay.h.
_ElectronEndPoint_X
double larcv::TrackerEventDisplay::_ElectronEndPoint_X private
Definition at line 176 of file TrackerEventDisplay.h.
_ElectronEndPoint_Y
double larcv::TrackerEventDisplay::_ElectronEndPoint_Y private
Definition at line 180 of file TrackerEventDisplay.h.
_ElectronEndPoint_Z
double larcv::TrackerEventDisplay::_ElectronEndPoint_Z private
Definition at line 184 of file TrackerEventDisplay.h.
_ElectronStartPoint_X
double larcv::TrackerEventDisplay::_ElectronStartPoint_X private
Definition at line 161 of file TrackerEventDisplay.h.
_ElectronStartPoint_Y
double larcv::TrackerEventDisplay::_ElectronStartPoint_Y private
Definition at line 165 of file TrackerEventDisplay.h.
_ElectronStartPoint_Z
double larcv::TrackerEventDisplay::_ElectronStartPoint_Z private
Definition at line 169 of file TrackerEventDisplay.h.
_Em_t
double larcv::TrackerEventDisplay::_Em_t private
Definition at line 153 of file TrackerEventDisplay.h.
_entry
int larcv::TrackerEventDisplay::_entry private
Definition at line 83 of file TrackerEventDisplay.h.
Referenced by process().
_Ep_t
double larcv::TrackerEventDisplay::_Ep_t private
Definition at line 152 of file TrackerEventDisplay.h.
_event
int larcv::TrackerEventDisplay::_event private
Definition at line 81 of file TrackerEventDisplay.h.
Referenced by MCevaluation(), process(), and SearchMap().
_event_tree
int larcv::TrackerEventDisplay::_event_tree private
Definition at line 88 of file TrackerEventDisplay.h.
Referenced by initialize(), and MapTree().
_EventRecoVertices
std::vector<larlite::event_track> larcv::TrackerEventDisplay::_EventRecoVertices private
Definition at line 130 of file TrackerEventDisplay.h.
_fana
std::string larcv::TrackerEventDisplay::_fana private
Definition at line 193 of file TrackerEventDisplay.h.
Referenced by initialize(), and SetRootAnaFile().
_filename
std::string larcv::TrackerEventDisplay::_filename private
Definition at line 95 of file TrackerEventDisplay.h.
_finll
std::string larcv::TrackerEventDisplay::_finll private
Definition at line 192 of file TrackerEventDisplay.h.
Referenced by initialize(), and SetLLInName().
_foutll
std::string larcv::TrackerEventDisplay::_foutll private
Definition at line 191 of file TrackerEventDisplay.h.
Referenced by SetLLOutName().
_img2d_producer
std::string larcv::TrackerEventDisplay::_img2d_producer private
Definition at line 187 of file TrackerEventDisplay.h.
Referenced by configure(), and process().
_input_pgraph_producer
std::string larcv::TrackerEventDisplay::_input_pgraph_producer private
Definition at line 186 of file TrackerEventDisplay.h.
Referenced by configure().
_Ion_10cm_v
std::vector<double> larcv::TrackerEventDisplay::_Ion_10cm_v private
Definition at line 110 of file TrackerEventDisplay.h.
_Ion_5cm_v
std::vector<double> larcv::TrackerEventDisplay::_Ion_5cm_v private
Definition at line 109 of file TrackerEventDisplay.h.
_Ion_tot_v
std::vector<double> larcv::TrackerEventDisplay::_Ion_tot_v private
Definition at line 111 of file TrackerEventDisplay.h.
_IondivLength_v
std::vector<double> larcv::TrackerEventDisplay::_IondivLength_v private
Definition at line 119 of file TrackerEventDisplay.h.
_IonY_10cm_v
std::vector<double> larcv::TrackerEventDisplay::_IonY_10cm_v private
Definition at line 114 of file TrackerEventDisplay.h.
_IonY_5cm_v
std::vector<double> larcv::TrackerEventDisplay::_IonY_5cm_v private
Definition at line 113 of file TrackerEventDisplay.h.
_IonY_tot_v
std::vector<double> larcv::TrackerEventDisplay::_IonY_tot_v private
Definition at line 115 of file TrackerEventDisplay.h.
_jumpingTracks
bool larcv::TrackerEventDisplay::_jumpingTracks private
Definition at line 146 of file TrackerEventDisplay.h.
_Length_v
std::vector<double>* larcv::TrackerEventDisplay::_Length_v private
Definition at line 103 of file TrackerEventDisplay.h.
Referenced by initialize(), and process().
_mask_shower
bool larcv::TrackerEventDisplay::_mask_shower private
Definition at line 196 of file TrackerEventDisplay.h.
Referenced by configure().
_missingTrack
bool larcv::TrackerEventDisplay::_missingTrack private
Definition at line 138 of file TrackerEventDisplay.h.
_MuonEndPoint_X
double larcv::TrackerEventDisplay::_MuonEndPoint_X private
Definition at line 174 of file TrackerEventDisplay.h.
_MuonEndPoint_Y
double larcv::TrackerEventDisplay::_MuonEndPoint_Y private
Definition at line 178 of file TrackerEventDisplay.h.
_MuonEndPoint_Z
double larcv::TrackerEventDisplay::_MuonEndPoint_Z private
Definition at line 182 of file TrackerEventDisplay.h.
_MuonStartPoint_X
double larcv::TrackerEventDisplay::_MuonStartPoint_X private
Definition at line 159 of file TrackerEventDisplay.h.
_MuonStartPoint_Y
double larcv::TrackerEventDisplay::_MuonStartPoint_Y private
Definition at line 163 of file TrackerEventDisplay.h.
_MuonStartPoint_Z
double larcv::TrackerEventDisplay::_MuonStartPoint_Z private
Definition at line 167 of file TrackerEventDisplay.h.
_nentry
int larcv::TrackerEventDisplay::_nentry private
Definition at line 82 of file TrackerEventDisplay.h.
_nothingReconstructed
bool larcv::TrackerEventDisplay::_nothingReconstructed private
Definition at line 139 of file TrackerEventDisplay.h.
_Nreco
int larcv::TrackerEventDisplay::_Nreco private
Definition at line 84 of file TrackerEventDisplay.h.
_par_pix_producer
std::string larcv::TrackerEventDisplay::_par_pix_producer private
Definition at line 188 of file TrackerEventDisplay.h.
Referenced by configure().
_possibleCosmic
bool larcv::TrackerEventDisplay::_possibleCosmic private
Definition at line 143 of file TrackerEventDisplay.h.
_possiblyCrossing
bool larcv::TrackerEventDisplay::_possiblyCrossing private
Definition at line 144 of file TrackerEventDisplay.h.
_ProtonEndPoint_X
double larcv::TrackerEventDisplay::_ProtonEndPoint_X private
Definition at line 175 of file TrackerEventDisplay.h.
_ProtonEndPoint_Y
double larcv::TrackerEventDisplay::_ProtonEndPoint_Y private
Definition at line 179 of file TrackerEventDisplay.h.
_ProtonEndPoint_Z
double larcv::TrackerEventDisplay::_ProtonEndPoint_Z private
Definition at line 183 of file TrackerEventDisplay.h.
_ProtonStartPoint_X
double larcv::TrackerEventDisplay::_ProtonStartPoint_X private
Definition at line 160 of file TrackerEventDisplay.h.
_ProtonStartPoint_Y
double larcv::TrackerEventDisplay::_ProtonStartPoint_Y private
Definition at line 164 of file TrackerEventDisplay.h.
_ProtonStartPoint_Z
double larcv::TrackerEventDisplay::_ProtonStartPoint_Z private
Definition at line 168 of file TrackerEventDisplay.h.
_Reco_goodness_v
std::vector<bool>* larcv::TrackerEventDisplay::_Reco_goodness_v private
Definition at line 128 of file TrackerEventDisplay.h.
Referenced by initialize(), and process().
_recoTree
TTree* larcv::TrackerEventDisplay::_recoTree private
Definition at line 97 of file TrackerEventDisplay.h.
Referenced by initialize(), MapTree(), and process().
_RecoVertex
TVector3 larcv::TrackerEventDisplay::_RecoVertex private
Definition at line 135 of file TrackerEventDisplay.h.
_run
int larcv::TrackerEventDisplay::_run private
Definition at line 79 of file TrackerEventDisplay.h.
Referenced by MCevaluation(), process(), and SearchMap().
_run_tree
int larcv::TrackerEventDisplay::_run_tree private
Definition at line 86 of file TrackerEventDisplay.h.
Referenced by initialize(), and MapTree().
_spline_file
std::string larcv::TrackerEventDisplay::_spline_file private
Definition at line 190 of file TrackerEventDisplay.h.
Referenced by initialize(), and SetSplineLocation().
_storage
larlite::storage_manager larcv::TrackerEventDisplay::_storage private
Definition at line 71 of file TrackerEventDisplay.h.
Referenced by finalize(), initialize(), and process().
_subrun
int larcv::TrackerEventDisplay::_subrun private
Definition at line 80 of file TrackerEventDisplay.h.
Referenced by MCevaluation(), process(), and SearchMap().
_subrun_tree
int larcv::TrackerEventDisplay::_subrun_tree private
Definition at line 87 of file TrackerEventDisplay.h.
Referenced by initialize(), and MapTree().
_tooManyTracksAtVertex
bool larcv::TrackerEventDisplay::_tooManyTracksAtVertex private
Definition at line 142 of file TrackerEventDisplay.h.
_tooShortDeadWire
bool larcv::TrackerEventDisplay::_tooShortDeadWire private
Definition at line 140 of file TrackerEventDisplay.h.
_tooShortFaintTrack
bool larcv::TrackerEventDisplay::_tooShortFaintTrack private
Definition at line 141 of file TrackerEventDisplay.h.
_TotalADCvalues_v
std::vector< std::vector<double> > larcv::TrackerEventDisplay::_TotalADCvalues_v private
Definition at line 126 of file TrackerEventDisplay.h.
_track_Goodness_v
std::vector<bool>* larcv::TrackerEventDisplay::_track_Goodness_v private
Definition at line 129 of file TrackerEventDisplay.h.
Referenced by initialize(), and process().
_trackQ10_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ10_v private
Definition at line 122 of file TrackerEventDisplay.h.
_trackQ20_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ20_v private
Definition at line 123 of file TrackerEventDisplay.h.
_trackQ30_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ30_v private
Definition at line 124 of file TrackerEventDisplay.h.
_trackQ3_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ3_v private
Definition at line 120 of file TrackerEventDisplay.h.
_trackQ50_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ50_v private
Definition at line 125 of file TrackerEventDisplay.h.
_trackQ5_v
std::vector<std::vector<double> > larcv::TrackerEventDisplay::_trackQ5_v private
Definition at line 121 of file TrackerEventDisplay.h.
_trk_id_v
std::vector<int> larcv::TrackerEventDisplay::_trk_id_v private
Definition at line 100 of file TrackerEventDisplay.h.
_true_roi_producer
std::string larcv::TrackerEventDisplay::_true_roi_producer private
Definition at line 189 of file TrackerEventDisplay.h.
Referenced by configure().
_Trunc_dQdX1_v
std::vector<double> larcv::TrackerEventDisplay::_Trunc_dQdX1_v private
Definition at line 117 of file TrackerEventDisplay.h.
_Trunc_dQdX3_v
std::vector<double> larcv::TrackerEventDisplay::_Trunc_dQdX3_v private
Definition at line 118 of file TrackerEventDisplay.h.
_vertexInfo
std::vector< std::vector<int> > larcv::TrackerEventDisplay::_vertexInfo private
Definition at line 73 of file TrackerEventDisplay.h.
_vertexPhi
std::vector<double> larcv::TrackerEventDisplay::_vertexPhi private
Definition at line 106 of file TrackerEventDisplay.h.
_vertexTheta
std::vector<double> larcv::TrackerEventDisplay::_vertexTheta private
Definition at line 107 of file TrackerEventDisplay.h.
_vtx_id
int larcv::TrackerEventDisplay::_vtx_id private
Definition at line 90 of file TrackerEventDisplay.h.
Referenced by process(), and SearchMap().
_vtx_id_tree
int larcv::TrackerEventDisplay::_vtx_id_tree private
Definition at line 89 of file TrackerEventDisplay.h.
Referenced by initialize(), and MapTree().
_vtx_x
float larcv::TrackerEventDisplay::_vtx_x private
Definition at line 148 of file TrackerEventDisplay.h.
_vtx_y
float larcv::TrackerEventDisplay::_vtx_y private
Definition at line 149 of file TrackerEventDisplay.h.
_vtx_z
float larcv::TrackerEventDisplay::_vtx_z private
Definition at line 150 of file TrackerEventDisplay.h.
checkEvents
std::vector<std::string> larcv::TrackerEventDisplay::checkEvents private
Definition at line 94 of file TrackerEventDisplay.h.
Referenced by MCevaluation().
Em_t
double larcv::TrackerEventDisplay::Em_t private
Definition at line 77 of file TrackerEventDisplay.h.
Referenced by MCevaluation().
Ep_t
double larcv::TrackerEventDisplay::Ep_t private
Definition at line 76 of file TrackerEventDisplay.h.
Referenced by MCevaluation().
eventListFile
std::string larcv::TrackerEventDisplay::eventListFile private
Definition at line 195 of file TrackerEventDisplay.h.
Referenced by CreateSelectedList(), and SetEventList().
GoodVertex
bool larcv::TrackerEventDisplay::GoodVertex private
Definition at line 137 of file TrackerEventDisplay.h.
iTrack
int larcv::TrackerEventDisplay::iTrack private
Definition at line 70 of file TrackerEventDisplay.h.
MCvertex
TVector3 larcv::TrackerEventDisplay::MCvertex private
Definition at line 133 of file TrackerEventDisplay.h.
MCVertices
std::vector<TVector3> larcv::TrackerEventDisplay::MCVertices private
Definition at line 132 of file TrackerEventDisplay.h.
NeutrinoEnergyReco
double larcv::TrackerEventDisplay::NeutrinoEnergyReco private
Definition at line 75 of file TrackerEventDisplay.h.
NeutrinoEnergyTh
double larcv::TrackerEventDisplay::NeutrinoEnergyTh private
Definition at line 74 of file TrackerEventDisplay.h.
Referenced by MCevaluation().
NgoodReco
int larcv::TrackerEventDisplay::NgoodReco private
Definition at line 92 of file TrackerEventDisplay.h.
NtracksReco
int larcv::TrackerEventDisplay::NtracksReco private
Definition at line 93 of file TrackerEventDisplay.h.
NvertexSubmitted
int larcv::TrackerEventDisplay::NvertexSubmitted private
Definition at line 91 of file TrackerEventDisplay.h.
out_dir
std::string larcv::TrackerEventDisplay::out_dir private
Definition at line 194 of file TrackerEventDisplay.h.
Referenced by initialize(), and SetOutDir().
RecoVertex
TVector3 larcv::TrackerEventDisplay::RecoVertex private
Definition at line 134 of file TrackerEventDisplay.h.
SelectedList
std::vector< std::vector<int> > larcv::TrackerEventDisplay::SelectedList private
Definition at line 99 of file TrackerEventDisplay.h.
Referenced by CreateSelectedList(), and SearchMap().
tracker
larcv::AStarTracker larcv::TrackerEventDisplay::tracker private
Definition at line 72 of file TrackerEventDisplay.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetSplineLocation().
TreeMap
std::vector< std::vector<int> > larcv::TrackerEventDisplay::TreeMap private
Definition at line 98 of file TrackerEventDisplay.h.
Referenced by MapTree(), and SearchMap().
The documentation for this class was generated from the following files:
TrackerEventDisplay.h
TrackerEventDisplay.cxx