LArCV: larcv::SuperaMCROI Class Reference
larcv::SuperaMCROI Class Reference
#include <SuperaMCROI.h>
Public Member Functions
SuperaMCROI (const std::string name="SuperaMCROI")
Default constructor.
~SuperaMCROI ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
bool StoreG4SecondaryROI () const
bool StoreG4PrimaryROI () const
const std::vector< std::pair< size_t, size_t > > & ROI2MCNode (int roi_index) const
const std::vector< std::vector< std::pair< size_t, size_t > > > & ROI2MCNode () const
const supera::MCParticleTree & ParticleTree () const
virtual bool is (const std::string question) const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
template<class T >
const std::vector< T > & LArData () const
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
const std::string & LArDataLabel (supera::LArDataType_t type) const
int TimeOffset () const
void ClearEventData ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
const std::string & OutROILabel () const
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
ImageMetaMakerBase * MetaMakerPtr ()
Private Member Functions
bool FilterNode (const supera::MCNode &node) const
larcv::ImageMeta FormatMeta (const larcv::ImageMeta &part_image, const larcv::ImageMeta &event_image) const
larcv::ROI MakeROI (const supera::MCNode &node, const std::vector< supera::LArSimCh_t > &sch_v) const
void UpdatePrimaryROI (larcv::ROI &pri_roi, std::vector< larcv::ROI > &sec_roi_v) const
Private Attributes
bool _store_roi
bool _store_g4_primary_roi
bool _store_g4_secondary_roi
std::vector< larcv::ROI > _roi_v
supera::MCParticleTree _mcpt
supera::MCROIMaker _mcroi_maker
std::vector< std::vector< std::pair< size_t, size_t > > > _roi2mcnode_vv
unsigned short _pass_origin
std::vector< int > _filter_pdg
std::vector< double > _filter_min_einit
std::vector< double > _filter_min_edep
double _shower_min_einit
double _shower_min_edep
double _track_min_einit
double _track_min_edep
size_t _filter_min_cols
size_t _filter_min_rows
Detailed Description
Definition at line 32 of file SuperaMCROI.h.
Constructor & Destructor Documentation
SuperaMCROI()
larcv::SuperaMCROI::SuperaMCROI (const std::string name = "SuperaMCROI")
Default constructor.
Definition at line 14 of file SuperaMCROI.cxx.
Referenced by larcv::SuperaMCROIProcessFactory::create().
     : SuperaBase(name)
   {}
~SuperaMCROI()
larcv::SuperaMCROI::~SuperaMCROI () inline
Default destructor.
Definition at line 42 of file SuperaMCROI.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData () inherited
Definition at line 89 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v, larcv::SuperaBase::_ptr_mcs_v, larcv::SuperaBase::_ptr_mct_v, larcv::SuperaBase::_ptr_mctruth_v, larcv::SuperaBase::_ptr_opdigit_v, larcv::SuperaBase::_ptr_sch_v, and larcv::SuperaBase::_ptr_wire_v.
Referenced by larcv::SuperaBase::finalize(), larcv::SuperaBase::initialize(), larcv::SuperaMetaMaker::process(), larcv::SuperaBase::SuperaBase(), and larcv::SuperaBase::TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
ColCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::ColCompressionFactor () const inherited
Definition at line 36 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::ColCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->ColCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->ColCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
configure()
void larcv::SuperaMCROI::configure (const PSet & cfg) virtual
Reimplemented from supera::ImageMetaMaker.
Definition at line 26 of file SuperaMCROI.cxx.
References _filter_min_cols, _filter_min_edep, _filter_min_einit, _filter_min_rows, _filter_pdg, _mcpt, _mcroi_maker, _pass_origin, _shower_min_edep, _shower_min_einit, _store_g4_primary_roi, _store_g4_secondary_roi, _store_roi, _track_min_edep, _track_min_einit, supera::ParamsROI::configure(), supera::MCROIMaker::configure(), larcv::SuperaBase::configure(), supera::ImageMetaMaker::configure(), larcv::supera::MCParticleTree< T, U, V, W >::configure(), larcv::PSet::get(), and LARCV_CRITICAL.
Referenced by larcv::SuperaMCPCluster::configure(), and ~SuperaMCROI().
   {
     SuperaBase::configure(cfg);
     supera::ParamsROI::configure(cfg);
     supera::ImageMetaMaker::configure(cfg);
     _store_roi = cfg.get<bool>("StoreROI",true);
     _store_g4_secondary_roi = cfg.get<bool>("StoreG4SecondaryROI",true);
     _store_g4_primary_roi = cfg.get<bool>("StoreG4PrimaryROI",true);
     _mcpt.configure(cfg.get<supera::Config_t>("MCParticleTree"));
     _mcroi_maker.configure(cfg.get<supera::Config_t>("MCROIMaker"));
     _pass_origin = cfg.get<unsigned short>("Origin");
     _mcpt.FilterOrigin(_pass_origin);
     _filter_pdg  = cfg.get<std::vector<int> >("FilterTargetPDG");
     _filter_min_einit = cfg.get<std::vector<double> >("FilterTargetInitEMin");
     _filter_min_edep  = cfg.get<std::vector<double> >("FilterTargetDepEMin");
     if(_filter_pdg.size() != _filter_min_einit.size()) {
       LARCV_CRITICAL() << "FilterTargetPDG and FilterTargetInitEMin not the same length!" << std::endl;
       throw larbys();
     }
     if(_filter_pdg.size() != _filter_min_edep.size()) {
       LARCV_CRITICAL() << "FilterTargetPDG and FilterTargetDepEMin not the same length!" << std::endl;
       throw larbys();
     }
     _shower_min_einit = cfg.get<double>("ShowerInitEMin");
     _shower_min_edep  = cfg.get<double>("ShowerDepEMin");
     _track_min_einit = cfg.get<double>("TrackInitEMin");
     _track_min_edep  = cfg.get<double>("TrackDepEMin");
     _filter_min_cols = cfg.get<size_t>("FilterROIMinCols");
     _filter_min_rows = cfg.get<size_t>("FilterROIMinRows");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
FilterNode()
bool larcv::SuperaMCROI::FilterNode (const supera::MCNode & node) const private
Definition at line 279 of file SuperaMCROI.cxx.
References _filter_min_edep, _filter_min_einit, _filter_pdg, _pass_origin, _shower_min_edep, _shower_min_einit, _track_min_edep, _track_min_einit, supera::MCNode::kMCShower, supera::MCNode::kMCTrack, supera::MCNode::kMCTruth, LARCV_DEBUG, supera::MCNode::origin, supera::MCNode::source_index, and supera::MCNode::source_type.
Referenced by process().
   {
     if(node.source_type == supera::MCNode::SourceType_t::kMCTruth) {
       if(_pass_origin && node.origin != _pass_origin)
     return false;
     }else if(node.source_type == supera::MCNode::SourceType_t::kMCTrack) {
       auto const& mctrack = LArData<supera::LArMCTrack_t>()[node.source_index];
       LARCV_DEBUG() << "MCTrack InitE " << mctrack.Start().E() << " ... DepE "
             << (mctrack.size() >1 ? mctrack.front().E() - mctrack.back().E() : 0) << std::endl;
       if(mctrack.Start().E() < _track_min_einit) return false;
       if(_track_min_edep > 0) {
     if(mctrack.size()<2) return false;
     if( (mctrack.front().E() - mctrack.back().E()) < _track_min_edep ) return false;
       }
       for(size_t filter_idx=0; filter_idx<_filter_pdg.size(); ++filter_idx) {
     auto const& pdg = _filter_pdg[filter_idx];
     if(pdg != mctrack.PdgCode()) continue;
     auto const& filter_min_einit = _filter_min_einit[filter_idx];
     if(mctrack.Start().E() < filter_min_einit) return false;
     auto const& filter_min_edep = _filter_min_edep[filter_idx];
     if(filter_min_edep > 0) {
       if(mctrack.size()<2) return false;
       if( (mctrack.front().E() - mctrack.back().E()) < filter_min_edep ) return false;
     }
       }
     }else if(node.source_type == supera::MCNode::SourceType_t::kMCShower) {
       auto const& mcshower = LArData<supera::LArMCShower_t>()[node.source_index];
       LARCV_DEBUG() << "MCShower InitE " << mcshower.Start().E() << " ... DepE "
             << mcshower.DetProfile().E() << std::endl;
       if(mcshower.Start().E() < _shower_min_einit) return false;
       if(mcshower.DetProfile().E() < _shower_min_edep) return false;
       for(size_t filter_idx=0; filter_idx<_filter_pdg.size(); ++filter_idx) {
     auto const& pdg = _filter_pdg[filter_idx];
     if(pdg != mcshower.PdgCode()) continue;
     auto const& filter_min_einit = _filter_min_einit[filter_idx];
     if(mcshower.Start().E() < filter_min_einit) return false;
     auto const& filter_min_edep = _filter_min_edep[filter_idx];
     if( mcshower.DetProfile().E() < filter_min_edep) return false;
       }
     }
     return true;
   }
finalize()
void larcv::SuperaMCROI::finalize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 479 of file SuperaMCROI.cxx.
Referenced by larcv::SuperaMCPCluster::finalize(), and ~SuperaMCROI().
   {}
FormatMeta()
larcv::ImageMeta larcv::SuperaMCROI::FormatMeta (const larcv::ImageMeta & part_image, const larcv::ImageMeta & event_image) const private
Definition at line 401 of file SuperaMCROI.cxx.
References larcv::ImageMeta::cols(), larcv::ImageMeta::dump(), larcv::ImageMeta::height(), LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), larcv::ImageMeta::rows(), and larcv::ImageMeta::width().
Referenced by MakeROI().
   {
     LARCV_DEBUG() << "Before format  " << part_image.dump();
     const size_t modular_row = event_image.height() / event_image.rows();
     const size_t modular_col = event_image.width()  / event_image.cols();
     if (event_image.rows() < modular_row || event_image.cols() < modular_col) {
       LARCV_ERROR() << "Event image too small to format ROI!" << std::endl;
       throw larbys();
     }
     double min_x  = (part_image.min_x() < event_image.min_x() ? event_image.min_x() : part_image.min_x() );
     double max_y  = (part_image.max_y() > event_image.max_y() ? event_image.max_y() : part_image.max_y() );
     double width  = (part_image.width() + min_x > event_image.max_x() ? event_image.max_x() - min_x : part_image.width());
     double height = (max_y - part_image.height() < event_image.min_y() ? max_y - event_image.min_y() : part_image.height());
     size_t rows   = height / part_image.pixel_height();
     size_t cols   = width  / part_image.pixel_width();
     if (modular_col > 1 && cols % modular_col) {
       int npixels = (modular_col - (cols % modular_col));
       if (event_image.width() < (width + npixels * part_image.pixel_width()))  npixels -= modular_col;
       cols += npixels;
       width += part_image.pixel_width() * npixels;
       if (npixels > 0) {
     // If expanded, make sure it won't go across event_image boundary
     if ( (min_x + width) > event_image.max_x() ) {
       LARCV_DEBUG() << "X: " << min_x << " => " << min_x + width
                << " exceeds event boundary " << event_image.max_x() << std::endl;
       min_x = event_image.max_x() - width;
     } else if (min_x < event_image.min_x()) {
       LARCV_DEBUG() << "X: " << min_x << " => " << min_x + width
                << " exceeds event boundary " << event_image.min_x() << std::endl;
       min_x = event_image.min_x();
     }
       }
     }
     if (modular_row > 1 && rows % modular_row) {
       int npixels = (modular_row - (rows % modular_row));
       if (event_image.height() < (height + npixels * part_image.pixel_height()))  npixels -= modular_row;
       rows += npixels;
       height += part_image.pixel_height() * npixels;
       if (npixels > 0) {
     // If expanded, make sure it won't go across event_image boundary
     if ( (max_y - height) < event_image.min_y() ) {
       LARCV_DEBUG() << "Y: " << max_y - height << " => " << max_y
                << " exceeds event boundary " << event_image.min_y() << std::endl;
       max_y = event_image.min_y() + height;
     } else if (max_y > event_image.max_y()) {
       LARCV_DEBUG() << "Y: " << max_y - height << " => " << max_y
                << " exceeds event boundary " << event_image.max_y() << std::endl;
       max_y = event_image.max_y();
     }
       }
     }
     LARCV_INFO() << "Creating ImageMeta Width=" << width
          << " Height=" << height
          << " NRows=" << rows / modular_row
          << " NCols=" << cols / modular_col
          << " Origin @ (" << min_x << "," << max_y << ")" << std::endl;
     larcv::ImageMeta res(width, height,
              rows / modular_row, cols / modular_col,
              min_x, max_y,
              part_image.plane());
     LARCV_DEBUG() << "Event image   " << event_image.dump();
     LARCV_DEBUG() << "After format  " << res.dump();
     /*
     res = event_image.overlap(res);
     LARCV_DEBUG() << "After overlap " << res.dump();
     */
     return res;
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaMCROI::initialize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 66 of file SuperaMCROI.cxx.
References larcv::SuperaBase::initialize().
Referenced by larcv::SuperaMCPCluster::initialize(), and ~SuperaMCROI().
   {
     SuperaBase::initialize();
   }
is()
bool larcv::SuperaBase::is (const std::string question) const virtual inherited
Reimplemented from larcv::ProcessBase.
Reimplemented in larcv::SuperaChStatus.
Definition at line 83 of file SuperaBase.cxx.
Referenced by larcv::SuperaBase::~SuperaBase().
   {
     if(question == "Supera") return true;
     return false;
   }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &) inherited
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const inherited
Referenced by larcv::SuperaBase::~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const inherited
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const inherited
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const inherited
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const inherited
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const inherited
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v) inherited
Definition at line 121 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v) inherited
Definition at line 124 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v) inherited
Definition at line 127 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v) inherited
Definition at line 130 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v) inherited
Definition at line 133 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v) inherited
Definition at line 136 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v) inherited
Definition at line 139 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const inherited
Definition at line 18 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::SuperaBase::_empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), process(), and larcv::SuperaBase::~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MakeROI()
larcv::ROI larcv::SuperaMCROI::MakeROI (const supera::MCNode & node, const std::vector< supera::LArSimCh_t > & sch_v) const private
Definition at line 322 of file SuperaMCROI.cxx.
References _mcroi_maker, larcv::ROI::BB(), FormatMeta(), supera::MCNode::kMCShower, supera::MCNode::kMCTrack, supera::MCNode::kMCTruth, larcv::ROI::MCSTIndex(), supera::ImageMetaMaker::Meta(), supera::MCROIMaker::ParticleROI(), larcv::ROI::SetBB(), supera::MCNode::source_index, supera::MCNode::source_type, and larcv::SuperaBase::TimeOffset().
Referenced by process().
   {
     larcv::ROI res;
     if(node.source_type == supera::MCNode::SourceType_t::kMCTruth)
       throw larbys("MCTruth type cannot make ROI using MCROIMaker!");
     else if(node.source_type == supera::MCNode::SourceType_t::kMCTrack) {
       auto const& mctrack = LArData<supera::LArMCTrack_t>().at(node.source_index);
       if(sch_v.empty()) res = _mcroi_maker.ParticleROI(mctrack,TimeOffset());
       else res = _mcroi_maker.ParticleROI(mctrack,sch_v,TimeOffset());
       res.MCSTIndex(node.source_index);
     }
     else if(node.source_type == supera::MCNode::SourceType_t::kMCShower) {
       auto const& mcshower = LArData<supera::LArMCShower_t>().at(node.source_index);
       if(sch_v.empty()) res = _mcroi_maker.ParticleROI(mcshower,TimeOffset());
       else res = _mcroi_maker.ParticleROI(mcshower,sch_v,TimeOffset());
       res.MCSTIndex(node.source_index);
     }else
       throw larbys("Unexpected SourceType_t!");
     // format ROI
     std::vector<larcv::ImageMeta> bb_v;
     for(size_t plane=0; plane<res.BB().size(); ++plane) {
       auto const& part_meta  = res.BB().at(plane);
       auto const& event_meta = Meta().at(plane);
       bb_v.push_back(FormatMeta(part_meta,event_meta));
     }
     res.SetBB(bb_v);
     return res;
   }
Meta()
const std::vector< larcv::ImageMeta > & supera::ImageMetaMaker::Meta () const inherited
Definition at line 16 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::Meta(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaSimCh::process(), larcv::SuperaOpDigit::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), and process().
   {
     if(_meta_maker) return _meta_maker->Meta();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->Meta();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
MetaMakerPtr()
ImageMetaMakerBase* supera::ImageMetaMaker::MetaMakerPtr () inline inherited
Definition at line 51 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker.
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and process().
     { return _meta_maker; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OutROILabel()
const std::string& supera::ParamsROI::OutROILabel () const inline inherited
Definition at line 41 of file ParamsROI.h.
References supera::ParamsROI::_out_roi_producer.
Referenced by larcv::SuperaMCPCluster::process(), and process().
 { return _out_roi_producer;      }
ParticleTree()
const supera::MCParticleTree& larcv::SuperaMCROI::ParticleTree () const inline
Definition at line 61 of file SuperaMCROI.h.
References _mcpt.
Referenced by larcv::SuperaMCPCluster::process().
 { return _mcpt; }
process()
bool larcv::SuperaMCROI::process (IOManager & mgr) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 71 of file SuperaMCROI.cxx.
References _filter_min_cols, _filter_min_rows, _mcpt, _pass_origin, _roi2mcnode_vv, _roi_v, _store_g4_primary_roi, _store_g4_secondary_roi, _store_roi, larcv::ROI::BB(), FilterNode(), larcv::IOManager< T >::get_data(), supera::PulledPork3DSlicer::Is(), larcv::kINVALID_SIZE, supera::kLArSimCh_t, supera::MCNode::kMCTruth, larcv::kProductROI, LARCV_CRITICAL, LARCV_INFO, LARCV_NORMAL, larcv::SuperaBase::LArDataLabel(), MakeROI(), supera::ImageMetaMaker::Meta(), supera::ImageMetaMaker::MetaMakerPtr(), supera::ParamsROI::OutROILabel(), larcv::ROI::PdgCode(), larcv::SuperaBase::process(), larcv::SuperaBase::TimeOffset(), and UpdatePrimaryROI().
Referenced by larcv::SuperaMCPCluster::process(), and ~SuperaMCROI().
   {
     SuperaBase::process(mgr);
     if(supera::PulledPork3DSlicer::Is(supera::ImageMetaMaker::MetaMakerPtr())) {
       auto ptr = (supera::PulledPork3DSlicer*)(supera::ImageMetaMaker::MetaMakerPtr());
       ptr->ClearEventData();
       ptr->AddConstraint(LArData<supera::LArMCTruth_t>());
       ptr->GenerateMeta(LArData<supera::LArSimCh_t>(),TimeOffset());
     }
     auto const& meta_v = Meta();
     if(meta_v.empty()) {
       LARCV_CRITICAL() << "Meta not created!" << std::endl;
       throw larbys();
     }
     auto ev_roi = (EventROI*)(mgr.get_data(kProductROI,OutROILabel()));
     if(!ev_roi) {
       LARCV_CRITICAL() << "Output roi could not be created!" << std::endl;
       throw larbys();
     }
     if(!(ev_roi->ROIArray().empty())) {
       LARCV_CRITICAL() << "Output roi array not empty!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << "Running MCParticleTree::Register" << std::endl;
     _mcpt.Register(LArData<supera::LArMCTruth_t>(),
            LArData<supera::LArMCTrack_t>(),
            LArData<supera::LArMCShower_t>());
     auto primary_v = _mcpt.PrimaryArray();
     LARCV_INFO() << "Found " << primary_v.size() << " primary particles" << std::endl;
     std::vector<supera::LArSimCh_t> empty_sch_v;
     _roi_v.clear();
     _roi2mcnode_vv.clear();
     for(size_t primary_idx = 0; primary_idx < primary_v.size(); ++primary_idx) {
       auto& primary = primary_v[primary_idx];
       // filter out primary of certain origin, if specified
       if(_pass_origin && primary.origin != _pass_origin) {
     LARCV_INFO() << "Skipping MCTruth primary " << primary_idx
              << " (origin type " << primary.origin
              << " PDG " << primary.pdg
              << ") with " << primary.daughter_v.size() << " children"
              << std::endl;
     continue;
       }
       if(primary.source_type != supera::MCNode::SourceType_t::kMCTruth) {
     if(!FilterNode(primary)) {
       LARCV_INFO() << "Skipping a non-MCTruth primary (TrackID " << primary.track_id
                << " Origin " << primary.origin
                << " PDG " << primary.pdg
                << ") due to FilterNode()" << std::endl;
       continue;
     }
     if(LArDataLabel(supera::LArDataType_t::kLArSimCh_t).empty())
       primary.roi = MakeROI(primary,empty_sch_v);
     else
       primary.roi = MakeROI(primary,LArData<supera::LArSimCh_t>());
       }
       LARCV_INFO() << "Analyzing primary " << primary_idx << " PDG " << primary.roi.PdgCode()
            << " Origin " << primary.origin
            << " PDG << " << primary.pdg
            << " with " << primary.daughter_v.size() << " children" << std::endl;
       std::vector<larcv::ROI> sec_roi_v;
       std::vector<size_t> sec_idx_v;
       for(size_t daughter_idx=0; daughter_idx<primary.daughter_v.size(); ++daughter_idx) {
     auto const& daughter = primary.daughter_v[daughter_idx];
     if(!FilterNode(daughter)) {
       LARCV_INFO() << "Skipping a daughter " << daughter_idx
                << " (TrackID " << daughter.track_id
                << " Origin " << daughter.origin
                << " PDG " << daughter.pdg
                << ") due to FilterNode()" << std::endl;
       continue;
     }
     larcv::ROI roi;
     try {
       if(LArDataLabel(supera::LArDataType_t::kLArSimCh_t).empty())
         roi = MakeROI(daughter,empty_sch_v);
       else
         roi = MakeROI(daughter,LArData<supera::LArSimCh_t>());
     }catch(const larcv::larbys& err) {
       LARCV_NORMAL() << "Skipping a secondary (PDG,TrackID) = ("
              << daughter.pdg << "," << daughter.track_id << ") as it could not be turned into ROI" << std::endl;
       continue;
     }
     if( (_filter_min_rows>0 || _filter_min_cols>0) && roi.BB().empty() ) {
       LARCV_INFO() << "Skipping a daughter " << daughter_idx
                << " (TrackID " << daughter.track_id
                << " Origin " << daughter.origin
                << " PDG " << roi.PdgCode() << ") due to the size of ROI" << std::endl;
       continue;
     }
     bool skip=false;
     for(auto const& bb : roi.BB()) {
       if(bb.rows() <= _filter_min_rows && bb.cols() <= _filter_min_cols) {
         LARCV_INFO() << "Skipping a daughter " << daughter_idx
              << " (TrackID " << daughter.track_id
              << " Origin " << daughter.origin
              << " PDG " << roi.PdgCode() << ") due to the size of ROI "
              << "(row,col) = (" << bb.rows() << "," << bb.cols() << ")"
              << std::endl;
         skip=true;
         break;
       }
     }
     if(skip) continue;
     LARCV_INFO() << "Registering a daughter " << daughter_idx
              << " (TrackID " << daughter.track_id
              << " Origin " << daughter.origin
              << " PDG " << roi.PdgCode() << ")" << std::endl;
     sec_roi_v.push_back(roi);
     sec_idx_v.push_back(daughter_idx);
       }
       LARCV_INFO() << "Updating primary ROI with " << sec_roi_v.size() << " children" << std::endl;
       UpdatePrimaryROI(primary.roi, sec_roi_v);
       if( (_filter_min_rows>0 || _filter_min_cols>0) && primary.roi.BB().empty() )
     continue;
       bool skip=false;
       for(auto const& bb : primary.roi.BB()) {
     if(bb.rows() >= _filter_min_rows && bb.cols() >= _filter_min_cols)
       continue;
     skip=true;
     break;
       }
       if(skip) continue;
       std::vector<std::pair<size_t,size_t> > roi2mcnode_v;
       roi2mcnode_v.clear();
       //
       // Register primary ROI
       //
       LARCV_INFO() << "Storing primary ROI (PDG " << primary.roi.PdgCode()
            << " Shape " << primary.roi.Shape()
            << " MCTIndex " << primary.roi.MCTIndex()
            << " MCSTIndex) " << primary.roi.MCSTIndex()
            << std::endl;
       _roi_v.push_back(primary.roi);
       // Record incorporated mcnode
       roi2mcnode_v.emplace_back(primary_idx, larcv::kINVALID_SIZE);
       for(size_t daughter_idx=0; daughter_idx<sec_roi_v.size(); ++daughter_idx) {
     auto const& secondary_idx = sec_idx_v[daughter_idx];
     auto const& secondary_roi = sec_roi_v[daughter_idx];
     if( (_store_g4_primary_roi && secondary_roi.TrackID() == secondary_roi.ParentTrackID())
         ||
         (_store_g4_secondary_roi && secondary_roi.TrackID() != secondary_roi.ParentTrackID())
         )
       roi2mcnode_v.emplace_back(primary_idx,secondary_idx);
       }
       for(size_t daughter_idx=0; daughter_idx<sec_roi_v.size(); ++daughter_idx) {
     auto const& daughter_roi = sec_roi_v[daughter_idx];
     LARCV_INFO() << "    Associated secondary (PDG " << daughter_roi.PdgCode()
              << " Shape " << daughter_roi.Shape()
              << " MCTIndex " << daughter_roi.MCTIndex()
              << " MCSTIndex) " << daughter_roi.MCSTIndex()
              << std::endl;
       }
       _roi2mcnode_vv.emplace_back(std::move(roi2mcnode_v));
       //
       // Register secondary ROI
       //
       roi2mcnode_v.clear();
       for(size_t daughter_idx=0; daughter_idx<sec_roi_v.size(); ++daughter_idx) {
     auto const& secondary_idx = sec_idx_v[daughter_idx];
     auto& secondary_roi = sec_roi_v[daughter_idx];
     if( (_store_g4_primary_roi && secondary_roi.TrackID() == secondary_roi.ParentTrackID())
         ||
         (_store_g4_secondary_roi && secondary_roi.TrackID() != secondary_roi.ParentTrackID())
         )
       {
         LARCV_INFO() << "Storing secondary ROI (PDG " << secondary_roi.PdgCode()
              << " Shape " << secondary_roi.Shape()
              << " MCTIndex " << secondary_roi.MCTIndex()
              << " MCSTIndex) " << secondary_roi.MCSTIndex()
              << std::endl;
         roi2mcnode_v.clear();
         roi2mcnode_v.emplace_back(primary_idx,secondary_idx);
         _roi_v.emplace_back(std::move(secondary_roi));
         _roi2mcnode_vv.emplace_back(std::move(roi2mcnode_v));
       }
       }
     }
     if(_store_roi)
       ev_roi->Emplace(std::move(_roi_v));
     return true;
   }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name) inherited
Definition at line 15 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::larcv_base::name().
Referenced by larcv::SuperaBase::configure(), and larcv::SuperaBase::~SuperaBase().
   { _data_request_m[type]=name; }
ROI2MCNode() [1/2]
const std::vector< std::pair< size_t, size_t > > & larcv::SuperaMCROI::ROI2MCNode (int roi_index) const
Definition at line 18 of file SuperaMCROI.cxx.
References _roi2mcnode_vv.
   {
     if(roi_index >= (int)(_roi2mcnode_vv.size()))
       throw larbys("Invalid ROI index requested");
     return _roi2mcnode_vv[roi_index];
   }
ROI2MCNode() [2/2]
const std::vector<std::vector<std::pair<size_t,size_t> > >& larcv::SuperaMCROI::ROI2MCNode () const inline
Definition at line 59 of file SuperaMCROI.h.
References _roi2mcnode_vv.
Referenced by larcv::SuperaMCPCluster::process(), and StoreG4PrimaryROI().
 { return _roi2mcnode_vv; }
RowCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::RowCompressionFactor () const inherited
Definition at line 26 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::RowCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->RowCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->RowCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
StoreG4PrimaryROI()
bool larcv::SuperaMCROI::StoreG4PrimaryROI () const inline
Definition at line 54 of file SuperaMCROI.h.
References _store_g4_primary_roi, and ROI2MCNode().
 { return _store_g4_primary_roi; }
StoreG4SecondaryROI()
bool larcv::SuperaMCROI::StoreG4SecondaryROI () const inline
Definition at line 52 of file SuperaMCROI.h.
References _store_g4_secondary_roi.
 { return _store_g4_secondary_roi; }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline inherited
Definition at line 64 of file SuperaBase.h.
References larcv::SuperaBase::_time_offset, and larcv::SuperaBase::ClearEventData().
Referenced by MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and process().
 { return _time_offset; }
UpdatePrimaryROI()
void larcv::SuperaMCROI::UpdatePrimaryROI (larcv::ROI & pri_roi, std::vector< larcv::ROI > & sec_roi_v) const private
Definition at line 353 of file SuperaMCROI.cxx.
References larcv::ROI::BB(), larcv::ROI::EnergyDeposit(), LARCV_DEBUG, LARCV_INFO, larcv::ROI::MCTIndex(), and larcv::ROI::SetBB().
Referenced by process().
   {
     LARCV_DEBUG() << "start" << std::endl;
     std::map<larcv::PlaneID_t, larcv::ImageMeta> sum_roi_m;
     double energy_deposit = 0;
     // register primary BB
     for (auto const& bb : pri_roi.BB()) {
       if(pri_roi.EnergyDeposit()>0) energy_deposit += pri_roi.EnergyDeposit();
       if (!(bb.height() > 1 && bb.width() > 1)) continue;
       auto iter = sum_roi_m.find(bb.plane());
       if (iter == sum_roi_m.end())
     sum_roi_m[bb.plane()] = bb;
       else
     (*iter).second = (*iter).second.inclusive(bb);
     }
     // Next, secondary BB
     for (auto& sec_roi : sec_roi_v) {
       energy_deposit += sec_roi.EnergyDeposit();
       // loop over plane-by-plane ImageMeta
       for (auto const& bb : sec_roi.BB()) {
     if (!(bb.height() > 1 && bb.width() > 1)) continue;
     auto iter = sum_roi_m.find(bb.plane());
     if (iter == sum_roi_m.end())
       sum_roi_m[bb.plane()] = bb;
     else
       (*iter).second = (*iter).second.inclusive(bb);
       }
       sec_roi.MCTIndex(pri_roi.MCTIndex());
     }
     std::vector<larcv::ImageMeta> bb_v;
     bb_v.reserve(sum_roi_m.size());
     for (auto const& plane_roi : sum_roi_m) {
       if(bb_v.size() <= plane_roi.first)
     bb_v.resize(plane_roi.first+1);
       bb_v[plane_roi.first] = plane_roi.second;
       LARCV_INFO() << "Updated primary ROI plane " << plane_roi.first << " ... " << plane_roi.second.dump();
     }
     pri_roi.EnergyDeposit(energy_deposit);
     pri_roi.SetBB(bb_v);
   }
Member Data Documentation
_filter_min_cols
size_t larcv::SuperaMCROI::_filter_min_cols private
Definition at line 84 of file SuperaMCROI.h.
Referenced by configure(), and process().
_filter_min_edep
std::vector<double> larcv::SuperaMCROI::_filter_min_edep private
Definition at line 76 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_filter_min_einit
std::vector<double> larcv::SuperaMCROI::_filter_min_einit private
Definition at line 75 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_filter_min_rows
size_t larcv::SuperaMCROI::_filter_min_rows private
Definition at line 85 of file SuperaMCROI.h.
Referenced by configure(), and process().
_filter_pdg
std::vector<int> larcv::SuperaMCROI::_filter_pdg private
Definition at line 74 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_mcpt
supera::MCParticleTree larcv::SuperaMCROI::_mcpt private
Definition at line 69 of file SuperaMCROI.h.
Referenced by configure(), ParticleTree(), and process().
_mcroi_maker
supera::MCROIMaker larcv::SuperaMCROI::_mcroi_maker private
Definition at line 70 of file SuperaMCROI.h.
Referenced by configure(), and MakeROI().
_pass_origin
unsigned short larcv::SuperaMCROI::_pass_origin private
Definition at line 73 of file SuperaMCROI.h.
Referenced by configure(), FilterNode(), and process().
_roi2mcnode_vv
std::vector<std::vector<std::pair<size_t,size_t> > > larcv::SuperaMCROI::_roi2mcnode_vv private
Definition at line 71 of file SuperaMCROI.h.
Referenced by process(), and ROI2MCNode().
_roi_v
std::vector<larcv::ROI> larcv::SuperaMCROI::_roi_v private
Definition at line 68 of file SuperaMCROI.h.
Referenced by process().
_shower_min_edep
double larcv::SuperaMCROI::_shower_min_edep private
Definition at line 79 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_shower_min_einit
double larcv::SuperaMCROI::_shower_min_einit private
Definition at line 78 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_store_g4_primary_roi
bool larcv::SuperaMCROI::_store_g4_primary_roi private
Definition at line 66 of file SuperaMCROI.h.
Referenced by configure(), process(), and StoreG4PrimaryROI().
_store_g4_secondary_roi
bool larcv::SuperaMCROI::_store_g4_secondary_roi private
Definition at line 67 of file SuperaMCROI.h.
Referenced by configure(), process(), and StoreG4SecondaryROI().
_store_roi
bool larcv::SuperaMCROI::_store_roi private
Definition at line 65 of file SuperaMCROI.h.
Referenced by configure(), and process().
_track_min_edep
double larcv::SuperaMCROI::_track_min_edep private
Definition at line 82 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
_track_min_einit
double larcv::SuperaMCROI::_track_min_einit private
Definition at line 81 of file SuperaMCROI.h.
Referenced by configure(), and FilterNode().
The documentation for this class was generated from the following files:
SuperaMCROI.h
SuperaMCROI.cxx