LArCV: larcv::ImageFromPixel2D Class Reference
larcv::ImageFromPixel2D Class Reference
#include <ImageFromPixel2D.h>
Public Member Functions
ImageFromPixel2D (const std::string name="ImageFromPixel2D")
Default constructor.
~ImageFromPixel2D ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Types
enum PIType_t { PIType_t::kPITypeFixedPI, PIType_t::kPITypeInputImage, PIType_t::kPITypeClusterIndex, PIType_t::kPITypeUndefined }
Private Attributes
float _fixed_pi
PIType_t _type_pi
std::string _pixel_producer
std::string _image_producer
std::string _output_producer
Detailed Description
Definition at line 26 of file ImageFromPixel2D.h.
Member Enumeration Documentation
PIType_t
enum larcv::ImageFromPixel2D::PIType_t strong private
Enumerator
kPITypeFixedPI
kPITypeInputImage
kPITypeClusterIndex
kPITypeUndefined
Definition at line 46 of file ImageFromPixel2D.h.
{
       kPITypeFixedPI,
       kPITypeInputImage,
       kPITypeClusterIndex,
       kPITypeUndefined
     };
Constructor & Destructor Documentation
ImageFromPixel2D()
larcv::ImageFromPixel2D::ImageFromPixel2D (const std::string name = "ImageFromPixel2D")
Default constructor.
Definition at line 11 of file ImageFromPixel2D.cxx.
Referenced by larcv::ImageFromPixel2DProcessFactory::create().
     : ProcessBase(name)
   {}
~ImageFromPixel2D()
larcv::ImageFromPixel2D::~ImageFromPixel2D () inline
Default destructor.
Definition at line 34 of file ImageFromPixel2D.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ImageFromPixel2D::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file ImageFromPixel2D.cxx.
References _fixed_pi, _image_producer, _output_producer, _pixel_producer, _type_pi, larcv::PSet::get(), and kPITypeFixedPI.
Referenced by ~ImageFromPixel2D().
   {
     _pixel_producer  = cfg.get<std::string>("PixelProducer");
     _image_producer  = cfg.get<std::string>("ImageProducer");
     _output_producer = cfg.get<std::string>("OutputProducer");
     _type_pi  = (PIType_t)(cfg.get<unsigned short>("PIType",(unsigned short)(PIType_t::kPITypeFixedPI)));
     _fixed_pi = cfg.get<float>("FixedPI",100);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ImageFromPixel2D::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 104 of file ImageFromPixel2D.cxx.
Referenced by ~ImageFromPixel2D().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ImageFromPixel2D::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 24 of file ImageFromPixel2D.cxx.
Referenced by ~ImageFromPixel2D().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ImageFromPixel2D::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 27 of file ImageFromPixel2D.cxx.
References _fixed_pi, _image_producer, _output_producer, _pixel_producer, _type_pi, larcv::IOManager< T >::get_data(), kPITypeClusterIndex, kPITypeFixedPI, kPITypeInputImage, kPITypeUndefined, larcv::kProductImage2D, larcv::kProductPixel2D, LARCV_CRITICAL, larcv::Image2D::paint(), and larcv::Image2D::set_pixel().
Referenced by ~ImageFromPixel2D().
   {
     auto ev_pixel     = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pixel_producer));
     auto ev_in_image  = (EventImage2D*)(mgr.get_data(kProductImage2D,_image_producer));
     auto ev_out_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_output_producer));
     if(!ev_pixel) {
       LARCV_CRITICAL() << "EventPixel2D not found by name " << _pixel_producer << std::endl;
       throw larbys();
     }
     if(!ev_in_image) {
       LARCV_CRITICAL() << "EventImage2D not found by name " << _image_producer << std::endl;
       throw larbys();
     }
     if(!ev_out_image) {
       LARCV_CRITICAL() << "EventImage2D could not be craeted by name " << _output_producer << std::endl;
       throw larbys();
     }
     if(ev_out_image->Image2DArray().size()) {
       LARCV_CRITICAL() << "EventImage2D by name " << _output_producer << " (output) is not empty!" << std::endl;
       throw larbys();
     }
     auto const& pcluster_m = ev_pixel->Pixel2DArray();
     auto const& meta_m     = ev_pixel->MetaArray();
     auto const& image_v    = ev_in_image->Image2DArray();
     for(size_t plane=0; plane<image_v.size(); plane++) {
       auto const& ref_meta = image_v.at(plane).meta();
       auto const& ref_data = image_v.at(plane).as_vector();
       Image2D out_image(ref_meta);
       out_image.paint(0.);
       auto const& pcluster_iter = pcluster_m.find(plane);
       if(pcluster_iter == pcluster_m.end()) {
     ev_out_image->Emplace(std::move(out_image));
     continue;
       }
       auto meta_iter = meta_m.find(plane);
       if(meta_iter != meta_m.end() && ref_meta != (*meta_iter).second) {
     LARCV_CRITICAL() << "Found non-compatible image meta!" << std::endl
              << "      Cluster: " << (*meta_iter).second.dump()
              << "      Ref    : " << ref_meta.dump();
     throw larbys();
       }
       auto const& pcluster = (*pcluster_iter).second;
       //std::cout<<ref_meta.dump()<<std::endl;
       for(auto const& pixel2d : pcluster) {
     //std::cout<<pixel2d.X() << " " << pixel2d.Y() << " ... " << pixel2d.Intensity() << std::endl;
     //out_image.set_pixel(pixel2d.Y(), pixel2d.X(),100);
     float val=_fixed_pi;
     size_t index = (pixel2d.X() * ref_meta.rows() + pixel2d.Y());
     switch(_type_pi) {
     case PIType_t::kPITypeFixedPI:
       break;
     case PIType_t::kPITypeInputImage:
       val = ref_data[index];
       break;
     case PIType_t::kPITypeClusterIndex:
       LARCV_CRITICAL() << "kPITypeClusterIndex not unsupported!" <<std::endl;
       throw larbys();
       break;
     case PIType_t::kPITypeUndefined:
       val = pixel2d.Intensity();
       break;
     }
     //std::cout<<"Filling " << pixel2d.X() << "  " << pixel2d.Y() << std::endl;
     out_image.set_pixel( (pixel2d.X() * ref_meta.rows() + pixel2d.Y()),val);
       }
       ev_out_image->Emplace(std::move(out_image));
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_fixed_pi
float larcv::ImageFromPixel2D::_fixed_pi private
Definition at line 52 of file ImageFromPixel2D.h.
Referenced by configure(), and process().
_image_producer
std::string larcv::ImageFromPixel2D::_image_producer private
Definition at line 55 of file ImageFromPixel2D.h.
Referenced by configure(), and process().
_output_producer
std::string larcv::ImageFromPixel2D::_output_producer private
Definition at line 56 of file ImageFromPixel2D.h.
Referenced by configure(), and process().
_pixel_producer
std::string larcv::ImageFromPixel2D::_pixel_producer private
Definition at line 54 of file ImageFromPixel2D.h.
Referenced by configure(), and process().
_type_pi
PIType_t larcv::ImageFromPixel2D::_type_pi private
Definition at line 53 of file ImageFromPixel2D.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ImageFromPixel2D.h
ImageFromPixel2D.cxx