LArCV: larcv::LArbysRecoHolder Class Reference
larcv::LArbysRecoHolder Class Reference
#include <LArbysRecoHolder.h>
Public Member Functions
LArbysRecoHolder ()
~LArbysRecoHolder ()
void Configure (const PSet &pset)
void Initialize ()
void SetMeta (const std::vector< Image2D > &adc_img_v)
void FilterMatches ()
void ShapeData (const larocv::ImageClusterManager &mgr)
void Filter ()
void SetMatches (std::vector< int > &&vtxid_match_v)
std::vector< std::vector< std::pair< size_t, size_t > > > Match (size_t vtx_id, const std::vector< cv::Mat > &adc_cvimg_v, bool stort=true)
void ResetOutput ()
void StoreEvent (size_t run, size_t subrun, size_t event, size_t entry)
bool WriteOut (TFile *fout)
void Reset ()
void Write ()
const larocv::VertexAnalysis & ana ()
const std::vector< const larocv::data::Vertex3D * > Verticies ()
const larocv::data::Vertex3D * Vertex (size_t vertexid)
const std::vector< std::vector< std::vector< const larocv::data::ParticleCluster * > > > & VertexPlaneParticles ()
const std::vector< std::vector< const larocv::data::ParticleCluster * > > & PlaneParticles (size_t vertexid)
const std::vector< const larocv::data::ParticleCluster * > & Particles (size_t vertexid, size_t planeid)
const larocv::data::ParticleCluster * Particle (size_t vertexid, size_t planeid, size_t particleid)
const std::vector< std::vector< std::vector< const larocv::data::TrackClusterCompound * > > > & VertexPlaneTracks ()
const std::vector< std::vector< const larocv::data::TrackClusterCompound * > > & PlaneTracks (size_t vertexid)
const std::vector< const larocv::data::TrackClusterCompound * > & Tracks (size_t vertexid, size_t planeid)
const larocv::data::TrackClusterCompound * Track (size_t vertexid, size_t planeid, size_t trackid)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _output_module_name
size_t _output_module_offset
bool _require_two_multiplicity
bool _require_fiducial
float _match_coverage
float _match_particles_per_plane
float _match_min_number
bool _match_check_type
bool _match_weight_by_size
larocv::VertexAnalysis _vtx_ana
std::vector< const larocv::data::Vertex3D * > _vertex_ptr_v
std::vector< std::vector< std::vector< const larocv::data::ParticleCluster * > > > _particle_cluster_ptr_vvv
std::vector< std::vector< std::vector< const larocv::data::TrackClusterCompound * > > > _track_comp_ptr_vvv
std::vector< int > _matched_v
TTree * _out_tree
uint _run
uint _subrun
uint _event
uint _entry
LArOCVSerial * _larocvserial
Detailed Description
Definition at line 30 of file LArbysRecoHolder.h.
Constructor & Destructor Documentation
LArbysRecoHolder()
larcv::LArbysRecoHolder::LArbysRecoHolder () inline
Definition at line 34 of file LArbysRecoHolder.h.
                        :
       _vtx_ana(),
       _out_tree(nullptr),
       _larocvserial(nullptr)
     {  Reset(); }
~LArbysRecoHolder()
larcv::LArbysRecoHolder::~LArbysRecoHolder () inline
Definition at line 40 of file LArbysRecoHolder.h.
 {}
Member Function Documentation
ana()
const larocv::VertexAnalysis& larcv::LArbysRecoHolder::ana () inline
Definition at line 71 of file LArbysRecoHolder.h.
     { return _vtx_ana; }
Configure()
void larcv::LArbysRecoHolder::Configure (const PSet & pset)
Definition at line 185 of file LArbysRecoHolder.cxx.
References larcv::PSet::get(), larcv::kINVALID_SIZE, and set_verbosity().
{
     this->set_verbosity((msg::Level_t)pset.get<int>("Verbosity"));
     _require_two_multiplicity = false;
     _require_fiducial = false;
     _match_coverage            = pset.get<float>("MatchCoverage",0.5);
     _match_particles_per_plane = pset.get<float>("MatchParticlesPerPlane",2);
     _match_min_number          = pset.get<float>("MatchMinimumNumber",2);
     _match_check_type          = pset.get<bool>("MatchCheckType",true);
     _match_weight_by_size      = pset.get<bool>("MatchWeightBySize",false);
     _output_module_name   = pset.get<std::string>("OutputModuleName");
     _output_module_offset = pset.get<size_t>("OutputModuleOffset",kINVALID_SIZE);
     return;
   }
Filter()
void larcv::LArbysRecoHolder::Filter ()
Definition at line 116 of file LArbysRecoHolder.cxx.
References LARCV_DEBUG.
{
     std::vector<const larocv::data::Vertex3D*> vertex_ptr_v;
     std::vector<std::vector<std::vector<const larocv::data::ParticleCluster*> > > particle_cluster_ptr_vvv;
     std::vector<std::vector<std::vector<const larocv::data::TrackClusterCompound*> > > track_comp_ptr_vvv;
     for(size_t vertexid=0; vertexid<this->Verticies().size(); ++vertexid) {
       if (_require_two_multiplicity) {
     auto multiplicity=_vtx_ana.RequireParticleCount(this->PlaneParticles(vertexid),2,2);
     if (!multiplicity) {
       LARCV_DEBUG() << "Filtered id " << vertexid << " @ multiplicity" << std::endl;
       continue;
     }
       }
       if (_require_fiducial) {
     auto fiduciality=_vtx_ana.CheckFiducial(*this->Vertex(vertexid));
     if (!fiduciality) {
       LARCV_DEBUG() << "Filtered id " << vertexid << " @ fiduciality" << std::endl;
       continue;
     }
       }
       vertex_ptr_v.emplace_back(this->Vertex(vertexid));
       particle_cluster_ptr_vvv.emplace_back(this->PlaneParticles(vertexid));
       track_comp_ptr_vvv.emplace_back(this->PlaneTracks(vertexid));
     }
     LARCV_DEBUG() <<"Filtered "<<this->Verticies().size()<<" to "<<vertex_ptr_v.size()<<std::endl;
     std::swap(vertex_ptr_v,            _vertex_ptr_v);
     std::swap(particle_cluster_ptr_vvv,_particle_cluster_ptr_vvv);
     std::swap(track_comp_ptr_vvv,      _track_comp_ptr_vvv);
   }
FilterMatches()
void larcv::LArbysRecoHolder::FilterMatches ()
Definition at line 29 of file LArbysRecoHolder.cxx.
References LARCV_DEBUG.
{
     std::vector<const larocv::data::Vertex3D*> vertex_ptr_v;
     std::vector<std::vector<std::vector<const larocv::data::ParticleCluster*> > > particle_cluster_ptr_vvv;
     std::vector<std::vector<std::vector<const larocv::data::TrackClusterCompound*> > > track_comp_ptr_vvv;
     auto& match_pvvv = _larocvserial->_match_pvvv;
     for(size_t vertexid=0; vertexid<this->Verticies().size(); ++vertexid) {
       if (match_pvvv[vertexid].empty()) continue;
       vertex_ptr_v.emplace_back(this->Vertex(vertexid));
       particle_cluster_ptr_vvv.emplace_back(this->PlaneParticles(vertexid));
       track_comp_ptr_vvv.emplace_back(this->PlaneTracks(vertexid));
     }
     LARCV_DEBUG() <<"Filtered "<<this->Verticies().size()<<" to "<<vertex_ptr_v.size()<<std::endl;
     std::swap(vertex_ptr_v,            _vertex_ptr_v);
     std::swap(particle_cluster_ptr_vvv,_particle_cluster_ptr_vvv);
     std::swap(track_comp_ptr_vvv,      _track_comp_ptr_vvv);
   }
Initialize()
void larcv::LArbysRecoHolder::Initialize ()
Definition at line 206 of file LArbysRecoHolder.cxx.
References larcv::LArOCVSerial::LArOCVSerial().
   {
     _out_tree = new TTree("RecoTree","");
     _out_tree->Branch("run"   ,&_run   ,"run/i");
     _out_tree->Branch("subrun",&_subrun,"subrun/i");
     _out_tree->Branch("event" ,&_event ,"event/i");
     _out_tree->Branch("entry" ,&_entry ,"entry/i");
     _larocvserial = new LArOCVSerial();
     _out_tree->Branch("AlgoData" ,&_larocvserial);
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Match()
std::vector< std::vector< std::pair< size_t, size_t > > > larcv::LArbysRecoHolder::Match (size_t vtx_id, const std::vector< cv::Mat > & adc_cvimg_v, bool stort = true)
Definition at line 57 of file LArbysRecoHolder.cxx.
References LARCV_DEBUG.
{
     LARCV_DEBUG() << "@ vertex id " << vtx_id << " requested coverage " << _match_coverage << " & "
           << _match_particles_per_plane << " particles per plane & "
           << _match_min_number << " min number of matches " << std::endl;
     auto match_vv = _vtx_ana.MatchClusters(this->PlaneParticles(vtx_id), // particles per plane
                        adc_cvimg_v,                  // adc cv image
                        _match_coverage,              // required coverage
                        _match_particles_per_plane,   // requires # particles per plane
                        _match_min_number,            // min number of matches
                        _match_check_type,            // ensure particle type is same
                        _match_weight_by_size);       // weight match by particle n pixels
     LARCV_DEBUG() << "returned " << match_vv.size() << " matches" << std::endl;
     if (sort) {
       // Sort the match so that the tracks come first
       std::vector<std::vector<std::pair<size_t,size_t> > > match_temp_vv;
       //put the tracks first
       for( auto match_v : match_vv ) {
     auto& plane0     = match_v.front().first;
     auto& id0        = match_v.front().second;
     const auto& par0 = *(this->Particle(vtx_id,plane0,id0));
     auto partype=par0.type;
     if (partype==larocv::data::ParticleType_t::kTrack) {
       match_temp_vv.push_back(match_v);
     }
       }
       // Put the showers second
       for( auto match_v : match_vv ) {
     auto& plane0     = match_v.front().first;
     auto& id0        = match_v.front().second;
     const auto& par0 = *(this->Particle(vtx_id,plane0,id0));
     auto partype=par0.type;
     if (partype==larocv::data::ParticleType_t::kShower) {
       match_temp_vv.push_back(match_v);
     }
       }
       if(match_vv.size() != match_temp_vv.size())
     throw larbys("Invalid match_vv ordering");
       std::swap(match_vv,match_temp_vv);
     }
     auto& match_pvvv = _larocvserial->_match_pvvv;
     if (vtx_id >= match_pvvv.size())
       match_pvvv.resize(vtx_id+1);
     match_pvvv[vtx_id] = match_vv;
     return match_vv;
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
Particle()
const larocv::data::ParticleCluster* larcv::LArbysRecoHolder::Particle (size_t vertexid, size_t planeid, size_t particleid) inline
Definition at line 99 of file LArbysRecoHolder.h.
     { return _particle_cluster_ptr_vvv[vertexid][planeid][particleid]; }
Particles()
const std::vector<const larocv::data::ParticleCluster*>& larcv::LArbysRecoHolder::Particles (size_t vertexid, size_t planeid) inline
Definition at line 95 of file LArbysRecoHolder.h.
     { return _particle_cluster_ptr_vvv[vertexid][planeid]; }
PlaneParticles()
const std::vector<std::vector<const larocv::data::ParticleCluster*> >& larcv::LArbysRecoHolder::PlaneParticles (size_t vertexid) inline
Definition at line 91 of file LArbysRecoHolder.h.
     { return _particle_cluster_ptr_vvv[vertexid]; }
PlaneTracks()
const std::vector<std::vector<const larocv::data::TrackClusterCompound*> >& larcv::LArbysRecoHolder::PlaneTracks (size_t vertexid) inline
Definition at line 110 of file LArbysRecoHolder.h.
     { return _track_comp_ptr_vvv[vertexid]; }
Reset()
void larcv::LArbysRecoHolder::Reset ()
Definition at line 151 of file LArbysRecoHolder.cxx.
References larcv::LArOCVSerial::_matched_v, and LARCV_DEBUG.
{
     LARCV_DEBUG() << "Reset pointers" << std::endl;
     _vertex_ptr_v.clear();
     _particle_cluster_ptr_vvv.clear();
     _track_comp_ptr_vvv.clear();
     _matched_v.clear();
     LARCV_DEBUG() << "done." << std::endl;
   }
ResetOutput()
void larcv::LArbysRecoHolder::ResetOutput ()
Definition at line 161 of file LArbysRecoHolder.cxx.
References larcv::kINVALID_INT, and LARCV_DEBUG.
{
     LARCV_DEBUG() << "Reset output copies" << std::endl;
     _larocvserial->Clear();
     _run   = kINVALID_INT;
     _subrun= kINVALID_INT;
     _event = kINVALID_INT;
     _entry = kINVALID_INT;
     this->Reset();
     LARCV_DEBUG() << "done." << std::endl;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetMatches()
void larcv::LArbysRecoHolder::SetMatches (std::vector< int > && vtxid_match_v)
Definition at line 51 of file LArbysRecoHolder.cxx.
References larcv::LArOCVSerial::_matched_v.
{
     _matched_v = std::move(vtxid_match_v);
     return;
   }
SetMeta()
void larcv::LArbysRecoHolder::SetMeta (const std::vector< Image2D > & adc_img_v)
Definition at line 19 of file LArbysRecoHolder.cxx.
{
     std::vector<ImageMeta> meta_v;
     meta_v.reserve(3);
     auto& meta_vv = _larocvserial->_meta_vv;
     for(const auto& adc_img : adc_img_v) meta_v.emplace_back(adc_img.meta());
     for (size_t vtxid=0; vtxid<this->Verticies().size(); ++vtxid)
       meta_vv.emplace_back(meta_v);
   }
ShapeData()
void larcv::LArbysRecoHolder::ShapeData (const larocv::ImageClusterManager & mgr)
Definition at line 218 of file LArbysRecoHolder.cxx.
References larcv::kINVALID_SIZE, LARCV_DEBUG, and LARCV_WARNING.
{
     const larocv::data::AlgoDataManager& data_mgr   = mgr.DataManager();
     const larocv::data::AlgoDataAssManager& ass_man = data_mgr.AssManager();
     auto output_module_id = data_mgr.ID(_output_module_name);
     if (output_module_id==kINVALID_SIZE)  {
       if(_output_module_name.empty()) {
     LARCV_WARNING() << "Empty algo name specified, nothing to do" << std::endl;
     return;
       }
       LARCV_WARNING() << "Invalid algmodule name (" << _output_module_name <<") specified" << std::endl;
       throw larbys();
     }
     const auto vtx3d_array = (larocv::data::Vertex3DArray*) data_mgr.Data(output_module_id, 0);
     const auto& vertex3d_v = vtx3d_array->as_vector();
     LARCV_DEBUG() << "Observed " << vertex3d_v.size() << " verticies" << std::endl;
     for(size_t vtxid=0;vtxid<vertex3d_v.size();++vtxid) {
       const auto& vtx3d = vertex3d_v[vtxid];
       LARCV_DEBUG() << "On vertex " << vtxid
             << " of type " << (uint) vtx3d.type
             << " @ " << &vtx3d << std::endl;
       LARCV_DEBUG() << "Current size " << _vertex_ptr_v.size() << std::endl;
       _vertex_ptr_v.push_back(&vtx3d);
       LARCV_DEBUG() << ".. now size  " << _vertex_ptr_v.size() << std::endl;
       std::vector<std::vector<const larocv::data::ParticleCluster* > > pcluster_vv;
       std::vector<std::vector<const larocv::data::TrackClusterCompound* > > tcluster_vv;
       pcluster_vv.resize(3);
       tcluster_vv.resize(3);
       for(size_t plane=0;plane<3;++plane) {
     auto& pcluster_v=pcluster_vv[plane];
     auto& tcluster_v=tcluster_vv[plane];
     auto output_module_id = data_mgr.ID(_output_module_name);
     const auto par_array = (larocv::data::ParticleClusterArray*)
       data_mgr.Data(output_module_id, plane+_output_module_offset);
     const auto comp_array = (larocv::data::TrackClusterCompoundArray*)
       data_mgr.Data(output_module_id, plane+_output_module_offset+3);
     auto par_ass_idx_v = ass_man.GetManyAss(vtx3d,par_array->ID());
     pcluster_v.resize(par_ass_idx_v.size());
     tcluster_v.resize(par_ass_idx_v.size());
     for(size_t ass_id=0;ass_id<par_ass_idx_v.size();++ass_id) {
       auto ass_idx = par_ass_idx_v[ass_id];
       if (ass_idx==kINVALID_SIZE) throw larbys("Invalid vertex->particle association detected");
       const auto& par = par_array->as_vector()[ass_idx];
       pcluster_v[ass_id] = &par;
       auto comp_ass_id = ass_man.GetOneAss(par,comp_array->ID());
       if (comp_ass_id==kINVALID_SIZE && par.type==larocv::data::ParticleType_t::kTrack) {
         throw larbys("Track particle with no track!");
       }
       else if (comp_ass_id==kINVALID_SIZE) {
         tcluster_v[ass_id] = nullptr;
         continue;
       }
       const auto& comp = comp_array->as_vector()[comp_ass_id];
       tcluster_v[ass_id] = &comp;
     }
     _vtx_ana.ResetPlaneInfo(mgr.InputImageMetas(larocv::ImageSetID_t::kImageSetWire).at(plane));
       }
       _particle_cluster_ptr_vvv.emplace_back(std::move(pcluster_vv));
       _track_comp_ptr_vvv.emplace_back(std::move(tcluster_vv));
     } //end this vertex
   }
StoreEvent()
void larcv::LArbysRecoHolder::StoreEvent (size_t run, size_t subrun, size_t event, size_t entry)
Definition at line 302 of file LArbysRecoHolder.cxx.
References larcv::LArOCVSerial::_matched_v, and LARCV_DEBUG.
{
     _run    = run;
     _subrun = subrun;
     _event  = event;
     _entry  = entry;
     LARCV_DEBUG() << "Copying " << _vertex_ptr_v.size() << " verticies" << std::endl;
     if (_vertex_ptr_v.empty()) return;
     auto& vertex_v             = _larocvserial->_vertex_v;
     auto& particle_cluster_vvv = _larocvserial->_particle_cluster_vvv;
     auto& track_comp_vvv       = _larocvserial->_track_comp_vvv;
     auto& matched_v            = _larocvserial->_matched_v;
     size_t n_old   = vertex_v.size();
     size_t n_new   = _vertex_ptr_v.size();
     size_t n_total = n_old + n_new;
     LARCV_DEBUG() << "Already stored " << n_old << " vertices" << std::endl;
     LARCV_DEBUG() << "Now adding     " << n_new << " vertices" << std::endl;
     LARCV_DEBUG() << "Total          " << n_total << std::endl;
     vertex_v.resize(n_total);
     particle_cluster_vvv.resize(n_total);
     track_comp_vvv.resize(n_total);
     matched_v.resize(n_total);
     for(size_t vertexid=0; vertexid<this->Verticies().size(); ++vertexid) {
       auto offset = n_old + vertexid;
       auto& vertex              = vertex_v.at(offset);
       auto& particle_cluster_vv = particle_cluster_vvv.at(offset);
       auto& track_comp_vv       = track_comp_vvv.at(offset);
       //
       // Copy the vertex, particles, and track cluster compounds
       //
       vertex = *(this->Vertex(vertexid));
       size_t nplanes = 3;
       particle_cluster_vv.resize(nplanes);
       track_comp_vv.resize(nplanes);
       for(size_t plane=0;plane<nplanes;++plane) {
     auto& particle_cluster_v = particle_cluster_vv[plane];
     auto& track_comp_v = track_comp_vv[plane];
     auto npars = this->Particles(vertexid,plane).size();
     particle_cluster_v.resize(npars);
     track_comp_v.resize(npars);
     for(size_t particleid=0;particleid<npars;++particleid) {
       auto& particle_cluster = particle_cluster_v[particleid];
       auto& track_comp = track_comp_v[particleid];
       particle_cluster = *(this->Particle(vertexid,plane,particleid));
       if (!(this->Track(vertexid,plane,particleid))) {
         LARCV_DEBUG() << "SKIP!" << std::endl;
         continue;
       }
       track_comp = *(this->Track(vertexid,plane,particleid));
     } //particle id
       } //plane id
       //
       // Set the vertex as good match or not
       //
       auto& matched = matched_v.at(offset);
       matched = _matched_v.at(vertexid);
     } //vertex id
   }
Track()
const larocv::data::TrackClusterCompound* larcv::LArbysRecoHolder::Track (size_t vertexid, size_t planeid, size_t trackid) inline
Definition at line 118 of file LArbysRecoHolder.h.
     { return _track_comp_ptr_vvv[vertexid][planeid][trackid]; }
Tracks()
const std::vector<const larocv::data::TrackClusterCompound*>& larcv::LArbysRecoHolder::Tracks (size_t vertexid, size_t planeid) inline
Definition at line 114 of file LArbysRecoHolder.h.
     { return _track_comp_ptr_vvv[vertexid][planeid]; }
Vertex()
const larocv::data::Vertex3D* larcv::LArbysRecoHolder::Vertex (size_t vertexid) inline
Definition at line 79 of file LArbysRecoHolder.h.
     { return _vertex_ptr_v[vertexid]; }
VertexPlaneParticles()
const std::vector<std::vector<std::vector<const larocv::data::ParticleCluster*> > >& larcv::LArbysRecoHolder::VertexPlaneParticles () inline
Definition at line 87 of file LArbysRecoHolder.h.
     { return _particle_cluster_ptr_vvv; }
VertexPlaneTracks()
const std::vector<std::vector<std::vector<const larocv::data::TrackClusterCompound*> > >& larcv::LArbysRecoHolder::VertexPlaneTracks () inline
Definition at line 106 of file LArbysRecoHolder.h.
     { return _track_comp_ptr_vvv; }
Verticies()
const std::vector<const larocv::data::Vertex3D*> larcv::LArbysRecoHolder::Verticies () inline
Definition at line 75 of file LArbysRecoHolder.h.
     { return _vertex_ptr_v; }
Write()
void larcv::LArbysRecoHolder::Write ()
Definition at line 176 of file LArbysRecoHolder.cxx.
References LARCV_DEBUG.
{
     const auto& vertex_v = _larocvserial->_vertex_v;
     LARCV_DEBUG() << "Writing " << vertex_v.size() << " verticies" << std::endl;
     //if(vertex_v.empty()) return;
     _out_tree->Fill();
     LARCV_DEBUG() << "done." << std::endl;
   }
WriteOut()
bool larcv::LArbysRecoHolder::WriteOut (TFile * fout)
Definition at line 292 of file LArbysRecoHolder.cxx.
{
     if (fout && _out_tree) {
       fout->cd();
       _out_tree->Write();
       return true;
     }
     return false;
   }
Member Data Documentation
_entry
uint larcv::LArbysRecoHolder::_entry private
Definition at line 144 of file LArbysRecoHolder.h.
_event
uint larcv::LArbysRecoHolder::_event private
Definition at line 143 of file LArbysRecoHolder.h.
_larocvserial
LArOCVSerial* larcv::LArbysRecoHolder::_larocvserial private
Definition at line 145 of file LArbysRecoHolder.h.
_match_check_type
bool larcv::LArbysRecoHolder::_match_check_type private
Definition at line 130 of file LArbysRecoHolder.h.
_match_coverage
float larcv::LArbysRecoHolder::_match_coverage private
Definition at line 127 of file LArbysRecoHolder.h.
_match_min_number
float larcv::LArbysRecoHolder::_match_min_number private
Definition at line 129 of file LArbysRecoHolder.h.
_match_particles_per_plane
float larcv::LArbysRecoHolder::_match_particles_per_plane private
Definition at line 128 of file LArbysRecoHolder.h.
_match_weight_by_size
bool larcv::LArbysRecoHolder::_match_weight_by_size private
Definition at line 131 of file LArbysRecoHolder.h.
_matched_v
std::vector<int> larcv::LArbysRecoHolder::_matched_v private
Definition at line 138 of file LArbysRecoHolder.h.
_out_tree
TTree* larcv::LArbysRecoHolder::_out_tree private
Definition at line 140 of file LArbysRecoHolder.h.
_output_module_name
std::string larcv::LArbysRecoHolder::_output_module_name private
Definition at line 123 of file LArbysRecoHolder.h.
_output_module_offset
size_t larcv::LArbysRecoHolder::_output_module_offset private
Definition at line 124 of file LArbysRecoHolder.h.
_particle_cluster_ptr_vvv
std::vector<std::vector<std::vector<const larocv::data::ParticleCluster*> > > larcv::LArbysRecoHolder::_particle_cluster_ptr_vvv private
Definition at line 136 of file LArbysRecoHolder.h.
_require_fiducial
bool larcv::LArbysRecoHolder::_require_fiducial private
Definition at line 126 of file LArbysRecoHolder.h.
_require_two_multiplicity
bool larcv::LArbysRecoHolder::_require_two_multiplicity private
Definition at line 125 of file LArbysRecoHolder.h.
_run
uint larcv::LArbysRecoHolder::_run private
Definition at line 141 of file LArbysRecoHolder.h.
_subrun
uint larcv::LArbysRecoHolder::_subrun private
Definition at line 142 of file LArbysRecoHolder.h.
_track_comp_ptr_vvv
std::vector<std::vector<std::vector<const larocv::data::TrackClusterCompound*> > > larcv::LArbysRecoHolder::_track_comp_ptr_vvv private
Definition at line 137 of file LArbysRecoHolder.h.
_vertex_ptr_v
std::vector<const larocv::data::Vertex3D*> larcv::LArbysRecoHolder::_vertex_ptr_v private
Definition at line 135 of file LArbysRecoHolder.h.
_vtx_ana
larocv::VertexAnalysis larcv::LArbysRecoHolder::_vtx_ana private
Definition at line 133 of file LArbysRecoHolder.h.
The documentation for this class was generated from the following files:
LArbysRecoHolder.h
LArbysRecoHolder.cxx