LArCV: larcv::SimplePixelAna Class Reference
larcv::SimplePixelAna Class Reference
#include <SimplePixelAna.h>
Public Member Functions
SimplePixelAna (const std::string name="SimplePixelAna")
Default constructor.
~SimplePixelAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::string _image_name
Image2D producer name.
TTree * _tree
TTree for analysis later.
unsigned short _image_index
Image index value.
float _max_pixel
Analysis variable: Max pixel value.
float _pixel_sum
Analysis variable: Sum of pixel values.
int _pixel_count
Analysis variable: Pixel count above a certain threshold.
float _pixel_count_threshold
Analysis variable: Threshold to increment a pixel count.
Detailed Description
Definition at line 26 of file SimplePixelAna.h.
Constructor & Destructor Documentation
SimplePixelAna()
larcv::SimplePixelAna::SimplePixelAna (const std::string name = "SimplePixelAna")
Default constructor.
Definition at line 10 of file SimplePixelAna.cxx.
Referenced by larcv::SimplePixelAnaProcessFactory::create().
     : ProcessBase(name)
   {}
~SimplePixelAna()
larcv::SimplePixelAna::~SimplePixelAna () inline
Default destructor.
Definition at line 34 of file SimplePixelAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SimplePixelAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file SimplePixelAna.cxx.
References _image_name, _pixel_count_threshold, and larcv::PSet::get().
Referenced by ~SimplePixelAna().
   {
     // Get Image2D key string
     _image_name = cfg.get<std::string>("ImageName");
     // Get pixel counting (analysis) threshold value
     _pixel_count_threshold = cfg.get<float>("PixelCountThreshold");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SimplePixelAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 78 of file SimplePixelAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~SimplePixelAna().
   {
     // If an analysis output file is configured to exist, write TTree into an output
     if(has_ana_file()) _tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SimplePixelAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 22 of file SimplePixelAna.cxx.
References _image_index, _max_pixel, _pixel_count, _pixel_sum, and _tree.
Referenced by ~SimplePixelAna().
   {
     // Instantiate & prepare TTree
     _tree = new TTree("tree","Tree for simple analysis");
     // Create variable holder in TTree
     _tree->Branch( "max_pixel",   &_max_pixel,   "max_pixel/F"   );
     _tree->Branch( "pixel_sum",   &_pixel_sum,   "pixel_sum/F"   );
     _tree->Branch( "pixel_count", &_pixel_count, "pixel_count/I" );
     _tree->Branch( "image_index", &_image_index, "image_index/s" );
     // Initialize variable contents
     _max_pixel   = 0.;
     _pixel_sum   = 0.;
     _pixel_count = 0;
     _image_index = 0;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SimplePixelAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 38 of file SimplePixelAna.cxx.
References _image_index, _image_name, _max_pixel, _pixel_count, _pixel_count_threshold, _pixel_sum, _tree, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, and LARCV_DEBUG.
Referenced by ~SimplePixelAna().
   {
     // get EventImage2D (image2d collection)
     auto my_event_image2d = (EventImage2D*)(mgr.get_data(kProductImage2D,_image_name));
     //LARCV_NORMAL() << my_event_image2d << std::endl;
     // get a direct reference to std::vector<larcv::Image2D> (i.e. array of Image2D)
     auto const& img2d_v = my_event_image2d->Image2DArray();
     // Loop over each Image2D and fill analysis variable
     for(size_t index=0; index < img2d_v.size(); ++index) {
       // Initialize analysis variables
       _image_index = index;
       _pixel_sum   = _max_pixel = 0.;
       _pixel_count = 0;
       // Access Image2D
       auto const& img2d = img2d_v[index];
       // get 1D array reference to call C++ function to find max
       auto const& pixel_array = img2d.as_vector(); // this returns std::vector<float>
       // Method 1: using smart way which we hate
       //float _max_pixel = *(std::max_element(pixel_array.begin(),pixel_array.end()));
       // Method 2: using our way
       for(auto const& v : pixel_array) {
     if(v > _max_pixel) _max_pixel = v;
     if(v > _pixel_count_threshold) _pixel_count++;
       }
       LARCV_DEBUG() << "pixel max value: " << _max_pixel << std::endl;
       _tree->Fill();
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_image_index
unsigned short larcv::SimplePixelAna::_image_index
Image index value.
Definition at line 46 of file SimplePixelAna.h.
Referenced by initialize(), and process().
_image_name
std::string larcv::SimplePixelAna::_image_name
Image2D producer name.
Definition at line 44 of file SimplePixelAna.h.
Referenced by configure(), and process().
_max_pixel
float larcv::SimplePixelAna::_max_pixel
Analysis variable: Max pixel value.
Definition at line 47 of file SimplePixelAna.h.
Referenced by initialize(), and process().
_pixel_count
int larcv::SimplePixelAna::_pixel_count
Analysis variable: Pixel count above a certain threshold.
Definition at line 49 of file SimplePixelAna.h.
Referenced by initialize(), and process().
_pixel_count_threshold
float larcv::SimplePixelAna::_pixel_count_threshold
Analysis variable: Threshold to increment a pixel count.
Definition at line 50 of file SimplePixelAna.h.
Referenced by configure(), and process().
_pixel_sum
float larcv::SimplePixelAna::_pixel_sum
Analysis variable: Sum of pixel values.
Definition at line 48 of file SimplePixelAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::SimplePixelAna::_tree
TTree for analysis later.
Definition at line 45 of file SimplePixelAna.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
SimplePixelAna.h
SimplePixelAna.cxx