LArCV: ANNkd_node Class Reference
ANNkd_node Class Reference abstract
#include <kd_tree.h>
Public Member Functions
virtual ~ANNkd_node ()
virtual void ann_search (ANNdist)=0
virtual void ann_pri_search (ANNdist)=0
virtual void ann_FR_search (ANNdist)=0
virtual void getStats (int dim, ANNkdStats &st, ANNorthRect &bnd_box)=0
virtual void print (int level, ostream &out)=0
virtual void dump (ostream &out)=0
Friends
class ANNkd_tree
Detailed Description
Definition at line 46 of file kd_tree.h.
Constructor & Destructor Documentation
~ANNkd_node()
virtual ANNkd_node::~ANNkd_node () inline virtual
Definition at line 48 of file kd_tree.h.
References dim.
 {}                  // virtual distroyer
Member Function Documentation
ann_FR_search()
virtual void ANNkd_node::ann_FR_search (ANNdist) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
Referenced by ANNbd_shrink::ann_FR_search(), and ANNkd_tree::annkFRSearch().
ann_pri_search()
virtual void ANNkd_node::ann_pri_search (ANNdist) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
Referenced by ANNbd_shrink::ann_pri_search().
ann_search()
virtual void ANNkd_node::ann_search (ANNdist) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
Referenced by ANNbd_shrink::ann_search(), and ANNkd_tree::annkSearch().
dump()
virtual void ANNkd_node::dump (ostream & out) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
getStats()
virtual void ANNkd_node::getStats (int dim, ANNkdStats & st, ANNorthRect & bnd_box) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
Referenced by ANNbd_shrink::getStats(), and ANNkd_split::getStats().
print()
virtual void ANNkd_node::print (int level, ostream & out) pure virtual
Implemented in ANNkd_split, ANNkd_leaf, and ANNbd_shrink.
Referenced by ANNbd_shrink::print(), and ANNkd_split::print().
Friends And Related Function Documentation
ANNkd_tree
friend class ANNkd_tree friend
Definition at line 62 of file kd_tree.h.
The documentation for this class was generated from the following file:
kd_tree.h