LArCV: larcv::ROI Class Reference
larcv::ROI Class Reference
User defined class ROI ...
#include <ROI.h>
Public Member Functions
ROI (larcv::ROIType_t type=larcv::kROIUnknown, larcv::ShapeType_t shape=larcv::kShapeUnknown)
Default constructor.
~ROI ()
Default destructor.
ROIIndex_t Index () const
ROIType_t Type () const
ShapeType_t Shape () const
MCSTIndex_t MCSTIndex () const
MCTIndex_t MCTIndex () const
double EnergyDeposit () const
double EnergyInit () const
int PdgCode () const
int ParentPdgCode () const
unsigned int TrackID () const
unsigned int ParentTrackID () const
const larcv::Vertex & Position () const
double X () const
double Y () const
double Z () const
double T () const
double Px () const
double Py () const
double Pz () const
double ParentX () const
double ParentY () const
double ParentZ () const
double ParentT () const
double ParentPx () const
double ParentPy () const
double ParentPz () const
const larcv::Vertex & ParentPosition () const
const std::vector< larcv::ImageMeta > & BB () const
const ImageMeta & BB (PlaneID_t plane) const
short NuCurrentType () const
short NuInteractionType () const
const std::string & CreationProcess () const
const larcv::Vertex & EndPosition () const
const larcv::Vertex & FirstStep () const
const larcv::Vertex & LastStep () const
double DistanceTravel () const
const std::vector< float > & TypeScore () const
void Index (ROIIndex_t id)
void Type (ROIType_t type)
void Shape (ShapeType_t shape)
void MCSTIndex (MCSTIndex_t id)
void MCTIndex (MCTIndex_t id)
void EnergyDeposit (double e)
void EnergyInit (double e)
void PdgCode (int code)
void ParentPdgCode (int code)
void TrackID (unsigned int id)
void ParentTrackID (unsigned int id)
void Position (const larcv::Vertex &vtx)
void Position (double x, double y, double z, double t)
void Momentum (double px, double py, double pz)
void ParentPosition (const larcv::Vertex &vtx)
void ParentPosition (double x, double y, double z, double t)
void ParentMomentum (double px, double py, double pz)
void AppendBB (const larcv::ImageMeta &bb)
void SetBB (const std::vector< larcv::ImageMeta > &bb_v)
void NuCurrentType (short curr)
void NuInteractionType (short itype)
void CreationProcess (const std::string &proc)
void EndPosition (const larcv::Vertex &vtx)
void EndPosition (double x, double y, double z, double t)
void FirstStep (const larcv::Vertex &vtx)
void FirstStep (double x, double y, double z, double t)
void LastStep (const larcv::Vertex &vtx)
void LastStep (double x, double y, double z, double t)
void DistanceTravel (double dist)
void TypeScore (const std::vector< float > &score_v)
std::string dump () const
Private Attributes
ROIIndex_t _index
ShapeType_t _shape
ROIType_t _type
MCSTIndex_t _mcst_index
MCTIndex_t _mct_index
double _energy_deposit
double _energy_init
int _pdg
int _parent_pdg
unsigned int _trackid
unsigned int _parent_trackid
Vertex _vtx
double _px
double _py
double _pz
Vertex _parent_vtx
double _parent_px
double _parent_py
double _parent_pz
std::vector< larcv::ImageMeta > _bb_v
short _current_type
short _interaction_type
std::string _process
Vertex _end_pt
std::vector< float > _type_score_v
Vertex _first_step
Vertex _last_step
double _dist_travel
Detailed Description
User defined class ROI ...
these comments are used to generate doxygen documentation!
Definition at line 28 of file ROI.h.
Constructor & Destructor Documentation
ROI()
larcv::ROI::ROI (larcv::ROIType_t type = larcv::kROIUnknown, larcv::ShapeType_t shape = larcv::kShapeUnknown) inline
Default constructor.
Definition at line 33 of file ROI.h.
       : _index      (kINVALID_INDEX)
       , _shape      (shape)
       , _type       (type )
       , _mcst_index (kINVALID_INDEX)
       , _mct_index  (kINVALID_INDEX)
       , _energy_deposit (0.)
       , _energy_init    (0.)
       , _pdg            (0)
       , _parent_pdg     (0)
       , _trackid        (kINVALID_UINT)
       , _parent_trackid (kINVALID_UINT)
       , _px             (0.)
       , _py             (0.)
       , _pz             (0.)
       , _current_type   (-1)
       , _interaction_type (-1)
       , _process ("")
       , _dist_travel(-1)
     {}
~ROI()
larcv::ROI::~ROI () inline
Default destructor.
Definition at line 56 of file ROI.h.
 {}
Member Function Documentation
AppendBB()
void larcv::ROI::AppendBB (const larcv::ImageMeta & bb)
Definition at line 16 of file ROI.cxx.
References _bb_v, and larcv::ImageMeta::plane().
Referenced by ParentMomentum(), larcv::LArbysImage::process(), larcv::SingleROIFaker::process(), larcv::ROIMask::process(), larcv::LArbysImage::StoreParticles(), and larcv::UnionROI::Union().
   {
     // Make sure this is not duplicate in terms of plane ID
     std::set<larcv::PlaneID_t> ids;
     for(auto const& meta : _bb_v) ids.insert(meta.plane());
     if(ids.find(bb.plane()) != ids.end()) throw larbys("Cannot have ImageMeta of duplicate plane!");
     _bb_v.push_back(bb);
   }
BB() [1/2]
const std::vector<larcv::ImageMeta>& larcv::ROI::BB () const inline
Definition at line 85 of file ROI.h.
References _bb_v.
Referenced by larcv::PIDImageMaker::CROIImgFiller(), dump(), larcv::LArbysImageExtract::FillcvMat(), larcv::SuperaMCROI::MakeROI(), larcv::LArbysImageReAna::Process(), larcv::SuperaMCROI::process(), larcv::hires::HiResImageDivider::process(), and larcv::SuperaMCROI::UpdatePrimaryROI().
 { return _bb_v;  }
BB() [2/2]
const ImageMeta & larcv::ROI::BB (PlaneID_t plane) const
Definition at line 10 of file ROI.cxx.
References _bb_v.
   {
     for(auto const& bb : _bb_v) { if(bb.plane() == plane) return bb; }
     throw larbys("Could not locate requested plane's bounding box!");
   }
CreationProcess() [1/2]
const std::string& larcv::ROI::CreationProcess () const inline
Definition at line 89 of file ROI.h.
References _process.
Referenced by dump(), and supera::MCROIMaker::ParticleROI().
 { return _process; }
CreationProcess() [2/2]
void larcv::ROI::CreationProcess (const std::string & proc) inline
Definition at line 117 of file ROI.h.
References _process.
 { _process = proc; }
DistanceTravel() [1/2]
double larcv::ROI::DistanceTravel () const inline
Definition at line 93 of file ROI.h.
References _dist_travel.
Referenced by supera::MCROIMaker::ParticleROI().
 { return _dist_travel; }
DistanceTravel() [2/2]
void larcv::ROI::DistanceTravel (double dist) inline
Definition at line 124 of file ROI.h.
References _dist_travel.
 { _dist_travel = dist; }
dump()
std::string larcv::ROI::dump () const
Definition at line 34 of file ROI.cxx.
References BB(), CreationProcess(), EnergyDeposit(), EnergyInit(), larcv::kROIBNB, larcv::kROICosmic, ParentPdgCode(), ParentTrackID(), PdgCode(), Px(), Py(), Pz(), larcv::ROIType2String(), T(), TrackID(), Type(), X(), Y(), and Z().
Referenced by larcv::hires::HiResImageDivider::generateSingleMCDivision(), supera::MCROIMaker::ParticleROI(), larcv::hires::HiResImageDivider::process(), and TypeScore().
   {
     std::stringstream ss;
     std::stringstream buf;
     if(Type() == larcv::kROIBNB || Type() == larcv::kROICosmic) {
       ss  << "    \033[93m" << (Type() == larcv::kROIBNB ? "BNB PdgCode=" : "Cosmic PdgCode=") << PdgCode() << "\033[00m" << std::endl;
       buf << "    ";
     }
     else {
       ss  << "      \033[95m" << "Particle " << ROIType2String(Type()) << " (PdgCode,TrackID) = (" << PdgCode() << "," << TrackID() << ")\033[00m "
       << "... with Parent (" << ParentPdgCode() << "," << ParentTrackID() << ")" << std::endl;
       buf << "      ";
     }
     ss << buf.str() << "Vertex   (x, y, z, t) = (" << X() << "," << Y() << "," << Z() << "," << T() << ")" << std::endl
        << buf.str() << "Momentum (px, py, pz) = (" << Px() << "," << Py() << "," << Pz() << ")" << std::endl
        << buf.str() << "Inittial Energy  = " << EnergyInit() << std::endl
        << buf.str() << "Deposit  Energy  = " << EnergyDeposit() << std::endl
        << buf.str() << "Creation Process = " << CreationProcess() << std::endl
        << buf.str() << "# Bounding Box   = " << BB().size() << std::endl;
     buf << "    ";
     for(auto const& meta : BB())
       ss << buf.str() << meta.dump();
     ss << std::endl;
     return ss.str();
   }
EndPosition() [1/3]
const larcv::Vertex& larcv::ROI::EndPosition () const inline
Definition at line 90 of file ROI.h.
References _end_pt.
Referenced by supera::MCROIMaker::ParticleROI(), and larcv::LArbysImage::StoreParticles().
 { return _end_pt; }
EndPosition() [2/3]
void larcv::ROI::EndPosition (const larcv::Vertex & vtx) inline
Definition at line 118 of file ROI.h.
References _end_pt.
 { _end_pt = vtx; }
EndPosition() [3/3]
void larcv::ROI::EndPosition (double x, double y, double z, double t) inline
Definition at line 119 of file ROI.h.
References _end_pt.
 { _end_pt = Vertex(x,y,z,t); }
EnergyDeposit() [1/2]
double larcv::ROI::EnergyDeposit () const inline
Definition at line 63 of file ROI.h.
References _energy_deposit.
Referenced by supera::MCParticleTree::DefinePrimary(), dump(), supera::MCROIMaker::ParticleROI(), and larcv::SuperaMCROI::UpdatePrimaryROI().
 { return _energy_deposit; }
EnergyDeposit() [2/2]
void larcv::ROI::EnergyDeposit (double e) inline
Definition at line 101 of file ROI.h.
References _energy_deposit.
 { _energy_deposit = e; }
EnergyInit() [1/2]
double larcv::ROI::EnergyInit () const inline
Definition at line 64 of file ROI.h.
References _energy_init.
Referenced by supera::MCParticleTree::DefinePrimary(), dump(), and supera::MCROIMaker::ParticleROI().
 { return _energy_init;    }
EnergyInit() [2/2]
void larcv::ROI::EnergyInit (double e) inline
Definition at line 102 of file ROI.h.
References _energy_init.
 { _energy_init = e;    }
FirstStep() [1/3]
const larcv::Vertex& larcv::ROI::FirstStep () const inline
Definition at line 91 of file ROI.h.
References _first_step.
Referenced by supera::MCROIMaker::ParticleROI().
 { return _first_step; }
FirstStep() [2/3]
void larcv::ROI::FirstStep (const larcv::Vertex & vtx) inline
Definition at line 120 of file ROI.h.
References _first_step.
 { _first_step = vtx; }
FirstStep() [3/3]
void larcv::ROI::FirstStep (double x, double y, double z, double t) inline
Definition at line 121 of file ROI.h.
References _first_step.
 { _first_step = Vertex(x,y,z,t); }
Index() [1/2]
ROIIndex_t larcv::ROI::Index () const inline
Definition at line 58 of file ROI.h.
References _index.
 { return _index;          }
Index() [2/2]
void larcv::ROI::Index (ROIIndex_t id) inline
Definition at line 96 of file ROI.h.
References _index.
 { _index = id;         }
LastStep() [1/3]
const larcv::Vertex& larcv::ROI::LastStep () const inline
Definition at line 92 of file ROI.h.
References _last_step.
Referenced by supera::MCROIMaker::ParticleROI().
 { return _last_step; }
LastStep() [2/3]
void larcv::ROI::LastStep (const larcv::Vertex & vtx) inline
Definition at line 122 of file ROI.h.
References _last_step.
 { _last_step = vtx; }
LastStep() [3/3]
void larcv::ROI::LastStep (double x, double y, double z, double t) inline
Definition at line 123 of file ROI.h.
References _last_step.
 { _last_step = Vertex(x,y,z,t); }
MCSTIndex() [1/2]
MCSTIndex_t larcv::ROI::MCSTIndex () const inline
Definition at line 61 of file ROI.h.
References _mcst_index.
Referenced by larcv::hires::HiResImageDivider::isInteresting(), and larcv::SuperaMCROI::MakeROI().
 { return _mcst_index;     }
MCSTIndex() [2/2]
void larcv::ROI::MCSTIndex (MCSTIndex_t id) inline
Definition at line 99 of file ROI.h.
References _mcst_index.
 { _mcst_index = id;    }
MCTIndex() [1/2]
MCTIndex_t larcv::ROI::MCTIndex () const inline
Definition at line 62 of file ROI.h.
References _mct_index.
Referenced by supera::MCParticleTree::DefinePrimary(), and larcv::SuperaMCROI::UpdatePrimaryROI().
 { return _mct_index;      }
MCTIndex() [2/2]
void larcv::ROI::MCTIndex (MCTIndex_t id) inline
Definition at line 100 of file ROI.h.
References _mct_index.
 { _mct_index = id;     }
Momentum()
void larcv::ROI::Momentum (double px, double py, double pz) inline
Definition at line 109 of file ROI.h.
References _px, _py, and _pz.
Referenced by supera::MCParticleTree::DefinePrimary(), and supera::MCROIMaker::ParticleROI().
 { _px = px; _py = py; _pz = pz; }
NuCurrentType() [1/2]
short larcv::ROI::NuCurrentType () const inline
Definition at line 87 of file ROI.h.
References _current_type.
 { return _current_type; }
NuCurrentType() [2/2]
void larcv::ROI::NuCurrentType (short curr) inline
Definition at line 115 of file ROI.h.
References _current_type.
 { curr = -1; _current_type = curr; }
NuInteractionType() [1/2]
short larcv::ROI::NuInteractionType () const inline
Definition at line 88 of file ROI.h.
References _interaction_type.
 { return _interaction_type; }
NuInteractionType() [2/2]
void larcv::ROI::NuInteractionType (short itype) inline
Definition at line 116 of file ROI.h.
References _interaction_type.
 { itype = -1; _interaction_type = itype; }
ParentMomentum()
void larcv::ROI::ParentMomentum (double px, double py, double pz) inline
Definition at line 112 of file ROI.h.
References _parent_px, _parent_py, _parent_pz, AppendBB(), and SetBB().
Referenced by supera::MCROIMaker::ParticleROI().
 { _parent_px = px; _parent_py = py; _parent_pz = pz; }
ParentPdgCode() [1/2]
int larcv::ROI::ParentPdgCode () const inline
Definition at line 66 of file ROI.h.
References _parent_pdg.
Referenced by dump(), and supera::MCROIMaker::ParticleROI().
 { return _parent_pdg;     }
ParentPdgCode() [2/2]
void larcv::ROI::ParentPdgCode (int code) inline
Definition at line 104 of file ROI.h.
References _parent_pdg.
 { _parent_pdg = code;  }
ParentPosition() [1/3]
const larcv::Vertex& larcv::ROI::ParentPosition () const inline
Definition at line 84 of file ROI.h.
References _parent_vtx.
Referenced by supera::MCROIMaker::ParticleROI().
 { return _parent_vtx;}
ParentPosition() [2/3]
void larcv::ROI::ParentPosition (const larcv::Vertex & vtx) inline
Definition at line 110 of file ROI.h.
References _parent_vtx.
 { _parent_vtx = vtx; }
ParentPosition() [3/3]
void larcv::ROI::ParentPosition (double x, double y, double z, double t) inline
Definition at line 111 of file ROI.h.
References _parent_vtx.
 { _parent_vtx = Vertex(x,y,z,t); }
ParentPx()
double larcv::ROI::ParentPx () const inline
Definition at line 81 of file ROI.h.
References _parent_px.
 { return _parent_px;      }
ParentPy()
double larcv::ROI::ParentPy () const inline
Definition at line 82 of file ROI.h.
References _parent_py.
 { return _parent_py;      }
ParentPz()
double larcv::ROI::ParentPz () const inline
Definition at line 83 of file ROI.h.
References _parent_pz.
 { return _parent_pz;      }
ParentT()
double larcv::ROI::ParentT () const inline
Definition at line 80 of file ROI.h.
References _parent_vtx, and larcv::Vertex::T().
 { return _parent_vtx.T(); }
ParentTrackID() [1/2]
unsigned int larcv::ROI::ParentTrackID () const inline
Definition at line 68 of file ROI.h.
References _parent_trackid.
Referenced by dump(), and supera::MCROIMaker::ParticleROI().
 { return _parent_trackid; }
ParentTrackID() [2/2]
void larcv::ROI::ParentTrackID (unsigned int id) inline
Definition at line 106 of file ROI.h.
References _parent_trackid.
 { _parent_trackid = id;}
ParentX()
double larcv::ROI::ParentX () const inline
Definition at line 77 of file ROI.h.
References _parent_vtx, and larcv::Vertex::X().
 { return _parent_vtx.X(); }
ParentY()
double larcv::ROI::ParentY () const inline
Definition at line 78 of file ROI.h.
References _parent_vtx, and larcv::Vertex::Y().
 { return _parent_vtx.Y(); }
ParentZ()
double larcv::ROI::ParentZ () const inline
Definition at line 79 of file ROI.h.
References _parent_vtx, and larcv::Vertex::Z().
 { return _parent_vtx.Z(); }
PdgCode() [1/2]
int larcv::ROI::PdgCode () const inline
Definition at line 65 of file ROI.h.
References _pdg.
Referenced by supera::MCParticleTree::DefinePrimary(), dump(), larcv::NuFilter::MCSelect(), supera::MCROIMaker::ParticleROI(), and larcv::SuperaMCROI::process().
 { return _pdg;            }
PdgCode() [2/2]
void larcv::ROI::PdgCode (int code) inline
Definition at line 103 of file ROI.h.
References _pdg.
 { _pdg = code;         }
Position() [1/3]
const larcv::Vertex& larcv::ROI::Position () const inline
Definition at line 69 of file ROI.h.
References _vtx.
Referenced by supera::MCParticleTree::DefinePrimary(), larcv::hires::HiResImageDivider::findVertexDivision(), larcv::hires::HiResImageDivider::generateSingleCosmicDivision(), supera::MCROIMaker::ParticleROI(), and larcv::LArbysImage::StoreParticles().
 { return _vtx;            }
Position() [2/3]
void larcv::ROI::Position (const larcv::Vertex & vtx) inline
Definition at line 107 of file ROI.h.
References _vtx.
 { _vtx = vtx;    }
Position() [3/3]
void larcv::ROI::Position (double x, double y, double z, double t) inline
Definition at line 108 of file ROI.h.
References _vtx.
 { _vtx = Vertex(x,y,z,t); }
Px()
double larcv::ROI::Px () const inline
Definition at line 74 of file ROI.h.
References _px.
Referenced by dump().
 { return _px;      }
Py()
double larcv::ROI::Py () const inline
Definition at line 75 of file ROI.h.
References _py.
Referenced by dump().
 { return _py;      }
Pz()
double larcv::ROI::Pz () const inline
Definition at line 76 of file ROI.h.
References _pz.
Referenced by dump().
 { return _pz;      }
SetBB()
void larcv::ROI::SetBB (const std::vector< larcv::ImageMeta > & bb_v)
Definition at line 25 of file ROI.cxx.
References _bb_v.
Referenced by larcv::SuperaMCROI::MakeROI(), ParentMomentum(), supera::MCROIMaker::ParticleROI(), larcv::hires::HiResImageDivider::process(), and larcv::SuperaMCROI::UpdatePrimaryROI().
   {
     // Make sure this is not duplicate in terms of plane ID
     std::set<larcv::PlaneID_t> ids;
     for(auto const& meta : bb_v) ids.insert(meta.plane());
     if(ids.size() != bb_v.size()) throw larbys("Cannot have ImageMeta of duplicate plane!");
     _bb_v = bb_v;
   }
Shape() [1/2]
ShapeType_t larcv::ROI::Shape () const inline
Definition at line 60 of file ROI.h.
References _shape.
Referenced by supera::MCROIMaker::ParticleROI(), and larcv::LArbysImage::StoreParticles().
 { return _shape;          }
Shape() [2/2]
void larcv::ROI::Shape (ShapeType_t shape) inline
Definition at line 98 of file ROI.h.
References _shape.
 { _shape = shape;      }
T()
double larcv::ROI::T () const inline
Definition at line 73 of file ROI.h.
References _vtx, and larcv::Vertex::T().
Referenced by dump().
 { return _vtx.T(); }
TrackID() [1/2]
unsigned int larcv::ROI::TrackID () const inline
Definition at line 67 of file ROI.h.
References _trackid.
Referenced by dump(), and supera::MCROIMaker::ParticleROI().
 { return _trackid;        }
TrackID() [2/2]
void larcv::ROI::TrackID (unsigned int id) inline
Definition at line 105 of file ROI.h.
References _trackid.
 { _trackid = id;       }
Type() [1/2]
ROIType_t larcv::ROI::Type () const inline
Definition at line 59 of file ROI.h.
References _type.
Referenced by dump(), larcv::hires::HiResImageDivider::generateSingleCosmicDivision(), supera::MCROIMaker::ParticleROI(), larcv::CosmicROIFiller::process(), and larcv::hires::HiResImageDivider::process().
 { return _type;           }
Type() [2/2]
void larcv::ROI::Type (ROIType_t type) inline
Definition at line 97 of file ROI.h.
References _type.
 { _type  = type;       }
TypeScore() [1/2]
const std::vector<float>& larcv::ROI::TypeScore () const inline
Definition at line 94 of file ROI.h.
References _type_score_v.
 { return _type_score_v; }
TypeScore() [2/2]
void larcv::ROI::TypeScore (const std::vector< float > & score_v) inline
Definition at line 125 of file ROI.h.
References _type_score_v, and dump().
 { _type_score_v = score_v; }
X()
double larcv::ROI::X () const inline
Definition at line 70 of file ROI.h.
References _vtx, and larcv::Vertex::X().
Referenced by dump().
 { return _vtx.X(); }
Y()
double larcv::ROI::Y () const inline
Definition at line 71 of file ROI.h.
References _vtx, and larcv::Vertex::Y().
Referenced by dump(), and larcv::VtxInRegion::process().
 { return _vtx.Y(); }
Z()
double larcv::ROI::Z () const inline
Definition at line 72 of file ROI.h.
References _vtx, and larcv::Vertex::Z().
Referenced by dump(), and larcv::VtxInRegion::process().
 { return _vtx.Z(); }
Member Data Documentation
_bb_v
std::vector<larcv::ImageMeta> larcv::ROI::_bb_v private
Definition at line 147 of file ROI.h.
Referenced by AppendBB(), BB(), and SetBB().
_current_type
short larcv::ROI::_current_type private
Definition at line 148 of file ROI.h.
Referenced by NuCurrentType().
_dist_travel
double larcv::ROI::_dist_travel private
Definition at line 156 of file ROI.h.
Referenced by DistanceTravel().
_end_pt
Vertex larcv::ROI::_end_pt private
Definition at line 152 of file ROI.h.
Referenced by EndPosition().
_energy_deposit
double larcv::ROI::_energy_deposit private
Definition at line 137 of file ROI.h.
Referenced by EnergyDeposit().
_energy_init
double larcv::ROI::_energy_init private
Definition at line 138 of file ROI.h.
Referenced by EnergyInit().
_first_step
Vertex larcv::ROI::_first_step private
Definition at line 154 of file ROI.h.
Referenced by FirstStep().
_index
ROIIndex_t larcv::ROI::_index private
Definition at line 131 of file ROI.h.
Referenced by Index().
_interaction_type
short larcv::ROI::_interaction_type private
Definition at line 149 of file ROI.h.
Referenced by NuInteractionType().
_last_step
Vertex larcv::ROI::_last_step private
Definition at line 155 of file ROI.h.
Referenced by LastStep().
_mcst_index
MCSTIndex_t larcv::ROI::_mcst_index private
Definition at line 134 of file ROI.h.
Referenced by MCSTIndex().
_mct_index
MCTIndex_t larcv::ROI::_mct_index private
Definition at line 135 of file ROI.h.
Referenced by MCTIndex().
_parent_pdg
int larcv::ROI::_parent_pdg private
Definition at line 140 of file ROI.h.
Referenced by ParentPdgCode().
_parent_px
double larcv::ROI::_parent_px private
Definition at line 146 of file ROI.h.
Referenced by ParentMomentum(), and ParentPx().
_parent_py
double larcv::ROI::_parent_py private
Definition at line 146 of file ROI.h.
Referenced by ParentMomentum(), and ParentPy().
_parent_pz
double larcv::ROI::_parent_pz private
Definition at line 146 of file ROI.h.
Referenced by ParentMomentum(), and ParentPz().
_parent_trackid
unsigned int larcv::ROI::_parent_trackid private
Definition at line 142 of file ROI.h.
Referenced by ParentTrackID().
_parent_vtx
Vertex larcv::ROI::_parent_vtx private
Definition at line 145 of file ROI.h.
Referenced by ParentPosition(), ParentT(), ParentX(), ParentY(), and ParentZ().
_pdg
int larcv::ROI::_pdg private
Definition at line 139 of file ROI.h.
Referenced by PdgCode().
_process
std::string larcv::ROI::_process private
Definition at line 151 of file ROI.h.
Referenced by CreationProcess().
_px
double larcv::ROI::_px private
Definition at line 144 of file ROI.h.
Referenced by Momentum(), and Px().
_py
double larcv::ROI::_py private
Definition at line 144 of file ROI.h.
Referenced by Momentum(), and Py().
_pz
double larcv::ROI::_pz private
Definition at line 144 of file ROI.h.
Referenced by Momentum(), and Pz().
_shape
ShapeType_t larcv::ROI::_shape private
Definition at line 132 of file ROI.h.
Referenced by Shape().
_trackid
unsigned int larcv::ROI::_trackid private
Definition at line 141 of file ROI.h.
Referenced by TrackID().
_type
ROIType_t larcv::ROI::_type private
Definition at line 133 of file ROI.h.
Referenced by Type().
_type_score_v
std::vector<float> larcv::ROI::_type_score_v private
Definition at line 153 of file ROI.h.
Referenced by TypeScore().
_vtx
Vertex larcv::ROI::_vtx private
Definition at line 143 of file ROI.h.
Referenced by Position(), T(), X(), Y(), and Z().
The documentation for this class was generated from the following files:
ROI.h
ROI.cxx