LArCV: larcv::Range< T > Class Template Reference
larcv::Range< T > Class Template Reference
represents a "Range" w/ notion of ordering.
#include <Range.h>
Public Member Functions
Range ()
Default ctor.
Range (const T &start, const T &end)
Enforced ctor. start must be less than end.
~Range ()
Default dtor.
bool valid () const
validity
const T & Start () const
"start" accessor
const T & End () const
"end" accessor
void Set (const T &s, const T &e)
Setter.
bool Inside (const T &v) const
Checker (if value is inside range or not)
bool Outside (const T &v) const
Checker (if value is outside range or not)
bool operator< (const Range &rhs) const
bool operator> (const Range &rhs) const
bool operator== (const Range &rhs) const
bool operator!= (const Range &rhs) const
bool operator< (const T &rhs) const
bool operator> (const T &rhs) const
Range< T > operator+ (const Range< T > &rhs) const
Merge two larcv::Range into 1.
Range< T > & operator+= (const Range< T > &rhs)
Range< T > & operator+= (const T &rhs)
Protected Attributes
std::pair< T, T > _window
Protected to avoid user's illegal modification on first/second (sorry users!)
bool _valid
For validity.
Friends
class UniqueRangeSet< T >
Detailed Description
template<class T>
class larcv::Range< T >
represents a "Range" w/ notion of ordering.
A range is defined by a pair of "start" and "end" values. This is stored in std::pair
attribute larcv::Range::_window. This attribute is protected so that the start/end cannot
be changed w/o a check that start is always less than end. Note the specialization
requires a template class T to have less operator implemented.
Definition at line 34 of file Range.h.
Constructor & Destructor Documentation
Range() [1/2]
template<class T> larcv::Range< T >::Range () inline
Default ctor.
Definition at line 40 of file Range.h.
             : _valid(false)
     {}
Range() [2/2]
template<class T> larcv::Range< T >::Range (const T & start, const T & end) inline
Enforced ctor. start must be less than end.
Definition at line 44 of file Range.h.
       : _window(start,end)
       , _valid(true)
     { if(start>end) throw std::runtime_error("Inserted invalid range: end before start."); }
~Range()
template<class T> larcv::Range< T >::~Range () inline
Default dtor.
Definition at line 51 of file Range.h.
 {}
Member Function Documentation
End()
template<class T> const T& larcv::Range< T >::End () const inline
"end" accessor
Definition at line 58 of file Range.h.
References larcv::Range< T >::_window.
Referenced by larcv::Range< T >::operator+(), larcv::Range< T >::operator+=(), larcv::Range< T >::operator==(), and larcv::Range< T >::operator>().
 { return _window.second; }
Inside()
template<class T> bool larcv::Range< T >::Inside (const T & v) const inline
Checker (if value is inside range or not)
Definition at line 68 of file Range.h.
References larcv::Range< T >::_window.
Referenced by larcv::Range< T >::Outside().
     { return _window.first <= v && v <= _window.second; }
operator!=()
template<class T> bool larcv::Range< T >::operator!= (const Range< T > & rhs) const inline
Definition at line 83 of file Range.h.
     {return !( (*this) == rhs ); }
operator+()
template<class T> Range<T> larcv::Range< T >::operator+ (const Range< T > & rhs) const inline
Merge two larcv::Range into 1.
Definition at line 95 of file Range.h.
References larcv::Range< T >::_window, larcv::Range< T >::End(), larcv::Range< T >::Set(), and larcv::Range< T >::Start().
     {
       Range<T> res(*this);
       res.Set(std::min( _window.first,  rhs.Start() ),
           std::max( _window.second, rhs.End()   ) );
       return res;
     }
operator+=() [1/2]
template<class T> Range<T>& larcv::Range< T >::operator+= (const Range< T > & rhs) inline
Definition at line 102 of file Range.h.
References larcv::Range< T >::_window, larcv::Range< T >::End(), and larcv::Range< T >::Start().
     {
       _window.first  = std::min( _window.first,  rhs.Start() );
       _window.second = std::max( _window.second, rhs.End()   );
       return (*this);
     }
operator+=() [2/2]
template<class T> Range<T>& larcv::Range< T >::operator+= (const T & rhs) inline
Definition at line 108 of file Range.h.
References larcv::Range< T >::_window.
     {
       _window.first  = std::min( _window.first,  rhs );
       _window.second = std::max( _window.second, rhs );
       return (*this);
     }
operator<() [1/2]
template<class T> bool larcv::Range< T >::operator< (const Range< T > & rhs) const inline
Definition at line 77 of file Range.h.
References larcv::Range< T >::_window, and larcv::Range< T >::Start().
     {return ( _window.second < rhs.Start() ); }
operator<() [2/2]
template<class T> bool larcv::Range< T >::operator< (const T & rhs) const inline
Definition at line 89 of file Range.h.
References larcv::Range< T >::_window.
     {return (_window.second < rhs); }
operator==()
template<class T> bool larcv::Range< T >::operator== (const Range< T > & rhs) const inline
Definition at line 81 of file Range.h.
References larcv::Range< T >::_window, larcv::Range< T >::End(), and larcv::Range< T >::Start().
     {return ( _window.first == rhs.Start() && _window.second == rhs.End() ); }
operator>() [1/2]
template<class T> bool larcv::Range< T >::operator> (const Range< T > & rhs) const inline
Definition at line 79 of file Range.h.
References larcv::Range< T >::_window, and larcv::Range< T >::End().
     {return ( _window.first > rhs.End() ); }
operator>() [2/2]
template<class T> bool larcv::Range< T >::operator> (const T & rhs) const inline
Definition at line 91 of file Range.h.
References larcv::Range< T >::_window.
     {return (_window.first > rhs); }
Outside()
template<class T> bool larcv::Range< T >::Outside (const T & v) const inline
Checker (if value is outside range or not)
Definition at line 71 of file Range.h.
References larcv::Range< T >::Inside().
     { return !(this->Inside(v)); }
Set()
template<class T> void larcv::Range< T >::Set (const T & s, const T & e) inline
Setter.
Definition at line 60 of file Range.h.
References larcv::Range< T >::_valid, and larcv::Range< T >::_window.
Referenced by larcv::Range< T >::operator+().
     {
       if(s>e) throw std::runtime_error("Inserted invalid range: end before start.");
       _window.first  = s;
       _window.second = e;
       _valid = true;
     }
Start()
template<class T> const T& larcv::Range< T >::Start () const inline
"start" accessor
Definition at line 56 of file Range.h.
References larcv::Range< T >::_window.
Referenced by larcv::Range< T >::operator+(), larcv::Range< T >::operator+=(), larcv::Range< T >::operator<(), and larcv::Range< T >::operator==().
 { return _window.first;  }
valid()
template<class T> bool larcv::Range< T >::valid () const inline
validity
Definition at line 54 of file Range.h.
References larcv::Range< T >::_valid.
 { return _valid; }
Friends And Related Function Documentation
UniqueRangeSet< T >
template<class T> friend class UniqueRangeSet< T > friend
Definition at line 36 of file Range.h.
Member Data Documentation
_valid
template<class T> bool larcv::Range< T >::_valid protected
For validity.
Definition at line 125 of file Range.h.
Referenced by larcv::Range< T >::Set(), and larcv::Range< T >::valid().
_window
template<class T> std::pair<T,T> larcv::Range< T >::_window protected
Protected to avoid user's illegal modification on first/second (sorry users!)
Definition at line 123 of file Range.h.
Referenced by larcv::Range< T >::End(), larcv::UniqueRangeSet< T >::insert(), larcv::Range< T >::Inside(), larcv::Range< T >::operator+(), larcv::Range< T >::operator+=(), larcv::Range< T >::operator<(), larcv::Range< T >::operator==(), larcv::Range< T >::operator>(), larcv::Range< T >::Set(), and larcv::Range< T >::Start().
The documentation for this class was generated from the following file:
Range.h