LArCV: larcv::SegmentRelabel Class Reference
larcv::SegmentRelabel Class Reference
#include <SegmentRelabel.h>
Public Member Functions
SegmentRelabel (const std::string name="SegmentRelabel")
Default constructor.
~SegmentRelabel ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
std::string fInputSegmentProducer
std::string fOutputSegmentProducer
std::map< int, int > fOrigToNewMap
Detailed Description
Definition at line 32 of file SegmentRelabel.h.
Constructor & Destructor Documentation
SegmentRelabel()
larcv::SegmentRelabel::SegmentRelabel (const std::string name = "SegmentRelabel")
Default constructor.
Definition at line 13 of file SegmentRelabel.cxx.
Referenced by larcv::SegmentRelabelProcessFactory::create().
     : ProcessBase(name)
   {}
~SegmentRelabel()
larcv::SegmentRelabel::~SegmentRelabel () inline
Default destructor.
Definition at line 40 of file SegmentRelabel.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SegmentRelabel::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 17 of file SegmentRelabel.cxx.
References fInputSegmentProducer, fOrigToNewMap, fOutputSegmentProducer, larcv::PSet::get(), and LARCV_DEBUG.
Referenced by ~SegmentRelabel().
   {
     fInputSegmentProducer = cfg.get<std::string>("InputSegmentProducerName"); // input producer
     fOutputSegmentProducer = cfg.get<std::string>("OutputSegmentProducerName"); // input producer
     PSet  fRelabelPset   = cfg.get<PSet>("LabelMap");
     // the label map should look something like:
     //  { 0:[1,2,5],
     //    1:[0,3],
     //    2:[4,5]
     //       ...}: the index will be used as the new label. items in vector are old labels
     // parse the label map
     fOrigToNewMap.clear();
     for (auto const& it : fRelabelPset.keys() ) {
       int key = atoi( it.c_str() );
       std::vector<int> old_label_list = fRelabelPset.get< std::vector<int> >( it );
       for (auto &old_label : old_label_list ) {
     fOrigToNewMap[old_label] = key;
     LARCV_DEBUG() << "Reassigning " << old_label << " to " << key << std::endl;
       }
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SegmentRelabel::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 116 of file SegmentRelabel.cxx.
Referenced by ~SegmentRelabel().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SegmentRelabel::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 42 of file SegmentRelabel.cxx.
Referenced by ~SegmentRelabel().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SegmentRelabel::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 45 of file SegmentRelabel.cxx.
References larcv::Image2D::as_vector(), larcv::Image2D::copy(), larcv::EventImage2D::Emplace(), fInputSegmentProducer, fOrigToNewMap, fOutputSegmentProducer, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_ERROR, larcv::Image2D::meta(), and larcv::EventImage2D::Move().
Referenced by ~SegmentRelabel().
   {
     // input segmentation images
     bool inplace = false;
     if ( fOutputSegmentProducer==fInputSegmentProducer )
       inplace = true;
     EventImage2D* event_original_segment = (EventImage2D*)mgr.get_data(kProductImage2D, fInputSegmentProducer);
     EventImage2D* event_relabel_segment = NULL;
     if (!inplace)
       event_relabel_segment  = (EventImage2D*)mgr.get_data(kProductImage2D, fOutputSegmentProducer);
     else
       event_relabel_segment = event_original_segment;
     if ( !event_original_segment ) {
       LARCV_ERROR() << "Could not open input images." << std::endl;
       return false;
     }
     if ( !event_relabel_segment )  {
       LARCV_ERROR() << "Could not open output image holder." << std::endl;
       return false;
     }
     std::vector< larcv::Image2D> image_v;
     event_original_segment->Move(image_v ); // original moves ownership of its image vectors to us
     std::vector< larcv::Image2D > relabel_image_v; // space for new images if we are not working in place
     std::vector<float> _buffer;
     for ( size_t i=0; i<image_v.size(); ++i ) {
       // get access to the data
       larcv::Image2D& original_image = image_v[i];
       auto const& labels = original_image.as_vector();
       // make a space for the relabeling
       _buffer.resize( labels.size(), 0.0 ); //
       // do the relabeling
       for (size_t ival=0; ival<labels.size(); ival++) {
     int label=std::floor( labels.at(ival)+0.5 );
     int relabel=fOrigToNewMap[label];
     _buffer.at(ival) = (float)relabel;
       }
       // now place it
       if ( inplace ) {
     // if in place, we copy it back into the old data
     original_image.copy(0,0,_buffer,_buffer.size());
       }
       else {
     // else we make a new one and put it into the new relabeled iamge vector
     Image2D img( original_image.meta(), _buffer );
     relabel_image_v.emplace_back( std::move(img) );
       }
     }
     // store
     // no matter what, give the image vector back to the original event2d container
     event_original_segment->Emplace( std::move(image_v) );
     if (!inplace) {
       // if not inplace, we give the new image2d container our relabeled images
       event_relabel_segment->Emplace( std::move(relabel_image_v) );
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fInputSegmentProducer
std::string larcv::SegmentRelabel::fInputSegmentProducer protected
Definition at line 52 of file SegmentRelabel.h.
Referenced by configure(), and process().
fOrigToNewMap
std::map<int,int> larcv::SegmentRelabel::fOrigToNewMap protected
Definition at line 54 of file SegmentRelabel.h.
Referenced by configure(), and process().
fOutputSegmentProducer
std::string larcv::SegmentRelabel::fOutputSegmentProducer protected
Definition at line 53 of file SegmentRelabel.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
SegmentRelabel.h
SegmentRelabel.cxx