LArCV: larcv::Compressor Class Reference
larcv::Compressor Class Reference
#include <Compressor.h>
Public Member Functions
Compressor (const std::string name="Compressor")
Default constructor.
~Compressor ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< std::string > _image_producer_v
std::vector< size_t > _row_compression_v
std::vector< size_t > _col_compression_v
std::vector< larcv::Image2D::CompressionModes_t > _mode_v
Detailed Description
Definition at line 27 of file Compressor.h.
Constructor & Destructor Documentation
Compressor()
larcv::Compressor::Compressor (const std::string name = "Compressor")
Default constructor.
Definition at line 11 of file Compressor.cxx.
Referenced by larcv::CompressorProcessFactory::create().
     : ProcessBase(name)
   {}
~Compressor()
larcv::Compressor::~Compressor () inline
Default destructor.
Definition at line 35 of file Compressor.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::Compressor::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file Compressor.cxx.
References _col_compression_v, _image_producer_v, _mode_v, _row_compression_v, larcv::PSet::get(), and LARCV_CRITICAL.
Referenced by ~Compressor().
   {
     _image_producer_v  = cfg.get<std::vector<std::string> >("ImageProducer");
     _row_compression_v = cfg.get<std::vector<size_t     > >("RowCompression");
     _col_compression_v = cfg.get<std::vector<size_t     > >("ColCompression");
     auto mode_v = cfg.get<std::vector<unsigned short> >("Mode");
     _mode_v.clear();
     for(auto const& v : mode_v) _mode_v.push_back( (Image2D::CompressionModes_t)v );
     if(_mode_v.size() != _image_producer_v.size()  ||
        _mode_v.size() != _row_compression_v.size() ||
        _mode_v.size() != _col_compression_v.size() ) {
       LARCV_CRITICAL() << "Length of parameter arrays do not match!" << std::endl;
       throw larbys();
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::Compressor::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 113 of file Compressor.cxx.
Referenced by ~Compressor().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::Compressor::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 33 of file Compressor.cxx.
References _col_compression_v, _image_producer_v, _mode_v, _row_compression_v, and LARCV_CRITICAL.
Referenced by ~Compressor().
   {
     for(size_t i=0; i<_mode_v.size(); ++i) {
       auto const& image_producer  = _image_producer_v[i];
       auto const& row_compression = _row_compression_v[i];
       auto const& col_compression = _col_compression_v[i];
       if(!row_compression) {
     LARCV_CRITICAL() << "Row compression factor is 0 (undefined)!" << std::endl;
     throw larbys();
       }
       if(!col_compression) {
     LARCV_CRITICAL() << "Col compression factor is 0 (undefined)!" << std::endl;
     throw larbys();
       }
       if(image_producer.empty()) {
     LARCV_CRITICAL() << "Image producer not specified!" << std::endl;
     throw larbys();
       }
     }
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::Compressor::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 56 of file Compressor.cxx.
References _col_compression_v, _image_producer_v, _mode_v, _row_compression_v, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, and LARCV_CRITICAL.
Referenced by ~Compressor().
   {
     // Check if compression factor works
     for(size_t i=0; i<_mode_v.size(); ++i) {
       auto const& image_producer  = _image_producer_v[i];
       auto const& row_compression = _row_compression_v[i];
       auto const& col_compression = _col_compression_v[i];
       auto ev_image = (EventImage2D*)(mgr.get_data(kProductImage2D,image_producer));
       if(!ev_image) {
     LARCV_CRITICAL() << "Input image not found by producer name " << image_producer << std::endl;
     throw larbys();
       }
       for(auto const& img : ev_image->Image2DArray()) {
     auto const& meta = img.meta();
     if(meta.rows() % row_compression) {
       LARCV_CRITICAL() << "Input image # rows (" << meta.rows()
                << ") cannot be divide by compression factor (" << row_compression
                << ")" << std::endl;
       throw larbys();
     }
     if(meta.cols() % col_compression) {
       LARCV_CRITICAL() << "Input image # cols (" << meta.cols()
                << ") cannot be divide by compression factor (" << col_compression
                << ")" << std::endl;
       throw larbys();
     }
       }
     }
     // Apply compression
     for(size_t i=0; i<_mode_v.size(); ++i) {
       auto const& image_producer  = _image_producer_v[i];
       auto const& row_compression = _row_compression_v[i];
       auto const& col_compression = _col_compression_v[i];
       auto const& mode = _mode_v[i];
       auto ev_image = (EventImage2D*)(mgr.get_data(kProductImage2D,image_producer));
       std::vector<larcv::Image2D> image_v;
       ev_image->Move(image_v);
       for(auto& img : image_v) {
     img.compress( img.meta().rows() / row_compression,
               img.meta().cols() / col_compression,
               mode );
       }
       ev_image->Emplace(std::move(image_v));
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_col_compression_v
std::vector<size_t > larcv::Compressor::_col_compression_v private
Definition at line 49 of file Compressor.h.
Referenced by configure(), initialize(), and process().
_image_producer_v
std::vector<std::string> larcv::Compressor::_image_producer_v private
Definition at line 47 of file Compressor.h.
Referenced by configure(), initialize(), and process().
_mode_v
std::vector<larcv::Image2D::CompressionModes_t> larcv::Compressor::_mode_v private
Definition at line 50 of file Compressor.h.
Referenced by configure(), initialize(), and process().
_row_compression_v
std::vector<size_t > larcv::Compressor::_row_compression_v private
Definition at line 48 of file Compressor.h.
Referenced by configure(), initialize(), and process().
The documentation for this class was generated from the following files:
Compressor.h
Compressor.cxx