LArCV: larcv::SuperaHitProcessFactory Class Reference
larcv::SuperaHitProcessFactory Class Reference
#include <SuperaHit.h>
Public Member Functions
SuperaHitProcessFactory ()
ctor
~SuperaHitProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 57 of file SuperaHit.h.
Constructor & Destructor Documentation
SuperaHitProcessFactory()
larcv::SuperaHitProcessFactory::SuperaHitProcessFactory () inline
ctor
Definition at line 60 of file SuperaHit.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SuperaHit",this); }
~SuperaHitProcessFactory()
larcv::SuperaHitProcessFactory::~SuperaHitProcessFactory () inline
dtor
Definition at line 62 of file SuperaHit.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SuperaHitProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 64 of file SuperaHit.h.
References larcv::SuperaHit::SuperaHit().
 { return new SuperaHit(instance_name); }
The documentation for this class was generated from the following file:
SuperaHit.h