LArCV: larcv::EmbedImageProcessFactory Class Reference
larcv::EmbedImageProcessFactory Class Reference
#include <EmbedImage.h>
Public Member Functions
EmbedImageProcessFactory ()
ctor
~EmbedImageProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 61 of file EmbedImage.h.
Constructor & Destructor Documentation
EmbedImageProcessFactory()
larcv::EmbedImageProcessFactory::EmbedImageProcessFactory () inline
ctor
Definition at line 64 of file EmbedImage.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("EmbedImage",this); }
~EmbedImageProcessFactory()
larcv::EmbedImageProcessFactory::~EmbedImageProcessFactory () inline
dtor
Definition at line 66 of file EmbedImage.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::EmbedImageProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 68 of file EmbedImage.h.
References larcv::EmbedImage::EmbedImage().
 { return new EmbedImage(instance_name); }
The documentation for this class was generated from the following file:
EmbedImage.h