LArCV: larcv::CompressorProcessFactory Class Reference
larcv::CompressorProcessFactory Class Reference
#include <Compressor.h>
Public Member Functions
CompressorProcessFactory ()
ctor
~CompressorProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 58 of file Compressor.h.
Constructor & Destructor Documentation
CompressorProcessFactory()
larcv::CompressorProcessFactory::CompressorProcessFactory () inline
ctor
Definition at line 61 of file Compressor.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("Compressor",this); }
~CompressorProcessFactory()
larcv::CompressorProcessFactory::~CompressorProcessFactory () inline
dtor
Definition at line 63 of file Compressor.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::CompressorProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 65 of file Compressor.h.
References larcv::Compressor::Compressor().
 { return new Compressor(instance_name); }
The documentation for this class was generated from the following file:
Compressor.h