LArCV: larcv::LArbysImageAna Class Reference
larcv::LArbysImageAna Class Reference
#include <LArbysImageAna.h>
Public Member Functions
LArbysImageAna (const std::string name="LArbysImageAna")
~LArbysImageAna ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void SetInputLArbysRecoFile (std::string file)
void SetInputLArbysMCFile (std::string file)
const larocv::data::Vertex3D & TrueVertex ()
const std::vector< larocv::data::Vertex3D > & Verticies ()
const larocv::data::Vertex3D & Vertex (size_t vertexid)
const std::vector< std::vector< std::vector< larocv::data::ParticleCluster > > > & VertexPlaneParticles (size_t vertexid)
const std::vector< std::vector< larocv::data::ParticleCluster > > & PlaneParticles (size_t vertexid)
const std::vector< larocv::data::ParticleCluster > & Particles (size_t vertexid, size_t planeid)
const std::vector< std::vector< std::vector< larocv::data::TrackClusterCompound > > > & VertexPlaneTracks (size_t vertexid)
const std::vector< std::vector< larocv::data::TrackClusterCompound > > & PlaneTracks (size_t vertexid)
const std::vector< larocv::data::TrackClusterCompound > & Tracks (size_t vertexid, size_t planeid)
const std::string GetMCTreeName ()
const std::string GetMCRootName ()
const std::string GetRecoRootName ()
const uint GetEvent ()
const uint GetSubrun ()
const uint GetRun ()
const uint GetEntry ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
bool increment (uint entry)
Private Attributes
std::string _mc_tree_name
std::string _reco_tree_name
std::string _input_larbys_reco_root_file
std::string _input_larbys_mc_root_file
TChain * _mc_chain
TChain * _reco_chain
size_t _mc_entries
size_t _reco_entries
uint _mc_event
uint _mc_entry
uint _mc_run
uint _mc_subrun
uint _reco_event
uint _reco_entry
uint _reco_run
uint _reco_subrun
size_t _mc_index
size_t _reco_index
bool _mc_exists
std::vector< larocv::data::Vertex3D > * _reco_vertex_v
std::vector< std::vector< std::vector< larocv::data::ParticleCluster > > > * _particle_cluster_vvv
std::vector< std::vector< std::vector< larocv::data::TrackClusterCompound > > > * _track_cluster_comp_vvv
larocv::data::Vertex3D _mc_vertex
double _true_x
double _true_y
double _true_z
std::vector< double > * _vtx2d_w_v
std::vector< double > * _vtx2d_t_v
Detailed Description
Definition at line 12 of file LArbysImageAna.h.
Constructor & Destructor Documentation
LArbysImageAna()
larcv::LArbysImageAna::LArbysImageAna (const std::string name = "LArbysImageAna")
Definition at line 10 of file LArbysImageAna.cxx.
Referenced by larcv::LArbysImageAnaProcessFactory::create().
     : ProcessBase(name),
       _mc_chain(nullptr),
       _reco_chain(nullptr),
       _vtx2d_w_v(nullptr),
       _vtx2d_t_v(nullptr),
       _reco_vertex_v(nullptr),
       _particle_cluster_vvv(nullptr),
       _track_cluster_comp_vvv(nullptr)
   {}
~LArbysImageAna()
larcv::LArbysImageAna::~LArbysImageAna () inline
Definition at line 16 of file LArbysImageAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::LArbysImageAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 21 of file LArbysImageAna.cxx.
References _mc_exists, _mc_tree_name, _reco_tree_name, and larcv::PSet::get().
Referenced by ~LArbysImageAna().
   {
     _mc_tree_name = cfg.get<std::string>("MCTreeName");
     _reco_tree_name = cfg.get<std::string>("RecoTreeName");
     _mc_exists = cfg.get<bool>("MCExists");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImageAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 121 of file LArbysImageAna.cxx.
Referenced by ~LArbysImageAna().
   {}
GetEntry()
const uint larcv::LArbysImageAna::GetEntry () inline
Definition at line 86 of file LArbysImageAna.h.
References _mc_entry, _mc_exists, and _reco_entry.
{
       if (_mc_entry!=_reco_entry && _mc_exists) throw larbys("Invalid mc-reco alignment");
       return _mc_exists ? _mc_entry : _reco_entry;
     }
GetEvent()
const uint larcv::LArbysImageAna::GetEvent () inline
Definition at line 74 of file LArbysImageAna.h.
References _mc_event, _mc_exists, and _reco_event.
{
       if (_mc_event!=_reco_event && _mc_exists) throw larbys("Invalid mc-reco alignment");
       return _mc_exists ? _mc_event : _reco_event;
     }
GetMCRootName()
const std::string larcv::LArbysImageAna::GetMCRootName () inline
Definition at line 68 of file LArbysImageAna.h.
References _input_larbys_mc_root_file.
     { return _input_larbys_mc_root_file; }
GetMCTreeName()
const std::string larcv::LArbysImageAna::GetMCTreeName () inline
Definition at line 65 of file LArbysImageAna.h.
References _mc_tree_name.
Referenced by larcv::LArbysImageFilter::finalize().
     { return _mc_tree_name; }
GetRecoRootName()
const std::string larcv::LArbysImageAna::GetRecoRootName () inline
Definition at line 71 of file LArbysImageAna.h.
References _input_larbys_reco_root_file.
     { return _input_larbys_reco_root_file; }
GetRun()
const uint larcv::LArbysImageAna::GetRun () inline
Definition at line 82 of file LArbysImageAna.h.
References _mc_exists, _mc_run, and _reco_run.
{
       if (_mc_run!=_reco_run && _mc_exists) throw larbys("Invalid mc-reco alignment");
       return _mc_exists ? _mc_run : _reco_run;
     }
GetSubrun()
const uint larcv::LArbysImageAna::GetSubrun () inline
Definition at line 78 of file LArbysImageAna.h.
References _mc_exists, _mc_subrun, and _reco_subrun.
{
       if (_mc_subrun!=_reco_subrun && _mc_exists) throw larbys("Invalid mc-reco alignment");
       return _mc_exists ? _mc_subrun : _reco_subrun;
     }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
increment()
bool larcv::LArbysImageAna::increment (uint entry) private
Definition at line 68 of file LArbysImageAna.cxx.
References _mc_chain, _mc_entries, _mc_entry, _mc_exists, _mc_index, _reco_chain, _reco_entries, _reco_entry, and _reco_index.
Referenced by process().
   {
     if(_mc_exists)
       _mc_chain->GetEntry(_mc_index);
     _reco_chain->GetEntry(_reco_index);
     if ((_mc_entry   <= entry) && (_mc_index   != _mc_entries))   { _mc_index++;   }
     if ((_reco_entry <= entry) && (_reco_index != _reco_entries)) { _reco_index++; }
     if ( entry     != _reco_entry) return false;
     if (_mc_exists) {
       if ( entry     !=  _mc_entry ) return false;
       if ( _mc_entry != _reco_entry) return false;
     }
     return true;
   }
initialize()
void larcv::LArbysImageAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 28 of file LArbysImageAna.cxx.
References _input_larbys_mc_root_file, _input_larbys_reco_root_file, _mc_chain, _mc_entries, _mc_entry, _mc_event, _mc_exists, _mc_index, _mc_run, _mc_subrun, _mc_tree_name, _particle_cluster_vvv, _reco_chain, _reco_entries, _reco_entry, _reco_event, _reco_index, _reco_run, _reco_subrun, _reco_tree_name, _reco_vertex_v, _track_cluster_comp_vvv, _true_x, _true_y, _true_z, _vtx2d_t_v, _vtx2d_w_v, and LARCV_DEBUG.
Referenced by ~LArbysImageAna().
   {
     if (_mc_exists) {
       if (_input_larbys_mc_root_file.empty()) throw larbys("No input root file specified");
       LARCV_DEBUG() << "Setting input MC ROOT file: " << _input_larbys_mc_root_file << std::endl;
       _mc_chain = new TChain(_mc_tree_name.c_str());
       _mc_chain->AddFile(_input_larbys_mc_root_file.c_str());
       _mc_chain->SetBranchAddress("run",&_mc_run);
       _mc_chain->SetBranchAddress("subrun",&_mc_subrun);
       _mc_chain->SetBranchAddress("event",&_mc_event);
       _mc_chain->SetBranchAddress("entry",&_mc_entry);
       _mc_chain->SetBranchAddress("parentX",&_true_x);
       _mc_chain->SetBranchAddress("parentY",&_true_y);
       _mc_chain->SetBranchAddress("parentZ",&_true_z);
       _mc_chain->SetBranchAddress("vtx2d_w",&_vtx2d_w_v);
       _mc_chain->SetBranchAddress("vtx2d_t",&_vtx2d_t_v);
       _mc_index=0;
       _mc_chain->GetEntry(_mc_index);
       _mc_entries = _mc_chain->GetEntries();
       LARCV_DEBUG() << "Got " << _reco_entries << " mc entries" << std::endl;
     }
     if (_input_larbys_reco_root_file.empty()) throw larbys("No input root file specified");
     LARCV_DEBUG() << "Setting input Reco ROOT file: " << _input_larbys_reco_root_file << std::endl;
     _reco_chain = new TChain(_reco_tree_name.c_str());
     _reco_chain->AddFile(_input_larbys_reco_root_file.c_str());
     _reco_chain->SetBranchAddress("run",&_reco_run);
     _reco_chain->SetBranchAddress("subrun",&_reco_subrun);
     _reco_chain->SetBranchAddress("event",&_reco_event);
     _reco_chain->SetBranchAddress("entry",&_reco_entry);
     _reco_chain->SetBranchAddress("Vertex3D_v",&_reco_vertex_v);
     _reco_chain->SetBranchAddress("ParticleCluster_vvv",&_particle_cluster_vvv);
     _reco_chain->SetBranchAddress("TrackClusterCompound_vvv",&_track_cluster_comp_vvv);
     _reco_index=0;
     _reco_chain->GetEntry(_reco_index);
     _reco_entries = _reco_chain->GetEntries();
     LARCV_DEBUG() << "Got " << _reco_entries << " reco entries" << std::endl;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
Particles()
const std::vector<larocv::data::ParticleCluster>& larcv::LArbysImageAna::Particles (size_t vertexid, size_t planeid) inline
Definition at line 50 of file LArbysImageAna.h.
References _particle_cluster_vvv.
Referenced by larcv::LArbysImageFilter::process(), and larcv::LArbysImageFilter::WriteOut().
     { return (*_particle_cluster_vvv)[vertexid][planeid]; }
PlaneParticles()
const std::vector<std::vector<larocv::data::ParticleCluster> >& larcv::LArbysImageAna::PlaneParticles (size_t vertexid) inline
Definition at line 46 of file LArbysImageAna.h.
References _particle_cluster_vvv.
Referenced by larcv::LArbysImageFilter::WriteOut().
     { return (*_particle_cluster_vvv)[vertexid]; }
PlaneTracks()
const std::vector<std::vector<larocv::data::TrackClusterCompound> >& larcv::LArbysImageAna::PlaneTracks (size_t vertexid) inline
Definition at line 58 of file LArbysImageAna.h.
References _track_cluster_comp_vvv.
Referenced by larcv::LArbysImageFilter::WriteOut().
     { return (*_track_cluster_comp_vvv)[vertexid]; }
process()
bool larcv::LArbysImageAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 86 of file LArbysImageAna.cxx.
References _mc_entry, _mc_exists, _mc_index, _mc_vertex, _reco_entry, _reco_index, _true_x, _true_y, _true_z, _vtx2d_w_v, larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::event_id(), increment(), LARCV_DEBUG, and larcv::EventBase::run().
Referenced by ~LArbysImageAna().
   {
     uint entry = mgr.current_entry();
     LARCV_DEBUG() << "(this,mc,reco) entry & index @ (" << entry <<","<<_mc_entry<<","<<_reco_entry<<")"
           << " & " << "(-,"<<_mc_index<<","<<_reco_index<<")"<<std::endl;
     if ( !increment(entry) ) return false;
     const auto& event_id = mgr.event_id();
     auto run    = event_id.run();
     auto subrun = event_id.subrun();
     auto event  = event_id.event();
     LARCV_DEBUG()<<"Passed @ (r,s,e,e) -- ["<<run<<","<<subrun<<","<<event<<","<<entry<<"]"<<std::endl;
     if (!_mc_exists)
       return true;
     _mc_vertex._Clear_();
     _mc_vertex.x=_true_x;
     _mc_vertex.y=_true_y;
     _mc_vertex.z=_true_z;
     _mc_vertex.vtx2d_v.clear();
     for(size_t plane=0;plane<_vtx2d_w_v->size();++plane) {
       larocv::data::Vertex2D vtx2d;
       vtx2d.pt.x=(*_vtx2d_t_v)[plane];
       vtx2d.pt.y=(*_vtx2d_w_v)[plane];
       _mc_vertex.vtx2d_v.emplace_back(std::move(vtx2d));
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetInputLArbysMCFile()
void larcv::LArbysImageAna::SetInputLArbysMCFile (std::string file) inline
Definition at line 26 of file LArbysImageAna.h.
References _input_larbys_mc_root_file.
     { _input_larbys_mc_root_file = file; }
SetInputLArbysRecoFile()
void larcv::LArbysImageAna::SetInputLArbysRecoFile (std::string file) inline
Definition at line 23 of file LArbysImageAna.h.
References _input_larbys_reco_root_file.
     { _input_larbys_reco_root_file = file; }
Tracks()
const std::vector<larocv::data::TrackClusterCompound>& larcv::LArbysImageAna::Tracks (size_t vertexid, size_t planeid) inline
Definition at line 62 of file LArbysImageAna.h.
References _track_cluster_comp_vvv.
     { return (*_track_cluster_comp_vvv)[vertexid][planeid]; }
TrueVertex()
const larocv::data::Vertex3D& larcv::LArbysImageAna::TrueVertex () inline
Definition at line 30 of file LArbysImageAna.h.
References _mc_vertex.
     { return _mc_vertex; }
Vertex()
const larocv::data::Vertex3D& larcv::LArbysImageAna::Vertex (size_t vertexid) inline
Definition at line 38 of file LArbysImageAna.h.
References _reco_vertex_v.
Referenced by larcv::LArbysImageFilter::process(), and larcv::LArbysImageFilter::WriteOut().
     { return (*_reco_vertex_v)[vertexid]; }
VertexPlaneParticles()
const std::vector<std::vector<std::vector<larocv::data::ParticleCluster> > >& larcv::LArbysImageAna::VertexPlaneParticles (size_t vertexid) inline
Definition at line 42 of file LArbysImageAna.h.
References _particle_cluster_vvv.
     { return (*_particle_cluster_vvv); }
VertexPlaneTracks()
const std::vector<std::vector<std::vector<larocv::data::TrackClusterCompound> > >& larcv::LArbysImageAna::VertexPlaneTracks (size_t vertexid) inline
Definition at line 54 of file LArbysImageAna.h.
References _track_cluster_comp_vvv.
     { return (*_track_cluster_comp_vvv); }
Verticies()
const std::vector<larocv::data::Vertex3D>& larcv::LArbysImageAna::Verticies () inline
Definition at line 34 of file LArbysImageAna.h.
References _reco_vertex_v.
Referenced by larcv::LArbysImageFilter::ClearEvent(), larcv::LArbysImageFilter::process(), and larcv::LArbysImageOut::process().
     { return *_reco_vertex_v; }
Member Data Documentation
_input_larbys_mc_root_file
std::string larcv::LArbysImageAna::_input_larbys_mc_root_file private
Definition at line 95 of file LArbysImageAna.h.
Referenced by GetMCRootName(), initialize(), and SetInputLArbysMCFile().
_input_larbys_reco_root_file
std::string larcv::LArbysImageAna::_input_larbys_reco_root_file private
Definition at line 94 of file LArbysImageAna.h.
Referenced by GetRecoRootName(), initialize(), and SetInputLArbysRecoFile().
_mc_chain
TChain* larcv::LArbysImageAna::_mc_chain private
Definition at line 97 of file LArbysImageAna.h.
Referenced by increment(), and initialize().
_mc_entries
size_t larcv::LArbysImageAna::_mc_entries private
Definition at line 100 of file LArbysImageAna.h.
Referenced by increment(), and initialize().
_mc_entry
uint larcv::LArbysImageAna::_mc_entry private
Definition at line 104 of file LArbysImageAna.h.
Referenced by GetEntry(), increment(), initialize(), and process().
_mc_event
uint larcv::LArbysImageAna::_mc_event private
Definition at line 103 of file LArbysImageAna.h.
Referenced by GetEvent(), and initialize().
_mc_exists
bool larcv::LArbysImageAna::_mc_exists private
Definition at line 118 of file LArbysImageAna.h.
Referenced by configure(), GetEntry(), GetEvent(), GetRun(), GetSubrun(), increment(), initialize(), and process().
_mc_index
size_t larcv::LArbysImageAna::_mc_index private
Definition at line 113 of file LArbysImageAna.h.
Referenced by increment(), initialize(), and process().
_mc_run
uint larcv::LArbysImageAna::_mc_run private
Definition at line 105 of file LArbysImageAna.h.
Referenced by GetRun(), and initialize().
_mc_subrun
uint larcv::LArbysImageAna::_mc_subrun private
Definition at line 106 of file LArbysImageAna.h.
Referenced by GetSubrun(), and initialize().
_mc_tree_name
std::string larcv::LArbysImageAna::_mc_tree_name private
Definition at line 92 of file LArbysImageAna.h.
Referenced by configure(), GetMCTreeName(), and initialize().
_mc_vertex
larocv::data::Vertex3D larcv::LArbysImageAna::_mc_vertex private
Definition at line 124 of file LArbysImageAna.h.
Referenced by process(), and TrueVertex().
_particle_cluster_vvv
std::vector<std::vector<std::vector<larocv::data::ParticleCluster> > >* larcv::LArbysImageAna::_particle_cluster_vvv private
Definition at line 121 of file LArbysImageAna.h.
Referenced by initialize(), Particles(), PlaneParticles(), and VertexPlaneParticles().
_reco_chain
TChain* larcv::LArbysImageAna::_reco_chain private
Definition at line 98 of file LArbysImageAna.h.
Referenced by increment(), and initialize().
_reco_entries
size_t larcv::LArbysImageAna::_reco_entries private
Definition at line 101 of file LArbysImageAna.h.
Referenced by increment(), and initialize().
_reco_entry
uint larcv::LArbysImageAna::_reco_entry private
Definition at line 109 of file LArbysImageAna.h.
Referenced by GetEntry(), increment(), initialize(), and process().
_reco_event
uint larcv::LArbysImageAna::_reco_event private
Definition at line 108 of file LArbysImageAna.h.
Referenced by GetEvent(), and initialize().
_reco_index
size_t larcv::LArbysImageAna::_reco_index private
Definition at line 114 of file LArbysImageAna.h.
Referenced by increment(), initialize(), and process().
_reco_run
uint larcv::LArbysImageAna::_reco_run private
Definition at line 110 of file LArbysImageAna.h.
Referenced by GetRun(), and initialize().
_reco_subrun
uint larcv::LArbysImageAna::_reco_subrun private
Definition at line 111 of file LArbysImageAna.h.
Referenced by GetSubrun(), and initialize().
_reco_tree_name
std::string larcv::LArbysImageAna::_reco_tree_name private
Definition at line 93 of file LArbysImageAna.h.
Referenced by configure(), and initialize().
_reco_vertex_v
std::vector<larocv::data::Vertex3D>* larcv::LArbysImageAna::_reco_vertex_v private
Definition at line 120 of file LArbysImageAna.h.
Referenced by initialize(), Vertex(), and Verticies().
_track_cluster_comp_vvv
std::vector<std::vector<std::vector<larocv::data::TrackClusterCompound> > >* larcv::LArbysImageAna::_track_cluster_comp_vvv private
Definition at line 122 of file LArbysImageAna.h.
Referenced by initialize(), PlaneTracks(), Tracks(), and VertexPlaneTracks().
_true_x
double larcv::LArbysImageAna::_true_x private
Definition at line 125 of file LArbysImageAna.h.
Referenced by initialize(), and process().
_true_y
double larcv::LArbysImageAna::_true_y private
Definition at line 126 of file LArbysImageAna.h.
Referenced by initialize(), and process().
_true_z
double larcv::LArbysImageAna::_true_z private
Definition at line 127 of file LArbysImageAna.h.
Referenced by initialize(), and process().
_vtx2d_t_v
std::vector<double>* larcv::LArbysImageAna::_vtx2d_t_v private
Definition at line 129 of file LArbysImageAna.h.
Referenced by initialize().
_vtx2d_w_v
std::vector<double>* larcv::LArbysImageAna::_vtx2d_w_v private
Definition at line 128 of file LArbysImageAna.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
LArbysImageAna.h
LArbysImageAna.cxx