LArCV: larcv::RunFilter Class Reference
larcv::RunFilter Class Reference
#include <RunFilter.h>
Public Member Functions
RunFilter (const std::string name="RunFilter")
Default constructor.
~RunFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::set< size_t > _run_s
a set of runs to be filtered out
std::string _producer
a producer name
ProductType_t _type
a product type
Detailed Description
Definition at line 26 of file RunFilter.h.
Constructor & Destructor Documentation
RunFilter()
larcv::RunFilter::RunFilter (const std::string name = "RunFilter")
Default constructor.
Definition at line 10 of file RunFilter.cxx.
Referenced by larcv::RunFilterProcessFactory::create().
     : ProcessBase(name)
   {}
~RunFilter()
larcv::RunFilter::~RunFilter () inline
Default destructor.
Definition at line 34 of file RunFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::RunFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file RunFilter.cxx.
References _producer, _run_s, _type, larcv::PSet::get(), and LARCV_WARNING.
Referenced by ~RunFilter().
   {
     _producer   = cfg.get<std::string>("Producer");
     _type       = (ProductType_t)(cfg.get<unsigned short>("ProductType"));
     auto run_v = cfg.get<std::vector<size_t> >("Exclude");
     for(auto const& v : run_v) {
       if(_run_s.find(v) != _run_s.end()) {
     LARCV_WARNING() << "Run " << v << " appears more than once in the list..." << std::endl;
     continue;
       }
       _run_s.insert(v);
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::RunFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 37 of file RunFilter.cxx.
Referenced by ~RunFilter().
   { return; }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::RunFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 28 of file RunFilter.cxx.
Referenced by ~RunFilter().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::RunFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 31 of file RunFilter.cxx.
References _producer, _run_s, _type, and larcv::IOManager< T >::get_data().
Referenced by ~RunFilter().
   {
     auto ptr = mgr.get_data(_type,_producer);
     return (_run_s.find(ptr->run()) == _run_s.end());
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_producer
std::string larcv::RunFilter::_producer private
a producer name
Definition at line 46 of file RunFilter.h.
Referenced by configure(), and process().
_run_s
std::set<size_t> larcv::RunFilter::_run_s private
a set of runs to be filtered out
Definition at line 45 of file RunFilter.h.
Referenced by configure(), and process().
_type
ProductType_t larcv::RunFilter::_type private
a product type
Definition at line 47 of file RunFilter.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
RunFilter.h
RunFilter.cxx