LArCV: larcv::SegmentMask Class Reference
larcv::SegmentMask Class Reference
#include <SegmentMask.h>
Public Member Functions
SegmentMask (const std::string name="SegmentMask")
Default constructor.
~SegmentMask ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< larcv::ROIType_t > _valid_roi_v
ROIType_t _mask_value
std::string _image_producer
std::string _output_producer
std::string _roi_producer
std::vector< unsigned short > _plane_v
Detailed Description
Definition at line 26 of file SegmentMask.h.
Constructor & Destructor Documentation
SegmentMask()
larcv::SegmentMask::SegmentMask (const std::string name = "SegmentMask")
Default constructor.
Definition at line 13 of file SegmentMask.cxx.
References _output_producer.
Referenced by larcv::SegmentMaskProcessFactory::create().
     : ProcessBase(name)
   {
     _output_producer = "";
   }
~SegmentMask()
larcv::SegmentMask::~SegmentMask () inline
Default destructor.
Definition at line 34 of file SegmentMask.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SegmentMask::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file SegmentMask.cxx.
References _image_producer, _mask_value, _output_producer, _plane_v, _roi_producer, _valid_roi_v, larcv::PSet::get(), larcv::kROIUnknown, LARCV_CRITICAL, larcv::larcv_base::name(), and larcv::String2ROIType().
Referenced by ~SegmentMask().
   {
     _roi_producer = cfg.get<std::string>("ROIProducer","");
     _output_producer = cfg.get<std::string>("OutputProducer","");
     _valid_roi_v.clear();
     auto valid_roi = cfg.get<std::vector<std::string> >("ValidROI");
     for(auto const& name : valid_roi) {
       auto const roi_type = String2ROIType(name);
       if(roi_type == kROIUnknown) {
     LARCV_CRITICAL() << "Invalid ROI type name provided: " << name << std::endl;
     throw larbys();
       }
       _valid_roi_v.push_back((ROIType_t)roi_type);
     }
     if(_valid_roi_v.empty() && _roi_producer.empty()) {
       LARCV_CRITICAL() << "No valid ROI type nor ROI producer name provided!" << std::endl;
       throw larbys();
     }
     _mask_value = (ROIType_t)(cfg.get<unsigned short>("MaskValue",(unsigned short)(kROIUnknown)));
     _image_producer = cfg.get<std::string>("ImageProducer");
     _plane_v = cfg.get<std::vector<unsigned short> >("PlaneID");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SegmentMask::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 130 of file SegmentMask.cxx.
Referenced by ~SegmentMask().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SegmentMask::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 42 of file SegmentMask.cxx.
Referenced by ~SegmentMask().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SegmentMask::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 45 of file SegmentMask.cxx.
References _image_producer, _mask_value, _output_producer, _plane_v, _roi_producer, _valid_roi_v, larcv::EventImage2D::Emplace(), larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::kProductImage2D, larcv::kProductROI, larcv::kROITypeMax, LARCV_CRITICAL, LARCV_WARNING, and larcv::EventImage2D::Move().
Referenced by ~SegmentMask().
   {
     auto event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_image_producer));
     if(!event_image) {
       LARCV_CRITICAL() << "EventImage2D not found: " << _image_producer << std::endl;
       throw larbys();
     }
     EventImage2D* output_event_image = nullptr;
     std::vector<Image2D> image_v;
     if(_output_producer.empty()) {
       event_image->Move(image_v);
       output_event_image = event_image;
     }
     else {
       output_event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_output_producer));
       if(!output_event_image) {
     LARCV_CRITICAL() << "Failed to create an output data product w/ name " <<_output_producer << std::endl;
     throw larbys();
       }
       if(output_event_image->Image2DArray().size()) {
     LARCV_CRITICAL() << "Output producer not empty! " << _output_producer << std::endl;
     throw larbys();
       }
       image_v = event_image->Image2DArray();
     }
     std::vector<bool> valid_roi_v(kROITypeMax,false);
     if(!_roi_producer.empty()) {
       auto event_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_producer));
       if(!event_roi) {
     LARCV_CRITICAL() << "EventROI not found: " << _roi_producer << std::endl;
     throw larbys();
       }
       for(auto const& roi : event_roi->ROIArray())
     valid_roi_v[roi.Type()] = true;
     }
     for(auto const& roi : _valid_roi_v) valid_roi_v[roi] = true;
     // Plane ID sanity check
     for(auto const& pid : _plane_v) {
       if(pid < image_v.size()) continue;
       LARCV_CRITICAL() << "Plane ID " << pid << " does not exist!" << std::endl;
       throw larbys();
     }
     for(auto const& pid : _plane_v) {
       auto& image = image_v[pid];
       auto const& data = image.as_vector();
       for(size_t px_idx=0; px_idx < data.size(); ++px_idx) {
     if(data[px_idx]>=valid_roi_v.size()) {
       LARCV_WARNING() << "Masking an invalid segment value " << data[px_idx] << " @ " << px_idx << std::endl;
       image.set_pixel(px_idx,_mask_value);
     }
     else if(!valid_roi_v[(size_t)(data[px_idx])])
       image.set_pixel(px_idx,_mask_value);
       }
       size_t pixel_val;
       for(size_t px_idx=0; px_idx < data.size(); ++px_idx) {
     if(data[px_idx]<0) image.set_pixel(px_idx,_mask_value);
     else{
       pixel_val = (size_t)(data[px_idx]);
       if(pixel_val >= valid_roi_v.size() || !valid_roi_v[pixel_val])
         image.set_pixel(px_idx,_mask_value);
     }
       }
     }
     output_event_image->Emplace(std::move(image_v));
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_image_producer
std::string larcv::SegmentMask::_image_producer private
Definition at line 50 of file SegmentMask.h.
Referenced by configure(), and process().
_mask_value
ROIType_t larcv::SegmentMask::_mask_value private
Definition at line 48 of file SegmentMask.h.
Referenced by configure(), and process().
_output_producer
std::string larcv::SegmentMask::_output_producer private
Definition at line 52 of file SegmentMask.h.
Referenced by configure(), process(), and SegmentMask().
_plane_v
std::vector<unsigned short> larcv::SegmentMask::_plane_v private
Definition at line 56 of file SegmentMask.h.
Referenced by configure(), and process().
_roi_producer
std::string larcv::SegmentMask::_roi_producer private
Definition at line 54 of file SegmentMask.h.
Referenced by configure(), and process().
_valid_roi_v
std::vector<larcv::ROIType_t> larcv::SegmentMask::_valid_roi_v private
Definition at line 46 of file SegmentMask.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
SegmentMask.h
SegmentMask.cxx