LArCV: larcv::EventROI Class Reference
larcv::EventROI Class Reference
Event-wise class to store a collection of larcv::ROI.
#include <EventROI.h>
Public Member Functions
EventROI ()
Default constructor.
~EventROI ()
Default destructor.
void clear ()
larcv::ROI array clearer
const std::vector< larcv::ROI > & ROIArray () const
larcv::ROI array const reference getter
const ROI & at (ROIIndex_t id) const
larcv::ROI array index accessor
void Append (const ROI &img)
larcv::ROI inserter
void Set (const std::vector< larcv::ROI > &part_v)
larcv::ROI array to replace what is stored
void Emplace (ROI &&img)
Emplacer for larcv::ROI.
void Emplace (std::vector< larcv::ROI > &&part_v)
Emplacer for larcv::ROI array.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::vector< larcv::ROI > _part_v
Detailed Description
Event-wise class to store a collection of larcv::ROI.
A concrete factory class for larcv::EventROI.
Definition at line 26 of file EventROI.h.
Constructor & Destructor Documentation
EventROI()
larcv::EventROI::EventROI () inline
Default constructor.
Definition at line 31 of file EventROI.h.
Referenced by larcv::EventROIFactory::create().
 {}
~EventROI()
larcv::EventROI::~EventROI () inline
Default destructor.
Definition at line 34 of file EventROI.h.
References clear().
 {}
Member Function Documentation
Append()
void larcv::EventROI::Append (const ROI & img)
larcv::ROI inserter
Definition at line 23 of file EventROI.cxx.
References _part_v.
Referenced by ROIArray(), and Set().
   {
     _part_v.push_back(part);
     _part_v.back().Index((ROIIndex_t)(_part_v.size()-1));
   }
at()
const ROI & larcv::EventROI::at (ROIIndex_t id) const
larcv::ROI array index accessor
Definition at line 17 of file EventROI.cxx.
References _part_v.
Referenced by larcv::NuFilter::MCSelect(), and ROIArray().
   {
     if( id >= _part_v.size() ) throw larbys("Invalid request (ImageIndex_t out-o-range)!");
     return _part_v[id];
   }
clear()
void larcv::EventROI::clear () virtual
larcv::ROI array clearer
Reimplemented from larcv::EventBase.
Definition at line 11 of file EventROI.cxx.
References _part_v, and larcv::EventBase::clear().
Referenced by ~EventROI().
   {
     EventBase::clear();
     _part_v.clear();
   }
Emplace() [1/2]
void larcv::EventROI::Emplace (ROI && img)
Emplacer for larcv::ROI.
Definition at line 36 of file EventROI.cxx.
References _part_v.
Referenced by larcv::ROIMask::process(), and ROIArray().
   {
     _part_v.emplace_back(part);
     _part_v.back().Index((ROIIndex_t)(_part_v.size()-1));
   }
Emplace() [2/2]
void larcv::EventROI::Emplace (std::vector< larcv::ROI > && part_v)
Emplacer for larcv::ROI array.
Definition at line 42 of file EventROI.cxx.
References _part_v.
   {
     _part_v = std::move(part_v);
     for(size_t i=0; i<_part_v.size(); ++i) _part_v[i].Index((ROIIndex_t)i);
   }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
ROIArray()
const std::vector<larcv::ROI>& larcv::EventROI::ROIArray () const inline
larcv::ROI array const reference getter
Definition at line 40 of file EventROI.h.
References _part_v, Append(), at(), Emplace(), and Set().
Referenced by larcv::hires::HiResImageDivider::generateSingleMCDivision(), larcv::NuFilter::MCSelect(), larcv::VertexInROI::process(), larcv::LArbysImageExtract::process(), larcv::VertexAna::process(), larcv::LEE1e1pAna::process(), larcv::BadRegionAna::process(), larcv::GoodcROIFilter::process(), larcv::VertexImg::process(), larcv::ROIAna::process(), larcv::ROIMask::process(), larcv::Run3DTracker::process(), larcv::ReadJarrettFile::process(), and larcv::hires::HiResImageDivider::process().
 { return _part_v; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
Set()
void larcv::EventROI::Set (const std::vector< larcv::ROI > & part_v)
larcv::ROI array to replace what is stored
Definition at line 29 of file EventROI.cxx.
References _part_v, and Append().
Referenced by ROIArray().
   {
     _part_v.clear();
     _part_v.reserve(part_v.size());
     for(auto const& p : part_v) Append(p);
   }
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
_part_v
std::vector<larcv::ROI> larcv::EventROI::_part_v private
Definition at line 59 of file EventROI.h.
Referenced by Append(), at(), clear(), Emplace(), ROIArray(), and Set().
The documentation for this class was generated from the following files:
EventROI.h
EventROI.cxx