LArCV: larcv::AStar3DNodePtrList Class Reference
larcv::AStar3DNodePtrList Class Reference
#include <AStar3DAlgo.h>
Classes
struct dirnodeptr_compare_hscore_t
struct dirnodeptr_compare_t
Public Member Functions
AStar3DNodePtrList ()
virtual ~AStar3DNodePtrList ()
void sort ()
void sort_by_hscore ()
void addnode (AStar3DNode *elem)
Public Attributes
T elements
STL member.
Protected Attributes
struct larcv::AStar3DNodePtrList::dirnodeptr_compare_t m_thecomparator
struct larcv::AStar3DNodePtrList::dirnodeptr_compare_hscore_t m_the_hscore_comparator
Detailed Description
Definition at line 199 of file AStar3DAlgo.h.
Constructor & Destructor Documentation
AStar3DNodePtrList()
larcv::AStar3DNodePtrList::AStar3DNodePtrList () inline
Definition at line 202 of file AStar3DAlgo.h.
 {};
~AStar3DNodePtrList()
virtual larcv::AStar3DNodePtrList::~AStar3DNodePtrList () inline virtual
Definition at line 203 of file AStar3DAlgo.h.
 {};
Member Function Documentation
addnode()
void larcv::AStar3DNodePtrList::addnode (AStar3DNode * elem) inline
Definition at line 232 of file AStar3DAlgo.h.
References larcv::AStar3DNode::inopenset.
Referenced by larcv::AStar3DAlgoProton::evaluteLatticePoint(), larcv::AStar3DAlgo::evaluteLatticePoint(), larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
{
         elem->inopenset = true;
       push_back( elem );
       //sort();
     }
sort()
void larcv::AStar3DNodePtrList::sort () inline
Definition at line 225 of file AStar3DAlgo.h.
Referenced by larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
                 {
       std::sort(this->begin(),this->end(), m_thecomparator);
     }
sort_by_hscore()
void larcv::AStar3DNodePtrList::sort_by_hscore () inline
Definition at line 228 of file AStar3DAlgo.h.
Referenced by larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
{
       std::sort(this->begin(),this->end(), m_the_hscore_comparator);
     }
Member Data Documentation
elements
T std::vector< T >::elements inherited
STL member.
m_the_hscore_comparator
struct larcv::AStar3DNodePtrList::dirnodeptr_compare_hscore_t larcv::AStar3DNodePtrList::m_the_hscore_comparator protected
m_thecomparator
struct larcv::AStar3DNodePtrList::dirnodeptr_compare_t larcv::AStar3DNodePtrList::m_thecomparator protected
The documentation for this class was generated from the following file:
AStar3DAlgo.h