LArCV: larcv::EmbedImage Class Reference
larcv::EmbedImage Class Reference
#include <EmbedImage.h>
Public Member Functions
EmbedImage (const std::string name="EmbedImage")
Default constructor.
~EmbedImage ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
std::string fInputProducer
std::string fOutputProducer
int fOutputRows
int fOutputCols
bool finplace
Detailed Description
Definition at line 29 of file EmbedImage.h.
Constructor & Destructor Documentation
EmbedImage()
larcv::EmbedImage::EmbedImage (const std::string name = "EmbedImage")
Default constructor.
Definition at line 11 of file EmbedImage.cxx.
Referenced by larcv::EmbedImageProcessFactory::create().
     : ProcessBase(name)
   {}
~EmbedImage()
larcv::EmbedImage::~EmbedImage () inline
Default destructor.
Definition at line 37 of file EmbedImage.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::EmbedImage::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file EmbedImage.cxx.
References finplace, fInputProducer, fOutputCols, fOutputProducer, fOutputRows, and larcv::PSet::get().
Referenced by ~EmbedImage().
   {
     fInputProducer  = cfg.get<std::string>("InputProducerName");  // input producer
     fOutputProducer = cfg.get<std::string>("OutputProducerName"); // input producer
     fOutputRows     = cfg.get<int>("OutputRows");
     fOutputCols     = cfg.get<int>("OutputCols");
     finplace = ( fInputProducer==fOutputProducer ) ? true : false;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::EmbedImage::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 119 of file EmbedImage.cxx.
Referenced by ~EmbedImage().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::EmbedImage::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 24 of file EmbedImage.cxx.
Referenced by ~EmbedImage().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::EmbedImage::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 27 of file EmbedImage.cxx.
References larcv::ImageMeta::cols(), larcv::EventImage2D::Emplace(), finplace, fInputProducer, fOutputCols, fOutputProducer, fOutputRows, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_ERROR, larcv::ImageMeta::max_y(), larcv::Image2D::meta(), larcv::ImageMeta::min_x(), larcv::EventImage2D::Move(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), and larcv::ImageMeta::rows().
Referenced by ~EmbedImage().
   {
     EventImage2D* event_original = (EventImage2D*)mgr.get_data(kProductImage2D, fInputProducer);
     EventImage2D* event_resize   = NULL;
     if (!finplace)
       event_resize  = (EventImage2D*)mgr.get_data(kProductImage2D, fOutputProducer);
     else
       event_resize  = event_original;
     if ( !event_original ) {
       LARCV_ERROR() << "Could not open input images." << std::endl;
       return false;
     }
     if ( !event_resize )  {
       LARCV_ERROR() << "Could not open output image holder." << std::endl;
       return false;
     }
     std::vector< larcv::Image2D> image_v;
     event_original->Move(image_v ); // original moves ownership of its image vectors to us
     std::vector< larcv::Image2D > resize_image_v; // space for new images if we are not working in place
     std::vector<float> _buffer;
     for ( size_t i=0; i<image_v.size(); ++i ) {
       // get access to the data
       larcv::Image2D& original_image = image_v[i];
       // get the image size
       int orig_rows = original_image.meta().rows();
       int orig_cols = original_image.meta().cols();
       if ( orig_rows>fOutputRows ) {
     LARCV_ERROR() << "Image is taller than Embedding image (" << orig_rows << ">" << fOutputRows << ")" << std::endl;
     return false;
       }
       if ( orig_cols>fOutputCols ) {
     LARCV_ERROR() << "Image is wider than Embedding image (" << orig_cols << ">" << fOutputCols <<")" << std::endl;
     return false;
       }
       // get the origin
       float topleft_x = original_image.meta().min_x();
       float topleft_y = original_image.meta().max_y();
       // get width
       float width_per_pixel  = original_image.meta().pixel_width();
       float height_per_pixel = original_image.meta().pixel_height();
       // get new width, keeping same pixel scales
       float new_width  = float(fOutputCols)*width_per_pixel;
       float new_height = float(fOutputRows)*height_per_pixel;
       // new origin
       int offset_row = 0.5*(fOutputRows-orig_rows);
       int offset_col = 0.5*(fOutputCols-orig_cols);
       float new_topleft_x = topleft_x - offset_row*width_per_pixel;
       float new_topleft_y = topleft_y + offset_col*height_per_pixel;
       // define the new meta
       larcv::ImageMeta new_meta( new_width, new_height,
                  fOutputRows, fOutputCols,
                  new_topleft_x, new_topleft_y,
                  original_image.meta().plane() );
       // define the new image
       larcv::Image2D new_image( new_meta );
       new_image.paint( 0.0 );
       new_image.overlay( original_image );
       resize_image_v.emplace_back( std::move(new_image) );
     }
     // store
     if ( finplace ) {
       // give the new images
       event_original->Emplace( std::move(resize_image_v) );
     }
     else {
       // return the original images
       event_original->Emplace( std::move( image_v ) );
       // we give the new image2d container our relabeled images
       event_resize->Emplace( std::move(resize_image_v) );
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
finplace
bool larcv::EmbedImage::finplace protected
Definition at line 53 of file EmbedImage.h.
Referenced by configure(), and process().
fInputProducer
std::string larcv::EmbedImage::fInputProducer protected
Definition at line 49 of file EmbedImage.h.
Referenced by configure(), and process().
fOutputCols
int larcv::EmbedImage::fOutputCols protected
Definition at line 52 of file EmbedImage.h.
Referenced by configure(), and process().
fOutputProducer
std::string larcv::EmbedImage::fOutputProducer protected
Definition at line 50 of file EmbedImage.h.
Referenced by configure(), and process().
fOutputRows
int larcv::EmbedImage::fOutputRows protected
Definition at line 51 of file EmbedImage.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
EmbedImage.h
EmbedImage.cxx