LArCV: supera::MCROIMaker Class Reference
supera::MCROIMaker Class Reference
#include <MCROIMaker.h>
Public Member Functions
MCROIMaker ()
virtual ~MCROIMaker ()
void configure (const supera::Config_t &cfg)
WTRangeArray_t WireTimeBoundary (const supera::LArMCTrack_t &mct) const
Given single MCTrack, returns length 4 range array (3 planes + time)
which contains all trajectory points of input MCTrack.
WTRangeArray_t WireTimeBoundary (const supera::LArMCTrack_t &mct, const std::vector< supera::LArSimCh_t > &sch_v) const
WTRangeArray_t WireTimeBoundary (const supera::LArMCShower_t &mcs) const
WTRangeArray_t WireTimeBoundary (const supera::LArMCShower_t &mcs, const std::vector< supera::LArSimCh_t > &sch_v) const
::larcv::ROI ParticleROI (const supera::LArMCTrack_t &mct, const int time_offset) const
::larcv::ROI ParticleROI (const supera::LArMCTrack_t &mct, const std::vector< supera::LArSimCh_t > &sch_v, const int time_offset) const
::larcv::ROI ParticleROI (const supera::LArMCShower_t &mcs, const int time_offset) const
::larcv::ROI ParticleROI (const supera::LArMCShower_t &mcs, const std::vector< supera::LArSimCh_t > &sch_v, const int time_offset) const
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
std::vector< larcv::ImageMeta > WTRange2BB (const WTRangeArray_t &) const
Private Attributes
unsigned int _max_time_tick
Maximum tick number in time.
unsigned int _time_padding
Padding in time axis (height) for MCROIMaker::Format function.
unsigned int _wire_padding
Padding in wire axis (width) for MCROIMaker::Format function.
unsigned int _min_width
unsigned int _min_height
bool _apply_sce
Detailed Description
Definition at line 25 of file MCROIMaker.h.
Constructor & Destructor Documentation
MCROIMaker()
supera::MCROIMaker::MCROIMaker () inline
Definition at line 29 of file MCROIMaker.h.
                  : larcv::larcv_base("MCROIMaker")
          , _max_time_tick(9600)
          , _time_padding(10)
          , _wire_padding(10)
          , _min_width(10)
          , _min_height(14)
     {}
~MCROIMaker()
virtual supera::MCROIMaker::~MCROIMaker () inline virtual
Definition at line 37 of file MCROIMaker.h.
References configure(), ParticleROI(), WireTimeBoundary(), and WTRange2BB().
 {}
Member Function Documentation
configure()
void supera::MCROIMaker::configure (const supera::Config_t & cfg)
Definition at line 11 of file MCROIMaker.cxx.
References _apply_sce, _max_time_tick, _min_height, _min_width, _time_padding, _wire_padding, larcv::PSet::get(), LARCV_DEBUG, LARCV_NORMAL, larcv::larcv_base::logger(), and larcv::larcv_base::set_verbosity().
Referenced by larcv::SuperaMCROI::configure(), and ~MCROIMaker().
   {
     LARCV_DEBUG() << "start" << std::endl;
     set_verbosity((::larcv::msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     _max_time_tick = cfg.get<unsigned int>("MaxTimeTick");
     _time_padding  = cfg.get<unsigned int>("TimePadding");
     _wire_padding  = cfg.get<unsigned int>("WirePadding");
     _min_width     = cfg.get<unsigned int>("MinWidth");
     _min_height    = cfg.get<unsigned int>("MinHeight");
     _apply_sce     = cfg.get<bool>("ApplySCE");
     LARCV_NORMAL() << "Configuration called..." << std::endl
            << " Padding   (wire,time) = (" << _wire_padding << "," << _time_padding << ")" << std::endl
            << " Min. Size (wire,time) = (" << _min_width << "," << _min_height << ")" << std::endl;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
ParticleROI() [1/4]
larcv::ROI supera::MCROIMaker::ParticleROI (const supera::LArMCTrack_t & mct, const int time_offset) const
Definition at line 310 of file MCROIMaker.cxx.
References _apply_sce, supera::ApplySCE(), larcv::ROI::CreationProcess(), larcv::ROI::DistanceTravel(), larcv::ROI::dump(), larcv::ROI::EndPosition(), larcv::ROI::EnergyDeposit(), larcv::ROI::EnergyInit(), larcv::ROI::FirstStep(), larcv::kShapeTrack, LARCV_DEBUG, LARCV_INFO, larcv::ROI::LastStep(), larcv::ROI::Momentum(), larcv::ROI::ParentMomentum(), larcv::ROI::ParentPdgCode(), larcv::ROI::ParentPosition(), larcv::ROI::ParentTrackID(), larcv::ROI::PdgCode(), larcv::PdgCode2ROIType(), larcv::ROI::Position(), larcv::ROI::SetBB(), larcv::ROI::Shape(), larcv::ROI::TrackID(), larcv::ROI::Type(), WireTimeBoundary(), WTRange2BB(), and larcv::Vertex::X().
Referenced by larcv::SuperaMCROI::MakeROI(), and ~MCROIMaker().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_INFO() << "Assessing MCTrack G4Track ID = " << mct.TrackID() << " PdgCode " << mct.PdgCode() << std::endl;
     auto wtrange_v = WireTimeBoundary(mct);
     // Add time offset
     wtrange_v.back().Set(wtrange_v.back().Start()+time_offset, wtrange_v.back().End()+time_offset);
     auto bb_v = WTRange2BB(wtrange_v);
     double xyz[3] = {0.};
     ::larcv::ROI res;
     res.SetBB(bb_v);
     res.Shape(::larcv::kShapeTrack);
     res.Type(::larcv::PdgCode2ROIType(mct.PdgCode()));
     if (mct.size())
       res.EnergyDeposit(mct.front().E() - mct.back().E());
     else
       res.EnergyDeposit(0);
     res.EnergyInit(mct.Start().E());
     xyz[0] = mct.Start().X();
     xyz[1] = mct.Start().Y();
     xyz[2] = mct.Start().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.Position(xyz[0], xyz[1], xyz[2], mct.Start().T());
     xyz[0] = mct.End().X();
     xyz[1] = mct.End().Y();
     xyz[2] = mct.End().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.EndPosition(xyz[0], xyz[1], xyz[2], mct.End().T());
     res.CreationProcess(mct.Process());
     if(mct.size()>0) {
       auto const& first_step = mct.front();
       xyz[0] = first_step.X();
       xyz[1] = first_step.Y();
       xyz[2] = first_step.Z();
       if(_apply_sce) ApplySCE(xyz);
       res.FirstStep(xyz[0], xyz[1], xyz[2], first_step.T());
     }
     if(mct.size()>1) {
       auto const& last_step = mct.back();
       res.LastStep(last_step.X(), last_step.Y(), last_step.Z(), last_step.T());
       double length=0;
       for(size_t step_idx=1; step_idx<mct.size(); ++step_idx) {
     auto const& step1 = mct[step_idx-1];
     auto const& step2 = mct[step_idx];
     length += sqrt(pow(step1.X()-step2.X(),2) + pow(step1.Y()-step2.Y(),2) + pow(step1.Z()-step2.Z(),2));
       }
       res.DistanceTravel(length);
     }
     res.Momentum(mct.Start().Px(), mct.Start().Py(), mct.Start().Pz());
     res.PdgCode(mct.PdgCode());
     res.ParentPdgCode(mct.MotherPdgCode());
     res.TrackID(mct.TrackID());
     res.ParentTrackID(mct.MotherTrackID());
     xyz[0] = mct.MotherStart().X();
     xyz[1] = mct.MotherStart().Y();
     xyz[2] = mct.MotherStart().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.ParentPosition(xyz[0], xyz[1], xyz[2], mct.MotherStart().T());
     res.ParentMomentum(mct.MotherStart().Px(),
                mct.MotherStart().Py(),
                mct.MotherStart().Pz());
     LARCV_INFO() << res.dump();
     return res;
   }
ParticleROI() [2/4]
larcv::ROI supera::MCROIMaker::ParticleROI (const supera::LArMCTrack_t & mct, const std::vector< supera::LArSimCh_t > & sch_v, const int time_offset) const
Definition at line 384 of file MCROIMaker.cxx.
References _apply_sce, supera::ApplySCE(), larcv::ROI::CreationProcess(), larcv::ROI::DistanceTravel(), larcv::ROI::dump(), larcv::ROI::EndPosition(), larcv::ROI::EnergyDeposit(), larcv::ROI::EnergyInit(), larcv::ROI::FirstStep(), larcv::kShapeTrack, LARCV_DEBUG, LARCV_INFO, larcv::ROI::LastStep(), larcv::ROI::Momentum(), larcv::ROI::ParentMomentum(), larcv::ROI::ParentPdgCode(), larcv::ROI::ParentPosition(), larcv::ROI::ParentTrackID(), larcv::ROI::PdgCode(), larcv::PdgCode2ROIType(), larcv::ROI::Position(), larcv::ROI::SetBB(), larcv::ROI::Shape(), larcv::ROI::TrackID(), larcv::ROI::Type(), WireTimeBoundary(), WTRange2BB(), and larcv::Vertex::X().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_INFO() << "Assessing MCTrack G4Track ID = " << mct.TrackID() << " PdgCode " << mct.PdgCode() << std::endl;
     auto wtrange_v = WireTimeBoundary(mct, sch_v);
     wtrange_v.back().Set(wtrange_v.back().Start()+time_offset, wtrange_v.back().End()+time_offset);
     auto bb_v = WTRange2BB(wtrange_v);
     double xyz[3] = {0.};
     ::larcv::ROI res;
     res.SetBB(bb_v);
     res.Shape(::larcv::kShapeTrack);
     res.Type(::larcv::PdgCode2ROIType(mct.PdgCode()));
     if (mct.size())
       res.EnergyDeposit(mct.front().E() - mct.back().E());
     else
       res.EnergyDeposit(0);
     res.EnergyInit(mct.Start().E());
     xyz[0] = mct.Start().X();
     xyz[1] = mct.Start().Y();
     xyz[2] = mct.Start().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.Position(xyz[0], xyz[1], xyz[2], mct.Start().T());
     xyz[0] = mct.End().X();
     xyz[1] = mct.End().Y();
     xyz[2] = mct.End().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.EndPosition(xyz[0], xyz[1], xyz[2], mct.End().T());
     res.CreationProcess(mct.Process());
     if(mct.size()>0) {
       auto const& first_step = mct.front();
       xyz[0] = first_step.X();
       xyz[1] = first_step.Y();
       xyz[2] = first_step.Z();
       if(_apply_sce) ApplySCE(xyz);
       res.FirstStep(xyz[0], xyz[1], xyz[2], first_step.T());
     }
     if(mct.size()>1) {
       auto const& last_step = mct.back();
       res.LastStep(last_step.X(), last_step.Y(), last_step.Z(), last_step.T());
       double length=0;
       for(size_t step_idx=1; step_idx<mct.size(); ++step_idx) {
     auto const& step1 = mct[step_idx-1];
     auto const& step2 = mct[step_idx];
     length += sqrt(pow(step1.X()-step2.X(),2) + pow(step1.Y()-step2.Y(),2) + pow(step1.Z()-step2.Z(),2));
       }
       res.DistanceTravel(length);
     }
     res.Momentum(mct.Start().Px(), mct.Start().Py(), mct.Start().Pz());
     res.PdgCode(mct.PdgCode());
     res.ParentPdgCode(mct.MotherPdgCode());
     res.TrackID(mct.TrackID());
     res.ParentTrackID(mct.MotherTrackID());
     xyz[0] = mct.MotherStart().X();
     xyz[1] = mct.MotherStart().Y();
     xyz[2] = mct.MotherStart().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.ParentPosition(xyz[0], xyz[1], xyz[2], mct.MotherStart().T());
     res.ParentMomentum(mct.MotherStart().Px(),
                mct.MotherStart().Py(),
                mct.MotherStart().Pz());
     LARCV_INFO() << res.dump();
     return res;
   }
ParticleROI() [3/4]
larcv::ROI supera::MCROIMaker::ParticleROI (const supera::LArMCShower_t & mcs, const int time_offset) const
Definition at line 457 of file MCROIMaker.cxx.
References _apply_sce, supera::ApplySCE(), larcv::ROI::CreationProcess(), larcv::ROI::dump(), larcv::ROI::EndPosition(), larcv::ROI::EnergyDeposit(), larcv::ROI::EnergyInit(), larcv::ROI::FirstStep(), larcv::kShapeShower, LARCV_DEBUG, LARCV_INFO, larcv::ROI::Momentum(), larcv::ROI::ParentMomentum(), larcv::ROI::ParentPdgCode(), larcv::ROI::ParentPosition(), larcv::ROI::ParentTrackID(), larcv::ROI::PdgCode(), larcv::PdgCode2ROIType(), larcv::ROI::Position(), larcv::ROI::SetBB(), larcv::ROI::Shape(), larcv::ROI::TrackID(), larcv::ROI::Type(), WireTimeBoundary(), WTRange2BB(), and larcv::Vertex::X().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_INFO() << "Assessing MCShower G4Track ID = " << mcs.TrackID() << " PdgCode " << mcs.PdgCode() << std::endl;
     auto wtrange_v = WireTimeBoundary(mcs);
     wtrange_v.back().Set(wtrange_v.back().Start()+time_offset, wtrange_v.back().End()+time_offset);
     auto bb_v = WTRange2BB(wtrange_v);
     double xyz[3] = {0.};
     ::larcv::ROI res;
     res.SetBB(bb_v);
     res.Shape(::larcv::kShapeShower);
     res.Type(::larcv::PdgCode2ROIType(mcs.PdgCode()));
     res.EnergyDeposit(mcs.DetProfile().E());
     //res.EnergyDeposit(0);
     res.EnergyInit(mcs.Start().E());
     xyz[0] = mcs.Start().X();
     xyz[1] = mcs.Start().Y();
     xyz[2] = mcs.Start().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.Position(xyz[0], xyz[1], xyz[2], mcs.Start().T());
     xyz[0] = mcs.End().X();
     xyz[1] = mcs.End().Y();
     xyz[2] = mcs.End().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.EndPosition(xyz[0], xyz[1], xyz[2], mcs.End().T());
     res.CreationProcess(mcs.Process());
     auto const& first_step = mcs.DetProfile();
     xyz[0] = first_step.X();
     xyz[1] = first_step.Y();
     xyz[2] = first_step.Z();
     if(_apply_sce) ApplySCE(xyz);
     res.FirstStep(xyz[0], xyz[1], xyz[2], first_step.T());
     res.Momentum(mcs.Start().Px(), mcs.Start().Py(), mcs.Start().Pz());
     res.PdgCode(mcs.PdgCode());
     res.ParentPdgCode(mcs.MotherPdgCode());
     res.TrackID(mcs.TrackID());
     res.ParentTrackID(mcs.MotherTrackID());
     xyz[0] = mcs.MotherStart().X();
     xyz[1] = mcs.MotherStart().Y();
     xyz[2] = mcs.MotherStart().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.ParentPosition(xyz[0], xyz[1], xyz[2], mcs.MotherStart().T());
     res.ParentMomentum(mcs.MotherStart().Px(),
                mcs.MotherStart().Py(),
                mcs.MotherStart().Pz());
     LARCV_INFO() << res.dump();
     return res;
   }
ParticleROI() [4/4]
larcv::ROI supera::MCROIMaker::ParticleROI (const supera::LArMCShower_t & mcs, const std::vector< supera::LArSimCh_t > & sch_v, const int time_offset) const
Definition at line 515 of file MCROIMaker.cxx.
References _apply_sce, supera::ApplySCE(), larcv::ROI::CreationProcess(), larcv::ROI::dump(), larcv::ROI::EndPosition(), larcv::ROI::EnergyDeposit(), larcv::ROI::EnergyInit(), larcv::ROI::FirstStep(), larcv::kShapeShower, LARCV_DEBUG, LARCV_INFO, larcv::ROI::Momentum(), larcv::ROI::ParentMomentum(), larcv::ROI::ParentPdgCode(), larcv::ROI::ParentPosition(), larcv::ROI::ParentTrackID(), larcv::ROI::PdgCode(), larcv::PdgCode2ROIType(), larcv::ROI::Position(), larcv::ROI::SetBB(), larcv::ROI::Shape(), larcv::ROI::TrackID(), larcv::ROI::Type(), WireTimeBoundary(), WTRange2BB(), and larcv::Vertex::X().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_INFO() << "Assessing MCShower G4Track ID = " << mcs.TrackID() << " PdgCode " << mcs.PdgCode() << std::endl;
     auto wtrange_v = WireTimeBoundary(mcs, sch_v);
     wtrange_v.back().Set(wtrange_v.back().Start()+time_offset, wtrange_v.back().End()+time_offset);
     auto bb_v = WTRange2BB(wtrange_v);
     double xyz[3] = {0.};
     ::larcv::ROI res;
     res.SetBB(bb_v);
     res.Shape(::larcv::kShapeShower);
     res.Type(::larcv::PdgCode2ROIType(mcs.PdgCode()));
     res.EnergyDeposit(mcs.DetProfile().E());
     //res.EnergyDeposit(0);
     res.EnergyInit(mcs.Start().E());
     xyz[0] = mcs.Start().X();
     xyz[1] = mcs.Start().Y();
     xyz[2] = mcs.Start().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.Position(xyz[0], xyz[1], xyz[2], mcs.Start().T());
     xyz[0] = mcs.End().X();
     xyz[1] = mcs.End().Y();
     xyz[2] = mcs.End().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.EndPosition(xyz[0], xyz[1], xyz[2], mcs.End().T());
     res.CreationProcess(mcs.Process());
     auto const& first_step = mcs.DetProfile();
     xyz[0] = first_step.X();
     xyz[1] = first_step.Y();
     xyz[2] = first_step.Z();
     if(_apply_sce) ApplySCE(xyz);
     res.FirstStep(xyz[0], xyz[1], xyz[2], first_step.T());
     res.Momentum(mcs.Start().Px(), mcs.Start().Py(), mcs.Start().Pz());
     res.PdgCode(mcs.PdgCode());
     res.ParentPdgCode(mcs.MotherPdgCode());
     res.TrackID(mcs.TrackID());
     res.ParentTrackID(mcs.MotherTrackID());
     xyz[0] = mcs.MotherStart().X();
     xyz[1] = mcs.MotherStart().Y();
     xyz[2] = mcs.MotherStart().Z();
     if(_apply_sce) ApplySCE(xyz);
     res.ParentPosition(xyz[0], xyz[1], xyz[2], mcs.MotherStart().T());
     res.ParentMomentum(mcs.MotherStart().Px(),
                mcs.MotherStart().Py(),
                mcs.MotherStart().Pz());
     LARCV_INFO() << res.dump();
     return res;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
WireTimeBoundary() [1/4]
WTRangeArray_t supera::MCROIMaker::WireTimeBoundary (const supera::LArMCTrack_t & mct) const
Given single MCTrack, returns length 4 range array (3 planes + time)
which contains all trajectory points of input MCTrack.
Definition at line 74 of file MCROIMaker.cxx.
References _apply_sce, _max_time_tick, supera::ApplySCE(), supera::DriftVelocity(), LARCV_DEBUG, LARCV_INFO, supera::NearestWire(), supera::Nplanes(), supera::PlaneTickOffset(), and supera::TPCG4Time2Tick().
Referenced by ParticleROI(), and ~MCROIMaker().
   {
     LARCV_DEBUG() << "start" << std::endl;
     const double drift_velocity = ::supera::DriftVelocity() * 1.0e-3; // make it cm/ns
     //const int tick_max = ::supera::NumberTimeSamples();
     const double plane_tick_offset = PlaneTickOffset(0,1); // plane 1 as a reference
     const int tick_max = _max_time_tick;
     TVector3 xyz; xyz[0] = xyz[1] = xyz[2] = 0.;
     // result is N planes' wire boundary + time boundary (N+1 elements)
     WTRangeArray_t result(::supera::Nplanes() + 1);
     for (auto& step : mct) {
       xyz[0] = step.X();
       xyz[1] = step.Y();
       xyz[2] = step.Z();
       if(_apply_sce) ApplySCE(xyz);
       // Figure out time
       int tick = (int)(::supera::TPCG4Time2Tick(step.T() + (xyz[0]  / drift_velocity)) + plane_tick_offset + 0.5);
       if (tick < 0 || tick >= tick_max) {
     LARCV_DEBUG() << "tick out of time: " << tick << std::endl;
     continue;
       }
       auto& trange = result.back();
       if (!trange.valid()) trange.Set((unsigned int)tick, (unsigned int)tick); // 1st time: "set" it
       else trange += (unsigned int)tick; // >1st time: "add (include)" it
       // Figure out wire per plane
       LARCV_DEBUG() << "(x,t,v) = (" << xyz[0] << "," << step.T() << "," << drift_velocity << ") ... tick = " << tick << std::endl;
       for (size_t plane = 0; plane < supera::Nplanes(); ++plane) {
     auto wire_id = ::supera::NearestWire(xyz, plane);
     auto& wrange = result[plane];
     LARCV_DEBUG() << "(y,z) = (" << xyz[1] << "," << xyz[2] << ") ... @ plane " << plane << " wire = " << wire_id
              << (wrange.valid() ? " updating wire-range" : " setting wire-range") << std::endl;
     if (!wrange.valid()) wrange.Set((unsigned int)wire_id, (unsigned int)wire_id);
     else wrange += (unsigned int)wire_id;
       }
     }
     for (auto& r : result) if (!r.valid()) r.Set(0, 0);
     //if(!r.valid() || (r.End() - r.Start()) < 2) r.Set(0,0);
     for (size_t plane = 0; plane <= supera::Nplanes(); ++plane)
       LARCV_INFO() << "Single MCTrack ... Plane " << plane
            << " bound " << result[plane].Start() << " => " << result[plane].End() << std::endl;
     return result;
   }
WireTimeBoundary() [2/4]
WTRangeArray_t supera::MCROIMaker::WireTimeBoundary (const supera::LArMCTrack_t & mct, const std::vector< supera::LArSimCh_t > & sch_v) const
Definition at line 27 of file MCROIMaker.cxx.
References _max_time_tick, supera::ChannelToWireID(), LARCV_DEBUG, LARCV_INFO, supera::Nplanes(), and supera::TPCTDC2Tick().
   {
     LARCV_DEBUG() << "start" << std::endl;
     // result is N planes' wire boundary + time boundary (N+1 elements)
     WTRangeArray_t result(supera::Nplanes() + 1);
     for (auto const& sch : sch_v) {
       auto const wire = ChannelToWireID(sch.Channel());
       auto& wrange = result[wire.Plane];
       auto& trange = result.back();
       for (auto const& tdc_ide_v : sch.TDCIDEMap()) {
     bool store = false;
     double tick = TPCTDC2Tick((double)(tdc_ide_v.first));
     //if(tick<0 || tick >= NumberTimeSamples()) continue;
     if (tick < 0 || tick >= _max_time_tick) continue;
     tick += 0.5;
     for (auto const& ide : tdc_ide_v.second) {
       unsigned int trackid = (ide.trackID < 0 ? (-1 * ide.trackID) : ide.trackID);
       if (trackid != mct.TrackID()) continue;
       store = true;
       LARCV_DEBUG() << "IDE wire = " << (unsigned int)wire.Wire
                << " ... tick = " << (unsigned int)tick << std::endl
                << " (tdc=" << tdc_ide_v.first << ", x=" << ide.x << ")" << std::endl;
       break;
     }
     if (!store) continue;
     if (!wrange.valid()) wrange.Set((unsigned int)wire.Wire, (unsigned int)(wire.Wire));
     else wrange += (unsigned int)(wire.Wire);
     if (!trange.valid()) trange.Set((unsigned int)(tick), (unsigned int)(tick));
     else trange += (unsigned int)(tick);
       }
     }
     for (auto& r : result) if (!r.valid()) r.Set(0, 0);
     for (size_t plane = 0; plane <= supera::Nplanes(); ++plane)
       LARCV_INFO() << "Single MCShower ... Plane " << plane
            << " bound " << result[plane].Start() << " => " << result[plane].End() << std::endl;
     return result;
   }
WireTimeBoundary() [3/4]
WTRangeArray_t supera::MCROIMaker::WireTimeBoundary (const supera::LArMCShower_t & mcs) const
Definition at line 130 of file MCROIMaker.cxx.
References _apply_sce, _max_time_tick, supera::ApplySCE(), supera::DriftVelocity(), LARCV_DEBUG, LARCV_INFO, supera::NearestWire(), supera::Nplanes(), supera::PlaneTickOffset(), and supera::TPCG4Time2Tick().
   {
     LARCV_DEBUG() << "start" << std::endl;
     const double drift_velocity = ::supera::DriftVelocity() * 1.0e-3; // make it cm/ns
     //const int tick_max = ::supera::NumberTimeSamples();
     const int tick_max = _max_time_tick;
     double xyz[3] = {0.};
     // result is N planes' wire boundary + time boundary (N+1 elements)
     WTRangeArray_t result(::supera::Nplanes() + 1);
     auto const& detprofile = mcs.DetProfile();
     double energy = detprofile.E();
     double showerlength = 13.8874 + 0.121734 * energy - (3.75571e-05) * energy * energy;
     showerlength *= 2.5;
     //double showerlength = 100.0;
     double detprofnorm = sqrt( detprofile.Px() * detprofile.Px() + detprofile.Py() * detprofile.Py() + detprofile.Pz() * detprofile.Pz() );
     TLorentzVector showerend;
     const double plane_tick_offset = PlaneTickOffset(0,1); // plane 1 as a reference
     showerend[0] = detprofile.X() + showerlength * (detprofile.Px() / detprofnorm);
     showerend[1] = detprofile.Y() + showerlength * (detprofile.Py() / detprofnorm);
     showerend[2] = detprofile.Z() + showerlength * (detprofile.Pz() / detprofnorm);
     showerend[3] = detprofile.T();
     //std::cout << "showerlength: " << showerlength << " norm=" << detprofnorm << std::endl;
     std::vector< TLorentzVector > step_v;
     step_v.push_back( detprofile.Position() );
     step_v.push_back( showerend );
     for (auto& step : step_v) {
       xyz[0] = step.X();
       xyz[1] = step.Y();
       xyz[2] = step.Z();
       if(_apply_sce) ApplySCE(xyz);
       // Figure out time
       int tick = (int)(::supera::TPCG4Time2Tick(step.T() + (xyz[0]  / drift_velocity)) + plane_tick_offset + 0.5);
       if (tick < 0 || tick >= tick_max) continue;
       auto& trange = result.back();
       if (!trange.valid()) trange.Set((unsigned int)tick, (unsigned int)tick);
       else trange += (unsigned int)tick;
       // Figure out wire per plane
       for (size_t plane = 0; plane < supera::Nplanes(); ++plane) {
     auto wire_id = ::supera::NearestWire(xyz, plane);
     auto& wrange = result[plane];
     if (!wrange.valid()) wrange.Set((unsigned int)wire_id, (unsigned int)wire_id);
     else wrange += (unsigned int)wire_id;
       }
       LARCV_DEBUG() << "(x,t,v) = (" << xyz[0] << "," << step.T() << "," << drift_velocity << ") ... tick = " << tick << std::endl;
     }
     for (auto& r : result) if (!r.valid()) r.Set(0, 0);
     for (size_t plane = 0; plane <= supera::Nplanes(); ++plane)
       LARCV_INFO() << "Single MCShower ... Plane " << plane
            << " bound " << result[plane].Start() << " => " << result[plane].End() << std::endl;
     return result;
   }
WireTimeBoundary() [4/4]
WTRangeArray_t supera::MCROIMaker::WireTimeBoundary (const supera::LArMCShower_t & mcs, const std::vector< supera::LArSimCh_t > & sch_v) const
Definition at line 198 of file MCROIMaker.cxx.
References _max_time_tick, supera::ChannelToWireID(), LARCV_DEBUG, LARCV_INFO, supera::Nplanes(), and supera::TPCTDC2Tick().
   {
     LARCV_DEBUG() << "start" << std::endl;
     // result is N planes' wire boundary + time boundary (N+1 elements)
     WTRangeArray_t result(::supera::Nplanes() + 1);
     std::set<unsigned int> daughters;
     for (auto const& trackid : mcs.DaughterTrackID()) daughters.insert(trackid);
     daughters.insert(mcs.TrackID());
     for (auto const& sch : sch_v) {
       auto const wire = ChannelToWireID(sch.Channel());
       auto& wrange = result[wire.Plane];
       auto& trange = result.back();
       for (auto const& tdc_ide_v : sch.TDCIDEMap()) {
     bool store = false;
     double tick = TPCTDC2Tick((double)(tdc_ide_v.first));
     //if(tick<0 || tick >= NumberTimeSamples()) continue;
     if (tick < 0 || tick >= _max_time_tick) continue;
     tick += 0.5;
     for (auto const& ide : tdc_ide_v.second) {
       unsigned int trackid = (ide.trackID < 0 ? (-1 * ide.trackID) : ide.trackID);
       if (daughters.find(trackid) != daughters.end()) {
         store = true;
         LARCV_DEBUG() << "IDE wire = " << (unsigned int)wire.Wire
              << " ... tick = " << (unsigned int)tick << std::endl
              << " (tdc=" << tdc_ide_v.first << ", x=" << ide.x << ")" << std::endl;
         break;
       }
     }
     if (!store) continue;
     if (!wrange.valid()) wrange.Set((unsigned int)wire.Wire, (unsigned int)(wire.Wire));
     else wrange += (unsigned int)(wire.Wire);
     if (!trange.valid()) trange.Set((unsigned int)(tick), (unsigned int)(tick));
     else trange += (unsigned int)(tick);
       }
     }
     for (auto& r : result) if (!r.valid()) r.Set(0, 0);
     for (size_t plane = 0; plane <= supera::Nplanes(); ++plane)
       LARCV_INFO() << "Single MCShower ... Plane " << plane
            << " bound " << result[plane].Start() << " => " << result[plane].End() << std::endl;
     return result;
   }
WTRange2BB()
std::vector< larcv::ImageMeta > supera::MCROIMaker::WTRange2BB (const WTRangeArray_t & wtrange_v) const private
Definition at line 248 of file MCROIMaker.cxx.
References _min_height, _min_width, _time_padding, _wire_padding, LARCV_DEBUG, and LARCV_INFO.
Referenced by ParticleROI(), and ~MCROIMaker().
   {
     LARCV_DEBUG() << "start" << std::endl;
     std::vector<larcv::ImageMeta> bb_v;
     if (wtrange_v.empty()) return bb_v;
     bb_v.reserve(wtrange_v.size() - 1);
     bool invalid = false;
     for (size_t i = 0; i < wtrange_v.size() - 1; ++i) {
       auto const& wrange = wtrange_v[i];
       auto const& trange = wtrange_v.back();
       if(!wrange.valid() || !trange.valid()) {
     LARCV_INFO() << "Invalid WTRange_t for Plane " << i << std::endl
              << "      W: " << wrange.Start() << " => " << wrange.End() << (wrange.valid() ? " good" : " bad")
              << " ... T: " << trange.Start() << " => " << trange.End() << (trange.valid() ? " good" : " bad") << std::endl;
     invalid = true;
       }
       double width, height;
       double origin_x, origin_y;
       size_t rows, cols;
       width = (int)(wrange.End()) - (int)(wrange.Start());
       height = (int)(trange.End()) - (int)(trange.Start());
       origin_x = wrange.Start();
       origin_y = trange.End();
       rows = (int)(trange.End()) - (int)(trange.Start());
       cols = (int)(wrange.End()) - (int)(wrange.Start());
       //if(wrange.valid() && (wrange.End() - wrange.Start())) {
       if (wrange.valid() && wrange.Start()) {
     width = (int)(wrange.End()) - (int)(wrange.Start()) + 1 + 2 * ((int)_wire_padding);
     cols = (int)(wrange.End()) - (int)(wrange.Start()) + 1 + 2 * ((int)_wire_padding);
     origin_x = (double)(wrange.Start()) - (double)(_wire_padding);
       }
       //if(trange.valid() && (trange.End() - trange.Start())) {
       if (trange.valid() && trange.Start()) {
     height = (int)(trange.End()) - (int)(trange.Start()) + 1 + 2 * (int)(_time_padding);
     rows = (int)(trange.End()) - (int)(trange.Start()) + 1 + 2 * (int)(_time_padding);
     origin_y = (int)(trange.End()) + (int)(_time_padding);
       }
       if ( (width - 2 * _wire_padding) < _min_width || (height - 2 * _time_padding) < _min_height ) {
     LARCV_INFO() << "Too small WTRange_t for Plane " << i << std::endl
              << "      W: " << wrange.Start() << " => " << wrange.End() << (wrange.valid() ? " good" : " bad")
              << " ... T: " << trange.Start() << " => " << trange.End() << (trange.valid() ? " good" : " bad") << std::endl;
     invalid = true;
       } else {
     LARCV_INFO() << "Constructing ImageMeta from WTRange_t for Plane " << i
              << " w/ padding (w,t) = (" << _wire_padding << "," << _time_padding << ")" << std::endl
              << "      W: " << wrange.Start() << " => " << wrange.End() << (wrange.valid() ? " good" : " bad")
              << " ... T: " << trange.Start() << " => " << trange.End() << (trange.valid() ? " good" : " bad") << std::endl
              << "      Origin: (" << origin_x << "," << origin_y << ")" << std::endl
              << "      Rows = " << rows << " Cols = " << cols << " ... Height = " << height << " Width = " << width << std::endl;
     bb_v.emplace_back(width, height, rows, cols, origin_x, origin_y, i);
       }
     }
     if(invalid) bb_v.clear();
     return bb_v;
   }
Member Data Documentation
_apply_sce
bool supera::MCROIMaker::_apply_sce private
Definition at line 77 of file MCROIMaker.h.
Referenced by configure(), ParticleROI(), and WireTimeBoundary().
_max_time_tick
unsigned int supera::MCROIMaker::_max_time_tick private
Maximum tick number in time.
Definition at line 72 of file MCROIMaker.h.
Referenced by configure(), and WireTimeBoundary().
_min_height
unsigned int supera::MCROIMaker::_min_height private
Definition at line 76 of file MCROIMaker.h.
Referenced by configure(), and WTRange2BB().
_min_width
unsigned int supera::MCROIMaker::_min_width private
Definition at line 75 of file MCROIMaker.h.
Referenced by configure(), and WTRange2BB().
_time_padding
unsigned int supera::MCROIMaker::_time_padding private
Padding in time axis (height) for MCROIMaker::Format function.
Definition at line 73 of file MCROIMaker.h.
Referenced by configure(), and WTRange2BB().
_wire_padding
unsigned int supera::MCROIMaker::_wire_padding private
Padding in wire axis (width) for MCROIMaker::Format function.
Definition at line 74 of file MCROIMaker.h.
Referenced by configure(), and WTRange2BB().
The documentation for this class was generated from the following files:
MCROIMaker.h
MCROIMaker.cxx