LArCV: larcv::CCQETruthFilter Class Reference
larcv::CCQETruthFilter Class Reference
#include <CCQETruthFilter.h>
Public Member Functions
CCQETruthFilter (const std::string name="CCQETruthFilter")
Default constructor.
~CCQETruthFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _roi_producer
double _nu_energy_max
double _nu_energy_min
TTree * _tree
int _pdg
double _energy
double _x
double _y
double _z
int _type
double _energy_init
double _energy_deposit
Detailed Description
Definition at line 27 of file CCQETruthFilter.h.
Constructor & Destructor Documentation
CCQETruthFilter()
larcv::CCQETruthFilter::CCQETruthFilter (const std::string name = "CCQETruthFilter")
Default constructor.
Definition at line 11 of file CCQETruthFilter.cxx.
Referenced by larcv::CCQETruthFilterProcessFactory::create().
     : ProcessBase(name)
   {}
~CCQETruthFilter()
larcv::CCQETruthFilter::~CCQETruthFilter () inline
Default destructor.
Definition at line 35 of file CCQETruthFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::CCQETruthFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file CCQETruthFilter.cxx.
References _nu_energy_max, _nu_energy_min, _roi_producer, and larcv::PSet::get().
Referenced by ~CCQETruthFilter().
   {
     _roi_producer  = cfg.get<std::string>("ROIProducer");
     _nu_energy_max = cfg.get<double>("NuEnergyMax");
     _nu_energy_min = cfg.get<double>("NuEnergyMin");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::CCQETruthFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 93 of file CCQETruthFilter.cxx.
References _tree, larcv::ProcessBase::ana_file(), and larcv::ProcessBase::has_ana_file().
Referenced by ~CCQETruthFilter().
   {
     if(this->has_ana_file()) {
       this->ana_file().cd();
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::CCQETruthFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 22 of file CCQETruthFilter.cxx.
References _energy, _energy_deposit, _energy_init, _pdg, _tree, _type, _x, _y, and _z.
Referenced by ~CCQETruthFilter().
   {
     _tree = new TTree("tree","");
     _tree->Branch("pdg",&_pdg,"pdg/I");
     _tree->Branch("energy",&_energy,"energy/D");
     _tree->Branch("x",&_x,"x/D");
     _tree->Branch("y",&_y,"y/D");
     _tree->Branch("z",&_z,"z/D");
     _tree->Branch("itype",&_type,"itype/I");
     _tree->Branch("energy_init",&_energy_init,"energy_init/D");
     _tree->Branch("energy_deposit",&_energy_deposit,"energy_deposit/D");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::CCQETruthFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 35 of file CCQETruthFilter.cxx.
References _energy, _energy_deposit, _energy_init, _nu_energy_max, _nu_energy_min, _pdg, _roi_producer, _tree, _type, _x, _y, _z, larcv::IOManager< T >::get_data(), larcv::kINVALID_INDEX, larcv::kProductROI, LARCV_WARNING, and larcv::ParticleMass().
Referenced by ~CCQETruthFilter().
   {
     auto const evroi = (EventROI*)(mgr.get_data(kProductROI,_roi_producer));
     bool keep=false;
     _pdg = 0;
     _energy = 0;
     _x = _y = _z = -1e20;
     _type = -1;
     _energy_init = _energy_deposit = 0;
     bool nu_found=false;
     std::stringstream tmp_ss;
     for(auto const& roi : evroi->ROIArray()) {
       tmp_ss <<"Pdg: " << roi.PdgCode() << " track id " << roi.TrackID() << " parent pdg " << roi.ParentPdgCode() << " parent track id " << roi.ParentTrackID()
          << " energy init " << roi.EnergyInit() << " energy deposit " << roi.EnergyDeposit()
          << " interaction " << roi.NuInteractionType()
          << " ("<<roi.X()<<","<<roi.Y()<<","<<roi.Z()<<")"<<std::endl;
       if(roi.MCSTIndex() != kINVALID_INDEX) {
     _energy_init += roi.EnergyInit();
     if(roi.PdgCode() != 111)
       _energy_init -= ParticleMass(roi.PdgCode());
     _energy_deposit += roi.EnergyDeposit();
     continue;
       }
       if(roi.PdgCode() != 12 && roi.PdgCode() != 14 && roi.PdgCode() != -12 && roi.PdgCode() != -14) continue;
       if(nu_found) {
     LARCV_WARNING() << "2nd nu found..." << std::endl << tmp_ss.str() << std::endl;
     return false;
       }
       _x = roi.X();
       _y = roi.Y();
       _z = roi.Z();
       _energy = roi.EnergyInit();
       _pdg = roi.PdgCode();
       _type = roi.NuInteractionType();
       nu_found = true;
       if(roi.EnergyInit() < _nu_energy_min || roi.EnergyInit() > _nu_energy_max) continue;
       if(roi.NuInteractionType() != 1001) continue;
       if( roi.X() < 5.     || roi.X() > 251.35 ) continue;
       if( roi.Y() < -111.5 || roi.Y() > 111.5  ) continue;
       if( roi.Z() < 5.     || roi.Z() > 1031.8 ) continue;
       keep=true;
     }
     if(_energy_deposit/_energy_init > 1.01)
       LARCV_WARNING() << "Energy deposit/init > 1.01..." << std::endl << tmp_ss.str() << std::endl;
     /*
     if(keep) std::cout<<"Kept!"<<std::endl;
     else std::cout<<"... skipped" << std::endl;
     */
     _tree->Fill();
     return keep;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_energy
double larcv::CCQETruthFilter::_energy private
Definition at line 51 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_energy_deposit
double larcv::CCQETruthFilter::_energy_deposit private
Definition at line 57 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_energy_init
double larcv::CCQETruthFilter::_energy_init private
Definition at line 56 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_nu_energy_max
double larcv::CCQETruthFilter::_nu_energy_max private
Definition at line 47 of file CCQETruthFilter.h.
Referenced by configure(), and process().
_nu_energy_min
double larcv::CCQETruthFilter::_nu_energy_min private
Definition at line 48 of file CCQETruthFilter.h.
Referenced by configure(), and process().
_pdg
int larcv::CCQETruthFilter::_pdg private
Definition at line 50 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_roi_producer
std::string larcv::CCQETruthFilter::_roi_producer private
Definition at line 46 of file CCQETruthFilter.h.
Referenced by configure(), and process().
_tree
TTree* larcv::CCQETruthFilter::_tree private
Definition at line 49 of file CCQETruthFilter.h.
Referenced by finalize(), initialize(), and process().
_type
int larcv::CCQETruthFilter::_type private
Definition at line 55 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_x
double larcv::CCQETruthFilter::_x private
Definition at line 52 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_y
double larcv::CCQETruthFilter::_y private
Definition at line 53 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
_z
double larcv::CCQETruthFilter::_z private
Definition at line 54 of file CCQETruthFilter.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
CCQETruthFilter.h
CCQETruthFilter.cxx