LArCV: larcv::EventPGraphFactory Class Reference
larcv::EventPGraphFactory Class Reference
#include <EventPGraph.h>
Public Member Functions
EventPGraphFactory ()
ctor
~EventPGraphFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 67 of file EventPGraph.h.
Constructor & Destructor Documentation
EventPGraphFactory()
larcv::EventPGraphFactory::EventPGraphFactory () inline
ctor
Definition at line 70 of file EventPGraph.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductPGraph.
 { DataProductFactory::get().add_factory(kProductPGraph,this); }
~EventPGraphFactory()
larcv::EventPGraphFactory::~EventPGraphFactory () inline
dtor
Definition at line 72 of file EventPGraph.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventPGraphFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 74 of file EventPGraph.h.
References larcv::EventPGraph::EventPGraph().
 { return new EventPGraph; }
The documentation for this class was generated from the following file:
EventPGraph.h