LArCV: larcv::SuperaKeyPointCluster Class Reference
larcv::SuperaKeyPointCluster Class Reference
#include <SuperaKeyPointCluster.h>
Public Member Functions
SuperaKeyPointCluster (const std::string name="SuperaKeyPointCluster")
Default constructor.
~SuperaKeyPointCluster ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
template<class T >
const std::vector< T > & LArData () const
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
const std::string & LArDataLabel (supera::LArDataType_t type) const
int TimeOffset () const
void ClearEventData ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
const std::string & OutPixel2DLabel () const
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
ImageMetaMakerBase * MetaMakerPtr ()
Private Member Functions
larcv::Vertex GetPoint (const supera::LArMCStep_t &step)
std::vector< larcv::Pixel2DCluster > CreateCluster (const std::vector< larcv::ImageMeta > &meta_v, const std::set< larcv::Vertex > &pt_s, const unsigned short val, const int time_offset)
Private Attributes
std::string _in_roi_label
bool _apply_sce
size_t _row_pad
size_t _col_pad
bool _cluster_primary_start
bool _cluster_secondary_start
bool _cluster_scattering
Detailed Description
Definition at line 30 of file SuperaKeyPointCluster.h.
Constructor & Destructor Documentation
SuperaKeyPointCluster()
larcv::SuperaKeyPointCluster::SuperaKeyPointCluster (const std::string name = "SuperaKeyPointCluster")
Default constructor.
Definition at line 14 of file SuperaKeyPointCluster.cxx.
Referenced by larcv::SuperaKeyPointClusterProcessFactory::create().
     : SuperaBase(name)
   {}
~SuperaKeyPointCluster()
larcv::SuperaKeyPointCluster::~SuperaKeyPointCluster () inline
Default destructor.
Definition at line 40 of file SuperaKeyPointCluster.h.
References configure(), CreateCluster(), finalize(), GetPoint(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData () inherited
Definition at line 89 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v, larcv::SuperaBase::_ptr_mcs_v, larcv::SuperaBase::_ptr_mct_v, larcv::SuperaBase::_ptr_mctruth_v, larcv::SuperaBase::_ptr_opdigit_v, larcv::SuperaBase::_ptr_sch_v, and larcv::SuperaBase::_ptr_wire_v.
Referenced by larcv::SuperaBase::finalize(), larcv::SuperaBase::initialize(), larcv::SuperaMetaMaker::process(), larcv::SuperaBase::SuperaBase(), and larcv::SuperaBase::TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
ColCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::ColCompressionFactor () const inherited
Definition at line 36 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::ColCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->ColCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->ColCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
configure()
void larcv::SuperaKeyPointCluster::configure (const PSet & cfg) virtual
Reimplemented from supera::ImageMetaMaker.
Definition at line 18 of file SuperaKeyPointCluster.cxx.
References _apply_sce, _cluster_primary_start, _cluster_scattering, _cluster_secondary_start, _col_pad, _in_roi_label, _row_pad, supera::ParamsPixel2D::configure(), larcv::SuperaBase::configure(), supera::ImageMetaMaker::configure(), and larcv::PSet::get().
Referenced by ~SuperaKeyPointCluster().
   {
     SuperaBase::configure(cfg);
     supera::ParamsPixel2D::configure(cfg);
     supera::ImageMetaMaker::configure(cfg);
     _in_roi_label = cfg.get<std::string>("InputROILabel");
     _apply_sce    = cfg.get<bool>("ApplySCE");
     _row_pad      = cfg.get<size_t>("RowPad");
     _col_pad      = cfg.get<size_t>("ColPad");
     _cluster_primary_start   = cfg.get<bool>("UsePrimaryStart",true);
     _cluster_secondary_start = cfg.get<bool>("UseSecondaryStart",true);
     _cluster_scattering      = cfg.get<bool>("UseScattering",false);
   }
CreateCluster()
std::vector< larcv::Pixel2DCluster > larcv::SuperaKeyPointCluster::CreateCluster (const std::vector< larcv::ImageMeta > & meta_v, const std::set< larcv::Vertex > & pt_s, const unsigned short val, const int time_offset) private
Definition at line 176 of file SuperaKeyPointCluster.cxx.
References _col_pad, _row_pad, larcv::Pixel2D::Intensity(), LARCV_DEBUG, LARCV_INFO, larcv::supera::NearestWire(), supera::PlaneTickOffset(), and larcv::supera::TPCG4Time2Tick().
Referenced by process(), and ~SuperaKeyPointCluster().
   {
     double xyz[3];
     std::vector<larcv::Pixel2DCluster> res_v;
     res_v.resize(meta_v.size());
     static std::vector<std::vector<unsigned short> > data_v;
     data_v.resize(meta_v.size());
     for(size_t plane=0; plane<meta_v.size(); ++plane) {
       LARCV_DEBUG() << "Clustering plane " << plane << std::endl;
       auto const& meta = meta_v[plane];
       auto& data = data_v[plane];
       data.resize(meta.rows() * meta.cols());
       for(auto& v : data) v = 0.;
       for(auto const& pt : pt_s) {
     xyz[0] = pt.X();
     xyz[1] = pt.Y();
     xyz[2] = pt.Z();
     double tick_float = (double)(::supera::TPCG4Time2Tick(pt.T()) + time_offset) + supera::PlaneTickOffset(0,plane) + 0.5;
     double wire_float = (double)(::supera::NearestWire(xyz, plane)) + 0.5;
     LARCV_DEBUG() << wire_float << " ... " << meta.min_x() << " => " << meta.max_x() << std::endl;
     LARCV_DEBUG() << tick_float << " ... " << meta.min_y() << " => " << meta.max_y() << std::endl;
     if(wire_float < meta.min_x() || meta.max_x() < wire_float) continue;
     if(tick_float < meta.min_y() || meta.max_y() < tick_float) continue;
     auto tick = meta.row(tick_float);
     auto wire = meta.col(wire_float);
     LARCV_DEBUG() << "Masking around (tick,wire) = (" << tick << "," << wire << ")" << std::endl;
     for(int row=((int)tick - (int)_row_pad); row<=((int)tick + (int)(_row_pad)); ++row) {
       for(int col=((int)wire - (int)_col_pad); col<=((int)wire + (int)_col_pad); ++col) {
         if(row<0 || row >= (int)(meta.rows())) continue;
         if(col<0 || col >= (int)(meta.cols())) continue;
         LARCV_DEBUG() << "    Registering (row,col) = (" << row << "," << col << ") w/ value " << val << std::endl;
         auto index = meta.index((size_t)row,(size_t)col);
         if(data[index] < val) data[index] = val;
       }
     }
       }
       auto& res = res_v[plane];
       for(size_t index=0; index<data.size(); ++index) {
     if(data[index]<1) continue;
     size_t col = index / meta.rows();
     size_t row = index % meta.rows();
     LARCV_DEBUG() << "Clustering pixel (row,col) = (" << row << "," << col << ")" << std::endl;
     larcv::Pixel2D px2d(col,row);
     px2d.Intensity(data[index]);
     res.emplace_back(std::move(px2d));
       }
       LARCV_INFO() << "Clustered " << res.size() << " points @ plane " << plane << std::endl;
     }
     return res_v;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SuperaKeyPointCluster::finalize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 243 of file SuperaKeyPointCluster.cxx.
References larcv::SuperaBase::finalize().
Referenced by ~SuperaKeyPointCluster().
   { SuperaBase::finalize(); }
GetPoint()
larcv::Vertex larcv::SuperaKeyPointCluster::GetPoint (const supera::LArMCStep_t & step) private
Definition at line 37 of file SuperaKeyPointCluster.cxx.
References _apply_sce, supera::ApplySCE(), and supera::DriftVelocity().
Referenced by process(), and ~SuperaKeyPointCluster().
   {
     static double xyz[3];
     static const double drift_velocity = ::supera::DriftVelocity() * 1.0e-3; // make it cm/ns
     xyz[0] = step.X();
     xyz[1] = step.Y();
     xyz[2] = step.Z();
     if(_apply_sce) supera::ApplySCE(xyz);
     larcv::Vertex pt(xyz[0],xyz[1],xyz[2],
              (double)(step.T() + (xyz[0] / drift_velocity)));
     return pt;
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaKeyPointCluster::initialize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 34 of file SuperaKeyPointCluster.cxx.
References larcv::SuperaBase::initialize().
Referenced by ~SuperaKeyPointCluster().
   { SuperaBase::initialize(); }
is()
bool larcv::SuperaBase::is (const std::string question) const virtual inherited
Reimplemented from larcv::ProcessBase.
Reimplemented in larcv::SuperaChStatus.
Definition at line 83 of file SuperaBase.cxx.
Referenced by larcv::SuperaBase::~SuperaBase().
   {
     if(question == "Supera") return true;
     return false;
   }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &) inherited
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const inherited
Referenced by larcv::SuperaBase::~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const inherited
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const inherited
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const inherited
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const inherited
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const inherited
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v) inherited
Definition at line 121 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v) inherited
Definition at line 124 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v) inherited
Definition at line 127 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v) inherited
Definition at line 130 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v) inherited
Definition at line 133 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v) inherited
Definition at line 136 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v) inherited
Definition at line 139 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const inherited
Definition at line 18 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::SuperaBase::_empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), larcv::SuperaMCROI::process(), and larcv::SuperaBase::~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Meta()
const std::vector< larcv::ImageMeta > & supera::ImageMetaMaker::Meta () const inherited
Definition at line 16 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::Meta(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaSimCh::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimVoxel3D::process(), process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
   {
     if(_meta_maker) return _meta_maker->Meta();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->Meta();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
MetaMakerPtr()
ImageMetaMakerBase* supera::ImageMetaMaker::MetaMakerPtr () inline inherited
Definition at line 51 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker.
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaWire::process(), process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
     { return _meta_maker; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OutPixel2DLabel()
const std::string& supera::ParamsPixel2D::OutPixel2DLabel () const inline inherited
Definition at line 41 of file ParamsPixel2D.h.
References supera::ParamsPixel2D::_out_pixel2d_producer.
Referenced by larcv::SuperaMCPCluster::process(), and process().
 { return _out_pixel2d_producer;  }
process()
bool larcv::SuperaKeyPointCluster::process (IOManager & mgr) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 52 of file SuperaKeyPointCluster.cxx.
References _cluster_primary_start, _cluster_scattering, _cluster_secondary_start, _in_roi_label, supera::ImageMetaMaker::ColCompressionFactor(), CreateCluster(), larcv::IOManager< T >::get_data(), GetPoint(), supera::PulledPork3DSlicer::Is(), larcv::kProductPixel2D, larcv::kProductROI, LARCV_CRITICAL, LARCV_INFO, supera::ImageMetaMaker::Meta(), supera::ImageMetaMaker::MetaMakerPtr(), supera::ParamsPixel2D::OutPixel2DLabel(), larcv::SuperaBase::process(), supera::ImageMetaMaker::RowCompressionFactor(), and larcv::SuperaBase::TimeOffset().
Referenced by ~SuperaKeyPointCluster().
   {
     SuperaBase::process(mgr);
     if(supera::PulledPork3DSlicer::Is(supera::ImageMetaMaker::MetaMakerPtr())) {
       auto ptr = (supera::PulledPork3DSlicer*)(supera::ImageMetaMaker::MetaMakerPtr());
       ptr->ClearEventData();
       ptr->AddConstraint(LArData<supera::LArMCTruth_t>());
       ptr->GenerateMeta(LArData<supera::LArSimCh_t>(),TimeOffset());
     }
     auto ev_pixel2d = (EventPixel2D*)(mgr.get_data(kProductPixel2D,OutPixel2DLabel()));
     if(!ev_pixel2d) {
       LARCV_CRITICAL() << "Failed to create Pixel2D output data container w/ label " << OutPixel2DLabel() << std::endl;
       throw larbys();
     }
     auto ev_roi = (EventROI*)(mgr.get_data(kProductROI,_in_roi_label));
     if(!ev_roi) {
       LARCV_CRITICAL() << "Failed to fetch an input ROI by " << _in_roi_label << std::endl;
       throw larbys();
     }
     std::set<larcv::Vertex> primary_start_s;
     std::set<larcv::Vertex> secondary_start_s;
     std::set<larcv::Vertex> scattering_s;
     for(auto const& mctrack : LArData<supera::LArMCTrack_t>()) {
       if(mctrack.size()<2) continue;
       auto start = GetPoint(mctrack.Start());
       if(mctrack.TrackID() == mctrack.MotherTrackID()) {
     if(_cluster_primary_start) {
       LARCV_INFO() << "Primary MCTrack (PDG " << mctrack.PdgCode() << ") start @ ("
                << start.X() << "," << start.Y() << "," << start.Z() << ")"
                << " @ G4 Time = " << start.T() << " [ns]" << std::endl;
       primary_start_s.emplace(std::move(start));
     }
       }
       else {
     if(_cluster_secondary_start) {
       LARCV_INFO() << "Secondary MCTrack (PDG " << mctrack.PdgCode() << ") start @ ("
                << start.X() << "," << start.Y() << "," << start.Z() << ")"
                << " @ G4 Time = " << start.T() << " [ns]" << std::endl;
       secondary_start_s.emplace(std::move(start));
     }
       }
       if(_cluster_scattering) {
     for(auto const& step : mctrack) {
       if(step.T() == mctrack.Start().T()) continue;
       auto pt = GetPoint(step);
       LARCV_INFO() << "Scattering @ ("
                << pt.X() << "," << pt.Y() << "," << pt.Z() << ")"
                << " @ G4 Time = " << pt.T() << " [ns]" << std::endl;
       scattering_s.emplace(std::move(pt));
     }
       }
     }
     for(auto const& mcshower : LArData<supera::LArMCShower_t>()) {
       if(mcshower.DetProfile().E()<=0) continue;
       auto start = GetPoint(mcshower.Start());
       if(mcshower.TrackID() == mcshower.MotherTrackID()) {
     if(_cluster_primary_start) {
       LARCV_INFO() << "Primary MCShower (PDG " << mcshower.PdgCode() << ") start @ ("
                << start.X() << "," << start.Y() << "," << start.Z() << ")"
                << " @ G4 Time = " << start.T() << " [ns]" << std::endl;
       primary_start_s.emplace(std::move(start));
     }
       }
       else {
     if(_cluster_secondary_start) {
       LARCV_INFO() << "Primary MCShower (PDG " << mcshower.PdgCode() << ") start @ ("
                << start.X() << "," << start.Y() << "," << start.Z() << ")"
                << " @ G4 Time = " << start.T() << " [ns]" << std::endl;
       secondary_start_s.emplace(std::move(start));
     }
       }
       if(_cluster_secondary_start) {
     if(mcshower.Start().T() != mcshower.DetProfile().T()) {
       auto pt = GetPoint(mcshower.DetProfile());
       LARCV_INFO() << "DetProfile @ ("
                << pt.X() << "," << pt.Y() << "," << pt.Z() << ")"
                << " @ G4 Time = " << pt.T() << " [ns]" << std::endl;
       secondary_start_s.emplace(std::move(pt));
     }
       }
     }
     auto meta_v = Meta();
     for(size_t plane=0; plane<meta_v.size(); ++plane) {
       auto& meta = meta_v[plane];
       meta.update(meta.rows() / RowCompressionFactor().at(plane),
           meta.cols() / ColCompressionFactor().at(plane));
     }
     const unsigned short primary_start_val   = 3;
     const unsigned short secondary_start_val = 2;
     const unsigned short scattering_val      = 1;
     LARCV_INFO() << "Creating cluster for primary start from " << primary_start_s.size() << " 3D points." << std::endl;
     auto primary_start_pcluster_v   = CreateCluster( meta_v, primary_start_s,   primary_start_val,   TimeOffset() );
     LARCV_INFO() << "Creating cluster for secondary start from " << secondary_start_s.size() << " 3D points." << std::endl;
     auto secondary_start_pcluster_v = CreateCluster( meta_v, secondary_start_s, secondary_start_val, TimeOffset() );
     LARCV_INFO() << "Creating cluster for scattering points from " << scattering_s.size() << " 3D points." << std::endl;
     auto scattering_pcluster_v      = CreateCluster( meta_v, scattering_s,      scattering_val,      TimeOffset() );
     for(size_t plane=0; plane<meta_v.size(); ++plane) {
       auto const& meta = meta_v[plane];
       ev_pixel2d->Emplace( plane, std::move( primary_start_pcluster_v.at(plane)   ), meta );
       ev_pixel2d->Emplace( plane, std::move( secondary_start_pcluster_v.at(plane) ), meta );
       ev_pixel2d->Emplace( plane, std::move( scattering_pcluster_v.at(plane)      ), meta );
     }
     return true;
   }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name) inherited
Definition at line 15 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::larcv_base::name().
Referenced by larcv::SuperaBase::configure(), and larcv::SuperaBase::~SuperaBase().
   { _data_request_m[type]=name; }
RowCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::RowCompressionFactor () const inherited
Definition at line 26 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::RowCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->RowCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->RowCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline inherited
Definition at line 64 of file SuperaBase.h.
References larcv::SuperaBase::_time_offset, and larcv::SuperaBase::ClearEventData().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaWire::process(), process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
 { return _time_offset; }
Member Data Documentation
_apply_sce
bool larcv::SuperaKeyPointCluster::_apply_sce private
Definition at line 61 of file SuperaKeyPointCluster.h.
Referenced by configure(), and GetPoint().
_cluster_primary_start
bool larcv::SuperaKeyPointCluster::_cluster_primary_start private
Definition at line 64 of file SuperaKeyPointCluster.h.
Referenced by configure(), and process().
_cluster_scattering
bool larcv::SuperaKeyPointCluster::_cluster_scattering private
Definition at line 66 of file SuperaKeyPointCluster.h.
Referenced by configure(), and process().
_cluster_secondary_start
bool larcv::SuperaKeyPointCluster::_cluster_secondary_start private
Definition at line 65 of file SuperaKeyPointCluster.h.
Referenced by configure(), and process().
_col_pad
size_t larcv::SuperaKeyPointCluster::_col_pad private
Definition at line 63 of file SuperaKeyPointCluster.h.
Referenced by configure(), and CreateCluster().
_in_roi_label
std::string larcv::SuperaKeyPointCluster::_in_roi_label private
Definition at line 60 of file SuperaKeyPointCluster.h.
Referenced by configure(), and process().
_row_pad
size_t larcv::SuperaKeyPointCluster::_row_pad private
Definition at line 62 of file SuperaKeyPointCluster.h.
Referenced by configure(), and CreateCluster().
The documentation for this class was generated from the following files:
SuperaKeyPointCluster.h
SuperaKeyPointCluster.cxx