LArCV: larcv::StepDigitizer Class Reference
larcv::StepDigitizer Class Reference
#include <StepDigitizer.h>
Public Member Functions
StepDigitizer (const std::string name="StepDigitizer")
Default constructor.
~StepDigitizer ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _image_producer
std::vector< float > _adc_boundary_v
std::vector< float > _adc_val_v
std::vector< float > _buffer
Detailed Description
Definition at line 26 of file StepDigitizer.h.
Constructor & Destructor Documentation
StepDigitizer()
larcv::StepDigitizer::StepDigitizer (const std::string name = "StepDigitizer")
Default constructor.
Definition at line 11 of file StepDigitizer.cxx.
Referenced by larcv::StepDigitizerProcessFactory::create().
     : ProcessBase(name)
   {}
~StepDigitizer()
larcv::StepDigitizer::~StepDigitizer () inline
Default destructor.
Definition at line 34 of file StepDigitizer.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::StepDigitizer::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file StepDigitizer.cxx.
References _adc_boundary_v, _adc_val_v, _image_producer, larcv::PSet::get(), and LARCV_CRITICAL.
Referenced by ~StepDigitizer().
   {
     _image_producer  = cfg.get< std::string        > ( "ImageProducer" );
     _adc_boundary_v  = cfg.get< std::vector<float> > ( "ADCBoundary"   );
     _adc_val_v       = cfg.get< std::vector<float> > ( "ADCValue"      );
     if( (_adc_boundary_v.size()+1) != _adc_val_v.size() ) {
       LARCV_CRITICAL() << "Boundary ADC values must be shorter than ADC value array by 1!" << std::endl;
       throw larbys();
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::StepDigitizer::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 60 of file StepDigitizer.cxx.
Referenced by ~StepDigitizer().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::StepDigitizer::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 26 of file StepDigitizer.cxx.
Referenced by ~StepDigitizer().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::StepDigitizer::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 29 of file StepDigitizer.cxx.
References _adc_boundary_v, _adc_val_v, _buffer, _image_producer, larcv::IOManager< T >::get_data(), and larcv::kProductImage2D.
Referenced by ~StepDigitizer().
   {
     auto event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_image_producer));
     std::vector<larcv::Image2D> image_v;
     event_image->Move(image_v);
     for(auto& img : image_v) {
       auto const& adc_vec = img.as_vector();
       _buffer.resize(adc_vec.size(),0.);
       for(size_t i=0; i<adc_vec.size(); ++i) {
     float val = _adc_val_v[0];
     for(size_t j=0; j<_buffer.size(); ++j) {
       if(adc_vec[i] < _adc_boundary_v[j]) break;
       val = _adc_val_v[j];
     }
     _buffer[i] = val;
       }
       img.copy(0,0,_buffer,_buffer.size());
     }
     event_image->Emplace(std::move(image_v));
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_adc_boundary_v
std::vector<float> larcv::StepDigitizer::_adc_boundary_v private
Definition at line 47 of file StepDigitizer.h.
Referenced by configure(), and process().
_adc_val_v
std::vector<float> larcv::StepDigitizer::_adc_val_v private
Definition at line 48 of file StepDigitizer.h.
Referenced by configure(), and process().
_buffer
std::vector<float> larcv::StepDigitizer::_buffer private
Definition at line 49 of file StepDigitizer.h.
Referenced by process().
_image_producer
std::string larcv::StepDigitizer::_image_producer private
Definition at line 46 of file StepDigitizer.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
StepDigitizer.h
StepDigitizer.cxx