LArCV: larcv::supera::SuperaCore< R, S, T, U, V, W, Q > Class Template Reference
larcv::supera::SuperaCore< R, S, T, U, V, W, Q > Class Template Reference
User defined class SuperaCore ...
#include <SuperaCore.h>
Public Member Functions
SuperaCore ()
Default constructor.
~SuperaCore ()
Default destructor.
void configure (const Config_t &cfg)
void initialize ()
void clear_data ()
void set_id (unsigned int run, unsigned int subrun, unsigned int event)
bool process_event (const std::vector< R > &, const std::vector< S > &, const std::vector< Q > &, const std::vector< T > &, const std::vector< U > &, const std::vector< V > &, const std::vector< W > &)
void finalize ()
void set_chstatus (unsigned int ch, short status)
void set_chstatus (::larcv::PlaneID_t plane, unsigned int ch, short status)
const std::string & producer_hit () const
const std::string & producer_opdigit () const
const std::string & producer_digit () const
const std::string & producer_wire () const
const std::string & producer_generator () const
const std::string & producer_mcreco () const
const std::string & producer_simch () const
const std::string & producer_chstatus () const
bool use_mc () const
bool store_chstatus () const
const ::larcv::logger & logger () const
void supera_fname (std::string name)
void set_verbosity (unsigned short v)
void fill (Image2D &img, const std::vector< S > &wires, const int time_offset=0)
void fill (Image2D &img, const std::vector< Q > &hits, const int time_offset=0)
void fill (Image2D &img, const std::vector< R > &opdigit_v, const int time_offset=0)
void fill (std::vector< Image2D > &img, const std::vector< U > &mct_v, const std::vector< V > &mcs_v, const std::vector< W > &sch_v, const larcv::supera::InteractionROI_t &interaction_roi, const int time_offset=0)
Private Member Functions
larcv::ImageMeta format_meta (const larcv::ImageMeta &part_image, const larcv::ImageMeta &event_image, const size_t modular_row, const size_t modular_col)
Private Attributes
size_t _run
size_t _subrun
size_t _event
MCParticleTree< T, U, V, W > _mctp
std::map< larcv::PlaneID_t, larcv::ChStatus > _status_m
std::vector< std::pair< unsigned short, unsigned short > > _channel_to_plane_wire
larcv::logger _logger
larcv::IOManager _larcv_io
std::string _producer_hit
std::string _producer_digit
std::string _producer_simch
std::string _producer_wire
std::string _producer_gen
std::string _producer_mcreco
std::string _producer_opdigit
std::string _producer_chstatus
std::vector< size_t > _event_image_cols
std::vector< size_t > _event_image_rows
std::vector< size_t > _event_comp_rows
std::vector< size_t > _event_comp_cols
double _min_time
double _min_wire
int _tpc_tick_offset
int _mc_tick_offset
larcv::Image2D _full_image
bool _skip_empty_image
bool _configured
bool _use_mc
bool _store_chstatus
bool _store_interaction_images
std::string _supera_fname
larcv::ROIType_t _default_roi_type
Detailed Description
template<class R, class S, class T, class U, class V, class W, class Q>
class larcv::supera::SuperaCore< R, S, T, U, V, W, Q >
User defined class SuperaCore ...
these comments are used to generate doxygen documentation!
Definition at line 32 of file SuperaCore.h.
Constructor & Destructor Documentation
SuperaCore()
template<class R, class S, class T, class U, class V, class W, class Q> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::SuperaCore ()
Default constructor.
~SuperaCore()
template<class R, class S, class T, class U, class V, class W, class Q> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::~SuperaCore () inline
Default destructor.
Definition at line 40 of file SuperaCore.h.
 {}
Member Function Documentation
clear_data()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::clear_data () inline
Definition at line 46 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
       { _larcv_io.clear_entry(); _run = _subrun = _event = ::larcv::kINVALID_SIZE; }
configure()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::configure (const Config_t & cfg)
Referenced by larlite::Supera::initialize(), Supera::Supera(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::~SuperaCore().
fill() [1/4]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::fill (Image2D & img, const std::vector< S > & wires, const int time_offset = 0)
Referenced by larlite::SuperaWireAlgo::fillImage(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_verbosity().
fill() [2/4]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::fill (Image2D & img, const std::vector< Q > & hits, const int time_offset = 0)
fill() [3/4]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::fill (Image2D & img, const std::vector< R > & opdigit_v, const int time_offset = 0)
fill() [4/4]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::fill (std::vector< Image2D > & img, const std::vector< U > & mct_v, const std::vector< V > & mcs_v, const std::vector< W > & sch_v, const larcv::supera::InteractionROI_t & interaction_roi, const int time_offset = 0)
finalize()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::finalize ()
Referenced by Supera::endJob(), larlite::Supera::finalize(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_id().
format_meta()
template<class R, class S, class T, class U, class V, class W, class Q> larcv::ImageMeta larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::format_meta (const larcv::ImageMeta & part_image, const larcv::ImageMeta & event_image, const size_t modular_row, const size_t modular_col) private
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_verbosity().
initialize()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::initialize ()
Referenced by Supera::beginJob(), larlite::Supera::initialize(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::~SuperaCore().
logger()
template<class R, class S, class T, class U, class V, class W, class Q> const ::larcv::logger& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::logger () const inline
Definition at line 74 of file SuperaCore.h.
 { return _logger;}
process_event()
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::process_event (const std::vector< R > & , const std::vector< S > & , const std::vector< Q > & , const std::vector< T > & , const std::vector< U > & , const std::vector< V > & , const std::vector< W > &)
Referenced by larlite::Supera::analyze(), Supera::filter(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_id().
producer_chstatus()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_chstatus () const inline
Definition at line 71 of file SuperaCore.h.
Referenced by larlite::Supera::analyze().
 { return _producer_chstatus; }
producer_digit()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_digit () const inline
Definition at line 66 of file SuperaCore.h.
Referenced by Supera::filter().
 { return _producer_digit;    }
producer_generator()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_generator () const inline
Definition at line 68 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _producer_gen;      }
producer_hit()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_hit () const inline
Definition at line 64 of file SuperaCore.h.
Referenced by larlite::Supera::analyze().
 { return _producer_hit;  }
producer_mcreco()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_mcreco () const inline
Definition at line 69 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _producer_mcreco;   }
producer_opdigit()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_opdigit () const inline
Definition at line 65 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _producer_opdigit;  }
producer_simch()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_simch () const inline
Definition at line 70 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _producer_simch;    }
producer_wire()
template<class R, class S, class T, class U, class V, class W, class Q> const std::string& larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_wire () const inline
Definition at line 67 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _producer_wire;     }
set_chstatus() [1/2]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_chstatus (unsigned int ch, short status)
Referenced by larlite::Supera::analyze(), Supera::filter(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_id().
set_chstatus() [2/2]
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_chstatus (::larcv::PlaneID_t plane, unsigned int ch, short status)
set_id()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_id (unsigned int run, unsigned int subrun, unsigned int event) inline
Definition at line 49 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
       { _larcv_io.set_id(run,subrun,event); }
set_verbosity()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_verbosity (unsigned short v) inline
Definition at line 76 of file SuperaCore.h.
Referenced by larlite::SuperaWireAlgo::setVerbosity().
 { _logger.set( (::larcv::msg::Level_t)v ); };
store_chstatus()
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::store_chstatus () const inline
Definition at line 73 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _store_chstatus; }
supera_fname()
template<class R, class S, class T, class U, class V, class W, class Q> void larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::supera_fname (std::string name) inline
Definition at line 75 of file SuperaCore.h.
Referenced by larlite::Supera::supera_fname().
 { _supera_fname = name; }
use_mc()
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::use_mc () const inline
Definition at line 72 of file SuperaCore.h.
Referenced by larlite::Supera::analyze(), and Supera::filter().
 { return _use_mc; }
Member Data Documentation
_channel_to_plane_wire
template<class R, class S, class T, class U, class V, class W, class Q> std::vector<std::pair<unsigned short,unsigned short> > larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_channel_to_plane_wire private
Definition at line 97 of file SuperaCore.h.
_configured
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_configured private
Definition at line 118 of file SuperaCore.h.
_default_roi_type
template<class R, class S, class T, class U, class V, class W, class Q> larcv::ROIType_t larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_default_roi_type private
Definition at line 123 of file SuperaCore.h.
_event
template<class R, class S, class T, class U, class V, class W, class Q> size_t larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_event private
Definition at line 94 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data().
_event_comp_cols
template<class R, class S, class T, class U, class V, class W, class Q> std::vector<size_t> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_event_comp_cols private
Definition at line 111 of file SuperaCore.h.
_event_comp_rows
template<class R, class S, class T, class U, class V, class W, class Q> std::vector<size_t> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_event_comp_rows private
Definition at line 110 of file SuperaCore.h.
_event_image_cols
template<class R, class S, class T, class U, class V, class W, class Q> std::vector<size_t> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_event_image_cols private
Definition at line 108 of file SuperaCore.h.
_event_image_rows
template<class R, class S, class T, class U, class V, class W, class Q> std::vector<size_t> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_event_image_rows private
Definition at line 109 of file SuperaCore.h.
_full_image
template<class R, class S, class T, class U, class V, class W, class Q> larcv::Image2D larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_full_image private
Definition at line 116 of file SuperaCore.h.
_larcv_io
template<class R, class S, class T, class U, class V, class W, class Q> larcv::IOManager larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_larcv_io private
Definition at line 99 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_id().
_logger
template<class R, class S, class T, class U, class V, class W, class Q> larcv::logger larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_logger private
Definition at line 98 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::logger(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_verbosity().
_mc_tick_offset
template<class R, class S, class T, class U, class V, class W, class Q> int larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_mc_tick_offset private
Definition at line 115 of file SuperaCore.h.
_mctp
template<class R, class S, class T, class U, class V, class W, class Q> MCParticleTree<T,U,V,W> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_mctp private
Definition at line 95 of file SuperaCore.h.
_min_time
template<class R, class S, class T, class U, class V, class W, class Q> double larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_min_time private
Definition at line 112 of file SuperaCore.h.
_min_wire
template<class R, class S, class T, class U, class V, class W, class Q> double larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_min_wire private
Definition at line 113 of file SuperaCore.h.
_producer_chstatus
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_chstatus private
Definition at line 107 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_chstatus().
_producer_digit
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_digit private
Definition at line 101 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_digit().
_producer_gen
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_gen private
Definition at line 104 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_generator().
_producer_hit
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_hit private
Definition at line 100 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_hit().
_producer_mcreco
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_mcreco private
Definition at line 105 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_mcreco().
_producer_opdigit
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_opdigit private
Definition at line 106 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_opdigit().
_producer_simch
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_simch private
Definition at line 102 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_simch().
_producer_wire
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_producer_wire private
Definition at line 103 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::producer_wire().
_run
template<class R, class S, class T, class U, class V, class W, class Q> size_t larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_run private
Definition at line 94 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data().
_skip_empty_image
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_skip_empty_image private
Definition at line 117 of file SuperaCore.h.
_status_m
template<class R, class S, class T, class U, class V, class W, class Q> std::map<larcv::PlaneID_t,larcv::ChStatus> larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_status_m private
Definition at line 96 of file SuperaCore.h.
_store_chstatus
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_store_chstatus private
Definition at line 120 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::store_chstatus().
_store_interaction_images
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_store_interaction_images private
Definition at line 121 of file SuperaCore.h.
_subrun
template<class R, class S, class T, class U, class V, class W, class Q> size_t larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_subrun private
Definition at line 94 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data().
_supera_fname
template<class R, class S, class T, class U, class V, class W, class Q> std::string larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_supera_fname private
Definition at line 122 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::supera_fname().
_tpc_tick_offset
template<class R, class S, class T, class U, class V, class W, class Q> int larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_tpc_tick_offset private
Definition at line 114 of file SuperaCore.h.
_use_mc
template<class R, class S, class T, class U, class V, class W, class Q> bool larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::_use_mc private
Definition at line 119 of file SuperaCore.h.
Referenced by larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::use_mc().
The documentation for this class was generated from the following file:
SuperaCore.h