LArCV: larcv::DBSCANProcessFactory Class Reference
larcv::DBSCANProcessFactory Class Reference
#include <DBSCAN.h>
Public Member Functions
DBSCANProcessFactory ()
ctor
~DBSCANProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 61 of file DBSCAN.h.
Constructor & Destructor Documentation
DBSCANProcessFactory()
larcv::DBSCANProcessFactory::DBSCANProcessFactory () inline
ctor
Definition at line 64 of file DBSCAN.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("DBSCAN",this); }
~DBSCANProcessFactory()
larcv::DBSCANProcessFactory::~DBSCANProcessFactory () inline
dtor
Definition at line 66 of file DBSCAN.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::DBSCANProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 68 of file DBSCAN.h.
References larcv::DBSCAN::DBSCAN().
 { return new DBSCAN(instance_name); }
The documentation for this class was generated from the following file:
DBSCAN.h