LArCV: larcv::RandomGaus Class Reference
larcv::RandomGaus Class Reference
Threaded generator for a pool of gaussian random numbers.
#include <RandomGaus.h>
Public Member Functions
RandomGaus (double mean=1., double sigma=0.1, size_t pool_size=10000000)
Default ctor.
RandomGaus (RandomGaus &&rhs)
Move ctor.
~RandomGaus ()
dtor, make sure to join generator thread
void reset (double mean, double sigma)
Reset gaussian parameters.
void start_filling ()
Start thread to fill gaussian random numbers.
void get (std::vector< float > &container)
Retrieve a pool of generated gaussian random numbers (if thread is still running this function will wait)
Private Member Functions
void _fill_ ()
Private Attributes
std::vector< float > _pool
double _mean
double _sigma
std::thread _th
Detailed Description
Threaded generator for a pool of gaussian random numbers.
Definition at line 32 of file RandomGaus.h.
Constructor & Destructor Documentation
RandomGaus() [1/2]
larcv::RandomGaus::RandomGaus (double mean = 1., double sigma = 0.1, size_t pool_size = 10000000)
Default ctor.
Definition at line 9 of file RandomGaus.cxx.
References _pool.
     : _pool(pool_size)
     , _mean(mean)
     , _sigma(sigma)
   {if(_pool.empty()) throw larbys("Empty pool is meaningless!"); }
RandomGaus() [2/2]
larcv::RandomGaus::RandomGaus (RandomGaus && rhs) inline
Move ctor.
Definition at line 38 of file RandomGaus.h.
References _fill_(), reset(), start_filling(), and ~RandomGaus().
                                  : _pool(std::move(rhs._pool))
                  , _mean(rhs._mean)
                  , _sigma(rhs._sigma)
                  , _th(std::move(rhs._th))
     {}
~RandomGaus()
larcv::RandomGaus::~RandomGaus ()
dtor, make sure to join generator thread
Definition at line 15 of file RandomGaus.cxx.
References _th.
Referenced by RandomGaus().
 { if(_th.joinable()) _th.join(); }
Member Function Documentation
_fill_()
void larcv::RandomGaus::_fill_ () private
Definition at line 39 of file RandomGaus.cxx.
References _mean, _pool, and _sigma.
Referenced by RandomGaus(), and start_filling().
{
     std::random_device rd;
     std::mt19937 gen(rd());
     std::normal_distribution<> d(_mean,_sigma);
     for(size_t i=0; i<_pool.size(); ++i)
       _pool[i] = (float)(d(gen));
   }
get()
void larcv::RandomGaus::get (std::vector< float > & container)
Retrieve a pool of generated gaussian random numbers (if thread is still running this function will wait)
Definition at line 27 of file RandomGaus.cxx.
References _pool, _th, and start_filling().
   {
     if(!_th.joinable()) {
       start_filling();
       _th.join();
     }
     else _th.join();
     size_t pool_size=_pool.size();
     container = std::move(_pool);
       _pool.resize(pool_size);
   }
reset()
void larcv::RandomGaus::reset (double mean, double sigma)
Reset gaussian parameters.
Definition at line 17 of file RandomGaus.cxx.
References _mean, and _sigma.
Referenced by RandomGaus().
   { _mean=mean; _sigma=sigma; }
start_filling()
void larcv::RandomGaus::start_filling ()
Start thread to fill gaussian random numbers.
Definition at line 21 of file RandomGaus.cxx.
References _fill_(), and _th.
Referenced by get(), and RandomGaus().
{
     if(_th.joinable()) return;
     std::thread t(&larcv::RandomGaus::_fill_,this);
     _th = std::move(t);
   }
Member Data Documentation
_mean
double larcv::RandomGaus::_mean private
Definition at line 56 of file RandomGaus.h.
Referenced by _fill_(), and reset().
_pool
std::vector<float> larcv::RandomGaus::_pool private
Definition at line 55 of file RandomGaus.h.
Referenced by _fill_(), get(), and RandomGaus().
_sigma
double larcv::RandomGaus::_sigma private
Definition at line 57 of file RandomGaus.h.
Referenced by _fill_(), and reset().
_th
std::thread larcv::RandomGaus::_th private
Definition at line 59 of file RandomGaus.h.
Referenced by get(), start_filling(), and ~RandomGaus().
The documentation for this class was generated from the following files:
RandomGaus.h
RandomGaus.cxx