LArCV: larcv::DBSCAN Class Reference
larcv::DBSCAN Class Reference
#include <DBSCAN.h>
Public Member Functions
DBSCAN (const std::string name="DBSCAN")
Default constructor.
~DBSCAN ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
std::string ftpc_producer
std::vector< std::string > fauxdata_producers
std::vector< float > fauxdim_scale
std::string foutput_producer
std::vector< double > feps
std::vector< int > fminpoints
std::vector< double > fthreshold
Detailed Description
Definition at line 26 of file DBSCAN.h.
Constructor & Destructor Documentation
DBSCAN()
larcv::DBSCAN::DBSCAN (const std::string name = "DBSCAN")
Default constructor.
Definition at line 15 of file DBSCAN.cxx.
Referenced by larcv::DBSCANProcessFactory::create().
     : ProcessBase(name)
   {
   }
~DBSCAN()
larcv::DBSCAN::~DBSCAN () inline
Default destructor.
Definition at line 34 of file DBSCAN.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::DBSCAN::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 20 of file DBSCAN.cxx.
References fauxdata_producers, fauxdim_scale, feps, fminpoints, foutput_producer, fthreshold, ftpc_producer, and larcv::PSet::get().
Referenced by ~DBSCAN().
   {
     ftpc_producer      = cfg.get<std::string>("TPCImageProducer");
     fauxdata_producers = cfg.get<std::vector<std::string> >("AuxDataImageProducer");
     fauxdim_scale      = cfg.get<std::vector<float> >("AuxDimScales");
     foutput_producer   = cfg.get<std::string>("OutputImageProducer");
     feps               = cfg.get< std::vector<double> >("planeNeighborRadius");
     fminpoints         = cfg.get< std::vector<int> >("planeMinPoints");
     fthreshold         = cfg.get< std::vector<double> >("adchitthreshold");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::DBSCAN::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 121 of file DBSCAN.cxx.
Referenced by ~DBSCAN().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DBSCAN::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 32 of file DBSCAN.cxx.
Referenced by ~DBSCAN().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DBSCAN::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 35 of file DBSCAN.cxx.
References dbscan::dbscanOutput::clusters, larcv::ImageMeta::cols(), larcv::EventImage2D::Emplace(), eps, fauxdata_producers, fauxdim_scale, feps, fminpoints, foutput_producer, fthreshold, ftpc_producer, larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::kProductImage2D, LARCV_DEBUG, LARCV_INFO, larcv::Image2D::paint(), larcv::ImageMeta::plane(), larcv::ImageMeta::rows(), dbscan::DBSCANAlgo::scan(), and larcv::Image2D::set_pixel().
Referenced by ~DBSCAN().
   {
     larcv::EventImage2D* input_imgs  = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, ftpc_producer );
     larcv::EventImage2D* output_imgs = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, foutput_producer );
     int nauxproducers = (int)fauxdata_producers.size();
     larcv::EventImage2D* aux_imgs[nauxproducers];
     for (int iaux=0; iaux<nauxproducers; iaux++) {
       aux_imgs[iaux] = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, fauxdata_producers.at(iaux) );
     }
     // go through each plane.
     std::vector< larcv::Image2D > output_images;
     for ( auto const& img : input_imgs->Image2DArray() ) {
       // set image meta parameters, clustering parameters
       const larcv::ImageMeta& meta = img.meta();
       int plane     = (int)meta.plane();
       double thresh = fthreshold.at(plane);
       double eps    = feps.at(plane);
       int minpoints = fminpoints.at(plane);
       LARCV_INFO() << "clustering plane=" << plane << ": thresh=" << thresh << " radius=" << eps << " minpoints=" << minpoints << std::endl;
       // find hits.
       dbscan::dbPoints pixels;
       LARCV_DEBUG() << "making points for above threshold pixels" << std::endl;
       for (size_t c=0; c<meta.cols(); c++) {
     for (size_t r=0; r<meta.rows(); r++) {
       if ( img.pixel( r, c )>thresh ) {
         // hit found, we assemble out point in augmented space
         // i.e., we combine 2D position, plus values from auxillary image data
         std::vector<double> pt(2+nauxproducers,0.0);
         // set the 2D position
         pt.at(0) = c;
         pt.at(1) = r;
         // set the aux values
         for (int iaux=0; iaux<nauxproducers; iaux++) {
           const std::vector<larcv::Image2D>& aux_v = aux_imgs[iaux]->Image2DArray();
           // find the matching plane
           for (auto &aux_img : aux_v ) {
         if ( aux_img.meta().plane()==plane ) {
           // found the matching plane
           pt.at(2+iaux) = aux_img.pixel(r,c)/fauxdim_scale.at(iaux); // value scaled
         }
           }
         }
         pixels.emplace_back(pt);
       }
     }
       }
       LARCV_DEBUG() << "run dbscan algo" << std::endl;
       dbscan::DBSCANAlgo algo;
       dbscan::dbscanOutput clusterout = algo.scan( pixels, minpoints, eps );
       LARCV_DEBUG() << "dbscan algo finished" << std::endl;
       // make output image
       larcv::Image2D imgout( meta );
       imgout.paint(0.0);
       LARCV_INFO() << "number of clusters found in plane=" << plane << ": " << clusterout.clusters.size() << std::endl;
       // nothing = 0
       // background labeled with 1
       // rest increment cluster id i+1
       LARCV_DEBUG() << "make output cluster image" << std::endl;
       for (size_t ic=0; ic<clusterout.clusters.size(); ic++) {
     const std::vector< int >& cl = clusterout.clusters.at(ic);
     for ( auto& idx : cl ) {
       const std::vector<double>& pix = pixels.at(idx);
       if ( cl.size()>1 )
         imgout.set_pixel( (int)(pix.at(1)+0.1), (int)(pix.at(0)+0.1), ic+1 );
       else
         imgout.set_pixel( (int)(pix.at(1)+0.1), (int)(pix.at(0)+0.1), 1 );
     }
       }
       output_images.emplace_back( imgout );
     }
     output_imgs->Emplace( std::move(output_images) );
     return true;
   }//end of analyze
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fauxdata_producers
std::vector<std::string> larcv::DBSCAN::fauxdata_producers protected
Definition at line 47 of file DBSCAN.h.
Referenced by configure(), and process().
fauxdim_scale
std::vector<float> larcv::DBSCAN::fauxdim_scale protected
Definition at line 48 of file DBSCAN.h.
Referenced by configure(), and process().
feps
std::vector<double> larcv::DBSCAN::feps protected
Definition at line 51 of file DBSCAN.h.
Referenced by configure(), and process().
fminpoints
std::vector<int> larcv::DBSCAN::fminpoints protected
Definition at line 52 of file DBSCAN.h.
Referenced by configure(), and process().
foutput_producer
std::string larcv::DBSCAN::foutput_producer protected
Definition at line 50 of file DBSCAN.h.
Referenced by configure(), and process().
fthreshold
std::vector<double> larcv::DBSCAN::fthreshold protected
Definition at line 53 of file DBSCAN.h.
Referenced by configure(), and process().
ftpc_producer
std::string larcv::DBSCAN::ftpc_producer protected
Definition at line 46 of file DBSCAN.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
DBSCAN.h
DBSCAN.cxx