LArCV: dbscan::ClusterExtrema Class Reference
dbscan::ClusterExtrema Class Reference
#include <DBSCANAlgo.h>
Public Types
enum Extrema_t {
kleftmost =0, krightmost, ktopmost, kbottommost,
kNumExtrema
}
Public Member Functions
virtual ~ClusterExtrema ()
bool isempty () const
const std::vector< double > & leftmost () const
const std::vector< double > & rightmost () const
const std::vector< double > & topmost () const
const std::vector< double > & bottommost () const
const std::vector< double > & extrema (const Extrema_t whichpoint) const
std::vector< double > & leftmost ()
std::vector< double > & rightmost ()
std::vector< double > & topmost ()
std::vector< double > & bottommost ()
std::vector< double > & extrema (const Extrema_t whichpoint)
Static Public Member Functions
static ClusterExtrema FindClusterExtrema (const int cluster_id, const dbscanOutput &clustering_info, const dbPoints &hitlist)
static ClusterExtrema FindClusterExtrema (const dbCluster &cluster, const dbPoints &hitlist)
static ClusterExtrema MakeEmptyExtrema ()
Public Attributes
std::vector< std::vector< double > > m_extrema
bool empty
Protected Member Functions
ClusterExtrema ()
Detailed Description
Definition at line 55 of file DBSCANAlgo.h.
Member Enumeration Documentation
Extrema_t
enum dbscan::ClusterExtrema::Extrema_t
Enumerator
kleftmost
krightmost
ktopmost
kbottommost
kNumExtrema
Definition at line 57 of file DBSCANAlgo.h.
 { kleftmost=0, krightmost, ktopmost, kbottommost, kNumExtrema } Extrema_t;
Constructor & Destructor Documentation
ClusterExtrema()
dbscan::ClusterExtrema::ClusterExtrema () inline protected
Definition at line 64 of file DBSCANAlgo.h.
{
         empty = false;
         m_extrema.resize(4);
         for (size_t i=0; i<(size_t)kNumExtrema; i++ )
           m_extrema.at(i).resize(2,0.0);
       };
~ClusterExtrema()
virtual dbscan::ClusterExtrema::~ClusterExtrema () inline virtual
Definition at line 72 of file DBSCANAlgo.h.
 {};
Member Function Documentation
bottommost() [1/2]
const std::vector<double>& dbscan::ClusterExtrema::bottommost () const inline
Definition at line 78 of file DBSCANAlgo.h.
Referenced by FindClusterExtrema().
 { return m_extrema[kbottommost]; }
bottommost() [2/2]
std::vector<double>& dbscan::ClusterExtrema::bottommost () inline
Definition at line 83 of file DBSCANAlgo.h.
 { return m_extrema[kbottommost]; }
extrema() [1/2]
const std::vector<double>& dbscan::ClusterExtrema::extrema (const Extrema_t whichpoint) const inline
Definition at line 79 of file DBSCANAlgo.h.
 { return m_extrema[(size_t)whichpoint]; }
extrema() [2/2]
std::vector<double>& dbscan::ClusterExtrema::extrema (const Extrema_t whichpoint) inline
Definition at line 84 of file DBSCANAlgo.h.
 { return m_extrema[(size_t)whichpoint]; }
FindClusterExtrema() [1/2]
ClusterExtrema dbscan::ClusterExtrema::FindClusterExtrema (const int cluster_id, const dbscanOutput & clustering_info, const dbPoints & hitlist) static
Definition at line 305 of file DBSCANAlgo.cxx.
References dbscan::dbscanOutput::clusters.
{
     if ( cluster_id <0 || cluster_id >= (int)clustering_info.clusters.size() )
         throw std::runtime_error("ClusterExtrema::FindClusterExtrema[error] cluster id is invalid");
     const dbCluster& cluster = clustering_info.clusters.at(cluster_id);
     return ClusterExtrema::FindClusterExtrema( cluster, hitlist );
   }
FindClusterExtrema() [2/2]
ClusterExtrema dbscan::ClusterExtrema::FindClusterExtrema (const dbCluster & cluster, const dbPoints & hitlist) static
Definition at line 313 of file DBSCANAlgo.cxx.
References bottommost(), empty, leftmost(), rightmost(), and topmost().
{
     ClusterExtrema extrema;
     if ( cluster.size()==0 )
       return extrema;
     // seed the values
     int firsthit_idx = cluster.front();
     const std::vector<double>& hit = hitlist.at(firsthit_idx);
     extrema.leftmost() = hit;
     extrema.rightmost() = hit;
     extrema.topmost() = hit;
     extrema.bottommost() = hit;
     // find the extrema
     for ( int ihit=1; ihit<(int)cluster.size(); ihit++) {
       int hitidx = cluster.at(ihit);
       const std::vector<double>& hit = hitlist.at(hitidx);
       if ( hit[0]<extrema.leftmost()[0]) {
         extrema.leftmost()[0] = hit[0];
         extrema.leftmost()[1] = hit[1];
       }
       if (hit[0]>extrema.rightmost()[0]) {
         extrema.rightmost()[0] = hit[0];
         extrema.rightmost()[1] = hit[1];
       }
       if (hit[1]>extrema.topmost()[1]) {
         extrema.topmost()[0] = hit[0];
         extrema.topmost()[1] = hit[1];
       }
       if (hit[1]<extrema.bottommost()[1]) {
         extrema.bottommost()[0] = hit[0];
         extrema.bottommost()[1] = hit[1];
       }
     }
     extrema.empty = false;
     return extrema;
   }
isempty()
bool dbscan::ClusterExtrema::isempty () const inline
Definition at line 74 of file DBSCANAlgo.h.
 { return empty; }
leftmost() [1/2]
const std::vector<double>& dbscan::ClusterExtrema::leftmost () const inline
Definition at line 75 of file DBSCANAlgo.h.
Referenced by FindClusterExtrema().
 { return m_extrema[kleftmost]; }
leftmost() [2/2]
std::vector<double>& dbscan::ClusterExtrema::leftmost () inline
Definition at line 80 of file DBSCANAlgo.h.
 { return m_extrema[kleftmost]; }
MakeEmptyExtrema()
ClusterExtrema dbscan::ClusterExtrema::MakeEmptyExtrema () static
Definition at line 352 of file DBSCANAlgo.cxx.
{
     ClusterExtrema empty;
     return empty;
   }
rightmost() [1/2]
const std::vector<double>& dbscan::ClusterExtrema::rightmost () const inline
Definition at line 76 of file DBSCANAlgo.h.
Referenced by FindClusterExtrema().
 { return m_extrema[krightmost]; }
rightmost() [2/2]
std::vector<double>& dbscan::ClusterExtrema::rightmost () inline
Definition at line 81 of file DBSCANAlgo.h.
 { return m_extrema[krightmost]; }
topmost() [1/2]
const std::vector<double>& dbscan::ClusterExtrema::topmost () const inline
Definition at line 77 of file DBSCANAlgo.h.
Referenced by FindClusterExtrema().
 { return m_extrema[ktopmost]; }
topmost() [2/2]
std::vector<double>& dbscan::ClusterExtrema::topmost () inline
Definition at line 82 of file DBSCANAlgo.h.
 { return m_extrema[ktopmost]; }
Member Data Documentation
empty
bool dbscan::ClusterExtrema::empty
Definition at line 60 of file DBSCANAlgo.h.
Referenced by FindClusterExtrema().
m_extrema
std::vector< std::vector<double> > dbscan::ClusterExtrema::m_extrema
Definition at line 59 of file DBSCANAlgo.h.
The documentation for this class was generated from the following files:
DBSCANAlgo.h
DBSCANAlgo.cxx