LArCV: larcv::EventPGraph Class Reference
larcv::EventPGraph Class Reference
Event-wise class to store a collection of larcv::PGraph.
#include <EventPGraph.h>
Public Member Functions
EventPGraph ()
Default constructor.
~EventPGraph ()
Default destructor.
void clear ()
larcv::PGraph array clearer
const std::vector< larcv::PGraph > & PGraphArray () const
larcv::PGraph array const reference getter
const PGraph & at (size_t id) const
larcv::PGraph array index accessor
void Append (const PGraph &img)
larcv::PGraph inserter
void Set (const std::vector< larcv::PGraph > &int_v)
larcv::PGraph array to replace what is stored
void Emplace (PGraph &&img)
Emplacer for larcv::PGraph.
void Emplace (std::vector< larcv::PGraph > &&int_v)
Emplacer for larcv::PGraph array.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::vector< larcv::PGraph > _int_v
Detailed Description
Event-wise class to store a collection of larcv::PGraph.
A concrete factory class for larcv::EventPGraph.
Definition at line 26 of file EventPGraph.h.
Constructor & Destructor Documentation
EventPGraph()
larcv::EventPGraph::EventPGraph () inline
Default constructor.
Definition at line 31 of file EventPGraph.h.
Referenced by larcv::EventPGraphFactory::create().
 {}
~EventPGraph()
larcv::EventPGraph::~EventPGraph () inline
Default destructor.
Definition at line 34 of file EventPGraph.h.
References clear().
 {}
Member Function Documentation
Append()
void larcv::EventPGraph::Append (const PGraph & img)
larcv::PGraph inserter
Definition at line 23 of file EventPGraph.cxx.
References _int_v.
Referenced by PGraphArray(), and Set().
   {
     _int_v.push_back(part);
     //_int_v.back().Index(_int_v.size()-1);
   }
at()
const PGraph & larcv::EventPGraph::at (size_t id) const
larcv::PGraph array index accessor
Definition at line 17 of file EventPGraph.cxx.
References _int_v.
Referenced by PGraphArray().
   {
     if( id >= _int_v.size() ) throw larbys("Invalid request (ImageIndex_t out-o-range)!");
     return _int_v[id];
   }
clear()
void larcv::EventPGraph::clear () virtual
larcv::PGraph array clearer
Reimplemented from larcv::EventBase.
Definition at line 11 of file EventPGraph.cxx.
References _int_v, and larcv::EventBase::clear().
Referenced by ~EventPGraph().
   {
     EventBase::clear();
     _int_v.clear();
   }
Emplace() [1/2]
void larcv::EventPGraph::Emplace (PGraph && img)
Emplacer for larcv::PGraph.
Definition at line 36 of file EventPGraph.cxx.
References _int_v.
Referenced by PGraphArray().
   {
     _int_v.emplace_back(part);
     //_int_v.back().Index(_int_v.size()-1);
   }
Emplace() [2/2]
void larcv::EventPGraph::Emplace (std::vector< larcv::PGraph > && int_v)
Emplacer for larcv::PGraph array.
Definition at line 42 of file EventPGraph.cxx.
References _int_v.
   {
     _int_v = std::move(int_v);
     //for(size_t i=0; i<_int_v.size(); ++i) _int_v[i].Index(i);
   }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
PGraphArray()
const std::vector<larcv::PGraph>& larcv::EventPGraph::PGraphArray () const inline
larcv::PGraph array const reference getter
Definition at line 40 of file EventPGraph.h.
References _int_v, Append(), at(), Emplace(), and Set().
Referenced by larcv::ExampleAna::Analyze(), larcv::ParticleAna::AnalyzeAngle(), larcv::ParticleAna::AnalyzedQdX(), larcv::ParticleAna::AnalyzeParticle(), larcv::ParticleAna::AnalyzeSignal(), larcv::VertexAna::process(), larcv::BadRegionAna::process(), and larcv::CosmicVertexAna::process().
 { return _int_v; }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
Set()
void larcv::EventPGraph::Set (const std::vector< larcv::PGraph > & int_v)
larcv::PGraph array to replace what is stored
Definition at line 29 of file EventPGraph.cxx.
References _int_v, and Append().
Referenced by PGraphArray().
   {
     _int_v.clear();
     _int_v.reserve(int_v.size());
     for(auto const& p : int_v) Append(p);
   }
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
_int_v
std::vector<larcv::PGraph> larcv::EventPGraph::_int_v private
Definition at line 59 of file EventPGraph.h.
Referenced by Append(), at(), clear(), Emplace(), PGraphArray(), and Set().
The documentation for this class was generated from the following files:
EventPGraph.h
EventPGraph.cxx