LArCV: larcv::MergeTwoStream Class Reference
larcv::MergeTwoStream Class Reference
User defined class MergeTwoStream ...
#include <MergeTwoStream.h>
Public Member Functions
MergeTwoStream ()
Default constructor.
~MergeTwoStream ()
Default destructor.
void configure (std::string cfg_file)
void override_input_file (const std::vector< std::string > &nu_flist=std::vector< std::string >(), const std::vector< std::string > &cosmic_flist=std::vector< std::string >())
void override_ana_file (std::string out_ana_fname)
void override_output_file (std::string out_fname)
void initialize ()
bool process ()
void batch_process ()
void finalize ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
ProcessDriver _in1_driver
ImageHolder * _in1_proc
std::string _in1_proc_name
ProcessDriver _in2_driver
ImageHolder * _in2_proc
std::string _in2_proc_name
ProcessDriver _merge_driver
ImageMerger * _merge_proc
std::string _merge_proc_name
bool _prepared
size_t _num_in1
size_t _num_in2
size_t _num_processed
size_t _num_input_max
size_t _num_output_max
size_t _num_frac
Detailed Description
User defined class MergeTwoStream ...
these comments are used to generate doxygen documentation!
Definition at line 27 of file MergeTwoStream.h.
Constructor & Destructor Documentation
MergeTwoStream()
larcv::MergeTwoStream::MergeTwoStream ()
Default constructor.
Definition at line 12 of file MergeTwoStream.cxx.
                                  : larcv_base      ( "MergeTwoStream"   )
                    , _in1_driver     ( "InputStream1"     )
                    , _in1_proc       ( nullptr            )
                    , _in1_proc_name  ( ""                 )
                    , _in2_driver     ( "InputStream2"     )
                    , _in2_proc       ( nullptr            )
                    , _in2_proc_name  ( ""                 )
                    , _merge_driver   ( "OutStream"        )
                    , _prepared       (false)
                    , _num_in1        (0)
                    , _num_in2        (0)
                    , _num_processed  (0)
                    , _num_input_max  (0)
                    , _num_output_max (0)
                    , _num_frac       (0)
   {}
~MergeTwoStream()
larcv::MergeTwoStream::~MergeTwoStream () inline
Default destructor.
Definition at line 35 of file MergeTwoStream.h.
References batch_process(), configure(), finalize(), initialize(), override_ana_file(), override_input_file(), override_output_file(), and process().
 {}
Member Function Documentation
batch_process()
void larcv::MergeTwoStream::batch_process ()
Definition at line 172 of file MergeTwoStream.cxx.
References _num_output_max, _num_processed, LARCV_NORMAL, and process().
Referenced by ~MergeTwoStream().
   {
     while(_num_processed<_num_output_max) if(!process()) break;
     LARCV_NORMAL() << "Finished 100%" << std::endl;
   }
configure()
void larcv::MergeTwoStream::configure (std::string cfg_file)
Definition at line 60 of file MergeTwoStream.cxx.
References _in1_driver, _in1_proc_name, _in2_driver, _in2_proc_name, _merge_driver, _merge_proc_name, _num_output_max, _prepared, larcv::ProcessDriver::configure(), larcv::CreatePSetFromFile(), LARCV_CRITICAL, LARCV_NORMAL, LARCV_WARNING, larcv::larcv_base::name(), and larcv::larcv_base::set_verbosity().
Referenced by ~MergeTwoStream().
   {
     if(_prepared) {
       LARCV_CRITICAL() << "Cannot re-configure after initialized..." << std::endl;
       throw larbys();
     }
     auto main_cfg = CreatePSetFromFile(cfg_file);
     auto const& cfg = main_cfg.get_pset(name());
     if(!cfg.contains_pset(_in2_driver.name())) {
       LARCV_CRITICAL() << "InputStream2 parameter set not found..." << std::endl;
       throw larbys();
     }
     if(!cfg.contains_pset(_in1_driver.name())) {
       LARCV_CRITICAL() << "InputStream1 parameter set not found..." << std::endl;
       throw larbys();
     }
     if(!cfg.contains_pset(_merge_driver.name())) {
       LARCV_CRITICAL() << "OutStream parameter set not found..." << std::endl;
       throw larbys();
     }
     _in2_proc_name = cfg.get<std::string>("Input2ImageHolder");
     if(_in2_proc_name.empty()) {
       LARCV_CRITICAL() << "Input2ImageHolder name is empty" << std::endl;
       throw larbys();
     }
     _in1_proc_name = cfg.get<std::string>("Input1ImageHolder");
     if(_in1_proc_name.empty()) {
       LARCV_CRITICAL() << "Input1ImageHolder name is empty" << std::endl;
       throw larbys();
     }
     _merge_proc_name = cfg.get<std::string>("ImageMerger");
     if(_merge_proc_name.empty()) {
       LARCV_CRITICAL() << "ImageMerger name is empty" << std::endl;
       throw larbys();
     }
     LARCV_WARNING() << "Note CosmicDataStream should contain image to-be-overlayed with ROI (Stream2 is the base image)"<<std::endl;
     LARCV_NORMAL() << "Registered Input1: " << _in2_proc_name << std::endl;
     LARCV_NORMAL() << "Registered Input2: " << _in1_proc_name << std::endl;
     LARCV_NORMAL() << "Registered Output: " << _merge_proc_name << std::endl;
     set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     _num_output_max = cfg.get<size_t>("MaxOutputEntries");
     _merge_driver.configure(cfg.get_pset(_merge_driver.name()));
     _in2_driver.configure(cfg.get_pset(_in2_driver.name()));
     _in1_driver.configure(cfg.get_pset(_in1_driver.name()));
   }
finalize()
void larcv::MergeTwoStream::finalize ()
Definition at line 178 of file MergeTwoStream.cxx.
References _in1_driver, _in2_driver, _merge_driver, _prepared, larcv::ProcessDriver::finalize(), and LARCV_CRITICAL.
Referenced by ~MergeTwoStream().
   {
     if(!_prepared) {
       LARCV_CRITICAL() << "Must call initialize() beore process()" << std::endl;
       throw larbys();
     }
     _in1_driver.finalize();
     _in2_driver.finalize();
     _merge_driver.finalize();
   }
initialize()
void larcv::MergeTwoStream::initialize ()
Definition at line 108 of file MergeTwoStream.cxx.
References _in1_driver, _in1_proc, _in1_proc_name, _in2_driver, _in2_proc, _in2_proc_name, _merge_driver, _merge_proc, _merge_proc_name, _num_frac, _num_in1, _num_in2, _num_input_max, _num_output_max, _num_processed, _prepared, larcv::IOManager< T >::get_n_entries(), larcv::ProcessDriver::initialize(), larcv::ImageMerger::InputImageHolder1(), larcv::ImageMerger::InputImageHolder2(), larcv::ProcessDriver::io(), LARCV_NORMAL, larcv::ProcessDriver::process_id(), and larcv::ProcessDriver::process_ptr().
Referenced by ~MergeTwoStream().
   {
     _merge_driver.initialize();
     _in2_driver.initialize();
     _in1_driver.initialize();
     // retrieve image holder 1 & 2
     auto const id_cosmic = _in2_driver.process_id(_in2_proc_name);
     _in2_proc = (ImageHolder*)(_in2_driver.process_ptr(id_cosmic));
     auto const id_nu = _in1_driver.process_id(_in1_proc_name);
     _in1_proc = (ImageHolder*)(_in1_driver.process_ptr(id_nu));
     auto const id_merged = _merge_driver.process_id(_merge_proc_name);
     _merge_proc = (ImageMerger*)(_merge_driver.process_ptr(id_merged));
     _merge_proc->InputImageHolder1(_in1_proc);
     _merge_proc->InputImageHolder2(_in2_proc);
     _prepared=true;
     _num_in2 = 0;
     _num_in1 = 0;
     _num_input_max = std::min(_in2_driver.io().get_n_entries(),_in1_driver.io().get_n_entries());
     _num_frac = _num_input_max/10 + 1;
     if(_num_output_max > _num_input_max) {
       LARCV_NORMAL() << "Only " << _num_input_max << " entries available from input. Re-setting output max entry..." << std::endl;
       _num_output_max = _num_input_max;
     }
     LARCV_NORMAL() << "Processing max " << _num_output_max << " entries..." << std::endl;
     _num_processed = 0;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
override_ana_file()
void larcv::MergeTwoStream::override_ana_file (std::string out_ana_fname)
Definition at line 42 of file MergeTwoStream.cxx.
References _merge_driver, _prepared, LARCV_CRITICAL, and larcv::ProcessDriver::override_ana_file().
Referenced by ~MergeTwoStream().
   {
     if(_prepared) {
       LARCV_CRITICAL() << "Cannot re-configure after initialized..." << std::endl;
       throw larbys();
     }
     _merge_driver.override_ana_file(out_ana_fname);
   }
override_input_file()
void larcv::MergeTwoStream::override_input_file (const std::vector< std::string > & nu_flist = std::vector<std::string>(), const std::vector< std::string > & cosmic_flist = std::vector<std::string>())
Definition at line 29 of file MergeTwoStream.cxx.
References _in1_driver, _in2_driver, _prepared, LARCV_CRITICAL, and larcv::ProcessDriver::override_input_file().
Referenced by ~MergeTwoStream().
   {
     if(_prepared) {
       LARCV_CRITICAL() << "Cannot re-configure after initialized..." << std::endl;
       throw larbys();
     }
     if(in1_flist.size())
       _in1_driver.override_input_file(in1_flist);
     if(in2_flist.size())
       _in2_driver.override_input_file(in2_flist);
   }
override_output_file()
void larcv::MergeTwoStream::override_output_file (std::string out_fname)
Definition at line 51 of file MergeTwoStream.cxx.
References _merge_driver, _prepared, LARCV_CRITICAL, and larcv::ProcessDriver::override_output_file().
Referenced by ~MergeTwoStream().
   {
     if(_prepared) {
       LARCV_CRITICAL() << "Cannot re-configure after initialized..." << std::endl;
       throw larbys();
     }
     _merge_driver.override_output_file(out_fname);
   }
process()
bool larcv::MergeTwoStream::process ()
Definition at line 135 of file MergeTwoStream.cxx.
References _in1_driver, _in2_driver, _merge_driver, _num_frac, _num_in1, _num_in2, _num_input_max, _num_output_max, _num_processed, _prepared, LARCV_CRITICAL, LARCV_INFO, LARCV_NORMAL, and larcv::ProcessDriver::process_entry().
Referenced by batch_process(), and ~MergeTwoStream().
   {
     if(!_prepared) {
       LARCV_CRITICAL() << "Must call initialize() beore process()" << std::endl;
       throw larbys();
     }
     if(_num_processed > _num_output_max) {
       LARCV_CRITICAL() << "No more output entry to be made!" << std::endl;
       return false;
     }
     while(_num_in2 < _num_input_max) {
       ++_num_in2;
       if(_in2_driver.process_entry()) break;
     }
     while(_num_in1 < _num_input_max) {
       ++_num_in1;
       if(_in1_driver.process_entry()) break;
     }
     if(_num_in2 > _num_input_max) return false;
     if(_num_in1 > _num_input_max) return false;
     LARCV_INFO() << "Processing InputStream1 entry " << _num_in2
          << " ... InputStream2 entry " << _num_in1 << std::endl;
     _merge_driver.process_entry();
     ++_num_processed;
     if(_num_output_max < 10)
       { LARCV_NORMAL() << "Processed " << _num_processed << " entries..." << std::endl; }
     else if( _num_processed && (_num_processed%_num_frac == 0) )
       { LARCV_NORMAL() << "Processed " << 10*((_num_processed/_num_frac)+1) << " % processed..." << std::endl; }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_in1_driver
ProcessDriver larcv::MergeTwoStream::_in1_driver private
Definition at line 55 of file MergeTwoStream.h.
Referenced by configure(), finalize(), initialize(), override_input_file(), and process().
_in1_proc
ImageHolder* larcv::MergeTwoStream::_in1_proc private
Definition at line 56 of file MergeTwoStream.h.
Referenced by initialize().
_in1_proc_name
std::string larcv::MergeTwoStream::_in1_proc_name private
Definition at line 57 of file MergeTwoStream.h.
Referenced by configure(), and initialize().
_in2_driver
ProcessDriver larcv::MergeTwoStream::_in2_driver private
Definition at line 59 of file MergeTwoStream.h.
Referenced by configure(), finalize(), initialize(), override_input_file(), and process().
_in2_proc
ImageHolder* larcv::MergeTwoStream::_in2_proc private
Definition at line 60 of file MergeTwoStream.h.
Referenced by initialize().
_in2_proc_name
std::string larcv::MergeTwoStream::_in2_proc_name private
Definition at line 61 of file MergeTwoStream.h.
Referenced by configure(), and initialize().
_merge_driver
ProcessDriver larcv::MergeTwoStream::_merge_driver private
Definition at line 63 of file MergeTwoStream.h.
Referenced by configure(), finalize(), initialize(), override_ana_file(), override_output_file(), and process().
_merge_proc
ImageMerger* larcv::MergeTwoStream::_merge_proc private
Definition at line 64 of file MergeTwoStream.h.
Referenced by initialize().
_merge_proc_name
std::string larcv::MergeTwoStream::_merge_proc_name private
Definition at line 65 of file MergeTwoStream.h.
Referenced by configure(), and initialize().
_num_frac
size_t larcv::MergeTwoStream::_num_frac private
Definition at line 73 of file MergeTwoStream.h.
Referenced by initialize(), and process().
_num_in1
size_t larcv::MergeTwoStream::_num_in1 private
Definition at line 68 of file MergeTwoStream.h.
Referenced by initialize(), and process().
_num_in2
size_t larcv::MergeTwoStream::_num_in2 private
Definition at line 69 of file MergeTwoStream.h.
Referenced by initialize(), and process().
_num_input_max
size_t larcv::MergeTwoStream::_num_input_max private
Definition at line 71 of file MergeTwoStream.h.
Referenced by initialize(), and process().
_num_output_max
size_t larcv::MergeTwoStream::_num_output_max private
Definition at line 72 of file MergeTwoStream.h.
Referenced by batch_process(), configure(), initialize(), and process().
_num_processed
size_t larcv::MergeTwoStream::_num_processed private
Definition at line 70 of file MergeTwoStream.h.
Referenced by batch_process(), initialize(), and process().
_prepared
bool larcv::MergeTwoStream::_prepared private
Definition at line 67 of file MergeTwoStream.h.
Referenced by configure(), finalize(), initialize(), override_ana_file(), override_input_file(), override_output_file(), and process().
The documentation for this class was generated from the following files:
MergeTwoStream.h
MergeTwoStream.cxx