LArCV: larcv::QSumFilterProcessFactory Class Reference
larcv::QSumFilterProcessFactory Class Reference
#include <QSumFilter.h>
Public Member Functions
QSumFilterProcessFactory ()
ctor
~QSumFilterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 57 of file QSumFilter.h.
Constructor & Destructor Documentation
QSumFilterProcessFactory()
larcv::QSumFilterProcessFactory::QSumFilterProcessFactory () inline
ctor
Definition at line 60 of file QSumFilter.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("QSumFilter",this); }
~QSumFilterProcessFactory()
larcv::QSumFilterProcessFactory::~QSumFilterProcessFactory () inline
dtor
Definition at line 62 of file QSumFilter.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::QSumFilterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 64 of file QSumFilter.h.
References larcv::QSumFilter::QSumFilter().
 { return new QSumFilter(instance_name); }
The documentation for this class was generated from the following file:
QSumFilter.h