LArCV: larcv::ADCScaleAna Class Reference
larcv::ADCScaleAna Class Reference
#include <ADCScaleAna.h>
Public Member Functions
ADCScaleAna (const std::string name="ADCScaleAna")
Default constructor.
~ADCScaleAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< TH1D * > _hADC_v
std::string _image_producer
Detailed Description
Definition at line 27 of file ADCScaleAna.h.
Constructor & Destructor Documentation
ADCScaleAna()
larcv::ADCScaleAna::ADCScaleAna (const std::string name = "ADCScaleAna")
Default constructor.
Definition at line 11 of file ADCScaleAna.cxx.
Referenced by larcv::ADCScaleAnaProcessFactory::create().
     : ProcessBase(name)
   {}
~ADCScaleAna()
larcv::ADCScaleAna::~ADCScaleAna () inline
Default destructor.
Definition at line 35 of file ADCScaleAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ADCScaleAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file ADCScaleAna.cxx.
References _image_producer, and larcv::PSet::get().
Referenced by ~ADCScaleAna().
   {
     _image_producer = cfg.get<std::string>("ImageProducer");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ADCScaleAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 54 of file ADCScaleAna.cxx.
References _hADC_v, and larcv::ProcessBase::has_ana_file().
Referenced by ~ADCScaleAna().
   {
     if(has_ana_file())
       for(auto& p : _hADC_v) if(p) p->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ADCScaleAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 20 of file ADCScaleAna.cxx.
References _hADC_v.
Referenced by ~ADCScaleAna().
   {
     for(auto& p : _hADC_v) delete p;
     _hADC_v.clear();
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ADCScaleAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 26 of file ADCScaleAna.cxx.
References _hADC_v, _image_producer, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, and larcv::IOManager< T >::producer_id().
Referenced by ~ADCScaleAna().
   {
     static ProducerID_t id = mgr.producer_id(kProductImage2D,_image_producer);
     auto event_image = (EventImage2D*)(mgr.get_data(id));
     for(auto const& img : event_image->Image2DArray()) {
       auto const plane = img.meta().plane();
       if(_hADC_v.size() <= plane) _hADC_v.resize(plane+1,nullptr);
       if(!_hADC_v[plane]) _hADC_v[plane] = new TH1D(Form("hADC_%s_Plane%02hu",_image_producer.c_str(),plane),
                             Form("ADC Values for Plane %hu",plane),
                             100,0,500);
       auto& ptr = _hADC_v[plane];
       auto const& adc_v = img.as_vector();
       for(size_t i=1; i<adc_v.size()-1; ++i) {
     float pre = adc_v[i-1];
     float now = adc_v[i];
     float post = adc_v[i+1];
     if(pre < now && now > post && now > 5)
       ptr->Fill(now);
       }
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_hADC_v
std::vector<TH1D*> larcv::ADCScaleAna::_hADC_v private
Definition at line 47 of file ADCScaleAna.h.
Referenced by finalize(), initialize(), and process().
_image_producer
std::string larcv::ADCScaleAna::_image_producer private
Definition at line 48 of file ADCScaleAna.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ADCScaleAna.h
ADCScaleAna.cxx