LArCV: larcv::ProcessFactory Class Reference
larcv::ProcessFactory Class Reference
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
#include <ProcessFactory.h>
Public Member Functions
ProcessFactory ()
Default ctor, shouldn't be used.
~ProcessFactory ()
Default dtor.
void add_factory (const std::string name, larcv::ProcessFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
ProcessBase * create (const std::string name, const std::string instance_name)
Factory creation method (should be called by clients, possibly you!)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static ProcessFactory & get ()
Static sharable instance getter.
Private Attributes
std::map< std::string, larcv::ProcessFactoryBase * > _factory_map
Static factory container.
Static Private Attributes
static ProcessFactory * _me = nullptr
Static self.
Detailed Description
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
The actual factory core (to which each algorithm must register creation factory instance) is
a static std::map. Use static method to get a static instance (larcv::ProcessFactory::get)
to access a factory.
Definition at line 46 of file ProcessFactory.h.
Constructor & Destructor Documentation
ProcessFactory()
larcv::ProcessFactory::ProcessFactory () inline
Default ctor, shouldn't be used.
Definition at line 50 of file ProcessFactory.h.
                      : larcv_base("ProcessFactory")
     {}
~ProcessFactory()
larcv::ProcessFactory::~ProcessFactory () inline
Default dtor.
Definition at line 53 of file ProcessFactory.h.
 {_factory_map.clear();}
Member Function Documentation
add_factory()
void larcv::ProcessFactory::add_factory (const std::string name, larcv::ProcessFactoryBase * factory) inline
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 58 of file ProcessFactory.h.
Referenced by larcv::ADCScaleAnaProcessFactory::ADCScaleAnaProcessFactory(), larcv::ADCScaleProcessFactory::ADCScaleProcessFactory(), larcv::ADCThresholdProcessFactory::ADCThresholdProcessFactory(), larcv::AlgoDataAnaProcessFactory::AlgoDataAnaProcessFactory(), larcv::BadRegionAnaProcessFactory::BadRegionAnaProcessFactory(), larcv::BinarizeProcessFactory::BinarizeProcessFactory(), larcv::BlankImageProcessFactory::BlankImageProcessFactory(), larcv::calcPeakADCProcessFactory::calcPeakADCProcessFactory(), larcv::CCIncFilterProcessFactory::CCIncFilterProcessFactory(), larcv::CCQETruthFilterProcessFactory::CCQETruthFilterProcessFactory(), larcv::ChannelMaxProcessFactory::ChannelMaxProcessFactory(), larcv::ChStatusConverterProcessFactory::ChStatusConverterProcessFactory(), larcv::CombineImagesProcessFactory::CombineImagesProcessFactory(), larcv::CompressorProcessFactory::CompressorProcessFactory(), larcv::CosmicFilterProcessFactory::CosmicFilterProcessFactory(), larcv::CosmicPixelAnaProcessFactory::CosmicPixelAnaProcessFactory(), larcv::CosmicROIFillerProcessFactory::CosmicROIFillerProcessFactory(), larcv::CosmicSegmentProcessFactory::CosmicSegmentProcessFactory(), larcv::CosmicTrackAnaProcessFactory::CosmicTrackAnaProcessFactory(), larcv::CosmicVertexAnaProcessFactory::CosmicVertexAnaProcessFactory(), larcv::CropROIProcessFactory::CropROIProcessFactory(), larcv::DataStreamProcessFactory::DataStreamProcessFactory(), larcv::DBSCANProcessFactory::DBSCANProcessFactory(), larcv::DeadWireAnaProcessFactory::DeadWireAnaProcessFactory(), larcv::DoNothingProcessFactory::DoNothingProcessFactory(), larcv::DumpHiResCropImagesProcessFactory::DumpHiResCropImagesProcessFactory(), larcv::EmbedImageProcessFactory::EmbedImageProcessFactory(), larcv::EmptyImageFilterProcessFactory::EmptyImageFilterProcessFactory(), larcv::ExampleAnaProcessFactory::ExampleAnaProcessFactory(), larcv::GenDeadChannelMapProcessFactory::GenDeadChannelMapProcessFactory(), larcv::GoodcROIFilterProcessFactory::GoodcROIFilterProcessFactory(), larcv::hires::HiResImageDividerProcessFactory::HiResImageDividerProcessFactory(), larcv::HistADCProcessFactory::HistADCProcessFactory(), larcv::ImageChargeAnaProcessFactory::ImageChargeAnaProcessFactory(), larcv::ImageFromPixel2DClusterProcessFactory::ImageFromPixel2DClusterProcessFactory(), larcv::ImageFromPixel2DProcessFactory::ImageFromPixel2DProcessFactory(), larcv::ImageMergerProcessFactory::ImageMergerProcessFactory(), larcv::ImageROICheckMCProcessFactory::ImageROICheckMCProcessFactory(), larcv::LArbysImageAnaProcessFactory::LArbysImageAnaProcessFactory(), larcv::LArbysImageCheaterProcessFactory::LArbysImageCheaterProcessFactory(), larcv::LArbysImageExtractProcessFactory::LArbysImageExtractProcessFactory(), larcv::LArbysImageFilterProcessFactory::LArbysImageFilterProcessFactory(), larcv::LArbysImageMCProcessFactory::LArbysImageMCProcessFactory(), larcv::LArbysImageOutProcessFactory::LArbysImageOutProcessFactory(), larcv::LArbysImagePIDProcessFactory::LArbysImagePIDProcessFactory(), larcv::LArbysImageProcessFactory::LArbysImageProcessFactory(), larcv::LArbysImageReAnaProcessFactory::LArbysImageReAnaProcessFactory(), larcv::LArbysTrashProcessFactory::LArbysTrashProcessFactory(), larcv::LEE1e1pAnaProcessFactory::LEE1e1pAnaProcessFactory(), larcv::MaskImageProcessFactory::MaskImageProcessFactory(), larcv::MCFilterProcessFactory::MCFilterProcessFactory(), larcv::MCSingleParticleFilterProcessFactory::MCSingleParticleFilterProcessFactory(), larcv::MeanSubtractionProcessFactory::MeanSubtractionProcessFactory(), larcv::ModularPadImageProcessFactory::ModularPadImageProcessFactory(), larcv::MultiClassFillerProcessFactory::MultiClassFillerProcessFactory(), larcv::MultiROICropperProcessFactory::MultiROICropperProcessFactory(), larcv::NNCosineProcessFactory::NNCosineProcessFactory(), larcv::NuFilterProcessFactory::NuFilterProcessFactory(), larcv::OperateImageProcessFactory::OperateImageProcessFactory(), larcv::ParticleAnaProcessFactory::ParticleAnaProcessFactory(), larcv::PassProcessFactory::PassProcessFactory(), larcv::PGraphTruthMatchProcessFactory::PGraphTruthMatchProcessFactory(), larcv::PIDImageMakerProcessFactory::PIDImageMakerProcessFactory(), larcv::PlaneImageMergerProcessFactory::PlaneImageMergerProcessFactory(), larcv::pmtweights::PMTWeightImageBuilderProcessFactory::PMTWeightImageBuilderProcessFactory(), larcv::PreProcessorAnaProcessFactory::PreProcessorAnaProcessFactory(), larcv::PyImageMakerProcessFactory::PyImageMakerProcessFactory(), larcv::PyImageStitcherProcessFactory::PyImageStitcherProcessFactory(), larcv::QSumFilterProcessFactory::QSumFilterProcessFactory(), larcv::ReadJarrettFileProcessFactory::ReadJarrettFileProcessFactory(), larcv::ReadNueFileProcessFactory::ReadNueFileProcessFactory(), larcv::ReadRuiFileProcessFactory::ReadRuiFileProcessFactory(), larcv::ResizeImageProcessFactory::ResizeImageProcessFactory(), larcv::ROIAnaProcessFactory::ROIAnaProcessFactory(), larcv::ROIClipperProcessFactory::ROIClipperProcessFactory(), larcv::ROICountFilterProcessFactory::ROICountFilterProcessFactory(), larcv::ROIMaskProcessFactory::ROIMaskProcessFactory(), larcv::ROIMergerProcessFactory::ROIMergerProcessFactory(), larcv::ROIPadProcessFactory::ROIPadProcessFactory(), larcv::ROISizeFilterProcessFactory::ROISizeFilterProcessFactory(), larcv::RSEFilterProcessFactory::RSEFilterProcessFactory(), larcv::Run3DTrackerProcessFactory::Run3DTrackerProcessFactory(), larcv::RunFilterProcessFactory::RunFilterProcessFactory(), larcv::SegFillerProcessFactory::SegFillerProcessFactory(), larcv::SegImageAnaProcessFactory::SegImageAnaProcessFactory(), larcv::SegmentAnaProcessFactory::SegmentAnaProcessFactory(), larcv::SegmentFilterProcessFactory::SegmentFilterProcessFactory(), larcv::SegmentMakerProcessFactory::SegmentMakerProcessFactory(), larcv::SegmentMaskProcessFactory::SegmentMaskProcessFactory(), larcv::SegmentRelabelProcessFactory::SegmentRelabelProcessFactory(), larcv::SegWeightInstanceProcessFactory::SegWeightInstanceProcessFactory(), larcv::SegWeightTrackShowerProcessFactory::SegWeightTrackShowerProcessFactory(), larcv::SimpleDigitizerProcessFactory::SimpleDigitizerProcessFactory(), larcv::SimpleFillerProcessFactory::SimpleFillerProcessFactory(), larcv::SimplePixelAnaProcessFactory::SimplePixelAnaProcessFactory(), larcv::SingleROIFakerProcessFactory::SingleROIFakerProcessFactory(), larcv::SliceImagesProcessFactory::SliceImagesProcessFactory(), larcv::SSNetEventAnaProcessFactory::SSNetEventAnaProcessFactory(), larcv::SSNetTruthAnaProcessFactory::SSNetTruthAnaProcessFactory(), larcv::StepDigitizerProcessFactory::StepDigitizerProcessFactory(), larcv::SuperaBaseProcessFactory::SuperaBaseProcessFactory(), larcv::SuperaChStatusProcessFactory::SuperaChStatusProcessFactory(), larcv::SuperaHitProcessFactory::SuperaHitProcessFactory(), larcv::SuperaKeyPointClusterProcessFactory::SuperaKeyPointClusterProcessFactory(), larcv::SuperaMCPClusterProcessFactory::SuperaMCPClusterProcessFactory(), larcv::SuperaMCROIProcessFactory::SuperaMCROIProcessFactory(), larcv::SuperaMetaMakerProcessFactory::SuperaMetaMakerProcessFactory(), larcv::SuperaOpDigitProcessFactory::SuperaOpDigitProcessFactory(), larcv::SuperaSimChProcessFactory::SuperaSimChProcessFactory(), larcv::SuperaSimVoxel3DProcessFactory::SuperaSimVoxel3DProcessFactory(), larcv::SuperaWireProcessFactory::SuperaWireProcessFactory(), larcv::TrackerEventDisplayProcessFactory::TrackerEventDisplayProcessFactory(), larcv::UnionROIProcessFactory::UnionROIProcessFactory(), larcv::VertexAnaProcessFactory::VertexAnaProcessFactory(), larcv::VertexFilterProcessFactory::VertexFilterProcessFactory(), larcv::VertexImgProcessFactory::VertexImgProcessFactory(), larcv::VertexInROIProcessFactory::VertexInROIProcessFactory(), larcv::VtxInRegionProcessFactory::VtxInRegionProcessFactory(), and larcv::WireMaskProcessFactory::WireMaskProcessFactory().
     { _factory_map[name] = factory; }
create()
ProcessBase* larcv::ProcessFactory::create (const std::string name, const std::string instance_name) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 61 of file ProcessFactory.h.
References LARCV_ERROR.
Referenced by larcv::ProcessDriver::configure(), and larcv::ThreadDatumFiller::configure().
{
       auto iter = _factory_map.find(name);
       if(iter == _factory_map.end() || !((*iter).second)) {
     LARCV_ERROR() << "Found no registered class " << name << std::endl;
     return nullptr;
       }
       auto ptr = (*iter).second->create(instance_name);
       ptr->_typename = name;
       return ptr;
     }
get()
static ProcessFactory& larcv::ProcessFactory::get () inline static
Static sharable instance getter.
Definition at line 55 of file ProcessFactory.h.
Referenced by larcv::ADCScaleAnaProcessFactory::ADCScaleAnaProcessFactory(), larcv::ADCScaleProcessFactory::ADCScaleProcessFactory(), larcv::ADCThresholdProcessFactory::ADCThresholdProcessFactory(), larcv::AlgoDataAnaProcessFactory::AlgoDataAnaProcessFactory(), larcv::BadRegionAnaProcessFactory::BadRegionAnaProcessFactory(), larcv::BinarizeProcessFactory::BinarizeProcessFactory(), larcv::BlankImageProcessFactory::BlankImageProcessFactory(), larcv::calcPeakADCProcessFactory::calcPeakADCProcessFactory(), larcv::CCIncFilterProcessFactory::CCIncFilterProcessFactory(), larcv::CCQETruthFilterProcessFactory::CCQETruthFilterProcessFactory(), larcv::ChannelMaxProcessFactory::ChannelMaxProcessFactory(), larcv::ChStatusConverterProcessFactory::ChStatusConverterProcessFactory(), larcv::CombineImagesProcessFactory::CombineImagesProcessFactory(), larcv::CompressorProcessFactory::CompressorProcessFactory(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::CosmicFilterProcessFactory::CosmicFilterProcessFactory(), larcv::CosmicPixelAnaProcessFactory::CosmicPixelAnaProcessFactory(), larcv::CosmicROIFillerProcessFactory::CosmicROIFillerProcessFactory(), larcv::CosmicSegmentProcessFactory::CosmicSegmentProcessFactory(), larcv::CosmicTrackAnaProcessFactory::CosmicTrackAnaProcessFactory(), larcv::CosmicVertexAnaProcessFactory::CosmicVertexAnaProcessFactory(), larcv::CropROIProcessFactory::CropROIProcessFactory(), larcv::DataStreamProcessFactory::DataStreamProcessFactory(), larcv::DBSCANProcessFactory::DBSCANProcessFactory(), larcv::DeadWireAnaProcessFactory::DeadWireAnaProcessFactory(), larcv::DoNothingProcessFactory::DoNothingProcessFactory(), larcv::DumpHiResCropImagesProcessFactory::DumpHiResCropImagesProcessFactory(), larcv::EmbedImageProcessFactory::EmbedImageProcessFactory(), larcv::EmptyImageFilterProcessFactory::EmptyImageFilterProcessFactory(), larcv::ExampleAnaProcessFactory::ExampleAnaProcessFactory(), larcv::GenDeadChannelMapProcessFactory::GenDeadChannelMapProcessFactory(), larcv::GoodcROIFilterProcessFactory::GoodcROIFilterProcessFactory(), larcv::hires::HiResImageDividerProcessFactory::HiResImageDividerProcessFactory(), larcv::HistADCProcessFactory::HistADCProcessFactory(), larcv::ImageChargeAnaProcessFactory::ImageChargeAnaProcessFactory(), larcv::ImageFromPixel2DClusterProcessFactory::ImageFromPixel2DClusterProcessFactory(), larcv::ImageFromPixel2DProcessFactory::ImageFromPixel2DProcessFactory(), larcv::ImageMergerProcessFactory::ImageMergerProcessFactory(), larcv::ImageROICheckMCProcessFactory::ImageROICheckMCProcessFactory(), larcv::LArbysImageAnaProcessFactory::LArbysImageAnaProcessFactory(), larcv::LArbysImageCheaterProcessFactory::LArbysImageCheaterProcessFactory(), larcv::LArbysImageExtractProcessFactory::LArbysImageExtractProcessFactory(), larcv::LArbysImageFilterProcessFactory::LArbysImageFilterProcessFactory(), larcv::LArbysImageMCProcessFactory::LArbysImageMCProcessFactory(), larcv::LArbysImageOutProcessFactory::LArbysImageOutProcessFactory(), larcv::LArbysImagePIDProcessFactory::LArbysImagePIDProcessFactory(), larcv::LArbysImageProcessFactory::LArbysImageProcessFactory(), larcv::LArbysImageReAnaProcessFactory::LArbysImageReAnaProcessFactory(), larcv::LArbysTrashProcessFactory::LArbysTrashProcessFactory(), larcv::LEE1e1pAnaProcessFactory::LEE1e1pAnaProcessFactory(), larcv::MaskImageProcessFactory::MaskImageProcessFactory(), larcv::MCFilterProcessFactory::MCFilterProcessFactory(), larcv::MCSingleParticleFilterProcessFactory::MCSingleParticleFilterProcessFactory(), larcv::MeanSubtractionProcessFactory::MeanSubtractionProcessFactory(), larcv::ModularPadImageProcessFactory::ModularPadImageProcessFactory(), larcv::MultiClassFillerProcessFactory::MultiClassFillerProcessFactory(), larcv::MultiROICropperProcessFactory::MultiROICropperProcessFactory(), larcv::NNCosineProcessFactory::NNCosineProcessFactory(), larcv::NuFilterProcessFactory::NuFilterProcessFactory(), larcv::OperateImageProcessFactory::OperateImageProcessFactory(), larcv::ParticleAnaProcessFactory::ParticleAnaProcessFactory(), larcv::PassProcessFactory::PassProcessFactory(), larcv::PGraphTruthMatchProcessFactory::PGraphTruthMatchProcessFactory(), larcv::PIDImageMakerProcessFactory::PIDImageMakerProcessFactory(), larcv::PlaneImageMergerProcessFactory::PlaneImageMergerProcessFactory(), larcv::pmtweights::PMTWeightImageBuilderProcessFactory::PMTWeightImageBuilderProcessFactory(), larcv::PreProcessorAnaProcessFactory::PreProcessorAnaProcessFactory(), larcv::PyImageMakerProcessFactory::PyImageMakerProcessFactory(), larcv::PyImageStitcherProcessFactory::PyImageStitcherProcessFactory(), larcv::QSumFilterProcessFactory::QSumFilterProcessFactory(), larcv::ReadJarrettFileProcessFactory::ReadJarrettFileProcessFactory(), larcv::ReadNueFileProcessFactory::ReadNueFileProcessFactory(), larcv::ReadRuiFileProcessFactory::ReadRuiFileProcessFactory(), larcv::ResizeImageProcessFactory::ResizeImageProcessFactory(), larcv::ROIAnaProcessFactory::ROIAnaProcessFactory(), larcv::ROIClipperProcessFactory::ROIClipperProcessFactory(), larcv::ROICountFilterProcessFactory::ROICountFilterProcessFactory(), larcv::ROIMaskProcessFactory::ROIMaskProcessFactory(), larcv::ROIMergerProcessFactory::ROIMergerProcessFactory(), larcv::ROIPadProcessFactory::ROIPadProcessFactory(), larcv::ROISizeFilterProcessFactory::ROISizeFilterProcessFactory(), larcv::RSEFilterProcessFactory::RSEFilterProcessFactory(), larcv::Run3DTrackerProcessFactory::Run3DTrackerProcessFactory(), larcv::RunFilterProcessFactory::RunFilterProcessFactory(), larcv::SegFillerProcessFactory::SegFillerProcessFactory(), larcv::SegImageAnaProcessFactory::SegImageAnaProcessFactory(), larcv::SegmentAnaProcessFactory::SegmentAnaProcessFactory(), larcv::SegmentFilterProcessFactory::SegmentFilterProcessFactory(), larcv::SegmentMakerProcessFactory::SegmentMakerProcessFactory(), larcv::SegmentMaskProcessFactory::SegmentMaskProcessFactory(), larcv::SegmentRelabelProcessFactory::SegmentRelabelProcessFactory(), larcv::SegWeightInstanceProcessFactory::SegWeightInstanceProcessFactory(), larcv::SegWeightTrackShowerProcessFactory::SegWeightTrackShowerProcessFactory(), larcv::SimpleDigitizerProcessFactory::SimpleDigitizerProcessFactory(), larcv::SimpleFillerProcessFactory::SimpleFillerProcessFactory(), larcv::SimplePixelAnaProcessFactory::SimplePixelAnaProcessFactory(), larcv::SingleROIFakerProcessFactory::SingleROIFakerProcessFactory(), larcv::SliceImagesProcessFactory::SliceImagesProcessFactory(), larcv::SSNetEventAnaProcessFactory::SSNetEventAnaProcessFactory(), larcv::SSNetTruthAnaProcessFactory::SSNetTruthAnaProcessFactory(), larcv::StepDigitizerProcessFactory::StepDigitizerProcessFactory(), larcv::SuperaBaseProcessFactory::SuperaBaseProcessFactory(), larcv::SuperaChStatusProcessFactory::SuperaChStatusProcessFactory(), larcv::SuperaHitProcessFactory::SuperaHitProcessFactory(), larcv::SuperaKeyPointClusterProcessFactory::SuperaKeyPointClusterProcessFactory(), larcv::SuperaMCPClusterProcessFactory::SuperaMCPClusterProcessFactory(), larcv::SuperaMCROIProcessFactory::SuperaMCROIProcessFactory(), larcv::SuperaMetaMakerProcessFactory::SuperaMetaMakerProcessFactory(), larcv::SuperaOpDigitProcessFactory::SuperaOpDigitProcessFactory(), larcv::SuperaSimChProcessFactory::SuperaSimChProcessFactory(), larcv::SuperaSimVoxel3DProcessFactory::SuperaSimVoxel3DProcessFactory(), larcv::SuperaWireProcessFactory::SuperaWireProcessFactory(), larcv::TrackerEventDisplayProcessFactory::TrackerEventDisplayProcessFactory(), larcv::UnionROIProcessFactory::UnionROIProcessFactory(), larcv::VertexAnaProcessFactory::VertexAnaProcessFactory(), larcv::VertexFilterProcessFactory::VertexFilterProcessFactory(), larcv::VertexImgProcessFactory::VertexImgProcessFactory(), larcv::VertexInROIProcessFactory::VertexInROIProcessFactory(), larcv::VtxInRegionProcessFactory::VtxInRegionProcessFactory(), and larcv::WireMaskProcessFactory::WireMaskProcessFactory().
     { if(!_me) _me = new ProcessFactory; return *_me; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_factory_map
std::map<std::string,larcv::ProcessFactoryBase*> larcv::ProcessFactory::_factory_map private
Static factory container.
Definition at line 74 of file ProcessFactory.h.
_me
larcv::ProcessFactory * larcv::ProcessFactory::_me = nullptr static private
Static self.
Definition at line 76 of file ProcessFactory.h.
The documentation for this class was generated from the following files:
ProcessFactory.h
ProcessFactory.cxx