LArCV: larcv::SuperaBaseProcessFactory Class Reference
larcv::SuperaBaseProcessFactory Class Reference
#include <SuperaBase.h>
Public Member Functions
SuperaBaseProcessFactory ()
ctor
~SuperaBaseProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 118 of file SuperaBase.h.
Constructor & Destructor Documentation
SuperaBaseProcessFactory()
larcv::SuperaBaseProcessFactory::SuperaBaseProcessFactory () inline
ctor
Definition at line 121 of file SuperaBase.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SuperaBase",this); }
~SuperaBaseProcessFactory()
larcv::SuperaBaseProcessFactory::~SuperaBaseProcessFactory () inline
dtor
Definition at line 123 of file SuperaBase.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SuperaBaseProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 125 of file SuperaBase.h.
References larcv::SuperaBase::SuperaBase().
 { return new SuperaBase(instance_name); }
The documentation for this class was generated from the following file:
SuperaBase.h