LArCV: larcv::ViewROOT Class Reference
larcv::ViewROOT Class Reference
#include <ViewROOT.h>
Classes
struct VisInfo_t
Public Member Functions
void setEntry (int entry)
void clearVisItems ()
void draw (std::string datatype, std::string producer, int instance=-1, std::string opt="")
Static Public Member Functions
static ViewROOT & getViewROOT (std::string fname="")
Protected Member Functions
ViewROOT (std::string fmame)
~ViewROOT ()
void initialize (std::string fname)
void updateEntry ()
Protected Attributes
bool _init
IOManager * _io
int _canv_nplanes
std::map< std::string, VisInfo_t > _items
TCanvas * _canv
TH2D * _default_image2d
std::string _current_image2d
int _current_image2d_id
Static Protected Attributes
static ViewROOT * _global_instance = nullptr
Detailed Description
Definition at line 29 of file ViewROOT.h.
Constructor & Destructor Documentation
ViewROOT()
larcv::ViewROOT::ViewROOT (std::string fmame) protected
Definition at line 17 of file ViewROOT.cxx.
References initialize().
Referenced by getViewROOT().
     : _init(false),
       _io(nullptr),
       _canv_nplanes(1),
       _canv(nullptr),
       _default_image2d(nullptr),
       _current_image2d("__default__"),
       _current_image2d_id(-1)
   {
     initialize(fname);
   };
~ViewROOT()
larcv::ViewROOT::~ViewROOT () protected
Definition at line 30 of file ViewROOT.cxx.
References _canv, _default_image2d, _init, _io, clearVisItems(), larcv::IOManager< T >::finalize(), and larcv::IOManager< T >::reset().
                       {
     if ( !_init ) return;
     clearVisItems();
     delete _default_image2d;
     delete _canv;
     _io->reset();
     _io->finalize();
   }
Member Function Documentation
clearVisItems()
void larcv::ViewROOT::clearVisItems ()
Definition at line 59 of file ViewROOT.cxx.
References _canv, and _items.
Referenced by ~ViewROOT().
{
     _canv->Clear();
     for ( auto& p : _items )
       delete p.second.item;
     _items.clear();
   }
draw()
void larcv::ViewROOT::draw (std::string datatype, std::string producer, int instance = -1, std::string opt = "")
Definition at line 78 of file ViewROOT.cxx.
References _current_image2d, _current_image2d_id, _io, _items, larcv::ViewROOT::VisInfo_t::_keyname, larcv::as_th2d(), larcv::ViewROOT::VisInfo_t::datatype, larcv::IOManager< T >::get_data(), larcv::ViewROOT::VisInfo_t::instanceid, larcv::ViewROOT::VisInfo_t::item, larcv::kProductImage2D, and larcv::ViewROOT::VisInfo_t::producer.
{
     std::stringstream ss;
     ss << datatype << "_" << producer << "_" << instance;
     std::string keyname = ss.str();
     // LARCV ITEMS
     if ( datatype=="image2d" ) {
       // image2d special -- it sets the items
       _current_image2d    = producer;
       if ( instance<0 )
     _current_image2d_id = 0;
       else
     _current_image2d_id = instance;
       auto ev_img = (larcv::EventImage2D*)_io->get_data( larcv::kProductImage2D, producer );
       TH2D* hist = new TH2D( larcv::as_th2d( ev_img->Image2DArray()[instance], keyname ) );
       VisInfo_t info;
       info.producer   = producer;
       info.datatype   = datatype;
       info.instanceid = instance;
       info.item       = hist;
       info._keyname   = keyname;
       _items[ keyname ] = info;
     }
   }
getViewROOT()
ViewROOT & larcv::ViewROOT::getViewROOT (std::string fname = "") static
Definition at line 71 of file ViewROOT.cxx.
References _global_instance, and ViewROOT().
{
     if ( _global_instance==nullptr )
       _global_instance = new ViewROOT( fname );
     return *_global_instance;
   }
initialize()
void larcv::ViewROOT::initialize (std::string fname) protected
Definition at line 39 of file ViewROOT.cxx.
References _canv, _default_image2d, _init, _io, larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::initialize(), and larcv::IOManager< T >::kREAD.
Referenced by ViewROOT().
{
     if ( _init ) return;
     if ( gDirectory->GetFile()==nullptr && fname=="" ) {
       std::cout << "[ViewROOT::initialize] no filename provided nor ROOT file loaded" << std::endl;
       return;
     }
     _default_image2d = new TH2D( "__larcv_view_root_default", "", 100, 0, 3456, 100, 2400, 8448 );
     _canv = new TCanvas( "larcvCanvas", "LArCV Canvas", 1200, 600 );
     _io = new IOManager( larcv::IOManager::kREAD );
     if ( fname!="" ) {
       _io->add_in_file( fname );
     }
     else if ( gDirectory->GetFile() ) {
       _io->add_in_file( gDirectory->GetFile()->GetName() );
     }
     _io->initialize();
   }
setEntry()
void larcv::ViewROOT::setEntry (int entry)
Definition at line 66 of file ViewROOT.cxx.
References _io, and larcv::IOManager< T >::read_entry().
{
     _io->read_entry( entry );
     // drawCanvas()
   }
updateEntry()
void larcv::ViewROOT::updateEntry () inline protected
Definition at line 53 of file ViewROOT.h.
References _canv_nplanes.
 {};
Member Data Documentation
_canv
TCanvas* larcv::ViewROOT::_canv protected
Definition at line 66 of file ViewROOT.h.
Referenced by clearVisItems(), initialize(), and ~ViewROOT().
_canv_nplanes
int larcv::ViewROOT::_canv_nplanes protected
Definition at line 53 of file ViewROOT.h.
Referenced by updateEntry().
_current_image2d
std::string larcv::ViewROOT::_current_image2d protected
Definition at line 68 of file ViewROOT.h.
Referenced by draw().
_current_image2d_id
int larcv::ViewROOT::_current_image2d_id protected
Definition at line 69 of file ViewROOT.h.
Referenced by draw().
_default_image2d
TH2D* larcv::ViewROOT::_default_image2d protected
Definition at line 67 of file ViewROOT.h.
Referenced by initialize(), and ~ViewROOT().
_global_instance
ViewROOT * larcv::ViewROOT::_global_instance = nullptr static protected
Definition at line 71 of file ViewROOT.h.
Referenced by getViewROOT().
_init
bool larcv::ViewROOT::_init protected
Definition at line 48 of file ViewROOT.h.
Referenced by initialize(), and ~ViewROOT().
_io
IOManager* larcv::ViewROOT::_io protected
Definition at line 52 of file ViewROOT.h.
Referenced by draw(), initialize(), setEntry(), and ~ViewROOT().
_items
std::map< std::string, VisInfo_t > larcv::ViewROOT::_items protected
Definition at line 64 of file ViewROOT.h.
Referenced by clearVisItems(), and draw().
The documentation for this class was generated from the following files:
ViewROOT.h
ViewROOT.cxx