LArCV: larcv::ReadRuiFile Class Reference
larcv::ReadRuiFile Class Reference
#include <ReadRuiFile.h>
Public Member Functions
ReadRuiFile (const std::string name="ReadRuiFile")
Default constructor.
~ReadRuiFile ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
bool IsGoodVertex (int run, int subrun, int event, int ROIid, int vtxID)
void ReadVertexFile (std::string filename)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
int iTrack
larcv::AStarTracker tracker
std::vector< std::vector< int > > _vertexInfo
Detailed Description
Definition at line 28 of file ReadRuiFile.h.
Constructor & Destructor Documentation
ReadRuiFile()
larcv::ReadRuiFile::ReadRuiFile (const std::string name = "ReadRuiFile")
Default constructor.
Definition at line 47 of file ReadRuiFile.cxx.
Referenced by larcv::ReadRuiFileProcessFactory::create().
     : ProcessBase(name)
     {}
~ReadRuiFile()
larcv::ReadRuiFile::~ReadRuiFile () inline
Default destructor.
Definition at line 36 of file ReadRuiFile.h.
References configure(), finalize(), initialize(), IsGoodVertex(), process(), and ReadVertexFile().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ReadRuiFile::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 51 of file ReadRuiFile.cxx.
Referenced by ~ReadRuiFile().
     {}
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ReadRuiFile::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 242 of file ReadRuiFile.cxx.
References larcv::AStarTracker::finalize(), and tracker.
Referenced by ~ReadRuiFile().
     {
         tracker.finalize();
     }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ReadRuiFile::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 54 of file ReadRuiFile.cxx.
References larcv::AStarTracker::initialize(), iTrack, ReadVertexFile(), larcv::AStarTracker::SetCompressionFactors(), larcv::AStarTracker::SetVerbose(), and tracker.
Referenced by ~ReadRuiFile().
     {
         std::cout << "[ReadRuiFile]" << std::endl;
         tracker.initialize();
         tracker.SetCompressionFactors(1,6);
         tracker.SetVerbose(0);
         iTrack = 0;
         ReadVertexFile("data/numuSelected.txt");
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
IsGoodVertex()
bool larcv::ReadRuiFile::IsGoodVertex (int run, int subrun, int event, int ROIid, int vtxID)
Definition at line 201 of file ReadRuiFile.cxx.
References _vertexInfo.
Referenced by ~ReadRuiFile().
     {
         bool okVertex = false;
         for(size_t ivertex = 0;ivertex<_vertexInfo.size();ivertex++){
             if(   run    == _vertexInfo[ivertex][0]
                && subrun == _vertexInfo[ivertex][1]
                && event  == _vertexInfo[ivertex][2]
                && ROIid  == _vertexInfo[ivertex][4]
                && vtxID  == _vertexInfo[ivertex][5])okVertex = true;
         }
         return okVertex;
     }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ReadRuiFile::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 65 of file ReadRuiFile.cxx.
References larcv::AStarTracker::CheckEndPointsInVolume(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::get_n_entries(), iTrack, larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductROI, larcv::AStarTracker::ReconstructEvent(), larcv::AStarTracker::SetEventVertices(), larcv::AStarTracker::SetOriginalImage(), larcv::AStarTracker::SetTrackInfo(), and tracker.
Referenced by ~ReadRuiFile().
     {
         std::cout << std::endl;
         std::cout << "============================================" << std::endl;
         std::cout << "Entry " << mgr.current_entry() << " / " << mgr.get_n_entries() << std::endl;
         std::cout << "============================================" << std::endl;
         gStyle->SetOptStat(0);
         TVector3 vertex, endPoint[2];
         //
         // Loop per vertex (larcv type is PGraph "Particle Graph")
         //
         auto ev_img_v      = (EventImage2D*)mgr.get_data(kProductImage2D,"wire");
         auto ev_pgraph_v   = (EventPGraph*) mgr.get_data(kProductPGraph,"test");
         //auto ev_pcluster_v = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_img");
         //auto ev_ctor_v     = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_ctor");
         auto ev_partroi_v  = (EventROI*)mgr.get_data(kProductROI,"segment");
         int run    = ev_pgraph_v->run();
         int subrun = ev_pgraph_v->subrun();
         int event  = ev_pgraph_v->event();
         // get the event clusters and full images
         //auto const& ctor_m = ev_ctor_v->Pixel2DClusterArray();
         auto full_adc_img_v = &(ev_img_v->Image2DArray());
         auto mc_roi_v = ev_partroi_v->ROIArray();
         // get MC vertex
         std::vector<TVector3> MuonVertices;
         std::vector<TVector3> ProtonVertices;
         std::vector<TVector3> ElectronVertices;
         std::vector<TVector3> MuonEndPoint;
         std::vector<TVector3> ProtonEndPoint;
         std::vector<TVector3> ElectronEndPoint;
         for(size_t iMC = 0;iMC<mc_roi_v.size();iMC++){
             if(mc_roi_v[iMC].PdgCode() == 13){
                 std::cout << "muon.....@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 MuonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 MuonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
             if(mc_roi_v[iMC].PdgCode() == 2212){
                 std::cout << "proton...@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 ProtonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 ProtonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
             if(mc_roi_v[iMC].PdgCode() == 11){
                 std::cout << "electron.@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 ElectronVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 ElectronEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
         }
         std::vector<TVector3> MCVertices;
         std::vector<TVector3> MCEndPoint;
         bool isVertex = false;
         bool isNumu = false;
         bool isNue = false;
         std::vector<int> goodMuon, goodElectron;
         for(size_t iProton = 0;iProton<ProtonVertices.size();iProton++){
             isVertex = false;
             isNumu = false;
             isNue = false;
             for(size_t iMuon = 0;iMuon<MuonVertices.size();iMuon++){
                 if(MuonVertices[iMuon] == ProtonVertices[iProton]){isVertex = true;isNumu = true;goodMuon.push_back(iMuon);}
             }
             for(size_t iElectron = 0;iElectron<ElectronVertices.size();iElectron++){
                 if(ProtonVertices[iProton] == ElectronVertices[iProton]){isVertex = true;isNue = true;goodElectron.push_back(iElectron);}
             }
             if(isVertex && MCVertices.size()!=0 && ProtonVertices[iProton] == MCVertices[MCVertices.size()-1])continue;
             if(isVertex){
                 MCVertices.push_back(ProtonVertices[iProton]);
                 MCEndPoint.push_back(ProtonEndPoint[iProton]);
                 if(isNumu){
                     for(size_t imu = 0;imu<goodMuon.size();imu++){
                         MCEndPoint.push_back(MuonEndPoint[goodMuon[imu]]);
                     }
                 }
                 if(isNue){
                     for(size_t ie = 0;ie<goodElectron.size();ie++){
                         MCEndPoint.push_back(ElectronEndPoint[goodElectron[ie]]);
                     }
                 }
             }
         }
         // loop over found vertices
         //auto const& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
         std::vector<TVector3> vertex_v;
         std::vector<larcv::ImageMeta> Full_meta_v(3);
         std::vector<larcv::Image2D> Full_image_v(3);
         double wireRange = 5000;
         double tickRange = 8502;
         // Create base image2D with the full view, fill it with the input image 2D, we will crop it later
         for(size_t iPlane=0;iPlane<3;iPlane++){
             Full_meta_v[iPlane] = larcv::ImageMeta(wireRange,tickRange,(int)(tickRange)/6,(int)(wireRange),0,tickRange);
             Full_image_v[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             if(full_adc_img_v->size() == 3)Full_image_v[iPlane].overlay( (*full_adc_img_v)[iPlane] );
         }
         tracker.SetOriginalImage(Full_image_v);
         tracker.SetTrackInfo(run, subrun, event, 0);
         for(size_t pgraph_id = 0; pgraph_id < ev_pgraph_v->PGraphArray().size(); ++pgraph_id) {
             iTrack++;
             //int i = iTrack;
             auto const& pgraph        = ev_pgraph_v->PGraphArray().at(pgraph_id);
             //auto const& roi_v         = pgraph.ParticleArray();
             //auto const& cluster_idx_v = pgraph.ClusterIndexArray();
             //size_t nparticles = cluster_idx_v.size();
             //
             // Get Estimated 3D Start and End Points
             std::vector<TVector3> EndPoints;
             TVector3 vertex(pgraph.ParticleArray().front().X(),pgraph.ParticleArray().front().Y(),pgraph.ParticleArray().front().Z());
             EndPoints.push_back(vertex);
             bool WrongEndPoint = false;
             for(size_t iPoint = 0;iPoint<EndPoints.size();iPoint++){
                 if(!tracker.CheckEndPointsInVolume(EndPoints[iPoint]) ){std::cout << "=============> ERROR! End point " << iPoint << " outside of volume" << std::endl; WrongEndPoint = false;}
             }
             if(WrongEndPoint)continue;
             vertex_v.push_back(vertex);
         }
         tracker.SetEventVertices(vertex_v);
         tracker.ReconstructEvent();
         std::cout << std::endl << std::endl;
         return true;
     }
ReadVertexFile()
void larcv::ReadRuiFile::ReadVertexFile (std::string filename)
Definition at line 214 of file ReadRuiFile.cxx.
References _vertexInfo.
Referenced by initialize(), and ~ReadRuiFile().
     {
         if(_vertexInfo.size()!=0)_vertexInfo.clear();
         std::vector<int> thisVertexInfo;
         std::ifstream file(Form("%s",filename.c_str()));
         if(!file){std::cout << "ERROR, could not open file of selected vertices to sort through" << std::endl;return;}
         std::string firstline;
         getline(file, firstline);
         bool goOn = true;
         int Run,SubRun,Event,Entry,ROI_ID,vtxid;
         double x,y,z;
         char coma;
         while(goOn){
             file >> Run >> coma >> SubRun >> coma >> Event >> coma >> Entry >> coma >> ROI_ID >> coma >> vtxid >> coma >> x >> coma >> y >> coma >> z;
             if(thisVertexInfo.size()!=0)thisVertexInfo.clear();
             thisVertexInfo.push_back(Run);      //0
             thisVertexInfo.push_back(SubRun);   //1
             thisVertexInfo.push_back(Event);    //2
             thisVertexInfo.push_back(Entry);    //3
             thisVertexInfo.push_back(ROI_ID);   //4
             thisVertexInfo.push_back(vtxid);    //5
             _vertexInfo.push_back(thisVertexInfo);
             if(file.eof()){goOn=false;break;}
         }
         std::cout << _vertexInfo.size() << " vertices to loop through" << std::endl;
     }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_vertexInfo
std::vector< std::vector<int> > larcv::ReadRuiFile::_vertexInfo private
Definition at line 52 of file ReadRuiFile.h.
Referenced by IsGoodVertex(), and ReadVertexFile().
iTrack
int larcv::ReadRuiFile::iTrack private
Definition at line 50 of file ReadRuiFile.h.
Referenced by initialize(), and process().
tracker
larcv::AStarTracker larcv::ReadRuiFile::tracker private
Definition at line 51 of file ReadRuiFile.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
ReadRuiFile.h
ReadRuiFile.cxx