LArCV: larcv::SegFiller Class Reference
larcv::SegFiller Class Reference
#include <SegFiller.h>
Public Types
enum FillerDataType_t { kFillerImageData, kFillerLabelData, kFillerWeightData, kFillerMultiplicityData }
Public Member Functions
SegFiller (const std::string name="SegFiller")
Default constructor.
~SegFiller ()
Default destructor.
void child_configure (const PSet &)
void child_initialize ()
void child_batch_begin ()
void child_batch_end ()
void child_finalize ()
const std::vector< bool > & mirrored () const
const std::vector< int > dim (bool image=true) const
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
const std::string & producer (FillerDataType_t type) const
virtual bool is (const std::string question) const
size_t entries () const
const std::vector< std::vector< larcv::ImageMeta > > & meta () const
const std::vector< float > & data (FillerDataType_t dtype=kFillerImageData) const
size_t entry_image_size () const
size_t entry_label_size () const
size_t entry_weight_size () const
size_t entry_multiplicity_size () const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Member Functions
void fill_entry_data (const EventBase *image_data, const EventBase *label_data, const EventBase *weight_data, const EventBase *multiplicity_data)
size_t compute_image_size (const EventBase *image_data)
size_t compute_label_size (const EventBase *label_data)
size_t compute_multiplicity_size (const EventBase *multiplicity_data)
const std::vector< float > & entry_data (FillerDataType_t dtype=kFillerImageData) const
const std::vector< larcv::ImageMeta > & entry_meta () const
Protected Attributes
std::vector< float > _entry_image_data
std::vector< float > _entry_label_data
std::vector< float > _entry_weight_data
std::vector< float > _entry_multiplicity_data
ProductType_t _image_product_type
ProductType_t _label_product_type
ProductType_t _weight_product_type
ProductType_t _multiplicity_product_type
std::vector< larcv::ImageMeta > _entry_meta_data
Private Member Functions
void assert_dimension (const std::vector< larcv::Image2D > &)
Private Attributes
size_t _seg_channel
size_t _rows
size_t _cols
size_t _num_channels
std::vector< size_t > _slice_v
size_t _max_ch
std::vector< size_t > _caffe_idx_to_img_idx
std::vector< size_t > _mirror_caffe_idx_to_img_idx
std::vector< size_t > _roitype_to_class
std::vector< bool > _mirrored
bool _mirror_image
bool _crop_image
RandomCropper _cropper
Detailed Description
Definition at line 27 of file SegFiller.h.
Member Enumeration Documentation
FillerDataType_t
enum larcv::DatumFillerBase::FillerDataType_t inherited
Enumerator
kFillerImageData
kFillerLabelData
kFillerWeightData
kFillerMultiplicityData
Definition at line 31 of file DatumFillerBase.h.
{
       kFillerImageData,
       kFillerLabelData,
       kFillerWeightData,
       kFillerMultiplicityData
     };
Constructor & Destructor Documentation
SegFiller()
larcv::SegFiller::SegFiller (const std::string name = "SegFiller")
Default constructor.
Definition at line 13 of file SegFiller.cxx.
References larcv::DatumFillerBase::_image_product_type, larcv::DatumFillerBase::_label_product_type, _seg_channel, larcv::DatumFillerBase::_weight_product_type, larcv::kINVALID_SIZE, and larcv::kProductImage2D.
Referenced by larcv::SegFillerProcessFactory::create().
     : DatumFillerBase(name)
     , _slice_v()
     , _max_ch(0)
   {
     _image_product_type  = kProductImage2D;
     _label_product_type  = kProductImage2D;
     _weight_product_type = kProductImage2D;
     _seg_channel = kINVALID_SIZE;
   }
~SegFiller()
larcv::SegFiller::~SegFiller () inline
Default destructor.
Definition at line 35 of file SegFiller.h.
References child_batch_begin(), child_batch_end(), child_configure(), child_finalize(), and child_initialize().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
assert_dimension()
void larcv::SegFiller::assert_dimension (const std::vector< larcv::Image2D > & image_v) private
Definition at line 168 of file SegFiller.cxx.
References _cols, _crop_image, _max_ch, _rows, larcv::kINVALID_SIZE, LARCV_CRITICAL, and LARCV_WARNING.
Referenced by fill_entry_data(), and mirrored().
   {
     if(_rows == kINVALID_SIZE) {
       LARCV_WARNING() << "set_dimension() must be called prior to check_dimension()" << std::endl;
       return;
     }
     bool valid_ch   = (image_v.size() > _max_ch);
     bool valid_rows = true;
     for(auto const& img : image_v) {
       if ( !_crop_image )
         valid_rows = ( _rows == img.meta().rows() );
       if(!valid_rows) break;
     }
     bool valid_cols = true;
     for(auto const& img : image_v) {
       if ( !_crop_image )
         valid_cols = ( _cols == img.meta().cols() );
       if(!valid_cols) break;
     }
     if(!valid_rows) {
       LARCV_CRITICAL() << "# of rows in the input image have changed!" << std::endl;
       throw larbys();
     }
     if(!valid_cols) {
       LARCV_CRITICAL() << "# of cols in the input image have changed!" << std::endl;
       throw larbys();
     }
     if(!valid_ch) {
       LARCV_CRITICAL() << "# of channels have changed in the input image! Image vs. MaxCh ("
       << image_v.size() << " vs. " << _max_ch << ")" << std::endl;
       throw larbys();
     }
   }
child_batch_begin()
void larcv::SegFiller::child_batch_begin () virtual
Reimplemented from larcv::DatumFillerBase.
Definition at line 73 of file SegFiller.cxx.
References _mirrored, and larcv::DatumFillerBase::entries().
Referenced by ~SegFiller().
   {
     _mirrored.clear();
     _mirrored.reserve(entries());
   }
child_batch_end()
void larcv::SegFiller::child_batch_end () virtual
Reimplemented from larcv::DatumFillerBase.
Definition at line 79 of file SegFiller.cxx.
References _mirrored, larcv::DatumFillerBase::data(), larcv::DatumFillerBase::kFillerLabelData, larcv::msg::kINFO, LARCV_INFO, and larcv::larcv_base::logger().
Referenced by ~SegFiller().
   {
     if(logger().level() <= msg::kINFO) {
       std::vector<size_t> ctr_v;
       for(auto const& v : data(kFillerLabelData)) {
         if(v>=ctr_v.size()) ctr_v.resize(v+1,0);
         ctr_v[v] += 1;
       }
       std::stringstream ss;
       ss << "Used: ";
       for(size_t i=0;i<ctr_v.size();++i)
         ss << ctr_v[i] << " of class " << i << " ... ";
       LARCV_INFO() << ss.str() << std::endl;
       size_t mirror_ctr=0;
       for(auto const& v : _mirrored) if(v) ++mirror_ctr;
         LARCV_INFO() << mirror_ctr << " / " << _mirrored.size() << " images are mirrored!" << std::endl;
     }
   }
child_configure()
void larcv::SegFiller::child_configure (const PSet & cfg) virtual
Implements larcv::DatumFillerBase.
Definition at line 24 of file SegFiller.cxx.
References _crop_image, _cropper, _mirror_image, _roitype_to_class, _seg_channel, _slice_v, larcv::RandomCropper::configure(), larcv::PSet::get(), larcv::kINVALID_SIZE, larcv::kROITypeMax, larcv::kROIUnknown, and LARCV_CRITICAL.
Referenced by ~SegFiller().
   {
     _slice_v = cfg.get<std::vector<size_t> >("Channels",_slice_v);
     _seg_channel = cfg.get<size_t>("SegChannel");
     _mirror_image = cfg.get<bool>("EnableMirror",false);
     _crop_image     = cfg.get<bool>("EnableCrop",false);
     if(_crop_image)
       _cropper.configure(cfg);
     auto type_def = cfg.get<std::vector<unsigned short> >("ClassTypeDef");
     if(type_def.size() != kROITypeMax) {
       LARCV_CRITICAL() << "ClassTypeDef length is " << type_def.size()
                << " but it needs to be length kROITypeMax (" << kROITypeMax << ")!" << std::endl;
       throw larbys();
     }
     for(auto const& v : type_def) {
       if(v >= kROITypeMax) {
     LARCV_CRITICAL() << "ClassTypeDef contains invalid value (" << v << ") for ROIType_t!" << std::endl;
     throw larbys();
       }
     }
     auto type_to_class = cfg.get<std::vector<unsigned short> >("ClassTypeList");
     if(type_to_class.empty()) {
       LARCV_CRITICAL() << "ClassTypeList needed to define classes!" << std::endl;
       throw larbys();
     }
     _roitype_to_class.clear();
     _roitype_to_class.resize(kROITypeMax,kINVALID_SIZE);
     _roitype_to_class[larcv::kROIUnknown] = 0;
     for(size_t i=0; i<type_to_class.size(); ++i) {
       auto const& type = type_to_class[i];
       if(type >= kROITypeMax) {
         LARCV_CRITICAL() << "ClassTypeList contains type " << type << " which is not a valid ROIType_t!" << std::endl;
         throw larbys();
       }
       _roitype_to_class[type] = i+1;
     }
     for(size_t i=0; i<_roitype_to_class.size(); ++i) {
       if(_roitype_to_class[i] != kINVALID_SIZE) continue;
       _roitype_to_class[i] = _roitype_to_class[type_def[i]];
     }
   }
child_finalize()
void larcv::SegFiller::child_finalize () virtual
Reimplemented from larcv::DatumFillerBase.
Definition at line 100 of file SegFiller.cxx.
Referenced by ~SegFiller().
 {}
child_initialize()
void larcv::SegFiller::child_initialize () virtual
Reimplemented from larcv::DatumFillerBase.
Definition at line 67 of file SegFiller.cxx.
References larcv::DatumFillerBase::_entry_image_data, and larcv::DatumFillerBase::_entry_label_data.
Referenced by ~SegFiller().
   {
     _entry_image_data.clear();
     _entry_label_data.clear();
   }
compute_image_size()
size_t larcv::SegFiller::compute_image_size (const EventBase * image_data) protected virtual
Implements larcv::DatumFillerBase.
Definition at line 122 of file SegFiller.cxx.
References _caffe_idx_to_img_idx, _cols, _crop_image, _cropper, _max_ch, _mirror_caffe_idx_to_img_idx, _num_channels, _rows, _slice_v, larcv::RandomCropper::cols(), LARCV_CRITICAL, and larcv::RandomCropper::rows().
Referenced by compute_label_size(), and mirrored().
   {
     auto const& image_v = ((EventImage2D*)image_data)->Image2DArray();
     if(image_v.empty()) {
       LARCV_CRITICAL() << "Input image is empty!" << std::endl;
       throw larbys();
     }
     if(_slice_v.empty()) {
       _slice_v.resize(image_v.size());
       for(size_t i=0; i<_slice_v.size(); ++i) _slice_v[i] = i;
     }
     _num_channels = _slice_v.size();
     _max_ch = 0;
     for(auto const& v : _slice_v) if(_max_ch < v) _max_ch = v;
     if(image_v.size() <= _max_ch) {
       LARCV_CRITICAL() << "Requested slice max channel (" << _max_ch
         << ") exceeds available # of channels in the input image" << std::endl;
       throw larbys();
     }
     if ( !_crop_image ) {
       // set the dimensions from the image
       _rows = image_v.front().meta().rows();
       _cols = image_v.front().meta().cols();
     }
     else {
       // gonna crop (if speicifed dim is smaller than image dim)
       _rows = std::min( image_v.front().meta().rows(), _cropper.rows() );
       _cols = std::min( image_v.front().meta().cols(), _cropper.cols() );
     }
     // Define caffe idx to Image2D idx (assuming no crop)
     _caffe_idx_to_img_idx.resize(_rows*_cols,0);
     _mirror_caffe_idx_to_img_idx.resize(_rows*_cols,0);
     size_t caffe_idx = 0;
     for(size_t row=0; row<_rows; ++row) {
       for(size_t col=0; col<_cols; ++col) {
         _caffe_idx_to_img_idx[caffe_idx] = col*_rows + row;
         _mirror_caffe_idx_to_img_idx[caffe_idx] = (_cols-col-1)*_rows + row;
         ++caffe_idx;
       }
     }
     return (_rows * _cols * _num_channels);
   }
compute_label_size()
size_t larcv::SegFiller::compute_label_size (const EventBase * label_data) protected virtual
Implements larcv::DatumFillerBase.
Definition at line 116 of file SegFiller.cxx.
References compute_image_size(), larcv::DatumFillerBase::entry_image_size(), and larcv::kINVALID_SIZE.
Referenced by mirrored().
   {
     if(entry_image_size() != kINVALID_SIZE) return entry_image_size();
     return compute_image_size(label_data);
   }
compute_multiplicity_size()
size_t larcv::SegFiller::compute_multiplicity_size (const EventBase * multiplicity_data) protected virtual
Implements larcv::DatumFillerBase.
Definition at line 112 of file SegFiller.cxx.
Referenced by mirrored().
{
     return 1;
   }
configure()
void larcv::DatumFillerBase::configure (const PSet & cfg) virtual inherited
Implements larcv::ProcessBase.
Definition at line 73 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_image_producer, larcv::DatumFillerBase::_label_producer, larcv::DatumFillerBase::_multiplicity_producer, larcv::DatumFillerBase::_weight_producer, larcv::DatumFillerBase::child_configure(), and larcv::PSet::get().
Referenced by larcv::DatumFillerBase::~DatumFillerBase().
   {
     _image_producer        = cfg.get<std::string>("ImageProducer");
     _label_producer        = cfg.get<std::string>("LabelProducer");
     _weight_producer       = cfg.get<std::string>("WeightProducer","");
     _multiplicity_producer = cfg.get<std::string>("MultiplicityProducer","");
     this->child_configure(cfg);
   }
data()
const std::vector< float > & larcv::DatumFillerBase::data (DatumFillerBase::FillerDataType_t dtype = kFillerImageData) const inherited
Definition at line 43 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_image_data, larcv::DatumFillerBase::_label_data, larcv::DatumFillerBase::_multiplicity_data, larcv::DatumFillerBase::_weight_data, larcv::DatumFillerBase::kFillerImageData, larcv::DatumFillerBase::kFillerLabelData, larcv::DatumFillerBase::kFillerMultiplicityData, and larcv::DatumFillerBase::kFillerWeightData.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), child_batch_end(), larcv::ThreadDatumFiller::data(), larcv::ThreadDatumFiller::labels(), larcv::ThreadDatumFiller::multiplicities(), larcv::ThreadDatumFiller::weights(), and larcv::DatumFillerBase::~DatumFillerBase().
   { switch(dtype) {
     case kFillerImageData:
       return _image_data;
     case kFillerLabelData:
       return _label_data;
     case kFillerWeightData:
       return _weight_data;
     case kFillerMultiplicityData:
       return _multiplicity_data;
     }
     return _weight_data;
   }
dim()
const std::vector< int > larcv::SegFiller::dim (bool image = true) const virtual
Implements larcv::DatumFillerBase.
Definition at line 102 of file SegFiller.cxx.
References _cols, _num_channels, _rows, and larcv::DatumFillerBase::entries().
Referenced by mirrored().
   {
     std::vector<int> res(4,0);
     res[0] = entries();
     res[1] = image ? _num_channels : 1;
     res[2] = _rows;
     res[3] = _cols;
     return res;
   }
entries()
size_t larcv::DatumFillerBase::entries () const inherited
Definition at line 34 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_nentries.
Referenced by larcv::MultiClassFiller::child_batch_begin(), child_batch_begin(), larcv::SimpleFiller::child_batch_begin(), dim(), larcv::SimpleFiller::dim(), larcv::MultiClassFiller::dim(), and larcv::DatumFillerBase::~DatumFillerBase().
 { return _nentries; }
entry_data()
const std::vector< float > & larcv::DatumFillerBase::entry_data (DatumFillerBase::FillerDataType_t dtype = kFillerImageData) const protected inherited
Definition at line 58 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_entry_image_data, larcv::DatumFillerBase::_entry_label_data, larcv::DatumFillerBase::_entry_multiplicity_data, larcv::DatumFillerBase::_entry_weight_data, larcv::DatumFillerBase::kFillerImageData, larcv::DatumFillerBase::kFillerLabelData, larcv::DatumFillerBase::kFillerMultiplicityData, and larcv::DatumFillerBase::kFillerWeightData.
Referenced by larcv::DatumFillerBase::child_finalize(), and larcv::DatumFillerBase::process().
   {
     switch(dtype) {
     case kFillerImageData:
       return _entry_image_data;
     case kFillerLabelData:
       return _entry_label_data;
     case kFillerWeightData:
       return _entry_weight_data;
     case kFillerMultiplicityData:
       return _entry_multiplicity_data;
     }
     return _entry_weight_data;
   }
entry_image_size()
size_t larcv::DatumFillerBase::entry_image_size () const inline inherited
Definition at line 65 of file DatumFillerBase.h.
References larcv::DatumFillerBase::_entry_image_size.
Referenced by compute_label_size(), larcv::SimpleFiller::fill_entry_data(), fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
 { return _entry_image_size;  }
entry_label_size()
size_t larcv::DatumFillerBase::entry_label_size () const inline inherited
Definition at line 67 of file DatumFillerBase.h.
References larcv::DatumFillerBase::_entry_label_size.
Referenced by fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
 { return _entry_label_size;  }
entry_meta()
const std::vector<larcv::ImageMeta>& larcv::DatumFillerBase::entry_meta () const inline protected inherited
Definition at line 98 of file DatumFillerBase.h.
References larcv::DatumFillerBase::_entry_meta_data.
     { return _entry_meta_data;}
entry_multiplicity_size()
size_t larcv::DatumFillerBase::entry_multiplicity_size () const inline inherited
Definition at line 71 of file DatumFillerBase.h.
References larcv::DatumFillerBase::_entry_multiplicity_size, and larcv::DatumFillerBase::child_configure().
Referenced by larcv::MultiClassFiller::fill_entry_data().
 { return _entry_multiplicity_size; }
entry_weight_size()
size_t larcv::DatumFillerBase::entry_weight_size () const inline inherited
Definition at line 69 of file DatumFillerBase.h.
References larcv::DatumFillerBase::_entry_weight_size.
Referenced by fill_entry_data().
 { return _entry_weight_size; }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
fill_entry_data()
void larcv::SegFiller::fill_entry_data (const EventBase * image_data, const EventBase * label_data, const EventBase * weight_data, const EventBase * multiplicity_data) protected virtual
Implements larcv::DatumFillerBase.
Definition at line 202 of file SegFiller.cxx.
References _caffe_idx_to_img_idx, _cols, _crop_image, _cropper, larcv::DatumFillerBase::_entry_image_data, larcv::DatumFillerBase::_entry_label_data, larcv::DatumFillerBase::_entry_meta_data, larcv::DatumFillerBase::_entry_weight_data, _mirror_caffe_idx_to_img_idx, _mirror_image, _mirrored, _num_channels, _roitype_to_class, _rows, _seg_channel, _slice_v, assert_dimension(), larcv::RandomCropper::cols(), larcv::RandomCropper::crop(), larcv::DatumFillerBase::entry_image_size(), larcv::DatumFillerBase::entry_label_size(), larcv::DatumFillerBase::entry_weight_size(), larcv::kINVALID_SIZE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, larcv::RandomCropper::rows(), and larcv::RandomCropper::set_crop_region().
Referenced by mirrored().
   {
     LARCV_DEBUG() << "Start" << std::endl;
     auto const& image_v = ((EventImage2D*)image_data)->Image2DArray();
     this->assert_dimension(image_v);
     /* Let's not require weight to exist on all channel by default
     if(weight_data) {
       auto const& weight_v = ((EventImage2D*)weight_data)->Image2DArray();
       this->assert_dimension(weight_data);
     }
     */
     auto const& label_v = ((EventImage2D*)label_data)->Image2DArray();
     // Check label validity
     if(_seg_channel >= label_v.size()) {
       LARCV_CRITICAL() << "Segmentation image channel (" << _seg_channel << ") does not exist in data!" << std::endl;
       throw larbys();
     }
     if(_entry_image_data.empty()) _entry_image_data.resize(entry_image_size(),0.);
     for(auto& v : _entry_image_data) v = 0.;
     if(_entry_label_data.empty()) _entry_label_data.resize(entry_label_size(),0.);
     for(auto& v : _entry_label_data) v = 0.;
     if(_entry_weight_data.empty()) _entry_weight_data.resize(entry_weight_size(),0.);
     for(auto& v : _entry_weight_data) v = 0.;
     std::random_device rd;
     std::mt19937 gen(rd());
     std::uniform_int_distribution<> irand(0,1);
     bool mirror_image = false;
     if(_mirror_image && irand(gen)) {
       _mirrored.push_back(true);
       mirror_image = true;
       LARCV_INFO() << "Mirroring the image..." << std::endl;
     }
     else { _mirrored.push_back(false); }
     for(size_t ch=0;ch<_num_channels;++ch) {
         size_t input_ch = _slice_v[ch];
     LARCV_INFO() << "Filling for an image channel " << input_ch << std::endl;
         auto const& input_img2d = image_v[input_ch];
     auto const& input_meta  = input_img2d.meta();
     _entry_meta_data.push_back(input_meta);
         if(!ch && _crop_image) {
       LARCV_INFO() << "First image: setting cropping region ("
                << _cropper.rows() << "x" << _cropper.cols() << std::endl;
           _cropper.set_crop_region(input_meta.rows(), input_meta.cols());
     }
         auto const& input_image = (_crop_image ? _cropper.crop(input_img2d) : input_img2d.as_vector());
     LARCV_INFO() << "Input image size: " << input_image.size() << " pixels" << std::endl;
         size_t caffe_idx=0;
         size_t output_idx = ch * _rows * _cols;
     LARCV_INFO() << "Start filling image from output data index " << output_idx << " for " << _rows * _cols << " pixels" << std::endl;
     if(!weight_data) {
       for(size_t row=0; row<_rows; ++row) {
         for(size_t col=0; col<_cols; ++col) {
           if(mirror_image)
         _entry_image_data[output_idx] = input_image[_mirror_caffe_idx_to_img_idx[caffe_idx]];
           else
         _entry_image_data[output_idx] = input_image[_caffe_idx_to_img_idx[caffe_idx]];
           ++output_idx;
           ++caffe_idx;
         }
       }
     }else{
       auto const& weight_img2d = ((EventImage2D*)(weight_data))->Image2DArray()[input_ch];
       // Make sure dimension matches
       if(weight_img2d.meta().cols() != input_meta.cols() ||
          weight_img2d.meta().rows() != input_meta.rows() ) {
         LARCV_CRITICAL() << "Channel " << input_ch << ": weight dim (col,row) = ("
                  << weight_img2d.meta().rows() << "," << weight_img2d.meta().cols() << ")"
                  << " vs. Image dim ("
                  << input_meta.rows() << "," << input_meta.cols() << ")"
                  << std::endl;
         throw larbys();
       }
       auto const& weight_image = (_crop_image ? _cropper.crop(weight_img2d) : weight_img2d.as_vector());
       for(size_t row=0; row<_rows; ++row) {
         for(size_t col=0; col<_cols; ++col) {
           if(mirror_image) {
         _entry_image_data  [output_idx] = input_image  [_mirror_caffe_idx_to_img_idx[caffe_idx]];
         _entry_weight_data [output_idx] = weight_image [_mirror_caffe_idx_to_img_idx[caffe_idx]];
           }else{
         _entry_image_data  [output_idx] = input_image  [_caffe_idx_to_img_idx[caffe_idx]];
         _entry_weight_data [output_idx] = weight_image [_caffe_idx_to_img_idx[caffe_idx]];
           }
           ++output_idx;
           ++caffe_idx;
         }
       }
     }
     }
     // Label
     LARCV_INFO() << "Filling for a label channel "
          << _seg_channel << " (input length " << label_v.size() << ")" << std::endl;
     auto const& input_lbl2d = label_v[_seg_channel];
     auto const& input_label = (_crop_image ? _cropper.crop(input_lbl2d) : input_lbl2d.as_vector());
     LARCV_INFO() << "Input image size: " << input_label.size() << " pixels" << std::endl;
     size_t caffe_idx=0;
     size_t output_idx = 0;
     float label_value = kINVALID_SIZE;
     LARCV_INFO() << "Start filling label from output data index " << output_idx << " for " << _rows * _cols << " pixels" << std::endl;
     for(size_t row=0; row<_rows; ++row) {
       for(size_t col=0; col<_cols; ++col) {
         if(mirror_image)
           label_value = input_label[_mirror_caffe_idx_to_img_idx[caffe_idx]];
         else
           label_value = input_label[_caffe_idx_to_img_idx[caffe_idx]];
     size_t class_value = _roitype_to_class[(size_t)label_value];
     //if(label_value || (size_t)(class_value))
     //std::cout<<"Label value conversion: " << label_value << " => " << class_value << std::endl;
     if(class_value == kINVALID_SIZE) {
       LARCV_CRITICAL() << "Found invalid ROI type in the label image: " << label_value << std::endl;
       throw larbys();
     }
     _entry_label_data[output_idx] = float(class_value);
         ++output_idx;
         ++caffe_idx;
       }
     }
     LARCV_DEBUG() << "End" << std::endl;
   }
finalize()
void larcv::DatumFillerBase::finalize () virtual inherited
Implements larcv::ProcessBase.
Definition at line 261 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::child_finalize().
Referenced by larcv::ThreadDatumFiller::finalize(), and larcv::DatumFillerBase::~DatumFillerBase().
   { this->child_finalize(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DatumFillerBase::initialize () virtual inherited
Implements larcv::ProcessBase.
Definition at line 82 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_current_entry, larcv::DatumFillerBase::_entry_image_size, larcv::DatumFillerBase::_entry_label_size, larcv::DatumFillerBase::_entry_multiplicity_size, larcv::DatumFillerBase::_entry_weight_size, larcv::DatumFillerBase::_image_producer_id, larcv::DatumFillerBase::_label_producer_id, larcv::DatumFillerBase::_multiplicity_producer_id, larcv::DatumFillerBase::_nentries, larcv::DatumFillerBase::_weight_producer_id, larcv::DatumFillerBase::child_initialize(), larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, and LARCV_CRITICAL.
Referenced by larcv::ThreadDatumFiller::initialize(), and larcv::DatumFillerBase::~DatumFillerBase().
   {
     if(_nentries == kINVALID_SIZE) {
       LARCV_CRITICAL() << "# entries not set... must be set @ initialize! " << std::endl;
       throw larbys();
     }
     _current_entry = kINVALID_SIZE;
     _entry_image_size   = _entry_label_size = kINVALID_SIZE;
     _entry_weight_size  = 0;
     _entry_multiplicity_size  = 0;
     _image_producer_id        = kINVALID_PRODUCER;
     _label_producer_id        = kINVALID_PRODUCER;
     _weight_producer_id       = kINVALID_PRODUCER;
     _multiplicity_producer_id = kINVALID_PRODUCER;
     this->child_initialize();
   }
is()
bool larcv::DatumFillerBase::is (const std::string question) const virtual inherited
Reimplemented from larcv::ProcessBase.
Definition at line 36 of file DatumFillerBase.cxx.
Referenced by larcv::DatumFillerBase::~DatumFillerBase().
   { return (question == "DatumFiller"); }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
meta()
const std::vector< std::vector< larcv::ImageMeta > > & larcv::DatumFillerBase::meta () const inherited
Definition at line 39 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_meta_data.
Referenced by larcv::ThreadDatumFiller::meta(), and larcv::DatumFillerBase::~DatumFillerBase().
   { return _meta_data; }
mirrored()
const std::vector<bool>& larcv::SegFiller::mirrored () const inline
Definition at line 47 of file SegFiller.h.
References _mirrored, assert_dimension(), compute_image_size(), compute_label_size(), compute_multiplicity_size(), dim(), and fill_entry_data().
 { return _mirrored; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DatumFillerBase::process (IOManager & mgr) virtual inherited
Implements larcv::ProcessBase.
Definition at line 117 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_current_entry, larcv::DatumFillerBase::_entry_image_size, larcv::DatumFillerBase::_entry_label_size, larcv::DatumFillerBase::_entry_meta_data, larcv::DatumFillerBase::_entry_multiplicity_size, larcv::DatumFillerBase::_entry_weight_size, larcv::DatumFillerBase::_image_data, larcv::DatumFillerBase::_image_producer, larcv::DatumFillerBase::_image_producer_id, larcv::DatumFillerBase::_image_product_type, larcv::DatumFillerBase::_label_data, larcv::DatumFillerBase::_label_producer, larcv::DatumFillerBase::_label_producer_id, larcv::DatumFillerBase::_label_product_type, larcv::DatumFillerBase::_meta_data, larcv::DatumFillerBase::_multiplicity_data, larcv::DatumFillerBase::_multiplicity_producer, larcv::DatumFillerBase::_multiplicity_producer_id, larcv::DatumFillerBase::_multiplicity_product_type, larcv::DatumFillerBase::_nentries, larcv::DatumFillerBase::_weight_data, larcv::DatumFillerBase::_weight_producer, larcv::DatumFillerBase::_weight_producer_id, larcv::DatumFillerBase::_weight_product_type, larcv::DatumFillerBase::compute_image_size(), larcv::DatumFillerBase::compute_label_size(), larcv::DatumFillerBase::compute_multiplicity_size(), current_image_index_start, larcv::DatumFillerBase::entry_data(), entry_image_data, entry_label_data, larcv::EventBase::event(), larcv::DatumFillerBase::fill_entry_data(), larcv::IOManager< T >::get_data(), larcv::DatumFillerBase::kFillerImageData, larcv::DatumFillerBase::kFillerLabelData, larcv::DatumFillerBase::kFillerMultiplicityData, larcv::DatumFillerBase::kFillerWeightData, larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, LARCV_CRITICAL, LARCV_INFO, larcv::IOManager< T >::producer_id(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::ThreadDatumFiller::batch_process(), and larcv::DatumFillerBase::~DatumFillerBase().
   {
     LARCV_INFO() << std::endl;
     if(_current_entry == kINVALID_SIZE) {
       LARCV_CRITICAL() << "batch_begin() not called... Note this process is only meant to use with ThreadReadDriver!\n";
       throw larbys();
     }
     LARCV_INFO() << std::endl;
     if(_image_producer_id == kINVALID_PRODUCER) {
       _image_producer_id = mgr.producer_id(_image_product_type,_image_producer);
       if(_image_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Image producer " << _image_producer << " not valid!" << std::endl;
         throw larbys();
       }
       _label_producer_id = mgr.producer_id(_label_product_type,_label_producer);
       if(_label_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Label producer " << _label_producer << " not valid!" << std::endl;
         throw larbys();
       }
       LARCV_INFO() << std::endl;
       if(!_multiplicity_producer.empty()) {
     _multiplicity_producer_id = mgr.producer_id(_multiplicity_product_type,_multiplicity_producer);
     if(_multiplicity_producer_id == kINVALID_PRODUCER) {
       LARCV_CRITICAL() << "Multiplicity producer " << _multiplicity_producer << " not valid!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << std::endl;
       }
       if(!_weight_producer.empty()) {
     _weight_producer_id = mgr.producer_id(_weight_product_type,_weight_producer);
     if(_weight_producer_id == kINVALID_PRODUCER) {
       LARCV_CRITICAL() << "Weight producer " << _weight_producer << " not valid!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << std::endl;
       }
     }
     LARCV_INFO() << std::endl;
     auto const image_data        = mgr.get_data(_image_producer_id);
     auto const label_data        = mgr.get_data(_label_producer_id);
     const larcv::EventImage2D* multiplicity_data = NULL;
     LARCV_INFO() << std::endl;
     if(_entry_image_size==kINVALID_SIZE || _nentries == 1) {
       _entry_image_size        = compute_image_size(image_data);
       _entry_label_size        = compute_label_size(label_data);
       LARCV_INFO() << "Recomputed image size: "        << _entry_image_size << std::endl;
       LARCV_INFO() << "Recomputed label size: "        << _entry_label_size << std::endl;
       LARCV_INFO() << "Recomputed multiplicity size: " << _entry_multiplicity_size << std::endl;
       if( _entry_image_size == kINVALID_SIZE || _entry_label_size == kINVALID_SIZE) {
         LARCV_CRITICAL() << "Rows/Cols/NumChannels not set!" << std::endl;
         throw larbys();
       }
       _image_data.resize         (_entry_image_size         * _nentries, 0.);
       _label_data.resize         (_entry_label_size         * _nentries, 0.);
       if(_weight_producer_id != kINVALID_PRODUCER) {
     _entry_weight_size = _entry_image_size;
     _weight_data.resize (_entry_weight_size * _nentries, 0.);
       }
       if(_multiplicity_producer_id!=kINVALID_PRODUCER) {
     multiplicity_data = (larcv::EventImage2D*)mgr.get_data(_multiplicity_producer_id);
     _entry_multiplicity_size = compute_multiplicity_size(multiplicity_data);
     _multiplicity_data.resize  (_entry_multiplicity_size  * _nentries, 0.);
       }
     }
     EventBase* weight_data=nullptr;
     if(_weight_producer_id != kINVALID_PRODUCER)
       weight_data = mgr.get_data(_weight_producer_id);
     _entry_meta_data.clear();
     this->fill_entry_data(image_data,label_data,weight_data,multiplicity_data);
     auto const& entry_image_data        = entry_data(kFillerImageData);
     auto const& entry_label_data        = entry_data(kFillerLabelData);
     auto const& entry_weight_data       = entry_data(kFillerWeightData);
     auto const& entry_multiplicity_data = entry_data(kFillerMultiplicityData);
     if(entry_image_data.size() != _entry_image_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << image_data->run() << "," << image_data->subrun() << "," << image_data->event() << ")"
       << "Entry image size should be " << _entry_image_size << " but found " << entry_image_data.size() << std::endl;
       throw larbys();
     }
     if(entry_label_data.size() != _entry_label_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << label_data->run() << "," << label_data->subrun() << "," << label_data->event() << ")"
       << "Entry label size should be " << _entry_label_size << " but found " << entry_label_data.size() << std::endl;
       throw larbys();
     }
     if(entry_multiplicity_data.size() != _entry_multiplicity_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << multiplicity_data->run() << "," << multiplicity_data->subrun() << "," << multiplicity_data->event() << ")"
       << "Entry multiplicity size should be " << _entry_multiplicity_size << " but found " << entry_multiplicity_data.size() << std::endl;
       throw larbys();
     }
     if(entry_weight_data.size() != _entry_weight_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << weight_data->run() << "," << weight_data->subrun() << "," << weight_data->event() << ")"
       << "Entry weight size should be " << _entry_weight_size << " but found " << entry_weight_data.size() << std::endl;
       throw larbys();
     }
     const size_t current_image_index_start = _current_entry * _entry_image_size;
     for(size_t i = 0; i<_entry_image_size; ++i)
       _image_data[current_image_index_start + i] = entry_image_data[i];
     const size_t current_label_index_start = _current_entry * _entry_label_size;
     for(size_t i = 0; i<_entry_label_size; ++i)
       _label_data[current_label_index_start + i] = entry_label_data[i];
     const size_t current_multiplicity_index_start = _current_entry * _entry_multiplicity_size;
     for(size_t i = 0; i<_entry_multiplicity_size; ++i)
       _multiplicity_data[current_multiplicity_index_start + i] = entry_multiplicity_data[i];
     const size_t current_weight_index_start = _current_entry * _entry_weight_size;
     for(size_t i = 0; i<_entry_weight_size; ++i)
       _weight_data[current_weight_index_start + i] = entry_weight_data[i];
     _meta_data.emplace_back(std::move(_entry_meta_data));
     ++_current_entry;
     return true;
   }
producer()
const std::string & larcv::DatumFillerBase::producer (DatumFillerBase::FillerDataType_t dtype) const inherited
Definition at line 20 of file DatumFillerBase.cxx.
References larcv::DatumFillerBase::_image_producer, larcv::DatumFillerBase::_label_producer, larcv::DatumFillerBase::_multiplicity_producer, larcv::DatumFillerBase::_weight_producer, larcv::DatumFillerBase::kFillerImageData, larcv::DatumFillerBase::kFillerLabelData, larcv::DatumFillerBase::kFillerMultiplicityData, and larcv::DatumFillerBase::kFillerWeightData.
Referenced by larcv::ThreadDatumFiller::producer(), and larcv::DatumFillerBase::~DatumFillerBase().
   { switch(dtype) {
     case kFillerImageData:
       return _image_producer;
     case kFillerLabelData:
       return _label_producer;
     case kFillerWeightData:
       return _weight_producer;
     case kFillerMultiplicityData:
       return _multiplicity_producer;
     }
     return _weight_producer;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_caffe_idx_to_img_idx
std::vector<size_t> larcv::SegFiller::_caffe_idx_to_img_idx private
Definition at line 74 of file SegFiller.h.
Referenced by compute_image_size(), and fill_entry_data().
_cols
size_t larcv::SegFiller::_cols private
Definition at line 70 of file SegFiller.h.
Referenced by assert_dimension(), compute_image_size(), dim(), and fill_entry_data().
_crop_image
bool larcv::SegFiller::_crop_image private
Definition at line 79 of file SegFiller.h.
Referenced by assert_dimension(), child_configure(), compute_image_size(), and fill_entry_data().
_cropper
RandomCropper larcv::SegFiller::_cropper private
Definition at line 81 of file SegFiller.h.
Referenced by child_configure(), compute_image_size(), and fill_entry_data().
_entry_image_data
std::vector<float> larcv::DatumFillerBase::_entry_image_data protected inherited
Definition at line 101 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), child_initialize(), larcv::SimpleFiller::child_initialize(), larcv::DatumFillerBase::entry_data(), larcv::SimpleFiller::fill_entry_data(), fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_label_data
std::vector<float> larcv::DatumFillerBase::_entry_label_data protected inherited
Definition at line 102 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), child_initialize(), larcv::SimpleFiller::child_initialize(), larcv::DatumFillerBase::entry_data(), larcv::SimpleFiller::fill_entry_data(), fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_meta_data
std::vector<larcv::ImageMeta> larcv::DatumFillerBase::_entry_meta_data protected inherited
Definition at line 109 of file DatumFillerBase.h.
Referenced by larcv::DatumFillerBase::entry_meta(), larcv::SimpleFiller::fill_entry_data(), fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), and larcv::DatumFillerBase::process().
_entry_multiplicity_data
std::vector<float> larcv::DatumFillerBase::_entry_multiplicity_data protected inherited
Definition at line 104 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), larcv::DatumFillerBase::entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_weight_data
std::vector<float> larcv::DatumFillerBase::_entry_weight_data protected inherited
Definition at line 103 of file DatumFillerBase.h.
Referenced by larcv::DatumFillerBase::entry_data(), and fill_entry_data().
_image_product_type
ProductType_t larcv::DatumFillerBase::_image_product_type protected inherited
Definition at line 105 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), larcv::DatumFillerBase::process(), SegFiller(), and larcv::SimpleFiller::SimpleFiller().
_label_product_type
ProductType_t larcv::DatumFillerBase::_label_product_type protected inherited
Definition at line 106 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), larcv::DatumFillerBase::process(), SegFiller(), and larcv::SimpleFiller::SimpleFiller().
_max_ch
size_t larcv::SegFiller::_max_ch private
Definition at line 73 of file SegFiller.h.
Referenced by assert_dimension(), and compute_image_size().
_mirror_caffe_idx_to_img_idx
std::vector<size_t> larcv::SegFiller::_mirror_caffe_idx_to_img_idx private
Definition at line 75 of file SegFiller.h.
Referenced by compute_image_size(), and fill_entry_data().
_mirror_image
bool larcv::SegFiller::_mirror_image private
Definition at line 78 of file SegFiller.h.
Referenced by child_configure(), and fill_entry_data().
_mirrored
std::vector<bool> larcv::SegFiller::_mirrored private
Definition at line 77 of file SegFiller.h.
Referenced by child_batch_begin(), child_batch_end(), fill_entry_data(), and mirrored().
_multiplicity_product_type
ProductType_t larcv::DatumFillerBase::_multiplicity_product_type protected inherited
Definition at line 108 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), and larcv::DatumFillerBase::process().
_num_channels
size_t larcv::SegFiller::_num_channels private
Definition at line 71 of file SegFiller.h.
Referenced by compute_image_size(), dim(), and fill_entry_data().
_roitype_to_class
std::vector<size_t> larcv::SegFiller::_roitype_to_class private
Definition at line 76 of file SegFiller.h.
Referenced by child_configure(), and fill_entry_data().
_rows
size_t larcv::SegFiller::_rows private
Definition at line 69 of file SegFiller.h.
Referenced by assert_dimension(), compute_image_size(), dim(), and fill_entry_data().
_seg_channel
size_t larcv::SegFiller::_seg_channel private
Definition at line 68 of file SegFiller.h.
Referenced by child_configure(), fill_entry_data(), and SegFiller().
_slice_v
std::vector<size_t> larcv::SegFiller::_slice_v private
Definition at line 72 of file SegFiller.h.
Referenced by child_configure(), compute_image_size(), and fill_entry_data().
_weight_product_type
ProductType_t larcv::DatumFillerBase::_weight_product_type protected inherited
Definition at line 107 of file DatumFillerBase.h.
Referenced by larcv::DatumFillerBase::process(), and SegFiller().
The documentation for this class was generated from the following files:
SegFiller.h
SegFiller.cxx