LArCV: larcv::PostTagger Class Reference
larcv::PostTagger Class Reference
#include <PostTagger.h>
Public Member Functions
PostTagger ()
~PostTagger ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void Configure (const PSet &pset)
void MergeTaggedPixels (cv::Mat &adc_img, cv::Mat &trk_img, cv::Mat &shr_img, cv::Mat &thrumu_img, cv::Mat &stopmu_img)
Private Attributes
unsigned _ctor_sz_threshold
bool _check_thrumu
bool _check_stopmu
Detailed Description
Definition at line 13 of file PostTagger.h.
Constructor & Destructor Documentation
PostTagger()
larcv::PostTagger::PostTagger ()
Definition at line 10 of file PostTagger.cxx.
References _check_stopmu, _check_thrumu, and _ctor_sz_threshold.
{
     _ctor_sz_threshold = 3;
     _check_thrumu = true;
     _check_stopmu = true;
   }
~PostTagger()
larcv::PostTagger::~PostTagger () inline
Definition at line 17 of file PostTagger.h.
References Configure(), and MergeTaggedPixels().
 {}
Member Function Documentation
Configure()
void larcv::PostTagger::Configure (const PSet & pset) private
Definition at line 16 of file PostTagger.cxx.
Referenced by ~PostTagger().
{
     return;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MergeTaggedPixels()
void larcv::PostTagger::MergeTaggedPixels (cv::Mat & adc_img, cv::Mat & trk_img, cv::Mat & shr_img, cv::Mat & thrumu_img, cv::Mat & stopmu_img) private
Definition at line 20 of file PostTagger.cxx.
References _check_stopmu, _check_thrumu, and _ctor_sz_threshold.
Referenced by ~PostTagger().
{
     auto ctor_v = larocv::FindContours(adc_img);
     for(const auto& ctor : ctor_v) {
       if (ctor.size() <= _ctor_sz_threshold) continue;
       if (_check_thrumu && larocv::CountNonZero(larocv::MaskImage(thrumu_img,ctor,0,false))) {
     adc_img = larocv::MaskImage(adc_img,ctor,0,true);
     shr_img = larocv::MaskImage(shr_img,ctor,0,true);
     trk_img = larocv::MaskImage(trk_img,ctor,0,true);
       }
       if (_check_stopmu && larocv::CountNonZero(larocv::MaskImage(stopmu_img,ctor,0,false))) {
     adc_img = larocv::MaskImage(adc_img,ctor,0,true);
     shr_img = larocv::MaskImage(shr_img,ctor,0,true);
     trk_img = larocv::MaskImage(trk_img,ctor,0,true);
       }
     } // end this contour
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_check_stopmu
bool larcv::PostTagger::_check_stopmu private
Definition at line 30 of file PostTagger.h.
Referenced by MergeTaggedPixels(), and PostTagger().
_check_thrumu
bool larcv::PostTagger::_check_thrumu private
Definition at line 29 of file PostTagger.h.
Referenced by MergeTaggedPixels(), and PostTagger().
_ctor_sz_threshold
unsigned larcv::PostTagger::_ctor_sz_threshold private
Definition at line 28 of file PostTagger.h.
Referenced by MergeTaggedPixels(), and PostTagger().
The documentation for this class was generated from the following files:
PostTagger.h
PostTagger.cxx