LArCV: larcv::ROIMerger Class Reference
larcv::ROIMerger Class Reference
#include <ROIMerger.h>
Public Member Functions
ROIMerger (const std::string name="ROIMerger")
Default constructor.
~ROIMerger ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
const std::string & output_producer () const
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void SearchScore (size_t this_id, size_t that_id, std::vector< std::vector< std::pair< size_t, float > > > &scores_pvv, std::vector< std::set< size_t > > &merge_id_vv, std::vector< bool > &seek_v)
Private Attributes
std::string _input_roi_producer
std::string _output_roi_producer
float _iou_threshold
Detailed Description
Definition at line 26 of file ROIMerger.h.
Constructor & Destructor Documentation
ROIMerger()
larcv::ROIMerger::ROIMerger (const std::string name = "ROIMerger")
Default constructor.
Definition at line 15 of file ROIMerger.cxx.
Referenced by larcv::ROIMergerProcessFactory::create().
     : ProcessBase(name)
   {}
~ROIMerger()
larcv::ROIMerger::~ROIMerger () inline
Default destructor.
Definition at line 34 of file ROIMerger.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ROIMerger::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file ROIMerger.cxx.
References _input_roi_producer, _iou_threshold, _output_roi_producer, larcv::PSet::get(), and LARCV_DEBUG.
Referenced by ~ROIMerger().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _input_roi_producer = cfg.get<std::string>("InputROIProducer");
     _output_roi_producer = cfg.get<std::string>("OutputROIProducer");
     _iou_threshold = cfg.get<float>("IOUThreshold",0.5);
     LARCV_DEBUG() << "end" << std::endl;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ROIMerger::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 187 of file ROIMerger.cxx.
Referenced by ~ROIMerger().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ROIMerger::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 28 of file ROIMerger.cxx.
Referenced by ~ROIMerger().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
output_producer()
const std::string& larcv::ROIMerger::output_producer () const inline
Definition at line 44 of file ROIMerger.h.
References _output_roi_producer.
     { return _output_roi_producer; }
process()
bool larcv::ROIMerger::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 41 of file ROIMerger.cxx.
References _input_roi_producer, _output_roi_producer, larcv::IOManager< T >::get_data(), larcv::Intersection(), larcv::kINVALID_SIZE, larcv::kProductROI, LARCV_DEBUG, larcv::MakeRect(), and SearchScore().
Referenced by ~ROIMerger().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if (_input_roi_producer.empty()) throw larbys("No roi producer specified");
     LARCV_DEBUG() << "Reading ev roi @ producer " << _input_roi_producer << std::endl;
     auto in_ev_roi = (EventROI*)(mgr.get_data(kProductROI,_input_roi_producer));
     if (!in_ev_roi) throw larbys("input ROI not found!");
     auto out_ev_roi = (EventROI*)(mgr.get_data(kProductROI,_output_roi_producer));
     if (!out_ev_roi) throw larbys("output ROI failed creation");
     const auto& in_roi_v = in_ev_roi->ROIArray();
     const size_t nrois=in_roi_v.size();
     std::vector<std::array<geo2d::Rect,3>> roi_rect_v;
     roi_rect_v.resize(nrois);
     std::vector<float> roi_size_v(nrois,0.0);
     for(size_t roiid=0;roiid<nrois;++roiid) {
       const auto& roi = in_roi_v[roiid];
       auto& roi_size = roi_size_v[roiid];
       for(size_t plane=0;plane<3;++plane) {
     const auto& bb = roi.BB(plane);
     LARCV_DEBUG() << "@ roi " << roiid << "," << bb.dump();
     auto& rect = roi_rect_v[roiid][plane];
     rect = MakeRect(bb);
     roi_size+=rect.area();
       }
     }
     size_t n=0;
     std::vector<size_t> roi_idx_v(nrois,kINVALID_SIZE);
     for(auto& v : roi_idx_v) {v = n; ++n;}
     std::sort(std::begin(roi_idx_v),std::end(roi_idx_v),
           [&roi_size_v](size_t i1, size_t i2) { return roi_size_v[i1] > roi_size_v[i2]; } );
     /*
     std::stringstream ss;
     ss.str("");
     ss << "Area ordered [";
     for(auto srid : roi_idx_v) ss << srid << ",";
     ss << "]";
     LARCV_DEBUG() << ss.str() << std::endl;
     ss.str("");
     */
     std::vector<std::vector<std::pair<size_t,float> > > scores_pvv;
     scores_pvv.resize(nrois);
     for(size_t rid1=0;rid1<nrois;++rid1) {
       for(size_t rid2=0;rid2<nrois;++rid2) {
     if (rid1==rid2) continue;
     const auto& sroi1 = roi_rect_v[rid1];
     const auto& sroi2 = roi_rect_v[rid2];
     float iomin=0.0;
     for(size_t plane=0;plane<3;++plane) {
       auto rect1 = sroi1[plane];
       auto rect2 = sroi2[plane];
       auto inter_ = geo2d::Intersection(rect1,rect2).area();
       //auto union_ = geo2d::Union(rect1,rect2).area();
       // if (union_>0)
       iomin += inter_/std::min(rect1.area(),rect2.area());
     }
     scores_pvv[rid1].emplace_back(rid2,iomin/3.0);
       }
     }
     /*
     ss.str("")
     ss << "Scores " << std::endl;
     for(size_t id_=0;id_<scores_pvv.size();++id_) {
       auto& scores_pv = scores_pvv[id_];
       ss << "\t\t" << id_<<")";
       for(auto& scores_p : scores_pv) {
     ss << "("<<scores_p.first<<","<<scores_p.second<<") -- ";
       }
       ss << std::endl;
     }
     LARCV_DEBUG() << ss.str() << std::endl;
     */
     std::vector<std::set<size_t> > merge_id_vv;
     merge_id_vv.resize(nrois);
     for(auto srid : roi_idx_v) {
       std::vector<bool> seek_v(nrois,false);
       seek_v[srid]=true;
       auto& scores_pv = scores_pvv[srid];
       SearchScore(srid,srid,scores_pvv,merge_id_vv,seek_v);
     }
     /*
     ss << "Merging... " << std::endl;
     for(size_t merged_id=0;merged_id<merge_id_vv.size();++merged_id) {
       auto& merged_id_v = merge_id_vv[merged_id];
       ss << "\t\t" << merged_id<<") [";
       for(auto merged_id_ : merged_id_v)
     ss << merged_id_ << ",";
       ss << "]" << std::endl;
     }
     LARCV_DEBUG() << ss.str() << std::endl;
     ss.str("");
     */
     std::vector<bool> seek_v(nrois,false);
     for(auto srid : roi_idx_v) {
       if (seek_v[srid]) continue;
       seek_v[srid]=true;
       auto roi = in_roi_v[srid];
       auto res_meta_v = roi.BB();
       for(auto merge_id : merge_id_vv[srid]) {
     seek_v[merge_id]=true;
     for(size_t plane=0;plane<3;++plane) {
       const auto& merge_meta = in_roi_v[merge_id].BB(plane);
       auto& res_meta = res_meta_v[plane];
       res_meta = res_meta.inclusive(merge_meta);
     }
       }
       roi.SetBB(res_meta_v);
       out_ev_roi->Emplace(std::move(roi));
     }
     return true;
   }
SearchScore()
void larcv::ROIMerger::SearchScore (size_t this_id, size_t that_id, std::vector< std::vector< std::pair< size_t, float > > > & scores_pvv, std::vector< std::set< size_t > > & merge_id_vv, std::vector< bool > & seek_v) private
Definition at line 171 of file ROIMerger.cxx.
References _iou_threshold.
Referenced by process().
{
     for(auto score : scores_pvv[that_id]) {
       if ( seek_v[score.first] ) continue;
       seek_v[score.first] = true;
       if (score.second<_iou_threshold)  continue;
       merge_id_vv[this_id].insert(score.first);
       SearchScore(this_id,that_id,scores_pvv,merge_id_vv,seek_v);
     }
     return;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_input_roi_producer
std::string larcv::ROIMerger::_input_roi_producer private
Definition at line 49 of file ROIMerger.h.
Referenced by configure(), and process().
_iou_threshold
float larcv::ROIMerger::_iou_threshold private
Definition at line 51 of file ROIMerger.h.
Referenced by configure(), and SearchScore().
_output_roi_producer
std::string larcv::ROIMerger::_output_roi_producer private
Definition at line 50 of file ROIMerger.h.
Referenced by configure(), output_producer(), and process().
The documentation for this class was generated from the following files:
ROIMerger.h
ROIMerger.cxx