LArCV: larcv::CombineImagesProcessFactory Class Reference
larcv::CombineImagesProcessFactory Class Reference
#include <CombineImages.h>
Public Member Functions
CombineImagesProcessFactory ()
ctor
~CombineImagesProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 55 of file CombineImages.h.
Constructor & Destructor Documentation
CombineImagesProcessFactory()
larcv::CombineImagesProcessFactory::CombineImagesProcessFactory () inline
ctor
Definition at line 58 of file CombineImages.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("CombineImages",this); }
~CombineImagesProcessFactory()
larcv::CombineImagesProcessFactory::~CombineImagesProcessFactory () inline
dtor
Definition at line 60 of file CombineImages.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::CombineImagesProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 62 of file CombineImages.h.
References larcv::CombineImages::CombineImages().
 { return new CombineImages(instance_name); }
The documentation for this class was generated from the following file:
CombineImages.h