LArCV: larcv::PSet Class Reference
larcv::PSet Class Reference
User defined class PSet ...
#include <PSet.h>
Public Member Functions
PSet (const std::string name="", const std::string data="")
Default constructor.
virtual ~PSet ()
Default destructor.
PSet (const PSet &orig)
Copy ctor.
const std::string & name () const
name getter
bool operator== (const PSet &rhs) const
operator override
bool operator!= (const PSet &rhs) const
void clear ()
clear method
void add (const std::string &data)
Set data contents.
void add_value (std::string key, std::string value)
Insert method for a simple param.
void add_pset (const PSet &p)
Insert method for a PSet rep.
void add_pset (std::string key, std::string pset)
Insert method for a PSet rep.
std::string dump (size_t indent_size=0) const
Dump into a text format.
std::string data_string () const
Dump data string.
template<class T >
T get (const std::string &key) const
Template getter.
template<class T >
T get (const std::string &key, const T default_value) const
Template getter w/ default value.
const PSet & get_pset (const std::string &key) const
None-template function to retrieve parameter set (deprecated)
size_t size () const
Returns # of parameters.
const std::vector< std::string > keys () const
Returns a vector of all parameter keys.
const std::vector< std::string > value_keys () const
Returns a vector of keys for key-value pairs.
const std::vector< std::string > pset_keys () const
Returns a vector of keys for key-PSet pairs.
bool contains_value (const std::string &key) const
Check if a specified key exists for key-value pairs.
bool contains_pset (const std::string &key) const
Check if a specified key exists for key-PSet pairs.
template<>
PSet get (const std::string &key) const
Private Types
enum KeyChar_t {
kParamDef, kBlockStart, kBlockEnd, kString,
kNone
}
Private Member Functions
std::pair< PSet::KeyChar_t, size_t > search (const std::string &txt, const size_t start) const
void strip (std::string &str, const std::string &key)
void rstrip (std::string &str, const std::string &key)
void trim_space (std::string &txt)
void no_space (std::string &txt)
Private Attributes
std::string _name
The name of this larcv::PSet.
std::map< std::string, std::string > _data_value
Key-Value pairs.
std::map< std::string,::larcv::PSet > _data_pset
Key-PSet pairs.
Detailed Description
User defined class PSet ...
these comments are used to generate doxygen documentation!
Definition at line 28 of file PSet.h.
Member Enumeration Documentation
KeyChar_t
enum larcv::PSet::KeyChar_t private
Enumerator
kParamDef
kBlockStart
kBlockEnd
kString
kNone
Definition at line 139 of file PSet.h.
                    {
       kParamDef,
       kBlockStart,
       kBlockEnd,
       kString,
       kNone
     };
Constructor & Destructor Documentation
PSet() [1/2]
larcv::PSet::PSet (const std::string name = "", const std::string data = "")
Default constructor.
Definition at line 8 of file PSet.cxx.
References _name, add(), and name().
Referenced by add_pset().
   {
     if(name.empty()) throw larbys("Cannot make PSet with an empty name!");
     _name = name;
     if(!data.empty()) this->add(data);
   }
~PSet()
virtual larcv::PSet::~PSet () inline virtual
Default destructor.
Definition at line 37 of file PSet.h.
 {};
PSet() [2/2]
larcv::PSet::PSet (const PSet & orig) inline
Copy ctor.
Definition at line 40 of file PSet.h.
                            : _name       ( orig._name       )
                , _data_value ( orig._data_value )
                , _data_pset  ( orig._data_pset  )
     {}
Member Function Documentation
add()
void larcv::PSet::add (const std::string & data)
Set data contents.
Definition at line 167 of file PSet.cxx.
References add_pset(), add_value(), kBlockEnd, kBlockStart, kNone, kParamDef, kString, no_space(), rstrip(), search(), strip(), and trim_space().
Referenced by larcv::ConfigManager::AddConfigString(), clear(), and PSet().
   {
     if(contents.size()<1) return;
     size_t index=0;
     while(contents.find(" ",index) == index)
       index +=1;
     if(index >= contents.size()) return;
     size_t end_index=contents.size()-1;
     while(contents.rfind(" ",end_index) == end_index)
       end_index -= 1;
     if(end_index <= index || end_index > contents.size()) return;
     std::string key,value,tmp;
     KeyChar_t last_mark=kNone;
     while(index <= end_index) {
       auto next_marker = this->search(contents,index);
       if(next_marker.first == kString) {
     //std::cout<<"String found in here: "<<contents.substr(index,(next_marker.second-index))<<std::endl;
     while(next_marker.second < end_index+1) {
       next_marker = this->search(contents,next_marker.second+1);
       if(next_marker.first == kString) {
         next_marker = this->search(contents,next_marker.second+1);
         break;
       }
     }
     //std::cout<<"String found in here: "<<contents.substr(index,next_marker.second-index)<<std::endl;
       }
       if(next_marker.second > end_index) break;
       if(next_marker.first == kNone) break;
       /*
       std::cout<<"index: "<<index<<std::endl;
       std::cout<<"marker: "<<next_marker.second<<std::endl;
       std::cout<<"type  : "<<next_marker.first<<std::endl;
       std::cout<<"last  : "<<last_mark<<std::endl;
       std::cout<<"Inspecting: "<<"\""<<contents.substr(index,(next_marker.second-index))<<"\""<<std::endl;
       */
       if(next_marker.first == kParamDef) {
     if(last_mark ==  kNone || last_mark == kBlockEnd){
       key = contents.substr(index,(next_marker.second-index));
       no_space(key);
     }
     else if(last_mark == kParamDef || last_mark == kString) {
       tmp = contents.substr(index,(next_marker.second-index));
       //std::cout<<"Inspecting: \""<<tmp<<"\"" <<std::endl;
       strip(tmp," ");
       rstrip(tmp," ");
       size_t sep_index = tmp.rfind(" ");
       if(sep_index >= tmp.size())
         throw larbys("Invalid format (key:value)");
       value = tmp.substr(0,sep_index);
       // complete pair
       this->add_value(key,value);
       //std::cout<<"Found value: "<<value<<std::endl;
       key = value = "";
       key = tmp.substr(sep_index+1,(tmp.size()-sep_index-1));
       no_space(key);
     }
       }else if(next_marker.first == kBlockEnd)
     throw larbys("Block end logic error!");
       else if(next_marker.first == kBlockStart){
     //std::cout<<"Block start!"<<std::endl;
     if(last_mark != kParamDef)
       throw larbys("Invalid paramter set start!");
     // fast forward till this block ends
     int start_ctr = 1;
     index = next_marker.second + 1;
     while(start_ctr && next_marker.second <= end_index) {
       next_marker = this->search(contents,next_marker.second+1);
       if(next_marker.first == kString) {
         while(next_marker.second < end_index+1) {
           next_marker = this->search(contents,next_marker.second+1);
           auto tmp_next_marker = this->search(contents,next_marker.second+1);
           if(next_marker.first == kString && tmp_next_marker.second != kString) {
         next_marker = tmp_next_marker;
         break;
           }
         }
         //std::cout<<"Found string :"<<contents.substr(index,next_marker.second)<<std::endl;
       }
       switch(next_marker.first){
       case kBlockStart:
         start_ctr +=1;
         break;
       case kBlockEnd:
         start_ctr -=1;
         break;
       default:
         break;
       }
     }
     if(start_ctr) {
       std::string msg;
       msg = "Invalid block:\n" + contents.substr(index,next_marker.second-index) + "\n";
       throw larbys(msg.c_str());
     }
     value = contents.substr(index,next_marker.second-index);
     //std::cout<<"PSET!\n"<<value<<"\n"<<std::endl;
     // complete key/value
     this->add_pset(key,value);
     key="";
     value="";
       }
       else throw larbys("Unknown error!");
       index = next_marker.second+1;
       last_mark = next_marker.first;
     }
     if(index <= end_index) {
       if(!value.empty()) throw larbys("Non-empty value @ process-end!");
       if(key.empty()) throw larbys("Empty key @ process-end!");
       tmp = contents.substr(index+1,end_index-index);
       //no_space(tmp);
       trim_space(tmp);
       if(tmp.empty()) throw larbys("Empty value @ end!");
       value = tmp;
       this->add_value(key,value);
       key = "";
       value = "";
     }
     if(!key.empty() || !value.empty())
       throw larbys("Unpaired key:value!");
   }
add_pset() [1/2]
void larcv::PSet::add_pset (const PSet & p)
Insert method for a PSet rep.
Definition at line 140 of file PSet.cxx.
References _data_pset, _data_value, and name().
Referenced by add(), larcv::ConfigManager::AddConfigFile(), larcv::ConfigManager::AddConfigString(), and clear().
   {
     if( _data_value.find(p.name()) != _data_value.end() ||
         _data_pset.find(p.name())  != _data_pset.end() ) {
       std::string msg;
       msg = " Duplicate key: \"" + p.name() + "\"";
       throw larbys(msg.c_str());
     }
     _data_pset.insert(std::make_pair(p.name(),p));
   }
add_pset() [2/2]
void larcv::PSet::add_pset (std::string key, std::string pset)
Insert method for a PSet rep.
Definition at line 151 of file PSet.cxx.
References _data_pset, _data_value, no_space(), PSet(), rstrip(), and strip().
   {
     if( _data_value.find(key) != _data_value.end() ||
         _data_pset.find(key)  != _data_pset.end() ) {
       std::string msg;
       msg = " Duplicate key: \"" + key + "\"";
       throw larbys(msg.c_str());
     }
     no_space(key);
     if(key.empty()) throw larbys("Empty key cannot be registered!");
     strip(value," ");
     rstrip(value," ");
     _data_pset.emplace(key,PSet(key,value));
   }
add_value()
void larcv::PSet::add_value (std::string key, std::string value)
Insert method for a simple param.
Definition at line 122 of file PSet.cxx.
References _data_pset, _data_value, no_space(), and trim_space().
Referenced by add(), clear(), and larcv::ThreadDatumFiller::set_next_batch().
   {
     //std::cout<<"  "<<key<<" => "<<value<<std::endl;
     if( _data_value.find(key) != _data_value.end() ||
         _data_pset.find(key)  != _data_pset.end() ) {
       std::string msg;
       msg = " Duplicate key: \"" + key + "\"";
       throw larbys(msg.c_str());
     }
     no_space(key);
     if(key.empty()) throw larbys("Empty key cannot be registered!");
     //std::cout<<"value: @"<<value<<"@"<<std::endl;
     trim_space(value);
     //if(value.empty()) throw larbys("Empty value cannot be registered!");
     _data_value[key]=value;
   }
clear()
void larcv::PSet::clear () inline
clear method
Definition at line 75 of file PSet.h.
References _data_pset, _data_value, add(), add_pset(), add_value(), data_string(), and dump().
Referenced by larcv::ProcessDriver::configure(), and larcv::ThreadDatumFiller::configure().
     { _data_value.clear(); _data_pset.clear(); }
contains_pset()
bool larcv::PSet::contains_pset (const std::string & key) const
Check if a specified key exists for key-PSet pairs.
Definition at line 46 of file PSet.cxx.
References _data_pset.
Referenced by larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), get(), and operator==().
   {
     return (_data_pset.find(key) != _data_pset.end());
   }
contains_value()
bool larcv::PSet::contains_value (const std::string & key) const
Check if a specified key exists for key-value pairs.
Definition at line 42 of file PSet.cxx.
References _data_value.
Referenced by get(), and operator==().
   {
     return (_data_value.find(key) != _data_value.end());
   }
data_string()
std::string larcv::PSet::data_string () const
Dump data string.
Definition at line 339 of file PSet.cxx.
References _data_pset, _data_value, and _name.
Referenced by clear().
   {
     std::string res;
     res = _name + ": {";
     for(auto const& key_value : _data_value)
       res += key_value.first + ": " + key_value.second + " ";
     for(auto const& key_value : _data_pset)
       res += key_value.second.data_string();
     res += "} ";
     return res;
   }
dump()
std::string larcv::PSet::dump (size_t indent_size = 0) const
Dump into a text format.
Definition at line 320 of file PSet.cxx.
References _data_pset, _data_value, and _name.
Referenced by clear(), larcv::ThreadDatumFiller::configure(), larcv::ProcessDriver::configure(), and get().
   {
     std::string res,in_indent,out_indent;
     for(size_t i=0; i<indent_size; ++i) out_indent += " ";
     res = out_indent + _name + " : {\n";
     in_indent = out_indent + "  ";
     for(auto const& key_value : _data_value)
       res += in_indent + key_value.first + " : " + key_value.second + "\n";
     for(auto const& key_value : _data_pset)
       res += key_value.second.dump(in_indent.size()) + "\n";
     res += out_indent + "}\n";
     return res;
   }
get() [1/3]
template<class T > T larcv::PSet::get (const std::string & key) const inline
Template getter.
Definition at line 99 of file PSet.h.
References _data_value, and dump().
Referenced by larcv::ProcessBase::_configure_(), larcv::MultiClassFiller::child_configure(), larcv::SegFiller::child_configure(), larcv::SimpleFiller::child_configure(), larcv::PGraphTruthMatch::configure(), larcv::LArbysTrash::configure(), larcv::ROIClipper::configure(), larcv::VertexFilter::configure(), larcv::VertexInROI::configure(), larcv::AlgoDataAna::configure(), larcv::ROIPad::configure(), larcv::LArbysImageFilter::configure(), larcv::ReadNueFile::configure(), larcv::DeadWireAna::configure(), larcv::UnionROI::configure(), larcv::LArbysImageAna::configure(), larcv::SSNetEventAna::configure(), larcv::LArbysImageExtract::configure(), larcv::LArbysImageResult::Configure(), larcv::TrackShowerAna::Configure(), larcv::SSNetTruthAna::configure(), larcv::CosmicPixelAna::configure(), larcv::VertexAna::configure(), larcv::LEE1e1pAna::configure(), larcv::DLCosmicTagUtil::Configure(), larcv::LArbysImage::configure(), larcv::ExampleAna::configure(), larcv::ParticleAna::configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::LArbysImageMC::configure(), larcv::WireMask::configure(), larcv::ADCThreshold::configure(), larcv::BlankImage::configure(), larcv::EmptyImageFilter::configure(), supera::ParamsChStatus::configure(), supera::ParamsImage2D::configure(), larcv::CosmicROIFiller::configure(), supera::ParamsROI::configure(), supera::ParamsPixel2D::configure(), supera::ParamsVoxel3D::configure(), larcv::CosmicSegment::configure(), larcv::ROICountFilter::configure(), larcv::CropROI::configure(), larcv::ImageFromPixel2D::configure(), larcv::ImageFromPixel2DCluster::configure(), larcv::SimplePixelAna::configure(), larcv::CosmicTrackAna::configure(), larcv::QSumFilter::configure(), larcv::DataStream::configure(), larcv::ResizeImage::configure(), larcv::CCIncFilter::configure(), larcv::SegmentFilter::configure(), larcv::ROIMerger::configure(), larcv::ChannelMax::configure(), larcv::ROISizeFilter::configure(), larcv::RunFilter::configure(), larcv::DBSCAN::configure(), larcv::SegImageAna::configure(), larcv::SegmentAna::configure(), larcv::SegmentMask::configure(), larcv::SegWeightInstance::configure(), larcv::MaskImage::configure(), larcv::MCFilter::configure(), larcv::SegWeightTrackShower::configure(), larcv::SimpleDigitizer::configure(), larcv::CombineImages::configure(), larcv::DoNothing::configure(), larcv::SliceImages::configure(), larcv::StepDigitizer::configure(), larcv::MCSingleParticleFilter::configure(), larcv::ModularPadImage::configure(), larcv::ChStatusConverter::configure(), larcv::MultiROICropper::configure(), larcv::ImageMerger::configure(), larcv::CCQETruthFilter::configure(), larcv::ADCScaleAna::configure(), larcv::SegmentMaker::configure(), larcv::Compressor::configure(), larcv::MeanSubtraction::configure(), larcv::NuFilter::configure(), larcv::ADCScale::configure(), larcv::PlaneImageMerger::configure(), larcv::PreProcessorAna::configure(), supera::ImageMetaFromConfig::configure(), larcv::PyImageMaker::configure(), larcv::PyImageStitcher::configure(), larcv::RandomCropper::configure(), larcv::BadRegionAna::configure(), larcv::CosmicFilter::configure(), larcv::SuperaChStatus::configure(), larcv::VtxInRegion::configure(), larcv::GenDeadChannelMap::configure(), larcv::VertexImg::configure(), larcv::CosmicVertexAna::configure(), larcv::DumpHiResCropImages::configure(), supera::MCROIMaker::configure(), larcv::EmbedImage::configure(), larcv::ROIAna::configure(), larcv::GoodcROIFilter::configure(), larcv::Binarize::configure(), supera::ImageMetaMakerBase::configure(), larcv::NNCosine::configure(), larcv::OperateImage::configure(), larcv::SegDatumFillerBase::configure(), larcv::ThreadDatumFiller::configure(), larcv::ROIMask::configure(), larcv::calcPeakADC::configure(), larcv::SuperaSimCh::configure(), larcv::HistADC::configure(), larcv::ImageROICheckMC::configure(), larcv::ProcessDriver::configure(), larcv::SuperaBase::configure(), larcv::SuperaSimVoxel3D::configure(), larcv::pmtweights::PMTWeightImageBuilder::configure(), larcv::SuperaKeyPointCluster::configure(), larcv::SegmentRelabel::configure(), supera::PulledPork3DSlicer::configure(), larcv::LArbysRecoHolder::Configure(), larcv::LArbysImagePID::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::SuperaMCROI::configure(), larcv::DatumFillerBase::configure(), larcv::PIDImageMaker::configure(), larcv::Run3DTracker::configure(), larcv::hires::HiResImageDivider::configure(), larcv::TrackerEventDisplay::configure(), larcv::ReadJarrettFile::configure(), larcv::IOManager< T >::configure(), larcv::RSEFilter::configure(), supera::MCParticleTree::configure(), supera::CreateImageMetaMaker(), larlite::Supera::initialize(), larcv::AStar3DAlgoConfig::MakeFromPSet(), operator==(), and larcv::ThreadDatumFiller::set_next_batch().
{
       auto iter = _data_value.find(key);
       if( iter == _data_value.end() ) {
         std::string msg;
         msg = "Key does not exist: \"" + key + "\"";
     std::cout<<dump()<<std::endl;
         throw larbys(msg);
       }
       return parser::FromString<T>((*iter).second);
     }
get() [2/3]
template<class T > T larcv::PSet::get (const std::string & key, const T default_value) const inline
Template getter w/ default value.
Definition at line 112 of file PSet.h.
References _data_value, contains_pset(), contains_value(), get_pset(), keys(), pset_keys(), size(), and value_keys().
{
       auto iter = _data_value.find(key);
       if( iter == _data_value.end() )
         return default_value;
       return parser::FromString<T>((*iter).second);
     }
get() [3/3]
template<> PSet larcv::PSet::get (const std::string & key) const
get_pset()
const PSet & larcv::PSet::get_pset (const std::string & key) const
None-template function to retrieve parameter set (deprecated)
Definition at line 356 of file PSet.cxx.
References _data_pset.
Referenced by larcv::LArbysImage::configure(), get(), larcv::ConfigManager::GetConfig(), operator==(), larcv::PSet::get< larcv::PSet >(), and larcv::ThreadDatumFiller::set_next_batch().
   {
     auto iter = _data_pset.find(key);
     if( iter == _data_pset.end() ) {
       std::string msg;
       msg = "Key does not exist: \"" + key + "\"";
       throw larbys(msg);
     }
     return (*iter).second;
   }
keys()
const std::vector< std::string > larcv::PSet::keys () const
Returns a vector of all parameter keys.
Definition at line 19 of file PSet.cxx.
References _data_pset, and _data_value.
Referenced by get().
   {
     std::vector<std::string> res;
     res.reserve(_data_value.size() + _data_pset.size());
     for(auto const& key_value : _data_value) res.push_back(key_value.first);
     for(auto const& key_value : _data_pset ) res.push_back(key_value.first);
     return res;
   }
name()
const std::string& larcv::PSet::name () const inline
name getter
Definition at line 46 of file PSet.h.
References _name.
Referenced by add_pset(), operator==(), and PSet().
 { return _name; }
no_space()
void larcv::PSet::no_space (std::string & txt) private
Definition at line 78 of file PSet.cxx.
References trim_space().
Referenced by add(), add_pset(), and add_value().
{
     trim_space(txt);
     if(txt.find(" ") < txt.size()) {
       std::stringstream ss;
       ss << " Processing: " << txt.c_str() << " ... Space not allowed!";
       throw larbys(ss.str());
     }
     if(txt.find("\t") < txt.size())
       throw larbys("Tab not allowed!");
   }
operator!=()
bool larcv::PSet::operator!= (const PSet & rhs) const inline
Definition at line 71 of file PSet.h.
     { return !((*this) == rhs); }
operator==()
bool larcv::PSet::operator== (const PSet & rhs) const inline
operator override
Definition at line 49 of file PSet.h.
References _name, contains_pset(), contains_value(), get(), get_pset(), name(), pset_keys(), and value_keys().
     {
       if(_name != rhs.name()) return false;
       auto const v_keys = this->value_keys();
       if(v_keys.size() != rhs.value_keys().size()) return false;
       for(auto const& key : v_keys) {
         if(!rhs.contains_value(key))
           return false;
         if(this->get<std::string>(key) != rhs.get<std::string>(key))
           return false;
       }
       auto const p_keys = this->pset_keys();
       if(p_keys.size() != rhs.pset_keys().size()) return false;
       for(auto const& key : p_keys) {
         if(!rhs.contains_pset(key))
           return false;
         if(this->get_pset(key) != rhs.get_pset(key))
           return false;
       }
       return true;
     }
pset_keys()
const std::vector< std::string > larcv::PSet::pset_keys () const
Returns a vector of keys for key-PSet pairs.
Definition at line 35 of file PSet.cxx.
References _data_pset.
Referenced by get(), operator==(), and larcv::ThreadDatumFiller::set_next_batch().
   {
     std::vector<std::string> res;
     res.reserve(_data_pset.size());
     for(auto const& key_value : _data_pset) res.push_back(key_value.first);
     return res;
   }
rstrip()
void larcv::PSet::rstrip (std::string & str, const std::string & key) private
Definition at line 58 of file PSet.cxx.
Referenced by add(), add_pset(), and trim_space().
   {
     size_t index = str.rfind(key);
     if(index >= str.size()) return;
     while(key.size() == (str.size() - index)) {
       str = str.substr(0,index);
       index = str.rfind(key);
       if(index >= str.size()) break;
     }
   }
search()
std::pair< PSet::KeyChar_t, size_t > larcv::PSet::search (const std::string & txt, const size_t start) const private
Definition at line 89 of file PSet.cxx.
References kBlockEnd, kBlockStart, kNone, and kParamDef.
Referenced by add().
   {
     std::pair<KeyChar_t,size_t> res(kNone,size_t(-1));
     size_t index = 0;
     //
     // kParamDef
     //
     index = txt.find(":",start);
     if(index != std::string::npos && index < res.second) {
       res.first  = kParamDef;
       res.second = index;
     }
     index = txt.find("{",start);
     if(index != std::string::npos && index < res.second) {
       res.first  = kBlockStart;
       res.second = index;
     }
     index = txt.find("}",start);
     if(index != std::string::npos && index < res.second) {
       res.first  = kBlockEnd;
       res.second = index;
     }
     /*
     index = txt.find("\"",start);
     if(index != std::string::npos && index < res.second) {
       res.first  = kString;
       res.second = index;
     }
     */
     return res;
   }
size()
size_t larcv::PSet::size () const
Returns # of parameters.
Definition at line 16 of file PSet.cxx.
References _data_pset, and _data_value.
Referenced by get().
   { return (_data_value.size() + _data_pset.size()); }
strip()
void larcv::PSet::strip (std::string & str, const std::string & key) private
Definition at line 51 of file PSet.cxx.
Referenced by add(), add_pset(), and trim_space().
   {
     if(str.find(key) != 0) return;
     while(str.find(key) == 0)
       str = str.substr(key.size(),str.size());
   }
trim_space()
void larcv::PSet::trim_space (std::string & txt) private
Definition at line 69 of file PSet.cxx.
References rstrip(), and strip().
Referenced by add(), add_value(), and no_space().
{
     strip  ( txt, " "  );
     strip  ( txt, "\t" );
     strip  ( txt, " "  );
     rstrip ( txt, " "  );
     rstrip ( txt, "\t" );
     rstrip ( txt, " "  );
   }
value_keys()
const std::vector< std::string > larcv::PSet::value_keys () const
Returns a vector of keys for key-value pairs.
Definition at line 28 of file PSet.cxx.
References _data_value.
Referenced by get(), operator==(), and larcv::ThreadDatumFiller::set_next_batch().
   {
     std::vector<std::string> res;
     res.reserve(_data_value.size());
     for(auto const& key_value : _data_value) res.push_back(key_value.first);
     return res;
   }
Member Data Documentation
_data_pset
std::map<std::string,::larcv::PSet> larcv::PSet::_data_pset private
Key-PSet pairs.
Definition at line 158 of file PSet.h.
Referenced by add_pset(), add_value(), clear(), contains_pset(), data_string(), dump(), get_pset(), keys(), pset_keys(), and size().
_data_value
std::map<std::string,std::string> larcv::PSet::_data_value private
Key-Value pairs.
Definition at line 156 of file PSet.h.
Referenced by add_pset(), add_value(), clear(), contains_value(), data_string(), dump(), get(), keys(), size(), and value_keys().
_name
std::string larcv::PSet::_name private
The name of this larcv::PSet.
Definition at line 154 of file PSet.h.
Referenced by data_string(), dump(), name(), operator==(), and PSet().
The documentation for this class was generated from the following files:
PSet.h
PSet.cxx