LArCV: larcv::LArbysImageOutProcessFactory Class Reference
larcv::LArbysImageOutProcessFactory Class Reference
#include <LArbysImageOut.h>
Public Member Functions
LArbysImageOutProcessFactory ()
ctor
~LArbysImageOutProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 71 of file LArbysImageOut.h.
Constructor & Destructor Documentation
LArbysImageOutProcessFactory()
larcv::LArbysImageOutProcessFactory::LArbysImageOutProcessFactory () inline
ctor
Definition at line 74 of file LArbysImageOut.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("LArbysImageOut",this); }
~LArbysImageOutProcessFactory()
larcv::LArbysImageOutProcessFactory::~LArbysImageOutProcessFactory () inline
dtor
Definition at line 76 of file LArbysImageOut.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::LArbysImageOutProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 78 of file LArbysImageOut.h.
References larcv::LArbysImageOut::LArbysImageOut().
 { return new LArbysImageOut(instance_name); }
The documentation for this class was generated from the following file:
LArbysImageOut.h