LArCV: supera::ParamsImage2D Class Reference
supera::ParamsImage2D Class Reference
User defined class ParamsImage2D ...
#include <ParamsImage2D.h>
Public Member Functions
ParamsImage2D ()
Default constructor.
~ParamsImage2D ()
Default destructor.
void configure (const supera::Config_t &)
const std::string & OutImageLabel () const
Private Attributes
std::string _out_image_producer
Detailed Description
User defined class ParamsImage2D ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file ParamsImage2D.h.
Constructor & Destructor Documentation
ParamsImage2D()
supera::ParamsImage2D::ParamsImage2D () inline
Default constructor.
Definition at line 31 of file ParamsImage2D.h.
 {}
~ParamsImage2D()
supera::ParamsImage2D::~ParamsImage2D () inline
Default destructor.
Definition at line 34 of file ParamsImage2D.h.
References configure().
 {}
Member Function Documentation
configure()
void supera::ParamsImage2D::configure (const supera::Config_t & cfg)
Definition at line 8 of file ParamsImage2D.cxx.
References _out_image_producer, and larcv::PSet::get().
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::configure(), larcv::SuperaWire::configure(), larcv::SuperaHit::configure(), and ~ParamsImage2D().
   {
     _out_image_producer = cfg.get<std::string>("OutImageLabel","");
   }
OutImageLabel()
const std::string& supera::ParamsImage2D::OutImageLabel () const inline
Definition at line 41 of file ParamsImage2D.h.
References _out_image_producer.
Referenced by larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), and larcv::SuperaHit::process().
 { return _out_image_producer;    }
Member Data Documentation
_out_image_producer
std::string supera::ParamsImage2D::_out_image_producer private
Definition at line 45 of file ParamsImage2D.h.
Referenced by configure(), and OutImageLabel().
The documentation for this class was generated from the following files:
ParamsImage2D.h
ParamsImage2D.cxx