LArCV: larcv::DLCosmicTagImageMaker Class Reference
larcv::DLCosmicTagImageMaker Class Reference
#include <DLCosmicTagImageMaker.h>
Public Member Functions
DLCosmicTagImageMaker ()
~DLCosmicTagImageMaker ()
void Configure (const PSet &pset)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Detailed Description
Definition at line 36 of file DLCosmicTagImageMaker.h.
Constructor & Destructor Documentation
DLCosmicTagImageMaker()
larcv::DLCosmicTagImageMaker::DLCosmicTagImageMaker () inline
Definition at line 40 of file DLCosmicTagImageMaker.h.
 {};
~DLCosmicTagImageMaker()
larcv::DLCosmicTagImageMaker::~DLCosmicTagImageMaker () inline
Definition at line 41 of file DLCosmicTagImageMaker.h.
References Configure().
 {};
Member Function Documentation
Configure()
void larcv::DLCosmicTagImageMaker::Configure (const PSet & pset)
Definition at line 10 of file DLCosmicTagImageMaker.cxx.
References larcv::PSet::get(), LARCV_DEBUG, and larcv::larcv_base::set_verbosity().
Referenced by ~DLCosmicTagImageMaker().
{
     LARCV_DEBUG() << "start" << std::endl;
     this->set_verbosity((msg::Level_t)pset.get<int>("Verbosity",2));
     LARCV_DEBUG() << "end" << std::endl;
     return;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
The documentation for this class was generated from the following files:
DLCosmicTagImageMaker.h
DLCosmicTagImageMaker.cxx