LArCV: larcv::SegImageAna Class Reference
larcv::SegImageAna Class Reference
#include <SegImageAna.h>
Public Member Functions
SegImageAna (const std::string name="SegImageAna")
Default constructor.
~SegImageAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _image_producer
Input Image2D producer name.
std::string _label_producer
Segmentation ground-truth (label) Image2D producer name.
std::string _segment_producer
Segmentation prediction (by CNN) Image2D producer name.
std::string _roi_producer
Some MCTruth info might be interesting.
size_t _image_channel
Which channel to use from input Image2D (assuming 1 channel)
size_t _label_channel
Which channel to use from input label Image2D (assuming 1 channel)
std::vector< size_t > _roitype_to_class
Attribute to convert ROIType_t to class type defined by caffe.
size_t _ntypes
Number of unique classes used by caffe.
TTree * _tree
Output analysis tree.
double _pi_thresh
Pixel Intensity (PI) threshold value to filter out pixels we do not care.
int _npx_thresh
pixels above PI threshold
int _npx_total
pixels total
int _npx_correct
pixels where prediction got it right
int _roi_type
enum for ROIType
double _prob_correct
Probability of getting the right pixel value in the whole image.
std::vector< int > _npx_total_v
of total pixel for a specific type (based on ground truth)
std::vector< int > _npx_predicted_v
of predicted pixel for a specific type
std::vector< int > _npx_correct_v
of correctly labeled pixel for a specific type
std::vector< double > _prob_correct_v
Probability of getting the right pixel value in the whole image for a specific type.
Detailed Description
Definition at line 26 of file SegImageAna.h.
Constructor & Destructor Documentation
SegImageAna()
larcv::SegImageAna::SegImageAna (const std::string name = "SegImageAna")
Default constructor.
Definition at line 12 of file SegImageAna.cxx.
Referenced by larcv::SegImageAnaProcessFactory::create().
     : ProcessBase(name)
   {}
~SegImageAna()
larcv::SegImageAna::~SegImageAna () inline
Default destructor.
Definition at line 34 of file SegImageAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SegImageAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file SegImageAna.cxx.
References _image_channel, _image_producer, _label_channel, _label_producer, _ntypes, _pi_thresh, _roi_producer, _roitype_to_class, _segment_producer, larcv::PSet::get(), larcv::kINVALID_SIZE, larcv::kROITypeMax, larcv::kROIUnknown, and LARCV_CRITICAL.
Referenced by ~SegImageAna().
   {
     _image_producer   = cfg.get<std::string>("ImageProducer");
     _label_producer   = cfg.get<std::string>("LabelProducer");
     _segment_producer = cfg.get<std::string>("SegmentProducer");
     _roi_producer = cfg.get<std::string>("ROIProducer");
     _image_channel = cfg.get<size_t>("ImageChannel");
     _label_channel = cfg.get<size_t>("LabelChannel");
     _pi_thresh     = cfg.get<double>("PIThreshold");
     auto type_def = cfg.get<std::vector<unsigned short> >("ClassTypeDef");
     if (type_def.size() != kROITypeMax) {
       LARCV_CRITICAL() << "ClassTypeDef length is " << type_def.size()
                        << " but it needs to be length kROITypeMax (" << kROITypeMax << ")!" << std::endl;
       throw larbys();
     }
     for (auto const& v : type_def) {
       if (v >= kROITypeMax) {
         LARCV_CRITICAL() << "ClassTypeDef contains invalid value (" << v << ") for ROIType_t!" << std::endl;
         throw larbys();
       }
     }
     auto type_to_class = cfg.get<std::vector<unsigned short> >("ClassTypeList");
     if (type_to_class.empty()) {
       LARCV_CRITICAL() << "ClassTypeList needed to define classes!" << std::endl;
       throw larbys();
     }
     _roitype_to_class.clear();
     _ntypes = type_to_class.size() + 1;
     _roitype_to_class.resize(kROITypeMax, kINVALID_SIZE);
     _roitype_to_class[larcv::kROIUnknown] = 0;
     for (size_t i = 0; i < type_to_class.size(); ++i) {
       auto const& type = type_to_class[i];
       if (type >= kROITypeMax) {
         LARCV_CRITICAL() << "ClassTypeList contains type " << type << " which is not a valid ROIType_t!" << std::endl;
         throw larbys();
       }
       _roitype_to_class[type] = i + 1;
     }
     for (size_t i = 0; i < _roitype_to_class.size(); ++i) {
       if (_roitype_to_class[i] != kINVALID_SIZE) continue;
       _roitype_to_class[i] = _roitype_to_class[type_def[i]];
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SegImageAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 210 of file SegImageAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~SegImageAna().
   {
     if ( has_ana_file() ) { _tree->Write(); }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SegImageAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 66 of file SegImageAna.cxx.
References _npx_correct, _npx_correct_v, _npx_predicted_v, _npx_thresh, _npx_total, _npx_total_v, _ntypes, _pi_thresh, _prob_correct, _prob_correct_v, _roi_type, and _tree.
Referenced by ~SegImageAna().
   {
     _npx_total_v.clear     ();  _npx_total_v.resize     (_ntypes, 0.);
     _npx_predicted_v.clear ();  _npx_predicted_v.resize (_ntypes, 0.);
     _npx_correct_v.clear   ();  _npx_correct_v.resize   (_ntypes, 0.);
     _prob_correct_v.clear  ();  _prob_correct_v.resize  (_ntypes, 0.);
     _tree = new TTree("segtree","");
     _tree->Branch("pi_thresh",      &_pi_thresh,    "pi_thresh/D"    );
     _tree->Branch("npx_thresh",     &_npx_thresh,   "npx_thresh/i"   );
     _tree->Branch("npx_total",      &_npx_total,    "npx_total/i"    );
     _tree->Branch("npx_correct",    &_npx_correct,  "npx_correct/i"  );
     _tree->Branch("roi_type",       &_roi_type,     "roi_type/i"     );
     _tree->Branch("prob_correct",   &_prob_correct, "prob_correct/D" );
     _tree->Branch("npx_total_v",    &_npx_total_v    );
     _tree->Branch("npx_predicted_v",&_npx_predicted_v);
     _tree->Branch("npx_correct_v",  &_npx_correct_v  );
     _tree->Branch("prob_correct_v", &_prob_correct_v );
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SegImageAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 87 of file SegImageAna.cxx.
References _image_channel, _image_producer, _label_channel, _label_producer, _npx_correct, _npx_correct_v, _npx_predicted_v, _npx_thresh, _npx_total, _npx_total_v, _ntypes, _pi_thresh, _prob_correct, _prob_correct_v, _roi_producer, _roi_type, _roitype_to_class, _segment_producer, _tree, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, and LARCV_CRITICAL.
Referenced by ~SegImageAna().
   {
     auto event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_image_producer));
     auto event_label = (EventImage2D*)(mgr.get_data(kProductImage2D,_label_producer));
     auto event_segment = (EventImage2D*)(mgr.get_data(kProductImage2D,_segment_producer));
     auto event_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_producer));
     _roi_type = (int)(event_roi->ROIArray()[1].Type());
     if(!event_image) {
       LARCV_CRITICAL() << "Image by " << _image_producer << " not found..." << std::endl;
       throw larbys();
     }else if(event_image->Image2DArray().size() <= _image_channel) {
       LARCV_CRITICAL() << "Image by " << _image_producer
       << " has length " << event_image->Image2DArray().size()
       << " ... too short for requesting a channel " << _image_channel << std::endl;
       throw larbys();
     }
     if(!event_label) {
       LARCV_CRITICAL() << "Label Image by " << _label_producer << " not found..." << std::endl;
       throw larbys();
     }else if(event_label->Image2DArray().size() <= _label_channel) {
       LARCV_CRITICAL() << "Label image by " << _label_producer
       << " has length " << event_label->Image2DArray().size()
       << " ... too short for requesting a channel " << _label_channel << std::endl;
       throw larbys();
     }
     if(!event_segment) {
       LARCV_CRITICAL() << "Segment image by " << _segment_producer << " not found..." << std::endl;
       throw larbys();
     }else if(event_segment->Image2DArray().size() != _ntypes) {
       LARCV_CRITICAL() << "Segment image by " << _segment_producer
       << " has length " << event_segment->Image2DArray().size()
       << " ... not same size as specified # of channels " << _ntypes << std::endl;
       throw larbys();
     }
     // Get input image
     auto const& image = event_image->Image2DArray()[_image_channel].as_vector();
     auto const& label = event_label->Image2DArray()[_label_channel].as_vector();
     auto const& segment_v = event_segment->Image2DArray();
     if(image.size()!=label.size()) {
       LARCV_CRITICAL() << "Image and label dimension is different!" << std::endl;
       throw larbys();
     }
     for(auto const& seg : event_segment->Image2DArray()) {
       if(seg.as_vector().size() != image.size()) {
         LARCV_CRITICAL() << "Found a segment image which dimension is not same as input image!" << std::endl;
         throw larbys();
       }
     }
     // Loop over pixels to perform analysis
     _npx_thresh   = 0;
     _npx_total    = 0;
     _npx_correct  = 0;
     _prob_correct = 0;
     for(auto& v : _npx_total_v     ) v = 0;
     for(auto& v : _npx_predicted_v ) v = 0;
     for(auto& v : _npx_correct_v   ) v = 0;
     for(auto& v : _prob_correct_v  ) v = 0;
     for(size_t i=0; i<image.size(); ++i) {
       ++_npx_total;
       // If below PI threshold, ignore
       if(image[i] < _pi_thresh) continue;
       ++_npx_thresh;
       // Get the correct label
       auto const& truth_type = _roitype_to_class[(size_t)(label[i])];
       // Increment count for the truth label type
       _npx_total_v[truth_type] += 1;
       // Find the prediction
       size_t prediction_type =   0;
       float prediction_max   = -1.;
       float prediction_sum   =  0.;
       float prob     =  0.;
       for(size_t type_index = 0; type_index < _ntypes; ++type_index) {
         float score = std::exp( segment_v[type_index].as_vector()[i] );
         prediction_sum += score;
         if(truth_type == type_index) prob = score;
         if(score > prediction_max) {
           prediction_max = score;
           prediction_type = type_index;
         }
       }
       prob /= prediction_sum;             //softmax per pixel (across classes)
       prediction_max /= prediction_sum;   //max softmax score per pixel (across classes)
       // Increment a counter for a predicted type
       _npx_predicted_v[prediction_type] += 1;
       // Increment a counter for a correct prediction
       if(prediction_type == truth_type) {
         _npx_correct += 1;
         _npx_correct_v[prediction_type] += 1;
       }
       // Increment correct probability overall
       _prob_correct += prob;
       // Increment correct probability of truth label type
       _prob_correct_v[truth_type] += prob;
     }
     //normalize probability
     if ( _npx_thresh > 0 )
       _prob_correct /= (float)(_npx_thresh);
     else
       _prob_correct = 0;
     for(size_t type=0; type<_ntypes; ++type)  {
     if (_npx_total_v[type] > 0 )
       _prob_correct_v[type] /= (float)(_npx_total_v[type]);
     else
       _prob_correct_v[type] = 0.0;
       }
     _tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_image_channel
size_t larcv::SegImageAna::_image_channel private
Which channel to use from input Image2D (assuming 1 channel)
Definition at line 51 of file SegImageAna.h.
Referenced by configure(), and process().
_image_producer
std::string larcv::SegImageAna::_image_producer private
Input Image2D producer name.
Definition at line 46 of file SegImageAna.h.
Referenced by configure(), and process().
_label_channel
size_t larcv::SegImageAna::_label_channel private
Which channel to use from input label Image2D (assuming 1 channel)
Definition at line 52 of file SegImageAna.h.
Referenced by configure(), and process().
_label_producer
std::string larcv::SegImageAna::_label_producer private
Segmentation ground-truth (label) Image2D producer name.
Definition at line 47 of file SegImageAna.h.
Referenced by configure(), and process().
_npx_correct
int larcv::SegImageAna::_npx_correct private
pixels where prediction got it right
Definition at line 60 of file SegImageAna.h.
Referenced by initialize(), and process().
_npx_correct_v
std::vector<int> larcv::SegImageAna::_npx_correct_v private
of correctly labeled pixel for a specific type
Definition at line 66 of file SegImageAna.h.
Referenced by initialize(), and process().
_npx_predicted_v
std::vector<int> larcv::SegImageAna::_npx_predicted_v private
of predicted pixel for a specific type
Definition at line 65 of file SegImageAna.h.
Referenced by initialize(), and process().
_npx_thresh
int larcv::SegImageAna::_npx_thresh private
pixels above PI threshold
Definition at line 58 of file SegImageAna.h.
Referenced by initialize(), and process().
_npx_total
int larcv::SegImageAna::_npx_total private
pixels total
Definition at line 59 of file SegImageAna.h.
Referenced by initialize(), and process().
_npx_total_v
std::vector<int> larcv::SegImageAna::_npx_total_v private
of total pixel for a specific type (based on ground truth)
Definition at line 64 of file SegImageAna.h.
Referenced by initialize(), and process().
_ntypes
size_t larcv::SegImageAna::_ntypes private
Number of unique classes used by caffe.
Definition at line 54 of file SegImageAna.h.
Referenced by configure(), initialize(), and process().
_pi_thresh
double larcv::SegImageAna::_pi_thresh private
Pixel Intensity (PI) threshold value to filter out pixels we do not care.
Definition at line 57 of file SegImageAna.h.
Referenced by configure(), initialize(), and process().
_prob_correct
double larcv::SegImageAna::_prob_correct private
Probability of getting the right pixel value in the whole image.
Definition at line 63 of file SegImageAna.h.
Referenced by initialize(), and process().
_prob_correct_v
std::vector<double> larcv::SegImageAna::_prob_correct_v private
Probability of getting the right pixel value in the whole image for a specific type.
Definition at line 67 of file SegImageAna.h.
Referenced by initialize(), and process().
_roi_producer
std::string larcv::SegImageAna::_roi_producer private
Some MCTruth info might be interesting.
Definition at line 49 of file SegImageAna.h.
Referenced by configure(), and process().
_roi_type
int larcv::SegImageAna::_roi_type private
enum for ROIType
Definition at line 61 of file SegImageAna.h.
Referenced by initialize(), and process().
_roitype_to_class
std::vector<size_t> larcv::SegImageAna::_roitype_to_class private
Attribute to convert ROIType_t to class type defined by caffe.
Definition at line 53 of file SegImageAna.h.
Referenced by configure(), and process().
_segment_producer
std::string larcv::SegImageAna::_segment_producer private
Segmentation prediction (by CNN) Image2D producer name.
Definition at line 48 of file SegImageAna.h.
Referenced by configure(), and process().
_tree
TTree* larcv::SegImageAna::_tree private
Output analysis tree.
Definition at line 56 of file SegImageAna.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
SegImageAna.h
SegImageAna.cxx