LArCV: larcv::hires::HiResImageDividerProcessFactory Class Reference
larcv::hires::HiResImageDividerProcessFactory Class Reference
#include <HiResImageDivider.h>
Public Member Functions
HiResImageDividerProcessFactory ()
ctor
~HiResImageDividerProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 118 of file HiResImageDivider.h.
Constructor & Destructor Documentation
HiResImageDividerProcessFactory()
larcv::hires::HiResImageDividerProcessFactory::HiResImageDividerProcessFactory () inline
ctor
Definition at line 121 of file HiResImageDivider.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("HiResImageDivider",this); }
~HiResImageDividerProcessFactory()
larcv::hires::HiResImageDividerProcessFactory::~HiResImageDividerProcessFactory () inline
dtor
Definition at line 123 of file HiResImageDivider.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::hires::HiResImageDividerProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 125 of file HiResImageDivider.h.
References larcv::hires::HiResImageDivider::HiResImageDivider().
 { return new HiResImageDivider(instance_name); }
The documentation for this class was generated from the following file:
HiResImageDivider.h