LArCV: larcv::SuperaMCPCluster Class Reference
larcv::SuperaMCPCluster Class Reference
#include <SuperaMCPCluster.h>
Public Member Functions
SuperaMCPCluster (const std::string name="SuperaMCPCluster")
Default constructor.
~SuperaMCPCluster ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
bool StoreG4SecondaryROI () const
bool StoreG4PrimaryROI () const
const std::vector< std::pair< size_t, size_t > > & ROI2MCNode (int roi_index) const
const std::vector< std::vector< std::pair< size_t, size_t > > > & ROI2MCNode () const
const supera::MCParticleTree & ParticleTree () const
virtual bool is (const std::string question) const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
template<class T >
const std::vector< T > & LArData () const
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
const std::string & LArDataLabel (supera::LArDataType_t type) const
int TimeOffset () const
void ClearEventData ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
const std::string & OutROILabel () const
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
ImageMetaMakerBase * MetaMakerPtr ()
const std::string & OutPixel2DLabel () const
Detailed Description
Definition at line 26 of file SuperaMCPCluster.h.
Constructor & Destructor Documentation
SuperaMCPCluster()
larcv::SuperaMCPCluster::SuperaMCPCluster (const std::string name = "SuperaMCPCluster")
Default constructor.
Definition at line 13 of file SuperaMCPCluster.cxx.
Referenced by larcv::SuperaMCPClusterProcessFactory::create().
     : SuperaMCROI(name)
   {}
~SuperaMCPCluster()
larcv::SuperaMCPCluster::~SuperaMCPCluster () inline
Default destructor.
Definition at line 35 of file SuperaMCPCluster.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData () inherited
Definition at line 89 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v, larcv::SuperaBase::_ptr_mcs_v, larcv::SuperaBase::_ptr_mct_v, larcv::SuperaBase::_ptr_mctruth_v, larcv::SuperaBase::_ptr_opdigit_v, larcv::SuperaBase::_ptr_sch_v, and larcv::SuperaBase::_ptr_wire_v.
Referenced by larcv::SuperaBase::finalize(), larcv::SuperaBase::initialize(), larcv::SuperaMetaMaker::process(), larcv::SuperaBase::SuperaBase(), and larcv::SuperaBase::TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
ColCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::ColCompressionFactor () const inherited
Definition at line 36 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::ColCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->ColCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->ColCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
configure()
void larcv::SuperaMCPCluster::configure (const PSet & cfg) virtual
Reimplemented from supera::ImageMetaMaker.
Definition at line 17 of file SuperaMCPCluster.cxx.
References supera::ParamsPixel2D::configure(), and larcv::SuperaMCROI::configure().
Referenced by ~SuperaMCPCluster().
   {
     SuperaMCROI::configure(cfg);
     supera::ParamsPixel2D::configure(cfg);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SuperaMCPCluster::finalize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 138 of file SuperaMCPCluster.cxx.
References larcv::SuperaMCROI::finalize().
Referenced by ~SuperaMCPCluster().
   { SuperaMCROI::finalize(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaMCPCluster::initialize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 23 of file SuperaMCPCluster.cxx.
References larcv::SuperaMCROI::initialize().
Referenced by ~SuperaMCPCluster().
   { SuperaMCROI::initialize(); }
is()
bool larcv::SuperaBase::is (const std::string question) const virtual inherited
Reimplemented from larcv::ProcessBase.
Reimplemented in larcv::SuperaChStatus.
Definition at line 83 of file SuperaBase.cxx.
Referenced by larcv::SuperaBase::~SuperaBase().
   {
     if(question == "Supera") return true;
     return false;
   }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &) inherited
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const inherited
Referenced by larcv::SuperaBase::~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const inherited
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const inherited
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const inherited
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const inherited
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const inherited
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v) inherited
Definition at line 121 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v) inherited
Definition at line 124 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v) inherited
Definition at line 127 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v) inherited
Definition at line 130 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v) inherited
Definition at line 133 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v) inherited
Definition at line 136 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v) inherited
Definition at line 139 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const inherited
Definition at line 18 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::SuperaBase::_empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), larcv::SuperaMCROI::process(), and larcv::SuperaBase::~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Meta()
const std::vector< larcv::ImageMeta > & supera::ImageMetaMaker::Meta () const inherited
Definition at line 16 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::Meta(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCROI::MakeROI(), process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
   {
     if(_meta_maker) return _meta_maker->Meta();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->Meta();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
MetaMakerPtr()
ImageMetaMakerBase* supera::ImageMetaMaker::MetaMakerPtr () inline inherited
Definition at line 51 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker.
Referenced by larcv::SuperaOpDigit::configure(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
     { return _meta_maker; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OutPixel2DLabel()
const std::string& supera::ParamsPixel2D::OutPixel2DLabel () const inline inherited
Definition at line 41 of file ParamsPixel2D.h.
References supera::ParamsPixel2D::_out_pixel2d_producer.
Referenced by process(), and larcv::SuperaKeyPointCluster::process().
 { return _out_pixel2d_producer;  }
OutROILabel()
const std::string& supera::ParamsROI::OutROILabel () const inline inherited
Definition at line 41 of file ParamsROI.h.
References supera::ParamsROI::_out_roi_producer.
Referenced by process(), and larcv::SuperaMCROI::process().
 { return _out_roi_producer;      }
ParticleTree()
const supera::MCParticleTree& larcv::SuperaMCROI::ParticleTree () const inline inherited
Definition at line 61 of file SuperaMCROI.h.
References larcv::SuperaMCROI::_mcpt.
Referenced by process().
 { return _mcpt; }
process()
bool larcv::SuperaMCPCluster::process (IOManager & mgr) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 26 of file SuperaMCPCluster.cxx.
References supera::ImageMetaMaker::ColCompressionFactor(), larcv::IOManager< T >::get_data(), larcv::kINVALID_SIZE, larcv::kINVALID_UINT, supera::MCNode::kMCShower, supera::MCNode::kMCTruth, larcv::kProductPixel2D, larcv::kProductROI, LARCV_CRITICAL, supera::ImageMetaMaker::Meta(), larcv::supera::Nplanes(), supera::ParamsPixel2D::OutPixel2DLabel(), supera::ParamsROI::OutROILabel(), larcv::SuperaMCROI::ParticleTree(), larcv::SuperaMCROI::process(), larcv::SuperaMCROI::ROI2MCNode(), supera::ImageMetaMaker::RowCompressionFactor(), supera::SimCh2Pixel2DCluster(), and larcv::SuperaBase::TimeOffset().
Referenced by ~SuperaMCPCluster().
   {
     SuperaMCROI::process(mgr);
     auto ev_pixel2d = (EventPixel2D*)(mgr.get_data(kProductPixel2D,OutPixel2DLabel()));
     if(!ev_pixel2d) {
       LARCV_CRITICAL() << "Failed to create an output pixel2d w/ label " << OutPixel2DLabel() << std::endl;
       throw larbys();
     }
     auto ev_roi = (EventROI*)(mgr.get_data(kProductROI,OutROILabel()));
     if(!ev_roi) {
       LARCV_CRITICAL() << "Failed to fetch ROI (needs to be created) by " << OutROILabel() << std::endl;
       throw larbys();
     }
     std::vector<size_t> trackid2cluster;
     auto const& roi2mcnode_vv = ROI2MCNode();
     auto const& primary_v = ParticleTree().PrimaryArray();
     // check ROI length
     if(ev_roi->ROIArray().size() != roi2mcnode_vv.size()) {
       LARCV_CRITICAL() << "ROI2MCNode() return length not same as EventROI!" << std::endl;
       throw larbys();
     }
     auto const& mcshower_v = LArData<supera::LArMCShower_t>();
     for(size_t roi_idx=0; roi_idx<roi2mcnode_vv.size(); ++roi_idx) {
       auto const& roi2mcnode_v = roi2mcnode_vv[roi_idx];
       for(auto const& mcnode_info : roi2mcnode_v) {
     auto const& primary_idx = mcnode_info.first;
     auto const& secondary_idx = mcnode_info.second;
     auto const& primary = primary_v[primary_idx];
     // if this is secondary
     if(secondary_idx != larcv::kINVALID_SIZE) {
       auto const& node = primary.daughter_v[secondary_idx];
       if(trackid2cluster.size() <= node.track_id)
         trackid2cluster.resize(node.track_id+1,larcv::kINVALID_SIZE);
       trackid2cluster[node.track_id] = roi_idx;
       // if this is mcshower
       if(node.source_type == supera::MCNode::SourceType_t::kMCShower) {
         auto const& mcshower = mcshower_v.at(node.source_index);
         for(auto const& daughter_track_id : mcshower.DaughterTrackID()) {
           if(daughter_track_id == larcv::kINVALID_UINT) continue;
           if(trackid2cluster.size() <= daughter_track_id)
         trackid2cluster.resize(daughter_track_id+1,larcv::kINVALID_SIZE);
           trackid2cluster[daughter_track_id] = roi_idx;
         }
       }
       continue;
     }
     // if primary but mctruth
     if(primary.source_type == supera::MCNode::SourceType_t::kMCTruth)
       continue;
     // if primary and not mctruth
     if(trackid2cluster.size() <= primary.track_id)
       trackid2cluster.resize(primary.track_id+1);
     trackid2cluster[primary.track_id] = roi_idx;
     if(primary.source_type == supera::MCNode::SourceType_t::kMCShower) {
       auto const& mcshower = mcshower_v.at(primary.source_index);
       for(auto const& daughter_track_id : mcshower.DaughterTrackID()) {
         if(daughter_track_id == larcv::kINVALID_UINT) continue;
         if(trackid2cluster.size() <= daughter_track_id)
           trackid2cluster.resize(daughter_track_id+1,larcv::kINVALID_SIZE);
         trackid2cluster[daughter_track_id] = roi_idx;
       }
     }
       }
     }
     auto pxcluster_vv = supera::SimCh2Pixel2DCluster(Meta(),
                              RowCompressionFactor(),
                              ColCompressionFactor(),
                              LArData<supera::LArSimCh_t>(),
                              trackid2cluster,
                              TimeOffset());
     auto const& roi_v = ev_roi->ROIArray();
     if(roi_v.size() != pxcluster_vv.size()) {
       LARCV_CRITICAL() << "# PixelCluster does not match with # ROI!" << std::endl;
       throw larbys();
     }
     auto meta_v = Meta();
     for(auto& meta: meta_v) meta.update(meta.rows() / RowCompressionFactor().at(meta.plane()),
                     meta.cols() / ColCompressionFactor().at(meta.plane()));
     for(size_t roi_idx=0; roi_idx<roi_v.size(); ++roi_idx) {
       auto const& pc_v = pxcluster_vv.at(roi_idx);
       if(pc_v.size() != supera::Nplanes()) {
     LARCV_CRITICAL() << "# pixel cluster not same as # planes!" << std::endl;
     throw larbys();
       }
       for(size_t plane=0; plane<supera::Nplanes(); ++plane)
     ev_pixel2d->Emplace(plane, std::move(pxcluster_vv[roi_idx][plane]), meta_v.at(plane));
     }
     return true;
   }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name) inherited
Definition at line 15 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::larcv_base::name().
Referenced by larcv::SuperaBase::configure(), and larcv::SuperaBase::~SuperaBase().
   { _data_request_m[type]=name; }
ROI2MCNode() [1/2]
const std::vector< std::pair< size_t, size_t > > & larcv::SuperaMCROI::ROI2MCNode (int roi_index) const inherited
Definition at line 18 of file SuperaMCROI.cxx.
References larcv::SuperaMCROI::_roi2mcnode_vv.
   {
     if(roi_index >= (int)(_roi2mcnode_vv.size()))
       throw larbys("Invalid ROI index requested");
     return _roi2mcnode_vv[roi_index];
   }
ROI2MCNode() [2/2]
const std::vector<std::vector<std::pair<size_t,size_t> > >& larcv::SuperaMCROI::ROI2MCNode () const inline inherited
Definition at line 59 of file SuperaMCROI.h.
References larcv::SuperaMCROI::_roi2mcnode_vv.
Referenced by process(), and larcv::SuperaMCROI::StoreG4PrimaryROI().
 { return _roi2mcnode_vv; }
RowCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::RowCompressionFactor () const inherited
Definition at line 26 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::RowCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->RowCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->RowCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
StoreG4PrimaryROI()
bool larcv::SuperaMCROI::StoreG4PrimaryROI () const inline inherited
Definition at line 54 of file SuperaMCROI.h.
References larcv::SuperaMCROI::_store_g4_primary_roi, and larcv::SuperaMCROI::ROI2MCNode().
 { return _store_g4_primary_roi; }
StoreG4SecondaryROI()
bool larcv::SuperaMCROI::StoreG4SecondaryROI () const inline inherited
Definition at line 52 of file SuperaMCROI.h.
References larcv::SuperaMCROI::_store_g4_secondary_roi.
 { return _store_g4_secondary_roi; }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline inherited
Definition at line 64 of file SuperaBase.h.
References larcv::SuperaBase::_time_offset, and larcv::SuperaBase::ClearEventData().
Referenced by larcv::SuperaMCROI::MakeROI(), process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
 { return _time_offset; }
The documentation for this class was generated from the following files:
SuperaMCPCluster.h
SuperaMCPCluster.cxx