LArCV: larcv::LEE1e1pAna Class Reference
larcv::LEE1e1pAna Class Reference
#include <LEE1e1pAna.h>
Public Member Functions
LEE1e1pAna (const std::string name="LEE1e1pAna")
Default constructor.
~LEE1e1pAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void ClearEvent ()
void ClearVertex ()
Private Attributes
TTree * _tree
int _entry
int _run
int _subrun
int _event
int _roid
int _vtxid
std::vector< double > _score0
std::vector< double > _score1
int _shape0
int _shape1
double _score_shower0
double _score_shower1
double _score_track0
double _score_track1
double _score0_e
double _score0_g
double _score0_pi
double _score0_mu
double _score0_p
double _score1_e
double _score1_g
double _score1_pi
double _score1_mu
double _score1_p
int _npx0
int _npx1
double _q0
double _q1
double _area0
double _area1
double _len0
double _len1
int _nprotons
int _nothers
std::string _img2d_prod
std::string _pgraph_prod
std::string _pcluster_ctor_prod
std::string _pcluster_img_prod
std::string _truth_roi_prod
std::string _reco_roi_prod
Detailed Description
Definition at line 14 of file LEE1e1pAna.h.
Constructor & Destructor Documentation
LEE1e1pAna()
larcv::LEE1e1pAna::LEE1e1pAna (const std::string name = "LEE1e1pAna")
Default constructor.
Definition at line 19 of file LEE1e1pAna.cxx.
Referenced by larcv::LEE1e1pAnaProcessFactory::create().
     : ProcessBase(name)
   {}
~LEE1e1pAna()
larcv::LEE1e1pAna::~LEE1e1pAna () inline
Default destructor.
Definition at line 22 of file LEE1e1pAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEvent()
void larcv::LEE1e1pAna::ClearEvent () private
Definition at line 246 of file LEE1e1pAna.cxx.
References _nothers, _nprotons, _vtxid, ClearVertex(), and larcv::kINVALID_INT.
Referenced by process().
{
     _vtxid = kINVALID_INT;
     _nprotons = kINVALID_INT;
     _nothers = kINVALID_INT;
     ClearVertex();
   }
ClearVertex()
void larcv::LEE1e1pAna::ClearVertex () private
Definition at line 255 of file LEE1e1pAna.cxx.
References _area0, _area1, _len0, _len1, _npx0, _npx1, _q0, _q1, _shape0, _shape1, larcv::kINVALID_DOUBLE, and larcv::kINVALID_INT.
Referenced by ClearEvent(), and process().
{
     _shape0 = kINVALID_INT;
     _shape1 = kINVALID_INT;
     _npx0 = kINVALID_INT;
     _npx1 = kINVALID_INT;
     _q0 = kINVALID_DOUBLE;
     _q1 = kINVALID_DOUBLE;
     _area0 = kINVALID_DOUBLE;
     _area1 = kINVALID_DOUBLE;
     _len0 = kINVALID_DOUBLE;
     _len1 = kINVALID_DOUBLE;
   }
configure()
void larcv::LEE1e1pAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 23 of file LEE1e1pAna.cxx.
References _img2d_prod, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _reco_roi_prod, _truth_roi_prod, larcv::PSet::get(), and LARCV_DEBUG.
Referenced by ~LEE1e1pAna().
   {
     _img2d_prod         = cfg.get<std::string>("Image2DProducer");
     _pgraph_prod        = cfg.get<std::string>("PGraphProducer");
     _pcluster_ctor_prod = cfg.get<std::string>("PxContourProducer");
     _pcluster_img_prod  = cfg.get<std::string>("PxImageProducer");
     _truth_roi_prod     = cfg.get<std::string>("TrueROIProducer");
     _reco_roi_prod      = cfg.get<std::string>("RecoROIProducer");
     LARCV_DEBUG() << "Image2DProducer:  " << _img2d_prod << std::endl;
     LARCV_DEBUG() << "PGraphProducer:   " << _pgraph_prod << std::endl;
     LARCV_DEBUG() << "PxContourProducer: " << _pcluster_ctor_prod << std::endl;
     LARCV_DEBUG() << "PxImageProducer:  " << _pcluster_img_prod << std::endl;
     LARCV_DEBUG() << "TrueROIProducer:  " << _truth_roi_prod << std::endl;
     LARCV_DEBUG() << "RecoROIProducer:  " << _reco_roi_prod << std::endl;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LEE1e1pAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 273 of file LEE1e1pAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~LEE1e1pAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LEE1e1pAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 41 of file LEE1e1pAna.cxx.
References _area0, _area1, _entry, _event, _len0, _len1, _nothers, _nprotons, _npx0, _npx1, _q0, _q1, _roid, _run, _shape0, _shape1, _subrun, _tree, and _vtxid.
Referenced by ~LEE1e1pAna().
   {
     _tree = new TTree("LEE1e1pTree","");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("roid",&_roid,"roid/I");
     _tree->Branch("vtxid",&_vtxid,"vtxid/I");
     _tree->Branch("shape0",&_shape0,"shape0/I");
     _tree->Branch("shape1",&_shape1,"shape1/I");
     _tree->Branch("q0",&_q0,"q0/D");
     _tree->Branch("q1",&_q1,"q1/D");
     _tree->Branch("npx0",&_npx0,"npx0/I");
     _tree->Branch("npx1",&_npx1,"npx1/I");
     _tree->Branch("nprotons",&_nprotons,"nprotons/I");
     _tree->Branch("nothers", &_nothers,   "nothers/I");
     _tree->Branch("area0",&_area0,"area0/D");
     _tree->Branch("area1",&_area1,"area1/D");
     _tree->Branch("len0",&_len0,"len0/D");
     _tree->Branch("len1",&_len1,"len1/D");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::LEE1e1pAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 71 of file LEE1e1pAna.cxx.
References _area0, _area1, _entry, _event, _img2d_prod, _len0, _len1, _nothers, _nprotons, _npx0, _npx1, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _q0, _q1, _reco_roi_prod, _roid, _run, _shape0, _shape1, _subrun, _tree, _truth_roi_prod, _vtxid, ClearEvent(), ClearVertex(), larcv::crop_metas(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, LARCV_CRITICAL, LARCV_DEBUG, and larcv::EventROI::ROIArray().
Referenced by ~LEE1e1pAna().
   {
     auto const ev_img2d = (EventImage2D*)(mgr.get_data(kProductImage2D,_img2d_prod));
     if (!ev_img2d) throw larbys("Invalid image producer provided");
     auto const ev_pgraph = (EventPGraph*)(mgr.get_data(kProductPGraph,_pgraph_prod));
     if (!ev_pgraph) throw larbys("Invalid pgraph producer provided!");
     auto const ev_ctor_v = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pcluster_ctor_prod));
     if (!ev_ctor_v) throw larbys("Invalid Contour Pixel2D producer provided!");
     auto const ev_pcluster_v = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pcluster_img_prod));
     if (!ev_pcluster_v) throw larbys("Invalid Particle Pixel2D producer provided!");
     EventROI* ev_roi_v = nullptr;
     if (!_truth_roi_prod.empty()) {
       ev_roi_v = (EventROI*)(mgr.get_data(kProductROI,_truth_roi_prod));
       if (!ev_roi_v) throw larbys("Invalid truth roi producer provided");
       if (ev_roi_v->ROIArray().empty()) throw larbys("Empty truth roi producer provided");
     }
     auto const ev_croi_v     = (EventROI*)(mgr.get_data(kProductROI,_reco_roi_prod));
     if (!ev_croi_v) throw larbys("Invalid cROI producer provided");
     ClearEvent();
     _run    = ev_img2d->run();
     _subrun = ev_img2d->subrun();
     _event  = ev_img2d->event();
     _entry  = mgr.current_entry();
     LARCV_DEBUG() << "Got RSEE=("<<_run<<","<<_subrun<<","<<_event<<","<<_entry<<")"<<std::endl;
     const auto& adc_img_v = ev_img2d->Image2DArray();
     std::vector<std::vector<ImageMeta> > roid_v;
     roid_v.reserve(ev_croi_v->ROIArray().size());
     for(auto const& croi : ev_croi_v->ROIArray()) {
       auto const& bb_v = croi.BB();
       roid_v.push_back(crop_metas(adc_img_v,bb_v));
     }
     _nprotons = 0;
     _nothers  = 0;
     auto const& ctor_m = ev_ctor_v->Pixel2DClusterArray();
     auto const& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
     std::vector<size_t> plane_order_v = {2,0,1};
     _vtxid = -1;
     auto vtx_counts = ev_pgraph->PGraphArray().size();
     LARCV_DEBUG() << "Got " << vtx_counts << " vertices" << std::endl;
     for (int vtx_idx = 0; vtx_idx < (int)vtx_counts; ++vtx_idx) {
       LARCV_DEBUG() << "@ vtx_idx=" << vtx_idx << std::endl;
       ClearVertex();
       _vtxid += 1;
       assert((size_t)vtx_idx < ev_pgraph->PGraphArray().size());
       auto pgraph = ev_pgraph->PGraphArray().at(vtx_idx);
       auto const& roi_v = pgraph.ParticleArray();
       auto const& bb_v = roi_v.front().BB();
       auto iter = std::find(roid_v.begin(),roid_v.end(),bb_v);
       if (iter == roid_v.end()) throw larbys("Unknown image meta");
       auto roid = iter - roid_v.begin();
       if (roid!=_roid) _vtxid = 0;
       _roid  = roid;
       auto const& cluster_idx_v = pgraph.ClusterIndexArray();
       LARCV_DEBUG() << "cluster index array size=" << cluster_idx_v.size() << std::endl;
       if (roi_v.size() < 2) {
     _tree->Fill();
     continue;
       }
       auto const& roi0 = roi_v.at(0);
       LARCV_DEBUG() << "got roi0@" << &roi0 << "..." << std::endl;
       auto const& roi1 = roi_v.at(1);
       LARCV_DEBUG() << "got roi1@" << &roi1 << "..." << std::endl;
       _shape0 = (int)(roi0.Shape());
       _shape1 = (int)(roi1.Shape());
       auto const& cluster_idx0 = cluster_idx_v.at(0);
       auto const& cluster_idx1 = cluster_idx_v.at(1);
       bool done0=false;
       bool done1=false;
       _npx0 = _npx1 = 0;
       _len0 = _len1 = _area0 = _area1 = 0.;
       _q0 = _q1 = 0.;
       for(auto const& plane : plane_order_v) {
     auto iter_pcluster = pcluster_m.find(plane);
     if(iter_pcluster == pcluster_m.end()) continue;
     auto iter_ctor = ctor_m.find(plane);
     if(iter_ctor == ctor_m.end()) continue;
     auto const& pcluster_v = (*iter_pcluster).second;
     auto const& ctor_v = (*iter_ctor).second;
     if (cluster_idx0 > pcluster_v.size()) {
       LARCV_CRITICAL() << "idx0 " << cluster_idx0 << " vs " << pcluster_v.size() << std::endl;
       throw larbys("die");
     }
     if (cluster_idx1 > pcluster_v.size()) {
       LARCV_CRITICAL() << "idx1 " << cluster_idx1 << " vs " << pcluster_v.size() << std::endl;
       throw larbys("die");
     }
     auto const& pcluster0 = pcluster_v.at(cluster_idx0);
     auto const& ctor0 = ctor_v.at(cluster_idx0);
     if(!done0 && ctor0.size()>2) {
       _npx0 = pcluster0.size();
       for(auto const& pt : pcluster0) _q0 += pt.Intensity();
       for(size_t i=1; i<ctor0.size(); ++i) {
         auto const& pt0 = ctor0.at(i-1);
         auto const& pt1 = ctor0.at(i);
         _len0 += sqrt(pow((float)(pt0.X()) - (float)(pt1.X()),2) + pow((float)(pt0.Y()) - (float)(pt1.Y()),2));
       }
       _len0 += sqrt(pow((float)(ctor0.front().X()) - (float)(ctor0.back().X()),2) +
             pow((float)(ctor0.front().Y()) - (float)(ctor0.back().Y()),2));
       larocv::GEO2D_Contour_t ctor;
       ctor.resize(ctor0.size());
       for(size_t i=0; i<ctor0.size(); ++i) {
         ctor.at(i).x = ctor0.at(i).X();
         ctor.at(i).y = ctor0.at(i).Y();
       }
       _area0 = larocv::ContourArea(ctor);
       done0 = true;
     }
     auto const& pcluster1 = pcluster_v.at(cluster_idx1);
     auto const& ctor1 = ctor_v.at(cluster_idx1);
     if(!done1 && ctor1.size()>2) {
       _npx1 = pcluster1.size();
       for(auto const& pt : pcluster1) _q1 += pt.Intensity();
       for(size_t i=1; i<ctor1.size(); ++i) {
         auto const& pt0 = ctor1[i-1];
         auto const& pt1 = ctor1.at(i);
         _len1 += sqrt(pow((float)(pt0.X()) - (float)(pt1.X()),2) + pow((float)(pt0.Y()) - (float)(pt1.Y()),2));
       }
       _len1 += sqrt(pow((float)(ctor1.front().X()) - (float)(ctor1.back().X()),2) +
             pow((float)(ctor1.front().Y()) - (float)(ctor1.back().Y()),2));
       larocv::GEO2D_Contour_t ctor;
       ctor.resize(ctor1.size());
       for(size_t i=0; i<ctor1.size(); ++i) {
         ctor.at(i).x = ctor1.at(i).X();
         ctor.at(i).y = ctor1.at(i).Y();
       }
       _area1 = larocv::ContourArea(ctor);
       done1 = true;
     }
     if(done0 && done1) break;
       }
       _tree->Fill();
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_area0
double larcv::LEE1e1pAna::_area0 private
Definition at line 73 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_area1
double larcv::LEE1e1pAna::_area1 private
Definition at line 74 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_entry
int larcv::LEE1e1pAna::_entry private
Definition at line 36 of file LEE1e1pAna.h.
Referenced by initialize(), and process().
_event
int larcv::LEE1e1pAna::_event private
Definition at line 39 of file LEE1e1pAna.h.
Referenced by initialize(), and process().
_img2d_prod
std::string larcv::LEE1e1pAna::_img2d_prod private
Definition at line 82 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_len0
double larcv::LEE1e1pAna::_len0 private
Definition at line 76 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_len1
double larcv::LEE1e1pAna::_len1 private
Definition at line 77 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_nothers
int larcv::LEE1e1pAna::_nothers private
Definition at line 80 of file LEE1e1pAna.h.
Referenced by ClearEvent(), initialize(), and process().
_nprotons
int larcv::LEE1e1pAna::_nprotons private
Definition at line 79 of file LEE1e1pAna.h.
Referenced by ClearEvent(), initialize(), and process().
_npx0
int larcv::LEE1e1pAna::_npx0 private
Definition at line 67 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_npx1
int larcv::LEE1e1pAna::_npx1 private
Definition at line 68 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_pcluster_ctor_prod
std::string larcv::LEE1e1pAna::_pcluster_ctor_prod private
Definition at line 84 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_pcluster_img_prod
std::string larcv::LEE1e1pAna::_pcluster_img_prod private
Definition at line 85 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_pgraph_prod
std::string larcv::LEE1e1pAna::_pgraph_prod private
Definition at line 83 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_q0
double larcv::LEE1e1pAna::_q0 private
Definition at line 70 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_q1
double larcv::LEE1e1pAna::_q1 private
Definition at line 71 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_reco_roi_prod
std::string larcv::LEE1e1pAna::_reco_roi_prod private
Definition at line 87 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_roid
int larcv::LEE1e1pAna::_roid private
Definition at line 40 of file LEE1e1pAna.h.
Referenced by initialize(), and process().
_run
int larcv::LEE1e1pAna::_run private
Definition at line 37 of file LEE1e1pAna.h.
Referenced by initialize(), and process().
_score0
std::vector<double> larcv::LEE1e1pAna::_score0 private
Definition at line 43 of file LEE1e1pAna.h.
_score0_e
double larcv::LEE1e1pAna::_score0_e private
Definition at line 55 of file LEE1e1pAna.h.
_score0_g
double larcv::LEE1e1pAna::_score0_g private
Definition at line 56 of file LEE1e1pAna.h.
_score0_mu
double larcv::LEE1e1pAna::_score0_mu private
Definition at line 58 of file LEE1e1pAna.h.
_score0_p
double larcv::LEE1e1pAna::_score0_p private
Definition at line 59 of file LEE1e1pAna.h.
_score0_pi
double larcv::LEE1e1pAna::_score0_pi private
Definition at line 57 of file LEE1e1pAna.h.
_score1
std::vector<double> larcv::LEE1e1pAna::_score1 private
Definition at line 44 of file LEE1e1pAna.h.
_score1_e
double larcv::LEE1e1pAna::_score1_e private
Definition at line 61 of file LEE1e1pAna.h.
_score1_g
double larcv::LEE1e1pAna::_score1_g private
Definition at line 62 of file LEE1e1pAna.h.
_score1_mu
double larcv::LEE1e1pAna::_score1_mu private
Definition at line 64 of file LEE1e1pAna.h.
_score1_p
double larcv::LEE1e1pAna::_score1_p private
Definition at line 65 of file LEE1e1pAna.h.
_score1_pi
double larcv::LEE1e1pAna::_score1_pi private
Definition at line 63 of file LEE1e1pAna.h.
_score_shower0
double larcv::LEE1e1pAna::_score_shower0 private
Definition at line 49 of file LEE1e1pAna.h.
_score_shower1
double larcv::LEE1e1pAna::_score_shower1 private
Definition at line 50 of file LEE1e1pAna.h.
_score_track0
double larcv::LEE1e1pAna::_score_track0 private
Definition at line 52 of file LEE1e1pAna.h.
_score_track1
double larcv::LEE1e1pAna::_score_track1 private
Definition at line 53 of file LEE1e1pAna.h.
_shape0
int larcv::LEE1e1pAna::_shape0 private
Definition at line 46 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_shape1
int larcv::LEE1e1pAna::_shape1 private
Definition at line 47 of file LEE1e1pAna.h.
Referenced by ClearVertex(), initialize(), and process().
_subrun
int larcv::LEE1e1pAna::_subrun private
Definition at line 38 of file LEE1e1pAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::LEE1e1pAna::_tree private
Definition at line 34 of file LEE1e1pAna.h.
Referenced by finalize(), initialize(), and process().
_truth_roi_prod
std::string larcv::LEE1e1pAna::_truth_roi_prod private
Definition at line 86 of file LEE1e1pAna.h.
Referenced by configure(), and process().
_vtxid
int larcv::LEE1e1pAna::_vtxid private
Definition at line 41 of file LEE1e1pAna.h.
Referenced by ClearEvent(), initialize(), and process().
The documentation for this class was generated from the following files:
LEE1e1pAna.h
LEE1e1pAna.cxx