LArCV: larcv::PreProcessorAna Class Reference
larcv::PreProcessorAna Class Reference
#include <PreProcessorAna.h>
Public Member Functions
PreProcessorAna (const std::string name="PreProcessorAna")
Default constructor.
~PreProcessorAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void Clear ()
Private Attributes
TTree * _out_tree
PreProcessor _PreProcessor
std::vector< float > _true_track_ctr_v
std::vector< float > _true_shower_ctr_v
std::vector< float > _ss_track_ctr_v
std::vector< float > _ss_shower_ctr_v
std::vector< float > _pss_track_ctr_v
std::vector< float > _pss_shower_ctr_v
std::vector< float > _ss_ratio_v
std::vector< float > _pss_ratio_v
Detailed Description
Definition at line 28 of file PreProcessorAna.h.
Constructor & Destructor Documentation
PreProcessorAna()
larcv::PreProcessorAna::PreProcessorAna (const std::string name = "PreProcessorAna")
Default constructor.
Definition at line 13 of file PreProcessorAna.cxx.
Referenced by larcv::PreProcessorAnaProcessFactory::create().
     : ProcessBase(name),
       _out_tree(nullptr)
   {}
~PreProcessorAna()
larcv::PreProcessorAna::~PreProcessorAna () inline
Default destructor.
Definition at line 36 of file PreProcessorAna.h.
References Clear(), configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
Clear()
void larcv::PreProcessorAna::Clear () private
Definition at line 42 of file PreProcessorAna.cxx.
References _pss_ratio_v, _pss_shower_ctr_v, _pss_track_ctr_v, _ss_ratio_v, _ss_shower_ctr_v, _ss_track_ctr_v, _true_shower_ctr_v, and _true_track_ctr_v.
Referenced by process(), and ~PreProcessorAna().
{
     _true_track_ctr_v.clear();
     _true_shower_ctr_v.clear();
     _ss_track_ctr_v.clear();
     _ss_shower_ctr_v.clear();
     _pss_track_ctr_v.clear();
     _pss_shower_ctr_v.clear();
     _ss_ratio_v.clear();
     _pss_ratio_v.clear();
     _true_track_ctr_v.resize(3);
     _true_shower_ctr_v.resize(3);
     _ss_track_ctr_v.resize(3);
     _ss_shower_ctr_v.resize(3);
     _pss_track_ctr_v.resize(3);
     _pss_shower_ctr_v.resize(3);
     _ss_ratio_v.resize(3);
     _pss_ratio_v.resize(3);
   }
configure()
void larcv::PreProcessorAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 18 of file PreProcessorAna.cxx.
References _PreProcessor, larcv::PreProcessor::Configure(), and larcv::PSet::get().
Referenced by ~PreProcessorAna().
   {
     _PreProcessor.Configure(cfg.get<larcv::PSet>("PreProcessor"));
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::PreProcessorAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 166 of file PreProcessorAna.cxx.
References _out_tree.
Referenced by ~PreProcessorAna().
   {
     _out_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::PreProcessorAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 23 of file PreProcessorAna.cxx.
References _out_tree, _pss_ratio_v, _pss_shower_ctr_v, _pss_track_ctr_v, _ss_ratio_v, _ss_shower_ctr_v, _ss_track_ctr_v, _true_shower_ctr_v, and _true_track_ctr_v.
Referenced by ~PreProcessorAna().
   {
     _out_tree = new TTree("ssana","");
     _out_tree->Branch("true_track_ctr_v",&_true_track_ctr_v);
     _out_tree->Branch("true_shower_ctr_v",&_true_shower_ctr_v);
     _out_tree->Branch("ss_track_ctr_v",&_ss_track_ctr_v);
     _out_tree->Branch("ss_shower_ctr_v",&_ss_shower_ctr_v);
     _out_tree->Branch("pss_track_ctr_v",&_pss_track_ctr_v);
     _out_tree->Branch("pss_shower_ctr_v",&_pss_shower_ctr_v);
     _out_tree->Branch("ss_ratio_v",&_ss_ratio_v);
     _out_tree->Branch("pss_ratio_v",&_pss_ratio_v);
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::PreProcessorAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 62 of file PreProcessorAna.cxx.
References _out_tree, _PreProcessor, _pss_ratio_v, _pss_shower_ctr_v, _pss_track_ctr_v, _ss_ratio_v, _ss_shower_ctr_v, _ss_track_ctr_v, _true_shower_ctr_v, _true_track_ctr_v, larcv::as_gray_mat(), Clear(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, and larcv::PreProcessor::PreProcess().
Referenced by ~PreProcessorAna().
   {
     // adc image
     const auto adc_ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,"tpc_hires_crop");
     std::vector<cv::Mat> adc_v;
     adc_v.reserve(3);
     for(const auto& adc_img2d : adc_ev_img->Image2DArray())
       adc_v.emplace_back(as_gray_mat(adc_img2d,0.1,500,2));
     // true track and ss shower
     const auto true_track_ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,"true_track_hires_crop");
     const auto true_shower_ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,"true_shower_hires_crop");
     std::vector<cv::Mat> true_track_v;
     std::vector<cv::Mat> true_shower_v;
     true_track_v.reserve(3);
     true_shower_v.reserve(3);
     for(const auto& true_track_img2d : true_track_ev_img->Image2DArray())
       true_track_v.emplace_back(as_gray_mat(true_track_img2d,0.1,500,2));
     for(const auto& true_shower_img2d : true_shower_ev_img->Image2DArray())
       true_shower_v.emplace_back(as_gray_mat(true_shower_img2d,0.1,500,2));
     // ss track and ss shower
     const auto ss_track_ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,"ss_track_hires_crop");
     const auto ss_shower_ev_img = (EventImage2D*)mgr.get_data(kProductImage2D,"ss_shower_hires_crop");
     std::vector<cv::Mat> ss_track_v,ss_shower_v;
     ss_track_v.reserve(3);
     ss_shower_v.reserve(3)
       ;
     for(const auto& ss_track_img2d : ss_track_ev_img->Image2DArray())
       ss_track_v.emplace_back(as_gray_mat(ss_track_img2d,0.1,500,2));
     for(const auto& ss_shower_img2d : ss_shower_ev_img->Image2DArray())
       ss_shower_v.emplace_back(as_gray_mat(ss_shower_img2d,0.1,500,2));
     Clear();
     for(size_t plane=0;plane<adc_v.size();++plane) {
       auto& adc_img = adc_v[plane];
       auto& ss_track_img = ss_track_v[plane];
       auto& ss_shower_img = ss_shower_v[plane];
       auto pss_track_img = ss_track_img.clone();
       auto pss_shower_img = ss_shower_img.clone();
       _PreProcessor.PreProcess(adc_img,pss_track_img,pss_shower_img);
       auto& true_track_img = true_track_v[plane];
       auto& true_shower_img = true_shower_v[plane];
       //binary images
       auto true_track_img_t = larocv::Threshold(true_track_img,10,1);
       auto true_shower_img_t = larocv::Threshold(true_shower_img,10,1);
       auto ss_track_img_t = larocv::Threshold(ss_track_img,10,1);
       auto ss_shower_img_t = larocv::Threshold(ss_shower_img,10,1);
       auto pss_track_img_t = larocv::Threshold(pss_track_img,10,1);
       auto pss_shower_img_t = larocv::Threshold(pss_shower_img,10,1);
       float true_track_ctr = cv::countNonZero(true_track_img_t);
       float true_shower_ctr = cv::countNonZero(true_shower_img_t);
       cv::Mat out;
       cv::bitwise_and(true_track_img_t,ss_track_img_t,out);
       float ss_track_ctr = cv::countNonZero(out);
       cv::bitwise_and(true_shower_img_t,ss_shower_img_t,out);
       float ss_shower_ctr = cv::countNonZero(out);
       cv::bitwise_and(true_track_img_t,pss_track_img_t,out);
       float pss_track_ctr = cv::countNonZero(out);
       cv::bitwise_and(true_shower_img_t,pss_shower_img_t,out);
       float pss_shower_ctr = cv::countNonZero(out);
       float ss_ratio = (ss_track_ctr+ss_shower_ctr)/(true_track_ctr+true_shower_ctr);
       float pss_ratio = (pss_track_ctr+pss_shower_ctr)/(true_track_ctr+true_shower_ctr);
       _true_track_ctr_v[plane]  = true_track_ctr;
       _true_shower_ctr_v[plane] = true_shower_ctr;
       _ss_track_ctr_v[plane] = ss_track_ctr;
       _ss_shower_ctr_v[plane] = ss_shower_ctr;
       _pss_track_ctr_v[plane] = pss_track_ctr;
       _pss_shower_ctr_v[plane] = pss_shower_ctr;
       _ss_ratio_v[plane] = ss_ratio;
       _pss_ratio_v[plane] = pss_ratio;
     }
     _out_tree->Fill();
     //Determine the correct fraction for this event
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_out_tree
TTree* larcv::PreProcessorAna::_out_tree private
Definition at line 49 of file PreProcessorAna.h.
Referenced by finalize(), initialize(), and process().
_PreProcessor
PreProcessor larcv::PreProcessorAna::_PreProcessor private
Definition at line 50 of file PreProcessorAna.h.
Referenced by configure(), and process().
_pss_ratio_v
std::vector<float> larcv::PreProcessorAna::_pss_ratio_v private
Definition at line 58 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_pss_shower_ctr_v
std::vector<float> larcv::PreProcessorAna::_pss_shower_ctr_v private
Definition at line 56 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_pss_track_ctr_v
std::vector<float> larcv::PreProcessorAna::_pss_track_ctr_v private
Definition at line 55 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_ss_ratio_v
std::vector<float> larcv::PreProcessorAna::_ss_ratio_v private
Definition at line 57 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_ss_shower_ctr_v
std::vector<float> larcv::PreProcessorAna::_ss_shower_ctr_v private
Definition at line 54 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_ss_track_ctr_v
std::vector<float> larcv::PreProcessorAna::_ss_track_ctr_v private
Definition at line 53 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_true_shower_ctr_v
std::vector<float> larcv::PreProcessorAna::_true_shower_ctr_v private
Definition at line 52 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
_true_track_ctr_v
std::vector<float> larcv::PreProcessorAna::_true_track_ctr_v private
Definition at line 51 of file PreProcessorAna.h.
Referenced by Clear(), initialize(), and process().
The documentation for this class was generated from the following files:
PreProcessorAna.h
PreProcessorAna.cxx