LArCV: larlite::Supera Class Reference
larlite::Supera Class Reference
User custom analysis class made by SHELL_USER_NAME.
#include <Supera.h>
Public Member Functions
Supera ()
Default constructor.
virtual ~Supera ()
Default destructor.
virtual bool initialize ()
IMPLEMENT in Supera.cc! Initialization method to be called before the analysis event loop.
virtual bool analyze (storage_manager *storage)
IMPLEMENT in Supera.cc! Analyze a data event-by-event.
virtual bool finalize ()
IMPLEMENT in Supera.cc! Finalize method to be called after all events processed.
void set_config (const std::string cfg_file)
void supera_fname (std::string name)
Protected Attributes
::larcv::supera::SuperaCore< larlite::opdetwaveform, larlite::wire, larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch, larlite::hit > _core
std::string _config_file
Detailed Description
User custom analysis class made by SHELL_USER_NAME.
Definition at line 32 of file Supera.h.
Constructor & Destructor Documentation
Supera()
Supera::Supera ()
Default constructor.
Definition at line 10 of file Supera.cxx.
   {_name = "Supera"; _fout=nullptr;}
~Supera()
virtual larlite::Supera::~Supera () inline virtual
Default destructor.
Definition at line 40 of file Supera.h.
References analyze(), finalize(), and initialize().
 {}
Member Function Documentation
analyze()
bool Supera::analyze (storage_manager * storage) virtual
IMPLEMENT in Supera.cc! Analyze a data event-by-event.
Definition at line 25 of file Supera.cxx.
References _core, larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::clear_data(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::process_event(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_chstatus(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_generator(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_hit(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_mcreco(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_opdigit(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_simch(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::producer_wire(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_chstatus(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_id(), larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::store_chstatus(), and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::use_mc().
Referenced by ~Supera().
{
     _core.clear_data();
     _core.set_id(storage->run_id(),storage->subrun_id(),storage->event_id());
     event_wire* wire_h = nullptr;
     event_hit*  hit_h  = nullptr;
     if(!_core.producer_wire().empty()) {
       wire_h = storage->get_data<event_wire>(_core.producer_wire());
       if(!wire_h) { throw DataFormatException("Could not load wire data!"); }
     }
     if(!_core.producer_hit().empty()) {
       hit_h = storage->get_data<event_hit>(_core.producer_hit());
       if(!hit_h) { throw DataFormatException("Could not load hit data!"); }
     }
     if(!hit_h && !wire_h)
       throw DataFormatException("No wire nor hit producer specified...");
     if(hit_h && wire_h)
       throw DataFormatException("Both hit and wire producer specified (one has to be empty)");
     auto opdigit_h = storage->get_data<event_opdetwaveform>(_core.producer_opdigit());
     if(_core.store_chstatus()) {
       auto chstatus_h = storage->get_data<event_chstatus>(_core.producer_chstatus());
       if(!chstatus_h || chstatus_h->empty())
         throw ::larcv::larbys("ChStatus not found or empty!");
       for(auto const& chs : *chstatus_h) {
         auto const& pid = chs.plane();
         auto const& status_v = chs.status();
         for(size_t wire=0; wire<status_v.size(); ++wire)
           _core.set_chstatus(pid.Plane,wire,status_v[wire]);
       }
     }
     bool status=true;
     if(_core.use_mc()) {
       auto mctruth_h  = storage->get_data<event_mctruth>(_core.producer_generator());
       auto mctrack_h  = storage->get_data<event_mctrack>(_core.producer_mcreco());
       auto mcshower_h = storage->get_data<event_mcshower>(_core.producer_mcreco());
       if(!mctruth_h || !mctrack_h || !mcshower_h) throw DataFormatException("Necessary MC info missing...");
       if(_core.producer_simch().empty()) {
         std::vector<larlite::simch> empty_simch;
         std::vector<larlite::wire> empty_wire;
         std::vector<larlite::hit> empty_hit;
         if(opdigit_h) {
           if(wire_h)
             status = _core.process_event(*opdigit_h, *wire_h, empty_hit,
               *mctruth_h, *mctrack_h, *mcshower_h, empty_simch);
           else
             status = _core.process_event(*opdigit_h, empty_wire, *hit_h,
               *mctruth_h, *mctrack_h, *mcshower_h, empty_simch);
         }
         else{
           std::vector<larlite::opdetwaveform> empty_opdigit;
           if(wire_h)
             status = _core.process_event(empty_opdigit, *wire_h, empty_hit,
               *mctruth_h, *mctrack_h, *mcshower_h, empty_simch);
           else
             status = _core.process_event(empty_opdigit, empty_wire, *hit_h,
               *mctruth_h, *mctrack_h, *mcshower_h, empty_simch);
         }
       }else{
         auto simch_h = storage->get_data<event_simch>(_core.producer_simch());
         if(!simch_h) throw DataFormatException("SimChannel requested but not available");
         std::vector<larlite::wire> empty_wire;
         std::vector<larlite::hit> empty_hit;
         if(opdigit_h) {
           if(wire_h)
             status = _core.process_event(*opdigit_h, *wire_h, empty_hit,
               *mctruth_h, *mctrack_h, *mcshower_h, *simch_h);
           else
             status = _core.process_event(*opdigit_h, empty_wire, *hit_h,
               *mctruth_h, *mctrack_h, *mcshower_h, *simch_h);
         }
         else{
           std::vector<larlite::opdetwaveform> empty_opdigit;
           if(wire_h)
             status = _core.process_event(empty_opdigit, *wire_h, empty_hit,
               *mctruth_h, *mctrack_h, *mcshower_h, *simch_h);
           else
             status = _core.process_event(empty_opdigit, empty_wire, *hit_h,
               *mctruth_h, *mctrack_h, *mcshower_h, *simch_h);
         }
       }
     }else{
       std::vector<larlite::mctruth>  empty_mctruth;
       std::vector<larlite::mctrack>  empty_mctrack;
       std::vector<larlite::mcshower> empty_mcshower;
       std::vector<larlite::simch>    empty_simch;
       std::vector<larlite::wire> empty_wire;
       std::vector<larlite::hit> empty_hit;
       if(opdigit_h) {
         if(wire_h)
           status = _core.process_event(*opdigit_h, *wire_h, empty_hit,
             empty_mctruth, empty_mctrack, empty_mcshower, empty_simch);
         else
           status = _core.process_event(*opdigit_h, empty_wire, *hit_h,
             empty_mctruth, empty_mctrack, empty_mcshower, empty_simch);
       }
       else{
         std::vector<larlite::opdetwaveform> empty_opdigit;
         if(wire_h)
           status = _core.process_event(empty_opdigit, *wire_h, empty_hit,
             empty_mctruth, empty_mctrack, empty_mcshower, empty_simch);
         else
           status = _core.process_event(empty_opdigit, empty_wire, *hit_h,
             empty_mctruth, empty_mctrack, empty_mcshower, empty_simch);
       }
     }
     return status;
   }
finalize()
bool Supera::finalize () virtual
IMPLEMENT in Supera.cc! Finalize method to be called after all events processed.
Definition at line 158 of file Supera.cxx.
References _core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::finalize().
Referenced by ~Supera().
{
     _core.finalize();
     return true;
   }
initialize()
bool Supera::initialize () virtual
IMPLEMENT in Supera.cc! Initialization method to be called before the analysis event loop.
Definition at line 13 of file Supera.cxx.
References _config_file, _core, larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::configure(), larcv::CreatePSetFromFile(), larcv::PSet::get(), and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::initialize().
Referenced by ~Supera().
{
     auto main_cfg = ::larcv::CreatePSetFromFile(_config_file).get<larcv::PSet>(_name);
     //std::cout<<main_cfg.dump()<<std::endl;
     _core.configure(main_cfg);
     _core.initialize();
     return true;
   }
set_config()
void larlite::Supera::set_config (const std::string cfg_file) inline
Definition at line 57 of file Supera.h.
References _config_file.
 {_config_file=cfg_file;}
supera_fname()
void larlite::Supera::supera_fname (std::string name) inline
Definition at line 59 of file Supera.h.
References _core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::supera_fname().
 { _core.supera_fname(name); }
Member Data Documentation
_config_file
std::string larlite::Supera::_config_file protected
Definition at line 69 of file Supera.h.
Referenced by initialize(), and set_config().
_core
::larcv::supera::SuperaCore<larlite::opdetwaveform, larlite::wire, larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch, larlite::hit> larlite::Supera::_core protected
Definition at line 68 of file Supera.h.
Referenced by analyze(), finalize(), initialize(), and supera_fname().
The documentation for this class was generated from the following files:
Supera.h
Supera.cxx