LArCV: larcv::ROICountFilterProcessFactory Class Reference
larcv::ROICountFilterProcessFactory Class Reference
#include <ROICountFilter.h>
Public Member Functions
ROICountFilterProcessFactory ()
ctor
~ROICountFilterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 55 of file ROICountFilter.h.
Constructor & Destructor Documentation
ROICountFilterProcessFactory()
larcv::ROICountFilterProcessFactory::ROICountFilterProcessFactory () inline
ctor
Definition at line 58 of file ROICountFilter.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ROICountFilter",this); }
~ROICountFilterProcessFactory()
larcv::ROICountFilterProcessFactory::~ROICountFilterProcessFactory () inline
dtor
Definition at line 60 of file ROICountFilter.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ROICountFilterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 62 of file ROICountFilter.h.
References larcv::ROICountFilter::ROICountFilter().
 { return new ROICountFilter(instance_name); }
The documentation for this class was generated from the following file:
ROICountFilter.h