LArCV: larcv::DumpHiResCropImages Class Reference
larcv::DumpHiResCropImages Class Reference
#include <DumpHiResCropImages.h>
Public Member Functions
DumpHiResCropImages (const std::string name="DumpHiResCropImages")
Default constructor.
~DumpHiResCropImages ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::string fTPCImageProducer
std::string fSegmentationProducer
std::string fPMTWeightedProducer
std::string fPMTRawProducer
Protected Member Functions
void DumpBGRImage (IOManager &mgr, std::string producer, std::string imglabel, bool ismc, bool augment)
Detailed Description
Definition at line 29 of file DumpHiResCropImages.h.
Constructor & Destructor Documentation
DumpHiResCropImages()
larcv::DumpHiResCropImages::DumpHiResCropImages (const std::string name = "DumpHiResCropImages")
Default constructor.
Definition at line 18 of file DumpHiResCropImages.cxx.
Referenced by larcv::DumpHiResCropImagesProcessFactory::create().
     : ProcessBase(name)
   {}
~DumpHiResCropImages()
larcv::DumpHiResCropImages::~DumpHiResCropImages () inline
Default destructor.
Definition at line 37 of file DumpHiResCropImages.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::DumpHiResCropImages::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 22 of file DumpHiResCropImages.cxx.
References fPMTRawProducer, fPMTWeightedProducer, fSegmentationProducer, fTPCImageProducer, and larcv::PSet::get().
Referenced by ~DumpHiResCropImages().
   {
     fTPCImageProducer     = cfg.get<std::string>( "TPCProducer","" );
     fSegmentationProducer = cfg.get<std::string>( "SegmentationProducer", "" );
     fPMTWeightedProducer  = cfg.get<std::string>( "PMTWeightedProducer", "" );
     fPMTRawProducer       = cfg.get<std::string>( "PMTProducer", "" );
   }
DumpBGRImage()
void larcv::DumpHiResCropImages::DumpBGRImage (IOManager & mgr, std::string producer, std::string imglabel, bool ismc, bool augment) protected
Definition at line 87 of file DumpHiResCropImages.cxx.
References larcv::ImageMeta::cols(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::Image2D::meta(), larcv::Image2D::pixel(), and larcv::ImageMeta::rows().
Referenced by process().
{
 #ifdef USE_OPENCV
     auto input_images = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,producer));
     cv::Mat img;
     for (size_t p=0; p<3; p++) {
       larcv::Image2D const& src = input_images->at(p);
       if ( p==0 )
     img = cv::Mat::zeros( src.meta().rows(), src.meta().cols(), CV_8UC3 );
       for (size_t r=0; r<src.meta().rows(); r++) {
     for (size_t c=0; c<src.meta().cols(); c++) {
       unsigned short pix = src.pixel( r, c );
       int val = std::min( 255, (int)(pix) );
       if ( augment )
         val = std::min( 255, (int)(val+0.4)*10 );
       val = std::max( 0, val );
       img.at< cv::Vec3b >(r,c)[p] = (unsigned int)val;
     }
       }
     }
     char testname[200];
     if (ismc )
       sprintf( testname, "test_%s_%s_%zu_mc.png", producer.c_str(), imglabel.c_str(), input_images->event() );
     else
       sprintf( testname, "test_%s_%s_%zu.png", producer.c_str(), imglabel.c_str(), input_images->event() );
     cv::imwrite( testname, img );
 #endif
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::DumpHiResCropImages::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 84 of file DumpHiResCropImages.cxx.
Referenced by ~DumpHiResCropImages().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DumpHiResCropImages::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 30 of file DumpHiResCropImages.cxx.
Referenced by ~DumpHiResCropImages().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DumpHiResCropImages::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 33 of file DumpHiResCropImages.cxx.
References larcv::ImageMeta::cols(), DumpBGRImage(), fPMTRawProducer, fPMTWeightedProducer, fSegmentationProducer, fTPCImageProducer, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::Image2D::meta(), larcv::Image2D::pixel(), and larcv::ImageMeta::rows().
Referenced by ~DumpHiResCropImages().
   {
     bool hasmc = false;
 #ifndef USE_OPENCV
     return false;
 #else
     if ( fTPCImageProducer!="" )
       DumpBGRImage( mgr, fTPCImageProducer, "tpc", false, true );
     if ( fSegmentationProducer!="" )
       DumpBGRImage( mgr, fSegmentationProducer, "segment", false, false );
     if ( fPMTWeightedProducer!="" )
       DumpBGRImage( mgr, fPMTWeightedProducer, "pmtweighted", false, true );
     if ( fPMTRawProducer!="" ) {
       //needs custom routine
       auto input_pmtraw_images = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fPMTRawProducer));
       cv::Mat pmtimg;
       larcv::Image2D const& pmtsrc = input_pmtraw_images->at(0);
       pmtimg = cv::Mat::zeros( pmtsrc.meta().rows(), pmtsrc.meta().cols(), CV_8UC3 );
       for (size_t r=0; r<pmtsrc.meta().rows(); r++) {
     for (size_t c=0; c<pmtsrc.meta().cols(); c++) {
       float adc = pmtsrc.pixel( r, c ) - 2047.0;
       int val = std::min( 255, (int)(adc) );
       //std::cout << "(" << r << "," << c << ") " << pmtsrc.pixel( r, c ) << std::endl;
       val = std::max( 0, val );
       for (size_t i=0; i<3; i++) {
         pmtimg.at< cv::Vec3b >(r,c)[i] = val;
       }
       if ( r==190 || r==310 )
         pmtimg.at< cv::Vec3b >(r,c)[2] = 100;
     }
       }
       char testname[200];
       if (hasmc )
     sprintf( testname, "test_%s_pmtraw_%zu_mc.png", fPMTRawProducer.c_str(), input_pmtraw_images->event() );
       else
     sprintf( testname, "test_%s_pmtraw_%zu.png", fPMTRawProducer.c_str(), input_pmtraw_images->event() );
       cv::imwrite( testname, pmtimg );
       return true;
     }
 #endif
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fPMTRawProducer
std::string larcv::DumpHiResCropImages::fPMTRawProducer
Definition at line 50 of file DumpHiResCropImages.h.
Referenced by configure(), and process().
fPMTWeightedProducer
std::string larcv::DumpHiResCropImages::fPMTWeightedProducer
Definition at line 49 of file DumpHiResCropImages.h.
Referenced by configure(), and process().
fSegmentationProducer
std::string larcv::DumpHiResCropImages::fSegmentationProducer
Definition at line 48 of file DumpHiResCropImages.h.
Referenced by configure(), and process().
fTPCImageProducer
std::string larcv::DumpHiResCropImages::fTPCImageProducer
Definition at line 47 of file DumpHiResCropImages.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
DumpHiResCropImages.h
DumpHiResCropImages.cxx