LArCV: larcv::EventPixel2D Class Reference
larcv::EventPixel2D Class Reference
Event-wise class to store a collection of larcv::Pixel2D and larcv::Pixel2DCluster.
#include <EventPixel2D.h>
Public Member Functions
EventPixel2D ()
Default constructor.
virtual ~EventPixel2D ()
Default destructor.
void clear ()
Clears an array of larcv::Pixel2D.
const std::vector< larcv::Pixel2D > & Pixel2DArray (const ::larcv::PlaneID_t plane)
Retrieve Pixel2D for a plane.
const std::vector< larcv::Pixel2DCluster > & Pixel2DClusterArray (const ::larcv::PlaneID_t plane)
Retrieve Pixel2DCluster for a plane.
const ImageMeta & Meta (const ::larcv::PlaneID_t plane) const
Retrieve ImageMeta for a plane (for simple Pixel2D collection)
const std::vector< larcv::ImageMeta > & ClusterMetaArray (const ::larcv::PlaneID_t plane) const
Retrieve ImageMeta for a plane (for Pixel2DCluster)
const ImageMeta & ClusterMeta (const ::larcv::PlaneID_t plane, const size_t) const
Retrieve ImageMeta for a plane (for Pixel2DCluster)
const std::map< ::larcv::PlaneID_t, std::vector< larcv::Pixel2D > > & Pixel2DArray () const
const std::map< ::larcv::PlaneID_t, std::vector< larcv::Pixel2DCluster > > & Pixel2DClusterArray () const
const std::map< ::larcv::PlaneID_t, larcv::ImageMeta > & MetaArray () const
const std::map< ::larcv::PlaneID_t, std::vector< ::larcv::ImageMeta > > & ClusterMetaArray () const
void SetMeta (const larcv::PlaneID_t plane, const ImageMeta &meta)
Set ImageMeta.
void Append (const larcv::PlaneID_t plane, const Pixel2D &pixel)
Insert larcv::Pixel2D into a collection.
void Append (const larcv::PlaneID_t plane, const Pixel2DCluster &cluster)
Insert larcv::Pixel2DCluster into a collection.
void Append (const larcv::PlaneID_t plane, const Pixel2DCluster &cluster, const ImageMeta &)
Insert larcv::Pixel2DCluster into a collection.
void Emplace (const larcv::PlaneID_t plane, Pixel2D &&pixel)
Emplace larcv::Pixel2D into a collection.
void Emplace (const larcv::PlaneID_t plane, Pixel2DCluster &&cluster, const ImageMeta &)
Emplace larcv::Pixel2DCluster into a collection.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2D > > _pixel_m
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2DCluster > > _cluster_m
std::map< ::larcv::PlaneID_t, ::larcv::ImageMeta > _meta_m
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::ImageMeta > > _cluster_meta_m
Detailed Description
Event-wise class to store a collection of larcv::Pixel2D and larcv::Pixel2DCluster.
A concrete factory class for larcv::EventPixel2D.
Definition at line 30 of file EventPixel2D.h.
Constructor & Destructor Documentation
EventPixel2D()
larcv::EventPixel2D::EventPixel2D () inline
Default constructor.
Definition at line 35 of file EventPixel2D.h.
Referenced by larcv::EventPixel2DFactory::create().
 {}
~EventPixel2D()
virtual larcv::EventPixel2D::~EventPixel2D () inline virtual
Default destructor.
Definition at line 38 of file EventPixel2D.h.
References clear(), ClusterMeta(), ClusterMetaArray(), Meta(), Pixel2DArray(), and Pixel2DClusterArray().
 {}
Member Function Documentation
Append() [1/3]
void larcv::EventPixel2D::Append (const larcv::PlaneID_t plane, const Pixel2D & pixel)
Insert larcv::Pixel2D into a collection.
Definition at line 92 of file EventPixel2D.cxx.
References _pixel_m.
Referenced by Append(), larcv::VertexFilter::FillParticles(), and SetMeta().
   {
     _pixel_m[plane].push_back(pixel);
   }
Append() [2/3]
void larcv::EventPixel2D::Append (const larcv::PlaneID_t plane, const Pixel2DCluster & cluster)
Insert larcv::Pixel2DCluster into a collection.
Definition at line 97 of file EventPixel2D.cxx.
References Append().
   {
     for(auto const& px2d : cluster) Append(plane,px2d);
   }
Append() [3/3]
void larcv::EventPixel2D::Append (const larcv::PlaneID_t plane, const Pixel2DCluster & cluster, const ImageMeta & meta)
Insert larcv::Pixel2DCluster into a collection.
Definition at line 102 of file EventPixel2D.cxx.
References _cluster_m, and _cluster_meta_m.
   {
     auto& col = _cluster_m[plane];
     col.push_back(cluster);
     col.back()._id = col.size() - 1;
     _cluster_meta_m[plane].push_back(meta);
   }
clear()
void larcv::EventPixel2D::clear () virtual
Clears an array of larcv::Pixel2D.
Reimplemented from larcv::EventBase.
Definition at line 13 of file EventPixel2D.cxx.
References _cluster_m, _cluster_meta_m, _meta_m, _pixel_m, and larcv::EventBase::clear().
Referenced by ~EventPixel2D().
   {
     EventBase::clear();
     _pixel_m.clear();
     _cluster_m.clear();
     _meta_m.clear();
     _cluster_meta_m.clear();
   }
ClusterMeta()
const ImageMeta & larcv::EventPixel2D::ClusterMeta (const ::larcv::PlaneID_t plane, const size_t cluster_id) const
Retrieve ImageMeta for a plane (for Pixel2DCluster)
Definition at line 80 of file EventPixel2D.cxx.
References ClusterMetaArray(), larcv::logger::get(), larcv::msg::kCRITICAL, and larcv::logger::send().
Referenced by ~EventPixel2D().
   {
     auto const& meta_v = ClusterMetaArray(plane);
     if(meta_v.size() <= cluster_id) {
       // oops
       logger::get("EventPixel2D").send(msg::kCRITICAL, __FUNCTION__, __LINE__)
     << "No image meta for plane " << plane << " index " << cluster_id <<std::endl;
       throw larbys();
     }
     return meta_v[cluster_id];
   }
ClusterMetaArray() [1/2]
const std::vector< larcv::ImageMeta > & larcv::EventPixel2D::ClusterMetaArray (const ::larcv::PlaneID_t plane) const
Retrieve ImageMeta for a plane (for Pixel2DCluster)
Definition at line 68 of file EventPixel2D.cxx.
References _cluster_meta_m, larcv::logger::get(), larcv::msg::kCRITICAL, and larcv::logger::send().
Referenced by larcv::VertexFilter::FillParticles(), larcv::ReadNueFile::process(), and larcv::Run3DTracker::process().
   {
     auto iter = _cluster_meta_m.find(plane);
     if(iter == _cluster_meta_m.end()) {
       // oops
       logger::get("EventPixel2D").send(msg::kCRITICAL, __FUNCTION__, __LINE__)
     << "No image meta for plane " << plane << std::endl;
       throw larbys();
     }
     return (*iter).second;
   }
ClusterMetaArray() [2/2]
const std::map< ::larcv::PlaneID_t, std::vector< ::larcv::ImageMeta> >& larcv::EventPixel2D::ClusterMetaArray () const inline
Definition at line 63 of file EventPixel2D.h.
References _cluster_meta_m.
Referenced by ClusterMeta(), and ~EventPixel2D().
     { return _cluster_meta_m; }
Emplace() [1/2]
void larcv::EventPixel2D::Emplace (const larcv::PlaneID_t plane, Pixel2D && pixel)
Emplace larcv::Pixel2D into a collection.
Definition at line 110 of file EventPixel2D.cxx.
References _pixel_m.
Referenced by SetMeta().
   {
     auto& col = _pixel_m[plane];
     col.emplace_back(std::move(pixel));
   }
Emplace() [2/2]
void larcv::EventPixel2D::Emplace (const larcv::PlaneID_t plane, Pixel2DCluster && cluster, const ImageMeta & meta)
Emplace larcv::Pixel2DCluster into a collection.
Definition at line 116 of file EventPixel2D.cxx.
References _cluster_m, and _cluster_meta_m.
   {
     auto& col = _cluster_m[plane];
     col.emplace_back(std::move(cluster));
     col.back()._id = col.size() - 1;
     _cluster_meta_m[plane].push_back(meta);
   }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
Meta()
const ImageMeta & larcv::EventPixel2D::Meta (const ::larcv::PlaneID_t plane) const
Retrieve ImageMeta for a plane (for simple Pixel2D collection)
Definition at line 56 of file EventPixel2D.cxx.
References _meta_m, larcv::logger::get(), larcv::msg::kCRITICAL, and larcv::logger::send().
Referenced by ~EventPixel2D().
   {
     auto iter = _meta_m.find(plane);
     if(iter == _meta_m.end()) {
       // oops
       logger::get("EventPixel2D").send(msg::kCRITICAL, __FUNCTION__, __LINE__)
     << "No image meta for plane " << plane << std::endl;
       throw larbys();
     }
     return (*iter).second;
   }
MetaArray()
const std::map< ::larcv::PlaneID_t, larcv::ImageMeta>& larcv::EventPixel2D::MetaArray () const inline
Definition at line 60 of file EventPixel2D.h.
References _meta_m.
     { return _meta_m; }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
Pixel2DArray() [1/2]
const std::vector< larcv::Pixel2D > & larcv::EventPixel2D::Pixel2DArray (const ::larcv::PlaneID_t plane)
Retrieve Pixel2D for a plane.
Definition at line 22 of file EventPixel2D.cxx.
References _pixel_m, larcv::logger::get(), larcv::msg::kCRITICAL, and larcv::logger::send().
   {
     // I prefer to return empty vector than fail
     auto iter = _pixel_m.find(plane);
     if(iter == _pixel_m.end()) {
       _pixel_m.insert( std::pair< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2D > >( plane, std::vector< ::larcv::Pixel2D >() ) );
       iter = _pixel_m.find(plane); // get the new iterator
       if ( iter==_pixel_m.end() ) {
     // oops
     logger::get("EventPixel2D").send(msg::kCRITICAL, __FUNCTION__, __LINE__)
       << "No pixel for plane " << plane << " and could not make empty vector." << std::endl;
     throw larbys();
       }
     }
     return (*iter).second;
   }
Pixel2DArray() [2/2]
const std::map< ::larcv::PlaneID_t, std::vector<larcv::Pixel2D> >& larcv::EventPixel2D::Pixel2DArray () const inline
Definition at line 54 of file EventPixel2D.h.
References _pixel_m.
Referenced by ~EventPixel2D().
     { return _pixel_m; }
Pixel2DClusterArray() [1/2]
const std::vector< larcv::Pixel2DCluster > & larcv::EventPixel2D::Pixel2DClusterArray (const ::larcv::PlaneID_t plane)
Retrieve Pixel2DCluster for a plane.
Definition at line 39 of file EventPixel2D.cxx.
References _cluster_m, larcv::logger::get(), larcv::msg::kCRITICAL, and larcv::logger::send().
Referenced by larcv::ExampleAna::Analyze(), larcv::ParticleAna::AnalyzeAngle(), larcv::ParticleAna::AnalyzedQdX(), larcv::ParticleAna::AnalyzeParticle(), larcv::ParticleAna::AnalyzeSignal(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::VertexFilter::FillParticles(), larcv::VertexFilter::process(), larcv::ReadNueFile::process(), larcv::CosmicVertexAna::process(), and larcv::Run3DTracker::process().
   {
     auto iter = _cluster_m.find(plane);
     if(iter == _cluster_m.end()) {
       _cluster_m.insert( std::pair< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2DCluster > >( plane, std::vector< ::larcv::Pixel2DCluster >() ) );
       iter = _cluster_m.find(plane); // get the new iterator
       if ( iter==_cluster_m.end() ) {
     // oops
     logger::get("EventPixel2D").send(msg::kCRITICAL, __FUNCTION__, __LINE__)
       << "No pixel cluster for plane " << plane << " and could not make empty vector." << std::endl;
     throw larbys();
       }
     }
     return (*iter).second;
   }
Pixel2DClusterArray() [2/2]
const std::map< ::larcv::PlaneID_t, std::vector<larcv::Pixel2DCluster> >& larcv::EventPixel2D::Pixel2DClusterArray () const inline
Definition at line 57 of file EventPixel2D.h.
References _cluster_m.
Referenced by ~EventPixel2D().
     { return _cluster_m; }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
SetMeta()
void larcv::EventPixel2D::SetMeta (const larcv::PlaneID_t plane, const ImageMeta & meta) inline
Set ImageMeta.
Definition at line 67 of file EventPixel2D.h.
References _meta_m, Append(), and Emplace().
     { _meta_m[plane] = meta;}
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
_cluster_m
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2DCluster > > larcv::EventPixel2D::_cluster_m private
Definition at line 87 of file EventPixel2D.h.
Referenced by Append(), clear(), Emplace(), and Pixel2DClusterArray().
_cluster_meta_m
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::ImageMeta > > larcv::EventPixel2D::_cluster_meta_m private
Definition at line 89 of file EventPixel2D.h.
Referenced by Append(), clear(), ClusterMetaArray(), and Emplace().
_meta_m
std::map< ::larcv::PlaneID_t, ::larcv::ImageMeta > larcv::EventPixel2D::_meta_m private
Definition at line 88 of file EventPixel2D.h.
Referenced by clear(), Meta(), MetaArray(), and SetMeta().
_pixel_m
std::map< ::larcv::PlaneID_t, std::vector< ::larcv::Pixel2D > > larcv::EventPixel2D::_pixel_m private
Definition at line 86 of file EventPixel2D.h.
Referenced by Append(), clear(), Emplace(), and Pixel2DArray().
The documentation for this class was generated from the following files:
EventPixel2D.h
EventPixel2D.cxx