LArCV: larcv::RSEFilter Class Reference
larcv::RSEFilter Class Reference
#include <RSEFilter.h>
Public Member Functions
RSEFilter (const std::string name="RSEFilter")
Default constructor.
~RSEFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
TTree * _tree
std::map< larcv::RSEID, bool > _rse_m
std::string _ref_producer
size_t _ref_type
bool _remove_duplicate
std::string _fname
int _run
int _subrun
int _event
Detailed Description
Definition at line 58 of file RSEFilter.h.
Constructor & Destructor Documentation
RSEFilter()
larcv::RSEFilter::RSEFilter (const std::string name = "RSEFilter")
Default constructor.
Definition at line 11 of file RSEFilter.cxx.
     : ProcessBase(name), _tree(nullptr)
   {}
~RSEFilter()
larcv::RSEFilter::~RSEFilter () inline
Default destructor.
Definition at line 66 of file RSEFilter.h.
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::RSEFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file RSEFilter.cxx.
References _ref_producer, _ref_type, _remove_duplicate, _rse_m, larcv::RSEID::event, larcv::PSet::get(), LARCV_INFO, larcv::read_csv(), larcv::RSEID::run, and larcv::RSEID::subrun.
   {
     _ref_producer=cfg.get<std::string>("RefProducer");
     _ref_type=cfg.get<size_t>("RefType");
     _remove_duplicate=cfg.get<int>("RemoveDuplicate",0);
     auto file_path=cfg.get<std::string>("CSVFilePath");
     auto format=cfg.get<std::string>("Format","II");
     auto data = larcv::read_csv(file_path,format);
     auto const& run_v = data.get<int>("run");
     auto const& subrun_v = data.get<int>("subrun");
     auto const& event_v = data.get<int>("event");
     _rse_m.clear();
     RSEID rse_id;
     for(size_t i=0; i<run_v.size(); ++i) {
       rse_id.run = run_v[i];
       rse_id.subrun = subrun_v[i];
       rse_id.event = event_v[i];
       _rse_m[rse_id] = false;
     }
     LARCV_INFO() << "Registered: " << _rse_m.size() << " unique events to be kept..." << std::endl;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::RSEFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 76 of file RSEFilter.cxx.
References _rse_m, _tree, larcv::ProcessBase::has_ana_file(), and LARCV_WARNING.
   {
     for(auto const& rse_used : _rse_m) {
       if(rse_used.second) continue;
       LARCV_WARNING() << "Event ID not found in data file (unused): Run " << rse_used.first.run
               << " Event " << rse_used.first.event << std::endl;
     }
     if(has_ana_file())
       _tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), finalize(), initialize(), and process().
     { return _fout != nullptr; }
initialize()
void larcv::RSEFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 38 of file RSEFilter.cxx.
References _event, _fname, _run, _subrun, _tree, and larcv::ProcessBase::has_ana_file().
   {
     if(has_ana_file()) {
       _tree = new TTree("RSEFilter","");
       _tree->Branch("fname"  , &_fname);
       _tree->Branch("run"    , &_run   , "run/I");
       _tree->Branch("subrun" , &_subrun, "subrun/I");
       _tree->Branch("event"  , &_event , "event/I");
     }
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::RSEFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 49 of file RSEFilter.cxx.
References _event, _fname, _ref_producer, _ref_type, _remove_duplicate, _rse_m, _run, _subrun, _tree, larcv::IOManager< T >::file_list(), larcv::IOManager< T >::get_data(), larcv::ProcessBase::has_ana_file(), LARCV_INFO, and LARCV_WARNING.
   {
     auto ptr = mgr.get_data((larcv::ProductType_t)_ref_type,_ref_producer);
     auto const rse = RSEID(ptr->run(),ptr->subrun(),ptr->event());
     auto itr = _rse_m.find(rse);
     bool keepit = (itr != _rse_m.end());
     LARCV_INFO() << "Event key: " << ptr->event_key() << " ... keep it? " << keepit << std::endl;
     bool duplicate = false;
     if(keepit) {
       duplicate = (*itr).second;
       if(duplicate) LARCV_WARNING() << "Run " << rse.run << " Event " << rse.event << " is duplicated!!!" << std::endl;
       (*itr).second = true;
     }
     if(duplicate && _remove_duplicate) return false;
     if(has_ana_file()) {
       _fname  = (std::string) mgr.file_list().front();
       _run    = (int) ptr->run();
       _subrun = (int) ptr->subrun();
       _event  = (int) ptr->event();
       _tree->Fill();
     }
     return keepit;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_event
int larcv::RSEFilter::_event private
Definition at line 87 of file RSEFilter.h.
Referenced by initialize(), and process().
_fname
std::string larcv::RSEFilter::_fname private
Definition at line 84 of file RSEFilter.h.
Referenced by initialize(), and process().
_ref_producer
std::string larcv::RSEFilter::_ref_producer private
Definition at line 81 of file RSEFilter.h.
Referenced by configure(), and process().
_ref_type
size_t larcv::RSEFilter::_ref_type private
Definition at line 82 of file RSEFilter.h.
Referenced by configure(), and process().
_remove_duplicate
bool larcv::RSEFilter::_remove_duplicate private
Definition at line 83 of file RSEFilter.h.
Referenced by configure(), and process().
_rse_m
std::map<larcv::RSEID,bool> larcv::RSEFilter::_rse_m private
Definition at line 80 of file RSEFilter.h.
Referenced by configure(), finalize(), and process().
_run
int larcv::RSEFilter::_run private
Definition at line 85 of file RSEFilter.h.
Referenced by initialize(), and process().
_subrun
int larcv::RSEFilter::_subrun private
Definition at line 86 of file RSEFilter.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::RSEFilter::_tree private
Definition at line 78 of file RSEFilter.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
RSEFilter.h
RSEFilter.cxx