LArCV: larcv::ImageMeta Class Reference
larcv::ImageMeta Class Reference
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
#include <ImageMeta.h>
Public Member Functions
ImageMeta (const double width=0., const double height=0., const size_t row_count=0., const size_t col_count=0, const double origin_x=0., const double origin_y=0., const PlaneID_t plane=::larcv::kINVALID_PLANE)
Default constructor: width, height, and origin coordinate won't be modifiable.
~ImageMeta ()
Default destructor.
bool operator== (const ImageMeta &rhs) const
bool operator!= (const ImageMeta &rhs) const
ImageIndex_t image_index () const
void image_index (ImageIndex_t id)
const Point2D & tl () const
Top-left corner point.
const Point2D bl () const
Bottom-left corner point.
const Point2D tr () const
Top-right corner point.
const Point2D br () const
Bottom-right corner point.
PlaneID_t plane () const
PlaneID_t getter.
double width () const
Width accessor.
double height () const
Height accessor.
size_t rows () const
rows accessor
size_t cols () const
columns accessor
double pixel_width () const
Pixel horizontal size.
double pixel_height () const
Pixel vertical size.
size_t index (size_t row, size_t col) const
Provide 1-D array index from row and column.
double min_x () const
Provide absolute scale min x.
double max_x () const
Provide absolute scale max x.
double min_y () const
Provide absolute scale min y.
double max_y () const
Provide absolute scale max y.
double pos_x (size_t col) const
Provide absolute horizontal coordinate of the center of a specified pixel row.
double pos_y (size_t row) const
Provide absolute vertical coordinate of the center of a specified pixel row.
size_t col (double x) const
Provide horizontal pixel index for a given horizontal x position (in absolute coordinate)
size_t row (double y) const
Provide vertical pixel index for a given vertical y position (in absolute coordinate)
void update (size_t row_count, size_t col_count)
Change # of vertical/horizontal pixels in meta data.
void reset_origin (double x, double y)
Reset origin coordinate.
ImageMeta overlap (const ImageMeta &meta) const
Check if there's an overlap. If so return overlapping bounding box.
ImageMeta inclusive (const ImageMeta &meta) const
Construct a union bounding box.
bool contains (const ImageMeta &meta) const
Check if this meta containers given.
bool contains (float x, float y) const
Check if point is inside meta.
std::string dump () const
Dump info in text.
Protected Attributes
ImageIndex_t _image_id
Associated image ID (of the same producer name)
larcv::Point2D _origin
Absolute coordinate of the left top corner of an image.
double _width
Horizontal size of an image in double floating precision (in original coordinate unit size)
double _height
Vertical size of an image in double floating precision (in original coordinate unit size)
size_t _col_count
of pixels in horizontal axis
size_t _row_count
of pixels in vertical axis
PlaneID_t _plane
unique plane ID number
Friends
class Image2D
Detailed Description
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
For cv::Mat, there
is a function ImageMeta::update to constantly update vertical/horizontal # pixels
as it may change in the course of matrix operation.
Definition at line 35 of file ImageMeta.h.
Constructor & Destructor Documentation
ImageMeta()
larcv::ImageMeta::ImageMeta (const double width = 0., const double height = 0., const size_t row_count = 0., const size_t col_count = 0, const double origin_x = 0., const double origin_y = 0., const PlaneID_t plane = ::larcv::kINVALID_PLANE) inline
Default constructor: width, height, and origin coordinate won't be modifiable.
Definition at line 42 of file ImageMeta.h.
References height(), update(), and width().
Referenced by inclusive(), and overlap().
       : _image_id (kINVALID_INDEX)
       , _origin (origin_x,origin_y)
       , _width  (width)
       , _height (height)
       , _plane  (plane)
     {
       if( width  < 0. ) throw larbys("Width must be a positive floating point!");
       if( height < 0. ) throw larbys("Height must be a positive floating point!");
       update(row_count,col_count);
     }
~ImageMeta()
larcv::ImageMeta::~ImageMeta () inline
Default destructor.
Definition at line 58 of file ImageMeta.h.
 {}
Member Function Documentation
bl()
const Point2D larcv::ImageMeta::bl () const inline
Bottom-left corner point.
Definition at line 79 of file ImageMeta.h.
References _height, _origin, larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::Get2DRoi().
 { return Point2D(_origin.x,          _origin.y - _height); }
br()
const Point2D larcv::ImageMeta::br () const inline
Bottom-right corner point.
Definition at line 83 of file ImageMeta.h.
References _height, _origin, _width, larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::MakeRect(), larcv::Project3D(), and larcv::ProjectTo3D().
 { return Point2D(_origin.x + _width, _origin.y - _height); }
col()
size_t larcv::ImageMeta::col (double x) const
Provide horizontal pixel index for a given horizontal x position (in absolute coordinate)
Definition at line 18 of file ImageMeta.cxx.
References _origin, _width, pixel_width(), and larcv::Point2D::x.
Referenced by larcv::Image2D::crop(), larcv::crop_meta(), larcv::AStar3DAlgo::downsampleAndFindPath(), larcv::draw_bb(), larcv::UBWireTool::getProjectedImagePixel(), supera::Hit2Image2D(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::Image2D::overlay(), pixel_height(), pos_x(), pos_y(), and supera::Wire2Image2D().
   {
     if(x < _origin.x || x >= (_origin.x + _width)) {
       std::stringstream ss;
       ss << "Requested col for x=" << x << " ... but the x (rows) span only " << _origin.x << " => " << _origin.x + _width << "!" << std::endl;
       throw larbys(ss.str());
     }
     return (size_t)((x - _origin.x) / pixel_width());
   }
cols()
size_t larcv::ImageMeta::cols () const inline
columns accessor
Definition at line 93 of file ImageMeta.h.
References _col_count.
Referenced by larcv::ROIAna::area(), larcv::as_caffe_ndarray(), larcv::as_ndarray(), larcv::as_th2d(), larcv::Image2D::copy_compress(), larcv::AStarTracker::CreateDataImage(), larcv::RandomCropper::crop(), larcv::AStarTracker::CropFullImage2bounds(), larcv::DumpHiResCropImages::DumpBGRImage(), larcv::Image2D::eltwise(), dbscan::extractPointsFromImage(), dbscan::extractPointsFromImageBounds(), larcv::fill_img_col(), larcv::SuperaMCROI::FormatMeta(), larcv::Get2DRoi(), larcv::UBWireTool::getProjectedImagePixel(), larcv::Image2D::Image2D(), larcv::mat_to_image2d(), larcv::Image2D::multiRHS(), larcv::Image2D::operator+=(), larcv::ROIPad::PadMeta(), larcv::Image2D::paint_row(), larcv::DBSCAN::process(), larcv::ChannelMax::process(), larcv::DumpHiResCropImages::process(), larcv::EmbedImage::process(), larcv::VertexImg::process(), larcv::NNCosine::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::hires::HiResImageDivider::process(), larcv::Project3D(), larcv::ProjectTo3D(), larcv::Image2D::reset(), larcv::Image2D::resize(), and larcv::Image2D::set_pixel().
 { return _col_count; }
contains() [1/2]
bool larcv::ImageMeta::contains (const ImageMeta & meta) const
Check if this meta containers given.
Check if this meta contains the given meta.
Parameters
[in] meta Meta to check if contained within this meta.
Returns
True if given meta is contained
Definition at line 88 of file ImageMeta.cxx.
References max_x(), max_y(), min_x(), and min_y().
Referenced by larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::DLCosmicTagUtil::makeIntimeCroppedImage(), and reset_origin().
{
     if ( meta!=(*this)
      && (meta.min_x() < this->min_x()
          || meta.max_x() > this->max_x()
          || meta.min_y() < this->min_y()
          || meta.max_y() > this->max_y() ) )
       return false;
     return true;
   }
contains() [2/2]
bool larcv::ImageMeta::contains (float x, float y) const
Check if point is inside meta.
Test if point is within the meta's bounding box.
Parameters
[in] x X-coordinate
[in] y Y-coordinate
Returns
True if (x,y) point is within meta bounds
Definition at line 105 of file ImageMeta.cxx.
References max_x(), max_y(), min_x(), and min_y().
{
     if ( x<min_x() || x>=max_x()
      || y<=min_y() || y>max_y() ) {
       return false;
     }
     return true;
   }
dump()
std::string larcv::ImageMeta::dump () const
Dump info in text.
Definition at line 72 of file ImageMeta.cxx.
References _col_count, _row_count, max_x(), max_y(), min_x(), min_y(), and plane().
Referenced by supera::ImageMetaFromConfig::configure(), larcv::hires::HiResImageDivider::cropEventImages(), larcv::SuperaMCROI::FormatMeta(), supera::Hit2Image2D(), larcv::MultiROICropper::process(), reset_origin(), and supera::Wire2Image2D().
   {
     std::stringstream ss;
     ss << "Plane " << plane() << " (rows,cols) = (" << _row_count << "," << _col_count
        << ") ... Left Top (" << min_x() << "," << max_y()
        << ") ... Right Bottom (" << max_x() << "," << min_y()
        << ")" << std::endl;
     return ss.str();
   }
height()
double larcv::ImageMeta::height () const inline
Height accessor.
Definition at line 89 of file ImageMeta.h.
References _height.
Referenced by larcv::Image2D::compress(), larcv::SuperaMCROI::FormatMeta(), larcv::Get2DRoi(), ImageMeta(), larcv::mat_to_image2d(), larcv::ROIPad::PadMeta(), larcv::hires::HiResImageDivider::process(), larcv::Project3D(), and larcv::ProjectTo3D().
 { return _height;    }
image_index() [1/2]
ImageIndex_t larcv::ImageMeta::image_index () const inline
Definition at line 74 of file ImageMeta.h.
References _image_id.
 { return _image_id; }
image_index() [2/2]
void larcv::ImageMeta::image_index (ImageIndex_t id) inline
Definition at line 75 of file ImageMeta.h.
References _image_id.
 { _image_id = id;   }
inclusive()
ImageMeta larcv::ImageMeta::inclusive (const ImageMeta & meta) const
Construct a union bounding box.
Definition at line 58 of file ImageMeta.cxx.
References _plane, ImageMeta(), max_x(), max_y(), min_x(), min_y(), pixel_height(), and pixel_width().
Referenced by larcv::DLCosmicTagUtil::makeIntimeCroppedImage(), larcv::PyImageStitcher::process(), and reset_origin().
   {
     double min_x = ( meta.min_x() < this->min_x() ? meta.min_x() : this->min_x() ); //pick smaller x min-boudn
     double max_x = ( meta.max_x() > this->max_x() ? meta.max_x() : this->max_x() ); //pick larger x max-bound
     double min_y = ( meta.min_y() < this->min_y() ? meta.min_y() : this->min_y() ); //pick smaller y min-boudn
     double max_y = ( meta.max_y() > this->max_y() ? meta.max_y() : this->max_y() ); //pick larger y max-bound
     return ImageMeta(max_x - min_x, max_y - min_y,
              (max_y - min_y) / pixel_height(),
              (max_x - min_x) / pixel_width(),
              min_x, max_y, _plane);
   }
index()
size_t larcv::ImageMeta::index (size_t row, size_t col) const
Provide 1-D array index from row and column.
Definition at line 8 of file ImageMeta.cxx.
References _col_count, and _row_count.
Referenced by larcv::Image2D::copy(), larcv::Image2D::crop(), larcv::Image2D::overlay(), larcv::Image2D::pixel(), pixel_height(), larcv::Image2D::reverse_copy(), and larcv::Image2D::set_pixel().
{
     if ( row >= _row_count || col >= _col_count ) {
       std::stringstream ss;
       ss << "Invalid pixel index queried: (" << row << "," << col << ") but the dimension is only ("<<_row_count<<","<<_col_count<<")!"<<std::endl;
       throw larbys(ss.str());
     }
     return ( col * _row_count + row );
   }
max_x()
double larcv::ImageMeta::max_x () const inline
Provide absolute scale max x.
Definition at line 104 of file ImageMeta.h.
References _origin, _width, and larcv::Point2D::x.
Referenced by larcv::as_th2d(), contains(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::draw_bb(), dump(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), inclusive(), supera::OpDigit2Image2D(), overlap(), larcv::Image2D::overlay(), and larcv::MultiROICropper::process().
 { return _origin.x + _width; }
max_y()
double larcv::ImageMeta::max_y () const inline
Provide absolute scale max y.
Definition at line 108 of file ImageMeta.h.
References _origin, and larcv::Point2D::y.
Referenced by larcv::as_th2d(), larcv::Image2D::compress(), contains(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::draw_bb(), dump(), larcv::fill_img_col(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), supera::Hit2Image2D(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::MultiROICropper::process(), larcv::EmbedImage::process(), larcv::hires::HiResImageDivider::process(), larcv::Image2D::resize(), and supera::Wire2Image2D().
 { return _origin.y; }
min_x()
double larcv::ImageMeta::min_x () const inline
Provide absolute scale min x.
Definition at line 102 of file ImageMeta.h.
References _origin, and larcv::Point2D::x.
Referenced by larcv::as_th2d(), larcv::Image2D::compress(), contains(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::draw_bb(), dump(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), inclusive(), supera::OpDigit2Image2D(), overlap(), larcv::Image2D::overlay(), larcv::MultiROICropper::process(), larcv::EmbedImage::process(), larcv::VertexImg::process(), larcv::ROIMask::process(), larcv::hires::HiResImageDivider::process(), and larcv::Image2D::resize().
 { return _origin.x; }
min_y()
double larcv::ImageMeta::min_y () const inline
Provide absolute scale min y.
Definition at line 106 of file ImageMeta.h.
References _height, _origin, and larcv::Point2D::y.
Referenced by larcv::as_th2d(), contains(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::draw_bb(), dump(), larcv::fill_img_col(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), supera::Hit2Image2D(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::MultiROICropper::process(), larcv::VertexImg::process(), and supera::Wire2Image2D().
 { return _origin.y - _height; }
operator!=()
bool larcv::ImageMeta::operator!= (const ImageMeta & rhs) const inline
Definition at line 71 of file ImageMeta.h.
     { return !((*this) == rhs); }
operator==()
bool larcv::ImageMeta::operator== (const ImageMeta & rhs) const inline
Definition at line 60 of file ImageMeta.h.
References _col_count, _height, _origin, _plane, _row_count, _width, larcv::Point2D::x, and larcv::Point2D::y.
     {
       return ( _origin.x  == rhs._origin.x  &&
            _origin.y  == rhs._origin.y  &&
            _width     == rhs._width     &&
            _height    == rhs._height    &&
            _plane     == rhs._plane     &&
            _row_count == rhs._row_count &&
            _col_count == rhs._col_count );
     }
overlap()
ImageMeta larcv::ImageMeta::overlap (const ImageMeta & meta) const
Check if there's an overlap. If so return overlapping bounding box.
Definition at line 38 of file ImageMeta.cxx.
References _plane, ImageMeta(), max_x(), max_y(), min_x(), min_y(), pixel_height(), and pixel_width().
Referenced by larcv::DLCosmicTagUtil::makeIntimeCroppedImage(), larcv::MultiROICropper::process(), and reset_origin().
   {
     double minx = ( meta.min_x() < this->min_x() ? this->min_x() : meta.min_x()  ); //pick larger x min-bound
     double maxx = ( meta.max_x() < this->max_x() ? meta.max_x()  : this->max_x() ); //pick smaller x max-bound
     double miny = ( meta.min_y() < this->min_y() ? this->min_y() : meta.min_y()  ); //pick larger x min-bound
     double maxy = ( meta.max_y() < this->max_y() ? meta.max_y()  : this->max_y() ); //pick smaller x max-bound
     if(!(minx < maxx && miny < maxy)) {
       std::stringstream ss;
       ss << "No overlap found ... this X: " << this->min_x() << " => " << this->max_x() << " Y: " << this->min_y() << " => " << this->max_y()
      << " ... the other X: " << meta.min_x() << " => " << meta.max_x() << " Y: " << meta.min_y() << " => " << meta.max_y() << std::endl;
       throw larbys(ss.str());
     }
     return ImageMeta(maxx - minx, maxy - miny,
              (maxy - miny) / pixel_height(),
              (maxx - minx) / pixel_width(),
              minx, maxy, _plane);
   }
pixel_height()
double larcv::ImageMeta::pixel_height () const inline
Pixel vertical size.
Definition at line 97 of file ImageMeta.h.
References _height, _row_count, col(), index(), and row().
Referenced by dbscan::dbscanOutput::closestHitsInCluster(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::AStar3DAlgoProton::findpath(), larcv::AStar3DAlgo::findpath(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::ROIPad::PadMeta(), pos_y(), larcv::EmbedImage::process(), larcv::VertexImg::process(), larcv::Image2D::resize(), row(), and supera::Wire2Image2D().
 { return (_row_count ? _height / (double)_row_count : 0.); }
pixel_width()
double larcv::ImageMeta::pixel_width () const inline
Pixel horizontal size.
Definition at line 95 of file ImageMeta.h.
References _col_count, and _width.
Referenced by dbscan::dbscanOutput::closestHitsInCluster(), col(), larcv::Image2D::crop(), larcv::crop_meta(), larcv::AStar3DAlgoProton::findpath(), larcv::AStar3DAlgo::findpath(), larcv::SuperaMCROI::FormatMeta(), larcv::UBWireTool::getProjectedImagePixel(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::ROIPad::PadMeta(), pos_x(), larcv::VertexImg::process(), larcv::EmbedImage::process(), and larcv::Image2D::resize().
 { return (_col_count ? _width  / (double)_col_count : 0.); }
plane()
PlaneID_t larcv::ImageMeta::plane () const inline
PlaneID_t getter.
Definition at line 85 of file ImageMeta.h.
References _plane.
Referenced by larcv::ParticleROI::AppendBB(), larcv::ROI::AppendBB(), larcv::Image2D::compress(), larcv::Image2D::crop(), larcv::crop_meta(), dump(), larcv::SuperaMCROI::FormatMeta(), supera::Hit2Image2D(), larcv::ROIPad::PadMeta(), larcv::DBSCAN::process(), larcv::VertexImg::process(), larcv::EmbedImage::process(), larcv::NNCosine::process(), larcv::calcPeakADC::process(), larcv::hires::HiResImageDivider::process(), larcv::Image2D::resize(), and supera::Wire2Image2D().
 { return _plane;     }
pos_x()
double larcv::ImageMeta::pos_x (size_t col) const inline
Provide absolute horizontal coordinate of the center of a specified pixel row.
Definition at line 110 of file ImageMeta.h.
References _origin, col(), pixel_width(), and larcv::Point2D::x.
Referenced by larcv::AStar3DAlgo::downsampleAndFindPath().
 { return _origin.x + pixel_width() * col; }
pos_y()
double larcv::ImageMeta::pos_y (size_t row) const inline
Provide absolute vertical coordinate of the center of a specified pixel row.
Definition at line 112 of file ImageMeta.h.
References _origin, col(), pixel_height(), row(), and larcv::Point2D::y.
Referenced by larcv::AStar3DAlgo::downsampleAndFindPath(), larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
 { return _origin.y - pixel_height() * row; }
reset_origin()
void larcv::ImageMeta::reset_origin (double x, double y) inline
Reset origin coordinate.
Definition at line 123 of file ImageMeta.h.
References _origin, contains(), dump(), inclusive(), and overlap().
Referenced by larcv::Image2D::reset_origin().
 { _origin = Point2D(x,y); }
row()
size_t larcv::ImageMeta::row (double y) const
Provide vertical pixel index for a given vertical y position (in absolute coordinate)
Definition at line 28 of file ImageMeta.cxx.
References _height, _origin, pixel_height(), and larcv::Point2D::y.
Referenced by larcv::Image2D::crop(), larcv::crop_meta(), larcv::AStar3DAlgo::downsampleAndFindPath(), larcv::draw_bb(), larcv::fill_img_col(), larcv::UBWireTool::getProjectedImagePixel(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::Image2D::overlay(), pixel_height(), pos_y(), and supera::Wire2Image2D().
   {
     if(y <= (_origin.y - _height) || y > _origin.y) {
       std::stringstream ss;
       ss << "Requested col for y=" << y << " ... but the y (cols) spans only " << _origin.y - _height << " => " << _origin.y << "!" << std::endl;
       throw larbys(ss.str());
     }
     return (size_t)((_origin.y - y) / pixel_height());
   }
rows()
size_t larcv::ImageMeta::rows () const inline
rows accessor
Definition at line 91 of file ImageMeta.h.
References _row_count.
Referenced by larcv::ROIAna::area(), larcv::as_caffe_ndarray(), larcv::as_ndarray(), larcv::as_th2d(), larcv::Image2D::copy_compress(), larcv::AStarTracker::CreateDataImage(), larcv::RandomCropper::crop(), larcv::AStarTracker::CropFullImage2bounds(), larcv::DumpHiResCropImages::DumpBGRImage(), larcv::Image2D::eltwise(), dbscan::extractPointsFromImage(), dbscan::extractPointsFromImageBounds(), larcv::SuperaMCROI::FormatMeta(), larcv::Get2DRoi(), larcv::UBWireTool::getProjectedImagePixel(), larcv::Image2D::Image2D(), larcv::mat_to_image2d(), larcv::Image2D::multiRHS(), supera::OpDigit2Image2D(), larcv::Image2D::operator+=(), larcv::ROIPad::PadMeta(), larcv::Image2D::paint_col(), larcv::DBSCAN::process(), larcv::ChannelMax::process(), larcv::DumpHiResCropImages::process(), larcv::EmbedImage::process(), larcv::VertexImg::process(), larcv::NNCosine::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::hires::HiResImageDivider::process(), larcv::Project3D(), larcv::ProjectTo3D(), larcv::Image2D::reset(), larcv::Image2D::resize(), and larcv::Image2D::set_pixel().
 { return _row_count; }
tl()
const Point2D& larcv::ImageMeta::tl () const inline
Top-left corner point.
Definition at line 77 of file ImageMeta.h.
References _origin.
Referenced by larcv::MakeRect(), larcv::ROIPad::PadMeta(), larcv::Project3D(), and larcv::ProjectTo3D().
 { return _origin;                                          }
tr()
const Point2D larcv::ImageMeta::tr () const inline
Top-right corner point.
Definition at line 81 of file ImageMeta.h.
References _origin, _width, larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::Get2DRoi().
 { return Point2D(_origin.x + _width, _origin.y          ); }
update()
void larcv::ImageMeta::update (size_t row_count, size_t col_count) inline
Change # of vertical/horizontal pixels in meta data.
Definition at line 118 of file ImageMeta.h.
References _col_count, and _row_count.
Referenced by larcv::Image2D::clear(), larcv::hires::HiResImageDivider::cropEventImages(), and ImageMeta().
{
       _row_count = row_count;
       _col_count = col_count;
     }
width()
double larcv::ImageMeta::width () const inline
Width accessor.
Definition at line 87 of file ImageMeta.h.
References _width.
Referenced by larcv::Image2D::compress(), larcv::SuperaMCROI::FormatMeta(), larcv::Get2DRoi(), ImageMeta(), larcv::mat_to_image2d(), larcv::ROIPad::PadMeta(), larcv::hires::HiResImageDivider::process(), larcv::Project3D(), and larcv::ProjectTo3D().
 { return _width;     }
Friends And Related Function Documentation
Image2D
friend class Image2D friend
Definition at line 37 of file ImageMeta.h.
Member Data Documentation
_col_count
size_t larcv::ImageMeta::_col_count protected
of pixels in horizontal axis
Definition at line 142 of file ImageMeta.h.
Referenced by cols(), dump(), index(), operator==(), pixel_width(), and update().
_height
double larcv::ImageMeta::_height protected
Vertical size of an image in double floating precision (in original coordinate unit size)
Definition at line 141 of file ImageMeta.h.
Referenced by bl(), br(), height(), min_y(), operator==(), pixel_height(), and row().
_image_id
ImageIndex_t larcv::ImageMeta::_image_id protected
Associated image ID (of the same producer name)
Definition at line 138 of file ImageMeta.h.
Referenced by image_index().
_origin
larcv::Point2D larcv::ImageMeta::_origin protected
Absolute coordinate of the left top corner of an image.
Definition at line 139 of file ImageMeta.h.
Referenced by bl(), br(), col(), max_x(), max_y(), min_x(), min_y(), operator==(), pos_x(), pos_y(), reset_origin(), row(), tl(), and tr().
_plane
PlaneID_t larcv::ImageMeta::_plane protected
unique plane ID number
Definition at line 144 of file ImageMeta.h.
Referenced by inclusive(), operator==(), overlap(), and plane().
_row_count
size_t larcv::ImageMeta::_row_count protected
of pixels in vertical axis
Definition at line 143 of file ImageMeta.h.
Referenced by dump(), index(), operator==(), pixel_height(), rows(), and update().
_width
double larcv::ImageMeta::_width protected
Horizontal size of an image in double floating precision (in original coordinate unit size)
Definition at line 140 of file ImageMeta.h.
Referenced by br(), col(), max_x(), operator==(), pixel_width(), tr(), and width().
The documentation for this class was generated from the following files:
ImageMeta.h
ImageMeta.cxx