LArCV: larcv::SegDatumFillerBase Class Reference
larcv::SegDatumFillerBase Class Reference abstract
#include <SegDatumFillerBase.h>
Public Member Functions
SegDatumFillerBase (const std::string name="SegDatumFillerBase")
Default constructor.
~SegDatumFillerBase ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
bool is (const std::string &question) const
size_t rows () const
size_t cols () const
size_t channels () const
const std::vector< larcv::Image2D > & mean_image () const
const std::vector< float > & mean_adc () const
const std::vector< float > & data () const
const std::vector< float > & labels () const
virtual void child_configure (const PSet &)=0
virtual void child_initialize ()
virtual void child_batch_begin ()
virtual void child_batch_end ()
virtual void child_finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Member Functions
virtual void set_dimension (const std::vector< larcv::Image2D > &)=0
virtual void fill_entry_data (const std::vector< larcv::Image2D > &, const std::vector< larcv::Image2D > &)=0
const std::vector< float > & entry_data () const
const std::vector< float > & seg_entry_data () const
Protected Attributes
std::vector< float > _entry_data
std::vector< float > _seg_entry_data
size_t _nentries
size_t _num_channels
size_t _rows
size_t _cols
float _label
Private Member Functions
void batch_begin ()
void batch_end ()
Private Attributes
std::string _image_producer
std::string _seg_image_producer
std::vector< float > _data
std::vector< float > _labels
ProducerID_t _image_producer_id
ProducerID_t _seg_image_producer_id
size_t _current_entry
size_t _entry_data_size
std::vector< larcv::Image2D > _mean_image_v
std::vector< float > _mean_adc_v
Friends
class ThreadDatumFiller
Detailed Description
Definition at line 29 of file SegDatumFillerBase.h.
Constructor & Destructor Documentation
SegDatumFillerBase()
larcv::SegDatumFillerBase::SegDatumFillerBase (const std::string name = "SegDatumFillerBase")
Default constructor.
Definition at line 10 of file SegDatumFillerBase.cxx.
     : ProcessBase(name)
     , _nentries(kINVALID_SIZE)
     , _image_producer_id(kINVALID_PRODUCER)
     , _seg_image_producer_id(kINVALID_PRODUCER)
   {}
~SegDatumFillerBase()
larcv::SegDatumFillerBase::~SegDatumFillerBase () inline
Default destructor.
Definition at line 38 of file SegDatumFillerBase.h.
References configure(), finalize(), initialize(), is(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
batch_begin()
void larcv::SegDatumFillerBase::batch_begin () private
Definition at line 42 of file SegDatumFillerBase.cxx.
References _current_entry, _nentries, child_batch_begin(), and larcv::kINVALID_SIZE.
{
     if(_entry_image_size != kINVALID_SIZE)
       _image_data.resize(_nentries * _entry_image_size);
     if(_entry_label_size != kINVALID_SIZE)
       _label_data.resize(_nentries * _entry_label_size);
     for(auto& v : _image_data) v=0;
     for(auto& v : _label_data) v=0.;
     _current_entry = 0;
     this->child_batch_begin();
   }
batch_end()
void SegDatumFillerBase::batch_end () private
Definition at line 128 of file SegDatumFillerBase.cxx.
References child_batch_end().
   {
     this->child_batch_end();
   }
channels()
size_t larcv::SegDatumFillerBase::channels () const inline
Definition at line 52 of file SegDatumFillerBase.h.
References _num_channels.
 { return _num_channels; }
child_batch_begin()
virtual void larcv::SegDatumFillerBase::child_batch_begin () inline virtual
Definition at line 63 of file SegDatumFillerBase.h.
Referenced by batch_begin().
 {}
child_batch_end()
virtual void larcv::SegDatumFillerBase::child_batch_end () inline virtual
Definition at line 65 of file SegDatumFillerBase.h.
Referenced by batch_end().
 {}
child_configure()
virtual void larcv::SegDatumFillerBase::child_configure (const PSet &) pure virtual
Referenced by configure(), and labels().
child_finalize()
virtual void larcv::SegDatumFillerBase::child_finalize () inline virtual
Definition at line 67 of file SegDatumFillerBase.h.
References fill_entry_data(), and set_dimension().
Referenced by finalize().
 {}
child_initialize()
virtual void larcv::SegDatumFillerBase::child_initialize () inline virtual
Definition at line 61 of file SegDatumFillerBase.h.
Referenced by initialize().
 {}
cols()
size_t larcv::SegDatumFillerBase::cols () const inline
Definition at line 51 of file SegDatumFillerBase.h.
References _cols.
 { return _cols; }
configure()
void larcv::SegDatumFillerBase::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 20 of file SegDatumFillerBase.cxx.
References _image_producer, _seg_image_producer, child_configure(), and larcv::PSet::get().
Referenced by ~SegDatumFillerBase().
   {
     _image_producer = cfg.get<std::string>("InputProducer");
     _seg_image_producer = cfg.get<std::string>("SegProducer");
     this->child_configure(cfg);
   }
data()
const std::vector<float>& larcv::SegDatumFillerBase::data () const inline
Definition at line 56 of file SegDatumFillerBase.h.
References _data.
 { return _data;         }
entry_data()
const std::vector<float>& larcv::SegDatumFillerBase::entry_data () const inline protected
Definition at line 76 of file SegDatumFillerBase.h.
References _entry_data.
 { return _entry_data; }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
fill_entry_data()
virtual void larcv::SegDatumFillerBase::fill_entry_data (const std::vector< larcv::Image2D > & , const std::vector< larcv::Image2D > &) protected pure virtual
Referenced by child_finalize(), and process().
finalize()
void SegDatumFillerBase::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 134 of file SegDatumFillerBase.cxx.
References child_finalize().
Referenced by ~SegDatumFillerBase().
   { this->child_finalize(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SegDatumFillerBase::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 27 of file SegDatumFillerBase.cxx.
References _current_entry, _image_producer_id, _nentries, child_initialize(), larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, and LARCV_CRITICAL.
Referenced by ~SegDatumFillerBase().
   {
     if(_nentries == kINVALID_SIZE) {
       LARCV_CRITICAL() << "# entries not set... must be set @ initialize! " << std::endl;
       throw larbys();
     }
     _entry_image_size = _entry_label_size = kINVALID_SIZE;
     _current_entry = kINVALID_SIZE;
     _image_producer_id = kINVALID_PRODUCER;
     _label_producer_id = kINVALID_PRODUCER;
     this->child_initialize();
   }
is() [1/2]
bool larcv::SegDatumFillerBase::is (const std::string & question) const
Definition at line 17 of file SegDatumFillerBase.cxx.
Referenced by ~SegDatumFillerBase().
   { return (question == "DatumFiller"); }
is() [2/2]
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
labels()
const std::vector<float>& larcv::SegDatumFillerBase::labels () const inline
Definition at line 57 of file SegDatumFillerBase.h.
References _labels, and child_configure().
 { return _labels;       }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
mean_adc()
const std::vector<float>& larcv::SegDatumFillerBase::mean_adc () const inline
Definition at line 55 of file SegDatumFillerBase.h.
References _mean_adc_v.
 { return _mean_adc_v;   }
mean_image()
const std::vector<larcv::Image2D>& larcv::SegDatumFillerBase::mean_image () const inline
Definition at line 54 of file SegDatumFillerBase.h.
References _mean_image_v.
 { return _mean_image_v; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SegDatumFillerBase::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 56 of file SegDatumFillerBase.cxx.
References _current_entry, _data, _image_producer, _image_producer_id, _labels, _nentries, _seg_image_producer_id, fill_entry_data(), larcv::IOManager< T >::get_data(), larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, larcv::kProductImage2D, LARCV_CRITICAL, LARCV_INFO, larcv::IOManager< T >::producer_id(), and set_dimension().
Referenced by ~SegDatumFillerBase().
   {
     if(_current_entry == kINVALID_SIZE) {
       LARCV_CRITICAL() << "batch_begin() not called... Note this process is only meant to use with ThreadReadDriver!\n";
       throw larbys();
     }
     if(_image_producer_id == kINVALID_PRODUCER) {
       _image_producer_id = mgr.producer_id(kProductImage2D,_image_producer);
       if(_image_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Image producer " << _image_producer << " not valid!" << std::endl;
         throw larbys();
       }
       _label_producer_id = mgr.producer_id(kProductImage2D,_label_producer);
       if(_label_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Label producer " << _label_producer << " not valid!" << std::endl;
         throw larbys();
       }
     }
     auto const event_image_data = mgr.get_data(_image_producer_id);
     auto const event_label_data = mgr.get_data(_seg_image_producer_id);
     if(_entry_image_size == kINVALID_SIZE) {
       set_dimension(event_image_data, event_label_data);
       if(_entry_image_size == kINVALID_SIZE)
         LARCV_CRITICAL() << "Image data size per entry is not set!" << std::endl;
         throw larbys();
       }
       else LARCV_INFO() << "Image data size per entry: " << _event_image_size << std::endl;
       if(_entry_label_size == kINVALID_SIZE)
         LARCV_CRITICAL() << "Label data size per entry is not set!" << std::endl;
         throw larbys();
       }
rows()
size_t larcv::SegDatumFillerBase::rows () const inline
Definition at line 50 of file SegDatumFillerBase.h.
References _rows.
 { return _rows; }
seg_entry_data()
const std::vector<float>& larcv::SegDatumFillerBase::seg_entry_data () const inline protected
Definition at line 77 of file SegDatumFillerBase.h.
References _seg_entry_data.
 { return _seg_entry_data; }
set_dimension()
virtual void larcv::SegDatumFillerBase::set_dimension (const std::vector< larcv::Image2D > &) protected pure virtual
Referenced by child_finalize(), and process().
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Friends And Related Function Documentation
ThreadDatumFiller
friend class ThreadDatumFiller friend
Definition at line 30 of file SegDatumFillerBase.h.
Member Data Documentation
_cols
size_t larcv::SegDatumFillerBase::_cols protected
Definition at line 85 of file SegDatumFillerBase.h.
Referenced by cols().
_current_entry
size_t larcv::SegDatumFillerBase::_current_entry private
Definition at line 101 of file SegDatumFillerBase.h.
Referenced by batch_begin(), initialize(), and process().
_data
std::vector<float> larcv::SegDatumFillerBase::_data private
Definition at line 95 of file SegDatumFillerBase.h.
Referenced by data(), and process().
_entry_data
std::vector<float> larcv::SegDatumFillerBase::_entry_data protected
Definition at line 79 of file SegDatumFillerBase.h.
Referenced by entry_data().
_entry_data_size
size_t larcv::SegDatumFillerBase::_entry_data_size private
Definition at line 102 of file SegDatumFillerBase.h.
_image_producer
std::string larcv::SegDatumFillerBase::_image_producer private
Definition at line 92 of file SegDatumFillerBase.h.
Referenced by configure(), and process().
_image_producer_id
ProducerID_t larcv::SegDatumFillerBase::_image_producer_id private
Definition at line 98 of file SegDatumFillerBase.h.
Referenced by initialize(), and process().
_label
float larcv::SegDatumFillerBase::_label protected
Definition at line 86 of file SegDatumFillerBase.h.
_labels
std::vector<float> larcv::SegDatumFillerBase::_labels private
Definition at line 96 of file SegDatumFillerBase.h.
Referenced by labels(), and process().
_mean_adc_v
std::vector<float> larcv::SegDatumFillerBase::_mean_adc_v private
Definition at line 105 of file SegDatumFillerBase.h.
Referenced by mean_adc().
_mean_image_v
std::vector<larcv::Image2D> larcv::SegDatumFillerBase::_mean_image_v private
Definition at line 104 of file SegDatumFillerBase.h.
Referenced by mean_image().
_nentries
size_t larcv::SegDatumFillerBase::_nentries protected
Definition at line 82 of file SegDatumFillerBase.h.
Referenced by batch_begin(), initialize(), and process().
_num_channels
size_t larcv::SegDatumFillerBase::_num_channels protected
Definition at line 83 of file SegDatumFillerBase.h.
Referenced by channels().
_rows
size_t larcv::SegDatumFillerBase::_rows protected
Definition at line 84 of file SegDatumFillerBase.h.
Referenced by rows().
_seg_entry_data
std::vector<float> larcv::SegDatumFillerBase::_seg_entry_data protected
Definition at line 80 of file SegDatumFillerBase.h.
Referenced by seg_entry_data().
_seg_image_producer
std::string larcv::SegDatumFillerBase::_seg_image_producer private
Definition at line 93 of file SegDatumFillerBase.h.
Referenced by configure().
_seg_image_producer_id
ProducerID_t larcv::SegDatumFillerBase::_seg_image_producer_id private
Definition at line 99 of file SegDatumFillerBase.h.
Referenced by process().
The documentation for this class was generated from the following files:
SegDatumFillerBase.h
SegDatumFillerBase.cxx