LArCV: larcv::PIDImageMaker Class Reference
larcv::PIDImageMaker Class Reference
#include <PIDImageMaker.h>
Public Member Functions
PIDImageMaker (const std::string name="PIDImageMaker")
Default constructor.
~PIDImageMaker ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void SPIDRecoImgFiller (std::map< larcv::PlaneID_t, std::vector< larcv::Pixel2DCluster >> ev_pcluster_array, std::vector< larcv::Image2D > &p0_img_v, std::vector< larcv::Image2D > &p1_img_v)
void MPIDRecoImgFiller (std::map< larcv::PlaneID_t, std::vector< larcv::Pixel2DCluster >> ev_pcluster_array, std::vector< larcv::Image2D > &p01_img_v)
void VoidImgFiller (std::vector< larcv::Image2D > &p0_img_v, std::vector< larcv::Image2D > &p1_img_v)
void CROIImgFiller (ROI croi, std::vector< larcv::Image2D > &p01_img_v)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
size_t _nevents
size_t _nevents_passing_nueLL
std::pair< int, int > _outimage_dim
std::string _roi_input_producer
std::string _p0_roi_output_producer
std::string _p1_roi_output_producer
std::string _pgraph_producer
std::string _pixel2d_ctor_producer
std::string _pixel2d_img_producer
std::string _p0_image_producer
std::string _p1_image_producer
std::string _multi_image_producer
larocv::ImageClusterManager _alg_mgr
LArbysImageMaker _LArbysImageMaker
Detailed Description
Definition at line 35 of file PIDImageMaker.h.
Constructor & Destructor Documentation
PIDImageMaker()
larcv::PIDImageMaker::PIDImageMaker (const std::string name = "PIDImageMaker")
Default constructor.
Definition at line 11 of file PIDImageMaker.cxx.
Referenced by larcv::PIDImageMakerProcessFactory::create().
     : ProcessBase(name)
   {}
~PIDImageMaker()
larcv::PIDImageMaker::~PIDImageMaker () inline
Default destructor.
Definition at line 43 of file PIDImageMaker.h.
References configure(), CROIImgFiller(), finalize(), initialize(), MPIDRecoImgFiller(), process(), SPIDRecoImgFiller(), and VoidImgFiller().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::PIDImageMaker::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file PIDImageMaker.cxx.
References _LArbysImageMaker, _multi_image_producer, _nevents, _nevents_passing_nueLL, _outimage_dim, _p0_image_producer, _p0_roi_output_producer, _p1_image_producer, _p1_roi_output_producer, _pgraph_producer, _pixel2d_ctor_producer, _pixel2d_img_producer, _roi_input_producer, larcv::LArbysImageMaker::Configure(), and larcv::PSet::get().
Referenced by ~PIDImageMaker().
   {
     //input
     _roi_input_producer     = cfg.get<std::string>("ROIInputProducer");
     _pgraph_producer        = cfg.get<std::string>("RecoPGraphProducer");
     _pixel2d_ctor_producer  = cfg.get<std::string>("Pixel2DContourProducer");
     _pixel2d_img_producer   = cfg.get<std::string>("Pixel2DImageProducer");
     //output
     _p0_roi_output_producer = cfg.get<std::string>("P0ROIOutputProducer");
     _p1_roi_output_producer = cfg.get<std::string>("P1ROIOutputProducer");
     _p0_image_producer      = cfg.get<std::string>("P0OutImageProducer");
     _p1_image_producer      = cfg.get<std::string>("P1OutImageProducer");
     _multi_image_producer   = cfg.get<std::string>("MultiOutImageProducer");
     _outimage_dim           = cfg.get<std::pair<int, int>>("OutputImageDim");
     _LArbysImageMaker.Configure(cfg.get<larcv::PSet>("LArbysImageMaker"));
     _nevents = 0;
     _nevents_passing_nueLL = 0;
   }
CROIImgFiller()
void larcv::PIDImageMaker::CROIImgFiller (ROI croi, std::vector< larcv::Image2D > & p01_img_v)
Definition at line 262 of file PIDImageMaker.cxx.
References larcv::ROI::BB().
Referenced by process(), and ~PIDImageMaker().
{
     //croi
     for(size_t plane =0; plane <=2 ;++plane){
       ImageMeta this_plane_meta = croi.BB(plane);
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::PIDImageMaker::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 128 of file PIDImageMaker.cxx.
References _nevents, _nevents_passing_nueLL, and LARCV_DEBUG.
Referenced by ~PIDImageMaker().
   {
     LARCV_DEBUG()<<"================>>>>>>total events : "<<_nevents<<std::endl;
     LARCV_DEBUG()<<"========>>>>>>passing NueLL events : "<<_nevents_passing_nueLL<<std::endl;
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::PIDImageMaker::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 38 of file PIDImageMaker.cxx.
Referenced by ~PIDImageMaker().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MPIDRecoImgFiller()
void larcv::PIDImageMaker::MPIDRecoImgFiller (std::map< larcv::PlaneID_t, std::vector< larcv::Pixel2DCluster >> ev_pcluster_array, std::vector< larcv::Image2D > & p01_img_v)
Definition at line 196 of file PIDImageMaker.cxx.
References _nevents_passing_nueLL, _outimage_dim, LARCV_DEBUG, larcv::Image2D::resize(), larcv::Image2D::set_pixel(), and larcv::Image2D::size().
Referenced by process(), and ~PIDImageMaker().
{
     _nevents_passing_nueLL++;
     for (size_t plane = 0; plane< 3; ++plane){
       auto pcluster_v = ev_pcluster_array[plane];
       //IF there are not exaxtly 2 particles reconstructed
       // Here needs upates!
       if ( pcluster_v.size()!=2  || !(pcluster_v[0].size() * pcluster_v[1].size())) {
     //Need improve
     //LARCV_CRITICAL()<<"Not 2 particles on plane on"<<plane<<std::endl;
     Image2D img(_outimage_dim.first,_outimage_dim.second);
     img.resize(_outimage_dim.first,_outimage_dim.second, 0.0);
     p01_img_v.emplace_back(std::move(img));
     continue;
       }
       //IF there are 2 particles reconstructed
       Image2D img(_outimage_dim.first,_outimage_dim.second);
       img.resize(_outimage_dim.first,_outimage_dim.second, 0.0);
       //if(!(pcluster_v[0].size() * pcluster_v[1].size())) continue;
       int max_x = (pcluster_v[0].max_x() > pcluster_v[1].max_x() ? pcluster_v[0].max_x() : pcluster_v[1].max_x());
       int min_x = (pcluster_v[0].min_x() < pcluster_v[1].min_x() ? pcluster_v[0].min_x() : pcluster_v[1].min_x());
       int max_y = (pcluster_v[0].max_y() > pcluster_v[1].max_y() ? pcluster_v[0].max_y() : pcluster_v[1].max_y());
       int min_y = (pcluster_v[0].min_y() < pcluster_v[1].min_y() ? pcluster_v[0].min_y() : pcluster_v[1].min_y());
       LARCV_DEBUG()<<"created pixel 2d image size is "<<img.size()<<std::endl;
       for (size_t pid = 0; pid < 2; ++pid ){
     auto pcluster = pcluster_v[pid];
     //LARCV_DEBUG()<<"In MPID pid is "<<pid<<" with size of "<<pcluster.size()<<std::endl;
     for (auto pixel: pcluster) {
       //LARCV_DEBUG()<<"raw x "<<pixel.X()<<" raw y "<<pixel.Y()<<std::endl;
       //LARCV_DEBUG()<<"cal x "<<pixel.X() - pcluster.min_x()<<"cal y "<<pixel.Y() - pcluster.min_y()<<std::endl;
       if(pixel.X() - min_x > (_outimage_dim.first  -6) ||
          pixel.Y() - min_y > (_outimage_dim.second -6)) continue;
       img.set_pixel(pixel.X() - min_x+5,
             pixel.Y() - min_y+5,
             pixel.Intensity());
     }
       }
       p01_img_v.emplace_back(std::move(img));
     }
     //LARCV_DEBUG()<<"p01_img_v has size of "<<p01_img_v.size()<<std::endl;
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::PIDImageMaker::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 41 of file PIDImageMaker.cxx.
References _alg_mgr, _multi_image_producer, _nevents, _p0_image_producer, _p0_roi_output_producer, _p1_image_producer, _p1_roi_output_producer, _pgraph_producer, _pixel2d_ctor_producer, _pixel2d_img_producer, CROIImgFiller(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, MPIDRecoImgFiller(), and SPIDRecoImgFiller().
Referenced by ~PIDImageMaker().
   {
     _nevents++;
     //auto const event_roi           = (EventROI*)(mgr.get_data(kProductROI, _roi_input_producer));
     auto const event_pgraph        = (EventPGraph*) (mgr.get_data(kProductPGraph,_pgraph_producer));
     auto const event_img_pixel2d  = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pixel2d_img_producer));
     auto const event_ctor_pixel2d   = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_pixel2d_ctor_producer));
     auto event_p0_image      = (EventImage2D*)(mgr.get_data(kProductImage2D,_p0_image_producer));
     auto event_p1_image      = (EventImage2D*)(mgr.get_data(kProductImage2D,_p1_image_producer));
     auto event_multi_image   = (EventImage2D*)(mgr.get_data(kProductImage2D,_multi_image_producer));
     auto event_p0_roi        = (EventROI*)(mgr.get_data(kProductROI, _p0_roi_output_producer));
     auto event_p1_roi        = (EventROI*)(mgr.get_data(kProductROI, _p1_roi_output_producer));
     auto run    = (uint) event_pgraph->run();
     auto subrun = (uint) event_pgraph->subrun();
     auto event  = (uint) event_pgraph->event();
     auto entry  = (uint) mgr.current_entry();
     _alg_mgr.SetRSEE(run,subrun,event,entry);
     auto pgraph_v = event_pgraph->PGraphArray();
     if(pgraph_v.size()){
       ROI croi = pgraph_v[0].ParticleArray().front();
       std::vector<Image2D> p01_croi_img;
       CROIImgFiller(croi, p01_croi_img);
     }
     //if(pgraph_v.size()>1)
       //LARCV_DEBUG()<<"size of pgraph_v"<<pgraph_v.size()<<std::endl;
     //ROI croi = event_pgraph->ParticleArray();
     //auto ev_ctor_meta_array = event_ctor_pixel2d->MetaArray();
     //auto ev_roi              = event_roi->ROIArray();
     auto ev_p_array            = event_img_pixel2d->Pixel2DArray();
     auto ev_pcluster_array     = event_img_pixel2d->Pixel2DClusterArray(); //std::vector< ::larcv::Pixel2DCluster >
     auto ev_clustermeta_array  = event_img_pixel2d->ClusterMetaArray(); // std::vector< ::larcv::ImageMeta>
     auto ev_imagemeta_array    = event_img_pixel2d->MetaArray();
     std::vector<Image2D> p0_img_v;
     p0_img_v.clear();
     std::vector<Image2D> p1_img_v;
     p1_img_v.clear();
     std::vector<Image2D> p01_img_v;
     p01_img_v.clear();
     // checking how many planes have reco pgrapgh
     //if (ev_pcluster_array.size() ==3) {
     if (ev_pcluster_array.size() > 0 ) {
       ROI proi;
       event_p0_roi->clear();
       event_p0_roi->Append(proi);
       event_p1_roi->clear();
       event_p1_roi->Append(proi);
       SPIDRecoImgFiller(ev_pcluster_array, p0_img_v, p1_img_v);
       MPIDRecoImgFiller(ev_pcluster_array, p01_img_v);
       for(auto each : p0_img_v ) event_p0_image->Append(each);
       for(auto each : p1_img_v ) event_p1_image->Append(each);
       for(auto each : p01_img_v) event_multi_image->Append(each);
       return true;
     }else return false;
     /*else{
       //LARCV_CRITICAL()<<"No pixel2d clusters found. "<<std::endl;
       LARCV_DEBUG()<<"run"<<run
            <<"subrun"<<subrun
            <<"event"<<event
            <<"pixel2dclusterarraysize"<<ev_pcluster_array.size()<<std::endl;
       VoidImgFiller(p0_img_v,p1_img_v);
     }
     //event_p0_image->Emplace(std::move(p0_img_v));
     //event_p1_image->Emplace(std::move(p1_img_v));
     for(auto each : p0_img_v) event_p0_image->Append(each);
     for(auto each : p1_img_v) event_p1_image->Append(each);
     */
     //return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SPIDRecoImgFiller()
void larcv::PIDImageMaker::SPIDRecoImgFiller (std::map< larcv::PlaneID_t, std::vector< larcv::Pixel2DCluster >> ev_pcluster_array, std::vector< larcv::Image2D > & p0_img_v, std::vector< larcv::Image2D > & p1_img_v)
Definition at line 134 of file PIDImageMaker.cxx.
References _nevents_passing_nueLL, _outimage_dim, LARCV_DEBUG, larcv::Image2D::resize(), larcv::Image2D::set_pixel(), and larcv::Image2D::size().
Referenced by process(), and ~PIDImageMaker().
{
     _nevents_passing_nueLL++;
     for (size_t plane = 0; plane< 3; ++plane){
       auto pcluster_v = ev_pcluster_array[plane];
       if (pcluster_v.size()!=2) {
     //Need improve
     //LARCV_CRITICAL()<<"Not 2 particles on plane "<<plane<<std::endl;
     Image2D img(_outimage_dim.first,_outimage_dim.second);
     img.resize(_outimage_dim.first,_outimage_dim.second, 0.0);
     p0_img_v.emplace_back(std::move(img));
     p1_img_v.emplace_back(std::move(img));
     continue;
       }
       for (size_t pid = 0; pid < 2; ++pid ){
     auto pcluster = pcluster_v[pid];
     //LARCV_DEBUG()<<"pid is "<<pid<<" with size of "<<pcluster.size()<<std::endl;
     Image2D img(_outimage_dim.first,_outimage_dim.second);
     if (!pcluster.size()) {
       img.resize(_outimage_dim.first,_outimage_dim.second, 0.0);
     }
     else{
       LARCV_DEBUG()<<"max_x "<<pcluster.max_x()
                <<" min_x "<<pcluster.min_x()
                <<" max_y "<<pcluster.max_y()
                <<" min_y "<<pcluster.min_y()
                <<std::endl;
       /*    size_t rows = std::abs(pcluster.max_x() - pcluster.min_x());
         size_t cols = std::abs(pcluster.max_y() - pcluster.min_y());
         LARCV_DEBUG()<<"creating rows is "<<rows<< " and creating cols is "<<cols;
         Image2D img(rows+1, cols+1);*/
     //img.clear_data();
       LARCV_DEBUG()<<"created pixel 2d image size is "<<img.size()<<std::endl;
       for (auto pixel: pcluster) {
         //LARCV_DEBUG()<<"raw x "<<pixel.X()<<" raw y "<<pixel.Y()<<std::endl;
         //LARCV_DEBUG()<<"cal x "<<pixel.X() - pcluster.min_x()<<"cal y "<<pixel.Y() - pcluster.min_y()<<std::endl;
         if(pixel.X() - pcluster.min_x() > (_outimage_dim.first  -1) ||
            pixel.Y() - pcluster.min_y() > (_outimage_dim.second -1)) continue;
         img.set_pixel(pixel.X() - pcluster.min_x(),
               pixel.Y() - pcluster.min_y(),
               pixel.Intensity());
         //if(plane==2)LARCV_DEBUG()<<pixel.X() - pcluster.min_x()<<", "<<pixel.Y() - pcluster.min_y()<<", "<<pixel.Intensity()<<std::endl;
       }
     }
     if (pid == 0 ) p0_img_v.emplace_back(std::move(img));
     if (pid == 1 ) p1_img_v.emplace_back(std::move(img));
       }
     }
   }
VoidImgFiller()
void larcv::PIDImageMaker::VoidImgFiller (std::vector< larcv::Image2D > & p0_img_v, std::vector< larcv::Image2D > & p1_img_v)
Definition at line 250 of file PIDImageMaker.cxx.
References _outimage_dim, and larcv::Image2D::resize().
Referenced by ~PIDImageMaker().
{
     for (size_t plane = 0; plane< 3; ++plane){
       Image2D img(_outimage_dim.first,_outimage_dim.second);
       img.resize(_outimage_dim.first,_outimage_dim.second, 0.0);
       p0_img_v.emplace_back(std::move(img));
       p1_img_v.emplace_back(std::move(img));
     }
   }
Member Data Documentation
_alg_mgr
larocv::ImageClusterManager larcv::PIDImageMaker::_alg_mgr private
Definition at line 88 of file PIDImageMaker.h.
Referenced by process().
_LArbysImageMaker
LArbysImageMaker larcv::PIDImageMaker::_LArbysImageMaker private
Definition at line 90 of file PIDImageMaker.h.
Referenced by configure().
_multi_image_producer
std::string larcv::PIDImageMaker::_multi_image_producer private
Definition at line 86 of file PIDImageMaker.h.
Referenced by configure(), and process().
_nevents
size_t larcv::PIDImageMaker::_nevents private
Definition at line 70 of file PIDImageMaker.h.
Referenced by configure(), finalize(), and process().
_nevents_passing_nueLL
size_t larcv::PIDImageMaker::_nevents_passing_nueLL private
Definition at line 71 of file PIDImageMaker.h.
Referenced by configure(), finalize(), MPIDRecoImgFiller(), and SPIDRecoImgFiller().
_outimage_dim
std::pair<int, int> larcv::PIDImageMaker::_outimage_dim private
Definition at line 73 of file PIDImageMaker.h.
Referenced by configure(), MPIDRecoImgFiller(), SPIDRecoImgFiller(), and VoidImgFiller().
_p0_image_producer
std::string larcv::PIDImageMaker::_p0_image_producer private
Definition at line 83 of file PIDImageMaker.h.
Referenced by configure(), and process().
_p0_roi_output_producer
std::string larcv::PIDImageMaker::_p0_roi_output_producer private
Definition at line 76 of file PIDImageMaker.h.
Referenced by configure(), and process().
_p1_image_producer
std::string larcv::PIDImageMaker::_p1_image_producer private
Definition at line 84 of file PIDImageMaker.h.
Referenced by configure(), and process().
_p1_roi_output_producer
std::string larcv::PIDImageMaker::_p1_roi_output_producer private
Definition at line 77 of file PIDImageMaker.h.
Referenced by configure(), and process().
_pgraph_producer
std::string larcv::PIDImageMaker::_pgraph_producer private
Definition at line 79 of file PIDImageMaker.h.
Referenced by configure(), and process().
_pixel2d_ctor_producer
std::string larcv::PIDImageMaker::_pixel2d_ctor_producer private
Definition at line 80 of file PIDImageMaker.h.
Referenced by configure(), and process().
_pixel2d_img_producer
std::string larcv::PIDImageMaker::_pixel2d_img_producer private
Definition at line 81 of file PIDImageMaker.h.
Referenced by configure(), and process().
_roi_input_producer
std::string larcv::PIDImageMaker::_roi_input_producer private
Definition at line 75 of file PIDImageMaker.h.
Referenced by configure().
The documentation for this class was generated from the following files:
PIDImageMaker.h
PIDImageMaker.cxx