LArCV: larcv::NNCosine Class Reference
larcv::NNCosine Class Reference
#include <NNCosine.h>
Public Member Functions
NNCosine (const std::string name="NNCosine")
Default constructor.
~NNCosine ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::string finput_producer
std::string foutput_producer
std::vector< float > fthresholds
std::vector< int > fminhits
std::vector< float > fradii
bool fmakehitmarker
std::string fhitmarkerpro
Detailed Description
Definition at line 30 of file NNCosine.h.
Constructor & Destructor Documentation
NNCosine()
larcv::NNCosine::NNCosine (const std::string name = "NNCosine")
Default constructor.
Definition at line 18 of file NNCosine.cxx.
Referenced by larcv::NNCosineProcessFactory::create().
     : ProcessBase(name)
   {}
~NNCosine()
larcv::NNCosine::~NNCosine () inline
Default destructor.
Definition at line 38 of file NNCosine.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::NNCosine::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 22 of file NNCosine.cxx.
References fhitmarkerpro, finput_producer, fmakehitmarker, fminhits, foutput_producer, fradii, fthresholds, and larcv::PSet::get().
Referenced by ~NNCosine().
   {
     finput_producer  = cfg.get<std::string>("InputProducer");
     foutput_producer = cfg.get<std::string>("OutputProducer","nncosine");
     fthresholds      = cfg.get<std::vector<float> >("PlaneThresholds");
     fminhits         = cfg.get<std::vector<int> >("PlaneMinHits");
     fradii           = cfg.get<std::vector<float> >("PlaneRadii");
     fmakehitmarker   = cfg.get<bool>("MakeHitMarkerImage",true);
     fhitmarkerpro    = cfg.get<std::string>("HitMarkerProducer","nncosine_hitmarker");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::NNCosine::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 162 of file NNCosine.cxx.
Referenced by ~NNCosine().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::NNCosine::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 33 of file NNCosine.cxx.
Referenced by ~NNCosine().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::NNCosine::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 36 of file NNCosine.cxx.
References larcv::ImageMeta::cols(), larcv::EventImage2D::Emplace(), fhitmarkerpro, finput_producer, fminhits, foutput_producer, fradii, fthresholds, larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::kProductImage2D, larcv::Image2D::paint(), larcv::ImageMeta::plane(), larcv::ImageMeta::rows(), larcv::Image2D::set_pixel(), and ann::ANNAlgo::setPoint().
Referenced by ~NNCosine().
   {
     larcv::EventImage2D* event_imgs = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, finput_producer );
     larcv::EventImage2D* event_out  = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, foutput_producer );
     larcv::EventImage2D* event_hit  = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, fhitmarkerpro );
     // y-plane only for now
     std::vector< larcv::Image2D > angleimg_v;
     std::vector< larcv::Image2D > hitimg_v;
     for ( auto const& img : event_imgs->Image2DArray() ) {
       larcv::ImageMeta const& meta = img.meta();
       int plane = (int)meta.plane();
       // find hit pixels
       std::vector<std::vector<double> > hitpixels;
       for (int r=0; r<meta.rows(); r++) {
     for (int c=0; c<meta.cols(); c++) {
       if ( img.pixel( r, c )>fthresholds.at(plane) ) {
         std::vector<double> hit(2,0.0);
         hit.at(0) = c;
         hit.at(1) = r;
         hitpixels.emplace_back( hit );
       }
     }
       }
       // setup kdtree
       ann::ANNAlgo algo( hitpixels.size(), 2 );
       for (int i=0; i<(int)hitpixels.size(); i++) {
     algo.setPoint( i, hitpixels.at(i) );
       }
       algo.initialize();
       // make output images
       larcv::Image2D angle_img(meta);
       larcv::Image2D hit_px(meta);
       angle_img.paint(0.0);
       hit_px.paint(0.0);
       // perform NN cosine calculations
       for (int i=0; i<(int)hitpixels.size(); i++) {
     std::vector<int> nn = algo.regionQuery( i, fradii.at(plane), 0.0 );
     double ave_ang = 0.0;
     double maxnorm = 0.0;
     double totw = 0.0;
     if ( (int)nn.size()<fminhits.at(plane) )
       continue;
     double origin[2] = { hitpixels.at(i).at(0), hitpixels.at(i).at(1) };
     hit_px.set_pixel( origin[1], origin[0], 1.0 ); // mark hits
     //  std::cout << "-----------------"<< std::endl;
     //  std::cout << "[hit " << i << "] " << "px=(" << origin[0] << "," << origin[1] << ") "
     //        << " pos=(" << meta.pos_x( origin[0] ) << ", " << meta.pos_y( origin[1] ) << ") " << std::endl;
     for (int inn=0; inn<(int)nn.size(); inn++) {
       int hitidx = nn.at(inn);
       if ( hitidx==i ) continue; // do not include self
       double pos[2] = { hitpixels.at(hitidx).at(0), hitpixels.at(hitidx).at(1) };
       // make direction vector
       double diffnn[2] = { pos[0]-origin[0], pos[1]-origin[1] };
       double normdiff = 0.;
       for (int v=0;v<2; v++) normdiff += diffnn[v]*diffnn[v];
       normdiff = sqrt(normdiff);
       for (int v=0; v<2; v++) diffnn[v] /= normdiff;
       if ( normdiff>maxnorm ) maxnorm = normdiff;
       // for debug
       //      double hitx = meta.pos_x( pos[0] );
       //      double hity = meta.pos_y( pos[1] );
       //      std::cout << "  nn=" << inn << " hitid=" << hitidx << ": "
 //          << " px=" << pos[0] << "," << pos[1]
 //          << " pos=(" << hitx << "," << hity << ") "
 //          << " dist=" << normdiff << ": dir=(" << diffnn[0]  << "," << diffnn[1] << ")" << std::endl;
       // adjust vector by quadrant
       if ( diffnn[0]<0 && diffnn[1]<=0 ) {
         diffnn[0] *=-1.0;
         diffnn[1] *=-1.0;
       }
       else if ( diffnn[0]<0 && diffnn[1]>0 ) {
         diffnn[0] *=-1.0;
         diffnn[1] *=-1.0;
       }
       // weight
       double w = img.pixel( (int)(hitpixels.at(hitidx).at(1)+0.1), (int)(hitpixels.at(hitidx).at(0)+0.1) );
       if ( w<fthresholds.at(plane) ) {
         std::cout << "mistake" << std::endl;
         assert(false);
       }
       totw += fabs(w);
       double diffang = atan2( diffnn[1], diffnn[0] );
       ave_ang += w*diffang;
     }
     ave_ang /= totw;
     //       std::cout << i << ": nn=" << nn.size()
     //      << " w=" << totw
     //      << " ang=" << ave_ang*180.0/3.14159
     //      << " maxnorm=" << maxnorm
     //      << std::endl;
     if ( !std::isnan(ave_ang) ) {
       angle_img.set_pixel( (int)hitpixels.at(i).at(1), (int)hitpixels.at(i).at(0), ave_ang );
     }
       }//loop over hit pixels
       angleimg_v.emplace_back( angle_img );
       hitimg_v.emplace_back( hit_px );
     }// loop over input images
     event_out->Emplace( std::move(angleimg_v) );
     event_hit->Emplace( std::move(hitimg_v) );
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fhitmarkerpro
std::string larcv::NNCosine::fhitmarkerpro
Definition at line 54 of file NNCosine.h.
Referenced by configure(), and process().
finput_producer
std::string larcv::NNCosine::finput_producer
Definition at line 48 of file NNCosine.h.
Referenced by configure(), and process().
fmakehitmarker
bool larcv::NNCosine::fmakehitmarker
Definition at line 53 of file NNCosine.h.
Referenced by configure().
fminhits
std::vector<int> larcv::NNCosine::fminhits
Definition at line 51 of file NNCosine.h.
Referenced by configure(), and process().
foutput_producer
std::string larcv::NNCosine::foutput_producer
Definition at line 49 of file NNCosine.h.
Referenced by configure(), and process().
fradii
std::vector<float> larcv::NNCosine::fradii
Definition at line 52 of file NNCosine.h.
Referenced by configure(), and process().
fthresholds
std::vector<float> larcv::NNCosine::fthresholds
Definition at line 50 of file NNCosine.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
NNCosine.h
NNCosine.cxx