LArCV: supera::ParamsPixel2D Class Reference
supera::ParamsPixel2D Class Reference
User defined class ParamsPixel2D ...
#include <ParamsPixel2D.h>
Public Member Functions
ParamsPixel2D ()
Default constructor.
~ParamsPixel2D ()
Default destructor.
void configure (const supera::Config_t &)
const std::string & OutPixel2DLabel () const
Private Attributes
std::string _out_pixel2d_producer
Detailed Description
User defined class ParamsPixel2D ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file ParamsPixel2D.h.
Constructor & Destructor Documentation
ParamsPixel2D()
supera::ParamsPixel2D::ParamsPixel2D () inline
Default constructor.
Definition at line 31 of file ParamsPixel2D.h.
 {}
~ParamsPixel2D()
supera::ParamsPixel2D::~ParamsPixel2D () inline
Default destructor.
Definition at line 34 of file ParamsPixel2D.h.
References configure().
 {}
Member Function Documentation
configure()
void supera::ParamsPixel2D::configure (const supera::Config_t & cfg)
Definition at line 8 of file ParamsPixel2D.cxx.
References _out_pixel2d_producer, and larcv::PSet::get().
Referenced by larcv::SuperaMCPCluster::configure(), larcv::SuperaKeyPointCluster::configure(), and ~ParamsPixel2D().
   {
     _out_pixel2d_producer = cfg.get<std::string>("OutPixel2DLabel", "");
   }
OutPixel2DLabel()
const std::string& supera::ParamsPixel2D::OutPixel2DLabel () const inline
Definition at line 41 of file ParamsPixel2D.h.
References _out_pixel2d_producer.
Referenced by larcv::SuperaMCPCluster::process(), and larcv::SuperaKeyPointCluster::process().
 { return _out_pixel2d_producer;  }
Member Data Documentation
_out_pixel2d_producer
std::string supera::ParamsPixel2D::_out_pixel2d_producer private
Definition at line 45 of file ParamsPixel2D.h.
Referenced by configure(), and OutPixel2DLabel().
The documentation for this class was generated from the following files:
ParamsPixel2D.h
ParamsPixel2D.cxx