LArCV: larcv::ResizeImageProcessFactory Class Reference
larcv::ResizeImageProcessFactory Class Reference
#include <ResizeImage.h>
Public Member Functions
ResizeImageProcessFactory ()
ctor
~ResizeImageProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 61 of file ResizeImage.h.
Constructor & Destructor Documentation
ResizeImageProcessFactory()
larcv::ResizeImageProcessFactory::ResizeImageProcessFactory () inline
ctor
Definition at line 64 of file ResizeImage.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ResizeImage",this); }
~ResizeImageProcessFactory()
larcv::ResizeImageProcessFactory::~ResizeImageProcessFactory () inline
dtor
Definition at line 66 of file ResizeImage.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ResizeImageProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 68 of file ResizeImage.h.
References larcv::ResizeImage::ResizeImage().
 { return new ResizeImage(instance_name); }
The documentation for this class was generated from the following file:
ResizeImage.h