LArCV: larcv::HistADC Class Reference
larcv::HistADC Class Reference
#include <HistADC.h>
Public Member Functions
HistADC (const std::string name="HistADC")
Default constructor.
~HistADC ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::vector< TH1D * > m_hADC_v
std::string fHiResCropProducer
std::string fROIProducer
int fPlane0Thresh
int fPlane1Thresh
int fPlane2Thresh
bool fFillCosmic
TTree * m_tree
int m_plane
int m_neutrino
int m_npixels
float m_sum
float m_edep
Detailed Description
Definition at line 31 of file HistADC.h.
Constructor & Destructor Documentation
HistADC()
larcv::HistADC::HistADC (const std::string name = "HistADC")
Default constructor.
Definition at line 13 of file HistADC.cxx.
Referenced by larcv::HistADCProcessFactory::create().
     : ProcessBase(name)
   {}
~HistADC()
larcv::HistADC::~HistADC () inline
Default destructor.
Definition at line 39 of file HistADC.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::HistADC::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 17 of file HistADC.cxx.
References fFillCosmic, fHiResCropProducer, fPlane0Thresh, fPlane1Thresh, fPlane2Thresh, fROIProducer, and larcv::PSet::get().
Referenced by ~HistADC().
   {
     fHiResCropProducer = cfg.get<std::string>("HiResCropProducer");
     fROIProducer       = cfg.get<std::string>("ROIProducer");
     fPlane0Thresh      = cfg.get<int>("Plane0Thresh");
     fPlane1Thresh      = cfg.get<int>("Plane1Thresh");
     fPlane2Thresh      = cfg.get<int>("Plane2Thresh");
     fFillCosmic        = cfg.get<bool>("FillCosmic");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::HistADC::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 120 of file HistADC.cxx.
References larcv::ProcessBase::has_ana_file(), and m_tree.
Referenced by ~HistADC().
   {
     if ( has_ana_file() ) {
       //for(auto& p : m_hADC_v) if(p) p->Write();
       m_tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::HistADC::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 27 of file HistADC.cxx.
References m_edep, m_hADC_v, m_neutrino, m_npixels, m_plane, m_sum, and m_tree.
Referenced by ~HistADC().
   {
     // clear the vector
     for (auto &p : m_hADC_v ) {
       delete p;
       p = NULL;
     }
     m_hADC_v.clear();
     m_tree = new TTree("adctree","ADC/pixel summary of cropped regions");
     m_tree->Branch( "plane",&m_plane,"plane/I");
     m_tree->Branch( "isneutrino",&m_neutrino,"isneutrino/I");
     m_tree->Branch( "npixels",&m_npixels,"npixels/I");
     m_tree->Branch( "adcsum",&m_sum,"adcsum/F");
     m_tree->Branch( "edep",&m_edep,"edep/F");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::HistADC::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 45 of file HistADC.cxx.
References fHiResCropProducer, fPlane0Thresh, fPlane1Thresh, fPlane2Thresh, fROIProducer, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, larcv::kROICosmic, m_edep, m_hADC_v, m_neutrino, m_npixels, m_plane, m_sum, and m_tree.
Referenced by ~HistADC().
   {
     auto event_image = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fHiResCropProducer));
     auto event_roi         = (larcv::EventROI*)(mgr.get_data(kProductROI,fROIProducer));
     auto roi = event_roi->at(0);
     // if ( fFillCosmic && roi.Type()!=kROICosmic)
     //   return true;
     // if ( !fFillCosmic && roi.Type()==kROICosmic )
     //   return true;
     if ( roi.Type()!=kROICosmic ) {
       m_neutrino = 1;
       m_edep = roi.EnergyDeposit();
     }
     else {
       m_neutrino = 0;
       m_edep = 0.;
     }
     //m_neutrino = ( fFillCosmic ) ? 0 : 1;
     for ( auto const& img: event_image->Image2DArray() ) {
       auto const plane = img.meta().plane();
       if(m_hADC_v.size() <= plane) m_hADC_v.resize(plane+1,nullptr);
       // if(!m_hADC_v[plane]) {
       //    if (fFillCosmic )
       //      m_hADC_v[plane] = new TH1D(Form("hADCsum_%s_Plane%02hu_cosmic",fHiResCropProducer.c_str(),plane),
       //                     Form("ADC Values for Plane %hu",plane),
       //                     500,0,10e3);
       //    else
       //      m_hADC_v[plane] = new TH1D(Form("hADCsum_%s_Plane%02hu_neutrino",fHiResCropProducer.c_str(),plane),
       //                     Form("ADC Values for Plane %hu",plane),
       //                     500,0,10e3);
       // }
       m_sum = 0.0;
       m_npixels = 0;
       auto const& adc_v = img.as_vector();
       float thresh = 0;
       switch ( plane ) {
       case 0:
     thresh = fPlane0Thresh;
     break;
       case 1:
     thresh = fPlane1Thresh;
     break;
       case 2:
     thresh = fPlane2Thresh;
     break;
       }
       for ( auto const& adc : adc_v ) {
     if ( adc>thresh ) {
       m_sum += adc;
       m_npixels++;
     }
       }
       //auto& p_hADC = m_hADC_v[plane];
       //std::cout << sum << std::endl;
       //p_hADC->Fill( m_sum );
       m_plane = plane;
       m_tree->Fill();
     }//end of loop over plane image
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fFillCosmic
bool larcv::HistADC::fFillCosmic
Definition at line 55 of file HistADC.h.
Referenced by configure().
fHiResCropProducer
std::string larcv::HistADC::fHiResCropProducer
Definition at line 50 of file HistADC.h.
Referenced by configure(), and process().
fPlane0Thresh
int larcv::HistADC::fPlane0Thresh
Definition at line 52 of file HistADC.h.
Referenced by configure(), and process().
fPlane1Thresh
int larcv::HistADC::fPlane1Thresh
Definition at line 53 of file HistADC.h.
Referenced by configure(), and process().
fPlane2Thresh
int larcv::HistADC::fPlane2Thresh
Definition at line 54 of file HistADC.h.
Referenced by configure(), and process().
fROIProducer
std::string larcv::HistADC::fROIProducer
Definition at line 51 of file HistADC.h.
Referenced by configure(), and process().
m_edep
float larcv::HistADC::m_edep
Definition at line 62 of file HistADC.h.
Referenced by initialize(), and process().
m_hADC_v
std::vector<TH1D*> larcv::HistADC::m_hADC_v
Definition at line 49 of file HistADC.h.
Referenced by initialize(), and process().
m_neutrino
int larcv::HistADC::m_neutrino
Definition at line 59 of file HistADC.h.
Referenced by initialize(), and process().
m_npixels
int larcv::HistADC::m_npixels
Definition at line 60 of file HistADC.h.
Referenced by initialize(), and process().
m_plane
int larcv::HistADC::m_plane
Definition at line 58 of file HistADC.h.
Referenced by initialize(), and process().
m_sum
float larcv::HistADC::m_sum
Definition at line 61 of file HistADC.h.
Referenced by initialize(), and process().
m_tree
TTree* larcv::HistADC::m_tree
Definition at line 57 of file HistADC.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
HistADC.h
HistADC.cxx