LArCV: larcv::ROIMaskProcessFactory Class Reference
larcv::ROIMaskProcessFactory Class Reference
#include <ROIMask.h>
Public Member Functions
ROIMaskProcessFactory ()
ctor
~ROIMaskProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 66 of file ROIMask.h.
Constructor & Destructor Documentation
ROIMaskProcessFactory()
larcv::ROIMaskProcessFactory::ROIMaskProcessFactory () inline
ctor
Definition at line 69 of file ROIMask.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ROIMask",this); }
~ROIMaskProcessFactory()
larcv::ROIMaskProcessFactory::~ROIMaskProcessFactory () inline
dtor
Definition at line 71 of file ROIMask.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ROIMaskProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 73 of file ROIMask.h.
References larcv::ROIMask::ROIMask().
 { return new ROIMask(instance_name); }
The documentation for this class was generated from the following file:
ROIMask.h