LArCV: larcv::Run3DTracker Class Reference
larcv::Run3DTracker Class Reference
#include <Run3DTracker.h>
Public Member Functions
Run3DTracker (const std::string name="Run3DTracker")
Default constructor.
~Run3DTracker ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void SetSplineLocation (const std::string &fpath)
void SetLLOutName (const std::string &foutll)
void advance_larlite ()
void FillMC (const std::vector< ROI > &mc_roi_v)
void ClearEvent ()
void ClearVertex ()
void SetOutDir (std::string s)
bool IsGoodVertex (int run, int subrun, int event, int vtxID)
bool IsGoodEntry (int run, int subrun, int event)
void ReadVertexFile (std::string filename)
std::vector< TVector3 > GetJarretVertex (int run, int subrun, int event)
void finalize ()
void MCevaluation ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
int iTrack
larlite::storage_manager _storage
larcv::AStarTracker tracker
std::vector< std::vector< int > > _vertexInfo
double NeutrinoEnergyTh
double NeutrinoEnergyReco
double Ep_t
double Em_t
int _run
int _subrun
int _event
int _nentry
int _entry
int _Nreco
int _vtx_id
int NvertexSubmitted
int NgoodReco
int NtracksReco
std::vector< std::string > checkEvents
std::string _filename
TTree * _recoTree
std::vector< int > _trk_id_v
std::vector< double > _E_muon_v
std::vector< double > _E_proton_v
std::vector< double > _Length_v
std::vector< double > _Avg_Ion_v
std::vector< double > _Avg_IonY_v
std::vector< double > _vertexPhi
std::vector< double > _vertexTheta
std::vector< double > _closestWall
std::vector< double > _Ion_5cm_v
std::vector< double > _Ion_10cm_v
std::vector< double > _Ion_tot_v
std::vector< double > _IonY_5cm_v
std::vector< double > _IonY_10cm_v
std::vector< double > _IonY_tot_v
std::vector< double > _Trunc_dQdX1_v
std::vector< double > _Trunc_dQdX3_v
std::vector< double > _IondivLength_v
std::vector< std::vector< double > > _trackQ3_v
std::vector< std::vector< double > > _trackQ5_v
std::vector< std::vector< double > > _trackQ10_v
std::vector< std::vector< double > > _trackQ20_v
std::vector< std::vector< double > > _trackQ30_v
std::vector< std::vector< double > > _trackQ50_v
std::vector< std::vector< double > > _TotalADCvalues_v
std::vector< std::vector< double > > _Angle_v
std::vector< bool > _Reco_goodness_v
std::vector< bool > _track_Goodness_v
std::vector< larlite::event_track > _EventRecoVertices
std::vector< TVector3 > MCVertices
TVector3 MCvertex
TVector3 RecoVertex
TVector3 _RecoVertex
bool GoodVertex
bool _missingTrack
bool _nothingReconstructed
bool _tooShortDeadWire
bool _tooShortFaintTrack
bool _tooManyTracksAtVertex
bool _possibleCosmic
bool _possiblyCrossing
bool _branchingTracks
bool _jumpingTracks
float _vtx_x
float _vtx_y
float _vtx_z
double _Ep_t
double _Em_t
double _Ee_t
double _MuonStartPoint_X
double _ProtonStartPoint_X
double _ElectronStartPoint_X
double _MuonStartPoint_Y
double _ProtonStartPoint_Y
double _ElectronStartPoint_Y
double _MuonStartPoint_Z
double _ProtonStartPoint_Z
double _ElectronStartPoint_Z
double _MuonEndPoint_X
double _ProtonEndPoint_X
double _ElectronEndPoint_X
double _MuonEndPoint_Y
double _ProtonEndPoint_Y
double _ElectronEndPoint_Y
double _MuonEndPoint_Z
double _ProtonEndPoint_Z
double _ElectronEndPoint_Z
std::string _input_pgraph_producer
std::string _img2d_producer
std::string _par_pix_producer
std::string _true_roi_producer
std::string _spline_file
std::string _foutll
std::string out_dir
bool _mask_shower
Detailed Description
Definition at line 36 of file Run3DTracker.h.
Constructor & Destructor Documentation
Run3DTracker()
larcv::Run3DTracker::Run3DTracker (const std::string name = "Run3DTracker")
Default constructor.
Definition at line 52 of file Run3DTracker.cxx.
Referenced by larcv::Run3DTrackerProcessFactory::create().
     : ProcessBase(name),
     _foutll("larlite_reco3D.root"),
     _spline_file("Proton_Muon_Range_dEdx_LAr_TSplines.root"),
     _recoTree(nullptr)
     {}
~Run3DTracker()
larcv::Run3DTracker::~Run3DTracker () inline
Default destructor.
Definition at line 44 of file Run3DTracker.h.
References configure(), initialize(), process(), and SetSplineLocation().
 {}
Member Function Documentation
advance_larlite()
void larcv::Run3DTracker::advance_larlite ()
Definition at line 502 of file Run3DTracker.cxx.
References _event, _run, _storage, and _subrun.
Referenced by process(), and SetLLOutName().
{
         _storage.set_id(_run,_subrun,_event);
         _storage.next_event(true);
     }
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEvent()
void larcv::Run3DTracker::ClearEvent ()
Definition at line 610 of file Run3DTracker.cxx.
References _Ee_t, _ElectronEndPoint_X, _ElectronEndPoint_Y, _ElectronEndPoint_Z, _ElectronStartPoint_X, _ElectronStartPoint_Y, _ElectronStartPoint_Z, _Em_t, _Ep_t, _event, _MuonEndPoint_X, _MuonEndPoint_Y, _MuonEndPoint_Z, _MuonStartPoint_X, _MuonStartPoint_Y, _MuonStartPoint_Z, _Nreco, _ProtonEndPoint_X, _ProtonEndPoint_Y, _ProtonEndPoint_Z, _ProtonStartPoint_X, _ProtonStartPoint_Y, _ProtonStartPoint_Z, _run, _subrun, ClearVertex(), larcv::kINVALID_DOUBLE, larcv::kINVALID_INT, MCvertex, and MCVertices.
Referenced by process(), and SetLLOutName().
{
         _run    = kINVALID_INT;
         _subrun = kINVALID_INT;
         _event  = kINVALID_INT;
         _Nreco = 0;
         _MuonStartPoint_X = -1.0*kINVALID_DOUBLE;
         _ProtonStartPoint_X = -1.0*kINVALID_DOUBLE;
         _ElectronStartPoint_X = -1.0*kINVALID_DOUBLE;
         _MuonStartPoint_Y = -1.0*kINVALID_DOUBLE;
         _ProtonStartPoint_Y = -1.0*kINVALID_DOUBLE;
         _ElectronStartPoint_Y = -1.0*kINVALID_DOUBLE;
         _MuonStartPoint_Z = -1.0*kINVALID_DOUBLE;
         _ProtonStartPoint_Z = -1.0*kINVALID_DOUBLE;
         _ElectronStartPoint_Z = -1.0*kINVALID_DOUBLE;
         _MuonEndPoint_X = -1.0*kINVALID_DOUBLE;
         _ProtonEndPoint_X = -1.0*kINVALID_DOUBLE;
         _ElectronEndPoint_X = -1.0*kINVALID_DOUBLE;
         _MuonEndPoint_Y = -1.0*kINVALID_DOUBLE;
         _ProtonEndPoint_Y = -1.0*kINVALID_DOUBLE;
         _ElectronEndPoint_Y = -1.0*kINVALID_DOUBLE;
         _MuonEndPoint_Z = -1.0*kINVALID_DOUBLE;
         _ProtonEndPoint_Z = -1.0*kINVALID_DOUBLE;
         _ElectronEndPoint_Z = -1.0*kINVALID_DOUBLE;
         _Ep_t = -1.0*kINVALID_DOUBLE;
         _Em_t = -1.0*kINVALID_DOUBLE;
         _Ee_t = -1.0*kINVALID_DOUBLE;
         MCvertex.SetXYZ(-1,-1,-1);
         if(MCVertices.size()!=0)MCVertices.clear();
         ClearVertex();
     }
ClearVertex()
void larcv::Run3DTracker::ClearVertex ()
Definition at line 651 of file Run3DTracker.cxx.
References _Angle_v, _Avg_Ion_v, _branchingTracks, _E_muon_v, _E_proton_v, _jumpingTracks, _Length_v, _missingTrack, _nothingReconstructed, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _trackQ10_v, _trackQ20_v, _trackQ30_v, _trackQ3_v, _trackQ50_v, _trackQ5_v, _vtx_id, _vtx_x, _vtx_y, _vtx_z, GoodVertex, larcv::kINVALID_FLOAT, and larcv::kINVALID_INT.
Referenced by ClearEvent(), process(), and SetLLOutName().
{
         _vtx_id = -1.0 * kINVALID_INT;
         _vtx_x  = -1.0 * kINVALID_FLOAT;
         _vtx_y  = -1.0 * kINVALID_FLOAT;
         _vtx_z  = -1.0 * kINVALID_FLOAT;
         _E_muon_v.clear();
         _E_proton_v.clear();
         _Length_v.clear();
         _Avg_Ion_v.clear();
         _Angle_v.clear();
         _Reco_goodness_v.clear();
         GoodVertex = -1.0*kINVALID_INT;
         _missingTrack = -1.0*kINVALID_INT;
         _nothingReconstructed = -1.0*kINVALID_INT;
         _tooShortDeadWire = -1.0*kINVALID_INT;
         _tooShortFaintTrack = -1.0*kINVALID_INT;
         _tooManyTracksAtVertex = -1.0*kINVALID_INT;
         _possibleCosmic = -1.0*kINVALID_INT;
         _possiblyCrossing = -1.0*kINVALID_INT;
         _branchingTracks = -1.0*kINVALID_INT;
         _jumpingTracks = -1.0*kINVALID_INT;
         _trackQ50_v.clear();
         _trackQ30_v.clear();
         _trackQ20_v.clear();
         _trackQ10_v.clear();
         _trackQ5_v.clear();
         _trackQ3_v.clear();
     }
configure()
void larcv::Run3DTracker::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 59 of file Run3DTracker.cxx.
References _img2d_producer, _input_pgraph_producer, _mask_shower, _par_pix_producer, _true_roi_producer, and larcv::PSet::get().
Referenced by ~Run3DTracker().
     {
         _input_pgraph_producer     = cfg.get<std::string>("InputPgraphProducer");
         _img2d_producer            = cfg.get<std::string>("Image2DProducer");
         _par_pix_producer          = cfg.get<std::string>("ParPixelProducer");
         _true_roi_producer         = cfg.get<std::string>("TrueROIProducer");
         _mask_shower               = cfg.get<bool>("MaskShower",false);
     }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
FillMC()
void larcv::Run3DTracker::FillMC (const std::vector< ROI > & mc_roi_v)
Definition at line 507 of file Run3DTracker.cxx.
References _Ee_t, _ElectronEndPoint_X, _ElectronEndPoint_Y, _ElectronEndPoint_Z, _ElectronStartPoint_X, _ElectronStartPoint_Y, _ElectronStartPoint_Z, _Em_t, _Ep_t, _MuonEndPoint_X, _MuonEndPoint_Y, _MuonEndPoint_Z, _MuonStartPoint_X, _MuonStartPoint_Y, _MuonStartPoint_Z, _ProtonEndPoint_X, _ProtonEndPoint_Y, _ProtonEndPoint_Z, _ProtonStartPoint_X, _ProtonStartPoint_Y, _ProtonStartPoint_Z, Em_t, Ep_t, LARCV_INFO, MCvertex, MCVertices, and NeutrinoEnergyTh.
Referenced by process(), and SetLLOutName().
{
         bool found_muon = false;
         bool found_proton = false;
         bool found_electron = false;
         std::vector<TVector3> MuonVertices;
         std::vector<TVector3> ProtonVertices;
         std::vector<TVector3> ElectronVertices;
         std::vector<TVector3> MuonEndPoint;
         std::vector<TVector3> ProtonEndPoint;
         std::vector<TVector3> ElectronEndPoint;
         for(size_t iMC = 0;iMC<mc_roi_v.size();iMC++){
             if(mc_roi_v[iMC].PdgCode() == 13){
                 if (found_muon) continue;
                 LARCV_INFO() << "muon.....@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 _MuonStartPoint_X = mc_roi_v[iMC].X();
                 _MuonStartPoint_Y = mc_roi_v[iMC].Y();
                 _MuonStartPoint_Z = mc_roi_v[iMC].Z();
                 _MuonEndPoint_X = mc_roi_v[iMC].EndPosition().X();
                 _MuonEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
                 _MuonEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
                 _Em_t = mc_roi_v[iMC].EnergyDeposit();
                 found_muon = true;
             }
             if(mc_roi_v[iMC].PdgCode() == 2212){
                 if (found_proton) continue;
                 LARCV_INFO() << "proton...@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 _ProtonStartPoint_X = mc_roi_v[iMC].X();
                 _ProtonStartPoint_Y = mc_roi_v[iMC].Y();
                 _ProtonStartPoint_Z = mc_roi_v[iMC].Z();
                 _ProtonEndPoint_X = mc_roi_v[iMC].EndPosition().X();
                 _ProtonEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
                 _ProtonEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
                 _Ep_t = mc_roi_v[iMC].EnergyDeposit();
                 found_proton = true;
             }
             if(mc_roi_v[iMC].PdgCode() == 11){
                 if(found_electron) continue;
                 LARCV_INFO() << "electron.@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 _ElectronStartPoint_X = mc_roi_v[iMC].X();
                 _ElectronStartPoint_Y = mc_roi_v[iMC].Y();
                 _ElectronStartPoint_Z = mc_roi_v[iMC].Z();
                 _ElectronEndPoint_X = mc_roi_v[iMC].EndPosition().X();
                 _ElectronEndPoint_Y = mc_roi_v[iMC].EndPosition().Y();
                 _ElectronEndPoint_Z = mc_roi_v[iMC].EndPosition().Z();
                 _Ee_t = mc_roi_v[iMC].EnergyDeposit();
                 found_electron = true;
             }
             // Adrien old version
             if(mc_roi_v[iMC].PdgCode() == 14){
                 NeutrinoEnergyTh = mc_roi_v[iMC].EnergyDeposit();
                 std::cout << "Neutrino : " << NeutrinoEnergyTh << " MeV" << std::endl;
             }
             if(mc_roi_v[iMC].PdgCode() == 13){
                 std::cout << "muon.....@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 Em_t = mc_roi_v[iMC].EnergyDeposit();
                 MuonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 MuonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
             if(mc_roi_v[iMC].PdgCode() == 2212){
                 if(mc_roi_v[iMC].EnergyDeposit() < 60) continue;
                 std::cout << "proton...@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 Ep_t = mc_roi_v[iMC].EnergyDeposit();
                 ProtonVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 ProtonEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
             if(mc_roi_v[iMC].PdgCode() == 11){
                 std::cout << "electron.@" << mc_roi_v[iMC].X() << ", " << mc_roi_v[iMC].Y() << ", " << mc_roi_v[iMC].Z() << " ... " << mc_roi_v[iMC].EnergyDeposit() << " MeV" << std::endl;
                 ElectronVertices.push_back(TVector3(mc_roi_v[iMC].X(),mc_roi_v[iMC].Y(),mc_roi_v[iMC].Z()));
                 ElectronEndPoint.push_back(TVector3(mc_roi_v[iMC].EndPosition().X(), mc_roi_v[iMC].EndPosition().Y(), mc_roi_v[iMC].EndPosition().Z()));
             }
             bool isVertex = false;
             bool isNumu = false;
             bool isNue = false;
             std::vector<int> goodMuon, goodElectron;
             for(size_t iProton = 0;iProton<ProtonVertices.size();iProton++){
                 isVertex = false;
                 isNumu = false;
                 isNue = false;
                 for(size_t iMuon = 0;iMuon<MuonVertices.size();iMuon++){
                     if(MuonVertices[iMuon] == ProtonVertices[iProton]){isVertex = true;isNumu = true;goodMuon.push_back(iMuon);}
                 }
                 for(size_t iElectron = 0;iElectron<ElectronVertices.size();iElectron++){
                     if(ProtonVertices[iProton] == ElectronVertices[iProton]){isVertex = true;isNue = true;goodElectron.push_back(iElectron);}
                 }
                 if(isVertex && MCVertices.size()!=0 && ProtonVertices[iProton] == MCVertices[MCVertices.size()-1])continue;
                 if(isVertex){
                     MCvertex = ProtonVertices[iProton];
                     MCVertices.push_back(MCvertex);
                 }
             }
             // end Adrien
         } // end rois
         return;
     } // end mc
finalize()
void larcv::Run3DTracker::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 482 of file Run3DTracker.cxx.
References _recoTree, _storage, larcv::ProcessBase::ana_file(), larcv::AStarTracker::finalize(), larcv::ProcessBase::has_ana_file(), and tracker.
Referenced by SetOutDir().
     {
         tracker.finalize();
         std::cout << "finalized tracker" << std::endl;
         if(has_ana_file()) {
             ana_file().cd();
             _recoTree->Write();
         }
         _storage.close();
     }
GetJarretVertex()
std::vector<TVector3> larcv::Run3DTracker::GetJarretVertex (int run, int subrun, int event)
Referenced by SetOutDir().
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::Run3DTracker::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 69 of file Run3DTracker.cxx.
References _Angle_v, _Avg_Ion_v, _Avg_IonY_v, _branchingTracks, _closestWall, _E_muon_v, _E_proton_v, _Ee_t, _ElectronEndPoint_X, _ElectronEndPoint_Y, _ElectronEndPoint_Z, _ElectronStartPoint_X, _ElectronStartPoint_Y, _ElectronStartPoint_Z, _Em_t, _entry, _Ep_t, _event, _foutll, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _IonY_10cm_v, _IonY_5cm_v, _IonY_tot_v, _jumpingTracks, _Length_v, _missingTrack, _MuonEndPoint_X, _MuonEndPoint_Y, _MuonEndPoint_Z, _MuonStartPoint_X, _MuonStartPoint_Y, _MuonStartPoint_Z, _nothingReconstructed, _possibleCosmic, _possiblyCrossing, _ProtonEndPoint_X, _ProtonEndPoint_Y, _ProtonEndPoint_Z, _ProtonStartPoint_X, _ProtonStartPoint_Y, _ProtonStartPoint_Z, _Reco_goodness_v, _recoTree, _RecoVertex, _run, _spline_file, _storage, _subrun, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _TotalADCvalues_v, _track_Goodness_v, _trackQ10_v, _trackQ20_v, _trackQ30_v, _trackQ3_v, _trackQ50_v, _trackQ5_v, _trk_id_v, _Trunc_dQdX1_v, _Trunc_dQdX3_v, _vertexPhi, _vertexTheta, _vtx_id, _vtx_x, _vtx_y, _vtx_z, GoodVertex, larcv::AStarTracker::initialize(), LARCV_CRITICAL, LARCV_INFO, MCvertex, NtracksReco, out_dir, larcv::AStarTracker::SetDrawOutputs(), larcv::AStarTracker::SetOutputDir(), larcv::AStarTracker::SetSplineFile(), larcv::AStarTracker::SetVerbose(), and tracker.
Referenced by ~Run3DTracker().
     {
         LARCV_INFO() << "[Run3DTracker]" << std::endl;
         assert(!_spline_file.empty());
         tracker.SetDrawOutputs(false);
         tracker.SetOutputDir(out_dir);
         tracker.SetSplineFile(_spline_file);
         tracker.initialize();
         tracker.SetVerbose(0);
         std::string filename;
         std::cout << filename << std::endl;
         _recoTree = new TTree("_recoTree","_recoTree");
         _recoTree->Branch("run"     , &_run   , "_run/I");
         _recoTree->Branch("subrun"  , &_subrun, "_subrun/I");
         _recoTree->Branch("event"   , &_event , "_event/I");
         _recoTree->Branch("entry"   , &_entry , "_entry/I");
         _recoTree->Branch("vtx_id", &_vtx_id , "vtx_id/I");
         _recoTree->Branch("vtx_x" , &_vtx_x , "vtx_x/F");
         _recoTree->Branch("vtx_y" , &_vtx_y , "vtx_y/F");
         _recoTree->Branch("vtx_z" , &_vtx_z , "vtx_z/F");
         _recoTree->Branch("trk_id_v", &_trk_id_v);
         _recoTree->Branch("NtracksReco",&NtracksReco);
         _recoTree->Branch("trackQ3_v",&_trackQ3_v);
         _recoTree->Branch("trackQ5_v",&_trackQ5_v);
         _recoTree->Branch("trackQ10_v",&_trackQ10_v);
         _recoTree->Branch("trackQ20_v",&_trackQ20_v);
         _recoTree->Branch("trackQ30_v",&_trackQ30_v);
         _recoTree->Branch("trackQ50_v",&_trackQ50_v);
         _recoTree->Branch("E_muon_v",&_E_muon_v);
         _recoTree->Branch("E_proton_v",&_E_proton_v);
         _recoTree->Branch("Length_v",&_Length_v);
         _recoTree->Branch("Avg_Ion_v",&_Avg_Ion_v);
         _recoTree->Branch("Avg_IonY_v",&_Avg_IonY_v);
         _recoTree->Branch("Ion_5cm_v",&_Ion_5cm_v);
         _recoTree->Branch("Ion_10cm_v",&_Ion_10cm_v);
         _recoTree->Branch("Ion_tot_v",&_Ion_tot_v);
         _recoTree->Branch("IonY_5cm_v",&_IonY_5cm_v);
         _recoTree->Branch("IonY_10cm_v",&_IonY_10cm_v);
         _recoTree->Branch("IonY_tot_v",&_IonY_tot_v);
         _recoTree->Branch("Truncated_dQdX1_v",&_Trunc_dQdX1_v);
         _recoTree->Branch("Truncated_dQdX3_v",&_Trunc_dQdX3_v);
         _recoTree->Branch("IondivLength_v",&_IondivLength_v);
         _recoTree->Branch("TotalADCvalues_v",&_TotalADCvalues_v);
         _recoTree->Branch("Angle_v",&_Angle_v);
         _recoTree->Branch("Reco_goodness_v",&_Reco_goodness_v);
         _recoTree->Branch("track_Goodness_v",&_track_Goodness_v);
         _recoTree->Branch("GoodVertex",&GoodVertex);
         _recoTree->Branch("missingTrack",&_missingTrack);
         _recoTree->Branch("nothingReconstructed",&_nothingReconstructed);
         _recoTree->Branch("tooShortDeadWire",&_tooShortDeadWire);
         _recoTree->Branch("tooShortFaintTrack",&_tooShortFaintTrack);
         _recoTree->Branch("tooManyTracksAtVertex",&_tooManyTracksAtVertex);
         _recoTree->Branch("possibleCosmic",&_possibleCosmic);
         _recoTree->Branch("possiblyCrossing",&_possiblyCrossing);
         _recoTree->Branch("branchingTracks",&_branchingTracks);
         _recoTree->Branch("jumpingTracks",&_jumpingTracks);
         _recoTree->Branch("RecoVertex",&_RecoVertex);
         _recoTree->Branch("vertexPhi",&_vertexPhi);
         _recoTree->Branch("vertexTheta",&_vertexTheta);
         _recoTree->Branch("closestWall",&_closestWall);
         _recoTree->Branch("MCvertex",&MCvertex);
         _recoTree->Branch("Ep_t"       , &_Ep_t       , "Ep_t/D");
         _recoTree->Branch("Em_t"       , &_Em_t       , "Em_t/D");
         _recoTree->Branch("Ee_t"       , &_Ee_t       , "Ee_t/D");
         _recoTree->Branch("MuonStartPoint_X", &_MuonStartPoint_X, "MuonStartPoint_X/D");
         _recoTree->Branch("ProtonStartPoint_X", &_ProtonStartPoint_X, "ProtonStartPoint_X/D");
         _recoTree->Branch("ElectronStartPoint_X", &_ElectronStartPoint_X, "ElectronStartPoint_X/D");
         _recoTree->Branch("MuonStartPoint_Y", &_MuonStartPoint_Y, "MuonStartPoint_Y/D");
         _recoTree->Branch("ProtonStartPoint_Y", &_ProtonStartPoint_Y, "ProtonStartPoint_Y/D");
         _recoTree->Branch("ElectronStartPoint_Y", &_ElectronStartPoint_Y, "ElectronStartPoint_Y/D");
         _recoTree->Branch("MuonStartPoint_Z", &_MuonStartPoint_Z, "MuonStartPoint_Z/D");
         _recoTree->Branch("ProtonStartPoint_Z", &_ProtonStartPoint_Z, "ProtonStartPoint_Z/D");
         _recoTree->Branch("ElectronStartPoint_Z", &_ElectronStartPoint_Z, "ElectronStartPoint_Z/D");
         _recoTree->Branch("MuonEndPoint_X", &_MuonEndPoint_X, "MuonEndPoint_X/D");
         _recoTree->Branch("ProtonEndPoint_X", &_ProtonEndPoint_X, "ProtonEndPoint_X/D");
         _recoTree->Branch("ElectronEndPoint_X", &_ElectronEndPoint_X, "ElectronEndPoint_X/D");
         _recoTree->Branch("MuonEndPoint_Y", &_MuonEndPoint_Y, "MuonEndPoint_Y/D");
         _recoTree->Branch("ProtonEndPoint_Y", &_ProtonEndPoint_Y, "ProtonEndPoint_Y/D");
         _recoTree->Branch("ElectronEndPoint_Y", &_ElectronEndPoint_Y, "ElectronEndPoint_Y/D");
         _recoTree->Branch("MuonEndPoint_Z", &_MuonEndPoint_Z, "MuonEndPoint_Z/D");
         _recoTree->Branch("ProtonEndPoint_Z", &_ProtonEndPoint_Z, "ProtonEndPoint_Z/D");
         _recoTree->Branch("ElectronEndPoint_Z", &_ElectronEndPoint_Z, "ElectronEndPoint_Z/D");
         if (_foutll.empty()) throw larbys("specify larlite file output name");
         _storage.set_io_mode(larlite::storage_manager::kWRITE);
         _storage.set_out_filename(_foutll);
         if(!_storage.open()) {
             LARCV_CRITICAL() << "ERROR, larlite output file could not open" << std::endl;
             throw larbys("die");
         }
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
IsGoodEntry()
bool larcv::Run3DTracker::IsGoodEntry (int run, int subrun, int event)
Referenced by SetOutDir().
IsGoodVertex()
bool larcv::Run3DTracker::IsGoodVertex (int run, int subrun, int event, int vtxID)
Referenced by SetOutDir().
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MCevaluation()
void larcv::Run3DTracker::MCevaluation ()
Definition at line 444 of file Run3DTracker.cxx.
References _Avg_Ion_v, _event, _run, _subrun, checkEvents, Em_t, Ep_t, larcv::AStarTracker::GetEnergies(), larcv::AStarTracker::IsGoodVertex(), NeutrinoEnergyTh, and tracker.
Referenced by process(), and SetOutDir().
{
         std::cout << "MCevaluation()" << std::endl;
         std::vector< std::vector<double> > Energies_v = tracker.GetEnergies();
         //_Length_v = tracker.GetVertexLength();
         if(!tracker.IsGoodVertex()){std::cout << "error: is not good vertex" << std::endl;return;}
         if(_Avg_Ion_v.size()!=2){std::cout << "error: _Avg_Ion_v.size() = " << _Avg_Ion_v.size() << std::endl;return;}
         std::cout << "in store energies : " << std::endl;
         std::cout << Energies_v[0][0] << ":" << Energies_v[0][1] << std::endl;
         std::cout << Energies_v[1][0] << ":" << Energies_v[1][1] << std::endl;
         double Epreco;
         double Emreco;
         if(_Avg_Ion_v[0] > _Avg_Ion_v[1]){
             Epreco = Energies_v[0][0];// first track is proton
             Emreco = Energies_v[1][1];// second track is muon
         }
         else{
             Epreco = Energies_v[1][0]; // second track is proton
             Emreco = Energies_v[0][1]; // first track is muon
         }
         if( std::abs((Epreco-Ep_t)/Ep_t) > 0.1 || std::abs((Emreco-Em_t)/Em_t) > 0.1 ){
             checkEvents.push_back(Form("%d_%d_%d",_run,_subrun,_event));
         }
         std::cout << "proton : Epreco = " << Epreco << " MeV, Epth : " << Ep_t << " MeV..." << 100*(Epreco-Ep_t)/Ep_t << " %" << std::endl;
         std::cout << "muon   : Emreco = " << Emreco << " MeV, Emth : " << Em_t << " MeV..." << 100*(Emreco-Em_t)/Em_t << " %" << std::endl;
         std::cout << "E nu th   : " << NeutrinoEnergyTh << " MeV" << std::endl;
         std::cout << "E nu Reco : " << Epreco+Emreco << " MeV" << std::endl;
         std::cout << "relative Enu diff: " << 100*((Epreco+Emreco+146)-NeutrinoEnergyTh)/NeutrinoEnergyTh << " %" << std::endl;
         std::cout << "relative Enu_p+m diff: " << 100*((Epreco+Emreco)-(Ep_t+Em_t))/(Ep_t+Em_t) << " %" << std::endl;
     }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::Run3DTracker::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 180 of file Run3DTracker.cxx.
References _Angle_v, _Avg_Ion_v, _Avg_IonY_v, _branchingTracks, _closestWall, _E_muon_v, _E_proton_v, _entry, _event, _img2d_producer, _input_pgraph_producer, _Ion_10cm_v, _Ion_5cm_v, _Ion_tot_v, _IondivLength_v, _IonY_10cm_v, _IonY_5cm_v, _IonY_tot_v, _jumpingTracks, _Length_v, _mask_shower, _missingTrack, _nothingReconstructed, _par_pix_producer, _possibleCosmic, _possiblyCrossing, _Reco_goodness_v, _recoTree, _RecoVertex, _run, _storage, _subrun, _tooManyTracksAtVertex, _tooShortDeadWire, _tooShortFaintTrack, _TotalADCvalues_v, _track_Goodness_v, _trackQ10_v, _trackQ20_v, _trackQ30_v, _trackQ3_v, _trackQ50_v, _trackQ5_v, _trk_id_v, _true_roi_producer, _Trunc_dQdX1_v, _Trunc_dQdX3_v, _vertexPhi, _vertexTheta, _vtx_id, _vtx_x, _vtx_y, _vtx_z, advance_larlite(), ClearEvent(), ClearVertex(), larcv::EventPixel2D::ClusterMetaArray(), larcv::AStarTracker::ComputeTruncateddQdX(), larcv::IOManager< T >::current_entry(), FillMC(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::get_n_entries(), larcv::AStarTracker::GetAverageIonization(), larcv::AStarTracker::GetAverageIonization_Yplane(), larcv::AStarTracker::GetClosestWall(), larcv::AStarTracker::GetEnergies(), larcv::AStarTracker::GetRecoGoodness(), larcv::AStarTracker::GetReconstructedVertexTracks(), larcv::AStarTracker::GetTotalIonization(), larcv::AStarTracker::GetTotalIonization_Yplane(), larcv::AStarTracker::GetTotalPixADC(), larcv::AStarTracker::GetVertexAngle(), larcv::AStarTracker::GetVertexLength(), larcv::AStarTracker::GetVertexPhi(), larcv::AStarTracker::GetVertexTheta(), larcv::AStarTracker::GetVtxQuality(), GoodVertex, larcv::AStarTracker::IsGoodVertex(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, larcv::kShapeTrack, MCevaluation(), NtracksReco, NvertexSubmitted, larcv::EventPixel2D::Pixel2DClusterArray(), larcv::AStarTracker::ReconstructVertex(), RecoVertex, larcv::EventROI::ROIArray(), larcv::AStarTracker::SetOriginalImage(), larcv::AStarTracker::SetSingleVertex(), larcv::AStarTracker::SetTaggedImage(), larcv::AStarTracker::SetTrackInfo(), larcv::AStarTracker::SetVertexID(), and tracker.
Referenced by ~Run3DTracker().
     {
         ClearEvent();
         std::cout << std::endl;
         std::cout << "============================================" << std::endl;
         std::cout << "Entry " << mgr.current_entry() << " / " << mgr.get_n_entries() << std::endl;
         std::cout << "============================================" << std::endl;
         gStyle->SetOptStat(0);
         TVector3 vertex(-1,-1,-1);
         auto ev_pgraph_v     = (EventPGraph*) mgr.get_data(kProductPGraph,_input_pgraph_producer); // for BNB 5e19, comment when EXTBNB
         _run    = (int) ev_pgraph_v->run();
         _subrun = (int) ev_pgraph_v->subrun();
         _event  = (int) ev_pgraph_v->event();
         _entry  = (int) mgr.current_entry();
         auto ev_track  = (larlite::event_track*)  _storage.get_data(larlite::data::kTrack,"trackReco");
         auto ev_vertex = (larlite::event_vertex*) _storage.get_data(larlite::data::kVertex,"trackReco");
         auto ev_ass    = (larlite::event_ass*)    _storage.get_data(larlite::data::kAssociation,"trackReco");
         if(ev_pgraph_v->PGraphArray().size()==0){advance_larlite();return true;}
         auto ev_img_v           = (EventImage2D*)mgr.get_data(kProductImage2D,_img2d_producer);
         //auto tag_img_thru_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"thrumutags");
         //auto tag_img_stop_v     = (EventImage2D*)mgr.get_data(kProductImage2D,"stopmutags");
         EventPixel2D* ev_pix_v = nullptr;
         if (!_par_pix_producer.empty())
             ev_pix_v = (EventPixel2D*) mgr.get_data(kProductPixel2D,_par_pix_producer);
         //auto ev_pcluster_v = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_img");
         //auto ev_ctor_v     = (EventPixel2D*)mgr.get_data(kProductPixel2D,"test_ctor");
         // get the event clusters and full images
         //auto const& ctor_m = ev_ctor_v->Pixel2DClusterArray();
         auto full_adc_img_v = &(ev_img_v->Image2DArray());
         //auto full_tag_img_thru_v = &(tag_img_thru_v->Image2DArray());
         //auto full_tag_img_stop_v = &(tag_img_stop_v->Image2DArray());
         //
         // Fill MC if exists
         //
         EventROI* ev_partroi_v = nullptr;
         if (!_true_roi_producer.empty()) ev_partroi_v = (EventROI*) mgr.get_data(kProductROI,_true_roi_producer);
         if (ev_partroi_v) {
             const auto& mc_roi_v = ev_partroi_v->ROIArray();
             FillMC(mc_roi_v);
         }
         // loop over found vertices
         //auto const& pcluster_m = ev_pcluster_v->Pixel2DClusterArray();
         std::vector<larcv::ImageMeta> Full_meta_v(3);
         std::vector<larcv::Image2D> Tagged_Image(3);
         std::vector<larcv::Image2D> Full_image_v(3);
         double wireRange = 5000;
         double tickRange = 8502;
         // Create base image2D with the full view, fill it with the input image 2D, we will crop it later
         for(size_t iPlane=0;iPlane<3;iPlane++){
             Full_meta_v[iPlane] = larcv::ImageMeta(wireRange,tickRange,(int)(tickRange)/6,(int)(wireRange),0,tickRange);
             Full_image_v[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             Tagged_Image[iPlane] = larcv::Image2D(Full_meta_v[iPlane]);
             if(full_adc_img_v->size() == 3)Full_image_v[iPlane].overlay( (*full_adc_img_v)[iPlane] );
             //if(full_tag_img_thru_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_thru_v)[iPlane] );
             //if(full_tag_img_stop_v->size() == 3)Tagged_Image[iPlane].overlay( (*full_tag_img_stop_v)[iPlane] );
         }
         tracker.SetOriginalImage(Full_image_v);
         tracker.SetTaggedImage(Tagged_Image);
         tracker.SetTrackInfo(_run, _subrun, _event, 0);
         std::cout << _run << " " << _subrun << " " << _event <<  std::endl;
         //if(!(_subrun == 107 && _event == 96242)){advance_larlite(); return true;}
         static std::vector<TVector3> vertex_v;
         if(vertex_v.size()!=0)vertex_v.clear();
         for(size_t pgraph_id = 0; pgraph_id < ev_pgraph_v->PGraphArray().size(); ++pgraph_id) {
             auto const& pgraph = ev_pgraph_v->PGraphArray().at(pgraph_id);
             auto const& roi_v         = pgraph.ParticleArray();
             auto const& cluster_idx_v = pgraph.ClusterIndexArray();
             RecoVertex.SetXYZ(pgraph.ParticleArray().front().X(),pgraph.ParticleArray().front().Y(),pgraph.ParticleArray().front().Z());
             vertex_v.push_back(RecoVertex);
             if (_mask_shower) {
                 assert (ev_pix_v);
                 const auto& pix_m          = ev_pix_v->Pixel2DClusterArray();
                 const auto& pix_meta_m     = ev_pix_v->ClusterMetaArray();
                 //
                 // mask shower particle pixels
                 // method : pixels stored via larbys image
                 //
                 for(size_t roid=0; roid < roi_v.size(); ++roid) {
                     const auto& roi = roi_v[roid];
                     auto cidx = cluster_idx_v.at(roid);
                     if (roi.Shape() == kShapeTrack) continue;
                     for(size_t plane=0; plane<3; ++plane) {
                         auto iter_pix = pix_m.find(plane);
                         if(iter_pix == pix_m.end())
                             continue;
                         auto iter_pix_meta = pix_meta_m.find(plane);
                         if(iter_pix_meta == pix_meta_m.end())
                             continue;
                         auto const& pix_v      = (*iter_pix).second;
                         auto const& pix_meta_v = (*iter_pix_meta).second;
                         auto const& pix      = pix_v.at(cidx);
                         auto const& pix_meta = pix_meta_v.at(cidx);
                         auto& plane_img = Full_image_v.at(plane);
                         for(const auto& px : pix) {
                             auto posx = pix_meta.pos_x(px.Y());
                             auto posy = pix_meta.pos_y(px.X());
                             auto row = plane_img.meta().row(posy);
                             auto col = plane_img.meta().col(posx);
                             plane_img.set_pixel(row,col,0);
                         }
                     } // end plane
                 } // end ROI
             }//end mask Shower
         }
         tracker.SetOriginalImage(Full_image_v);
         tracker.SetTaggedImage(Tagged_Image);
         tracker.SetTrackInfo(_run, _subrun, _event, 0);
         std::vector<std::vector<unsigned> > ass_vertex_to_track_vv;
         ass_vertex_to_track_vv.resize(vertex_v.size());
         //vertex_v = MCVertices;
         NvertexSubmitted+=vertex_v.size();
         int TrackID = 0;
         if(vertex_v.size()!=0){
             for(size_t ivertex = 0;ivertex<vertex_v.size();ivertex++){
                 NtracksReco = 0;
                 if(_trk_id_v.size()!=0)_trk_id_v.clear();
                 if(_IondivLength_v.size()!=0)_IondivLength_v.clear();
                 if(_TotalADCvalues_v.size()!=0)_TotalADCvalues_v.clear();
                 double xyz[3] = {vertex_v[ivertex].X(),vertex_v[ivertex].Y(),vertex_v[ivertex].Z()};
                 ev_vertex->push_back(larlite::vertex(xyz,ivertex));
                 auto& ass_vertex_to_track_v = ass_vertex_to_track_vv[ivertex];
                 tracker.SetSingleVertex(vertex_v[ivertex]);
                 tracker.SetVertexID((int)(ivertex));
                 tracker.ReconstructVertex();
                 auto recoedVertex = tracker.GetReconstructedVertexTracks();
                 for(size_t itrack = 0; itrack<recoedVertex.size();itrack++){
                     ass_vertex_to_track_v.push_back(ev_track->size());
                     recoedVertex[itrack].set_track_id(TrackID);
                     (*ev_track).push_back(recoedVertex[itrack]);
                     _trk_id_v.push_back(TrackID);
                     TrackID++;
                     if(recoedVertex[itrack].Length(0) > 5){NtracksReco++;}
                 }
                 auto Energies_v = tracker.GetEnergies();
                 _E_muon_v.resize(Energies_v.size());
                 _E_proton_v.resize(Energies_v.size());
                 for(size_t trackid=0; trackid<Energies_v.size(); ++trackid) {
                     _E_proton_v[trackid] = Energies_v[trackid].front();
                     _E_muon_v[trackid]   = Energies_v[trackid].back();
                 }
                 _vtx_id = (int) ivertex;
                 _vtx_x  = (float) vertex_v[ivertex].X();
                 _vtx_y  = (float) vertex_v[ivertex].Y();
                 _vtx_z  = (float) vertex_v[ivertex].Z();
                 _Length_v    = tracker.GetVertexLength();
                 _closestWall = tracker.GetClosestWall();
                 _trackQ3_v     = tracker.GetTotalPixADC(3.);
                 _trackQ5_v     = tracker.GetTotalPixADC(5.);
                 _trackQ10_v    = tracker.GetTotalPixADC(10.);
                 _trackQ20_v    = tracker.GetTotalPixADC(20.);
                 _trackQ30_v    = tracker.GetTotalPixADC(30.);
                 _trackQ50_v    = tracker.GetTotalPixADC(50.);
                 _Avg_Ion_v     = tracker.GetAverageIonization();
                 _Ion_5cm_v     = tracker.GetTotalIonization(5);
                 _Ion_10cm_v    = tracker.GetTotalIonization(10);
                 _Ion_tot_v     = tracker.GetTotalIonization();
                 _Avg_IonY_v     = tracker.GetAverageIonization_Yplane();
                 _IonY_5cm_v     = tracker.GetTotalIonization_Yplane(5);
                 _IonY_10cm_v    = tracker.GetTotalIonization_Yplane(10);
                 _IonY_tot_v     = tracker.GetTotalIonization_Yplane();
                 _Trunc_dQdX1_v = tracker.ComputeTruncateddQdX(1.0);
                 _Trunc_dQdX3_v = tracker.ComputeTruncateddQdX(3.0);
                 for(size_t itrack = 0; itrack<_Length_v.size();itrack++){
                     _IondivLength_v.push_back(_Ion_tot_v[itrack]/_Length_v[itrack]);
                 }
                 _TotalADCvalues_v = tracker.GetTotalPixADC();
                 _Angle_v   = tracker.GetVertexAngle(15); // average over 15 cm to estimate the angles
                 _vertexPhi   = tracker.GetVertexPhi();
                 _vertexTheta = tracker.GetVertexTheta();
                 _Reco_goodness_v = tracker.GetRecoGoodness();
                 _track_Goodness_v = tracker.GetVtxQuality();
                 assert (_Reco_goodness_v.size() == 9);
                 _missingTrack          = _Reco_goodness_v.at(0);
                 _nothingReconstructed  = _Reco_goodness_v.at(1);
                 _tooShortDeadWire      = _Reco_goodness_v.at(2);
                 _tooShortFaintTrack    = _Reco_goodness_v.at(3);
                 _tooManyTracksAtVertex = _Reco_goodness_v.at(4);
                 _possibleCosmic        = _Reco_goodness_v.at(5);
                 _possiblyCrossing      = _Reco_goodness_v.at(6);
                 _branchingTracks       = _Reco_goodness_v.at(7);
                 _jumpingTracks         = _Reco_goodness_v.at(8);
                 _RecoVertex = vertex_v.at(ivertex);
                 GoodVertex = false;
                 GoodVertex = tracker.IsGoodVertex();
                 //if(!_nothingReconstructed)tracker.DrawVertex();
                 //______________________
                 if(ev_partroi_v)MCevaluation();
                 //----------------------
                 _recoTree->Fill();
                 ClearVertex();
                 std::cout << std::endl << std::endl;
             }
         }
         // set the ass
         ev_ass->set_association(ev_vertex->id(),ev_track->id(), ass_vertex_to_track_vv);
         advance_larlite();
         std::cout << "...Reconstruted..." << std::endl;
         return true;
     }
ReadVertexFile()
void larcv::Run3DTracker::ReadVertexFile (std::string filename)
Referenced by SetOutDir().
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetLLOutName()
void larcv::Run3DTracker::SetLLOutName (const std::string & foutll) inline
Definition at line 51 of file Run3DTracker.h.
References _foutll, advance_larlite(), ClearEvent(), ClearVertex(), and FillMC().
 { _foutll = foutll; }
SetOutDir()
void larcv::Run3DTracker::SetOutDir (std::string s) inline
Definition at line 56 of file Run3DTracker.h.
References finalize(), GetJarretVertex(), IsGoodEntry(), IsGoodVertex(), MCevaluation(), out_dir, and ReadVertexFile().
 {out_dir = s;}
SetSplineLocation()
void larcv::Run3DTracker::SetSplineLocation (const std::string & fpath)
Definition at line 495 of file Run3DTracker.cxx.
References _spline_file, LARCV_DEBUG, LARCV_INFO, larcv::AStarTracker::SetSplineFile(), and tracker.
Referenced by ~Run3DTracker().
{
         LARCV_INFO() << "setting spline loc @ " << fpath << std::endl;
         tracker.SetSplineFile(fpath);
         _spline_file = fpath;
         LARCV_DEBUG() << "end" << std::endl;
     }
Member Data Documentation
_Angle_v
std::vector< std::vector<double> > larcv::Run3DTracker::_Angle_v private
Definition at line 120 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_Avg_Ion_v
std::vector<double> larcv::Run3DTracker::_Avg_Ion_v private
Definition at line 97 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), MCevaluation(), and process().
_Avg_IonY_v
std::vector<double> larcv::Run3DTracker::_Avg_IonY_v private
Definition at line 98 of file Run3DTracker.h.
Referenced by initialize(), and process().
_branchingTracks
bool larcv::Run3DTracker::_branchingTracks private
Definition at line 138 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_closestWall
std::vector<double> larcv::Run3DTracker::_closestWall private
Definition at line 101 of file Run3DTracker.h.
Referenced by initialize(), and process().
_E_muon_v
std::vector<double> larcv::Run3DTracker::_E_muon_v private
Definition at line 94 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_E_proton_v
std::vector<double> larcv::Run3DTracker::_E_proton_v private
Definition at line 95 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_Ee_t
double larcv::Run3DTracker::_Ee_t private
Definition at line 147 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronEndPoint_X
double larcv::Run3DTracker::_ElectronEndPoint_X private
Definition at line 169 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronEndPoint_Y
double larcv::Run3DTracker::_ElectronEndPoint_Y private
Definition at line 173 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronEndPoint_Z
double larcv::Run3DTracker::_ElectronEndPoint_Z private
Definition at line 177 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronStartPoint_X
double larcv::Run3DTracker::_ElectronStartPoint_X private
Definition at line 154 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronStartPoint_Y
double larcv::Run3DTracker::_ElectronStartPoint_Y private
Definition at line 158 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ElectronStartPoint_Z
double larcv::Run3DTracker::_ElectronStartPoint_Z private
Definition at line 162 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_Em_t
double larcv::Run3DTracker::_Em_t private
Definition at line 146 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_entry
int larcv::Run3DTracker::_entry private
Definition at line 82 of file Run3DTracker.h.
Referenced by initialize(), and process().
_Ep_t
double larcv::Run3DTracker::_Ep_t private
Definition at line 145 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_event
int larcv::Run3DTracker::_event private
Definition at line 80 of file Run3DTracker.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), MCevaluation(), and process().
_EventRecoVertices
std::vector<larlite::event_track> larcv::Run3DTracker::_EventRecoVertices private
Definition at line 123 of file Run3DTracker.h.
_filename
std::string larcv::Run3DTracker::_filename private
Definition at line 90 of file Run3DTracker.h.
_foutll
std::string larcv::Run3DTracker::_foutll private
Definition at line 184 of file Run3DTracker.h.
Referenced by initialize(), and SetLLOutName().
_img2d_producer
std::string larcv::Run3DTracker::_img2d_producer private
Definition at line 180 of file Run3DTracker.h.
Referenced by configure(), and process().
_input_pgraph_producer
std::string larcv::Run3DTracker::_input_pgraph_producer private
Definition at line 179 of file Run3DTracker.h.
Referenced by configure(), and process().
_Ion_10cm_v
std::vector<double> larcv::Run3DTracker::_Ion_10cm_v private
Definition at line 103 of file Run3DTracker.h.
Referenced by initialize(), and process().
_Ion_5cm_v
std::vector<double> larcv::Run3DTracker::_Ion_5cm_v private
Definition at line 102 of file Run3DTracker.h.
Referenced by initialize(), and process().
_Ion_tot_v
std::vector<double> larcv::Run3DTracker::_Ion_tot_v private
Definition at line 104 of file Run3DTracker.h.
Referenced by initialize(), and process().
_IondivLength_v
std::vector<double> larcv::Run3DTracker::_IondivLength_v private
Definition at line 112 of file Run3DTracker.h.
Referenced by initialize(), and process().
_IonY_10cm_v
std::vector<double> larcv::Run3DTracker::_IonY_10cm_v private
Definition at line 107 of file Run3DTracker.h.
Referenced by initialize(), and process().
_IonY_5cm_v
std::vector<double> larcv::Run3DTracker::_IonY_5cm_v private
Definition at line 106 of file Run3DTracker.h.
Referenced by initialize(), and process().
_IonY_tot_v
std::vector<double> larcv::Run3DTracker::_IonY_tot_v private
Definition at line 108 of file Run3DTracker.h.
Referenced by initialize(), and process().
_jumpingTracks
bool larcv::Run3DTracker::_jumpingTracks private
Definition at line 139 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_Length_v
std::vector<double> larcv::Run3DTracker::_Length_v private
Definition at line 96 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_mask_shower
bool larcv::Run3DTracker::_mask_shower private
Definition at line 186 of file Run3DTracker.h.
Referenced by configure(), and process().
_missingTrack
bool larcv::Run3DTracker::_missingTrack private
Definition at line 131 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_MuonEndPoint_X
double larcv::Run3DTracker::_MuonEndPoint_X private
Definition at line 167 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_MuonEndPoint_Y
double larcv::Run3DTracker::_MuonEndPoint_Y private
Definition at line 171 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_MuonEndPoint_Z
double larcv::Run3DTracker::_MuonEndPoint_Z private
Definition at line 175 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_MuonStartPoint_X
double larcv::Run3DTracker::_MuonStartPoint_X private
Definition at line 152 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_MuonStartPoint_Y
double larcv::Run3DTracker::_MuonStartPoint_Y private
Definition at line 156 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_MuonStartPoint_Z
double larcv::Run3DTracker::_MuonStartPoint_Z private
Definition at line 160 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_nentry
int larcv::Run3DTracker::_nentry private
Definition at line 81 of file Run3DTracker.h.
_nothingReconstructed
bool larcv::Run3DTracker::_nothingReconstructed private
Definition at line 132 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_Nreco
int larcv::Run3DTracker::_Nreco private
Definition at line 83 of file Run3DTracker.h.
Referenced by ClearEvent().
_par_pix_producer
std::string larcv::Run3DTracker::_par_pix_producer private
Definition at line 181 of file Run3DTracker.h.
Referenced by configure(), and process().
_possibleCosmic
bool larcv::Run3DTracker::_possibleCosmic private
Definition at line 136 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_possiblyCrossing
bool larcv::Run3DTracker::_possiblyCrossing private
Definition at line 137 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_ProtonEndPoint_X
double larcv::Run3DTracker::_ProtonEndPoint_X private
Definition at line 168 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ProtonEndPoint_Y
double larcv::Run3DTracker::_ProtonEndPoint_Y private
Definition at line 172 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ProtonEndPoint_Z
double larcv::Run3DTracker::_ProtonEndPoint_Z private
Definition at line 176 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ProtonStartPoint_X
double larcv::Run3DTracker::_ProtonStartPoint_X private
Definition at line 153 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ProtonStartPoint_Y
double larcv::Run3DTracker::_ProtonStartPoint_Y private
Definition at line 157 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_ProtonStartPoint_Z
double larcv::Run3DTracker::_ProtonStartPoint_Z private
Definition at line 161 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
_Reco_goodness_v
std::vector<bool> larcv::Run3DTracker::_Reco_goodness_v private
Definition at line 121 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_recoTree
TTree* larcv::Run3DTracker::_recoTree private
Definition at line 92 of file Run3DTracker.h.
Referenced by finalize(), initialize(), and process().
_RecoVertex
TVector3 larcv::Run3DTracker::_RecoVertex private
Definition at line 128 of file Run3DTracker.h.
Referenced by initialize(), and process().
_run
int larcv::Run3DTracker::_run private
Definition at line 78 of file Run3DTracker.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), MCevaluation(), and process().
_spline_file
std::string larcv::Run3DTracker::_spline_file private
Definition at line 183 of file Run3DTracker.h.
Referenced by initialize(), and SetSplineLocation().
_storage
larlite::storage_manager larcv::Run3DTracker::_storage private
Definition at line 70 of file Run3DTracker.h.
Referenced by advance_larlite(), finalize(), initialize(), and process().
_subrun
int larcv::Run3DTracker::_subrun private
Definition at line 79 of file Run3DTracker.h.
Referenced by advance_larlite(), ClearEvent(), initialize(), MCevaluation(), and process().
_tooManyTracksAtVertex
bool larcv::Run3DTracker::_tooManyTracksAtVertex private
Definition at line 135 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_tooShortDeadWire
bool larcv::Run3DTracker::_tooShortDeadWire private
Definition at line 133 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_tooShortFaintTrack
bool larcv::Run3DTracker::_tooShortFaintTrack private
Definition at line 134 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_TotalADCvalues_v
std::vector< std::vector<double> > larcv::Run3DTracker::_TotalADCvalues_v private
Definition at line 119 of file Run3DTracker.h.
Referenced by initialize(), and process().
_track_Goodness_v
std::vector<bool> larcv::Run3DTracker::_track_Goodness_v private
Definition at line 122 of file Run3DTracker.h.
Referenced by initialize(), and process().
_trackQ10_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ10_v private
Definition at line 115 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trackQ20_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ20_v private
Definition at line 116 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trackQ30_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ30_v private
Definition at line 117 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trackQ3_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ3_v private
Definition at line 113 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trackQ50_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ50_v private
Definition at line 118 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trackQ5_v
std::vector<std::vector<double> > larcv::Run3DTracker::_trackQ5_v private
Definition at line 114 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_trk_id_v
std::vector<int> larcv::Run3DTracker::_trk_id_v private
Definition at line 93 of file Run3DTracker.h.
Referenced by initialize(), and process().
_true_roi_producer
std::string larcv::Run3DTracker::_true_roi_producer private
Definition at line 182 of file Run3DTracker.h.
Referenced by configure(), and process().
_Trunc_dQdX1_v
std::vector<double> larcv::Run3DTracker::_Trunc_dQdX1_v private
Definition at line 110 of file Run3DTracker.h.
Referenced by initialize(), and process().
_Trunc_dQdX3_v
std::vector<double> larcv::Run3DTracker::_Trunc_dQdX3_v private
Definition at line 111 of file Run3DTracker.h.
Referenced by initialize(), and process().
_vertexInfo
std::vector< std::vector<int> > larcv::Run3DTracker::_vertexInfo private
Definition at line 72 of file Run3DTracker.h.
_vertexPhi
std::vector<double> larcv::Run3DTracker::_vertexPhi private
Definition at line 99 of file Run3DTracker.h.
Referenced by initialize(), and process().
_vertexTheta
std::vector<double> larcv::Run3DTracker::_vertexTheta private
Definition at line 100 of file Run3DTracker.h.
Referenced by initialize(), and process().
_vtx_id
int larcv::Run3DTracker::_vtx_id private
Definition at line 85 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_x
float larcv::Run3DTracker::_vtx_x private
Definition at line 141 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_y
float larcv::Run3DTracker::_vtx_y private
Definition at line 142 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx_z
float larcv::Run3DTracker::_vtx_z private
Definition at line 143 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
checkEvents
std::vector<std::string> larcv::Run3DTracker::checkEvents private
Definition at line 89 of file Run3DTracker.h.
Referenced by MCevaluation().
Em_t
double larcv::Run3DTracker::Em_t private
Definition at line 76 of file Run3DTracker.h.
Referenced by FillMC(), and MCevaluation().
Ep_t
double larcv::Run3DTracker::Ep_t private
Definition at line 75 of file Run3DTracker.h.
Referenced by FillMC(), and MCevaluation().
GoodVertex
bool larcv::Run3DTracker::GoodVertex private
Definition at line 130 of file Run3DTracker.h.
Referenced by ClearVertex(), initialize(), and process().
iTrack
int larcv::Run3DTracker::iTrack private
Definition at line 69 of file Run3DTracker.h.
MCvertex
TVector3 larcv::Run3DTracker::MCvertex private
Definition at line 126 of file Run3DTracker.h.
Referenced by ClearEvent(), FillMC(), and initialize().
MCVertices
std::vector<TVector3> larcv::Run3DTracker::MCVertices private
Definition at line 125 of file Run3DTracker.h.
Referenced by ClearEvent(), and FillMC().
NeutrinoEnergyReco
double larcv::Run3DTracker::NeutrinoEnergyReco private
Definition at line 74 of file Run3DTracker.h.
NeutrinoEnergyTh
double larcv::Run3DTracker::NeutrinoEnergyTh private
Definition at line 73 of file Run3DTracker.h.
Referenced by FillMC(), and MCevaluation().
NgoodReco
int larcv::Run3DTracker::NgoodReco private
Definition at line 87 of file Run3DTracker.h.
NtracksReco
int larcv::Run3DTracker::NtracksReco private
Definition at line 88 of file Run3DTracker.h.
Referenced by initialize(), and process().
NvertexSubmitted
int larcv::Run3DTracker::NvertexSubmitted private
Definition at line 86 of file Run3DTracker.h.
Referenced by process().
out_dir
std::string larcv::Run3DTracker::out_dir private
Definition at line 185 of file Run3DTracker.h.
Referenced by initialize(), and SetOutDir().
RecoVertex
TVector3 larcv::Run3DTracker::RecoVertex private
Definition at line 127 of file Run3DTracker.h.
Referenced by process().
tracker
larcv::AStarTracker larcv::Run3DTracker::tracker private
Definition at line 71 of file Run3DTracker.h.
Referenced by finalize(), initialize(), MCevaluation(), process(), and SetSplineLocation().
The documentation for this class was generated from the following files:
Run3DTracker.h
Run3DTracker.cxx