LArCV: larcv::ROIClipperProcessFactory Class Reference
larcv::ROIClipperProcessFactory Class Reference
#include <ROIClipper.h>
Public Member Functions
ROIClipperProcessFactory ()
~ROIClipperProcessFactory ()
ProcessBase * create (const std::string instance_name)
Abstract constructor method.
Detailed Description
Definition at line 27 of file ROIClipper.h.
Constructor & Destructor Documentation
ROIClipperProcessFactory()
larcv::ROIClipperProcessFactory::ROIClipperProcessFactory () inline
Definition at line 30 of file ROIClipper.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ROIClipper",this); }
~ROIClipperProcessFactory()
larcv::ROIClipperProcessFactory::~ROIClipperProcessFactory () inline
Definition at line 31 of file ROIClipper.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ROIClipperProcessFactory::create (const std::string instance_name) inline virtual
Abstract constructor method.
Implements larcv::ProcessFactoryBase.
Definition at line 32 of file ROIClipper.h.
References larcv::ROIClipper::ROIClipper().
 { return new ROIClipper(instance_name); }
The documentation for this class was generated from the following file:
ROIClipper.h