LArCV: larcv::WireMaskProcessFactory Class Reference
larcv::WireMaskProcessFactory Class Reference
#include <WireMask.h>
Public Member Functions
WireMaskProcessFactory ()
ctor
~WireMaskProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 57 of file WireMask.h.
Constructor & Destructor Documentation
WireMaskProcessFactory()
larcv::WireMaskProcessFactory::WireMaskProcessFactory () inline
ctor
Definition at line 60 of file WireMask.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("WireMask",this); }
~WireMaskProcessFactory()
larcv::WireMaskProcessFactory::~WireMaskProcessFactory () inline
dtor
Definition at line 62 of file WireMask.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::WireMaskProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 64 of file WireMask.h.
References larcv::WireMask::WireMask().
 { return new WireMask(instance_name); }
The documentation for this class was generated from the following file:
WireMask.h