LArCV: larcv::ResizeImage Class Reference
larcv::ResizeImage Class Reference
#include <ResizeImage.h>
Public Member Functions
ResizeImage (const std::string name="ResizeImage")
Default constructor.
~ResizeImage ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _input_producer
std::string _output_producer
std::vector< double > _origin_x_v
std::vector< double > _origin_y_v
std::vector< double > _width_v
std::vector< double > _height_v
std::vector< size_t > _rows_v
std::vector< size_t > _cols_v
Detailed Description
Definition at line 26 of file ResizeImage.h.
Constructor & Destructor Documentation
ResizeImage()
larcv::ResizeImage::ResizeImage (const std::string name = "ResizeImage")
Default constructor.
Definition at line 10 of file ResizeImage.cxx.
Referenced by larcv::ResizeImageProcessFactory::create().
     : ProcessBase(name)
   {}
~ResizeImage()
larcv::ResizeImage::~ResizeImage () inline
Default destructor.
Definition at line 34 of file ResizeImage.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ResizeImage::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file ResizeImage.cxx.
References _cols_v, _height_v, _input_producer, _origin_x_v, _origin_y_v, _output_producer, _rows_v, _width_v, larcv::PSet::get(), and LARCV_CRITICAL.
Referenced by ~ResizeImage().
   {
     _input_producer  = cfg.get<std::string>("InputProducer");
     _output_producer = cfg.get<std::string>("OutputProducer");
     _origin_x_v = cfg.get<std::vector<double> >("OriginX");
     _origin_y_v = cfg.get<std::vector<double> >("OriginY");
     _width_v    = cfg.get<std::vector<double> >("Width");
     _height_v   = cfg.get<std::vector<double> >("Height");
     _rows_v     = cfg.get<std::vector<size_t> >("Rows");
     _cols_v     = cfg.get<std::vector<size_t> >("Cols");
     if(_origin_x_v.size() != _origin_y_v.size() ||
        _origin_x_v.size() != _width_v.size() ||
        _origin_x_v.size() != _height_v.size() ||
        _origin_x_v.size() != _rows_v.size() ||
        _origin_x_v.size() != _cols_v.size() ) {
       LARCV_CRITICAL() << "Input parameter array size does not match!" << std::endl;
       throw larbys();
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ResizeImage::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 75 of file ResizeImage.cxx.
Referenced by ~ResizeImage().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ResizeImage::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 35 of file ResizeImage.cxx.
Referenced by ~ResizeImage().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ResizeImage::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 38 of file ResizeImage.cxx.
References _cols_v, _height_v, _input_producer, _origin_x_v, _origin_y_v, _output_producer, _rows_v, _width_v, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, LARCV_CRITICAL, and LARCV_INFO.
Referenced by ~ResizeImage().
   {
     auto event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_output_producer));
     auto const& image_v = event_image->Image2DArray();
     std::vector<larcv::Image2D> res_image_v;
     if(image_v.size() != _origin_x_v.size()) {
       if(image_v.empty()) {
     LARCV_INFO() << "Skipping an empty image event..." << std::endl;
     return false;
       }
       LARCV_CRITICAL() << "Image array size does not match with input parameter array size!" << std::endl;
       throw larbys();
     }
     for(size_t i=0; i<image_v.size(); ++i) {
       auto const& image = image_v[i];
       ImageMeta res_meta(_width_v[i], _height_v[i],
              _rows_v[i], _cols_v[i],
              _origin_x_v[i], _origin_y_v[i],
              image.meta().plane());
       Image2D res(res_meta);
       res.paint(0.);
       res.overlay(image);
       res_image_v.emplace_back(std::move(res));
     }
     auto output_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_input_producer));
     output_image->Emplace(std::move(res_image_v));
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_cols_v
std::vector<size_t> larcv::ResizeImage::_cols_v private
Definition at line 53 of file ResizeImage.h.
Referenced by configure(), and process().
_height_v
std::vector<double> larcv::ResizeImage::_height_v private
Definition at line 51 of file ResizeImage.h.
Referenced by configure(), and process().
_input_producer
std::string larcv::ResizeImage::_input_producer private
Definition at line 46 of file ResizeImage.h.
Referenced by configure(), and process().
_origin_x_v
std::vector<double> larcv::ResizeImage::_origin_x_v private
Definition at line 48 of file ResizeImage.h.
Referenced by configure(), and process().
_origin_y_v
std::vector<double> larcv::ResizeImage::_origin_y_v private
Definition at line 49 of file ResizeImage.h.
Referenced by configure(), and process().
_output_producer
std::string larcv::ResizeImage::_output_producer private
Definition at line 47 of file ResizeImage.h.
Referenced by configure(), and process().
_rows_v
std::vector<size_t> larcv::ResizeImage::_rows_v private
Definition at line 52 of file ResizeImage.h.
Referenced by configure(), and process().
_width_v
std::vector<double> larcv::ResizeImage::_width_v private
Definition at line 50 of file ResizeImage.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ResizeImage.h
ResizeImage.cxx