LArCV: larcv::EventParticleROI Class Reference
larcv::EventParticleROI Class Reference
User defined class EventParticleROI ...
#include <EventParticleROI.h>
Public Member Functions
EventParticleROI ()
Default constructor.
~EventParticleROI ()
Default destructor.
void clear ()
Set all run/subrun/event to kINVALID_SIZE.
const std::vector< larcv::ParticleROI > & ParticleROIArray () const
const ParticleROI & at (ParticleROIIndex_t id)
void Append (const ParticleROI &img)
void Set (const std::vector< larcv::ParticleROI > &part_v)
void Emplace (ParticleROI &&img)
void Emplace (std::vector< larcv::ParticleROI > &&part_v)
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::vector< larcv::ParticleROI > _part_v
Detailed Description
User defined class EventParticleROI ...
these comments are used to generate doxygen documentation!
Definition at line 27 of file EventParticleROI.h.
Constructor & Destructor Documentation
EventParticleROI()
larcv::EventParticleROI::EventParticleROI () inline
Default constructor.
Definition at line 32 of file EventParticleROI.h.
 {}
~EventParticleROI()
larcv::EventParticleROI::~EventParticleROI () inline
Default destructor.
Definition at line 35 of file EventParticleROI.h.
References clear().
 {}
Member Function Documentation
Append()
void larcv::EventParticleROI::Append (const ParticleROI & img)
Definition at line 20 of file EventParticleROI.cxx.
References _part_v.
Referenced by ParticleROIArray(), and Set().
   {
     _part_v.push_back(part);
     _part_v.back().index((ParticleROIIndex_t)(_part_v.size()-1));
   }
at()
const ParticleROI & larcv::EventParticleROI::at (ParticleROIIndex_t id)
Definition at line 14 of file EventParticleROI.cxx.
References _part_v.
Referenced by ParticleROIArray().
   {
     if( id >= _part_v.size() ) throw larbys("Invalid request (ImageIndex_t out-o-range)!");
     return _part_v[id];
   }
clear()
void larcv::EventParticleROI::clear () virtual
Set all run/subrun/event to kINVALID_SIZE.
Reimplemented from larcv::EventBase.
Definition at line 8 of file EventParticleROI.cxx.
References _part_v, and larcv::EventBase::clear().
Referenced by ~EventParticleROI().
   {
     EventBase::clear();
     _part_v.clear();
   }
Emplace() [1/2]
void larcv::EventParticleROI::Emplace (ParticleROI && img)
Definition at line 33 of file EventParticleROI.cxx.
References _part_v.
Referenced by ParticleROIArray().
   {
     _part_v.emplace_back(part);
     _part_v.back().index((ParticleROIIndex_t)(_part_v.size()-1));
   }
Emplace() [2/2]
void larcv::EventParticleROI::Emplace (std::vector< larcv::ParticleROI > && part_v)
Definition at line 39 of file EventParticleROI.cxx.
References _part_v.
   {
     _part_v.clear();
     std::swap(_part_v,part_v);
     for(size_t i=0; i<_part_v.size(); ++i) _part_v[i].Index((ParticleROIIndex_t)i);
   }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
ParticleROIArray()
const std::vector<larcv::ParticleROI>& larcv::EventParticleROI::ParticleROIArray () const inline
Definition at line 39 of file EventParticleROI.h.
References _part_v, Append(), at(), Emplace(), and Set().
 { return _part_v; }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
Set()
void larcv::EventParticleROI::Set (const std::vector< larcv::ParticleROI > & part_v)
Definition at line 26 of file EventParticleROI.cxx.
References _part_v, and Append().
Referenced by ParticleROIArray().
   {
     _part_v.clear();
     _part_v.reserve(part_v.size());
     for(auto const& p : part_v) Append(p);
   }
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
_part_v
std::vector<larcv::ParticleROI> larcv::EventParticleROI::_part_v private
Definition at line 52 of file EventParticleROI.h.
Referenced by Append(), at(), clear(), Emplace(), ParticleROIArray(), and Set().
The documentation for this class was generated from the following files:
EventParticleROI.h
EventParticleROI.cxx