LArCV: larcv::LArbysImageAnaBase Class Reference
larcv::LArbysImageAnaBase Class Reference abstract
#include <LArbysImageAnaBase.h>
Public Member Functions
LArbysImageAnaBase (const std::string name="LArbysImageAnaBase")
~LArbysImageAnaBase ()
virtual void Configure (const larcv::PSet &)=0
virtual void Initialize ()=0
virtual bool Analyze (larocv::ImageClusterManager &mgr)=0
virtual void Finalize (TFile *fout=nullptr)=0
void EventID (const size_t entry, const size_t run, const size_t subrun, const size_t event)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
size_t _run
Unique event keys.
size_t _subrun
size_t _event
size_t _entry
Detailed Description
Definition at line 12 of file LArbysImageAnaBase.h.
Constructor & Destructor Documentation
LArbysImageAnaBase()
larcv::LArbysImageAnaBase::LArbysImageAnaBase (const std::string name = "LArbysImageAnaBase")
Definition at line 7 of file LArbysImageAnaBase.cxx.
     : larcv_base(name)
   {}
~LArbysImageAnaBase()
larcv::LArbysImageAnaBase::~LArbysImageAnaBase () inline
Definition at line 17 of file LArbysImageAnaBase.h.
References Analyze(), Configure(), Finalize(), and Initialize().
 {}
Member Function Documentation
Analyze()
virtual bool larcv::LArbysImageAnaBase::Analyze (larocv::ImageClusterManager & mgr) pure virtual
Referenced by ~LArbysImageAnaBase().
Configure()
virtual void larcv::LArbysImageAnaBase::Configure (const larcv::PSet &) pure virtual
Implemented in larcv::LArbysImageResult.
Referenced by ~LArbysImageAnaBase().
EventID()
void larcv::LArbysImageAnaBase::EventID (const size_t entry, const size_t run, const size_t subrun, const size_t event) inline
Definition at line 24 of file LArbysImageAnaBase.h.
References _entry, _event, _run, and _subrun.
     { _entry = entry; _run = run; _subrun = subrun; _event = event; }
Finalize()
virtual void larcv::LArbysImageAnaBase::Finalize (TFile * fout = nullptr) pure virtual
Implemented in larcv::LArbysImageResult.
Referenced by ~LArbysImageAnaBase().
Initialize()
virtual void larcv::LArbysImageAnaBase::Initialize () pure virtual
Implemented in larcv::LArbysImageResult.
Referenced by ~LArbysImageAnaBase().
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_entry
size_t larcv::LArbysImageAnaBase::_entry protected
Definition at line 34 of file LArbysImageAnaBase.h.
Referenced by EventID().
_event
size_t larcv::LArbysImageAnaBase::_event protected
Definition at line 33 of file LArbysImageAnaBase.h.
Referenced by EventID().
_run
size_t larcv::LArbysImageAnaBase::_run protected
Unique event keys.
Definition at line 31 of file LArbysImageAnaBase.h.
Referenced by EventID().
_subrun
size_t larcv::LArbysImageAnaBase::_subrun protected
Definition at line 32 of file LArbysImageAnaBase.h.
Referenced by EventID().
The documentation for this class was generated from the following files:
LArbysImageAnaBase.h
LArbysImageAnaBase.cxx