LArCV: larcv::ConfigManager Class Reference
larcv::ConfigManager Class Reference
User defined class ConfigManager ...
#include <ConfigManager.h>
Public Member Functions
ConfigManager ()
Default constructor.
~ConfigManager ()
Default destructor.
void AddConfigFile (const std::string cfg_file)
Adder of configuration from a file.
void AddConfigString (const std::string cfg_str)
Adder of configuration from parsed string.
const PSet & GetConfig (const std::string cfg)
Configuration retrieval method.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static const ConfigManager & get ()
Shared static reference getter.
Private Attributes
std::set< std::string > _cfg_files
PSet _cfg
Static Private Attributes
static ConfigManager * _me = nullptr
Detailed Description
User defined class ConfigManager ...
these comments are used to generate doxygen documentation!
Definition at line 29 of file ConfigManager.h.
Constructor & Destructor Documentation
ConfigManager()
larcv::ConfigManager::ConfigManager () inline
Default constructor.
Definition at line 34 of file ConfigManager.h.
Referenced by get().
                     : larcv_base("ConfigManager")
     {}
~ConfigManager()
larcv::ConfigManager::~ConfigManager () inline
Default destructor.
Definition at line 38 of file ConfigManager.h.
 {}
Member Function Documentation
AddConfigFile()
void larcv::ConfigManager::AddConfigFile (const std::string cfg_file)
Adder of configuration from a file.
Definition at line 10 of file ConfigManager.cxx.
References _cfg, _cfg_files, larcv::PSet::add_pset(), larcv::CreatePSetFromFile(), and LARCV_CRITICAL.
Referenced by get().
   {
     if(_cfg_files.find(cfg_file)!=_cfg_files.end()) {
       LARCV_CRITICAL() << "Duplicate addition of config fiel: " << cfg_file << std::endl;
       throw larbys();
     }
     _cfg.add_pset(CreatePSetFromFile(cfg_file));
   }
AddConfigString()
void larcv::ConfigManager::AddConfigString (const std::string cfg_str)
Adder of configuration from parsed string.
Definition at line 20 of file ConfigManager.cxx.
References _cfg, larcv::PSet::add(), and larcv::PSet::add_pset().
Referenced by get().
   {
     PSet p;
     p.add(cfg_str);
     _cfg.add_pset(p);
   }
get()
static const ConfigManager& larcv::ConfigManager::get () inline static
Shared static reference getter.
Definition at line 40 of file ConfigManager.h.
References _me, AddConfigFile(), AddConfigString(), ConfigManager(), and GetConfig().
     {
       if(!_me) _me = new ConfigManager;
       return *_me;
     }
GetConfig()
const PSet & larcv::ConfigManager::GetConfig (const std::string cfg)
Configuration retrieval method.
Definition at line 27 of file ConfigManager.cxx.
References _cfg, and larcv::PSet::get_pset().
Referenced by get().
   {
     return _cfg.get_pset(cfg);
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_cfg
PSet larcv::ConfigManager::_cfg private
Definition at line 56 of file ConfigManager.h.
Referenced by AddConfigFile(), AddConfigString(), and GetConfig().
_cfg_files
std::set<std::string> larcv::ConfigManager::_cfg_files private
Definition at line 55 of file ConfigManager.h.
Referenced by AddConfigFile().
_me
ConfigManager * larcv::ConfigManager::_me = nullptr static private
Definition at line 54 of file ConfigManager.h.
Referenced by get().
The documentation for this class was generated from the following files:
ConfigManager.h
ConfigManager.cxx