LArCV: larcv::Voxel3DSet Class Reference
larcv::Voxel3DSet Class Reference
Container of multiple voxels consisting of ordered sparse vector and meta data.
#include <Voxel3D.h>
Public Member Functions
Voxel3DSet (const Voxel3DMeta &meta=Voxel3DMeta())
Default ctor.
~Voxel3DSet ()
Default dtor.
const std::vector< larcv::Voxel3D > & GetVoxelSet () const
getter
const Voxel3DMeta & GetVoxelMeta () const
getter
void Clear ()
clear
void Reset (const Voxel3DMeta &meta)
reset
void Add (const Voxel3D &vox)
adder
void Emplace (Voxel3D &&vox)
adder
void Move (Voxel3DSet &&vox_set)
mover
Private Attributes
Voxel3DMeta _meta
Meta data information.
std::vector< larcv::Voxel3D > _voxel_v
Ordered sparse vector of voxels.
Detailed Description
Container of multiple voxels consisting of ordered sparse vector and meta data.
Definition at line 177 of file Voxel3D.h.
Constructor & Destructor Documentation
Voxel3DSet()
larcv::Voxel3DSet::Voxel3DSet (const Voxel3DMeta & meta = Voxel3DMeta())
Default ctor.
Definition at line 161 of file Voxel3D.cxx.
     : _meta(meta)
   {}
~Voxel3DSet()
larcv::Voxel3DSet::~Voxel3DSet () inline
Default dtor.
Definition at line 182 of file Voxel3D.h.
 {}
Member Function Documentation
Add()
void larcv::Voxel3DSet::Add (const Voxel3D & vox)
adder
Definition at line 165 of file Voxel3D.cxx.
References Emplace().
   {
     Voxel3D copy(vox);
     Emplace(std::move(copy));
   }
Clear()
void larcv::Voxel3DSet::Clear () inline
clear
Definition at line 192 of file Voxel3D.h.
Referenced by larcv::EventVoxel3D::clear().
 { _voxel_v.clear(); _meta.Clear();}
Emplace()
void larcv::Voxel3DSet::Emplace (Voxel3D && vox)
adder
Definition at line 171 of file Voxel3D.cxx.
References _meta, _voxel_v, and larcv::Voxel3DMeta::Valid().
Referenced by Add(), and supera::SimCh2Voxel3D().
   {
     if(!_meta.Valid())
       throw larbys("Voxel3DSet::Emplace cannot be called without a valid meta!");
     // In case it's empty or greater than the last one
     if(_voxel_v.empty() || _voxel_v.back() < vox) {
       _voxel_v.emplace_back(std::move(vox));
       return;
     }
     // In case it's smaller than the first one
     if(_voxel_v.front() > vox) {
       _voxel_v.emplace_back(std::move(vox));
       for(size_t idx=0; (idx+1)<_voxel_v.size(); ++idx) {
     auto& element1 = _voxel_v[ _voxel_v.size() - (idx+1) ];
     auto& element2 = _voxel_v[ _voxel_v.size() - (idx+2) ];
     std::swap( element1, element2 );
       }
       return;
     }
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     // Cannot be the end
     if( iter == _voxel_v.end() )
       throw larbys("Voxel3DSet sorting logic error!");
     // If found, merge
     if( !(vox < (*iter)) ) {
       (*iter) += vox.Value();
       return;
     }
     // Else insert @ appropriate place
     else {
       size_t target_loc = iter - _voxel_v.begin();
       _voxel_v.emplace_back(std::move(vox));
       for(size_t idx=target_loc; (idx+1)<_voxel_v.size(); ++idx) {
     auto& element1 = _voxel_v[ _voxel_v.size() - (idx+1) ];
     auto& element2 = _voxel_v[ _voxel_v.size() - (idx+2) ];
     std::swap( element1, element2 );
       }
     }
     return;
   }
GetVoxelMeta()
const Voxel3DMeta& larcv::Voxel3DSet::GetVoxelMeta () const inline
getter
Definition at line 189 of file Voxel3D.h.
     { return _meta; }
GetVoxelSet()
const std::vector<larcv::Voxel3D>& larcv::Voxel3DSet::GetVoxelSet () const inline
getter
Definition at line 185 of file Voxel3D.h.
     { return _voxel_v; }
Move()
void larcv::Voxel3DSet::Move (Voxel3DSet && vox_set) inline
mover
Definition at line 203 of file Voxel3D.h.
     { _meta = std::move(vox_set._meta); _voxel_v = std::move(vox_set._voxel_v); }
Reset()
void larcv::Voxel3DSet::Reset (const Voxel3DMeta & meta) inline
reset
Definition at line 194 of file Voxel3D.h.
     { Clear(); _meta = meta; }
Member Data Documentation
_meta
Voxel3DMeta larcv::Voxel3DSet::_meta private
Meta data information.
Definition at line 209 of file Voxel3D.h.
Referenced by Emplace().
_voxel_v
std::vector<larcv::Voxel3D> larcv::Voxel3DSet::_voxel_v private
Ordered sparse vector of voxels.
Definition at line 211 of file Voxel3D.h.
Referenced by Emplace().
The documentation for this class was generated from the following files:
Voxel3D.h
Voxel3D.cxx