LArCV: larcv::ImageROICheckMC Class Reference
larcv::ImageROICheckMC Class Reference
#include <ImageROICheckMC.h>
Public Member Functions
ImageROICheckMC (const std::string name="ImageROICheckMC")
Default constructor.
~ImageROICheckMC ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
bool CheckNumNuROIs (IOManager &mgr)
bool VertexInFid (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _producer_roi
bool _check_num_bb
bool _check_vtxfid
float xmin = 0.0
float ymin = -116.5
float zmin = 0.0
float xmax = 256.25
float ymax = 116.5
float zmax = 1036.8
float edge_x = 10.0
float edge_y = 10.0
float edge_z = 10.0
Detailed Description
Definition at line 31 of file ImageROICheckMC.h.
Constructor & Destructor Documentation
ImageROICheckMC()
larcv::ImageROICheckMC::ImageROICheckMC (const std::string name = "ImageROICheckMC")
Default constructor.
Definition at line 12 of file ImageROICheckMC.cxx.
Referenced by larcv::ImageROICheckMCProcessFactory::create().
     : ProcessBase(name)
   {}
~ImageROICheckMC()
larcv::ImageROICheckMC::~ImageROICheckMC () inline
Default destructor.
Definition at line 39 of file ImageROICheckMC.h.
References CheckNumNuROIs(), configure(), finalize(), initialize(), process(), and VertexInFid().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
CheckNumNuROIs()
bool larcv::ImageROICheckMC::CheckNumNuROIs (IOManager & mgr)
Definition at line 25 of file ImageROICheckMC.cxx.
References _producer_roi, larcv::IOManager< T >::get_data(), and larcv::kProductROI.
Referenced by process(), and ~ImageROICheckMC().
   {
     const auto event_roi = (larcv::EventROI*) mgr.get_data(kProductROI,_producer_roi);
     auto roi = (*event_roi).at(0);
     if ((roi.BB()).size() != 3) { return false; }
     return true;
   }
configure()
void larcv::ImageROICheckMC::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file ImageROICheckMC.cxx.
References _check_num_bb, _check_vtxfid, _producer_roi, and larcv::PSet::get().
Referenced by ~ImageROICheckMC().
   {
     _producer_roi = cfg.get<std::string>("MCProducer");
     _check_num_bb = cfg.get<bool>("CheckNumNuROIs");
     _check_vtxfid = cfg.get<bool>("CheckVertexInFid");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ImageROICheckMC::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 74 of file ImageROICheckMC.cxx.
Referenced by ~ImageROICheckMC().
 {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ImageROICheckMC::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 23 of file ImageROICheckMC.cxx.
Referenced by ~ImageROICheckMC().
 {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ImageROICheckMC::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 52 of file ImageROICheckMC.cxx.
References _check_num_bb, _check_vtxfid, CheckNumNuROIs(), larcv::IOManager< T >::current_entry(), LARCV_DEBUG, and VertexInFid().
Referenced by ~ImageROICheckMC().
   {
     if (_check_num_bb)
       {
     if (CheckNumNuROIs(mgr) == false) {
       LARCV_DEBUG() << "ROI filtered @ entry: " << mgr.current_entry() << std::endl;
       return false;
     }
       }
     if (_check_vtxfid)
       {
     if (VertexInFid(mgr) == false) {
       LARCV_DEBUG() << "Vertex filtered @ entry: " << mgr.current_entry() << std::endl;
       return false;
     }
       }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
VertexInFid()
bool larcv::ImageROICheckMC::VertexInFid (IOManager & mgr)
Definition at line 36 of file ImageROICheckMC.cxx.
References _producer_roi, edge_x, edge_y, edge_z, larcv::IOManager< T >::get_data(), larcv::kProductROI, xmax, xmin, ymax, ymin, zmax, and zmin.
Referenced by process(), and ~ImageROICheckMC().
   {
     const auto event_roi = (larcv::EventROI*) mgr.get_data(kProductROI,_producer_roi);
     auto roi = (*event_roi).at(0);
     bool xInFid = (roi.X() < (xmax - edge_x) && (roi.X() > xmin + edge_x) );
     bool yInFid = (roi.Y() < (ymax - edge_y) && (roi.Y() > ymin + edge_y) );
     bool zInFid = (roi.Z() < (zmax - edge_z) && (roi.Z() > zmin + edge_z) );
     if (xInFid && yInFid && zInFid) {return true;}
     return false;
   }
Member Data Documentation
_check_num_bb
bool larcv::ImageROICheckMC::_check_num_bb private
Definition at line 56 of file ImageROICheckMC.h.
Referenced by configure(), and process().
_check_vtxfid
bool larcv::ImageROICheckMC::_check_vtxfid private
Definition at line 57 of file ImageROICheckMC.h.
Referenced by configure(), and process().
_producer_roi
std::string larcv::ImageROICheckMC::_producer_roi private
Definition at line 55 of file ImageROICheckMC.h.
Referenced by CheckNumNuROIs(), configure(), and VertexInFid().
edge_x
float larcv::ImageROICheckMC::edge_x = 10.0 private
Definition at line 67 of file ImageROICheckMC.h.
Referenced by VertexInFid().
edge_y
float larcv::ImageROICheckMC::edge_y = 10.0 private
Definition at line 68 of file ImageROICheckMC.h.
Referenced by VertexInFid().
edge_z
float larcv::ImageROICheckMC::edge_z = 10.0 private
Definition at line 69 of file ImageROICheckMC.h.
Referenced by VertexInFid().
xmax
float larcv::ImageROICheckMC::xmax = 256.25 private
Definition at line 63 of file ImageROICheckMC.h.
Referenced by VertexInFid().
xmin
float larcv::ImageROICheckMC::xmin = 0.0 private
Definition at line 59 of file ImageROICheckMC.h.
Referenced by VertexInFid().
ymax
float larcv::ImageROICheckMC::ymax = 116.5 private
Definition at line 64 of file ImageROICheckMC.h.
Referenced by VertexInFid().
ymin
float larcv::ImageROICheckMC::ymin = -116.5 private
Definition at line 60 of file ImageROICheckMC.h.
Referenced by VertexInFid().
zmax
float larcv::ImageROICheckMC::zmax = 1036.8 private
Definition at line 65 of file ImageROICheckMC.h.
Referenced by VertexInFid().
zmin
float larcv::ImageROICheckMC::zmin = 0.0 private
Definition at line 61 of file ImageROICheckMC.h.
Referenced by VertexInFid().
The documentation for this class was generated from the following files:
ImageROICheckMC.h
ImageROICheckMC.cxx