LArCV: larcv::SuperaBase Class Reference
larcv::SuperaBase Class Reference
#include <SuperaBase.h>
Public Member Functions
SuperaBase (const std::string name="SuperaBase")
Default constructor.
~SuperaBase ()
Default destructor.
virtual void configure (const PSet &)
virtual void initialize ()
virtual bool process (IOManager &mgr)
virtual void finalize ()
virtual bool is (const std::string question) const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
const std::string & LArDataLabel (supera::LArDataType_t type) const
template<class T >
const std::vector< T > & LArData () const
int TimeOffset () const
void ClearEventData ()
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _empty_string
int _time_offset
std::map< supera::LArDataType_t, std::string > _data_request_m
std::vector< supera::LArWire_t > * _ptr_wire_v
std::vector< supera::LArHit_t > * _ptr_hit_v
std::vector< supera::LArOpDigit_t > * _ptr_opdigit_v
std::vector< supera::LArSimCh_t > * _ptr_sch_v
std::vector< supera::LArMCTruth_t > * _ptr_mctruth_v
std::vector< supera::LArMCTrack_t > * _ptr_mct_v
std::vector< supera::LArMCShower_t > * _ptr_mcs_v
Detailed Description
Definition at line 31 of file SuperaBase.h.
Constructor & Destructor Documentation
SuperaBase()
larcv::SuperaBase::SuperaBase (const std::string name = "SuperaBase")
Default constructor.
Definition at line 10 of file SuperaBase.cxx.
References ClearEventData().
Referenced by larcv::SuperaBaseProcessFactory::create().
     : ProcessBase(name)
     , _empty_string()
   { ClearEventData(); }
~SuperaBase()
larcv::SuperaBase::~SuperaBase () inline
Default destructor.
Definition at line 39 of file SuperaBase.h.
References configure(), finalize(), initialize(), is(), LArData(), LArDataLabel(), process(), and Request().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData ()
Definition at line 89 of file SuperaBase.cxx.
References _ptr_hit_v, _ptr_mcs_v, _ptr_mct_v, _ptr_mctruth_v, _ptr_opdigit_v, _ptr_sch_v, and _ptr_wire_v.
Referenced by finalize(), initialize(), larcv::SuperaMetaMaker::process(), SuperaBase(), and TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
configure()
void larcv::SuperaBase::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Reimplemented in larcv::SuperaMCROI, larcv::SuperaHit, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SuperaChStatus, larcv::SuperaMCPCluster, and larcv::SuperaMetaMaker.
Definition at line 25 of file SuperaBase.cxx.
References _time_offset, larcv::PSet::get(), supera::kLArHit_t, supera::kLArMCShower_t, supera::kLArMCTrack_t, supera::kLArMCTruth_t, supera::kLArOpDigit_t, supera::kLArSimCh_t, supera::kLArWire_t, LARCV_INFO, and Request().
Referenced by larcv::SuperaMetaMaker::configure(), larcv::SuperaChStatus::configure(), larcv::SuperaSimCh::configure(), larcv::SuperaSimVoxel3D::configure(), larcv::SuperaOpDigit::configure(), larcv::SuperaKeyPointCluster::configure(), larcv::SuperaWire::configure(), larcv::SuperaHit::configure(), larcv::SuperaMCROI::configure(), and ~SuperaBase().
   {
     _time_offset  = cfg.get<int>("TimeOffset",2400);
     auto producer_wire     = cfg.get<std::string>("LArWireProducer",    "");
     auto producer_hit      = cfg.get<std::string>("LArHitProducer",     "");
     auto producer_opdigit  = cfg.get<std::string>("LArOpDigitProducer", "");
     auto producer_mctruth  = cfg.get<std::string>("LArMCTruthProducer", "");
     auto producer_mctrack  = cfg.get<std::string>("LArMCTrackProducer", "");
     auto producer_mcshower = cfg.get<std::string>("LArMCShowerProducer","");
     auto producer_simch    = cfg.get<std::string>("LArSimChProducer",   "");
     if(!producer_wire.empty()    ) {
       LARCV_INFO() << "Requesting Wire data product by " << producer_wire << std::endl;
       Request(supera::LArDataType_t::kLArWire_t, producer_wire);
     }
     if(!producer_hit.empty()     ) {
       LARCV_INFO() << "Requesting Hit data product by " << producer_hit << std::endl;
       Request(supera::LArDataType_t::kLArHit_t, producer_hit);
     }
     if(!producer_opdigit.empty() ) {
       LARCV_INFO() << "Requesting OpDigit data product by " << producer_opdigit << std::endl;
       Request(supera::LArDataType_t::kLArOpDigit_t, producer_opdigit );
     }
     if(!producer_mctruth.empty() ) {
       LARCV_INFO() << "Requesting MCTruth data product by " << producer_mctruth << std::endl;
       Request(supera::LArDataType_t::kLArMCTruth_t, producer_mctruth );
     }
     if(!producer_mctrack.empty() ) {
       LARCV_INFO() << "Requesting MCTrack data product by " << producer_mctrack << std::endl;
       Request(supera::LArDataType_t::kLArMCTrack_t, producer_mctrack );
     }
     if(!producer_mcshower.empty()) {
       LARCV_INFO() << "Requesting MCShower data product by " << producer_mcshower << std::endl;
       Request(supera::LArDataType_t::kLArMCShower_t, producer_mcshower);
     }
     if(!producer_simch.empty()   ) {
       LARCV_INFO() << "Requesting SimCh data product by " << producer_simch << std::endl;
       Request(supera::LArDataType_t::kLArSimCh_t, producer_simch);
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SuperaBase::finalize () virtual
Implements larcv::ProcessBase.
Reimplemented in larcv::SuperaMCROI, larcv::SuperaHit, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SuperaChStatus, larcv::SuperaMCPCluster, and larcv::SuperaMetaMaker.
Definition at line 80 of file SuperaBase.cxx.
References ClearEventData().
Referenced by larcv::SuperaChStatus::finalize(), larcv::SuperaKeyPointCluster::finalize(), larcv::SuperaHit::finalize(), and ~SuperaBase().
   {ClearEventData();}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaBase::initialize () virtual
Implements larcv::ProcessBase.
Reimplemented in larcv::SuperaMCROI, larcv::SuperaHit, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SuperaChStatus, larcv::SuperaMCPCluster, and larcv::SuperaMetaMaker.
Definition at line 74 of file SuperaBase.cxx.
References ClearEventData().
Referenced by larcv::SuperaMetaMaker::initialize(), larcv::SuperaChStatus::initialize(), larcv::SuperaOpDigit::initialize(), larcv::SuperaKeyPointCluster::initialize(), larcv::SuperaWire::initialize(), larcv::SuperaHit::initialize(), larcv::SuperaMCROI::initialize(), and ~SuperaBase().
   {ClearEventData();}
is()
bool larcv::SuperaBase::is (const std::string question) const virtual
Reimplemented from larcv::ProcessBase.
Reimplemented in larcv::SuperaChStatus.
Definition at line 83 of file SuperaBase.cxx.
Referenced by ~SuperaBase().
   {
     if(question == "Supera") return true;
     return false;
   }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &)
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const
Referenced by ~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v)
Definition at line 121 of file SuperaBase.cxx.
References _ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v)
Definition at line 124 of file SuperaBase.cxx.
References _ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v)
Definition at line 127 of file SuperaBase.cxx.
References _ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v)
Definition at line 130 of file SuperaBase.cxx.
References _ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v)
Definition at line 133 of file SuperaBase.cxx.
References _ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v)
Definition at line 136 of file SuperaBase.cxx.
References _ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v)
Definition at line 139 of file SuperaBase.cxx.
References _ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const
Definition at line 18 of file SuperaBase.cxx.
References _data_request_m, and _empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), larcv::SuperaMCROI::process(), and ~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SuperaBase::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Reimplemented in larcv::SuperaMCROI, larcv::SuperaHit, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SuperaChStatus, larcv::SuperaMCPCluster, and larcv::SuperaMetaMaker.
Definition at line 77 of file SuperaBase.cxx.
Referenced by larcv::SuperaMetaMaker::process(), larcv::SuperaChStatus::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), larcv::SuperaMCROI::process(), and ~SuperaBase().
   { return true; }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name)
Definition at line 15 of file SuperaBase.cxx.
References _data_request_m, and larcv::larcv_base::name().
Referenced by configure(), and ~SuperaBase().
   { _data_request_m[type]=name; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline
Definition at line 64 of file SuperaBase.h.
References _time_offset, and ClearEventData().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
 { return _time_offset; }
Member Data Documentation
_data_request_m
std::map<supera::LArDataType_t,std::string> larcv::SuperaBase::_data_request_m private
Definition at line 72 of file SuperaBase.h.
Referenced by LArDataLabel(), and Request().
_empty_string
std::string larcv::SuperaBase::_empty_string private
Definition at line 70 of file SuperaBase.h.
Referenced by LArDataLabel().
_ptr_hit_v
std::vector<supera::LArHit_t>* larcv::SuperaBase::_ptr_hit_v private
Definition at line 74 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArHit_t >().
_ptr_mcs_v
std::vector<supera::LArMCShower_t>* larcv::SuperaBase::_ptr_mcs_v private
Definition at line 79 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArMCShower_t >().
_ptr_mct_v
std::vector<supera::LArMCTrack_t>* larcv::SuperaBase::_ptr_mct_v private
Definition at line 78 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArMCTrack_t >().
_ptr_mctruth_v
std::vector<supera::LArMCTruth_t>* larcv::SuperaBase::_ptr_mctruth_v private
Definition at line 77 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArMCTruth_t >().
_ptr_opdigit_v
std::vector<supera::LArOpDigit_t>* larcv::SuperaBase::_ptr_opdigit_v private
Definition at line 75 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArOpDigit_t >().
_ptr_sch_v
std::vector<supera::LArSimCh_t>* larcv::SuperaBase::_ptr_sch_v private
Definition at line 76 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArSimCh_t >().
_ptr_wire_v
std::vector<supera::LArWire_t>* larcv::SuperaBase::_ptr_wire_v private
Definition at line 73 of file SuperaBase.h.
Referenced by ClearEventData(), LArData(), and larcv::SuperaBase::LArData< supera::LArWire_t >().
_time_offset
int larcv::SuperaBase::_time_offset private
Definition at line 71 of file SuperaBase.h.
Referenced by configure(), and TimeOffset().
The documentation for this class was generated from the following files:
SuperaBase.h
SuperaBase.cxx