LArCV: larcv::UniqueRangeSet< T > Class Template Reference
larcv::UniqueRangeSet< T > Class Template Reference
std::set of larcv::Range, which does not allow any overlap in contained element.
#include <Range.h>
Public Member Functions
UniqueRangeSet ()
default ctor
~UniqueRangeSet ()
default dtor
UniqueRangeSet & operator+= (const UniqueRangeSet &rhs)
Merge two UniqueRangeSet<T>
UniqueRangeSet operator+ (const UniqueRangeSet &rhs)
const T & Start () const
Very first "start" of all contained range.
const T & End () const
Very first "start" of all contained range.
UniqueRangeSet< T > Exclusive (const T start, const T end) const
size_t emplace (const T &start, const T &end)
Modified emplace that merges overlapping range. Return = # merged range.
size_t insert (const Range< T > &a)
Modified insert that merges overlapping range. Return = # merged range.
Public Attributes
K keys
STL member.
Detailed Description
template<class T>
class larcv::UniqueRangeSet< T >
std::set of larcv::Range, which does not allow any overlap in contained element.
std::set<Range> w/ modified insert/emplace function. Original std::set does not allow
modification of element. I assume what we're interested in is "find if the range already \n exists, and merge if it exists". The insert function does that by recursively looking up
overlapping elements w.r.t. input argument of insert function.
One important function worth noting is larcv::UniqueRangeSet::Exclusive which takes two
input arguments, "start" and "end", and returns larcv::UniqueRangeSet of all exclusive
regions between "start" and "end". By definition, merging this return with the original
instance will result in 1 huge larcv::Range.
Definition at line 23 of file Range.h.
Constructor & Destructor Documentation
UniqueRangeSet()
template<class T > larcv::UniqueRangeSet< T >::UniqueRangeSet () inline
default ctor
Definition at line 41 of file UniqueRangeSet.h.
 {}
~UniqueRangeSet()
template<class T > larcv::UniqueRangeSet< T >::~UniqueRangeSet () inline
default dtor
Definition at line 43 of file UniqueRangeSet.h.
 {}
Member Function Documentation
emplace()
template<class T > size_t larcv::UniqueRangeSet< T >::emplace (const T & start, const T & end) inline
Modified emplace that merges overlapping range. Return = # merged range.
Definition at line 109 of file UniqueRangeSet.h.
References larcv::UniqueRangeSet< T >::insert().
Referenced by larcv::UniqueRangeSet< T >::insert(), and larcv::UniqueRangeSet< T >::operator+=().
{
       auto res = std::set<larcv::Range<T> >::emplace(start,end);
       if(res.second) return 0;
       auto& iter = res.first;
       auto tmp_a = Range<T>(start,end);
       size_t ctr=0;
       while(iter != this->end()) {
     tmp_a += (*iter);
     this->erase(iter);
     iter = this->find(tmp_a);
     ++ctr;
       }
       this->insert(tmp_a);
       return ctr;
     }
End()
template<class T > const T& larcv::UniqueRangeSet< T >::End () const inline
Very first "start" of all contained range.
Definition at line 70 of file UniqueRangeSet.h.
     {
       if(!(this->size())) throw std::runtime_error("Nothing in the set!");
       return (*(this->rbegin()))._window.second;
     }
Exclusive()
template<class T > UniqueRangeSet<T> larcv::UniqueRangeSet< T >::Exclusive (const T start, const T end) const inline
Definition at line 81 of file UniqueRangeSet.h.
     {
       UniqueRangeSet<T> res;
       auto start_iter = std::lower_bound(this->begin(),this->end(),start);
       auto end_iter   = std::lower_bound(this->begin(),this->end(),end);
       // Anything to add to the head?
       if(start < (*start_iter)._window.first) res.emplace(start,(*start_iter)._window.first);
       auto iter = start_iter;
       T  tmp_end=end;
       while(iter != this->end()) {
     if(iter != start_iter)
       res.emplace(tmp_end,(*iter)._window.first);
     tmp_end   = (*iter)._window.second;
     if(iter == end_iter) break;
     ++iter;
       }
       // Anything to add to the tail?
       if(tmp_end < end)
     res.emplace(tmp_end,end);
       return res;
     }
insert()
template<class T > size_t larcv::UniqueRangeSet< T >::insert (const Range< T > & a) inline
Modified insert that merges overlapping range. Return = # merged range.
Definition at line 128 of file UniqueRangeSet.h.
References larcv::Range< T >::_window, and larcv::UniqueRangeSet< T >::emplace().
Referenced by larcv::UniqueRangeSet< T >::emplace().
     {return emplace(a._window.first,a._window.second);}
operator+()
template<class T > UniqueRangeSet larcv::UniqueRangeSet< T >::operator+ (const UniqueRangeSet< T > & rhs) inline
Definition at line 51 of file UniqueRangeSet.h.
     {
       UniqueRangeSet res((*this));
       res += rhs;
       return res;
     }
operator+=()
template<class T > UniqueRangeSet& larcv::UniqueRangeSet< T >::operator+= (const UniqueRangeSet< T > & rhs) inline
Merge two UniqueRangeSet<T>
Definition at line 46 of file UniqueRangeSet.h.
References larcv::UniqueRangeSet< T >::emplace().
     {
       for(auto const& r : rhs) emplace(r._window.first,r._window.second);
       return (*this);
     }
Start()
template<class T > const T& larcv::UniqueRangeSet< T >::Start () const inline
Very first "start" of all contained range.
Definition at line 63 of file UniqueRangeSet.h.
     {
       if(!(this->size())) throw std::runtime_error("Nothing in the set!");
       return (*(this->begin()))._window.first;
     }
Member Data Documentation
keys
K std::set< K >::keys inherited
STL member.
The documentation for this class was generated from the following files:
Range.h
UniqueRangeSet.h