LArCV: larcv::DataProductFactory Class Reference
larcv::DataProductFactory Class Reference
#include <DataProductFactory.h>
Public Member Functions
DataProductFactory ()
Default ctor, shouldn't be used.
~DataProductFactory ()
Default dtor.
void add_factory (const ProductType_t type, larcv::DataProductFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
EventBase * create (const ProductType_t type, const std::string producer)
Factory creation method (should be called by clients, possibly you!)
void list () const
List registered products.
std::string ROIType2String (const ROIType_t type)
ROIType_t String2ROIType (const std::string &name)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static DataProductFactory & get ()
Static sharable instance getter.
Private Attributes
std::map< larcv::ProductType_t, larcv::DataProductFactoryBase * > _factory_map
Static factory container.
Static Private Attributes
static DataProductFactory * _me = nullptr
Static self.
Detailed Description
Definition at line 51 of file DataProductFactory.h.
Constructor & Destructor Documentation
DataProductFactory()
larcv::DataProductFactory::DataProductFactory () inline
Default ctor, shouldn't be used.
Definition at line 55 of file DataProductFactory.h.
                          : larcv_base("DataProductFactory")
     {}
~DataProductFactory()
larcv::DataProductFactory::~DataProductFactory () inline
Default dtor.
Definition at line 58 of file DataProductFactory.h.
 {_factory_map.clear();}
Member Function Documentation
add_factory()
void larcv::DataProductFactory::add_factory (const ProductType_t type, larcv::DataProductFactoryBase * factory) inline
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 63 of file DataProductFactory.h.
References LARCV_CRITICAL, LARCV_INFO, and larcv::ProductName().
Referenced by larcv::EventChStatusFactory::EventChStatusFactory(), larcv::EventImage2DFactory::EventImage2DFactory(), larcv::EventPGraphFactory::EventPGraphFactory(), larcv::EventPixel2DFactory::EventPixel2DFactory(), larcv::EventROIFactory::EventROIFactory(), and larcv::EventVoxel3DFactory::EventVoxel3DFactory().
     {
       LARCV_INFO() << "Registering a factory " << factory << " of type " << ProductName(type) << std::endl;
       auto iter = _factory_map.find(type);
       if(iter != _factory_map.end()) {
     LARCV_CRITICAL() << "Attempted a duplicate registration of Data product "
              << ProductName(type) << " to a factory!" << std::endl;
     throw larbys();
       }
       _factory_map[type] = factory;
     }
create()
EventBase* larcv::DataProductFactory::create (const ProductType_t type, const std::string producer) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 78 of file DataProductFactory.h.
References LARCV_ERROR, and larcv::ProductName().
Referenced by larcv::IOManager< T >::register_producer().
{
       auto iter = _factory_map.find(type);
       if(iter == _factory_map.end() || !((*iter).second)) {
     LARCV_ERROR() << "Found no registered class " << ProductName(type) << std::endl;
     return nullptr;
       }
       auto ptr = (*iter).second->create();
       ptr->_producer = producer;
       return ptr;
     }
get()
static DataProductFactory& larcv::DataProductFactory::get () inline static
Static sharable instance getter.
Definition at line 60 of file DataProductFactory.h.
Referenced by larcv::EventChStatusFactory::EventChStatusFactory(), larcv::EventImage2DFactory::EventImage2DFactory(), larcv::EventPGraphFactory::EventPGraphFactory(), larcv::EventPixel2DFactory::EventPixel2DFactory(), larcv::EventROIFactory::EventROIFactory(), larcv::EventVoxel3DFactory::EventVoxel3DFactory(), and larcv::IOManager< T >::register_producer().
     { if(!_me) _me = new DataProductFactory; return *_me; }
list()
void larcv::DataProductFactory::list () const inline
List registered products.
Definition at line 90 of file DataProductFactory.h.
References LARCV_NORMAL, and larcv::ProductName().
                       {
       std::stringstream ss;
       ss << "    Listing registered products:" << std::endl;
       for(auto const& type_factory : _factory_map) {
     ss << "    Type: " << type_factory.first
        << " ... Name: " << ProductName(type_factory.first)
        << " ... Factory @ " << type_factory.second
        << std::endl;
       }
       ss << std::endl;
       LARCV_NORMAL() << ss.str() << std::endl;
     }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
ROIType2String()
std::string larcv::DataProductFactory::ROIType2String (const ROIType_t type) inline
Definition at line 103 of file DataProductFactory.h.
References larcv::ROIType2String().
     { return ::larcv::ROIType2String(type); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
String2ROIType()
ROIType_t larcv::DataProductFactory::String2ROIType (const std::string & name) inline
Definition at line 106 of file DataProductFactory.h.
References larcv::String2ROIType().
     { return ::larcv::String2ROIType(name); }
Member Data Documentation
_factory_map
std::map<larcv::ProductType_t,larcv::DataProductFactoryBase*> larcv::DataProductFactory::_factory_map private
Static factory container.
Definition at line 111 of file DataProductFactory.h.
_me
larcv::DataProductFactory * larcv::DataProductFactory::_me = nullptr static private
Static self.
Definition at line 113 of file DataProductFactory.h.
The documentation for this class was generated from the following files:
DataProductFactory.h
DataProductFactory.cxx