LArCV: larcv::GenDeadChannelMap Class Reference
larcv::GenDeadChannelMap Class Reference
#include <GenDeadChannelMap.h>
Public Member Functions
GenDeadChannelMap (const std::string name="GenDeadChannelMap")
Default constructor.
~GenDeadChannelMap ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _img_producer
std::vector< std::vector< float > > _img_v
std::vector< ImageMeta > _meta_v
Detailed Description
Definition at line 29 of file GenDeadChannelMap.h.
Constructor & Destructor Documentation
GenDeadChannelMap()
larcv::GenDeadChannelMap::GenDeadChannelMap (const std::string name = "GenDeadChannelMap")
Default constructor.
Definition at line 10 of file GenDeadChannelMap.cxx.
Referenced by larcv::GenDeadChannelMapProcessFactory::create().
     : ProcessBase(name)
   {}
~GenDeadChannelMap()
larcv::GenDeadChannelMap::~GenDeadChannelMap () inline
Default destructor.
Definition at line 37 of file GenDeadChannelMap.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::GenDeadChannelMap::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file GenDeadChannelMap.cxx.
References _img_producer, and larcv::PSet::get().
Referenced by ~GenDeadChannelMap().
   {
     _img_producer = cfg.get<std::string>("ImageProducer");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::GenDeadChannelMap::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 52 of file GenDeadChannelMap.cxx.
References _img_v, _meta_v, larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::kProductImage2D, larcv::IOManager< T >::kWRITE, larcv::Image2D::move(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), larcv::IOManager< T >::set_out_file(), and larcv::larcv_base::set_verbosity().
Referenced by ~GenDeadChannelMap().
   {
     IOManager out_iom(IOManager::kWRITE);
     out_iom.set_verbosity((larcv::msg::Level_t)0);
     out_iom.set_out_file("test.root");
     out_iom.initialize();
     auto ev_img2d = (EventImage2D*)out_iom.get_data(kProductImage2D,"test");
     for(size_t plane=0; plane<3; ++plane) {
       Image2D img(_meta_v[plane]);
       img.move(std::move(_img_v[plane]));
       ev_img2d->Emplace(std::move(img));
     }
     out_iom.set_id(1,1,1);
     out_iom.save_entry();
     out_iom.finalize();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::GenDeadChannelMap::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 19 of file GenDeadChannelMap.cxx.
Referenced by ~GenDeadChannelMap().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::GenDeadChannelMap::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 22 of file GenDeadChannelMap.cxx.
References _img_producer, _img_v, _meta_v, larcv::IOManager< T >::get_data(), and larcv::kProductImage2D.
Referenced by ~GenDeadChannelMap().
   {
     auto ev_img2d = (EventImage2D*) mgr.get_data(kProductImage2D,_img_producer);
     if (_img_v.empty()) {
       _img_v.resize(3);
       _meta_v.resize(3);
       auto img2d_v = ev_img2d->Image2DArray();
       for(size_t plane=0; plane<3; ++plane) {
     img2d_v[plane].binary_threshold(1.0,0.0,1.0);
     _img_v[plane]  = std::move(img2d_v[plane].move());
     _meta_v[plane] = ev_img2d->Image2DArray()[plane].meta();
       }
       return true;
     }
     for(size_t plane=0; plane<3; ++plane) {
       const auto& img = ev_img2d->Image2DArray()[plane].as_vector();
       for(size_t pid=0; pid < _img_v[plane].size(); ++pid) {
     if (img[pid]>=1.0) _img_v[plane][pid] += 1.0;
       }
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_img_producer
std::string larcv::GenDeadChannelMap::_img_producer private
Definition at line 49 of file GenDeadChannelMap.h.
Referenced by configure(), and process().
_img_v
std::vector<std::vector<float> > larcv::GenDeadChannelMap::_img_v private
Definition at line 50 of file GenDeadChannelMap.h.
Referenced by finalize(), and process().
_meta_v
std::vector<ImageMeta> larcv::GenDeadChannelMap::_meta_v private
Definition at line 51 of file GenDeadChannelMap.h.
Referenced by finalize(), and process().
The documentation for this class was generated from the following files:
GenDeadChannelMap.h
GenDeadChannelMap.cxx