LArCV: larcv::RandomCropper Class Reference
larcv::RandomCropper Class Reference
User defined class RandomCropper ...
#include <RandomCropper.h>
Public Member Functions
RandomCropper (const std::string name="RandomCropper")
Default constructor.
~RandomCropper ()
Default destructor.
void configure (const PSet &cfg)
void set_crop_region (const size_t rows, const size_t cols)
size_t rows () const
size_t cols () const
const std::vector< float > crop (const larcv::Image2D &image)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
size_t _target_rows
size_t _target_cols
size_t _crop_rows
size_t _crop_cols
size_t _col_offset
size_t _row_offset
bool _randomize_crop
std::vector< float > _cropped_image
Detailed Description
User defined class RandomCropper ...
these comments are used to generate doxygen documentation!
Definition at line 28 of file RandomCropper.h.
Constructor & Destructor Documentation
RandomCropper()
larcv::RandomCropper::RandomCropper (const std::string name = "RandomCropper")
Default constructor.
Definition at line 9 of file RandomCropper.cxx.
References _crop_cols, _crop_rows, and _randomize_crop.
     : larcv_base(name)
     , _target_rows(0)
     , _target_cols(0)
     , _crop_rows(0)
     , _crop_cols(0)
     , _randomize_crop(false)
   {
     _crop_cols = _crop_rows = 0;
     _randomize_crop = false;
   }
~RandomCropper()
larcv::RandomCropper::~RandomCropper () inline
Default destructor.
Definition at line 36 of file RandomCropper.h.
References cols(), configure(), rows(), and set_crop_region().
 {}
Member Function Documentation
cols()
size_t larcv::RandomCropper::cols () const inline
Definition at line 44 of file RandomCropper.h.
References _crop_cols, and crop().
Referenced by larcv::SegFiller::compute_image_size(), larcv::SimpleFiller::compute_image_size(), larcv::MultiClassFiller::compute_image_size(), larcv::SegFiller::fill_entry_data(), set_crop_region(), and ~RandomCropper().
 { return _crop_cols; }
configure()
void larcv::RandomCropper::configure (const PSet & cfg)
Definition at line 21 of file RandomCropper.cxx.
References _crop_cols, _crop_rows, _randomize_crop, and larcv::PSet::get().
Referenced by larcv::MultiClassFiller::child_configure(), larcv::SimpleFiller::child_configure(), larcv::SegFiller::child_configure(), and ~RandomCropper().
   {
     _randomize_crop = cfg.get<bool>("RandomizeCrop",false);
     _crop_cols      = cfg.get<int>("CroppedCols");
     _crop_rows      = cfg.get<int>("CroppedRows");
   }
crop()
const std::vector< float > larcv::RandomCropper::crop (const larcv::Image2D & image)
Definition at line 57 of file RandomCropper.cxx.
References _col_offset, _crop_cols, _crop_rows, _cropped_image, _row_offset, _target_cols, _target_rows, larcv::Image2D::as_vector(), larcv::ImageMeta::cols(), LARCV_CRITICAL, larcv::Image2D::meta(), and larcv::ImageMeta::rows().
Referenced by cols(), larcv::SimpleFiller::fill_entry_data(), larcv::SegFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
   {
     // Check input image size
     if(image.meta().rows() != _target_rows ||
        image.meta().cols() != _target_cols) {
       LARCV_CRITICAL() << "Image dimension (" << image.meta().rows()
       << "," << image.meta().cols() << ") does not match with what is specified ("
       << _target_rows << "," << _target_cols << ")!" << std::endl;
       throw larbys();
     }
     // Set _cropped_image size
     size_t cropped_rows = std::min(_target_rows, _crop_rows);
     size_t cropped_cols = std::min(_target_cols, _crop_cols);
     _cropped_image.resize( cropped_rows * cropped_cols );
     auto const& data_v = image.as_vector();
     for(size_t col = 0; col < cropped_cols; ++col) {
       for(size_t row = 0; row < cropped_rows; ++row) {
         _cropped_image[cropped_rows * col + row] = data_v[(col + _col_offset) * _target_rows + row + _row_offset];
       }
     }
     return _cropped_image;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
rows()
size_t larcv::RandomCropper::rows () const inline
Definition at line 42 of file RandomCropper.h.
References _crop_rows.
Referenced by larcv::SegFiller::compute_image_size(), larcv::SimpleFiller::compute_image_size(), larcv::MultiClassFiller::compute_image_size(), larcv::SegFiller::fill_entry_data(), set_crop_region(), and ~RandomCropper().
 { return _crop_rows; }
set_crop_region()
void larcv::RandomCropper::set_crop_region (const size_t rows, const size_t cols)
Definition at line 28 of file RandomCropper.cxx.
References _col_offset, _crop_cols, _crop_rows, _randomize_crop, _row_offset, _target_cols, _target_rows, cols(), and rows().
Referenced by larcv::SegFiller::fill_entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), and ~RandomCropper().
   {
     _target_rows = rows;
     _target_cols = cols;
     _col_offset = _row_offset = 0;
     int coldiff = std::max(0,(int)_target_cols - (int)_crop_cols);
     int rowdiff = std::max(0,(int)_target_rows - (int)_crop_rows);
     if ( _randomize_crop ) {
       std::random_device rd;
       std::mt19937 gen(rd());
       if ( coldiff>0 ) {
         std::uniform_int_distribution<> irand_col(0,coldiff);
         _col_offset = irand_col(gen);
       }
       if ( rowdiff>0 ) {
         std::uniform_int_distribution<> irand_row(0,rowdiff);
         _row_offset = irand_row(gen);
       }
     }
     else {
       if ( coldiff>0 ) _col_offset = (int)coldiff/2;
       if ( rowdiff>0 ) _row_offset = (int)rowdiff/2;
     }
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_col_offset
size_t larcv::RandomCropper::_col_offset private
Definition at line 54 of file RandomCropper.h.
Referenced by crop(), and set_crop_region().
_crop_cols
size_t larcv::RandomCropper::_crop_cols private
Definition at line 53 of file RandomCropper.h.
Referenced by cols(), configure(), crop(), RandomCropper(), and set_crop_region().
_crop_rows
size_t larcv::RandomCropper::_crop_rows private
Definition at line 52 of file RandomCropper.h.
Referenced by configure(), crop(), RandomCropper(), rows(), and set_crop_region().
_cropped_image
std::vector<float> larcv::RandomCropper::_cropped_image private
Definition at line 57 of file RandomCropper.h.
Referenced by crop().
_randomize_crop
bool larcv::RandomCropper::_randomize_crop private
Definition at line 56 of file RandomCropper.h.
Referenced by configure(), RandomCropper(), and set_crop_region().
_row_offset
size_t larcv::RandomCropper::_row_offset private
Definition at line 55 of file RandomCropper.h.
Referenced by crop(), and set_crop_region().
_target_cols
size_t larcv::RandomCropper::_target_cols private
Definition at line 51 of file RandomCropper.h.
Referenced by crop(), and set_crop_region().
_target_rows
size_t larcv::RandomCropper::_target_rows private
Definition at line 50 of file RandomCropper.h.
Referenced by crop(), and set_crop_region().
The documentation for this class was generated from the following files:
RandomCropper.h
RandomCropper.cxx