LArCV: larcv::LArbysImageMC Class Reference
larcv::LArbysImageMC Class Reference
#include <LArbysImageMC.h>
Classes
struct aparticle
struct entry_info
Public Member Functions
LArbysImageMC (const std::string name="LArbysImageMC")
Default constructor.
~LArbysImageMC ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void Clear ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
std::vector< double > _vtx_2d_w_v
2D Vertex Info
std::vector< double > _vtx_2d_t_v
Protected Attributes
std::string _producer_roi
std::string _producer_image2d
bool _neutrino_present
TTree * _mc_tree
int _run
Event ID.
int _subrun
int _event
int _entry
std::string _rse_producer
int _parent_pdg
Primary Particle Info.
double _energy_deposit
double _energy_init
double _parent_x
double _parent_y
double _parent_z
double _parent_t
double _parent_px
double _parent_py
double _parent_pz
int _current_type
int _interaction_type
float _length_2d
int _nprimary
int _ntotal
int _nproton
int _nlepton
int _nshower
int _nmeson
int _nneutron
int _hi_lep_pdg
double _hi_lep_e
double _dep_sum_lepton
double _ke_sum_lepton
double _dep_sum_proton
double _ke_sum_proton
double _dep_sum_meson
double _ke_sum_meson
double _dep_sum_shower
double _ke_sum_shower
double _dep_sum_neutron
double _ke_sum_neutron
geo2d::Vector< float > _start
geo2d::Vector< float > _dir
std::vector< int > _daughter_pdg_v
std::vector< int > _daughter_trackid_v
std::vector< int > _daughter_parenttrackid_v
std::vector< double > _daughter_energyinit_v
std::vector< double > _daughter_energydep_v
std::vector< std::vector< double > > _daughter_length_vv
std::vector< std::vector< double > > _daughter_2dstartx_vv
std::vector< std::vector< double > > _daughter_2dstarty_vv
std::vector< std::vector< double > > _daughter_2dendx_vv
std::vector< std::vector< double > > _daughter_2dendy_vv
std::vector< std::vector< double > > _daughter_2dcosangle_vv
std::vector< double > _daughterPx_v
std::vector< double > _daughterPy_v
std::vector< double > _daughterPz_v
std::vector< double > _daughterX_v
std::vector< double > _daughterY_v
std::vector< double > _daughterZ_v
std::vector< double > _daughter_length3d_v
double _true_proton_end_pt_x
double _true_proton_end_pt_y
double _true_proton_end_pt_z
double _proton_1st_pt_x
double _proton_1st_pt_y
double _proton_1st_pt_z
double _proton_last_pt_x
double _proton_last_pt_y
double _proton_last_pt_z
double _true_lepton_end_pt_x
double _true_lepton_end_pt_y
double _true_lepton_end_pt_z
double _lepton_1st_pt_x
double _lepton_1st_pt_y
double _lepton_1st_pt_z
double _lepton_last_pt_x
double _lepton_last_pt_y
double _lepton_last_pt_z
std::vector< larcv::Image2D > _image_v
LARCV Image2D data.
ImageMeta _meta
float _min_nu_dep_e
Filtering.
float _max_nu_dep_e
float _min_nu_init_e
float _max_nu_init_e
int _min_n_proton
int _min_n_neutron
int _min_n_lepton
int _min_n_meson
int _min_n_shower
float _min_proton_init_e
float _min_proton_dep
float _max_proton_dep
float _min_lepton_init_e
bool _check_vis
bool _do_not_reco
bool _selected
bool _select_signal
bool _select_background
entry_info _entry_info
bool _is_signal
Detailed Description
Definition at line 22 of file LArbysImageMC.h.
Constructor & Destructor Documentation
LArbysImageMC()
larcv::LArbysImageMC::LArbysImageMC (const std::string name = "LArbysImageMC")
Default constructor.
Definition at line 14 of file LArbysImageMC.cxx.
Referenced by larcv::LArbysImageMCProcessFactory::create().
     : ProcessBase(name), _mc_tree(nullptr)
   {}
~LArbysImageMC()
larcv::LArbysImageMC::~LArbysImageMC () inline
Default destructor.
Definition at line 30 of file LArbysImageMC.h.
References Clear(), configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
Clear()
void larcv::LArbysImageMC::Clear ()
Definition at line 461 of file LArbysImageMC.cxx.
References _daughter_2dcosangle_vv, _daughter_2dendx_vv, _daughter_2dendy_vv, _daughter_2dstartx_vv, _daughter_2dstarty_vv, _daughter_energydep_v, _daughter_energyinit_v, _daughter_length3d_v, _daughter_length_vv, _daughter_parenttrackid_v, _daughter_pdg_v, _daughter_trackid_v, _daughterPx_v, _daughterPy_v, _daughterPz_v, _daughterX_v, _daughterY_v, _daughterZ_v, _image_v, _vtx_2d_t_v, and _vtx_2d_w_v.
Referenced by process(), and ~LArbysImageMC().
{
     _vtx_2d_w_v.clear();
     _vtx_2d_t_v.clear();
     _vtx_2d_w_v.resize(3);
     _vtx_2d_t_v.resize(3);
     _image_v.clear();
     _image_v.resize(3);
     _daughter_pdg_v.clear();
     _daughter_trackid_v.clear();
     _daughter_parenttrackid_v.clear();
     _daughter_energyinit_v.clear();
     _daughter_energydep_v.clear();
     _daughter_length_vv.clear();
     _daughter_length3d_v.clear();
     _daughter_2dstartx_vv.clear();
     _daughter_2dstarty_vv.clear();
     _daughter_2dendx_vv.clear();
     _daughter_2dendy_vv.clear();
     _daughterPx_v.clear();
     _daughterPy_v.clear();
     _daughterPz_v.clear();
     _daughterX_v.clear();
     _daughterY_v.clear();
     _daughterZ_v.clear();
     _daughter_2dcosangle_vv.clear();
   }
configure()
void larcv::LArbysImageMC::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 18 of file LArbysImageMC.cxx.
References _neutrino_present, _producer_image2d, _producer_roi, _rse_producer, and larcv::PSet::get().
Referenced by ~LArbysImageMC().
   {
     _rse_producer       = cfg.get<std::string>("RSEProducer");
     _producer_roi       = cfg.get<std::string>("MCProducer");
     _producer_image2d   = cfg.get<std::string>("Image2DProducer");
     _neutrino_present   = cfg.get<bool>("NeutrinoPresent",true);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImageMC::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 456 of file LArbysImageMC.cxx.
References _mc_tree.
Referenced by ~LArbysImageMC().
   {
     _mc_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImageMC::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 26 of file LArbysImageMC.cxx.
References _current_type, _daughter_2dcosangle_vv, _daughter_2dendx_vv, _daughter_2dendy_vv, _daughter_2dstartx_vv, _daughter_2dstarty_vv, _daughter_energydep_v, _daughter_energyinit_v, _daughter_length3d_v, _daughter_length_vv, _daughter_parenttrackid_v, _daughter_pdg_v, _daughter_trackid_v, _daughterPx_v, _daughterPy_v, _daughterPz_v, _daughterX_v, _daughterY_v, _daughterZ_v, _dep_sum_lepton, _dep_sum_meson, _dep_sum_neutron, _dep_sum_proton, _dep_sum_shower, _energy_deposit, _energy_init, _entry, _event, _hi_lep_pdg, _is_signal, _ke_sum_lepton, _ke_sum_meson, _ke_sum_neutron, _ke_sum_proton, _ke_sum_shower, _lepton_1st_pt_x, _lepton_1st_pt_y, _lepton_1st_pt_z, _lepton_last_pt_x, _lepton_last_pt_y, _lepton_last_pt_z, _mc_tree, _nlepton, _nmeson, _nneutron, _nprimary, _nproton, _nshower, _ntotal, _parent_pdg, _parent_px, _parent_py, _parent_pz, _parent_t, _parent_x, _parent_y, _parent_z, _proton_1st_pt_x, _proton_1st_pt_y, _proton_1st_pt_z, _proton_last_pt_x, _proton_last_pt_y, _proton_last_pt_z, _run, _subrun, _true_lepton_end_pt_x, _true_lepton_end_pt_y, _true_lepton_end_pt_z, _true_proton_end_pt_x, _true_proton_end_pt_y, _true_proton_end_pt_z, _vtx_2d_t_v, and _vtx_2d_w_v.
Referenced by ~LArbysImageMC().
   {
     _mc_tree = new TTree("MCTree","MC infomation");
     _mc_tree->Branch("run",&_run,"run/I");
     _mc_tree->Branch("subrun",&_subrun,"subrun/I");
     _mc_tree->Branch("event",&_event,"event/I");
     _mc_tree->Branch("entry"  ,&_entry  , "entry/I");
     _mc_tree->Branch("parentPDG",&_parent_pdg,"parentPDG/I");
     _mc_tree->Branch("signal",&_is_signal,"_is_signal/O");
     _mc_tree->Branch("energyDeposit",&_energy_deposit,"energyDeposit/D");
     _mc_tree->Branch("energyInit",&_energy_init,"energyInit/D");
     _mc_tree->Branch("parentX",&_parent_x,"parentX/D");
     _mc_tree->Branch("parentY",&_parent_y,"parentY/D");
     _mc_tree->Branch("parentZ",&_parent_z,"parentZ/D");
     _mc_tree->Branch("parentT",&_parent_t,"parentT/D");
     _mc_tree->Branch("parentPx",&_parent_px,"parentPx/D");
     _mc_tree->Branch("parentPy",&_parent_py,"parentPy/D");
     _mc_tree->Branch("parentPz",&_parent_pz,"parentpz/D");
     _mc_tree->Branch("currentType",&_current_type,"currentType/I");
     _mc_tree->Branch("interactionType",&_current_type,"InteractionType/I");
     _mc_tree->Branch("vtx2d_w",&_vtx_2d_w_v);
     _mc_tree->Branch("vtx2d_t",&_vtx_2d_t_v);
     _mc_tree->Branch("nprimary", &_nprimary,"nprimary/I");
     _mc_tree->Branch("ntotal", &_ntotal,"ntotal/I");
     _mc_tree->Branch("nproton", &_nproton,"nproton/I");
     _mc_tree->Branch("nlepton", &_nlepton,"nlepton/I");
     _mc_tree->Branch("nmeson", &_nmeson,"nmeson/I");
     _mc_tree->Branch("nshower", &_nshower,"nshower/I");
     _mc_tree->Branch("nneutron", &_nneutron,"nneutron/I");
     _mc_tree->Branch("hi_lep_pdg",&_hi_lep_pdg,"hi_lep_pdg/I");
     _mc_tree->Branch("dep_sum_lepton",&_dep_sum_lepton,"dep_sum_lepton/D");
     _mc_tree->Branch("ke_sum_lepton",&_ke_sum_lepton,"ke_sum_lepton/D");
     _mc_tree->Branch("dep_sum_proton",&_dep_sum_proton,"dep_sum_proton/D");
     _mc_tree->Branch("ke_sum_proton",&_ke_sum_proton,"ke_sum_proton/D");
     _mc_tree->Branch("dep_sum_meson",&_dep_sum_meson,"dep_sum_meson/D");
     _mc_tree->Branch("ke_sum_meson",&_ke_sum_meson,"ke_sum_meson/D");
     _mc_tree->Branch("dep_sum_shower",&_dep_sum_shower,"dep_sum_shower/D");
     _mc_tree->Branch("ke_sum_shower",&_ke_sum_shower,"ke_sum_shower/D");
     _mc_tree->Branch("dep_sum_neutron",&_dep_sum_neutron,"dep_sum_neutron/D");
     _mc_tree->Branch("ke_sum_neutron",&_ke_sum_neutron,"ke_sum_neutron/D");
     _mc_tree->Branch("daughterPx_v", &_daughterPx_v);
     _mc_tree->Branch("daughterPy_v", &_daughterPy_v);
     _mc_tree->Branch("daughterPz_v", &_daughterPz_v);
     _mc_tree->Branch("daughterX_v", &_daughterX_v);
     _mc_tree->Branch("daughterY_v", &_daughterY_v);
     _mc_tree->Branch("daughterZ_v", &_daughterZ_v);
     _mc_tree->Branch("daughterPdg_v"           , &_daughter_pdg_v);
     _mc_tree->Branch("daughterTrackid_v"       , &_daughter_trackid_v);
     _mc_tree->Branch("daughterParentTrackid_v" , &_daughter_parenttrackid_v);
     _mc_tree->Branch("daughterLength3d_v"      , &_daughter_length3d_v);
     _mc_tree->Branch("daughterLength_vv"       , &_daughter_length_vv);
     _mc_tree->Branch("daughterEnergyInit_v"    , &_daughter_energyinit_v);
     _mc_tree->Branch("daughterEnergyDep_v"     , &_daughter_energydep_v);
     _mc_tree->Branch("daughter2DStartX_vv"     , &_daughter_2dstartx_vv);
     _mc_tree->Branch("daughter2DStartY_vv"     , &_daughter_2dstarty_vv);
     _mc_tree->Branch("daughter2DEndX_vv"       , &_daughter_2dendx_vv);
     _mc_tree->Branch("daughter2DEndY_vv"       , &_daughter_2dendy_vv);
     _mc_tree->Branch("daughter2DCosAngle_vv"   , &_daughter_2dcosangle_vv);
     _mc_tree->Branch("true_proton_end_pt_x", &_true_proton_end_pt_x);
     _mc_tree->Branch("true_proton_end_pt_y", &_true_proton_end_pt_y);
     _mc_tree->Branch("true_proton_end_pt_z", &_true_proton_end_pt_z);
     _mc_tree->Branch("proton_1st_pt_x", &_proton_1st_pt_x);
     _mc_tree->Branch("proton_1st_pt_y", &_proton_1st_pt_y);
     _mc_tree->Branch("proton_1st_pt_z", &_proton_1st_pt_z);
     _mc_tree->Branch("proton_last_pt_x", &_proton_last_pt_x);
     _mc_tree->Branch("proton_last_pt_y", &_proton_last_pt_y);
     _mc_tree->Branch("proton_last_pt_z", &_proton_last_pt_z);
     _mc_tree->Branch("true_lepton_end_pt_x", &_true_lepton_end_pt_x);
     _mc_tree->Branch("true_lepton_end_pt_y", &_true_lepton_end_pt_y);
     _mc_tree->Branch("true_lepton_end_pt_z", &_true_lepton_end_pt_z);
     _mc_tree->Branch("lepton_1st_pt_x", &_lepton_1st_pt_x);
     _mc_tree->Branch("lepton_1st_pt_y", &_lepton_1st_pt_y);
     _mc_tree->Branch("lepton_1st_pt_z", &_lepton_1st_pt_z);
     _mc_tree->Branch("lepton_last_pt_x", &_lepton_last_pt_x);
     _mc_tree->Branch("lepton_last_pt_y", &_lepton_last_pt_y);
     _mc_tree->Branch("lepton_last_pt_z", &_lepton_last_pt_z);
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::LArbysImageMC::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 129 of file LArbysImageMC.cxx.
References _current_type, _daughter_2dcosangle_vv, _daughter_2dendx_vv, _daughter_2dendy_vv, _daughter_2dstartx_vv, _daughter_2dstarty_vv, _daughter_energydep_v, _daughter_energyinit_v, _daughter_length3d_v, _daughter_length_vv, _daughter_parenttrackid_v, _daughter_pdg_v, _daughter_trackid_v, _daughterPx_v, _daughterPy_v, _daughterPz_v, _daughterX_v, _daughterY_v, _daughterZ_v, _dep_sum_lepton, _dep_sum_meson, _dep_sum_neutron, _dep_sum_proton, _dep_sum_shower, _energy_deposit, _energy_init, _entry, _entry_info, _event, _hi_lep_e, _hi_lep_pdg, _interaction_type, _ke_sum_lepton, _ke_sum_meson, _ke_sum_neutron, _ke_sum_proton, _ke_sum_shower, _lepton_1st_pt_x, _lepton_1st_pt_y, _lepton_1st_pt_z, _lepton_last_pt_x, _lepton_last_pt_y, _lepton_last_pt_z, _mc_tree, _neutrino_present, _nlepton, _nmeson, _nneutron, _nprimary, _nproton, _nshower, _ntotal, _parent_pdg, _parent_px, _parent_py, _parent_pz, _parent_t, _parent_x, _parent_y, _parent_z, _producer_image2d, _producer_roi, _proton_1st_pt_x, _proton_1st_pt_y, _proton_1st_pt_z, _proton_last_pt_x, _proton_last_pt_y, _proton_last_pt_z, _rse_producer, _run, _subrun, _true_lepton_end_pt_x, _true_lepton_end_pt_y, _true_lepton_end_pt_z, _true_proton_end_pt_x, _true_proton_end_pt_y, _true_proton_end_pt_z, _vtx_2d_t_v, _vtx_2d_w_v, Clear(), larcv::IOManager< T >::current_entry(), larcv::LArbysImageMC::aparticle::depeng, larcv::LArbysImageMC::entry_info::event, larcv::Get2DRoi(), larcv::IOManager< T >::get_data(), larcv::Intersection(), larcv::kProductImage2D, larcv::kProductROI, LARCV_DEBUG, larcv::LArbysImageMC::aparticle::parenttrackid, larcv::LArbysImageMC::aparticle::primary, larcv::Project3D(), larcv::LArbysImageMC::entry_info::run, larcv::LArbysImageMC::entry_info::subrun, and larcv::LArbysImageMC::aparticle::trackid.
Referenced by ~LArbysImageMC().
   {
     Clear();
     auto rse_prod = (EventImage2D*) mgr.get_data(kProductImage2D,_rse_producer);
     _run    = rse_prod->run();
     _subrun = rse_prod->subrun();
     _event  = rse_prod->event();
     _entry  = mgr.current_entry();
     if (_producer_roi.empty()) {
       _mc_tree->Fill();
       return true;
     }
     const auto ev_roi     = (larcv::EventROI*)     mgr.get_data(kProductROI,_producer_roi);
     if (_producer_image2d.empty()) throw larbys("Empty image2d producer specified");
     const auto ev_image2d = (larcv::EventImage2D*) mgr.get_data(kProductImage2D,_producer_image2d);
     _entry_info.run    = _run;
     _entry_info.subrun = _subrun;
     _entry_info.event  = _event;
     // If we've got a neutrino, sample that
     if(_neutrino_present){
       auto roi = (*ev_roi).at(0);
       _parent_pdg       = roi.PdgCode();
       _energy_deposit   = roi.EnergyDeposit();
       _energy_init      = roi.EnergyInit();
       _parent_x         = roi.X();
       _parent_y         = roi.Y();
       _parent_z         = roi.Z();
       _parent_t         = roi.T();
       _parent_px        = roi.Px();
       _parent_py        = roi.Py();
       _parent_pz        = roi.Pz();
       _current_type     = roi.NuCurrentType();
       _interaction_type = roi.NuInteractionType();
       // Get 2D projections from 3D
       for (int plane = 0 ; plane<3;++plane){
         const auto& img  = ev_image2d->Image2DArray()[plane];
         const auto& meta = img.meta();
         double x_pixel, y_pixel;
         x_pixel=y_pixel=0;
         Project3D(meta,_parent_x,_parent_y,_parent_z,_parent_t,plane,x_pixel,y_pixel);
         _vtx_2d_w_v[plane] = x_pixel;
         _vtx_2d_t_v[plane] = y_pixel;
       }
     }
     // for each ROI not nu, lets get the 3D line in direction of particle trajectory.
     // then project onto plane, and find the intersection with the edge of the particle
     // ROI box, I think this won't be such a bad proxy for the MC particle length and angle.
     _nprimary = 0;
     _ntotal   = 0;
     _nproton  = 0;
     _nneutron = 0;
     _nlepton  = 0;
     _nmeson   = 0;
     _nshower  = 0;
     _hi_lep_pdg      = -1;
     _hi_lep_e        = 0;
     _dep_sum_lepton  = 0;
     _ke_sum_lepton   = 0;
     _dep_sum_proton  = 0;
     _ke_sum_proton   = 0;
     _dep_sum_meson   = 0;
     _ke_sum_meson    = 0;
     _dep_sum_shower  = 0;
     _ke_sum_shower   = 0;
     _dep_sum_neutron = 0;
     _ke_sum_neutron  = 0;
     bool first=_neutrino_present;
     std::vector<aparticle> proton_v;
     proton_v.clear();
     if(!ev_roi) throw larbys("Bad ROI producer specified");
     for(const auto& roi : ev_roi->ROIArray()) {
       if (first){
         first=false;
         continue;
       }
       LARCV_DEBUG() << "This particle is PDG code " << roi.ParentPdgCode() << std::endl;
       // Get a unit vector for this pdg in 3 coordinates
       auto px = roi.Px();
       auto py = roi.Py();
       auto pz = roi.Pz();
       auto lenp = sqrt(px*px+py*py+pz*pz);
       px /= lenp;
       py /= lenp;
       pz /= lenp;
       // The Original location
       auto x0 = roi.X();
       auto y0 = roi.Y();
       auto z0 = roi.Z();
       auto t0 = roi.T();
       // Here is another point in the direction of p, ignore units...
       // Pxyz are info from genie (meaning that it won't be identical to PCA assumption).
       auto end_pt = roi.EndPosition();
       auto first_step = roi.FirstStep();
       auto last_step = roi.LastStep();
       auto x1 = x0 + px;
       auto y1 = y0 + py;
       auto z1 = z0 + pz;
       auto t1 = t0;
       _daughter_length_vv.resize(3);
       _daughter_2dstartx_vv.resize(3);
       _daughter_2dstarty_vv.resize(3);
       _daughter_2dendx_vv.resize(3);
       _daughter_2dendy_vv.resize(3);
       _daughter_2dcosangle_vv.resize(3);
       //lets project both points
       for(size_t plane=0; plane<3; ++plane) {
     auto& daughter_length_v      = _daughter_length_vv[plane];
     auto& daughter_2dstartx_v    = _daughter_2dstartx_vv[plane];
     auto& daughter_2dstarty_v    = _daughter_2dstarty_vv[plane];
     auto& daughter_2dendx_v      = _daughter_2dendx_vv[plane];
     auto& daughter_2dendy_v      = _daughter_2dendy_vv[plane];
     auto& daughter_2dcosangle_v  = _daughter_2dcosangle_vv[plane];
     const auto& img  = ev_image2d->Image2DArray()[plane];
     const auto& meta = img.meta();
     double x_pixel0, y_pixel0, x_pixel1, y_pixel1;
     x_pixel0 = y_pixel0 = 0;
     x_pixel1 = y_pixel1 = 0;
     Project3D(meta,x0,y0,z0,t0,plane,x_pixel0,y_pixel0);
     Project3D(meta,x1,y1,z1,t1,plane,x_pixel1,y_pixel1);
     // Start and end in 2D
     geo2d::Vector<float> start(x_pixel0,y_pixel0);
     geo2d::Vector<float> end  (x_pixel1,y_pixel1);
     // Get the line of particle
     geo2d::HalfLine<float> hline(start,end-start);
     // Here is the bbox on this plane --> we need to get the single intersection point
     // for the half line and this bbox
     ImageMeta bb;
     try { bb = roi.BB(plane); }
     catch(...) // No intersection occurs?
       { continue; }
     auto roi_on_plane = Get2DRoi(meta,roi.BB(plane));
     // The start point will be inside the 2D ROI
     // we need to intersection point between the edge and this half line, find it
     auto pt_edge = Intersection(hline,roi_on_plane);
     daughter_length_v.push_back(geo2d::length(pt_edge - start));
     daughter_2dstartx_v.push_back(start.x);
     daughter_2dstarty_v.push_back(start.y);
     daughter_2dendx_v.push_back(pt_edge.x);
     daughter_2dendy_v.push_back(pt_edge.y);
     auto dir = pt_edge - start;
     double cosangle = dir.x / sqrt(dir.x*dir.x + dir.y*dir.y);
     daughter_2dcosangle_v.push_back(cosangle);
       }
       _daughterPx_v.push_back(roi.Px());
       _daughterPy_v.push_back(roi.Py());
       _daughterPz_v.push_back(roi.Pz());
       _daughterX_v.push_back(roi.X());
       _daughterY_v.push_back(roi.Y());
       _daughterZ_v.push_back(roi.Z());
       double length3d = sqrt(pow(roi.LastStep().X()-roi.FirstStep().X(),2)+pow(roi.LastStep().Y()-roi.FirstStep().Y(),2)+pow(roi.LastStep().Z()-roi.FirstStep().Z(),2));
       _daughter_length3d_v.push_back(length3d);
       int pdgcode = roi.PdgCode();
       _daughter_pdg_v.push_back((int) roi.PdgCode());
       _daughter_trackid_v.push_back((int) roi.TrackID());
       _daughter_parenttrackid_v.push_back((int) roi.ParentTrackID());
       _daughter_energyinit_v.push_back(roi.EnergyInit());
       _daughter_energydep_v.push_back(roi.EnergyDeposit());
       _ntotal++;
       pdgcode = std::abs(pdgcode);
       // This is proton
       if (pdgcode==2212) {
         //primary protons
         if (roi.TrackID() == roi.ParentTrackID()) {
           _nproton++;
       _ke_sum_proton  += (roi.EnergyInit() - 938.0);
         }
     _true_proton_end_pt_x = end_pt.X();
     _true_proton_end_pt_y = end_pt.Y();
     _true_proton_end_pt_z = end_pt.Z();
     _proton_1st_pt_x = first_step.X();
     _proton_1st_pt_y = first_step.Y();
     _proton_1st_pt_z = first_step.Z();
     _proton_last_pt_x = last_step.X();
     _proton_last_pt_y = last_step.Y();
     _proton_last_pt_z = last_step.Z();
     //capture proton
         aparticle thispro;
         thispro.trackid       = roi.TrackID();
         thispro.parenttrackid = roi.ParentTrackID();
         thispro.depeng        = roi.EnergyDeposit();
         thispro.primary = (roi.TrackID()==roi.ParentTrackID());
         proton_v.emplace_back(std::move(thispro));
       }
       // its not a primary, skip
       if (roi.TrackID() != roi.ParentTrackID()) continue;
       //it is
       _nprimary++;
       //this is neutron
       if (pdgcode==2112) {
         _nneutron++;
         _dep_sum_neutron += roi.EnergyDeposit();
         _ke_sum_neutron  += (roi.EnergyInit() - 939.5);
       }
       // mesons are pion,kaon, ... what else
       if (pdgcode==211 or pdgcode==321) {
         _nmeson++;
         _dep_sum_meson += roi.EnergyDeposit();
         _ke_sum_meson  += roi.EnergyInit();
       }
       // leptons are electron, muon, ... what else
       if (pdgcode==11 or pdgcode==13) {
         _nlepton++;
         _dep_sum_lepton += roi.EnergyDeposit();
         _ke_sum_lepton  += roi.EnergyInit();
         if (roi.EnergyInit() > _hi_lep_e)  {
           _hi_lep_e = roi.EnergyInit();
           _hi_lep_pdg = pdgcode;
         }
     _true_lepton_end_pt_x = end_pt.X();
     _true_lepton_end_pt_y = end_pt.Y();
     _true_lepton_end_pt_z = end_pt.Z();
     _lepton_1st_pt_x = first_step.X();
     _lepton_1st_pt_y = first_step.Y();
     _lepton_1st_pt_z = first_step.Z();
     _lepton_last_pt_x = last_step.X();
     _lepton_last_pt_y = last_step.Y();
     _lepton_last_pt_z = last_step.Z();
       }
       // shower are electron, gamma, pi0
       if (pdgcode==11 or pdgcode==22 or pdgcode==111) {
         _nshower++;
         _dep_sum_shower += roi.EnergyDeposit();
         _ke_sum_shower  += roi.EnergyInit();
       }
     }
     auto nprotons=proton_v.size();
     float max_proton_e = 0;
     std::vector<float> proton_engs;
     proton_engs.reserve(nprotons);
     if (nprotons){
       for (int x=0; x < (int)nprotons; x++){
         const auto& proton1 = proton_v[x];
         max_proton_e  = 0;
         max_proton_e += proton1.depeng;
         auto trackid  = proton1.trackid;
         for (int y=x+1; y < (int)nprotons; y++ ){
           const auto& proton2 = proton_v[y];
           if (proton2.daughterof(proton1)) {
             max_proton_e += proton2.depeng;
           }
         }
         proton_engs.push_back(max_proton_e);
       }
       auto max_proton_e = *(std::max_element(std::begin(proton_engs),
                          std::end(proton_engs)));
       _dep_sum_proton = max_proton_e;
     }
     _mc_tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_check_vis
bool larcv::LArbysImageMC::_check_vis protected
Definition at line 176 of file LArbysImageMC.h.
_current_type
int larcv::LArbysImageMC::_current_type protected
Definition at line 68 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_daughter_2dcosangle_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_2dcosangle_vv protected
Definition at line 114 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_2dendx_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_2dendx_vv protected
Definition at line 112 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_2dendy_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_2dendy_vv protected
Definition at line 113 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_2dstartx_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_2dstartx_vv protected
Definition at line 110 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_2dstarty_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_2dstarty_vv protected
Definition at line 111 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_energydep_v
std::vector<double> larcv::LArbysImageMC::_daughter_energydep_v protected
Definition at line 107 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_energyinit_v
std::vector<double> larcv::LArbysImageMC::_daughter_energyinit_v protected
Definition at line 106 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_length3d_v
std::vector<double> larcv::LArbysImageMC::_daughter_length3d_v protected
Definition at line 122 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_length_vv
std::vector<std::vector<double> > larcv::LArbysImageMC::_daughter_length_vv protected
Definition at line 109 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_parenttrackid_v
std::vector<int> larcv::LArbysImageMC::_daughter_parenttrackid_v protected
Definition at line 104 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_pdg_v
std::vector<int> larcv::LArbysImageMC::_daughter_pdg_v protected
Definition at line 102 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughter_trackid_v
std::vector<int> larcv::LArbysImageMC::_daughter_trackid_v protected
Definition at line 103 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterPx_v
std::vector<double> larcv::LArbysImageMC::_daughterPx_v protected
Definition at line 116 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterPy_v
std::vector<double> larcv::LArbysImageMC::_daughterPy_v protected
Definition at line 117 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterPz_v
std::vector<double> larcv::LArbysImageMC::_daughterPz_v protected
Definition at line 118 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterX_v
std::vector<double> larcv::LArbysImageMC::_daughterX_v protected
Definition at line 119 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterY_v
std::vector<double> larcv::LArbysImageMC::_daughterY_v protected
Definition at line 120 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_daughterZ_v
std::vector<double> larcv::LArbysImageMC::_daughterZ_v protected
Definition at line 121 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_dep_sum_lepton
double larcv::LArbysImageMC::_dep_sum_lepton protected
Definition at line 84 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_dep_sum_meson
double larcv::LArbysImageMC::_dep_sum_meson protected
Definition at line 90 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_dep_sum_neutron
double larcv::LArbysImageMC::_dep_sum_neutron protected
Definition at line 96 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_dep_sum_proton
double larcv::LArbysImageMC::_dep_sum_proton protected
Definition at line 87 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_dep_sum_shower
double larcv::LArbysImageMC::_dep_sum_shower protected
Definition at line 93 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_dir
geo2d::Vector<float> larcv::LArbysImageMC::_dir protected
Definition at line 100 of file LArbysImageMC.h.
_do_not_reco
bool larcv::LArbysImageMC::_do_not_reco protected
Definition at line 178 of file LArbysImageMC.h.
_energy_deposit
double larcv::LArbysImageMC::_energy_deposit protected
Definition at line 57 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_energy_init
double larcv::LArbysImageMC::_energy_init protected
Definition at line 58 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_entry
int larcv::LArbysImageMC::_entry protected
Definition at line 50 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_entry_info
entry_info larcv::LArbysImageMC::_entry_info protected
Definition at line 202 of file LArbysImageMC.h.
Referenced by process().
_event
int larcv::LArbysImageMC::_event protected
Definition at line 49 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_hi_lep_e
double larcv::LArbysImageMC::_hi_lep_e protected
Definition at line 82 of file LArbysImageMC.h.
Referenced by process().
_hi_lep_pdg
int larcv::LArbysImageMC::_hi_lep_pdg protected
Definition at line 81 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_image_v
std::vector<larcv::Image2D> larcv::LArbysImageMC::_image_v protected
LARCV Image2D data.
Definition at line 156 of file LArbysImageMC.h.
Referenced by Clear().
_interaction_type
int larcv::LArbysImageMC::_interaction_type protected
Definition at line 69 of file LArbysImageMC.h.
Referenced by process().
_is_signal
bool larcv::LArbysImageMC::_is_signal protected
Definition at line 203 of file LArbysImageMC.h.
Referenced by initialize().
_ke_sum_lepton
double larcv::LArbysImageMC::_ke_sum_lepton protected
Definition at line 85 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_ke_sum_meson
double larcv::LArbysImageMC::_ke_sum_meson protected
Definition at line 91 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_ke_sum_neutron
double larcv::LArbysImageMC::_ke_sum_neutron protected
Definition at line 97 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_ke_sum_proton
double larcv::LArbysImageMC::_ke_sum_proton protected
Definition at line 88 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_ke_sum_shower
double larcv::LArbysImageMC::_ke_sum_shower protected
Definition at line 94 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_length_2d
float larcv::LArbysImageMC::_length_2d protected
Definition at line 70 of file LArbysImageMC.h.
_lepton_1st_pt_x
double larcv::LArbysImageMC::_lepton_1st_pt_x protected
Definition at line 140 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_lepton_1st_pt_y
double larcv::LArbysImageMC::_lepton_1st_pt_y protected
Definition at line 141 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_lepton_1st_pt_z
double larcv::LArbysImageMC::_lepton_1st_pt_z protected
Definition at line 142 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_lepton_last_pt_x
double larcv::LArbysImageMC::_lepton_last_pt_x protected
Definition at line 144 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_lepton_last_pt_y
double larcv::LArbysImageMC::_lepton_last_pt_y protected
Definition at line 145 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_lepton_last_pt_z
double larcv::LArbysImageMC::_lepton_last_pt_z protected
Definition at line 146 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_max_nu_dep_e
float larcv::LArbysImageMC::_max_nu_dep_e protected
Definition at line 161 of file LArbysImageMC.h.
_max_nu_init_e
float larcv::LArbysImageMC::_max_nu_init_e protected
Definition at line 163 of file LArbysImageMC.h.
_max_proton_dep
float larcv::LArbysImageMC::_max_proton_dep protected
Definition at line 173 of file LArbysImageMC.h.
_mc_tree
TTree* larcv::LArbysImageMC::_mc_tree protected
Definition at line 44 of file LArbysImageMC.h.
Referenced by finalize(), initialize(), and process().
_meta
ImageMeta larcv::LArbysImageMC::_meta protected
Definition at line 157 of file LArbysImageMC.h.
_min_lepton_init_e
float larcv::LArbysImageMC::_min_lepton_init_e protected
Definition at line 174 of file LArbysImageMC.h.
_min_n_lepton
int larcv::LArbysImageMC::_min_n_lepton protected
Definition at line 167 of file LArbysImageMC.h.
_min_n_meson
int larcv::LArbysImageMC::_min_n_meson protected
Definition at line 168 of file LArbysImageMC.h.
_min_n_neutron
int larcv::LArbysImageMC::_min_n_neutron protected
Definition at line 166 of file LArbysImageMC.h.
_min_n_proton
int larcv::LArbysImageMC::_min_n_proton protected
Definition at line 165 of file LArbysImageMC.h.
_min_n_shower
int larcv::LArbysImageMC::_min_n_shower protected
Definition at line 169 of file LArbysImageMC.h.
_min_nu_dep_e
float larcv::LArbysImageMC::_min_nu_dep_e protected
Filtering.
Definition at line 160 of file LArbysImageMC.h.
_min_nu_init_e
float larcv::LArbysImageMC::_min_nu_init_e protected
Definition at line 162 of file LArbysImageMC.h.
_min_proton_dep
float larcv::LArbysImageMC::_min_proton_dep protected
Definition at line 172 of file LArbysImageMC.h.
_min_proton_init_e
float larcv::LArbysImageMC::_min_proton_init_e protected
Definition at line 171 of file LArbysImageMC.h.
_neutrino_present
bool larcv::LArbysImageMC::_neutrino_present protected
Definition at line 42 of file LArbysImageMC.h.
Referenced by configure(), and process().
_nlepton
int larcv::LArbysImageMC::_nlepton protected
Definition at line 76 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_nmeson
int larcv::LArbysImageMC::_nmeson protected
Definition at line 78 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_nneutron
int larcv::LArbysImageMC::_nneutron protected
Definition at line 79 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_nprimary
int larcv::LArbysImageMC::_nprimary protected
Definition at line 72 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_nproton
int larcv::LArbysImageMC::_nproton protected
Definition at line 75 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_nshower
int larcv::LArbysImageMC::_nshower protected
Definition at line 77 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_ntotal
int larcv::LArbysImageMC::_ntotal protected
Definition at line 73 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_pdg
int larcv::LArbysImageMC::_parent_pdg protected
Primary Particle Info.
Definition at line 55 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_px
double larcv::LArbysImageMC::_parent_px protected
Definition at line 64 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_py
double larcv::LArbysImageMC::_parent_py protected
Definition at line 65 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_pz
double larcv::LArbysImageMC::_parent_pz protected
Definition at line 66 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_t
double larcv::LArbysImageMC::_parent_t protected
Definition at line 63 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_x
double larcv::LArbysImageMC::_parent_x protected
Definition at line 60 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_y
double larcv::LArbysImageMC::_parent_y protected
Definition at line 61 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_parent_z
double larcv::LArbysImageMC::_parent_z protected
Definition at line 62 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_producer_image2d
std::string larcv::LArbysImageMC::_producer_image2d protected
Definition at line 41 of file LArbysImageMC.h.
Referenced by configure(), and process().
_producer_roi
std::string larcv::LArbysImageMC::_producer_roi protected
Definition at line 40 of file LArbysImageMC.h.
Referenced by configure(), and process().
_proton_1st_pt_x
double larcv::LArbysImageMC::_proton_1st_pt_x protected
Definition at line 128 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_proton_1st_pt_y
double larcv::LArbysImageMC::_proton_1st_pt_y protected
Definition at line 129 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_proton_1st_pt_z
double larcv::LArbysImageMC::_proton_1st_pt_z protected
Definition at line 130 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_proton_last_pt_x
double larcv::LArbysImageMC::_proton_last_pt_x protected
Definition at line 132 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_proton_last_pt_y
double larcv::LArbysImageMC::_proton_last_pt_y protected
Definition at line 133 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_proton_last_pt_z
double larcv::LArbysImageMC::_proton_last_pt_z protected
Definition at line 134 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_rse_producer
std::string larcv::LArbysImageMC::_rse_producer protected
Definition at line 52 of file LArbysImageMC.h.
Referenced by configure(), and process().
_run
int larcv::LArbysImageMC::_run protected
Event ID.
Definition at line 47 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_select_background
bool larcv::LArbysImageMC::_select_background protected
Definition at line 183 of file LArbysImageMC.h.
_select_signal
bool larcv::LArbysImageMC::_select_signal protected
Definition at line 182 of file LArbysImageMC.h.
_selected
bool larcv::LArbysImageMC::_selected protected
Definition at line 180 of file LArbysImageMC.h.
_start
geo2d::Vector<float> larcv::LArbysImageMC::_start protected
Definition at line 99 of file LArbysImageMC.h.
_subrun
int larcv::LArbysImageMC::_subrun protected
Definition at line 48 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_lepton_end_pt_x
double larcv::LArbysImageMC::_true_lepton_end_pt_x protected
Definition at line 136 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_lepton_end_pt_y
double larcv::LArbysImageMC::_true_lepton_end_pt_y protected
Definition at line 137 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_lepton_end_pt_z
double larcv::LArbysImageMC::_true_lepton_end_pt_z protected
Definition at line 138 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_proton_end_pt_x
double larcv::LArbysImageMC::_true_proton_end_pt_x protected
Definition at line 124 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_proton_end_pt_y
double larcv::LArbysImageMC::_true_proton_end_pt_y protected
Definition at line 125 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_true_proton_end_pt_z
double larcv::LArbysImageMC::_true_proton_end_pt_z protected
Definition at line 126 of file LArbysImageMC.h.
Referenced by initialize(), and process().
_vtx_2d_t_v
std::vector<double> larcv::LArbysImageMC::_vtx_2d_t_v
Definition at line 151 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
_vtx_2d_w_v
std::vector<double> larcv::LArbysImageMC::_vtx_2d_w_v
2D Vertex Info
Definition at line 150 of file LArbysImageMC.h.
Referenced by Clear(), initialize(), and process().
The documentation for this class was generated from the following files:
LArbysImageMC.h
LArbysImageMC.cxx