LArCV: larcv::calcPeakADC Class Reference
larcv::calcPeakADC Class Reference
#include <calcPeakADC.h>
Public Member Functions
calcPeakADC (const std::string name="calcPeakADC")
Default constructor.
~calcPeakADC ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Public Attributes
float fThreshold
float fDeadtime
int fNewCols
int fNewRows
bool fDebug
std::string fImageProducer
TTree * ttree
float peakmax
int wireid
int planeid
float width
Detailed Description
Definition at line 31 of file calcPeakADC.h.
Constructor & Destructor Documentation
calcPeakADC()
larcv::calcPeakADC::calcPeakADC (const std::string name = "calcPeakADC")
Default constructor.
Definition at line 11 of file calcPeakADC.cxx.
Referenced by larcv::calcPeakADCProcessFactory::create().
     : ProcessBase(name)
   {}
~calcPeakADC()
larcv::calcPeakADC::~calcPeakADC () inline
Default destructor.
Definition at line 39 of file calcPeakADC.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::calcPeakADC::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file calcPeakADC.cxx.
References fDeadtime, fDebug, fImageProducer, fNewCols, fNewRows, fThreshold, and larcv::PSet::get().
Referenced by ~calcPeakADC().
   {
     fImageProducer = cfg.get<std::string>("ImageProducerName");
     fThreshold = cfg.get<float>("PeakThreshold");
     fDeadtime  = cfg.get<float>("Deadtime");
     fNewCols   = cfg.get<int>("NewCols",-1);
     fNewRows   = cfg.get<int>("NewRows",-1);
     fDebug     = cfg.get<bool>("Debug",false);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::calcPeakADC::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 106 of file calcPeakADC.cxx.
References ttree.
Referenced by ~calcPeakADC().
   {
     ttree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::calcPeakADC::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 25 of file calcPeakADC.cxx.
References peakmax, planeid, ttree, width, and wireid.
Referenced by ~calcPeakADC().
   {
     ttree = new TTree("adc","");
     ttree->Branch("planeid",&planeid,"planeid/I");
     ttree->Branch("wireid",&wireid,"wireid/I");
     ttree->Branch("peak",&peakmax, "peak/F" );
     ttree->Branch("width",&width, "width/F" );
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::calcPeakADC::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 34 of file calcPeakADC.cxx.
References larcv::ImageMeta::cols(), larcv::Image2D::compress(), larcv::EventImage2D::Emplace(), fDeadtime, fDebug, fImageProducer, fNewCols, fNewRows, fThreshold, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::Image2D::meta(), larcv::Image2D::paint(), peakmax, larcv::Image2D::pixel(), larcv::ImageMeta::plane(), planeid, larcv::ImageMeta::rows(), larcv::Image2D::set_pixel(), ttree, width, and wireid.
Referenced by ~calcPeakADC().
   {
     auto event_images = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, fImageProducer );
     larcv::EventImage2D* out_images = NULL;
     if ( fDebug )
       out_images = (larcv::EventImage2D*)mgr.get_data( larcv::kProductImage2D, "calib" );
     for ( auto const& img_src : event_images->Image2DArray() ) {
       //for ( int p=0; p<=8; p+=4 ) { // hack for 12 channel data
       //auto const& img_src = event_images->Image2DArray().at(p);
       larcv::Image2D img( img_src );
       if ( fNewCols>0 || fNewRows>0 )
     img.compress( fNewRows, fNewCols ); //504, 864
       int wfms = img.meta().cols();
       int ticks = img.meta().rows();
       //std::cout << "img (wmfs,ticks) = (" << wfms << " x " << ticks << ")" << std::endl;
       larcv::Image2D imgout( img_src );
       imgout.paint( 0.0 );
       for (int w=0; w<wfms; w++) {
     bool inpeak = false;
     float pmax = -1;
     int peakcenter = -1;
     int peakstart = -1;
     std::vector<int> peakcenters;
     for (int t=0; t<ticks; t++) {
       float y = img.pixel( t, w );
       if (y < fThreshold) // below thresh, skip
         continue;
       if (!inpeak) {
         if (peakcenters.size()==0 || peakcenters.at(peakcenters.size()-1)+fDeadtime<t ) {
           inpeak = true;
           pmax = y;
           peakcenter = t;
           peakstart = t;
         }
       }
       else {
         if (y>pmax) {
           pmax = y;
           peakcenter = t;
         }
         else {
           inpeak = false;
           wireid = w;
           planeid = img.meta().plane();
           peakmax = pmax;
           width   = t-peakstart;
           peakcenters.push_back( peakcenter );
           imgout.set_pixel( peakcenter, wireid, pmax );
           ttree->Fill();
         }
       }//end of if in peak
     }//end of tick loop
       }//end of wire loop
       if ( fDebug )
     out_images->Emplace( std::move(imgout) );
     }//end of img loop
   }//end of process
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fDeadtime
float larcv::calcPeakADC::fDeadtime
Definition at line 51 of file calcPeakADC.h.
Referenced by configure(), and process().
fDebug
bool larcv::calcPeakADC::fDebug
Definition at line 54 of file calcPeakADC.h.
Referenced by configure(), and process().
fImageProducer
std::string larcv::calcPeakADC::fImageProducer
Definition at line 55 of file calcPeakADC.h.
Referenced by configure(), and process().
fNewCols
int larcv::calcPeakADC::fNewCols
Definition at line 52 of file calcPeakADC.h.
Referenced by configure(), and process().
fNewRows
int larcv::calcPeakADC::fNewRows
Definition at line 53 of file calcPeakADC.h.
Referenced by configure(), and process().
fThreshold
float larcv::calcPeakADC::fThreshold
Definition at line 50 of file calcPeakADC.h.
Referenced by configure(), and process().
peakmax
float larcv::calcPeakADC::peakmax
Definition at line 59 of file calcPeakADC.h.
Referenced by initialize(), and process().
planeid
int larcv::calcPeakADC::planeid
Definition at line 61 of file calcPeakADC.h.
Referenced by initialize(), and process().
ttree
TTree* larcv::calcPeakADC::ttree
Definition at line 58 of file calcPeakADC.h.
Referenced by finalize(), initialize(), and process().
width
float larcv::calcPeakADC::width
Definition at line 62 of file calcPeakADC.h.
Referenced by initialize(), and process().
wireid
int larcv::calcPeakADC::wireid
Definition at line 60 of file calcPeakADC.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
calcPeakADC.h
calcPeakADC.cxx