LArCV: larcv::Image2D Class Reference
larcv::Image2D Class Reference
Meant to be a storage class for an image into a ROOT file.
#include <Image2D.h>
Public Types
enum CompressionModes_t { kSum, kAverage, kMaxPool, kOverWrite }
Various modes used to combine pixels.
Public Member Functions
Image2D (size_t row_count=0, size_t col_count=0)
ctor by # rows and # columns
Image2D (const ImageMeta &)
ctor from ImageMeta
Image2D (const ImageMeta &, const std::vector< float > &)
ctor from ImageMeta and 1D array data
Image2D (const Image2D &)
copy ctor
Image2D (ImageMeta &&, std::vector< float > &&)
attribute move ctor
virtual ~Image2D ()
dtor
void reset (const ImageMeta &)
Reset contents w/ new larcv::ImageMeta.
void reset_origin (double x, double y)
Move origin position.
ImageIndex_t index () const
Return image index ID number (should be unique within larcv::EventImage2D)
void index (ImageIndex_t n)
Index setter.
size_t size () const
Size of data, equivalent of # rows x # columns.
float pixel (size_t row, size_t col) const
Specific pixel value getter.
const ImageMeta & meta () const
larcv::ImageMeta const reference getter
std::vector< float > copy_compress (size_t row_count, size_t col_count, CompressionModes_t mode=kSum) const
Compress image data and returns compressed data 1D array.
void copy (size_t row, size_t col, const float *src, size_t num_pixel)
Mem-copy: insert num_pixel many data from src 1D array @ data index starting from (row,col)
void copy (size_t row, size_t col, const std::vector< float > &src, size_t num_pixel=0)
Mem-copy: insert num_pixel many data from src 1D array @ data index starting from (row,col)
void copy (size_t row, size_t col, const short *src, size_t num_pixel)
Fake mem-copy (loop element-wise copy): insert num_pixel many data from src 1D array @ data index starting from (row,col)
void copy (size_t row, size_t col, const std::vector< short > &src, size_t num_pixel=0)
Fake mem-copy (loop element-wise copy): insert num_pixel many data from src 1D array @ data index starting from (row,col)
void reverse_copy (size_t row, size_t col, const std::vector< float > &src, size_t nskip=0, size_t num_pixel=0)
Same as copy, but perform in reverse direction of rows (useful when src is not in the same order)
void reverse_copy (size_t row, size_t col, const std::vector< short > &src, size_t nskip=0, size_t num_pixel=0)
Same as copy, but perform in reverse direction of rows (useful when src is not in the same order)
Image2D crop (const ImageMeta &crop_meta) const
Crop specified region via crop_meta to generate a new larcv::Image2D.
const std::vector< float > & as_vector () const
1D const reference array getter
void resize (size_t row_count, size_t col_count, float fillval=0.0)
Re-size the 1D data array w/ updated # rows and # columns.
void set_pixel (size_t row, size_t col, float value)
Set pixel value via row/col specification.
void set_pixel (size_t index, float value)
Set pixel value via index specification.
void paint (float value)
Paint all pixels with a specified value.
void paint_row (int row, float value)
Paint a row of pixels with a specified value.
void paint_col (int col, float value)
Paint a column of pixels with a specified value.
void threshold (float thres, float lower_overwrite)
Apply threshold: pixels lower than "thres" are all overwritten by lower_overwrite value.
void binary_threshold (float thres, float lower_overwrite, float upper_overwrite)
Apply threshold: make all pixels to take only 2 values, lower_overwrite or upper_overwrite.
void clear_data ()
Clear data contents.
void compress (size_t row_count, size_t col_count, CompressionModes_t mode=kSum)
Call copy_compress internally and set itself to the result.
void overlay (const Image2D &, CompressionModes_t mode=kSum)
Overlay with another Image2D: overlapped pixel region is merged.
std::vector< float > && move ()
Move data contents out.
void move (std::vector< float > &&)
Move data contents in.
Image2D & operator+= (const float val)
Image2D operator+ (const float val) const
Image2D & operator-= (const float val)
Image2D operator- (const float val) const
Image2D & operator*= (const float val)
Image2D operator* (const float val) const
Image2D & operator/= (const float val)
Image2D operator/ (const float val) const
Image2D & operator+= (const std::vector< float > &rhs)
Image2D & operator-= (const std::vector< float > &rhs)
Image2D & operator+= (const larcv::Image2D &rhs)
Image2D multiRHS (const Image2D &rhs) const
Matrix multiplicaition.
Image2D & operator*= (const Image2D &rhs)
uniry operator for matrix multiplicaition
Image2D operator* (const Image2D &rhs) const
binary operator for matrix multiplication
void eltwise (const Image2D &rhs)
Element-wise pixel value multiplication.
void eltwise (const std::vector< float > &arr, bool allow_longer=false)
Element-wise multiplication w/ 1D array data.
Private Member Functions
void clear ()
Private Attributes
std::vector< float > _img
ImageIndex_t _id
ImageMeta _meta
Detailed Description
Meant to be a storage class for an image into a ROOT file.
Ultimately data is 1D array.
Definition at line 28 of file Image2D.h.
Member Enumeration Documentation
CompressionModes_t
enum larcv::Image2D::CompressionModes_t
Various modes used to combine pixels.
Enumerator
kSum
kAverage
kMaxPool
kOverWrite
Definition at line 50 of file Image2D.h.
 { kSum, kAverage, kMaxPool, kOverWrite};
Constructor & Destructor Documentation
Image2D() [1/5]
larcv::Image2D::Image2D (size_t row_count = 0, size_t col_count = 0)
ctor by # rows and # columns
Definition at line 8 of file Image2D.cxx.
Referenced by crop().
     : _img(row_count*col_count,0.)
     , _meta(col_count,row_count,row_count,col_count,0.,0.)
   {}
Image2D() [2/5]
larcv::Image2D::Image2D (const ImageMeta & meta)
ctor from ImageMeta
Definition at line 13 of file Image2D.cxx.
     : _img(meta.rows()*meta.cols(),0.)
     , _meta(meta)
   {}
Image2D() [3/5]
larcv::Image2D::Image2D (const ImageMeta & meta, const std::vector< float > & img)
ctor from ImageMeta and 1D array data
Definition at line 18 of file Image2D.cxx.
References larcv::ImageMeta::cols(), and larcv::ImageMeta::rows().
     : _img(img)
     , _meta(meta)
   { if(img.size() != meta.rows() * meta.cols()) throw larbys("Inconsistent dimensions!"); }
Image2D() [4/5]
larcv::Image2D::Image2D (const Image2D & rhs)
copy ctor
Definition at line 23 of file Image2D.cxx.
     : _img(rhs._img)
     , _meta(rhs._meta)
   {}
Image2D() [5/5]
larcv::Image2D::Image2D (ImageMeta && meta, std::vector< float > && img)
attribute move ctor
Definition at line 28 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::cols(), and larcv::ImageMeta::rows().
     : _img(std::move(img))
     , _meta(std::move(meta))
   { if(_img.size() != _meta.rows() * _meta.cols()) throw larbys("Inconsistent dimensions!"); }
~Image2D()
virtual larcv::Image2D::~Image2D () inline virtual
dtor
Definition at line 45 of file Image2D.h.
 {}
Member Function Documentation
as_vector()
const std::vector<float>& larcv::Image2D::as_vector () const inline
1D const reference array getter
Definition at line 80 of file Image2D.h.
References _img, binary_threshold(), clear_data(), compress(), index(), kSum, move(), overlay(), paint(), paint_col(), paint_row(), resize(), set_pixel(), and threshold().
Referenced by larcv::as_caffe_ndarray(), larcv::as_ndarray(), larcv::RandomCropper::crop(), eltwise(), larcv::mask_image(), overlay(), larcv::SSNetEventAna::process(), larcv::ROIMask::process(), and larcv::SegmentRelabel::process().
     { return _img; }
binary_threshold()
void larcv::Image2D::binary_threshold (float thres, float lower_overwrite, float upper_overwrite)
Apply threshold: make all pixels to take only 2 values, lower_overwrite or upper_overwrite.
Definition at line 98 of file Image2D.cxx.
References _img.
Referenced by as_vector().
   { for(auto& v : _img) v = (v <= thres ? lower_overwrite : upper_overwrite); }
clear()
void larcv::Image2D::clear () private
Definition at line 60 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::update().
                       {
     _img.clear();
     _img.resize(1,0);
     _meta.update(1,1);
     //std::cout << "[Image2D (" << this << ")] Cleared image memory " << std::endl;
   }
clear_data()
void larcv::Image2D::clear_data ()
Clear data contents.
Definition at line 67 of file Image2D.cxx.
References _img.
Referenced by as_vector().
 { for(auto& v : _img) v = 0.; }
compress()
void larcv::Image2D::compress (size_t row_count, size_t col_count, CompressionModes_t mode = kSum)
Call copy_compress internally and set itself to the result.
Definition at line 214 of file Image2D.cxx.
References _img, _meta, copy_compress(), larcv::ImageMeta::height(), larcv::ImageMeta::max_y(), larcv::ImageMeta::min_x(), larcv::ImageMeta::plane(), and larcv::ImageMeta::width().
Referenced by as_vector(), larcv::AStarTracker::CreateDataImage(), larcv::AStar3DAlgo::downsampleAndFindPath(), larcv::calcPeakADC::process(), and larcv::pmtweights::PMTWeightImageBuilder::process().
   {
     _img = copy_compress(rows,cols,mode);
     _meta = ImageMeta(_meta.width(),_meta.height(),rows,cols,_meta.min_x(),_meta.max_y(),_meta.plane());
   }
copy() [1/4]
void larcv::Image2D::copy (size_t row, size_t col, const float * src, size_t num_pixel)
Mem-copy: insert num_pixel many data from src 1D array @ data index starting from (row,col)
Definition at line 104 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::index().
Referenced by copy(), meta(), supera::OpDigit2Image2D(), and larcv::SegmentRelabel::process().
   {
     const size_t idx = _meta.index(row,col);
     if(idx+num_pixel-1 >= _img.size()) throw larbys("memcpy size exceeds allocated memory!");
     memcpy(&(_img[idx]),src, num_pixel * sizeof(float));
   }
copy() [2/4]
void larcv::Image2D::copy (size_t row, size_t col, const std::vector< float > & src, size_t num_pixel = 0)
Mem-copy: insert num_pixel many data from src 1D array @ data index starting from (row,col)
Definition at line 111 of file Image2D.cxx.
References copy().
   {
     if(!num_pixel)
       this->copy(row,col,(float*)(&(src[0])),src.size());
     else if(num_pixel <= src.size())
       this->copy(row,col,(float*)&src[0],num_pixel);
     else
       throw larbys("Not enough pixel in source!");
   }
copy() [3/4]
void larcv::Image2D::copy (size_t row, size_t col, const short * src, size_t num_pixel)
Fake mem-copy (loop element-wise copy): insert num_pixel many data from src 1D array @ data index starting from (row,col)
Definition at line 121 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::index().
   {
     const size_t idx = _meta.index(row,col);
     if(idx+num_pixel-1 >= _img.size()) throw larbys("memcpy size exceeds allocated memory!");
     for(size_t i=0; i<num_pixel; ++i) _img[idx+i] = src[idx];
   }
copy() [4/4]
void larcv::Image2D::copy (size_t row, size_t col, const std::vector< short > & src, size_t num_pixel = 0)
Fake mem-copy (loop element-wise copy): insert num_pixel many data from src 1D array @ data index starting from (row,col)
Definition at line 128 of file Image2D.cxx.
References copy().
   {
     if(!num_pixel)
       this->copy(row,col,(short*)(&(src[0])),src.size());
     else if(num_pixel <= src.size())
       this->copy(row,col,(short*)&src[0],num_pixel);
     else
       throw larbys("Not enough pixel in source!");
   }
copy_compress()
std::vector< float > larcv::Image2D::copy_compress (size_t row_count, size_t col_count, CompressionModes_t mode = kSum) const
Compress image data and returns compressed data 1D array.
Definition at line 172 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::cols(), kAverage, kMaxPool, kOverWrite, and larcv::ImageMeta::rows().
Referenced by compress(), and meta().
   {
     if(mode == kOverWrite)
       throw larbys("kOverWrite is invalid for copy_compress!");
     const size_t self_cols = _meta.cols();
     const size_t self_rows = _meta.rows();
     if(self_cols % cols || self_rows % rows) {
       char oops[500];
       sprintf(oops,"Compression only possible if height/width are modular 0 of compression factor! H:%zuMOD%zu=%zu W:%zuMOD%zu=%zu",
           self_rows,rows,self_rows%rows,self_cols,cols,self_cols%cols);
       throw larbys(oops);
     }
     size_t cols_factor = self_cols / cols;
     size_t rows_factor = self_rows / rows;
     std::vector<float> result(cols*rows,0);
     for(size_t col=0; col<cols; ++col) {
       for(size_t row=0; row<rows; ++row) {
     float value = 0;
     for(size_t orig_col=col*cols_factor; orig_col<(col+1)*cols_factor; ++orig_col)
       for(size_t orig_row=row*rows_factor; orig_row<(row+1)*rows_factor; ++orig_row) {
         if ( mode!=kMaxPool ) {
           // for sum and average mode
           value += _img[orig_col * self_rows + orig_row];
         }
         else {
           // maxpool
           value = ( value<_img[orig_col * self_rows + orig_row] ) ? _img[orig_col * self_rows + orig_row] : value;
         }
       }
     result[col*rows + row] = value;
     if ( mode==kAverage )
       result[col*rows + row] /= (float)(rows_factor*cols_factor);
       }
     }
     return result;
   }
crop()
Image2D larcv::Image2D::crop (const ImageMeta & crop_meta) const
Crop specified region via crop_meta to generate a new larcv::Image2D.
Definition at line 220 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::col(), Image2D(), larcv::ImageMeta::index(), larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), and larcv::ImageMeta::row().
Referenced by larcv::LArbysImageExtract::FillcvMat(), meta(), larcv::MultiROICropper::process(), and larcv::ROIMask::process().
   {
     // Croppin region must be within the image
     if( crop_meta.min_x() < _meta.min_x() || crop_meta.min_y() < _meta.min_y() ||
     crop_meta.max_x() > _meta.max_x() || crop_meta.max_y() > _meta.max_y() )
       throw larbys("Cropping region contains region outside the image!");
     size_t min_col = _meta.col(crop_meta.min_x() + _meta.pixel_width()  / 2. );
     size_t max_col = _meta.col(crop_meta.max_x() - _meta.pixel_width()  / 2. );
     size_t min_row = _meta.row(crop_meta.max_y() - _meta.pixel_height() / 2. );
     size_t max_row = _meta.row(crop_meta.min_y() + _meta.pixel_height() / 2. );
     /*
     std::cout<<"Cropping! Requested:" << std::endl
          << crop_meta.dump() << std::endl
          <<"Original:"<<std::endl
          <<_meta.dump()<<std::endl;
     std::cout<<min_col<< " => " << max_col << " ... " << min_row << " => " << max_row << std::endl;
     std::cout<<_meta.width() << " / " << _meta.cols() << " = " << _meta.pixel_width() << std::endl;
     */
     ImageMeta res_meta( (max_col - min_col + 1) * _meta.pixel_width(),
             (max_row - min_row + 1) * _meta.pixel_height(),
             (max_row - min_row + 1),
             (max_col - min_col + 1),
             _meta.min_x() + min_col * _meta.pixel_width(),
             _meta.max_y() - min_row * _meta.pixel_height(),
             _meta.plane());
     std::vector<float> img;
     img.resize(res_meta.cols() * res_meta.rows());
     size_t column_size = max_row - min_row + 1;
     for(size_t col=min_col; col<=max_col; ++col)
       memcpy(&(img[(col-min_col)*column_size]), &(_img[_meta.index(min_row,col)]), column_size * sizeof(float));
     //std::cout<<"Cropped:" << std::endl << res_meta.dump()<<std::endl;
     return Image2D(std::move(res_meta),std::move(img));
   }
eltwise() [1/2]
void larcv::Image2D::eltwise (const Image2D & rhs)
Element-wise pixel value multiplication.
Definition at line 409 of file Image2D.cxx.
References _meta, as_vector(), larcv::ImageMeta::cols(), meta(), and larcv::ImageMeta::rows().
Referenced by operator/().
{
     // check multiplication is valid
     auto const& meta = rhs.meta();
     if(meta.cols() != _meta.cols() || meta.rows() != _meta.rows()) {
       char oops[500];
       sprintf( oops, "Image2D element-wise multiplication not valid. LHS cols (%zu) != RHS rcols (%zu) or LHS rows(%zu)!=RHS rows(%zu)",
            _meta.cols(), meta.cols(), _meta.rows(), meta.rows() );
       throw larbys(oops);
     }
     eltwise(rhs.as_vector(),false);
   }
eltwise() [2/2]
void larcv::Image2D::eltwise (const std::vector< float > & arr, bool allow_longer = false)
Element-wise multiplication w/ 1D array data.
Definition at line 396 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::cols().
{
     // check multiplication is valid
     if ( !( (allow_longer && _img.size() <= arr.size()) || arr.size() == _img.size() ) ) {
       char oops[500];
       sprintf( oops, "Image2D element-wise multiplication not valid. LHS size = %zu (row=%zu col=%zu) while argument size = %zu",
            _img.size(),_meta.cols(), _meta.cols(), arr.size());
       throw larbys(oops);
     }
     // Element-wise multiplication: do random access as dimension has already been checked
     for (size_t i=0; i<_img.size(); ++i)
       _img[i] *= arr[i];
   }
index() [1/2]
ImageIndex_t larcv::Image2D::index () const inline
Return image index ID number (should be unique within larcv::EventImage2D)
Definition at line 54 of file Image2D.h.
References _id.
Referenced by as_vector(), and set_pixel().
 { return _id; }
index() [2/2]
void larcv::Image2D::index (ImageIndex_t n) inline
Index setter.
Definition at line 56 of file Image2D.h.
References _id.
 { _id = n; }
meta()
const ImageMeta& larcv::Image2D::meta () const inline
larcv::ImageMeta const reference getter
Definition at line 62 of file Image2D.h.
References _meta, copy(), copy_compress(), crop(), larcv::crop_meta(), kSum, and reverse_copy().
Referenced by larcv::as_caffe_ndarray(), larcv::as_gray_mat(), larcv::as_mat(), larcv::as_mat_1FC(), larcv::as_mat_greyscale2bgr(), larcv::as_ndarray(), larcv::as_th2d(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::AStarTracker::CreateDataImage(), larcv::RandomCropper::crop(), larcv::crop_meta(), larcv::AStarTracker::CropFullImage2bounds(), larcv::DumpHiResCropImages::DumpBGRImage(), eltwise(), dbscan::extractPointsFromImage(), dbscan::extractPointsFromImageBounds(), larcv::fill_img_col(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::mask_image(), multiRHS(), operator+=(), overlay(), larcv::ChannelMax::process(), larcv::MultiROICropper::process(), larcv::VertexImg::process(), larcv::DumpHiResCropImages::process(), larcv::EmbedImage::process(), larcv::ROIMask::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::SegmentRelabel::process(), larcv::hires::HiResImageDivider::process(), and reset().
 { return _meta; }
move() [1/2]
std::vector< float > && larcv::Image2D::move ()
Move data contents out.
Definition at line 331 of file Image2D.cxx.
References _img.
Referenced by as_vector(), larcv::GenDeadChannelMap::finalize(), and larcv::mask_image().
   { return std::move(_img); }
move() [2/2]
void larcv::Image2D::move (std::vector< float > && data)
Move data contents in.
Definition at line 334 of file Image2D.cxx.
References _img.
   { _img = std::move(data); }
multiRHS()
Image2D larcv::Image2D::multiRHS (const Image2D & rhs) const
Matrix multiplicaition.
Definition at line 363 of file Image2D.cxx.
References larcv::ImageMeta::cols(), k, meta(), pixel(), resize(), larcv::ImageMeta::rows(), and set_pixel().
Referenced by operator*(), operator*=(), and operator/().
{
     // check multiplication is valid
     if ( meta().cols()!=rhs.meta().rows() ) {
       char oops[500];
       sprintf( oops, "Image2D Matrix multiplication not valid. LHS cols (%zu) != RHS rows (%zu).", meta().cols(), rhs.meta().rows() );
       throw larbys(oops);
     }
     // LHS copies internal data
     Image2D out( *this );
     out.resize( (*this).meta().rows(), rhs.meta().cols() );
     for (int r=0; r<(int)(out.meta().rows()); r++) {
       for (int c=0; c<(int)(out.meta().cols()); c++) {
     float val = 0.0;
     for (int k=0; k<(int)(meta().cols()); k++) {
       val += pixel( r, k )*rhs.pixel(k,c);
     }
     out.set_pixel( r, c, val );
       }
     }
     return out;
   }
operator*() [1/2]
Image2D larcv::Image2D::operator* (const float val) const inline
Definition at line 119 of file Image2D.h.
Referenced by operator/().
     { Image2D res = (*this); res*=val; return res; }
operator*() [2/2]
Image2D larcv::Image2D::operator* (const Image2D & rhs) const
binary operator for matrix multiplication
Definition at line 387 of file Image2D.cxx.
References multiRHS().
{
     return (*this).multiRHS( rhs );
   }
operator*=() [1/2]
Image2D& larcv::Image2D::operator*= (const float val) inline
Definition at line 117 of file Image2D.h.
References _img.
Referenced by operator/().
     { for(auto& v : _img) v*= val; return (*this);}
operator*=() [2/2]
Image2D & larcv::Image2D::operator*= (const Image2D & rhs)
uniry operator for matrix multiplicaition
Definition at line 391 of file Image2D.cxx.
References multiRHS().
{
     (*this) = multiRHS( rhs );
     return (*this);
   }
operator+()
Image2D larcv::Image2D::operator+ (const float val) const inline
Definition at line 111 of file Image2D.h.
     { Image2D res = (*this); res+=val; return res; }
operator+=() [1/3]
Image2D& larcv::Image2D::operator+= (const float val) inline
Definition at line 109 of file Image2D.h.
References _img.
Referenced by operator/().
     { for(auto& v : _img) v+= val; return (*this);}
operator+=() [2/3]
Image2D & larcv::Image2D::operator+= (const std::vector< float > & rhs)
Definition at line 337 of file Image2D.cxx.
References _img.
   {
     if(rhs.size()!=_img.size()) throw larbys("Cannot call += uniry operator w/ incompatible size!");
     for(size_t i=0; i<_img.size(); ++i) _img[i] += rhs[i];
     return (*this);
   }
operator+=() [3/3]
Image2D & larcv::Image2D::operator+= (const larcv::Image2D & rhs)
Definition at line 344 of file Image2D.cxx.
References _img, larcv::ImageMeta::cols(), meta(), pixel(), larcv::ImageMeta::rows(), set_pixel(), and size().
   {
     if(rhs.size()!=_img.size()) throw larbys("Cannot call += uniry operator w/ incompatible size!");
     for (size_t col=0; col<meta().cols(); col++) {
       for ( size_t row=0; row<meta().rows(); row++ ) {
         float val = pixel(row,col);
         set_pixel(row,col,val+rhs.pixel(row,col));
       }
     }
     return (*this);
   }
operator-()
Image2D larcv::Image2D::operator- (const float val) const inline
Definition at line 115 of file Image2D.h.
     { Image2D res = (*this); res-=val; return res; }
operator-=() [1/2]
Image2D& larcv::Image2D::operator-= (const float val) inline
Definition at line 113 of file Image2D.h.
References _img.
Referenced by operator/().
     { for(auto& v : _img) v-= val; return (*this);}
operator-=() [2/2]
Image2D & larcv::Image2D::operator-= (const std::vector< float > & rhs)
Definition at line 356 of file Image2D.cxx.
References _img.
   {
     if(rhs.size()!=_img.size()) throw larbys("Cannot call += uniry operator w/ incompatible size!");
     for(size_t i=0; i<_img.size(); ++i) _img[i] -= rhs[i];
     return (*this);
   }
operator/()
Image2D larcv::Image2D::operator/ (const float val) const inline
Definition at line 123 of file Image2D.h.
References eltwise(), multiRHS(), operator*(), operator*=(), operator+=(), and operator-=().
     { Image2D res = (*this); res/=val; return res; }
operator/=()
Image2D& larcv::Image2D::operator/= (const float val) inline
Definition at line 121 of file Image2D.h.
References _img.
     { for(auto& v : _img) v/= val; return (*this);}
overlay()
void larcv::Image2D::overlay (const Image2D & rhs, CompressionModes_t mode = kSum)
Overlay with another Image2D: overlapped pixel region is merged.
Definition at line 262 of file Image2D.cxx.
References _img, _meta, as_vector(), larcv::ImageMeta::col(), larcv::ImageMeta::index(), kAverage, kMaxPool, kOverWrite, kSum, larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), meta(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), and larcv::ImageMeta::row().
Referenced by as_vector(), larcv::ImageMerger::process(), larcv::PyImageStitcher::process(), and larcv::ROIMask::process().
   {
     auto const& rhs_meta = rhs.meta();
     if(rhs_meta.pixel_height() != _meta.pixel_height() || rhs_meta.pixel_width() != _meta.pixel_width())
       throw larbys("Overlay not supported yet for images w/ different pixel size!");
     double x_min = std::max(_meta.min_x(),rhs_meta.min_x());
     double x_max = std::min(_meta.max_x(),rhs_meta.max_x());
     if(x_min >= x_max) return;
     double y_min = std::max(_meta.min_y(),rhs_meta.min_y());
     double y_max = std::min(_meta.max_y(),rhs_meta.max_y());
     if(y_min >= y_max) return;
     size_t row_min1 = _meta.row(y_max);
     size_t col_min1 = _meta.col(x_min);
     size_t row_min2 = rhs_meta.row(y_max);
     size_t col_min2 = rhs_meta.col(x_min);
     size_t nrows = (y_max - y_min) / _meta.pixel_height();
     size_t ncols = (x_max - x_min) / _meta.pixel_width();
     auto const& img2 = rhs.as_vector();
     for(size_t col_index=0; col_index < ncols; ++col_index) {
       size_t index1 = _meta.index(row_min1,col_min1+col_index);
       size_t index2 = rhs_meta.index(row_min2,col_min2+col_index);
       switch(mode) {
       case kSum:
     for(size_t row_index=0; row_index < nrows; ++row_index)
       _img[index1+row_index] += img2[index2+row_index];
     break;
       case kAverage:
     for(size_t row_index=0; row_index < nrows; ++row_index)
       _img[index1+row_index] += (_img[index1+row_index] + img2[index2+row_index]) / 2.;
     break;
       case kMaxPool:
     for(size_t row_index=0; row_index < nrows; ++row_index)
       _img[index1+row_index] = std::max(_img[index1+row_index],img2[index2+row_index]);
     break;
       case kOverWrite:
     for(size_t row_index=0; row_index < nrows; ++row_index)
       _img[index1+row_index] = img2[index2+row_index];
     break;
       }
     }
   }
paint()
void larcv::Image2D::paint (float value)
Paint all pixels with a specified value.
Definition at line 80 of file Image2D.cxx.
References _img.
Referenced by as_vector(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), supera::OpDigit2Image2D(), larcv::SegWeightTrackShower::process(), larcv::BlankImage::process(), larcv::ImageFromPixel2D::process(), larcv::DBSCAN::process(), larcv::ImageFromPixel2DCluster::process(), larcv::SegWeightInstance::process(), larcv::MaskImage::process(), larcv::PyImageStitcher::process(), larcv::VertexImg::process(), larcv::NNCosine::process(), larcv::calcPeakADC::process(), larcv::ROIMask::process(), reset(), larcv::AStar3DAlgo::visualizeScores(), and supera::Wire2Image2D().
   { for(auto& v : _img) v=value; }
paint_col()
void larcv::Image2D::paint_col (int col, float value)
Paint a column of pixels with a specified value.
Definition at line 89 of file Image2D.cxx.
References _meta, larcv::ImageMeta::rows(), and set_pixel().
Referenced by as_vector().
   {
     for ( size_t row=0; row<_meta.rows(); row++ )
       set_pixel( row, col, value );
   }
paint_row()
void larcv::Image2D::paint_row (int row, float value)
Paint a row of pixels with a specified value.
Definition at line 83 of file Image2D.cxx.
References _meta, larcv::ImageMeta::cols(), and set_pixel().
Referenced by as_vector().
   {
     for ( size_t col=0; col<_meta.cols(); col++ )
       set_pixel( row, col, value );
   }
pixel()
float larcv::Image2D::pixel (size_t row, size_t col) const
Specific pixel value getter.
Definition at line 101 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::index().
Referenced by larcv::as_gray_mat(), larcv::as_mat(), larcv::as_mat_1FC(), larcv::as_mat_greyscale2bgr(), larcv::as_th2d(), larcv::AStarTracker::CropFullImage2bounds(), larcv::DumpHiResCropImages::DumpBGRImage(), dbscan::extractPointsFromImageBounds(), larcv::fill_img_col(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), multiRHS(), operator+=(), larcv::DumpHiResCropImages::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), and size().
   { return _img[_meta.index(row,col)]; }
reset()
void larcv::Image2D::reset (const ImageMeta & meta)
Reset contents w/ new larcv::ImageMeta.
Definition at line 33 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::cols(), meta(), paint(), and larcv::ImageMeta::rows().
   {
     _meta = meta;
     if(_img.size() != _meta.rows() * _meta.cols()) _img.resize(_meta.rows() * _meta.cols());
     paint(0.);
   }
reset_origin()
void larcv::Image2D::reset_origin (double x, double y) inline
Move origin position.
Definition at line 52 of file Image2D.h.
References _meta, and larcv::ImageMeta::reset_origin().
 {_meta.reset_origin(x,y);}
resize()
void larcv::Image2D::resize (size_t row_count, size_t col_count, float fillval = 0.0)
Re-size the 1D data array w/ updated # rows and # columns.
Definition at line 40 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::cols(), larcv::ImageMeta::max_y(), larcv::ImageMeta::min_x(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), and larcv::ImageMeta::rows().
Referenced by as_vector(), larcv::PIDImageMaker::MPIDRecoImgFiller(), multiRHS(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::PIDImageMaker::SPIDRecoImgFiller(), and larcv::PIDImageMaker::VoidImgFiller().
   {
     auto const current_rows = _meta.rows();
     auto const current_cols = _meta.cols();
     std::vector<float> img(rows*cols,fillval);
     size_t npixels = std::min(current_rows,rows);
     for(size_t c=0; c < std::min(cols,current_cols); ++c) {
       for(size_t r=0; r<npixels; ++r) {
     img[c*rows+r] = _img[c*current_rows+r];
       }
     }
     _meta = ImageMeta(cols * _meta.pixel_width(), rows * _meta.pixel_height(),
               rows, cols,
               _meta.min_x(), _meta.max_y(),
               _meta.plane());
     _img = std::move(img);
   }
reverse_copy() [1/2]
void larcv::Image2D::reverse_copy (size_t row, size_t col, const std::vector< float > & src, size_t nskip = 0, size_t num_pixel = 0)
Same as copy, but perform in reverse direction of rows (useful when src is not in the same order)
Definition at line 138 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::index().
Referenced by meta(), and supera::Wire2Image2D().
   {
     size_t idx = 0;
     try{
       idx = _meta.index(row,col);
     }catch(const larbys& err){
       std::cout << "Exception caught @ " << __FUNCTION__ << std::endl
         << "Image2D ... fill row: "<<row<<" => "<<(row+num_pixel-1)<<std::endl
         << "Image2D ... orig idx: "<<nskip<<" => "<<nskip+num_pixel-1<<std::endl
         << "Re-throwing exception..."<<std::endl;
       throw err;
     }
     if(!num_pixel) num_pixel = src.size() - nskip;
     if( (idx+1) < num_pixel ) num_pixel = idx + 1;
     for(size_t i=0; i<num_pixel; ++i) { _img[idx+i] = src[nskip+num_pixel-i-1]; }
   }
reverse_copy() [2/2]
void larcv::Image2D::reverse_copy (size_t row, size_t col, const std::vector< short > & src, size_t nskip = 0, size_t num_pixel = 0)
Same as copy, but perform in reverse direction of rows (useful when src is not in the same order)
Definition at line 155 of file Image2D.cxx.
References _img, _meta, and larcv::ImageMeta::index().
   {
     size_t idx = 0;
     try{
       idx = _meta.index(row,col);
     }catch(const larbys& err){
       std::cout << "Exception caught @ " << __FUNCTION__ << std::endl
         << "Image2D ... fill row: "<<row<<" => "<<(row+num_pixel-1)<<std::endl
         << "Image2D ... orig idx: "<<nskip<<" => "<<nskip+num_pixel-1<<std::endl
         << "Re-throwing exception..."<<std::endl;
       throw err;
     }
     if(!num_pixel) num_pixel = src.size() - nskip;
     if( (idx+1) < num_pixel ) num_pixel = idx + 1;
     for(size_t i=0; i<num_pixel; ++i) { _img[idx+i] = (float)(src[nskip+num_pixel-i-1]); }
   }
set_pixel() [1/2]
void larcv::Image2D::set_pixel (size_t row, size_t col, float value)
Set pixel value via row/col specification.
Definition at line 74 of file Image2D.cxx.
References _img, _meta, larcv::ImageMeta::cols(), larcv::ImageMeta::index(), and larcv::ImageMeta::rows().
Referenced by as_vector(), larcv::cluster_to_image2d(), larcv::pmtweights::PMTWireWeights::configure(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::AStarTracker::CropFullImage2bounds(), larcv::AStarTracker::EnhanceDerivative(), larcv::fill_img_col(), supera::Hit2Image2D(), larcv::imread(), larcv::imread_gray(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::mat_to_image2d(), larcv::PIDImageMaker::MPIDRecoImgFiller(), multiRHS(), operator+=(), paint_col(), paint_row(), larcv::DBSCAN::process(), larcv::ImageFromPixel2D::process(), larcv::ChannelMax::process(), larcv::ImageFromPixel2DCluster::process(), larcv::NNCosine::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::PIDImageMaker::SPIDRecoImgFiller(), and supera::Wire2Image2D().
{
     if ( row >= _meta.rows() || col >= _meta.cols() )
       throw larbys("Out-of-bound pixel set request!");
     _img[ _meta.index(row,col) ] = value;
   }
set_pixel() [2/2]
void larcv::Image2D::set_pixel (size_t index, float value)
Set pixel value via index specification.
Definition at line 69 of file Image2D.cxx.
References _img, and index().
{
     if ( index >= _img.size() ) throw larbys("Out-of-bound pixel set request!");
     _img[ index ] = value;
   }
size()
size_t larcv::Image2D::size () const inline
Size of data, equivalent of # rows x # columns.
Definition at line 58 of file Image2D.h.
References _img, and pixel().
Referenced by larcv::PIDImageMaker::MPIDRecoImgFiller(), operator+=(), and larcv::PIDImageMaker::SPIDRecoImgFiller().
 { return _img.size(); }
threshold()
void larcv::Image2D::threshold (float thres, float lower_overwrite)
Apply threshold: pixels lower than "thres" are all overwritten by lower_overwrite value.
Definition at line 95 of file Image2D.cxx.
References _img.
Referenced by as_vector().
   { for(auto& v : _img) if( v <= thres ) v = lower_overwrite; }
Member Data Documentation
_id
ImageIndex_t larcv::Image2D::_id private
Definition at line 145 of file Image2D.h.
Referenced by index().
_img
std::vector<float> larcv::Image2D::_img private
Definition at line 144 of file Image2D.h.
Referenced by as_vector(), binary_threshold(), clear(), clear_data(), compress(), copy(), copy_compress(), crop(), eltwise(), Image2D(), move(), operator*=(), operator+=(), operator-=(), operator/=(), overlay(), paint(), pixel(), reset(), resize(), reverse_copy(), set_pixel(), size(), and threshold().
_meta
ImageMeta larcv::Image2D::_meta private
Definition at line 146 of file Image2D.h.
Referenced by clear(), compress(), copy(), copy_compress(), crop(), eltwise(), Image2D(), meta(), overlay(), paint_col(), paint_row(), pixel(), reset(), reset_origin(), resize(), reverse_copy(), and set_pixel().
The documentation for this class was generated from the following files:
Image2D.h
Image2D.cxx