LArCV: larcv::supera::MCParticleTree< T, U, V, W > Class Template Reference
larcv::supera::MCParticleTree< T, U, V, W > Class Template Reference
User defined class MCParticleTree ...
#include <MCParticleTree.h>
Public Member Functions
MCParticleTree ()
Default constructor.
~MCParticleTree ()
Default destructor.
void configure (const Config_t &cfg)
Cropper< U, V, W > & GetCropper ()
void DefinePrimary (const std::vector< T > &)
void RegisterSecondary (const std::vector< U > &, const int time_offset)
void RegisterSecondary (const std::vector< U > &, const std::vector< W > &, const int time_offset)
void RegisterSecondary (const std::vector< V > &, const int time_offset)
void RegisterSecondary (const std::vector< V > &, const std::vector< W > &, const int time_offset)
void DefinePrimary (const larcv::Vertex &vtx, const larcv::ROI &interaction)
void DefinePrimaries (const std::vector< U > &, const int time_offset)
void DefinePrimaries (const std::vector< V > &, const int time_offset)
void RegisterSecondary (const larcv::Vertex &vtx, const larcv::ROI &secondary)
void UpdatePrimaryROI ()
std::vector< larcv::supera::InteractionROI_t > GetPrimaryROI () const
std::vector< larcv::supera::InteractionROI_t > GetNeutrinoROI () const
void clear ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
Cropper< U, V, W > _cropper
std::map< larcv::Vertex, larcv::supera::InteractionROI_t > _roi_m
std::vector< MCPNode *> nodelist
std::vector< int > idx_primaries
std::map< larcv::Vertex, int > idx_vertexmap
std::map< int, MCPNode *> primaryids
std::map< int, double > _min_energy_init_pdg
std::map< int, double > _min_energy_deposit_pdg
double _min_energy_init_mcshower
double _min_energy_init_mctrack
double _min_energy_deposit_mcshower
double _min_energy_deposit_mctrack
size_t _min_nplanes
Detailed Description
template<class T, class U, class V, class W>
class larcv::supera::MCParticleTree< T, U, V, W >
User defined class MCParticleTree ...
these comments are used to generate doxygen documentation!
Definition at line 36 of file Supera/larfmwk_shared/MCParticleTree.h.
Constructor & Destructor Documentation
MCParticleTree()
template<class T, class U, class V, class W> larcv::supera::MCParticleTree< T, U, V, W >::MCParticleTree () inline
Default constructor.
Definition at line 41 of file Supera/larfmwk_shared/MCParticleTree.h.
                        : larcv::larcv_base("MCParticleTree")
                , _min_energy_init_mcshower(0)
                , _min_energy_init_mctrack(0)
                , _min_energy_deposit_mcshower(0)
                , _min_energy_deposit_mctrack(0)
                , _min_nplanes(2)
       {}
~MCParticleTree()
template<class T, class U, class V, class W> larcv::supera::MCParticleTree< T, U, V, W >::~MCParticleTree () inline
Default destructor.
Definition at line 50 of file Supera/larfmwk_shared/MCParticleTree.h.
 {}
Member Function Documentation
clear()
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::clear () inline
Definition at line 79 of file Supera/larfmwk_shared/MCParticleTree.h.
       {
     _roi_m.clear();
     for ( std::vector<MCPNode*>::iterator it=nodelist.begin(); it!=nodelist.end(); it++ ) {
       delete (*it);
       (*it) = NULL;
     }
     nodelist.clear();
     idx_primaries.clear();
     primaryids.clear();
     //idx_secondary2primary.clear();
       };
configure()
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::configure (const Config_t & cfg)
Referenced by larcv::SuperaMCROI::configure(), and larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::~MCParticleTree().
DefinePrimaries() [1/2]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::DefinePrimaries (const std::vector< U > & , const int time_offset)
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
DefinePrimaries() [2/2]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::DefinePrimaries (const std::vector< V > & , const int time_offset)
DefinePrimary() [1/2]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::DefinePrimary (const std::vector< T > &)
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
DefinePrimary() [2/2]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::DefinePrimary (const larcv::Vertex & vtx, const larcv::ROI & interaction)
GetCropper()
template<class T, class U, class V, class W> Cropper<U,V,W>& larcv::supera::MCParticleTree< T, U, V, W >::GetCropper () inline
Definition at line 54 of file Supera/larfmwk_shared/MCParticleTree.h.
 { return _cropper; }
GetNeutrinoROI()
template<class T, class U, class V, class W> std::vector<larcv::supera::InteractionROI_t> larcv::supera::MCParticleTree< T, U, V, W >::GetNeutrinoROI () const
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
GetPrimaryROI()
template<class T, class U, class V, class W> std::vector<larcv::supera::InteractionROI_t> larcv::supera::MCParticleTree< T, U, V, W >::GetPrimaryROI () const
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
RegisterSecondary() [1/5]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::RegisterSecondary (const std::vector< U > & , const int time_offset)
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
RegisterSecondary() [2/5]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::RegisterSecondary (const std::vector< U > & , const std::vector< W > & , const int time_offset)
RegisterSecondary() [3/5]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::RegisterSecondary (const std::vector< V > & , const int time_offset)
RegisterSecondary() [4/5]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::RegisterSecondary (const std::vector< V > & , const std::vector< W > & , const int time_offset)
RegisterSecondary() [5/5]
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::RegisterSecondary (const larcv::Vertex & vtx, const larcv::ROI & secondary)
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
UpdatePrimaryROI()
template<class T, class U, class V, class W> void larcv::supera::MCParticleTree< T, U, V, W >::UpdatePrimaryROI ()
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
Member Data Documentation
_cropper
template<class T, class U, class V, class W> Cropper<U,V,W> larcv::supera::MCParticleTree< T, U, V, W >::_cropper private
Definition at line 90 of file Supera/larfmwk_shared/MCParticleTree.h.
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::GetCropper().
_min_energy_deposit_mcshower
template<class T, class U, class V, class W> double larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_deposit_mcshower private
Definition at line 108 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_energy_deposit_mctrack
template<class T, class U, class V, class W> double larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_deposit_mctrack private
Definition at line 109 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_energy_deposit_pdg
template<class T, class U, class V, class W> std::map<int,double> larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_deposit_pdg private
Definition at line 105 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_energy_init_mcshower
template<class T, class U, class V, class W> double larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_init_mcshower private
Definition at line 106 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_energy_init_mctrack
template<class T, class U, class V, class W> double larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_init_mctrack private
Definition at line 107 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_energy_init_pdg
template<class T, class U, class V, class W> std::map<int,double> larcv::supera::MCParticleTree< T, U, V, W >::_min_energy_init_pdg private
Definition at line 104 of file Supera/larfmwk_shared/MCParticleTree.h.
_min_nplanes
template<class T, class U, class V, class W> size_t larcv::supera::MCParticleTree< T, U, V, W >::_min_nplanes private
Definition at line 110 of file Supera/larfmwk_shared/MCParticleTree.h.
_roi_m
template<class T, class U, class V, class W> std::map<larcv::Vertex,larcv::supera::InteractionROI_t> larcv::supera::MCParticleTree< T, U, V, W >::_roi_m private
Definition at line 95 of file Supera/larfmwk_shared/MCParticleTree.h.
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::clear().
idx_primaries
template<class T, class U, class V, class W> std::vector< int > larcv::supera::MCParticleTree< T, U, V, W >::idx_primaries private
Definition at line 99 of file Supera/larfmwk_shared/MCParticleTree.h.
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::clear().
idx_vertexmap
template<class T, class U, class V, class W> std::map<larcv::Vertex,int> larcv::supera::MCParticleTree< T, U, V, W >::idx_vertexmap private
Definition at line 101 of file Supera/larfmwk_shared/MCParticleTree.h.
nodelist
template<class T, class U, class V, class W> std::vector< MCPNode* > larcv::supera::MCParticleTree< T, U, V, W >::nodelist private
Definition at line 98 of file Supera/larfmwk_shared/MCParticleTree.h.
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::clear().
primaryids
template<class T, class U, class V, class W> std::map< int, MCPNode* > larcv::supera::MCParticleTree< T, U, V, W >::primaryids private
Definition at line 102 of file Supera/larfmwk_shared/MCParticleTree.h.
Referenced by larcv::supera::MCParticleTree< larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch >::clear().
The documentation for this class was generated from the following file:
Supera/larfmwk_shared/MCParticleTree.h