LArCV: larcv::LArbysImageProcessFactory Class Reference
larcv::LArbysImageProcessFactory Class Reference
#include <LArbysImage.h>
Public Member Functions
LArbysImageProcessFactory ()
ctor
~LArbysImageProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 132 of file LArbysImage.h.
Constructor & Destructor Documentation
LArbysImageProcessFactory()
larcv::LArbysImageProcessFactory::LArbysImageProcessFactory () inline
ctor
Definition at line 135 of file LArbysImage.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("LArbysImage",this); }
~LArbysImageProcessFactory()
larcv::LArbysImageProcessFactory::~LArbysImageProcessFactory () inline
dtor
Definition at line 137 of file LArbysImage.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::LArbysImageProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 139 of file LArbysImage.h.
References larcv::LArbysImage::LArbysImage().
 { return new LArbysImage(instance_name); }
The documentation for this class was generated from the following file:
LArbysImage.h