LArCV: larcv::CosmicROIFillerProcessFactory Class Reference
larcv::CosmicROIFillerProcessFactory Class Reference
#include <CosmicROIFiller.h>
Public Member Functions
CosmicROIFillerProcessFactory ()
ctor
~CosmicROIFillerProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 57 of file CosmicROIFiller.h.
Constructor & Destructor Documentation
CosmicROIFillerProcessFactory()
larcv::CosmicROIFillerProcessFactory::CosmicROIFillerProcessFactory () inline
ctor
Definition at line 60 of file CosmicROIFiller.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("CosmicROIFiller",this); }
~CosmicROIFillerProcessFactory()
larcv::CosmicROIFillerProcessFactory::~CosmicROIFillerProcessFactory () inline
dtor
Definition at line 62 of file CosmicROIFiller.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::CosmicROIFillerProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 64 of file CosmicROIFiller.h.
References larcv::CosmicROIFiller::CosmicROIFiller().
 { return new CosmicROIFiller(instance_name); }
The documentation for this class was generated from the following file:
CosmicROIFiller.h