LArCV: larcv::MCSingleParticleFilter Class Reference
larcv::MCSingleParticleFilter Class Reference
#include <MCSingleParticleFilter.h>
Public Member Functions
MCSingleParticleFilter (const std::string name="MCSingleParticleFilter")
Default constructor.
~MCSingleParticleFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _roi_producer
double _shower_min_energy
double _track_min_energy
double _proton_min_energy
Detailed Description
Definition at line 26 of file MCSingleParticleFilter.h.
Constructor & Destructor Documentation
MCSingleParticleFilter()
larcv::MCSingleParticleFilter::MCSingleParticleFilter (const std::string name = "MCSingleParticleFilter")
Default constructor.
Definition at line 10 of file MCSingleParticleFilter.cxx.
Referenced by larcv::MCSingleParticleFilterProcessFactory::create().
     : ProcessBase(name)
   {}
~MCSingleParticleFilter()
larcv::MCSingleParticleFilter::~MCSingleParticleFilter () inline
Default destructor.
Definition at line 34 of file MCSingleParticleFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::MCSingleParticleFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 14 of file MCSingleParticleFilter.cxx.
References _proton_min_energy, _roi_producer, _shower_min_energy, _track_min_energy, and larcv::PSet::get().
Referenced by ~MCSingleParticleFilter().
   {
     _roi_producer = cfg.get<std::string>("ROIProducer");
     _shower_min_energy = cfg.get<double>("ShowerMinEnergy");
     _track_min_energy = cfg.get<double>("TrackMinEnergy");
     _proton_min_energy = cfg.get<double>("ProtonMinEnergy");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::MCSingleParticleFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 59 of file MCSingleParticleFilter.cxx.
Referenced by ~MCSingleParticleFilter().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::MCSingleParticleFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 22 of file MCSingleParticleFilter.cxx.
Referenced by ~MCSingleParticleFilter().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::MCSingleParticleFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 25 of file MCSingleParticleFilter.cxx.
References _proton_min_energy, _roi_producer, _shower_min_energy, _track_min_energy, larcv::IOManager< T >::get_data(), larcv::kINVALID_USHORT, larcv::kProductROI, larcv::kShapeTrack, and LARCV_INFO.
Referenced by ~MCSingleParticleFilter().
   {
     auto ev_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_producer));
     size_t part_ctr = 0;
     for(auto const& roi : ev_roi->ROIArray()) {
       if(roi.MCSTIndex() == kINVALID_USHORT) continue;
       if( (roi.PdgCode() == 11 || roi.PdgCode() == -11 || roi.PdgCode() == 22 || roi.PdgCode() == 111) &&
       roi.EnergyDeposit() < _shower_min_energy) {
     LARCV_INFO() << "Ignoring Shower (PdgCode=" << roi.PdgCode() << ") with energy " << roi.EnergyDeposit() << std::endl;
     continue;
       }
       if(roi.PdgCode() == 2212 && roi.EnergyDeposit() < _proton_min_energy) {
     LARCV_INFO() << "Ignoring Proton with energy " << roi.EnergyDeposit() << std::endl;
     continue;
       }else if(roi.Shape() == kShapeTrack && roi.EnergyDeposit() < _track_min_energy) {
     LARCV_INFO() << "Ignoring TRACK (PdgCode=" << roi.PdgCode() << ") with energy " << roi.EnergyDeposit() << std::endl;
     continue;
       }
       LARCV_INFO() << "Counting particle (PdgCode=" << roi.PdgCode() << ") with energy " << roi.EnergyDeposit() << std::endl;
       ++part_ctr;
     }
     return (part_ctr == 1);
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_proton_min_energy
double larcv::MCSingleParticleFilter::_proton_min_energy private
Definition at line 49 of file MCSingleParticleFilter.h.
Referenced by configure(), and process().
_roi_producer
std::string larcv::MCSingleParticleFilter::_roi_producer private
Definition at line 46 of file MCSingleParticleFilter.h.
Referenced by configure(), and process().
_shower_min_energy
double larcv::MCSingleParticleFilter::_shower_min_energy private
Definition at line 47 of file MCSingleParticleFilter.h.
Referenced by configure(), and process().
_track_min_energy
double larcv::MCSingleParticleFilter::_track_min_energy private
Definition at line 48 of file MCSingleParticleFilter.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
MCSingleParticleFilter.h
MCSingleParticleFilter.cxx