LArCV: larcv::CosmicTrackAna Class Reference
larcv::CosmicTrackAna Class Reference
#include <CosmicTrackAna.h>
Public Member Functions
CosmicTrackAna (const std::string name="CosmicTrackAna")
Default constructor.
~CosmicTrackAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void clear ()
Private Attributes
std::string _croi_prod
std::string _thrumu_px_prod
std::string _stopmu_px_prod
std::string _top_px_prod
std::string _bot_px_prod
std::string _up_px_prod
std::string _down_px_prod
std::string _anode_px_prod
std::string _cathode_px_prod
TTree * _tree
int _run
int _subrun
int _event
int _entry
int _n_croi
int _n_thru_mu_trk
int _n_thru_mu_pix_p0
int _n_thru_mu_pix_p1
int _n_thru_mu_pix_p2
float _avg_thru_mu_pix
int _n_stop_mu_trk
int _n_stop_mu_pix_p0
int _n_stop_mu_pix_p1
int _n_stop_mu_pix_p2
float _avg_stop_mu_pix
int _n_top_pts
int _n_bot_pts
int _n_up_pts
int _n_down_pts
int _n_anode_pts
int _n_cathode_pts
Detailed Description
Definition at line 26 of file CosmicTrackAna.h.
Constructor & Destructor Documentation
CosmicTrackAna()
larcv::CosmicTrackAna::CosmicTrackAna (const std::string name = "CosmicTrackAna")
Default constructor.
Definition at line 13 of file CosmicTrackAna.cxx.
Referenced by larcv::CosmicTrackAnaProcessFactory::create().
     : ProcessBase(name), _tree(nullptr)
   {}
~CosmicTrackAna()
larcv::CosmicTrackAna::~CosmicTrackAna () inline
Default destructor.
Definition at line 34 of file CosmicTrackAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
clear()
void larcv::CosmicTrackAna::clear () private
Definition at line 223 of file CosmicTrackAna.cxx.
References _avg_stop_mu_pix, _avg_thru_mu_pix, _entry, _event, _n_anode_pts, _n_bot_pts, _n_cathode_pts, _n_croi, _n_down_pts, _n_stop_mu_pix_p0, _n_stop_mu_pix_p1, _n_stop_mu_pix_p2, _n_stop_mu_trk, _n_thru_mu_pix_p0, _n_thru_mu_pix_p1, _n_thru_mu_pix_p2, _n_thru_mu_trk, _n_top_pts, _n_up_pts, _run, _subrun, and larcv::kINVALID_INT.
Referenced by process().
{
     _run=-1.0*kINVALID_INT;
     _subrun=-1.0*kINVALID_INT;
     _event=-1.0*kINVALID_INT;
     _entry=-1.0*kINVALID_INT;
     _n_thru_mu_trk=-1.0*kINVALID_INT;
     _n_thru_mu_pix_p0=-1.0*kINVALID_INT;
     _n_thru_mu_pix_p1=-1.0*kINVALID_INT;
     _n_thru_mu_pix_p2=-1.0*kINVALID_INT;
     _avg_thru_mu_pix=-1.0*kINVALID_INT;
     _n_stop_mu_trk=-1.0*kINVALID_INT;
     _n_stop_mu_pix_p0=-1.0*kINVALID_INT;
     _n_stop_mu_pix_p1=-1.0*kINVALID_INT;
     _n_stop_mu_pix_p2=-1.0*kINVALID_INT;
     _avg_stop_mu_pix=-1.0*kINVALID_INT;
     _n_top_pts=-1.0*kINVALID_INT;
     _n_bot_pts=-1.0*kINVALID_INT;
     _n_up_pts=-1.0*kINVALID_INT;
     _n_down_pts=-1.0*kINVALID_INT;
     _n_anode_pts=-1.0*kINVALID_INT;
     _n_cathode_pts=-1.0*kINVALID_INT;
     _n_croi=-1.0*kINVALID_INT;
   }
configure()
void larcv::CosmicTrackAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 17 of file CosmicTrackAna.cxx.
References _anode_px_prod, _bot_px_prod, _cathode_px_prod, _croi_prod, _down_px_prod, _stopmu_px_prod, _thrumu_px_prod, _top_px_prod, _up_px_prod, and larcv::PSet::get().
Referenced by ~CosmicTrackAna().
   {
     //
     // cROI Producer
     //
     _croi_prod = cfg.get<std::string>("ROIProducer");
     //
     // ThruMu and StopMu producers (Pixel2D)
     //
     _thrumu_px_prod = cfg.get<std::string>("ThruMuProducer");
     _stopmu_px_prod = cfg.get<std::string>("StopMuProducer");
     //
     // End points producers (Pixel2D)
     //
     _top_px_prod = cfg.get<std::string>("TopPxProducer");
     _bot_px_prod = cfg.get<std::string>("BotPxProducer");
     _up_px_prod   = cfg.get<std::string>("UpPxProducer");
     _down_px_prod = cfg.get<std::string>("DownPxProducer");
     _anode_px_prod   = cfg.get<std::string>("AnodePxProducer");
     _cathode_px_prod = cfg.get<std::string>("CathodePxProducer");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::CosmicTrackAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 220 of file CosmicTrackAna.cxx.
References _tree.
Referenced by ~CosmicTrackAna().
   { _tree->Write(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::CosmicTrackAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 44 of file CosmicTrackAna.cxx.
References _avg_stop_mu_pix, _avg_thru_mu_pix, _entry, _event, _n_anode_pts, _n_bot_pts, _n_cathode_pts, _n_croi, _n_down_pts, _n_stop_mu_pix_p0, _n_stop_mu_pix_p1, _n_stop_mu_pix_p2, _n_stop_mu_trk, _n_thru_mu_pix_p0, _n_thru_mu_pix_p1, _n_thru_mu_pix_p2, _n_thru_mu_trk, _n_top_pts, _n_up_pts, _run, _subrun, and _tree.
Referenced by ~CosmicTrackAna().
   {
     //
     // RSE
     //
     _tree = new TTree("EventCosmicTrackTree","");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("n_croi", &_n_croi,"n_croi/I");
     //
     // ThruMu & StopMu
     //
     _tree->Branch("n_thru_mu_trk", &_n_thru_mu_trk,"n_thru_mu_trk/I");
     _tree->Branch("n_thru_mu_pix_p0", &_n_thru_mu_pix_p0,"n_thru_mu_pix_p0/I");
     _tree->Branch("n_thru_mu_pix_p1", &_n_thru_mu_pix_p1,"n_thru_mu_pix_p1/I");
     _tree->Branch("n_thru_mu_pix_p2", &_n_thru_mu_pix_p2,"n_thru_mu_pix_p2/I");
     _tree->Branch("avg_thru_mu_pix",  &_avg_thru_mu_pix,"avg_thru_mu_pix/F");
     _tree->Branch("n_stop_mu_trk",    &_n_stop_mu_trk,"n_stop_mu_trk/I");
     _tree->Branch("n_stop_mu_pix_p0", &_n_stop_mu_pix_p0,"n_stop_mu_pix_p0/I");
     _tree->Branch("n_stop_mu_pix_p1", &_n_stop_mu_pix_p1,"n_stop_mu_pix_p1/I");
     _tree->Branch("n_stop_mu_pix_p2", &_n_stop_mu_pix_p2,"n_stop_mu_pix_p2/I");
     _tree->Branch("avg_stop_mu_pix",  &_avg_stop_mu_pix,"avg_stop_mu_pix/F");
     //
     // End points
     //
     _tree->Branch("n_top_pts", &_n_top_pts , "n_top_pts/I");
     _tree->Branch("n_bot_pts", &_n_bot_pts , "n_bot_pts/I");
     _tree->Branch("n_up_pts"  , &_n_up_pts   , "n_up_pts/I");
     _tree->Branch("n_down_pts", &_n_down_pts , "n_down_pts/I");
     _tree->Branch("n_anode_pts"  , &_n_anode_pts   , "n_anode_pts/I");
     _tree->Branch("n_cathode_pts", &_n_cathode_pts , "n_cathode_pts/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::CosmicTrackAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 87 of file CosmicTrackAna.cxx.
References _anode_px_prod, _avg_stop_mu_pix, _avg_thru_mu_pix, _bot_px_prod, _cathode_px_prod, _croi_prod, _down_px_prod, _entry, _event, _n_anode_pts, _n_bot_pts, _n_cathode_pts, _n_croi, _n_down_pts, _n_stop_mu_pix_p0, _n_stop_mu_pix_p1, _n_stop_mu_pix_p2, _n_stop_mu_trk, _n_thru_mu_pix_p0, _n_thru_mu_pix_p1, _n_thru_mu_pix_p2, _n_thru_mu_trk, _n_top_pts, _n_up_pts, _run, _stopmu_px_prod, _subrun, _thrumu_px_prod, _top_px_prod, _tree, _up_px_prod, clear(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductPixel2D, larcv::kProductROI, and LARCV_DEBUG.
Referenced by ~CosmicTrackAna().
   {
     LARCV_DEBUG() << "start" << std::endl;
     clear();
     auto const ev_croi = (EventROI*)(mgr.get_data(kProductROI,_croi_prod));
     if(!ev_croi) throw larbys("Invalid cROI producer specified!");
     auto const ev_thrumu = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_thrumu_px_prod));
     if (!ev_thrumu) throw larbys("Invalid ThruMu producer provided!");
     auto const ev_stopmu = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_stopmu_px_prod));
     if (!ev_stopmu) throw larbys("Invalid StopMu producer provided!");
     auto const ev_top_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_top_px_prod));
     if (!ev_top_pts) throw larbys("Invalid top_pts producer provided!");
     auto const ev_bot_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_bot_px_prod));
     if (!ev_bot_pts) throw larbys("Invalid bot_pts producer provided!");
     auto const ev_up_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_up_px_prod));
     if (!ev_up_pts) throw larbys("Invalid up_pts producer provided!");
     auto const ev_down_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_down_px_prod));
     if (!ev_down_pts) throw larbys("Invalid down_pts producer provided!");
     auto const ev_cathode_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_cathode_px_prod));
     if (!ev_cathode_pts) throw larbys("Invalid cathode_pts producer provided!");
     auto const ev_anode_pts = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_anode_px_prod));
     if (!ev_anode_pts) throw larbys("Invalid anode_pts producer provided!");
     _run    = (int) ev_thrumu->run();
     _subrun = (int) ev_thrumu->subrun();
     _event  = (int) ev_thrumu->event();
     _entry  = (int) mgr.current_entry();
     //
     // Store the number of cROI
     //
     _n_croi =(int)ev_croi->ROIArray().size();
     //
     // Count the number of points @ each side
     //
     _n_top_pts     = 0;
     _n_bot_pts     = 0;
     _n_up_pts      = 0;
     _n_down_pts    = 0;
     _n_anode_pts   = 0;
     _n_cathode_pts = 0;
     if(!ev_top_pts->Pixel2DArray().empty())
       _n_top_pts     = (int) ev_top_pts->Pixel2DArray(0).size();
     if(!ev_bot_pts->Pixel2DArray().empty())
       _n_bot_pts     = (int) ev_bot_pts->Pixel2DArray(0).size();
     if(!ev_up_pts->Pixel2DArray().empty())
       _n_up_pts      = (int) ev_up_pts->Pixel2DArray(0).size();
     if(!ev_down_pts->Pixel2DArray().empty())
       _n_down_pts    = (int) ev_down_pts->Pixel2DArray(0).size();
     if(!ev_anode_pts->Pixel2DArray().empty())
       _n_anode_pts   = (int) ev_anode_pts->Pixel2DArray(0).size();
     if (!ev_cathode_pts->Pixel2DArray().empty())
       _n_cathode_pts = (int) ev_cathode_pts->Pixel2DArray(0).size();
     //
     // Count the number of stopmu
     //
     _avg_thru_mu_pix   = 0.0;
     _avg_stop_mu_pix = 0.0;
     for(size_t plane=0; plane<3; ++plane) {
       const auto& thrumu_v = ev_thrumu->Pixel2DClusterArray(plane);
       const auto& stopmu_v = ev_stopmu->Pixel2DClusterArray(plane);
       if (plane==0) {
     _n_thru_mu_trk = (int)thrumu_v.size();
     _n_stop_mu_trk = (int)stopmu_v.size();
     _n_thru_mu_pix_p0 = 0;
     for(const auto& v : thrumu_v) _n_thru_mu_pix_p0 += (int)v.size();
     _n_stop_mu_pix_p0 = 0;
     for(const auto& v : stopmu_v) _n_stop_mu_pix_p0 += (int)v.size();
     _avg_thru_mu_pix  += _n_thru_mu_pix_p0;
     _avg_stop_mu_pix  += _n_stop_mu_pix_p0;
       }
       if (plane==1) {
     _n_thru_mu_pix_p1 = 0;
     for(const auto& v : thrumu_v) _n_thru_mu_pix_p1 += (int)v.size();
     _n_stop_mu_pix_p1 = 0;
     for(const auto& v : stopmu_v) _n_stop_mu_pix_p1 += (int)v.size();
     _avg_thru_mu_pix  += _n_thru_mu_pix_p1;
     _avg_stop_mu_pix  += _n_stop_mu_pix_p1;
       }
       if (plane==1) {
     _n_thru_mu_pix_p2 = 0;
     for(const auto& v : thrumu_v) _n_thru_mu_pix_p2 += (int)v.size();
     _n_stop_mu_pix_p2 = 0;
     for(const auto& v : stopmu_v) _n_stop_mu_pix_p2 += (int)v.size();
     _avg_thru_mu_pix  += _n_thru_mu_pix_p2;
     _avg_stop_mu_pix  += _n_stop_mu_pix_p2;
       }
     }
     _avg_thru_mu_pix /= 3.0;
     _avg_stop_mu_pix /= 3.0;
     _tree->Fill();
     LARCV_DEBUG() << "end" << std::endl;
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_anode_px_prod
std::string larcv::CosmicTrackAna::_anode_px_prod private
Definition at line 54 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_avg_stop_mu_pix
float larcv::CosmicTrackAna::_avg_stop_mu_pix private
Definition at line 76 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_avg_thru_mu_pix
float larcv::CosmicTrackAna::_avg_thru_mu_pix private
Definition at line 70 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_bot_px_prod
std::string larcv::CosmicTrackAna::_bot_px_prod private
Definition at line 51 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_cathode_px_prod
std::string larcv::CosmicTrackAna::_cathode_px_prod private
Definition at line 55 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_croi_prod
std::string larcv::CosmicTrackAna::_croi_prod private
Definition at line 47 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_down_px_prod
std::string larcv::CosmicTrackAna::_down_px_prod private
Definition at line 53 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_entry
int larcv::CosmicTrackAna::_entry private
Definition at line 62 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_event
int larcv::CosmicTrackAna::_event private
Definition at line 61 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_anode_pts
int larcv::CosmicTrackAna::_n_anode_pts private
Definition at line 82 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_bot_pts
int larcv::CosmicTrackAna::_n_bot_pts private
Definition at line 79 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_cathode_pts
int larcv::CosmicTrackAna::_n_cathode_pts private
Definition at line 83 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_croi
int larcv::CosmicTrackAna::_n_croi private
Definition at line 64 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_down_pts
int larcv::CosmicTrackAna::_n_down_pts private
Definition at line 81 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_stop_mu_pix_p0
int larcv::CosmicTrackAna::_n_stop_mu_pix_p0 private
Definition at line 73 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_stop_mu_pix_p1
int larcv::CosmicTrackAna::_n_stop_mu_pix_p1 private
Definition at line 74 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_stop_mu_pix_p2
int larcv::CosmicTrackAna::_n_stop_mu_pix_p2 private
Definition at line 75 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_stop_mu_trk
int larcv::CosmicTrackAna::_n_stop_mu_trk private
Definition at line 72 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_thru_mu_pix_p0
int larcv::CosmicTrackAna::_n_thru_mu_pix_p0 private
Definition at line 67 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_thru_mu_pix_p1
int larcv::CosmicTrackAna::_n_thru_mu_pix_p1 private
Definition at line 68 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_thru_mu_pix_p2
int larcv::CosmicTrackAna::_n_thru_mu_pix_p2 private
Definition at line 69 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_thru_mu_trk
int larcv::CosmicTrackAna::_n_thru_mu_trk private
Definition at line 66 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_top_pts
int larcv::CosmicTrackAna::_n_top_pts private
Definition at line 78 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_n_up_pts
int larcv::CosmicTrackAna::_n_up_pts private
Definition at line 80 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_run
int larcv::CosmicTrackAna::_run private
Definition at line 59 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_stopmu_px_prod
std::string larcv::CosmicTrackAna::_stopmu_px_prod private
Definition at line 49 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_subrun
int larcv::CosmicTrackAna::_subrun private
Definition at line 60 of file CosmicTrackAna.h.
Referenced by clear(), initialize(), and process().
_thrumu_px_prod
std::string larcv::CosmicTrackAna::_thrumu_px_prod private
Definition at line 48 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_top_px_prod
std::string larcv::CosmicTrackAna::_top_px_prod private
Definition at line 50 of file CosmicTrackAna.h.
Referenced by configure(), and process().
_tree
TTree* larcv::CosmicTrackAna::_tree private
Definition at line 57 of file CosmicTrackAna.h.
Referenced by finalize(), initialize(), and process().
_up_px_prod
std::string larcv::CosmicTrackAna::_up_px_prod private
Definition at line 52 of file CosmicTrackAna.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
CosmicTrackAna.h
CosmicTrackAna.cxx