LArCV: larcv::ChStatusConverterProcessFactory Class Reference
larcv::ChStatusConverterProcessFactory Class Reference
#include <ChStatusConverter.h>
Public Member Functions
ChStatusConverterProcessFactory ()
ctor
~ChStatusConverterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 54 of file ChStatusConverter.h.
Constructor & Destructor Documentation
ChStatusConverterProcessFactory()
larcv::ChStatusConverterProcessFactory::ChStatusConverterProcessFactory () inline
ctor
Definition at line 57 of file ChStatusConverter.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ChStatusConverter",this); }
~ChStatusConverterProcessFactory()
larcv::ChStatusConverterProcessFactory::~ChStatusConverterProcessFactory () inline
dtor
Definition at line 59 of file ChStatusConverter.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ChStatusConverterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 61 of file ChStatusConverter.h.
References larcv::ChStatusConverter::ChStatusConverter().
 { return new ChStatusConverter(instance_name); }
The documentation for this class was generated from the following file:
ChStatusConverter.h