LArCV: larcv::logger Class Reference
larcv::logger Class Reference
Utility class used to show formatted message on the screen.
#include <larcv_logger.h>
Public Member Functions
logger (const std::string &name="no_name")
Default constructor.
virtual ~logger ()
Default destructor.
const std::string & name () const
Logger's name.
void set (const msg::Level_t level)
Verbosity level setter.
msg::Level_t level () const
Verbosity level getter.
bool operator< (const logger &rhs) const
Comparison operator for static collection of loggers.
bool debug () const
bool info () const
bool normal () const
bool warning () const
bool error () const
std::ostream & send (const msg::Level_t) const
Formatted message (simplest)
std::ostream & send (const msg::Level_t level, const std::string &function) const
Formatted message (function name included)
std::ostream & send (const msg::Level_t level, const std::string &function, const unsigned int line_num) const
Formatted message (function name + line number)
std::ostream & send (const msg::Level_t level, const std::string &function, const unsigned int line_num, const std::string &file_name) const
Formatted message (function name + line number + file name)
Static Public Member Functions
static logger & get (const std::string name)
Getter of a message instance.
static logger & get_shared ()
static msg::Level_t default_level ()
Default logger level getter.
static void default_level (msg::Level_t l)
Default logger level setter (only affect future loggers)
static void force_level (msg::Level_t l)
Force all loggers to change level.
Private Attributes
std::ostream * _ostrm
ostream
msg::Level_t _level
Level.
std::string _name
Name.
Static Private Attributes
static std::map< std::string, larcv::logger > * _logger_m = nullptr
Set of loggers.
static larcv::logger * _shared_logger = nullptr
Shared logger.
static msg::Level_t _level_default = msg::kNORMAL
Default logger level.
Detailed Description
Utility class used to show formatted message on the screen.
A logger class for larcv. Simply shows a formatted colored message on a screen.
A static getter method is provided to create a sharable logger instance (see larcv_base for useage).
Definition at line 31 of file larcv_logger.h.
Constructor & Destructor Documentation
logger()
larcv::logger::logger (const std::string & name = "no_name") inline
Default constructor.
Definition at line 36 of file larcv_logger.h.
Referenced by get(), and get_shared().
       : _ostrm(&std::cout)
       , _name(name)
     {}
~logger()
virtual larcv::logger::~logger () inline virtual
Default destructor.
Definition at line 42 of file larcv_logger.h.
References _ostrm.
 {};
Member Function Documentation
debug()
bool larcv::logger::debug () const inline
Definition at line 111 of file larcv_logger.h.
References larcv::msg::kDEBUG.
 { return _level <= msg::kDEBUG;   }
default_level() [1/2]
static msg::Level_t larcv::logger::default_level () inline static
Default logger level getter.
Definition at line 98 of file larcv_logger.h.
References _level_default.
Referenced by force_level().
 { return _level_default; }
default_level() [2/2]
static void larcv::logger::default_level (msg::Level_t l) inline static
Default logger level setter (only affect future loggers)
Definition at line 100 of file larcv_logger.h.
 { _level_default = l; }
error()
bool larcv::logger::error () const inline
Definition at line 115 of file larcv_logger.h.
References file_name, larcv::msg::kERROR, level(), and send().
 { return _level <= msg::kERROR;   }
force_level()
static void larcv::logger::force_level (msg::Level_t l) inline static
Force all loggers to change level.
Definition at line 102 of file larcv_logger.h.
References default_level().
     {
       default_level(l);
       for(auto& name_logger : *_logger_m) name_logger.second.set(l);
     }
get()
static logger& larcv::logger::get (const std::string name) inline static
Getter of a message instance.
Definition at line 84 of file larcv_logger.h.
References get_shared(), larcv::msg::kNORMAL, logger(), and name().
Referenced by larcv::as_image2d(), larcv::as_image2d_meta(), larcv::EventPixel2D::ClusterMeta(), larcv::EventPixel2D::ClusterMetaArray(), larcv::larcv_base::larcv_base(), larcv::EventPixel2D::Meta(), larcv::EventPixel2D::Pixel2DArray(), and larcv::EventPixel2D::Pixel2DClusterArray().
     {
       if(!_logger_m) _logger_m = new std::map<std::string,larcv::logger>();
       auto iter = _logger_m->find(name);
       if(iter == _logger_m->end()) {
         iter = _logger_m->emplace(name,logger(name)).first;
         iter->second.set(msg::kNORMAL);
       }
       return iter->second;
     };
get_shared()
logger & larcv::logger::get_shared () static
Definition at line 48 of file larcv_logger.cxx.
References _shared_logger, and logger().
Referenced by larcv::ProcessDriver::configure(), and get().
   {
     if(!_shared_logger) _shared_logger = new logger("GLOBAL");
     return *_shared_logger;
   }
info()
bool larcv::logger::info () const inline
Definition at line 112 of file larcv_logger.h.
References larcv::msg::kINFO.
 { return _level <= msg::kINFO;    }
level()
msg::Level_t larcv::logger::level () const inline
Verbosity level getter.
Definition at line 73 of file larcv_logger.h.
References _level.
Referenced by error(), send(), set(), and larcv::ThreadDatumFiller::set_next_batch().
 { return _level; }
name()
const std::string& larcv::logger::name () const inline
Logger's name.
Definition at line 67 of file larcv_logger.h.
References _name.
Referenced by get(), larcv::larcv_base::name(), and operator<().
 { return _name; }
normal()
bool larcv::logger::normal () const inline
Definition at line 113 of file larcv_logger.h.
References larcv::msg::kNORMAL.
 { return _level <= msg::kNORMAL;  }
operator<()
bool larcv::logger::operator< (const logger & rhs) const inline
Comparison operator for static collection of loggers.
Definition at line 76 of file larcv_logger.h.
References name().
     {
       if(_name < rhs.name()) return true;
       if(_name > rhs.name()) return false;
       return false;
     }
send() [1/4]
std::ostream & larcv::logger::send (const msg::Level_t level) const
Formatted message (simplest)
Definition at line 13 of file larcv_logger.cxx.
References _ostrm, larcv::msg::kStringPrefix, and level().
Referenced by larcv::as_image2d(), larcv::as_image2d_meta(), larcv::EventPixel2D::ClusterMeta(), larcv::EventPixel2D::ClusterMetaArray(), error(), larcv::EventPixel2D::Meta(), larcv::EventPixel2D::Pixel2DArray(), larcv::EventPixel2D::Pixel2DClusterArray(), and send().
   {
     (*_ostrm)  << msg::kStringPrefix[level].c_str()
            << "\033[0m ";
     return (*_ostrm);
   }
send() [2/4]
std::ostream & larcv::logger::send (const msg::Level_t level, const std::string & function) const
Formatted message (function name included)
Definition at line 20 of file larcv_logger.cxx.
References _name, and send().
   {
     auto& strm(send(level));
     strm << "\033[94m<" << _name << "::" << function.c_str() << ">\033[00m ";
     return strm;
   }
send() [3/4]
std::ostream & larcv::logger::send (const msg::Level_t level, const std::string & function, const unsigned int line_num) const
Formatted message (function name + line number)
Definition at line 28 of file larcv_logger.cxx.
References _name, and send().
   {
     auto& strm(send(level));
     strm << "\033[94m<" << _name << "::" << function.c_str() << "::L" << line_num << ">\033[00m ";
     return strm;
   }
send() [4/4]
std::ostream & larcv::logger::send (const msg::Level_t level, const std::string & function, const unsigned int line_num, const std::string & file_name) const
Formatted message (function name + line number + file name)
Definition at line 37 of file larcv_logger.cxx.
References send().
   {
     auto& strm(send(level,function));
     // FIXME temporary operation to fetch file name from full path
     strm << file_name.substr(file_name.rfind("/")+1,file_name.size()).c_str() << "::L" << line_num << " ";
     return strm;
   }
set()
void larcv::logger::set (const msg::Level_t level) inline
Verbosity level setter.
Definition at line 70 of file larcv_logger.h.
References level().
Referenced by larcv::ProcessDriver::configure(), set_verbosity(), larcv::larcv_base::set_verbosity(), and larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_verbosity().
 { _level = level; }
warning()
bool larcv::logger::warning () const inline
Definition at line 114 of file larcv_logger.h.
References larcv::msg::kWARNING.
 { return _level <= msg::kWARNING; }
Member Data Documentation
_level
msg::Level_t larcv::logger::_level private
Level.
Definition at line 50 of file larcv_logger.h.
Referenced by level().
_level_default
msg::Level_t larcv::logger::_level_default = msg::kNORMAL static private
Default logger level.
Definition at line 62 of file larcv_logger.h.
Referenced by default_level().
_logger_m
std::map< std::string, logger > * larcv::logger::_logger_m = nullptr static private
Set of loggers.
Definition at line 56 of file larcv_logger.h.
_name
std::string larcv::logger::_name private
Name.
Definition at line 53 of file larcv_logger.h.
Referenced by name(), and send().
_ostrm
std::ostream* larcv::logger::_ostrm private
ostream
Definition at line 42 of file larcv_logger.h.
Referenced by send(), and ~logger().
_shared_logger
logger * larcv::logger::_shared_logger = nullptr static private
Shared logger.
Definition at line 59 of file larcv_logger.h.
Referenced by get_shared().
The documentation for this class was generated from the following files:
larcv_logger.h
larcv_logger.cxx