LArCV: larcv::ADCScale Class Reference
larcv::ADCScale Class Reference
#include <ADCScale.h>
Public Member Functions
ADCScale (const std::string name="ADCScale")
Default constructor.
~ADCScale ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _image_producer
ProducerID_t _image_id
std::vector< double > _gaus_mean_v
std::vector< double > _gaus_sigma_v
std::vector< size_t > _gaus_pool_size_v
bool _per_pixel
std::vector< larcv::RandomGaus > _randg_v
Detailed Description
Definition at line 28 of file ADCScale.h.
Constructor & Destructor Documentation
ADCScale()
larcv::ADCScale::ADCScale (const std::string name = "ADCScale")
Default constructor.
Definition at line 11 of file ADCScale.cxx.
Referenced by larcv::ADCScaleProcessFactory::create().
     : ProcessBase(name)
   {}
~ADCScale()
larcv::ADCScale::~ADCScale () inline
Default destructor.
Definition at line 36 of file ADCScale.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ADCScale::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file ADCScale.cxx.
References _gaus_mean_v, _gaus_sigma_v, _image_producer, _per_pixel, larcv::PSet::get(), LARCV_CRITICAL, and true.
Referenced by ~ADCScale().
   {
     _image_producer = cfg.get<std::string>         ( "ImageProducer" );
     _gaus_mean_v    = cfg.get<std::vector<double> >( "ADCScaleMean"  );
     _gaus_sigma_v   = cfg.get<std::vector<double> >( "ADCScaleSigma" );
     _per_pixel      = cfg.get<bool>( "PixelWise", true );
     if(_gaus_mean_v.size() != _gaus_sigma_v.size()) {
       LARCV_CRITICAL() << "ADCScale Mean & Sigma must be of same length!" << std::endl;
       throw larbys();
     }
     /*
     // Threaded gaussian commented out (too big pool size)
     _gaus_pool_size_v.clear();
     _gaus_pool_size_v.resize(3,9600*3456);
     _gaus_pool_size_v  = cfg.get<std::vector<size_t> >( "RandomPoolSize", _gaus_pool_size_v);
     if(_gaus_mean_v.size() != _gaus_pool_size_v.size()) {
       LARCV_CRITICAL() << "ADCScale Mean/Sigma and pool size must be of same length!" << std::endl;
       throw larbys();
     }
     _randg_v.clear();
     for(size_t i=0; i<_gaus_mean_v.size(); ++i)
       _randg_v.emplace_back(_gaus_mean_v[i], _gaus_sigma_v[i], _gaus_pool_size_v[i]);
     */
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ADCScale::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 146 of file ADCScale.cxx.
Referenced by ~ADCScale().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ADCScale::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 44 of file ADCScale.cxx.
References _image_id, and larcv::kINVALID_SIZE.
Referenced by ~ADCScale().
   {
     _image_id = kINVALID_SIZE;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ADCScale::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 49 of file ADCScale.cxx.
References _gaus_mean_v, _gaus_sigma_v, _image_id, _image_producer, _per_pixel, larcv::IOManager< T >::get_data(), larcv::kINVALID_SIZE, larcv::kProductImage2D, LARCV_INFO, LARCV_WARNING, and larcv::IOManager< T >::producer_id().
Referenced by ~ADCScale().
   {
     if(_image_id == kINVALID_SIZE)
       _image_id = mgr.producer_id(kProductImage2D,_image_producer);
     // Smear ADCs if random gaussian is provided
     if(!_gaus_mean_v.empty()) {
       auto event_image = (EventImage2D*)(mgr.get_data(_image_id));
       std::vector<larcv::Image2D> tpc_image_v;
       event_image->Move(tpc_image_v);
       for(size_t i=0; i<tpc_image_v.size(); ++i) {
     std::random_device rd;
     std::mt19937 gen(rd());
     std::normal_distribution<> d(_gaus_mean_v[i],_gaus_sigma_v[i]);
     //auto& randg = _randg_v[i];
     auto& tpc_image = tpc_image_v[i];
     // Throw warning: @ this code it "should be" index = plane id
     if(tpc_image.meta().plane() != i)
       LARCV_WARNING() << "Image index != plane ID is detected... " << std::endl;
     if(_per_pixel) {
       auto const& img_vec = tpc_image.as_vector();
       for(size_t i=0; i<img_vec.size(); ++i) {
         if(img_vec[i] < 1.) continue;
         float factor = d(gen);
         size_t col = i / tpc_image.meta().rows();
         size_t row = i - col * tpc_image.meta().rows();
         tpc_image.set_pixel(row,col,img_vec[i] * factor);
       }
     }else{
       float factor = d(gen);
       LARCV_INFO() << "Applying scaling factor " << factor << " to image " << i << std::endl;
       /*
       float min=1e9;
       float max=0;
       for(auto const& v : tpc_image.as_vector()) { if(v<min) min = v; if (v>max) max = v; }
       LARCV_INFO() << "BEFORE: min = " << min << " ... max = " << max << std::endl;
       */
       tpc_image *= factor;
       /*
       min = 1e9;
       max = 0;
       for(auto const& v : tpc_image.as_vector()) { if(v<min) min = v; if (v>max) max = v; }
       LARCV_INFO() << "AFTER: min = " << min << " ... max = " << max << std::endl;
       */
     }
       }
       event_image->Emplace(std::move(tpc_image_v));
     }
     /*
     // Thread method commented out... too much memory for pool!
     if(!_randg_v.empty()) {
       auto event_image = (EventImage2D*)(mgr.get_data(id));
       std::vector<larcv::Image2D> tpc_image_v;
       event_image->Move(tpc_image_v);
       // Make sure enough generators exist (# images)
       if(tpc_image_v.size() < _randg_v.size()) {
     LARCV_CRITICAL() << "# images > # of gaussian generator... check config!" << std::endl;
     throw larbys();
       }
       // Loop over images
       for(size_t i=0; i<tpc_image_v.size(); ++i) {
     //auto& randg = _randg_v[i];
     auto& tpc_image = tpc_image_v[i];
     // Throw warning: @ this code it "should be" index = plane id
     if(tpc_image.meta().plane() != i)
       LARCV_WARNING() << "Image index != plane ID is detected... " << std::endl;
     // Prepare random image and fill from gaussian generator
     std::vector<float> rand_img;
     _randg_v[i].get(rand_img);
     // If size is too small regenerate
     if(rand_img.size() < tpc_image.size()) {
       LARCV_CRITICAL() << "Detected image size > random number pool size!" << std::endl;
       throw larbys();
     }
     // Perform elt-wise multiplication. Allow random image to be larger in size
     LARCV_INFO() << "ElementWise mult on TPC Image2D " << std::endl;
     tpc_image.eltwise(rand_img,true);
     // Start thread for gaussian random number generation
     sleep(5);
     _randg_v[i].start_filling();
       }
       event_image->Emplace(std::move(tpc_image_v));
     }
     */
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_gaus_mean_v
std::vector<double> larcv::ADCScale::_gaus_mean_v private
Definition at line 50 of file ADCScale.h.
Referenced by configure(), and process().
_gaus_pool_size_v
std::vector<size_t> larcv::ADCScale::_gaus_pool_size_v private
Definition at line 52 of file ADCScale.h.
_gaus_sigma_v
std::vector<double> larcv::ADCScale::_gaus_sigma_v private
Definition at line 51 of file ADCScale.h.
Referenced by configure(), and process().
_image_id
ProducerID_t larcv::ADCScale::_image_id private
Definition at line 49 of file ADCScale.h.
Referenced by initialize(), and process().
_image_producer
std::string larcv::ADCScale::_image_producer private
Definition at line 48 of file ADCScale.h.
Referenced by configure(), and process().
_per_pixel
bool larcv::ADCScale::_per_pixel private
Definition at line 53 of file ADCScale.h.
Referenced by configure(), and process().
_randg_v
std::vector<larcv::RandomGaus > larcv::ADCScale::_randg_v private
Definition at line 56 of file ADCScale.h.
The documentation for this class was generated from the following files:
ADCScale.h
ADCScale.cxx