LArCV: larcv::ImageMerger Class Reference
larcv::ImageMerger Class Reference
#include <ImageMerger.h>
Public Member Functions
ImageMerger (const std::string name="ImageMerger")
Default constructor.
virtual ~ImageMerger ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void InputImageHolder1 (ImageHolder *ptr)
void InputImageHolder2 (ImageHolder *ptr)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
ImageHolder * _in1_proc
ImageHolder * _in2_proc
float _pmt_pedestal
std::string _out_tpc_producer
std::string _out_pmt_producer
std::string _out_status_producer
std::string _out_roi_producer
std::string _out_segment_producer
Detailed Description
Definition at line 27 of file ImageMerger.h.
Constructor & Destructor Documentation
ImageMerger()
larcv::ImageMerger::ImageMerger (const std::string name = "ImageMerger")
Default constructor.
Definition at line 13 of file ImageMerger.cxx.
Referenced by larcv::ImageMergerProcessFactory::create().
     : ProcessBase(name)
     , _in1_proc  (nullptr)
     , _in2_proc  (nullptr)
   {}
~ImageMerger()
virtual larcv::ImageMerger::~ImageMerger () inline virtual
Default destructor.
Definition at line 35 of file ImageMerger.h.
References configure(), finalize(), initialize(), InputImageHolder1(), InputImageHolder2(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ImageMerger::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file ImageMerger.cxx.
References _out_pmt_producer, _out_roi_producer, _out_segment_producer, _out_status_producer, _out_tpc_producer, _pmt_pedestal, and larcv::PSet::get().
Referenced by ~ImageMerger().
   {
     _pmt_pedestal         = cfg.get<float>       ("PMTPedestal"      );
     _out_tpc_producer     = cfg.get<std::string> ("OutNameTPCImage"  );
     _out_pmt_producer     = cfg.get<std::string> ("OutNamePMTImage"  );
     _out_roi_producer     = cfg.get<std::string> ("OutNameROI"       );
     _out_status_producer  = cfg.get<std::string> ("OutNameChStatus"  );
     _out_segment_producer = cfg.get<std::string> ("OutNameSegment"   );
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ImageMerger::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 216 of file ImageMerger.cxx.
Referenced by ~ImageMerger().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ImageMerger::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 29 of file ImageMerger.cxx.
Referenced by ~ImageMerger().
   {
   }
InputImageHolder1()
void larcv::ImageMerger::InputImageHolder1 (ImageHolder * ptr)
Definition at line 33 of file ImageMerger.cxx.
References _in1_proc.
Referenced by larcv::MergeTwoStream::initialize(), and ~ImageMerger().
   { _in1_proc = ptr; }
InputImageHolder2()
void larcv::ImageMerger::InputImageHolder2 (ImageHolder * ptr)
Definition at line 36 of file ImageMerger.cxx.
References _in2_proc.
Referenced by larcv::MergeTwoStream::initialize(), and ~ImageMerger().
   { _in2_proc = ptr; }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ImageMerger::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 39 of file ImageMerger.cxx.
References _in1_proc, _in2_proc, _out_pmt_producer, _out_roi_producer, _out_segment_producer, _out_status_producer, _out_tpc_producer, _pmt_pedestal, larcv::ImageHolder::event(), larcv::IOManager< T >::get_data(), larcv::Image2D::kMaxPool, larcv::kProductChStatus, larcv::kProductImage2D, larcv::kProductROI, larcv::Image2D::kSum, LARCV_CRITICAL, LARCV_ERROR, LARCV_INFO, larcv::ImageHolder::move_ch_status(), larcv::ImageHolder::move_pmt_image(), larcv::ImageHolder::move_roi(), larcv::ImageHolder::move_tpc_image(), larcv::ImageHolder::move_tpc_segment(), larcv::Image2D::overlay(), larcv::ImageHolder::run(), larcv::IOManager< T >::set_id(), and larcv::ImageHolder::subrun().
Referenced by ~ImageMerger().
   {
     LARCV_INFO() << "Start merging" << std::endl;
     if (!_in1_proc) {
       LARCV_CRITICAL() << "InputImageHolder1() must be called to set ImageHolder pointer!" << std::endl;
       throw larbys();
     }
     if (!_in2_proc) {
       LARCV_CRITICAL() << "InputImageHolder2() must be called to set ImageHolder pointer!" << std::endl;
       throw larbys();
     }
     mgr.set_id(_in2_proc->run(), _in2_proc->subrun(), _in2_proc->event());
     //
     // Retrieve data from data/mc image holders
     //
     std::vector<larcv::Image2D>  in1_tpc_image_v;
     std::vector<larcv::Image2D>  in1_tpc_segment_v;
     larcv::Image2D  in1_pmt_image;
     std::map<larcv::PlaneID_t, larcv::ChStatus> in1_status_m;
     std::vector<larcv::ROI> in1_roi_v;
     std::vector<larcv::Image2D>  in2_tpc_image_v;
     std::vector<larcv::Image2D>  in2_tpc_segment_v;
     larcv::Image2D  in2_pmt_image;
     std::map<larcv::PlaneID_t, larcv::ChStatus> in2_status_m;
     std::vector<larcv::ROI> in2_roi_v;
     LARCV_INFO() << "Moving Input1 images..." << std::endl;
     _in1_proc->move_tpc_image   ( in1_tpc_image_v   );
     _in1_proc->move_tpc_segment ( in1_tpc_segment_v );
     _in1_proc->move_pmt_image   ( in1_pmt_image     );
     _in1_proc->move_ch_status   ( in1_status_m      );
     _in1_proc->move_roi         ( in1_roi_v         );
     LARCV_INFO() << "Moving Input2 images..." << std::endl;
     _in2_proc->move_tpc_image   ( in2_tpc_image_v   );
     _in2_proc->move_tpc_segment ( in2_tpc_segment_v );
     _in2_proc->move_pmt_image   ( in2_pmt_image     );
     _in2_proc->move_ch_status   ( in2_status_m      );
     _in2_proc->move_roi         ( in2_roi_v         );
     //
     // Sanity checks
     //
     // Check size
     if (in1_tpc_image_v.size() != in2_tpc_image_v.size()) {
       LARCV_ERROR() << "# of Data stream image do not match between two streams! Skipping this entry..." << std::endl;
       return false;
     }
     // Check PlaneID
     for (size_t i = 0; i < in1_tpc_image_v.size(); ++i) {
       auto const& image1 = in1_tpc_image_v[i];
       auto const& image2 = in2_tpc_image_v[i];
       if (image1.meta().plane() != image2.meta().plane()) {
         LARCV_ERROR() << "Plane ID mismatch! skipping..." << std::endl;
         return false;
       }
       if ( (!in2_status_m.empty() && (in2_status_m.find(image2.meta().plane()) == in2_status_m.end())) ||
            (!in1_status_m.empty() && (in1_status_m.find(image1.meta().plane()) == in1_status_m.end())) ) {
         LARCV_ERROR() << "Plane ID " << image1.meta().plane() << " not found for ch status!" << std::endl;
         return false;
       }
     }
     // All check done
     //
     // Merge them
     //
     // Merge status
     std::set<larcv::PlaneID_t> status_plane_s;
     for ( auto const& plane_status : in1_status_m ) status_plane_s.insert(plane_status.first);
     for ( auto const& plane_status : in2_status_m ) status_plane_s.insert(plane_status.first);
     for ( auto const& plane : status_plane_s) {
       auto in1_iter = in1_status_m.find(plane);
       auto in2_iter = in2_status_m.find(plane);
       if (in2_iter == in2_status_m.end()) continue;
       if (in1_iter == in1_status_m.end()) {
         in1_status_m[plane] = (*in2_iter).second;
         continue;
       }
       auto const& in1_status_v = (*in1_iter).second.as_vector();
       auto const& in2_status_v = (*in2_iter).second.as_vector();
       std::vector<short> status_v(std::max(in1_status_v.size(), in2_status_v.size()), 0);
       const size_t min_entry = std::min(in1_status_v.size(), in2_status_v.size());
       for (size_t i = 0; i < min_entry; ++i)
         status_v[i] = std::min(in1_status_v[i], in2_status_v[i]);
       if (in1_status_v.size() > min_entry)
         for (size_t i = min_entry; i < in1_status_v.size(); ++i) status_v[i] = in2_status_v[i];
       if (in2_status_v.size() > min_entry)
         for (size_t i = min_entry; i < in2_status_v.size(); ++i) status_v[i] = in2_status_v[i];
       (*in1_iter).second = std::move(ChStatus(plane, std::move(status_v)));
     }
     // Merge tpc image
     for (size_t i = 0; i < in1_tpc_image_v.size(); ++i) {
       // retrieve & sum
       auto& in1_image = in1_tpc_image_v[i];
       auto& in2_image = in2_tpc_image_v[i];
       in1_image.overlay(in2_image, Image2D::kSum);
     }
     in2_tpc_image_v.clear(); // free memory, slow but keep job memory low
     // Merge tpc segment
     std::vector<larcv::Image2D> out_segment_v;
     if (in1_tpc_segment_v.empty()) {
       out_segment_v = std::move(in1_tpc_segment_v);
     }
     else if (in2_tpc_segment_v.empty()) {
       out_segment_v = std::move(in2_tpc_segment_v);
     }
     else {
       out_segment_v = std::move(in1_tpc_segment_v);
       for (size_t i = 0; i < out_segment_v.size(); ++i) {
         // retrieve & sum
         auto& in1_segment = out_segment_v[i];
         if (in2_tpc_segment_v.size() > i) {
           auto const& in2_segment   = in2_tpc_segment_v[i];
           in1_segment.overlay(in2_segment, Image2D::kMaxPool);
         }
       }
     }
     // Merge pmt image
     in1_pmt_image.overlay(in2_pmt_image);
     in1_pmt_image -= _pmt_pedestal;
     // Merge ROI
     std::vector<larcv::ROI> out_roi_v;
     out_roi_v.reserve(in1_roi_v.size() + in2_roi_v.size());
     for (auto const& roi : in1_roi_v) out_roi_v.push_back(roi);
     for (auto const& roi : in2_roi_v) out_roi_v.push_back(roi);
     // Store
     auto out_tpc_image   = (EventImage2D*)(mgr.get_data(kProductImage2D, _out_tpc_producer));
     out_tpc_image->Emplace(std::move(in1_tpc_image_v));
     if (!_out_pmt_producer.empty()) {
       auto out_pmt_image   = (EventImage2D*)(mgr.get_data(kProductImage2D, _out_pmt_producer));
       out_pmt_image->Emplace(std::move(in1_pmt_image));
     }
     if (!_out_segment_producer.empty()) {
       auto out_tpc_segment = (EventImage2D*)(mgr.get_data(kProductImage2D, _out_segment_producer));
       out_tpc_segment->Emplace(std::move(out_segment_v));
     }
     if (!_out_status_producer.empty()) {
       auto out_status = (EventChStatus*)(mgr.get_data(kProductChStatus, _out_status_producer));
       for (auto& plane_status : in1_status_m)  out_status->Emplace(std::move(plane_status.second));
     }
     if (!_out_roi_producer.empty()) {
       auto out_roi = (EventROI*)(mgr.get_data(kProductROI, _out_roi_producer));
       out_roi->Emplace(std::move(out_roi_v));
     }
     LARCV_INFO() << "End merging" << std::endl;
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_in1_proc
ImageHolder* larcv::ImageMerger::_in1_proc protected
Definition at line 51 of file ImageMerger.h.
Referenced by InputImageHolder1(), and process().
_in2_proc
ImageHolder* larcv::ImageMerger::_in2_proc protected
Definition at line 52 of file ImageMerger.h.
Referenced by InputImageHolder2(), and process().
_out_pmt_producer
std::string larcv::ImageMerger::_out_pmt_producer protected
Definition at line 55 of file ImageMerger.h.
Referenced by configure(), and process().
_out_roi_producer
std::string larcv::ImageMerger::_out_roi_producer protected
Definition at line 57 of file ImageMerger.h.
Referenced by configure(), and process().
_out_segment_producer
std::string larcv::ImageMerger::_out_segment_producer protected
Definition at line 58 of file ImageMerger.h.
Referenced by configure(), and process().
_out_status_producer
std::string larcv::ImageMerger::_out_status_producer protected
Definition at line 56 of file ImageMerger.h.
Referenced by configure(), and process().
_out_tpc_producer
std::string larcv::ImageMerger::_out_tpc_producer protected
Definition at line 54 of file ImageMerger.h.
Referenced by configure(), and process().
_pmt_pedestal
float larcv::ImageMerger::_pmt_pedestal protected
Definition at line 53 of file ImageMerger.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ImageMerger.h
ImageMerger.cxx