LArCV: larcv::DatumFillerBase Class Reference
larcv::DatumFillerBase Class Reference abstract
#include <DatumFillerBase.h>
Public Types
enum FillerDataType_t { kFillerImageData, kFillerLabelData, kFillerWeightData, kFillerMultiplicityData }
Public Member Functions
DatumFillerBase (const std::string name="DatumFillerBase")
Default constructor.
~DatumFillerBase ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
const std::string & producer (FillerDataType_t type) const
virtual bool is (const std::string question) const
size_t entries () const
const std::vector< std::vector< larcv::ImageMeta > > & meta () const
const std::vector< float > & data (FillerDataType_t dtype=kFillerImageData) const
virtual const std::vector< int > dim (bool image=true) const =0
size_t entry_image_size () const
size_t entry_label_size () const
size_t entry_weight_size () const
size_t entry_multiplicity_size () const
virtual void child_configure (const PSet &)=0
virtual void child_initialize ()
virtual void child_batch_begin ()
virtual void child_batch_end ()
virtual void child_finalize ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Member Functions
virtual void fill_entry_data (const larcv::EventBase *image, const larcv::EventBase *label, const larcv::EventBase *weight, const larcv::EventBase *multiplicity)=0
virtual size_t compute_image_size (const larcv::EventBase *image)=0
virtual size_t compute_label_size (const larcv::EventBase *label)=0
virtual size_t compute_multiplicity_size (const larcv::EventBase *multiplicity)=0
const std::vector< float > & entry_data (FillerDataType_t dtype=kFillerImageData) const
const std::vector< larcv::ImageMeta > & entry_meta () const
Protected Attributes
std::vector< float > _entry_image_data
std::vector< float > _entry_label_data
std::vector< float > _entry_weight_data
std::vector< float > _entry_multiplicity_data
ProductType_t _image_product_type
ProductType_t _label_product_type
ProductType_t _weight_product_type
ProductType_t _multiplicity_product_type
std::vector< larcv::ImageMeta > _entry_meta_data
Private Member Functions
void batch_begin ()
void batch_end ()
Private Attributes
size_t _nentries
std::string _image_producer
std::string _label_producer
std::string _weight_producer
std::string _multiplicity_producer
ProducerID_t _image_producer_id
ProducerID_t _label_producer_id
ProducerID_t _weight_producer_id
ProducerID_t _multiplicity_producer_id
std::vector< float > _image_data
std::vector< float > _label_data
std::vector< float > _weight_data
std::vector< float > _multiplicity_data
std::vector< std::vector< larcv::ImageMeta > > _meta_data
size_t _current_entry
size_t _entry_image_size
size_t _entry_label_size
size_t _entry_weight_size
size_t _entry_multiplicity_size
Friends
class ThreadDatumFiller
Detailed Description
Definition at line 28 of file DatumFillerBase.h.
Member Enumeration Documentation
FillerDataType_t
enum larcv::DatumFillerBase::FillerDataType_t
Enumerator
kFillerImageData
kFillerLabelData
kFillerWeightData
kFillerMultiplicityData
Definition at line 31 of file DatumFillerBase.h.
{
       kFillerImageData,
       kFillerLabelData,
       kFillerWeightData,
       kFillerMultiplicityData
     };
Constructor & Destructor Documentation
DatumFillerBase()
larcv::DatumFillerBase::DatumFillerBase (const std::string name = "DatumFillerBase")
Default constructor.
Definition at line 10 of file DatumFillerBase.cxx.
     : ProcessBase(name)
     , _nentries(kINVALID_SIZE)
     , _image_producer_id  (kINVALID_PRODUCER)
     , _label_producer_id  (kINVALID_PRODUCER)
     , _weight_producer_id (kINVALID_PRODUCER)
     , _multiplicity_producer_id (kINVALID_PRODUCER)
   {}
~DatumFillerBase()
larcv::DatumFillerBase::~DatumFillerBase () inline
Default destructor.
Definition at line 43 of file DatumFillerBase.h.
References configure(), data(), dim(), entries(), finalize(), initialize(), is(), kFillerImageData, meta(), process(), and producer().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
batch_begin()
void larcv::DatumFillerBase::batch_begin () private
Definition at line 99 of file DatumFillerBase.cxx.
References _current_entry, _entry_image_size, _entry_label_size, _entry_multiplicity_size, _entry_weight_size, _image_data, _label_data, _meta_data, _multiplicity_data, _multiplicity_producer, _nentries, _weight_data, _weight_producer, child_batch_begin(), and larcv::kINVALID_SIZE.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), and larcv::ThreadDatumFiller::batch_process().
{
     if(_entry_image_size != kINVALID_SIZE) {
       _image_data.resize(_nentries * _entry_image_size);
       _label_data.resize(_nentries * _entry_label_size);
       if(!_weight_producer.empty())
     _weight_data.resize(_nentries * _entry_weight_size);
       if(!_multiplicity_producer.empty())
     _multiplicity_data.resize(_nentries * _entry_multiplicity_size);
     }
     for( auto& v : _image_data         ) v=0.;
     for( auto& v : _label_data         ) v=0.;
     for( auto& v : _multiplicity_data  ) v=0.;
     for( auto& v : _weight_data        ) v=0.;
     _current_entry = 0;
     _meta_data.clear();
     this->child_batch_begin();
   }
batch_end()
void larcv::DatumFillerBase::batch_end () private
Definition at line 256 of file DatumFillerBase.cxx.
References child_batch_end().
Referenced by larcv::ThreadDatumFiller::_batch_process_(), and larcv::ThreadDatumFiller::batch_process().
   {
     this->child_batch_end();
   }
child_batch_begin()
virtual void larcv::DatumFillerBase::child_batch_begin () inline virtual
Reimplemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Definition at line 77 of file DatumFillerBase.h.
Referenced by batch_begin().
 {}
child_batch_end()
virtual void larcv::DatumFillerBase::child_batch_end () inline virtual
Reimplemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Definition at line 79 of file DatumFillerBase.h.
Referenced by batch_end().
 {}
child_configure()
virtual void larcv::DatumFillerBase::child_configure (const PSet &) pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by configure(), and entry_multiplicity_size().
child_finalize()
virtual void larcv::DatumFillerBase::child_finalize () inline virtual
Reimplemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Definition at line 81 of file DatumFillerBase.h.
References compute_image_size(), compute_label_size(), compute_multiplicity_size(), entry_data(), fill_entry_data(), and kFillerImageData.
Referenced by finalize().
 {}
child_initialize()
virtual void larcv::DatumFillerBase::child_initialize () inline virtual
Reimplemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Definition at line 75 of file DatumFillerBase.h.
Referenced by initialize().
 {}
compute_image_size()
virtual size_t larcv::DatumFillerBase::compute_image_size (const larcv::EventBase * image) protected pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by child_finalize(), and process().
compute_label_size()
virtual size_t larcv::DatumFillerBase::compute_label_size (const larcv::EventBase * label) protected pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by child_finalize(), and process().
compute_multiplicity_size()
virtual size_t larcv::DatumFillerBase::compute_multiplicity_size (const larcv::EventBase * multiplicity) protected pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by child_finalize(), and process().
configure()
void larcv::DatumFillerBase::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 73 of file DatumFillerBase.cxx.
References _image_producer, _label_producer, _multiplicity_producer, _weight_producer, child_configure(), and larcv::PSet::get().
Referenced by ~DatumFillerBase().
   {
     _image_producer        = cfg.get<std::string>("ImageProducer");
     _label_producer        = cfg.get<std::string>("LabelProducer");
     _weight_producer       = cfg.get<std::string>("WeightProducer","");
     _multiplicity_producer = cfg.get<std::string>("MultiplicityProducer","");
     this->child_configure(cfg);
   }
data()
const std::vector< float > & larcv::DatumFillerBase::data (DatumFillerBase::FillerDataType_t dtype = kFillerImageData) const
Definition at line 43 of file DatumFillerBase.cxx.
References _image_data, _label_data, _multiplicity_data, _weight_data, kFillerImageData, kFillerLabelData, kFillerMultiplicityData, and kFillerWeightData.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), larcv::ThreadDatumFiller::data(), larcv::ThreadDatumFiller::labels(), larcv::ThreadDatumFiller::multiplicities(), larcv::ThreadDatumFiller::weights(), and ~DatumFillerBase().
   { switch(dtype) {
     case kFillerImageData:
       return _image_data;
     case kFillerLabelData:
       return _label_data;
     case kFillerWeightData:
       return _weight_data;
     case kFillerMultiplicityData:
       return _multiplicity_data;
     }
     return _weight_data;
   }
dim()
virtual const std::vector<int> larcv::DatumFillerBase::dim (bool image = true) const pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by larcv::ThreadDatumFiller::dim(), and ~DatumFillerBase().
entries()
size_t larcv::DatumFillerBase::entries () const
Definition at line 34 of file DatumFillerBase.cxx.
References _nentries.
Referenced by larcv::MultiClassFiller::child_batch_begin(), larcv::SegFiller::child_batch_begin(), larcv::SimpleFiller::child_batch_begin(), larcv::SegFiller::dim(), larcv::SimpleFiller::dim(), larcv::MultiClassFiller::dim(), and ~DatumFillerBase().
 { return _nentries; }
entry_data()
const std::vector< float > & larcv::DatumFillerBase::entry_data (DatumFillerBase::FillerDataType_t dtype = kFillerImageData) const protected
Definition at line 58 of file DatumFillerBase.cxx.
References _entry_image_data, _entry_label_data, _entry_multiplicity_data, _entry_weight_data, kFillerImageData, kFillerLabelData, kFillerMultiplicityData, and kFillerWeightData.
Referenced by child_finalize(), and process().
   {
     switch(dtype) {
     case kFillerImageData:
       return _entry_image_data;
     case kFillerLabelData:
       return _entry_label_data;
     case kFillerWeightData:
       return _entry_weight_data;
     case kFillerMultiplicityData:
       return _entry_multiplicity_data;
     }
     return _entry_weight_data;
   }
entry_image_size()
size_t larcv::DatumFillerBase::entry_image_size () const inline
Definition at line 65 of file DatumFillerBase.h.
References _entry_image_size.
Referenced by larcv::SegFiller::compute_label_size(), larcv::SimpleFiller::fill_entry_data(), larcv::SegFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
 { return _entry_image_size;  }
entry_label_size()
size_t larcv::DatumFillerBase::entry_label_size () const inline
Definition at line 67 of file DatumFillerBase.h.
References _entry_label_size.
Referenced by larcv::SegFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
 { return _entry_label_size;  }
entry_meta()
const std::vector<larcv::ImageMeta>& larcv::DatumFillerBase::entry_meta () const inline protected
Definition at line 98 of file DatumFillerBase.h.
References _entry_meta_data.
     { return _entry_meta_data;}
entry_multiplicity_size()
size_t larcv::DatumFillerBase::entry_multiplicity_size () const inline
Definition at line 71 of file DatumFillerBase.h.
References _entry_multiplicity_size, and child_configure().
Referenced by larcv::MultiClassFiller::fill_entry_data().
 { return _entry_multiplicity_size; }
entry_weight_size()
size_t larcv::DatumFillerBase::entry_weight_size () const inline
Definition at line 69 of file DatumFillerBase.h.
References _entry_weight_size.
Referenced by larcv::SegFiller::fill_entry_data().
 { return _entry_weight_size; }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
fill_entry_data()
virtual void larcv::DatumFillerBase::fill_entry_data (const larcv::EventBase * image, const larcv::EventBase * label, const larcv::EventBase * weight, const larcv::EventBase * multiplicity) protected pure virtual
Implemented in larcv::MultiClassFiller, larcv::SegFiller, and larcv::SimpleFiller.
Referenced by child_finalize(), and process().
finalize()
void larcv::DatumFillerBase::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 261 of file DatumFillerBase.cxx.
References child_finalize().
Referenced by larcv::ThreadDatumFiller::finalize(), and ~DatumFillerBase().
   { this->child_finalize(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DatumFillerBase::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 82 of file DatumFillerBase.cxx.
References _current_entry, _entry_image_size, _entry_label_size, _entry_multiplicity_size, _entry_weight_size, _image_producer_id, _label_producer_id, _multiplicity_producer_id, _nentries, _weight_producer_id, child_initialize(), larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, and LARCV_CRITICAL.
Referenced by larcv::ThreadDatumFiller::initialize(), and ~DatumFillerBase().
   {
     if(_nentries == kINVALID_SIZE) {
       LARCV_CRITICAL() << "# entries not set... must be set @ initialize! " << std::endl;
       throw larbys();
     }
     _current_entry = kINVALID_SIZE;
     _entry_image_size   = _entry_label_size = kINVALID_SIZE;
     _entry_weight_size  = 0;
     _entry_multiplicity_size  = 0;
     _image_producer_id        = kINVALID_PRODUCER;
     _label_producer_id        = kINVALID_PRODUCER;
     _weight_producer_id       = kINVALID_PRODUCER;
     _multiplicity_producer_id = kINVALID_PRODUCER;
     this->child_initialize();
   }
is()
bool larcv::DatumFillerBase::is (const std::string question) const virtual
Reimplemented from larcv::ProcessBase.
Definition at line 36 of file DatumFillerBase.cxx.
Referenced by ~DatumFillerBase().
   { return (question == "DatumFiller"); }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
meta()
const std::vector< std::vector< larcv::ImageMeta > > & larcv::DatumFillerBase::meta () const
Definition at line 39 of file DatumFillerBase.cxx.
References _meta_data.
Referenced by larcv::ThreadDatumFiller::meta(), and ~DatumFillerBase().
   { return _meta_data; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DatumFillerBase::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 117 of file DatumFillerBase.cxx.
References _current_entry, _entry_image_size, _entry_label_size, _entry_meta_data, _entry_multiplicity_size, _entry_weight_size, _image_data, _image_producer, _image_producer_id, _image_product_type, _label_data, _label_producer, _label_producer_id, _label_product_type, _meta_data, _multiplicity_data, _multiplicity_producer, _multiplicity_producer_id, _multiplicity_product_type, _nentries, _weight_data, _weight_producer, _weight_producer_id, _weight_product_type, compute_image_size(), compute_label_size(), compute_multiplicity_size(), current_image_index_start, entry_data(), entry_image_data, entry_label_data, larcv::EventBase::event(), fill_entry_data(), larcv::IOManager< T >::get_data(), kFillerImageData, kFillerLabelData, kFillerMultiplicityData, kFillerWeightData, larcv::kINVALID_PRODUCER, larcv::kINVALID_SIZE, LARCV_CRITICAL, LARCV_INFO, larcv::IOManager< T >::producer_id(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::ThreadDatumFiller::batch_process(), and ~DatumFillerBase().
   {
     LARCV_INFO() << std::endl;
     if(_current_entry == kINVALID_SIZE) {
       LARCV_CRITICAL() << "batch_begin() not called... Note this process is only meant to use with ThreadReadDriver!\n";
       throw larbys();
     }
     LARCV_INFO() << std::endl;
     if(_image_producer_id == kINVALID_PRODUCER) {
       _image_producer_id = mgr.producer_id(_image_product_type,_image_producer);
       if(_image_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Image producer " << _image_producer << " not valid!" << std::endl;
         throw larbys();
       }
       _label_producer_id = mgr.producer_id(_label_product_type,_label_producer);
       if(_label_producer_id == kINVALID_PRODUCER) {
         LARCV_CRITICAL() << "Label producer " << _label_producer << " not valid!" << std::endl;
         throw larbys();
       }
       LARCV_INFO() << std::endl;
       if(!_multiplicity_producer.empty()) {
     _multiplicity_producer_id = mgr.producer_id(_multiplicity_product_type,_multiplicity_producer);
     if(_multiplicity_producer_id == kINVALID_PRODUCER) {
       LARCV_CRITICAL() << "Multiplicity producer " << _multiplicity_producer << " not valid!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << std::endl;
       }
       if(!_weight_producer.empty()) {
     _weight_producer_id = mgr.producer_id(_weight_product_type,_weight_producer);
     if(_weight_producer_id == kINVALID_PRODUCER) {
       LARCV_CRITICAL() << "Weight producer " << _weight_producer << " not valid!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << std::endl;
       }
     }
     LARCV_INFO() << std::endl;
     auto const image_data        = mgr.get_data(_image_producer_id);
     auto const label_data        = mgr.get_data(_label_producer_id);
     const larcv::EventImage2D* multiplicity_data = NULL;
     LARCV_INFO() << std::endl;
     if(_entry_image_size==kINVALID_SIZE || _nentries == 1) {
       _entry_image_size        = compute_image_size(image_data);
       _entry_label_size        = compute_label_size(label_data);
       LARCV_INFO() << "Recomputed image size: "        << _entry_image_size << std::endl;
       LARCV_INFO() << "Recomputed label size: "        << _entry_label_size << std::endl;
       LARCV_INFO() << "Recomputed multiplicity size: " << _entry_multiplicity_size << std::endl;
       if( _entry_image_size == kINVALID_SIZE || _entry_label_size == kINVALID_SIZE) {
         LARCV_CRITICAL() << "Rows/Cols/NumChannels not set!" << std::endl;
         throw larbys();
       }
       _image_data.resize         (_entry_image_size         * _nentries, 0.);
       _label_data.resize         (_entry_label_size         * _nentries, 0.);
       if(_weight_producer_id != kINVALID_PRODUCER) {
     _entry_weight_size = _entry_image_size;
     _weight_data.resize (_entry_weight_size * _nentries, 0.);
       }
       if(_multiplicity_producer_id!=kINVALID_PRODUCER) {
     multiplicity_data = (larcv::EventImage2D*)mgr.get_data(_multiplicity_producer_id);
     _entry_multiplicity_size = compute_multiplicity_size(multiplicity_data);
     _multiplicity_data.resize  (_entry_multiplicity_size  * _nentries, 0.);
       }
     }
     EventBase* weight_data=nullptr;
     if(_weight_producer_id != kINVALID_PRODUCER)
       weight_data = mgr.get_data(_weight_producer_id);
     _entry_meta_data.clear();
     this->fill_entry_data(image_data,label_data,weight_data,multiplicity_data);
     auto const& entry_image_data        = entry_data(kFillerImageData);
     auto const& entry_label_data        = entry_data(kFillerLabelData);
     auto const& entry_weight_data       = entry_data(kFillerWeightData);
     auto const& entry_multiplicity_data = entry_data(kFillerMultiplicityData);
     if(entry_image_data.size() != _entry_image_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << image_data->run() << "," << image_data->subrun() << "," << image_data->event() << ")"
       << "Entry image size should be " << _entry_image_size << " but found " << entry_image_data.size() << std::endl;
       throw larbys();
     }
     if(entry_label_data.size() != _entry_label_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << label_data->run() << "," << label_data->subrun() << "," << label_data->event() << ")"
       << "Entry label size should be " << _entry_label_size << " but found " << entry_label_data.size() << std::endl;
       throw larbys();
     }
     if(entry_multiplicity_data.size() != _entry_multiplicity_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << multiplicity_data->run() << "," << multiplicity_data->subrun() << "," << multiplicity_data->event() << ")"
       << "Entry multiplicity size should be " << _entry_multiplicity_size << " but found " << entry_multiplicity_data.size() << std::endl;
       throw larbys();
     }
     if(entry_weight_data.size() != _entry_weight_size) {
       LARCV_CRITICAL() << "(run,subrun,event) = ("
       << weight_data->run() << "," << weight_data->subrun() << "," << weight_data->event() << ")"
       << "Entry weight size should be " << _entry_weight_size << " but found " << entry_weight_data.size() << std::endl;
       throw larbys();
     }
     const size_t current_image_index_start = _current_entry * _entry_image_size;
     for(size_t i = 0; i<_entry_image_size; ++i)
       _image_data[current_image_index_start + i] = entry_image_data[i];
     const size_t current_label_index_start = _current_entry * _entry_label_size;
     for(size_t i = 0; i<_entry_label_size; ++i)
       _label_data[current_label_index_start + i] = entry_label_data[i];
     const size_t current_multiplicity_index_start = _current_entry * _entry_multiplicity_size;
     for(size_t i = 0; i<_entry_multiplicity_size; ++i)
       _multiplicity_data[current_multiplicity_index_start + i] = entry_multiplicity_data[i];
     const size_t current_weight_index_start = _current_entry * _entry_weight_size;
     for(size_t i = 0; i<_entry_weight_size; ++i)
       _weight_data[current_weight_index_start + i] = entry_weight_data[i];
     _meta_data.emplace_back(std::move(_entry_meta_data));
     ++_current_entry;
     return true;
   }
producer()
const std::string & larcv::DatumFillerBase::producer (DatumFillerBase::FillerDataType_t dtype) const
Definition at line 20 of file DatumFillerBase.cxx.
References _image_producer, _label_producer, _multiplicity_producer, _weight_producer, kFillerImageData, kFillerLabelData, kFillerMultiplicityData, and kFillerWeightData.
Referenced by larcv::ThreadDatumFiller::producer(), and ~DatumFillerBase().
   { switch(dtype) {
     case kFillerImageData:
       return _image_producer;
     case kFillerLabelData:
       return _label_producer;
     case kFillerWeightData:
       return _weight_producer;
     case kFillerMultiplicityData:
       return _multiplicity_producer;
     }
     return _weight_producer;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Friends And Related Function Documentation
ThreadDatumFiller
friend class ThreadDatumFiller friend
Definition at line 29 of file DatumFillerBase.h.
Member Data Documentation
_current_entry
size_t larcv::DatumFillerBase::_current_entry private
Definition at line 132 of file DatumFillerBase.h.
Referenced by batch_begin(), initialize(), and process().
_entry_image_data
std::vector<float> larcv::DatumFillerBase::_entry_image_data protected
Definition at line 101 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), larcv::SegFiller::child_initialize(), larcv::SimpleFiller::child_initialize(), entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::SegFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_image_size
size_t larcv::DatumFillerBase::_entry_image_size private
Definition at line 133 of file DatumFillerBase.h.
Referenced by batch_begin(), entry_image_size(), initialize(), and process().
_entry_label_data
std::vector<float> larcv::DatumFillerBase::_entry_label_data protected
Definition at line 102 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), larcv::SegFiller::child_initialize(), larcv::SimpleFiller::child_initialize(), entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::SegFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_label_size
size_t larcv::DatumFillerBase::_entry_label_size private
Definition at line 134 of file DatumFillerBase.h.
Referenced by batch_begin(), entry_label_size(), initialize(), and process().
_entry_meta_data
std::vector<larcv::ImageMeta> larcv::DatumFillerBase::_entry_meta_data protected
Definition at line 109 of file DatumFillerBase.h.
Referenced by entry_meta(), larcv::SimpleFiller::fill_entry_data(), larcv::SegFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), and process().
_entry_multiplicity_data
std::vector<float> larcv::DatumFillerBase::_entry_multiplicity_data protected
Definition at line 104 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::child_initialize(), entry_data(), and larcv::MultiClassFiller::fill_entry_data().
_entry_multiplicity_size
size_t larcv::DatumFillerBase::_entry_multiplicity_size private
Definition at line 136 of file DatumFillerBase.h.
Referenced by batch_begin(), entry_multiplicity_size(), initialize(), and process().
_entry_weight_data
std::vector<float> larcv::DatumFillerBase::_entry_weight_data protected
Definition at line 103 of file DatumFillerBase.h.
Referenced by entry_data(), and larcv::SegFiller::fill_entry_data().
_entry_weight_size
size_t larcv::DatumFillerBase::_entry_weight_size private
Definition at line 135 of file DatumFillerBase.h.
Referenced by batch_begin(), entry_weight_size(), initialize(), and process().
_image_data
std::vector<float> larcv::DatumFillerBase::_image_data private
Definition at line 127 of file DatumFillerBase.h.
Referenced by batch_begin(), data(), and process().
_image_producer
std::string larcv::DatumFillerBase::_image_producer private
Definition at line 119 of file DatumFillerBase.h.
Referenced by configure(), process(), and producer().
_image_producer_id
ProducerID_t larcv::DatumFillerBase::_image_producer_id private
Definition at line 123 of file DatumFillerBase.h.
Referenced by initialize(), and process().
_image_product_type
ProductType_t larcv::DatumFillerBase::_image_product_type protected
Definition at line 105 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), process(), larcv::SegFiller::SegFiller(), and larcv::SimpleFiller::SimpleFiller().
_label_data
std::vector<float> larcv::DatumFillerBase::_label_data private
Definition at line 128 of file DatumFillerBase.h.
Referenced by batch_begin(), data(), and process().
_label_producer
std::string larcv::DatumFillerBase::_label_producer private
Definition at line 120 of file DatumFillerBase.h.
Referenced by configure(), process(), and producer().
_label_producer_id
ProducerID_t larcv::DatumFillerBase::_label_producer_id private
Definition at line 124 of file DatumFillerBase.h.
Referenced by initialize(), and process().
_label_product_type
ProductType_t larcv::DatumFillerBase::_label_product_type protected
Definition at line 106 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), process(), larcv::SegFiller::SegFiller(), and larcv::SimpleFiller::SimpleFiller().
_meta_data
std::vector<std::vector<larcv::ImageMeta> > larcv::DatumFillerBase::_meta_data private
Definition at line 131 of file DatumFillerBase.h.
Referenced by batch_begin(), meta(), and process().
_multiplicity_data
std::vector<float> larcv::DatumFillerBase::_multiplicity_data private
Definition at line 130 of file DatumFillerBase.h.
Referenced by batch_begin(), data(), and process().
_multiplicity_producer
std::string larcv::DatumFillerBase::_multiplicity_producer private
Definition at line 122 of file DatumFillerBase.h.
Referenced by batch_begin(), configure(), process(), and producer().
_multiplicity_producer_id
ProducerID_t larcv::DatumFillerBase::_multiplicity_producer_id private
Definition at line 126 of file DatumFillerBase.h.
Referenced by initialize(), and process().
_multiplicity_product_type
ProductType_t larcv::DatumFillerBase::_multiplicity_product_type protected
Definition at line 108 of file DatumFillerBase.h.
Referenced by larcv::MultiClassFiller::MultiClassFiller(), and process().
_nentries
size_t larcv::DatumFillerBase::_nentries private
Definition at line 117 of file DatumFillerBase.h.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), batch_begin(), larcv::ThreadDatumFiller::batch_process(), entries(), initialize(), and process().
_weight_data
std::vector<float> larcv::DatumFillerBase::_weight_data private
Definition at line 129 of file DatumFillerBase.h.
Referenced by batch_begin(), data(), and process().
_weight_producer
std::string larcv::DatumFillerBase::_weight_producer private
Definition at line 121 of file DatumFillerBase.h.
Referenced by batch_begin(), configure(), process(), and producer().
_weight_producer_id
ProducerID_t larcv::DatumFillerBase::_weight_producer_id private
Definition at line 125 of file DatumFillerBase.h.
Referenced by initialize(), and process().
_weight_product_type
ProductType_t larcv::DatumFillerBase::_weight_product_type protected
Definition at line 107 of file DatumFillerBase.h.
Referenced by process(), and larcv::SegFiller::SegFiller().
The documentation for this class was generated from the following files:
DatumFillerBase.h
DatumFillerBase.cxx