LArCV: larcv::ReadJarrettFileProcessFactory Class Reference
larcv::ReadJarrettFileProcessFactory Class Reference
#include <ReadJarrettFile.h>
Public Member Functions
ReadJarrettFileProcessFactory ()
ctor
~ReadJarrettFileProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 142 of file ReadJarrettFile.h.
Constructor & Destructor Documentation
ReadJarrettFileProcessFactory()
larcv::ReadJarrettFileProcessFactory::ReadJarrettFileProcessFactory () inline
ctor
Definition at line 145 of file ReadJarrettFile.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ReadJarrettFile",this); }
~ReadJarrettFileProcessFactory()
larcv::ReadJarrettFileProcessFactory::~ReadJarrettFileProcessFactory () inline
dtor
Definition at line 147 of file ReadJarrettFile.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ReadJarrettFileProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 149 of file ReadJarrettFile.h.
References larcv::ReadJarrettFile::ReadJarrettFile().
 { return new ReadJarrettFile(instance_name); }
The documentation for this class was generated from the following file:
ReadJarrettFile.h