LArCV: larcv::AlgoDataAnaProcessFactory Class Reference
larcv::AlgoDataAnaProcessFactory Class Reference
#include <AlgoDataAna.h>
Public Member Functions
AlgoDataAnaProcessFactory ()
~AlgoDataAnaProcessFactory ()
ProcessBase * create (const std::string instance_name)
Abstract constructor method.
Detailed Description
Definition at line 43 of file AlgoDataAna.h.
Constructor & Destructor Documentation
AlgoDataAnaProcessFactory()
larcv::AlgoDataAnaProcessFactory::AlgoDataAnaProcessFactory () inline
Definition at line 45 of file AlgoDataAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("AlgoDataAna",this); }
~AlgoDataAnaProcessFactory()
larcv::AlgoDataAnaProcessFactory::~AlgoDataAnaProcessFactory () inline
Definition at line 46 of file AlgoDataAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::AlgoDataAnaProcessFactory::create (const std::string instance_name) inline virtual
Abstract constructor method.
Implements larcv::ProcessFactoryBase.
Definition at line 47 of file AlgoDataAna.h.
References larcv::AlgoDataAna::AlgoDataAna().
 { return new AlgoDataAna(instance_name); }
The documentation for this class was generated from the following file:
AlgoDataAna.h