LArCV: larcv::ExampleAna Class Reference
larcv::ExampleAna Class Reference
#include <ExampleAna.h>
Public Member Functions
ExampleAna (const std::string name="ExampleAna")
Default constructor.
~ExampleAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void Analyze ()
Private Attributes
EventImage2D * _ev_img_v
EventImage2D * _ev_trk_img_v
EventImage2D * _ev_shr_img_v
EventROI * _ev_roi_v
EventPGraph * _ev_pgraph_v
EventPixel2D * _ev_pcluster_v
EventPixel2D * _ev_ctor_v
int _run
int _subrun
int _event
int _entry
std::string _img_prod
std::string _reco_roi_prod
std::string _pgraph_prod
std::string _pcluster_img_prod
std::string _pcluster_ctor_prod
std::string _trk_img_prod
std::string _shr_img_prod
LArbysImageMaker _LArbysImageMaker
TTree * _tree
Detailed Description
Definition at line 18 of file ExampleAna.h.
Constructor & Destructor Documentation
ExampleAna()
larcv::ExampleAna::ExampleAna (const std::string name = "ExampleAna")
Default constructor.
Definition at line 14 of file ExampleAna.cxx.
Referenced by larcv::ExampleAnaProcessFactory::create().
     : ProcessBase(name), _LArbysImageMaker(), _tree(nullptr)
   { }
~ExampleAna()
larcv::ExampleAna::~ExampleAna () inline
Default destructor.
Definition at line 26 of file ExampleAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
Analyze()
void larcv::ExampleAna::Analyze () private
Definition at line 82 of file ExampleAna.cxx.
References _entry, _ev_ctor_v, _ev_img_v, _ev_pcluster_v, _ev_pgraph_v, _ev_shr_img_v, _ev_trk_img_v, _LArbysImageMaker, _tree, larcv::LArbysImageMaker::ExtractMat(), larcv::EventImage2D::Image2DArray(), larcv::kINVALID_DOUBLE, LARCV_DEBUG, larcv::EventPGraph::PGraphArray(), larcv::EventPixel2D::Pixel2DClusterArray(), and larcv::Project3D().
Referenced by process().
{
     auto const& ctor_m = _ev_ctor_v->Pixel2DClusterArray();
     auto const& pcluster_m = _ev_pcluster_v->Pixel2DClusterArray();
     std::vector<ImageMeta> all_meta_v;
     std::vector<cv::Mat>   adc_cvimg_v;
     std::vector<cv::Mat>   trk_cvimg_v;
     std::vector<cv::Mat>   shr_cvimg_v;
     for(auto const& pgraph : _ev_pgraph_v->PGraphArray()) {
       auto const& roi_v = pgraph.ParticleArray();
       for(size_t plane=0; plane<3; ++plane) {
     auto meta = roi_v.front().BB(plane);
     auto meta_iter = std::find(std::begin(all_meta_v),std::end(all_meta_v),meta);
     if ( meta_iter != all_meta_v.end()) continue;
     auto adc_img2d = _ev_img_v->Image2DArray().at(plane).crop(meta);
     auto trk_img2d = _ev_trk_img_v->Image2DArray().at(plane).crop(meta);
     auto shr_img2d = _ev_shr_img_v->Image2DArray().at(plane).crop(meta);
     auto adc_cvimg = _LArbysImageMaker.ExtractMat(adc_img2d);
     adc_cvimg = larocv::Transpose(adc_cvimg);
     adc_cvimg = larocv::Flip(adc_cvimg,0);
     auto trk_cvimg = _LArbysImageMaker.ExtractMat(trk_img2d);
     trk_cvimg = larocv::Transpose(trk_cvimg);
     trk_cvimg = larocv::Flip(trk_cvimg,0);
     auto shr_cvimg = _LArbysImageMaker.ExtractMat(shr_img2d);
     shr_cvimg = larocv::Transpose(shr_cvimg);
     shr_cvimg = larocv::Flip(shr_cvimg,0);
     all_meta_v.emplace_back(std::move(meta));
     adc_cvimg_v.emplace_back(std::move(adc_cvimg));
     trk_cvimg_v.emplace_back(std::move(shr_cvimg));
     shr_cvimg_v.emplace_back(std::move(trk_cvimg));
       }
     }
     for(size_t pgraph_id = 0; pgraph_id < _ev_pgraph_v->PGraphArray().size(); ++pgraph_id) {
       std::stringstream base_ss;
       base_ss << _entry << "_pgraph_id";
       std::string base_str = base_ss.str();
       LARCV_DEBUG() << "@pgraph=" << pgraph_id << std::endl;
       auto const& pgraph = _ev_pgraph_v->PGraphArray().at(pgraph_id);
       auto const& roi_v = pgraph.ParticleArray();
       auto const& cluster_idx_v = pgraph.ClusterIndexArray();
       // Get the 3D vertex position
       auto vtx_x = pgraph.ParticleArray().front().X();
       auto vtx_y = pgraph.ParticleArray().front().Y();
       auto vtx_z = pgraph.ParticleArray().front().Z();
       // Get the 3D end point
       auto end_x = pgraph.ParticleArray().front().EndPosition().X();
       auto end_y = pgraph.ParticleArray().front().EndPosition().Y();
       auto end_z = pgraph.ParticleArray().front().EndPosition().Z();
       LARCV_DEBUG() << "vertex=(" << vtx_x << "," << vtx_y << "," << vtx_z << ")" << std::endl;
       LARCV_DEBUG() << "end   =(" << end_x << "," << end_y << "," << end_z << ")" << std::endl;
       auto nparticles = cluster_idx_v.size();
       // Loop per plane, get the particle contours and images for this plane
       for(size_t plane=0; plane<3; ++plane) {
     std::stringstream plane_ss;
     LARCV_DEBUG() << "@plane=" <<plane << std::endl;
     auto iter_pcluster = pcluster_m.find(plane);
     if(iter_pcluster == pcluster_m.end()) continue;
     auto iter_ctor = ctor_m.find(plane);
     if(iter_ctor == ctor_m.end()) continue;
     // Retrieve the particle images and particle contours on this plane
     const auto& pcluster_v = (*iter_pcluster).second;
     const auto& ctor_v = (*iter_ctor).second;
     // Get this planes meta
     auto meta = roi_v.front().BB(plane);
     auto meta_iter = std::find(std::begin(all_meta_v),std::end(all_meta_v),meta);
     if ( meta_iter == all_meta_v.end()) throw larbys("Where is this meta?");
     auto meta_id = meta_iter - all_meta_v.begin();
     auto& adc_cvimg = adc_cvimg_v.at(meta_id);
     auto& trk_cvimg = trk_cvimg_v.at(meta_id);
     auto& shr_cvimg = shr_cvimg_v.at(meta_id);
     double x_pixel,y_pixel;
     x_pixel = y_pixel = kINVALID_DOUBLE;
     Project3D(meta,
           vtx_x,vtx_y,vtx_z,0, // (x,y,z,t)
           plane,
           x_pixel,y_pixel);    // result
     y_pixel = meta.rows() - y_pixel;
     auto adc_cvimg_bw = larocv::Threshold(adc_cvimg,10,255);
     plane_ss << base_str << "_plane_"<<plane<<"_adc.png";
     cv::imwrite(plane_ss.str().c_str(),adc_cvimg_bw);
     // For each particle, get the contour and image on this plane (from pcluster_v/ctor_v)
     for(size_t par_id=0; par_id < cluster_idx_v.size(); ++par_id) {
       auto cluster_idx = cluster_idx_v[par_id];
       const auto& pcluster = pcluster_v.at(cluster_idx);
       const auto& pctor    = ctor_v.at(cluster_idx);
       // There is no particle cluster on this plane
       if (pctor.empty()) continue;
       // Convert the Pixel2DArray of contour points to a GEO2D_Contour_t
       larocv::GEO2D_Contour_t ctor;
       ctor.resize(pctor.size());
       for(size_t i=0;i<ctor.size();++i) {
         ctor[i].x = pctor[i].X();
         ctor[i].y = pctor[i].Y();
       }
     } // end this particle
       } // end this plane
       _tree->Fill();
     } // end this vertex
     return;
   }
configure()
void larcv::ExampleAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 18 of file ExampleAna.cxx.
References _img_prod, _LArbysImageMaker, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _reco_roi_prod, _shr_img_prod, _trk_img_prod, larcv::LArbysImageMaker::Configure(), and larcv::PSet::get().
Referenced by ~ExampleAna().
   {
     _LArbysImageMaker.Configure(cfg.get<larcv::PSet>("LArbysImageMaker"));
     _img_prod           = cfg.get<std::string>("ImageProducer"       ,"tpc");
     _pgraph_prod        = cfg.get<std::string>("PGraphProducer"      ,"test");
     _pcluster_ctor_prod = cfg.get<std::string>("Pixel2DCtorProducer" ,"test_ctor");
     _pcluster_img_prod  = cfg.get<std::string>("Pixel2DImageProducer","test_img");
     _reco_roi_prod      = cfg.get<std::string>("RecoROIProducer"     ,"croimerge");
     _trk_img_prod = cfg.get<std::string>("TrackImageProducer" ,"");
     _shr_img_prod = cfg.get<std::string>("ShowerImageProducer","");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ExampleAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 77 of file ExampleAna.cxx.
References _tree.
Referenced by ~ExampleAna().
   {
     _tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ExampleAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 33 of file ExampleAna.cxx.
References _entry, _event, _run, _subrun, and _tree.
Referenced by ~ExampleAna().
   {
     //
     // Event Tree (per vertex)
     //
     _tree = new TTree("SignalTree","SignalTree");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ExampleAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 47 of file ExampleAna.cxx.
References _entry, _ev_ctor_v, _ev_img_v, _ev_pcluster_v, _ev_pgraph_v, _ev_roi_v, _ev_shr_img_v, _ev_trk_img_v, _event, _img_prod, _pcluster_ctor_prod, _pcluster_img_prod, _pgraph_prod, _reco_roi_prod, _run, _shr_img_prod, _subrun, _trk_img_prod, Analyze(), larcv::IOManager< T >::current_entry(), larcv::EventBase::event(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductPixel2D, larcv::kProductROI, larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by ~ExampleAna().
   {
     _ev_img_v      = (EventImage2D*)mgr.get_data(kProductImage2D,_img_prod);
     if(!_trk_img_prod.empty())
       _ev_trk_img_v      = (EventImage2D*)mgr.get_data(kProductImage2D,_trk_img_prod);
     if(!_shr_img_prod.empty())
       _ev_shr_img_v      = (EventImage2D*)mgr.get_data(kProductImage2D,_shr_img_prod);
     _ev_roi_v      = (EventROI*)    mgr.get_data(kProductROI,_reco_roi_prod);
     _ev_pgraph_v   = (EventPGraph*) mgr.get_data(kProductPGraph,_pgraph_prod);
     _ev_pcluster_v = (EventPixel2D*)mgr.get_data(kProductPixel2D,_pcluster_img_prod);
     _ev_ctor_v     = (EventPixel2D*)mgr.get_data(kProductPixel2D,_pcluster_ctor_prod);
     if(!_trk_img_prod.empty())
       _ev_trk_img_v = (EventImage2D*)mgr.get_data(kProductImage2D,_trk_img_prod);
     if(!_shr_img_prod.empty())
       _ev_shr_img_v = (EventImage2D*)mgr.get_data(kProductImage2D,_shr_img_prod);
     _run    = _ev_pgraph_v->run();
     _subrun = _ev_pgraph_v->subrun();
     _event  = _ev_pgraph_v->event();
     _entry  = mgr.current_entry();
     Analyze();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_entry
int larcv::ExampleAna::_entry private
Definition at line 46 of file ExampleAna.h.
Referenced by Analyze(), initialize(), and process().
_ev_ctor_v
EventPixel2D* larcv::ExampleAna::_ev_ctor_v private
Definition at line 41 of file ExampleAna.h.
Referenced by Analyze(), and process().
_ev_img_v
EventImage2D* larcv::ExampleAna::_ev_img_v private
Definition at line 35 of file ExampleAna.h.
Referenced by Analyze(), and process().
_ev_pcluster_v
EventPixel2D* larcv::ExampleAna::_ev_pcluster_v private
Definition at line 40 of file ExampleAna.h.
Referenced by Analyze(), and process().
_ev_pgraph_v
EventPGraph* larcv::ExampleAna::_ev_pgraph_v private
Definition at line 39 of file ExampleAna.h.
Referenced by Analyze(), and process().
_ev_roi_v
EventROI* larcv::ExampleAna::_ev_roi_v private
Definition at line 38 of file ExampleAna.h.
Referenced by process().
_ev_shr_img_v
EventImage2D* larcv::ExampleAna::_ev_shr_img_v private
Definition at line 37 of file ExampleAna.h.
Referenced by Analyze(), and process().
_ev_trk_img_v
EventImage2D* larcv::ExampleAna::_ev_trk_img_v private
Definition at line 36 of file ExampleAna.h.
Referenced by Analyze(), and process().
_event
int larcv::ExampleAna::_event private
Definition at line 45 of file ExampleAna.h.
Referenced by initialize(), and process().
_img_prod
std::string larcv::ExampleAna::_img_prod private
Definition at line 48 of file ExampleAna.h.
Referenced by configure(), and process().
_LArbysImageMaker
LArbysImageMaker larcv::ExampleAna::_LArbysImageMaker private
Definition at line 56 of file ExampleAna.h.
Referenced by Analyze(), and configure().
_pcluster_ctor_prod
std::string larcv::ExampleAna::_pcluster_ctor_prod private
Definition at line 52 of file ExampleAna.h.
Referenced by configure(), and process().
_pcluster_img_prod
std::string larcv::ExampleAna::_pcluster_img_prod private
Definition at line 51 of file ExampleAna.h.
Referenced by configure(), and process().
_pgraph_prod
std::string larcv::ExampleAna::_pgraph_prod private
Definition at line 50 of file ExampleAna.h.
Referenced by configure(), and process().
_reco_roi_prod
std::string larcv::ExampleAna::_reco_roi_prod private
Definition at line 49 of file ExampleAna.h.
Referenced by configure(), and process().
_run
int larcv::ExampleAna::_run private
Definition at line 43 of file ExampleAna.h.
Referenced by initialize(), and process().
_shr_img_prod
std::string larcv::ExampleAna::_shr_img_prod private
Definition at line 54 of file ExampleAna.h.
Referenced by configure(), and process().
_subrun
int larcv::ExampleAna::_subrun private
Definition at line 44 of file ExampleAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::ExampleAna::_tree private
Definition at line 60 of file ExampleAna.h.
Referenced by Analyze(), finalize(), and initialize().
_trk_img_prod
std::string larcv::ExampleAna::_trk_img_prod private
Definition at line 53 of file ExampleAna.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ExampleAna.h
ExampleAna.cxx