LArCV: larcv::VertexInROIProcessFactory Class Reference
larcv::VertexInROIProcessFactory Class Reference
#include <VertexInROI.h>
Public Member Functions
VertexInROIProcessFactory ()
~VertexInROIProcessFactory ()
ProcessBase * create (const std::string instance_name)
Abstract constructor method.
Detailed Description
Definition at line 34 of file VertexInROI.h.
Constructor & Destructor Documentation
VertexInROIProcessFactory()
larcv::VertexInROIProcessFactory::VertexInROIProcessFactory () inline
Definition at line 36 of file VertexInROI.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("VertexInROI",this); }
~VertexInROIProcessFactory()
larcv::VertexInROIProcessFactory::~VertexInROIProcessFactory () inline
Definition at line 38 of file VertexInROI.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::VertexInROIProcessFactory::create (const std::string instance_name) inline virtual
Abstract constructor method.
Implements larcv::ProcessFactoryBase.
Definition at line 40 of file VertexInROI.h.
References larcv::VertexInROI::VertexInROI().
 { return new VertexInROI(instance_name); }
The documentation for this class was generated from the following file:
VertexInROI.h