LArCV: larcv::CCQETruthFilterProcessFactory Class Reference
larcv::CCQETruthFilterProcessFactory Class Reference
#include <CCQETruthFilter.h>
Public Member Functions
CCQETruthFilterProcessFactory ()
ctor
~CCQETruthFilterProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 64 of file CCQETruthFilter.h.
Constructor & Destructor Documentation
CCQETruthFilterProcessFactory()
larcv::CCQETruthFilterProcessFactory::CCQETruthFilterProcessFactory () inline
ctor
Definition at line 67 of file CCQETruthFilter.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("CCQETruthFilter",this); }
~CCQETruthFilterProcessFactory()
larcv::CCQETruthFilterProcessFactory::~CCQETruthFilterProcessFactory () inline
dtor
Definition at line 69 of file CCQETruthFilter.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::CCQETruthFilterProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 71 of file CCQETruthFilter.h.
References larcv::CCQETruthFilter::CCQETruthFilter().
 { return new CCQETruthFilter(instance_name); }
The documentation for this class was generated from the following file:
CCQETruthFilter.h