LArCV: larcv::NuFilter Class Reference
larcv::NuFilter Class Reference
#include <NuFilter.h>
Classes
struct aparticle
Public Member Functions
NuFilter (const std::string name="NuFilter")
Default constructor.
~NuFilter ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
bool MCSelect (const EventROI *ev_roi)
Private Attributes
bool _mc_available
std::string _true_roi_producer_name
std::string _reco_roi_producer_name
std::string _rse_producer
int _nu_pdg
int _interaction_mode
double _min_nu_init_e
double _max_nu_init_e
double _dep_sum_lepton
double _dep_sum_proton
bool _select_signal
bool _select_background
int _n_fail_nupdg
int _n_fail_ccqe
int _n_fail_nuE
int _n_fail_lepton_dep
int _n_fail_proton_dep
int _n_pass
int _n_calls
int _n_fail_unknowns
int _n_fail_inter
TTree * _event_tree
int _run
int _subrun
int _event
int _entry
int _number_croi
int _selected
Detailed Description
Definition at line 28 of file NuFilter.h.
Constructor & Destructor Documentation
NuFilter()
larcv::NuFilter::NuFilter (const std::string name = "NuFilter")
Default constructor.
Definition at line 12 of file NuFilter.cxx.
References _n_calls, _n_fail_ccqe, _n_fail_inter, _n_fail_lepton_dep, _n_fail_nuE, _n_fail_nupdg, _n_fail_proton_dep, _n_fail_unknowns, and _n_pass.
Referenced by larcv::NuFilterProcessFactory::create().
     : ProcessBase(name), _event_tree(nullptr)
   {
     _n_calls = 0;
     _n_fail_ccqe =0;
     _n_fail_nupdg = 0;
     _n_fail_nuE = 0;
     _n_fail_lepton_dep = 0;
     _n_fail_proton_dep = 0;
     _n_pass = 0;
     _n_fail_unknowns=0;
     _n_fail_inter=0;
   }
~NuFilter()
larcv::NuFilter::~NuFilter () inline
Default destructor.
Definition at line 36 of file NuFilter.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::NuFilter::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 26 of file NuFilter.cxx.
References _dep_sum_lepton, _dep_sum_proton, _entry, _event, _event_tree, _interaction_mode, _max_nu_init_e, _min_nu_init_e, _nu_pdg, _number_croi, _reco_roi_producer_name, _rse_producer, _run, _select_background, _select_signal, _selected, _subrun, _true_roi_producer_name, larcv::PSet::get(), and larcv::larcv_base::set_verbosity().
Referenced by ~NuFilter().
   {
     this->set_verbosity((msg::Level_t)cfg.get<uint>("Verbosity",2));
     _rse_producer = cfg.get<std::string>("RSEProducer");
     _nu_pdg = cfg.get<int>("NuPDG");
     _interaction_mode = cfg.get<int>("InteractionMode");
     _dep_sum_lepton = 0.0;
     _dep_sum_proton = 0.0;
     _min_nu_init_e  = cfg.get<double>("MinNuEnergy");
     _max_nu_init_e  = cfg.get<double>("MaxNuEnergy");
     _dep_sum_lepton = cfg.get<double>("MinEDepSumLepton");
     _dep_sum_proton = cfg.get<double>("MinEDepSumProton");
     _select_signal     = cfg.get<bool>("SelectSignal");
     _select_background = cfg.get<bool>("SelectBackground");
     _true_roi_producer_name = cfg.get<std::string>("TrueROIProducer");
     _reco_roi_producer_name = cfg.get<std::string>("RecoROIProducer");
     _event_tree = new TTree("NuFilterTree","");
     _event_tree->Branch("run"      , &_run      , "run/I");
     _event_tree->Branch("subrun"   , &_subrun   , "subrun/I");
     _event_tree->Branch("event"    , &_event    , "event/I");
     _event_tree->Branch("entry"    , &_entry    , "entry/I");
     _event_tree->Branch("number_croi"  , &_number_croi   , "number_croi/I");
     _event_tree->Branch("selected1L1P" , &_selected , "selected1L1P/I");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::NuFilter::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 266 of file NuFilter.cxx.
References _event_tree.
Referenced by ~NuFilter().
   {
     _event_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::NuFilter::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 209 of file NuFilter.cxx.
References LARCV_DEBUG.
Referenced by ~NuFilter().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_DEBUG() << "end" << std::endl;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MCSelect()
bool larcv::NuFilter::MCSelect (const EventROI * ev_roi) private
Definition at line 57 of file NuFilter.cxx.
References _dep_sum_lepton, _dep_sum_proton, _interaction_mode, _max_nu_init_e, _min_nu_init_e, _n_fail_inter, _n_fail_lepton_dep, _n_fail_nuE, _n_fail_nupdg, _n_fail_proton_dep, _n_fail_unknowns, _nu_pdg, larcv::EventROI::at(), larcv::NuFilter::aparticle::depeng, larcv::NuFilter::aparticle::pdg, larcv::ROI::PdgCode(), larcv::NuFilter::aparticle::primary, larcv::NuFilter::aparticle::ptrackid, larcv::EventROI::ROIArray(), and larcv::NuFilter::aparticle::trackid.
Referenced by process().
{
     bool pdg_b = false;
     bool interaction_mode_b = false;
     bool energy_init_b = false;
     bool vis_lepton_b = false;
     bool vis_one_proton_b = false;
     bool vis_no_unknowns_b = false;
     int nlepton  = 0;
     int nproton  = 0;
     int unknown_ctr = 0.0;
     // Get neutrino ROI
     const auto& roi = ev_roi->at(0);
     int pdgcode          = roi.PdgCode();
     int interaction_mode = roi.NuInteractionType();
     double energy_init   = roi.EnergyInit();
     std::vector<aparticle> protons_v;
     std::vector<aparticle> leptons_v;
     std::vector<aparticle> unknown_v;
     bool first = false;
     for(const auto& roi : ev_roi->ROIArray()) {
       if(!first) { first=true; continue; }
       int pdgcode = std::abs(roi.PdgCode());
       if (pdgcode==2212) {
     aparticle thispro;
     thispro.pdg           = pdgcode;
     thispro.trackid       = roi.TrackID();
     thispro.ptrackid      = roi.ParentTrackID();
     thispro.depeng        = roi.EnergyDeposit();
     thispro.primary       = ( roi.TrackID() == roi.ParentTrackID() );
     protons_v.push_back(std::move(thispro));
       }
       else if (pdgcode==11 or pdgcode==13) {
     aparticle thislep;
     thislep.pdg           = pdgcode;
     thislep.trackid       = roi.TrackID();
     thislep.ptrackid      = roi.ParentTrackID();
     thislep.depeng        = roi.EnergyDeposit();
     thislep.primary       = ( roi.TrackID() == roi.ParentTrackID() );
     leptons_v.push_back(std::move(thislep));
       }
       else {
     aparticle thisunknown;
     thisunknown.pdg           = pdgcode;
     thisunknown.trackid       = roi.TrackID();
     thisunknown.ptrackid      = roi.ParentTrackID();
     thisunknown.depeng        = roi.EnergyDeposit();
     thisunknown.primary       = ( roi.TrackID() == roi.ParentTrackID() );
     unknown_v.push_back(std::move(thisunknown));
       }
     }
     //calculate the visible lepton energy
     int lepton_engs_ctr = 0 ;
     for (size_t p1=0;p1 < leptons_v.size() ; p1++ ){
       const auto& lepton1 = leptons_v[p1];
       if (! lepton1.primary ) continue;
       nlepton+=1;
       float this_lepton_eng = lepton1.depeng;
       for (size_t p2=0;p2 < leptons_v.size() ; p2++ ){
         if (p1==p2) continue;
         const auto& lepton2 = leptons_v[p2];
         if (lepton2.ptrackid != lepton1.trackid) continue;
         this_lepton_eng+=lepton2.depeng;
       }
       if ( this_lepton_eng > _dep_sum_lepton ) lepton_engs_ctr ++;
     }
     //calculate the visible proton energy
     int proton_engs_ctr = 0 ;
     for (size_t p1=0;p1 < protons_v.size() ; p1++ ){
       const auto& proton1 = protons_v[p1];
       if (! proton1.primary ) continue;
       nproton+=1;
       float this_proton_eng = proton1.depeng;
       for (size_t p2=0;p2 < protons_v.size() ; p2++ ){
     if (p1==p2) continue;
     const auto& proton2 = protons_v[p2];
     if (proton2.ptrackid != proton1.trackid) continue;
     this_proton_eng+=proton2.depeng;
       }
       if ( this_proton_eng > _dep_sum_proton ) proton_engs_ctr ++;
     }
     for(const auto& unknown : unknown_v) {
       if (!unknown.primary) continue;
       unknown_ctr+=1;
     }
     // requested nu PDG code
     if (pdgcode == _nu_pdg or _nu_pdg == 0) {
       pdg_b = true;
     }
     // requested nu interaction mode
     if ((interaction_mode == _interaction_mode) or (_interaction_mode == 0)) {
       interaction_mode_b = true;
     }
     // neutrino energy range
     if (energy_init >= _min_nu_init_e && energy_init <= _max_nu_init_e) {
       energy_init_b = true;
     }
     // interaction must have visible leptons
     if (lepton_engs_ctr == 1) {
       vis_lepton_b = true;
     }
     // There must be 1 visible proton
     if (proton_engs_ctr == 1) {
       vis_one_proton_b = true;
     }
     // There must be no primary unknowns
     if (unknown_ctr==0) {
       vis_no_unknowns_b = true;
     }
     bool selected =
       pdg_b               &&
       interaction_mode_b  &&
       energy_init_b       &&
       vis_lepton_b        &&
       vis_one_proton_b    &&
       vis_no_unknowns_b;
     if (! pdg_b)              _n_fail_nupdg      += 1;
     if (! interaction_mode_b) _n_fail_inter      += 1;
     if (! energy_init_b)      _n_fail_nuE        += 1;
     if (! vis_lepton_b)       _n_fail_lepton_dep += 1;
     if (! vis_one_proton_b)   _n_fail_proton_dep += 1;
     if (! vis_no_unknowns_b)  _n_fail_unknowns   += 1;
     return selected;
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::NuFilter::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 215 of file NuFilter.cxx.
References _entry, _event, _event_tree, _number_croi, _reco_roi_producer_name, _rse_producer, _run, _select_background, _select_signal, _selected, _subrun, _true_roi_producer_name, larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kINVALID_INT, larcv::kProductImage2D, larcv::kProductROI, LARCV_DEBUG, and MCSelect().
Referenced by ~NuFilter().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _run      = kINVALID_INT;
     _subrun   = kINVALID_INT;
     _event    = kINVALID_INT;
     _entry    = kINVALID_INT;
     _selected = kINVALID_INT;
     auto rse_prod = (EventImage2D*) mgr.get_data(kProductImage2D,_rse_producer);
     _run    = rse_prod->run();
     _subrun = rse_prod->subrun();
     _event  = rse_prod->event();
     _entry  = mgr.current_entry();
     auto ev_reco_roi = (EventROI*) mgr.get_data(kProductROI, _reco_roi_producer_name);
     _number_croi = (int)ev_reco_roi->ROIArray().size();
     if(_true_roi_producer_name.empty()) {
       _event_tree->Fill();
       return true;
     }
     auto ev_roi = (EventROI*) mgr.get_data(kProductROI, _true_roi_producer_name);
     bool signal_selected = MCSelect(ev_roi);
     LARCV_DEBUG() << "selected: " << signal_selected << std::endl;
     _selected = (int) signal_selected;
     // if atleast 1 of config selection is false, then test against signal selected
     if ( !_select_signal or !_select_background) {
       if ( _select_signal and !signal_selected ) {
     _event_tree->Fill();
     LARCV_DEBUG() << "false" << std::endl;
     return false;
       }
       if ( _select_background and  signal_selected ) {
     _event_tree->Fill();
     LARCV_DEBUG() << "false" << std::endl;
     return false;
       }
     }
     _event_tree->Fill();
     LARCV_DEBUG() << "true" << std::endl;
     LARCV_DEBUG() << "end" << std::endl;
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_dep_sum_lepton
double larcv::NuFilter::_dep_sum_lepton private
Definition at line 58 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_dep_sum_proton
double larcv::NuFilter::_dep_sum_proton private
Definition at line 59 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_entry
int larcv::NuFilter::_entry private
Definition at line 87 of file NuFilter.h.
Referenced by configure(), and process().
_event
int larcv::NuFilter::_event private
Definition at line 86 of file NuFilter.h.
Referenced by configure(), and process().
_event_tree
TTree* larcv::NuFilter::_event_tree private
Definition at line 82 of file NuFilter.h.
Referenced by configure(), finalize(), and process().
_interaction_mode
int larcv::NuFilter::_interaction_mode private
Definition at line 54 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_max_nu_init_e
double larcv::NuFilter::_max_nu_init_e private
Definition at line 57 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_mc_available
bool larcv::NuFilter::_mc_available private
Definition at line 45 of file NuFilter.h.
_min_nu_init_e
double larcv::NuFilter::_min_nu_init_e private
Definition at line 56 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_n_calls
int larcv::NuFilter::_n_calls private
Definition at line 78 of file NuFilter.h.
Referenced by NuFilter().
_n_fail_ccqe
int larcv::NuFilter::_n_fail_ccqe private
Definition at line 73 of file NuFilter.h.
Referenced by NuFilter().
_n_fail_inter
int larcv::NuFilter::_n_fail_inter private
Definition at line 80 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_fail_lepton_dep
int larcv::NuFilter::_n_fail_lepton_dep private
Definition at line 75 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_fail_nuE
int larcv::NuFilter::_n_fail_nuE private
Definition at line 74 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_fail_nupdg
int larcv::NuFilter::_n_fail_nupdg private
Definition at line 72 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_fail_proton_dep
int larcv::NuFilter::_n_fail_proton_dep private
Definition at line 76 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_fail_unknowns
int larcv::NuFilter::_n_fail_unknowns private
Definition at line 79 of file NuFilter.h.
Referenced by MCSelect(), and NuFilter().
_n_pass
int larcv::NuFilter::_n_pass private
Definition at line 77 of file NuFilter.h.
Referenced by NuFilter().
_nu_pdg
int larcv::NuFilter::_nu_pdg private
Definition at line 53 of file NuFilter.h.
Referenced by configure(), and MCSelect().
_number_croi
int larcv::NuFilter::_number_croi private
Definition at line 88 of file NuFilter.h.
Referenced by configure(), and process().
_reco_roi_producer_name
std::string larcv::NuFilter::_reco_roi_producer_name private
Definition at line 50 of file NuFilter.h.
Referenced by configure(), and process().
_rse_producer
std::string larcv::NuFilter::_rse_producer private
Definition at line 51 of file NuFilter.h.
Referenced by configure(), and process().
_run
int larcv::NuFilter::_run private
Definition at line 84 of file NuFilter.h.
Referenced by configure(), and process().
_select_background
bool larcv::NuFilter::_select_background private
Definition at line 62 of file NuFilter.h.
Referenced by configure(), and process().
_select_signal
bool larcv::NuFilter::_select_signal private
Definition at line 61 of file NuFilter.h.
Referenced by configure(), and process().
_selected
int larcv::NuFilter::_selected private
Definition at line 89 of file NuFilter.h.
Referenced by configure(), and process().
_subrun
int larcv::NuFilter::_subrun private
Definition at line 85 of file NuFilter.h.
Referenced by configure(), and process().
_true_roi_producer_name
std::string larcv::NuFilter::_true_roi_producer_name private
Definition at line 49 of file NuFilter.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
NuFilter.h
NuFilter.cxx