LArCV: larcv::EventBase Class Reference
larcv::EventBase Class Reference
Base class for an event data product (what is stored in output file), holding run/subrun/event ID + producer name.
#include <EventBase.h>
Public Member Functions
EventBase ()
Default constructor.
EventBase (const EventBase &rhs)
Copy ctor.
virtual ~EventBase ()
Default destructor.
virtual void clear ()
Set all run/subrun/event to kINVALID_SIZE.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::string _producer
Producer name string.
size_t _run
LArSoft run number.
size_t _subrun
LArSoft sub-run number.
size_t _event
LArSoft event number.
Friends
class IOManager
class DataProductFactory
Detailed Description
Base class for an event data product (what is stored in output file), holding run/subrun/event ID + producer name.
Definition at line 27 of file EventBase.h.
Constructor & Destructor Documentation
EventBase() [1/2]
larcv::EventBase::EventBase () inline
Default constructor.
Definition at line 33 of file EventBase.h.
                 :
       _run      (kINVALID_SIZE)
           , _subrun (kINVALID_SIZE)
           , _event  (kINVALID_SIZE)
     {}
EventBase() [2/2]
larcv::EventBase::EventBase (const EventBase & rhs) inline
Copy ctor.
Definition at line 39 of file EventBase.h.
                                     : _producer(rhs._producer)
                     , _run(rhs._run)
                     , _subrun(rhs._subrun)
                     , _event(rhs._event)
     {}
~EventBase()
virtual larcv::EventBase::~EventBase () inline virtual
Default destructor.
Definition at line 46 of file EventBase.h.
References clear().
 {}
Member Function Documentation
clear()
void larcv::EventBase::clear () virtual
Set all run/subrun/event to kINVALID_SIZE.
Reimplemented in larcv::EventPixel2D, larcv::EventChStatus, larcv::EventImage2D, larcv::EventVoxel3D, larcv::EventParticleROI, larcv::EventPGraph, and larcv::EventROI.
Definition at line 9 of file EventBase.cxx.
References _event, _run, _subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::EventParticleROI::clear(), larcv::EventPGraph::clear(), larcv::EventROI::clear(), larcv::EventVoxel3D::clear(), larcv::EventImage2D::clear(), larcv::EventChStatus::clear(), larcv::EventPixel2D::clear(), larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::set_id(), and ~EventBase().
   { _run = _subrun = _event = kINVALID_SIZE; }
event()
size_t larcv::EventBase::event () const inline
Event number getter.
Definition at line 56 of file EventBase.h.
References _event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), operator<(), operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References _event, _run, and _subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References _event, _run, _subrun, event(), event_key(), run(), and subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References _event, _run, _subrun, event(), run(), and subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
producer()
const std::string& larcv::EventBase::producer () const inline
Producer name getter.
Definition at line 50 of file EventBase.h.
References _producer.
 { return _producer; }
run()
size_t larcv::EventBase::run () const inline
Run number getter.
Definition at line 52 of file EventBase.h.
References _run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), operator<(), operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
subrun()
size_t larcv::EventBase::subrun () const inline
SubRun number getter.
Definition at line 54 of file EventBase.h.
References _subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), operator<(), operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References _event, _run, _subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Friends And Related Function Documentation
DataProductFactory
friend class DataProductFactory friend
Definition at line 29 of file EventBase.h.
IOManager
friend class IOManager friend
Definition at line 28 of file EventBase.h.
Member Data Documentation
_event
size_t larcv::EventBase::_event private
LArSoft event number.
Definition at line 85 of file EventBase.h.
Referenced by clear(), event(), event_key(), operator<(), operator==(), larcv::IOManager< T >::set_id(), and valid().
_producer
std::string larcv::EventBase::_producer private
Producer name string.
Definition at line 82 of file EventBase.h.
Referenced by producer().
_run
size_t larcv::EventBase::_run private
LArSoft run number.
Definition at line 83 of file EventBase.h.
Referenced by clear(), event_key(), operator<(), operator==(), run(), larcv::IOManager< T >::set_id(), and valid().
_subrun
size_t larcv::EventBase::_subrun private
LArSoft sub-run number.
Definition at line 84 of file EventBase.h.
Referenced by clear(), event_key(), operator<(), operator==(), larcv::IOManager< T >::set_id(), subrun(), and valid().
The documentation for this class was generated from the following files:
EventBase.h
EventBase.cxx