LArCV: larcv::CosmicPixelAna Class Reference
larcv::CosmicPixelAna Class Reference
#include <CosmicPixelAna.h>
Public Member Functions
CosmicPixelAna (const std::string name="CosmicPixelAna")
Default constructor.
~CosmicPixelAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
LArbysImageMaker _LArbysImageMaker
TTree * _tree
int _entry
int _run
int _subrun
int _event
std::string _ev_img2d_prod
std::string _seg_img2d_prod
std::string _thrumu_img_prod
std::string _stopmu_img_prod
std::string _true_roi_prod
std::string _roi_prod
size_t _crop_radius
ProductType_t _tags_datatype
int _nupixel0
int _nupixel1
int _nupixel2
int _cosmicpixel0
int _cosmicpixel1
int _cosmicpixel2
float _ratiopixel0
float _ratiopixel1
float _ratiopixel2
float _nupixelsum
float _nupixelavg
float _cosmicpixelsum
float _cosmicpixelavg
float _ratiopixelsum
float _ratiopixelavg
larutil::SpaceChargeMicroBooNE _sce
int _vertex_nupixel0
int _vertex_nupixel1
int _vertex_nupixel2
int _vertex_cosmicpixel0
int _vertex_cosmicpixel1
int _vertex_cosmicpixel2
float _vertex_ratiopixel0
float _vertex_ratiopixel1
float _vertex_ratiopixel2
float _vertex_nupixelsum
float _vertex_nupixelavg
float _vertex_cosmicpixelsum
float _vertex_cosmicpixelavg
float _vertex_ratiopixelsum
float _vertex_ratiopixelavg
int _nearest_wire_error
int _not_inside
Detailed Description
Definition at line 11 of file CosmicPixelAna.h.
Constructor & Destructor Documentation
CosmicPixelAna()
larcv::CosmicPixelAna::CosmicPixelAna (const std::string name = "CosmicPixelAna")
Default constructor.
Definition at line 18 of file CosmicPixelAna.cxx.
Referenced by larcv::CosmicPixelAnaProcessFactory::create().
                                                      :
     ProcessBase(name),
     _LArbysImageMaker(),
     _tree(nullptr)
   {}
~CosmicPixelAna()
larcv::CosmicPixelAna::~CosmicPixelAna () inline
Default destructor.
Definition at line 20 of file CosmicPixelAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::CosmicPixelAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 24 of file CosmicPixelAna.cxx.
References _crop_radius, _ev_img2d_prod, _LArbysImageMaker, _roi_prod, _seg_img2d_prod, _stopmu_img_prod, _tags_datatype, _thrumu_img_prod, _true_roi_prod, larcv::LArbysImageMaker::Configure(), and larcv::PSet::get().
Referenced by ~CosmicPixelAna().
   {
     _ev_img2d_prod   = cfg.get<std::string>("EventImage2DProducer");
     _seg_img2d_prod  = cfg.get<std::string>("SegmentImage2DProducer");
     _thrumu_img_prod = cfg.get<std::string>("ThruMuProducer");
     _stopmu_img_prod = cfg.get<std::string>("StopMuProducer");
     _roi_prod        = cfg.get<std::string>("ROIProducer");
     _true_roi_prod   = cfg.get<std::string>("TrueROIProducer");
     _crop_radius     = cfg.get<size_t>("CropRadius");
     auto tags_datatype        = cfg.get<size_t>("CosmicTagDataType");
     _tags_datatype = (ProductType_t) tags_datatype;
     _LArbysImageMaker.Configure(cfg.get<PSet>("LArbysImageMaker"));
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::CosmicPixelAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 389 of file CosmicPixelAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~CosmicPixelAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::CosmicPixelAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 39 of file CosmicPixelAna.cxx.
References _cosmicpixel0, _cosmicpixel1, _cosmicpixel2, _cosmicpixelavg, _cosmicpixelsum, _entry, _event, _nearest_wire_error, _not_inside, _nupixel0, _nupixel1, _nupixel2, _nupixelavg, _nupixelsum, _ratiopixel0, _ratiopixel1, _ratiopixel2, _ratiopixelavg, _ratiopixelsum, _run, _subrun, _tree, _vertex_cosmicpixel0, _vertex_cosmicpixel1, _vertex_cosmicpixel2, _vertex_cosmicpixelavg, _vertex_cosmicpixelsum, _vertex_nupixel0, _vertex_nupixel1, _vertex_nupixel2, _vertex_nupixelavg, _vertex_nupixelsum, _vertex_ratiopixel0, _vertex_ratiopixel1, _vertex_ratiopixel2, _vertex_ratiopixelavg, and _vertex_ratiopixelsum.
Referenced by ~CosmicPixelAna().
   {
     _tree = new TTree("EventCosmicPixelTree","");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("nupixel0",&_nupixel0,"nupixel0/I");
     _tree->Branch("nupixel1",&_nupixel1,"nupixel1/I");
     _tree->Branch("nupixel2",&_nupixel2,"nupixel2/I");
     _tree->Branch("nupixelsum",&_nupixelsum,"nupixelsum/F");
     _tree->Branch("nupixelavg",&_nupixelavg,"nupixelavg/F");
     _tree->Branch("cosmicpixel0",&_cosmicpixel0,"cosmicpixel0/I");
     _tree->Branch("cosmicpixel1",&_cosmicpixel1,"cosmicpixel1/I");
     _tree->Branch("cosmicpixel2",&_cosmicpixel2,"cosmicpixel2/I");
     _tree->Branch("cosmicpixelsum",&_cosmicpixelsum,"cosmicpixelsum/F");
     _tree->Branch("cosmicpixelavg",&_cosmicpixelavg,"cosmicpixelavg/F");
     _tree->Branch("ratiopixel0",&_ratiopixel0,"ratiopixel0/F");
     _tree->Branch("ratiopixel1",&_ratiopixel1,"ratiopixel1/F");
     _tree->Branch("ratiopixel2",&_ratiopixel2,"ratiopixel2/F");
     _tree->Branch("ratiopixelsum",&_ratiopixelsum,"ratiopixelsum/F");
     _tree->Branch("ratiopixelavg",&_ratiopixelavg,"ratiopixelavg/F");
     _tree->Branch("vertex_nupixel0",&_vertex_nupixel0,"vertex_nupixel0/I");
     _tree->Branch("vertex_nupixel1",&_vertex_nupixel1,"vertex_nupixel1/I");
     _tree->Branch("vertex_nupixel2",&_vertex_nupixel2,"vertex_nupixel2/I");
     _tree->Branch("vertex_nupixelsum",&_vertex_nupixelsum,"vertex_nupixelsum/F");
     _tree->Branch("vertex_nupixelavg",&_vertex_nupixelavg,"vertex_nupixelavg/F");
     _tree->Branch("vertex_cosmicpixel0",&_vertex_cosmicpixel0,"vertex_cosmicpixel0/I");
     _tree->Branch("vertex_cosmicpixel1",&_vertex_cosmicpixel1,"vertex_cosmicpixel1/I");
     _tree->Branch("vertex_cosmicpixel2",&_vertex_cosmicpixel2,"vertex_cosmicpixel2/I");
     _tree->Branch("vertex_cosmicpixelsum",&_vertex_cosmicpixelsum,"vertex_cosmicpixelsum/F");
     _tree->Branch("vertex_cosmicpixelavg",&_vertex_cosmicpixelavg,"vertex_cosmicpixelavg/F");
     _tree->Branch("vertex_ratiopixel0",&_vertex_ratiopixel0,"vertex_ratiopixel0/F");
     _tree->Branch("vertex_ratiopixel1",&_vertex_ratiopixel1,"vertex_ratiopixel1/F");
     _tree->Branch("vertex_ratiopixel2",&_vertex_ratiopixel2,"vertex_ratiopixel2/F");
     _tree->Branch("vertex_ratiopixelsum",&_vertex_ratiopixelsum,"vertex_ratiopixelsum/F");
     _tree->Branch("vertex_ratiopixelavg",&_vertex_ratiopixelavg,"vertex_ratiopixelavg/F");
     _tree->Branch("nearest_wire_error",&_nearest_wire_error,"nearest_wire_error/I");
     _tree->Branch("not_inside",&_not_inside,"not_inside/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::CosmicPixelAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 94 of file CosmicPixelAna.cxx.
References _cosmicpixel0, _cosmicpixel1, _cosmicpixel2, _cosmicpixelavg, _cosmicpixelsum, _crop_radius, _entry, _ev_img2d_prod, _event, _LArbysImageMaker, _nearest_wire_error, _not_inside, _nupixel0, _nupixel1, _nupixel2, _nupixelavg, _nupixelsum, _ratiopixel0, _ratiopixel1, _ratiopixel2, _ratiopixelavg, _ratiopixelsum, _roi_prod, _run, _sce, _seg_img2d_prod, _stopmu_img_prod, _subrun, _tags_datatype, _thrumu_img_prod, _tree, _true_roi_prod, _vertex_cosmicpixel0, _vertex_cosmicpixel1, _vertex_cosmicpixel2, _vertex_cosmicpixelavg, _vertex_cosmicpixelsum, _vertex_nupixel0, _vertex_nupixel1, _vertex_nupixel2, _vertex_nupixelavg, _vertex_nupixelsum, _vertex_ratiopixel0, _vertex_ratiopixel1, _vertex_ratiopixel2, _vertex_ratiopixelavg, _vertex_ratiopixelsum, larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kINVALID_FLOAT, larcv::kProductImage2D, larcv::kProductROI, LARCV_DEBUG, LARCV_INFO, and LARCV_WARNING.
Referenced by ~CosmicPixelAna().
   {
     if (_ev_img2d_prod.empty()) {
       LARCV_INFO() << "No event image provided nothing to do" << std::endl;
       return false;
     }
     auto const ev_img2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_img2d_prod));
     if (!ev_img2d) throw larbys("Invalid event image producer provided");
     if (_seg_img2d_prod.empty()) {
       LARCV_INFO() << "No segment image provided nothing to do" << std::endl;
       return false;
     }
     auto const seg_img2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_seg_img2d_prod));
     if (!seg_img2d) throw larbys("Invalid segment image producer provided");
     assert(ev_img2d->Image2DArray().size() == seg_img2d->Image2DArray().size());
     for(size_t img_id=0; img_id<ev_img2d->Image2DArray().size(); ++img_id) {
       const auto& ev_img  = ev_img2d->Image2DArray().at(img_id);
       const auto& seg_img = seg_img2d->Image2DArray().at(img_id);
       if (ev_img.meta().rows() != seg_img.meta().rows()) {
     LARCV_WARNING() << "Event image and segmentation image differ in row size @ plane=" << img_id
             << " ("<<ev_img.meta().rows()<<"!="<<seg_img.meta().rows()<<")"<<std::endl;
     return false;
       }
       if (ev_img.meta().cols() != seg_img.meta().cols()) {
     LARCV_WARNING() << "Event image and segmentation image differ in col size @ plane=" << img_id
             << " ("<<ev_img.meta().cols()<<"!="<<seg_img.meta().cols()<<")"<<std::endl;
     return false;
       }
     }
     // auto const ev_thrumu = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_thrumu_img_prod));
     // if (!ev_thrumu) throw larbys("Invalid ThruMu producer provided!");
     // auto const ev_stopmu = (EventPixel2D*)(mgr.get_data(kProductPixel2D,_stopmu_img_prod));
     // if (!ev_stopmu) throw larbys("Invalid StopMu producer provided!");
     auto const ev_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_prod));
     if (!ev_roi) throw larbys("Invalid ROI producer provided!");
     auto const ev_true_roi = (EventROI*)(mgr.get_data(kProductROI,_true_roi_prod));
     if (!ev_true_roi) throw larbys("Invalid True ROI producer provided!");
     const auto& roi = ev_roi->ROIArray().front();
     _run    = (int) ev_img2d->run();
     _subrun = (int) ev_img2d->subrun();
     _event  = (int) ev_img2d->event();
     _entry  = (int) mgr.current_entry();
     LARCV_DEBUG() << "(r,s,e,e)=("<<_run<<","<<_subrun<<","<<_event<<","<<_entry<<")"<<std::endl;
     std::array<size_t,3> neutrino_pixel_v;
     std::array<size_t,3> cosmic_pixel_v;
     std::array<size_t,3> vertex_neutrino_pixel_v;
     std::array<size_t,3> vertex_cosmic_pixel_v;
     const auto& nu_roi = ev_true_roi->ROIArray().front();
     LARCV_DEBUG() << "PDG: " << nu_roi.PdgCode() << std::endl;
     auto tx = nu_roi.X();
     auto ty = nu_roi.Y();
     auto tz = nu_roi.Z();
     auto tt = nu_roi.T();
     auto const offset = _sce.GetPosOffsets(tx,ty,tz);
     auto scex = tx - offset[0] + 0.7;
     auto scey = ty + offset[1];
     auto scez = tz + offset[2];
     LARCV_DEBUG() << "(x,y,z,t)==>sce(x,y,z,t) : ("<<tx<<","<<ty<<","<<tz<<","<<tt<<")==>("<<scex<<","<<scey<<","<<scez<<","<<tt<<")"<<std::endl;
     auto geo  = larutil::Geometry::GetME();
     auto larp = larutil::LArProperties::GetME();
     double xyz[3];
     double wire_v[3];
     const double tick = (scex / larp->DriftVelocity() + 4) * 2. + 3200.;
     xyz[0] = scex;
     xyz[1] = scey;
     xyz[2] = scez;
     _nearest_wire_error = 0;
     try {
       wire_v[0] = geo->NearestWire(xyz,0);
       wire_v[1] = geo->NearestWire(xyz,1);
       wire_v[2] = geo->NearestWire(xyz,2);
     } catch(const std::exception& e) {
       _tree->Fill();
       _nearest_wire_error=1;
       return true;
     }
     std::vector<larcv::Image2D> thrumu_img2d_v;
     std::vector<larcv::Image2D> stopmu_img2d_v;
     _LArbysImageMaker.ConstructCosmicImage(mgr,_thrumu_img_prod,_tags_datatype,seg_img2d->Image2DArray(),thrumu_img2d_v);
     _LArbysImageMaker.ConstructCosmicImage(mgr,_stopmu_img_prod,_tags_datatype,seg_img2d->Image2DArray(),stopmu_img2d_v);
     _not_inside = 0;
     for (size_t plane=0; plane<3; ++plane) {
       const auto& img2d = seg_img2d->Image2DArray().at(plane);
       const auto& thrumu_img2d = thrumu_img2d_v[plane];
       const auto& stopmu_img2d = stopmu_img2d_v[plane];
       const auto& bb = roi.BB(plane);
       auto const& wire = wire_v[plane];
       float xpixel = -1.0;
       float ypixel = -1.0;
       if( bb.min_x() <= wire && wire <= bb.max_x() &&
       bb.min_y() <= tick && tick <= bb.max_y() ) {
     xpixel = wire - bb.min_x();
     ypixel = (tick - bb.min_y()) / 6.0;
     LARCV_DEBUG() << "Set (xpixel,ypixel)=("<<xpixel<<","<<ypixel<<")"<<std::endl;
       } else {
     _tree->Fill();
     _not_inside = 1;
     return true;
       }
       auto crop_img2d  = img2d.crop(bb);
       auto crop_thrumu = thrumu_img2d.crop(bb);
       auto crop_stopmu = stopmu_img2d.crop(bb);
       auto crop_cosmic_img = crop_thrumu;
       crop_cosmic_img += crop_stopmu;
       crop_cosmic_img.eltwise(crop_img2d);
       size_t cosmic_pixels = 0;
       size_t neutrino_pixels = 0;
       size_t vertex_cosmic_pixels = 0;
       size_t vertex_neutrino_pixels = 0;
       assert(crop_cosmic_img.as_vector().size() == crop_img2d.as_vector().size());
       float x;
       float y;
       float d;
       x = kINVALID_FLOAT;
       y = kINVALID_FLOAT;
       d = kINVALID_FLOAT;
       LARCV_DEBUG()<<"loop @ plane="<<plane<<"(row,col)==("<<crop_cosmic_img.meta().rows()<<","<<crop_cosmic_img.meta().cols()<<")"<<std::endl;
       LARCV_DEBUG() << std::endl;
       ypixel = crop_cosmic_img.meta().rows() - ypixel;
       /*
       auto mat0 = as_gray_mat(crop_img2d,0,255,1);
       auto mat1 = as_gray_mat(crop_cosmic_img,0,255,1);
       cv::threshold(mat0,mat0,1,255,1);
       cv::threshold(mat1,mat1,1,255,1);
       auto mat2 = mat1.clone();
       mat2.setTo(cv::Scalar(255.0));
       mat2.at<uchar>((int)ypixel,(int)xpixel) = (uchar)0.0;
       if (plane==0) {
     cv::imwrite("out0.png"   ,mat0);
     cv::imwrite("cosmic0.png",mat1);
     cv::imwrite("vtx0.png"   ,mat2);
       }
       if (plane==1) {
     cv::imwrite("out1.png"   ,mat0);
     cv::imwrite("cosmic1.png",mat1);
     cv::imwrite("vtx1.png"   ,mat2);
       }
       if (plane==2) {
     cv::imwrite("out2.png"   ,mat0);
     cv::imwrite("cosmic2.png",mat1);
     cv::imwrite("vtx2.png"   ,mat2);
       }
       */
       for(size_t row=0; row < crop_cosmic_img.meta().rows(); ++row) {
     for(size_t col=0; col < crop_cosmic_img.meta().cols(); ++col) {
       auto cosmic_px   = crop_cosmic_img.pixel(row,col);
       auto neutrino_px = crop_img2d.pixel(row,col);
       if (cosmic_px)   cosmic_pixels++;
       if (neutrino_px) neutrino_pixels++;
       float dx = std::pow((float)row - (float)ypixel,2);
       float dy = std::pow((float)col - (float)xpixel,2);
       float dd =  dx + dy;
       dd = std::sqrt(dd);
       if (dd < d) d = dd;
       if (dx < x) x = dx;
       if (dy < y) y = dy;
       if (dd < (float)_crop_radius) {
         if (cosmic_px)   vertex_cosmic_pixels++;
         if (neutrino_px) vertex_neutrino_pixels++;
       }
     }
       }
       LARCV_DEBUG() << "@ plane="<<plane << " min d was " << d << std::endl;
       LARCV_DEBUG() << "@ plane="<<plane << " min x was " << x << std::endl;
       LARCV_DEBUG() << "@ plane="<<plane << " min y was " << y << std::endl;
       LARCV_DEBUG() << "@ plane="<<plane << " vtx co px " << vertex_cosmic_pixels << std::endl;
       LARCV_DEBUG() << "@ plane="<<plane << " vtx nu px " << vertex_neutrino_pixels << std::endl;
       if (d > (float)_crop_radius) throw larbys("Vertex not in ROI");
       cosmic_pixel_v[plane] = cosmic_pixels;
       neutrino_pixel_v[plane] = neutrino_pixels;
       vertex_cosmic_pixel_v[plane] = vertex_cosmic_pixels;
       vertex_neutrino_pixel_v[plane] = vertex_neutrino_pixels;
     }
     // if (_entry==41) std::exit(1);
     //
     // ROI region
     //
     _nupixel0 = neutrino_pixel_v[0];
     _nupixel1 = neutrino_pixel_v[1];
     _nupixel2 = neutrino_pixel_v[2];
     _cosmicpixel0 = cosmic_pixel_v[0];
     _cosmicpixel1 = cosmic_pixel_v[1];
     _cosmicpixel2 = cosmic_pixel_v[2];
     _ratiopixel0 = _nupixel0 ? (float)_cosmicpixel0 / (float)_nupixel0 : 0;
     _ratiopixel1 = _nupixel1 ? (float)_cosmicpixel1 / (float)_nupixel1 : 0;
     _ratiopixel2 = _nupixel2 ? (float)_cosmicpixel2 / (float)_nupixel2 : 0;
     _nupixelsum = _nupixel0 + _nupixel1 + _nupixel2;
     _nupixelavg = _nupixelsum / 3.0;
     _cosmicpixelsum = _cosmicpixel0 + _cosmicpixel1 + _cosmicpixel2;
     _cosmicpixelavg = _cosmicpixelsum / 3.0;
     _ratiopixelsum = _ratiopixel0 + _ratiopixel1 + _ratiopixel2;
     _ratiopixelavg = _ratiopixelsum / 3.0;
     //
     // Vertex Region
     //
     _vertex_nupixel0 = vertex_neutrino_pixel_v[0];
     _vertex_nupixel1 = vertex_neutrino_pixel_v[1];
     _vertex_nupixel2 = vertex_neutrino_pixel_v[2];
     _vertex_cosmicpixel0 = vertex_cosmic_pixel_v[0];
     _vertex_cosmicpixel1 = vertex_cosmic_pixel_v[1];
     _vertex_cosmicpixel2 = vertex_cosmic_pixel_v[2];
     _vertex_ratiopixel0 = _vertex_nupixel0 ? (float)_vertex_cosmicpixel0 / (float)_vertex_nupixel0 : 0;
     _vertex_ratiopixel1 = _vertex_nupixel1 ? (float)_vertex_cosmicpixel1 / (float)_vertex_nupixel1 : 0;
     _vertex_ratiopixel2 = _vertex_nupixel2 ? (float)_vertex_cosmicpixel2 / (float)_vertex_nupixel2 : 0;
     _vertex_nupixelsum = _vertex_nupixel0 + _vertex_nupixel1 + _vertex_nupixel2;
     _vertex_nupixelavg = _vertex_nupixelsum / 3.0;
     _vertex_cosmicpixelsum = _vertex_cosmicpixel0 + _vertex_cosmicpixel1 + _vertex_cosmicpixel2;
     _vertex_cosmicpixelavg = _vertex_cosmicpixelsum / 3.0;
     _vertex_ratiopixelsum = _vertex_ratiopixel0 + _vertex_ratiopixel1 + _vertex_ratiopixel2;
     _vertex_ratiopixelavg = _vertex_ratiopixelsum / 3.0;
     _tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_cosmicpixel0
int larcv::CosmicPixelAna::_cosmicpixel0 private
Definition at line 58 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_cosmicpixel1
int larcv::CosmicPixelAna::_cosmicpixel1 private
Definition at line 59 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_cosmicpixel2
int larcv::CosmicPixelAna::_cosmicpixel2 private
Definition at line 60 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_cosmicpixelavg
float larcv::CosmicPixelAna::_cosmicpixelavg private
Definition at line 70 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_cosmicpixelsum
float larcv::CosmicPixelAna::_cosmicpixelsum private
Definition at line 69 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_crop_radius
size_t larcv::CosmicPixelAna::_crop_radius private
Definition at line 48 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_entry
int larcv::CosmicPixelAna::_entry private
Definition at line 37 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ev_img2d_prod
std::string larcv::CosmicPixelAna::_ev_img2d_prod private
Definition at line 42 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_event
int larcv::CosmicPixelAna::_event private
Definition at line 40 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_LArbysImageMaker
LArbysImageMaker larcv::CosmicPixelAna::_LArbysImageMaker private
Definition at line 32 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_nearest_wire_error
int larcv::CosmicPixelAna::_nearest_wire_error private
Definition at line 106 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_not_inside
int larcv::CosmicPixelAna::_not_inside private
Definition at line 107 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_nupixel0
int larcv::CosmicPixelAna::_nupixel0 private
Definition at line 54 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_nupixel1
int larcv::CosmicPixelAna::_nupixel1 private
Definition at line 55 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_nupixel2
int larcv::CosmicPixelAna::_nupixel2 private
Definition at line 56 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_nupixelavg
float larcv::CosmicPixelAna::_nupixelavg private
Definition at line 67 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_nupixelsum
float larcv::CosmicPixelAna::_nupixelsum private
Definition at line 66 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ratiopixel0
float larcv::CosmicPixelAna::_ratiopixel0 private
Definition at line 62 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ratiopixel1
float larcv::CosmicPixelAna::_ratiopixel1 private
Definition at line 63 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ratiopixel2
float larcv::CosmicPixelAna::_ratiopixel2 private
Definition at line 64 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ratiopixelavg
float larcv::CosmicPixelAna::_ratiopixelavg private
Definition at line 73 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_ratiopixelsum
float larcv::CosmicPixelAna::_ratiopixelsum private
Definition at line 72 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_roi_prod
std::string larcv::CosmicPixelAna::_roi_prod private
Definition at line 47 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_run
int larcv::CosmicPixelAna::_run private
Definition at line 38 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_sce
larutil::SpaceChargeMicroBooNE larcv::CosmicPixelAna::_sce private
Definition at line 79 of file CosmicPixelAna.h.
Referenced by process().
_seg_img2d_prod
std::string larcv::CosmicPixelAna::_seg_img2d_prod private
Definition at line 43 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_stopmu_img_prod
std::string larcv::CosmicPixelAna::_stopmu_img_prod private
Definition at line 45 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_subrun
int larcv::CosmicPixelAna::_subrun private
Definition at line 39 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_tags_datatype
ProductType_t larcv::CosmicPixelAna::_tags_datatype private
Definition at line 49 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_thrumu_img_prod
std::string larcv::CosmicPixelAna::_thrumu_img_prod private
Definition at line 44 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_tree
TTree* larcv::CosmicPixelAna::_tree private
Definition at line 34 of file CosmicPixelAna.h.
Referenced by finalize(), initialize(), and process().
_true_roi_prod
std::string larcv::CosmicPixelAna::_true_roi_prod private
Definition at line 46 of file CosmicPixelAna.h.
Referenced by configure(), and process().
_vertex_cosmicpixel0
int larcv::CosmicPixelAna::_vertex_cosmicpixel0 private
Definition at line 85 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_cosmicpixel1
int larcv::CosmicPixelAna::_vertex_cosmicpixel1 private
Definition at line 86 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_cosmicpixel2
int larcv::CosmicPixelAna::_vertex_cosmicpixel2 private
Definition at line 87 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_cosmicpixelavg
float larcv::CosmicPixelAna::_vertex_cosmicpixelavg private
Definition at line 97 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_cosmicpixelsum
float larcv::CosmicPixelAna::_vertex_cosmicpixelsum private
Definition at line 96 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_nupixel0
int larcv::CosmicPixelAna::_vertex_nupixel0 private
Definition at line 81 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_nupixel1
int larcv::CosmicPixelAna::_vertex_nupixel1 private
Definition at line 82 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_nupixel2
int larcv::CosmicPixelAna::_vertex_nupixel2 private
Definition at line 83 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_nupixelavg
float larcv::CosmicPixelAna::_vertex_nupixelavg private
Definition at line 94 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_nupixelsum
float larcv::CosmicPixelAna::_vertex_nupixelsum private
Definition at line 93 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_ratiopixel0
float larcv::CosmicPixelAna::_vertex_ratiopixel0 private
Definition at line 89 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_ratiopixel1
float larcv::CosmicPixelAna::_vertex_ratiopixel1 private
Definition at line 90 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_ratiopixel2
float larcv::CosmicPixelAna::_vertex_ratiopixel2 private
Definition at line 91 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_ratiopixelavg
float larcv::CosmicPixelAna::_vertex_ratiopixelavg private
Definition at line 100 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
_vertex_ratiopixelsum
float larcv::CosmicPixelAna::_vertex_ratiopixelsum private
Definition at line 99 of file CosmicPixelAna.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
CosmicPixelAna.h
CosmicPixelAna.cxx