LArCV: supera::ParamsVoxel3D Class Reference
supera::ParamsVoxel3D Class Reference
User defined class ParamsVoxel3D ...
#include <ParamsVoxel3D.h>
Public Member Functions
ParamsVoxel3D ()
Default constructor.
~ParamsVoxel3D ()
Default destructor.
void configure (const supera::Config_t &)
const std::string & OutVoxel3DLabel () const
Private Attributes
std::string _out_voxel3d_producer
Detailed Description
User defined class ParamsVoxel3D ...
these comments are used to generate doxygen documentation!
Definition at line 26 of file ParamsVoxel3D.h.
Constructor & Destructor Documentation
ParamsVoxel3D()
supera::ParamsVoxel3D::ParamsVoxel3D () inline
Default constructor.
Definition at line 31 of file ParamsVoxel3D.h.
 {}
~ParamsVoxel3D()
supera::ParamsVoxel3D::~ParamsVoxel3D () inline
Default destructor.
Definition at line 34 of file ParamsVoxel3D.h.
References configure().
 {}
Member Function Documentation
configure()
void supera::ParamsVoxel3D::configure (const supera::Config_t & cfg)
Definition at line 8 of file ParamsVoxel3D.cxx.
References _out_voxel3d_producer, and larcv::PSet::get().
Referenced by larcv::SuperaSimVoxel3D::configure(), and ~ParamsVoxel3D().
   {
     _out_voxel3d_producer  = cfg.get<std::string>("OutVoxel3DLabel",  "");
   }
OutVoxel3DLabel()
const std::string& supera::ParamsVoxel3D::OutVoxel3DLabel () const inline
Definition at line 41 of file ParamsVoxel3D.h.
References _out_voxel3d_producer.
Referenced by larcv::SuperaSimVoxel3D::process().
 { return _out_voxel3d_producer;  }
Member Data Documentation
_out_voxel3d_producer
std::string supera::ParamsVoxel3D::_out_voxel3d_producer private
Definition at line 45 of file ParamsVoxel3D.h.
Referenced by configure(), and OutVoxel3DLabel().
The documentation for this class was generated from the following files:
ParamsVoxel3D.h
ParamsVoxel3D.cxx