LArCV: larcv::ProcessBase Class Reference
larcv::ProcessBase Class Reference abstract
User defined class ProcessBase ...
#include <ProcessBase.h>
Public Member Functions
ProcessBase (const std::string name="ProcessBase")
Default constructor.
virtual ~ProcessBase ()
Default destructor.
virtual void configure (const PSet &)=0
virtual void initialize ()=0
virtual bool process (IOManager &mgr)=0
virtual void finalize ()=0
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void _configure_ (const PSet &)
bool _process_ (IOManager &mgr)
Private Attributes
bool _event_creator
special flag to mark this algorithm an event creator
larcv::Watch _watch
algorithm profile stopwatch
double _proc_time
algorithm execution time record (cumulative)
size_t _proc_count
algorithm execution counter (cumulative)
larcv::ProcessID_t _id
unique algorithm identifier
bool _profile
measure process time if profile flag is on
std::string _typename
process type from factory
TFile * _fout
output analysis file
Friends
class ProcessDriver
class ProcessFactory
Detailed Description
User defined class ProcessBase ...
User defined class VertexImg ...
User defined class ChStatusConverter ...
User defined class Pass ...
User defined class Run3DTracker ...
User defined class ReadJarrettFile ...
User defined class ReadRuiFile ...
User defined class SimplePixelAna ...
User defined class DoNothing ...
User defined class ImageMerger ...
User defined class ImageHolder ...
User defined class DataStream ...
User defined class SuperaWire ...
User defined class SuperaSimVoxel3D ...
User defined class SuperaSimCh ...
User defined class SuperaOpDigit ...
User defined class SuperaMetaMaker ...
User defined class SuperaMCROI ...
User defined class SuperaMCPCluster ...
User defined class SuperaKeyPointCluster ...
User defined class SuperaHit ...
User defined class SuperaChStatus ...
User defined class SuperaBase ...
User defined class SingleROIFaker ...
User defined class SegmentFilter ...
User defined class ROIAna ...
User defined class PIDImageMaker ...
User defined class OperateImage ...
User defined class LArbysImageMC ...
User defined class ImageROICheckMC ...
User defined class GoodcROIFilter ...
User defined class GenDeadChannelMap ...
User defined class CosmicVertexAna ...
User defined class CosmicTrackAna ...
User defined class BlankImage ...
User defined class BadRegionAna ...
User defined class PreProcessorAna ...
User defined class LArbysImagePID ...
User defined class StepDigitizer ...
User defined class SliceImages ...
User defined class SimpleDigitizer ...
User defined class SegWeightTrackShower ...
User defined class SegWeightInstance ...
User defined class SegmentRelabel ...
User defined class SegmentMask ...
User defined class SegmentMaker ...
User defined class SegmentAna ...
User defined class ROIMerger ...
User defined class ROIMask ...
User defined class ResizeImage ...
User defined class PlaneImageMerger ...
User defined class MultiROICropper ...
User defined class ModularPadImage ...
User defined class MeanSubtraction ...
User defined class MaskImage ...
User defined class ImageFromPixel2DCluster ...
User defined class ImageFromPixel2D ...
User defined class ImageChargeAna ...
User defined class EmbedImage ...
User defined class CropROI ...
User defined class CosmicROIFiller ...
User defined class Compressor ...
User defined class CombineImages ...
User defined class ChannelMax ...
User defined class Binarize ...
User defined class ADCThreshold ...
User defined class ADCScaleAna ...
User defined class ADCScale ...
User defined class SegImageAna ...
User defined class HistADC ...
User defined class DumpHiResCropImages ...
User defined class CosmicSegment ...
User defined class VtxInRegion ...
User defined class RSEFilter ...
User defined class ROISizeFilter ...
User defined class ROICountFilter ...
User defined class QSumFilter ...
User defined class NuFilter ...
User defined class MCSingleParticleFilter ...
User defined class MCFilter ...
User defined class EmptyImageFilter ...
User defined class CosmicFilter ...
User defined class CCQETruthFilter ...
User defined class CCIncFilter ...
User defined class NNCosine ...
User defined class DBSCAN ...
User defined class calcPeakADC ...
User defined class SimpleFiller ...
User defined class SegFiller ...
User defined class MultiClassFiller ...
User defined class DatumFillerBase ...
User defined class SegDatumFillerBase ...
User defined class PyImageStitcher ...
User defined class PyImageMaker ...
User defined class RunFilter ...
these comments are used to generate doxygen documentation!
Definition at line 29 of file ProcessBase.h.
Constructor & Destructor Documentation
ProcessBase()
ProcessBase::ProcessBase (const std::string name = "ProcessBase")
Default constructor.
Definition at line 8 of file ProcessBase.cxx.
     : larcv_base  ( name )
     , _proc_time  ( 0. )
     , _proc_count ( 0  )
     , _id         ( kINVALID_SIZE )
     , _profile    ( false )
     , _fout       ( nullptr )
   {}
~ProcessBase()
virtual larcv::ProcessBase::~ProcessBase () inline virtual
Default destructor.
Definition at line 39 of file ProcessBase.h.
References configure(), finalize(), initialize(), is(), and process().
 {}
Member Function Documentation
_configure_()
void ProcessBase::_configure_ (const PSet & cfg) private
Definition at line 20 of file ProcessBase.cxx.
References _event_creator, _profile, configure(), larcv::PSet::get(), and larcv::larcv_base::set_verbosity().
Referenced by ana_file(), and larcv::ThreadDatumFiller::configure().
   {
     _profile = cfg.get<bool>("Profile",_profile);
     set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     _event_creator=cfg.get<bool>("EventCreator",false);
     configure(cfg);
   }
_process_()
bool ProcessBase::_process_ (IOManager & mgr) private
Definition at line 28 of file ProcessBase.cxx.
References _proc_count, _proc_time, _profile, _watch, process(), larcv::Watch::Start(), and larcv::Watch::WallTime().
Referenced by ana_file().
   {
     bool status=false;
     if(_profile) {
       _watch.Start();
       status = this->process(mgr);
       _proc_time += _watch.WallTime();
       ++_proc_count;
     }else status = this->process(mgr);
     return status;
   }
ana_file()
TFile& larcv::ProcessBase::ana_file () inline
Definition at line 57 of file ProcessBase.h.
References _configure_(), _fout, and _process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
virtual void larcv::ProcessBase::configure (const PSet &) pure virtual
Implemented in larcv::RSEFilter, larcv::ReadJarrettFile, larcv::hires::HiResImageDivider, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::LArbysImagePID, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::GoodcROIFilter, larcv::OperateImage, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::NuFilter, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::BadRegionAna, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LArbysImage, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by _configure_(), and ~ProcessBase().
event_creator()
bool larcv::ProcessBase::event_creator () const inline
Definition at line 51 of file ProcessBase.h.
References _event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
virtual void larcv::ProcessBase::finalize () pure virtual
Implemented in larcv::RSEFilter, larcv::TrackerEventDisplay, larcv::Run3DTracker, larcv::ReadJarrettFile, larcv::hires::HiResImageDivider, larcv::DatumFillerBase, larcv::ImageROICheckMC, larcv::PIDImageMaker, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::ReadRuiFile, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::GoodcROIFilter, larcv::OperateImage, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::NuFilter, larcv::WireMask, larcv::BadRegionAna, larcv::LArbysImageMC, larcv::LArbysImage, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by ~ProcessBase().
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline
Definition at line 54 of file ProcessBase.h.
References _fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
virtual void larcv::ProcessBase::initialize () pure virtual
Implemented in larcv::RSEFilter, larcv::hires::HiResImageDivider, larcv::ReadJarrettFile, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::GoodcROIFilter, larcv::OperateImage, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::NuFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::BadRegionAna, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LArbysImage, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by ~ProcessBase().
is()
bool ProcessBase::is (const std::string question) const virtual
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and ~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
virtual bool larcv::ProcessBase::process (IOManager & mgr) pure virtual
Implemented in larcv::RSEFilter, larcv::hires::HiResImageDivider, larcv::DatumFillerBase, larcv::PIDImageMaker, larcv::ReadJarrettFile, larcv::LArbysImagePID, larcv::SuperaMCROI, larcv::Run3DTracker, larcv::TrackerEventDisplay, larcv::SuperaHit, larcv::SegmentRelabel, larcv::SuperaKeyPointCluster, larcv::SuperaWire, larcv::pmtweights::PMTWeightImageBuilder, larcv::calcPeakADC, larcv::HistADC, larcv::ROIMask, larcv::ImageROICheckMC, larcv::SuperaBase, larcv::SuperaOpDigit, larcv::SuperaSimCh, larcv::SuperaSimVoxel3D, larcv::SegDatumFillerBase, larcv::NNCosine, larcv::Binarize, larcv::ROIAna, larcv::CosmicFilter, larcv::VtxInRegion, larcv::DumpHiResCropImages, larcv::EmbedImage, larcv::CosmicVertexAna, larcv::GenDeadChannelMap, larcv::SuperaChStatus, larcv::VertexImg, larcv::PyImageMaker, larcv::PyImageStitcher, larcv::ADCScale, larcv::PlaneImageMerger, larcv::PreProcessorAna, larcv::GoodcROIFilter, larcv::OperateImage, larcv::ReadRuiFile, larcv::CCQETruthFilter, larcv::ADCScaleAna, larcv::Compressor, larcv::ImageChargeAna, larcv::MeanSubtraction, larcv::MultiROICropper, larcv::SegmentMaker, larcv::SuperaMCPCluster, larcv::SuperaMetaMaker, larcv::ImageMerger, larcv::ChStatusConverter, larcv::RunFilter, larcv::DBSCAN, larcv::CCIncFilter, larcv::EmptyImageFilter, larcv::MCFilter, larcv::MCSingleParticleFilter, larcv::NuFilter, larcv::QSumFilter, larcv::ROICountFilter, larcv::ROISizeFilter, larcv::CosmicSegment, larcv::SegImageAna, larcv::ADCThreshold, larcv::ChannelMax, larcv::CombineImages, larcv::CosmicROIFiller, larcv::CropROI, larcv::ImageFromPixel2D, larcv::ImageFromPixel2DCluster, larcv::MaskImage, larcv::ModularPadImage, larcv::ResizeImage, larcv::ROIMerger, larcv::SegmentAna, larcv::SegmentMask, larcv::SegWeightInstance, larcv::SegWeightTrackShower, larcv::SimpleDigitizer, larcv::SliceImages, larcv::StepDigitizer, larcv::BadRegionAna, larcv::BlankImage, larcv::CosmicTrackAna, larcv::SegmentFilter, larcv::SingleROIFaker, larcv::DataStream, larcv::DoNothing, larcv::SimplePixelAna, larcv::Pass, larcv::WireMask, larcv::LArbysImageMC, larcv::LArbysImage, larcv::LArbysImageOut, larcv::ParticleAna, larcv::ExampleAna, larcv::LEE1e1pAna, larcv::VertexAna, larcv::CosmicPixelAna, larcv::SSNetTruthAna, larcv::LArbysImageExtract, larcv::UnionROI, larcv::LArbysImageAna, larcv::SSNetEventAna, larcv::DeadWireAna, larcv::ReadNueFile, larcv::ROIPad, larcv::AlgoDataAna, larcv::LArbysImageFilter, larcv::VertexFilter, larcv::VertexInROI, larcv::ROIClipper, larcv::LArbysTrash, and larcv::PGraphTruthMatch.
Referenced by _process_(), and ~ProcessBase().
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by _configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Friends And Related Function Documentation
ProcessDriver
friend class ProcessDriver friend
Definition at line 30 of file ProcessBase.h.
ProcessFactory
friend class ProcessFactory friend
Definition at line 31 of file ProcessBase.h.
Member Data Documentation
_event_creator
bool larcv::ProcessBase::_event_creator private
special flag to mark this algorithm an event creator
Definition at line 66 of file ProcessBase.h.
Referenced by _configure_(), and event_creator().
_fout
TFile* larcv::ProcessBase::_fout private
output analysis file
Definition at line 76 of file ProcessBase.h.
Referenced by ana_file(), and has_ana_file().
_id
larcv::ProcessID_t larcv::ProcessBase::_id private
unique algorithm identifier
Definition at line 73 of file ProcessBase.h.
Referenced by larcv::ProcessDriver::configure().
_proc_count
size_t larcv::ProcessBase::_proc_count private
algorithm execution counter (cumulative)
Definition at line 71 of file ProcessBase.h.
Referenced by _process_().
_proc_time
double larcv::ProcessBase::_proc_time private
algorithm execution time record (cumulative)
Definition at line 70 of file ProcessBase.h.
Referenced by _process_().
_profile
bool larcv::ProcessBase::_profile private
measure process time if profile flag is on
Definition at line 74 of file ProcessBase.h.
Referenced by _configure_(), and _process_().
_typename
std::string larcv::ProcessBase::_typename private
process type from factory
Definition at line 75 of file ProcessBase.h.
_watch
larcv::Watch larcv::ProcessBase::_watch private
algorithm profile stopwatch
Definition at line 68 of file ProcessBase.h.
Referenced by _process_().
The documentation for this class was generated from the following files:
ProcessBase.h
ProcessBase.cxx