LArCV: larcv::hires::DivisionDef Class Reference
larcv::hires::DivisionDef Class Reference
#include <DivisionDef.h>
Public Member Functions
DivisionDef (int plane0_wirebounds[], int plane1_wirebounds[], int plane2_wirebounds[], int tickbounds[], float det_xbounds[], float det_ybounds[], float det_zbounds[])
DivisionDef (const DivisionDef &)
DivisionDef ()
~DivisionDef ()
const larcv::ImageMeta & getPlaneMeta (larcv::PlaneID_t plane) const
bool isInsideDetRegion (float x, float y, float z) const
bool operator< (const DivisionDef &rhs) const
const DivisionID & ID () const
void print () const
Protected Member Functions
void setPlaneMeta (larcv::PlaneID_t plane, int wirebounds[], int tickbounds[])
Protected Attributes
int mNPlanes
std::map< larcv::PlaneID_t, larcv::ImageMeta > m_planeMeta
float fDetBounds [3][2]
size_t fDivisionIDX
size_t fDivisionIDY
size_t fDivisionIDZ
DivisionID fID
Detailed Description
Definition at line 55 of file DivisionDef.h.
Constructor & Destructor Documentation
DivisionDef() [1/3]
larcv::hires::DivisionDef::DivisionDef (int plane0_wirebounds[], int plane1_wirebounds[], int plane2_wirebounds[], int tickbounds[], float det_xbounds[], float det_ybounds[], float det_zbounds[])
Definition at line 8 of file DivisionDef.cxx.
References fDetBounds, mNPlanes, and setPlaneMeta().
       : fID(plane0_wirebounds[0],plane0_wirebounds[1],
         plane1_wirebounds[0],plane1_wirebounds[1],
         plane2_wirebounds[0],plane2_wirebounds[1],
         tickbounds[0],tickbounds[1])
     {
     // this constructor completely defines the definition (for 3 planes)
       mNPlanes = 0;
       setPlaneMeta( 0, plane0_wirebounds, tickbounds );
       setPlaneMeta( 1, plane1_wirebounds, tickbounds );
       setPlaneMeta( 2, plane2_wirebounds, tickbounds );
       for (int i=0; i<2; i++) {
     fDetBounds[0][i] = det_xbounds[i];
     fDetBounds[1][i] = det_ybounds[i];
     fDetBounds[2][i] = det_zbounds[i];
       }
     }
DivisionDef() [2/3]
larcv::hires::DivisionDef::DivisionDef (const DivisionDef & src)
Definition at line 27 of file DivisionDef.cxx.
References fDetBounds, and m_planeMeta.
       : fID(src.fID)
     {
       for ( std::map< larcv::PlaneID_t, larcv::ImageMeta >::const_iterator it=src.m_planeMeta.begin(); it!=src.m_planeMeta.end(); it++ ) {
     m_planeMeta[ (*it).first ] = (*it).second; // implied copy?
       }
       for (int i=0; i<2; i++)
     for (int j=0; j<3; j++)
       fDetBounds[j][i] = src.fDetBounds[j][i];
     }
DivisionDef() [3/3]
larcv::hires::DivisionDef::DivisionDef () inline
Definition at line 60 of file DivisionDef.h.
 : fID(0,0,0,0,0,0,0,0) {};
~DivisionDef()
larcv::hires::DivisionDef::~DivisionDef () inline
Definition at line 61 of file DivisionDef.h.
 {};
Member Function Documentation
getPlaneMeta()
const larcv::ImageMeta & larcv::hires::DivisionDef::getPlaneMeta (larcv::PlaneID_t plane) const
Definition at line 38 of file DivisionDef.cxx.
References m_planeMeta.
Referenced by larcv::hires::HiResImageDivider::cropEventImages().
{
       std::map< larcv::PlaneID_t, larcv::ImageMeta >::const_iterator it=m_planeMeta.find( plane );
       if ( it==m_planeMeta.end() )
     throw larcv::larbys("Did not have a division Image meta for plane.");
       return (*it).second;
     }
ID()
const DivisionID& larcv::hires::DivisionDef::ID () const inline
Definition at line 68 of file DivisionDef.h.
Referenced by larcv::hires::HiResImageDivider::CalculateDivisions(), and larcv::hires::HiResImageDivider::LoadDivisionsFromFile().
 { return fID; }
isInsideDetRegion()
bool larcv::hires::DivisionDef::isInsideDetRegion (float x, float y, float z) const
Definition at line 54 of file DivisionDef.cxx.
References fDetBounds.
Referenced by larcv::hires::HiResImageDivider::findVertexDivision().
{
       float pos[3] = { x, y, z};
       for (int v=0; v<3; v++) {
     if ( pos[v] < fDetBounds[v][0] || pos[v] > fDetBounds[v][1] )
       return false;
       }
       return true;
     }
operator<()
bool larcv::hires::DivisionDef::operator< (const DivisionDef & rhs) const inline
Definition at line 66 of file DivisionDef.h.
References fID.
 { return fID < rhs.fID; }
print()
void larcv::hires::DivisionDef::print () const
Definition at line 63 of file DivisionDef.cxx.
References fDetBounds.
{
       std::cout << "Division Def: x=[" << fDetBounds[0][0] << "," << fDetBounds[0][1] << "] "
         << " y=[" << fDetBounds[1][0] << "," << fDetBounds[1][1] << "] "
         << " z=[" << fDetBounds[2][0] << "," << fDetBounds[2][1] << "]" << std::endl;
     }
setPlaneMeta()
void larcv::hires::DivisionDef::setPlaneMeta (larcv::PlaneID_t plane, int wirebounds[], int tickbounds[]) protected
Definition at line 45 of file DivisionDef.cxx.
References m_planeMeta, and mNPlanes.
Referenced by DivisionDef().
{
       // we define divisions
       m_planeMeta[plane] = larcv::ImageMeta( wirebounds[1]-wirebounds[0], tickbounds[1]-tickbounds[0],
                          tickbounds[1]-tickbounds[0], wirebounds[1]-wirebounds[0],
                          wirebounds[0], tickbounds[1], plane );
       mNPlanes++;
       //LARCV_NORMAL() << m_planeMeta[plane].dump();
     }
Member Data Documentation
fDetBounds
float larcv::hires::DivisionDef::fDetBounds[3][2] protected
Definition at line 78 of file DivisionDef.h.
Referenced by DivisionDef(), isInsideDetRegion(), and print().
fDivisionIDX
size_t larcv::hires::DivisionDef::fDivisionIDX protected
Definition at line 80 of file DivisionDef.h.
fDivisionIDY
size_t larcv::hires::DivisionDef::fDivisionIDY protected
Definition at line 81 of file DivisionDef.h.
fDivisionIDZ
size_t larcv::hires::DivisionDef::fDivisionIDZ protected
Definition at line 82 of file DivisionDef.h.
fID
DivisionID larcv::hires::DivisionDef::fID protected
Definition at line 83 of file DivisionDef.h.
Referenced by operator<().
m_planeMeta
std::map< larcv::PlaneID_t, larcv::ImageMeta > larcv::hires::DivisionDef::m_planeMeta protected
Definition at line 77 of file DivisionDef.h.
Referenced by DivisionDef(), getPlaneMeta(), and setPlaneMeta().
mNPlanes
int larcv::hires::DivisionDef::mNPlanes protected
Definition at line 76 of file DivisionDef.h.
Referenced by DivisionDef(), and setPlaneMeta().
The documentation for this class was generated from the following files:
DivisionDef.h
DivisionDef.cxx