LArCV: larcv::LArbysImageExtract Class Reference
larcv::LArbysImageExtract Class Reference
#include <LArbysImageExtract.h>
Public Member Functions
LArbysImageExtract (const std::string name="LArbysImageExtract")
~LArbysImageExtract ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
const std::vector< larocv::ImageMeta > & ADCMetas () const
const std::vector< cv::Mat > & ADCImages () const
const std::vector< cv::Mat > & TrackImages () const
const std::vector< cv::Mat > & ShowerImages () const
const std::vector< cv::Mat > & ThruMuImages () const
const std::vector< cv::Mat > & StopMuImages () const
const std::vector< cv::Mat > & DeadImages () const
const larocv::ImageMeta & ADCMeta (size_t planeid) const
const cv::Mat & ADCImage (size_t planeid) const
const cv::Mat & TrackImage (size_t planeid) const
const cv::Mat & ShowerImage (size_t planeid) const
const cv::Mat & ThruMuImage (size_t planeid) const
const cv::Mat & StopMuImage (size_t planeid) const
const cv::Mat & DeadImage (size_t planeid) const
const std::vector< ROI > & TrueROI () const
const std::vector< ROI > & RecoROI () const
const LArbysImageMaker & maker () const
const PreProcessor & pproc () const
void FillcvMat (larcv::ROI *roi=nullptr)
const EventImage2D & ev_adc () const
const EventImage2D & ev_trk () const
const EventImage2D & ev_shr () const
const EventImage2D & ev_thrumu () const
const EventImage2D & ev_stopmu () const
const EventImage2D & ev_dead () const
const std::vector< Image2D > & adc_img_v () const
const std::vector< Image2D > & trk_img_v () const
const std::vector< Image2D > & shr_img_v () const
const std::vector< Image2D > & thrumu_v () const
const std::vector< Image2D > & stopmu_v () const
const std::vector< Image2D > & dead_v () const
const Image2D & adc_img (size_t plane) const
const Image2D & trk_img (size_t plane) const
const Image2D & shr_img (size_t plane) const
const Image2D & thumu_img (size_t plane) const
const Image2D & stopmu_img (size_t plane) const
const Image2D & dead_img (size_t plane) const
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _adc_producer
std::string _track_producer
std::string _shower_producer
std::string _thrumu_producer
std::string _stopmu_producer
std::string _true_roi_producer
std::string _reco_roi_producer
std::string _dead_producer
ProductType_t _tags_datatype
LArbysImageMaker _LArbysImageMaker
PreProcessor _PreProcessor
std::vector< ROI > _true_roi_v
std::vector< ROI > _reco_roi_v
std::vector< larocv::ImageMeta > _adc_meta_v
std::vector< cv::Mat > _adc_mat_v
std::vector< cv::Mat > _track_mat_v
std::vector< cv::Mat > _shower_mat_v
std::vector< cv::Mat > _thrumu_mat_v
std::vector< cv::Mat > _stopmu_mat_v
std::vector< cv::Mat > _dead_mat_v
EventImage2D _ev_adc
EventImage2D _ev_trk
EventImage2D _ev_shr
EventImage2D _ev_dead
EventImage2D _ev_thrumu
EventImage2D _ev_stopmu
Detailed Description
Definition at line 12 of file LArbysImageExtract.h.
Constructor & Destructor Documentation
LArbysImageExtract()
larcv::LArbysImageExtract::LArbysImageExtract (const std::string name = "LArbysImageExtract")
Definition at line 10 of file LArbysImageExtract.cxx.
Referenced by larcv::LArbysImageExtractProcessFactory::create().
     : ProcessBase(name),
       _LArbysImageMaker()
   {}
~LArbysImageExtract()
larcv::LArbysImageExtract::~LArbysImageExtract () inline
Definition at line 17 of file LArbysImageExtract.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
adc_img()
const Image2D& larcv::LArbysImageExtract::adc_img (size_t plane) const inline
Definition at line 103 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
Referenced by FillcvMat().
 { return _ev_adc.Image2DArray().at(plane); }
adc_img_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::adc_img_v () const inline
Definition at line 96 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_adc.Image2DArray(); }
ADCImage()
const cv::Mat& larcv::LArbysImageExtract::ADCImage (size_t planeid) const inline
Definition at line 35 of file LArbysImageExtract.h.
References _adc_mat_v.
 { return _adc_mat_v[planeid];    }
ADCImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::ADCImages () const inline
Definition at line 26 of file LArbysImageExtract.h.
References _adc_mat_v.
Referenced by larcv::LArbysImageFilter::process().
 { return _adc_mat_v;    }
ADCMeta()
const larocv::ImageMeta& larcv::LArbysImageExtract::ADCMeta (size_t planeid) const inline
Definition at line 33 of file LArbysImageExtract.h.
References _adc_meta_v.
Referenced by larcv::LArbysImageFilter::process().
 { return _adc_meta_v[planeid]; }
ADCMetas()
const std::vector<larocv::ImageMeta>& larcv::LArbysImageExtract::ADCMetas () const inline
Definition at line 24 of file LArbysImageExtract.h.
References _adc_meta_v.
 { return _adc_meta_v; }
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::LArbysImageExtract::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file LArbysImageExtract.cxx.
References _adc_producer, _dead_producer, _LArbysImageMaker, _PreProcessor, _reco_roi_producer, _shower_producer, _stopmu_producer, _tags_datatype, _thrumu_producer, _track_producer, _true_roi_producer, larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), and larcv::PSet::get().
Referenced by ~LArbysImageExtract().
   {
     _adc_producer    = cfg.get<std::string>("ADCImageProducer");
     _track_producer  = cfg.get<std::string>("TrackImageProducer","");
     _shower_producer = cfg.get<std::string>("ShowerImageProducer","");
     _dead_producer = cfg.get<std::string>("DeadWireProducer","");
     _thrumu_producer = cfg.get<std::string>("ThruMuProducer","");
     _stopmu_producer = cfg.get<std::string>("StopMuProducer","");
     auto tags_datatype = cfg.get<size_t>("CosmicTagDataType");
     _tags_datatype = (ProductType_t) tags_datatype;
     _reco_roi_producer = cfg.get<std::string>("RecoROIProducer","");
     _true_roi_producer = cfg.get<std::string>("TrueROIProducer","");
     _LArbysImageMaker.Configure(cfg.get<larcv::PSet>("LArbysImageMaker"));
     auto preprocess = cfg.get<bool>("PreProcess");
     if(preprocess)
       _PreProcessor.Configure(cfg.get<larcv::PSet>("PreProcessor"));
   }
dead_img()
const Image2D& larcv::LArbysImageExtract::dead_img (size_t plane) const inline
Definition at line 108 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
Referenced by FillcvMat().
 { return _ev_dead.Image2DArray().at(plane); }
dead_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::dead_v () const inline
Definition at line 101 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_dead.Image2DArray(); }
DeadImage()
const cv::Mat& larcv::LArbysImageExtract::DeadImage (size_t planeid) const inline
Definition at line 40 of file LArbysImageExtract.h.
References _stopmu_mat_v.
 { return _stopmu_mat_v[planeid]; }
DeadImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::DeadImages () const inline
Definition at line 31 of file LArbysImageExtract.h.
References _dead_mat_v.
 { return _dead_mat_v;   }
ev_adc()
const EventImage2D& larcv::LArbysImageExtract::ev_adc () const inline
Definition at line 89 of file LArbysImageExtract.h.
References _ev_adc.
Referenced by FillcvMat(), and process().
 { return _ev_adc; }
ev_dead()
const EventImage2D& larcv::LArbysImageExtract::ev_dead () const inline
Definition at line 94 of file LArbysImageExtract.h.
References _ev_dead.
Referenced by FillcvMat(), and process().
 { return _ev_dead; }
ev_shr()
const EventImage2D& larcv::LArbysImageExtract::ev_shr () const inline
Definition at line 91 of file LArbysImageExtract.h.
References _ev_shr.
Referenced by FillcvMat(), and process().
 { return _ev_shr; }
ev_stopmu()
const EventImage2D& larcv::LArbysImageExtract::ev_stopmu () const inline
Definition at line 93 of file LArbysImageExtract.h.
References _ev_stopmu.
Referenced by FillcvMat().
 { return _ev_stopmu; }
ev_thrumu()
const EventImage2D& larcv::LArbysImageExtract::ev_thrumu () const inline
Definition at line 92 of file LArbysImageExtract.h.
References _ev_thrumu.
Referenced by FillcvMat().
 { return _ev_thrumu; }
ev_trk()
const EventImage2D& larcv::LArbysImageExtract::ev_trk () const inline
Definition at line 90 of file LArbysImageExtract.h.
References _ev_trk.
Referenced by FillcvMat(), and process().
 { return _ev_trk; }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
FillcvMat()
void larcv::LArbysImageExtract::FillcvMat (larcv::ROI * roi = nullptr)
Definition at line 114 of file LArbysImageExtract.cxx.
References _adc_mat_v, _adc_meta_v, _dead_mat_v, _ev_adc, _ev_dead, _ev_shr, _ev_stopmu, _ev_thrumu, _ev_trk, _LArbysImageMaker, _shower_mat_v, _stopmu_mat_v, _thrumu_mat_v, _track_mat_v, adc_img(), larcv::EventImage2D::at(), larcv::ROI::BB(), larcv::Image2D::crop(), dead_img(), ev_adc(), ev_dead(), ev_shr(), ev_stopmu(), ev_thrumu(), ev_trk(), larcv::LArbysImageMaker::ExtractImage(), larcv::LArbysImageMaker::ExtractMat(), larcv::EventImage2D::Image2DArray(), shr_img(), stopmu_img(), and trk_img().
Referenced by pproc().
{
     auto ev_adc    = _ev_adc.Image2DArray();
     auto ev_trk    = _ev_trk.Image2DArray();
     auto ev_shr    = _ev_shr.Image2DArray();
     auto ev_thrumu = _ev_thrumu.Image2DArray();
     auto ev_stopmu = _ev_stopmu.Image2DArray();
     auto ev_dead   = _ev_dead.Image2DArray();
     if(roi) {
       for(size_t plane=0;plane<3;++plane) {
     auto& meta = roi->BB(plane);
     // crop the adc image
     auto& adc_img = ev_adc.at(plane);
     adc_img = adc_img.crop(meta);
     // crop the trk image
     if(ev_trk.size()) {
       auto& trk_img = ev_trk.at(plane);
       trk_img = trk_img.crop(meta);
     }
     // crop the shr image
     if(ev_shr.size()) {
       auto& shr_img = ev_shr.at(plane);
       shr_img = shr_img.crop(meta);
     }
     // crop the thrumu image
     if(ev_thrumu.size()) {
       auto& thrumu_img = ev_thrumu.at(plane);
       thrumu_img = thrumu_img.crop(meta);
     }
     // crop the stopmu image
     if(ev_stopmu.size()) {
       auto& stopmu_img = ev_stopmu.at(plane);
       stopmu_img = stopmu_img.crop(meta);
     }
     // crop the dead wire image
     if(ev_dead.size()) {
       auto& dead_img = ev_dead.at(plane);
       dead_img = dead_img.crop(meta);
     }
       }
     }
     _adc_mat_v.clear();
     _adc_meta_v.clear();
     _adc_mat_v.reserve(3);
     _adc_meta_v.reserve(3);
     for(auto img_data : _LArbysImageMaker.ExtractImage(ev_adc)) {
       _adc_mat_v.emplace_back(std::move(std::get<0>(img_data)));
       _adc_meta_v.emplace_back(std::move(std::get<1>(img_data)));
     }
     _track_mat_v  = _LArbysImageMaker.ExtractMat(ev_trk);
     _shower_mat_v = _LArbysImageMaker.ExtractMat(ev_shr);
     _thrumu_mat_v = _LArbysImageMaker.ExtractMat(ev_thrumu);
     _stopmu_mat_v = _LArbysImageMaker.ExtractMat(ev_stopmu);
     _dead_mat_v   = _LArbysImageMaker.ExtractMat(ev_dead);
   }
finalize()
void larcv::LArbysImageExtract::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 182 of file LArbysImageExtract.cxx.
Referenced by ~LArbysImageExtract().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImageExtract::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 37 of file LArbysImageExtract.cxx.
Referenced by ~LArbysImageExtract().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
maker()
const LArbysImageMaker& larcv::LArbysImageExtract::maker () const inline
Definition at line 45 of file LArbysImageExtract.h.
References _LArbysImageMaker.
 { return _LArbysImageMaker; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
pproc()
const PreProcessor& larcv::LArbysImageExtract::pproc () const inline
Definition at line 46 of file LArbysImageExtract.h.
References _PreProcessor, and FillcvMat().
 { return _PreProcessor;     }
process()
bool larcv::LArbysImageExtract::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 40 of file LArbysImageExtract.cxx.
References _adc_producer, _dead_producer, _ev_adc, _ev_dead, _ev_shr, _ev_stopmu, _ev_thrumu, _ev_trk, _LArbysImageMaker, _reco_roi_producer, _reco_roi_v, _shower_producer, _stopmu_producer, _tags_datatype, _thrumu_producer, _track_producer, _true_roi_producer, _true_roi_v, larcv::EventImage2D::clear(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::EventImage2D::Emplace(), ev_adc(), ev_dead(), ev_shr(), ev_trk(), larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::kProductImage2D, larcv::kProductROI, and larcv::EventROI::ROIArray().
Referenced by ~LArbysImageExtract().
   {
     const auto ev_adc = (EventImage2D*)mgr.get_data(kProductImage2D,_adc_producer);
     _ev_adc = *ev_adc;
     EventImage2D* ev_trk = nullptr;
     if (!_track_producer.empty())  {
       ev_trk = (EventImage2D*)mgr.get_data(kProductImage2D,_track_producer);
       _ev_trk = *ev_trk;
     }
     EventImage2D* ev_shr = nullptr;
     if (!_shower_producer.empty()) {
       ev_shr = (EventImage2D*)mgr.get_data(kProductImage2D,_shower_producer);
       _ev_shr = *ev_shr;
     }
     EventImage2D* ev_dead = nullptr;
     if (!_dead_producer.empty()) {
       ev_dead = (EventImage2D*)mgr.get_data(kProductImage2D,_dead_producer);
       _ev_dead = *ev_dead;
     }
     std::vector<Image2D> mu_img2d_v;
     mu_img2d_v.clear();
     if (!_thrumu_producer.empty()) {
       _ev_thrumu.clear();
       const auto& adc_img2d_v = ev_adc->Image2DArray();
       mu_img2d_v.resize(adc_img2d_v.size());
       _LArbysImageMaker.ConstructCosmicImage(mgr,
                          _thrumu_producer,
                          _tags_datatype,
                          adc_img2d_v,
                          mu_img2d_v);
       _ev_thrumu.Emplace(std::move(mu_img2d_v));
     }
     mu_img2d_v.clear();
     if (!_stopmu_producer.empty()) {
       _ev_stopmu.clear();
       const auto& adc_img2d_v = ev_adc->Image2DArray();
       mu_img2d_v.resize(adc_img2d_v.size());
       _LArbysImageMaker.ConstructCosmicImage(mgr,
                          _stopmu_producer,
                          _tags_datatype,
                          adc_img2d_v,
                          mu_img2d_v);
       _ev_stopmu.Emplace(std::move(mu_img2d_v));
     }
     EventROI* ev_reco_roi = nullptr;
     if(!_reco_roi_producer.empty()) {
       ev_reco_roi = (EventROI*)mgr.get_data(kProductROI,_reco_roi_producer);
       if(!ev_reco_roi) throw larbys("Unable to fetch ROI producer");
       _reco_roi_v = ev_reco_roi->ROIArray();
     }
     EventROI* ev_true_roi = nullptr;
     if(!_reco_roi_producer.empty()) {
       ev_true_roi = (EventROI*)mgr.get_data(kProductROI,_true_roi_producer);
       if(!ev_true_roi) throw larbys("Unable to fetch ROI producer");
       _true_roi_v = ev_true_roi->ROIArray();
     }
     return true;
   }
RecoROI()
const std::vector<ROI>& larcv::LArbysImageExtract::RecoROI () const inline
Definition at line 43 of file LArbysImageExtract.h.
References _reco_roi_v.
 { return _reco_roi_v; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
ShowerImage()
const cv::Mat& larcv::LArbysImageExtract::ShowerImage (size_t planeid) const inline
Definition at line 37 of file LArbysImageExtract.h.
References _shower_mat_v.
 { return _shower_mat_v[planeid]; }
ShowerImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::ShowerImages () const inline
Definition at line 28 of file LArbysImageExtract.h.
References _shower_mat_v.
 { return _shower_mat_v; }
shr_img()
const Image2D& larcv::LArbysImageExtract::shr_img (size_t plane) const inline
Definition at line 105 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
Referenced by FillcvMat().
 { return _ev_shr.Image2DArray().at(plane); }
shr_img_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::shr_img_v () const inline
Definition at line 98 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_shr.Image2DArray(); }
stopmu_img()
const Image2D& larcv::LArbysImageExtract::stopmu_img (size_t plane) const inline
Definition at line 107 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
Referenced by FillcvMat().
 { return _ev_stopmu.Image2DArray().at(plane); }
stopmu_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::stopmu_v () const inline
Definition at line 100 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_stopmu.Image2DArray(); }
StopMuImage()
const cv::Mat& larcv::LArbysImageExtract::StopMuImage (size_t planeid) const inline
Definition at line 39 of file LArbysImageExtract.h.
References _stopmu_mat_v.
 { return _stopmu_mat_v[planeid]; }
StopMuImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::StopMuImages () const inline
Definition at line 30 of file LArbysImageExtract.h.
References _stopmu_mat_v.
 { return _stopmu_mat_v; }
thrumu_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::thrumu_v () const inline
Definition at line 99 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_thrumu.Image2DArray(); }
ThruMuImage()
const cv::Mat& larcv::LArbysImageExtract::ThruMuImage (size_t planeid) const inline
Definition at line 38 of file LArbysImageExtract.h.
References _thrumu_mat_v.
 { return _thrumu_mat_v[planeid]; }
ThruMuImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::ThruMuImages () const inline
Definition at line 29 of file LArbysImageExtract.h.
References _thrumu_mat_v.
 { return _thrumu_mat_v; }
thumu_img()
const Image2D& larcv::LArbysImageExtract::thumu_img (size_t plane) const inline
Definition at line 106 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_thrumu.Image2DArray().at(plane); }
TrackImage()
const cv::Mat& larcv::LArbysImageExtract::TrackImage (size_t planeid) const inline
Definition at line 36 of file LArbysImageExtract.h.
References _track_mat_v.
 { return _track_mat_v[planeid];  }
TrackImages()
const std::vector<cv::Mat>& larcv::LArbysImageExtract::TrackImages () const inline
Definition at line 27 of file LArbysImageExtract.h.
References _track_mat_v.
 { return _track_mat_v;  }
trk_img()
const Image2D& larcv::LArbysImageExtract::trk_img (size_t plane) const inline
Definition at line 104 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
Referenced by FillcvMat().
 { return _ev_trk.Image2DArray().at(plane); }
trk_img_v()
const std::vector<Image2D>& larcv::LArbysImageExtract::trk_img_v () const inline
Definition at line 97 of file LArbysImageExtract.h.
References larcv::EventImage2D::Image2DArray().
 { return _ev_trk.Image2DArray(); }
TrueROI()
const std::vector<ROI>& larcv::LArbysImageExtract::TrueROI () const inline
Definition at line 42 of file LArbysImageExtract.h.
References _true_roi_v.
 { return _true_roi_v; }
Member Data Documentation
_adc_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_adc_mat_v private
Definition at line 72 of file LArbysImageExtract.h.
Referenced by ADCImage(), ADCImages(), and FillcvMat().
_adc_meta_v
std::vector<larocv::ImageMeta> larcv::LArbysImageExtract::_adc_meta_v private
Definition at line 71 of file LArbysImageExtract.h.
Referenced by ADCMeta(), ADCMetas(), and FillcvMat().
_adc_producer
std::string larcv::LArbysImageExtract::_adc_producer private
Definition at line 52 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_dead_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_dead_mat_v private
Definition at line 77 of file LArbysImageExtract.h.
Referenced by DeadImages(), and FillcvMat().
_dead_producer
std::string larcv::LArbysImageExtract::_dead_producer private
Definition at line 59 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_ev_adc
EventImage2D larcv::LArbysImageExtract::_ev_adc private
Definition at line 79 of file LArbysImageExtract.h.
Referenced by ev_adc(), FillcvMat(), and process().
_ev_dead
EventImage2D larcv::LArbysImageExtract::_ev_dead private
Definition at line 82 of file LArbysImageExtract.h.
Referenced by ev_dead(), FillcvMat(), and process().
_ev_shr
EventImage2D larcv::LArbysImageExtract::_ev_shr private
Definition at line 81 of file LArbysImageExtract.h.
Referenced by ev_shr(), FillcvMat(), and process().
_ev_stopmu
EventImage2D larcv::LArbysImageExtract::_ev_stopmu private
Definition at line 85 of file LArbysImageExtract.h.
Referenced by ev_stopmu(), FillcvMat(), and process().
_ev_thrumu
EventImage2D larcv::LArbysImageExtract::_ev_thrumu private
Definition at line 84 of file LArbysImageExtract.h.
Referenced by ev_thrumu(), FillcvMat(), and process().
_ev_trk
EventImage2D larcv::LArbysImageExtract::_ev_trk private
Definition at line 80 of file LArbysImageExtract.h.
Referenced by ev_trk(), FillcvMat(), and process().
_LArbysImageMaker
LArbysImageMaker larcv::LArbysImageExtract::_LArbysImageMaker private
Definition at line 63 of file LArbysImageExtract.h.
Referenced by configure(), FillcvMat(), maker(), and process().
_PreProcessor
PreProcessor larcv::LArbysImageExtract::_PreProcessor private
Definition at line 64 of file LArbysImageExtract.h.
Referenced by configure(), and pproc().
_reco_roi_producer
std::string larcv::LArbysImageExtract::_reco_roi_producer private
Definition at line 58 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_reco_roi_v
std::vector<ROI> larcv::LArbysImageExtract::_reco_roi_v private
Definition at line 68 of file LArbysImageExtract.h.
Referenced by process(), and RecoROI().
_shower_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_shower_mat_v private
Definition at line 74 of file LArbysImageExtract.h.
Referenced by FillcvMat(), ShowerImage(), and ShowerImages().
_shower_producer
std::string larcv::LArbysImageExtract::_shower_producer private
Definition at line 54 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_stopmu_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_stopmu_mat_v private
Definition at line 76 of file LArbysImageExtract.h.
Referenced by DeadImage(), FillcvMat(), StopMuImage(), and StopMuImages().
_stopmu_producer
std::string larcv::LArbysImageExtract::_stopmu_producer private
Definition at line 56 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_tags_datatype
ProductType_t larcv::LArbysImageExtract::_tags_datatype private
Definition at line 61 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_thrumu_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_thrumu_mat_v private
Definition at line 75 of file LArbysImageExtract.h.
Referenced by FillcvMat(), ThruMuImage(), and ThruMuImages().
_thrumu_producer
std::string larcv::LArbysImageExtract::_thrumu_producer private
Definition at line 55 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_track_mat_v
std::vector<cv::Mat> larcv::LArbysImageExtract::_track_mat_v private
Definition at line 73 of file LArbysImageExtract.h.
Referenced by FillcvMat(), TrackImage(), and TrackImages().
_track_producer
std::string larcv::LArbysImageExtract::_track_producer private
Definition at line 53 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_true_roi_producer
std::string larcv::LArbysImageExtract::_true_roi_producer private
Definition at line 57 of file LArbysImageExtract.h.
Referenced by configure(), and process().
_true_roi_v
std::vector<ROI> larcv::LArbysImageExtract::_true_roi_v private
Definition at line 67 of file LArbysImageExtract.h.
Referenced by process(), and TrueROI().
The documentation for this class was generated from the following files:
LArbysImageExtract.h
LArbysImageExtract.cxx