LArCV: larcv::BadRegionAna Class Reference
larcv::BadRegionAna Class Reference
#include <BadRegionAna.h>
Public Member Functions
BadRegionAna (const std::string name="BadRegionAna")
Default constructor.
~BadRegionAna ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
TTree * _tree
std::string _pgraph_prod
std::string _reco_roi_prod
std::string _adc_img_prod
int _run
int _subrun
int _event
int _entry
int _roid
int _vtxid
int _in_region_0
int _in_region_1
int _in_region_2
int _in_region_3
int _in_region_4
int _in_region_5
int _in_region_yz
int _in_region_xz
int _in_region
std::vector< std::array< geo2d::Vector< float >, 4 > > _yz_bound_v
std::vector< std::array< geo2d::Vector< float >, 4 > > _xz_bound_v
Detailed Description
Definition at line 28 of file BadRegionAna.h.
Constructor & Destructor Documentation
BadRegionAna()
larcv::BadRegionAna::BadRegionAna (const std::string name = "BadRegionAna")
Default constructor.
Definition at line 16 of file BadRegionAna.cxx.
Referenced by larcv::BadRegionAnaProcessFactory::create().
     :
     ProcessBase(name),
     _tree(nullptr)
   {}
~BadRegionAna()
larcv::BadRegionAna::~BadRegionAna () inline
Default destructor.
Definition at line 36 of file BadRegionAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::BadRegionAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 22 of file BadRegionAna.cxx.
References _adc_img_prod, _pgraph_prod, _reco_roi_prod, _xz_bound_v, _yz_bound_v, larcv::PSet::get(), and larcv::kINVALID_FLOAT.
Referenced by ~BadRegionAna().
   {
     _pgraph_prod    = cfg.get<std::string>("PGraphProducer");
     _reco_roi_prod  = cfg.get<std::string>("RecoROIProducer");
     _adc_img_prod   = cfg.get<std::string>("ADCImageProducer");
     // clock wise in YZ plane
     geo2d::Vector<float> t0,t1,t2,t3;
     t0=t1=t2=t3=geo2d::Vector<float>(kINVALID_FLOAT,kINVALID_FLOAT);
     std::array<geo2d::Vector<float>, 4 > pts_v;
     //
     // YZ plane
     //
     // region 1 (left)
     t0 = geo2d::Vector<float>(  0,-98);
     t1 = geo2d::Vector<float>(  0, 18);
     t2 = geo2d::Vector<float>(167, 111);
     t3 = geo2d::Vector<float>(341, 111);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _yz_bound_v.push_back(pts_v);
     // region 2 (middle left)
     t0 = geo2d::Vector<float>(134,-111);
     t1 = geo2d::Vector<float>(467, 111);
     t2 = geo2d::Vector<float>(520, 111);
     t3 = geo2d::Vector<float>(192,-111);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _yz_bound_v.push_back(pts_v);
     // region 3 (up and down)
     t0 = geo2d::Vector<float>(740,-111);
     t1 = geo2d::Vector<float>(700,-111);
     t2 = geo2d::Vector<float>(700, 111);
     t3 = geo2d::Vector<float>(740, 111);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _yz_bound_v.push_back(pts_v);
     // region 4 (right down to left)
     t0 = geo2d::Vector<float>(941,-111);
     t1 = geo2d::Vector<float>(887,-111);
     t2 = geo2d::Vector<float>(556, 111);
     t3 = geo2d::Vector<float>(610, 111);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _yz_bound_v.push_back(pts_v);
     //
     // XZ plane
     //
     // region 0 (bottom)
     t0 = geo2d::Vector<float>(0   ,50);
     t1 = geo2d::Vector<float>(1037,50);
     t2 = geo2d::Vector<float>(1037,50);
     t3 = geo2d::Vector<float>(0   ,0);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _xz_bound_v.push_back(pts_v);
     // region 0 (bottom)
     t0 = geo2d::Vector<float>(700,  0);
     t1 = geo2d::Vector<float>(700,256);
     t2 = geo2d::Vector<float>(740,256);
     t3 = geo2d::Vector<float>(740,  0);
     pts_v[0] = t0;
     pts_v[1] = t1;
     pts_v[2] = t2;
     pts_v[3] = t3;
     _xz_bound_v.push_back(pts_v);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::BadRegionAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 262 of file BadRegionAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~BadRegionAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::BadRegionAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 124 of file BadRegionAna.cxx.
References _entry, _event, _in_region, _in_region_0, _in_region_1, _in_region_2, _in_region_3, _in_region_4, _in_region_5, _in_region_xz, _in_region_yz, _roid, _run, _subrun, _tree, and _vtxid.
Referenced by ~BadRegionAna().
   {
     _tree = new TTree("BadRegionAna","");
     _tree->Branch("run"   , &_run    , "run/I");
     _tree->Branch("subrun", &_subrun , "subrun/I");
     _tree->Branch("event" , &_event  , "event/I");
     _tree->Branch("entry" , &_entry  , "entry/I");
     _tree->Branch("roid"  , &_roid   , "roid/I");
     _tree->Branch("vtxid" , &_vtxid  , "vtxid/I");
     _tree->Branch("in_region_0"   , &_in_region_0    , "in_region_0/I");
     _tree->Branch("in_region_1"   , &_in_region_1    , "in_region_1/I");
     _tree->Branch("in_region_2"   , &_in_region_2    , "in_region_2/I");
     _tree->Branch("in_region_3"   , &_in_region_3    , "in_region_3/I");
     _tree->Branch("in_region_4"   , &_in_region_4    , "in_region_4/I");
     _tree->Branch("in_region_5"   , &_in_region_5    , "in_region_5/I");
     _tree->Branch("in_region_yz" , &_in_region_yz  , "in_region_yz/I");
     _tree->Branch("in_region_xz" , &_in_region_xz  , "in_region_xz/I");
     _tree->Branch("in_region" , &_in_region  , "in_region/I");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::BadRegionAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 148 of file BadRegionAna.cxx.
References _adc_img_prod, _entry, _event, _in_region, _in_region_0, _in_region_1, _in_region_2, _in_region_3, _in_region_4, _in_region_5, _in_region_xz, _in_region_yz, _pgraph_prod, _reco_roi_prod, _roid, _run, _subrun, _tree, _vtxid, _xz_bound_v, _yz_bound_v, larcv::crop_metas(), larcv::IOManager< T >::current_entry(), larcv::EventBase::event(), larcv::IOManager< T >::get_data(), larcv::EventImage2D::Image2DArray(), larcv::InsideRegion(), larcv::kINVALID_INT, larcv::kProductImage2D, larcv::kProductPGraph, larcv::kProductROI, LARCV_DEBUG, larcv::EventPGraph::PGraphArray(), larcv::EventROI::ROIArray(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by ~BadRegionAna().
   {
     _run    = kINVALID_INT;
     _subrun = kINVALID_INT;
     _event  = kINVALID_INT;
     _entry  = kINVALID_INT;
     _roid   = kINVALID_INT;
     _vtxid  = kINVALID_INT;
     _in_region_0  = kINVALID_INT;
     _in_region_1  = kINVALID_INT;
     _in_region_2  = kINVALID_INT;
     _in_region_3  = kINVALID_INT;
     _in_region_4  = kINVALID_INT;
     _in_region_5  = kINVALID_INT;
     _in_region_yz = kINVALID_INT;
     _in_region_xz = kINVALID_INT;
     _in_region    = kINVALID_INT;
     EventImage2D* ev_img = nullptr;
     if (!_adc_img_prod.empty()) {
       ev_img = (EventImage2D*)(mgr.get_data(kProductImage2D,_adc_img_prod));
       if (!ev_img) throw larbys("Could not get Image2D from producer name");
     } else throw larbys("Specify image producer");
     EventPGraph* ev_pgraph = nullptr;
     if (!_pgraph_prod.empty()) {
       ev_pgraph = (EventPGraph*)(mgr.get_data(kProductPGraph,_pgraph_prod));
       if (!ev_pgraph) throw larbys("Could not get PGraph from producer name");
     } else throw larbys("Specify pgraph producer");
     EventROI* ev_croi = nullptr;
     if (!_reco_roi_prod.empty()) {
       ev_croi = (EventROI*)(mgr.get_data(kProductROI,_reco_roi_prod));
       if (!ev_croi) throw larbys("Could not get ROI from producer name");
     } else throw larbys("Specify reco ROI name");
     _run    = ev_pgraph->run();
     _subrun = ev_pgraph->subrun();
     _event  = ev_pgraph->event();
     _entry  = mgr.current_entry();
     LARCV_DEBUG() << "Got RSEE=("<<_run<<","<<_subrun<<","<<_event<<","<<_entry<<")"<<std::endl;
     const auto& adc_img_v = ev_img->Image2DArray();
     std::vector<std::vector<ImageMeta> > roid_v;
     roid_v.reserve(ev_croi->ROIArray().size());
     for(auto const& croi : ev_croi->ROIArray()) {
       auto const& bb_v = croi.BB();
       roid_v.push_back(crop_metas(adc_img_v,bb_v));
     }
     _vtxid=-1;
     auto vtx_counts = ev_pgraph->PGraphArray().size();
     LARCV_DEBUG() << "Got " << vtx_counts << " vertices" << std::endl;
     for (int vtx_idx = 0; vtx_idx < (int)vtx_counts; ++vtx_idx) {
       _vtxid += 1;
       auto pgraph = ev_pgraph->PGraphArray().at(vtx_idx);
       auto const& roi_v = pgraph.ParticleArray();
       auto const& bb_v  = roi_v.front().BB();
       auto iter = std::find(roid_v.begin(),roid_v.end(),bb_v);
       if (iter == roid_v.end()) throw larbys("Unknown image meta");
       auto roid = iter - roid_v.begin();
       if (roid != _roid) _vtxid = 0;
       _roid  = roid;
       auto const& a_roi = roi_v.front();
       auto x = a_roi.X();
       auto y = a_roi.Y();
       auto z = a_roi.Z();
       geo2d::Vector<float> pt(z,y);
       _in_region_0 = InsideRegion(pt,_yz_bound_v[0]);
       _in_region_1 = InsideRegion(pt,_yz_bound_v[1]);
       _in_region_2 = InsideRegion(pt,_yz_bound_v[2]);
       _in_region_3 = InsideRegion(pt,_yz_bound_v[3]);
       _in_region_yz = (_in_region_0 or
                _in_region_1 or
                _in_region_2 or
                _in_region_3);
       pt = geo2d::Vector<float>(z,x);
       _in_region_4 = InsideRegion(pt,_xz_bound_v[0]);
       _in_region_5 = InsideRegion(pt,_xz_bound_v[1]);
       _in_region_xz = (_in_region_4 or
                _in_region_5);
       _in_region = _in_region_yz or _in_region_xz;
       _tree->Fill();
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_adc_img_prod
std::string larcv::BadRegionAna::_adc_img_prod private
Definition at line 50 of file BadRegionAna.h.
Referenced by configure(), and process().
_entry
int larcv::BadRegionAna::_entry private
Definition at line 55 of file BadRegionAna.h.
Referenced by initialize(), and process().
_event
int larcv::BadRegionAna::_event private
Definition at line 54 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region
int larcv::BadRegionAna::_in_region private
Definition at line 66 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_0
int larcv::BadRegionAna::_in_region_0 private
Definition at line 58 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_1
int larcv::BadRegionAna::_in_region_1 private
Definition at line 59 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_2
int larcv::BadRegionAna::_in_region_2 private
Definition at line 60 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_3
int larcv::BadRegionAna::_in_region_3 private
Definition at line 61 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_4
int larcv::BadRegionAna::_in_region_4 private
Definition at line 62 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_5
int larcv::BadRegionAna::_in_region_5 private
Definition at line 63 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_xz
int larcv::BadRegionAna::_in_region_xz private
Definition at line 65 of file BadRegionAna.h.
Referenced by initialize(), and process().
_in_region_yz
int larcv::BadRegionAna::_in_region_yz private
Definition at line 64 of file BadRegionAna.h.
Referenced by initialize(), and process().
_pgraph_prod
std::string larcv::BadRegionAna::_pgraph_prod private
Definition at line 48 of file BadRegionAna.h.
Referenced by configure(), and process().
_reco_roi_prod
std::string larcv::BadRegionAna::_reco_roi_prod private
Definition at line 49 of file BadRegionAna.h.
Referenced by configure(), and process().
_roid
int larcv::BadRegionAna::_roid private
Definition at line 56 of file BadRegionAna.h.
Referenced by initialize(), and process().
_run
int larcv::BadRegionAna::_run private
Definition at line 52 of file BadRegionAna.h.
Referenced by initialize(), and process().
_subrun
int larcv::BadRegionAna::_subrun private
Definition at line 53 of file BadRegionAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::BadRegionAna::_tree private
Definition at line 46 of file BadRegionAna.h.
Referenced by finalize(), initialize(), and process().
_vtxid
int larcv::BadRegionAna::_vtxid private
Definition at line 57 of file BadRegionAna.h.
Referenced by initialize(), and process().
_xz_bound_v
std::vector<std::array<geo2d::Vector<float>, 4> > larcv::BadRegionAna::_xz_bound_v private
Definition at line 70 of file BadRegionAna.h.
Referenced by configure(), and process().
_yz_bound_v
std::vector<std::array<geo2d::Vector<float>, 4> > larcv::BadRegionAna::_yz_bound_v private
Definition at line 69 of file BadRegionAna.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
BadRegionAna.h
BadRegionAna.cxx