LArCV: larcv::VertexImg Class Reference
larcv::VertexImg Class Reference
#include <VertexImg.h>
Public Member Functions
VertexImg (const std::string name="VertexImg")
Default constructor.
~VertexImg ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
std::string fROIProducerName
std::string fImageProducerName
std::string fOutputProducerName
bool finplace
int fImageTickStart
int fVertexRadius
int fMarkValue
Detailed Description
Definition at line 29 of file VertexImg.h.
Constructor & Destructor Documentation
VertexImg()
larcv::VertexImg::VertexImg (const std::string name = "VertexImg")
Default constructor.
Definition at line 18 of file VertexImg.cxx.
Referenced by larcv::VertexImgProcessFactory::create().
     : ProcessBase(name)
   {}
~VertexImg()
larcv::VertexImg::~VertexImg () inline
Default destructor.
Definition at line 37 of file VertexImg.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::VertexImg::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 22 of file VertexImg.cxx.
References fImageProducerName, fImageTickStart, finplace, fMarkValue, fOutputProducerName, fROIProducerName, fVertexRadius, and larcv::PSet::get().
Referenced by ~VertexImg().
   {
     fROIProducerName    = cfg.get<std::string>("ROIProducerName");
     fImageProducerName  = cfg.get<std::string>("ImageProducerName");
     fOutputProducerName = cfg.get<std::string>("OutputProducerName");
     fImageTickStart     = cfg.get<int>("ImageTickStart");
     fVertexRadius       = cfg.get<int>("VertexRadius");
     fMarkValue          = cfg.get<int>("MarkValue",1);
     if ( fImageProducerName==fOutputProducerName )
       finplace = true;
     else
       finplace = false;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::VertexImg::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 177 of file VertexImg.cxx.
Referenced by ~VertexImg().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::VertexImg::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 36 of file VertexImg.cxx.
Referenced by ~VertexImg().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::VertexImg::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 39 of file VertexImg.cxx.
References larcv::ImageMeta::cols(), larcv::EventImage2D::Emplace(), fImageProducerName, fImageTickStart, finplace, fMarkValue, fOutputProducerName, fROIProducerName, fVertexRadius, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, larcv::kROIBNB, LARCV_DEBUG, LARCV_ERROR, larcv::Image2D::meta(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::EventImage2D::Move(), larcv::Image2D::paint(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), larcv::EventROI::ROIArray(), and larcv::ImageMeta::rows().
Referenced by ~VertexImg().
   {
     EventImage2D* event_original = (EventImage2D*)mgr.get_data(kProductImage2D, fImageProducerName);
     EventImage2D* event_vertex   = NULL;
     EventROI*     event_roi      = (EventROI*)mgr.get_data(kProductROI, fROIProducerName);
     if (!finplace)
       event_vertex  = (EventImage2D*)mgr.get_data(kProductImage2D, fOutputProducerName);
     else
       event_vertex  = event_original;
     if ( !event_original ) {
       LARCV_ERROR() << "Could not open input images." << std::endl;
       return false;
     }
     if ( !event_vertex )  {
       LARCV_ERROR() << "Could not open output image holder." << std::endl;
       return false;
     }
     // find neutrino interaction
     bool vertex_found = false;
     TVector3 vertex;
     double vertex_t = 0.0;
     double vertex_tdrift = 0.0;
     double vertex_tick = 0;
     double vertex_tg4elec = 0;
     LARCV_DEBUG() << "Drift velocity: " << ::larutil::LArProperties::GetME()->DriftVelocity() << " cm/us" << std::endl;
     LARCV_DEBUG() << "Trigger Time: " << ::larutil::TimeService::GetME()->TriggerTime() << " us" << std::endl;
     LARCV_DEBUG() << "Trigger offset: " << ::larutil::TimeService::GetME()->TriggerOffsetTPC() << std::endl;
     for ( auto& roi : event_roi->ROIArray() ) {
       if ( roi.Type()==kROIBNB ) {
     vertex.SetX( roi.X() );
     vertex.SetY( roi.Y() );
     vertex.SetZ( roi.Z() );
     vertex_t       = roi.T(); // G4 time [ns]
     vertex_tdrift  = roi.X()/::larutil::LArProperties::GetME()->DriftVelocity(); // [us]
     vertex_tg4elec = ::larutil::TimeService::GetME()->G4ToElecTime( vertex_t ); //
     vertex_tick    = fImageTickStart + (vertex_tg4elec-::larutil::TimeService::GetME()->TriggerTime() +vertex_tdrift + 400.333)/0.5; // hacks!!
     vertex_found   = true;
     break;
       }
     }
     double plane_offsets_ticks[3] = { 0.0,
                       0.3/::larutil::LArProperties::GetME()->DriftVelocity()/0.5,
                       0.6/::larutil::LArProperties::GetME()->DriftVelocity()/0.5 };
     if ( !vertex_found )
       return false;
     LARCV_DEBUG() << "Vertex: (" << vertex.X() << ", " << vertex.Y() << ", " << vertex.Z() << ","
          << " t=" << vertex_t*1.0e-3 << " us : "
          << " tdrift=" << vertex_tdrift << " us : "
          << " tg4elec=" << vertex_tg4elec << " us :  "
          << " tg4elec-trig=" << vertex_tg4elec-::larutil::TimeService::GetME()->TriggerTime() << " us :  "
          << " tick=" << vertex_tick << ")" << std::endl;
     std::vector< larcv::Image2D > image_v;
     event_original->Move(image_v ); // original moves ownership of its image vectors to us
     std::vector< larcv::Image2D > vertex_image_v; // space for new images if we are not working in place
     std::vector<float> _buffer;
     for ( size_t i=0; i<image_v.size(); ++i ) {
       // get access to the data
       larcv::Image2D& original_image = image_v[i];
       int plane = original_image.meta().plane();
       // get the image size
       int orig_rows = original_image.meta().rows();
       int orig_cols = original_image.meta().cols();
       // get the origin
       float topleft_x = original_image.meta().min_x();
       // get width
       float width_per_pixel  = original_image.meta().pixel_width();
       float height_per_pixel = original_image.meta().pixel_height();
       // get vertex in image
       // copied from supera
       double min_wire=0;
       double max_wire=::larutil::Geometry::GetME()->Nwires(plane)-1;
       double wire=::larutil::Geometry::GetME()->WireCoordinate(vertex,plane) + 0.5;
       if(wire<min_wire) wire = min_wire;
       if(wire>max_wire) wire = max_wire;
       int pixel_vertex_wire = (wire - topleft_x)/width_per_pixel;
       int pixel_vertex_time = (vertex_tick + plane_offsets_ticks[plane] - original_image.meta().min_y())/height_per_pixel;
       LARCV_DEBUG() << "origin: (" << topleft_x << "," << original_image.meta().min_y() << ")" << std::endl;
       LARCV_DEBUG() << "pixel vertex plane=" << plane << " (" << pixel_vertex_wire << ", " << pixel_vertex_time << ") "
             << "max(" << orig_cols << "," << orig_rows << ") "
             << "ds(" << width_per_pixel << "," << height_per_pixel << ")" << std::endl;
       // define the new image
       larcv::Image2D new_image( original_image.meta() );
       new_image.paint( 0.0 );
       if ( (pixel_vertex_wire>=0 && pixel_vertex_wire < orig_cols) && (pixel_vertex_time>=0 && pixel_vertex_time<orig_rows) ) {
     for (int r=pixel_vertex_time-fVertexRadius; r<=pixel_vertex_time+fVertexRadius; r++) {
       if ( r<0 ) continue;
       if ( r>=orig_rows ) continue;
       for (int c=pixel_vertex_wire-fVertexRadius; c<=pixel_vertex_wire+fVertexRadius; c++) {
         if ( c<0 ) continue;
         if ( c>=orig_cols ) continue;
         double dr = r-pixel_vertex_time;
         double dc = c-pixel_vertex_wire;
         if ( sqrt( dr*dr + dc*dc ) < fVertexRadius )
           LARCV_DEBUG() << "Mark pixel: (" << c << "," << orig_rows-r << ")" << std::endl;
           new_image.set_pixel( orig_rows-r, c, fMarkValue );
       }
     }
       }
       vertex_image_v.emplace_back( std::move(new_image) );
     }
     // store
     if ( finplace ) {
       // give the new images
       event_original->Emplace( std::move(vertex_image_v) );
     }
     else {
       // return the original images
       event_original->Emplace( std::move( image_v ) );
       // we give the new image2d container our relabeled images
       event_vertex->Emplace( std::move(vertex_image_v) );
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fImageProducerName
std::string larcv::VertexImg::fImageProducerName protected
Definition at line 51 of file VertexImg.h.
Referenced by configure(), and process().
fImageTickStart
int larcv::VertexImg::fImageTickStart protected
Definition at line 54 of file VertexImg.h.
Referenced by configure(), and process().
finplace
bool larcv::VertexImg::finplace protected
Definition at line 53 of file VertexImg.h.
Referenced by configure(), and process().
fMarkValue
int larcv::VertexImg::fMarkValue protected
Definition at line 56 of file VertexImg.h.
Referenced by configure(), and process().
fOutputProducerName
std::string larcv::VertexImg::fOutputProducerName protected
Definition at line 52 of file VertexImg.h.
Referenced by configure(), and process().
fROIProducerName
std::string larcv::VertexImg::fROIProducerName protected
Definition at line 50 of file VertexImg.h.
Referenced by configure(), and process().
fVertexRadius
int larcv::VertexImg::fVertexRadius protected
Definition at line 55 of file VertexImg.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
VertexImg.h
VertexImg.cxx