LArCV: larcv::TrackShowerAna Class Reference
larcv::TrackShowerAna Class Reference
#include <PAna.h>
Public Member Functions
TrackShowerAna ()
~TrackShowerAna ()
void Configure (const PSet &pset)
bool Analyze (const cv::Mat &adc_img, const cv::Mat &track_img, const cv::Mat &shower_img)
void Finalize (TFile *file)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void Clear ()
void CalcAndFill (const larocv::GEO2D_ContourArray_t &ctor_v, const cv::Mat &img, TTree *tree)
void FilterContours (larocv::GEO2D_ContourArray_t &ctor_v)
Private Attributes
uint _min_ctor_size
uint _min_points_inside
TTree * _track_tree
TTree * _shower_tree
float _length
float _width
float _perimeter
float _area
float _mean_pix_dist
float _sigma_pix_dist
float _n_pixel
float _weighted_angle
Detailed Description
Definition at line 13 of file PAna.h.
Constructor & Destructor Documentation
TrackShowerAna()
larcv::TrackShowerAna::TrackShowerAna ()
Definition at line 10 of file PAna.cxx.
References LARCV_DEBUG.
                                  :
     _track_tree(nullptr),
     _shower_tree(nullptr)
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_DEBUG() << "end" << std::endl;
   }
~TrackShowerAna()
larcv::TrackShowerAna::~TrackShowerAna () inline
Definition at line 18 of file PAna.h.
References Analyze(), CalcAndFill(), Clear(), Configure(), FilterContours(), and Finalize().
 {}
Member Function Documentation
Analyze()
bool larcv::TrackShowerAna::Analyze (const cv::Mat & adc_img, const cv::Mat & track_img, const cv::Mat & shower_img)
Definition at line 123 of file PAna.cxx.
References _shower_tree, _track_tree, CalcAndFill(), FilterContours(), and LARCV_DEBUG.
Referenced by ~TrackShowerAna().
   {
     LARCV_DEBUG() << "start" << std::endl;
     auto track_img_t = larocv::Threshold(track_img,10,1);
     auto shower_img_t = larocv::Threshold(shower_img,10,1);
     // FindContours
     larocv::GEO2D_ContourArray_t track_ctor_v,shower_ctor_v;
     track_ctor_v = larocv::FindContours(track_img_t);
     shower_ctor_v = larocv::FindContours(shower_img_t);
     // Filter them by size (number of contour points)
     FilterContours(track_ctor_v);
     FilterContours(shower_ctor_v);
     // Calculate metrics
     CalcAndFill(track_ctor_v,track_img,_track_tree);
     CalcAndFill(shower_ctor_v,shower_img,_shower_tree);
     return true;
     LARCV_DEBUG() << "end" << std::endl;
   }
CalcAndFill()
void larcv::TrackShowerAna::CalcAndFill (const larocv::GEO2D_ContourArray_t & ctor_v, const cv::Mat & img, TTree * tree) private
Definition at line 85 of file PAna.cxx.
References _area, _length, _mean_pix_dist, _min_points_inside, _n_pixel, _perimeter, _sigma_pix_dist, _weighted_angle, _width, Clear(), and LARCV_DEBUG.
Referenced by Analyze(), and ~TrackShowerAna().
{
     LARCV_DEBUG() << "calculating for " << ctor_v.size() << " contours" << std::endl;
     for(const auto& ctor : ctor_v) {
       auto npixel = cv::countNonZero(larocv::MaskImage(img,ctor,0,false));
       if (npixel < _min_points_inside) continue;
       _n_pixel = npixel;
       //rotated rect coordinates
       auto min_rect  = cv::minAreaRect(ctor);
       cv::Point2f vertices[4];
       min_rect.points(vertices);
       auto rect = min_rect.size;
       _length = rect.height > rect.width ? rect.height : rect.width;
       _width = rect.height > rect.width ? rect.width  : rect.height;
       _perimeter = cv::arcLength(ctor,1);
       _area = cv::contourArea(ctor);
       auto overallPCA = larocv::CalcPCA(ctor);
       auto masked_pts=larocv::MaskImage(img,ctor,0,false);
       _mean_pix_dist = larocv::MeanDistanceToLine(masked_pts,overallPCA);
       _sigma_pix_dist = larocv::SigmaDistanceToLine(masked_pts,overallPCA);
       _weighted_angle = larocv::CircumferenceAngularSum(ctor);
       tree->Fill();
       Clear();
     } // end this contour
   }
Clear()
void larcv::TrackShowerAna::Clear () private
Definition at line 58 of file PAna.cxx.
References _area, _length, _mean_pix_dist, _n_pixel, _perimeter, _sigma_pix_dist, _weighted_angle, and _width.
Referenced by CalcAndFill(), and ~TrackShowerAna().
{
     _length = 0.0;
     _width = 0.0;
     _perimeter = 0.0;
     _area = 0.0;
     _mean_pix_dist = 0.0;
     _sigma_pix_dist = 0.0;
     _n_pixel = 0.0;
     _weighted_angle = 0.0;
   }
Configure()
void larcv::TrackShowerAna::Configure (const PSet & pset)
Definition at line 19 of file PAna.cxx.
References _area, _length, _mean_pix_dist, _min_ctor_size, _min_points_inside, _n_pixel, _perimeter, _shower_tree, _sigma_pix_dist, _track_tree, _weighted_angle, _width, larcv::PSet::get(), LARCV_DEBUG, and larcv::larcv_base::set_verbosity().
Referenced by ~TrackShowerAna().
{
     LARCV_DEBUG() << "start" << std::endl;
     this->set_verbosity((msg::Level_t)pset.get<int>("Verbosity",2));
     _min_ctor_size = pset.get<uint>("MinContourSize",3);
     _min_points_inside = pset.get<uint>("MinPointsInside",10);
     std::string tree_prefix = pset.get<std::string>("TreePrefix");
     std::stringstream ss;
     ss.str("");
     ss << tree_prefix << "_track";
     _track_tree = new TTree(ss.str().c_str(),ss.str().c_str());
     _track_tree->Branch("length"         , &_length         ,"length/F");
     _track_tree->Branch("width"          , &_width          ,"width/F");
     _track_tree->Branch("perimeter"      , &_perimeter      ,"perimeter/F");
     _track_tree->Branch("area"           , &_area           ,"area/F");
     _track_tree->Branch("mean_pix_dist"  , &_mean_pix_dist  ,"mean_pix_dist/F");
     _track_tree->Branch("sigma_pix_dist" , &_sigma_pix_dist ,"sigma_pix_dist/F");
     _track_tree->Branch("n_pixel"        , &_n_pixel        ,"n_pixel/F");
     _track_tree->Branch("weighted_angle" , &_weighted_angle ,"weighted_angle/F");
     ss.str("");
     ss << tree_prefix << "_shower";
     _shower_tree = new TTree(ss.str().c_str(),ss.str().c_str());
     _shower_tree->Branch("length"         , &_length         ,"length/F");
     _shower_tree->Branch("width"          , &_width          ,"width/F");
     _shower_tree->Branch("perimeter"      , &_perimeter      ,"perimeter/F");
     _shower_tree->Branch("area"           , &_area           ,"area/F");
     _shower_tree->Branch("mean_pix_dist"  , &_mean_pix_dist  ,"mean_pix_dist/F");
     _shower_tree->Branch("sigma_pix_dist" , &_sigma_pix_dist ,"sigma_pix_dist/F");
     _shower_tree->Branch("n_pixel"        , &_n_pixel        ,"n_pixel/F");
     _shower_tree->Branch("weighted_angle" , &_weighted_angle ,"weighted_angle/F");
     LARCV_DEBUG() << "end" << std::endl;
     return;
   }
FilterContours()
void larcv::TrackShowerAna::FilterContours (larocv::GEO2D_ContourArray_t & ctor_v) private
Definition at line 72 of file PAna.cxx.
References _min_ctor_size.
Referenced by Analyze(), and ~TrackShowerAna().
{
     larocv::GEO2D_ContourArray_t ctor_tmp_v;
     ctor_tmp_v.reserve(ctor_v.size());
     for(auto& ctor : ctor_v)
       if(ctor.size()>_min_ctor_size)
     ctor_tmp_v.emplace_back(std::move(ctor));
     std::swap(ctor_tmp_v,ctor_v);
     return;
   }
Finalize()
void larcv::TrackShowerAna::Finalize (TFile * file)
Definition at line 148 of file PAna.cxx.
References _shower_tree, _track_tree, and LARCV_DEBUG.
Referenced by ~TrackShowerAna().
{
     LARCV_DEBUG() << "TS Finalize" << std::endl;
     if(file && _track_tree && _shower_tree) {
       file->cd();
       _track_tree->Write();
       _shower_tree->Write();
       LARCV_DEBUG() << "wrote" << std::endl;
     }
     LARCV_DEBUG() << "done" << std::endl;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_area
float larcv::TrackShowerAna::_area private
Definition at line 52 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_length
float larcv::TrackShowerAna::_length private
Definition at line 49 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_mean_pix_dist
float larcv::TrackShowerAna::_mean_pix_dist private
Definition at line 53 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_min_ctor_size
uint larcv::TrackShowerAna::_min_ctor_size private
Definition at line 43 of file PAna.h.
Referenced by Configure(), and FilterContours().
_min_points_inside
uint larcv::TrackShowerAna::_min_points_inside private
Definition at line 44 of file PAna.h.
Referenced by CalcAndFill(), and Configure().
_n_pixel
float larcv::TrackShowerAna::_n_pixel private
Definition at line 55 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_perimeter
float larcv::TrackShowerAna::_perimeter private
Definition at line 51 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_shower_tree
TTree* larcv::TrackShowerAna::_shower_tree private
Definition at line 47 of file PAna.h.
Referenced by Analyze(), Configure(), and Finalize().
_sigma_pix_dist
float larcv::TrackShowerAna::_sigma_pix_dist private
Definition at line 54 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_track_tree
TTree* larcv::TrackShowerAna::_track_tree private
Definition at line 46 of file PAna.h.
Referenced by Analyze(), Configure(), and Finalize().
_weighted_angle
float larcv::TrackShowerAna::_weighted_angle private
Definition at line 56 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
_width
float larcv::TrackShowerAna::_width private
Definition at line 50 of file PAna.h.
Referenced by CalcAndFill(), Clear(), and Configure().
The documentation for this class was generated from the following files:
PAna.h
PAna.cxx