LArCV: larcv::CircularBufferBase< T > Class Template Reference
larcv::CircularBufferBase< T > Class Template Reference
User defined class CircularBufferBase ...
#include <CircularBufferBase.h>
Public Member Functions
CircularBufferBase (size_t num_buf=10)
Default constructor.
virtual ~CircularBufferBase ()
Default destructor.
size_t size () const
BufferState_t state (const size_t id) const
bool flush (const size_t id)
bool init (const size_t id)
bool busy (const size_t id, const bool raise=false) const
T & get (const size_t id)
void lock (const size_t id)
void unlock (const size_t id)
Protected Member Functions
virtual std::shared_ptr< T > construct () const
virtual void destruct (std::shared_ptr< T >)
Protected Attributes
std::vector< std::shared_ptr< T > > _buffer_v
Private Member Functions
void check_id (const size_t id) const
void fill_buffer (const size_t id)
void clean_buffer (const size_t id)
Private Attributes
std::vector< larcv::BufferState_t > _state_v
std::vector< bool > _lock_v
std::vector< std::thread > _thread_v
Detailed Description
template<class T>
class larcv::CircularBufferBase< T >
User defined class CircularBufferBase ...
these comments are used to generate doxygen documentation!
Definition at line 38 of file CircularBufferBase.h.
Constructor & Destructor Documentation
CircularBufferBase()
template<class T > larcv::CircularBufferBase< T >::CircularBufferBase (size_t num_buf = 10)
Default constructor.
Definition at line 9 of file CircularBufferBase.cxx.
     : _buffer_v ( num_buf, nullptr )
     , _state_v  ( num_buf, kEmpty  )
     , _lock_v   ( num_buf, false   )
     , _thread_v ( num_buf          )
   {}
~CircularBufferBase()
template<class T > larcv::CircularBufferBase< T >::~CircularBufferBase () virtual
Default destructor.
Definition at line 17 of file CircularBufferBase.cxx.
   {
     // loop over buffers
     for(size_t i=0; i<_buffer_v.size(); ++i) {
       // if thread is running, wait
       if(_thread_v[i].joinable())
     _thread_v[i].join();
       // then flush
       if( _state_v[i] == kReady)
     flush(i);
     }
     // make sure destructor holds till flushing is done
     for(size_t i=0; i<_buffer_v.size(); ++i)
       if(_thread_v[i].joinable()) _thread_v[i].join();
     /*
     for(size_t i=0; i<_thread_v.size(); ++i) {
       std::cout<<i<<" ... state " << _state_v[i]<< " ... "<<(_thread_v[i].joinable() ? "joinable" : "not joinable")<<std::endl;
     }
     */
   }
Member Function Documentation
busy()
template<class T > bool larcv::CircularBufferBase< T >::busy (const size_t id, const bool raise = false) const
Definition at line 83 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     check_id(id);
     bool state = (_state_v[id] == kClean || _state_v[id] == kInit);
     if(state && raise) {
       std::cerr << "Buffer ID " << id << " is in busy state..." << std::endl;
       throw std::exception();
     }
     if(!state && _lock_v[id]) {
       state = true;
       if(raise) {
     std::cerr << "Buffer ID " << id << " is in locked state..." << std::endl;
     throw std::exception();
       }
     }
     return state;
   }
check_id()
template<class T > void larcv::CircularBufferBase< T >::check_id (const size_t id) const private
Definition at line 119 of file CircularBufferBase.cxx.
   { if( id < _state_v.size() ) return;
     std::cerr << "Invalid buffer id requested!" << std::endl;
     throw std::exception();
   }
clean_buffer()
template<class T > void larcv::CircularBufferBase< T >::clean_buffer (const size_t id) private
Definition at line 146 of file CircularBufferBase.cxx.
   {
     if(_state_v[id] != kReady) {
       std::cerr << "Buffer id " << id << " is not in kReady state!" << std::endl;
       throw std::exception();
     }
     _state_v[id]  = kClean;
     this->destruct(_buffer_v[id]);
     _buffer_v[id] = nullptr;
     _state_v[id]  = kEmpty;
   }
construct()
template<class T > std::shared_ptr< T > larcv::CircularBufferBase< T >::construct () const protected virtual
Reimplemented in larcv::ExampleCircularBuffer.
Definition at line 126 of file CircularBufferBase.cxx.
   { return std::shared_ptr<T>(new T); }
destruct()
template<class T> void larcv::CircularBufferBase< T >::destruct (std::shared_ptr< T > ptr) protected virtual
Reimplemented in larcv::ExampleCircularBuffer.
Definition at line 130 of file CircularBufferBase.cxx.
   { }
fill_buffer()
template<class T > void larcv::CircularBufferBase< T >::fill_buffer (const size_t id) private
Definition at line 134 of file CircularBufferBase.cxx.
   {
     if(_state_v[id] != kEmpty) {
       std::cerr << "Buffer id " << id << " is not in kEmpty state!" << std::endl;
       throw std::exception();
     }
     _state_v  [id] = kInit;
     _buffer_v [id] = this->construct();
     _state_v  [id] = kReady;
   }
flush()
template<class T > bool larcv::CircularBufferBase< T >::flush (const size_t id)
Definition at line 61 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     busy(id);
     if(_thread_v[id].joinable()) _thread_v[id].join();
     std::thread t(&CircularBufferBase<T>::clean_buffer, this, id);
     _thread_v[id] = std::move(t);
     usleep(500);
     return true;
   }
get()
template<class T > T & larcv::CircularBufferBase< T >::get (const size_t id)
Definition at line 104 of file CircularBufferBase.cxx.
   {
     check_id(id);
     if(busy(id)) {
       std::cerr << "Buffer " << id << " is busy!" << std::endl;
       throw std::exception();
     }
     if(!_buffer_v[id]) {
       std::cerr << "Buffer " << id << " does not exist!" << std::endl;
       throw std::exception();
     }
     return *(_buffer_v[id]);
   }
init()
template<class T > bool larcv::CircularBufferBase< T >::init (const size_t id)
Definition at line 72 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     busy(id,true);
     if(_thread_v[id].joinable()) _thread_v[id].join();
     std::thread t(&CircularBufferBase<T>::fill_buffer, this, id);
     _thread_v[id] = std::move(t);
     usleep(500);
     return true;
   }
lock()
template<class T > void larcv::CircularBufferBase< T >::lock (const size_t id)
Definition at line 40 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     busy(id,true);
     _lock_v[id] = true;
   }
size()
template<class T> size_t larcv::CircularBufferBase< T >::size () const inline
Definition at line 48 of file CircularBufferBase.h.
 { return _buffer_v.size(); }
state()
template<class T > BufferState_t larcv::CircularBufferBase< T >::state (const size_t id) const
Definition at line 54 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     check_id(id);
     return _state_v[id];
   }
unlock()
template<class T > void larcv::CircularBufferBase< T >::unlock (const size_t id)
Definition at line 47 of file CircularBufferBase.cxx.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
   {
     busy(id,true);
     _lock_v[id] = true;
   }
Member Data Documentation
_buffer_v
template<class T> std::vector<std::shared_ptr<T> > larcv::CircularBufferBase< T >::_buffer_v protected
Definition at line 66 of file CircularBufferBase.h.
Referenced by larcv::CircularBufferBase< std::vector< double > >::size().
_lock_v
template<class T> std::vector<bool> larcv::CircularBufferBase< T >::_lock_v private
Definition at line 81 of file CircularBufferBase.h.
_state_v
template<class T> std::vector<larcv::BufferState_t> larcv::CircularBufferBase< T >::_state_v private
Definition at line 80 of file CircularBufferBase.h.
_thread_v
template<class T> std::vector<std::thread> larcv::CircularBufferBase< T >::_thread_v private
Definition at line 84 of file CircularBufferBase.h.
The documentation for this class was generated from the following files:
CircularBufferBase.h
CircularBufferBase.cxx