LArCV: larcv::EventChStatus Class Reference
larcv::EventChStatus Class Reference
Event-wise class to store a collection of larcv::ChStatus (one per plane)
#include <EventChStatus.h>
Public Member Functions
EventChStatus ()
Default constructor.
virtual ~EventChStatus ()
Default destructor.
void clear ()
Clears an array of larcv::ChStatus.
const std::map< larcv::PlaneID_t, larcv::ChStatus > & ChStatusMap () const
Getter for a const reference of core data.
const ChStatus & Status (larcv::PlaneID_t id) const
Get larcv::ChStatus for a specified plane.
void Insert (const ChStatus &status)
Insert larcv::ChStatus into a collection.
void Emplace (ChStatus &&status)
Emplace larcv::ChStatus into a collection.
std::string dump () const
Dump contents in string representation.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Private Attributes
std::map< ::larcv::PlaneID_t, ::larcv::ChStatus > _status_m
Detailed Description
Event-wise class to store a collection of larcv::ChStatus (one per plane)
A concrete factory class for larcv::EventChStatus.
Definition at line 28 of file EventChStatus.h.
Constructor & Destructor Documentation
EventChStatus()
larcv::EventChStatus::EventChStatus () inline
Default constructor.
Definition at line 33 of file EventChStatus.h.
Referenced by larcv::EventChStatusFactory::create().
 {}
~EventChStatus()
virtual larcv::EventChStatus::~EventChStatus () inline virtual
Default destructor.
Definition at line 36 of file EventChStatus.h.
References clear().
 {}
Member Function Documentation
ChStatusMap()
const std::map<larcv::PlaneID_t,larcv::ChStatus>& larcv::EventChStatus::ChStatusMap () const inline
Getter for a const reference of core data.
Definition at line 42 of file EventChStatus.h.
References _status_m, dump(), Emplace(), Insert(), and Status().
 { return _status_m; }
clear()
void larcv::EventChStatus::clear () virtual
Clears an array of larcv::ChStatus.
Reimplemented from larcv::EventBase.
Definition at line 12 of file EventChStatus.cxx.
References _status_m, and larcv::EventBase::clear().
Referenced by ~EventChStatus().
   {
     EventBase::clear();
     _status_m.clear();
   }
dump()
std::string larcv::EventChStatus::dump () const
Dump contents in string representation.
Definition at line 31 of file EventChStatus.cxx.
References _status_m.
Referenced by ChStatusMap().
   {
     std::string res;
     for(auto const& plane_status : _status_m) res += plane_status.second.dump() + "\n";
     return res;
   }
Emplace()
void larcv::EventChStatus::Emplace (ChStatus && status)
Emplace larcv::ChStatus into a collection.
Definition at line 28 of file EventChStatus.cxx.
References _status_m.
Referenced by ChStatusMap().
   { _status_m.emplace(status.Plane(),std::move(status)); }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
Insert()
void larcv::EventChStatus::Insert (const ChStatus & status)
Insert larcv::ChStatus into a collection.
Definition at line 25 of file EventChStatus.cxx.
References _status_m, and larcv::ChStatus::Plane().
Referenced by ChStatusMap().
   { _status_m[status.Plane()] = status; }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
Status()
const ChStatus & larcv::EventChStatus::Status (larcv::PlaneID_t id) const
Get larcv::ChStatus for a specified plane.
Definition at line 18 of file EventChStatus.cxx.
References _status_m.
Referenced by ChStatusMap(), and larcv::WireMask::process().
   {
     auto iter = _status_m.find(id);
     if( iter == _status_m.end() ) throw larbys("Invalid request (PlaneID_t not found)!");
     return (*iter).second;
   }
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
_status_m
std::map< ::larcv::PlaneID_t, ::larcv::ChStatus > larcv::EventChStatus::_status_m private
Definition at line 60 of file EventChStatus.h.
Referenced by ChStatusMap(), clear(), dump(), Emplace(), Insert(), and Status().
The documentation for this class was generated from the following files:
EventChStatus.h
EventChStatus.cxx