LArCV: larcv::ExampleCircularBuffer Class Reference
larcv::ExampleCircularBuffer Class Reference
User defined class ExampleCircularBuffer ...
#include <ExampleCircularBuffer.h>
Public Member Functions
ExampleCircularBuffer ()
Default constructor.
~ExampleCircularBuffer ()
Default destructor.
size_t size () const
BufferState_t state (const size_t id) const
bool flush (const size_t id)
bool init (const size_t id)
bool busy (const size_t id, const bool raise=false) const
std::vector< double > & get (const size_t id)
void lock (const size_t id)
void unlock (const size_t id)
Public Attributes
size_t _num_elements
Protected Member Functions
std::shared_ptr< std::vector< double > > construct () const
void destruct (std::shared_ptr< std::vector< double > > ptr)
Protected Attributes
std::vector< std::shared_ptr< std::vector< double > > > _buffer_v
Detailed Description
User defined class ExampleCircularBuffer ...
these comments are used to generate doxygen documentation!
Definition at line 27 of file ExampleCircularBuffer.h.
Constructor & Destructor Documentation
ExampleCircularBuffer()
larcv::ExampleCircularBuffer::ExampleCircularBuffer () inline
Default constructor.
Definition at line 32 of file ExampleCircularBuffer.h.
References _num_elements.
                             : larcv::CircularBufferBase<std::vector<double> >()
     { _num_elements = 100; }
~ExampleCircularBuffer()
larcv::ExampleCircularBuffer::~ExampleCircularBuffer () inline
Default destructor.
Definition at line 36 of file ExampleCircularBuffer.h.
 { }
Member Function Documentation
busy()
bool larcv::CircularBufferBase< std::vector< double > >::busy (const size_t id, const bool raise = false) const inherited
Definition at line 83 of file CircularBufferBase.cxx.
References larcv::kClean, and larcv::kInit.
   {
     check_id(id);
     bool state = (_state_v[id] == kClean || _state_v[id] == kInit);
     if(state && raise) {
       std::cerr << "Buffer ID " << id << " is in busy state..." << std::endl;
       throw std::exception();
     }
     if(!state && _lock_v[id]) {
       state = true;
       if(raise) {
     std::cerr << "Buffer ID " << id << " is in locked state..." << std::endl;
     throw std::exception();
       }
     }
     return state;
   }
construct()
std::shared_ptr<std::vector<double> > larcv::ExampleCircularBuffer::construct () const inline protected virtual
Reimplemented from larcv::CircularBufferBase< std::vector< double > >.
Definition at line 42 of file ExampleCircularBuffer.h.
References _num_elements.
     {
       return std::shared_ptr<std::vector<double> >(new std::vector<double>(_num_elements,0.));
     }
destruct()
void larcv::ExampleCircularBuffer::destruct (std::shared_ptr< std::vector< double > > ptr) inline protected virtual
Reimplemented from larcv::CircularBufferBase< std::vector< double > >.
Definition at line 47 of file ExampleCircularBuffer.h.
     { ptr->clear(); }
flush()
bool larcv::CircularBufferBase< std::vector< double > >::flush (const size_t id) inherited
Definition at line 61 of file CircularBufferBase.cxx.
   {
     busy(id);
     if(_thread_v[id].joinable()) _thread_v[id].join();
     std::thread t(&CircularBufferBase<T>::clean_buffer, this, id);
     _thread_v[id] = std::move(t);
     usleep(500);
     return true;
   }
get()
std::vector< double > & larcv::CircularBufferBase< std::vector< double > >::get (const size_t id) inherited
Definition at line 104 of file CircularBufferBase.cxx.
   {
     check_id(id);
     if(busy(id)) {
       std::cerr << "Buffer " << id << " is busy!" << std::endl;
       throw std::exception();
     }
     if(!_buffer_v[id]) {
       std::cerr << "Buffer " << id << " does not exist!" << std::endl;
       throw std::exception();
     }
     return *(_buffer_v[id]);
   }
init()
bool larcv::CircularBufferBase< std::vector< double > >::init (const size_t id) inherited
Definition at line 72 of file CircularBufferBase.cxx.
   {
     busy(id,true);
     if(_thread_v[id].joinable()) _thread_v[id].join();
     std::thread t(&CircularBufferBase<T>::fill_buffer, this, id);
     _thread_v[id] = std::move(t);
     usleep(500);
     return true;
   }
lock()
void larcv::CircularBufferBase< std::vector< double > >::lock (const size_t id) inherited
Definition at line 40 of file CircularBufferBase.cxx.
   {
     busy(id,true);
     _lock_v[id] = true;
   }
size()
size_t larcv::CircularBufferBase< std::vector< double > >::size () const inline inherited
Definition at line 48 of file CircularBufferBase.h.
References larcv::CircularBufferBase< T >::_buffer_v, larcv::CircularBufferBase< T >::busy(), larcv::CircularBufferBase< T >::flush(), larcv::CircularBufferBase< T >::init(), larcv::CircularBufferBase< T >::lock(), larcv::CircularBufferBase< T >::state(), and larcv::CircularBufferBase< T >::unlock().
 { return _buffer_v.size(); }
state()
BufferState_t larcv::CircularBufferBase< std::vector< double > >::state (const size_t id) const inherited
Definition at line 54 of file CircularBufferBase.cxx.
   {
     check_id(id);
     return _state_v[id];
   }
unlock()
void larcv::CircularBufferBase< std::vector< double > >::unlock (const size_t id) inherited
Definition at line 47 of file CircularBufferBase.cxx.
   {
     busy(id,true);
     _lock_v[id] = true;
   }
Member Data Documentation
_buffer_v
std::vector<std::shared_ptr<std::vector< double > > > larcv::CircularBufferBase< std::vector< double > >::_buffer_v protected inherited
Definition at line 66 of file CircularBufferBase.h.
_num_elements
size_t larcv::ExampleCircularBuffer::_num_elements
Definition at line 38 of file ExampleCircularBuffer.h.
Referenced by construct(), and ExampleCircularBuffer().
The documentation for this class was generated from the following file:
ExampleCircularBuffer.h