LArCV: larcv::ROIPad Class Reference
larcv::ROIPad Class Reference
#include <ROIPad.h>
Public Member Functions
ROIPad (const std::string name="ROIPad")
~ROIPad ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
ImageMeta PadMeta (const ImageMeta &bb, float row_pad, float col_pad)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _img_producer
std::string _input_roi_producer
std::string _output_roi_producer
float _row_pad
float _col_pad
Detailed Description
Definition at line 10 of file ROIPad.h.
Constructor & Destructor Documentation
ROIPad()
larcv::ROIPad::ROIPad (const std::string name = "ROIPad")
Definition at line 12 of file ROIPad.cxx.
Referenced by larcv::ROIPadProcessFactory::create().
     : ProcessBase(name)
   {}
~ROIPad()
larcv::ROIPad::~ROIPad () inline
Definition at line 15 of file ROIPad.h.
References configure(), finalize(), initialize(), PadMeta(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ROIPad::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file ROIPad.cxx.
References _col_pad, _img_producer, _input_roi_producer, _output_roi_producer, _row_pad, larcv::PSet::get(), and larcv::kINVALID_FLOAT.
Referenced by ~ROIPad().
   {
     _img_producer = cfg.get<std::string>("ImageProducer");
     _input_roi_producer = cfg.get<std::string>("InputROIProducer");
     _output_roi_producer = cfg.get<std::string>("OutputROIProducer");
     _row_pad=_col_pad=kINVALID_FLOAT;
     _row_pad = cfg.get<float>("PadRows");
     _col_pad = cfg.get<float>("PadCols");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ROIPad::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 77 of file ROIPad.cxx.
Referenced by ~ROIPad().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ROIPad::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 27 of file ROIPad.cxx.
Referenced by ~ROIPad().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
PadMeta()
ImageMeta larcv::ROIPad::PadMeta (const ImageMeta & bb, float row_pad, float col_pad)
Definition at line 30 of file ROIPad.cxx.
References larcv::ImageMeta::cols(), larcv::ImageMeta::height(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), larcv::ImageMeta::rows(), larcv::ImageMeta::tl(), larcv::ImageMeta::width(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by process(), and ~ROIPad().
{
     float width   = bb.width()  + col_pad*bb.pixel_width();
     float height  = bb.height() + row_pad*bb.pixel_height();
     unsigned int  rows    = bb.rows()   + row_pad;
     unsigned int  cols    = bb.cols()   + col_pad;
     float originx = bb.tl().x   - col_pad/2.0;
     float originy = bb.tl().y   - row_pad/2.0;
     unsigned int  plane   = bb.plane();
     ImageMeta bb_copy(width, height, rows, cols, originx, originy, plane);
     return bb_copy;
   }
process()
bool larcv::ROIPad::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 45 of file ROIPad.cxx.
References _col_pad, _img_producer, _input_roi_producer, _output_roi_producer, _row_pad, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, and PadMeta().
Referenced by ~ROIPad().
   {
     const auto evimg2d = (EventImage2D*)mgr.get_data(kProductImage2D,_img_producer);
     const auto inroi = (EventROI*)mgr.get_data(kProductROI,_input_roi_producer);
     auto ouroi = (EventROI*)mgr.get_data(kProductROI,_output_roi_producer);
     for (auto roi_pad : inroi->ROIArray()) {
       auto bb_v = roi_pad.BB();
       bb_v.clear();
       bb_v.reserve(roi_pad.BB().size());
       for( auto bb : roi_pad.BB() ) {
     auto bb_copy = PadMeta(bb,_row_pad,_col_pad);
     bool outside=false;
     const auto& meta = evimg2d->Image2DArray().at(bb.plane()).meta();
     if (bb_copy.max_x() > meta.max_x()) outside=true;
     if (bb_copy.max_y() > meta.max_y()) outside=true;
     if (bb_copy.min_x() < meta.min_x()) outside=true;
     if (bb_copy.min_y() < meta.min_y()) outside=true;
     if (!outside) bb_v.emplace_back(std::move(bb_copy));
     else          bb_v.emplace_back(std::move(bb));
       }
       roi_pad.SetBB(bb_v);
       ouroi->Emplace(std::move(roi_pad));
     }
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_col_pad
float larcv::ROIPad::_col_pad private
Definition at line 34 of file ROIPad.h.
Referenced by configure(), and process().
_img_producer
std::string larcv::ROIPad::_img_producer private
Definition at line 29 of file ROIPad.h.
Referenced by configure(), and process().
_input_roi_producer
std::string larcv::ROIPad::_input_roi_producer private
Definition at line 30 of file ROIPad.h.
Referenced by configure(), and process().
_output_roi_producer
std::string larcv::ROIPad::_output_roi_producer private
Definition at line 31 of file ROIPad.h.
Referenced by configure(), and process().
_row_pad
float larcv::ROIPad::_row_pad private
Definition at line 33 of file ROIPad.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ROIPad.h
ROIPad.cxx