LArCV: larcv::SuperaChStatus Class Reference
larcv::SuperaChStatus Class Reference
#include <SuperaChStatus.h>
Public Member Functions
SuperaChStatus (const std::string name="SuperaChStatus")
Default constructor.
~SuperaChStatus ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
bool is (const std::string question) const
void set_chstatus (::larcv::PlaneID_t plane, unsigned int wire, short status)
const std::string & InputLabel () const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
template<class T >
const std::vector< T > & LArData () const
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
const std::string & LArDataLabel (supera::LArDataType_t type) const
int TimeOffset () const
void ClearEventData ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
const std::string & OutChStatusLabel () const
Private Attributes
std::string _in_chstatus_producer
std::map< larcv::PlaneID_t, larcv::ChStatus > _status_m
Detailed Description
Definition at line 28 of file SuperaChStatus.h.
Constructor & Destructor Documentation
SuperaChStatus()
larcv::SuperaChStatus::SuperaChStatus (const std::string name = "SuperaChStatus")
Default constructor.
Definition at line 11 of file SuperaChStatus.cxx.
Referenced by larcv::SuperaChStatusProcessFactory::create().
     : SuperaBase(name)
   {}
~SuperaChStatus()
larcv::SuperaChStatus::~SuperaChStatus () inline
Default destructor.
Definition at line 37 of file SuperaChStatus.h.
References configure(), finalize(), initialize(), is(), process(), and set_chstatus().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData () inherited
Definition at line 89 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v, larcv::SuperaBase::_ptr_mcs_v, larcv::SuperaBase::_ptr_mct_v, larcv::SuperaBase::_ptr_mctruth_v, larcv::SuperaBase::_ptr_opdigit_v, larcv::SuperaBase::_ptr_sch_v, and larcv::SuperaBase::_ptr_wire_v.
Referenced by larcv::SuperaBase::finalize(), larcv::SuperaBase::initialize(), larcv::SuperaMetaMaker::process(), larcv::SuperaBase::SuperaBase(), and larcv::SuperaBase::TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
configure()
void larcv::SuperaChStatus::configure (const PSet & cfg) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 15 of file SuperaChStatus.cxx.
References _in_chstatus_producer, supera::ParamsChStatus::configure(), larcv::SuperaBase::configure(), and larcv::PSet::get().
Referenced by ~SuperaChStatus().
   {
     SuperaBase::configure(cfg);
     supera::ParamsChStatus::configure(cfg);
     _in_chstatus_producer = cfg.get<std::string>("LArChStatusProducer");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SuperaChStatus::finalize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 58 of file SuperaChStatus.cxx.
References larcv::SuperaBase::finalize().
Referenced by ~SuperaChStatus().
   { SuperaBase::finalize(); }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaChStatus::initialize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 22 of file SuperaChStatus.cxx.
References _status_m, larcv::ChStatus::Initialize(), larcv::SuperaBase::initialize(), larcv::chstatus::kUNKNOWN, supera::Nplanes(), larcv::supera::Nwires(), and larcv::ChStatus::Plane().
Referenced by ~SuperaChStatus().
   {
     SuperaBase::initialize();
     for (size_t i = 0; i < ::supera::Nplanes(); ++i) {
       ::larcv::ChStatus status;
       status.Plane(i);
       status.Initialize(::supera::Nwires(i), ::larcv::chstatus::kUNKNOWN);
       _status_m.emplace(status.Plane(), status);
     }
   }
InputLabel()
const std::string& larcv::SuperaChStatus::InputLabel () const inline
Definition at line 51 of file SuperaChStatus.h.
References _in_chstatus_producer.
Referenced by larlite::LArLiteSuperaDriver::analyze().
 { return _in_chstatus_producer; }
is()
bool larcv::SuperaChStatus::is (const std::string question) const virtual
Reimplemented from larcv::SuperaBase.
Definition at line 61 of file SuperaChStatus.cxx.
Referenced by ~SuperaChStatus().
   { return (question == "SuperaChStatus"); }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &) inherited
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const inherited
Referenced by larcv::SuperaBase::~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const inherited
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const inherited
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const inherited
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const inherited
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const inherited
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v) inherited
Definition at line 121 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v) inherited
Definition at line 124 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v) inherited
Definition at line 127 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v) inherited
Definition at line 130 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v) inherited
Definition at line 133 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v) inherited
Definition at line 136 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v) inherited
Definition at line 139 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const inherited
Definition at line 18 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::SuperaBase::_empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), larcv::SuperaMCROI::process(), and larcv::SuperaBase::~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OutChStatusLabel()
const std::string& supera::ParamsChStatus::OutChStatusLabel () const inline inherited
Definition at line 41 of file ParamsChStatus.h.
References supera::ParamsChStatus::_out_chstatus_producer.
Referenced by process().
 { return _out_chstatus_producer; }
process()
bool larcv::SuperaChStatus::process (IOManager & mgr) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 39 of file SuperaChStatus.cxx.
References _status_m, larcv::IOManager< T >::get_data(), larcv::kProductChStatus, larcv::chstatus::kUNKNOWN, LARCV_CRITICAL, supera::ParamsChStatus::OutChStatusLabel(), and larcv::SuperaBase::process().
Referenced by ~SuperaChStatus().
   {
     SuperaBase::process(mgr);
     auto ev_chstatus = (EventChStatus*)(mgr.get_data(kProductChStatus,OutChStatusLabel()));
     if(!ev_chstatus) {
       LARCV_CRITICAL() << "Output chstatus could not be created!" << std::endl;
       throw larbys();
     }
     for (auto const& id_status : _status_m)
       ev_chstatus->Insert(id_status.second);
     // Reset status
     for (auto& plane_status : _status_m) plane_status.second.Reset(::larcv::chstatus::kUNKNOWN);
     return true;
   }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name) inherited
Definition at line 15 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::larcv_base::name().
Referenced by larcv::SuperaBase::configure(), and larcv::SuperaBase::~SuperaBase().
   { _data_request_m[type]=name; }
set_chstatus()
void larcv::SuperaChStatus::set_chstatus (::larcv::PlaneID_t plane, unsigned int wire, short status)
Definition at line 33 of file SuperaChStatus.cxx.
References _status_m, and larcv::supera::Nwires().
Referenced by ~SuperaChStatus().
   {
     if (wire >= ::supera::Nwires(plane)) throw ::larcv::larbys("Invalid wire number to store status!");
     _status_m[plane].Status(wire, status);
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline inherited
Definition at line 64 of file SuperaBase.h.
References larcv::SuperaBase::_time_offset, and larcv::SuperaBase::ClearEventData().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
 { return _time_offset; }
Member Data Documentation
_in_chstatus_producer
std::string larcv::SuperaChStatus::_in_chstatus_producer private
Definition at line 54 of file SuperaChStatus.h.
Referenced by configure(), and InputLabel().
_status_m
std::map<larcv::PlaneID_t,larcv::ChStatus> larcv::SuperaChStatus::_status_m private
Definition at line 55 of file SuperaChStatus.h.
Referenced by initialize(), process(), and set_chstatus().
The documentation for this class was generated from the following files:
SuperaChStatus.h
SuperaChStatus.cxx