LArCV: larcv::LArCVSuperaDriver Class Reference
larcv::LArCVSuperaDriver Class Reference
User defined class LArCVSuperaDriver ...
#include <LArCVSuperaDriver.h>
Public Member Functions
LArCVSuperaDriver ()
Default constructor.
~LArCVSuperaDriver ()
Default destructor.
void configure (const std::string cfg_file)
void configure (const larcv::PSet &cfg)
void override_input_file (const std::vector< std::string > &flist)
void override_output_file (const std::string fname)
const std::set< std::string > & DataLabels (supera::LArDataType_t type) const
template<class T >
void SetDataPointer (const std::vector< T > &data, const std::string label)
SuperaChStatus * SuperaChStatusPointer ()
void initialize ()
bool process (size_t run, size_t subrun, size_t event)
void finalize ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
ProcessDriver _driver
std::vector< size_t > _supera_idx_v
std::map< supera::LArDataType_t, std::set< std::string > > _data_request_m
SuperaChStatus * _supera_chstatus_ptr
Detailed Description
User defined class LArCVSuperaDriver ...
these comments are used to generate doxygen documentation!
Definition at line 32 of file LArCVSuperaDriver.h.
Constructor & Destructor Documentation
LArCVSuperaDriver()
larcv::LArCVSuperaDriver::LArCVSuperaDriver ()
Default constructor.
Definition at line 8 of file LArCVSuperaDriver.cxx.
     : _driver("ProcessDriver")
     , _supera_chstatus_ptr(nullptr)
   {}
~LArCVSuperaDriver()
larcv::LArCVSuperaDriver::~LArCVSuperaDriver () inline
Default destructor.
Definition at line 40 of file LArCVSuperaDriver.h.
References configure(), DataLabels(), override_input_file(), and override_output_file().
 {}
Member Function Documentation
configure() [1/2]
void larcv::LArCVSuperaDriver::configure (const std::string cfg_file)
Definition at line 13 of file LArCVSuperaDriver.cxx.
References _driver, and larcv::ProcessDriver::configure().
Referenced by larlite::LArLiteSuperaDriver::larcv_configure(), and ~LArCVSuperaDriver().
   {
     _driver.configure(cfg_file);
   }
configure() [2/2]
void larcv::LArCVSuperaDriver::configure (const larcv::PSet & cfg)
Definition at line 18 of file LArCVSuperaDriver.cxx.
References _driver, and larcv::ProcessDriver::configure().
   {
     _driver.configure(cfg);
   }
DataLabels()
const std::set< std::string > & larcv::LArCVSuperaDriver::DataLabels (supera::LArDataType_t type) const
Definition at line 36 of file LArCVSuperaDriver.cxx.
References _data_request_m.
Referenced by larlite::LArLiteSuperaDriver::analyze(), and ~LArCVSuperaDriver().
   {
     static std::set<std::string> empty_string;
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return empty_string;
     return (*iter).second;
   }
finalize()
void larcv::LArCVSuperaDriver::finalize ()
Definition at line 85 of file LArCVSuperaDriver.cxx.
References _driver, and larcv::ProcessDriver::finalize().
Referenced by larlite::LArLiteSuperaDriver::finalize(), and SetDataPointer().
 { _driver.finalize(); }
initialize()
void larcv::LArCVSuperaDriver::initialize ()
Definition at line 44 of file LArCVSuperaDriver.cxx.
References _data_request_m, _driver, _supera_chstatus_ptr, _supera_idx_v, larcv::ProcessDriver::initialize(), larcv::ProcessBase::is(), supera::kLArDataTypeMax, LARCV_CRITICAL, larcv::SuperaBase::LArDataLabel(), larcv::ProcessDriver::process_names(), and larcv::ProcessDriver::process_ptr().
Referenced by larlite::LArLiteSuperaDriver::initialize(), and SetDataPointer().
{
     _driver.initialize();
     _supera_idx_v.clear();
     for(size_t idx=0; idx<_driver.process_names().size(); ++idx) {
       auto proc_ptr = _driver.process_ptr(idx);
       if(proc_ptr->is("SuperaMetaMaker") && idx) {
     LARCV_CRITICAL() << "SuperaMetaMaker must be the first module!" << std::endl;
     throw larbys();
       }
       if(proc_ptr->is("Supera") || proc_ptr->is("SuperaMetaMaker")) {
     _supera_idx_v.push_back(idx);
     for(size_t data_type=0; data_type<(size_t)(supera::LArDataType_t::kLArDataTypeMax); ++data_type) {
       auto const& label = ((SuperaBase*)proc_ptr)->LArDataLabel((supera::LArDataType_t)data_type);
       if(label.empty()) continue;
       _data_request_m[(supera::LArDataType_t)(data_type)].insert(label);
     }
       }
       if(_driver.process_ptr(idx)->is("SuperaChStatus")) {
     _supera_chstatus_ptr = (SuperaChStatus*)(_driver.process_ptr(idx));
     for(size_t data_type=0; data_type<(size_t)(supera::LArDataType_t::kLArDataTypeMax); ++data_type) {
       auto const& label = _supera_chstatus_ptr->LArDataLabel((supera::LArDataType_t)data_type);
       if(label.empty()) continue;
       _data_request_m[(supera::LArDataType_t)(data_type)].insert(label);
     }
       }
     }
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
override_input_file()
void larcv::LArCVSuperaDriver::override_input_file (const std::vector< std::string > & flist)
Definition at line 23 of file LArCVSuperaDriver.cxx.
References _driver, and larcv::ProcessDriver::override_input_file().
Referenced by ~LArCVSuperaDriver().
   {
     _driver.override_input_file(flist);
   }
override_output_file()
void larcv::LArCVSuperaDriver::override_output_file (const std::string fname)
Definition at line 28 of file LArCVSuperaDriver.cxx.
References _driver, and larcv::ProcessDriver::override_output_file().
Referenced by larlite::LArLiteSuperaDriver::larcv_output_file(), and ~LArCVSuperaDriver().
   {
     _driver.override_output_file(fname);
   }
process()
bool larcv::LArCVSuperaDriver::process (size_t run, size_t subrun, size_t event)
Definition at line 79 of file LArCVSuperaDriver.cxx.
References _driver, larcv::ProcessDriver::process_entry(), and larcv::ProcessDriver::set_id().
Referenced by larlite::LArLiteSuperaDriver::analyze(), and SetDataPointer().
   {
     _driver.set_id(run,subrun,event);
     return _driver.process_entry();
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetDataPointer()
template<class T > void larcv::LArCVSuperaDriver::SetDataPointer (const std::vector< T > & data, const std::string label) inline
Definition at line 53 of file LArCVSuperaDriver.h.
References _driver, _supera_idx_v, finalize(), initialize(), LARCV_INFO, process(), larcv::ProcessDriver::process_ptr(), and SuperaChStatusPointer().
Referenced by larlite::LArLiteSuperaDriver::analyze().
     {
       LARCV_INFO() << "Received LArDataType_t " << (int)(supera::LArDataType<T>()) << " by label " << label << std::endl;
       for(auto& idx : _supera_idx_v) {
     auto supera_ptr = (SuperaBase*)(_driver.process_ptr(idx));
     if(supera_ptr->LArDataLabel(supera::LArDataType<T>()) != label) continue;
     LARCV_INFO() << "Data pointer provided to: " << supera_ptr->name() << std::endl;
     supera_ptr->LArData(data);
       }
     }
SuperaChStatusPointer()
SuperaChStatus * larcv::LArCVSuperaDriver::SuperaChStatusPointer ()
Definition at line 33 of file LArCVSuperaDriver.cxx.
References _supera_chstatus_ptr.
Referenced by larlite::LArLiteSuperaDriver::analyze(), and SetDataPointer().
   { return _supera_chstatus_ptr; }
Member Data Documentation
_data_request_m
std::map<supera::LArDataType_t,std::set<std::string> > larcv::LArCVSuperaDriver::_data_request_m private
Definition at line 75 of file LArCVSuperaDriver.h.
Referenced by DataLabels(), and initialize().
_driver
ProcessDriver larcv::LArCVSuperaDriver::_driver private
Definition at line 72 of file LArCVSuperaDriver.h.
Referenced by configure(), finalize(), initialize(), override_input_file(), override_output_file(), process(), and SetDataPointer().
_supera_chstatus_ptr
SuperaChStatus* larcv::LArCVSuperaDriver::_supera_chstatus_ptr private
Definition at line 76 of file LArCVSuperaDriver.h.
Referenced by initialize(), and SuperaChStatusPointer().
_supera_idx_v
std::vector<size_t> larcv::LArCVSuperaDriver::_supera_idx_v private
Definition at line 73 of file LArCVSuperaDriver.h.
Referenced by initialize(), and SetDataPointer().
The documentation for this class was generated from the following files:
LArCVSuperaDriver.h
LArCVSuperaDriver.cxx