LArCV: larcv::SSNetEventAna Class Reference
larcv::SSNetEventAna Class Reference
#include <SSNetEventAna.h>
Public Member Functions
SSNetEventAna (const std::string name="SSNetEventAna")
~SSNetEventAna ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void Reset ()
Private Attributes
TTree * _tree
std::string _ev_img2d_prod
std::string _ev_score0_prod
std::string _ev_score1_prod
std::string _ev_score2_prod
std::string _ev_trk2d_prod
std::string _ev_shr2d_prod
float _threshold
int _run
int _subrun
int _event
int _entry
float _n_trk_pixel0
float _n_trk_pixel1
float _n_trk_pixel2
float _avg_trk_pixel_val0
float _avg_trk_pixel_val1
float _avg_trk_pixel_val2
float _std_trk_pixel_val0
float _std_trk_pixel_val1
float _std_trk_pixel_val2
float _tot_trk_pixel_val0
float _tot_trk_pixel_val1
float _tot_trk_pixel_val2
float _avg_trk_score0
float _avg_trk_score1
float _avg_trk_score2
float _std_trk_score0
float _std_trk_score1
float _std_trk_score2
float _n_shr_pixel0
float _n_shr_pixel1
float _n_shr_pixel2
float _avg_shr_pixel_val0
float _avg_shr_pixel_val1
float _avg_shr_pixel_val2
float _std_shr_pixel_val0
float _std_shr_pixel_val1
float _std_shr_pixel_val2
float _tot_shr_pixel_val0
float _tot_shr_pixel_val1
float _tot_shr_pixel_val2
float _avg_shr_score0
float _avg_shr_score1
float _avg_shr_score2
float _std_shr_score0
float _std_shr_score1
float _std_shr_score2
float _n_adc_pixel0
float _n_adc_pixel1
float _n_adc_pixel2
float _avg_adc_pixel_val0
float _avg_adc_pixel_val1
float _avg_adc_pixel_val2
float _std_adc_pixel_val0
float _std_adc_pixel_val1
float _std_adc_pixel_val2
float _tot_adc_pixel_val0
float _tot_adc_pixel_val1
float _tot_adc_pixel_val2
Detailed Description
Definition at line 11 of file SSNetEventAna.h.
Constructor & Destructor Documentation
SSNetEventAna()
larcv::SSNetEventAna::SSNetEventAna (const std::string name = "SSNetEventAna")
Definition at line 15 of file SSNetEventAna.cxx.
Referenced by larcv::SSNetEventAnaProcessFactory::create().
     : ProcessBase(name), _tree(nullptr)
   {}
~SSNetEventAna()
larcv::SSNetEventAna::~SSNetEventAna () inline
Definition at line 16 of file SSNetEventAna.h.
References configure(), finalize(), initialize(), process(), and Reset().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::SSNetEventAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file SSNetEventAna.cxx.
References _ev_img2d_prod, _ev_score0_prod, _ev_score1_prod, _ev_score2_prod, _ev_shr2d_prod, _ev_trk2d_prod, _threshold, and larcv::PSet::get().
Referenced by ~SSNetEventAna().
   {
     _ev_img2d_prod   = cfg.get<std::string>("EventImage2DProducer");
     _ev_score0_prod  = cfg.get<std::string>("Score0Image2DProducer");
     _ev_score1_prod  = cfg.get<std::string>("Score1Image2DProducer");
     _ev_score2_prod  = cfg.get<std::string>("Score2Image2DProducer");
     _ev_trk2d_prod   = cfg.get<std::string>("TrackImage2DProducer");
     _ev_shr2d_prod   = cfg.get<std::string>("ShowerImage2DProducer");
     _threshold       = cfg.get<float>("Threshold",10);
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SSNetEventAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 470 of file SSNetEventAna.cxx.
References _tree.
Referenced by ~SSNetEventAna().
   {
     _tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SSNetEventAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 30 of file SSNetEventAna.cxx.
References _avg_adc_pixel_val0, _avg_adc_pixel_val1, _avg_adc_pixel_val2, _avg_shr_pixel_val0, _avg_shr_pixel_val1, _avg_shr_pixel_val2, _avg_shr_score0, _avg_shr_score1, _avg_shr_score2, _avg_trk_pixel_val0, _avg_trk_pixel_val1, _avg_trk_pixel_val2, _avg_trk_score0, _avg_trk_score1, _avg_trk_score2, _entry, _event, _n_adc_pixel0, _n_adc_pixel1, _n_adc_pixel2, _n_shr_pixel0, _n_shr_pixel1, _n_shr_pixel2, _n_trk_pixel0, _n_trk_pixel1, _n_trk_pixel2, _run, _std_adc_pixel_val0, _std_adc_pixel_val1, _std_adc_pixel_val2, _std_shr_pixel_val0, _std_shr_pixel_val1, _std_shr_pixel_val2, _std_shr_score0, _std_shr_score1, _std_shr_score2, _std_trk_pixel_val0, _std_trk_pixel_val1, _std_trk_pixel_val2, _std_trk_score0, _std_trk_score1, _std_trk_score2, _subrun, _tot_adc_pixel_val0, _tot_adc_pixel_val1, _tot_adc_pixel_val2, _tot_shr_pixel_val0, _tot_shr_pixel_val1, _tot_shr_pixel_val2, _tot_trk_pixel_val0, _tot_trk_pixel_val1, _tot_trk_pixel_val2, _tree, and Reset().
Referenced by ~SSNetEventAna().
   {
     _tree = new TTree("SSNetEventAna","");
     _tree->Branch("run",&_run,"run/I");
     _tree->Branch("subrun",&_subrun,"subrun/I");
     _tree->Branch("event",&_event,"event/I");
     _tree->Branch("entry",&_entry,"entry/I");
     _tree->Branch("n_trk_pixel0",&_n_trk_pixel0,"_n_trk_pixel0/F");
     _tree->Branch("n_trk_pixel1",&_n_trk_pixel1,"_n_trk_pixel1/F");
     _tree->Branch("n_trk_pixel2",&_n_trk_pixel2,"_n_trk_pixel2/F");
     _tree->Branch("avg_trk_pixel_val0", &_avg_trk_pixel_val0, "avg_trk_pixel_val0/F");
     _tree->Branch("avg_trk_pixel_val1", &_avg_trk_pixel_val1, "avg_trk_pixel_val1/F");
     _tree->Branch("avg_trk_pixel_val2", &_avg_trk_pixel_val2, "avg_trk_pixel_val2/F");
     _tree->Branch("std_trk_pixel_val0", &_std_trk_pixel_val0, "std_trk_pixel_val0/F");
     _tree->Branch("std_trk_pixel_val1", &_std_trk_pixel_val1, "std_trk_pixel_val1/F");
     _tree->Branch("std_trk_pixel_val2", &_std_trk_pixel_val2, "std_trk_pixel_val2/F");
     _tree->Branch("tot_trk_pixel_val0", &_tot_trk_pixel_val0, "tot_trk_pixel_val0/F");
     _tree->Branch("tot_trk_pixel_val1", &_tot_trk_pixel_val1, "tot_trk_pixel_val1/F");
     _tree->Branch("tot_trk_pixel_val2", &_tot_trk_pixel_val2, "tot_trk_pixel_val2/F");
     _tree->Branch("avg_trk_score0", &_avg_trk_score0, "avg_trk_score0/F");
     _tree->Branch("avg_trk_score1", &_avg_trk_score1, "avg_trk_score1/F");
     _tree->Branch("avg_trk_score2", &_avg_trk_score2, "avg_trk_score2/F");
     _tree->Branch("std_trk_score0", &_std_trk_score0, "std_trk_score0/F");
     _tree->Branch("std_trk_score1", &_std_trk_score1, "std_trk_score1/F");
     _tree->Branch("std_trk_score2", &_std_trk_score2, "std_trk_score2/F");
     _tree->Branch("n_shr_pixel0",&_n_shr_pixel0,"n_shr_pixel0/F");
     _tree->Branch("n_shr_pixel1",&_n_shr_pixel1,"n_shr_pixel1/F");
     _tree->Branch("n_shr_pixel2",&_n_shr_pixel2,"n_shr_pixel2/F");
     _tree->Branch("avg_shr_pixel_val0", &_avg_shr_pixel_val0, "avg_shr_pixel_val0/F");
     _tree->Branch("avg_shr_pixel_val1", &_avg_shr_pixel_val1, "avg_shr_pixel_val1/F");
     _tree->Branch("avg_shr_pixel_val2", &_avg_shr_pixel_val2, "avg_shr_pixel_val2/F");
     _tree->Branch("std_shr_pixel_val0", &_std_shr_pixel_val0, "std_shr_pixel_val0/F");
     _tree->Branch("std_shr_pixel_val1", &_std_shr_pixel_val1, "std_shr_pixel_val1/F");
     _tree->Branch("std_shr_pixel_val2", &_std_shr_pixel_val2, "std_shr_pixel_val2/F");
     _tree->Branch("tot_shr_pixel_val0", &_tot_shr_pixel_val0, "tot_shr_pixel_val0/F");
     _tree->Branch("tot_shr_pixel_val1", &_tot_shr_pixel_val1, "tot_shr_pixel_val1/F");
     _tree->Branch("tot_shr_pixel_val2", &_tot_shr_pixel_val2, "tot_shr_pixel_val2/F");
     _tree->Branch("avg_shr_score0", &_avg_shr_score0, "avg_shr_score0/F");
     _tree->Branch("avg_shr_score1", &_avg_shr_score1, "avg_shr_score1/F");
     _tree->Branch("avg_shr_score2", &_avg_shr_score2, "avg_shr_score2/F");
     _tree->Branch("std_shr_score0", &_std_shr_score0, "std_shr_score0/F");
     _tree->Branch("std_shr_score1", &_std_shr_score1, "std_shr_score1/F");
     _tree->Branch("std_shr_score2", &_std_shr_score2, "std_shr_score2/F");
     _tree->Branch("n_adcpixel0",&_n_adc_pixel0,"n_adc_pixel0/F");
     _tree->Branch("n_adcpixel1",&_n_adc_pixel1,"n_adc_pixel1/F");
     _tree->Branch("n_adcpixel2",&_n_adc_pixel2,"n_adc_pixel2/F");
     _tree->Branch("avg_adc_pixel_val0", &_avg_adc_pixel_val0, "avg_adc_pixel_val0/F");
     _tree->Branch("avg_adc_pixel_val1", &_avg_adc_pixel_val1, "avg_adc_pixel_val1/F");
     _tree->Branch("avg_adc_pixel_val2", &_avg_adc_pixel_val2, "avg_adc_pixel_val2/F");
     _tree->Branch("std_adc_pixel_val0", &_std_adc_pixel_val0, "std_adc_pixel_val0/F");
     _tree->Branch("std_adc_pixel_val1", &_std_adc_pixel_val1, "std_adc_pixel_val1/F");
     _tree->Branch("std_adc_pixel_val2", &_std_adc_pixel_val2, "std_adc_pixel_val2/F");
     _tree->Branch("tot_adc_pixel_val0", &_tot_adc_pixel_val0, "tot_adc_pixel_val0/F");
     _tree->Branch("tot_adc_pixel_val1", &_tot_adc_pixel_val1, "tot_adc_pixel_val1/F");
     _tree->Branch("tot_adc_pixel_val2", &_tot_adc_pixel_val2, "tot_adc_pixel_val2/F");
     Reset();
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::SSNetEventAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 107 of file SSNetEventAna.cxx.
References _avg_adc_pixel_val0, _avg_adc_pixel_val1, _avg_adc_pixel_val2, _avg_shr_pixel_val0, _avg_shr_pixel_val1, _avg_shr_pixel_val2, _avg_shr_score0, _avg_shr_score1, _avg_shr_score2, _avg_trk_pixel_val0, _avg_trk_pixel_val1, _avg_trk_pixel_val2, _avg_trk_score0, _avg_trk_score1, _avg_trk_score2, _entry, _ev_img2d_prod, _ev_score0_prod, _ev_score1_prod, _ev_score2_prod, _ev_shr2d_prod, _ev_trk2d_prod, _event, _n_adc_pixel0, _n_adc_pixel1, _n_adc_pixel2, _n_shr_pixel0, _n_shr_pixel1, _n_shr_pixel2, _n_trk_pixel0, _n_trk_pixel1, _n_trk_pixel2, _run, _std_adc_pixel_val0, _std_adc_pixel_val1, _std_adc_pixel_val2, _std_shr_pixel_val0, _std_shr_pixel_val1, _std_shr_pixel_val2, _std_shr_score0, _std_shr_score1, _std_shr_score2, _std_trk_pixel_val0, _std_trk_pixel_val1, _std_trk_pixel_val2, _std_trk_score0, _std_trk_score1, _std_trk_score2, _subrun, _threshold, _tot_adc_pixel_val0, _tot_adc_pixel_val1, _tot_adc_pixel_val2, _tot_shr_pixel_val0, _tot_shr_pixel_val1, _tot_shr_pixel_val2, _tot_trk_pixel_val0, _tot_trk_pixel_val1, _tot_trk_pixel_val2, _tree, larcv::Image2D::as_vector(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, and Reset().
Referenced by ~SSNetEventAna().
   {
     Reset();
     const auto ev_img2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_img2d_prod));
     if (!ev_img2d) throw larbys("Invalid event image producer provided");
     const auto ev_score0  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_score0_prod));
     if (!ev_score0) throw larbys("Invalid event score producer provided");
     const auto ev_score1  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_score1_prod));
     if (!ev_score1) throw larbys("Invalid event score producer provided");
     const auto ev_score2  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_score2_prod));
     if (!ev_score2) throw larbys("Invalid event score producer provided");
     const auto ev_trk2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_trk2d_prod));
     if (!ev_trk2d) throw larbys("Invalid event trk producer provided");
     const auto ev_shr2d  = (EventImage2D*)(mgr.get_data(kProductImage2D,_ev_shr2d_prod));
     if (!ev_shr2d) throw larbys("Invalid event shr producer provided");
     _run    = (int) ev_img2d->run();
     _subrun = (int) ev_img2d->subrun();
     _event  = (int) ev_img2d->event();
     _entry  = (int) mgr.current_entry();
     std::array<float,3> n_trk_pixel_v;
     std::array<float,3> avg_trk_pixel_val_v;
     std::array<float,3> std_trk_pixel_val_v;
     std::array<float,3> tot_trk_pixel_val_v;
     std::array<float,3> avg_trk_score_v;
     std::array<float,3> std_trk_score_v;
     std::array<float,3> n_shr_pixel_v;
     std::array<float,3> avg_shr_pixel_val_v;
     std::array<float,3> std_shr_pixel_val_v;
     std::array<float,3> tot_shr_pixel_val_v;
     std::array<float,3> avg_shr_score_v;
     std::array<float,3> std_shr_score_v;
     std::array<float,3> n_adc_pixel_v;
     std::array<float,3> avg_adc_pixel_val_v;
     std::array<float,3> std_adc_pixel_val_v;
     std::array<float,3> tot_adc_pixel_val_v;
     for(size_t plane=0; plane<3; ++plane) {
       n_trk_pixel_v[plane] = 0;
       avg_trk_pixel_val_v[plane] = 0;
       std_trk_pixel_val_v[plane] = 0;
       tot_trk_pixel_val_v[plane] = 0;
       avg_trk_score_v[plane] = 0;
       std_trk_score_v[plane] = 0;
       n_shr_pixel_v[plane] = 0;
       avg_shr_pixel_val_v[plane] = 0;
       std_shr_pixel_val_v[plane] = 0;
       tot_shr_pixel_val_v[plane] = 0;
       avg_shr_score_v[plane] = 0;
       std_shr_score_v[plane] = 0;
       n_adc_pixel_v[plane] = 0;
       avg_adc_pixel_val_v[plane] = 0;
       std_adc_pixel_val_v[plane] = 0;
       tot_adc_pixel_val_v[plane] = 0;
     }
     for(size_t plane=0; plane<3; ++plane) {
       const auto& adc_img   = ev_img2d->Image2DArray()[plane];
       const auto& trk_img   = ev_trk2d->Image2DArray()[plane];
       const auto& shr_img   = ev_shr2d->Image2DArray()[plane];
       const auto& adc_vec   = adc_img.as_vector();
       const auto& trk_vec   = trk_img.as_vector();
       const auto& shr_vec   = shr_img.as_vector();
       const larcv::Image2D* trk_score_img_ptr = nullptr;
       const larcv::Image2D* shr_score_img_ptr = nullptr;
       switch(plane) {
       case 0:
     trk_score_img_ptr = &(ev_score0->Image2DArray().back());
     shr_score_img_ptr = &(ev_score0->Image2DArray().front());
     break;
       case 1:
     trk_score_img_ptr = &(ev_score1->Image2DArray().back());
         shr_score_img_ptr = &(ev_score1->Image2DArray().front());
     break;
       case 2:
         trk_score_img_ptr = &(ev_score2->Image2DArray().back());
         shr_score_img_ptr = &(ev_score2->Image2DArray().front());
     break;
       default:
     throw larbys("die");
       }
       const auto& trk_score_vec = trk_score_img_ptr->as_vector();
       const auto& shr_score_vec = shr_score_img_ptr->as_vector();
       auto& n_adc_pixel = n_adc_pixel_v[plane];
       auto& avg_adc_pixel_val = avg_adc_pixel_val_v[plane];
       auto& std_adc_pixel_val = std_adc_pixel_val_v[plane];
       auto& tot_adc_pixel_val = tot_adc_pixel_val_v[plane];
       auto& n_trk_pixel = n_trk_pixel_v[plane];
       auto& avg_trk_pixel_val = avg_trk_pixel_val_v[plane];
       auto& std_trk_pixel_val = std_trk_pixel_val_v[plane];
       auto& tot_trk_pixel_val = tot_trk_pixel_val_v[plane];
       auto& avg_trk_score = avg_trk_score_v[plane];
       auto& std_trk_score = std_trk_score_v[plane];
       auto& n_shr_pixel = n_shr_pixel_v[plane];
       auto& avg_shr_pixel_val = avg_shr_pixel_val_v[plane];
       auto& std_shr_pixel_val = std_shr_pixel_val_v[plane];
       auto& tot_shr_pixel_val = tot_shr_pixel_val_v[plane];
       auto& avg_shr_score = avg_shr_score_v[plane];
       auto& std_shr_score = std_shr_score_v[plane];
       //
       // avg
       //
       for(size_t ix=0; ix<adc_vec.size(); ++ix) {
     if (adc_vec[ix] < _threshold) continue;
     n_adc_pixel       += 1;
     avg_adc_pixel_val += adc_vec[ix];
     tot_adc_pixel_val += adc_vec[ix];
     if (trk_vec[ix] > _threshold) {
       n_trk_pixel       += 1;
       avg_trk_pixel_val += trk_vec[ix];
       tot_trk_pixel_val += trk_vec[ix];
     }
     if (shr_vec[ix] > _threshold)  {
       n_shr_pixel       += 1;
       avg_shr_pixel_val += shr_vec[ix];
       tot_shr_pixel_val += shr_vec[ix];
     }
       }
       assert (shr_score_vec.size() == trk_score_vec.size());
       size_t n_trk_score = 0;
       size_t n_shr_score = 0;
       for(size_t ix=0; ix < shr_score_vec.size(); ++ix) {
     if (trk_score_vec[ix]>0) {
       avg_trk_score += trk_score_vec[ix];
       n_trk_score += 1;
     }
     if(shr_score_vec[ix]>0) {
       avg_shr_score += shr_score_vec[ix];
       n_shr_score += 1;
     }
       }
       avg_adc_pixel_val /= n_adc_pixel;
       avg_trk_pixel_val /= n_trk_pixel;
       avg_shr_pixel_val /= n_shr_pixel;
       avg_trk_score /= n_trk_score;
       avg_shr_score /= n_shr_score;
       //
       // std
       //
       for(size_t ix=0; ix<adc_vec.size(); ++ix) {
     if (adc_vec[ix] < _threshold) continue;
     std_adc_pixel_val += std::pow(adc_vec[ix] - avg_adc_pixel_val,2);
     if (trk_vec[ix] > _threshold) {
       std_trk_pixel_val += std::pow(trk_vec[ix] - avg_trk_pixel_val,2);
     }
     if (shr_vec[ix] > _threshold)  {
       std_shr_pixel_val += std::pow(shr_vec[ix] - avg_shr_pixel_val,2);
     }
       }
       for(size_t ix=0; ix < shr_score_vec.size(); ++ix) {
     if (trk_score_vec[ix] > 0)
       std_trk_score += std::pow(trk_score_vec[ix] - avg_trk_score,2);
     if (shr_score_vec[ix] > 0)
       std_shr_score += std::pow(shr_score_vec[ix] - avg_shr_score,2);
       }
       std_adc_pixel_val /= (n_adc_pixel - 1);
       std_trk_pixel_val /= (n_trk_pixel - 1);
       std_shr_pixel_val /= (n_shr_pixel - 1);
       std_trk_score /= (n_trk_score - 1);
       std_shr_score /= (n_shr_score - 1);
       std_adc_pixel_val = std::sqrt(std_adc_pixel_val);
       std_trk_pixel_val = std::sqrt(std_trk_pixel_val);
       std_shr_pixel_val = std::sqrt(std_shr_pixel_val);
       std_trk_score = std::sqrt(std_trk_score);
       std_shr_score = std::sqrt(std_shr_score);
     } // end plane
     //
     // plane 0
     //
     _n_trk_pixel0   = n_trk_pixel_v[0];
     _avg_trk_pixel_val0 = avg_trk_pixel_val_v[0];
     _std_trk_pixel_val0 = std_trk_pixel_val_v[0];
     _tot_trk_pixel_val0 = tot_trk_pixel_val_v[0];
     _avg_trk_score0 = avg_trk_score_v[0];
     _std_trk_score0 = std_trk_score_v[0];
     _n_shr_pixel0   = n_shr_pixel_v[0];
     _avg_shr_pixel_val0 = avg_shr_pixel_val_v[0];
     _std_shr_pixel_val0 = std_shr_pixel_val_v[0];
     _tot_shr_pixel_val0 = tot_shr_pixel_val_v[0];
     _avg_shr_score0 = avg_shr_score_v[0];
     _std_shr_score0 = std_shr_score_v[0];
     _n_adc_pixel0   = n_adc_pixel_v[0];
     _avg_adc_pixel_val0 = avg_adc_pixel_val_v[0];
     _std_adc_pixel_val0 = std_adc_pixel_val_v[0];
     _tot_adc_pixel_val0 = tot_adc_pixel_val_v[0];
     //
     // plane 1
     //
     _n_trk_pixel1   = n_trk_pixel_v[1];
     _avg_trk_pixel_val1 = avg_trk_pixel_val_v[1];
     _std_trk_pixel_val1 = std_trk_pixel_val_v[1];
     _tot_trk_pixel_val1 = tot_trk_pixel_val_v[1];
     _avg_trk_score1 = avg_trk_score_v[1];
     _std_trk_score1 = std_trk_score_v[1];
     _n_shr_pixel1   = n_shr_pixel_v[1];
     _avg_shr_pixel_val1 = avg_shr_pixel_val_v[1];
     _std_shr_pixel_val1 = std_shr_pixel_val_v[1];
     _tot_shr_pixel_val1 = tot_shr_pixel_val_v[1];
     _avg_shr_score1 = avg_shr_score_v[1];
     _std_shr_score1 = std_shr_score_v[1];
     _n_adc_pixel1   = n_adc_pixel_v[1];
     _avg_adc_pixel_val1 = avg_adc_pixel_val_v[1];
     _std_adc_pixel_val1 = std_adc_pixel_val_v[1];
     _tot_adc_pixel_val1 = tot_adc_pixel_val_v[1];
     //
     // plane 2
     //
     _n_trk_pixel2   = n_trk_pixel_v[2];
     _avg_trk_pixel_val2 = avg_trk_pixel_val_v[2];
     _std_trk_pixel_val2 = std_trk_pixel_val_v[2];
     _tot_trk_pixel_val2 = tot_trk_pixel_val_v[2];
     _avg_trk_score2 = avg_trk_score_v[2];
     _std_trk_score2 = std_trk_score_v[2];
     _n_shr_pixel2   = n_shr_pixel_v[2];
     _avg_shr_pixel_val2 = avg_shr_pixel_val_v[2];
     _std_shr_pixel_val2 = std_shr_pixel_val_v[2];
     _tot_shr_pixel_val2 = tot_shr_pixel_val_v[2];
     _avg_shr_score2 = avg_shr_score_v[2];
     _std_shr_score2 = std_shr_score_v[2];
     _n_adc_pixel2   = n_adc_pixel_v[2];
     _avg_adc_pixel_val2 = avg_adc_pixel_val_v[2];
     _std_adc_pixel_val2 = std_adc_pixel_val_v[2];
     _tot_adc_pixel_val2 = tot_adc_pixel_val_v[2];
     _tree->Fill();
     return true;
   } // end process
Reset()
void larcv::SSNetEventAna::Reset () private
Definition at line 397 of file SSNetEventAna.cxx.
References _avg_adc_pixel_val0, _avg_adc_pixel_val1, _avg_adc_pixel_val2, _avg_shr_pixel_val0, _avg_shr_pixel_val1, _avg_shr_pixel_val2, _avg_shr_score0, _avg_shr_score1, _avg_shr_score2, _avg_trk_pixel_val0, _avg_trk_pixel_val1, _avg_trk_pixel_val2, _avg_trk_score0, _avg_trk_score1, _avg_trk_score2, _entry, _event, _n_adc_pixel0, _n_adc_pixel1, _n_adc_pixel2, _n_shr_pixel0, _n_shr_pixel1, _n_shr_pixel2, _n_trk_pixel0, _n_trk_pixel1, _n_trk_pixel2, _run, _std_adc_pixel_val0, _std_adc_pixel_val1, _std_adc_pixel_val2, _std_shr_pixel_val0, _std_shr_pixel_val1, _std_shr_pixel_val2, _std_shr_score0, _std_shr_score1, _std_shr_score2, _std_trk_pixel_val0, _std_trk_pixel_val1, _std_trk_pixel_val2, _std_trk_score0, _std_trk_score1, _std_trk_score2, _subrun, _tot_adc_pixel_val0, _tot_adc_pixel_val1, _tot_adc_pixel_val2, _tot_shr_pixel_val0, _tot_shr_pixel_val1, _tot_shr_pixel_val2, _tot_trk_pixel_val0, _tot_trk_pixel_val1, _tot_trk_pixel_val2, larcv::kINVALID_FLOAT, and larcv::kINVALID_INT.
Referenced by initialize(), process(), and ~SSNetEventAna().
{
     _run = kINVALID_INT;
     _subrun = kINVALID_INT;
     _event = kINVALID_INT;
     _entry = kINVALID_INT;
     _n_trk_pixel0 = kINVALID_FLOAT;
     _n_trk_pixel1 = kINVALID_FLOAT;
     _n_trk_pixel2 = kINVALID_FLOAT;
     _avg_trk_pixel_val0 = kINVALID_FLOAT;
     _avg_trk_pixel_val1 = kINVALID_FLOAT;
     _avg_trk_pixel_val2 = kINVALID_FLOAT;
     _std_trk_pixel_val0 = kINVALID_FLOAT;
     _std_trk_pixel_val1 = kINVALID_FLOAT;
     _std_trk_pixel_val2 = kINVALID_FLOAT;
     _tot_trk_pixel_val0 = kINVALID_FLOAT;
     _tot_trk_pixel_val1 = kINVALID_FLOAT;
     _tot_trk_pixel_val2 = kINVALID_FLOAT;
     _avg_trk_score0 = kINVALID_FLOAT;
     _avg_trk_score1 = kINVALID_FLOAT;
     _avg_trk_score2 = kINVALID_FLOAT;
     _std_trk_score0 = kINVALID_FLOAT;
     _std_trk_score1 = kINVALID_FLOAT;
     _std_trk_score2 = kINVALID_FLOAT;
     _n_shr_pixel0 = kINVALID_FLOAT;
     _n_shr_pixel1 = kINVALID_FLOAT;
     _n_shr_pixel2 = kINVALID_FLOAT;
     _avg_shr_pixel_val0 = kINVALID_FLOAT;
     _avg_shr_pixel_val1 = kINVALID_FLOAT;
     _avg_shr_pixel_val2 = kINVALID_FLOAT;
     _std_shr_pixel_val0 = kINVALID_FLOAT;
     _std_shr_pixel_val1 = kINVALID_FLOAT;
     _std_shr_pixel_val2 = kINVALID_FLOAT;
     _tot_shr_pixel_val0 = kINVALID_FLOAT;
     _tot_shr_pixel_val1 = kINVALID_FLOAT;
     _tot_shr_pixel_val2 = kINVALID_FLOAT;
     _avg_shr_score0 = kINVALID_FLOAT;
     _avg_shr_score1 = kINVALID_FLOAT;
     _avg_shr_score2 = kINVALID_FLOAT;
     _std_shr_score0 = kINVALID_FLOAT;
     _std_shr_score1 = kINVALID_FLOAT;
     _std_shr_score2 = kINVALID_FLOAT;
     _n_adc_pixel0 = kINVALID_FLOAT;
     _n_adc_pixel1 = kINVALID_FLOAT;
     _n_adc_pixel2 = kINVALID_FLOAT;
     _avg_adc_pixel_val0 = kINVALID_FLOAT;
     _avg_adc_pixel_val1 = kINVALID_FLOAT;
     _avg_adc_pixel_val2 = kINVALID_FLOAT;
     _std_adc_pixel_val0 = kINVALID_FLOAT;
     _std_adc_pixel_val1 = kINVALID_FLOAT;
     _std_adc_pixel_val2 = kINVALID_FLOAT;
     _tot_adc_pixel_val0 = kINVALID_FLOAT;
     _tot_adc_pixel_val1 = kINVALID_FLOAT;
     _tot_adc_pixel_val2 = kINVALID_FLOAT;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_avg_adc_pixel_val0
float larcv::SSNetEventAna::_avg_adc_pixel_val0 private
Definition at line 95 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_adc_pixel_val1
float larcv::SSNetEventAna::_avg_adc_pixel_val1 private
Definition at line 96 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_adc_pixel_val2
float larcv::SSNetEventAna::_avg_adc_pixel_val2 private
Definition at line 97 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_pixel_val0
float larcv::SSNetEventAna::_avg_shr_pixel_val0 private
Definition at line 71 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_pixel_val1
float larcv::SSNetEventAna::_avg_shr_pixel_val1 private
Definition at line 72 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_pixel_val2
float larcv::SSNetEventAna::_avg_shr_pixel_val2 private
Definition at line 73 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_score0
float larcv::SSNetEventAna::_avg_shr_score0 private
Definition at line 83 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_score1
float larcv::SSNetEventAna::_avg_shr_score1 private
Definition at line 84 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_shr_score2
float larcv::SSNetEventAna::_avg_shr_score2 private
Definition at line 85 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_pixel_val0
float larcv::SSNetEventAna::_avg_trk_pixel_val0 private
Definition at line 47 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_pixel_val1
float larcv::SSNetEventAna::_avg_trk_pixel_val1 private
Definition at line 48 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_pixel_val2
float larcv::SSNetEventAna::_avg_trk_pixel_val2 private
Definition at line 49 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_score0
float larcv::SSNetEventAna::_avg_trk_score0 private
Definition at line 59 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_score1
float larcv::SSNetEventAna::_avg_trk_score1 private
Definition at line 60 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_avg_trk_score2
float larcv::SSNetEventAna::_avg_trk_score2 private
Definition at line 61 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_entry
int larcv::SSNetEventAna::_entry private
Definition at line 41 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_ev_img2d_prod
std::string larcv::SSNetEventAna::_ev_img2d_prod private
Definition at line 29 of file SSNetEventAna.h.
Referenced by configure(), and process().
_ev_score0_prod
std::string larcv::SSNetEventAna::_ev_score0_prod private
Definition at line 30 of file SSNetEventAna.h.
Referenced by configure(), and process().
_ev_score1_prod
std::string larcv::SSNetEventAna::_ev_score1_prod private
Definition at line 31 of file SSNetEventAna.h.
Referenced by configure(), and process().
_ev_score2_prod
std::string larcv::SSNetEventAna::_ev_score2_prod private
Definition at line 32 of file SSNetEventAna.h.
Referenced by configure(), and process().
_ev_shr2d_prod
std::string larcv::SSNetEventAna::_ev_shr2d_prod private
Definition at line 34 of file SSNetEventAna.h.
Referenced by configure(), and process().
_ev_trk2d_prod
std::string larcv::SSNetEventAna::_ev_trk2d_prod private
Definition at line 33 of file SSNetEventAna.h.
Referenced by configure(), and process().
_event
int larcv::SSNetEventAna::_event private
Definition at line 40 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_adc_pixel0
float larcv::SSNetEventAna::_n_adc_pixel0 private
Definition at line 91 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_adc_pixel1
float larcv::SSNetEventAna::_n_adc_pixel1 private
Definition at line 92 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_adc_pixel2
float larcv::SSNetEventAna::_n_adc_pixel2 private
Definition at line 93 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_shr_pixel0
float larcv::SSNetEventAna::_n_shr_pixel0 private
Definition at line 67 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_shr_pixel1
float larcv::SSNetEventAna::_n_shr_pixel1 private
Definition at line 68 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_shr_pixel2
float larcv::SSNetEventAna::_n_shr_pixel2 private
Definition at line 69 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_trk_pixel0
float larcv::SSNetEventAna::_n_trk_pixel0 private
Definition at line 43 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_trk_pixel1
float larcv::SSNetEventAna::_n_trk_pixel1 private
Definition at line 44 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_n_trk_pixel2
float larcv::SSNetEventAna::_n_trk_pixel2 private
Definition at line 45 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_run
int larcv::SSNetEventAna::_run private
Definition at line 38 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_adc_pixel_val0
float larcv::SSNetEventAna::_std_adc_pixel_val0 private
Definition at line 99 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_adc_pixel_val1
float larcv::SSNetEventAna::_std_adc_pixel_val1 private
Definition at line 100 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_adc_pixel_val2
float larcv::SSNetEventAna::_std_adc_pixel_val2 private
Definition at line 101 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_pixel_val0
float larcv::SSNetEventAna::_std_shr_pixel_val0 private
Definition at line 75 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_pixel_val1
float larcv::SSNetEventAna::_std_shr_pixel_val1 private
Definition at line 76 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_pixel_val2
float larcv::SSNetEventAna::_std_shr_pixel_val2 private
Definition at line 77 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_score0
float larcv::SSNetEventAna::_std_shr_score0 private
Definition at line 87 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_score1
float larcv::SSNetEventAna::_std_shr_score1 private
Definition at line 88 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_shr_score2
float larcv::SSNetEventAna::_std_shr_score2 private
Definition at line 89 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_pixel_val0
float larcv::SSNetEventAna::_std_trk_pixel_val0 private
Definition at line 51 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_pixel_val1
float larcv::SSNetEventAna::_std_trk_pixel_val1 private
Definition at line 52 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_pixel_val2
float larcv::SSNetEventAna::_std_trk_pixel_val2 private
Definition at line 53 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_score0
float larcv::SSNetEventAna::_std_trk_score0 private
Definition at line 63 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_score1
float larcv::SSNetEventAna::_std_trk_score1 private
Definition at line 64 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_std_trk_score2
float larcv::SSNetEventAna::_std_trk_score2 private
Definition at line 65 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_subrun
int larcv::SSNetEventAna::_subrun private
Definition at line 39 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_threshold
float larcv::SSNetEventAna::_threshold private
Definition at line 36 of file SSNetEventAna.h.
Referenced by configure(), and process().
_tot_adc_pixel_val0
float larcv::SSNetEventAna::_tot_adc_pixel_val0 private
Definition at line 103 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_adc_pixel_val1
float larcv::SSNetEventAna::_tot_adc_pixel_val1 private
Definition at line 104 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_adc_pixel_val2
float larcv::SSNetEventAna::_tot_adc_pixel_val2 private
Definition at line 105 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_shr_pixel_val0
float larcv::SSNetEventAna::_tot_shr_pixel_val0 private
Definition at line 79 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_shr_pixel_val1
float larcv::SSNetEventAna::_tot_shr_pixel_val1 private
Definition at line 80 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_shr_pixel_val2
float larcv::SSNetEventAna::_tot_shr_pixel_val2 private
Definition at line 81 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_trk_pixel_val0
float larcv::SSNetEventAna::_tot_trk_pixel_val0 private
Definition at line 55 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_trk_pixel_val1
float larcv::SSNetEventAna::_tot_trk_pixel_val1 private
Definition at line 56 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tot_trk_pixel_val2
float larcv::SSNetEventAna::_tot_trk_pixel_val2 private
Definition at line 57 of file SSNetEventAna.h.
Referenced by initialize(), process(), and Reset().
_tree
TTree* larcv::SSNetEventAna::_tree private
Definition at line 27 of file SSNetEventAna.h.
Referenced by finalize(), initialize(), and process().
The documentation for this class was generated from the following files:
SSNetEventAna.h
SSNetEventAna.cxx