LArCV: larcv::EventROIFactory Class Reference
larcv::EventROIFactory Class Reference
#include <EventROI.h>
Public Member Functions
EventROIFactory ()
ctor
~EventROIFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 67 of file EventROI.h.
Constructor & Destructor Documentation
EventROIFactory()
larcv::EventROIFactory::EventROIFactory () inline
ctor
Definition at line 70 of file EventROI.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductROI.
 { DataProductFactory::get().add_factory(kProductROI,this); }
~EventROIFactory()
larcv::EventROIFactory::~EventROIFactory () inline
dtor
Definition at line 72 of file EventROI.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventROIFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 74 of file EventROI.h.
References larcv::EventROI::EventROI().
 { return new EventROI; }
The documentation for this class was generated from the following file:
EventROI.h