LArCV: larcv::hires::HiResImageDivider Class Reference
larcv::hires::HiResImageDivider Class Reference
#include <HiResImageDivider.h>
Public Member Functions
HiResImageDivider (const std::string name="HiResImageDivider")
Default constructor.
~HiResImageDivider ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Member Functions
void ApplySCE (larcv::Vertex &vtx)
bool isInteresting (const larcv::ROI &roi)
bool isAbovePixelThreshold (const larcv::EventImage2D &imgs)
int findVertexDivision (const larcv::ROI &roi)
void cropEventImages (const larcv::EventImage2D &event_images, const larcv::hires::DivisionDef &div, larcv::EventImage2D &output_images)
void generateSingleCosmicDivision (std::vector< int > &divlist, const EventImage2D &input_event_images, larcv::ROI &roi)
void generateSingleMCDivision (std::vector< int > &divlist, EventROI &event_roi, larcv::ROI &roi)
void generateFitleredWholeImageDivision (std::vector< int > &divlist, const EventImage2D &input_event_images)
void LoadDivisionsFromFile ()
void CalculateDivisions ()
Protected Attributes
bool fApplySCE
bool fUseDivFile
std::string fDivisionFile
int fNumZdivisions
int fNumYdivisions
int fNumTdivisions
bool fOverlapDivisions
int fNPlanes
int fTickStart
int fTickPreCompression
int fWirePreCompression
int fMaxWireImageWidth
int fMaxWireInRegion
int fNumNonVertexDivisionsPerEvent
bool fCropSegmentation
bool fCropPMTWeighted
int fMaxRedrawAttempts
int fRedrawOnNEmptyPlanes
std::vector< int > fNumPixelRedrawThresh_v
std::vector< float > fInterestingPixelThresh_v
std::vector< larcv::hires::DivisionDef > m_divisions
std::string fInputPMTProducer
std::string fInputROIProducer
std::string fOutputROIProducer
std::string fInputImageProducer
std::string fInputSegmentationProducer
std::string fInputPMTWeightedProducer
std::string fOutputImageProducer
std::string fOutputSegmentationProducer
std::string fOutputPMTWeightedProducer
bool fDivideWholeImage
size_t fProcessedEvent
size_t fROISkippedEvent
size_t fProcessedROI
size_t fROISkipped
Detailed Description
Definition at line 36 of file HiResImageDivider.h.
Constructor & Destructor Documentation
HiResImageDivider()
larcv::hires::HiResImageDivider::HiResImageDivider (const std::string name = "HiResImageDivider")
Default constructor.
Definition at line 20 of file HiResImageDivider.cxx.
Referenced by larcv::hires::HiResImageDividerProcessFactory::create().
       : ProcessBase(name)
     {}
~HiResImageDivider()
larcv::hires::HiResImageDivider::~HiResImageDivider () inline
Default destructor.
Definition at line 44 of file HiResImageDivider.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ApplySCE()
void larcv::hires::HiResImageDivider::ApplySCE (larcv::Vertex & vtx) protected
Definition at line 24 of file HiResImageDivider.cxx.
References larcv::Vertex::Reset(), larcv::Vertex::T(), larcv::Vertex::X(), larcv::Vertex::Y(), and larcv::Vertex::Z().
Referenced by findVertexDivision().
     {
       static larutil::SpaceChargeMicroBooNE sce;
       auto pos = sce.GetPosOffsets(vtx.X(), vtx.Y(), vtx.Z());
       vtx.Reset( (vtx.X() - pos[0] + 0.7),
          (vtx.Y() + pos[1]),
          (vtx.Z() + pos[2]),
          vtx.T());
     }
CalculateDivisions()
void larcv::hires::HiResImageDivider::CalculateDivisions () protected
Definition at line 595 of file HiResImageDivider.cxx.
References fMaxWireImageWidth, fNumTdivisions, fNumYdivisions, fNumZdivisions, fOverlapDivisions, divalgo::DividerAlgo::getregionwires(), larcv::hires::DivisionDef::ID(), LARCV_INFO, and m_divisions.
Referenced by initialize().
{
       LARCV_INFO() << "Calculating Divisions." << std::endl;
       std::set<larcv::hires::DivisionID> unique_div_s;
       fMaxWireImageWidth = 0; // will fill this later
       float zbounds[2] = {    0.0, 1037.0 }; //{ 0.04, 1036.45 };
       float ybounds[2] = { -116.0,  118.0 }; //{-115.51,117.44};
       float tbounds[2] = { 2400.0, 8448.0 }; // 2400+6048 // TICKS
       float trigger_tick = 3200; // sets 'x=0'
       float zWidth = (zbounds[1]-zbounds[0])/fNumZdivisions;
       float yWidth = (ybounds[1]-ybounds[0])/fNumYdivisions;
       float tWidth = (tbounds[1]-tbounds[0])/fNumTdivisions; // in ticks
       int nz = fNumZdivisions;
       int ny = fNumYdivisions;
       int nt = fNumTdivisions;
       float zstep = zWidth;
       float ystep = yWidth;
       float tstep = tWidth;
       float driftx = 0.11*0.5; // (0.11 cm per microsecond) * 0.5 microseconds per tick
       if ( fOverlapDivisions ) {
     nz = 2*fNumZdivisions-1;
     ny = 2*fNumYdivisions-1;
     nt = 2*fNumTdivisions-1;
     zstep *= 0.5;
     ystep *= 0.5;
     tstep *= 0.5;
       }
       std::vector<int> uwires;
       std::vector<int> vwires;
       std::vector<int> ywires;
       divalgo::DividerAlgo algo;
       for (int iz=0; iz<nz; iz++) {
     for (int iy=0; iy<ny; iy++) {
       float box_z[2] = { zbounds[0]+iz*zstep, zbounds[0]+iz*zstep+zWidth };
       float box_y[2] = { ybounds[0]+iy*ystep, ybounds[0]+iy*ystep+zWidth };
       float bbox[4] = { box_z[0], box_y[0], box_z[1], box_y[1] };
       algo.getregionwires( bbox[0], bbox[1], bbox[2], bbox[3], ywires, uwires, vwires );
       int ubounds[2] = { uwires.at(0), uwires.back() };
       int vbounds[2] = { vwires.at(0), vwires.back() };
       int ybounds[2] = { ywires.at(0), ywires.back() };
       if ( (int)uwires.size()>fMaxWireImageWidth ) fMaxWireImageWidth = (int)uwires.size();
       if ( (int)vwires.size()>fMaxWireImageWidth ) fMaxWireImageWidth = (int)vwires.size();
       if ( (int)ywires.size()>fMaxWireImageWidth ) fMaxWireImageWidth = (int)ywires.size();
       for (int it=0; it<nt; it++) {
         int tickbounds[2] = { (int)(tbounds[0] + it*tstep), (int)(tbounds[0] + it*tstep + tWidth) };
         float box_x[2] = { (tickbounds[0]-trigger_tick)*driftx, (tickbounds[1]-trigger_tick)*driftx };
         DivisionDef div( ubounds, vbounds, ybounds, tickbounds, box_x, box_y, box_z );
         auto const& div_id = div.ID();
         if(unique_div_s.find(div_id) == unique_div_s.end()) {
           unique_div_s.insert(div.ID());
           m_divisions.emplace_back(div);
         }
       }//end of t-loop
     }//end of y-loop
       }//end of z-loop
     }
configure()
void larcv::hires::HiResImageDivider::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 34 of file HiResImageDivider.cxx.
References fApplySCE, fCropPMTWeighted, fCropSegmentation, fDivideWholeImage, fDivisionFile, fInputImageProducer, fInputPMTProducer, fInputPMTWeightedProducer, fInputROIProducer, fInputSegmentationProducer, fInterestingPixelThresh_v, fMaxRedrawAttempts, fMaxWireImageWidth, fNPlanes, fNumNonVertexDivisionsPerEvent, fNumPixelRedrawThresh_v, fNumTdivisions, fNumYdivisions, fNumZdivisions, fOutputImageProducer, fOutputPMTWeightedProducer, fOutputROIProducer, fOutputSegmentationProducer, fOverlapDivisions, fRedrawOnNEmptyPlanes, fTickPreCompression, fTickStart, fUseDivFile, fWirePreCompression, and larcv::PSet::get().
Referenced by ~HiResImageDivider().
     {
       fApplySCE           = cfg.get<bool>("ApplySCE",true);   // apply space-charge-effect correction
       fUseDivFile         = cfg.get<bool>("UseDivFile",true);       // load division definitions from file
       if ( !fUseDivFile ) {
     fDivisionFile       = cfg.get<std::string>("DivisionFile",""); // division file [not used]
     fNumZdivisions      = cfg.get<int>("NumZdivisions");           // number of pieces to divide Z dimension [must define]
     fNumYdivisions      = cfg.get<int>("NumYdivisions");           // number of pieces to divide Y dimension [must define]
     fNumTdivisions      = cfg.get<int>("NumTdivisions");           // number of pieces to divide T dimension [must define]
     fOverlapDivisions   = cfg.get<bool>("OverlapDivisions",false); // also make overlapping divisions that are offset by half-widths
       }
       else {
     fDivisionFile       = cfg.get<std::string>("DivisionFile");      // division file [must have this]
     fNumZdivisions      = cfg.get<int>("NumZdivisions",1);           // number of pieces to divide Z dimension [not used]
     fNumYdivisions      = cfg.get<int>("NumYdivisions",1);           // number of pieces to divide Y dimension [not used]
     fNumTdivisions      = cfg.get<int>("NumTdivisions",1);           // number of pieces to divide T dimension [not used]
     fOverlapDivisions   = cfg.get<bool>("OverlapDivisions",false); // also make overlapping divisions that are offset by half-widths
       }
       fNPlanes            = cfg.get<int>( "NPlanes", 3 );
       fTickStart          = cfg.get<int>( "TickStart", 2400 );
       fTickPreCompression = cfg.get<int>( "TickPreCompression", 6 );
       fWirePreCompression = cfg.get<int>( "WirePreCompression", 1 );
       fMaxWireImageWidth  = cfg.get<int>( "MaxWireImageWidth" );
       fInputPMTProducer   = cfg.get<std::string>( "InputPMTProducer" );
       fInputROIProducer   = cfg.get<std::string>( "InputROIProducer" );
       fOutputROIProducer  = cfg.get<std::string>( "OutputROIProducer" );
       fNumNonVertexDivisionsPerEvent = cfg.get<int>( "NumNonVertexDivisionsPerEvent" );
       fInputImageProducer = cfg.get<std::string>( "InputImageProducer" );
       fOutputImageProducer = cfg.get<std::string>( "OutputImageProducer" );
       fInputSegmentationProducer = cfg.get<std::string>( "InputSegmentationProducer" );
       fOutputSegmentationProducer = cfg.get<std::string>( "OutputSegmentationProducer" );
       fInputPMTWeightedProducer = cfg.get<std::string>( "InputPMTWeightedProducer" );
       fOutputPMTWeightedProducer = cfg.get<std::string>( "OutputPMTWeightedProducer" );
       fCropSegmentation = cfg.get<bool>( "CropSegmentation" );
       fCropPMTWeighted  = cfg.get<bool>( "CropPMTWeighted" );
       fNumPixelRedrawThresh_v = cfg.get< std::vector<int> >( "NumPixelRedrawThresh" );
       fInterestingPixelThresh_v = cfg.get< std::vector<float> >( "InterestingPixelThresh" );
       fRedrawOnNEmptyPlanes = cfg.get<int>("RedrawOnNEmptyPlanes",2);
       fMaxRedrawAttempts = cfg.get<int>("MaxRedrawAttempts");
       fDivideWholeImage = cfg.get<bool>("DivideWholeImage");
     }
cropEventImages()
void larcv::hires::HiResImageDivider::cropEventImages (const larcv::EventImage2D & event_images, const larcv::hires::DivisionDef & div, larcv::EventImage2D & output_images) protected
Definition at line 442 of file HiResImageDivider.cxx.
References larcv::ImageMeta::dump(), larcv::EventImage2D::Emplace(), fMaxWireImageWidth, larcv::hires::DivisionDef::getPlaneMeta(), larcv::EventImage2D::Image2DArray(), LARCV_DEBUG, and larcv::ImageMeta::update().
Referenced by generateFitleredWholeImageDivision(), generateSingleCosmicDivision(), and process().
{
       // Output Image Container
       std::vector<larcv::Image2D> cropped_images;
       LARCV_DEBUG() << "Images to crop: "<< event_images.Image2DArray().size() << std::endl;
       for ( auto const& img : event_images.Image2DArray() ) {
     int iplane = (int)img.meta().plane();
     larcv::ImageMeta const& divPlaneMeta = div.getPlaneMeta( iplane );
     // divPlaneMeta is based on un-compressed time axis.
     // align the same scaling as img meta
     auto scaled = divPlaneMeta;
     scaled.update(scaled.height()/img.meta().pixel_height(),scaled.cols());
     auto cropmeta = img.meta().overlap(scaled);
     auto cropped = img.crop(cropmeta);
     cropped.resize(fMaxWireImageWidth,fMaxWireImageWidth,0.);
     //div.print();
     LARCV_DEBUG() << "image: " << std::endl << img.meta().dump() ;
     LARCV_DEBUG() << "div: " << std::endl << divPlaneMeta.dump() ;
     LARCV_DEBUG() << "scaled: " << std::endl << scaled.dump() ;
     LARCV_DEBUG() << "to-be-cropped: " << std::endl << cropmeta.dump() ;
     LARCV_DEBUG() << "cropped: " << std::endl << cropped.meta().dump() ;
     /*
     // we adjust the actual crop meta
     int tstart = divPlaneMeta.min_y();
     int twidth = fMaxWireImageWidth*fTickDownSample;
     int tmax = std::min( tstart+twidth, (int)img.meta().max_y() );
     larcv::ImageMeta cropmeta( divPlaneMeta.width(), twidth,
                    twidth, divPlaneMeta.width(),
                    divPlaneMeta.min_x(), tmax );
     LARCV_INFO() << "image: " << std::endl << img.meta().dump() << std::endl;
     LARCV_INFO() << "div: " << std::endl << divPlaneMeta.dump() << std::endl;
     LARCV_INFO() << "crop: " << std::endl << cropmeta.dump() << std::endl;
     Image2D cropped = img.crop( cropmeta );
     LARCV_INFO() << "cropped." << std::endl;
     //cropped.resize( fMaxWireImageWidth*fTickDownSample, fMaxWireImageWidth, 0.0 );  // resize to final image size (and zero pad extra space)
     LARCV_INFO() << "resized." << std::endl;
     //cropped.compress( (int)cropped.meta().height()/6, fMaxWireImageWidth, larcv::Image2D::kSum );
     LARCV_INFO() << "downsampled. " << cropped.meta().height() << " x " << cropped.meta().width() << std::endl;
     */
     cropped_images.emplace_back( cropped );
     //LARCV_INFO() << "stored." << std::endl;
       }//end of plane loop
       output_images.Emplace( std::move( cropped_images ) );
     }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by process().
     { return _event_creator; }
finalize()
void larcv::hires::HiResImageDivider::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 292 of file HiResImageDivider.cxx.
References fProcessedEvent, fProcessedROI, fROISkipped, fROISkippedEvent, and LARCV_NORMAL.
Referenced by ~HiResImageDivider().
     {
       LARCV_NORMAL() << "Skipped events due to vertex-box not overlapping with ROI: " << fROISkippedEvent << " / " << fProcessedEvent << std::endl;
       LARCV_NORMAL() << "Skipped ROI due to not within vertex-box: " << fROISkipped << " / " << fProcessedROI << std::endl;
     }
findVertexDivision()
int larcv::hires::HiResImageDivider::findVertexDivision (const larcv::ROI & roi) protected
Definition at line 424 of file HiResImageDivider.cxx.
References ApplySCE(), fApplySCE, larcv::hires::DivisionDef::isInsideDetRegion(), m_divisions, and larcv::ROI::Position().
Referenced by generateSingleCosmicDivision(), and generateSingleMCDivision().
{
       auto vtx = roi.Position();
       if(fApplySCE) ApplySCE(vtx);
       int regionindex = 0;
       for ( std::vector< larcv::hires::DivisionDef >::iterator it=m_divisions.begin(); it!=m_divisions.end(); it++) {
     DivisionDef const& div = (*it);
     if ( div.isInsideDetRegion( vtx.X(), vtx.Y(), vtx.Z() ) )
       return regionindex;
     regionindex++;
       }
       return -1;
     }
generateFitleredWholeImageDivision()
void larcv::hires::HiResImageDivider::generateFitleredWholeImageDivision (std::vector< int > & divlist, const EventImage2D & input_event_images) protected
Definition at line 369 of file HiResImageDivider.cxx.
References cropEventImages(), isAbovePixelThreshold(), LARCV_INFO, and m_divisions.
Referenced by process().
{
       // we loop through all divisions and make a test crop. we then test this cropped region if it
       // satisfies the conditions to be deemed interesting enough to save
       divlist.clear();
       for ( int idiv=0; idiv<(int)m_divisions.size(); idiv++ ) {
     // div is a larcv::hires::DivisionDef
     larcv::hires::DivisionDef const& div = m_divisions.at(idiv);
     larcv::EventImage2D cropped;
     cropEventImages( input_event_images, div, cropped );
     if ( isAbovePixelThreshold( cropped ) )
       divlist.push_back( idiv );
       }
       LARCV_INFO() << "Generated " << divlist.size() << " / " << m_divisions.size() << " divisions..." << std::endl;
     }
generateSingleCosmicDivision()
void larcv::hires::HiResImageDivider::generateSingleCosmicDivision (std::vector< int > & divlist, const EventImage2D & input_event_images, larcv::ROI & roi) protected
Definition at line 301 of file HiResImageDivider.cxx.
References cropEventImages(), findVertexDivision(), fMaxRedrawAttempts, isAbovePixelThreshold(), larcv::kROICosmic, LARCV_ERROR, m_divisions, larcv::ROI::Position(), and larcv::ROI::Type().
Referenced by process().
{
       // we randomly pick a division (by randomly drawing a position in the detector
       // we return a division which satisfies some minimum amount of interesting pixel threshold
       bool viewok = false;
       int ntries = 0;
       roi.Type(kROICosmic);
       int idiv = -1;
       while (!viewok && ntries<fMaxRedrawAttempts) {
     ntries++;
     // FIXME: need a way to get detector dimension somehow...
     const double zmin = 0;
     const double zmax = 1036.0;
     const double ymin = -116.;
     const double ymax = 116.;
     const double xmin = 0.;
     const double xmax = 255.;
     const double tmin = 3125.; // in ns
     const double tmax = tmin + 1600.;
     std::random_device rd;
     std::mt19937 gen(rd());
     std::uniform_real_distribution<> dis(0.,1.);
     roi.Position( dis(gen) * (xmax - xmin) + xmin,
               dis(gen) * (ymax - ymin) + ymin,
               dis(gen) * (zmax - zmin) + zmin,
               dis(gen) * (tmax - tmin) + tmin);
     idiv = findVertexDivision( roi );
     if ( idiv==-1 ) {
       viewok = false;
       continue;
     }
     larcv::hires::DivisionDef const& vertex_div = m_divisions.at( idiv );
     larcv::EventImage2D cosmic_test;
     cropEventImages( input_event_images, vertex_div, cosmic_test );
     if ( isAbovePixelThreshold( cosmic_test ) )  {
       viewok = true;
       break;
     }
       }
       if ( !viewok ) {
     LARCV_ERROR() << "could not find cosmic roi with enough interesting pixels.\n" << std::endl;
       }
       else {
     divlist.push_back(idiv);
       }
     }
generateSingleMCDivision()
void larcv::hires::HiResImageDivider::generateSingleMCDivision (std::vector< int > & divlist, EventROI & event_roi, larcv::ROI & roi) protected
Definition at line 351 of file HiResImageDivider.cxx.
References larcv::ROI::dump(), findVertexDivision(), fInputROIProducer, isInteresting(), LARCV_ERROR, LARCV_INFO, and larcv::EventROI::ROIArray().
Referenced by process().
{
       int idiv = -1;
       if(!event_roi.ROIArray().empty()){
     LARCV_INFO() << "ROI by producer " << fInputROIProducer << " found. Searching for MC ROI..." << std::endl;
     for ( auto const& aroi : event_roi.ROIArray() )
       if ( isInteresting(aroi) ) { roi = aroi; break; }
     idiv = findVertexDivision( roi );
       }
       if ( idiv==-1 ) {
     LARCV_ERROR() << "No divisions were found that contained an event vertex.\n" << roi.dump() << std::endl;
       }
       else {
     divlist.push_back(idiv);
       }
     }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::hires::HiResImageDivider::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 77 of file HiResImageDivider.cxx.
References CalculateDivisions(), fProcessedEvent, fProcessedROI, fROISkipped, fROISkippedEvent, fUseDivFile, and LoadDivisionsFromFile().
Referenced by ~HiResImageDivider().
     {
       // Here we load the division definitions
       // We can use a pre-calculated divisions from file, or recalculate them using the DividerAlgo.
       if ( fUseDivFile )
     LoadDivisionsFromFile();
       else
     CalculateDivisions();
       fProcessedEvent=0;
       fROISkippedEvent=0;
       fProcessedROI=0;
       fROISkipped=0;
     }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
isAbovePixelThreshold()
bool larcv::hires::HiResImageDivider::isAbovePixelThreshold (const larcv::EventImage2D & imgs) protected
Definition at line 393 of file HiResImageDivider.cxx.
References fInterestingPixelThresh_v, fNumPixelRedrawThresh_v, fRedrawOnNEmptyPlanes, larcv::EventImage2D::Image2DArray(), and LARCV_INFO.
Referenced by generateFitleredWholeImageDivision(), generateSingleCosmicDivision(), and process().
{
       // warning, vectors assume plane ids are sequential and have no gaps
       std::vector<int> npixels(fInterestingPixelThresh_v.size(),0);
       for ( auto const& img: imgs.Image2DArray() ) {
     auto const plane = img.meta().plane();
     auto const& adc_v = img.as_vector();
     for ( auto const& adc : adc_v ) {
       if ( adc>fInterestingPixelThresh_v.at(plane) ) {
         npixels.at(plane)++;
       }
     }
       }
       int nempty = 0;
       for ( size_t i=0;i<npixels.size(); i++ ) {
     LARCV_INFO() << "Plane " << i << " has "
              << npixels[i] << " pixels above "
              << fInterestingPixelThresh_v[i] << " [ADC] ... Threshold = "
              << fNumPixelRedrawThresh_v[i] << std::endl;
     if ( fNumPixelRedrawThresh_v.at(i)>0 && npixels.at(i)<fNumPixelRedrawThresh_v.at(i) )
       nempty++;
       }
       LARCV_INFO() << "... " << nempty << " planes below threshold: returning "
            << ( nempty >=fRedrawOnNEmptyPlanes ? "false" : "true" ) << std::endl;
       if ( nempty>=fRedrawOnNEmptyPlanes )
     return false;
       return true;
     }
isInteresting()
bool larcv::hires::HiResImageDivider::isInteresting (const larcv::ROI & roi) protected
Definition at line 386 of file HiResImageDivider.cxx.
References larcv::kINVALID_USHORT, and larcv::ROI::MCSTIndex().
Referenced by generateSingleMCDivision(), and process().
{
       // Supposed to return the "primary"
       //return (roi.Type() == kROIBNB || roi.Type() == kROICosmic);
       // Consider if this came from MCTruth: MCSTIndex should be kINVALID_USHORT
       return (roi.MCSTIndex() == kINVALID_USHORT);
     }
LoadDivisionsFromFile()
void larcv::hires::HiResImageDivider::LoadDivisionsFromFile () protected
Definition at line 507 of file HiResImageDivider.cxx.
References fDivisionFile, fMaxWireImageWidth, fMaxWireInRegion, fNPlanes, fTickPreCompression, fTickStart, fWirePreCompression, larcv::hires::DivisionDef::ID(), LARCV_DEBUG, LARCV_INFO, and m_divisions.
Referenced by initialize().
{
       // The image divisions are calculated before hand in the fixed grid model
       // we load the prefined region image definitions here
       LARCV_INFO() << "Loading Divisions from File." << std::endl;
       std::set<larcv::hires::DivisionID> unique_div_s;
       TFile* f = new TFile( Form("%s/app/HiResDivider/dat/%s", getenv("LARCV_BASEDIR"),fDivisionFile.c_str()), "open" );
       TTree* t = (TTree*)f->Get("imagedivider/regionInfo");
       int **planebounds = new int*[fNPlanes];
       int planenwires[fNPlanes];
       for (int p=0; p<fNPlanes; p++) {
     planebounds[p] = new int[2];
     char bname1[100];
     sprintf( bname1, "plane%d_wirebounds", (int)p );
     t->SetBranchAddress( bname1, planebounds[p] );
     char bname2[100];
     sprintf( bname2, "plane%d_nwires", (int)p );
     t->SetBranchAddress( bname2, &(planenwires[p]) );
     //std::cout << "setup plane=" << p << " branches" << std::endl;
       }
       float zbounds[2];
       float xbounds[2];
       float ybounds[2];
       int tickbounds[2];
       t->SetBranchAddress( "zbounds", zbounds );
       t->SetBranchAddress( "ybounds", ybounds );
       t->SetBranchAddress( "xbounds", xbounds );
       t->SetBranchAddress( "tickbounds", tickbounds );
       fMaxWireInRegion = 0;
       size_t entry = 0;
       size_t bytes = t->GetEntry(entry);
       while ( bytes>0 ) {
     for (size_t p=0; p<3; p++) {
       if ( fMaxWireInRegion<planenwires[p] )
         fMaxWireInRegion = planenwires[p];
     }
     int plane0[2], plane1[2], plane2[2];
     for (size_t i=0; i<2; i++) {
       plane0[i] = (int)planebounds[0][i];
       plane1[i] = (int)planebounds[1][i];
       plane2[i] = (int)planebounds[2][i];
       tickbounds[i] *= fTickPreCompression;
       tickbounds[i] += fTickStart;
     }
     plane0[1] += fWirePreCompression;
     plane1[1] += fWirePreCompression;
     plane2[1] += fWirePreCompression;
     tickbounds[1] += fTickPreCompression;
     LARCV_DEBUG() << "division entry " << entry << ": "
               << " p0: [" << plane0[0] << "," << plane0[1] << "]"
               << " p1: [" << plane1[0] << "," << plane1[1] << "]"
               << " p2: [" << plane2[0] << "," << plane2[1] << "]"
               << " t: ["  << tickbounds[0] << "," << tickbounds[1] << "]"
               << std::endl;
     DivisionDef div( plane0, plane1, plane2, tickbounds, xbounds, ybounds, zbounds );
     auto const& div_id = div.ID();
     if(unique_div_s.find(div_id) == unique_div_s.end()) {
       unique_div_s.insert(div.ID());
       m_divisions.emplace_back(div);
     }
     entry++;
     bytes = t->GetEntry(entry);
     //std::cout << "Division tree entry:" << entry << " (" << bytes << ")" << std::endl;
       }
       if ( fMaxWireInRegion>fMaxWireImageWidth )
     fMaxWireImageWidth = fMaxWireInRegion;
       LARCV_INFO() << "Filled " << m_divisions.size() << " unique divisions..." << std::endl;
       LARCV_INFO() << "MaxWireImageWidth: " << fMaxWireImageWidth << std::endl;
       for (int p=0; p<fNPlanes; p++) {
     delete [] planebounds[p];
       }
       delete [] planebounds;
       f->Close();
     }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::hires::HiResImageDivider::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 92 of file HiResImageDivider.cxx.
References larcv::EventImage2D::at(), larcv::ROI::BB(), larcv::EventImage2D::clear(), larcv::ImageMeta::cols(), cropEventImages(), larcv::ROI::dump(), larcv::EventImage2D::Emplace(), larcv::ProcessBase::event_creator(), larcv::IOManager< T >::event_id(), fCropPMTWeighted, fCropSegmentation, fDivideWholeImage, fInputImageProducer, fInputPMTWeightedProducer, fInputROIProducer, fInputSegmentationProducer, fOutputImageProducer, fOutputPMTWeightedProducer, fOutputROIProducer, fOutputSegmentationProducer, fProcessedEvent, fProcessedROI, fROISkipped, fROISkippedEvent, generateFitleredWholeImageDivision(), generateSingleCosmicDivision(), generateSingleMCDivision(), larcv::IOManager< T >::get_data(), larcv::ImageMeta::height(), larcv::EventImage2D::Image2DArray(), isAbovePixelThreshold(), isInteresting(), larcv::kINVALID_PRODUCER, larcv::kProductImage2D, larcv::kProductROI, larcv::kROICosmic, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, LARCV_NORMAL, m_divisions, larcv::ImageMeta::max_y(), larcv::Image2D::meta(), larcv::ImageMeta::min_x(), overlap(), larcv::ImageMeta::plane(), larcv::IOManager< T >::producer_id(), larcv::EventROI::ROIArray(), larcv::ImageMeta::rows(), larcv::EventBase::run(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), larcv::ROI::SetBB(), larcv::ROI::Type(), and larcv::ImageMeta::width().
Referenced by ~HiResImageDivider().
     {
       ++fProcessedEvent;
       // This processor does the following:
       // 1) read in hi-res images (from producer specified in config)
       // 2) (how to choose which one we clip?)
       larcv::EventImage2D input_event_images = *((larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fInputImageProducer)));
       larcv::EventImage2D* input_seg_images;
       larcv::EventROI event_roi;
       // If it exists, we get the ROI which will guide us on how to use the image
       // This does not exist for cosmics, in which case we create
       ProducerID_t roi_producer_id = mgr.producer_id(::larcv::kProductROI,fInputROIProducer);
       larcv::ROI roi;
       if(roi_producer_id != kINVALID_PRODUCER) {
     LARCV_INFO() << "ROI by producer " << fInputROIProducer << " found. Searching for MC ROI..." << std::endl;
     event_roi = *((larcv::EventROI*)(mgr.get_data(roi_producer_id)));
     if(!fInputSegmentationProducer.empty())
       input_seg_images = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fInputSegmentationProducer));
       }else{
     LARCV_INFO() << "ROI by producer " << fInputROIProducer << " not found. Constructing Cosmic ROI..." << std::endl;
     // Input ROI did not exist. Assume this means cosmics and create one
     roi.Type(kROICosmic);
       }
       // First we decide what divisions need to be cropped
       std::vector<int> divlist;
       if ( fDivideWholeImage ) {
     generateFitleredWholeImageDivision( divlist, input_event_images );
       }
       else {
     if ( roi.Type()==kROICosmic )
       generateSingleCosmicDivision( divlist, input_event_images, roi );
     else
       generateSingleMCDivision( divlist, event_roi, roi );
     if(!isInteresting(roi)) {
       LARCV_CRITICAL() << "Did not find any interesting ROI and/or failed to construct Cosmic ROI..." << std::endl;
       if(roi_producer_id != kINVALID_PRODUCER) {
         LARCV_ERROR() << "Input ROI does exist. Looping over ROI types and printing out..." << std::endl;
         for(auto const& roi : event_roi.ROIArray()) LARCV_ERROR() << roi.dump();
         LARCV_ERROR() << "Dump finished..." << std::endl;
       }
       // Return false not to store this event in case of filter IO mode
       return false;
     }
       }
       // We call IOManger::store_entry which calls clear_data of all products.
       // To keep necessary input event information, let's copy-construct them
       auto const& event_id = mgr.event_id();
       const size_t input_run    = event_id.run();
       const size_t input_subrun = event_id.subrun();
       const size_t input_event  = event_id.event();
       bool store_entry = false;
       LARCV_INFO() << "Reading-in (run,subrun,event) = (" << input_run << "," << input_subrun << "," << input_event << ")" << std::endl;
       // now we loop through and make divisions
       for ( auto const& idiv : divlist ) {
     if ( idiv==-1 )
       continue;
     larcv::hires::DivisionDef const& vertex_div = m_divisions.at( idiv );
     //std::cout << "Vertex in ROI: " << roi.X() << ", " << roi.Y() << ", " << roi.Z() << std::endl;
     // now we crop out certain pieces
     // The input images
     auto output_event_images = (larcv::EventImage2D*)(mgr.get_data( kProductImage2D,fOutputImageProducer) );
     output_event_images->clear();
     LARCV_DEBUG() << "Crop " << fInputImageProducer << " Images." << std::endl;
     cropEventImages( input_event_images, vertex_div, *output_event_images );
     larcv::EventImage2D* output_seg_images = nullptr;
     larcv::EventImage2D* output_pmtweighted_images = nullptr;
     //
     // Image is cropped based on DivisionDef which is found from ROI's vertex
     // However ROI's vertex do not necessarily overlap with the same ROI's 2D bounding box
     // in case of a neutrino interaction because the former is a neutrino interaction vertex
     // while the latter is based on particles' trajectories that deposited energy. An example
     // is a neutron produced at vertex and hit proton far away from the vertex. So, here, we
     // ask, if it is non-cosmic type ROI, created image's meta overlaps with ROI's image meta.
     //
     if(roi.Type() != kROICosmic) {
       // if not cosmic, we check if neutrino image has enough interesting pixels
       if ( !isAbovePixelThreshold( *output_event_images ) ) {
         ++fROISkippedEvent;
         LARCV_NORMAL() << "Found an event w/ neutrino vertex without enough interesting pixels (" << fROISkippedEvent << " events skipped so far)" << std::endl;
         for(auto const& img : output_event_images->Image2DArray()) LARCV_INFO() << img.meta().dump();
         for(auto const& aroi : event_roi.ROIArray()) LARCV_INFO() << aroi.dump();
         output_event_images->clear();
         continue;
       }
       try{
         for(auto const& img : output_event_images->Image2DArray())
           roi.BB(img.meta().plane()).overlap(img.meta());
       }catch(const larbys& err) {
         ++fROISkippedEvent;
         LARCV_NORMAL() << "Found an event w/ neutrino vertex not within ROI bounding box (" << fROISkippedEvent << " events so far)" << std::endl;
         for(auto const& img : output_event_images->Image2DArray()) LARCV_INFO() << img.meta().dump();
         for(auto const& aroi : event_roi.ROIArray()) LARCV_INFO() << aroi.dump();
         output_event_images->clear();
         continue;
       }
     }
     // Output Segmentation
     if ( fCropSegmentation && input_seg_images->Image2DArray().size() ) {
       // the semantic segmentation is only filled in the neighboor hood of the interaction
       // we overlay it into a full image (and then crop out the division)
       larcv::EventImage2D full_seg_images;
       for ( unsigned int p=0; p<3; p++ ) {
         larcv::Image2D const& img = input_event_images.at( p );
         larcv::ImageMeta seg_image_meta( img.meta().width(), img.meta().height(),
                          img.meta().rows(), img.meta().cols(),
                          img.meta().min_x(), img.meta().max_y(),
                          img.meta().plane() );
         larcv::Image2D seg_image( seg_image_meta );
         seg_image.paint( 0.0 );
         seg_image.overlay( input_seg_images->at(p) );
         full_seg_images.Emplace( std::move(seg_image) );
       }
       LARCV_DEBUG() << "Crop " << fInputSegmentationProducer << " Images." << std::endl;
       output_seg_images = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fOutputSegmentationProducer));
       output_seg_images->clear();
       cropEventImages( full_seg_images, vertex_div, *output_seg_images );
     }// if crop seg
     // Output PMT weighted
     if ( fCropPMTWeighted )  {
       LARCV_DEBUG() << "Load " << fInputPMTWeightedProducer << " Images." << std::endl;
       larcv::EventImage2D input_pmtweighted_images = *((larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fInputPMTWeightedProducer)));
       LARCV_DEBUG() << "Allocate " << fOutputPMTWeightedProducer << " Images." << std::endl;
       output_pmtweighted_images = (larcv::EventImage2D*)(mgr.get_data(kProductImage2D,fOutputPMTWeightedProducer));
       output_pmtweighted_images->clear();
       LARCV_DEBUG() << "Crop " << fInputPMTWeightedProducer << " Images." << std::endl;
       cropEventImages( input_pmtweighted_images, vertex_div, *output_pmtweighted_images );
     }
     // Finally let's store ROI w/ updated ImageMeta arrays
     //
     // 0) Retrieve output image array and input ROI array (for the latter "if exists")
     // 1) Loop over ROI array (or single ROI for "cosmic" = input does not exist), ask overlap in 2D plane ImageMeta with each image
     auto output_rois = (larcv::EventROI*)(mgr.get_data(kProductROI,fOutputROIProducer));
     output_rois->clear();
     if(roi_producer_id != kINVALID_PRODUCER) {
       // Loop over and store in output
       for(auto const& aroi : event_roi.ROIArray()) {
         ++fProcessedROI;
         std::vector<larcv::ImageMeta> out_meta_v;
         try {
           //LARCV_INFO() << "Creating particle ROI for: " << roi.dump() << std::endl;
           for(auto const& bb : aroi.BB()) {
         auto const& img_meta = output_event_images->at(bb.plane()).meta();
         out_meta_v.push_back(img_meta.overlap(bb));
           }
         }catch(const larbys& err){
           LARCV_INFO() << "Found an ROI bounding box that has no overlap with neutrino vertex box. Skipping..." << std::endl;
           LARCV_INFO() << aroi.dump() << std::endl;
           out_meta_v.clear();
           ++fROISkipped;
         }
         ::larcv::ROI out_roi(aroi);
         out_roi.SetBB(out_meta_v);
         output_rois->Emplace(std::move(out_roi));
       }
     }else{
       std::vector<larcv::ImageMeta> out_meta_v;
       for(auto const& img : output_event_images->Image2DArray()) out_meta_v.push_back(img.meta());
       roi.SetBB(out_meta_v);
       output_rois->Emplace(std::move(roi));
     }
     if(output_rois->ROIArray().empty()) {
       output_event_images->clear();
       if(output_pmtweighted_images) output_pmtweighted_images->clear();
       if(output_seg_images) output_seg_images->clear();
     }else{
       store_entry = true;
       if(this->event_creator() && store_entry) {
         mgr.set_id(input_run,input_subrun,input_event);
         LARCV_INFO() << "Storing entry for a division..." << std::endl;
         mgr.save_entry();
       }
     }
       }//end of divlist loop
       LARCV_INFO() << "Done storing divisions" << std::endl;
       return store_entry;
     }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fApplySCE
bool larcv::hires::HiResImageDivider::fApplySCE protected
Definition at line 56 of file HiResImageDivider.h.
Referenced by configure(), and findVertexDivision().
fCropPMTWeighted
bool larcv::hires::HiResImageDivider::fCropPMTWeighted protected
Definition at line 72 of file HiResImageDivider.h.
Referenced by configure(), and process().
fCropSegmentation
bool larcv::hires::HiResImageDivider::fCropSegmentation protected
Definition at line 71 of file HiResImageDivider.h.
Referenced by configure(), and process().
fDivideWholeImage
bool larcv::hires::HiResImageDivider::fDivideWholeImage protected
Definition at line 88 of file HiResImageDivider.h.
Referenced by configure(), and process().
fDivisionFile
std::string larcv::hires::HiResImageDivider::fDivisionFile protected
Definition at line 58 of file HiResImageDivider.h.
Referenced by configure(), and LoadDivisionsFromFile().
fInputImageProducer
std::string larcv::hires::HiResImageDivider::fInputImageProducer protected
Definition at line 82 of file HiResImageDivider.h.
Referenced by configure(), and process().
fInputPMTProducer
std::string larcv::hires::HiResImageDivider::fInputPMTProducer protected
Definition at line 79 of file HiResImageDivider.h.
Referenced by configure().
fInputPMTWeightedProducer
std::string larcv::hires::HiResImageDivider::fInputPMTWeightedProducer protected
Definition at line 84 of file HiResImageDivider.h.
Referenced by configure(), and process().
fInputROIProducer
std::string larcv::hires::HiResImageDivider::fInputROIProducer protected
Definition at line 80 of file HiResImageDivider.h.
Referenced by configure(), generateSingleMCDivision(), and process().
fInputSegmentationProducer
std::string larcv::hires::HiResImageDivider::fInputSegmentationProducer protected
Definition at line 83 of file HiResImageDivider.h.
Referenced by configure(), and process().
fInterestingPixelThresh_v
std::vector< float > larcv::hires::HiResImageDivider::fInterestingPixelThresh_v protected
Definition at line 76 of file HiResImageDivider.h.
Referenced by configure(), and isAbovePixelThreshold().
fMaxRedrawAttempts
int larcv::hires::HiResImageDivider::fMaxRedrawAttempts protected
Definition at line 73 of file HiResImageDivider.h.
Referenced by configure(), and generateSingleCosmicDivision().
fMaxWireImageWidth
int larcv::hires::HiResImageDivider::fMaxWireImageWidth protected
Definition at line 68 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), configure(), cropEventImages(), and LoadDivisionsFromFile().
fMaxWireInRegion
int larcv::hires::HiResImageDivider::fMaxWireInRegion protected
Definition at line 69 of file HiResImageDivider.h.
Referenced by LoadDivisionsFromFile().
fNPlanes
int larcv::hires::HiResImageDivider::fNPlanes protected
Definition at line 64 of file HiResImageDivider.h.
Referenced by configure(), and LoadDivisionsFromFile().
fNumNonVertexDivisionsPerEvent
int larcv::hires::HiResImageDivider::fNumNonVertexDivisionsPerEvent protected
Definition at line 70 of file HiResImageDivider.h.
Referenced by configure().
fNumPixelRedrawThresh_v
std::vector< int > larcv::hires::HiResImageDivider::fNumPixelRedrawThresh_v protected
Definition at line 75 of file HiResImageDivider.h.
Referenced by configure(), and isAbovePixelThreshold().
fNumTdivisions
int larcv::hires::HiResImageDivider::fNumTdivisions protected
Definition at line 61 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), and configure().
fNumYdivisions
int larcv::hires::HiResImageDivider::fNumYdivisions protected
Definition at line 60 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), and configure().
fNumZdivisions
int larcv::hires::HiResImageDivider::fNumZdivisions protected
Definition at line 59 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), and configure().
fOutputImageProducer
std::string larcv::hires::HiResImageDivider::fOutputImageProducer protected
Definition at line 85 of file HiResImageDivider.h.
Referenced by configure(), and process().
fOutputPMTWeightedProducer
std::string larcv::hires::HiResImageDivider::fOutputPMTWeightedProducer protected
Definition at line 87 of file HiResImageDivider.h.
Referenced by configure(), and process().
fOutputROIProducer
std::string larcv::hires::HiResImageDivider::fOutputROIProducer protected
Definition at line 81 of file HiResImageDivider.h.
Referenced by configure(), and process().
fOutputSegmentationProducer
std::string larcv::hires::HiResImageDivider::fOutputSegmentationProducer protected
Definition at line 86 of file HiResImageDivider.h.
Referenced by configure(), and process().
fOverlapDivisions
bool larcv::hires::HiResImageDivider::fOverlapDivisions protected
Definition at line 62 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), and configure().
fProcessedEvent
size_t larcv::hires::HiResImageDivider::fProcessedEvent protected
Definition at line 90 of file HiResImageDivider.h.
Referenced by finalize(), initialize(), and process().
fProcessedROI
size_t larcv::hires::HiResImageDivider::fProcessedROI protected
Definition at line 92 of file HiResImageDivider.h.
Referenced by finalize(), initialize(), and process().
fRedrawOnNEmptyPlanes
int larcv::hires::HiResImageDivider::fRedrawOnNEmptyPlanes protected
Definition at line 74 of file HiResImageDivider.h.
Referenced by configure(), and isAbovePixelThreshold().
fROISkipped
size_t larcv::hires::HiResImageDivider::fROISkipped protected
Definition at line 93 of file HiResImageDivider.h.
Referenced by finalize(), initialize(), and process().
fROISkippedEvent
size_t larcv::hires::HiResImageDivider::fROISkippedEvent protected
Definition at line 91 of file HiResImageDivider.h.
Referenced by finalize(), initialize(), and process().
fTickPreCompression
int larcv::hires::HiResImageDivider::fTickPreCompression protected
Definition at line 66 of file HiResImageDivider.h.
Referenced by configure(), and LoadDivisionsFromFile().
fTickStart
int larcv::hires::HiResImageDivider::fTickStart protected
Definition at line 65 of file HiResImageDivider.h.
Referenced by configure(), and LoadDivisionsFromFile().
fUseDivFile
bool larcv::hires::HiResImageDivider::fUseDivFile protected
Definition at line 57 of file HiResImageDivider.h.
Referenced by configure(), and initialize().
fWirePreCompression
int larcv::hires::HiResImageDivider::fWirePreCompression protected
Definition at line 67 of file HiResImageDivider.h.
Referenced by configure(), and LoadDivisionsFromFile().
m_divisions
std::vector< larcv::hires::DivisionDef > larcv::hires::HiResImageDivider::m_divisions protected
Definition at line 77 of file HiResImageDivider.h.
Referenced by CalculateDivisions(), findVertexDivision(), generateFitleredWholeImageDivision(), generateSingleCosmicDivision(), LoadDivisionsFromFile(), and process().
The documentation for this class was generated from the following files:
HiResImageDivider.h
HiResImageDivider.cxx