LArCV: larcv::BadRegionAnaProcessFactory Class Reference
larcv::BadRegionAnaProcessFactory Class Reference
#include <BadRegionAna.h>
Public Member Functions
BadRegionAnaProcessFactory ()
ctor
~BadRegionAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 78 of file BadRegionAna.h.
Constructor & Destructor Documentation
BadRegionAnaProcessFactory()
larcv::BadRegionAnaProcessFactory::BadRegionAnaProcessFactory () inline
ctor
Definition at line 81 of file BadRegionAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("BadRegionAna",this); }
~BadRegionAnaProcessFactory()
larcv::BadRegionAnaProcessFactory::~BadRegionAnaProcessFactory () inline
dtor
Definition at line 83 of file BadRegionAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::BadRegionAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 85 of file BadRegionAna.h.
References larcv::BadRegionAna::BadRegionAna().
 { return new BadRegionAna(instance_name); }
The documentation for this class was generated from the following file:
BadRegionAna.h