LArCV: larcv::EventImage2DFactory Class Reference
larcv::EventImage2DFactory Class Reference
#include <EventImage2D.h>
Public Member Functions
EventImage2DFactory ()
ctor
~EventImage2DFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 68 of file EventImage2D.h.
Constructor & Destructor Documentation
EventImage2DFactory()
larcv::EventImage2DFactory::EventImage2DFactory () inline
ctor
Definition at line 71 of file EventImage2D.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductImage2D.
 { DataProductFactory::get().add_factory(kProductImage2D,this); }
~EventImage2DFactory()
larcv::EventImage2DFactory::~EventImage2DFactory () inline
dtor
Definition at line 73 of file EventImage2D.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventImage2DFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 75 of file EventImage2D.h.
References larcv::EventImage2D::EventImage2D().
 { return new EventImage2D; }
The documentation for this class was generated from the following file:
EventImage2D.h