LArCV: larcv::CSVData Class Reference
larcv::CSVData Class Reference
#include <CSVReader.h>
Public Types
enum ValueType_t {
ValueType_t::kSTRING, ValueType_t::kBOOL, ValueType_t::kINT, ValueType_t::kFLOAT,
ValueType_t::kDOUBLE
}
internal organization purpose
Public Member Functions
CSVData ()
default ctor
~CSVData ()
default dtor
CSVData (const std::string fname, const std::string format)
alternative ctor
CSVData (const std::string &fname, const std::vector< larcv::CSVData::ValueType_t > &format)
alternative ctor
void clear ()
Clear.
void read_file (const std::string, const std::string)
Read in CSV file.
void read_file (const std::string, const std::vector< larcv::CSVData::ValueType_t > &)
Read in CSV file.
template<class T >
const std::map< std::string, std::vector< T > > & get_container () const
A value-type-wise container getter.
template<class T >
const std::vector< T > & get (const std::string key) const
A column of a specific value type getter.
const std::vector< std::string > & get_string (const std::string key) const
For python.
const std::vector< int > & get_int (const std::string key) const
For python.
const std::vector< bool > & get_bool (const std::string key) const
For python.
const std::vector< float > & get_float (const std::string key) const
For python.
const std::vector< double > & get_double (const std::string key) const
For python.
template<>
const std::map< std::string, std::vector< bool > > & get_container () const
template<>
const std::map< std::string, std::vector< int > > & get_container () const
template<>
const std::map< std::string, std::vector< float > > & get_container () const
template<>
const std::map< std::string, std::vector< double > > & get_container () const
Private Member Functions
void read_line (const std::string &line_data, const std::vector< larcv::CSVData::ValueType_t > &value_types, std::vector< void *> &column_ptrs)
Private Attributes
std::map< std::string, std::vector< std::string > > _data_str
std::map< std::string, std::vector< bool > > _data_bool
std::map< std::string, std::vector< int > > _data_int
std::map< std::string, std::vector< float > > _data_float
std::map< std::string, std::vector< double > > _data_double
Detailed Description
Definition at line 13 of file CSVReader.h.
Member Enumeration Documentation
ValueType_t
enum larcv::CSVData::ValueType_t strong
internal organization purpose
Enumerator
kSTRING
kBOOL
kINT
kFLOAT
kDOUBLE
Definition at line 16 of file CSVReader.h.
 { kSTRING, kBOOL, kINT, kFLOAT, kDOUBLE };
Constructor & Destructor Documentation
CSVData() [1/3]
larcv::CSVData::CSVData () inline
default ctor
Definition at line 19 of file CSVReader.h.
References clear().
Referenced by larcv::read_csv().
 { clear(); }
~CSVData()
larcv::CSVData::~CSVData () inline
default dtor
Definition at line 21 of file CSVReader.h.
 {}
CSVData() [2/3]
larcv::CSVData::CSVData (const std::string fname, const std::string format) inline
alternative ctor
Definition at line 23 of file CSVReader.h.
References read_file().
     { read_file(fname,format); }
CSVData() [3/3]
larcv::CSVData::CSVData (const std::string & fname, const std::vector< larcv::CSVData::ValueType_t > & format) inline
alternative ctor
Definition at line 26 of file CSVReader.h.
References clear(), get_container(), and read_file().
     { read_file(fname,format); }
Member Function Documentation
clear()
void larcv::CSVData::clear ()
Clear.
Definition at line 7 of file CSVReader.cxx.
References _data_bool, _data_double, _data_float, _data_int, and _data_str.
Referenced by CSVData(), and read_file().
   { _data_str.clear(); _data_bool.clear(); _data_int.clear(); _data_float.clear(); _data_double.clear(); }
get()
template<class T > const std::vector< T > & larcv::CSVData::get (const std::string key) const inline
A column of a specific value type getter.
Definition at line 88 of file CSVReader.h.
References LARCV_SCRITICAL.
   {
     auto const& data_m = get_container<T>();
     auto iter = data_m.find(key);
     if(iter == data_m.end()) {
       LARCV_SCRITICAL() << "Key " << key << " does not exist!" << std::endl;
       throw larbys();
     }
     return (*iter).second;
   }
get_bool()
const std::vector<bool>& larcv::CSVData::get_bool (const std::string key) const inline
For python.
Definition at line 51 of file CSVReader.h.
     { return this->get<bool>(key); }
get_container() [1/5]
template<class T > const std::map<std::string,std::vector<T> >& larcv::CSVData::get_container () const
A value-type-wise container getter.
Referenced by CSVData().
get_container() [2/5]
template<> const std::map<std::string,std::vector<bool> >& larcv::CSVData::get_container () const inline
Definition at line 76 of file CSVReader.h.
References _data_bool.
 { return _data_bool;  }
get_container() [3/5]
template<> const std::map<std::string,std::vector<int> >& larcv::CSVData::get_container () const inline
Definition at line 79 of file CSVReader.h.
References _data_int.
 { return _data_int;   }
get_container() [4/5]
template<> const std::map<std::string,std::vector<float> >& larcv::CSVData::get_container () const inline
Definition at line 82 of file CSVReader.h.
References _data_float.
 { return _data_float; }
get_container() [5/5]
template<> const std::map<std::string,std::vector<double> >& larcv::CSVData::get_container () const inline
Definition at line 85 of file CSVReader.h.
References _data_double.
 { return _data_double; }
get_double()
const std::vector<double>& larcv::CSVData::get_double (const std::string key) const inline
For python.
Definition at line 57 of file CSVReader.h.
References read_line().
     { return this->get<double>(key); }
get_float()
const std::vector<float>& larcv::CSVData::get_float (const std::string key) const inline
For python.
Definition at line 54 of file CSVReader.h.
     { return this->get<float>(key); }
get_int()
const std::vector<int>& larcv::CSVData::get_int (const std::string key) const inline
For python.
Definition at line 48 of file CSVReader.h.
     { return this->get<int>(key); }
get_string()
const std::vector<std::string>& larcv::CSVData::get_string (const std::string key) const inline
For python.
Definition at line 45 of file CSVReader.h.
     { return this->get<std::string>(key); }
read_file() [1/2]
void larcv::CSVData::read_file (const std::string fname, const std::string format)
Read in CSV file.
Definition at line 10 of file CSVReader.cxx.
References kBOOL, kDOUBLE, kFLOAT, kINT, kSTRING, and LARCV_SCRITICAL.
Referenced by CSVData().
   {
     std::vector<larcv::CSVData::ValueType_t> value_types;
     for(size_t idx=0; idx<format.length(); ++idx) {
       auto v = format.substr(idx,1);
       CSVData::ValueType_t vt(CSVData::ValueType_t::kSTRING);
       if      (v == "S") vt = CSVData::ValueType_t::kSTRING;
       else if (v == "I") vt = CSVData::ValueType_t::kINT;
       else if (v == "B") vt = CSVData::ValueType_t::kBOOL;
       else if (v == "F") vt = CSVData::ValueType_t::kFLOAT;
       else if (v == "D") vt = CSVData::ValueType_t::kDOUBLE;
       else {
     LARCV_SCRITICAL() << "CSV value type \"" << v << "\" not supported!" << std::endl;
     throw larbys();
       }
       value_types.push_back(vt);
     }
     read_file(fname,value_types);
   }
read_file() [2/2]
void larcv::CSVData::read_file (const std::string fname, const std::vector< larcv::CSVData::ValueType_t > & value_types)
Read in CSV file.
Definition at line 30 of file CSVReader.cxx.
References _data_bool, _data_double, _data_float, _data_int, _data_str, clear(), kBOOL, kDOUBLE, kFLOAT, kINT, kSTRING, LARCV_SCRITICAL, and read_line().
   {
     clear();
     std::ifstream fstrm(fname.c_str());
     std::string   line_data;
     std::getline(fstrm, line_data);
     size_t last_pos=0;
     size_t next_pos=0;
     std::vector<std::string> column_names;
     std::vector<void*> column_ptrs;
     for(size_t idx=0; idx<value_types.size(); ++idx) {
       auto const& value_type = value_types[idx];
       void* column_ptr;
       if(idx<1)
     next_pos=line_data.find(",");
       else
     next_pos=line_data.find(",",last_pos);
       auto column_name = line_data.substr(last_pos, next_pos - last_pos);
       switch(value_type) {
       case CSVData::ValueType_t::kSTRING:
     if(_data_str.find(column_name) != _data_str.end()) {
       LARCV_SCRITICAL() << "CSV column type string w/ name " << column_name << " is duplicate..." << std::endl;
       throw larbys();
     }else
       column_ptr = (void*)(&(_data_str[column_name]));
     break;
       case CSVData::ValueType_t::kINT:
     if(_data_int.find(column_name) != _data_int.end()) {
       LARCV_SCRITICAL() << "CSV column type int w/ name " << column_name << " is duplicate..." << std::endl;
       throw larbys();
     }else
       column_ptr = (void*)(&(_data_int[column_name]));
     break;
       case CSVData::ValueType_t::kBOOL:
     if(_data_bool.find(column_name) != _data_bool.end()) {
       LARCV_SCRITICAL() << "CSV column type bool w/ name " << column_name << " is duplicate..." << std::endl;
       throw larbys();
     }else
       column_ptr = (void*)(&(_data_bool[column_name]));
     break;
       case CSVData::ValueType_t::kFLOAT:
     if(_data_float.find(column_name) != _data_float.end()) {
       LARCV_SCRITICAL() << "CSV column type float w/ name " << column_name << " is duplicate..." << std::endl;
       throw larbys();
     }else
       column_ptr = (void*)(&(_data_float[column_name]));
     break;
       case CSVData::ValueType_t::kDOUBLE:
     if(_data_double.find(column_name) != _data_double.end()) {
       LARCV_SCRITICAL() << "CSV column type double w/ name " << column_name << " is duplicate..." << std::endl;
       throw larbys();
     }else
       column_ptr = (void*)(&(_data_double[column_name]));
     break;
       }
       column_names.push_back(column_name);
       column_ptrs.push_back(column_ptr);
       last_pos = next_pos+1;
     }
     while(std::getline(fstrm, line_data)) {
       if(line_data.empty()) continue;
       this->read_line(line_data,value_types,column_ptrs);
     }
   }
read_line()
void larcv::CSVData::read_line (const std::string & line_data, const std::vector< larcv::CSVData::ValueType_t > & value_types, std::vector< void *> & column_ptrs) private
Definition at line 101 of file CSVReader.cxx.
References kBOOL, kDOUBLE, kFLOAT, kINT, kSTRING, and LARCV_SCRITICAL.
Referenced by get_double(), and read_file().
   {
     size_t last_pos=0;
     size_t next_pos=0;
     for(size_t idx=0; idx<value_types.size(); ++idx) {
       auto const& value_type = value_types[idx];
       auto& column_ptr = column_ptrs[idx];
       if(idx<1)
     next_pos=line_data.find(",");
       else
     next_pos=line_data.find(",",last_pos);
       auto value = line_data.substr(last_pos, next_pos - last_pos);
       switch(value_type) {
       case CSVData::ValueType_t::kSTRING:
     ((std::vector<std::string>*)column_ptr)->push_back(value);
     break;
       case CSVData::ValueType_t::kINT:
     ((std::vector<int>*)column_ptr)->push_back(std::atoi(value.c_str()));
     break;
       case CSVData::ValueType_t::kBOOL:
     if(value=="1" || value=="true") ((std::vector<bool>*)column_ptr)->push_back(true);
     else if(value=="0" || value=="false") ((std::vector<bool>*)column_ptr)->push_back(false);
     else {
       LARCV_SCRITICAL() << "Boolean value neither of [0,1,false,true] ..." << std::endl;
       throw larbys();
     }
     break;
       case CSVData::ValueType_t::kFLOAT:
     ((std::vector<float>*)column_ptr)->push_back(std::atof(value.c_str()));
     break;
       case CSVData::ValueType_t::kDOUBLE:
     ((std::vector<double>*)column_ptr)->push_back(std::atof(value.c_str()));
     break;
       }
       last_pos = next_pos+1;
     }
   }
Member Data Documentation
_data_bool
std::map< std::string, std::vector<bool> > larcv::CSVData::_data_bool private
Definition at line 66 of file CSVReader.h.
Referenced by clear(), get_container(), and read_file().
_data_double
std::map< std::string, std::vector<double> > larcv::CSVData::_data_double private
Definition at line 69 of file CSVReader.h.
Referenced by clear(), get_container(), and read_file().
_data_float
std::map< std::string, std::vector<float> > larcv::CSVData::_data_float private
Definition at line 68 of file CSVReader.h.
Referenced by clear(), get_container(), and read_file().
_data_int
std::map< std::string, std::vector<int> > larcv::CSVData::_data_int private
Definition at line 67 of file CSVReader.h.
Referenced by clear(), get_container(), and read_file().
_data_str
std::map< std::string, std::vector<std::string> > larcv::CSVData::_data_str private
Definition at line 65 of file CSVReader.h.
Referenced by clear(), larcv::CSVData::get_container< std::string >(), and read_file().
The documentation for this class was generated from the following files:
CSVReader.h
CSVReader.cxx