LArCV: larcv::larcv_base Class Reference
larcv::larcv_base Class Reference
Framework base class equipped with a logger class.
#include <larcv_base.h>
Public Member Functions
larcv_base (const std::string logger_name="larcv_base")
Default constructor.
larcv_base (const larcv_base &original)
Default copy constructor.
virtual ~larcv_base ()
Default destructor.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
larcv::logger * _logger
logger
Detailed Description
Framework base class equipped with a logger class.
Definition at line 27 of file larcv_base.h.
Constructor & Destructor Documentation
larcv_base() [1/2]
larcv::larcv_base::larcv_base (const std::string logger_name = "larcv_base") inline
Default constructor.
Definition at line 32 of file larcv_base.h.
References _logger, and larcv::logger::get().
       : _logger(nullptr)
     { _logger = &(::larcv::logger::get(logger_name)); }
larcv_base() [2/2]
larcv::larcv_base::larcv_base (const larcv_base & original) inline
Default copy constructor.
Definition at line 37 of file larcv_base.h.
 : _logger(original._logger) {}
~larcv_base()
virtual larcv::larcv_base::~larcv_base () inline virtual
Default destructor.
Definition at line 40 of file larcv_base.h.
 {};
Member Function Documentation
logger()
const larcv::logger& larcv::larcv_base::logger () const inline
Logger getter.
Definition at line 43 of file larcv_base.h.
References _logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline
Verbosity level.
Definition at line 47 of file larcv_base.h.
References _logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_logger
larcv::logger* larcv::larcv_base::_logger private
logger
Definition at line 56 of file larcv_base.h.
Referenced by larcv_base(), logger(), and set_verbosity().
The documentation for this class was generated from the following file:
larcv_base.h