LArCV: larcv::ParticleAnaProcessFactory Class Reference
larcv::ParticleAnaProcessFactory Class Reference
#include <ParticleAna.h>
Public Member Functions
ParticleAnaProcessFactory ()
ctor
~ParticleAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 180 of file ParticleAna.h.
Constructor & Destructor Documentation
ParticleAnaProcessFactory()
larcv::ParticleAnaProcessFactory::ParticleAnaProcessFactory () inline
ctor
Definition at line 183 of file ParticleAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("ParticleAna",this); }
~ParticleAnaProcessFactory()
larcv::ParticleAnaProcessFactory::~ParticleAnaProcessFactory () inline
dtor
Definition at line 185 of file ParticleAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::ParticleAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 187 of file ParticleAna.h.
References larcv::ParticleAna::ParticleAna().
 { return new ParticleAna(instance_name); }
The documentation for this class was generated from the following file:
ParticleAna.h