LArCV: larcv::EventChStatusFactory Class Reference
larcv::EventChStatusFactory Class Reference
#include <EventChStatus.h>
Public Member Functions
EventChStatusFactory ()
ctor
~EventChStatusFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 68 of file EventChStatus.h.
Constructor & Destructor Documentation
EventChStatusFactory()
larcv::EventChStatusFactory::EventChStatusFactory () inline
ctor
Definition at line 71 of file EventChStatus.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductChStatus.
 { DataProductFactory::get().add_factory(kProductChStatus,this); }
~EventChStatusFactory()
larcv::EventChStatusFactory::~EventChStatusFactory () inline
dtor
Definition at line 73 of file EventChStatus.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventChStatusFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 75 of file EventChStatus.h.
References larcv::EventChStatus::EventChStatus().
 { return new EventChStatus; }
The documentation for this class was generated from the following file:
EventChStatus.h