LArCV: larcv::CropROIProcessFactory Class Reference
larcv::CropROIProcessFactory Class Reference
#include <CropROI.h>
Public Member Functions
CropROIProcessFactory ()
ctor
~CropROIProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 57 of file CropROI.h.
Constructor & Destructor Documentation
CropROIProcessFactory()
larcv::CropROIProcessFactory::CropROIProcessFactory () inline
ctor
Definition at line 60 of file CropROI.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("CropROI",this); }
~CropROIProcessFactory()
larcv::CropROIProcessFactory::~CropROIProcessFactory () inline
dtor
Definition at line 62 of file CropROI.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::CropROIProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 64 of file CropROI.h.
References larcv::CropROI::CropROI().
 { return new CropROI(instance_name); }
The documentation for this class was generated from the following file:
CropROI.h