LArCV: larcv::EventVoxel3DFactory Class Reference
larcv::EventVoxel3DFactory Class Reference
#include <EventVoxel3D.h>
Public Member Functions
EventVoxel3DFactory ()
ctor
~EventVoxel3DFactory ()
dtor
EventBase * create ()
create method
Detailed Description
Definition at line 46 of file EventVoxel3D.h.
Constructor & Destructor Documentation
EventVoxel3DFactory()
larcv::EventVoxel3DFactory::EventVoxel3DFactory () inline
ctor
Definition at line 49 of file EventVoxel3D.h.
References larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::get(), and larcv::kProductVoxel3D.
 { DataProductFactory::get().add_factory(kProductVoxel3D,this); }
~EventVoxel3DFactory()
larcv::EventVoxel3DFactory::~EventVoxel3DFactory () inline
dtor
Definition at line 51 of file EventVoxel3D.h.
 {}
Member Function Documentation
create()
EventBase* larcv::EventVoxel3DFactory::create () inline virtual
create method
Implements larcv::DataProductFactoryBase.
Definition at line 53 of file EventVoxel3D.h.
References larcv::EventVoxel3D::EventVoxel3D().
 { return new EventVoxel3D; }
The documentation for this class was generated from the following file:
EventVoxel3D.h