LArCV: larcv::SuperaOpDigit Class Reference
larcv::SuperaOpDigit Class Reference
#include <SuperaOpDigit.h>
Public Member Functions
SuperaOpDigit (const std::string name="SuperaOpDigit")
Default constructor.
~SuperaOpDigit ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
void Request (supera::LArDataType_t, std::string)
template<class T >
void LArData (const T &)
template<class T >
const std::vector< T > & LArData () const
template<>
void LArData (const std::vector< supera::LArWire_t > &data_v)
template<>
void LArData (const std::vector< supera::LArHit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArOpDigit_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTruth_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCTrack_t > &data_v)
template<>
void LArData (const std::vector< supera::LArMCShower_t > &data_v)
template<>
void LArData (const std::vector< supera::LArSimCh_t > &data_v)
template<>
const std::vector< supera::LArWire_t > & LArData () const
template<>
const std::vector< supera::LArHit_t > & LArData () const
template<>
const std::vector< supera::LArOpDigit_t > & LArData () const
template<>
const std::vector< supera::LArSimCh_t > & LArData () const
template<>
const std::vector< supera::LArMCTruth_t > & LArData () const
template<>
const std::vector< supera::LArMCTrack_t > & LArData () const
template<>
const std::vector< supera::LArMCShower_t > & LArData () const
const std::string & LArDataLabel (supera::LArDataType_t type) const
int TimeOffset () const
void ClearEventData ()
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
const std::string & OutImageLabel () const
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
ImageMetaMakerBase * MetaMakerPtr ()
Detailed Description
Definition at line 29 of file SuperaOpDigit.h.
Constructor & Destructor Documentation
SuperaOpDigit()
larcv::SuperaOpDigit::SuperaOpDigit (const std::string name = "SuperaOpDigit")
Default constructor.
Definition at line 14 of file SuperaOpDigit.cxx.
Referenced by larcv::SuperaOpDigitProcessFactory::create().
     : SuperaBase(name)
   {}
~SuperaOpDigit()
larcv::SuperaOpDigit::~SuperaOpDigit () inline
Default destructor.
Definition at line 39 of file SuperaOpDigit.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearEventData()
void larcv::SuperaBase::ClearEventData () inherited
Definition at line 89 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v, larcv::SuperaBase::_ptr_mcs_v, larcv::SuperaBase::_ptr_mct_v, larcv::SuperaBase::_ptr_mctruth_v, larcv::SuperaBase::_ptr_opdigit_v, larcv::SuperaBase::_ptr_sch_v, and larcv::SuperaBase::_ptr_wire_v.
Referenced by larcv::SuperaBase::finalize(), larcv::SuperaBase::initialize(), larcv::SuperaMetaMaker::process(), larcv::SuperaBase::SuperaBase(), and larcv::SuperaBase::TimeOffset().
   {
     _ptr_wire_v     = nullptr;
     _ptr_hit_v      = nullptr;
     _ptr_opdigit_v  = nullptr;
     _ptr_sch_v      = nullptr;
     _ptr_mctruth_v  = nullptr;
     _ptr_mct_v      = nullptr;
     _ptr_mcs_v      = nullptr;
   }
ColCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::ColCompressionFactor () const inherited
Definition at line 36 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::ColCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->ColCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->ColCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
configure()
void larcv::SuperaOpDigit::configure (const PSet & cfg) virtual
Reimplemented from supera::ImageMetaMaker.
Definition at line 18 of file SuperaOpDigit.cxx.
References supera::ParamsImage2D::configure(), larcv::SuperaBase::configure(), supera::ImageMetaMaker::configure(), supera::PulledPork3DSlicer::Is(), LARCV_CRITICAL, and supera::ImageMetaMaker::MetaMakerPtr().
Referenced by ~SuperaOpDigit().
   {
     SuperaBase::configure(cfg);
     supera::ParamsImage2D::configure(cfg);
     supera::ImageMetaMaker::configure(cfg);
     if(supera::PulledPork3DSlicer::Is(supera::ImageMetaMaker::MetaMakerPtr())) {
       LARCV_CRITICAL() << "PulledPork3DSlicer should not be used for Optical image maker!" << std::endl;
       throw larbys();
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::SuperaOpDigit::finalize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 71 of file SuperaOpDigit.cxx.
Referenced by ~SuperaOpDigit().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::SuperaOpDigit::initialize () virtual
Reimplemented from larcv::SuperaBase.
Definition at line 29 of file SuperaOpDigit.cxx.
References larcv::SuperaBase::initialize().
Referenced by ~SuperaOpDigit().
   { SuperaBase::initialize(); }
is()
bool larcv::SuperaBase::is (const std::string question) const virtual inherited
Reimplemented from larcv::ProcessBase.
Reimplemented in larcv::SuperaChStatus.
Definition at line 83 of file SuperaBase.cxx.
Referenced by larcv::SuperaBase::~SuperaBase().
   {
     if(question == "Supera") return true;
     return false;
   }
LArData() [1/16]
template<class T > void larcv::SuperaBase::LArData (const T &) inherited
LArData() [2/16]
template<class T > const std::vector<T>& larcv::SuperaBase::LArData () const inherited
Referenced by larcv::SuperaBase::~SuperaBase().
LArData() [3/16]
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData () const inherited
LArData() [4/16]
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [5/16]
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData () const inherited
LArData() [6/16]
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData () const inherited
LArData() [7/16]
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData () const inherited
LArData() [8/16]
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData () const inherited
LArData() [9/16]
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData () const inherited
LArData() [10/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArWire_t > & data_v) inherited
Definition at line 121 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { _ptr_wire_v = (std::vector<supera::LArWire_t>*)(&data_v); }
LArData() [11/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArHit_t > & data_v) inherited
Definition at line 124 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { _ptr_hit_v = (std::vector<supera::LArHit_t>*)(&data_v); }
LArData() [12/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArOpDigit_t > & data_v) inherited
Definition at line 127 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { _ptr_opdigit_v = (std::vector<supera::LArOpDigit_t>*)(&data_v); }
LArData() [13/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTruth_t > & data_v) inherited
Definition at line 130 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { _ptr_mctruth_v = (std::vector<supera::LArMCTruth_t>*)(&data_v); }
LArData() [14/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCTrack_t > & data_v) inherited
Definition at line 133 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { _ptr_mct_v = (std::vector<supera::LArMCTrack_t>*)(&data_v); }
LArData() [15/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArMCShower_t > & data_v) inherited
Definition at line 136 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { _ptr_mcs_v = (std::vector<supera::LArMCShower_t>*)(&data_v); }
LArData() [16/16]
void larcv::SuperaBase::LArData (const std::vector< supera::LArSimCh_t > & data_v) inherited
Definition at line 139 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { _ptr_sch_v = (std::vector<supera::LArSimCh_t>*)(&data_v); }
LArDataLabel()
const std::string & larcv::SuperaBase::LArDataLabel (supera::LArDataType_t type) const inherited
Definition at line 18 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::SuperaBase::_empty_string.
Referenced by larcv::LArCVSuperaDriver::initialize(), larcv::SuperaMCROI::process(), and larcv::SuperaBase::~SuperaBase().
   {
     auto iter = _data_request_m.find(type);
     if(iter == _data_request_m.end()) return _empty_string;
     return (*iter).second;
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Meta()
const std::vector< larcv::ImageMeta > & supera::ImageMetaMaker::Meta () const inherited
Definition at line 16 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::Meta(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaSimCh::process(), process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
   {
     if(_meta_maker) return _meta_maker->Meta();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->Meta();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
MetaMakerPtr()
ImageMetaMakerBase* supera::ImageMetaMaker::MetaMakerPtr () inline inherited
Definition at line 51 of file ImageMetaMaker.h.
References larcv::SuperaMetaMaker::_meta_maker.
Referenced by configure(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
     { return _meta_maker; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OutImageLabel()
const std::string& supera::ParamsImage2D::OutImageLabel () const inline inherited
Definition at line 41 of file ParamsImage2D.h.
References supera::ParamsImage2D::_out_image_producer.
Referenced by process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), and larcv::SuperaHit::process().
 { return _out_image_producer;    }
process()
bool larcv::SuperaOpDigit::process (IOManager & mgr) virtual
Reimplemented from larcv::SuperaBase.
Definition at line 32 of file SuperaOpDigit.cxx.
References supera::ImageMetaMaker::ColCompressionFactor(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::Image2D::kSum, LARCV_CRITICAL, supera::ImageMetaMaker::Meta(), supera::OpDigit2Image2D(), supera::ParamsImage2D::OutImageLabel(), larcv::SuperaBase::process(), supera::ImageMetaMaker::RowCompressionFactor(), and larcv::SuperaBase::TimeOffset().
Referenced by ~SuperaOpDigit().
   {
     SuperaBase::process(mgr);
     auto const& meta_v = Meta();
     if(meta_v.empty()) {
       LARCV_CRITICAL() << "Meta not created!" << std::endl;
       throw larbys();
     }
     if(meta_v.size()!=1) {
       LARCV_CRITICAL() << "Meta > 1, not expected for OpDigit" << std::endl;
       throw larbys();
     }
     auto ev_image = (EventImage2D*)(mgr.get_data(kProductImage2D,OutImageLabel()));
     if(!ev_image) {
       LARCV_CRITICAL() << "Output image could not be created!" << std::endl;
       throw larbys();
     }
     if(!(ev_image->Image2DArray().empty())) {
       LARCV_CRITICAL() << "Output image array not empty!" << std::endl;
       throw larbys();
     }
     std::vector<larcv::Image2D> image_v;
     image_v.emplace_back(supera::OpDigit2Image2D(meta_v.front(), LArData<supera::LArOpDigit_t>(), TimeOffset()));
     for(size_t plane=0; plane<image_v.size(); ++plane) {
       auto& image = image_v[plane];
       image.compress(image.meta().rows() / RowCompressionFactor().at(plane),
              image.meta().cols() / ColCompressionFactor().at(plane),
              larcv::Image2D::kSum);
     }
     ev_image->Emplace(std::move(image_v));
     return true;
   }
Request()
void larcv::SuperaBase::Request (supera::LArDataType_t type, std::string name) inherited
Definition at line 15 of file SuperaBase.cxx.
References larcv::SuperaBase::_data_request_m, and larcv::larcv_base::name().
Referenced by larcv::SuperaBase::configure(), and larcv::SuperaBase::~SuperaBase().
   { _data_request_m[type]=name; }
RowCompressionFactor()
const std::vector< size_t > & supera::ImageMetaMaker::RowCompressionFactor () const inherited
Definition at line 26 of file ImageMetaMaker.cxx.
References supera::ImageMetaMaker::_meta_maker, supera::ImageMetaMakerBase::RowCompressionFactor(), and supera::ImageMetaMaker::SharedMetaMaker().
Referenced by larcv::SuperaMCPCluster::process(), process(), larcv::SuperaSimCh::process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), and larcv::SuperaHit::process().
   {
     if(_meta_maker) return _meta_maker->RowCompressionFactor();
     auto sptr = SharedMetaMaker();
     if(sptr) return sptr->RowCompressionFactor();
     std::cerr << "MetaMaker does not exist!" << std::endl;
     throw std::exception();
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
TimeOffset()
int larcv::SuperaBase::TimeOffset () const inline inherited
Definition at line 64 of file SuperaBase.h.
References larcv::SuperaBase::_time_offset, and larcv::SuperaBase::ClearEventData().
Referenced by larcv::SuperaMCROI::MakeROI(), larcv::SuperaMCPCluster::process(), larcv::SuperaMetaMaker::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), process(), larcv::SuperaWire::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaHit::process(), and larcv::SuperaMCROI::process().
 { return _time_offset; }
The documentation for this class was generated from the following files:
SuperaOpDigit.h
SuperaOpDigit.cxx