LArCV: larcv::EventVoxel3D Class Reference
larcv::EventVoxel3D Class Reference
Event-wise class to store a collection of larcv::Voxel3D.
#include <EventVoxel3D.h>
Public Member Functions
EventVoxel3D ()
Default constructor.
~EventVoxel3D ()
Default destructor.
void clear ()
larcv::Voxel3D array clearer
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
const std::vector< larcv::Voxel3D > & GetVoxelSet () const
getter
const Voxel3DMeta & GetVoxelMeta () const
getter
void Clear ()
clear
void Reset (const Voxel3DMeta &meta)
reset
void Add (const Voxel3D &vox)
adder
void Emplace (Voxel3D &&vox)
adder
void Move (Voxel3DSet &&vox_set)
mover
Detailed Description
Event-wise class to store a collection of larcv::Voxel3D.
A concrete factory class for larcv::EventVoxel3D.
Definition at line 26 of file EventVoxel3D.h.
Constructor & Destructor Documentation
EventVoxel3D()
larcv::EventVoxel3D::EventVoxel3D () inline
Default constructor.
Definition at line 32 of file EventVoxel3D.h.
Referenced by larcv::EventVoxel3DFactory::create().
 {}
~EventVoxel3D()
larcv::EventVoxel3D::~EventVoxel3D () inline
Default destructor.
Definition at line 35 of file EventVoxel3D.h.
References clear().
 {}
Member Function Documentation
Add()
void larcv::Voxel3DSet::Add (const Voxel3D & vox) inherited
adder
Definition at line 165 of file Voxel3D.cxx.
References larcv::Voxel3DSet::Emplace().
   {
     Voxel3D copy(vox);
     Emplace(std::move(copy));
   }
clear()
void larcv::EventVoxel3D::clear () virtual
larcv::Voxel3D array clearer
Reimplemented from larcv::EventBase.
Definition at line 11 of file EventVoxel3D.cxx.
References larcv::EventBase::clear(), and larcv::Voxel3DSet::Clear().
Referenced by ~EventVoxel3D().
   { EventBase::clear(); Voxel3DSet::Clear(); }
Clear()
void larcv::Voxel3DSet::Clear () inline inherited
clear
Definition at line 192 of file Voxel3D.h.
Referenced by clear().
 { _voxel_v.clear(); _meta.Clear();}
Emplace()
void larcv::Voxel3DSet::Emplace (Voxel3D && vox) inherited
adder
Definition at line 171 of file Voxel3D.cxx.
References larcv::Voxel3DSet::_meta, larcv::Voxel3DSet::_voxel_v, and larcv::Voxel3DMeta::Valid().
Referenced by larcv::Voxel3DSet::Add(), and supera::SimCh2Voxel3D().
   {
     if(!_meta.Valid())
       throw larbys("Voxel3DSet::Emplace cannot be called without a valid meta!");
     // In case it's empty or greater than the last one
     if(_voxel_v.empty() || _voxel_v.back() < vox) {
       _voxel_v.emplace_back(std::move(vox));
       return;
     }
     // In case it's smaller than the first one
     if(_voxel_v.front() > vox) {
       _voxel_v.emplace_back(std::move(vox));
       for(size_t idx=0; (idx+1)<_voxel_v.size(); ++idx) {
     auto& element1 = _voxel_v[ _voxel_v.size() - (idx+1) ];
     auto& element2 = _voxel_v[ _voxel_v.size() - (idx+2) ];
     std::swap( element1, element2 );
       }
       return;
     }
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     // Cannot be the end
     if( iter == _voxel_v.end() )
       throw larbys("Voxel3DSet sorting logic error!");
     // If found, merge
     if( !(vox < (*iter)) ) {
       (*iter) += vox.Value();
       return;
     }
     // Else insert @ appropriate place
     else {
       size_t target_loc = iter - _voxel_v.begin();
       _voxel_v.emplace_back(std::move(vox));
       for(size_t idx=target_loc; (idx+1)<_voxel_v.size(); ++idx) {
     auto& element1 = _voxel_v[ _voxel_v.size() - (idx+1) ];
     auto& element2 = _voxel_v[ _voxel_v.size() - (idx+2) ];
     std::swap( element1, element2 );
       }
     }
     return;
   }
event()
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _event;  }
event_key()
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::EventBase::operator<(), and larcv::IOManager< T >::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
GetVoxelMeta()
const Voxel3DMeta& larcv::Voxel3DSet::GetVoxelMeta () const inline inherited
getter
Definition at line 189 of file Voxel3D.h.
     { return _meta; }
GetVoxelSet()
const std::vector<larcv::Voxel3D>& larcv::Voxel3DSet::GetVoxelSet () const inline inherited
getter
Definition at line 185 of file Voxel3D.h.
     { return _voxel_v; }
Move()
void larcv::Voxel3DSet::Move (Voxel3DSet && vox_set) inline inherited
mover
Definition at line 203 of file Voxel3D.h.
     { _meta = std::move(vox_set._meta); _voxel_v = std::move(vox_set._voxel_v); }
operator!=()
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
operator<()
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
operator==()
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
producer()
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
Reset()
void larcv::Voxel3DSet::Reset (const Voxel3DMeta & meta) inline inherited
reset
Definition at line 194 of file Voxel3D.h.
     { Clear(); _meta = meta; }
run()
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::LArbysImageAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _run;    }
subrun()
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::ParticleAna::process(), larcv::ExampleAna::process(), larcv::BadRegionAna::process(), larcv::ROIAna::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::register_producer(), larcv::ImageHolder::retrieve_id(), and larcv::IOManager< T >::set_id().
 { return _subrun; }
valid()
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
The documentation for this class was generated from the following files:
EventVoxel3D.h
EventVoxel3D.cxx