LArCV: larcv::ChannelMax Class Reference
larcv::ChannelMax Class Reference
#include <ChannelMax.h>
Public Member Functions
ChannelMax (const std::string name="ChannelMax")
Default constructor.
~ChannelMax ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
size_t _nplanes
std::string _in_producer
std::string _out_producer
std::vector< float > _plane_weight_v
std::vector< bool > _relevant_chan_v
std::vector< float > _channel_mask_v
Detailed Description
Definition at line 26 of file ChannelMax.h.
Constructor & Destructor Documentation
ChannelMax()
larcv::ChannelMax::ChannelMax (const std::string name = "ChannelMax")
Default constructor.
Definition at line 11 of file ChannelMax.cxx.
Referenced by larcv::ChannelMaxProcessFactory::create().
     : ProcessBase(name)
   {}
~ChannelMax()
larcv::ChannelMax::~ChannelMax () inline
Default destructor.
Definition at line 34 of file ChannelMax.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ChannelMax::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 15 of file ChannelMax.cxx.
References _channel_mask_v, _in_producer, _nplanes, _out_producer, _plane_weight_v, _relevant_chan_v, and larcv::PSet::get().
Referenced by ~ChannelMax().
   {
     _in_producer      = cfg.get<std::string>("InProducer");
     _nplanes          = cfg.get<size_t>("NPlanes");
     _out_producer     = cfg.get<std::string>("OutputProducer");
     _plane_weight_v   = cfg.get<std::vector<float> >("ChannelWeights",{});
     if (_plane_weight_v.empty()) {
       _plane_weight_v.resize(_nplanes,1.0);
     }
     auto relevant_chanid_v  = cfg.get<std::vector<size_t> >("RelevantChannels",{});
     _relevant_chan_v.resize(_nplanes);
     //set all channels false
     for(size_t plane=0;plane<_nplanes;++plane) _relevant_chan_v[plane]=false;
     //if no input, set all channels true
     if (relevant_chanid_v.empty()) {
       for(size_t plane=0;plane<_nplanes;++plane) _relevant_chan_v[plane]=true;
     }
     //else set the requested ones true
     else {
       for(auto& chanid : relevant_chanid_v) {
     _relevant_chan_v[chanid]=true;
       }
     }
     auto channel_mask_v = cfg.get<std::vector<float> >("ChannelMask",{});
     _channel_mask_v.resize(_nplanes);
     if (channel_mask_v.empty()) {
       for(size_t plane=0;plane<_nplanes;++plane) _channel_mask_v[plane] = (float)plane;
     } else {
       _channel_mask_v = channel_mask_v;
     }
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ChannelMax::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 87 of file ChannelMax.cxx.
Referenced by ~ChannelMax().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ChannelMax::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 52 of file ChannelMax.cxx.
Referenced by ~ChannelMax().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ChannelMax::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 55 of file ChannelMax.cxx.
References _channel_mask_v, _in_producer, _nplanes, _out_producer, _plane_weight_v, _relevant_chan_v, larcv::ImageMeta::cols(), larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::Image2D::meta(), larcv::ImageMeta::rows(), and larcv::Image2D::set_pixel().
Referenced by ~ChannelMax().
   {
     auto event_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_in_producer));
     if(!event_image) throw larbys("No event image found");
     auto& img_v = event_image->Image2DArray();
     if (img_v.empty()) return false;
     larcv::Image2D image(img_v[0].meta());
     for(size_t row=0;row<image.meta().rows();++row){
       for(size_t col=0;col<image.meta().cols();++col){
     float maxpx(-1),maxpl(-1);
     for(size_t plane=0;plane<_nplanes;++plane) {
       if(!_relevant_chan_v[plane]) continue;
       auto px=img_v[plane].pixel(row,col);
       px*=_plane_weight_v[plane];
       if (px>maxpx) { maxpx=px; maxpl=plane; }
     }
     if (maxpx<0 or maxpl<0) throw larbys("No max plane identified");
     image.set_pixel(row,col,_channel_mask_v[maxpl]);
       }
     }
     auto out_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_out_producer));
     out_image->Emplace(std::move(image));
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_channel_mask_v
std::vector<float> larcv::ChannelMax::_channel_mask_v private
Definition at line 51 of file ChannelMax.h.
Referenced by configure(), and process().
_in_producer
std::string larcv::ChannelMax::_in_producer private
Definition at line 47 of file ChannelMax.h.
Referenced by configure(), and process().
_nplanes
size_t larcv::ChannelMax::_nplanes private
Definition at line 46 of file ChannelMax.h.
Referenced by configure(), and process().
_out_producer
std::string larcv::ChannelMax::_out_producer private
Definition at line 48 of file ChannelMax.h.
Referenced by configure(), and process().
_plane_weight_v
std::vector<float> larcv::ChannelMax::_plane_weight_v private
Definition at line 49 of file ChannelMax.h.
Referenced by configure(), and process().
_relevant_chan_v
std::vector<bool> larcv::ChannelMax::_relevant_chan_v private
Definition at line 50 of file ChannelMax.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ChannelMax.h
ChannelMax.cxx