LArCV: supera::ImageMetaMakerBase Class Reference
supera::ImageMetaMakerBase Class Reference abstract
User defined class ImageMetaMakerBase ...
#include <ImageMetaMakerBase.h>
Public Member Functions
ImageMetaMakerBase (std::string name="NoName")
Default constructor.
virtual ~ImageMetaMakerBase ()
Default destructor.
virtual void configure (const supera::Config_t &)
virtual const std::vector< larcv::ImageMeta > & Meta () const =0
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< size_t > _comp_rows
std::vector< size_t > _comp_cols
Detailed Description
User defined class ImageMetaMakerBase ...
these comments are used to generate doxygen documentation!
Definition at line 28 of file ImageMetaMakerBase.h.
Constructor & Destructor Documentation
ImageMetaMakerBase()
supera::ImageMetaMakerBase::ImageMetaMakerBase (std::string name = "NoName") inline
Default constructor.
Definition at line 33 of file ImageMetaMakerBase.h.
       : larcv_base(name)
     {}
~ImageMetaMakerBase()
virtual supera::ImageMetaMakerBase::~ImageMetaMakerBase () inline virtual
Default destructor.
Definition at line 38 of file ImageMetaMakerBase.h.
References configure(), and Meta().
 {}
Member Function Documentation
ColCompressionFactor()
const std::vector<size_t>& supera::ImageMetaMakerBase::ColCompressionFactor () const inline
Definition at line 44 of file ImageMetaMakerBase.h.
References _comp_cols.
Referenced by supera::ImageMetaMaker::ColCompressionFactor(), and supera::ImageMetaFromConfig::configure().
 { return _comp_cols; }
configure()
void supera::ImageMetaMakerBase::configure (const supera::Config_t & cfg) virtual
Reimplemented in supera::PulledPork3DSlicer, and supera::ImageMetaFromConfig.
Definition at line 8 of file ImageMetaMakerBase.cxx.
References _comp_cols, _comp_rows, larcv::PSet::get(), and supera::Nplanes().
Referenced by supera::ImageMetaFromConfig::configure(), supera::PulledPork3DSlicer::configure(), and ~ImageMetaMakerBase().
   {
     _comp_rows  = cfg.get<std::vector<size_t> >("EventCompRows");
     _comp_cols  = cfg.get<std::vector<size_t> >("EventCompCols");
     if(_comp_rows.size() != supera::Nplanes()) {
       std::cerr << "EventCompRows size != # planes..." << std::endl;
       throw std::exception();
     }
     if(_comp_cols.size() != supera::Nplanes()) {
       std::cerr << "EventCompCols size != # planes..." << std::endl;
       throw std::exception();
     }
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Meta()
virtual const std::vector<larcv::ImageMeta>& supera::ImageMetaMakerBase::Meta () const pure virtual
Implemented in supera::PulledPork3DSlicer, and supera::ImageMetaFromConfig.
Referenced by supera::ImageMetaMaker::Meta(), and ~ImageMetaMakerBase().
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
RowCompressionFactor()
const std::vector<size_t>& supera::ImageMetaMakerBase::RowCompressionFactor () const inline
Definition at line 43 of file ImageMetaMakerBase.h.
References _comp_rows.
Referenced by supera::ImageMetaFromConfig::configure(), and supera::ImageMetaMaker::RowCompressionFactor().
 { return _comp_rows; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_comp_cols
std::vector<size_t> supera::ImageMetaMakerBase::_comp_cols private
Definition at line 49 of file ImageMetaMakerBase.h.
Referenced by ColCompressionFactor(), and configure().
_comp_rows
std::vector<size_t> supera::ImageMetaMakerBase::_comp_rows private
Definition at line 48 of file ImageMetaMakerBase.h.
Referenced by configure(), and RowCompressionFactor().
The documentation for this class was generated from the following files:
ImageMetaMakerBase.h
ImageMetaMakerBase.cxx