LArCV: larcv::VertexAnaProcessFactory Class Reference
larcv::VertexAnaProcessFactory Class Reference
#include <VertexAna.h>
Public Member Functions
VertexAnaProcessFactory ()
ctor
~VertexAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 124 of file VertexAna.h.
Constructor & Destructor Documentation
VertexAnaProcessFactory()
larcv::VertexAnaProcessFactory::VertexAnaProcessFactory () inline
ctor
Definition at line 127 of file VertexAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("VertexAna",this); }
~VertexAnaProcessFactory()
larcv::VertexAnaProcessFactory::~VertexAnaProcessFactory () inline
dtor
Definition at line 129 of file VertexAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::VertexAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 131 of file VertexAna.h.
References larcv::VertexAna::VertexAna().
 { return new VertexAna(instance_name); }
The documentation for this class was generated from the following file:
VertexAna.h