LArCV: larcv::Vertex Class Reference
larcv::Vertex Class Reference
#include <Vertex.h>
Public Member Functions
Vertex ()
Particle ID default constructor.
Vertex (double x, double y, double z, double t)
void Reset ()
Reset function for x, y, z, t.
double X () const
double Y () const
double Z () const
double T () const
virtual ~Vertex ()
Default destructor.
bool operator== (const Vertex &rhs) const
bool operator!= (const Vertex &rhs) const
bool operator< (const Vertex &rhs) const
Vertex ()
Particle ID default constructor.
Vertex (double x, double y, double z, double t)
void Reset ()
Reset function.
void Reset (double x, double y, double z, double t)
Reset function for x, y, z, t.
double X () const
double Y () const
double Z () const
double T () const
virtual ~Vertex ()
Default destructor.
bool operator== (const Vertex &rhs) const
bool operator!= (const Vertex &rhs) const
bool operator< (const Vertex &rhs) const
Private Member Functions
void Approx ()
void Approx ()
Private Attributes
double _x
double _y
double _z
double _t
Friends
class Vertex
Detailed Description
Definition at line 6 of file arxiv/Vertex.h.
Constructor & Destructor Documentation
Vertex() [1/4]
larcv::Vertex::Vertex ()
Particle ID default constructor.
Vertex() [2/4]
larcv::Vertex::Vertex (double x, double y, double z, double t)
Definition at line 16 of file arxiv/Vertex.cxx.
     : _x(x), _y(y), _z(z), _t(t)
   {}
~Vertex() [1/2]
virtual larcv::Vertex::~Vertex () inline virtual
Default destructor.
Definition at line 23 of file arxiv/Vertex.h.
 {};
Vertex() [3/4]
larcv::Vertex::Vertex ()
Particle ID default constructor.
Vertex() [4/4]
larcv::Vertex::Vertex (double x, double y, double z, double t)
~Vertex() [2/2]
virtual larcv::Vertex::~Vertex () inline virtual
Default destructor.
Definition at line 24 of file Vertex.h.
 {};
Member Function Documentation
Approx() [1/2]
void larcv::Vertex::Approx () private
Definition at line 24 of file arxiv/Vertex.cxx.
References _t, _x, _y, and _z.
Referenced by operator<(), and Reset().
   {
     _x = (double)( ((signed long long)(_x * 1.e12)) * 1.e-12 );
     _y = (double)( ((signed long long)(_y * 1.e12)) * 1.e-12 );
     _z = (double)( ((signed long long)(_z * 1.e12)) * 1.e-12 );
     _t = (double)( ((signed long long)(_t * 1.e12)) * 1.e-12 );
   }
Approx() [2/2]
void larcv::Vertex::Approx () private
operator!=() [1/2]
bool larcv::Vertex::operator!= (const Vertex & rhs) const inline
Definition at line 30 of file arxiv/Vertex.h.
     {
       return !((*this) == rhs);
     }
operator!=() [2/2]
bool larcv::Vertex::operator!= (const Vertex & rhs) const inline
Definition at line 31 of file Vertex.h.
     {
       return !((*this) == rhs);
     }
operator<() [1/2]
bool larcv::Vertex::operator< (const Vertex & rhs) const inline
Definition at line 35 of file arxiv/Vertex.h.
References _t, _x, _y, and _z.
     {
       if( _x     < rhs._x ) return true;
       if( rhs._x < _x     ) return false;
       if( _y     < rhs._y ) return true;
       if( rhs._y < _y     ) return false;
       if( _z     < rhs._z ) return true;
       if( rhs._z < _z     ) return false;
       if( _t     < rhs._t ) return true;
       if( rhs._t < _t     ) return false;
       return false;
     }
operator<() [2/2]
bool larcv::Vertex::operator< (const Vertex & rhs) const inline
Definition at line 36 of file Vertex.h.
References _t, _x, _y, _z, and Approx().
     {
       if( _x     < rhs._x ) return true;
       if( rhs._x < _x     ) return false;
       if( _y     < rhs._y ) return true;
       if( rhs._y < _y     ) return false;
       if( _z     < rhs._z ) return true;
       if( rhs._z < _z     ) return false;
       if( _t     < rhs._t ) return true;
       if( rhs._t < _t     ) return false;
       return false;
     }
operator==() [1/2]
bool larcv::Vertex::operator== (const Vertex & rhs) const inline
Definition at line 25 of file arxiv/Vertex.h.
References _t, _x, _y, and _z.
     {
       return ( _x == rhs._x && _y == rhs._y && _z == rhs._z && _t == rhs._t );
     }
operator==() [2/2]
bool larcv::Vertex::operator== (const Vertex & rhs) const inline
Definition at line 26 of file Vertex.h.
References _t, _x, _y, and _z.
     {
       return ( _x == rhs._x && _y == rhs._y && _z == rhs._z && _t == rhs._t );
     }
Reset() [1/3]
void larcv::Vertex::Reset ()
Reset function.
Reset() [2/3]
void larcv::Vertex::Reset ()
Reset function for x, y, z, t.
Definition at line 20 of file arxiv/Vertex.cxx.
References _t, _x, _y, and _z.
Referenced by larcv::hires::HiResImageDivider::ApplySCE(), and supera::MCParticleTree::FillNode().
                     {
     _x = _y = _z = _t = 0;
   }
Reset() [3/3]
void larcv::Vertex::Reset (double x, double y, double z, double t)
Reset function for x, y, z, t.
Definition at line 24 of file Vertex.cxx.
References _t, _x, _y, _z, and Approx().
   {
     _x = x;
     _y = y;
     _z = z;
     _t = t;
     Approx();
   }
T() [1/2]
double larcv::Vertex::T () const inline
Definition at line 20 of file arxiv/Vertex.h.
References _t.
Referenced by larcv::hires::HiResImageDivider::ApplySCE(), supera::MCRoot::dt(), larcv::ROI::ParentT(), larcv::ParticleROI::T(), and larcv::ROI::T().
 { return _t; }
T() [2/2]
double larcv::Vertex::T () const inline
Definition at line 21 of file Vertex.h.
References _t.
 { return _t; }
X() [1/2]
double larcv::Vertex::X () const inline
Definition at line 17 of file arxiv/Vertex.h.
References _x.
Referenced by larcv::hires::HiResImageDivider::ApplySCE(), supera::MCParticleTree::FindPrimary(), larcv::ROI::ParentX(), supera::MCROIMaker::ParticleROI(), larcv::ParticleROI::X(), and larcv::ROI::X().
 { return _x; }
X() [2/2]
double larcv::Vertex::X () const inline
Definition at line 18 of file Vertex.h.
References _x.
 { return _x; }
Y() [1/2]
double larcv::Vertex::Y () const inline
Definition at line 18 of file arxiv/Vertex.h.
References _y.
Referenced by larcv::hires::HiResImageDivider::ApplySCE(), supera::MCParticleTree::FindPrimary(), larcv::ROI::ParentY(), larcv::ParticleROI::Y(), and larcv::ROI::Y().
 { return _y; }
Y() [2/2]
double larcv::Vertex::Y () const inline
Definition at line 19 of file Vertex.h.
References _y.
 { return _y; }
Z() [1/2]
double larcv::Vertex::Z () const inline
Definition at line 19 of file arxiv/Vertex.h.
References _z.
Referenced by larcv::hires::HiResImageDivider::ApplySCE(), supera::MCParticleTree::FindPrimary(), larcv::ROI::ParentZ(), larcv::ParticleROI::Z(), and larcv::ROI::Z().
 { return _z; }
Z() [2/2]
double larcv::Vertex::Z () const inline
Definition at line 20 of file Vertex.h.
References _z.
 { return _z; }
Friends And Related Function Documentation
Vertex
larcv::Vertex::Vertex friend
Definition at line 7 of file arxiv/Vertex.h.
Member Data Documentation
_t
double larcv::Vertex::_t private
Definition at line 50 of file arxiv/Vertex.h.
Referenced by Approx(), operator<(), operator==(), Reset(), and T().
_x
double larcv::Vertex::_x private
Definition at line 50 of file arxiv/Vertex.h.
Referenced by Approx(), operator<(), operator==(), Reset(), and X().
_y
double larcv::Vertex::_y private
Definition at line 50 of file arxiv/Vertex.h.
Referenced by Approx(), operator<(), operator==(), Reset(), and Y().
_z
double larcv::Vertex::_z private
Definition at line 50 of file arxiv/Vertex.h.
Referenced by Approx(), operator<(), operator==(), Reset(), and Z().
The documentation for this class was generated from the following files:
arxiv/Vertex.h
arxiv/Vertex.cxx