LArCV: larcv::PreProcessor Class Reference
larcv::PreProcessor Class Reference
#include <PreProcessor.h>
Public Member Functions
PreProcessor ()
~PreProcessor ()
bool PreProcess (cv::Mat &adc_img, cv::Mat &track_img, cv::Mat &shower_img)
void Configure (const PSet &pset)
void MergeTracklets (cv::Mat &track_img, cv::Mat &shower_img)
void ClaimShowers (cv::Mat &adc_img, cv::Mat &track_img, cv::Mat &shower_img)
void MergePixelByFraction (cv::Mat &adc_img, cv::Mat &track_img, cv::Mat &shower_img)
void MergeStraightShowers (cv::Mat &adc_img, cv::Mat &track_img, cv::Mat &shower_img)
void MergeEndNubs (cv::Mat &adc_img, cv::Mat &track_img, cv::Mat &shower_img)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
bool OverallStraightCompatible (const larocv::PixelChunk &pchunk1, const larocv::PixelChunk &pchunk2)
bool IsStraight (const larocv::PixelChunk &track, const cv::Mat &img)
void FilterContours (larocv::GEO2D_ContourArray_t &ctor_v)
std::vector< larocv::PixelChunk > MakePixelChunks (const cv::Mat &img, larocv::ChunkType_t type, bool calc_params=true, size_t min_ctor_size=0, size_t min_track_size=0)
bool EdgeConnected (const larocv::PixelChunk &track1, const larocv::PixelChunk &track2)
cv::Mat PrepareImage (const cv::Mat &img)
float GetClosestEdge (const larocv::PixelChunk &track1, const larocv::PixelChunk &track2, geo2d::Vector< float > &edge1, geo2d::Vector< float > &edge2)
float GetClosestEdge (const larocv::PixelChunk &track1, const larocv::PixelChunk &track2)
Private Attributes
uint _pi_threshold
uint _min_ctor_size
uint _blur
float _allowed_neighbor_dist
uint _pca_box_size
float _min_overall_angle
float _min_pca_angle
float _min_track_size
bool _merge_tracklets
bool _merge_pixel_frac
bool _claim_showers
float _min_track_frac
float _min_shower_frac
float _max_track_in_shower_frac
double _mean_distance_pca
uint _min_merge_track_size
bool _merge_straight_showers
uint _min_merge_track_shower_dist
double _allowed_merge_neighbor_dist
double _allowed_edge_overlap
bool _merge_end_nubs
uint _end_nub_max_pixels
uint _min_track_pixels
Detailed Description
Definition at line 16 of file PreProcessor.h.
Constructor & Destructor Documentation
PreProcessor()
larcv::PreProcessor::PreProcessor ()
General...
Straightness
MergeTracklets
ClaimShowers
MergePixelByFraction
MergeStraightShowers
MergeEndNubs
Definition at line 13 of file PreProcessor.cxx.
References _allowed_edge_overlap, _allowed_merge_neighbor_dist, _allowed_neighbor_dist, _blur, _claim_showers, _end_nub_max_pixels, _max_track_in_shower_frac, _mean_distance_pca, _merge_end_nubs, _merge_pixel_frac, _merge_straight_showers, _merge_tracklets, _min_ctor_size, _min_merge_track_shower_dist, _min_merge_track_size, _min_overall_angle, _min_pca_angle, _min_shower_frac, _min_track_frac, _min_track_pixels, _pca_box_size, _pi_threshold, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "start" << std::endl;
     _pi_threshold=1;
     _min_ctor_size=4;
     _blur = 4;
     _pca_box_size=5;
     _min_overall_angle=10;
     _min_pca_angle=10;
     _mean_distance_pca = 3;
     _merge_tracklets=true;
     _min_merge_track_size = 40;
     _min_merge_track_shower_dist = 2;
     _claim_showers=true;
     _max_track_in_shower_frac = 0.1;
     _merge_pixel_frac = true;
     _min_track_frac = 0.8;
     _min_shower_frac = 0.8;
     _allowed_neighbor_dist = 10;
     _allowed_merge_neighbor_dist=10;
     _allowed_edge_overlap=20;
     _merge_straight_showers=true;
     _merge_end_nubs     = false;
     _min_track_pixels   = 100;
     _end_nub_max_pixels = 30;
     LARCV_DEBUG() << "end" << std::endl;
   }
~PreProcessor()
larcv::PreProcessor::~PreProcessor () inline
Definition at line 21 of file PreProcessor.h.
References ClaimShowers(), Configure(), EdgeConnected(), FilterContours(), GetClosestEdge(), IsStraight(), MakePixelChunks(), MergeEndNubs(), MergePixelByFraction(), MergeStraightShowers(), MergeTracklets(), OverallStraightCompatible(), PrepareImage(), and PreProcess().
 {}
Member Function Documentation
ClaimShowers()
void larcv::PreProcessor::ClaimShowers (cv::Mat & adc_img, cv::Mat & track_img, cv::Mat & shower_img)
Definition at line 327 of file PreProcessor.cxx.
References _max_track_in_shower_frac, MakePixelChunks(), and PrepareImage().
Referenced by PreProcess(), and ~PreProcessor().
{
     auto adc_img_t = PrepareImage(adc_img);
     auto track_img_t = PrepareImage(track_img);
     auto shower_img_t = PrepareImage(shower_img);
     auto track_pchunk_v = MakePixelChunks(track_img_t,larocv::ChunkType_t::kTrack,true);
     auto shower_pchunk_v = MakePixelChunks(shower_img_t,larocv::ChunkType_t::kShower,true);
     for(auto& shower_pchunk : shower_pchunk_v) {
       auto& shower_ctor = shower_pchunk.ctor;
       auto& track_frac = shower_pchunk.track_frac;
       for(const auto& track_pchunk : track_pchunk_v) {
     //this track not near the edge point...
     auto& track_ctor = track_pchunk.ctor;
     track_frac += larocv::PixelFraction(adc_img_t,shower_ctor,track_ctor);
       }
       if (track_frac < _max_track_in_shower_frac) {
     auto mask_shower = larocv::MaskImage(track_img,shower_ctor,0,false);
     track_img = larocv::MaskImage(track_img,shower_ctor,0,true);
     shower_img = shower_img + mask_shower;
       }
     }
   }
Configure()
void larcv::PreProcessor::Configure (const PSet & pset)
Definition at line 56 of file PreProcessor.cxx.
References _allowed_neighbor_dist, _blur, _claim_showers, _end_nub_max_pixels, _merge_end_nubs, _merge_pixel_frac, _merge_straight_showers, _merge_tracklets, _min_ctor_size, _min_merge_track_shower_dist, _min_merge_track_size, _min_overall_angle, _min_track_pixels, _pca_box_size, _pi_threshold, larcv::PSet::get(), LARCV_DEBUG, and larcv::larcv_base::set_verbosity().
Referenced by larcv::LArbysImageExtract::configure(), larcv::LArbysImage::configure(), larcv::PreProcessorAna::configure(), and ~PreProcessor().
{
     LARCV_DEBUG() << "start" << std::endl;
     this->set_verbosity((msg::Level_t)pset.get<int>("Verbosity"));
     _pi_threshold = pset.get<uint>("PiThreshold",1);
     _min_ctor_size = pset.get<uint>("MinContourSize",4);
     _allowed_neighbor_dist = pset.get<float>("AllowedNeighborSeparation",10);
     _blur = pset.get<uint>("BlurSize",4);
     _pca_box_size = pset.get<uint>("EdgePCABoxSize",5);
     _min_overall_angle = pset.get<float>("MinPCAOverallAngle",10);
     _merge_tracklets = pset.get<bool>("MergeTracklets",false);
     if(_merge_tracklets) {
       _min_merge_track_size = pset.get<uint>("MergeTrackletsSize");
       _min_merge_track_shower_dist = pset.get<uint>("MergeTrackletsDist");
     }
     _claim_showers         = pset.get<bool>("ClaimShowers",false);
     _merge_pixel_frac      = pset.get<bool>("MergePixelFrac",false);
     _merge_straight_showers= pset.get<bool>("MergeStraightShowers",false);
     _merge_end_nubs         = pset.get<bool>("MergeEndNubs",false);
     _min_track_pixels       = pset.get<uint>("MinTrackPixels",100);
     _end_nub_max_pixels     = pset.get<uint>("MaxEndNubPixels",0);
     LARCV_DEBUG() << "end" << std::endl;
     return;
   }
EdgeConnected()
bool larcv::PreProcessor::EdgeConnected (const larocv::PixelChunk & track1, const larocv::PixelChunk & track2) private
Definition at line 223 of file PreProcessor.cxx.
References _allowed_neighbor_dist, and LARCV_DEBUG.
Referenced by MergeEndNubs(), MergeStraightShowers(), and ~PreProcessor().
{
     const auto& t1edge1 = track1.edge1;
     const auto& t1edge2 = track1.edge2;
     const auto& t2edge1 = track2.edge1;
     const auto& t2edge2 = track2.edge2;
     bool bt11t21,bt11t22,bt12t21,bt12t22;
     bt11t21=bt11t22=bt12t21=bt12t22=false;
     auto ft11t21 = geo2d::dist(t1edge1,t2edge1);
     auto ft11t22 = geo2d::dist(t1edge1,t2edge2);
     auto ft12t21 = geo2d::dist(t1edge2,t2edge1);
     auto ft12t22 = geo2d::dist(t1edge2,t2edge2);
     if(ft11t21 < _allowed_neighbor_dist) bt11t21=true;
     if(ft11t22 < _allowed_neighbor_dist) bt11t22=true;
     if(ft12t21 < _allowed_neighbor_dist) bt12t21=true;
     if(ft12t22 < _allowed_neighbor_dist) bt12t22=true;
     if (bt11t21)
       { LARCV_DEBUG() << "Track 1 edge1 & Track 2 edge1 neaby" << std::endl; return true; }
     if (bt11t22)
       { LARCV_DEBUG() << "Track 1 edge1 & Track 2 edge2 nearby" << std::endl; return true; }
     if (bt12t21)
       { LARCV_DEBUG() << "Track 1 edge2 & Track 2 edge1 nearby" << std::endl; return true; }
     if (bt12t22)
       { LARCV_DEBUG() << "Track 1 edge2 & Track 2 edge2 nearby" << std::endl; return true; }
     return false;
   }
FilterContours()
void larcv::PreProcessor::FilterContours (larocv::GEO2D_ContourArray_t & ctor_v) private
Definition at line 145 of file PreProcessor.cxx.
References _min_ctor_size.
Referenced by ~PreProcessor().
{
     larocv::GEO2D_ContourArray_t ctor_tmp_v;
     ctor_tmp_v.reserve(ctor_v.size());
     for(auto& ctor : ctor_v)
       if(ctor.size()>_min_ctor_size)
     ctor_tmp_v.emplace_back(std::move(ctor));
     std::swap(ctor_tmp_v,ctor_v);
     return;
   }
GetClosestEdge() [1/2]
float larcv::PreProcessor::GetClosestEdge (const larocv::PixelChunk & track1, const larocv::PixelChunk & track2, geo2d::Vector< float > & edge1, geo2d::Vector< float > & edge2) private
Definition at line 113 of file PreProcessor.cxx.
Referenced by GetClosestEdge(), MergePixelByFraction(), and ~PreProcessor().
{
     geo2d::Vector<float> e1,e2;
     float dist=std::numeric_limits<float>::max();
     auto dt1e1t2e1 = geo2d::dist(track1.edge1,track2.edge1);
     auto dt1e1t2e2 = geo2d::dist(track1.edge1,track2.edge2);
     auto dt1e2t2e1 = geo2d::dist(track1.edge2,track2.edge1);
     auto dt1e2t2e2 = geo2d::dist(track1.edge2,track2.edge2);
     if (dt1e1t2e1 < dist)
       { dist = dt1e1t2e1; edge1=track1.edge1; edge2=track2.edge1; }
     if (dt1e1t2e2 < dist)
       { dist = dt1e1t2e2; edge1=track1.edge1; edge2=track2.edge2; }
     if (dt1e2t2e1 < dist)
       { dist = dt1e2t2e1; edge1=track1.edge2; edge2=track2.edge1; }
     if (dt1e2t2e2 < dist)
       { dist = dt1e2t2e2; edge1=track1.edge2; edge2=track2.edge2; }
     return dist;
   }
GetClosestEdge() [2/2]
float larcv::PreProcessor::GetClosestEdge (const larocv::PixelChunk & track1, const larocv::PixelChunk & track2) private
Definition at line 138 of file PreProcessor.cxx.
References GetClosestEdge().
{
     geo2d::Vector<float> temp1,temp2;
     return GetClosestEdge(track1,track2,temp1,temp2);
   }
IsStraight()
bool larcv::PreProcessor::IsStraight (const larocv::PixelChunk & track, const cv::Mat & img) private
Definition at line 87 of file PreProcessor.cxx.
References _mean_distance_pca, and _min_pca_angle.
Referenced by MakePixelChunks(), and ~PreProcessor().
{
     auto e1e2_a = std::abs(geo2d::angle(track.edge1PCA,track.edge2PCA));
     auto e1oA_a = std::abs(geo2d::angle(track.edge1PCA,track.overallPCA));
     auto e2oA_a = std::abs(geo2d::angle(track.edge2PCA,track.overallPCA));
     // auto oe1PCA_a  = std::abs(geo2d::angle(track.overallPCA,track.edge1PCA));
     bool e1e2_b = false;
     bool e1oA_b = false;
     bool e2oA_b = false;
     bool pca_b = false;
     if ((e1e2_a < _min_pca_angle) or (e1e2_a > 180-_min_pca_angle)) // probably straight
       e1e2_b=true;
     if ((e1oA_a < _min_pca_angle) or (e1oA_a > 180-_min_pca_angle)) // probably straight
       e1oA_b=true;
     if ((e2oA_a < _min_pca_angle) or (e2oA_a > 180-_min_pca_angle)) // probably straight
       e2oA_b=true;
     if ( track.mean_pixel_dist < _mean_distance_pca)
       pca_b = true;
     return (pca_b and (e1e2_b or e1oA_b or e2oA_b));
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
MakePixelChunks()
std::vector< larocv::PixelChunk > larcv::PreProcessor::MakePixelChunks (const cv::Mat & img, larocv::ChunkType_t type, bool calc_params = true, size_t min_ctor_size = 0, size_t min_track_size = 0) private
Definition at line 158 of file PreProcessor.cxx.
References _pca_box_size, IsStraight(), and LARCV_DEBUG.
Referenced by ClaimShowers(), MergeEndNubs(), MergePixelByFraction(), MergeStraightShowers(), MergeTracklets(), and ~PreProcessor().
{
     auto ctor_v = larocv::FindContours(img);
     std::vector<larocv::PixelChunk> track_v;
     track_v.reserve(ctor_v.size());
     LARCV_DEBUG() << "Found " << ctor_v.size() << " contours of type " << (uint) type  << std::endl;
     for(auto& ctor_ : ctor_v) {
       LARCV_DEBUG() << "... size " << ctor_.size() << std::endl;
       if (ctor_.size() < min_ctor_size) continue;
       larocv::PixelChunk pchunk;
       pchunk.npixel = cv::countNonZero(larocv::MaskImage(img,ctor_,0,false));
       pchunk.type = type;
       pchunk.ctor = std::move(ctor_);
       auto& ctor = pchunk.ctor;
       if (pchunk.npixel < min_track_size) continue;
       if (calc_params) {
     // make the edge
     geo2d::Vector<float> edge1,edge2;
     larocv::FindEdges(ctor,edge1,edge2);
     //rotated rect coordinates
     auto min_rect  = cv::minAreaRect(ctor);
     cv::Point2f vertices[4];
     min_rect.points(vertices);
     pchunk.edge1 = edge1;
     pchunk.edge2 = edge2;
     //set parameters from rotated rect
     auto rect = min_rect.size;
     pchunk.length = rect.height > rect.width ? rect.height : rect.width;
     pchunk.width = rect.height > rect.width ? rect.width  : rect.height;
     pchunk.perimeter = cv::arcLength(ctor,1);
     pchunk.area = cv::contourArea(ctor);
     pchunk.overallPCA = larocv::CalcPCA(ctor);
     pchunk.edge1PCA = larocv::SquarePCA(img,edge1,_pca_box_size,_pca_box_size);
     pchunk.edge2PCA = larocv::SquarePCA(img,edge2,_pca_box_size,_pca_box_size);
     pchunk.track_frac = type==larocv::ChunkType_t::kTrack  ? 1 : 0;
     pchunk.shower_frac = type==larocv::ChunkType_t::kShower ? 1 : 0;
     auto masked_pts=larocv::MaskImage(img,ctor,0,false);
     pchunk.mean_pixel_dist = larocv::MeanDistanceToLine(masked_pts,pchunk.overallPCA);
     pchunk.sigma_pixel_dist = larocv::SigmaDistanceToLine(masked_pts,pchunk.overallPCA);
     pchunk.straight = IsStraight(pchunk,img);
       }
       //get the length, area, npixels
       track_v.emplace_back(std::move(pchunk));
     }
     return track_v;
   }
MergeEndNubs()
void larcv::PreProcessor::MergeEndNubs (cv::Mat & adc_img, cv::Mat & track_img, cv::Mat & shower_img)
Definition at line 525 of file PreProcessor.cxx.
References _end_nub_max_pixels, _min_track_pixels, EdgeConnected(), larcv::kUnknown, LARCV_INFO, MakePixelChunks(), and PrepareImage().
Referenced by PreProcess(), and ~PreProcessor().
{
     auto adc_img_t = PrepareImage(adc_img);
     auto track_img_t = PrepareImage(track_img);
     auto shower_img_t = PrepareImage(shower_img);
     auto adc_pchunk_v = MakePixelChunks(adc_img_t,larocv::ChunkType_t::kUnknown,false);
     auto track_pchunk_v = MakePixelChunks(track_img_t,larocv::ChunkType_t::kTrack,false);
     auto shower_pchunk_v = MakePixelChunks(shower_img_t,larocv::ChunkType_t::kShower,false);
     std::vector<size_t> cidx_v;
     for(size_t shower1_id=0;shower1_id<shower_pchunk_v.size();++shower1_id) {
       const auto& shower1 = shower_pchunk_v[shower1_id];
       for(size_t track1_id=0;track1_id<track_pchunk_v.size();++track1_id) {
         const auto& track1 = track_pchunk_v[track1_id];
         // Check if we're looking at a potential muon track, is it straight?
         if (!track1.straight)
           continue;
         // Typically mistag involves a good sized muon track with proton nub, ignore small tracks
         if (track1.npixel < _min_track_pixels)
           continue;
         // Are the shower and track connected? If not continue
         if (!EdgeConnected(shower1,track1))
           continue;
         // Check to be sure that the attached shower pixels is a small cluster
         if (shower1.npixel > _end_nub_max_pixels)
           continue;
         cidx_v.push_back(shower1_id);
       } // End loop over track clusters
     } // End loop over shower clusters
     LARCV_INFO() << "Found " << cidx_v.size() << " shower end nubs on track clusters" << std::endl;
     // Using these shower to mask the ADC image. Add them to the track image
     for(const auto& cidx : cidx_v) {
       const auto& shower_ctor = shower_pchunk_v[cidx].ctor;
       auto mask_adc = larocv::MaskImage(adc_img,shower_ctor,0,false);
       track_img += mask_adc;
       shower_img = larocv::MaskImage(shower_img,shower_ctor,0,true);
     }
   }
MergePixelByFraction()
void larcv::PreProcessor::MergePixelByFraction (cv::Mat & adc_img, cv::Mat & track_img, cv::Mat & shower_img)
determine track/shower fraction of ADC contours
Definition at line 356 of file PreProcessor.cxx.
References _allowed_edge_overlap, _allowed_merge_neighbor_dist, _min_shower_frac, _min_track_frac, GetClosestEdge(), larcv::kUnknown, LARCV_DEBUG, LARCV_INFO, MakePixelChunks(), and PrepareImage().
Referenced by PreProcess(), and ~PreProcessor().
{
     auto adc_img_t = PrepareImage(adc_img);
     auto track_img_t = PrepareImage(track_img);
     auto shower_img_t = PrepareImage(shower_img);
     auto adc_pchunk_v = MakePixelChunks(adc_img_t,larocv::ChunkType_t::kUnknown,true);
     auto track_pchunk_v = MakePixelChunks(track_img_t,larocv::ChunkType_t::kTrack,true);
     auto shower_pchunk_v = MakePixelChunks(shower_img_t,larocv::ChunkType_t::kShower,true);
     for(auto& adc_pchunk : adc_pchunk_v) {
       auto& adc_ctor = adc_pchunk.ctor;
       auto& track_frac = adc_pchunk.track_frac;
       auto& shower_frac = adc_pchunk.shower_frac;
       LARCV_DEBUG() << "ADC track @ " << &adc_pchunk << " contour size " << adc_ctor.size() << " w/ " << adc_pchunk.npixel << " pixels" << std::endl;
       LARCV_DEBUG() << "Edge 1 " << adc_pchunk.edge1 << " & Edge 2 " << adc_pchunk.edge2 << std::endl;
       const larocv::PixelChunk* track = nullptr;
       const larocv::PixelChunk* shower = nullptr;
       float largest_track_frac = std::numeric_limits<float>::min();
       float largest_shower_frac = std::numeric_limits<float>::min();
       bool track_at_edge=false;
       for(const auto& track_pchunk : track_pchunk_v) {
     auto frac = larocv::PixelFraction(adc_img_t,adc_ctor,track_pchunk.ctor);
     if (frac > largest_track_frac) {
       largest_track_frac = frac;
       track = &track_pchunk;
     }
     track_frac += frac;
     auto dist = GetClosestEdge(track_pchunk,adc_pchunk);
     if (dist<_allowed_edge_overlap) track_at_edge=true;
       }
       bool shower_at_edge=false;
       for(const auto& shower_pchunk : shower_pchunk_v) {
     auto frac = larocv::PixelFraction(adc_img_t,adc_ctor,shower_pchunk.ctor);
     if (frac > largest_shower_frac) {
       largest_shower_frac = frac;
       shower = &shower_pchunk;
     }
     shower_frac += frac;
     auto dist = GetClosestEdge(shower_pchunk,adc_pchunk);
     if (dist<_allowed_edge_overlap) shower_at_edge=true;
       }
       if (!track or !shower) continue;
       geo2d::Vector<float> ed1,ed2;
       auto dist = GetClosestEdge(*track,*shower,ed1,ed2);
       LARCV_DEBUG() << "Distance is " << dist << " and track @ edge " << track_at_edge << " & shower @ edge " << shower_at_edge << std::endl;
       if (dist < _allowed_merge_neighbor_dist or (track_at_edge and shower_at_edge))
     adc_pchunk.ignore=true;
     }
     // loop over the ADC contours, claim contours above threshold as track and shower
     for(auto& adc_pchunk : adc_pchunk_v) {
       if (adc_pchunk.ignore) continue;
       auto& adc_ctor = adc_pchunk.ctor;
       LARCV_DEBUG() << "Merging adc contour of size " << adc_pchunk.npixel << std::endl;
       auto& track_frac = adc_pchunk.track_frac;
       auto& shower_frac = adc_pchunk.shower_frac;
       LARCV_DEBUG() << "...with relative fractions (trk,shr)=("<<track_frac<<","<<shower_frac<<")"<<std::endl;
       if (track_frac > _min_track_frac) {
     LARCV_INFO() << "Claiming a mostly track ADC contour as track" << std::endl;
     auto mask_adc = larocv::MaskImage(adc_img,adc_ctor,0,false);
     auto mask_track = larocv::MaskImage(track_img,adc_ctor,0,true);
     track_img = mask_adc + mask_track;
     shower_img = larocv::MaskImage(shower_img,adc_ctor,0,true);
       }
       if (shower_frac > _min_shower_frac) {
     LARCV_INFO() << "Claiming a mostly shower ADC contour as shower" << std::endl;
     auto mask_adc = larocv::MaskImage(adc_img,adc_ctor,0,false);
     auto mask_shower = larocv::MaskImage(shower_img,adc_ctor,0,true);
     shower_img = mask_adc + mask_shower;
     track_img = larocv::MaskImage(track_img,adc_ctor,0,true);
       }
     }
   }
MergeStraightShowers()
void larcv::PreProcessor::MergeStraightShowers (cv::Mat & adc_img, cv::Mat & track_img, cv::Mat & shower_img)
Definition at line 454 of file PreProcessor.cxx.
References EdgeConnected(), larcv::kUnknown, LARCV_DEBUG, LARCV_INFO, MakePixelChunks(), OverallStraightCompatible(), and PrepareImage().
Referenced by PreProcess(), and ~PreProcessor().
{
     auto adc_img_t = PrepareImage(adc_img);
     auto track_img_t = PrepareImage(track_img);
     auto shower_img_t = PrepareImage(shower_img);
     auto adc_pchunk_v = MakePixelChunks(adc_img_t,larocv::ChunkType_t::kUnknown);
     auto track_pchunk_v = MakePixelChunks(track_img_t,larocv::ChunkType_t::kTrack);
     auto shower_pchunk_v = MakePixelChunks(shower_img_t,larocv::ChunkType_t::kShower);
     std::vector<size_t> cidx_v;
     for(size_t shower_id=0;shower_id<shower_pchunk_v.size();++shower_id) {
       const auto& shower = shower_pchunk_v[shower_id];
       for(size_t track1_id=0;track1_id<track_pchunk_v.size();++track1_id) {
     const auto& track1 = track_pchunk_v[track1_id];
     //Determine the straightness of this track and this shower
     if (track1.straight and shower.straight) {
       LARCV_DEBUG() << "Straight shower and straight track identified" << std::endl;
       if (OverallStraightCompatible(shower,track1)) {
         cidx_v.push_back(shower_id);
         continue;
       }
     }
     // are they connected by edge, if not move on
     if (!EdgeConnected(shower,track1))
       continue;
     // Find "sandwich" showers -- showers between two tracks
     for(size_t track2_id=track1_id+1;track2_id<track_pchunk_v.size();++track2_id) {
       const auto& track2 = track_pchunk_v[track2_id];
       // are they connected by edge, if not move on
       if (!EdgeConnected(shower,track2))
         continue;
       LARCV_DEBUG() << "Shower " << shower_id
             << " sandwich btw"
             << " track " << track1_id
             << " & track " << track2_id
             << std::endl;
       LARCV_DEBUG() << "This shower of size " << shower.npixel
             << " e1 " << shower.edge1 << " e2 " << shower.edge2
             << "mean dist " << shower.mean_pixel_dist << std::endl;
       LARCV_DEBUG() << "Straight " << shower.straight << std::endl;
       if (shower.straight)
         cidx_v.push_back(shower_id);
     } // end track2
       } // end track1
     } // end this shower
     LARCV_INFO() << "Found " << cidx_v.size() << " compatible tracks and showers" << std::endl;
     //lets use the shower to mask the ADC image, and append to the track image
     for(const auto& cidx : cidx_v) {
       const auto& shower_ctor = shower_pchunk_v[cidx].ctor;
       auto mask_adc = larocv::MaskImage(adc_img,shower_ctor,0,false);
       track_img += mask_adc;
       shower_img = larocv::MaskImage(shower_img,shower_ctor,0,true);
     }
   }
MergeTracklets()
void larcv::PreProcessor::MergeTracklets (cv::Mat & track_img, cv::Mat & shower_img)
Definition at line 297 of file PreProcessor.cxx.
References _min_merge_track_shower_dist, _min_merge_track_size, LARCV_DEBUG, MakePixelChunks(), and PrepareImage().
Referenced by PreProcess(), and ~PreProcessor().
{
     auto track_img_t = PrepareImage(track_img);
     auto shower_img_t = PrepareImage(shower_img);
     auto track_pchunk_v = MakePixelChunks(track_img_t,larocv::ChunkType_t::kTrack,false);
     auto shower_pchunk_v = MakePixelChunks(shower_img_t,larocv::ChunkType_t::kShower,false);
     LARCV_DEBUG() << "Track chunks " << track_pchunk_v.size()
           << " & Shower chunks " << shower_pchunk_v.size() << std::endl;
     for(auto& track : track_pchunk_v) {
       LARCV_DEBUG() << "npixel ... " << track.npixel << std::endl;
       if (track.npixel > _min_merge_track_size) continue;
       for(auto& shower : shower_pchunk_v) {
     auto dist=larocv::Pt2PtDistance(track.ctor,shower.ctor);
     LARCV_DEBUG() << "shower npix " << shower.npixel << " @ dist " << dist << std::endl;
     if ( dist > _min_merge_track_shower_dist) continue;
     LARCV_DEBUG() << "masking!" << std::endl;
     uint tol=0;
     if (track.npixel<4) tol=1;
     auto mask_shower = larocv::MaskImage(track_img,track.ctor,tol,false);
     track_img = larocv::MaskImage(track_img,track.ctor,tol,true);
     shower_img = shower_img + mask_shower;
       }
     }
   }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
OverallStraightCompatible()
bool larcv::PreProcessor::OverallStraightCompatible (const larocv::PixelChunk & pchunk1, const larocv::PixelChunk & pchunk2) private
Definition at line 445 of file PreProcessor.cxx.
References _min_overall_angle.
Referenced by MergeStraightShowers(), and ~PreProcessor().
{
     auto angle = std::abs(geo2d::angle(pchunk1.overallPCA,pchunk2.overallPCA));
     if ((angle < _min_overall_angle) or (angle > 180 - _min_overall_angle))
       return true;
     return false;
   }
PrepareImage()
cv::Mat larcv::PreProcessor::PrepareImage (const cv::Mat & img) private
Definition at line 257 of file PreProcessor.cxx.
References _blur, _pi_threshold, larcv::msg::kDEBUG, and larcv::larcv_base::logger().
Referenced by ClaimShowers(), MergeEndNubs(), MergePixelByFraction(), MergeStraightShowers(), MergeTracklets(), and ~PreProcessor().
{
     // Copy input
     cv::Mat img_t = img.clone();
     if(this->logger().level() == msg::kDEBUG) {
       static uint call0=0;
       std::stringstream ss;
       ss << "img_" << call0 << ".png";
       cv::imwrite(ss.str(),img_t);
       call0+=1;
     }
     // Blur
     if (_blur) {
       cv::blur(img_t,img_t,::cv::Size(_blur,_blur) );
       if(this->logger().level() == msg::kDEBUG) {
     static uint call1=0;
     std::stringstream ss;
     ss << "img_t0_" << call1 << ".png";
     cv::imwrite(ss.str(),img_t);
     call1+=1;
       }
     }
     // Threshold
     img_t = larocv::Threshold(img_t,_pi_threshold,255);
     if(this->logger().level() == msg::kDEBUG) {
       static uint call2=0;
       std::stringstream ss;
       ss << "img_t1_" << call2 << ".png";
       cv::imwrite(ss.str(),img_t);
       call2+=1;
     }
     return img_t;
   }
PreProcess()
bool larcv::PreProcessor::PreProcess (cv::Mat & adc_img, cv::Mat & track_img, cv::Mat & shower_img)
Definition at line 577 of file PreProcessor.cxx.
References _claim_showers, _merge_end_nubs, _merge_pixel_frac, _merge_straight_showers, _merge_tracklets, ClaimShowers(), LARCV_DEBUG, MergeEndNubs(), MergePixelByFraction(), MergeStraightShowers(), and MergeTracklets().
Referenced by larcv::PreProcessorAna::process(), larcv::LArbysImage::Reconstruct(), and ~PreProcessor().
   {
     LARCV_DEBUG() << "start" << std::endl;
     LARCV_DEBUG() << "Merging tracklets" << std::endl;
     if (_merge_tracklets) MergeTracklets(track_img,shower_img);
     else LARCV_DEBUG() << "... not" << std::endl;
     LARCV_DEBUG() << "Cleaning up showers first" << std::endl;
     if (_claim_showers) ClaimShowers(adc_img,track_img,shower_img);
     else LARCV_DEBUG() << "... not" << std::endl;
     LARCV_DEBUG() << "Merge via pixel frac" << std::endl;
     if (_merge_pixel_frac) MergePixelByFraction(adc_img,track_img,shower_img);
     else LARCV_DEBUG() << "... not" << std::endl;
     LARCV_DEBUG() << "Merging straight showers to track" << std::endl;
     if(_merge_straight_showers) MergeStraightShowers(adc_img,track_img,shower_img);
     else LARCV_DEBUG() << "... not" << std::endl;
     LARCV_DEBUG() << "Merging end nubs to track" << std::endl;
     if(_merge_end_nubs) MergeEndNubs(adc_img,track_img,shower_img);
     else LARCV_DEBUG() << "... not" << std::endl;
     // Lets make sure the track and shower images do not gain
     // extra pixel value from masking
     adc_img.copyTo(track_img,larocv::Threshold(track_img,1,1));
     adc_img.copyTo(shower_img,larocv::Threshold(shower_img,1,1));
     LARCV_DEBUG() << "end" << std::endl;
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_allowed_edge_overlap
double larcv::PreProcessor::_allowed_edge_overlap private
Definition at line 107 of file PreProcessor.h.
Referenced by MergePixelByFraction(), and PreProcessor().
_allowed_merge_neighbor_dist
double larcv::PreProcessor::_allowed_merge_neighbor_dist private
Definition at line 106 of file PreProcessor.h.
Referenced by MergePixelByFraction(), and PreProcessor().
_allowed_neighbor_dist
float larcv::PreProcessor::_allowed_neighbor_dist private
Definition at line 91 of file PreProcessor.h.
Referenced by Configure(), EdgeConnected(), and PreProcessor().
_blur
uint larcv::PreProcessor::_blur private
Definition at line 90 of file PreProcessor.h.
Referenced by Configure(), PrepareImage(), and PreProcessor().
_claim_showers
bool larcv::PreProcessor::_claim_showers private
Definition at line 98 of file PreProcessor.h.
Referenced by Configure(), PreProcess(), and PreProcessor().
_end_nub_max_pixels
uint larcv::PreProcessor::_end_nub_max_pixels private
Definition at line 109 of file PreProcessor.h.
Referenced by Configure(), MergeEndNubs(), and PreProcessor().
_max_track_in_shower_frac
float larcv::PreProcessor::_max_track_in_shower_frac private
Definition at line 101 of file PreProcessor.h.
Referenced by ClaimShowers(), and PreProcessor().
_mean_distance_pca
double larcv::PreProcessor::_mean_distance_pca private
Definition at line 102 of file PreProcessor.h.
Referenced by IsStraight(), and PreProcessor().
_merge_end_nubs
bool larcv::PreProcessor::_merge_end_nubs private
Definition at line 108 of file PreProcessor.h.
Referenced by Configure(), PreProcess(), and PreProcessor().
_merge_pixel_frac
bool larcv::PreProcessor::_merge_pixel_frac private
Definition at line 97 of file PreProcessor.h.
Referenced by Configure(), PreProcess(), and PreProcessor().
_merge_straight_showers
bool larcv::PreProcessor::_merge_straight_showers private
Definition at line 104 of file PreProcessor.h.
Referenced by Configure(), PreProcess(), and PreProcessor().
_merge_tracklets
bool larcv::PreProcessor::_merge_tracklets private
Definition at line 96 of file PreProcessor.h.
Referenced by Configure(), PreProcess(), and PreProcessor().
_min_ctor_size
uint larcv::PreProcessor::_min_ctor_size private
Definition at line 89 of file PreProcessor.h.
Referenced by Configure(), FilterContours(), and PreProcessor().
_min_merge_track_shower_dist
uint larcv::PreProcessor::_min_merge_track_shower_dist private
Definition at line 105 of file PreProcessor.h.
Referenced by Configure(), MergeTracklets(), and PreProcessor().
_min_merge_track_size
uint larcv::PreProcessor::_min_merge_track_size private
Definition at line 103 of file PreProcessor.h.
Referenced by Configure(), MergeTracklets(), and PreProcessor().
_min_overall_angle
float larcv::PreProcessor::_min_overall_angle private
Definition at line 93 of file PreProcessor.h.
Referenced by Configure(), OverallStraightCompatible(), and PreProcessor().
_min_pca_angle
float larcv::PreProcessor::_min_pca_angle private
Definition at line 94 of file PreProcessor.h.
Referenced by IsStraight(), and PreProcessor().
_min_shower_frac
float larcv::PreProcessor::_min_shower_frac private
Definition at line 100 of file PreProcessor.h.
Referenced by MergePixelByFraction(), and PreProcessor().
_min_track_frac
float larcv::PreProcessor::_min_track_frac private
Definition at line 99 of file PreProcessor.h.
Referenced by MergePixelByFraction(), and PreProcessor().
_min_track_pixels
uint larcv::PreProcessor::_min_track_pixels private
Definition at line 110 of file PreProcessor.h.
Referenced by Configure(), MergeEndNubs(), and PreProcessor().
_min_track_size
float larcv::PreProcessor::_min_track_size private
Definition at line 95 of file PreProcessor.h.
_pca_box_size
uint larcv::PreProcessor::_pca_box_size private
Definition at line 92 of file PreProcessor.h.
Referenced by Configure(), MakePixelChunks(), and PreProcessor().
_pi_threshold
uint larcv::PreProcessor::_pi_threshold private
Definition at line 88 of file PreProcessor.h.
Referenced by Configure(), PrepareImage(), and PreProcessor().
The documentation for this class was generated from the following files:
PreProcessor.h
PreProcessor.cxx