LArCV: larcv::Lattice Class Reference
larcv::Lattice Class Reference
#include <AStar3DAlgo.h>
Public Member Functions
Lattice (const std::vector< float > &origin, const std::vector< int > &widths, const std::vector< float > &pixel_lengths, const std::vector< const larcv::ImageMeta * > &meta_v)
virtual ~Lattice ()
A3DPixPos_t getNodePos (const std::vector< float > &pos)
std::vector< float > getPos (const int u, const int v, const int w)
std::vector< float > getPos (const A3DPixPos_t &)
AStar3DNode * getNode (const std::vector< float > &pos)
AStar3DNode * getNode (const int u, const int v, const int w)
AStar3DNode * getNode (const A3DPixPos_t &nodeid)
void getImageCoordinates (const A3DPixPos_t &nodeid, int &row, std::vector< int > &cols, bool &within_image)
const std::vector< int > & widths () const
const std::vector< float > & origin () const
const std::vector< float > & pixel_len () const
void setStartNodeWithPadding (AStar3DNode *start, const std::vector< int > &start_padding)
Public Attributes
K keys
STL member.
T elements
STL member.
Protected Member Functions
void cleanup ()
Protected Attributes
std::vector< float > m_origin
std::vector< int > m_widths
std::vector< float > m_cm_per_pixel
std::vector< const larcv::ImageMeta *> m_meta_v
AStar3DNode * m_start_node
A3DPixPos_t m_start_nodeid
std::vector< int > m_start_padding
bool fCheckStartPadding
Detailed Description
Definition at line 154 of file AStar3DAlgo.h.
Constructor & Destructor Documentation
Lattice()
larcv::Lattice::Lattice (const std::vector< float > & origin, const std::vector< int > & widths, const std::vector< float > & pixel_lengths, const std::vector< const larcv::ImageMeta * > & meta_v) inline
Definition at line 156 of file AStar3DAlgo.h.
{
       m_origin = origin;
       m_widths = widths;
       m_cm_per_pixel = pixel_lengths;
       m_meta_v = meta_v;
     }
~Lattice()
virtual larcv::Lattice::~Lattice () inline virtual
Definition at line 163 of file AStar3DAlgo.h.
 { cleanup(); };
Member Function Documentation
cleanup()
void larcv::Lattice::cleanup () protected
Definition at line 971 of file AStar3DAlgo.cxx.
{
     //if ( verbose>0 )
     //std::cout << "Lattice::cleanup";
     for ( auto &it : *this ) {
       delete it.second;
       it.second = nullptr;
     }
     //if ( verbose>0 )
     //std::cout << "... done." << std::endl;
     clear();
   }
getImageCoordinates()
void larcv::Lattice::getImageCoordinates (const A3DPixPos_t & nodeid, int & row, std::vector< int > & cols, bool & within_image)
Definition at line 943 of file AStar3DAlgo.cxx.
{
     // turn this lattice point into a position in the images
     row = 0;
     cols.resize(3,0);
     std::vector<float> tyz = getPos( nodeid );
     if ( tyz[0]<=m_meta_v.front()->min_y() || tyz[0]>=m_meta_v.front()->max_y() ) {
       within_image = false;
       return;
     }
     std::vector<float> wid(3,0);
     cols.resize(3,0);
     within_image = true;
     for ( int p=0; p<3; p++ ) {
       Double_t xyz[3] { (tyz[0]-3200)*0.5*::larutil::LArProperties::GetME()->DriftVelocity(), tyz[1], tyz[2] }; // (x doesn't matter really)
       wid[p] = larutil::Geometry::GetME()->WireCoordinate( xyz, p );
       if ( wid[p]<=m_meta_v.at(p)->min_x() || wid[p]>=m_meta_v.at(p)->max_x() ) {
         within_image = false;
         return;
       }
       cols[p] = m_meta_v.at(p)->col(wid[p]);
     }
     row = m_meta_v.front()->row(tyz[0]);
     return;
   }
getNode() [1/3]
AStar3DNode * larcv::Lattice::getNode (const std::vector< float > & pos)
Definition at line 925 of file AStar3DAlgo.cxx.
Referenced by larcv::AStar3DAlgoProton::evaluteLatticePoint(), larcv::AStar3DAlgo::evaluteLatticePoint(), larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
{
     return getNode( getNodePos(pos) );
   }
getNode() [2/3]
AStar3DNode * larcv::Lattice::getNode (const int u, const int v, const int w)
Definition at line 905 of file AStar3DAlgo.cxx.
{
     // check for node in the map
     A3DPixPos_t nodeid(u,v,w);
     return getNode( nodeid );
   }
getNode() [3/3]
AStar3DNode * larcv::Lattice::getNode (const A3DPixPos_t & nodeid)
Definition at line 875 of file AStar3DAlgo.cxx.
References larcv::AStar3DNode::cols, larcv::AStar3DNode::row, and larcv::AStar3DNode::within_image.
{
     // check bounds
     for (int i=0; i<3; i++) {
       if ( nodeid[i]<0 || nodeid[i]>=m_widths[i]) return nullptr;
     }
     // search map
     auto it_node = find( nodeid );
     AStar3DNode* node = nullptr;
     if ( it_node==end() ) {
       // [[ create a node ]]
       // get the detector coordinates (tick, y, z)
       std::vector<float> tyz = getPos( nodeid );
       // create the node
       node = new AStar3DNode( nodeid[0], nodeid[1], nodeid[2], tyz );
       // get the image coordinates
       getImageCoordinates( nodeid, node->row, node->cols, node->within_image );
       // put it into the map
       insert( a3dpos_pair_t(nodeid,node) );
     }
     else {
       node = (*it_node).second;
     }
     return node;
   }
getNodePos()
A3DPixPos_t larcv::Lattice::getNodePos (const std::vector< float > & pos)
Definition at line 914 of file AStar3DAlgo.cxx.
Referenced by larcv::AStar3DAlgoProton::findpath(), and larcv::AStar3DAlgo::findpath().
{
     A3DPixPos_t nodeid(0,0,0);
     for (int i=0; i<3; i++) {
       nodeid[i] = (int) (( pos[i]-m_origin[i])/m_cm_per_pixel[i]);
       if ( nodeid[i]<0 || nodeid[i]>=m_widths[i])
         return A3DPixPos_t(); // outside lattice, so send and empty one
     }
     return nodeid;
   }
getPos() [1/2]
std::vector< float > larcv::Lattice::getPos (const int u, const int v, const int w)
Definition at line 929 of file AStar3DAlgo.cxx.
{
     A3DPixPos_t nodeid( u, v, w );
     return getPos( nodeid );
   }
getPos() [2/2]
std::vector< float > larcv::Lattice::getPos (const A3DPixPos_t & nodeid)
Definition at line 934 of file AStar3DAlgo.cxx.
{
     std::vector<float> pos(3,0.0);
     for (int i=0; i<3; i++) {
       // check if within lattice?
       pos[i] = m_origin[i] + nodeid[i]*m_cm_per_pixel[i];
     }
     return pos;
   }
origin()
const std::vector<float>& larcv::Lattice::origin () const inline
Definition at line 174 of file AStar3DAlgo.h.
 { return m_origin; }
pixel_len()
const std::vector<float>& larcv::Lattice::pixel_len () const inline
Definition at line 175 of file AStar3DAlgo.h.
 { return m_cm_per_pixel; }
setStartNodeWithPadding()
void larcv::Lattice::setStartNodeWithPadding (AStar3DNode * start, const std::vector< int > & start_padding)
widths()
const std::vector<int>& larcv::Lattice::widths () const inline
Definition at line 173 of file AStar3DAlgo.h.
Referenced by larcv::AStar3DAlgoProton::evaluateNeighborNodes(), and larcv::AStar3DAlgo::evaluateNeighborNodes().
 { return m_widths; }
Member Data Documentation
elements
T std::map< K, T >::elements inherited
STL member.
fCheckStartPadding
bool larcv::Lattice::fCheckStartPadding protected
Definition at line 190 of file AStar3DAlgo.h.
keys
K std::map< K, T >::keys inherited
STL member.
m_cm_per_pixel
std::vector<float> larcv::Lattice::m_cm_per_pixel protected
Definition at line 183 of file AStar3DAlgo.h.
m_meta_v
std::vector< const larcv::ImageMeta* > larcv::Lattice::m_meta_v protected
Definition at line 184 of file AStar3DAlgo.h.
m_origin
std::vector<float> larcv::Lattice::m_origin protected
Definition at line 181 of file AStar3DAlgo.h.
m_start_node
AStar3DNode* larcv::Lattice::m_start_node protected
Definition at line 187 of file AStar3DAlgo.h.
m_start_nodeid
A3DPixPos_t larcv::Lattice::m_start_nodeid protected
Definition at line 188 of file AStar3DAlgo.h.
m_start_padding
std::vector<int> larcv::Lattice::m_start_padding protected
Definition at line 189 of file AStar3DAlgo.h.
m_widths
std::vector<int> larcv::Lattice::m_widths protected
Definition at line 182 of file AStar3DAlgo.h.
The documentation for this class was generated from the following files:
AStar3DAlgo.h
AStar3DAlgo.cxx