LArCV: larcv::SegImageAnaProcessFactory Class Reference
larcv::SegImageAnaProcessFactory Class Reference
#include <SegImageAna.h>
Public Member Functions
SegImageAnaProcessFactory ()
ctor
~SegImageAnaProcessFactory ()
dtor
ProcessBase * create (const std::string instance_name)
creation method
Detailed Description
Definition at line 75 of file SegImageAna.h.
Constructor & Destructor Documentation
SegImageAnaProcessFactory()
larcv::SegImageAnaProcessFactory::SegImageAnaProcessFactory () inline
ctor
Definition at line 78 of file SegImageAna.h.
References larcv::ProcessFactory::add_factory(), and larcv::ProcessFactory::get().
 { ProcessFactory::get().add_factory("SegImageAna", this); }
~SegImageAnaProcessFactory()
larcv::SegImageAnaProcessFactory::~SegImageAnaProcessFactory () inline
dtor
Definition at line 80 of file SegImageAna.h.
 {}
Member Function Documentation
create()
ProcessBase* larcv::SegImageAnaProcessFactory::create (const std::string instance_name) inline virtual
creation method
Implements larcv::ProcessFactoryBase.
Definition at line 82 of file SegImageAna.h.
References larcv::SegImageAna::SegImageAna().
 { return new SegImageAna(instance_name); }
The documentation for this class was generated from the following file:
SegImageAna.h