LArCV: larcv::DeadWireAna Class Reference
larcv::DeadWireAna Class Reference
#include <DeadWireAna.h>
Public Member Functions
DeadWireAna (const std::string name="DeadWireAna")
~DeadWireAna ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
TTree * _tree
int _run
int _subrun
int _event
int _entry
float _x
float _y
float _z
float _sx
float _sy
float _sz
int _vertex_in_dead_plane0
int _vertex_in_dead_plane1
int _vertex_in_dead_plane2
int _vertex_in_dead
int _vertex_near_dead_plane0
int _vertex_near_dead_plane1
int _vertex_near_dead_plane2
int _vertex_near_dead
int _nearest_wire_error
std::string _ev_img2d_prod
std::string _seg_roi_prod
float _d_dead
larutil::SpaceChargeMicroBooNE _sce
Detailed Description
Definition at line 11 of file DeadWireAna.h.
Constructor & Destructor Documentation
DeadWireAna()
larcv::DeadWireAna::DeadWireAna (const std::string name = "DeadWireAna")
Definition at line 14 of file DeadWireAna.cxx.
Referenced by larcv::DeadWireAnaProcessFactory::create().
     : ProcessBase(name),
       _tree(nullptr)
   {}
~DeadWireAna()
larcv::DeadWireAna::~DeadWireAna () inline
Definition at line 15 of file DeadWireAna.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::DeadWireAna::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 19 of file DeadWireAna.cxx.
References _d_dead, _ev_img2d_prod, _seg_roi_prod, and larcv::PSet::get().
Referenced by ~DeadWireAna().
   {
     _ev_img2d_prod  = cfg.get<std::string>("DeadWireImageProducer");
     _seg_roi_prod   = cfg.get<std::string>("SegmentROIProducer");
     _d_dead         = cfg.get<float>("DistanceToDead");
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::DeadWireAna::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 188 of file DeadWireAna.cxx.
References _tree, and larcv::ProcessBase::has_ana_file().
Referenced by ~DeadWireAna().
   {
     if(has_ana_file()) {
       _tree->Write();
     }
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DeadWireAna::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 26 of file DeadWireAna.cxx.
References _d_dead, _entry, _event, _nearest_wire_error, _run, _subrun, _sx, _sy, _sz, _tree, _vertex_in_dead, _vertex_in_dead_plane0, _vertex_in_dead_plane1, _vertex_in_dead_plane2, _vertex_near_dead, _vertex_near_dead_plane0, _vertex_near_dead_plane1, _vertex_near_dead_plane2, _x, _y, and _z.
Referenced by ~DeadWireAna().
   {
     _tree = new TTree("EventDeadWireTree","");
     _tree->Branch("run"    , &_run    , "run/I");
     _tree->Branch("subrun" , &_subrun , "subrun/I");
     _tree->Branch("event"  , &_event  , "event/I");
     _tree->Branch("entry"  , &_entry  , "entry/I");
     _tree->Branch("x",&_x,"x/F");
     _tree->Branch("y",&_y,"y/F");
     _tree->Branch("z",&_z,"z/F");
     _tree->Branch("sx",&_sx,"sx/F");
     _tree->Branch("sy",&_sy,"sy/F");
     _tree->Branch("sz",&_sz,"sz/F");
     _tree->Branch("vertex_in_dead_plane0", &_vertex_in_dead_plane0, "vertex_in_dead_plane0/I");
     _tree->Branch("vertex_in_dead_plane1", &_vertex_in_dead_plane1, "vertex_in_dead_plane1/I");
     _tree->Branch("vertex_in_dead_plane2", &_vertex_in_dead_plane2, "vertex_in_dead_plane2/I");
     _tree->Branch("vertex_in_dead", &_vertex_in_dead, "vertex_in_dead/I");
     _tree->Branch("vertex_near_dead_plane0", &_vertex_near_dead_plane0, "vertex_near_dead_plane0/I");
     _tree->Branch("vertex_near_dead_plane1", &_vertex_near_dead_plane1, "vertex_near_dead_plane1/I");
     _tree->Branch("vertex_near_dead_plane2", &_vertex_near_dead_plane2, "vertex_near_dead_plane2/I");
     _tree->Branch("vertex_near_dead", &_vertex_near_dead, "vertex_near_dead/I");
     _tree->Branch("nearest_wire_error", &_nearest_wire_error, "_nearest_wire_error/I");
     _tree->Branch("d_dead", &_d_dead, "d_dead/F");
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DeadWireAna::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 59 of file DeadWireAna.cxx.
References _d_dead, _entry, _ev_img2d_prod, _event, _nearest_wire_error, _run, _sce, _seg_roi_prod, _subrun, _sx, _sy, _sz, _tree, _vertex_in_dead, _vertex_in_dead_plane0, _vertex_in_dead_plane1, _vertex_in_dead_plane2, _vertex_near_dead, _vertex_near_dead_plane0, _vertex_near_dead_plane1, _vertex_near_dead_plane2, _x, _y, _z, larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::kINVALID_FLOAT, larcv::kINVALID_INT, larcv::kProductImage2D, larcv::kProductROI, LARCV_CRITICAL, and LARCV_DEBUG.
Referenced by ~DeadWireAna().
   {
     auto dead_img = (EventImage2D*) mgr.get_data(kProductImage2D,_ev_img2d_prod);
     if (dead_img->Image2DArray().size() != 3) throw larbys("Dead wire image does not have 3 planes");
     auto seg_roi  = (EventROI*) mgr.get_data(kProductROI,_seg_roi_prod);
     _run    = (int) seg_roi->run();
     _subrun = (int) seg_roi->subrun();
     _event  = (int) seg_roi->event();
     _entry  = (int) mgr.current_entry();
     const auto& nu_roi = seg_roi->ROIArray().front();
     LARCV_DEBUG() << "PDG: " << nu_roi.PdgCode() << std::endl;
     auto tx = nu_roi.X();
     auto ty = nu_roi.Y();
     auto tz = nu_roi.Z();
     auto tt = nu_roi.T();
     auto const offset = _sce.GetPosOffsets(tx,ty,tz);
     auto scex = tx - offset[0] + 0.7;
     auto scey = ty + offset[1];
     auto scez = tz + offset[2];
     _x = tx;
     _y = ty;
     _z = tz;
     _sx = scex;
     _sy = scey;
     _sz = scez;
     LARCV_DEBUG() << "(x,y,z,t)==>sce(x,y,z,t) : ("<<tx<<","<<ty<<","<<tz<<","<<tt<<")==>("<<scex<<","<<scey<<","<<scez<<","<<tt<<")"<<std::endl;
     auto geo  = larutil::Geometry::GetME();
     auto larp = larutil::LArProperties::GetME();
     double xyz[3];
     double wire_v[3];
     const double tick = (scex / larp->DriftVelocity() + 4) * 2. + 3200.;
     xyz[0] = scex;
     xyz[1] = scey;
     xyz[2] = scez;
     _nearest_wire_error = 0;
     try {
       wire_v[0] = geo->NearestWire(xyz,0);
       wire_v[1] = geo->NearestWire(xyz,1);
       wire_v[2] = geo->NearestWire(xyz,2);
     } catch(const std::exception& e) {
       _tree->Fill();
       LARCV_CRITICAL() << "Could not find nearest wire" << std::endl;
       _nearest_wire_error=1;
       return true;
     }
     _vertex_in_dead = 0;
     _vertex_near_dead = 0;
     for(size_t plane=0; plane<3; ++plane) {
       LARCV_DEBUG() << "@plane="<<plane<<std::endl;
       const auto& img = dead_img->Image2DArray().at(plane);
       const auto& bb  = img.meta();
       auto const& wire = wire_v[plane];
       float xpixel = kINVALID_FLOAT;
       float ypixel = kINVALID_FLOAT;
       if( bb.min_x() <= wire && wire <= bb.max_x() &&
       bb.min_y() <= tick && tick <= bb.max_y() ) {
     xpixel = wire - bb.min_x();
     ypixel = (tick - bb.min_y()) / 6.0;
     LARCV_DEBUG() << "Set (xpixel,ypixel)=("<<xpixel<<","<<ypixel<<")"<<std::endl;
       } else {
     throw larbys("Vertex outside image");
       }
       int in_dead = 0;
       int near_dead = 0;
       if (img.pixel((int)ypixel,(int)xpixel) == 0.0) in_dead = 1;
       int col_min = kINVALID_INT;
       int col_max = kINVALID_INT;
       col_min = xpixel - _d_dead;
       col_max = xpixel + _d_dead;
       if (col_max >= bb.cols()) col_max = bb.cols() - 1;
       if (col_min <= 0        ) col_min = 0;
       for(int col = col_min; col <= col_max; ++col) {
     if (img.pixel(ypixel,col) == 0.0)  {
       near_dead = 1;
     }
       }
       if (plane==0) {
     _vertex_in_dead_plane0   = in_dead;
     _vertex_near_dead_plane0 = near_dead;
       }
       if (plane==1) {
     _vertex_in_dead_plane1   = in_dead;
     _vertex_near_dead_plane1 = near_dead;
       }
       if (plane==2) {
     _vertex_in_dead_plane2   = in_dead;
     _vertex_near_dead_plane2 = near_dead;
       }
       _vertex_in_dead   += (int)in_dead;
       _vertex_near_dead += (int)near_dead;
     } // end plane
     _vertex_in_dead   = _vertex_in_dead > 1 ? 1 : 0;
     _vertex_near_dead = _vertex_near_dead > 1 ? 1 : 0;
     _tree->Fill();
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_d_dead
float larcv::DeadWireAna::_d_dead private
Definition at line 53 of file DeadWireAna.h.
Referenced by configure(), initialize(), and process().
_entry
int larcv::DeadWireAna::_entry private
Definition at line 29 of file DeadWireAna.h.
Referenced by initialize(), and process().
_ev_img2d_prod
std::string larcv::DeadWireAna::_ev_img2d_prod private
Definition at line 51 of file DeadWireAna.h.
Referenced by configure(), and process().
_event
int larcv::DeadWireAna::_event private
Definition at line 28 of file DeadWireAna.h.
Referenced by initialize(), and process().
_nearest_wire_error
int larcv::DeadWireAna::_nearest_wire_error private
Definition at line 49 of file DeadWireAna.h.
Referenced by initialize(), and process().
_run
int larcv::DeadWireAna::_run private
Definition at line 26 of file DeadWireAna.h.
Referenced by initialize(), and process().
_sce
larutil::SpaceChargeMicroBooNE larcv::DeadWireAna::_sce private
Definition at line 55 of file DeadWireAna.h.
Referenced by process().
_seg_roi_prod
std::string larcv::DeadWireAna::_seg_roi_prod private
Definition at line 52 of file DeadWireAna.h.
Referenced by configure(), and process().
_subrun
int larcv::DeadWireAna::_subrun private
Definition at line 27 of file DeadWireAna.h.
Referenced by initialize(), and process().
_sx
float larcv::DeadWireAna::_sx private
Definition at line 35 of file DeadWireAna.h.
Referenced by initialize(), and process().
_sy
float larcv::DeadWireAna::_sy private
Definition at line 36 of file DeadWireAna.h.
Referenced by initialize(), and process().
_sz
float larcv::DeadWireAna::_sz private
Definition at line 37 of file DeadWireAna.h.
Referenced by initialize(), and process().
_tree
TTree* larcv::DeadWireAna::_tree private
Definition at line 24 of file DeadWireAna.h.
Referenced by finalize(), initialize(), and process().
_vertex_in_dead
int larcv::DeadWireAna::_vertex_in_dead private
Definition at line 42 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_in_dead_plane0
int larcv::DeadWireAna::_vertex_in_dead_plane0 private
Definition at line 39 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_in_dead_plane1
int larcv::DeadWireAna::_vertex_in_dead_plane1 private
Definition at line 40 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_in_dead_plane2
int larcv::DeadWireAna::_vertex_in_dead_plane2 private
Definition at line 41 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_near_dead
int larcv::DeadWireAna::_vertex_near_dead private
Definition at line 47 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_near_dead_plane0
int larcv::DeadWireAna::_vertex_near_dead_plane0 private
Definition at line 44 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_near_dead_plane1
int larcv::DeadWireAna::_vertex_near_dead_plane1 private
Definition at line 45 of file DeadWireAna.h.
Referenced by initialize(), and process().
_vertex_near_dead_plane2
int larcv::DeadWireAna::_vertex_near_dead_plane2 private
Definition at line 46 of file DeadWireAna.h.
Referenced by initialize(), and process().
_x
float larcv::DeadWireAna::_x private
Definition at line 31 of file DeadWireAna.h.
Referenced by initialize(), and process().
_y
float larcv::DeadWireAna::_y private
Definition at line 32 of file DeadWireAna.h.
Referenced by initialize(), and process().
_z
float larcv::DeadWireAna::_z private
Definition at line 33 of file DeadWireAna.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
DeadWireAna.h
DeadWireAna.cxx