LArCV: larcv::DataStream Class Reference
larcv::DataStream Class Reference
#include <DataStream.h>
Public Member Functions
DataStream (const std::string name="DataStream")
Default constructor.
~DataStream ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void move_pmt_image (Image2D &)
void move_tpc_image (std::vector< larcv::Image2D > &)
void move_tpc_segment (std::vector< larcv::Image2D > &)
void move_ch_status (std::map< larcv::PlaneID_t, larcv::ChStatus > &)
void move_roi (std::vector< larcv::ROI > &)
void retrieve_id (const EventBase *data)
size_t run () const
size_t subrun () const
size_t event () const
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
size_t _run
size_t _subrun
size_t _event
std::vector< larcv::Image2D > _tpc_image_v
std::vector< larcv::Image2D > _tpc_segment_v
Image2D _pmt_image
std::map< ::larcv::PlaneID_t, larcv::ChStatus > _ch_status_m
std::vector< larcv::ROI > _roi_v
Private Attributes
std::string _tpc_image_producer
std::string _pmt_image_producer
std::string _ch_status_producer
std::string _roi_producer
std::string _segment_producer
Detailed Description
Definition at line 26 of file DataStream.h.
Constructor & Destructor Documentation
DataStream()
larcv::DataStream::DataStream (const std::string name = "DataStream")
Default constructor.
Definition at line 13 of file DataStream.cxx.
Referenced by larcv::DataStreamProcessFactory::create().
     : ImageHolder(name)
   {}
~DataStream()
larcv::DataStream::~DataStream () inline
Default destructor.
Definition at line 34 of file DataStream.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::DataStream::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 17 of file DataStream.cxx.
References _ch_status_producer, _pmt_image_producer, _roi_producer, _segment_producer, _tpc_image_producer, larcv::PSet::get(), and LARCV_INFO.
Referenced by ~DataStream().
   {
     _tpc_image_producer = cfg.get<std::string>("TPCImageProducer");
     _pmt_image_producer = cfg.get<std::string>("PMTImageProducer");
     _ch_status_producer = cfg.get<std::string>("ChStatusProducer","");
     _roi_producer = cfg.get<std::string>("ROIProducer");
     _segment_producer = cfg.get<std::string>("SegmentImageProducer","");
     LARCV_INFO() << "Configured" << std::endl;
   }
event()
size_t larcv::ImageHolder::event () const inline inherited
Definition at line 50 of file ImageHolder.h.
References larcv::ImageHolder::_event.
Referenced by larcv::ImageMerger::process().
 { return _event;  }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::DataStream::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 100 of file DataStream.cxx.
Referenced by ~DataStream().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::DataStream::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 28 of file DataStream.cxx.
References LARCV_INFO.
Referenced by ~DataStream().
   {
     LARCV_INFO() << "Initialized" << std::endl;
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
move_ch_status()
void larcv::ImageHolder::move_ch_status (std::map< larcv::PlaneID_t, larcv::ChStatus > & dest) inherited
Definition at line 21 of file ImageHolder.cxx.
References larcv::ImageHolder::_ch_status_m.
Referenced by larcv::ImageMerger::process(), and larcv::ImageHolder::~ImageHolder().
   { dest = std::move(_ch_status_m); }
move_pmt_image()
void larcv::ImageHolder::move_pmt_image (Image2D & dest) inherited
Definition at line 12 of file ImageHolder.cxx.
References larcv::ImageHolder::_pmt_image.
Referenced by larcv::ImageMerger::process(), and larcv::ImageHolder::~ImageHolder().
   { dest = std::move(_pmt_image); }
move_roi()
void larcv::ImageHolder::move_roi (std::vector< larcv::ROI > & dest) inherited
Definition at line 24 of file ImageHolder.cxx.
References larcv::ImageHolder::_roi_v.
Referenced by larcv::ImageMerger::process(), and larcv::ImageHolder::~ImageHolder().
   { dest = std::move(_roi_v); }
move_tpc_image()
void larcv::ImageHolder::move_tpc_image (std::vector< larcv::Image2D > & dest) inherited
Definition at line 15 of file ImageHolder.cxx.
References larcv::ImageHolder::_tpc_image_v.
Referenced by larcv::ImageMerger::process(), and larcv::ImageHolder::~ImageHolder().
   { dest = std::move(_tpc_image_v); }
move_tpc_segment()
void larcv::ImageHolder::move_tpc_segment (std::vector< larcv::Image2D > & dest) inherited
Definition at line 18 of file ImageHolder.cxx.
References larcv::ImageHolder::_tpc_segment_v.
Referenced by larcv::ImageMerger::process(), and larcv::ImageHolder::~ImageHolder().
   { dest = std::move(_tpc_segment_v); }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::DataStream::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 33 of file DataStream.cxx.
References larcv::ImageHolder::_ch_status_m, _ch_status_producer, larcv::ImageHolder::_pmt_image, _pmt_image_producer, _roi_producer, larcv::ImageHolder::_roi_v, _segment_producer, _tpc_image_producer, larcv::ImageHolder::_tpc_image_v, larcv::ImageHolder::_tpc_segment_v, larcv::IOManager< T >::get_data(), larcv::kProductChStatus, larcv::kProductImage2D, larcv::kProductROI, LARCV_INFO, and larcv::ImageHolder::retrieve_id().
Referenced by ~DataStream().
   {
     LARCV_INFO() << "Clearing attributes..." << std::endl;
     _ch_status_m.clear();
     _tpc_image_v.clear();
     _tpc_segment_v.clear();
     _roi_v.clear();
     _pmt_image = Image2D();
     // Retrieve ChStatus
     if(!_ch_status_producer.empty()) {
       LARCV_INFO() << "Reading-in ChStatus " << _ch_status_producer << std::endl;
       auto event_chstatus = (EventChStatus*)(mgr.get_data(kProductChStatus,_ch_status_producer));
       if(!event_chstatus || event_chstatus->ChStatusMap().empty()) return false;
       LARCV_INFO() << "Copying ChStatus " << _ch_status_producer << std::endl;
       _ch_status_m = event_chstatus->ChStatusMap();
     }
     // Retrieve TPC Image
     LARCV_INFO() << "Reading-in TPC Image2D " << _tpc_image_producer << std::endl;
     auto event_tpc_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_tpc_image_producer));
     if(!event_tpc_image || event_tpc_image->Image2DArray().empty()) return false;
     LARCV_INFO() << "Copying TPC Image2D " << _tpc_image_producer << std::endl;
     event_tpc_image->Move(_tpc_image_v);
     // Retrieve PMT Image
     if(!_pmt_image_producer.empty()) {
       LARCV_INFO() << "Reading-in PMT Image2D " << _pmt_image_producer << std::endl;
       auto event_pmt_image = (EventImage2D*)(mgr.get_data(kProductImage2D,_pmt_image_producer));
       if(!event_pmt_image || event_pmt_image->Image2DArray().empty()) return false;
       LARCV_INFO() << "Copying PMT Image2D " << _pmt_image_producer << std::endl;
       std::vector<larcv::Image2D> tmp_v;
       event_pmt_image->Move(tmp_v);
       if(tmp_v.size())
        _pmt_image = std::move(tmp_v[0]);
     }
     //Retrieve the ROI
     if(!_roi_producer.empty()) {
       LARCV_INFO() << "Reading-in ROI " << _roi_producer << std::endl;
       auto event_roi = (EventROI*)(mgr.get_data(kProductROI,_roi_producer));
       if(event_roi and !event_roi->ROIArray().empty())
           _roi_v = event_roi->ROIArray();
     }
     //Retrieve the segmenation image if exists
     if(!_segment_producer.empty()) {
       //segment_proc->move_segment(_tpc_segment_v);
       auto event_segment = (EventImage2D*)(mgr.get_data(kProductImage2D,_segment_producer));
       _tpc_segment_v = event_segment->Image2DArray();
     }
     // Retrieve event id
     retrieve_id(event_tpc_image);
     return true;
   }
retrieve_id()
void larcv::ImageHolder::retrieve_id (const EventBase * data) inline inherited
Definition at line 45 of file ImageHolder.h.
References larcv::ImageHolder::_event, larcv::ImageHolder::_run, larcv::ImageHolder::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by process().
     { _run=data->run(); _subrun=data->subrun(); _event=data->event(); }
run()
size_t larcv::ImageHolder::run () const inline inherited
Definition at line 48 of file ImageHolder.h.
References larcv::ImageHolder::_run.
Referenced by larcv::ImageMerger::process().
 { return _run;    }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
subrun()
size_t larcv::ImageHolder::subrun () const inline inherited
Definition at line 49 of file ImageHolder.h.
References larcv::ImageHolder::_subrun.
Referenced by larcv::ImageMerger::process().
 { return _subrun; }
Member Data Documentation
_ch_status_m
std::map< ::larcv::PlaneID_t,larcv::ChStatus> larcv::ImageHolder::_ch_status_m protected inherited
Definition at line 58 of file ImageHolder.h.
Referenced by larcv::ImageHolder::move_ch_status(), and process().
_ch_status_producer
std::string larcv::DataStream::_ch_status_producer private
Definition at line 48 of file DataStream.h.
Referenced by configure(), and process().
_event
size_t larcv::ImageHolder::_event protected inherited
Definition at line 54 of file ImageHolder.h.
Referenced by larcv::ImageHolder::event(), larcv::ImageHolder::ImageHolder(), and larcv::ImageHolder::retrieve_id().
_pmt_image
Image2D larcv::ImageHolder::_pmt_image protected inherited
Definition at line 57 of file ImageHolder.h.
Referenced by larcv::ImageHolder::move_pmt_image(), and process().
_pmt_image_producer
std::string larcv::DataStream::_pmt_image_producer private
Definition at line 47 of file DataStream.h.
Referenced by configure(), and process().
_roi_producer
std::string larcv::DataStream::_roi_producer private
Definition at line 49 of file DataStream.h.
Referenced by configure(), and process().
_roi_v
std::vector<larcv::ROI> larcv::ImageHolder::_roi_v protected inherited
Definition at line 59 of file ImageHolder.h.
Referenced by larcv::ImageHolder::move_roi(), and process().
_run
size_t larcv::ImageHolder::_run protected inherited
Definition at line 54 of file ImageHolder.h.
Referenced by larcv::ImageHolder::ImageHolder(), larcv::ImageHolder::retrieve_id(), and larcv::ImageHolder::run().
_segment_producer
std::string larcv::DataStream::_segment_producer private
Definition at line 50 of file DataStream.h.
Referenced by configure(), and process().
_subrun
size_t larcv::ImageHolder::_subrun protected inherited
Definition at line 54 of file ImageHolder.h.
Referenced by larcv::ImageHolder::ImageHolder(), larcv::ImageHolder::retrieve_id(), and larcv::ImageHolder::subrun().
_tpc_image_producer
std::string larcv::DataStream::_tpc_image_producer private
Definition at line 46 of file DataStream.h.
Referenced by configure(), and process().
_tpc_image_v
std::vector<larcv::Image2D> larcv::ImageHolder::_tpc_image_v protected inherited
Definition at line 55 of file ImageHolder.h.
Referenced by larcv::ImageHolder::move_tpc_image(), and process().
_tpc_segment_v
std::vector<larcv::Image2D> larcv::ImageHolder::_tpc_segment_v protected inherited
Definition at line 56 of file ImageHolder.h.
Referenced by larcv::ImageHolder::move_tpc_segment(), and process().
The documentation for this class was generated from the following files:
DataStream.h
DataStream.cxx