LArCV: larcv::LArbysImageOut Class Reference
larcv::LArbysImageOut Class Reference
#include <LArbysImageOut.h>
Public Member Functions
LArbysImageOut (const std::string name="LArbysImageOut")
~LArbysImageOut ()
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
void SetLArbysImageAna (LArbysImageAna *larana)
void SetLArbysImageExtract (LArbysImageExtract *larext)
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
void ClearVertex ()
Private Attributes
TTree * _vtx3d_tree
uint _run
uint _subrun
uint _event
uint _entry
uint _n_vtx3d
uint _vtx3d_n_planes
uint _vtx3d_type
uint _vtx3d_id
double _vtx3d_x
double _vtx3d_y
double _vtx3d_z
std::vector< double > _vtx2d_x_v
std::vector< double > _vtx2d_y_v
std::vector< double > _circle_x_v
std::vector< double > _circle_y_v
std::vector< uint > _ntrack_par_v
std::vector< uint > _nshower_par_v
std::vector< uint > _circle_xs_v
std::vector< uint > _par_multi
LArbysImageAna * _LArbysImageAna
LArbysImageExtract * _LArbysImageExtract
Detailed Description
Definition at line 21 of file LArbysImageOut.h.
Constructor & Destructor Documentation
LArbysImageOut()
larcv::LArbysImageOut::LArbysImageOut (const std::string name = "LArbysImageOut")
Definition at line 12 of file LArbysImageOut.cxx.
Referenced by larcv::LArbysImageOutProcessFactory::create().
     : ProcessBase(name),
       _vtx3d_tree(nullptr)
   {}
~LArbysImageOut()
larcv::LArbysImageOut::~LArbysImageOut () inline
Definition at line 26 of file LArbysImageOut.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
ClearVertex()
void larcv::LArbysImageOut::ClearVertex () private
Definition at line 20 of file LArbysImageOut.cxx.
References _circle_x_v, _circle_xs_v, _circle_y_v, _nshower_par_v, _ntrack_par_v, _par_multi, _vtx2d_x_v, and _vtx2d_y_v.
Referenced by process().
{
     _vtx2d_x_v.clear();
     _vtx2d_y_v.clear();
     _circle_x_v.clear();
     _circle_y_v.clear();
     _vtx2d_x_v.resize(3);
     _vtx2d_y_v.resize(3);
     _circle_x_v.resize(3);
     _circle_y_v.resize(3);
     _circle_xs_v.resize(3);
     _par_multi.clear();
     _par_multi.resize(3);
     _ntrack_par_v.clear();
     _nshower_par_v.clear();
     _ntrack_par_v.resize(3);
     _nshower_par_v.resize(3);
     std::fill(_ntrack_par_v.begin(), _ntrack_par_v.end(), 0);
     std::fill(_nshower_par_v.begin(), _nshower_par_v.end(), 0);
   }
configure()
void larcv::LArbysImageOut::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 17 of file LArbysImageOut.cxx.
Referenced by ~LArbysImageOut().
   {}
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::LArbysImageOut::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 118 of file LArbysImageOut.cxx.
References _vtx3d_tree.
Referenced by ~LArbysImageOut().
   {
     _vtx3d_tree->Write();
   }
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::LArbysImageOut::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 40 of file LArbysImageOut.cxx.
References _circle_x_v, _circle_xs_v, _circle_y_v, _entry, _event, _nshower_par_v, _ntrack_par_v, _par_multi, _run, _subrun, _vtx2d_x_v, _vtx2d_y_v, _vtx3d_id, _vtx3d_tree, _vtx3d_type, _vtx3d_x, _vtx3d_y, and _vtx3d_z.
Referenced by ~LArbysImageOut().
   {
     _vtx3d_tree = new TTree("Vertex3DTree","");
     _vtx3d_tree->Branch("run"   ,&_run       ,"run/i");
     _vtx3d_tree->Branch("subrun",&_subrun    ,"subrun/i");
     _vtx3d_tree->Branch("event" ,&_event     ,"event/i");
     _vtx3d_tree->Branch("entry" ,&_entry     ,"entry/i");
     _vtx3d_tree->Branch("id"    ,&_vtx3d_id  ,"id/i");
     _vtx3d_tree->Branch("type"  ,&_vtx3d_type,"type/i");
     _vtx3d_tree->Branch("x"     ,&_vtx3d_x   ,"x/D");
     _vtx3d_tree->Branch("y"     ,&_vtx3d_y   ,"y/D");
     _vtx3d_tree->Branch("z"     ,&_vtx3d_z   ,"z/D");
     _vtx3d_tree->Branch("vtx2d_x_v"    ,&_vtx2d_x_v);
     _vtx3d_tree->Branch("vtx2d_y_v"    ,&_vtx2d_y_v);
     _vtx3d_tree->Branch("cvtx2d_x_v"   ,&_circle_x_v);
     _vtx3d_tree->Branch("cvtx2d_y_v"   ,&_circle_y_v);
     _vtx3d_tree->Branch("cvtx2d_xs_v"  ,&_circle_xs_v);
     _vtx3d_tree->Branch("multi_v"      ,&_par_multi);
     _vtx3d_tree->Branch("ntrack_par_v" ,&_ntrack_par_v);
     _vtx3d_tree->Branch("nshower_par_v",&_nshower_par_v);
   }
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::LArbysImageOut::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 62 of file LArbysImageOut.cxx.
References _circle_x_v, _circle_xs_v, _circle_y_v, _entry, _event, _LArbysImageAna, _n_vtx3d, _run, _subrun, _vtx2d_x_v, _vtx2d_y_v, _vtx3d_id, _vtx3d_n_planes, _vtx3d_tree, _vtx3d_type, _vtx3d_x, _vtx3d_y, _vtx3d_z, ClearVertex(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::event_id(), LARCV_DEBUG, and larcv::LArbysImageAna::Verticies().
Referenced by ~LArbysImageOut().
   {
     if(!_LArbysImageAna) throw larbys("Invalid pointer to LArbysImageAna instance specified");
     const auto& event_id = mgr.event_id();
     _run    = event_id.run();
     _subrun = event_id.subrun();
     _event  = event_id.event();
     _entry  = mgr.current_entry();
     LARCV_DEBUG()<<"At (r,s,e,e) -- ["<<_run<<","<< _subrun<<","<<_event<<","<<_entry<<"]"<<std::endl;
     const auto& vertex_v = _LArbysImageAna->Verticies();
     if (vertex_v.empty()) return false;
     LARCV_DEBUG() << "... " << vertex_v.size() << " verticies" << std::endl;
     _n_vtx3d = vertex_v.size();
     for(size_t vtxid=0;vtxid<_n_vtx3d;++vtxid) {
       ClearVertex();
       _vtx3d_id=vtxid;
       const auto& vtx3d = vertex_v[vtxid];
       _vtx3d_type = (uint) vtx3d.type;
       _vtx3d_x = vtx3d.x;
       _vtx3d_y = vtx3d.y;
       _vtx3d_z = vtx3d.z;
       _vtx3d_n_planes = (uint) vtx3d.num_planes;
       for(size_t plane=0; plane<3;  ++plane) {
         if (_vtx3d_type < 2) {
           // store circle vertex information
           const auto& circle_vtx   = vtx3d.cvtx2d_v.at(plane);
           const auto& circle_vtx_c = circle_vtx.center;
           auto& circle_x  = _circle_x_v [plane];
           auto& circle_y  = _circle_y_v [plane];
           auto& circle_xs = _circle_xs_v[plane];
           circle_x = circle_vtx_c.x;
           circle_y = circle_vtx_c.y;
           circle_xs = (uint) circle_vtx.xs_v.size();
         }
         auto& vtx2d_x = _vtx2d_x_v[plane];
         auto& vtx2d_y = _vtx2d_y_v[plane];
         vtx2d_x = vtx3d.cvtx2d_v[plane].center.x;
         vtx2d_y = vtx3d.cvtx2d_v[plane].center.y;
       } // end plane
     _vtx3d_tree->Fill();
     } //end loop over vertex
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
SetLArbysImageAna()
void larcv::LArbysImageOut::SetLArbysImageAna (LArbysImageAna * larana) inline
Definition at line 33 of file LArbysImageOut.h.
References _LArbysImageAna.
     { _LArbysImageAna = larana; }
SetLArbysImageExtract()
void larcv::LArbysImageOut::SetLArbysImageExtract (LArbysImageExtract * larext) inline
Definition at line 35 of file LArbysImageOut.h.
References _LArbysImageExtract.
     { _LArbysImageExtract = larext; }
Member Data Documentation
_circle_x_v
std::vector<double> larcv::LArbysImageOut::_circle_x_v private
Definition at line 59 of file LArbysImageOut.h.
Referenced by ClearVertex(), initialize(), and process().
_circle_xs_v
std::vector<uint> larcv::LArbysImageOut::_circle_xs_v private
Definition at line 63 of file LArbysImageOut.h.
Referenced by ClearVertex(), initialize(), and process().
_circle_y_v
std::vector<double> larcv::LArbysImageOut::_circle_y_v private
Definition at line 60 of file LArbysImageOut.h.
Referenced by ClearVertex(), initialize(), and process().
_entry
uint larcv::LArbysImageOut::_entry private
Definition at line 47 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_event
uint larcv::LArbysImageOut::_event private
Definition at line 46 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_LArbysImageAna
LArbysImageAna* larcv::LArbysImageOut::_LArbysImageAna private
Definition at line 66 of file LArbysImageOut.h.
Referenced by process(), and SetLArbysImageAna().
_LArbysImageExtract
LArbysImageExtract* larcv::LArbysImageOut::_LArbysImageExtract private
Definition at line 67 of file LArbysImageOut.h.
Referenced by SetLArbysImageExtract().
_n_vtx3d
uint larcv::LArbysImageOut::_n_vtx3d private
Definition at line 49 of file LArbysImageOut.h.
Referenced by process().
_nshower_par_v
std::vector<uint> larcv::LArbysImageOut::_nshower_par_v private
Definition at line 62 of file LArbysImageOut.h.
Referenced by ClearVertex(), and initialize().
_ntrack_par_v
std::vector<uint> larcv::LArbysImageOut::_ntrack_par_v private
Definition at line 61 of file LArbysImageOut.h.
Referenced by ClearVertex(), and initialize().
_par_multi
std::vector<uint> larcv::LArbysImageOut::_par_multi private
Definition at line 64 of file LArbysImageOut.h.
Referenced by ClearVertex(), and initialize().
_run
uint larcv::LArbysImageOut::_run private
Definition at line 44 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_subrun
uint larcv::LArbysImageOut::_subrun private
Definition at line 45 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_vtx2d_x_v
std::vector<double> larcv::LArbysImageOut::_vtx2d_x_v private
Definition at line 57 of file LArbysImageOut.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx2d_y_v
std::vector<double> larcv::LArbysImageOut::_vtx2d_y_v private
Definition at line 58 of file LArbysImageOut.h.
Referenced by ClearVertex(), initialize(), and process().
_vtx3d_id
uint larcv::LArbysImageOut::_vtx3d_id private
Definition at line 52 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_vtx3d_n_planes
uint larcv::LArbysImageOut::_vtx3d_n_planes private
Definition at line 50 of file LArbysImageOut.h.
Referenced by process().
_vtx3d_tree
TTree* larcv::LArbysImageOut::_vtx3d_tree private
Definition at line 40 of file LArbysImageOut.h.
Referenced by finalize(), initialize(), and process().
_vtx3d_type
uint larcv::LArbysImageOut::_vtx3d_type private
Definition at line 51 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_vtx3d_x
double larcv::LArbysImageOut::_vtx3d_x private
Definition at line 53 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_vtx3d_y
double larcv::LArbysImageOut::_vtx3d_y private
Definition at line 54 of file LArbysImageOut.h.
Referenced by initialize(), and process().
_vtx3d_z
double larcv::LArbysImageOut::_vtx3d_z private
Definition at line 55 of file LArbysImageOut.h.
Referenced by initialize(), and process().
The documentation for this class was generated from the following files:
LArbysImageOut.h
LArbysImageOut.cxx