LArCV: supera::ImageMetaFromConfig Class Reference
supera::ImageMetaFromConfig Class Reference
User defined class ImageMetaFromConfig ...
#include <ImageMetaFromConfig.h>
Public Member Functions
ImageMetaFromConfig ()
Default constructor.
~ImageMetaFromConfig ()
Default destructor.
void configure (const supera::Config_t &)
const std::vector< larcv::ImageMeta > & Meta () const
const std::vector< size_t > & RowCompressionFactor () const
const std::vector< size_t > & ColCompressionFactor () const
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< larcv::ImageMeta > _meta_v
Detailed Description
User defined class ImageMetaFromConfig ...
these comments are used to generate doxygen documentation!
Definition at line 27 of file ImageMetaFromConfig.h.
Constructor & Destructor Documentation
ImageMetaFromConfig()
supera::ImageMetaFromConfig::ImageMetaFromConfig () inline
Default constructor.
Definition at line 32 of file ImageMetaFromConfig.h.
                           : ImageMetaMakerBase("ImageMetaFromConfig")
     {}
~ImageMetaFromConfig()
supera::ImageMetaFromConfig::~ImageMetaFromConfig () inline
Default destructor.
Definition at line 36 of file ImageMetaFromConfig.h.
References configure().
 {}
Member Function Documentation
ColCompressionFactor()
const std::vector<size_t>& supera::ImageMetaMakerBase::ColCompressionFactor () const inline inherited
Definition at line 44 of file ImageMetaMakerBase.h.
References supera::ImageMetaMakerBase::_comp_cols.
Referenced by supera::ImageMetaMaker::ColCompressionFactor(), and configure().
 { return _comp_cols; }
configure()
void supera::ImageMetaFromConfig::configure (const supera::Config_t & cfg) virtual
Reimplemented from supera::ImageMetaMakerBase.
Definition at line 8 of file ImageMetaFromConfig.cxx.
References _meta_v, supera::ImageMetaMakerBase::ColCompressionFactor(), supera::ImageMetaMakerBase::configure(), larcv::ImageMeta::dump(), larcv::PSet::get(), LARCV_INFO, supera::Nplanes(), and supera::ImageMetaMakerBase::RowCompressionFactor().
Referenced by ~ImageMetaFromConfig().
   {
     ImageMetaMakerBase::configure(cfg);
     auto min_time = cfg.get<double>("MinTime");
     auto min_wire = cfg.get<double>("MinWire");
     auto image_rows = cfg.get<std::vector<size_t> >("EventImageRows");
     auto image_cols = cfg.get<std::vector<size_t> >("EventImageCols");
     auto const& comp_rows = RowCompressionFactor();
     auto const& comp_cols = ColCompressionFactor();
     if(image_rows.size() != supera::Nplanes()) {
       std::cerr << "EventImageRows size != # planes..." << std::endl;
       throw std::exception();
     }
     if(image_cols.size() != supera::Nplanes()) {
       std::cerr << "EventImageCols size != # planes..." << std::endl;
       throw std::exception();
     }
     // construct meta
     for(size_t plane=0; plane<image_rows.size(); ++plane) {
       larcv::ImageMeta meta(image_cols[plane] * comp_cols[plane], image_rows[plane] * comp_rows[plane],
                 image_rows[plane] * comp_rows[plane], image_cols[plane] * comp_cols[plane],
                 min_wire, min_time + image_rows[plane] * comp_rows[plane],
                 plane);
       LARCV_INFO() << "Created meta " <<  meta.dump();
       _meta_v.emplace_back(std::move(meta));
     }
   }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
Meta()
const std::vector<larcv::ImageMeta>& supera::ImageMetaFromConfig::Meta () const inline virtual
Implements supera::ImageMetaMakerBase.
Definition at line 40 of file ImageMetaFromConfig.h.
References _meta_v.
     { return _meta_v; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
RowCompressionFactor()
const std::vector<size_t>& supera::ImageMetaMakerBase::RowCompressionFactor () const inline inherited
Definition at line 43 of file ImageMetaMakerBase.h.
References supera::ImageMetaMakerBase::_comp_rows.
Referenced by configure(), and supera::ImageMetaMaker::RowCompressionFactor().
 { return _comp_rows; }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
_meta_v
std::vector<larcv::ImageMeta> supera::ImageMetaFromConfig::_meta_v private
Definition at line 45 of file ImageMetaFromConfig.h.
Referenced by configure(), and Meta().
The documentation for this class was generated from the following files:
ImageMetaFromConfig.h
ImageMetaFromConfig.cxx