LArCV: larcv::ROIMask Class Reference
larcv::ROIMask Class Reference
#include <ROIMask.h>
Public Member Functions
ROIMask (const std::string name="ROIMask")
Default constructor.
~ROIMask ()
Default destructor.
void configure (const PSet &)
void initialize ()
bool process (IOManager &mgr)
void finalize ()
virtual bool is (const std::string question) const
bool event_creator () const
bool has_ana_file () const
TFile & ana_file ()
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Protected Attributes
std::string fInputImageProducer
std::string fOutputImageProducer
std::string fInputROIProducer
std::string fOutputROIProducer
bool fMaskOutsideROI
bool finplace
bool fCutOutOfBounds
int fROIid
larcv::ROIType_t fROILabel
Detailed Description
Definition at line 31 of file ROIMask.h.
Constructor & Destructor Documentation
ROIMask()
larcv::ROIMask::ROIMask (const std::string name = "ROIMask")
Default constructor.
Definition at line 12 of file ROIMask.cxx.
Referenced by larcv::ROIMaskProcessFactory::create().
     : ProcessBase(name)
   {}
~ROIMask()
larcv::ROIMask::~ROIMask () inline
Default destructor.
Definition at line 39 of file ROIMask.h.
References configure(), finalize(), initialize(), and process().
 {}
Member Function Documentation
ana_file()
TFile& larcv::ProcessBase::ana_file () inline inherited
Definition at line 57 of file ProcessBase.h.
References larcv::ProcessBase::_configure_(), larcv::ProcessBase::_fout, and larcv::ProcessBase::_process_().
Referenced by larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::LArbysImageFilter::finalize(), larcv::ReadNueFile::finalize(), larcv::LArbysImage::finalize(), larcv::CCQETruthFilter::finalize(), larcv::ReadJarrettFile::finalize(), and larcv::Run3DTracker::finalize().
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
configure()
void larcv::ROIMask::configure (const PSet & cfg) virtual
Implements larcv::ProcessBase.
Definition at line 16 of file ROIMask.cxx.
References fCutOutOfBounds, finplace, fInputImageProducer, fInputROIProducer, fMaskOutsideROI, fOutputImageProducer, fOutputROIProducer, fROIid, fROILabel, larcv::PSet::get(), and true.
Referenced by ~ROIMask().
   {
     fInputImageProducer  = cfg.get<std::string>( "InputImageProducer" );
     fOutputImageProducer = cfg.get<std::string>( "OutputImageProducer" );
     fInputROIProducer    = cfg.get<std::string>( "InputROIProducer" );
     fOutputROIProducer   = cfg.get<std::string>( "OutputROIProducer" );
     fMaskOutsideROI      = cfg.get<bool>( "MaskOutsideROI" );
     fCutOutOfBounds      = cfg.get<bool>( "CutOutOfBounds", true );
     fROIid               = cfg.get<int>("ROIid",0);
     fROILabel            = (larcv::ROIType_t)cfg.get<int>("ROILabel", 2 ); // larcv::kROIBNB
     if (fInputImageProducer==fOutputImageProducer) finplace = true;
     else finplace = false;
   }
event_creator()
bool larcv::ProcessBase::event_creator () const inline inherited
Definition at line 51 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
Referenced by larcv::hires::HiResImageDivider::process().
     { return _event_creator; }
finalize()
void larcv::ROIMask::finalize () virtual
Implements larcv::ProcessBase.
Definition at line 186 of file ROIMask.cxx.
Referenced by ~ROIMask().
   {}
has_ana_file()
bool larcv::ProcessBase::has_ana_file () const inline inherited
Definition at line 54 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
Referenced by larcv::DeadWireAna::finalize(), larcv::ReadNueFile::finalize(), larcv::SSNetTruthAna::finalize(), larcv::CosmicPixelAna::finalize(), larcv::LEE1e1pAna::finalize(), larcv::VertexAna::finalize(), larcv::LArbysImage::finalize(), larcv::BadRegionAna::finalize(), larcv::SegImageAna::finalize(), larcv::SimplePixelAna::finalize(), larcv::ImageChargeAna::finalize(), larcv::ADCScaleAna::finalize(), larcv::CCQETruthFilter::finalize(), larcv::CosmicVertexAna::finalize(), larcv::HistADC::finalize(), larcv::ReadJarrettFile::finalize(), larcv::Run3DTracker::finalize(), larcv::RSEFilter::finalize(), larcv::RSEFilter::initialize(), and larcv::RSEFilter::process().
     { return _fout != nullptr; }
initialize()
void larcv::ROIMask::initialize () virtual
Implements larcv::ProcessBase.
Definition at line 32 of file ROIMask.cxx.
Referenced by ~ROIMask().
   {}
is()
bool ProcessBase::is (const std::string question) const virtual inherited
Reimplemented in larcv::DatumFillerBase, larcv::SuperaBase, and larcv::SuperaChStatus.
Definition at line 17 of file ProcessBase.cxx.
Referenced by larcv::LArCVSuperaDriver::initialize(), and larcv::ProcessBase::~ProcessBase().
   { return false; }
logger()
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::MultiClassFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::larcv_base::name(), larcv::PreProcessor::PrepareImage(), and larcv::ThreadDatumFiller::set_next_batch().
     { return *_logger; }
name()
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::SegmentMask::configure(), larcv::MergeTwoStream::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::io_mode(), supera::PulledPork3DSlicer::Is(), larcv::SuperaBase::Request(), larcv::ThreadDatumFiller::set_next_batch(), larcv::IOManager< T >::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
process()
bool larcv::ROIMask::process (IOManager & mgr) virtual
Implements larcv::ProcessBase.
Definition at line 35 of file ROIMask.cxx.
References larcv::ROI::AppendBB(), larcv::Image2D::as_vector(), larcv::Image2D::crop(), larcv::EventImage2D::Emplace(), larcv::EventROI::Emplace(), fCutOutOfBounds, finplace, fInputImageProducer, fInputROIProducer, fMaskOutsideROI, fOutputImageProducer, fOutputROIProducer, fROIid, fROILabel, larcv::IOManager< T >::get_data(), larcv::kProductImage2D, larcv::kProductROI, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, larcv::Image2D::meta(), larcv::ImageMeta::min_x(), larcv::EventImage2D::Move(), larcv::Image2D::overlay(), larcv::Image2D::paint(), and larcv::EventROI::ROIArray().
Referenced by ~ROIMask().
   {
     // Get images (and setup output)
     EventImage2D* event_original = (EventImage2D*)mgr.get_data(kProductImage2D, fInputImageProducer);
     EventImage2D* event_masked   = NULL;
     if (!finplace)
       event_masked  = (EventImage2D*)mgr.get_data(kProductImage2D, fOutputImageProducer);
     else
       event_masked  = event_original;
     if ( !event_original ) {
       LARCV_ERROR() << "Could not open input images." << std::endl;
       return false;
     }
     if ( !event_masked )  {
       LARCV_ERROR() << "Could not open output image holder." << std::endl;
       return false;
     }
     // Get ROI
     EventROI* event_roi = (EventROI*)mgr.get_data(kProductROI, fInputROIProducer);
     auto rois = event_roi->ROIArray();
     EventROI* output_rois = (EventROI*)mgr.get_data(kProductROI, fOutputROIProducer);
     // original moves ownership of its image vectors to us
     std::vector< larcv::Image2D> image_v;
     event_original->Move(image_v );
     // container for new images if we are not working in place
     std::vector< larcv::Image2D > masked_image_v;
     std::vector<float> _buffer;
     bool outofbounds = false;
     larcv::ROI output_roi( fROILabel );
     for ( size_t i=0; i<image_v.size(); ++i ) {
       // get access to the data
       larcv::Image2D& original_image = image_v[i];
       auto meta = original_image.meta();
       if ( rois.size()<=0 ) {
     outofbounds = true;
     break;
       }
       auto roi = rois.at(fROIid); // fixme: smarter choice of ROI?
       auto bb  = roi.BB( meta.plane() );
       // make roi meta with same scale as input image
       double origin_x = bb.min_x();
       double origin_y = bb.max_y();
       double width    = bb.width();
       double height   = bb.height();
       // get row and col size based on scale of original image
       int cols = (int)width/meta.pixel_width();
       int rows = (int)height/meta.pixel_height();
       if ( rows==0 || height<meta.pixel_height() ) {
     // 0 thick roi...
     height=meta.pixel_height();
     rows = 1;
       }
       if ( cols==0 || width<meta.pixel_width() ) {
     width = meta.pixel_width();
     cols = 1;
       }
       ImageMeta maskedmeta( width, height, rows, cols, origin_x, origin_y, meta.plane() );
       LARCV_DEBUG() << "original meta: " << std::endl;
       LARCV_DEBUG() << "  " << meta.dump() << std::endl;
       LARCV_DEBUG() << "roi meta: " << std::endl;
       LARCV_DEBUG() << "  " << bb.dump() << std::endl;
       // we need to check that the roi is within image range
       if ( bb.min_x()<meta.min_x() || bb.max_x()>meta.max_x()
        || bb.min_y()<meta.min_y() || bb.max_y()>meta.max_y() ) {
     LARCV_INFO() << "ROI extends out of bounds" << std::endl;
     outofbounds = true;
     break;
       }
       if ( fMaskOutsideROI ) {
     // we want everything but the ROI to be zero
     // we crop out the region we're interested in
     larcv::Image2D cropped_image = original_image.crop( maskedmeta );
     // define the new image, and blank it out
     larcv::Image2D new_image( meta );
     new_image.paint( 0.0 );
     // overlay cropped image
     new_image.overlay( cropped_image );
     masked_image_v.emplace_back( std::move(new_image) );
       }
       else {
     // we want to zero the region inside the ROI
     // make blank with size of ROi
     larcv::Image2D roi_blank( maskedmeta );
     roi_blank.paint(0.0);
     // make copy of original
     larcv::Image2D new_image( meta, original_image.as_vector() );
     new_image.overlay( roi_blank );
     masked_image_v.emplace_back( std::move(new_image) );
       }
       // store the roi (maskedmeta)
       output_roi.AppendBB( maskedmeta );
     }
     if (outofbounds) {
       // out bound ROI found. skip or make blank
       if ( fCutOutOfBounds )
     return false;
       // make blanks
       masked_image_v.clear();
       for ( size_t i=0; i<image_v.size(); ++i ) {
     larcv::Image2D& original_image = image_v[i];
     auto meta = original_image.meta();
     larcv::Image2D new_image( meta );
         new_image.paint( 0.0 );
         masked_image_v.emplace_back( std::move(new_image) );
       }
     }
     // store
     if ( finplace ) {
       // give the new images
       event_original->Emplace( std::move(masked_image_v) );
     }
     else {
       // return the original images
       event_original->Emplace( std::move( image_v ) );
       // we give the new image2d container our relabeled images
       event_masked->Emplace( std::move(masked_image_v) );
     }
     output_rois->Emplace( std::move(output_roi) );
     return true;
   }
set_verbosity()
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::TrackShowerAna::Configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::MergeTwoStream::configure(), larcv::NuFilter::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), and larcv::ThreadDatumFiller::set_next_batch().
     { _logger->set(level); }
Member Data Documentation
fCutOutOfBounds
bool larcv::ROIMask::fCutOutOfBounds protected
Definition at line 56 of file ROIMask.h.
Referenced by configure(), and process().
finplace
bool larcv::ROIMask::finplace protected
Definition at line 55 of file ROIMask.h.
Referenced by configure(), and process().
fInputImageProducer
std::string larcv::ROIMask::fInputImageProducer protected
Definition at line 50 of file ROIMask.h.
Referenced by configure(), and process().
fInputROIProducer
std::string larcv::ROIMask::fInputROIProducer protected
Definition at line 52 of file ROIMask.h.
Referenced by configure(), and process().
fMaskOutsideROI
bool larcv::ROIMask::fMaskOutsideROI protected
Definition at line 54 of file ROIMask.h.
Referenced by configure(), and process().
fOutputImageProducer
std::string larcv::ROIMask::fOutputImageProducer protected
Definition at line 51 of file ROIMask.h.
Referenced by configure(), and process().
fOutputROIProducer
std::string larcv::ROIMask::fOutputROIProducer protected
Definition at line 53 of file ROIMask.h.
Referenced by configure(), and process().
fROIid
int larcv::ROIMask::fROIid protected
Definition at line 57 of file ROIMask.h.
Referenced by configure(), and process().
fROILabel
larcv::ROIType_t larcv::ROIMask::fROILabel protected
Definition at line 58 of file ROIMask.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
ROIMask.h
ROIMask.cxx