LArCV: APILArLite
APILArLite
Files
file ChStatusFinder.h
Class def header for a class ChStatusFinder.
file Supera.h
Class def header for a class Supera.
file SuperaWireAlgo.h
Class def header for a class SuperaWireAlgo.
file SuperaCore.h
Class def header for a class SuperaCore.
Namespaces
larlite
larcv
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Classes
class larlite::SuperaWireAlgo
Functions
larlite::SuperaWireAlgo::SuperaWireAlgo ()
virtual larlite::SuperaWireAlgo::~SuperaWireAlgo ()
void larlite::SuperaWireAlgo::fillImage (larcv::Image2D &img, const std::vector< larlite::wire > &wires, const int time_offset)
void larlite::SuperaWireAlgo::setVerbosity (unsigned short v)
Variables
::larcv::supera::SuperaCore< larlite::opdetwaveform, larlite::wire, larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch, larlite::hit > larlite::SuperaWireAlgo::_core
Detailed Description
Function Documentation
fillImage()
void larlite::SuperaWireAlgo::fillImage (larcv::Image2D & img, const std::vector< larlite::wire > & wires, const int time_offset)
Definition at line 8 of file SuperaWireAlgo.cxx.
References larlite::SuperaWireAlgo::_core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::fill().
Referenced by larlite::SuperaWireAlgo::~SuperaWireAlgo().
{
     _core.fill( img, wires, time_offset );
   }
setVerbosity()
void larlite::SuperaWireAlgo::setVerbosity (unsigned short v)
Definition at line 12 of file SuperaWireAlgo.cxx.
References larlite::SuperaWireAlgo::_core, and larcv::supera::SuperaCore< R, S, T, U, V, W, Q >::set_verbosity().
Referenced by larlite::SuperaWireAlgo::~SuperaWireAlgo().
{
     _core.set_verbosity(v);
   }
SuperaWireAlgo()
larlite::SuperaWireAlgo::SuperaWireAlgo () inline
Definition at line 38 of file SuperaWireAlgo.h.
 {};
~SuperaWireAlgo()
virtual larlite::SuperaWireAlgo::~SuperaWireAlgo () inline virtual
Definition at line 39 of file SuperaWireAlgo.h.
References larlite::SuperaWireAlgo::fillImage(), and larlite::SuperaWireAlgo::setVerbosity().
 {};
Variable Documentation
_core
::larcv::supera::SuperaCore<larlite::opdetwaveform, larlite::wire, larlite::mctruth, larlite::mctrack, larlite::mcshower, larlite::simch, larlite::hit> larlite::SuperaWireAlgo::_core protected
Definition at line 51 of file SuperaWireAlgo.h.
Referenced by larlite::SuperaWireAlgo::fillImage(), and larlite::SuperaWireAlgo::setVerbosity().