LArCV: LArCV
LArCV
Files
file larbys.h
Class def header for exception classes in LArUtil package.
file larcv_base.h
Class definition file of larcv_base.
file larcv_logger.h
logger utility class definition header file.
file larcv_logger.h
logger utility class definition header file.
file Image2D.h
Class def header for an image data holder.
file ImageMeta.h
Class def header for a class ImageMeta.
Namespaces
larcv
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Classes
class larcv::IOManager< T >
User defined class IOManager ...
Macros
#define LARCV_DEBUG() if(logger().debug ()) logger().send(::larcv::msg::kDEBUG, __FUNCTION__, __LINE__, __FILE__)
Compiler macro for DEBUG message.
#define LARCV_INFO() if(logger().info ()) logger().send(::larcv::msg::kINFO, __FUNCTION__, __LINE__)
Compiler macro for INFO message.
#define LARCV_NORMAL() if(logger().normal ()) logger().send(::larcv::msg::kNORMAL, __FUNCTION__)
Compiler macro for NORMAL message.
#define LARCV_WARNING() if(logger().warning ()) logger().send(::larcv::msg::kWARNING, __FUNCTION__)
Compiler macro for WARNING message.
#define LARCV_ERROR() if(logger().error ()) logger().send(::larcv::msg::kERROR, __FUNCTION__, __LINE__)
Compiler macro for ERROR message.
#define LARCV_CRITICAL() logger().send(::larcv::msg::kCRITICAL, __FUNCTION__, __LINE__, __FILE__)
Compiler macro for CRITICAL message.
#define LARCV_SDEBUG() if(larcv::logger::get_shared().debug()) larcv::logger::get_shared().send(::larcv::msg::kDEBUG, __FUNCTION__,__LINE__,__FILE__)
#define LARCV_SINFO() if(larcv::logger::get_shared().info()) larcv::logger::get_shared().send(::larcv::msg::kINFO, __FUNCTION__,__LINE__)
#define LARCV_SNORMAL() if(larcv::logger::get_shared().normal()) larcv::logger::get_shared().send(::larcv::msg::kNORMAL, __FUNCTION__)
#define LARCV_SWARNING() if(larcv::logger::get_shared().warning()) larcv::logger::get_shared().send(::larcv::msg::kWARNING, __FUNCTION__)
#define LARCV_SERROR() if(larcv::logger::get_shared().error()) larcv::logger::get_shared().send(::larcv::msg::kERROR, __FUNCTION__,__LINE__)
#define LARCV_SCRITICAL() larcv::logger::get_shared().send(::larcv::msg::kCRITICAL, __FUNCTION__,__LINE__,__FILE__)
Enumerations
enum larcv::IOManager< T >::IOMode_t {
larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD,
larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE,
larcv::IOManager< T >::kBOTH
}
enum larcv::IOManager< T >::IOMode_t {
larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD,
larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE,
larcv::IOManager< T >::kBOTH
}
Three IO modes: read, write, or read-and-write.
enum larcv::IOManager< T >::IOMode_t {
larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD,
larcv::IOManager< T >::kWRITE, larcv::IOManager< T >::kBOTH, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE,
larcv::IOManager< T >::kBOTH
}
Functions
larcv::IOManager< T >::IOManager (IOMode_t mode=kREAD)
Default constructor.
larcv::IOManager< T >::~IOManager ()
Default destructor.
void larcv::IOManager< T >::reset ()
void larcv::IOManager< T >::add_in_file (const std::string filename, const std::string dirname="")
void larcv::IOManager< T >::set_out_file (const std::string name)
size_t larcv::IOManager< T >::producer_id (const std::string &producer) const
bool larcv::IOManager< T >::initialize ()
bool larcv::IOManager< T >::read_entry (const size_t index)
bool larcv::IOManager< T >::save_entry ()
std::vector< T > & larcv::IOManager< T >::get_data (const std::string &producer)
std::vector< T > & larcv::IOManager< T >::get_data (const size_t id)
void larcv::IOManager< T >::finalize ()
void larcv::IOManager< T >::prepare_input ()
size_t larcv::IOManager< T >::register_producer (const std::string &name)
larcv::IOManager< T >::IOManager (IOMode_t mode=kREAD, std::string name="IOManager")
Default constructor.
larcv::IOManager< T >::IOManager (const PSet &cfg)
Configuration PSet construction so you don't have to call setter functions.
IOMode_t larcv::IOManager< T >::io_mode () const
IO mode accessor.
void larcv::IOManager< T >::clear_in_file ()
ProducerID_t larcv::IOManager< T >::producer_id (const ProductType_t type, const std::string &producer) const
ProductType_t larcv::IOManager< T >::product_type (const size_t id) const
void larcv::IOManager< T >::configure (const PSet &cfg)
bool larcv::IOManager< T >::read_entry (const size_t index, bool force_reload=false)
void larcv::IOManager< T >::clear_entry ()
void larcv::IOManager< T >::set_id (const size_t run, const size_t subrun, const size_t event)
size_t larcv::IOManager< T >::current_entry () const
size_t larcv::IOManager< T >::get_n_entries () const
EventBase * larcv::IOManager< T >::get_data (const ProductType_t type, const std::string &producer)
template<class T >
T & larcv::IOManager< T >::get_data (const std::string &producer)
template<class T >
T & larcv::IOManager< T >::get_data (const ProducerID_t id)
const EventBase & larcv::IOManager< T >::event_id () const
const EventBase & larcv::IOManager< T >::last_event_id () const
const std::vector< std::string > larcv::IOManager< T >::producer_list (const ProductType_t type) const
const std::vector< std::string > & larcv::IOManager< T >::file_list () const
void larcv::IOManager< T >::set_id ()
size_t larcv::IOManager< T >::register_producer (const ProductType_t type, const std::string &name)
Variables
IOMode_t larcv::IOManager< T >::_io_mode
bool larcv::IOManager< T >::_prepared
TFile * larcv::IOManager< T >::_out_file
size_t larcv::IOManager< T >::_tree_index
size_t larcv::IOManager< T >::_tree_entries
std::string larcv::IOManager< T >::_out_file_name
std::vector< std::string > larcv::IOManager< T >::_in_file_v
std::vector< std::string > larcv::IOManager< T >::_in_dir_v
std::vector< std::map< std::string, size_t > > larcv::IOManager< T >::_key_list
std::vector< TTree * > larcv::IOManager< T >::_out_tree_v
std::vector< TChain * > larcv::IOManager< T >::_in_tree_v
std::vector< size_t > larcv::IOManager< T >::_in_tree_index_v
size_t larcv::IOManager< T >::_product_ctr
std::vector< larcv::EventBase * > larcv::IOManager< T >::_product_ptr_v
std::vector< larcv::ProductType_t > larcv::IOManager< T >::_product_type_v
size_t larcv::IOManager< T >::_in_tree_index
size_t larcv::IOManager< T >::_out_tree_index
size_t larcv::IOManager< T >::_in_tree_entries
size_t larcv::IOManager< T >::_out_tree_entries
bool larcv::IOManager< T >::_hasindex
EventBase larcv::IOManager< T >::_event_id
EventBase larcv::IOManager< T >::_set_event_id
EventBase larcv::IOManager< T >::_last_event_id
std::vector< std::map< std::string, larcv::ProducerID_t > > larcv::IOManager< T >::_key_list
TChain * larcv::IOManager< T >::_in_index_tree_v
TChain * larcv::IOManager< T >::_out_index_tree_v
std::vector< std::string > larcv::IOManager< T >::_store_only_name
std::vector< larcv::ProductType_t > larcv::IOManager< T >::_store_only_type
std::vector< std::string > larcv::IOManager< T >::_read_only_name
std::vector< larcv::ProductType_t > larcv::IOManager< T >::_read_only_type
std::vector< bool > larcv::IOManager< T >::_store_only_bool
std::vector< bool > larcv::IOManager< T >::_read_id_bool
std::map< std::string, size_t > larcv::IOManager< T >::_key_m
std::vector< std::vector< T > * > larcv::IOManager< T >::_product_v
Detailed Description
Macro Definition Documentation
LARCV_CRITICAL
#define LARCV_CRITICAL () logger().send(::larcv::msg::kCRITICAL, __FUNCTION__, __LINE__, __FILE__)
Compiler macro for CRITICAL message.
Definition at line 147 of file larcv_logger.h.
Referenced by larcv::DataProductFactory::add_factory(), larcv::ConfigManager::AddConfigFile(), larcv::ParticleAna::AnalyzedQdX(), larcv::as_ndarray(), larcv::SegFiller::assert_dimension(), larcv::SimpleFiller::assert_dimension(), larcv::MultiClassFiller::assert_dimension(), larcv::ThreadDatumFiller::batch_process(), larcv::ProcessDriver::batch_process(), larcv::SegFiller::child_configure(), larcv::SimpleFiller::child_configure(), larcv::MultiClassFiller::child_configure(), larcv::SegFiller::compute_image_size(), larcv::SimpleFiller::compute_image_size(), larcv::MultiClassFiller::compute_image_size(), larcv::WireMask::configure(), larcv::ADCThreshold::configure(), larcv::QSumFilter::configure(), larcv::ResizeImage::configure(), larcv::ROISizeFilter::configure(), larcv::SegImageAna::configure(), larcv::SegmentMask::configure(), larcv::SegWeightInstance::configure(), larcv::SimpleDigitizer::configure(), larcv::SegWeightTrackShower::configure(), larcv::StepDigitizer::configure(), larcv::MeanSubtraction::configure(), larcv::Compressor::configure(), larcv::MergeTwoStream::configure(), larcv::ADCScale::configure(), larcv::ThreadDatumFiller::configure(), larcv::ProcessDriver::configure(), larcv::Binarize::configure(), larcv::SuperaOpDigit::configure(), supera::PulledPork3DSlicer::configure(), larcv::SuperaMCROI::configure(), larcv::IOManager< T >::configure(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::TrackerEventDisplay::CreateSelectedList(), larcv::RandomCropper::crop(), larcv::ThreadDatumFiller::data(), supera::PulledPork3DSlicer::DeriveMeta(), larcv::ThreadDatumFiller::dim(), larcv::SegFiller::fill_entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), larcv::MergeTwoStream::finalize(), larcv::IOManager< T >::get_data(), larcv::LArbysImage::get_image2d(), larcv::LArbysImage::get_rsee(), if(), larcv::ReadNueFile::initialize(), larcv::Compressor::initialize(), larcv::SegDatumFillerBase::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::ProcessDriver::initialize(), larcv::DatumFillerBase::initialize(), larcv::Run3DTracker::initialize(), larcv::TrackerEventDisplay::initialize(), larcv::ReadJarrettFile::initialize(), larcv::LArCVSuperaDriver::initialize(), larcv::ThreadDatumFiller::labels(), main(), larcv::ThreadDatumFiller::meta(), larcv::ThreadDatumFiller::multiplicities(), larcv::MergeTwoStream::override_ana_file(), larcv::ProcessDriver::override_ana_file(), larcv::MergeTwoStream::override_input_file(), larcv::MergeTwoStream::override_output_file(), larcv::IOManager< T >::prepare_input(), larcv::VertexFilter::process(), larcv::DeadWireAna::process(), larcv::UnionROI::process(), larcv::LEE1e1pAna::process(), larcv::LArbysImage::process(), larcv::WireMask::process(), larcv::SimpleDigitizer::process(), larcv::QSumFilter::process(), larcv::ModularPadImage::process(), larcv::ResizeImage::process(), larcv::ImageFromPixel2D::process(), larcv::ROICountFilter::process(), larcv::ROISizeFilter::process(), larcv::ImageFromPixel2DCluster::process(), larcv::SegImageAna::process(), larcv::MaskImage::process(), larcv::CosmicROIFiller::process(), larcv::SegWeightInstance::process(), larcv::SegWeightTrackShower::process(), larcv::SegmentMask::process(), larcv::CombineImages::process(), larcv::CosmicSegment::process(), larcv::ADCThreshold::process(), larcv::CropROI::process(), larcv::MultiROICropper::process(), larcv::MeanSubtraction::process(), larcv::ImageMerger::process(), larcv::SuperaMCPCluster::process(), larcv::Compressor::process(), larcv::OperateImage::process(), larcv::PyImageStitcher::process(), larcv::PyImageMaker::process(), larcv::PlaneImageMerger::process(), larcv::SuperaChStatus::process(), larcv::Binarize::process(), larcv::ROIAna::process(), larcv::SegDatumFillerBase::process(), larcv::SuperaOpDigit::process(), larcv::SuperaSimCh::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaKeyPointCluster::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), larcv::MergeTwoStream::process(), larcv::SuperaMCROI::process(), larcv::LArbysImagePID::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::ProcessDriver::process_entry(), larcv::ThreadDatumFiller::process_id(), larcv::ProcessDriver::process_id(), larcv::ThreadDatumFiller::process_ptr(), larcv::ProcessDriver::process_ptr(), larcv::ThreadDatumFiller::producer(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::product_type(), larcv::IOManager< T >::read_entry(), larcv::LArbysImage::Reconstruct(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::save_entry(), larcv::TrackerEventDisplay::SearchMap(), larcv::IOManager< T >::set_id(), larcv::ThreadDatumFiller::set_next_batch(), larcv::ThreadDatumFiller::set_next_index(), larcv::LArbysImage::StoreParticles(), supera::PulledPork3DSlicer::Test(), larcv::UnionROI::Union(), and larcv::ThreadDatumFiller::weights().
LARCV_DEBUG
#define LARCV_DEBUG () if(logger().debug ()) logger().send(::larcv::msg::kDEBUG, __FUNCTION__, __LINE__, __FILE__)
Compiler macro for DEBUG message.
Definition at line 137 of file larcv_logger.h.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::TrackShowerAna::Analyze(), larcv::ExampleAna::Analyze(), larcv::ParticleAna::AnalyzeAngle(), larcv::ParticleAna::AnalyzedQdX(), larcv::ParticleAna::AnalyzeParticle(), larcv::ThreadDatumFiller::batch_process(), larcv::ProcessDriver::batch_process(), larcv::TrackShowerAna::CalcAndFill(), larcv::VertexFilter::clear(), larcv::IOManager< T >::clear_entry(), larcv::TrackShowerAna::Configure(), larcv::VertexAna::configure(), larcv::LEE1e1pAna::configure(), larcv::PreProcessor::Configure(), larcv::LArbysImageMaker::Configure(), larcv::WireMask::configure(), larcv::ROIMerger::configure(), larcv::DoNothing::configure(), larcv::CosmicVertexAna::configure(), larcv::ProcessDriver::configure(), supera::MCROIMaker::configure(), larcv::ThreadDatumFiller::configure(), larcv::SegmentRelabel::configure(), larcv::DLCosmicTagImageMaker::Configure(), larcv::IOManager< T >::configure(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::SuperaKeyPointCluster::CreateCluster(), larcv::hires::HiResImageDivider::cropEventImages(), larcv::PreProcessor::EdgeConnected(), larcv::LArbysImageMaker::ExtractImage(), larcv::SegFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), larcv::VertexFilter::FillParticles(), larcv::LArbysRecoHolder::Filter(), larcv::LArbysRecoHolder::FilterMatches(), larcv::SuperaMCROI::FilterNode(), larcv::PGraphTruthMatch::finalize(), larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::TrackShowerAna::Finalize(), larcv::ThreadDatumFiller::finalize(), larcv::PIDImageMaker::finalize(), larcv::ProcessDriver::finalize(), larcv::IOManager< T >::finalize(), supera::MCParticleTree::FindPrimary(), larcv::SuperaMCROI::FormatMeta(), larcv::IOManager< T >::get_data(), larcv::LArbysImage::get_image2d(), larcv::DLCosmicTagUtil::go_to_entry(), larcv::PGraphTruthMatch::initialize(), larcv::LArbysImageAna::initialize(), larcv::NuFilter::initialize(), larcv::ProcessDriver::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::IOManager< T >::initialize(), larcv::hires::HiResImageDivider::LoadDivisionsFromFile(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::PreProcessor::MakePixelChunks(), larcv::LArbysRecoHolder::Match(), larcv::PreProcessor::MergePixelByFraction(), larcv::PreProcessor::MergeStraightShowers(), larcv::PreProcessor::MergeTracklets(), larcv::ThreadDatumFiller::meta(), larcv::PIDImageMaker::MPIDRecoImgFiller(), larcv::ProcessDriver::override_ana_file(), larcv::ProcessDriver::override_input_file(), larcv::ThreadDatumFiller::override_input_file(), larcv::ProcessDriver::override_output_file(), supera::MCROIMaker::ParticleROI(), larcv::IOManager< T >::prepare_input(), larcv::PreProcessor::PreProcess(), larcv::PreProcessor::PreProcessor(), larcv::PGraphTruthMatch::process(), larcv::ROIClipper::process(), larcv::VertexInROI::process(), larcv::LArbysImageFilter::process(), larcv::VertexFilter::process(), larcv::DeadWireAna::process(), larcv::UnionROI::process(), larcv::LArbysImageCheater::Process(), larcv::LArbysImageReAna::Process(), larcv::LArbysImageAna::process(), larcv::SSNetTruthAna::process(), larcv::CosmicPixelAna::process(), larcv::VertexAna::process(), larcv::LEE1e1pAna::process(), larcv::LArbysImageOut::process(), larcv::LArbysImage::process(), larcv::LArbysImageMC::process(), larcv::WireMask::process(), larcv::BadRegionAna::process(), larcv::SimplePixelAna::process(), larcv::CosmicTrackAna::process(), larcv::NuFilter::process(), larcv::BlankImage::process(), larcv::ROIMerger::process(), larcv::SegmentFilter::process(), larcv::MaskImage::process(), larcv::DBSCAN::process(), larcv::VertexImg::process(), larcv::ImageROICheckMC::process(), larcv::ROIMask::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::LArbysImagePID::process(), larcv::hires::HiResImageDivider::process(), larcv::ProcessDriver::process_entry(), larcv::ThreadDatumFiller::process_id(), larcv::ProcessDriver::process_id(), larcv::ThreadDatumFiller::process_map(), larcv::ProcessDriver::process_map(), larcv::ThreadDatumFiller::process_names(), larcv::ProcessDriver::process_names(), larcv::ThreadDatumFiller::process_ptr(), larcv::ProcessDriver::process_ptr(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::read_entry(), larcv::LArbysImage::Reconstruct(), larcv::IOManager< T >::register_producer(), larcv::ThreadDatumFiller::reset(), larcv::ProcessDriver::reset(), larcv::IOManager< T >::reset(), larcv::LArbysRecoHolder::Reset(), larcv::LArbysRecoHolder::ResetOutput(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), larcv::ThreadDatumFiller::set_next_batch(), larcv::LArbysImageReAna::SetPGraphProducer(), larcv::LArbysImageReAna::SetPixel2DProducer(), larcv::VertexInROI::SetROIIndex(), larcv::ReadNueFile::SetSplineLocation(), larcv::Run3DTracker::SetSplineLocation(), larcv::TrackerEventDisplay::SetSplineLocation(), larcv::ReadJarrettFile::SetSplineLocation(), larcv::LArbysImageReAna::SetVertexID(), larcv::LArbysRecoHolder::ShapeData(), larcv::PIDImageMaker::SPIDRecoImgFiller(), larcv::LArbysRecoHolder::StoreEvent(), larcv::LArbysImage::StoreParticles(), larcv::TrackShowerAna::TrackShowerAna(), larcv::UnionROI::Union(), larcv::SuperaMCROI::UpdatePrimaryROI(), supera::MCROIMaker::WireTimeBoundary(), larcv::LArbysRecoHolder::Write(), and supera::MCROIMaker::WTRange2BB().
LARCV_ERROR
#define LARCV_ERROR () if(logger().error ()) logger().send(::larcv::msg::kERROR, __FUNCTION__, __LINE__)
Compiler macro for ERROR message.
Definition at line 145 of file larcv_logger.h.
Referenced by larcv::SimpleFiller::assert_dimension(), larcv::MultiClassFiller::assert_dimension(), larcv::DLCosmicTagUtil::Configure(), larcv::IOManager< T >::configure(), larcv::ProcessFactory::create(), larcv::DataProductFactory::create(), larcv::SuperaMCROI::FormatMeta(), larcv::hires::HiResImageDivider::generateSingleCosmicDivision(), larcv::hires::HiResImageDivider::generateSingleMCDivision(), larcv::IOManager< T >::get_data(), larcv::DLCosmicTagUtil::getNumClusters(), larcv::DLCosmicTagUtil::go_to_entry(), larcv::IOManager< T >::initialize(), larcv::DLCosmicTagUtil::makeClusterTaggedImages(), larcv::DLCosmicTagUtil::makeCosmicMaskedImage(), larcv::DLCosmicTagUtil::makeIntimeCroppedImage(), larcv::SegmentAna::process(), larcv::ImageMerger::process(), larcv::EmbedImage::process(), larcv::VertexImg::process(), larcv::ROIMask::process(), larcv::SegmentRelabel::process(), larcv::hires::HiResImageDivider::process(), larcv::ProcessDriver::process_entry(), larcv::IOManager< T >::read_entry(), and larcv::IOManager< T >::save_entry().
LARCV_INFO
#define LARCV_INFO () if(logger().info ()) logger().send(::larcv::msg::kINFO, __FUNCTION__, __LINE__)
Compiler macro for INFO message.
Definition at line 139 of file larcv_logger.h.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::DataProductFactory::add_factory(), supera::PulledPork3DSlicer::AddConstraint(), larcv::PyImageStitcher::append_ndarray(), larcv::PyImageMaker::append_ndarray(), larcv::PyImageStitcher::append_ndarray_meta(), larcv::PyImageMaker::append_ndarray_meta(), larcv::hires::HiResImageDivider::CalculateDivisions(), larcv::MultiClassFiller::child_batch_end(), larcv::SegFiller::child_batch_end(), larcv::SimpleFiller::child_batch_end(), larcv::SimpleFiller::compute_image_size(), larcv::MultiClassFiller::compute_image_size(), larcv::PGraphTruthMatch::configure(), larcv::LArbysImage::configure(), larcv::BlankImage::configure(), larcv::DataStream::configure(), larcv::SegmentMaker::configure(), supera::ImageMetaFromConfig::configure(), larcv::VtxInRegion::configure(), larcv::SuperaBase::configure(), larcv::ThreadDatumFiller::configure(), larcv::ProcessDriver::configure(), supera::PulledPork3DSlicer::configure(), larcv::IOManager< T >::configure(), larcv::RSEFilter::configure(), larcv::SuperaKeyPointCluster::CreateCluster(), supera::MCParticleTree::DefinePrimary(), supera::MCParticleTree::DefineSecondary(), supera::PulledPork3DSlicer::DeriveMeta(), supera::MCParticleTree::EstimateSecondary(), larcv::SegFiller::fill_entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), larcv::ReadNueFile::FillMC(), larcv::Run3DTracker::FillMC(), larcv::LArbysTrash::finalize(), larcv::AlgoDataAna::finalize(), larcv::VtxInRegion::finalize(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::IOManager< T >::finalize(), larcv::SuperaMCROI::FormatMeta(), larcv::hires::HiResImageDivider::generateFitleredWholeImageDivision(), supera::PulledPork3DSlicer::GenerateMeta(), larcv::hires::HiResImageDivider::generateSingleMCDivision(), larcv::IOManager< T >::get_data(), larcv::ReadNueFile::initialize(), larcv::DataStream::initialize(), larcv::SegmentMaker::initialize(), larcv::VtxInRegion::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::ProcessDriver::initialize(), larcv::Run3DTracker::initialize(), larcv::TrackerEventDisplay::initialize(), larcv::ReadJarrettFile::initialize(), larcv::IOManager< T >::initialize(), larcv::hires::HiResImageDivider::isAbovePixelThreshold(), larcv::hires::HiResImageDivider::LoadDivisionsFromFile(), larcv::PreProcessor::MergeEndNubs(), larcv::PreProcessor::MergePixelByFraction(), larcv::PreProcessor::MergeStraightShowers(), larcv::ThreadDatumFiller::meta(), supera::MCROIMaker::ParticleROI(), larcv::IOManager< T >::prepare_input(), larcv::ReadNueFile::process(), larcv::CosmicPixelAna::process(), larcv::QSumFilter::process(), larcv::ResizeImage::process(), larcv::ROISizeFilter::process(), larcv::BlankImage::process(), larcv::DataStream::process(), larcv::DBSCAN::process(), larcv::MCSingleParticleFilter::process(), larcv::SegWeightInstance::process(), larcv::SegWeightTrackShower::process(), larcv::CCIncFilter::process(), larcv::MultiROICropper::process(), larcv::ImageMerger::process(), larcv::SegmentMaker::process(), larcv::ADCScale::process(), larcv::PyImageMaker::process(), larcv::VtxInRegion::process(), larcv::SegDatumFillerBase::process(), larcv::Binarize::process(), larcv::SuperaSimVoxel3D::process(), larcv::ROIMask::process(), larcv::SuperaKeyPointCluster::process(), larcv::MergeTwoStream::process(), larcv::SuperaMCROI::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), larcv::RSEFilter::process(), larcv::IOManager< T >::read_entry(), supera::MCParticleTree::Register(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), larcv::ThreadDatumFiller::set_next_batch(), larcv::LArCVSuperaDriver::SetDataPointer(), larcv::LArbysImageReAna::SetIOManager(), larcv::LArbysImageCheater::SetIOManager(), larcv::ReadNueFile::SetSplineLocation(), larcv::Run3DTracker::SetSplineLocation(), larcv::TrackerEventDisplay::SetSplineLocation(), larcv::ReadJarrettFile::SetSplineLocation(), larcv::LArbysImage::StoreParticles(), larcv::SuperaMCROI::UpdatePrimaryROI(), supera::MCROIMaker::WireTimeBoundary(), and supera::MCROIMaker::WTRange2BB().
LARCV_NORMAL
#define LARCV_NORMAL () if(logger().normal ()) logger().send(::larcv::msg::kNORMAL, __FUNCTION__)
Compiler macro for NORMAL message.
Definition at line 141 of file larcv_logger.h.
Referenced by larcv::MergeTwoStream::batch_process(), larcv::ProcessDriver::batch_process(), larcv::MeanSubtraction::configure(), larcv::MergeTwoStream::configure(), supera::MCROIMaker::configure(), larcv::ProcessDriver::configure(), larcv::ThreadDatumFiller::configure(), supera::PulledPork3DSlicer::configure(), larcv::IOManager< T >::configure(), larcv::ROICountFilter::finalize(), larcv::ThreadDatumFiller::finalize(), larcv::hires::HiResImageDivider::finalize(), larcv::ProcessDriver::finalize(), larcv::IOManager< T >::get_data(), larcv::ProcessDriver::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::MergeTwoStream::initialize(), larcv::DataProductFactory::list(), main(), larcv::IOManager< T >::prepare_input(), larcv::DoNothing::process(), larcv::MergeTwoStream::process(), larcv::SuperaMCROI::process(), larcv::hires::HiResImageDivider::process(), larcv::ProcessDriver::process_entry(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::set_id(), larcv::ThreadDatumFiller::set_next_batch(), and supera::PulledPork3DSlicer::Test().
LARCV_SCRITICAL
#define LARCV_SCRITICAL () larcv::logger::get_shared().send(::larcv::msg::kCRITICAL, __FUNCTION__,__LINE__,__FILE__)
Definition at line 154 of file larcv_logger.h.
Referenced by larcv::CSVData::get(), larcv::CSVData::read_file(), larcv::CSVData::read_line(), supera::SimCh2Pixel2DCluster(), and supera::Wire2Image2D().
LARCV_SDEBUG
#define LARCV_SDEBUG () if(larcv::logger::get_shared().debug()) larcv::logger::get_shared().send(::larcv::msg::kDEBUG, __FUNCTION__,__LINE__,__FILE__)
Definition at line 149 of file larcv_logger.h.
Referenced by supera::Wire2Image2D().
LARCV_SERROR
#define LARCV_SERROR () if(larcv::logger::get_shared().error()) larcv::logger::get_shared().send(::larcv::msg::kERROR, __FUNCTION__,__LINE__)
Definition at line 153 of file larcv_logger.h.
LARCV_SINFO
#define LARCV_SINFO () if(larcv::logger::get_shared().info()) larcv::logger::get_shared().send(::larcv::msg::kINFO, __FUNCTION__,__LINE__)
Definition at line 150 of file larcv_logger.h.
Referenced by supera::CreateImageMetaMaker(), supera::Hit2Image2D(), supera::SimCh2Image2D(), supera::SimCh2Voxel3D(), and supera::Wire2Image2D().
LARCV_SNORMAL
#define LARCV_SNORMAL () if(larcv::logger::get_shared().normal()) larcv::logger::get_shared().send(::larcv::msg::kNORMAL, __FUNCTION__)
Definition at line 151 of file larcv_logger.h.
LARCV_SWARNING
#define LARCV_SWARNING () if(larcv::logger::get_shared().warning()) larcv::logger::get_shared().send(::larcv::msg::kWARNING, __FUNCTION__)
Definition at line 152 of file larcv_logger.h.
LARCV_WARNING
#define LARCV_WARNING () if(logger().warning ()) logger().send(::larcv::msg::kWARNING, __FUNCTION__)
Compiler macro for WARNING message.
Definition at line 143 of file larcv_logger.h.
Referenced by larcv::SegFiller::assert_dimension(), larcv::SimpleFiller::assert_dimension(), larcv::MultiClassFiller::assert_dimension(), larcv::ProcessDriver::batch_process(), larcv::RunFilter::configure(), larcv::SegWeightInstance::configure(), larcv::SegWeightTrackShower::configure(), larcv::MergeTwoStream::configure(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::RSEFilter::finalize(), larcv::PGraphTruthMatch::process(), larcv::VertexInROI::process(), larcv::CosmicPixelAna::process(), larcv::VertexAna::process(), larcv::ImageFromPixel2DCluster::process(), larcv::SegmentMask::process(), larcv::CCQETruthFilter::process(), larcv::GoodcROIFilter::process(), larcv::PyImageStitcher::process(), larcv::ADCScale::process(), larcv::PyImageMaker::process(), larcv::ROIAna::process(), larcv::RSEFilter::process(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::set_id(), and larcv::LArbysRecoHolder::ShapeData().
Enumeration Type Documentation
IOMode_t [1/3]
template<class T > enum larcv::IOManager::IOMode_t
Enumerator
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
Definition at line 34 of file arxiv/IOManager.h.
 { kREAD, kWRITE, kBOTH };
IOMode_t [2/3]
template<class T > enum larcv::IOManager::IOMode_t
Enumerator
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
Definition at line 35 of file old/IOManager.h.
 { kREAD, kWRITE, kBOTH };
IOMode_t [3/3]
template<class T > enum larcv::IOManager::IOMode_t
Three IO modes: read, write, or read-and-write.
Enumerator
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
kREAD
kWRITE
kBOTH
Definition at line 37 of file IOManager.h.
 { kREAD, kWRITE, kBOTH };
Function Documentation
add_in_file()
template<class T > void larcv::IOManager< T >::add_in_file (const std::string filename, const std::string dirname = "") inline
Definition at line 58 of file arxiv/IOManager.h.
References larcv::IOManager< T >::_in_dir_v, and larcv::IOManager< T >::_in_file_v.
Referenced by larcv::MeanSubtraction::configure(), larcv::ViewROOT::initialize(), larcv::IOManager< T >::io_mode(), larcv::IOManager< T >::IOManager(), main(), larcv::ProcessDriver::override_input_file(), and larcv::ThreadDatumFiller::override_input_file().
     { _in_file_v.push_back(filename); _in_dir_v.push_back(dirname); }
clear_entry()
template<class T > void larcv::IOManager< T >::clear_entry ()
Definition at line 472 of file IOManager.cxx.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_last_event_id, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_set_event_id, larcv::EventBase::clear(), larcv::EventBase::event(), LARCV_DEBUG, larcv::EventBase::run(), larcv::EventBase::subrun(), and larcv::EventBase::valid().
Referenced by larcv::ProcessDriver::_process_entry_(), larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data(), larcv::IOManager< T >::io_mode(), and larcv::IOManager< T >::read_entry().
   {
     for(auto& p : _product_ptr_v) {
       if(!p) break;
       p->clear();
     }
     if(_set_event_id.valid()) {
       LARCV_DEBUG() << "Set _last_event_id to externally set values:"
             << " run = " << _set_event_id.run()
             << " subrun = " << _set_event_id.subrun()
             << " event = " << _set_event_id.event() << std::endl;
       _last_event_id = _set_event_id;
     }
     else {
       LARCV_DEBUG() << "Set _last_event_id to inherited values:"
             << " run = " << _event_id.run()
             << " subrun = " << _event_id.subrun()
             << " event = " << _event_id.event() << std::endl;
       _last_event_id = _event_id;
     }
     _event_id.clear();
     _set_event_id.clear();
   }
clear_in_file()
template<class T > void larcv::IOManager< T >::clear_in_file ()
Definition at line 60 of file IOManager.cxx.
References larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_out_file_name, larcv::larcv_base::name(), and larcv::IOManager< T >::set_out_file().
Referenced by larcv::IOManager< T >::io_mode(), larcv::ThreadDatumFiller::override_input_file(), and larcv::ProcessDriver::override_input_file().
   { _in_file_v.clear(); }
configure()
template<class T > void larcv::IOManager< T >::configure (const PSet & cfg)
Definition at line 75 of file IOManager.cxx.
References larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_in_tree_entries, larcv::IOManager< T >::_in_tree_index, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::_out_tree_index, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_read_id_bool, larcv::IOManager< T >::_read_only_name, larcv::IOManager< T >::_read_only_type, larcv::IOManager< T >::_store_only_bool, larcv::IOManager< T >::_store_only_name, larcv::IOManager< T >::_store_only_type, larcv::PSet::get(), larcv::IOManager< T >::initialize(), larcv::kProductUnknown, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, LARCV_NORMAL, larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), and larcv::larcv_base::set_verbosity().
Referenced by larcv::IOManager< T >::io_mode(), and larcv::IOManager< T >::IOManager().
   {
     if(_prepared) throw larbys("Cannot call configure() after initialize()!");
     set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     _io_mode = (IOMode_t)(cfg.get<unsigned short>("IOMode"));
     _out_file_name = cfg.get<std::string>("OutFileName","");
     // Figure out input files
     _in_file_v.clear();
     _in_file_v = cfg.get<std::vector<std::string> >("InputFiles",_in_file_v);
     _in_dir_v.clear();
     _in_dir_v = cfg.get<std::vector<std::string> >("InputDirs",_in_dir_v);
     if(_in_dir_v.empty()) _in_dir_v.resize(_in_file_v.size(),"");
     if(_in_dir_v.size()!=_in_file_v.size()) {
       LARCV_CRITICAL() << "# of input file (" << _in_file_v.size()
                << ") != # of input dir (" << _in_dir_v.size() << ")!" << std::endl;
       throw larbys();
     }
     _store_only_name = cfg.get<std::vector<std::string> >("StoreOnlyName",_store_only_name);
     std::vector<unsigned short> store_only_type;
     for(auto const& ptype : _store_only_type) store_only_type.push_back((unsigned short)ptype);
     store_only_type = cfg.get<std::vector<unsigned short> >("StoreOnlyType",store_only_type);
     _store_only_type.clear();
     for(auto const& ptype : store_only_type) {
       if(ptype >= (unsigned short)kProductUnknown) {
     LARCV_CRITICAL() << "StoreOnlyType contains invalid type: "
              << ptype << " (>=" << kProductUnknown << ")" << std::endl;
     throw larbys();
       }
       _store_only_type.push_back((ProductType_t)(ptype));
     }
     if(_store_only_name.size() != _store_only_type.size()) {
       LARCV_CRITICAL() << "StoreOnlyName and StoreOnlyType has different lengths!" << std::endl;
       throw larbys();
     }
     _read_only_name = cfg.get<std::vector<std::string> >("ReadOnlyName",_read_only_name);
     std::vector<unsigned short> read_only_type;
     for(auto const& ptype : _read_only_type) read_only_type.push_back((unsigned short)ptype);
     read_only_type = cfg.get<std::vector<unsigned short> >("ReadOnlyType",read_only_type);
     _read_only_type.clear();
     for(auto const& ptype : read_only_type) {
       if(ptype >= (unsigned short)kProductUnknown) {
     LARCV_CRITICAL() << "ReadOnlyType contains invalid type: "
              << ptype << " (>=" << kProductUnknown << ")" << std::endl;
     throw larbys();
       }
       _read_only_type.push_back((ProductType_t)(ptype));
     }
     if(_read_only_name.size() != _read_only_type.size()) {
       LARCV_CRITICAL() << "ReadOnlyName and ReadOnlyType has different lengths!" << std::endl;
       throw larbys();
     }
   }
current_entry()
template<class T > size_t larcv::IOManager< T >::current_entry () const inline
Definition at line 62 of file IOManager.h.
References larcv::IOManager< T >::_in_tree_index.
Referenced by larcv::LArbysImage::get_rsee(), larcv::PGraphTruthMatch::process(), larcv::LArbysImageFilter::process(), larcv::VertexFilter::process(), larcv::VertexInROI::process(), larcv::DeadWireAna::process(), larcv::ReadNueFile::process(), larcv::LArbysImageAna::process(), larcv::SSNetEventAna::process(), larcv::SSNetTruthAna::process(), larcv::CosmicPixelAna::process(), larcv::VertexAna::process(), larcv::LEE1e1pAna::process(), larcv::ParticleAna::process(), larcv::LArbysImageOut::process(), larcv::ExampleAna::process(), larcv::LArbysImage::process(), larcv::LArbysImageMC::process(), larcv::NuFilter::process(), larcv::SegmentFilter::process(), larcv::BadRegionAna::process(), larcv::CosmicTrackAna::process(), larcv::ReadRuiFile::process(), larcv::CosmicVertexAna::process(), larcv::ROIAna::process(), larcv::ImageROICheckMC::process(), larcv::LArbysImagePID::process(), larcv::Run3DTracker::process(), larcv::TrackerEventDisplay::process(), larcv::ReadJarrettFile::process(), and larcv::PIDImageMaker::process().
 { return _in_tree_index; }
event_id()
template<class T > const EventBase& larcv::IOManager< T >::event_id () const inline
Definition at line 88 of file IOManager.h.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_set_event_id, and larcv::EventBase::valid().
Referenced by larcv::LArbysImageFilter::process(), larcv::LArbysImageAna::process(), larcv::LArbysImageOut::process(), larcv::PyImageMaker::process(), larcv::PyImageStitcher::process(), and larcv::hires::HiResImageDivider::process().
 { return ( _set_event_id.valid() ? _set_event_id : _event_id ); }
file_list()
template<class T > const std::vector<std::string>& larcv::IOManager< T >::file_list () const inline
Definition at line 99 of file IOManager.h.
References larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
Referenced by larcv::RSEFilter::process().
     { return _in_file_v; }
finalize()
template<class T > void larcv::IOManager< T >::finalize ()
Definition at line 231 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_product_v, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_DEBUG, LARCV_INFO, and larcv::IOManager< T >::reset().
Referenced by larlite::ChStatusFinder::analyze(), larcv::MeanSubtraction::configure(), larcv::GenDeadChannelMap::finalize(), larcv::ThreadDatumFiller::finalize(), larcv::ProcessDriver::finalize(), larcv::IOManager< T >::io_mode(), main(), larcv::IOManager< T >::set_id(), larcv::IOManager< T >::set_out_file(), and larcv::ViewROOT::~ViewROOT().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(_io_mode != kWRITE) {
       LARCV_INFO() << "Deleting input TChains" << std::endl;
       for(auto& t : _in_tree_v) {if(!t) break; delete t;};
     }
     if(_io_mode != kREAD) {
       _out_file->cd();
       for(auto& t : _out_tree_v) {
     if(!t) break;
     LARCV_INFO() << "Writing " << t->GetName() << " with " << t->GetEntries() << " entries" << std::endl;
     t->Write();
       }
       LARCV_INFO() << "Closing output file" << std::endl;
       _out_file->Close();
       _out_file = nullptr;
     }
     LARCV_INFO() << "Deleting data pointers" << std::endl;
     for(auto& p : _product_v) { delete p; }
     reset();
   }
get_data() [1/5]
template<class T > std::vector< T > & larcv::IOManager< T >::get_data (const std::string & producer)
Definition at line 191 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_tree_entries, larcv::supera::Fill(), larcv::kINVALID_SIZE, larcv::IOManager< T >::kREAD, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, LARCV_NORMAL, larcv::IOManager< T >::producer_id(), and larcv::IOManager< T >::register_producer().
Referenced by larlite::ChStatusFinder::analyze(), larcv::ImageROICheckMC::CheckNumNuROIs(), larcv::MeanSubtraction::configure(), larcv::LArbysImageMaker::ConstructCosmicImage(), larcv::ViewROOT::draw(), larcv::DumpHiResCropImages::DumpBGRImage(), larcv::GenDeadChannelMap::finalize(), larcv::IOManager< T >::get_data(), larcv::LArbysImage::get_image2d(), larcv::IOManager< T >::get_n_entries(), larcv::LArbysImage::get_rsee(), main(), larcv::PGraphTruthMatch::process(), larcv::ROIClipper::process(), larcv::ROIPad::process(), larcv::VertexFilter::process(), larcv::VertexInROI::process(), larcv::ReadNueFile::process(), larcv::DeadWireAna::process(), larcv::SSNetEventAna::process(), larcv::LArbysImageCheater::Process(), larcv::LArbysImageReAna::Process(), larcv::UnionROI::process(), larcv::LArbysImageExtract::process(), larcv::SSNetTruthAna::process(), larcv::CosmicPixelAna::process(), larcv::VertexAna::process(), larcv::LEE1e1pAna::process(), larcv::ExampleAna::process(), larcv::ParticleAna::process(), larcv::LArbysImage::process(), larcv::LArbysImageMC::process(), larcv::WireMask::process(), larcv::BadRegionAna::process(), larcv::ModularPadImage::process(), larcv::NuFilter::process(), larcv::ADCThreshold::process(), larcv::CosmicROIFiller::process(), larcv::CCIncFilter::process(), larcv::ROIMerger::process(), larcv::QSumFilter::process(), larcv::CosmicSegment::process(), larcv::ImageFromPixel2D::process(), larcv::SimpleDigitizer::process(), larcv::ChannelMax::process(), larcv::ResizeImage::process(), larcv::ImageFromPixel2DCluster::process(), larcv::ROICountFilter::process(), larcv::CosmicTrackAna::process(), larcv::CropROI::process(), larcv::ROISizeFilter::process(), larcv::RunFilter::process(), larcv::SegImageAna::process(), larcv::DataStream::process(), larcv::SegmentAna::process(), larcv::SingleROIFaker::process(), larcv::SegmentMask::process(), larcv::DBSCAN::process(), larcv::MaskImage::process(), larcv::SegWeightTrackShower::process(), larcv::SimplePixelAna::process(), larcv::SegWeightInstance::process(), larcv::StepDigitizer::process(), larcv::SliceImages::process(), larcv::BlankImage::process(), larcv::DoNothing::process(), larcv::SegmentFilter::process(), larcv::CombineImages::process(), larcv::MCFilter::process(), larcv::MCSingleParticleFilter::process(), larcv::EmptyImageFilter::process(), larcv::ChStatusConverter::process(), larcv::MultiROICropper::process(), larcv::CCQETruthFilter::process(), larcv::ImageChargeAna::process(), larcv::ImageMerger::process(), larcv::Compressor::process(), larcv::SegmentMaker::process(), larcv::MeanSubtraction::process(), larcv::ADCScaleAna::process(), larcv::SuperaMCPCluster::process(), larcv::OperateImage::process(), larcv::ADCScale::process(), larcv::GoodcROIFilter::process(), larcv::PlaneImageMerger::process(), larcv::PreProcessorAna::process(), larcv::PyImageStitcher::process(), larcv::ReadRuiFile::process(), larcv::PyImageMaker::process(), larcv::CosmicFilter::process(), larcv::VertexImg::process(), larcv::GenDeadChannelMap::process(), larcv::CosmicVertexAna::process(), larcv::EmbedImage::process(), larcv::VtxInRegion::process(), larcv::DumpHiResCropImages::process(), larcv::SuperaChStatus::process(), larcv::ROIAna::process(), larcv::SegDatumFillerBase::process(), larcv::Binarize::process(), larcv::NNCosine::process(), larcv::ROIMask::process(), larcv::SuperaSimCh::process(), larcv::HistADC::process(), larcv::SuperaSimVoxel3D::process(), larcv::SuperaOpDigit::process(), larcv::calcPeakADC::process(), larcv::pmtweights::PMTWeightImageBuilder::process(), larcv::SuperaKeyPointCluster::process(), larcv::SegmentRelabel::process(), larcv::SuperaWire::process(), larcv::SuperaHit::process(), larcv::SuperaMCROI::process(), larcv::LArbysImagePID::process(), larcv::Run3DTracker::process(), larcv::TrackerEventDisplay::process(), larcv::ReadJarrettFile::process(), larcv::DatumFillerBase::process(), larcv::PIDImageMaker::process(), larcv::hires::HiResImageDivider::process(), larcv::RSEFilter::process(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::set_out_file(), larcv::LArbysImage::StoreParticles(), and larcv::ImageROICheckMC::VertexInFid().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(producer.empty()) {
       LARCV_CRITICAL() << "Empty producer name (invalid)" << std::endl;
       throw larbys();
     }
     auto id = producer_id(producer);
     if(id == kINVALID_SIZE) {
       if(_io_mode == kREAD) {
     LARCV_ERROR() << "Invalid producer requested:" << producer << std::endl;
     throw larbys();
       }
       id = register_producer(producer);
       for(size_t i=0; i<_tree_entries; ++i) _out_tree_v[id]->Fill();
       LARCV_NORMAL() << "Created TTree " << _out_tree_v[id]->GetName() << " (id=" << id <<") w/ " << _tree_entries << " entries..." << std::endl;
     }
     return get_data(id);
   }
get_data() [2/5]
template<class T > EventBase * larcv::IOManager< T >::get_data (const size_t id)
Definition at line 214 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_product_v, larcv::IOManager< T >::_tree_index, larcv::kINVALID_SIZE, larcv::IOManager< T >::kWRITE, LARCV_DEBUG, and LARCV_ERROR.
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(id >= _product_ctr) {
       LARCV_ERROR() << "Invalid producer ID requested:" << id << std::endl;
       throw larbys();
     }
     if(_io_mode != kWRITE && _tree_index && _tree_index != kINVALID_SIZE &&
        _in_tree_index_v[id] != _tree_index) {
       _in_tree_v[id]->GetEntry(_tree_index);
       _in_tree_index_v[id] =_tree_index;
     }
     return *(_product_v[id]);
   }
get_data() [3/5]
template<class T > EventBase * larcv::IOManager< T >::get_data (const ProductType_t type, const std::string & producer)
Definition at line 517 of file IOManager.cxx.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_in_tree_index, larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_read_id_bool, larcv::EventBase::event(), larcv::supera::Fill(), larcv::IOManager< T >::get_data(), larcv::kINVALID_SIZE, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, LARCV_NORMAL, larcv::IOManager< T >::producer_id(), larcv::ProductName(), larcv::IOManager< T >::register_producer(), larcv::EventBase::run(), larcv::EventBase::subrun(), and larcv::EventBase::valid().
   {
     LARCV_DEBUG() << "start" << std::endl;
     auto id = producer_id(type,producer);
     if(id == kINVALID_SIZE) {
       if(_io_mode == kREAD) {
     LARCV_ERROR() << "Invalid producer requested: " << producer << " for " << ProductName(type) << std::endl;
     throw larbys();
       }
       id = register_producer(type,producer);
       for(size_t i=0; i<_in_tree_index; ++i) _out_tree_v[id]->Fill();
       LARCV_NORMAL() << "Created TTree " << _out_tree_v[id]->GetName() << " (id=" << id <<") w/ " << _in_tree_index << " entries..." << std::endl;
     }
     return get_data(id);
   }
get_data() [4/5]
template<class T > template<class T > T& larcv::IOManager< T >::get_data (const std::string & producer) inline
Definition at line 73 of file IOManager.h.
References larcv::IOManager< T >::get_data().
     { return *((T*)(get_data(ProductType<T>(),producer))); }
get_data() [5/5]
template<class T > template<class T > T& larcv::IOManager< T >::get_data (const ProducerID_t id) inline
Definition at line 76 of file IOManager.h.
References larcv::IOManager< T >::get_data(), LARCV_CRITICAL, larcv::IOManager< T >::product_type(), and larcv::ProductName().
     {
       auto const type = product_type(id);
       if(ProductType<T>() != type) {
     LARCV_CRITICAL() << "Unmatched type (in memory type = " << ProductName(type)
              << " while specialization type = " << ProductName(ProductType<T>())
              << std::endl;
     throw larbys();
       }
       return *((T*)(get_data(id)));
     }
get_n_entries()
template<class T > size_t larcv::IOManager< T >::get_n_entries () const inline
Definition at line 64 of file IOManager.h.
References larcv::IOManager< T >::_in_tree_entries, larcv::IOManager< T >::_out_tree_entries, and larcv::IOManager< T >::get_data().
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::ThreadDatumFiller::batch_process(), larcv::ProcessDriver::batch_process(), larcv::ThreadDatumFiller::get_n_entries(), larlite::ChStatusFinder::initialize(), larcv::ProcessDriver::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::MergeTwoStream::initialize(), main(), larcv::ReadNueFile::process(), larcv::ReadRuiFile::process(), larcv::Run3DTracker::process(), larcv::TrackerEventDisplay::process(), and larcv::ReadJarrettFile::process().
     { return (_in_tree_entries ? _in_tree_entries : _out_tree_entries); }
initialize()
template<class T > bool larcv::IOManager< T >::initialize ()
Definition at line 10 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_tree_entries, larcv::IOManager< T >::_tree_index, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, and larcv::IOManager< T >::prepare_input().
Referenced by larcv::MeanSubtraction::configure(), larcv::IOManager< T >::configure(), larcv::GenDeadChannelMap::finalize(), larlite::ChStatusFinder::initialize(), larcv::ThreadDatumFiller::initialize(), larcv::ProcessDriver::initialize(), larcv::ViewROOT::initialize(), larcv::IOManager< T >::io_mode(), main(), and larcv::IOManager< T >::set_out_file().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(_io_mode != kREAD) {
       if(_out_file_name.empty()) throw larbys("Must set output file name!");
       LARCV_INFO() << "Opening an output file: " << _out_file_name << std::endl;
       _out_file = TFile::Open(_out_file_name.c_str(),"RECREATE");
     }
     if(_io_mode != kWRITE) {
       prepare_input();
       if(!_tree_entries) {
     LARCV_ERROR() << "Found 0 entries from input files..." << std::endl;
     return false;
       }
     }
     _tree_index = 0;
     _prepared = true;
     return true;
   }
io_mode()
template<class T > IOMode_t larcv::IOManager< T >::io_mode () const inline
IO mode accessor.
Definition at line 48 of file IOManager.h.
References larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::clear_in_file(), larcv::IOManager< T >::configure(), larcv::IOManager< T >::finalize(), larcv::IOManager< T >::initialize(), larcv::larcv_base::name(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::product_type(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
Referenced by larcv::ProcessDriver::_process_entry_(), larcv::ProcessDriver::batch_process(), larcv::ProcessDriver::initialize(), and larcv::ProcessDriver::process_entry().
 { return _io_mode;}
IOManager() [1/3]
template<class T > larcv::IOManager< T >::IOManager (IOMode_t mode = kREAD) inline
Default constructor.
Definition at line 37 of file arxiv/IOManager.h.
References larcv::IOManager< T >::reset().
       : _io_mode       ( mode          )
       , _prepared      ( false         )
       , _out_file      ( nullptr       )
       , _tree_index    ( 0             )
       , _tree_entries  ( 0             )
       , _out_file_name ( ""            )
       , _in_file_v     ()
       , _in_dir_v      ()
       , _key_list      ( kProductUnknown )
       , _out_tree_v    ()
       , _in_tree_v     ()
       , _in_tree_index_v ()
       , _product_v     ()
       , _product_ctr   (0)
     { reset(); }
IOManager() [2/3]
template<class T > larcv::IOManager< T >::IOManager (IOMode_t mode = kREAD, std::string name = "IOManager< T >")
Default constructor.
Definition at line 11 of file IOManager.cxx.
References larcv::IOManager< T >::reset().
     : larcv_base(name)
     , _io_mode          ( mode          )
     , _prepared         ( false         )
     , _out_file         ( nullptr       )
     , _in_tree_index    ( 0             )
     , _out_tree_index   ( 0             )
     , _in_tree_entries  ( 0             )
     , _out_tree_entries ( 0             )
     , _out_file_name    ( ""            )
     , _in_file_v        ()
     , _in_dir_v         ()
     , _key_list         ( kProductUnknown )
     , _out_tree_v       ()
     , _in_tree_v        ()
     , _in_tree_index_v  ()
     , _product_ctr      (0)
     , _product_ptr_v    ()
     , _product_type_v   ()
   { reset(); }
IOManager() [3/3]
template<class T > larcv::IOManager< T >::IOManager (const PSet & cfg)
Configuration PSet construction so you don't have to call setter functions.
Definition at line 32 of file IOManager.cxx.
References larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::configure(), and larcv::IOManager< T >::reset().
     : larcv_base(cfg.get<std::string>("Name"))
     , _io_mode          ( kREAD         )
     , _prepared         ( false         )
     , _out_file         ( nullptr       )
     , _in_tree_index    ( 0             )
     , _out_tree_index   ( 0             )
     , _in_tree_entries  ( 0             )
     , _out_tree_entries ( 0             )
     , _out_file_name    ( ""            )
     , _in_file_v        ()
     , _in_dir_v         ()
     , _key_list         ( kProductUnknown )
     , _out_tree_v       ()
     , _in_tree_v        ()
     , _in_tree_index_v  ()
     , _product_ctr      (0)
     , _product_ptr_v    ()
     , _product_type_v   ()
   {
     reset();
     configure(cfg);
   }
last_event_id()
template<class T > const EventBase& larcv::IOManager< T >::last_event_id () const inline
Definition at line 90 of file IOManager.h.
References larcv::IOManager< T >::_last_event_id.
Referenced by larcv::ProcessDriver::event_id().
 { return _last_event_id; }
prepare_input()
template<class T > void larcv::IOManager< T >::prepare_input () private
Definition at line 38 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_tree_entries, larcv::kINVALID_SIZE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, and larcv::IOManager< T >::register_producer().
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_out_file().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(_product_ctr) {
       LARCV_CRITICAL() << "Cannot call prepare_input before calling reset()!" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << "Start inspecting " << _in_file_v.size() << "files" << std::endl;
     for(size_t i=0; i<_in_file_v.size(); ++i) {
       auto const& fname = _in_file_v[i];
       auto const& dname = _in_dir_v[i];
       TFile *fin = TFile::Open(fname.c_str(),"READ");
       if(!fin) {
     LARCV_CRITICAL() << "Open attempt failed for a file: " << fname << std::endl;
     throw larbys();
       }
       LARCV_NORMAL() << "Opening a file in READ mode: " << fname << std::endl;
       TDirectoryFile* fin_dir = 0;
       if(dname.empty()) fin_dir = fin;
       else {
     TObject* obj = fin->Get(dname.c_str());
     if(!obj || std::string(obj->ClassName())!="TDirectoryFile") {
       LARCV_CRITICAL() << "Could not locate TDirectoryFile: " << dname << std::endl;
       throw larbys();
     }
     fin_dir = (TDirectoryFile*)obj;
       }
       TList* key_list = fin_dir->GetListOfKeys();
       TIter key_iter(key_list);
       while(1) {
     TObject* obj = key_iter.Next();
     if(!obj) break;
     obj = fin_dir->Get(obj->GetName());
     LARCV_DEBUG() << "Found object " << obj->GetName() << " (type=" << obj->ClassName() << ")" << std::endl;
     if(std::string(obj->ClassName())!="TTree") {
       LARCV_DEBUG() << "Skipping " << obj->GetName() << " ... (not TTree)" << std::endl;
       continue;
     }
     std::string obj_name = obj->GetName();
     char c[2] = "_";
     if(obj_name.find_first_of(c) > obj_name.size() ||
        obj_name.find_first_of(c) == obj_name.find_last_of(c)) {
         LARCV_INFO() << "Skipping " << obj->GetName() << " ... (not LArCV TTree)" << std::endl;
         continue;
     }
     std::string type_name( obj_name.substr(0,obj_name.find_first_of(c)) );
     std::string suffix( obj_name.substr(obj_name.find_last_of(c)+1, obj_name.size()-obj_name.find_last_of(c)) );
     std::string producer_name( obj_name.substr(obj_name.find_first_of(c)+1,obj_name.find_last_of(c)-obj_name.find_first_of(c)-1) );
     if(suffix != "tree") {
       LARCV_INFO() << "Skipping " << obj->GetName() << " ... (not LArCV TTree)" << std::endl;
       continue;
     }
     if(type_name != ProductName<T>()) {
       LARCV_INFO() << "Ignoring TTree " << obj->GetName() << " (not " << ProductName<T>() << " type)" << std::endl;
       continue;
     }
     auto id = register_producer(producer_name);
     LARCV_INFO() << "Registered: producer=" << producer_name << " Key=" << id << std::endl;
     _in_tree_v[id]->AddFile(fname.c_str());
       }
     }
     if(!_in_tree_v.front()) {
       _tree_entries = 0;
       return;
     }
     // Get tree entries
     _tree_entries = kINVALID_SIZE;
     for(auto const& t : _in_tree_v) {
       if(!t) break;
       size_t tmp_entries = t->GetEntries();
       LARCV_INFO() << "TTree " << t->GetName() << " has " << tmp_entries << " entries" << std::endl;
       if(!_tree_entries) _tree_entries = tmp_entries;
       else _tree_entries = (_tree_entries < tmp_entries ? _tree_entries : tmp_entries);
     }
   }
producer_id() [1/2]
template<class T > ProducerID_t larcv::IOManager< T >::producer_id (const ProductType_t type, const std::string & producer) const
Definition at line 496 of file IOManager.cxx.
References larcv::IOManager< T >::_key_list, larcv::kINVALID_PRODUCER, larcv::kProductUnknown, LARCV_CRITICAL, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(producer.empty()) {
       LARCV_CRITICAL() << "Empty producer name (invalid)" << std::endl;
       throw larbys();
     }
     if(type==kProductUnknown) {
       LARCV_CRITICAL() << "Queried kProductUnknown type!" << std::endl;
       throw larbys();
     }
     auto& m = _key_list[type];
     auto iter = m.find(producer);
     if(iter == m.end()) {
       return kINVALID_PRODUCER;
     }
     return (*iter).second;
   }
producer_id() [2/2]
template<class T > size_t larcv::IOManager< T >::producer_id (const std::string & producer) const
Definition at line 180 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_key_m, larcv::kINVALID_SIZE, and LARCV_DEBUG.
Referenced by larcv::IOManager< T >::get_data(), larcv::IOManager< T >::io_mode(), larcv::CosmicSegment::process(), larcv::ADCScaleAna::process(), larcv::ADCScale::process(), larcv::SegDatumFillerBase::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), and larcv::IOManager< T >::set_out_file().
   {
     LARCV_DEBUG() << "start" << std::endl;
     auto iter = _key_m.find(producer);
     if(iter == _key_m.end()) {
       return kINVALID_SIZE;
     }
     return (*iter).second;
   }
producer_list()
template<class T > const std::vector<std::string> larcv::IOManager< T >::producer_list (const ProductType_t type) const inline
Definition at line 92 of file IOManager.h.
References larcv::IOManager< T >::_key_list.
     {
       std::vector<std::string> res;
       for(auto const& key_value : _key_list[type]) res.push_back(key_value.first);
       return res;
     }
product_type()
template<class T > ProductType_t larcv::IOManager< T >::product_type (const size_t id) const
Definition at line 66 of file IOManager.cxx.
References larcv::IOManager< T >::_product_type_v, and LARCV_CRITICAL.
Referenced by larcv::IOManager< T >::get_data(), and larcv::IOManager< T >::io_mode().
   {
     if( id > _product_type_v.size() ) {
       LARCV_CRITICAL() << "Product ID " << id << " does not exist... " << std::endl;
       throw larbys();
     }
     return _product_type_v[id];
   }
read_entry() [1/2]
template<class T > bool larcv::IOManager< T >::read_entry (const size_t index, bool force_reload = false)
Definition at line 363 of file IOManager.cxx.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_in_tree_entries, larcv::IOManager< T >::_in_tree_index, larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_tree_entries, larcv::IOManager< T >::_out_tree_index, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_set_event_id, larcv::IOManager< T >::_store_only_bool, larcv::EventBase::clear(), larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::kBOTH, larcv::kINVALID_SIZE, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, LARCV_INFO, LARCV_WARNING, larcv::IOManager< T >::save_entry(), and larcv::IOManager< T >::set_id().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(_io_mode == kWRITE) {
       LARCV_WARNING() << "Nothing to read in kWRITE mode..." << std::endl;
       return false;
     }
     if(!_prepared) {
       LARCV_CRITICAL() << "Cannot be called before initialize()!" << std::endl;
       throw larbys();
     }
     if(index >= _in_tree_entries) {
       LARCV_ERROR() << "Input only has " << _in_tree_entries << " entries!" << std::endl;
       return false;
     }
     if(_in_tree_index != index) {
       _in_tree_index = index;
       _event_id.clear();
       _set_event_id.clear();
     }else if(force_reload){
       _in_tree_index = index;
       for(auto& v : _in_tree_index_v) v = kINVALID_SIZE;
       _event_id.clear();
       _set_event_id.clear();
     }
     LARCV_DEBUG() << "Current input tree index: " << _in_tree_index << std::endl;
     return true;
   }
read_entry() [2/2]
template<class T > bool larcv::IOManager< T >::read_entry (const size_t index)
Definition at line 130 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_tree_entries, larcv::IOManager< T >::_tree_index, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, and LARCV_WARNING.
Referenced by larlite::ChStatusFinder::analyze(), larcv::ThreadDatumFiller::batch_process(), larcv::ProcessDriver::batch_process(), larcv::MeanSubtraction::configure(), larcv::IOManager< T >::io_mode(), main(), larcv::ProcessDriver::process_entry(), larcv::IOManager< T >::set_out_file(), and larcv::ViewROOT::setEntry().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(_io_mode == kWRITE) {
       LARCV_WARNING() << "Nothing to read in kWRITE mode..." << std::endl;
       return false;
     }
     if(!_prepared) {
       LARCV_CRITICAL() << "Cannot be called before initialize()!" << std::endl;
       throw larbys();
     }
     if(index >= _tree_entries) {
       LARCV_ERROR() << "Input only has " << _tree_entries << " entries!" << std::endl;
       return false;
     }
     _tree_index = index;
     LARCV_DEBUG() << "Current tree index: " << _tree_index << std::endl;
     return true;
   }
register_producer() [1/2]
template<class T > size_t larcv::IOManager< T >::register_producer (const std::string & name) private
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_out_file().
register_producer() [2/2]
template<class T > size_t larcv::IOManager< T >::register_producer (const ProductType_t type, const std::string & name) private
Definition at line 175 of file IOManager.cxx.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_in_tree_entries, larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_key_list, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_product_type_v, larcv::IOManager< T >::_read_only_name, larcv::IOManager< T >::_read_only_type, larcv::IOManager< T >::_set_event_id, larcv::DataProductFactory::create(), larcv::EventBase::event(), larcv::DataProductFactory::get(), larcv::kINVALID_SIZE, larcv::kProductUnknown, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, larcv::IOManager< T >::prepare_input(), larcv::ProductName(), larcv::IOManager< T >::register_producer(), larcv::EventBase::run(), larcv::EventBase::subrun(), and larcv::EventBase::valid().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(type == kProductUnknown) {
       LARCV_CRITICAL() << "Cannot register a producer " << name << " for kProductUnknown!" << std::endl;
       throw larbys();
     }
     auto& key_m = _key_list[type];
     auto in_iter = key_m.find(name);
     std::string tree_name = std::string(ProductName(type)) + "_" + name + "_tree";
     std::string tree_desc = name + " tree";
     std::string br_name = std::string(ProductName(type)) + "_" + name + "_branch";
     LARCV_INFO() << "Requested to register a producer: " << name << " (TTree " << tree_name << ")" << std::endl;
     if(in_iter != key_m.end()) {
       LARCV_INFO() << "... already registered. Returning a registered key " << (*in_iter).second << std::endl;
       return (*in_iter).second;
     }
     _product_ptr_v[_product_ctr] = (EventBase*)(DataProductFactory::get().create(type,name));
     _product_type_v[_product_ctr] = type;
     const ProducerID_t id = _product_ctr;
     key_m.insert(std::make_pair(name,id));
     _product_ctr+=1;
     LARCV_INFO() << "It is a new producer registration (key=" << id << ")" << std::endl;
     // Set event ID
     if(_event_id.valid()) {
       _product_ptr_v[id]->_run    = _event_id.run();
       _product_ptr_v[id]->_subrun = _event_id.subrun();
       _product_ptr_v[id]->_event  = _event_id.event();
     }else if(_set_event_id.valid()) {
       _product_ptr_v[id]->_run    = _set_event_id.run();
       _product_ptr_v[id]->_subrun = _set_event_id.subrun();
       _product_ptr_v[id]->_event  = _set_event_id.event();
     }
     if(_io_mode != kWRITE) {
       LARCV_INFO() << "kREAD/kBOTH mode: creating an input TChain" << std::endl;
       LARCV_DEBUG() << "Branch name: " << br_name << " data pointer: " << _product_ptr_v[id] << std::endl;
       auto in_tree_ptr = new TChain(tree_name.c_str(),tree_desc.c_str());
       in_tree_ptr->SetBranchAddress(br_name.c_str(), &(_product_ptr_v[id]));
       _in_tree_v[id] = in_tree_ptr;
       _in_tree_index_v.push_back(kINVALID_SIZE);
     }
     if(_io_mode != kREAD) {
       LARCV_INFO() << "kWRITE/kBOTH mode: creating an output TTree" << std::endl;
       LARCV_DEBUG() << "Branch name: " << br_name << " data pointer: " << _product_ptr_v[id] << "(" << id <<"/"<<_product_ptr_v.size()<<")"<<std::endl;
       _out_file->cd();
       _out_tree_v[id] = new TTree(tree_name.c_str(),tree_desc.c_str());
       auto out_br_ptr = _out_tree_v[id]->Branch(br_name.c_str(), &(_product_ptr_v[id]));
       LARCV_DEBUG() << "Created TTree @ " << _out_tree_v[id] << " ... TBranch @ " << out_br_ptr << std::endl;
     }
     return id;
   }
reset()
template<class T > void larcv::IOManager< T >::reset ()
Definition at line 259 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_key_m, larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_product_type_v, larcv::IOManager< T >::_tree_entries, larcv::IOManager< T >::_tree_index, larcv::kProductUnknown, and LARCV_DEBUG.
Referenced by larcv::IOManager< T >::finalize(), larcv::IOManager< T >::io_mode(), larcv::IOManager< T >::IOManager(), larcv::ThreadDatumFiller::reset(), larcv::ProcessDriver::reset(), larcv::IOManager< T >::set_id(), larcv::IOManager< T >::~IOManager(), and larcv::ViewROOT::~ViewROOT().
   {
     LARCV_DEBUG() << "start" << std::endl;
     _in_tree_v.clear();
     _in_tree_v.resize(1000,nullptr);
     _in_tree_index_v.clear();
     _out_tree_v.clear();
     _out_tree_v.resize(1000,nullptr);
     _product_ptr_v.clear();
     _product_ptr_v.resize(1000,nullptr);
     _product_type_v.clear();
     _product_type_v.resize(1000,kProductUnknown);
     _product_ctr = 0;
     _tree_index = 0;
     _tree_entries = 0;
     _prepared = false;
     _out_file_name = "";
     _in_file_v.clear();
     _in_dir_v.clear();
     _key_m.clear();
   }
save_entry()
template<class T > bool larcv::IOManager< T >::save_entry ()
Definition at line 151 of file arxiv/IOManager.cxx.
References larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_tree_entries, larcv::IOManager< T >::_tree_index, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, and LARCV_INFO.
Referenced by larcv::ProcessDriver::_process_entry_(), larcv::GenDeadChannelMap::finalize(), larcv::IOManager< T >::io_mode(), main(), larcv::hires::HiResImageDivider::process(), larcv::IOManager< T >::read_entry(), and larcv::IOManager< T >::set_out_file().
   {
     LARCV_DEBUG() << "start" << std::endl;
     if(!_prepared) {
       LARCV_CRITICAL() << "Cannot be called before initialize()!" << std::endl;
       throw larbys();
     }
     if(_io_mode == kREAD) {
       LARCV_ERROR() << "Cannot save in READ mode..." << std::endl;
       return false;
     }
     LARCV_INFO() << "Saving new entry " << std::endl;
     for(auto& t : _out_tree_v) {
       if(!t) break;
       LARCV_DEBUG() << "Saving " << t->GetName() << " entry " << t->GetEntries() << std::endl;
       t->Fill();
     }
     _tree_entries += 1;
     if(_io_mode == kWRITE) _tree_index += 1;
     return true;
   }
set_id() [1/2]
template<class T > void larcv::IOManager< T >::set_id (const size_t run, const size_t subrun, const size_t event)
Definition at line 567 of file IOManager.cxx.
References larcv::EventBase::_event, larcv::IOManager< T >::_io_mode, larcv::EventBase::_run, larcv::IOManager< T >::_set_event_id, larcv::EventBase::_subrun, larcv::EventBase::event_key(), larcv::IOManager< T >::kREAD, LARCV_CRITICAL, LARCV_INFO, and larcv::EventBase::valid().
Referenced by larcv::GenDeadChannelMap::finalize(), main(), larcv::ImageMerger::process(), larcv::PyImageStitcher::process(), larcv::PyImageMaker::process(), larcv::hires::HiResImageDivider::process(), larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::set_id(), and larcv::ProcessDriver::set_id().
{
     if(_io_mode == kREAD) {
       LARCV_CRITICAL() << "Cannot change event id in kREAD mode" << std::endl;
       throw larbys();
     }
     EventBase tmp;
     tmp._run    = run;
     tmp._subrun = subrun;
     tmp._event  = event;
     LARCV_INFO() << "Request to set event id: " << tmp.event_key() << std::endl;
     if(_set_event_id.valid() && _set_event_id != tmp)
       LARCV_INFO() << "Force setting (run,subrun,event) ID as (" << run << "," << subrun << "," << event << ")" << std::endl;
     _set_event_id = tmp;
   }
set_id() [2/2]
template<class T > void larcv::IOManager< T >::set_id () private
Definition at line 588 of file IOManager.cxx.
References larcv::IOManager< T >::_event_id, larcv::IOManager< T >::_in_dir_v, larcv::IOManager< T >::_in_file_v, larcv::IOManager< T >::_in_tree_entries, larcv::IOManager< T >::_in_tree_index, larcv::IOManager< T >::_in_tree_index_v, larcv::IOManager< T >::_in_tree_v, larcv::IOManager< T >::_io_mode, larcv::IOManager< T >::_key_list, larcv::IOManager< T >::_out_file, larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::_out_tree_index, larcv::IOManager< T >::_out_tree_v, larcv::IOManager< T >::_prepared, larcv::IOManager< T >::_product_ctr, larcv::IOManager< T >::_product_ptr_v, larcv::IOManager< T >::_product_type_v, larcv::IOManager< T >::_set_event_id, larcv::IOManager< T >::_store_only_bool, larcv::EventBase::clear(), larcv::EventBase::event(), larcv::EventBase::event_key(), larcv::IOManager< T >::finalize(), larcv::kProductUnknown, larcv::IOManager< T >::kREAD, larcv::IOManager< T >::kWRITE, LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, LARCV_WARNING, larcv::ProductName(), larcv::IOManager< T >::reset(), larcv::EventBase::run(), larcv::EventBase::subrun(), and larcv::EventBase::valid().
Referenced by larcv::IOManager< T >::file_list(), larcv::IOManager< T >::io_mode(), and larcv::IOManager< T >::read_entry().
{
     LARCV_DEBUG() << "start" << std::endl;
     if(_io_mode == kREAD) return;
     if(_set_event_id.valid())
       _event_id = _set_event_id;
     LARCV_INFO() << "Setting event id for output trees: " << _event_id.event_key() << std::endl;
     for(size_t i=0; i<_product_ptr_v.size(); ++i) {
       auto& p = _product_ptr_v[i];
       if(!p) break;
       LARCV_DEBUG() << "Updating event id for product " << ProductName(_product_type_v[i]) << " by " << p->producer() << std::endl;
       if( (*p) != _event_id ) {
     if(p->valid()) {
       LARCV_WARNING() << "Override event id for product " << ProductName(_product_type_v[i])
               << " by " << p->producer()
               << " from (" << p->run() << "," << p->subrun() << "," << p->event() << ")"
               << " to (" << _event_id.run() << "," << _event_id.subrun() << "," << _event_id.event() << ")" << std::endl;
     }
     p->_run = _event_id.run();
     p->_subrun = _event_id.subrun();
     p->_event = _event_id.event();
       }
     }
   }
set_out_file()
template<class T > void larcv::IOManager< T >::set_out_file (const std::string name) inline
Definition at line 60 of file arxiv/IOManager.h.
References larcv::IOManager< T >::_out_file_name, larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::larcv_base::name(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::save_entry().
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::GenDeadChannelMap::finalize(), larcv::IOManager< T >::io_mode(), main(), and larcv::ProcessDriver::override_output_file().
     { _out_file_name = name; }
~IOManager()
template<class T > larcv::IOManager< T >::~IOManager () inline
Default destructor.
Definition at line 55 of file arxiv/IOManager.h.
References larcv::IOManager< T >::reset().
 {}
Variable Documentation
_event_id
template<class T > EventBase larcv::IOManager< T >::_event_id private
Definition at line 115 of file IOManager.h.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
_hasindex
template<class T > bool larcv::IOManager< T >::_hasindex private
Definition at line 114 of file IOManager.h.
_in_dir_v
template<class T > std::vector< std::string > larcv::IOManager< T >::_in_dir_v private
Definition at line 81 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::configure(), larcv::IOManager< T >::IOManager(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_in_file_v
template<class T > std::vector< std::string > larcv::IOManager< T >::_in_file_v private
Definition at line 80 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::add_in_file(), larcv::IOManager< T >::clear_in_file(), larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::IOManager(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_in_index_tree_v
template<class T > TChain* larcv::IOManager< T >::_in_index_tree_v private
Definition at line 124 of file IOManager.h.
_in_tree_entries
template<class T > size_t larcv::IOManager< T >::_in_tree_entries private
Definition at line 112 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::get_n_entries(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
_in_tree_index
template<class T > size_t larcv::IOManager< T >::_in_tree_index private
Definition at line 110 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::current_entry(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::read_entry(), and larcv::IOManager< T >::set_id().
_in_tree_index_v
template<class T > std::vector< size_t > larcv::IOManager< T >::_in_tree_index_v private
Definition at line 85 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::get_data(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), and larcv::IOManager< T >::set_id().
_in_tree_v
template<class T > std::vector< TChain * > larcv::IOManager< T >::_in_tree_v private
Definition at line 84 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), and larcv::IOManager< T >::set_id().
_io_mode
template<class T > IOMode_t larcv::IOManager< T >::_io_mode private
Definition at line 74 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::io_mode(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_key_list [1/2]
template<class T > std::vector<std::map<std::string,size_t> > larcv::IOManager< T >::_key_list private
Definition at line 82 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::producer_list(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
_key_list [2/2]
template<class T > std::vector<std::map<std::string,larcv::ProducerID_t> > larcv::IOManager< T >::_key_list private
Definition at line 121 of file IOManager.h.
_key_m
template<class T > std::map<std::string,size_t> larcv::IOManager< T >::_key_m private
Definition at line 83 of file old/IOManager.h.
Referenced by larcv::IOManager< T >::producer_id(), and larcv::IOManager< T >::reset().
_last_event_id
template<class T > EventBase larcv::IOManager< T >::_last_event_id private
Definition at line 117 of file IOManager.h.
Referenced by larcv::IOManager< T >::clear_entry(), and larcv::IOManager< T >::last_event_id().
_out_file
template<class T > TFile * larcv::IOManager< T >::_out_file private
Definition at line 76 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::finalize(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_out_file_name
template<class T > std::string larcv::IOManager< T >::_out_file_name private
Definition at line 79 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::clear_in_file(), larcv::IOManager< T >::configure(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_out_index_tree_v
template<class T > TChain* larcv::IOManager< T >::_out_index_tree_v private
Definition at line 125 of file IOManager.h.
_out_tree_entries
template<class T > size_t larcv::IOManager< T >::_out_tree_entries private
Definition at line 113 of file IOManager.h.
Referenced by larcv::IOManager< T >::get_n_entries(), and larcv::IOManager< T >::read_entry().
_out_tree_index
template<class T > size_t larcv::IOManager< T >::_out_tree_index private
Definition at line 111 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::read_entry(), and larcv::IOManager< T >::set_id().
_out_tree_v
template<class T > std::vector< TTree * > larcv::IOManager< T >::_out_tree_v private
Definition at line 83 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::finalize(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::save_entry(), and larcv::IOManager< T >::set_id().
_prepared
template<class T > bool larcv::IOManager< T >::_prepared private
Definition at line 75 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::file_list(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::save_entry(), larcv::IOManager< T >::set_id(), and larcv::IOManager< T >::set_out_file().
_product_ctr
template<class T > size_t larcv::IOManager< T >::_product_ctr private
Definition at line 86 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), and larcv::IOManager< T >::set_id().
_product_ptr_v
template<class T > std::vector< larcv::EventBase * > larcv::IOManager< T >::_product_ptr_v private
Definition at line 87 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::get_data(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), and larcv::IOManager< T >::set_id().
_product_type_v
template<class T > std::vector< larcv::ProductType_t > larcv::IOManager< T >::_product_type_v private
Definition at line 88 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::product_type(), larcv::IOManager< T >::register_producer(), larcv::IOManager< T >::reset(), and larcv::IOManager< T >::set_id().
_product_v
template<class T > std::vector<std::vector<T>*> larcv::IOManager< T >::_product_v private
Definition at line 87 of file old/IOManager.h.
Referenced by larcv::IOManager< T >::finalize(), and larcv::IOManager< T >::get_data().
_read_id_bool
template<class T > std::vector<bool> larcv::IOManager< T >::_read_id_bool private
Definition at line 135 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), and larcv::IOManager< T >::get_data().
_read_only_name
template<class T > std::vector<std::string> larcv::IOManager< T >::_read_only_name private
Definition at line 132 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), and larcv::IOManager< T >::register_producer().
_read_only_type
template<class T > std::vector<larcv::ProductType_t> larcv::IOManager< T >::_read_only_type private
Definition at line 133 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), and larcv::IOManager< T >::register_producer().
_set_event_id
template<class T > EventBase larcv::IOManager< T >::_set_event_id private
Definition at line 116 of file IOManager.h.
Referenced by larcv::IOManager< T >::clear_entry(), larcv::IOManager< T >::event_id(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
_store_only_bool
template<class T > std::vector<bool> larcv::IOManager< T >::_store_only_bool private
Definition at line 134 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure(), larcv::IOManager< T >::read_entry(), and larcv::IOManager< T >::set_id().
_store_only_name
template<class T > std::vector<std::string> larcv::IOManager< T >::_store_only_name private
Definition at line 130 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure().
_store_only_type
template<class T > std::vector<larcv::ProductType_t> larcv::IOManager< T >::_store_only_type private
Definition at line 131 of file IOManager.h.
Referenced by larcv::IOManager< T >::configure().
_tree_entries
template<class T > size_t larcv::IOManager< T >::_tree_entries private
Definition at line 78 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::prepare_input(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::save_entry(), and larcv::IOManager< T >::set_out_file().
_tree_index
template<class T > size_t larcv::IOManager< T >::_tree_index private
Definition at line 77 of file arxiv/IOManager.h.
Referenced by larcv::IOManager< T >::get_data(), larcv::IOManager< T >::initialize(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::reset(), larcv::IOManager< T >::save_entry(), and larcv::IOManager< T >::set_out_file().