LArCV: main_logger.h File Reference
main_logger.h File Reference
#include "Base/larcv_logger.h"
Functions
static larcv::logger & logger ()
static void set_verbosity (larcv::msg::Level_t l)
Function Documentation
logger()
static larcv::logger& logger () static
Definition at line 3 of file main_logger.h.
Referenced by set_verbosity().
 {
   static larcv::logger __main_logger__("main");
   return __main_logger__;
 }
set_verbosity()
static void set_verbosity (larcv::msg::Level_t l) static
Definition at line 9 of file main_logger.h.
References logger(), and larcv::logger::set().
 { logger().set(l); }