LArCV: larcv::parser Namespace Reference
larcv::parser Namespace Reference
Functions
template<>
std::string FromString (const std::string &value)
template<>
float FromString (const std::string &value)
template<>
double FromString (const std::string &value)
template<>
unsigned short FromString (const std::string &value)
template<>
unsigned int FromString (const std::string &value)
template<>
unsigned long FromString (const std::string &value)
template<>
short FromString (const std::string &value)
template<>
int FromString (const std::string &value)
template<>
long FromString (const std::string &value)
template<>
bool FromString (const std::string &value)
template<>
std::vector< std::string > FromString (const std::string &value)
template<>
std::vector< float > FromString< std::vector< float > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< double > FromString< std::vector< double > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< short > FromString< std::vector< short > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< int > FromString< std::vector< int > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< long > FromString< std::vector< long > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< unsigned short > FromString< std::vector< unsigned short > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< unsigned int > FromString< std::vector< unsigned int > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< unsigned long > FromString< std::vector< unsigned long > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< bool > FromString< std::vector< bool > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::pair< int, int > FromString< std::pair< int, int > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::string ToString< std::string > (const std::string &value)
Parse larcv::PSet configuration file content.
template<class T >
T FromString (const std::string &value)
template<>
std::string FromString< std::string > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
float FromString< float > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
double FromString< double > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
short FromString< short > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
int FromString< int > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
long FromString< long > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
unsigned short FromString< unsigned short > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
unsigned int FromString< unsigned int > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
unsigned long FromString< unsigned long > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
bool FromString< bool > (const std::string &value)
Parse larcv::PSet configuration file content.
template<>
std::vector< std::string > FromString< std::vector< std::string > > (const std::string &value)
Parse larcv::PSet configuration file content.
template<class T >
std::string ToString (const T &value)
Parse larcv::PSet configuration file content.
template<class T >
std::string VecToString (const std::vector< T > &value)
Parse larcv::PSet configuration file content.
Function Documentation
FromString() [1/12]
template<> std::string larcv::parser::FromString (const std::string & value)
Definition at line 9 of file Parser.cxx.
     {
       std::string res(value);
       if(res.empty()) return res;
       if(res.find("\"") == 0) res = res.substr(1);
       if(res.empty()) return res;
       if(res.rfind("\"") == (res.length()-1)) res = res.substr(0,res.length()-1);
       return res;
     }
FromString() [2/12]
template<class T > T larcv::parser::FromString (const std::string & value)
Definition at line 9 of file Parser.cxx.
     {
       std::string res(value);
       if(res.empty()) return res;
       if(res.find("\"") == 0) res = res.substr(1);
       if(res.empty()) return res;
       if(res.rfind("\"") == (res.length()-1)) res = res.substr(0,res.length()-1);
       return res;
     }
FromString() [3/12]
template<> float larcv::parser::FromString (const std::string & value)
Definition at line 21 of file Parser.cxx.
     { return std::stof(value); }
FromString() [4/12]
template<> double larcv::parser::FromString (const std::string & value)
Definition at line 24 of file Parser.cxx.
     { return std::stod(value); }
FromString() [5/12]
template<> unsigned short larcv::parser::FromString (const std::string & value)
Definition at line 27 of file Parser.cxx.
     { return std::stoul(value); }
FromString() [6/12]
template<> unsigned int larcv::parser::FromString (const std::string & value)
Definition at line 30 of file Parser.cxx.
     { return std::stoul(value); }
FromString() [7/12]
template<> unsigned long larcv::parser::FromString (const std::string & value)
Definition at line 33 of file Parser.cxx.
     { return std::stoul(value); }
FromString() [8/12]
template<> short larcv::parser::FromString (const std::string & value)
Definition at line 36 of file Parser.cxx.
     { return std::stoi(value); }
FromString() [9/12]
template<> int larcv::parser::FromString (const std::string & value)
Definition at line 39 of file Parser.cxx.
     { return std::stoi(value); }
FromString() [10/12]
template<> long larcv::parser::FromString (const std::string & value)
Definition at line 42 of file Parser.cxx.
     { return std::stol(value); }
FromString() [11/12]
template<> bool larcv::parser::FromString (const std::string & value)
Definition at line 45 of file Parser.cxx.
     {
       std::string tmp=value;
       std::transform(tmp.begin(),tmp.end(),tmp.begin(),::tolower);
       if( value == "true"  || value == "1" ) return true;
       if( value == "false" || value == "0" ) return false;
       tmp = "Invalid bool expression: " + tmp;
       throw larbys(tmp);
       return false;
     }
FromString() [12/12]
template<> std::vector< std::string > larcv::parser::FromString (const std::string & value)
Definition at line 56 of file Parser.cxx.
     {
       //std::cout<<value<<std::endl;
       std::vector<std::string> res;
       if(value.find("[") != 0 || (value.rfind("]")+1) != value.size()) {
         std::string msg;
         msg = "Invalid vector expression: " + value;
         throw larbys(msg);
       }
       size_t index = 1;
       while((index+1) < value.size()) {
         size_t next_index = value.find(",",index);
         if(next_index >= value.size()) break;
         std::string cand = value.substr(index,next_index-index);
         res.emplace_back(cand);
         index = next_index + 1;
       }
       if( (index+1) < value.size() )
         res.push_back(value.substr(index,value.size()-index-1));
       for(auto& s : res) {
         if(s.find("\"")==0) s=s.substr(1,s.size()-1);
         if(s.rfind("\"")+1 == s.size()) s = s.substr(0,s.size()-1);
       }
       //for(auto const& s : res) std::cout<<s<<std::endl;
       return res;
     }
FromString< bool >()
template<> bool larcv::parser::FromString< bool > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< bool > >().
FromString< double >()
template<> double larcv::parser::FromString< double > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< double > >().
FromString< float >()
template<> float larcv::parser::FromString< float > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< float > >().
FromString< int >()
template<> int larcv::parser::FromString< int > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::pair< int, int > >(), and FromString< std::vector< int > >().
FromString< long >()
template<> long larcv::parser::FromString< long > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< long > >().
FromString< short >()
template<> short larcv::parser::FromString< short > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< short > >().
FromString< std::pair< int, int > >()
template<> std::pair< int, int > larcv::parser::FromString< std::pair< int, int > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 174 of file Parser.cxx.
References FromString< int >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::pair<int , int> res;
       res.first  = FromString<int>(str_v[0]);
       res.second = FromString<int>(str_v[1]);
       return res;
     }
FromString< std::string >()
template<> std::string larcv::parser::FromString< std::string > (const std::string & value)
Parse larcv::PSet configuration file content.
FromString< std::vector< bool > >()
template<> std::vector< bool > larcv::parser::FromString< std::vector< bool > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 164 of file Parser.cxx.
References FromString< bool >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<bool> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<bool>(v) );
       return res;
     }
FromString< std::vector< double > >()
template<> std::vector< double > larcv::parser::FromString< std::vector< double > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 94 of file Parser.cxx.
References FromString< double >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<double> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<double>(v) );
       return res;
     }
FromString< std::vector< float > >()
template<> std::vector< float > larcv::parser::FromString< std::vector< float > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 84 of file Parser.cxx.
References FromString< float >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<float> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<float>(v) );
       return res;
     }
FromString< std::vector< int > >()
template<> std::vector< int > larcv::parser::FromString< std::vector< int > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 114 of file Parser.cxx.
References FromString< int >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<int> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<int>(v) );
       return res;
     }
FromString< std::vector< long > >()
template<> std::vector< long > larcv::parser::FromString< std::vector< long > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 124 of file Parser.cxx.
References FromString< long >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<long> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<long>(v) );
       return res;
     }
FromString< std::vector< short > >()
template<> std::vector< short > larcv::parser::FromString< std::vector< short > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 104 of file Parser.cxx.
References FromString< short >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<short> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<short>(v) );
       return res;
     }
FromString< std::vector< std::string > >()
template<> std::vector< std::string > larcv::parser::FromString< std::vector< std::string > > (const std::string & value)
Parse larcv::PSet configuration file content.
FromString< std::vector< unsigned int > >()
template<> std::vector< unsigned int > larcv::parser::FromString< std::vector< unsigned int > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 144 of file Parser.cxx.
References FromString< unsigned int >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<unsigned int> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<unsigned int>(v) );
       return res;
     }
FromString< std::vector< unsigned long > >()
template<> std::vector< unsigned long > larcv::parser::FromString< std::vector< unsigned long > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 154 of file Parser.cxx.
References FromString< unsigned long >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<unsigned long> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<unsigned long>(v) );
       return res;
     }
FromString< std::vector< unsigned short > >()
template<> std::vector< unsigned short > larcv::parser::FromString< std::vector< unsigned short > > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 134 of file Parser.cxx.
References FromString< unsigned short >().
     {
       auto str_v = FromString<std::vector<std::string> >(value);
       std::vector<unsigned short> res;
       res.reserve(str_v.size());
       for(auto const& v : str_v)
         res.push_back( FromString<unsigned short>(v) );
       return res;
     }
FromString< unsigned int >()
template<> unsigned int larcv::parser::FromString< unsigned int > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< unsigned int > >().
FromString< unsigned long >()
template<> unsigned long larcv::parser::FromString< unsigned long > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< unsigned long > >().
FromString< unsigned short >()
template<> unsigned short larcv::parser::FromString< unsigned short > (const std::string & value)
Parse larcv::PSet configuration file content.
Referenced by FromString< std::vector< unsigned short > >().
ToString()
template<class T > std::string larcv::parser::ToString (const T & value)
Parse larcv::PSet configuration file content.
Definition at line 56 of file Parser.h.
Referenced by VecToString().
     { return std::to_string(value); }
ToString< std::string >()
template<> std::string larcv::parser::ToString< std::string > (const std::string & value)
Parse larcv::PSet configuration file content.
Definition at line 183 of file Parser.cxx.
     {
       std::string res(value);
       if(res.empty()) return res;
       if(res.find("\"") == 0) res = res.substr(1);
       if(res.empty()) return res;
       if(res.rfind("\"") == (res.length()-1)) res = res.substr(0,res.length()-1);
       return res;
     }
VecToString()
template<class T > std::string larcv::parser::VecToString (const std::vector< T > & value)
Parse larcv::PSet configuration file content.
Definition at line 61 of file Parser.h.
References ToString().
     {
       std::string res="[";
       for(auto const& v : value)
     res += ToString(v) + ",";
       res = res.substr(0,res.size()-1);
       res += "]";
       return res;
     }