LArCV: dbscan Namespace Reference
dbscan Namespace Reference
Classes
class ClusterExtrema
class DBSCANAlgo
class dbscanOutput
Typedefs
typedef std::vector< std::vector< double > > dbPoints
typedef std::vector< int > dbCluster
typedef std::vector< std::vector< int > > dbClusters
Functions
dbPoints extractPointsFromImage (const larcv::Image2D &img, const double threshold)
dbPoints extractPointsFromImageBounds (const larcv::Image2D &img, const double threshold, int row_min, int row_max, int col_min, int col_max)
Typedef Documentation
dbCluster
typedef std::vector< int > dbscan::dbCluster
Definition at line 15 of file DBSCANAlgo.h.
dbClusters
typedef std::vector< std::vector<int> > dbscan::dbClusters
Definition at line 16 of file DBSCANAlgo.h.
dbPoints
typedef std::vector< std::vector<double> > dbscan::dbPoints
Definition at line 14 of file DBSCANAlgo.h.
Function Documentation
extractPointsFromImage()
dbPoints dbscan::extractPointsFromImage (const larcv::Image2D & img, const double threshold)
Definition at line 280 of file DBSCANAlgo.cxx.
References larcv::ImageMeta::cols(), extractPointsFromImageBounds(), larcv::Image2D::meta(), and larcv::ImageMeta::rows().
Referenced by dbscan::DBSCANAlgo::~DBSCANAlgo().
{
     const larcv::ImageMeta& meta = img.meta();
     dbPoints pixels = extractPointsFromImageBounds( img, threshold, 0, meta.rows()-1, 0, meta.cols()-1 );
     return pixels;
   }
extractPointsFromImageBounds()
dbPoints dbscan::extractPointsFromImageBounds (const larcv::Image2D & img, const double threshold, int row_min, int row_max, int col_min, int col_max)
Definition at line 285 of file DBSCANAlgo.cxx.
References larcv::ImageMeta::cols(), larcv::Image2D::meta(), larcv::Image2D::pixel(), and larcv::ImageMeta::rows().
Referenced by extractPointsFromImage(), and dbscan::DBSCANAlgo::~DBSCANAlgo().
{
     dbPoints pixels;
     const larcv::ImageMeta& meta = img.meta();
     if ( row_min<0 ) row_min = 0;
     if ( row_max>=(int)meta.rows() ) row_max = (int)meta.rows()-1;
     if ( col_min<0 ) col_min = 0;
     if ( col_max>=(int)meta.cols() ) col_max = (int)meta.cols()-1;
     for (int r=row_min; r<=row_max; r++) {
       for (int c=col_min; c<=col_max; c++) {
         if ( img.pixel(r,c)>threshold ) {
           std::vector<double> pixel(2,0.0);
           pixel[0] = (double)c;
           pixel[1] = (double)r;
           pixels.emplace_back( std::move(pixel) );
         }
       }
     }
     return pixels;
   }