LArCV: larcv Namespace Reference
larcv Namespace Reference
Base | LArCV | CVFhicl | Utils | CvUtil | DataFormat | Processor | Package_Name | PyUtil | MultiThreadTools | APICaffe | ImageMod | MeatSlicer | Merger | Adrien | APILArLite
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Namespaces
chstatus
Channel status constants.
hires
msg
Namespace for larcv message related types.
parser
pmtweights
supera
Classes
class A3DPixPos_t
class ADCScale
class ADCScaleAna
class ADCScaleAnaFactory
A concrete factory class for larcv::ADCScaleAna.
class ADCScaleAnaProcessFactory
class ADCScaleFactory
A concrete factory class for larcv::ADCScale.
class ADCScaleProcessFactory
class ADCThreshold
class ADCThresholdFactory
A concrete factory class for larcv::ADCThreshold.
class ADCThresholdProcessFactory
class AlgoDataAna
class AlgoDataAnaProcessFactory
class AStar3DAlgo
class AStar3DAlgoConfig
class AStar3DAlgoProton
class AStar3DNode
class AStar3DNodePtrList
class AStarTracker
User custom analysis class made by SHELL_USER_NAME.
class BadRegionAna
class BadRegionAnaFactory
A concrete factory class for larcv::BadRegionAna.
class BadRegionAnaProcessFactory
class Binarize
class BinarizeFactory
A concrete factory class for larcv::Binarize.
class BinarizeProcessFactory
class BlankImage
class BlankImageFactory
A concrete factory class for larcv::BlankImage.
class BlankImageProcessFactory
class calcPeakADC
class calcPeakADCFactory
A concrete factory class for larcv::calcPeakADC.
class calcPeakADCProcessFactory
class CCIncFilter
class CCIncFilterFactory
A concrete factory class for larcv::CCIncFilter.
class CCIncFilterProcessFactory
class CCQETruthFilter
class CCQETruthFilterFactory
A concrete factory class for larcv::CCQETruthFilter.
class CCQETruthFilterProcessFactory
class ChannelMax
class ChannelMaxFactory
A concrete factory class for larcv::ChannelMax.
class ChannelMaxProcessFactory
class ChStatus
User defined class ChStatus ...
class ChStatusConverter
class ChStatusConverterFactory
A concrete factory class for larcv::ChStatusConverter.
class ChStatusConverterProcessFactory
class CircularBufferBase
User defined class CircularBufferBase ...
class CombineImages
class CombineImagesFactory
A concrete factory class for larcv::CombineImages.
class CombineImagesProcessFactory
class Compressor
class CompressorFactory
A concrete factory class for larcv::Compressor.
class CompressorProcessFactory
class ConfigManager
User defined class ConfigManager ...
class CosmicFilter
class CosmicFilterFactory
A concrete factory class for larcv::CosmicFilter.
class CosmicFilterProcessFactory
class CosmicPixelAna
class CosmicPixelAnaFactory
A concrete factory class for larcv::CosmicPixelAna.
class CosmicPixelAnaProcessFactory
class CosmicROIFiller
class CosmicROIFillerFactory
A concrete factory class for larcv::CosmicROIFiller.
class CosmicROIFillerProcessFactory
class CosmicSegment
class CosmicSegmentFactory
A concrete factory class for larcv::CosmicSegment.
class CosmicSegmentProcessFactory
class CosmicTrackAna
class CosmicTrackAnaFactory
A concrete factory class for larcv::CosmicTrackAna.
class CosmicTrackAnaProcessFactory
class CosmicVertexAna
class CosmicVertexAnaFactory
A concrete factory class for larcv::CosmicVertexAna.
class CosmicVertexAnaProcessFactory
class CropROI
class CropROIFactory
A concrete factory class for larcv::CropROI.
class CropROIProcessFactory
class CSVData
class DataProductFactory
class DataProductFactoryBase
Abstract base class for factory (to be implemented per data product)
class DataStream
class DataStreamFactory
A concrete factory class for larcv::DataStream.
class DataStreamProcessFactory
class DatumFillerBase
class DBSCAN
class DBSCANFactory
A concrete factory class for larcv::DBSCAN.
class DBSCANProcessFactory
class DeadWireAna
class DeadWireAnaProcessFactory
class DLCosmicTagImageMaker
class DLCosmicTagUtil
class DoNothing
class DoNothingFactory
A concrete factory class for larcv::DoNothing.
class DoNothingProcessFactory
class DumpHiResCropImages
class DumpHiResCropImagesFactory
A concrete factory class for larcv::DumpHiResCropImages.
class DumpHiResCropImagesProcessFactory
class EmbedImage
class EmbedImageFactory
A concrete factory class for larcv::EmbedImage.
class EmbedImageProcessFactory
class EmptyImageFilter
class EmptyImageFilterFactory
A concrete factory class for larcv::EmptyImageFilter.
class EmptyImageFilterProcessFactory
class EventBase
Base class for an event data product (what is stored in output file), holding run/subrun/event ID + producer name.
class EventChStatus
Event-wise class to store a collection of larcv::ChStatus (one per plane)
class EventChStatusFactory
class EventImage2D
Event-wise class to store a collection of larcv::Image2D.
class EventImage2DFactory
class EventParticleROI
User defined class EventParticleROI ...
class EventPGraph
Event-wise class to store a collection of larcv::PGraph.
class EventPGraphFactory
class EventPixel2D
Event-wise class to store a collection of larcv::Pixel2D and larcv::Pixel2DCluster.
class EventPixel2DFactory
class EventROI
Event-wise class to store a collection of larcv::ROI.
class EventROIFactory
class EventVoxel3D
Event-wise class to store a collection of larcv::Voxel3D.
class EventVoxel3DFactory
class ExampleAna
class ExampleAnaFactory
A concrete factory class for larcv::ExampleAna.
class ExampleAnaProcessFactory
class ExampleCircularBuffer
User defined class ExampleCircularBuffer ...
class GenDeadChannelMap
class GenDeadChannelMapFactory
A concrete factory class for larcv::GenDeadChannelMap.
class GenDeadChannelMapProcessFactory
class GoodcROIFilter
class GoodcROIFilterFactory
A concrete factory class for larcv::GoodcROIFilter.
class GoodcROIFilterProcessFactory
class HiResImageDividerFactory
A concrete factory class for larcv::HiResImageDivider.
class HistADC
class HistADCFactory
A concrete factory class for larcv::HistADC.
class HistADCProcessFactory
class Image2D
Meant to be a storage class for an image into a ROOT file.
class ImageChargeAna
class ImageChargeAnaFactory
A concrete factory class for larcv::ImageChargeAna.
class ImageChargeAnaProcessFactory
class ImageFromPixel2D
class ImageFromPixel2DCluster
class ImageFromPixel2DClusterFactory
A concrete factory class for larcv::ImageFromPixel2DCluster.
class ImageFromPixel2DClusterProcessFactory
class ImageFromPixel2DFactory
A concrete factory class for larcv::ImageFromPixel2D.
class ImageFromPixel2DProcessFactory
class ImageHolder
class ImageMerger
class ImageMergerFactory
A concrete factory class for larcv::ImageMerger.
class ImageMergerProcessFactory
class ImageMeta
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
class ImageROICheckMC
class ImageROICheckMCFactory
A concrete factory class for larcv::ImageROICheckMC.
class ImageROICheckMCProcessFactory
class IOManager
User defined class IOManager ...
class larbys
Throw insignificant larbys when you find nonesense.
class LArbysImage
class LArbysImageAna
class LArbysImageAnaBase
class LArbysImageAnaProcessFactory
class LArbysImageCheater
class LArbysImageCheaterFactory
A concrete factory class for larcv::LArbysImageCheater.
class LArbysImageCheaterProcessFactory
class LArbysImageExtract
class LArbysImageExtractProcessFactory
class LArbysImageFactory
A concrete factory class for larcv::LArbysImage.
class LArbysImageFilter
class LArbysImageFilterProcessFactory
class LArbysImageMaker
class LArbysImageMC
class LArbysImageMCFactory
A concrete factory class for larcv::LArbysImageMC.
class LArbysImageMCProcessFactory
class LArbysImageOut
class LArbysImageOutProcessFactory
class LArbysImagePID
class LArbysImagePIDFactory
A concrete factory class for larcv::LArbysImagePID.
class LArbysImagePIDProcessFactory
class LArbysImageProcessFactory
class LArbysImageReAna
class LArbysImageReAnaFactory
A concrete factory class for larcv::LArbysImageReAna.
class LArbysImageReAnaProcessFactory
class LArbysImageResult
class LArbysLoader
class LArbysRecoHolder
class LArbysTrash
class LArbysTrashProcessFactory
class larcv_base
Framework base class equipped with a logger class.
class LArCVSuperaDriver
User defined class LArCVSuperaDriver ...
class LArOCVSerial
class Lattice
class LEE1e1pAna
class LEE1e1pAnaFactory
A concrete factory class for larcv::LEE1e1pAna.
class LEE1e1pAnaProcessFactory
class load_cvutil
User defined class load_cvutil ...
class load_pyutil
User defined class load_pyutil ...
class LoadImageMod
User defined class LoadImageMod ...
class logger
Utility class used to show formatted message on the screen.
class MaskImage
class MaskImageFactory
A concrete factory class for larcv::MaskImage.
class MaskImageProcessFactory
class MCFilter
class MCFilterFactory
A concrete factory class for larcv::MCFilter.
class MCFilterProcessFactory
class MCInteraction
User defined class MCInteraction ...
class MCSingleParticleFilter
class MCSingleParticleFilterFactory
A concrete factory class for larcv::MCSingleParticleFilter.
class MCSingleParticleFilterProcessFactory
class MeanSubtraction
class MeanSubtractionFactory
A concrete factory class for larcv::MeanSubtraction.
class MeanSubtractionProcessFactory
class MergeTwoStream
User defined class MergeTwoStream ...
class ModularPadImage
class ModularPadImageFactory
A concrete factory class for larcv::ModularPadImage.
class ModularPadImageProcessFactory
class MultiClassFiller
class MultiClassFillerFactory
A concrete factory class for larcv::MultiClassFiller.
class MultiClassFillerProcessFactory
class MultiROICropper
class MultiROICropperFactory
A concrete factory class for larcv::MultiROICropper.
class MultiROICropperProcessFactory
class NNCosine
class NNCosineFactory
A concrete factory class for larcv::NNCosine.
class NNCosineProcessFactory
class NuFilter
class NuFilterFactory
A concrete factory class for larcv::NuFilter.
class NuFilterProcessFactory
class OperateImage
class OperateImageFactory
A concrete factory class for larcv::OperateImage.
class OperateImageProcessFactory
class ParticleAna
class ParticleAnaFactory
A concrete factory class for larcv::ParticleAna.
class ParticleAnaProcessFactory
class ParticleROI
User defined class ParticleROI ...
class Pass
class PassFactory
A concrete factory class for larcv::Pass.
class PassProcessFactory
class PGraph
User defined class PGraph ...
class PGraphTruthMatch
class PGraphTruthMatchProcessFactory
class PIDImageMaker
class PIDImageMakerFactory
A concrete factory class for larcv::PIDImageMaker.
class PIDImageMakerProcessFactory
class Pixel2D
User defined class Pixel2D ...
class Pixel2DCluster
User defined class Pixel2DCluster ...
struct PixelChunk
class PlaneImageMerger
class PlaneImageMergerFactory
A concrete factory class for larcv::PlaneImageMerger.
class PlaneImageMergerProcessFactory
class PMTWeightImageBuilderFactory
A concrete factory class for larcv::PMTWeightImageBuilder.
struct Point2D
Simple 2D point struct (unit of "x" and "y" are not defined here and app specific)
class PostTagger
class PreProcessor
class PreProcessorAna
class PreProcessorAnaFactory
A concrete factory class for larcv::PreProcessorAna.
class PreProcessorAnaProcessFactory
class ProcessBase
User defined class ProcessBase ...
class ProcessDriver
User defined class ProcessDriver ...
class ProcessFactory
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
class ProcessFactoryBase
Abstract base class for factory (to be implemented per process)
class PSet
User defined class PSet ...
class PyImageMaker
class PyImageMakerFactory
A concrete factory class for larcv::PyImageMaker.
class PyImageMakerProcessFactory
class PyImageStitcher
class PyImageStitcherFactory
A concrete factory class for larcv::PyImageStitcher.
class PyImageStitcherProcessFactory
class QSumFilter
class QSumFilterFactory
A concrete factory class for larcv::QSumFilter.
class QSumFilterProcessFactory
class RandomCropper
User defined class RandomCropper ...
class RandomGaus
Threaded generator for a pool of gaussian random numbers.
class Range
represents a "Range" w/ notion of ordering.
class ReadJarrettFile
class ReadJarrettFileFactory
A concrete factory class for larcv::ReadJarrettFile.
class ReadJarrettFileProcessFactory
class ReadNueFile
class ReadNueFileProcessFactory
class ReadRuiFile
class ReadRuiFileFactory
A concrete factory class for larcv::ReadRuiFile.
class ReadRuiFileProcessFactory
class ResizeImage
class ResizeImageFactory
A concrete factory class for larcv::ResizeImage.
class ResizeImageProcessFactory
class ROI
User defined class ROI ...
class ROIAna
class ROIAnaFactory
A concrete factory class for larcv::ROIAna.
class ROIAnaProcessFactory
class ROIClipper
class ROIClipperProcessFactory
class ROICountFilter
class ROICountFilterFactory
A concrete factory class for larcv::ROICountFilter.
class ROICountFilterProcessFactory
class ROIMask
class ROIMaskFactory
A concrete factory class for larcv::ROIMask.
class ROIMaskProcessFactory
class ROIMerger
class ROIMergerFactory
A concrete factory class for larcv::ROIMerger.
class ROIMergerProcessFactory
class ROIPad
class ROIPadProcessFactory
class ROISizeFilter
class ROISizeFilterFactory
A concrete factory class for larcv::ROISizeFilter.
class ROISizeFilterProcessFactory
class RSEFilter
class RSEFilterFactory
A concrete factory class for larcv::RSEFilter.
class RSEFilterProcessFactory
class RSEID
class Run3DTracker
class Run3DTrackerFactory
A concrete factory class for larcv::Run3DTracker.
class Run3DTrackerProcessFactory
class RunFilter
class RunFilterFactory
A concrete factory class for larcv::RunFilter.
class RunFilterProcessFactory
class SegDatumFillerBase
class SegFiller
class SegFillerFactory
A concrete factory class for larcv::SegFiller.
class SegFillerProcessFactory
class SegImageAna
class SegImageAnaFactory
A concrete factory class for larcv::SegImageAna.
class SegImageAnaProcessFactory
class SegmentAna
class SegmentAnaFactory
A concrete factory class for larcv::SegmentAna.
class SegmentAnaProcessFactory
class SegmentFilter
class SegmentFilterFactory
A concrete factory class for larcv::SegmentFilter.
class SegmentFilterProcessFactory
class SegmentMaker
class SegmentMakerFactory
A concrete factory class for larcv::SegmentMaker.
class SegmentMakerProcessFactory
class SegmentMask
class SegmentMaskFactory
A concrete factory class for larcv::SegmentMask.
class SegmentMaskProcessFactory
class SegmentRelabel
class SegmentRelabelFactory
A concrete factory class for larcv::SegmentRelabel.
class SegmentRelabelProcessFactory
class SegWeightInstance
class SegWeightInstanceFactory
A concrete factory class for larcv::SegWeightInstance.
class SegWeightInstanceProcessFactory
class SegWeightTrackShower
class SegWeightTrackShowerFactory
A concrete factory class for larcv::SegWeightTrackShower.
class SegWeightTrackShowerProcessFactory
class SimpleDigitizer
class SimpleDigitizerFactory
A concrete factory class for larcv::SimpleDigitizer.
class SimpleDigitizerProcessFactory
class SimpleFiller
class SimpleFillerFactory
A concrete factory class for larcv::SimpleFiller.
class SimpleFillerProcessFactory
class SimplePixelAna
class SimplePixelAnaFactory
A concrete factory class for larcv::SimplePixelAna.
class SimplePixelAnaProcessFactory
class SingleROIFaker
class SingleROIFakerFactory
A concrete factory class for larcv::SingleROIFaker.
class SingleROIFakerProcessFactory
class SliceImages
class SliceImagesFactory
A concrete factory class for larcv::SliceImages.
class SliceImagesProcessFactory
class SSNetEventAna
class SSNetEventAnaProcessFactory
class SSNetTruthAna
class SSNetTruthAnaFactory
A concrete factory class for larcv::SSNetTruthAna.
class SSNetTruthAnaProcessFactory
class StepDigitizer
class StepDigitizerFactory
A concrete factory class for larcv::StepDigitizer.
class StepDigitizerProcessFactory
class SuperaBase
class SuperaBaseFactory
A concrete factory class for larcv::SuperaBase.
class SuperaBaseProcessFactory
class SuperaChStatus
class SuperaChStatusFactory
A concrete factory class for larcv::SuperaChStatus.
class SuperaChStatusProcessFactory
class SuperaHit
class SuperaHitFactory
A concrete factory class for larcv::SuperaHit.
class SuperaHitProcessFactory
class SuperaKeyPointCluster
class SuperaKeyPointClusterFactory
A concrete factory class for larcv::SuperaKeyPointCluster.
class SuperaKeyPointClusterProcessFactory
class SuperaMCPCluster
class SuperaMCPClusterFactory
A concrete factory class for larcv::SuperaMCPCluster.
class SuperaMCPClusterProcessFactory
class SuperaMCROI
class SuperaMCROIFactory
A concrete factory class for larcv::SuperaMCROI.
class SuperaMCROIProcessFactory
class SuperaMetaMaker
class SuperaMetaMakerFactory
A concrete factory class for larcv::SuperaMetaMaker.
class SuperaMetaMakerProcessFactory
class SuperaOpDigit
class SuperaOpDigitFactory
A concrete factory class for larcv::SuperaOpDigit.
class SuperaOpDigitProcessFactory
class SuperaSimCh
class SuperaSimChFactory
A concrete factory class for larcv::SuperaSimCh.
class SuperaSimChProcessFactory
class SuperaSimVoxel3D
class SuperaSimVoxel3DFactory
A concrete factory class for larcv::SuperaSimVoxel3D.
class SuperaSimVoxel3DProcessFactory
class SuperaWire
class SuperaWireFactory
A concrete factory class for larcv::SuperaWire.
class SuperaWireProcessFactory
class ThreadDatumFiller
User defined class ThreadDatumFiller ...
class ThreadFillerFactory
class TrackerEventDisplay
class TrackerEventDisplayFactory
A concrete factory class for larcv::TrackerEventDisplay.
class TrackerEventDisplayProcessFactory
class TrackShowerAna
class UBWireTool
class UnionROI
class UnionROIProcessFactory
class UniqueRangeSet
std::set of larcv::Range, which does not allow any overlap in contained element.
class Vertex
class VertexAna
class VertexAnaFactory
A concrete factory class for larcv::VertexAna.
class VertexAnaProcessFactory
class VertexFilter
class VertexFilterProcessFactory
class VertexImg
class VertexImgFactory
A concrete factory class for larcv::VertexImg.
class VertexImgProcessFactory
class VertexInROI
class VertexInROIProcessFactory
class ViewROOT
class Voxel3D
3D voxel definition element class consisting of ID and stored value
class Voxel3DMeta
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
class Voxel3DSet
Container of multiple voxels consisting of ordered sparse vector and meta data.
class VtxInRegion
class VtxInRegionFactory
A concrete factory class for larcv::VtxInRegion.
class VtxInRegionProcessFactory
class Watch
a very simple stopwatch class for simple time measurement
class WireData
class WireMask
This module is used to mask column pixels that correspond to a set of specified wires.
class WireMaskFactory
A concrete factory class for larcv::WireMask.
class WireMaskProcessFactory
Typedefs
typedef unsigned short ImageIndex_t
Image index type for Image2D within EventImage2D.
typedef unsigned short ROIIndex_t
ROI index type for ROI within EventROI.
typedef unsigned short MCSTIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
typedef unsigned short MCTIndex_t
"ID" of MCTruth in terms of its index number in the collection std::vector
typedef unsigned short PlaneID_t
"ID" for wire planes
typedef unsigned long long Voxel3DID_t
"ID" for Voxel3D
typedef size_t MCTrackID_t
"ID" of MCParticles in terms of its G4 track ID (unless mixing multiple MC samples)
typedef std::set< larcv::MCTrackID_t > MCTrackIDSet_t
A collection of MCTrackID_t for multiple MCParticles.
typedef size_t ProducerID_t
ProducerID_t to identify a unique data product within a process (for larcv::IOManager)
typedef unsigned short ParticleROIIndex_t
typedef size_t MCIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
typedef std::vector< larcv::supera::MCIndex_t > MCIndexSet_t
A collection of MCIndex_t for multiple MCShowers/MCTracks.
typedef size_t ProcessID_t
A unique identifier for an instantiated processes.
typedef std::vector< std::vector< AStar3DNode > > PathList_t
typedef std::pair< A3DPixPos_t, AStar3DNode *> a3dpos_pair_t
Enumerations
enum PoolType_t { kPoolSum, kPoolAverage, kPoolMax }
Pooling type.
enum ShapeType_t {
kShapeShower, kShapeTrack, kShapeUnknown, kMCShower,
kMCTrack, kUnknownShape
}
Object appearance type in LArTPC.
enum ROIType_t {
kROIUnknown =0, kROICosmic, kROIBNB, kROIEminus,
kROIGamma, kROIPizero, kROIMuminus, kROIKminus,
kROIPiminus, kROIProton, kROITypeMax
}
larcv::ROI types, used to define classification class typically
enum ProductType_t {
kProductImage2D, kProductROI, kProductChStatus, kProductPixel2D,
kProductPGraph, kProductVoxel3D, kProductUnknown
}
Type of data product.
enum ShapeType_t {
kShapeShower, kShapeTrack, kShapeUnknown, kMCShower,
kMCTrack, kUnknownShape
}
enum ParticleType_t {
kEminus, kKminus, kProton, kMuminus,
kPiminus, kGamma, kPizero, kBNB,
kCosmic, kUnknownParticle, kMCShower, kMCTrack,
kUnknown
}
enum ParticleType_t {
kEminus, kKminus, kProton, kMuminus,
kPiminus, kGamma, kPizero, kBNB,
kCosmic, kUnknownParticle, kMCShower, kMCTrack,
kUnknown
}
enum ThreadFillerState_t { kThreadStateIdle, kThreadStateStarting, kThreadStateRunning, kThreadStateUnknown }
enum BufferState_t {
kEmpty, kInit, kReady, kClean,
kUndefined
}
enum Type_t { Type_t::kUnknown, Type_t::kTrack, Type_t::kShower }
Functions
std::string ConfigFile2String (std::string fname)
Given a configuration string, format to create larcv::PSet.
PSet CreatePSetFromFile (std::string fname, std::string cfg_name="cfg")
Given a configuration file (full path), create and return larcv::PSet.
template<>
PSet PSet::get< larcv::PSet > (const std::string &key) const
template<>
const std::map< std::string, std::vector< std::string > > & CSVData::get_container< std::string > () const
CSVData read_csv (const std::string fname, const std::string format)
cv::Mat as_mat (const Image2D &larcv_img)
Image2D to cv::Mat converter (not supported in ROOT5 CINT)
cv::Mat as_gray_mat (const Image2D &larcv_img, float q_min, float q_max, float q_to_gray)
cv::Mat as_mat_1FC (const Image2D &larcv_img)
cv::Mat as_mat_greyscale2bgr (const Image2D &larcv_img, const float min, const float max)
larcv::Image2D mat_to_image2d (const cv::Mat &mat, const ImageMeta &src_meta)
Image2D imread (const std::string file_name)
larcv::Image2D creator from an image file
Image2D imread_gray (const std::string file_name)
Gray scale larcv::Image2D creator from an image file.
void draw_bb (cv::Mat &mat, const larcv::ImageMeta &img_meta, const larcv::ImageMeta &bbox, const int r, const int g, const int b, const int thickness)
ROIType_t PdgCode2ROIType (int pdgcode)
Return larcv::ROI type from PdgCode.
template<>
std::string ProductName< larcv::ImageMeta > ()
template<>
std::string ProductName< larcv::Image2D > ()
template<class T >
std::string ProductName ()
double ParticleMass (const int pdgcode)
Utility to get a particle mass.
const char * ProductName (ProductType_t type)
template<>
ProductType_t ProductType< larcv::Image2D > ()
template<>
ProductType_t ProductType< larcv::ROI > ()
template<>
ProductType_t ProductType< larcv::ChStatus > ()
template<>
ProductType_t ProductType< larcv::Pixel2D > ()
template<>
ProductType_t ProductType< larcv::PGraph > ()
template<>
ProductType_t ProductType< larcv::Voxel3D > ()
template<class T >
ProductType_t ProductType ()
ROIType_t PDG2ROIType (const int pdgcode)
std::string ROIType2String (const ROIType_t type)
ROIType_t String2ROIType (const std::string &name)
void SetPyUtil ()
Utility function: call one-time-only numpy module initialization (you don't have to call)
PyObject * as_ndarray (const std::vector< float > &vec)
PyObject * as_ndarray (const Image2D &img)
larcv::Image2D to numpy array converter
void copy_array (PyObject *arrayin, const std::vector< float > &cvec)
copy array
PyObject * as_caffe_ndarray (const Image2D &img)
larcv::Image2D to numpy array converter
larcv::Image2D as_image2d_meta (PyObject *pyarray, ImageMeta meta)
larcv::Image2D as_image2d (PyObject *pyarray)
void fill_img_col (Image2D &img, std::vector< short > &adcs, const int col, const int timedownsampling, const float pedestal)
TH2D as_th2d (const larcv::Image2D &img, std::string histname)
std::vector< TH2D > as_th2d_v (const std::vector< larcv::Image2D > &img_v, std::string histstemname)
Image2D cluster_to_image2d (const Pixel2DCluster &pcluster, size_t target_rows, size_t target_cols)
geo2d::Rect MakeRect (const larcv::ImageMeta &meta)
cv::Rect Get2DRoi (const ImageMeta &meta, const ImageMeta &bb)
void Project3D (const ImageMeta &meta, double parent_x, double parent_y, double parent_z, double parent_t, uint plane, double &xpixel, double &ypixel)
geo2d::Vector< float > Intersection (const geo2d::HalfLine< float > &hline, const cv::Rect &rect)
void mask_image (Image2D &target, const Image2D &ref)
std::vector< ImageMeta > crop_metas (const std::vector< Image2D > &img_v, const std::vector< ImageMeta > &meta_v)
ImageMeta crop_meta (const Image2D &img, const ImageMeta &meta)
bool InFiducialRegion3D (float X, float Y, float Z, float edge_x, float edge_y, float edge_z)
float Cross2D (const geo2d::Vector< float > &u, const geo2d::Vector< float > &v)
bool TriangleIsCCW (const geo2d::Vector< float > &a, const geo2d::Vector< float > &b, const geo2d::Vector< float > &c)
bool InsideRegion (const geo2d::Vector< float > &p, const std::array< geo2d::Vector< float >, 4 > &v)
bool InsideRegions (const geo2d::Vector< float > &p, const std::vector< std::array< geo2d::Vector< float >, 4 > > &v_v)
template<>
const std::vector< supera::LArWire_t > & SuperaBase::LArData< supera::LArWire_t > () const
template<>
const std::vector< supera::LArHit_t > & SuperaBase::LArData< supera::LArHit_t > () const
template<>
const std::vector< supera::LArOpDigit_t > & SuperaBase::LArData< supera::LArOpDigit_t > () const
template<>
const std::vector< supera::LArSimCh_t > & SuperaBase::LArData< supera::LArSimCh_t > () const
template<>
const std::vector< supera::LArMCTruth_t > & SuperaBase::LArData< supera::LArMCTruth_t > () const
template<>
const std::vector< supera::LArMCTrack_t > & SuperaBase::LArData< supera::LArMCTrack_t > () const
template<>
const std::vector< supera::LArMCShower_t > & SuperaBase::LArData< supera::LArMCShower_t > () const
void ProjectTo3D (const ImageMeta &meta, double parent_x, double parent_y, double parent_z, double parent_t, uint plane, double &xpixel, double &ypixel)
Variables
const long long kINVALID_LONGLONG = std::numeric_limits< long long >::max()
Used as an invalid value identifier for long long.
const unsigned long long kINVALID_ULONGLONG = std::numeric_limits< unsigned long long >::max()
Used as an invalid value identifier for unsigned long long.
const size_t kINVALID_SIZE = std::numeric_limits< size_t >::max()
Used as an invalid value identifier for size_t.
const int kINVALID_INT = std::numeric_limits< int >::max()
Used as an invalid value identifier for int.
const unsigned int kINVALID_UINT = std::numeric_limits< unsigned int >::max()
Used as an invalid value identifier for unsigned int.
const short kINVALID_SHORT = std::numeric_limits< short >::max()
Used as an invalid value identifier for unsigned short.
const unsigned short kINVALID_USHORT = std::numeric_limits< unsigned short >::max()
Used as an invalid value identifier for unsigned unsigned short.
const float kINVALID_FLOAT = std::numeric_limits< float >::max()
Used as an invalid value idnetifier for single-point precision.
const double kINVALID_DOUBLE = std::numeric_limits< double >::max()
Used as an invalid value idnetifier for double-point precision.
static const unsigned short kINVALID_INDEX = kINVALID_USHORT
Invalid rep for vector index.
static const PlaneID_t kINVALID_PLANE = kINVALID_USHORT
Invalid plane definition.
static const Voxel3DID_t kINVALID_VOXEL3DID = kINVALID_ULONGLONG
Invalid Voxel3DID_t definition.
static const ProducerID_t kINVALID_PRODUCER =kINVALID_SIZE
Invalid ProducerID_t.
static EventChStatusFactory __global_EventChStatusFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventImage2DFactory __global_EventImage2DFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventPGraphFactory __global_EventPGraphFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventPixel2DFactory __global_EventPixel2DFactory__
Global larcv::EventPixel2DFactory to register EventPixel2D.
static EventROIFactory __global_EventROIFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventVoxel3DFactory __global_EventVoxel3DFactory__
Global larcv::EventVoxel3D to register factory.
static const unsigned short kINVALID_INDEX = kINVALID_USHORT
static const PlaneID_t kINVALID_PLANE = kINVALID_USHORT
static RunFilterProcessFactory __global_RunFilterProcessFactory__
static PyImageMakerProcessFactory __global_PyImageMakerProcessFactory__
static PyImageStitcherProcessFactory __global_PyImageStitcherProcessFactory__
static MultiClassFillerProcessFactory __global_MultiClassFillerProcessFactory__
static SegFillerProcessFactory __global_SegFillerProcessFactory__
static SimpleFillerProcessFactory __global_SimpleFillerProcessFactory__
static calcPeakADCProcessFactory __global_calcPeakADCProcessFactory__
static DBSCANProcessFactory __global_DBSCANProcessFactory__
static NNCosineProcessFactory __global_NNCosineProcessFactory__
static CCIncFilterProcessFactory __global_CCIncFilterProcessFactory__
static CCQETruthFilterProcessFactory __global_CCQETruthFilterProcessFactory__
static CosmicFilterProcessFactory __global_CosmicFilterProcessFactory__
static EmptyImageFilterProcessFactory __global_EmptyImageFilterProcessFactory__
static MCFilterProcessFactory __global_MCFilterProcessFactory__
static MCSingleParticleFilterProcessFactory __global_MCSingleParticleFilterProcessFactory__
static NuFilterProcessFactory __global_NuFilterProcessFactory__
static QSumFilterProcessFactory __global_QSumFilterProcessFactory__
static ROICountFilterProcessFactory __global_ROICountFilterProcessFactory__
static ROISizeFilterProcessFactory __global_ROISizeFilterProcessFactory__
static RSEFilterProcessFactory __global_RSEFilterProcessFactory__
static VtxInRegionProcessFactory __global_VtxInRegionProcessFactory__
static CosmicSegmentProcessFactory __global_CosmicSegmentProcessFactory__
static DumpHiResCropImagesProcessFactory __global_DumpHiResCropImagesProcessFactory__
static HistADCProcessFactory __global_HistADCProcessFactory__
static SegImageAnaProcessFactory __global_SegImageAnaProcessFactory__
static ADCScaleProcessFactory __global_ADCScaleProcessFactory__
static ADCScaleAnaProcessFactory __global_ADCScaleAnaProcessFactory__
static ADCThresholdProcessFactory __global_ADCThresholdProcessFactory__
static BinarizeProcessFactory __global_BinarizeProcessFactory__
static ChannelMaxProcessFactory __global_ChannelMaxProcessFactory__
static CombineImagesProcessFactory __global_CombineImagesProcessFactory__
static CompressorProcessFactory __global_CompressorProcessFactory__
static CosmicROIFillerProcessFactory __global_CosmicROIFillerProcessFactory__
static CropROIProcessFactory __global_CropROIProcessFactory__
static EmbedImageProcessFactory __global_EmbedImageProcessFactory__
static ImageChargeAnaProcessFactory __global_ImageChargeAnaProcessFactory__
static ImageFromPixel2DProcessFactory __global_ImageFromPixel2DProcessFactory__
static ImageFromPixel2DClusterProcessFactory __global_ImageFromPixel2DClusterProcessFactory__
static MaskImageProcessFactory __global_MaskImageProcessFactory__
static MeanSubtractionProcessFactory __global_MeanSubtractionProcessFactory__
static ModularPadImageProcessFactory __global_ModularPadImageProcessFactory__
static MultiROICropperProcessFactory __global_MultiROICropperProcessFactory__
static PlaneImageMergerProcessFactory __global_PlaneImageMergerProcessFactory__
static ResizeImageProcessFactory __global_ResizeImageProcessFactory__
static ROIClipperProcessFactory __global_ROIClipperProcessFactory__
static ROIMaskProcessFactory __global_ROIMaskProcessFactory__
static ROIMergerProcessFactory __global_ROIMergerProcessFactory__
static ROIPadProcessFactory __global_ROIPadProcessFactory__
static SegmentAnaProcessFactory __global_SegmentAnaProcessFactory__
static SegmentMakerProcessFactory __global_SegmentMakerProcessFactory__
static SegmentMaskProcessFactory __global_SegmentMaskProcessFactory__
static SegmentRelabelProcessFactory __global_SegmentRelabelProcessFactory__
static SegWeightInstanceProcessFactory __global_SegWeightInstanceProcessFactory__
static SegWeightTrackShowerProcessFactory __global_SegWeightTrackShowerProcessFactory__
static SimpleDigitizerProcessFactory __global_SimpleDigitizerProcessFactory__
static SliceImagesProcessFactory __global_SliceImagesProcessFactory__
static StepDigitizerProcessFactory __global_StepDigitizerProcessFactory__
static UnionROIProcessFactory __global_UnionROIProcessFactory__
static WireMaskProcessFactory __global_WireMaskProcessFactory__
static AlgoDataAnaProcessFactory __global_AlgoDataAnaProcessFactory__
static LArbysImageAnaProcessFactory __global_LArbysImageAnaProcessFactory__
static LArbysImageFilterProcessFactory __global_LArbysImageFilterProcessFactory__
static LArbysImageOutProcessFactory __global_LArbysImageOutProcessFactory__
static LArbysImagePIDProcessFactory __global_LArbysImagePIDProcessFactory__
static LArbysTrashProcessFactory __global_LArbysTrashProcessFactory__
static ParticleAnaProcessFactory __global_ParticleAnaProcessFactory__
static PreProcessorAnaProcessFactory __global_PreProcessorAnaProcessFactory__
static BadRegionAnaProcessFactory __global_BadRegionAnaProcessFactory__
static BlankImageProcessFactory __global_BlankImageProcessFactory__
static CosmicPixelAnaProcessFactory __global_CosmicPixelAnaProcessFactory__
static CosmicTrackAnaProcessFactory __global_CosmicTrackAnaProcessFactory__
static CosmicVertexAnaProcessFactory __global_CosmicVertexAnaProcessFactory__
static DeadWireAnaProcessFactory __global_DeadWireAnaProcessFactory__
static ExampleAnaProcessFactory __global_ExampleAnaProcessFactory__
static GenDeadChannelMapProcessFactory __global_GenDeadChannelMapProcessFactory__
static GoodcROIFilterProcessFactory __global_GoodcROIFilterProcessFactory__
static ImageROICheckMCProcessFactory __global_ImageROICheckMCProcessFactory__
static LArbysImageProcessFactory __global_LArbysImageProcessFactory__
static LArbysImageCheaterProcessFactory __global_LArbysImageCheaterProcessFactory__
static LArbysImageExtractProcessFactory __global_LArbysImageExtractProcessFactory__
static LArbysImageMCProcessFactory __global_LArbysImageMCProcessFactory__
static LArbysImageReAnaProcessFactory __global_LArbysImageReAnaProcessFactory__
static LEE1e1pAnaProcessFactory __global_LEE1e1pAnaProcessFactory__
static OperateImageProcessFactory __global_OperateImageProcessFactory__
static PGraphTruthMatchProcessFactory __global_PGraphTruthMatchProcessFactory__
static PIDImageMakerProcessFactory __global_PIDImageMakerProcessFactory__
static ROIAnaProcessFactory __global_ROIAnaProcessFactory__
static SegmentFilterProcessFactory __global_SegmentFilterProcessFactory__
static SingleROIFakerProcessFactory __global_SingleROIFakerProcessFactory__
static SSNetEventAnaProcessFactory __global_SSNetEventAnaProcessFactory__
static SSNetTruthAnaProcessFactory __global_SSNetTruthAnaProcessFactory__
static VertexAnaProcessFactory __global_VertexAnaProcessFactory__
static VertexFilterProcessFactory __global_VertexFilterProcessFactory__
static VertexInROIProcessFactory __global_VertexInROIProcessFactory__
static SuperaBaseProcessFactory __global_SuperaBaseProcessFactory__
static SuperaChStatusProcessFactory __global_SuperaChStatusProcessFactory__
static SuperaHitProcessFactory __global_SuperaHitProcessFactory__
static SuperaKeyPointClusterProcessFactory __global_SuperaKeyPointClusterProcessFactory__
static SuperaMCPClusterProcessFactory __global_SuperaMCPClusterProcessFactory__
static SuperaMCROIProcessFactory __global_SuperaMCROIProcessFactory__
static SuperaMetaMakerProcessFactory __global_SuperaMetaMakerProcessFactory__
static SuperaOpDigitProcessFactory __global_SuperaOpDigitProcessFactory__
static SuperaSimChProcessFactory __global_SuperaSimChProcessFactory__
static SuperaSimVoxel3DProcessFactory __global_SuperaSimVoxel3DProcessFactory__
static SuperaWireProcessFactory __global_SuperaWireProcessFactory__
static DataStreamProcessFactory __global_DataStreamProcessFactory__
static ImageMergerProcessFactory __global_ImageMergerProcessFactory__
static DoNothingProcessFactory __global_DoNothingProcessFactory__
static SimplePixelAnaProcessFactory __global_SimplePixelAnaProcessFactory__
static ReadRuiFileProcessFactory __global_ReadRuiFileProcessFactory__
static ReadJarrettFileProcessFactory __global_ReadJarrettFileProcessFactory__
static ReadNueFileProcessFactory __global_ReadNueFileProcessFactory__
static Run3DTrackerProcessFactory __global_Run3DTrackerProcessFactory__
static TrackerEventDisplayProcessFactory __global_TrackerEventDisplayProcessFactory__
static PassProcessFactory __global_PassProcessFactory__
static ChStatusConverterProcessFactory __global_ChStatusConverterProcessFactory__
static VertexImgProcessFactory __global_VertexImgProcessFactory__
Detailed Description
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
AStar algorithm assuming 3D!! grid points.
Uses Image2D to hold image.
Typedef Documentation
a3dpos_pair_t
typedef std::pair< A3DPixPos_t, AStar3DNode* > larcv::a3dpos_pair_t
Definition at line 152 of file AStar3DAlgo.h.
ImageIndex_t
typedef unsigned short larcv::ImageIndex_t
Image index type for Image2D within EventImage2D.
Definition at line 12 of file DataFormatTypes.h.
MCIndex_t
typedef size_t larcv::MCIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
Definition at line 21 of file MCInfoTypes.h.
MCIndexSet_t
typedef std::vector<larcv::supera::MCIndex_t> larcv::MCIndexSet_t
A collection of MCIndex_t for multiple MCShowers/MCTracks.
Definition at line 23 of file MCInfoTypes.h.
MCSTIndex_t
typedef unsigned short larcv::MCSTIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
Definition at line 17 of file DataFormatTypes.h.
MCTIndex_t
typedef unsigned short larcv::MCTIndex_t
"ID" of MCTruth in terms of its index number in the collection std::vector
Definition at line 19 of file DataFormatTypes.h.
MCTrackID_t
typedef size_t larcv::MCTrackID_t
"ID" of MCParticles in terms of its G4 track ID (unless mixing multiple MC samples)
Definition at line 75 of file DataFormatTypes.h.
MCTrackIDSet_t
typedef std::set< larcv::supera::MCTrackID_t > larcv::MCTrackIDSet_t
A collection of MCTrackID_t for multiple MCParticles.
Definition at line 77 of file DataFormatTypes.h.
ParticleROIIndex_t
typedef unsigned short larcv::ParticleROIIndex_t
Definition at line 12 of file old/DataFormatTypes.h.
PathList_t
typedef std::vector< std::vector<AStar3DNode> > larcv::PathList_t
Definition at line 149 of file AStar3DAlgo.h.
PlaneID_t
typedef unsigned short larcv::PlaneID_t
"ID" for wire planes
Definition at line 21 of file DataFormatTypes.h.
ProcessID_t
typedef size_t larcv::ProcessID_t
A unique identifier for an instantiated processes.
Definition at line 6 of file ProcessorTypes.h.
ProducerID_t
typedef size_t larcv::ProducerID_t
ProducerID_t to identify a unique data product within a process (for larcv::IOManager)
Definition at line 80 of file DataFormatTypes.h.
ROIIndex_t
typedef unsigned short larcv::ROIIndex_t
ROI index type for ROI within EventROI.
Definition at line 14 of file DataFormatTypes.h.
Voxel3DID_t
typedef unsigned long long larcv::Voxel3DID_t
"ID" for Voxel3D
Definition at line 26 of file DataFormatTypes.h.
Enumeration Type Documentation
BufferState_t
enum larcv::BufferState_t
Enumerator
kEmpty
kInit
kReady
kClean
kUndefined
Definition at line 24 of file CircularBufferBase.h.
                      {
     kEmpty,
     kInit,
     kReady,
     kClean,
     kUndefined
   };
ParticleType_t [1/2]
enum larcv::ParticleType_t
Enumerator
kEminus
kKminus
kProton
kMuminus
kPiminus
kGamma
kPizero
kBNB
kCosmic
kUnknownParticle
kMCShower
kMCTrack
kUnknown
Definition at line 9 of file MCInfoTypes.h.
                       {
     kMCShower,
     kMCTrack,
     kUnknown
   };
ParticleType_t [2/2]
enum larcv::ParticleType_t
Enumerator
kEminus
kKminus
kProton
kMuminus
kPiminus
kGamma
kPizero
kBNB
kCosmic
kUnknownParticle
kMCShower
kMCTrack
kUnknown
Definition at line 28 of file old/DataFormatTypes.h.
                       {
     kEminus,
     kKminus,
     kProton,
     kMuminus,
     kPiminus,
     kGamma,
     kPizero,
     kBNB,
     kCosmic,
     kUnknownParticle
   };
PoolType_t
enum larcv::PoolType_t
Pooling type.
Enumerator
kPoolSum
sum channels
kPoolAverage
average over channels
kPoolMax
max channel
Definition at line 46 of file DataFormatTypes.h.
                   {
     kPoolSum,
     kPoolAverage,
     kPoolMax
   };
ProductType_t
enum larcv::ProductType_t
Type of data product.
Enumerator
kProductImage2D
Image2D, EventImage2D.
kProductROI
ROI, EventROI.
kProductChStatus
ChStatus, EventChStatus.
kProductPixel2D
Pixel2D, Pixel2DCluster.
kProductPGraph
PGraph, EventPGraph.
kProductVoxel3D
Voxel3D, EventVoxel3D.
kProductUnknown
LArbys.
Definition at line 85 of file DataFormatTypes.h.
                      {
     kProductImage2D,
     kProductROI,
     kProductChStatus,
     kProductPixel2D,
     //kProductGeo2D,    ///< Vector2D, LineSegment2D
     kProductPGraph,
     kProductVoxel3D,
     kProductUnknown
   };
ROIType_t
enum larcv::ROIType_t
larcv::ROI types, used to define classification class typically
Enumerator
kROIUnknown
LArbys.
kROICosmic
Cosmics.
kROIBNB
BNB.
kROIEminus
Electron.
kROIGamma
Gamma.
kROIPizero
Pi0.
kROIMuminus
Muon.
kROIKminus
Kaon.
kROIPiminus
Charged Pion.
kROIProton
Proton.
kROITypeMax
enum element counter
Definition at line 60 of file DataFormatTypes.h.
                  {
     kROIUnknown=0,
     kROICosmic,
     kROIBNB,
     kROIEminus,
     kROIGamma,
     kROIPizero,
     kROIMuminus,
     kROIKminus,
     kROIPiminus,
     kROIProton,
     kROITypeMax
   };
ShapeType_t [1/2]
enum larcv::ShapeType_t
Enumerator
kShapeShower
Shower.
kShapeTrack
Track.
kShapeUnknown
LArbys.
kMCShower
kMCTrack
kUnknownShape
Definition at line 22 of file old/DataFormatTypes.h.
                    {
     kMCShower,
     kMCTrack,
     kUnknownShape
   };
ShapeType_t [2/2]
enum larcv::ShapeType_t
Object appearance type in LArTPC.
Enumerator
kShapeShower
Shower.
kShapeTrack
Track.
kShapeUnknown
LArbys.
kMCShower
kMCTrack
kUnknownShape
Definition at line 53 of file DataFormatTypes.h.
                    {
     kShapeShower,
     kShapeTrack,
     kShapeUnknown
   };
ThreadFillerState_t
enum larcv::ThreadFillerState_t
Enumerator
kThreadStateIdle
kThreadStateStarting
kThreadStateRunning
kThreadStateUnknown
Definition at line 6 of file APICaffeTypes.h.
{
         kThreadStateIdle,
         kThreadStateStarting,
         kThreadStateRunning,
         kThreadStateUnknown
     };
Type_t
enum larcv::Type_t strong
Enumerator
kUnknown
kTrack
kShower
Definition at line 10 of file PixelChunk.h.
 { kUnknown, kTrack, kShower };
Function Documentation
as_caffe_ndarray()
PyObject * larcv::as_caffe_ndarray (const Image2D & img)
larcv::Image2D to numpy array converter
Definition at line 71 of file PyUtils.cxx.
References larcv::Image2D::as_vector(), larcv::ImageMeta::cols(), larcv::Image2D::meta(), larcv::ImageMeta::rows(), and SetPyUtil().
{
   SetPyUtil();
   int *dim_data = new int[2];
   dim_data[0] = img.meta().rows();
   dim_data[1] = img.meta().cols();
   auto const &vec = img.as_vector();
   return PyArray_FromDimsAndData(2, dim_data, NPY_FLOAT, (char *)&(vec[0]));
 }
as_gray_mat()
cv::Mat larcv::as_gray_mat (const Image2D & larcv_img, float q_min, float q_max, float q_to_gray)
Definition at line 28 of file CVUtil.cxx.
References larcv::Image2D::meta(), and larcv::Image2D::pixel().
Referenced by larcv::PreProcessorAna::process().
   {
     auto const& meta = larcv_img.meta();
     cv::Mat img(meta.rows(),meta.cols(),CV_8UC1);
     unsigned char* px_ptr = (unsigned char*)img.data;
     for(size_t i=0;i<meta.rows();i++) {
       for (size_t j=0;j<meta.cols();j++) {
     float q = larcv_img.pixel(i,j);
     q -= q_min;
     if(q < 0) q = 0;
     if(q > q_max) q = q_max;
     q /= q_to_gray;
     px_ptr[i*img.cols + j] = (uchar)((int)q);
     //img.at<uchar>(j,meta.rows()-1-i) = (uchar)((int)q);
       }
     }
     return img;
   }
as_image2d()
Image2D larcv::as_image2d (PyObject * pyarray)
Definition at line 105 of file PyUtils.cxx.
References larcv::logger::get(), larcv::msg::kCRITICAL, kINVALID_PLANE, larcv::logger::send(), and SetPyUtil().
Referenced by larcv::PyImageMaker::append_ndarray(), and larcv::PyImageStitcher::append_ndarray().
{
   SetPyUtil();
   float **carray;
   // Create C arrays from numpy objects:
   const int dtype = NPY_FLOAT;
   PyArray_Descr *descr = PyArray_DescrFromType(dtype);
   npy_intp dims[3];
   if (PyArray_AsCArray(&pyarray, (void **)&carray, dims, 2, descr) < 0) {
     logger::get("PyUtil").send(larcv::msg::kCRITICAL, __FUNCTION__, __LINE__,
                                "ERROR: cannot convert to 2D C-array");
     throw larbys();
   }
   std::vector<float> res_data(dims[0] * dims[1], 0.);
   for (int i = 0; i < dims[0]; ++i) {
     for (int j = 0; j < dims[1]; ++j) {
       res_data[i * dims[1] + j] = (float)(carray[j][i]);
     }
   }
   PyArray_Free(pyarray, (void *)carray);
   ImageMeta meta((double)(dims[0]), (double)(dims[1]), (size_t)(dims[1]),
                  (size_t)(dims[0]), 0., 0., larcv::kINVALID_PLANE);
   Image2D res(std::move(meta), std::move(res_data));
   return res;
 }
as_image2d_meta()
Image2D larcv::as_image2d_meta (PyObject * pyarray, ImageMeta meta)
Definition at line 80 of file PyUtils.cxx.
References larcv::logger::get(), larcv::msg::kCRITICAL, larcv::logger::send(), and SetPyUtil().
Referenced by larcv::PyImageMaker::append_ndarray_meta(), and larcv::PyImageStitcher::append_ndarray_meta().
{
   SetPyUtil();
   float **carray;
   // Create C arrays from numpy objects:
   const int dtype = NPY_FLOAT;
   PyArray_Descr *descr = PyArray_DescrFromType(dtype);
   npy_intp dims[3];
   if (PyArray_AsCArray(&pyarray, (void **)&carray, dims, 2, descr) < 0) {
     logger::get("PyUtil").send(larcv::msg::kCRITICAL, __FUNCTION__, __LINE__,
                                "ERROR: cannot convert to 2D C-array");
     throw larbys();
   }
   std::vector<float> res_data(dims[0] * dims[1], 0.);
   for (int i = 0; i < dims[0]; ++i) {
     for (int j = 0; j < dims[1]; ++j) {
       res_data[i * dims[1] + j] = (float)(carray[j][i]);
     }
   }
   PyArray_Free(pyarray, (void *)carray);
   Image2D res(std::move(meta), std::move(res_data));
   return res;
 }
as_mat()
cv::Mat larcv::as_mat (const Image2D & larcv_img)
Image2D to cv::Mat converter (not supported in ROOT5 CINT)
Definition at line 8 of file CVUtil.cxx.
References larcv::Image2D::meta(), and larcv::Image2D::pixel().
   {
     auto const& meta = larcv_img.meta();
     cv::Mat img(meta.rows(),meta.cols(),CV_8UC3);
     unsigned char* px_ptr = (unsigned char*)img.data;
     int cn = img.channels();
     for(size_t i=0;i<meta.rows();i++) {
       for (size_t j=0;j<meta.cols();j++) {
     float q = larcv_img.pixel(i,j);
     px_ptr[i*img.cols*cn + j*cn + 0] = (unsigned char)(((int)(q+0.5)));
     px_ptr[i*img.cols*cn + j*cn + 1] = (unsigned char)(((int)(q+0.5))/256);
     px_ptr[i*img.cols*cn + j*cn + 2] = (unsigned char)(((int)(q+0.5))/256/256);
       }
     }
     return img;
   }
as_mat_1FC()
cv::Mat larcv::as_mat_1FC (const Image2D & larcv_img)
Definition at line 49 of file CVUtil.cxx.
References larcv::Image2D::meta(), and larcv::Image2D::pixel().
   {
     auto const& meta = larcv_img.meta();
     cv::Mat img(meta.rows(),meta.cols(),CV_32FC1);
     for(size_t i=0;i<meta.rows();i++) {
       for (size_t j=0;j<meta.cols();j++) {
     float q = larcv_img.pixel(i,j);
     img.at<float>(i,j) = q;
       }
     }
     return img;
   }
as_mat_greyscale2bgr()
cv::Mat larcv::as_mat_greyscale2bgr (const Image2D & larcv_img, const float min, const float max)
Definition at line 64 of file CVUtil.cxx.
References larcv::Image2D::meta(), and larcv::Image2D::pixel().
   {
     // converts into a color scaled image
     auto const& meta = larcv_img.meta();
     cv::Mat img(meta.rows(),meta.cols(),CV_8UC3);
     unsigned char* px_ptr = (unsigned char*)img.data;
     int cn = img.channels();
     for(size_t i=0;i<meta.rows();i++) {
       for (size_t j=0;j<meta.cols();j++) {
     float q = larcv_img.pixel(i,j);
     if ( q>max ) q = max;
     if ( q<min ) q = min;
     float rgbval = ((q-min)/(max-min))*255.0;
     px_ptr[i*img.cols*cn + j*cn + 0] = (unsigned char)(((int)(rgbval)));
     px_ptr[i*img.cols*cn + j*cn + 1] = (unsigned char)(((int)(rgbval)));
     px_ptr[i*img.cols*cn + j*cn + 2] = (unsigned char)(((int)(rgbval)));
       }
     }
     return img;
   }
as_ndarray() [1/2]
PyObject * larcv::as_ndarray (const std::vector< float > & vec)
Definition at line 20 of file PyUtils.cxx.
References LARCV_CRITICAL, and SetPyUtil().
{
   SetPyUtil();
   if (vec.size() >= INT_MAX) {
     LARCV_CRITICAL() << "Length of data vector too long to specify ndarray. "
                         "Use by batch call."
                      << std::endl;
     throw larbys();
   }
   int nd = 1;
   npy_intp dims[1];
   dims[0] = (int)vec.size();
   PyArrayObject *array = (PyArrayObject *)PyArray_SimpleNewFromData(
       nd, dims, NPY_FLOAT, (char *)&(vec[0]));
   return PyArray_Return(array);
 }
as_ndarray() [2/2]
PyObject * larcv::as_ndarray (const Image2D & img)
larcv::Image2D to numpy array converter
Definition at line 37 of file PyUtils.cxx.
References larcv::Image2D::as_vector(), larcv::ImageMeta::cols(), larcv::Image2D::meta(), larcv::ImageMeta::rows(), and SetPyUtil().
{
   SetPyUtil();
   int *dim_data = new int[2];
   dim_data[0] = img.meta().cols();
   dim_data[1] = img.meta().rows();
   auto const &vec = img.as_vector();
   return PyArray_FromDimsAndData(2, dim_data, NPY_FLOAT, (char *)&(vec[0]));
 }
as_th2d()
TH2D larcv::as_th2d (const larcv::Image2D & img, std::string histname)
Definition at line 8 of file ROOTUtil.cxx.
References larcv::ImageMeta::cols(), larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), larcv::Image2D::meta(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::Image2D::pixel(), and larcv::ImageMeta::rows().
Referenced by as_th2d_v(), and larcv::ViewROOT::draw().
{
     const larcv::ImageMeta& meta = img.meta();
     // convert to th2d
     std::string hname = histname;
     if ( hname=="" )
       hname = "_temp_image2d_";
     TH2D h( hname.c_str(), "", meta.cols(), meta.min_x(), meta.max_x(), meta.rows(), meta.min_y(), meta.max_y() );
     for (size_t r=0; r<meta.rows(); r++) {
       for (size_t c=0; c<meta.cols(); c++) {
     h.SetBinContent( c+1, r+1, img.pixel( r, c ) );
       }
     }
     return h;
   }
as_th2d_v()
std::vector< TH2D > larcv::as_th2d_v (const std::vector< larcv::Image2D > & img_v, std::string histstemname)
Definition at line 29 of file ROOTUtil.cxx.
References as_th2d().
{
     std::vector< TH2D > h_v;
     h_v.reserve( img_v.size() );
     std::string stem = histstemname;
     if ( stem=="" )
       stem = "_image2d_v";
     for (size_t i=0; i<img_v.size(); i++) {
       std::stringstream ss;
       ss << stem << "_" << i;
       TH2D h = as_th2d( img_v[i], ss.str().c_str() );
       h_v.push_back( std::move(h) );
     }
     return h_v;
   }
cluster_to_image2d()
Image2D larcv::cluster_to_image2d (const Pixel2DCluster & pcluster, size_t target_rows, size_t target_cols)
Definition at line 8 of file ImageModUtils.cxx.
References kINVALID_PLANE, larcv::Pixel2DCluster::max_x(), larcv::Pixel2DCluster::max_y(), larcv::Pixel2DCluster::min_x(), larcv::Pixel2DCluster::min_y(), and larcv::Image2D::set_pixel().
   {
     double origin_x = 0.;
     if(!target_cols) {
       double min_x = pcluster.min_x();
       double max_x = pcluster.max_x();
       origin_x = min_x;
       target_cols = (max_x - min_x + 1);
     }else{
       // find charge centroid
       double mean_x=0;
       double nonzero_npt=0;
       for(auto const& px : pcluster) {
     if(px.Intensity() <= 0) continue;
     mean_x += px.X();
     nonzero_npt += 1.;
       }
       mean_x /= nonzero_npt;
       // compute the origin from centroid position
       origin_x = mean_x - ((double)target_cols)/2.;
     }
     double origin_y = 0.;
     if(!target_rows) {
       double min_y = pcluster.min_y();
       double max_y = pcluster.max_y();
       origin_y = max_y;
       target_rows = (max_y - min_y + 1);
     }else{
       // find charge centroid
       double mean_y=0;
       double nonzero_npt=0;
       for(auto const& px : pcluster) {
     if(px.Intensity() <= 0) continue;
     mean_y += px.Y();
     nonzero_npt += 1.;
       }
       mean_y /= nonzero_npt;
       // compute the origin from centroid position
       origin_y = mean_y + ((double)target_rows)/2.;
     }
     ImageMeta meta(target_cols, target_rows,
            target_rows, target_cols,
            origin_x, origin_y,
            larcv::kINVALID_PLANE);
     Image2D res(meta);
     for(auto const& px : pcluster) {
       int col = (int)((double)(px.X()) - origin_x + 0.5);
       if(col < 0 || col >= (int)(target_cols)) continue;
       int row = (int)(origin_y - (double)(px.Y()) - 0.5);
       if(row < 0 || row >= (int)(target_rows)) continue;
       res.set_pixel(row,col,px.Intensity());
     }
     return res;
   }
ConfigFile2String()
std::string larcv::ConfigFile2String (std::string fname)
Given a configuration string, format to create larcv::PSet.
Given a configuration file (full path), read & parse contents to create larcv::PSet
Definition at line 9 of file LArCVBaseUtilFunc.cxx.
Referenced by CreatePSetFromFile().
   {
     std::ifstream filestrm(fname.c_str());
     std::string   contents;
     std::string   line;
     while(std::getline(filestrm, line)) {
       if(line.empty()) continue;
       std::stringstream linestrm(line);
       std::string       valid_line;
       std::getline(linestrm, valid_line, '#');
       if(valid_line.empty()) continue;
       contents += " " + valid_line;
     }
     filestrm.close();
     return contents;
   }
copy_array()
void larcv::copy_array (PyObject * arrayin, const std::vector< float > & cvec)
copy array
Definition at line 46 of file PyUtils.cxx.
References SetPyUtil().
{
   SetPyUtil();
   PyArrayObject *ptr = (PyArrayObject *)(arrayin);
   /*
   std::cout<< PyArray_NDIM(ptr) << std::endl
            << PyArray_DIM(ptr,0)<<std::endl
            << PyArray_SIZE(ptr) << std::endl;
   */
   // Check dimension size is 1:
   if (PyArray_NDIM(ptr) != 1){
     throw std::exception();
   }
   if (cvec.size() != PyArray_SIZE(ptr))
     throw std::exception();
   npy_intp loc[1];
   loc[0] = 0;
   auto fptr = (float *)(PyArray_GetPtr(ptr, loc));
   for (size_t i = 0; i < size_t(PyArray_SIZE(ptr)); ++i) {
     // std::cout << fptr[i] << std::endl;
     fptr[i] = cvec[i];
   };
 }
CreatePSetFromFile()
PSet larcv::CreatePSetFromFile (std::string fname, std::string cfg_name)
Given a configuration file (full path), create and return larcv::PSet.
Definition at line 32 of file LArCVBaseUtilFunc.cxx.
References ConfigFile2String().
Referenced by larcv::ConfigManager::AddConfigFile(), larcv::MergeTwoStream::configure(), larcv::ThreadDatumFiller::configure(), larcv::ProcessDriver::configure(), larlite::Supera::initialize(), and larcv::ThreadDatumFiller::set_next_batch().
   {
     PSet res(cfg_name,ConfigFile2String(fname));
     return res;
   }
crop_meta()
ImageMeta larcv::crop_meta (const Image2D & img, const ImageMeta & meta)
Definition at line 138 of file LArbysUtils.cxx.
References larcv::ImageMeta::col(), larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), larcv::Image2D::meta(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::pixel_width(), larcv::ImageMeta::plane(), and larcv::ImageMeta::row().
Referenced by crop_metas(), and larcv::Image2D::meta().
   {
     // Croppin region must be within the image
     if( meta.min_x() < img.meta().min_x() || meta.min_y() < img.meta().min_y() ||
     meta.max_x() > img.meta().max_x() || meta.max_y() > img.meta().max_y() )
       throw larbys("Cropping region contains region outside the image!");
     size_t min_col = img.meta().col(meta.min_x() + img.meta().pixel_width()  / 2. );
     size_t max_col = img.meta().col(meta.max_x() - img.meta().pixel_width()  / 2. );
     size_t min_row = img.meta().row(meta.max_y() - img.meta().pixel_height() / 2. );
     size_t max_row = img.meta().row(meta.min_y() + img.meta().pixel_height() / 2. );
     return ImageMeta( (max_col - min_col + 1) * img.meta().pixel_width(),
               (max_row - min_row + 1) * img.meta().pixel_height(),
               (max_row - min_row + 1),
               (max_col - min_col + 1),
               img.meta().min_x() + min_col * img.meta().pixel_width(),
               img.meta().max_y() - min_row * img.meta().pixel_height(),
               img.meta().plane());
   }
crop_metas()
std::vector< ImageMeta > larcv::crop_metas (const std::vector< Image2D > & img_v, const std::vector< ImageMeta > & meta_v)
Definition at line 126 of file LArbysUtils.cxx.
References crop_meta().
Referenced by larcv::LEE1e1pAna::process(), larcv::VertexAna::process(), larcv::BadRegionAna::process(), and larcv::CosmicVertexAna::process().
{
     assert(img_v.size() == meta_v.size());
     std::vector<ImageMeta> res_v;
     res_v.resize(img_v.size());
     for(size_t img_id=0; img_id < img_v.size(); ++img_id)
       res_v[img_id] = crop_meta(img_v[img_id], meta_v[img_id]);
     return res_v;
   }
Cross2D()
float larcv::Cross2D (const geo2d::Vector< float > & u, const geo2d::Vector< float > & v)
Definition at line 181 of file LArbysUtils.cxx.
Referenced by TriangleIsCCW().
   {
     return (u.x * v.y) - (u.y * v.x);
   }
CSVData::get_container< std::string >()
template<> const std::map<std::string,std::vector<std::string> >& larcv::CSVData::get_container< std::string > () const inline
Definition at line 73 of file CSVReader.h.
References larcv::CSVData::_data_str.
 { return _data_str;   }
draw_bb()
void larcv::draw_bb (cv::Mat & mat, const larcv::ImageMeta & img_meta, const larcv::ImageMeta & bbox, const int r, const int g, const int b, const int thickness)
Definition at line 168 of file CVUtil.cxx.
References larcv::ImageMeta::col(), larcv::ImageMeta::max_x(), larcv::ImageMeta::max_y(), larcv::ImageMeta::min_x(), larcv::ImageMeta::min_y(), and larcv::ImageMeta::row().
{
     cv::rectangle( mat,
            cv::Point( img_meta.col( bbox.min_x() ), img_meta.row( bbox.min_y() ) ),
            cv::Point( img_meta.col( bbox.max_x() ), img_meta.row( bbox.max_y() ) ),
            cv::Scalar( b, g, r ),
            thickness );
   }
fill_img_col()
void larcv::fill_img_col (Image2D & img, std::vector< short > & adcs, const int col, const int timedownsampling, const float pedestal)
Definition at line 133 of file PyUtils.cxx.
References larcv::ImageMeta::cols(), larcv::ImageMeta::max_y(), larcv::Image2D::meta(), larcv::ImageMeta::min_y(), larcv::Image2D::pixel(), larcv::ImageMeta::row(), and larcv::Image2D::set_pixel().
{
   if (col < 0 || col >= img.meta().cols())
     return;
   for (int iadc = 0; iadc < (int)adcs.size(); iadc++) {
     if (iadc <= img.meta().min_y() || iadc >= img.meta().max_y())
       continue;
     int irow = img.meta().row(iadc);
     float val = img.pixel(irow, col);
     img.set_pixel(irow, col, val + ((float)adcs.at(iadc) - pedestal));
   }
 }
Get2DRoi()
cv::Rect larcv::Get2DRoi (const ImageMeta & meta, const ImageMeta & bb)
Definition at line 13 of file LArbysUtils.cxx.
References larcv::ImageMeta::bl(), larcv::ImageMeta::cols(), larcv::ImageMeta::height(), larcv::ImageMeta::rows(), larcv::ImageMeta::tr(), larcv::ImageMeta::width(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::LArbysImageMC::process().
{
     //bb == ROI on plane META
     float x_compression = meta.width()  / (float) meta.cols();
     float y_compression = meta.height() / (float) meta.rows();
     int x=(bb.bl().x - meta.bl().x)/x_compression;
     int y=(bb.bl().y - meta.bl().y)/y_compression;
     int dx=(bb.tr().x - bb.bl().x)/x_compression;
     int dy=(bb.tr().y - bb.bl().y)/y_compression;
     return cv::Rect(x,y,dx,dy);
   }
imread()
Image2D larcv::imread (const std::string file_name)
larcv::Image2D creator from an image file
Definition at line 123 of file CVUtil.cxx.
References larcv::Image2D::set_pixel().
Referenced by imread_gray().
   {
     ::cv::Mat image;
     image = ::cv::imread(file_name.c_str(), CV_LOAD_IMAGE_COLOR);
     ImageMeta meta(image.cols,image.rows,image.cols, image.rows, 0., 0.);
     Image2D larcv_img(meta);
     unsigned char* px_ptr = (unsigned char*)image.data;
     int cn = image.channels();
     for(int i=0;i<image.rows;i++) {
       for (int j=0;j<image.cols;j++) {
     float q = 0;
     q += (float)(px_ptr[i*image.cols*cn + j*cn + 0]);               //B
     q += (float)(px_ptr[i*image.cols*cn + j*cn + 1]) * 256.;        //G
     q += (float)(px_ptr[i*image.cols*cn + j*cn + 2]) * 256. * 256.; //R
     larcv_img.set_pixel(j,i,q);
       }
     }
     return larcv_img;
   }
imread_gray()
Image2D larcv::imread_gray (const std::string file_name)
Gray scale larcv::Image2D creator from an image file.
Definition at line 147 of file CVUtil.cxx.
References imread(), and larcv::Image2D::set_pixel().
   {
     ::cv::Mat image;
     image = ::cv::imread(file_name.c_str(), CV_LOAD_IMAGE_GRAYSCALE);
     ImageMeta meta(image.cols,image.rows,image.cols, image.rows, 0., 0.);
     Image2D larcv_img(meta);
     unsigned char* px_ptr = (unsigned char*)image.data;
     for(int i=0;i<image.rows;i++) {
       for (int j=0;j<image.cols;j++) {
     float q = 0;
     q += (float)(px_ptr[i*image.cols + j]);
     larcv_img.set_pixel(j,i,q);
       }
     }
     return larcv_img;
   }
InFiducialRegion3D()
bool larcv::InFiducialRegion3D (float X, float Y, float Z, float edge_x, float edge_y, float edge_z)
Definition at line 161 of file LArbysUtils.cxx.
Referenced by larcv::VertexAna::process().
{
     static float xmin =  0.0;
     static float ymin = -116.5;
     static float zmin =  0.0;
     static float xmax =  256.25; //cm
     static float ymax =  116.5;  //cm
     static float zmax = 1036.8;  //cm
     bool XInFid = (X < (xmax - edge_x) && (X > xmin + edge_x) );
     bool YInFid = (Y < (ymax - edge_y) && (Y > ymin + edge_y) );
     bool ZInFid = (Z < (zmax - edge_z) && (Z > zmin + edge_z) );
     if (XInFid && YInFid && ZInFid) return true;
     return false;
   }
InsideRegion()
bool larcv::InsideRegion (const geo2d::Vector< float > & p, const std::array< geo2d::Vector< float >, 4 > & v)
Definition at line 195 of file LArbysUtils.cxx.
References TriangleIsCCW().
Referenced by InsideRegions(), and larcv::BadRegionAna::process().
{
     int n = 4;
     int low = 0;
     int high = n;
     do {
       int mid = (low + high) / 2;
       if (TriangleIsCCW(v.at(0), v.at(mid), p))
     low = mid;
       else
     high = mid;
     } while (low + 1 < high);
     if (low == 0 || high == n) return false;
     return TriangleIsCCW(v.at(low), v.at(high), p);
   }
InsideRegions()
bool larcv::InsideRegions (const geo2d::Vector< float > & p, const std::vector< std::array< geo2d::Vector< float >, 4 > > & v_v)
Definition at line 215 of file LArbysUtils.cxx.
References InsideRegion().
{
     for(const auto& region : v_v) {
       if (!InsideRegion(p,region)) return false;
     }
     return true;
   }
Intersection()
geo2d::Vector< float > larcv::Intersection (const geo2d::HalfLine< float > & hline, const cv::Rect & rect)
Definition at line 58 of file LArbysUtils.cxx.
Referenced by larcv::LArbysImageMC::process(), and larcv::ROIMerger::process().
   {
     geo2d::LineSegment<float> ls1(geo2d::Vector<float>(rect.x           ,rect.y            ),
                   geo2d::Vector<float>(rect.x+rect.width,rect.y            ));
     geo2d::LineSegment<float> ls2(geo2d::Vector<float>(rect.x+rect.width,rect.y            ),
                   geo2d::Vector<float>(rect.x+rect.width,rect.y+rect.height));
     geo2d::LineSegment<float> ls3(geo2d::Vector<float>(rect.x+rect.width,rect.y+rect.height),
                   geo2d::Vector<float>(rect.x           ,rect.y+rect.height));
     geo2d::LineSegment<float> ls4(geo2d::Vector<float>(rect.x           ,rect.y+rect.height),
                   geo2d::Vector<float>(rect.x           ,rect.y            ));
     geo2d::Vector<float> pt(-1,-1);
     try {
       auto x = hline.x(ls1.pt1.y);
       pt.x=x;
       pt.y=ls1.pt1.y;
       if ( pt.x <= ls1.pt2.x and pt.x >= ls1.pt1.x ) return pt;
     } catch(...){}
     try {
       auto y = hline.y(ls2.pt1.x);
       pt.x=ls2.pt1.x;
       pt.y=y;
       if ( pt.y <= ls2.pt2.y and pt.y >= ls2.pt1.y ) return pt;
     } catch(...){}
     try {
       auto x = hline.x(ls3.pt1.y);
       pt.x=x;
       pt.y=ls3.pt1.y;
       if ( pt.x >= ls3.pt2.x and pt.x <= ls3.pt1.x ) return pt;
     } catch(...){}
     try {
       auto y= hline.y(ls4.pt1.x);
       pt.x=ls4.pt1.x;
       pt.y=y;
       if ( pt.y >= ls4.pt2.y and pt.y <= ls4.pt1.y ) return pt;
     } catch(...){}
     return pt;
   }
MakeRect()
geo2d::Rect larcv::MakeRect (const larcv::ImageMeta & meta)
Definition at line 31 of file ROIMerger.cxx.
References larcv::ImageMeta::br(), larcv::ImageMeta::tl(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::ROIMerger::process().
{
     auto xl = meta.tl().x;
     auto yl = meta.tl().y;
     auto xr = meta.br().x;
     auto yr = meta.br().y;
     auto dx = xr - xl;
     auto dy = yl - yr;
     return geo2d::Rect(xl,yr,dx,dy);
   }
mask_image()
void larcv::mask_image (Image2D & target, const Image2D & ref)
Definition at line 111 of file LArbysUtils.cxx.
References larcv::Image2D::as_vector(), larcv::Image2D::meta(), and larcv::Image2D::move().
Referenced by larcv::LArbysImage::process().
   {
     if(target.meta() != ref.meta())
       throw larbys("Cannot mask images w/ different meta");
     auto meta = target.meta();
     std::vector<float> data = target.move();
     auto const& ref_vec = ref.as_vector();
     for(size_t i=0; i<data.size(); ++i) { if(ref_vec[i]>0) data[i]=0; }
     target.move(std::move(data));
   }
mat_to_image2d()
Image2D larcv::mat_to_image2d (const cv::Mat & mat, const ImageMeta & src_meta)
Definition at line 88 of file CVUtil.cxx.
References larcv::ImageMeta::cols(), larcv::ImageMeta::height(), larcv::ImageMeta::rows(), larcv::Image2D::set_pixel(), and larcv::ImageMeta::width().
{
     int cn = mat.channels();
     // more than 1 channel assumes a color scale. not well-defined how to re-constitute image
     if ( cn>1 ) {
       throw std::runtime_error("CVUtil.cxx: mat_to_image2d, number of channels != 1");
     }
     // define the meta
     ImageMeta meta( src_meta );
     if ( meta.width()==0.0 && meta.height()==0.0 ) {
       // empty meta
       meta = ImageMeta( mat.cols, mat.rows, mat.rows, mat.cols );
     }
     larcv::Image2D img( meta );
     for (size_t i=0; i<meta.rows(); i++) {
       for (size_t j=0; j<meta.cols(); j++) {
     if ( mat.type()==CV_32F ) {
       float q = (float)mat.at<float>(i,j);
       img.set_pixel( i, j, q );
     }
     else if (mat.type()==CV_8U) {
       int q = (int)mat.at<unsigned char>(i,j);
       img.set_pixel( i, j, (float)q );
     }
     else {
       throw std::runtime_error("CVUtil.cxx: mat_to_image2d, data type not handled (accepts CV_8U=unsigned char or CV_64F=double)");
     }
       }
     }
     return img;
   }
ParticleMass()
double larcv::ParticleMass (const int pdgcode)
Utility to get a particle mass.
Definition at line 10 of file ParticleMass.cxx.
Referenced by larcv::CCQETruthFilter::process().
   {
     switch(pdgcode) {
       // electron
     case  11:
     case -11:
       return 0.510998910;
       // muon
     case  13:
     case -13:
       return 105.65838934;
       // gamma
     case 22:
       return 0.0;
       // neutrinos
     case 12:
     case 14:
       return 0.0;
       // proton
     case  2212:
     case -2212:
       return 938.272046;
       // neutron
     case  2112:
     case -2112:
       return 939.565378;
       // pi0
     case  111:
       return 134.9766;
       // pi +/-
     case  211:
     case -211:
       return 139.57018;
       // K0/K0L/K0S
     case  311:
     case  130:
     case  310:
       return 497.648;
       // K +/-
     case  321:
     case -321:
       return 493.667;
       // Delta
     case  2114:
     case  2214:
     case  2224:
     case  1114:
       return 1232.0;
       // Lambda
     case  3122:
     case -3122:
       return 1115.683;
       // Sigma+
     case  3222:
     case -3222:
       return 1189.37;
       // Sigma0
     case  3212:
     case -3212:
       return 1192.642;
       // Sigma-
     case  3112:
     case -3112:
       return 1197.449;
       // Xi0
     case  3322:
       return 1314.86;
       // Xi-/Xi+
     case  3312:
     case -3312:
       return 1321.71;
       // rho-0
     case  113:
       return 775.49;
       // rho-+
     case  123:
       return 775.4;
       // phi
     case  333:
       return 1019.445;
       // eta
     case  221:
       return 547.862;
       // eta'
     case  331:
       return 957.78;
       // deuteron
     case  1000010020:
       return 1875.6;
       // tritium
     case  1000010030:
       return 2829.87;
       // Helium 3
     case  1000020030:
       return 2829.85;
       // Helium 4
     case  1000020040:
       return 3755.53;
       // Berylium 8
     case  1000040080:
       return 7511.15;
     default:
       std::stringstream msg;
       msg << "PDG Code " << pdgcode << " is not handled yet! Please implement :) ";
       throw larbys(msg.str());
     }
     return -1;
   }
PDG2ROIType()
ROIType_t larcv::PDG2ROIType (const int pdgcode)
Definition at line 8 of file UtilFunc.cxx.
References kROIBNB, kROIEminus, kROIGamma, kROIKminus, kROIMuminus, kROIPiminus, kROIPizero, kROIProton, and kROIUnknown.
Referenced by larcv::SimpleFiller::fill_entry_data(), and larcv::MultiClassFiller::fill_entry_data().
   {
     switch(pdgcode) {
       // electron
     case  11:
     case -11:
       return kROIEminus;
       // muon
     case  13:
     case -13:
       return kROIMuminus;
       // gamma
     case 22:
       return kROIGamma;
       // neutrinos
     case 12:
     case 14:
       return kROIBNB;
     // proton
     case  2212:
     case -2212:
       return kROIProton;
       // pi0
     case  111:
       return kROIPizero;
     // pi +/-
     case  211:
     case -211:
       return kROIPiminus;
       // K +/-
     case  321:
     case -321:
       return kROIKminus;
     default:
       return kROIUnknown;
     }
     return kROIUnknown;
   }
PdgCode2ROIType()
ROIType_t larcv::PdgCode2ROIType (int pdgcode)
Return larcv::ROI type from PdgCode.
Definition at line 8 of file DataFormatUtil.cxx.
References kROIEminus, kROIGamma, kROIKminus, kROIMuminus, kROIPiminus, kROIPizero, kROIProton, and kROIUnknown.
Referenced by supera::MCROIMaker::ParticleROI(), and larcv::SuperaSimCh::process().
   {
     if(pdgcode == 11 || pdgcode == -11) return kROIEminus;
     if(pdgcode == 321 || pdgcode == -321) return kROIKminus;
     if(pdgcode == 2212) return kROIProton;
     if(pdgcode == 13 || pdgcode == -13) return kROIMuminus;
     if(pdgcode == 211 || pdgcode == -211) return kROIPiminus;
     if(pdgcode == 22) return kROIGamma;
     if(pdgcode == 111) return kROIPizero;
     return kROIUnknown;
   }
ProductName() [1/2]
template<class T > std::string larcv::ProductName ()
Referenced by larcv::DataProductFactory::add_factory(), larcv::DataProductFactory::create(), larcv::IOManager< T >::get_data(), larcv::DataProductFactory::list(), larcv::IOManager< T >::register_producer(), and larcv::IOManager< T >::set_id().
ProductName() [2/2]
const char * larcv::ProductName (ProductType_t type)
Definition at line 10 of file ProductMap.cxx.
References kProductChStatus, kProductImage2D, kProductPGraph, kProductPixel2D, kProductROI, and kProductVoxel3D.
   {
     switch(type) {
     case kProductImage2D:  return "image2d";
     case kProductROI:      return "partroi";
     case kProductChStatus: return "chstatus";
     case kProductPixel2D:  return "pixel2d";
     case kProductPGraph:   return "pgraph";
     case kProductVoxel3D:  return "voxel3d";
       //case kProductGeo2D:    return "geo2d";
     default:
       std::stringstream ss;
       ss << "Unsupported type (" << type << ")! Implement DataFormat/ProductMap.cxx!" << std::endl;
       throw larbys(ss.str());
     }
   }
ProductName< larcv::Image2D >()
template<> std::string larcv::ProductName< larcv::Image2D > ()
Definition at line 13 of file old/ProductMap.cxx.
   { return "img2d"; }
ProductName< larcv::ImageMeta >()
template<> std::string larcv::ProductName< larcv::ImageMeta > ()
Definition at line 9 of file old/ProductMap.cxx.
   { return "meta2d"; }
ProductType()
template<class T > ProductType_t larcv::ProductType ()
ProductType< larcv::ChStatus >()
template<> ProductType_t larcv::ProductType< larcv::ChStatus > ()
Definition at line 29 of file ProductMap.cxx.
References kProductChStatus, and ProductType< larcv::ChStatus >().
Referenced by ProductType< larcv::ChStatus >().
 { return kProductChStatus; }
ProductType< larcv::Image2D >()
template<> ProductType_t larcv::ProductType< larcv::Image2D > ()
Definition at line 27 of file ProductMap.cxx.
References kProductImage2D.
 { return kProductImage2D;  }
ProductType< larcv::PGraph >()
template<> ProductType_t larcv::ProductType< larcv::PGraph > ()
Definition at line 31 of file ProductMap.cxx.
References kProductPGraph.
 { return kProductPGraph;   }
ProductType< larcv::Pixel2D >()
template<> ProductType_t larcv::ProductType< larcv::Pixel2D > ()
Definition at line 30 of file ProductMap.cxx.
References kProductPixel2D.
 { return kProductPixel2D;  }
ProductType< larcv::ROI >()
template<> ProductType_t larcv::ProductType< larcv::ROI > ()
Definition at line 28 of file ProductMap.cxx.
References kProductROI.
 { return kProductROI;      }
ProductType< larcv::Voxel3D >()
template<> ProductType_t larcv::ProductType< larcv::Voxel3D > ()
Definition at line 32 of file ProductMap.cxx.
References kProductVoxel3D.
 { return kProductVoxel3D;  }
Project3D()
void larcv::Project3D (const ImageMeta & meta, double parent_x, double parent_y, double parent_z, double parent_t, uint plane, double & xpixel, double & ypixel)
Definition at line 32 of file LArbysUtils.cxx.
References larcv::ImageMeta::br(), larcv::ImageMeta::cols(), larcv::ImageMeta::height(), larcv::ImageMeta::rows(), larcv::ImageMeta::tl(), larcv::ImageMeta::width(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::ExampleAna::Analyze(), larcv::ParticleAna::AnalyzeAngle(), larcv::ParticleAna::AnalyzedQdX(), larcv::ParticleAna::AnalyzeSignal(), larcv::PGraphTruthMatch::process(), and larcv::LArbysImageMC::process().
   {
     auto geohelp = larutil::GeometryHelper::GetME();//Geohelper from LArLite
     auto larpro  = larutil::LArProperties::GetME(); //LArProperties from LArLite
     auto vtx_2d = geohelp->Point_3Dto2D(parent_x, parent_y, parent_z, plane );
     double x_compression  = (double)meta.width()  / (double)meta.cols();
     double y_compression  = (double)meta.height() / (double)meta.rows();
     xpixel = (vtx_2d.w/geohelp->WireToCm() - meta.tl().x) / x_compression;
     ypixel = (((parent_x/larpro->DriftVelocity() + parent_t/1000.)*2+3200)-meta.br().y)/y_compression;
   }
ProjectTo3D()
void larcv::ProjectTo3D (const ImageMeta & meta, double parent_x, double parent_y, double parent_z, double parent_t, uint plane, double & xpixel, double & ypixel)
Definition at line 13 of file AStarUtils.cxx.
References larcv::ImageMeta::br(), larcv::ImageMeta::cols(), larcv::ImageMeta::height(), kINVALID_DOUBLE, larcv::ImageMeta::rows(), larcv::ImageMeta::tl(), larcv::ImageMeta::width(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::AStarTracker::ComputedQdX(), larcv::AStarTracker::ComputeNewdQdX(), larcv::AStarTracker::ComputeTruncateddQdX(), larcv::AStarTracker::DiagnoseTrack(), larcv::AStarTracker::DrawROI(), larcv::AStarTracker::DrawTrack(), larcv::AStarTracker::DrawVertex(), larcv::AStarTracker::GetTotalPixADC(), larcv::AStarTracker::ImprovedCluster(), larcv::AStarTracker::MaskTrack(), larcv::AStarTracker::MaskVertex(), larcv::AStarTracker::Reconstruct(), larcv::AStarTracker::RecoverFromFail(), larcv::AStarTracker::SetTimeAndWireBounds(), and larcv::AStarTracker::SortAndOrderPoints().
   {
     auto geohelp = larutil::GeometryHelper::GetME();//Geohelper from LArLite
     auto larpro  = larutil::LArProperties::GetME(); //LArProperties from LArLite
     auto vtx_2d = geohelp->Point_3Dto2D(parent_x, parent_y, parent_z, plane );
     double x_compression  = (double)meta.width()  / (double)meta.cols();
     double y_compression  = (double)meta.height() / (double)meta.rows();
     xpixel = (vtx_2d.w/geohelp->WireToCm() - meta.tl().x) / x_compression;
     ypixel = (((parent_x/larpro->DriftVelocity() + parent_t/1000.)*2+3200)-meta.br().y)/y_compression;
   }
PSet::get< larcv::PSet >()
template<> PSet larcv::PSet::get< larcv::PSet > (const std::string & key) const
Definition at line 369 of file PSet.cxx.
References larcv::PSet::get_pset().
   { return this->get_pset(key); }
read_csv()
CSVData larcv::read_csv (const std::string fname, const std::string format) inline
Definition at line 99 of file CSVReader.h.
References larcv::CSVData::CSVData().
Referenced by larcv::RSEFilter::configure().
   { return CSVData(fname,format); }
ROIType2String()
std::string larcv::ROIType2String (const ROIType_t type)
Definition at line 48 of file UtilFunc.cxx.
References kROIBNB, kROICosmic, kROIEminus, kROIGamma, kROIKminus, kROIMuminus, kROIPiminus, kROIPizero, kROIProton, and kROIUnknown.
Referenced by larcv::ROI::dump(), larcv::SegmentFilter::process(), and larcv::DataProductFactory::ROIType2String().
   {
     switch(type) {
     case kROIUnknown: return "Unknown";
     case kROICosmic:  return "Cosmic";
     case kROIBNB:     return "BNB";
     case kROIEminus:  return "Eminus";
     case kROIGamma:   return "Gamms";
     case kROIPizero:  return "Pizero";
     case kROIMuminus: return "Muminus";
     case kROIKminus:  return "Kminus";
     case kROIPiminus: return "Piminus";
     case kROIProton:  return "Proton";
     default:
       std::stringstream ss;
       ss << "Unsupported type: " << type << std::endl;
       throw larbys(ss.str());
     }
     return "";
   }
SetPyUtil()
void larcv::SetPyUtil ()
Utility function: call one-time-only numpy module initialization (you don't have to call)
Definition at line 12 of file PyUtils.cxx.
Referenced by as_caffe_ndarray(), as_image2d(), as_image2d_meta(), as_ndarray(), and copy_array().
                  {
   static bool once = false;
   if (!once) {
     import_array();
     once = true;
   }
 }
String2ROIType()
ROIType_t larcv::String2ROIType (const std::string & name)
Definition at line 69 of file UtilFunc.cxx.
References kROIBNB, kROICosmic, kROIEminus, kROIGamma, kROIKminus, kROIMuminus, kROIPiminus, kROIPizero, kROIProton, and kROIUnknown.
Referenced by larcv::SegmentFilter::configure(), larcv::SegmentMask::configure(), and larcv::DataProductFactory::String2ROIType().
   {
     if(name == "Unknown") return kROIUnknown;
     if(name == "Cosmic" ) return kROICosmic;
     if(name == "BNB"    ) return kROIBNB;
     if(name == "Eminus" ) return kROIEminus;
     if(name == "Gamma"  ) return kROIGamma;
     if(name == "Pizero" ) return kROIPizero;
     if(name == "Muminus") return kROIMuminus;
     if(name == "Kminus" ) return kROIKminus;
     if(name == "Piminus") return kROIPiminus;
     if(name == "Proton" ) return kROIProton;
     std::stringstream ss;
     ss << "Unsupported name: " << name << std::endl;
     throw larbys(ss.str());
     return kROIUnknown;
   }
SuperaBase::LArData< supera::LArHit_t >()
template<> const std::vector<supera::LArHit_t>& larcv::SuperaBase::LArData< supera::LArHit_t > () const
Definition at line 103 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_hit_v.
   { if(!_ptr_hit_v) throw larbys("Hit data pointer not available"); return *_ptr_hit_v; }
SuperaBase::LArData< supera::LArMCShower_t >()
template<> const std::vector<supera::LArMCShower_t>& larcv::SuperaBase::LArData< supera::LArMCShower_t > () const
Definition at line 118 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mcs_v.
   { if(!_ptr_mcs_v) throw larbys("MCShower data pointer not available"); return *_ptr_mcs_v; }
SuperaBase::LArData< supera::LArMCTrack_t >()
template<> const std::vector<supera::LArMCTrack_t>& larcv::SuperaBase::LArData< supera::LArMCTrack_t > () const
Definition at line 115 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mct_v.
   { if(!_ptr_mct_v) throw larbys("MCTrack data pointer not available"); return *_ptr_mct_v; }
SuperaBase::LArData< supera::LArMCTruth_t >()
template<> const std::vector<supera::LArMCTruth_t>& larcv::SuperaBase::LArData< supera::LArMCTruth_t > () const
Definition at line 112 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_mctruth_v.
   { if(!_ptr_mctruth_v) throw larbys("MCTruth data pointer not available"); return *_ptr_mctruth_v; }
SuperaBase::LArData< supera::LArOpDigit_t >()
template<> const std::vector<supera::LArOpDigit_t>& larcv::SuperaBase::LArData< supera::LArOpDigit_t > () const
Definition at line 106 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_opdigit_v.
   { if(!_ptr_opdigit_v) throw larbys("OpDigit data pointer not available"); return *_ptr_opdigit_v; }
SuperaBase::LArData< supera::LArSimCh_t >()
template<> const std::vector<supera::LArSimCh_t>& larcv::SuperaBase::LArData< supera::LArSimCh_t > () const
Definition at line 109 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_sch_v.
   { if(!_ptr_sch_v) throw larbys("SimCh data pointer not available"); return *_ptr_sch_v; }
SuperaBase::LArData< supera::LArWire_t >()
template<> const std::vector<supera::LArWire_t>& larcv::SuperaBase::LArData< supera::LArWire_t > () const
Definition at line 100 of file SuperaBase.cxx.
References larcv::SuperaBase::_ptr_wire_v.
   { if(!_ptr_wire_v) throw larbys("Wire data pointer not available"); return *_ptr_wire_v; }
TriangleIsCCW()
bool larcv::TriangleIsCCW (const geo2d::Vector< float > & a, const geo2d::Vector< float > & b, const geo2d::Vector< float > & c)
Definition at line 187 of file LArbysUtils.cxx.
References Cross2D().
Referenced by InsideRegion().
   {
     return Cross2D(b - a, c - b) < 0;
   }
Variable Documentation
__global_ADCScaleAnaProcessFactory__
ADCScaleAnaProcessFactory larcv::__global_ADCScaleAnaProcessFactory__ static
Definition at line 9 of file ADCScaleAna.cxx.
__global_ADCScaleProcessFactory__
ADCScaleProcessFactory larcv::__global_ADCScaleProcessFactory__ static
Definition at line 9 of file ADCScale.cxx.
__global_ADCThresholdProcessFactory__
ADCThresholdProcessFactory larcv::__global_ADCThresholdProcessFactory__ static
Definition at line 8 of file ADCThreshold.cxx.
__global_AlgoDataAnaProcessFactory__
AlgoDataAnaProcessFactory larcv::__global_AlgoDataAnaProcessFactory__ static
Definition at line 8 of file AlgoDataAna.cxx.
__global_BadRegionAnaProcessFactory__
BadRegionAnaProcessFactory larcv::__global_BadRegionAnaProcessFactory__ static
Definition at line 14 of file BadRegionAna.cxx.
__global_BinarizeProcessFactory__
BinarizeProcessFactory larcv::__global_BinarizeProcessFactory__ static
Definition at line 9 of file Binarize.cxx.
__global_BlankImageProcessFactory__
BlankImageProcessFactory larcv::__global_BlankImageProcessFactory__ static
Definition at line 9 of file BlankImage.cxx.
__global_calcPeakADCProcessFactory__
calcPeakADCProcessFactory larcv::__global_calcPeakADCProcessFactory__ static
Definition at line 9 of file calcPeakADC.cxx.
__global_CCIncFilterProcessFactory__
CCIncFilterProcessFactory larcv::__global_CCIncFilterProcessFactory__ static
Definition at line 8 of file CCIncFilter.cxx.
__global_CCQETruthFilterProcessFactory__
CCQETruthFilterProcessFactory larcv::__global_CCQETruthFilterProcessFactory__ static
Definition at line 9 of file CCQETruthFilter.cxx.
__global_ChannelMaxProcessFactory__
ChannelMaxProcessFactory larcv::__global_ChannelMaxProcessFactory__ static
Definition at line 9 of file ChannelMax.cxx.
__global_ChStatusConverterProcessFactory__
ChStatusConverterProcessFactory larcv::__global_ChStatusConverterProcessFactory__ static
Definition at line 9 of file ChStatusConverter.cxx.
__global_CombineImagesProcessFactory__
CombineImagesProcessFactory larcv::__global_CombineImagesProcessFactory__ static
Definition at line 9 of file CombineImages.cxx.
__global_CompressorProcessFactory__
CompressorProcessFactory larcv::__global_CompressorProcessFactory__ static
Definition at line 9 of file Compressor.cxx.
__global_CosmicFilterProcessFactory__
CosmicFilterProcessFactory larcv::__global_CosmicFilterProcessFactory__ static
Definition at line 10 of file CosmicFilter.cxx.
__global_CosmicPixelAnaProcessFactory__
CosmicPixelAnaProcessFactory larcv::__global_CosmicPixelAnaProcessFactory__ static
Definition at line 16 of file CosmicPixelAna.cxx.
__global_CosmicROIFillerProcessFactory__
CosmicROIFillerProcessFactory larcv::__global_CosmicROIFillerProcessFactory__ static
Definition at line 8 of file CosmicROIFiller.cxx.
__global_CosmicSegmentProcessFactory__
CosmicSegmentProcessFactory larcv::__global_CosmicSegmentProcessFactory__ static
Definition at line 9 of file CosmicSegment.cxx.
__global_CosmicTrackAnaProcessFactory__
CosmicTrackAnaProcessFactory larcv::__global_CosmicTrackAnaProcessFactory__ static
Definition at line 11 of file CosmicTrackAna.cxx.
__global_CosmicVertexAnaProcessFactory__
CosmicVertexAnaProcessFactory larcv::__global_CosmicVertexAnaProcessFactory__ static
Definition at line 26 of file CosmicVertexAna.cxx.
__global_CropROIProcessFactory__
CropROIProcessFactory larcv::__global_CropROIProcessFactory__ static
Definition at line 9 of file CropROI.cxx.
__global_DataStreamProcessFactory__
DataStreamProcessFactory larcv::__global_DataStreamProcessFactory__ static
Definition at line 11 of file DataStream.cxx.
__global_DBSCANProcessFactory__
DBSCANProcessFactory larcv::__global_DBSCANProcessFactory__ static
Definition at line 13 of file DBSCAN.cxx.
__global_DeadWireAnaProcessFactory__
DeadWireAnaProcessFactory larcv::__global_DeadWireAnaProcessFactory__ static
Definition at line 12 of file DeadWireAna.cxx.
__global_DoNothingProcessFactory__
DoNothingProcessFactory larcv::__global_DoNothingProcessFactory__ static
Definition at line 8 of file DoNothing.cxx.
__global_DumpHiResCropImagesProcessFactory__
DumpHiResCropImagesProcessFactory larcv::__global_DumpHiResCropImagesProcessFactory__ static
Definition at line 16 of file DumpHiResCropImages.cxx.
__global_EmbedImageProcessFactory__
EmbedImageProcessFactory larcv::__global_EmbedImageProcessFactory__ static
Definition at line 9 of file EmbedImage.cxx.
__global_EmptyImageFilterProcessFactory__
EmptyImageFilterProcessFactory larcv::__global_EmptyImageFilterProcessFactory__ static
Definition at line 8 of file EmptyImageFilter.cxx.
__global_EventChStatusFactory__
EventChStatusFactory larcv::__global_EventChStatusFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 10 of file EventChStatus.cxx.
__global_EventImage2DFactory__
EventImage2DFactory larcv::__global_EventImage2DFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 10 of file EventImage2D.cxx.
__global_EventPGraphFactory__
EventPGraphFactory larcv::__global_EventPGraphFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 9 of file EventPGraph.cxx.
__global_EventPixel2DFactory__
EventPixel2DFactory larcv::__global_EventPixel2DFactory__ static
Global larcv::EventPixel2DFactory to register EventPixel2D.
Definition at line 11 of file EventPixel2D.cxx.
__global_EventROIFactory__
EventROIFactory larcv::__global_EventROIFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 9 of file EventROI.cxx.
__global_EventVoxel3DFactory__
EventVoxel3DFactory larcv::__global_EventVoxel3DFactory__ static
Global larcv::EventVoxel3D to register factory.
Definition at line 9 of file EventVoxel3D.cxx.
__global_ExampleAnaProcessFactory__
ExampleAnaProcessFactory larcv::__global_ExampleAnaProcessFactory__ static
Definition at line 12 of file ExampleAna.cxx.
__global_GenDeadChannelMapProcessFactory__
GenDeadChannelMapProcessFactory larcv::__global_GenDeadChannelMapProcessFactory__ static
Definition at line 8 of file GenDeadChannelMap.cxx.
__global_GoodcROIFilterProcessFactory__
GoodcROIFilterProcessFactory larcv::__global_GoodcROIFilterProcessFactory__ static
Definition at line 12 of file GoodcROIFilter.cxx.
__global_HistADCProcessFactory__
HistADCProcessFactory larcv::__global_HistADCProcessFactory__ static
Definition at line 11 of file HistADC.cxx.
__global_ImageChargeAnaProcessFactory__
ImageChargeAnaProcessFactory larcv::__global_ImageChargeAnaProcessFactory__ static
Definition at line 8 of file ImageChargeAna.cxx.
__global_ImageFromPixel2DClusterProcessFactory__
ImageFromPixel2DClusterProcessFactory larcv::__global_ImageFromPixel2DClusterProcessFactory__ static
Definition at line 9 of file ImageFromPixel2DCluster.cxx.
__global_ImageFromPixel2DProcessFactory__
ImageFromPixel2DProcessFactory larcv::__global_ImageFromPixel2DProcessFactory__ static
Definition at line 9 of file ImageFromPixel2D.cxx.
__global_ImageMergerProcessFactory__
ImageMergerProcessFactory larcv::__global_ImageMergerProcessFactory__ static
Definition at line 11 of file ImageMerger.cxx.
__global_ImageROICheckMCProcessFactory__
ImageROICheckMCProcessFactory larcv::__global_ImageROICheckMCProcessFactory__ static
Definition at line 10 of file ImageROICheckMC.cxx.
__global_LArbysImageAnaProcessFactory__
LArbysImageAnaProcessFactory larcv::__global_LArbysImageAnaProcessFactory__ static
Definition at line 8 of file LArbysImageAna.cxx.
__global_LArbysImageCheaterProcessFactory__
LArbysImageCheaterProcessFactory larcv::__global_LArbysImageCheaterProcessFactory__ static
Definition at line 10 of file LArbysImageCheater.cxx.
__global_LArbysImageExtractProcessFactory__
LArbysImageExtractProcessFactory larcv::__global_LArbysImageExtractProcessFactory__ static
Definition at line 8 of file LArbysImageExtract.cxx.
__global_LArbysImageFilterProcessFactory__
LArbysImageFilterProcessFactory larcv::__global_LArbysImageFilterProcessFactory__ static
Definition at line 7 of file LArbysImageFilter.cxx.
__global_LArbysImageMCProcessFactory__
LArbysImageMCProcessFactory larcv::__global_LArbysImageMCProcessFactory__ static
Definition at line 12 of file LArbysImageMC.cxx.
__global_LArbysImageOutProcessFactory__
LArbysImageOutProcessFactory larcv::__global_LArbysImageOutProcessFactory__ static
Definition at line 10 of file LArbysImageOut.cxx.
__global_LArbysImagePIDProcessFactory__
LArbysImagePIDProcessFactory larcv::__global_LArbysImagePIDProcessFactory__ static
Definition at line 8 of file LArbysImagePID.cxx.
__global_LArbysImageProcessFactory__
LArbysImageProcessFactory larcv::__global_LArbysImageProcessFactory__ static
Definition at line 20 of file LArbysImage.cxx.
__global_LArbysImageReAnaProcessFactory__
LArbysImageReAnaProcessFactory larcv::__global_LArbysImageReAnaProcessFactory__ static
Definition at line 14 of file LArbysImageReAna.cxx.
__global_LArbysTrashProcessFactory__
LArbysTrashProcessFactory larcv::__global_LArbysTrashProcessFactory__ static
Definition at line 8 of file LArbysTrash.cxx.
__global_LEE1e1pAnaProcessFactory__
LEE1e1pAnaProcessFactory larcv::__global_LEE1e1pAnaProcessFactory__ static
Definition at line 17 of file LEE1e1pAna.cxx.
__global_MaskImageProcessFactory__
MaskImageProcessFactory larcv::__global_MaskImageProcessFactory__ static
Definition at line 9 of file MaskImage.cxx.
__global_MCFilterProcessFactory__
MCFilterProcessFactory larcv::__global_MCFilterProcessFactory__ static
Definition at line 9 of file MCFilter.cxx.
__global_MCSingleParticleFilterProcessFactory__
MCSingleParticleFilterProcessFactory larcv::__global_MCSingleParticleFilterProcessFactory__ static
Definition at line 8 of file MCSingleParticleFilter.cxx.
__global_MeanSubtractionProcessFactory__
MeanSubtractionProcessFactory larcv::__global_MeanSubtractionProcessFactory__ static
Definition at line 9 of file MeanSubtraction.cxx.
__global_ModularPadImageProcessFactory__
ModularPadImageProcessFactory larcv::__global_ModularPadImageProcessFactory__ static
Definition at line 9 of file ModularPadImage.cxx.
__global_MultiClassFillerProcessFactory__
MultiClassFillerProcessFactory larcv::__global_MultiClassFillerProcessFactory__ static
Definition at line 12 of file MultiClassFiller.cxx.
__global_MultiROICropperProcessFactory__
MultiROICropperProcessFactory larcv::__global_MultiROICropperProcessFactory__ static
Definition at line 9 of file MultiROICropper.cxx.
__global_NNCosineProcessFactory__
NNCosineProcessFactory larcv::__global_NNCosineProcessFactory__ static
Definition at line 16 of file NNCosine.cxx.
__global_NuFilterProcessFactory__
NuFilterProcessFactory larcv::__global_NuFilterProcessFactory__ static
Definition at line 10 of file NuFilter.cxx.
__global_OperateImageProcessFactory__
OperateImageProcessFactory larcv::__global_OperateImageProcessFactory__ static
Definition at line 10 of file OperateImage.cxx.
__global_ParticleAnaProcessFactory__
ParticleAnaProcessFactory larcv::__global_ParticleAnaProcessFactory__ static
Definition at line 14 of file ParticleAna.cxx.
__global_PassProcessFactory__
PassProcessFactory larcv::__global_PassProcessFactory__ static
Definition at line 8 of file Pass.cxx.
__global_PGraphTruthMatchProcessFactory__
PGraphTruthMatchProcessFactory larcv::__global_PGraphTruthMatchProcessFactory__ static
Definition at line 14 of file PGraphTruthMatch.cxx.
__global_PIDImageMakerProcessFactory__
PIDImageMakerProcessFactory larcv::__global_PIDImageMakerProcessFactory__ static
Definition at line 9 of file PIDImageMaker.cxx.
__global_PlaneImageMergerProcessFactory__
PlaneImageMergerProcessFactory larcv::__global_PlaneImageMergerProcessFactory__ static
Definition at line 10 of file PlaneImageMerger.cxx.
__global_PreProcessorAnaProcessFactory__
PreProcessorAnaProcessFactory larcv::__global_PreProcessorAnaProcessFactory__ static
Definition at line 11 of file PreProcessorAna.cxx.
__global_PyImageMakerProcessFactory__
PyImageMakerProcessFactory larcv::__global_PyImageMakerProcessFactory__ static
Definition at line 9 of file PyImageMaker.cxx.
__global_PyImageStitcherProcessFactory__
PyImageStitcherProcessFactory larcv::__global_PyImageStitcherProcessFactory__ static
Definition at line 9 of file PyImageStitcher.cxx.
__global_QSumFilterProcessFactory__
QSumFilterProcessFactory larcv::__global_QSumFilterProcessFactory__ static
Definition at line 8 of file QSumFilter.cxx.
__global_ReadJarrettFileProcessFactory__
ReadJarrettFileProcessFactory larcv::__global_ReadJarrettFileProcessFactory__ static
Definition at line 50 of file ReadJarrettFile.cxx.
__global_ReadNueFileProcessFactory__
ReadNueFileProcessFactory larcv::__global_ReadNueFileProcessFactory__ static
Definition at line 33 of file ReadNueFile.cxx.
__global_ReadRuiFileProcessFactory__
ReadRuiFileProcessFactory larcv::__global_ReadRuiFileProcessFactory__ static
Definition at line 45 of file ReadRuiFile.cxx.
__global_ResizeImageProcessFactory__
ResizeImageProcessFactory larcv::__global_ResizeImageProcessFactory__ static
Definition at line 8 of file ResizeImage.cxx.
__global_ROIAnaProcessFactory__
ROIAnaProcessFactory larcv::__global_ROIAnaProcessFactory__ static
Definition at line 13 of file ROIAna.cxx.
__global_ROIClipperProcessFactory__
ROIClipperProcessFactory larcv::__global_ROIClipperProcessFactory__ static
Definition at line 10 of file ROIClipper.cxx.
__global_ROICountFilterProcessFactory__
ROICountFilterProcessFactory larcv::__global_ROICountFilterProcessFactory__ static
Definition at line 9 of file ROICountFilter.cxx.
__global_ROIMaskProcessFactory__
ROIMaskProcessFactory larcv::__global_ROIMaskProcessFactory__ static
Definition at line 10 of file ROIMask.cxx.
__global_ROIMergerProcessFactory__
ROIMergerProcessFactory larcv::__global_ROIMergerProcessFactory__ static
Definition at line 13 of file ROIMerger.cxx.
__global_ROIPadProcessFactory__
ROIPadProcessFactory larcv::__global_ROIPadProcessFactory__ static
Definition at line 10 of file ROIPad.cxx.
__global_ROISizeFilterProcessFactory__
ROISizeFilterProcessFactory larcv::__global_ROISizeFilterProcessFactory__ static
Definition at line 9 of file ROISizeFilter.cxx.
__global_RSEFilterProcessFactory__
RSEFilterProcessFactory larcv::__global_RSEFilterProcessFactory__ static
Definition at line 9 of file RSEFilter.cxx.
__global_Run3DTrackerProcessFactory__
Run3DTrackerProcessFactory larcv::__global_Run3DTrackerProcessFactory__ static
Definition at line 50 of file Run3DTracker.cxx.
__global_RunFilterProcessFactory__
RunFilterProcessFactory larcv::__global_RunFilterProcessFactory__ static
Definition at line 8 of file RunFilter.cxx.
__global_SegFillerProcessFactory__
SegFillerProcessFactory larcv::__global_SegFillerProcessFactory__ static
Definition at line 11 of file SegFiller.cxx.
__global_SegImageAnaProcessFactory__
SegImageAnaProcessFactory larcv::__global_SegImageAnaProcessFactory__ static
Definition at line 10 of file SegImageAna.cxx.
__global_SegmentAnaProcessFactory__
SegmentAnaProcessFactory larcv::__global_SegmentAnaProcessFactory__ static
Definition at line 10 of file SegmentAna.cxx.
__global_SegmentFilterProcessFactory__
SegmentFilterProcessFactory larcv::__global_SegmentFilterProcessFactory__ static
Definition at line 10 of file SegmentFilter.cxx.
__global_SegmentMakerProcessFactory__
SegmentMakerProcessFactory larcv::__global_SegmentMakerProcessFactory__ static
Definition at line 9 of file SegmentMaker.cxx.
__global_SegmentMaskProcessFactory__
SegmentMaskProcessFactory larcv::__global_SegmentMaskProcessFactory__ static
Definition at line 11 of file SegmentMask.cxx.
__global_SegmentRelabelProcessFactory__
SegmentRelabelProcessFactory larcv::__global_SegmentRelabelProcessFactory__ static
Definition at line 11 of file SegmentRelabel.cxx.
__global_SegWeightInstanceProcessFactory__
SegWeightInstanceProcessFactory larcv::__global_SegWeightInstanceProcessFactory__ static
Definition at line 10 of file SegWeightInstance.cxx.
__global_SegWeightTrackShowerProcessFactory__
SegWeightTrackShowerProcessFactory larcv::__global_SegWeightTrackShowerProcessFactory__ static
Definition at line 10 of file SegWeightTrackShower.cxx.
__global_SimpleDigitizerProcessFactory__
SimpleDigitizerProcessFactory larcv::__global_SimpleDigitizerProcessFactory__ static
Definition at line 8 of file SimpleDigitizer.cxx.
__global_SimpleFillerProcessFactory__
SimpleFillerProcessFactory larcv::__global_SimpleFillerProcessFactory__ static
Definition at line 12 of file SimpleFiller.cxx.
__global_SimplePixelAnaProcessFactory__
SimplePixelAnaProcessFactory larcv::__global_SimplePixelAnaProcessFactory__ static
Definition at line 8 of file SimplePixelAna.cxx.
__global_SingleROIFakerProcessFactory__
SingleROIFakerProcessFactory larcv::__global_SingleROIFakerProcessFactory__ static
Definition at line 11 of file SingleROIFaker.cxx.
__global_SliceImagesProcessFactory__
SliceImagesProcessFactory larcv::__global_SliceImagesProcessFactory__ static
Definition at line 9 of file SliceImages.cxx.
__global_SSNetEventAnaProcessFactory__
SSNetEventAnaProcessFactory larcv::__global_SSNetEventAnaProcessFactory__ static
Definition at line 13 of file SSNetEventAna.cxx.
__global_SSNetTruthAnaProcessFactory__
SSNetTruthAnaProcessFactory larcv::__global_SSNetTruthAnaProcessFactory__ static
Definition at line 16 of file SSNetTruthAna.cxx.
__global_StepDigitizerProcessFactory__
StepDigitizerProcessFactory larcv::__global_StepDigitizerProcessFactory__ static
Definition at line 9 of file StepDigitizer.cxx.
__global_SuperaBaseProcessFactory__
SuperaBaseProcessFactory larcv::__global_SuperaBaseProcessFactory__ static
Definition at line 8 of file SuperaBase.cxx.
__global_SuperaChStatusProcessFactory__
SuperaChStatusProcessFactory larcv::__global_SuperaChStatusProcessFactory__ static
Definition at line 9 of file SuperaChStatus.cxx.
__global_SuperaHitProcessFactory__
SuperaHitProcessFactory larcv::__global_SuperaHitProcessFactory__ static
Definition at line 11 of file SuperaHit.cxx.
__global_SuperaKeyPointClusterProcessFactory__
SuperaKeyPointClusterProcessFactory larcv::__global_SuperaKeyPointClusterProcessFactory__ static
Definition at line 12 of file SuperaKeyPointCluster.cxx.
__global_SuperaMCPClusterProcessFactory__
SuperaMCPClusterProcessFactory larcv::__global_SuperaMCPClusterProcessFactory__ static
Definition at line 11 of file SuperaMCPCluster.cxx.
__global_SuperaMCROIProcessFactory__
SuperaMCROIProcessFactory larcv::__global_SuperaMCROIProcessFactory__ static
Definition at line 12 of file SuperaMCROI.cxx.
__global_SuperaMetaMakerProcessFactory__
SuperaMetaMakerProcessFactory larcv::__global_SuperaMetaMakerProcessFactory__ static
Definition at line 13 of file SuperaMetaMaker.cxx.
__global_SuperaOpDigitProcessFactory__
SuperaOpDigitProcessFactory larcv::__global_SuperaOpDigitProcessFactory__ static
Definition at line 12 of file SuperaOpDigit.cxx.
__global_SuperaSimChProcessFactory__
SuperaSimChProcessFactory larcv::__global_SuperaSimChProcessFactory__ static
Definition at line 12 of file SuperaSimCh.cxx.
__global_SuperaSimVoxel3DProcessFactory__
SuperaSimVoxel3DProcessFactory larcv::__global_SuperaSimVoxel3DProcessFactory__ static
Definition at line 12 of file SuperaSimVoxel3D.cxx.
__global_SuperaWireProcessFactory__
SuperaWireProcessFactory larcv::__global_SuperaWireProcessFactory__ static
Definition at line 12 of file SuperaWire.cxx.
__global_TrackerEventDisplayProcessFactory__
TrackerEventDisplayProcessFactory larcv::__global_TrackerEventDisplayProcessFactory__ static
Definition at line 51 of file TrackerEventDisplay.cxx.
__global_UnionROIProcessFactory__
UnionROIProcessFactory larcv::__global_UnionROIProcessFactory__ static
Definition at line 8 of file UnionROI.cxx.
__global_VertexAnaProcessFactory__
VertexAnaProcessFactory larcv::__global_VertexAnaProcessFactory__ static
Definition at line 16 of file VertexAna.cxx.
__global_VertexFilterProcessFactory__
VertexFilterProcessFactory larcv::__global_VertexFilterProcessFactory__ static
Definition at line 12 of file VertexFilter.cxx.
__global_VertexImgProcessFactory__
VertexImgProcessFactory larcv::__global_VertexImgProcessFactory__ static
Definition at line 16 of file VertexImg.cxx.
__global_VertexInROIProcessFactory__
VertexInROIProcessFactory larcv::__global_VertexInROIProcessFactory__ static
Definition at line 11 of file VertexInROI.cxx.
__global_VtxInRegionProcessFactory__
VtxInRegionProcessFactory larcv::__global_VtxInRegionProcessFactory__ static
Definition at line 10 of file VtxInRegion.cxx.
__global_WireMaskProcessFactory__
WireMaskProcessFactory larcv::__global_WireMaskProcessFactory__ static
Definition at line 9 of file WireMask.cxx.
kINVALID_DOUBLE
const double larcv::kINVALID_DOUBLE = std::numeric_limits< double >::max()
Used as an invalid value idnetifier for double-point precision.
Definition at line 47 of file LArCVTypes.h.
Referenced by larcv::ExampleAna::Analyze(), larcv::ParticleAna::AnalyzeSignal(), larcv::Voxel3DMeta::Clear(), larcv::ReadNueFile::ClearEvent(), larcv::Run3DTracker::ClearEvent(), larcv::VertexAna::ClearEvent(), larcv::LArbysImageFilter::ClearVertex(), larcv::LEE1e1pAna::ClearVertex(), larcv::VertexAna::ClearVertex(), larcv::PGraphTruthMatch::process(), larcv::ReadNueFile::process(), larcv::VertexAna::process(), larcv::GoodcROIFilter::process(), larcv::ROIAna::process(), ProjectTo3D(), larcv::Voxel3DMeta::Set(), and larcv::LArbysImage::StoreParticles().
kINVALID_FLOAT
const float larcv::kINVALID_FLOAT = std::numeric_limits< float >::max()
Used as an invalid value idnetifier for single-point precision.
Definition at line 45 of file LArCVTypes.h.
Referenced by larcv::ReadNueFile::ClearVertex(), larcv::PGraphTruthMatch::ClearVertex(), larcv::Run3DTracker::ClearVertex(), larcv::ROIPad::configure(), larcv::BadRegionAna::configure(), larcv::VertexInROI::process(), larcv::DeadWireAna::process(), larcv::CosmicPixelAna::process(), and larcv::SSNetEventAna::Reset().
kINVALID_INDEX [1/2]
const unsigned short larcv::kINVALID_INDEX = kINVALID_USHORT static
Definition at line 9 of file old/DataFormatTypes.h.
kINVALID_INDEX [2/2]
const unsigned short larcv::kINVALID_INDEX = kINVALID_USHORT static
Invalid rep for vector index.
Definition at line 10 of file DataFormatTypes.h.
Referenced by larcv::CCQETruthFilter::process(), and larcv::MultiROICropper::process().
kINVALID_INT
const int larcv::kINVALID_INT = std::numeric_limits< int >::max()
Used as an invalid value identifier for int.
Definition at line 37 of file LArCVTypes.h.
Referenced by larcv::ParticleAna::AnalyzeSignal(), larcv::VertexFilter::clear(), larcv::CosmicTrackAna::clear(), larcv::ReadNueFile::ClearEvent(), larcv::Run3DTracker::ClearEvent(), larcv::LEE1e1pAna::ClearEvent(), larcv::VertexAna::ClearEvent(), larcv::LArbysImageFilter::ClearVertex(), larcv::ReadNueFile::ClearVertex(), larcv::PGraphTruthMatch::ClearVertex(), larcv::Run3DTracker::ClearVertex(), larcv::LEE1e1pAna::ClearVertex(), larcv::VertexAna::ClearVertex(), larcv::ReadNueFile::process(), larcv::DeadWireAna::process(), larcv::BadRegionAna::process(), larcv::NuFilter::process(), larcv::ROIAna::process(), larcv::SSNetEventAna::Reset(), and larcv::LArbysRecoHolder::ResetOutput().
kINVALID_LONGLONG
const long long larcv::kINVALID_LONGLONG = std::numeric_limits< long long >::max()
Used as an invalid value identifier for long long.
Definition at line 31 of file LArCVTypes.h.
kINVALID_PLANE [1/2]
const PlaneID_t larcv::kINVALID_PLANE = kINVALID_USHORT static
Definition at line 20 of file old/DataFormatTypes.h.
kINVALID_PLANE [2/2]
const PlaneID_t larcv::kINVALID_PLANE = kINVALID_USHORT static
Invalid plane definition.
Definition at line 23 of file DataFormatTypes.h.
Referenced by as_image2d(), larcv::Pixel2DCluster::bounds(), and cluster_to_image2d().
kINVALID_PRODUCER
const ProducerID_t larcv::kINVALID_PRODUCER =kINVALID_SIZE static
Invalid ProducerID_t.
Definition at line 82 of file DataFormatTypes.h.
Referenced by larcv::SegDatumFillerBase::initialize(), larcv::DatumFillerBase::initialize(), larcv::CosmicSegment::process(), larcv::SegDatumFillerBase::process(), larcv::DatumFillerBase::process(), larcv::hires::HiResImageDivider::process(), and larcv::IOManager< T >::producer_id().
kINVALID_SHORT
const short larcv::kINVALID_SHORT = std::numeric_limits< short >::max()
Used as an invalid value identifier for unsigned short.
Definition at line 41 of file LArCVTypes.h.
kINVALID_SIZE
const size_t larcv::kINVALID_SIZE = std::numeric_limits< size_t >::max()
Used as an invalid value identifier for size_t.
Definition at line 35 of file LArCVTypes.h.
Referenced by larcv::ThreadDatumFiller::_batch_process_(), larcv::LArbysImageResult::Analyze(), larcv::ParticleAna::AnalyzeSignal(), larcv::SegFiller::assert_dimension(), larcv::SimpleFiller::assert_dimension(), larcv::MultiClassFiller::assert_dimension(), larcv::SegDatumFillerBase::batch_begin(), larcv::DatumFillerBase::batch_begin(), larcv::SegFiller::child_configure(), larcv::SimpleFiller::child_configure(), larcv::MultiClassFiller::child_configure(), larcv::EventBase::clear(), larcv::Voxel3DMeta::Clear(), larcv::supera::SuperaCore< raw::OpDetWaveform, recob::Wire, simb::MCTruth, sim::MCTrack, sim::MCShower, sim::SimChannel >::clear_data(), larcv::SegFiller::compute_label_size(), larcv::MultiClassFiller::compute_label_size(), larcv::SegImageAna::configure(), larcv::LArbysRecoHolder::Configure(), supera::MCParticleTree::DefinePrimary(), supera::MCParticleTree::DefineSecondary(), larcv::MultiClassFiller::dim(), supera::MCParticleTree::EstimateSecondary(), larcv::SegFiller::fill_entry_data(), larcv::SimpleFiller::fill_entry_data(), larcv::MultiClassFiller::fill_entry_data(), supera::MCParticleTree::FindPrimary(), larcv::IOManager< T >::get_data(), larcv::LArbysImage::get_rsee(), larcv::CosmicSegment::initialize(), larcv::PyImageMaker::initialize(), larcv::PyImageStitcher::initialize(), larcv::ADCScale::initialize(), larcv::SegDatumFillerBase::initialize(), larcv::DatumFillerBase::initialize(), larcv::IOManager< T >::prepare_input(), larcv::LArbysImageReAna::Process(), larcv::ROIMerger::process(), larcv::CosmicSegment::process(), larcv::SuperaMCPCluster::process(), larcv::ADCScale::process(), larcv::PyImageStitcher::process(), larcv::PyImageMaker::process(), larcv::SegDatumFillerBase::process(), larcv::SuperaMCROI::process(), larcv::DatumFillerBase::process(), larcv::IOManager< T >::producer_id(), larcv::IOManager< T >::read_entry(), larcv::IOManager< T >::register_producer(), larcv::SegFiller::SegFiller(), larcv::Voxel3DMeta::Set(), larcv::ThreadDatumFiller::set_next_batch(), larcv::LArbysRecoHolder::ShapeData(), supera::SimCh2Pixel2DCluster(), larcv::LArbysImage::StoreParticles(), and larcv::EventBase::valid().
kINVALID_UINT
const unsigned int larcv::kINVALID_UINT = std::numeric_limits< unsigned int >::max()
Used as an invalid value identifier for unsigned int.
Definition at line 39 of file LArCVTypes.h.
Referenced by larcv::SuperaMCPCluster::process(), larcv::SuperaSimVoxel3D::process(), and larcv::SuperaSimCh::process().
kINVALID_ULONGLONG
const unsigned long long larcv::kINVALID_ULONGLONG = std::numeric_limits< unsigned long long >::max()
Used as an invalid value identifier for unsigned long long.
Definition at line 33 of file LArCVTypes.h.
kINVALID_USHORT
const unsigned short larcv::kINVALID_USHORT = std::numeric_limits< unsigned short >::max()
Used as an invalid value identifier for unsigned unsigned short.
Definition at line 43 of file LArCVTypes.h.
Referenced by larcv::SimpleFiller::fill_entry_data(), larcv::hires::HiResImageDivider::isInteresting(), larcv::ROISizeFilter::process(), larcv::MCSingleParticleFilter::process(), larcv::MCFilter::process(), and larcv::CCIncFilter::process().
kINVALID_VOXEL3DID
const Voxel3DID_t larcv::kINVALID_VOXEL3DID = kINVALID_ULONGLONG static
Invalid Voxel3DID_t definition.
Definition at line 28 of file DataFormatTypes.h.
Referenced by larcv::Voxel3DMeta::ID(), and supera::SimCh2Voxel3D().