LArCV: supera Namespace Reference
supera Namespace Reference
Package_Name | MeatSlicer
Classes
class GridPoint3D
class ImageMetaFromConfig
User defined class ImageMetaFromConfig ...
class ImageMetaMaker
User defined class ImageMetaMaker ...
class ImageMetaMakerBase
User defined class ImageMetaMakerBase ...
class MCNode
class MCParticleTree
User defined class MCParticleTree ...
class MCROIMaker
class MCRoot
class ParamsChStatus
User defined class ParamsChStatus ...
class ParamsImage2D
User defined class ParamsImage2D ...
class ParamsPixel2D
User defined class ParamsPixel2D ...
class ParamsROI
User defined class ParamsROI ...
class ParamsVoxel3D
User defined class ParamsVoxel3D ...
class PulledPork3DSlicer
User defined class PulledPork3DSlicer ...
class WireRange3D
User defined class WireRange3D ...
Typedefs
typedef ::larcv::PSet Config_t
typedef ::larlite::wire LArWire_t
typedef ::larlite::opdetwaveform LArOpDigit_t
typedef ::larlite::hit LArHit_t
typedef ::larlite::mctruth LArMCTruth_t
typedef ::larlite::mctrack LArMCTrack_t
typedef ::larlite::mcshower LArMCShower_t
typedef ::larlite::simch LArSimCh_t
typedef ::larlite::mcstep LArMCStep_t
typedef ::larcv::Range< unsigned int > WTRange_t
typedef std::vector< supera::WTRange_t > WTRangeArray_t
Enumerations
enum LArDataType_t : unsigned int {
LArDataType_t::kLArWire_t, LArDataType_t::kLArHit_t, LArDataType_t::kLArOpDigit_t, LArDataType_t::kLArMCTruth_t,
LArDataType_t::kLArMCTrack_t, LArDataType_t::kLArMCShower_t, LArDataType_t::kLArSimCh_t, LArDataType_t::kLArDataTypeMax
}
enum to define LAr* data type
Functions
::larlite::geo::WireID ChannelToWireID (unsigned int ch)
Channel number to wire ID.
double DriftVelocity ()
DriftVelocity in cm/us.
unsigned int NumberTimeSamples ()
Number of time ticks.
double DetHalfWidth ()
Detector width.
double DetHalfHeight ()
Detector height.
double DetLength ()
Detector length.
unsigned int Nchannels ()
Number of channels.
unsigned int Nplanes ()
Number of planes.
unsigned int Nwires (unsigned int plane)
Number of wires.
unsigned int NearestWire (const TVector3 &xyz, unsigned int plane)
Nearest wire.
unsigned int NearestWire (const double *xyz, unsigned int plane)
Nearest wire.
double PlaneTickOffset (size_t plane0, size_t plane1)
Tick offset for drift electrons across planes.
double WirePitch (size_t plane)
Wire pitch.
double WireAngleToVertical (unsigned int plane)
Angle from z-axis.
int TPCG4Time2Tick (double ns)
G4 time to TPC tick (plane 0)
int TPCG4Time2TDC (double ns)
G4 time to TPC tick (plane 0)
double TPCTDC2Tick (double tdc)
TDC to TPC tick.
double TriggerOffsetTPC ()
Trigger tick.
double TPCTickPeriod ()
TPC sampling period.
void ApplySCE (double &x, double &y, double &z)
Truth position to shifted.
void ApplySCE (double *xyz)
Truth position to shifted.
void ApplySCE (TVector3 &xyz)
Truth position to shifted.
ImageMetaMakerBase * CreateImageMetaMaker (const supera::Config_t &cfg)
larcv::Image2D Hit2Image2D (const larcv::ImageMeta &meta, const std::vector< supera::LArHit_t > &hits, const int time_offset)
std::vector< larcv::Image2D > Hit2Image2D (const std::vector< larcv::ImageMeta > &meta_v, const std::vector< supera::LArHit_t > &hits, const int time_offset)
larcv::Image2D Wire2Image2D (const larcv::ImageMeta &meta, const std::vector< supera::LArWire_t > &wires, const int time_offset)
std::vector< larcv::Image2D > Wire2Image2D (const std::vector< larcv::ImageMeta > &meta_v, const std::vector< supera::LArWire_t > &wires, const int time_offset)
larcv::Image2D OpDigit2Image2D (const larcv::ImageMeta &meta, const std::vector< supera::LArOpDigit_t > &opdigit_v, int time_offset)
std::vector< larcv::Image2D > SimCh2Image2D (const std::vector< larcv::ImageMeta > &meta_v, const std::vector< larcv::ROIType_t > &track2type_v, const std::vector< supera::LArSimCh_t > &sch_v, const int time_offset)
larcv::Voxel3DSet SimCh2Voxel3D (const larcv::Voxel3DMeta &meta, const std::vector< int > &track_v, const std::vector< supera::LArSimCh_t > &sch_v, const int time_offset, const size_t plane)
std::vector< std::vector< larcv::Pixel2DCluster > > SimCh2Pixel2DCluster (const std::vector< larcv::ImageMeta > &meta_v, const std::vector< size_t > &row_compression_v, const std::vector< size_t > &col_compression_v, const std::vector< supera::LArSimCh_t > &sch_v, const std::vector< size_t > &trackid2cluster, const int time_offset)
template<>
LArDataType_t LArDataType< supera::LArHit_t > ()
template<>
LArDataType_t LArDataType< supera::LArWire_t > ()
template<>
LArDataType_t LArDataType< supera::LArOpDigit_t > ()
template<>
LArDataType_t LArDataType< supera::LArMCTruth_t > ()
template<>
LArDataType_t LArDataType< supera::LArMCTrack_t > ()
template<>
LArDataType_t LArDataType< supera::LArMCShower_t > ()
template<>
LArDataType_t LArDataType< supera::LArSimCh_t > ()
template<class T >
LArDataType_t LArDataType ()
Typedef Documentation
Config_t
typedef ::larcv::PSet supera::Config_t
Definition at line 22 of file MeatSlicer/FMWKInterface.h.
LArHit_t
typedef ::larlite::hit supera::LArHit_t
Definition at line 26 of file MeatSlicer/FMWKInterface.h.
LArMCShower_t
typedef ::larlite::mcshower supera::LArMCShower_t
Definition at line 29 of file MeatSlicer/FMWKInterface.h.
LArMCStep_t
typedef ::larlite::mcstep supera::LArMCStep_t
Definition at line 31 of file MeatSlicer/FMWKInterface.h.
LArMCTrack_t
typedef ::larlite::mctrack supera::LArMCTrack_t
Definition at line 28 of file MeatSlicer/FMWKInterface.h.
LArMCTruth_t
typedef ::larlite::mctruth supera::LArMCTruth_t
Definition at line 27 of file MeatSlicer/FMWKInterface.h.
LArOpDigit_t
typedef ::larlite::opdetwaveform supera::LArOpDigit_t
Definition at line 25 of file MeatSlicer/FMWKInterface.h.
LArSimCh_t
typedef ::larlite::simch supera::LArSimCh_t
Definition at line 30 of file MeatSlicer/FMWKInterface.h.
LArWire_t
typedef ::larlite::wire supera::LArWire_t
Definition at line 24 of file MeatSlicer/FMWKInterface.h.
WTRange_t
typedef ::larcv::Range<unsigned int> supera::WTRange_t
Definition at line 22 of file MCROIMaker.h.
WTRangeArray_t
typedef std::vector<supera::WTRange_t> supera::WTRangeArray_t
Definition at line 23 of file MCROIMaker.h.
Enumeration Type Documentation
LArDataType_t
enum supera::LArDataType_t : unsigned int strong
enum to define LAr* data type
Enumerator
kLArWire_t
recob::Wire
kLArHit_t
recob::Hit
kLArOpDigit_t
raw::OpDetWaveform
kLArMCTruth_t
simb::MCTruth
kLArMCTrack_t
sim::MCTrack
kLArMCShower_t
sim::MCShower
kLArSimCh_t
sim::SimChannel
kLArDataTypeMax
Definition at line 9 of file MeatSlicer/SuperaTypes.h.
                            : unsigned int{
     kLArWire_t,
     kLArHit_t,
     kLArOpDigit_t,
     kLArMCTruth_t,
     kLArMCTrack_t,
     kLArMCShower_t,
     kLArSimCh_t,
     kLArDataTypeMax
   };
Function Documentation
ApplySCE() [1/3]
void supera::ApplySCE (double & x, double & y, double & z)
Truth position to shifted.
Definition at line 111 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::AddConstraint(), larcv::SuperaKeyPointCluster::GetPoint(), supera::MCROIMaker::ParticleROI(), and supera::MCROIMaker::WireTimeBoundary().
   {
     static larutil::SpaceChargeMicroBooNE sce;
     auto pos = sce.GetPosOffsets(x,y,z);
     x = x - pos[0] + 0.7;
     y = y + pos[1];
     z = z + pos[2];
   }
ApplySCE() [2/3]
void supera::ApplySCE (double * xyz)
Truth position to shifted.
Definition at line 120 of file MeatSlicer/FMWKInterface.cxx.
   {
     static larutil::SpaceChargeMicroBooNE sce;
     auto pos = sce.GetPosOffsets(xyz[0],xyz[1],xyz[2]);
     xyz[0] = xyz[0] - pos[0] + 0.7;
     xyz[1] = xyz[1] + pos[1];
     xyz[2] = xyz[2] + pos[2];
   }
ApplySCE() [3/3]
void supera::ApplySCE (TVector3 & xyz)
Truth position to shifted.
Definition at line 129 of file MeatSlicer/FMWKInterface.cxx.
   {
     static larutil::SpaceChargeMicroBooNE sce;
     auto pos = sce.GetPosOffsets(xyz[0],xyz[1],xyz[2]);
     xyz[0] = xyz[0] - pos[0] + 0.7;
     xyz[1] = xyz[1] + pos[1];
     xyz[2] = xyz[2] + pos[2];
   }
ChannelToWireID()
larlite::geo::WireID supera::ChannelToWireID (unsigned int ch)
Channel number to wire ID.
Definition at line 13 of file MeatSlicer/FMWKInterface.cxx.
Referenced by Hit2Image2D(), SimCh2Image2D(), SimCh2Pixel2DCluster(), SimCh2Voxel3D(), Wire2Image2D(), and supera::MCROIMaker::WireTimeBoundary().
   { return ::larutil::Geometry::GetME()->ChannelToWireID(ch); }
CreateImageMetaMaker()
ImageMetaMakerBase * supera::CreateImageMetaMaker (const supera::Config_t & cfg)
Definition at line 11 of file ImageMetaMakerFactory.cxx.
References larcv::PSet::get(), and LARCV_SINFO.
Referenced by larcv::SuperaMetaMaker::configure(), and supera::ImageMetaMaker::configure().
   {
     ImageMetaMakerBase* maker = nullptr;
     try{
       LARCV_SINFO() << "Attempting to construct supera::ImageMetaFromConfig... " << std::endl;
       auto const& meta_cfg = cfg.get<supera::Config_t>("MetaConfig");
       maker = new ImageMetaFromConfig();
       maker->configure(meta_cfg);
       LARCV_SINFO() << "Successfully made supera::ImageMetaFromConfig! " << std::endl;
     }catch(...){
       if(maker) delete maker;
     }
     if(!maker) {
       try{
     LARCV_SINFO() << "Attempting to construct supera::PuledPork3DSlicer..." << std::endl;
     auto const& meta_cfg = cfg.get<supera::Config_t>("PulledPork");
     maker = new PulledPork3DSlicer();
     maker->configure(meta_cfg);
     LARCV_SINFO() << "Successfully made supera::PulledPork3DSlicer! " << std::endl;
       }catch(...){
     if(maker) delete maker;
       }
     }
     LARCV_SINFO() << "Returning supera::ImageMetaMakerBase: " << maker << std::endl;
     return maker;
   }
DetHalfHeight()
double supera::DetHalfHeight ()
Detector height.
Definition at line 30 of file MeatSlicer/FMWKInterface.cxx.
Referenced by larcv::SuperaSimVoxel3D::process().
   { return ::larutil::Geometry::GetME()->DetHalfHeight(); }
DetHalfWidth()
double supera::DetHalfWidth ()
Detector width.
Definition at line 27 of file MeatSlicer/FMWKInterface.cxx.
   { return ::larutil::Geometry::GetME()->DetHalfWidth(); }
DetLength()
double supera::DetLength ()
Detector length.
Definition at line 33 of file MeatSlicer/FMWKInterface.cxx.
   { return ::larutil::Geometry::GetME()->DetLength(); }
DriftVelocity()
double supera::DriftVelocity ()
DriftVelocity in cm/us.
Definition at line 16 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::AddConstraint(), supera::PulledPork3DSlicer::configure(), supera::PulledPork3DSlicer::GenerateMeta(), larcv::SuperaKeyPointCluster::GetPoint(), PlaneTickOffset(), SimCh2Voxel3D(), and supera::MCROIMaker::WireTimeBoundary().
   { return ::larutil::LArProperties::GetME()->DriftVelocity(); }
Hit2Image2D() [1/2]
larcv::Image2D supera::Hit2Image2D (const larcv::ImageMeta & meta, const std::vector< supera::LArHit_t > & hits, const int time_offset)
Definition at line 9 of file LAr2Image.cxx.
References ChannelToWireID(), larcv::ImageMeta::col(), larcv::ImageMeta::dump(), LARCV_SINFO, larcv::ImageMeta::max_y(), larcv::ImageMeta::min_y(), larcv::ImageMeta::plane(), and larcv::Image2D::set_pixel().
Referenced by Hit2Image2D(), and larcv::SuperaHit::process().
   {
     //int nticks = meta.rows();
     //int nwires = meta.cols();
     //size_t row_comp_factor = (size_t)(meta.pixel_height());
     const int ymax = meta.max_y() - 1; // Need in terms of row coordinate
     const int ymin = (meta.min_y() >= 0 ? meta.min_y() : 0);
     larcv::Image2D img(meta);
     LARCV_SINFO() << "Filling an image: " << meta.dump();
     LARCV_SINFO() << "(ymin,ymax) = (" << ymin << "," << ymax << ")" << std::endl;
     for(auto const& h : hits) {
       auto const& wire_id = ::supera::ChannelToWireID(h.Channel());
       if ((int)(wire_id.Plane) != meta.plane()) continue;
       size_t col = 0;
       try { col = meta.col(wire_id.Wire); }
       catch (const larcv::larbys&) { continue; }
       int row = int(h.PeakTime()+0.5) + time_offset;
       if(row > ymax || row < ymin) continue;
       img.set_pixel(ymax-row,col,h.Integral());
     }
     return img;
   }
Hit2Image2D() [2/2]
std::vector< larcv::Image2D > supera::Hit2Image2D (const std::vector< larcv::ImageMeta > & meta_v, const std::vector< supera::LArHit_t > & hits, const int time_offset)
Definition at line 38 of file LAr2Image.cxx.
References Hit2Image2D(), and Nplanes().
   {
     std::vector<larcv::Image2D> res_v;
     for (size_t p = 0; p < ::supera::Nplanes(); ++p) {
       auto const& meta = meta_v.at(p);
       res_v.emplace_back(std::move(Hit2Image2D(meta,hits,time_offset)));
       res_v.back().index(res_v.size()-1);
     }
     return res_v;
   }
LArDataType()
template<class T > LArDataType_t supera::LArDataType ()
LArDataType< supera::LArHit_t >()
template<> LArDataType_t supera::LArDataType< supera::LArHit_t > ()
Definition at line 6 of file SuperaTypes.cxx.
References kLArHit_t.
 { return LArDataType_t::kLArHit_t;      }
LArDataType< supera::LArMCShower_t >()
template<> LArDataType_t supera::LArDataType< supera::LArMCShower_t > ()
Definition at line 11 of file SuperaTypes.cxx.
References kLArMCShower_t.
 { return LArDataType_t::kLArMCShower_t; }
LArDataType< supera::LArMCTrack_t >()
template<> LArDataType_t supera::LArDataType< supera::LArMCTrack_t > ()
Definition at line 10 of file SuperaTypes.cxx.
References kLArMCTrack_t.
 { return LArDataType_t::kLArMCTrack_t;  }
LArDataType< supera::LArMCTruth_t >()
template<> LArDataType_t supera::LArDataType< supera::LArMCTruth_t > ()
Definition at line 9 of file SuperaTypes.cxx.
References kLArMCTruth_t.
 { return LArDataType_t::kLArMCTruth_t;  }
LArDataType< supera::LArOpDigit_t >()
template<> LArDataType_t supera::LArDataType< supera::LArOpDigit_t > ()
Definition at line 8 of file SuperaTypes.cxx.
References kLArOpDigit_t.
 { return LArDataType_t::kLArOpDigit_t;  }
LArDataType< supera::LArSimCh_t >()
template<> LArDataType_t supera::LArDataType< supera::LArSimCh_t > ()
Definition at line 12 of file SuperaTypes.cxx.
References kLArSimCh_t.
 { return LArDataType_t::kLArSimCh_t;    }
LArDataType< supera::LArWire_t >()
template<> LArDataType_t supera::LArDataType< supera::LArWire_t > ()
Definition at line 7 of file SuperaTypes.cxx.
References kLArWire_t.
 { return LArDataType_t::kLArWire_t;     }
Nchannels()
unsigned int supera::Nchannels ()
Number of channels.
Definition at line 36 of file MeatSlicer/FMWKInterface.cxx.
Referenced by Supera::filter().
   { return ::larutil::Geometry::GetME()->Nchannels(); }
NearestWire() [1/2]
unsigned int supera::NearestWire (const TVector3 & xyz, unsigned int plane)
Nearest wire.
Definition at line 45 of file MeatSlicer/FMWKInterface.cxx.
References Nwires().
Referenced by supera::PulledPork3DSlicer::DeriveMeta(), and supera::MCROIMaker::WireTimeBoundary().
   {
     /*
       unsigned int res;
       try{
       res = ::larutil::Geometry::GetME()->NearestWire(xyz,plane);
       }catch( ::larutil::InvalidWireError& err){
       res = err.better_wire_number;
       }
     */
     double min_wire=0;
     double max_wire=Nwires(plane)-1;
     double wire = ::larutil::Geometry::GetME()->WireCoordinate(xyz,plane) + 0.5;
     if(wire<min_wire) wire = min_wire;
     if(wire>max_wire) wire = max_wire;
     return (unsigned int)wire;
   }
NearestWire() [2/2]
unsigned int supera::NearestWire (const double * xyz, unsigned int plane)
Nearest wire.
Definition at line 64 of file MeatSlicer/FMWKInterface.cxx.
References Nwires().
   {
     /*
       unsigned int res;
       try{
       res = ::larutil::Geometry::GetME()->NearestWire(xyz,plane);
       }catch( ::larutil::InvalidWireError& err){
       res = err.better_wire_number;
       }
     */
     double min_wire=0;
     double max_wire=Nwires(plane)-1;
     double wire = ::larutil::Geometry::GetME()->WireCoordinate(xyz,plane) + 0.5;
     if(wire<min_wire) wire = min_wire;
     if(wire>max_wire) wire = max_wire;
     return (unsigned int)wire;
   }
Nplanes()
unsigned int supera::Nplanes ()
Number of planes.
Definition at line 39 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::ImageMetaFromConfig::configure(), supera::ImageMetaMakerBase::configure(), supera::PulledPork3DSlicer::configure(), supera::PulledPork3DSlicer::DeriveMeta(), larcv::AStarTracker::GetTotalDepositedCharge(), Hit2Image2D(), larcv::SuperaChStatus::initialize(), SimCh2Pixel2DCluster(), supera::PulledPork3DSlicer::Test(), Wire2Image2D(), and supera::MCROIMaker::WireTimeBoundary().
   { return ::larutil::Geometry::GetME()->Nplanes(); }
NumberTimeSamples()
unsigned int supera::NumberTimeSamples ()
Number of time ticks.
Definition at line 19 of file MeatSlicer/FMWKInterface.cxx.
   {
     // Till resolved, do not use this function
     throw ::larcv::larbys("NumberTimeSamples function not available!");
     //return ::larutil::DetectorProperties::GetME()->NumberTimeSamples();
     //return 9600;
   }
Nwires()
unsigned int supera::Nwires (unsigned int plane)
Number of wires.
Definition at line 42 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::DeriveMeta(), and NearestWire().
   { return ::larutil::Geometry::GetME()->Nwires(plane); }
OpDigit2Image2D()
larcv::Image2D supera::OpDigit2Image2D (const larcv::ImageMeta & meta, const std::vector< supera::LArOpDigit_t > & opdigit_v, int time_offset)
Definition at line 160 of file LAr2Image.cxx.
References larcv::Image2D::copy(), larcv::ImageMeta::max_x(), larcv::ImageMeta::min_x(), larcv::Image2D::paint(), and larcv::ImageMeta::rows().
Referenced by larcv::SuperaOpDigit::process().
   {
     larcv::Image2D img(meta);
     img.paint(2048);
     std::vector<float> tmp_wf(meta.rows(), 2048);
     for (auto const& opdigit : opdigit_v) {
       if (opdigit.size() < 1000) continue;
       auto const col = opdigit.ChannelNumber();
       if (meta.min_x() > col) continue;
       if (col >= meta.max_x()) continue;
       //
       // HACK: right way is to use TimeService + trigger.
       //       for now I just record PMT beamgate tick=0 as edge of an image (w/ offset)
       //
       size_t nskip = 0;
       if (time_offset < 0) nskip = (-1 * time_offset);
       if (nskip >= opdigit.size()) continue;
       for (auto& v : tmp_wf) v = 2048;
       size_t num_pixel = std::min(meta.rows(), opdigit.size() - nskip);
       for (size_t i = 0; i < num_pixel; ++i) tmp_wf[i] = (float)(opdigit[nskip + i]);
       img.copy(0, col, &(tmp_wf[0]), num_pixel);
       //img.reverse_copy(0,col,opdigit,nskip,num_pixel);
     }
     return img;
   }
PlaneTickOffset()
double supera::PlaneTickOffset (size_t plane0, size_t plane1)
Tick offset for drift electrons across planes.
Definition at line 83 of file MeatSlicer/FMWKInterface.cxx.
References DriftVelocity().
Referenced by larcv::SuperaKeyPointCluster::CreateCluster(), and supera::MCROIMaker::WireTimeBoundary().
   {
     static double pitch = ::larutil::Geometry::GetME()->PlanePitch();
     static double tick_period = ::larutil::TimeService::GetME()->TPCClock().TickPeriod();
     return (plane1 - plane0) * pitch / DriftVelocity() / tick_period;
   }
SimCh2Image2D()
std::vector< larcv::Image2D > supera::SimCh2Image2D (const std::vector< larcv::ImageMeta > & meta_v, const std::vector< larcv::ROIType_t > & track2type_v, const std::vector< supera::LArSimCh_t > & sch_v, const int time_offset)
Definition at line 190 of file LAr2Image.cxx.
References ChannelToWireID(), larcv::kROIUnknown, LARCV_SINFO, and TPCTDC2Tick().
Referenced by larcv::SuperaSimCh::process().
   {
     LARCV_SINFO() << "Filling semantic-segmentation ground truth image..." << std::endl;
     std::vector<larcv::Image2D> img_v;
     for (auto const& meta : meta_v) {
       LARCV_SINFO() << meta.dump();
       img_v.emplace_back(larcv::Image2D(meta));
     }
     static std::vector<float> column;
     for (auto const& img : img_v) {
       if (img.meta().rows() >= column.size())
     column.resize(img.meta().rows() + 1, (float)(::larcv::kROIUnknown));
     }
     for (auto const& sch : sch_v) {
       auto ch = sch.Channel();
       auto const& wid = ::supera::ChannelToWireID(ch);
       auto const& plane = wid.Plane;
       auto& img = img_v.at(plane);
       auto const& meta = img.meta();
       size_t col = wid.Wire;
       if (col < meta.min_x()) continue;
       if (meta.max_x() <= col) continue;
       if (plane != img.meta().plane()) continue;
       col -= (size_t)(meta.min_x());
       // Initialize column vector
       for (auto& v : column) v = (float)(::larcv::kROIUnknown);
       //for (auto& v : column) v = (float)(-1);
       for (auto const tick_ides : sch.TDCIDEMap()) {
     int tick = supera::TPCTDC2Tick((double)(tick_ides.first)) + time_offset;
     if (tick < meta.min_y()) continue;
     if (tick >= meta.max_y()) continue;
     // Where is this tick in column vector?
     size_t index = (size_t)(meta.max_y() - tick);
     // Pick type
     double energy = 0;
     ::larcv::ROIType_t roi_type =::larcv::kROIUnknown;
     for (auto const& edep : tick_ides.second) {
       if (edep.energy < energy) continue;
       if (std::abs(edep.trackID) >= (int)(track2type_v.size())) continue;
       auto temp_roi_type = track2type_v[std::abs(edep.trackID)];
       if (temp_roi_type ==::larcv::kROIUnknown) continue;
       energy = edep.energy;
       roi_type = (::larcv::ROIType_t)temp_roi_type;
     }
     column[index] = roi_type;
       }
       // mem-copy column vector
       img.copy(0, col, column, img.meta().rows());
     }
     return img_v;
   }
SimCh2Pixel2DCluster()
std::vector< std::vector< larcv::Pixel2DCluster > > supera::SimCh2Pixel2DCluster (const std::vector< larcv::ImageMeta > & meta_v, const std::vector< size_t > & row_compression_v, const std::vector< size_t > & col_compression_v, const std::vector< supera::LArSimCh_t > & sch_v, const std::vector< size_t > & trackid2cluster, const int time_offset)
Definition at line 303 of file LAr2Image.cxx.
References ChannelToWireID(), larcv::kINVALID_SIZE, LARCV_SCRITICAL, Nplanes(), larcv::Pixel2D::Set(), and TPCTDC2Tick().
Referenced by larcv::SuperaMCPCluster::process().
   {
     std::vector<std::vector<larcv::Pixel2DCluster> > res_vv;
     static std::vector<float> column;
     for (auto const& meta : meta_v) {
       if (meta.rows() >= column.size())
     column.resize(meta.rows() + 1, 0);
     }
     // figure out # of clusters
     if(meta_v.size() != supera::Nplanes()) {
       LARCV_SCRITICAL() << "# Meta mismatch with # planes!" << std::endl;
       throw larcv::larbys();
     }
     // figure out # of clusters to be made
     size_t num_clusters=0;
     for(auto const& cidx : trackid2cluster) {
       if(cidx == larcv::kINVALID_SIZE) continue;
       if(cidx >= num_clusters) num_clusters = cidx + 1;
     }
     // loop over cluster index, construct cluster
     std::vector<larcv::Image2D> img_v;
     for(size_t plane=0; plane<supera::Nplanes(); ++plane)
       img_v.emplace_back(meta_v[plane]);
     std::vector<size_t> nonzero_npx_v(supera::Nplanes(),0);
     for(size_t cidx=0; cidx<num_clusters; ++cidx) {
       // initialize image container
       for(size_t plane=0; plane<supera::Nplanes(); ++plane) {
     img_v[plane].paint(0.);
     nonzero_npx_v[plane] = 0;
       }
       for (auto const& sch : sch_v) {
     auto ch = sch.Channel();
     auto const& wid   = ::supera::ChannelToWireID(ch);
     auto const& plane = wid.Plane;
     auto& img = img_v[plane];
     auto const& meta  = img.meta();
     auto& nonzero_npx = nonzero_npx_v[plane];
     size_t col = wid.Wire;
     if (col < meta.min_x()) continue;
     if (meta.max_x() <= col) continue;
     if (plane != img.meta().plane()) continue;
     col -= (size_t)(meta.min_x());
     // Initialize column vector
     for (auto& v : column) v = 0.;
     //for (auto& v : column) v = (float)(-1);
     for (auto const tick_ides : sch.TDCIDEMap()) {
       int tick = supera::TPCTDC2Tick((double)(tick_ides.first)) + time_offset;
       if (tick < meta.min_y()) continue;
       if (tick >= meta.max_y()) continue;
       // Where is this tick in column vector?
       size_t index = (size_t)(meta.max_y() - tick);
       // Accummulate energy for relevant cluster
       int trackid = 0;
       double energy = 0;
       for (auto const& edep : tick_ides.second) {
         trackid = std::abs(edep.trackID);
         if (trackid >= (int)(trackid2cluster.size())) continue;
         if (trackid2cluster[trackid] != cidx) continue;
         energy += edep.energy;
       }
       if(energy>0) {
         column[index] = energy;
         ++nonzero_npx;
       }
     }
     // mem-copy column vector
     img.copy(0, col, column, img.meta().rows());
       }
       // Now convert them into Pixel2DCluster
       std::vector<larcv::Pixel2DCluster> res_v;
       res_v.reserve(supera::Nplanes());
       larcv::Pixel2D px;
       for(size_t plane=0; plane<supera::Nplanes(); ++plane) {
     larcv::Pixel2DCluster res;
     res.reserve(nonzero_npx_v[plane]);
     auto const& full_img  = img_v[plane];
     auto const& full_meta = full_img.meta();
     auto data = full_img.copy_compress(full_meta.rows() / row_compression_v.at(plane),
                        full_meta.cols() / col_compression_v.at(plane),
                        larcv::Image2D::CompressionModes_t::kSum);
     size_t nrows = full_meta.rows() / row_compression_v[plane];
     for(size_t px_idx=0; px_idx<data.size(); ++px_idx) {
       if(data[px_idx] <= 0) continue;
       px.Set( px_idx / nrows,
           px_idx % nrows,
           data[px_idx] );
       res += px;
     }
     res_v.emplace_back(std::move(res));
       }
       res_vv.emplace_back(std::move(res_v));
     }
     return res_vv;
   }
SimCh2Voxel3D()
larcv::Voxel3DSet supera::SimCh2Voxel3D (const larcv::Voxel3DMeta & meta, const std::vector< int > & track_v, const std::vector< supera::LArSimCh_t > & sch_v, const int time_offset, const size_t plane)
Definition at line 252 of file LAr2Image.cxx.
References ChannelToWireID(), DriftVelocity(), larcv::Voxel3DSet::Emplace(), larcv::Voxel3DMeta::ID(), larcv::kINVALID_VOXEL3DID, LARCV_SINFO, TPCTDC2Tick(), and TPCTickPeriod().
Referenced by larcv::SuperaSimVoxel3D::process().
   {
     LARCV_SINFO() << "Filling Voxel3D ground truth volume..." << std::endl;
     larcv::Voxel3DSet res(meta);
     //double x, y, z, x_tick;
     double y, z, x_tick;
     //std::cout << "x_offset " << x_offset << std::endl;
     for (auto const& sch : sch_v) {
       auto ch = sch.Channel();
       auto const& wid = ::supera::ChannelToWireID(ch);
       if( plane != (size_t)(wid.Plane) ) continue;
       for (auto const tick_ides : sch.TDCIDEMap()) {
     x_tick = (supera::TPCTDC2Tick(tick_ides.first) + time_offset) * supera::TPCTickPeriod()  * supera::DriftVelocity();
     /*
     std::cout << tick_ides.first << " : " << supera::TPCTDC2Tick(tick_ides.first) << " : " << time_offset << " : " << x_tick << std::flush;
     std::cout << (supera::TPCTDC2Tick(tick_ides.first) + time_offset) << std::endl
           << (supera::TPCTDC2Tick(tick_ides.first) + time_offset) * supera::TPCTickPeriod() << std::endl
           << (supera::TPCTDC2Tick(tick_ides.first) + time_offset) * supera::TPCTickPeriod() * supera::DriftVelocity() << std::endl
           << std::endl;
     */
     for (auto const& edep : tick_ides.second) {
       if (std::abs(edep.trackID) >= (int)(track_v.size())) continue;
       if (track_v[std::abs(edep.trackID)]<=0) continue;
       //x = edep.x;
       y = edep.y;
       z = edep.z;
       //supera::ApplySCE(x,y,z);
       //std::cout << " ... " << x << std::endl;
       // Now use tick-based position for x
       auto vid = meta.ID(x_tick,y,z);
       if(vid == larcv::kINVALID_VOXEL3DID) continue;
       larcv::Voxel3D vx(vid,edep.energy);
       res.Emplace(std::move(vx));
     }
       }
     }
     return res;
   }
TPCG4Time2TDC()
int supera::TPCG4Time2TDC (double ns)
G4 time to TPC tick (plane 0)
Definition at line 99 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::GenerateMeta().
   { return ::larutil::TimeService::GetME()->TPCG4Time2TDC(ns); }
TPCG4Time2Tick()
int supera::TPCG4Time2Tick (double ns)
G4 time to TPC tick (plane 0)
Definition at line 96 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::MCROIMaker::WireTimeBoundary().
   { return ::larutil::TimeService::GetME()->TPCG4Time2Tick(ns); }
TPCTDC2Tick()
double supera::TPCTDC2Tick (double tdc)
TDC to TPC tick.
Definition at line 102 of file MeatSlicer/FMWKInterface.cxx.
Referenced by SimCh2Image2D(), SimCh2Pixel2DCluster(), SimCh2Voxel3D(), and supera::MCROIMaker::WireTimeBoundary().
   { return ::larutil::TimeService::GetME()->TPCTDC2Tick(tdc); }
TPCTickPeriod()
double supera::TPCTickPeriod ()
TPC sampling period.
Definition at line 108 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::configure(), supera::PulledPork3DSlicer::DeriveMeta(), supera::PulledPork3DSlicer::GenerateMeta(), larcv::SuperaSimVoxel3D::process(), and SimCh2Voxel3D().
   { return ::larutil::TimeService::GetME()->TPCClock().TickPeriod(); }
TriggerOffsetTPC()
double supera::TriggerOffsetTPC ()
Trigger tick.
Definition at line 105 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::DeriveMeta(), and larcv::SuperaSimVoxel3D::process().
   { return ::larutil::TimeService::GetME()->TriggerOffsetTPC(); }
Wire2Image2D() [1/2]
larcv::Image2D supera::Wire2Image2D (const larcv::ImageMeta & meta, const std::vector< supera::LArWire_t > & wires, const int time_offset)
Definition at line 51 of file LAr2Image.cxx.
References ChannelToWireID(), larcv::ImageMeta::col(), larcv::ImageMeta::dump(), LARCV_SCRITICAL, LARCV_SDEBUG, LARCV_SINFO, larcv::ImageMeta::max_y(), larcv::ImageMeta::min_y(), larcv::Image2D::paint(), larcv::ImageMeta::pixel_height(), larcv::ImageMeta::plane(), larcv::Image2D::reverse_copy(), larcv::ImageMeta::row(), and larcv::Image2D::set_pixel().
Referenced by larcv::SuperaWire::process(), and Wire2Image2D().
   {
     //int nticks = meta.rows();
     //int nwires = meta.cols();
     size_t row_comp_factor = (size_t)(meta.pixel_height());
     const int ymax = meta.max_y() - 1; // Need in terms of row coordinate
     const int ymin = (meta.min_y() >= 0 ? meta.min_y() : 0);
     larcv::Image2D img(meta);
     img.paint(0.);
     LARCV_SINFO() << "Filling an image: " << meta.dump();
     LARCV_SINFO() << "(ymin,ymax) = (" << ymin << "," << ymax << ")" << std::endl;
     for (auto const& wire : wires) {
       auto const& wire_id = ::supera::ChannelToWireID(wire.Channel());
       if ((int)(wire_id.Plane) != meta.plane()) continue;
       size_t col = 0;
       try {
     col = meta.col(wire_id.Wire);
       } catch (const ::larcv::larbys&) {
     continue;
       }
       for (auto const& range : wire.SignalROI().get_ranges()) {
     auto const& adcs = range.data();
     //double sumq = 0;
     //for(auto const& v : adcs) sumq += v;
     //sumq /= (double)(adcs.size());
     //if(sumq<3) continue;
     int start_index = range.begin_index() + time_offset;
     int end_index   = start_index + adcs.size() - 1;
     if (start_index > ymax || end_index < ymin) continue;
     if (row_comp_factor > 1) {
       for (size_t index = 0; index < adcs.size(); ++index) {
         if ((int)index + start_index < ymin) continue;
         if ((int)index + start_index > ymax) break;
         auto row = meta.row((double)(start_index + index));
         img.set_pixel(row, col, adcs[index]);
       }
     } else {
       // Fill matrix from start_index => end_index of matrix row
       // By default use index 0=>length-1 index of source vector
       int nskip = 0;
       int nsample = adcs.size();
       if (end_index   > ymax) {
         LARCV_SDEBUG() << "End index (" << end_index << ") exceeding image bound (" << ymax << ")" << std::endl;
         nsample   = adcs.size() - (end_index - ymax);
         end_index = ymax;
         LARCV_SDEBUG() << "Corrected End index = " << end_index << std::endl;
       }
       if (start_index < ymin) {
         LARCV_SDEBUG() << "Start index (" << start_index << ") exceeding image bound (" << ymin << ")" << std::endl;
         nskip = ymin - start_index;
         nsample -= nskip;
         start_index = ymin;
         LARCV_SDEBUG() << "Corrected Start index = " << start_index << std::endl;
       }
       LARCV_SDEBUG() << "Calling a reverse_copy..." << std::endl
              << "      source wf : start index = " << range.begin_index() << " length = " << adcs.size() << std::endl
              << "      (row,col) : (" << (ymax - end_index) << "," << col << ")" << std::endl
              << "      nskip     : "  << nskip << std::endl
              << "      nsample   : "  << nsample << std::endl;
       try {
         img.reverse_copy(ymax - end_index,
                  col,
                  adcs,
                  nskip,
                  nsample);
       } catch (const ::larcv::larbys& err) {
         LARCV_SCRITICAL() << "Attempted to fill an image..." << std::endl
                   << meta.dump()
                   << "(ymin,ymax) = (" << ymin << "," << ymax << ")" << std::endl
                   << "Called a reverse_copy..." << std::endl
                   << "      source wf : plane = " << wire_id.Plane << " wire = " << wire_id.Wire << std::endl
                   << "      timing    : start index = " << range.begin_index() << " length = " << adcs.size() << std::endl
                   << "      (row,col) : (" << (ymax - end_index) << "," << col << ")" << std::endl
                   << "      nskip     : "  << nskip << std::endl
                   << "Re-throwing an error:" << std::endl;
         throw err;
       }
     }
       }
     }
     return img;
   }
Wire2Image2D() [2/2]
std::vector< larcv::Image2D > supera::Wire2Image2D (const std::vector< larcv::ImageMeta > & meta_v, const std::vector< supera::LArWire_t > & wires, const int time_offset)
Definition at line 147 of file LAr2Image.cxx.
References Nplanes(), and Wire2Image2D().
   {
     std::vector<larcv::Image2D> res_v;
     for (size_t p = 0; p < ::supera::Nplanes(); ++p) {
       auto const& meta = meta_v.at(p);
       res_v.emplace_back(std::move(Wire2Image2D(meta,wires,time_offset)));
       res_v.back().index(res_v.size()-1);
     }
     return res_v;
   }
WireAngleToVertical()
double supera::WireAngleToVertical (unsigned int plane)
Angle from z-axis.
Definition at line 93 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::configure().
   { return ::larutil::Geometry::GetME()->WireAngleToVertical(larlite::geo::View_t(plane)); }
WirePitch()
double supera::WirePitch (size_t plane)
Wire pitch.
Definition at line 90 of file MeatSlicer/FMWKInterface.cxx.
Referenced by supera::PulledPork3DSlicer::configure(), and larcv::SuperaSimVoxel3D::process().
   { return ::larutil::Geometry::GetME()->WirePitch(::larlite::geo::View_t(plane)); }