LArCV: larcv::supera Namespace Reference
larcv::supera Namespace Reference
Classes
class Cropper
class MCParticleTree
User defined class MCParticleTree ...
class MCPNode
class SuperaCore
User defined class SuperaCore ...
Typedefs
typedef ::larcv::PSet Config_t
typedef ::larcv::Range< unsigned int > WTRange_t
typedef std::vector< larcv::supera::WTRange_t > WTRangeArray_t
typedef std::vector< larcv::ROI > ParticleROIArray_t
typedef larcv::ROI PrimaryROI_t
typedef std::pair< larcv::supera::PrimaryROI_t, larcv::supera::ParticleROIArray_t > InteractionROI_t
Functions
::larlite::geo::WireID ChannelToWireID (unsigned int ch)
Channel number to wire ID.
double DriftVelocity ()
DriftVelocity in cm/us.
unsigned int NumberTimeSamples ()
Number of time ticks.
unsigned int Nchannels ()
Number of channels.
unsigned int Nplanes ()
Number of planes.
unsigned int Nwires (unsigned int plane)
Number of wires.
unsigned int NearestWire (const TVector3 &xyz, unsigned int plane)
Nearest wire.
int TPCG4Time2Tick (double ns)
G4 time to TPC tick.
double TPCTDC2Tick (double tdc)
TDC to TPC tick.
template<class T >
void Fill (Image2D &img, const std::vector< T > &wires, const int time_offset=0)
Typedef Documentation
Config_t
typedef::fhicl::ParameterSet larcv::supera::Config_t
Definition at line 9 of file Supera/APILArLite/FMWKInterface.h.
InteractionROI_t
typedef std::pair<larcv::supera::PrimaryROI_t,larcv::supera::ParticleROIArray_t> larcv::supera::InteractionROI_t
Definition at line 15 of file Supera/larfmwk_shared/SuperaTypes.h.
ParticleROIArray_t
typedef std::vector<larcv::ROI> larcv::supera::ParticleROIArray_t
Definition at line 11 of file Supera/larfmwk_shared/SuperaTypes.h.
PrimaryROI_t
typedef larcv::ROI larcv::supera::PrimaryROI_t
Definition at line 13 of file Supera/larfmwk_shared/SuperaTypes.h.
WTRange_t
typedef ::larcv::Range<unsigned int> larcv::supera::WTRange_t
Definition at line 22 of file Cropper.h.
WTRangeArray_t
typedef std::vector<larcv::supera::WTRange_t> larcv::supera::WTRangeArray_t
Definition at line 23 of file Cropper.h.
Function Documentation
ChannelToWireID()
geo::WireID larcv::supera::ChannelToWireID (unsigned int ch)
Channel number to wire ID.
Definition at line 13 of file Supera/APILArLite/FMWKInterface.cxx.
     { return ::larutil::Geometry::GetME()->ChannelToWireID(ch); }
DriftVelocity()
double larcv::supera::DriftVelocity ()
DriftVelocity in cm/us.
Definition at line 16 of file Supera/APILArLite/FMWKInterface.cxx.
Referenced by larcv::SuperaSimVoxel3D::process().
     { return ::larutil::LArProperties::GetME()->DriftVelocity(); }
Fill()
template<class T > void larcv::supera::Fill (Image2D & img, const std::vector< T > & wires, const int time_offset = 0)
Referenced by larcv::IOManager< T >::get_data().
Nchannels()
unsigned int larcv::supera::Nchannels ()
Number of channels.
Definition at line 27 of file Supera/APILArLite/FMWKInterface.cxx.
Referenced by Supera::filter().
     { return ::larutil::Geometry::GetME()->Nchannels(); }
NearestWire()
unsigned int larcv::supera::NearestWire (const TVector3 & xyz, unsigned int plane)
Nearest wire.
Definition at line 36 of file Supera/APILArLite/FMWKInterface.cxx.
References Nwires().
Referenced by larcv::SuperaKeyPointCluster::CreateCluster().
     {
       /*
       unsigned int res;
       try{
     res = ::larutil::Geometry::GetME()->NearestWire(xyz,plane);
       }catch( ::larutil::InvalidWireError& err){
     res = err.better_wire_number;
       }
       */
       double min_wire=0;
       double max_wire=Nwires(plane)-1;
       double wire = ::larutil::Geometry::GetME()->WireCoordinate(xyz,plane) + 0.5;
       if(wire<min_wire) wire = min_wire;
       if(wire>max_wire) wire = max_wire;
       return (unsigned int)wire;
     }
Nplanes()
unsigned int larcv::supera::Nplanes ()
Number of planes.
Definition at line 30 of file Supera/APILArLite/FMWKInterface.cxx.
Referenced by larcv::SuperaMCPCluster::process().
     { return ::larutil::Geometry::GetME()->Nplanes(); }
NumberTimeSamples()
unsigned int larcv::supera::NumberTimeSamples ()
Number of time ticks.
Definition at line 19 of file Supera/APILArLite/FMWKInterface.cxx.
     {
       // Till resolved, do not use this function
       throw ::larcv::larbys("NumberTimeSamples function not available!");
       //return ::larutil::DetectorProperties::GetME()->NumberTimeSamples();
       //return 9600;
     }
Nwires()
unsigned int larcv::supera::Nwires (unsigned int plane)
Number of wires.
Definition at line 33 of file Supera/APILArLite/FMWKInterface.cxx.
Referenced by larcv::SuperaChStatus::initialize(), NearestWire(), and larcv::SuperaChStatus::set_chstatus().
     { return ::larutil::Geometry::GetME()->Nwires(plane); }
TPCG4Time2Tick()
int larcv::supera::TPCG4Time2Tick (double ns)
G4 time to TPC tick.
Definition at line 55 of file Supera/APILArLite/FMWKInterface.cxx.
Referenced by larcv::SuperaKeyPointCluster::CreateCluster().
     { return ::larutil::TimeService::GetME()->TPCG4Time2Tick(ns); }
TPCTDC2Tick()
double larcv::supera::TPCTDC2Tick (double tdc)
TDC to TPC tick.
TPC TDC to Tick.
Definition at line 58 of file Supera/APILArLite/FMWKInterface.cxx.
     { return ::larutil::TimeService::GetME()->TPCTDC2Tick(tdc); }