add_subdirectory(Base)
add_subdirectory(DataFormat)
add_subdirectory(Processor)
if (LARCV_USE_PYTHON)
  add_subdirectory(PyUtil)
endif()
if (USE_OPENCV)
  add_subdirectory(CVUtil)
endif()
add_subdirectory(json)
add_subdirectory(CPPUtil)
#add_subdirectory(ROOTUtil)


#if (Torch_FOUND)
#  add_subdirectory(TorchUtil)
#endif()
