import ROOT
#ROOT.gSystem.Load("libLArCV")
#ROOT.gSystem.Load("libLArCVData")
from ROOT import larcv
o=larcv.IOManager(larcv.IOManager.kREAD)
o.reset()
o.set_verbosity(0)
o.add_in_file("aho.root")
o.initialize()
#o.get_data("boke")
o.read_entry(0)
print o.get_data(larcv.kProductImage2D,"aho").Image2DArray().size()
print o.get_data(larcv.kProductImage2D,"aho").event_key()
o.read_entry(1)
print o.get_data(larcv.kProductImage2D,"aho").Image2DArray().size()
print o.get_data(larcv.kProductImage2D,"aho").event_key()
o.read_entry(2)
print o.get_data(larcv.kProductImage2D,"aho").Image2DArray().size()
print o.get_data(larcv.kProductImage2D,"aho").event_key()
#o.save_entry()
#o.save_entry()
#o.save_entry()
#o.save_entry()
o.finalize()
